### PR TITLE
- IndexedDB: Ensure any prior version of the database gets deleted before test

### PR DESCRIPTION
**Pull request by brettz9**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5586)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222705744)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222705748)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 661bfdb3b4fd18812d3a0fa78741b65d869ceffd
Using browser at version BuildID 20170416100136; SourceStamp ce69b6e1773e9e0d0a190ce899f34b1658e66ca4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5586/IndexedDB/idbversionchangeevent.htm">/IndexedDB/idbversionchangeevent.htm</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `IDBVersionChangeEvent fired in upgradeneeded, versionchange and deleteDatabase` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222705749)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 661bfdb3b4fd18812d3a0fa78741b65d869ceffd
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5586/IndexedDB/idbversionchangeevent.htm">/IndexedDB/idbversionchangeevent.htm</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `IDBVersionChangeEvent fired in upgradeneeded, versionchange and deleteDatabase` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5586/)

**Comment by annevk** [comment]
This kind of stuff should happen as part of the cleanup phase of a test. Something like test_ref.add_cleanup(...) is the syntax, from memory.

**Comment by brettz9** [comment]
Sure, but for this PR:

1. In `idbversionchangeevent.htm`, it is not clean-up, it is just just ensuring that the test doesn't fail because of a previous failed clean-up.

2. In `idbworker.js`, it is within a worker context without having used `importScripts`. For this case, the parent script could handle the deletion, but if the worker is ever reused, it seems to me a better place for it to be there in the worker. But I can adjust if this is not how you want to handle it.

**Comment by annevk** [comment]
I understand your goal, I'm just stating that I'd prefer to fix the problem at the source. Otherwise we'll hit this again, new folks reading this code won't understand why stuff is getting deleted, etc.

**Comment by brettz9** [comment]
Ok, the second case is easy to change... For the first case, the tests would probably need to be refactored using the likes of "support-promises.js" as that wrapper has a means for pre-deleting databases (`createNamedDatabase`): https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/support-promises.js#L127-L128 ...

**Comment by inexorabletash** [comment]
See https://github.com/w3c/web-platform-tests/issues/4560 - I'm tackling adding missing `add_cleanup()` calls (and fixing broken ones)

**Comment by brettz9** [comment]
As far as the remaining item in this PR, ensuring delete before testing begins, while many tests do this, there are some that don't (like the idbversionchangeevent test in this PR), so if there were previous errors, the test may continue to fail. However, I'm not inclined atm to provide fixes myself (or even to revise the PR to use the full promises system), so I'll even avoid filing an issue unless that may be something already of interest to others.

**Pull request closed without merging**
