### PR TITLE
Remove metadata_cache from all tests

### PR DESCRIPTION
**Pull request by foolip**
It does not appear to be useful for anything.

The most recent addition of a new block was in 2014 by @dbaron:
commit 404687459e8a36df9a9bde5e5bfa0f26f5893a27

Before that, in 2013, some was added on request by @plinss:
commit 1c3285a09834abdb9f6b335d7fa49edf792cb668

These test had stale or broken metadata:
css/cssom-view/scrollWidthHeight.xht
css/cssom-view/scrollWidthHeightWhenNotScrollable.xht
css/cssom/style-sheet-interfaces-001.html
css/mediaqueries/test_media_queries.html

### CODE REVIEW

**Comment by foolip** [comment]
A lot of code can be deleted in testharnessreport.js too, can do that in this PR or separately, whatever is preferred.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22233)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/323900735)

**Comment by dbaron** [comment]
IIRC, I added it because the relevant harness gave a warning when it wasn't added.

**Review by dbaron — APPROVED** [review]

**Comment by dbaron** [comment]
(Not merging this immediately in case you wanted additional review or checking with somebody...)

**Comment by plinss** [comment]
The metadata cache and associated code in testharnessreport.js was to expose the test metadata to Shepherd (or any other tooling that may come along) without requiring a js runtime to extract it. Since we've de-commited to using Shepherd to manage the tests I'm fine with removing it at this point. We can always re-generate it if needed in the future (it was a cache after all, not authoritative data).

**Comment by foolip** [comment]
Thanks @dbaron and @plinss! I'll also clean up in testharnessreport.js.

**Pull request merged**
