### PR TITLE
Upstream negative-playback-rate.html, positive-playback-rate.html from Blink

### PR DESCRIPTION
**Pull request by suzyh**
Import
https://chromium.googlesource.com/chromium/src/+/fe9ded7a6424a3808af6c51d5b839c4f0e7cb280/third_party/WebKit/LayoutTests/web-animations-api/animation-state-changes-negative-playback-rate.html
https://chromium.googlesource.com/chromium/src/+/3eda0025374cfc23d3e9af70f945f1a7b3ac6fee/third_party/WebKit/LayoutTests/web-animations-api/playState-changes.html

### CODE REVIEW

**Comment by birtles** [comment]
I don't understand what this is testing. What algorithm / spec text is being covered?

For example, in this test:

```diff
+test(function(t) {
+  var animation = createIdleAnimation(t);
+  assert_equals(animation.startTime, null);
+  assert_equals(animation.currentTime, null);
+  assert_equals(animation.playState, 'idle');
+}, "Play state is idle after cancelling a reversed animation");
```

First of all, there doesn't seem to be any cancelling or reversing going on. Second of all, are we testing the cancel procedure or the play state procedure?

For the play state procedure, all we need to do is create an animation with a null current time (e.g. `new Animation()`) and fetch the `playState` on it. If we want to test cancelling, then we should test that after calling `cancel()` the `currentTime` is `null`. There's no need to test the `playState` in that case.

**Comment by birtles** [comment]
Also, as a meta point, as per the [README.md](https://github.com/w3c/web-platform-tests/blob/master/web-animations/README.md), as far as possible we should avoid adding helper methods that obscure what the test is doing, e.g. instead of adding

```diff
+function createIdleAnimation(t) {
+  var animation = createDiv(t).animate(null, 100 * MS_PER_SEC);
+  animation.reverse();
+  animation.cancel();
+  return animation;
+}
```

we should just write:

```js
test(function(t) {
  var animation = new Animation();
  assert_equals(animation.playState, 'idle');
}, "Play state is idle when currentTime is null");
```

**Comment by alancutter** [comment]
This test runs the cross product of animation states and method calls and records the resulting animation state. It makes sense from an implementation stand point to cover this as a way of tracking changes in behaviour, perhaps it makes less sense from a spec testing perspective.

Does it sound reasonable to simply split these tests up according to the animation method being called? That way they are scoped to a section of the spec.

Also you mentioned "no need to test the `playState`" after calling `cancel()`, I'm not sure I understand the motivation to not have test coverage for the effect of `cancel()` in that instance.

**Comment by birtles** [comment]
> This test runs the cross product of animation states and method calls and records the resulting animation state. It makes sense from an implementation stand point to cover this as a way of tracking changes in behaviour, perhaps it makes less sense from a spec testing perspective.

Yeah, the idea is that we should be testing spec conformance here. If there are tests specific to your implementation, then they probably don't belong here.

> Does it sound reasonable to simply split these tests up according to the animation method being called? That way they are scoped to a section of the spec.

They should probably be split up according to the procedure they are testing. The methods / attributes are mostly just hooks to procedures defined earlier in the spec so the bulk of the tests should probably be covering those procedures (i.e. under `timing-model` / `animation-model`) rather than in `interfaces`. Some things like keyframe handling, however, are specific to the API and belong under `interfaces`.

(And a bunch of the existing tests are probably in the wrong place but we're gradually moving them as we touch them.)

> Also you mentioned "no need to test the playState" after calling cancel(), I'm not sure I understand the motivation to not have test coverage for the effect of cancel() in that instance.

The effect of `cancel()` is to call the "cancel an animation" procedure which updates the start time and hold time (observable most directly through `currentTime` being null). It's really tempting to also test `playState`, and `effect.timing.getComputedTiming().progress`, and `effect.timing.getComputedTiming().currentIteration`, and ``effect.timing.getComputedTiming().localTime`, and `getComputedStyle`, and so on--after all more testing is better, right? But in the long run, making the tests as simple and focussed as possible makes them easier to maintain, read, and write. It also makes it easy to check if the spec is being tested correctly and completely, and makes it easier to keep the tests consistent. If you have a moment, I think you'll find [Justin Searls' talk on testing](http://blog.testdouble.com/posts/2015-11-16-how-to-stop-hating-your-tests.html) really interesting since he talks a bit about this. Checking `playState` is probably ok in some cases, but I think most of the time it's unnecessary.

**Comment by suzyh** [comment]
Thanks for the review, Brian. I think addressing your comments is going to be a substantial rewrite of this patch, so I'm going to withdraw the pull request for now and get back to you with additional pull requests later.

**Pull request closed without merging**
