### PR TITLE
Add mandatory capabilities parameter for webdriver new session command

### LINKED ISSUE #17210: Possible missing capabilities parameter
A w3c compliant WebDriver server [expects](https://w3c.github.io/webdriver/#dfn-capabilities-processing) a `capabilities` field in the parameters for a `New Session` command. [Here](https://github.com/web-platform-tests/wpt/blob/3840f46213d9a991acc9288e3863530f7502c05e/tools/webdriver/webdriver/client.py#L405), if `requested_capabilities` is `None` the new session request will be sent without any `capabilities` field and no session will be created by the server.

### PR DESCRIPTION
**Pull request by georgeroman**
Fixes #17210

### CODE REVIEW

**Comment by jdm** [comment]
```
./webdriver/webdriver/client.py:417:31: W291 trailing whitespace
```

**Comment by georgeroman** [comment]
Is there any issue on Azure? I was wondering whether my changes were problematic, but it seems that the infrastructure tests fail even if I basically make no changes: https://github.com/web-platform-tests/wpt/pull/17212/files#diff-8f0dc082cb16d568172a0e6f39f0045cR416

**Comment by jdm** [comment]
Yeah, looks like those tests aren't behaving correctly on CI. Go ahead and revert to the actual changes and let the reviewers take care of it.

**Comment by jugglinmike** [comment]
> Is there any issue on Azure? I was wondering whether my changes were problematic, but it seems that the infrastructure tests fail even if I basically make no changes: https://github.com/web-platform-tests/wpt/pull/17212/files#diff-8f0dc082cb16d568172a0e6f39f0045cR416

For the change in question:

```diff
-  body = {}
+  body = { }
```

The resulting error is expected:

    ./webdriver/webdriver/client.py:416:17: E201 whitespace after '{'

We'll need to trial a different change if we want to verify the stability of the CI task.

**Comment by georgeroman** [comment]
@jugglinmike I reverted to the initial changes, the failures are still there.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /infrastructure/testdriver/actions/actionsWithKeyPressed.html:
  │ FAIL [expected PASS] TestDriver actions: actions with key pressed
  │   → assert_array_equals: lengths differ, expected 3 got 1
  │ 
  │     at Test.<anonymous> (http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:64:34)
  │     at Test.step (http://web-platform.test:8000/resources/testharness.js:1594:25)
  └     at http://web-platform.test:8000/resources/testharness.js:1634:32
```
Seems like a surprising failure for this change at first glance.

**Comment by jgraham** [comment]
Yeah, I would verify that test on master…

Also can we check the wdspec tests still pass. I think they ought to but it would be good to be sure. YOu can run them with `wpt run firefox wdspec`, but there will be some failures; we care that we aren't regressing anything relative to master.

**Comment by georgeroman** [comment]
I just ran the wdspec tests and got the same results on both master and this branch.

**Comment by gsnedders** [comment]
(Needs a rebase to pass CI, due to #17286. Sorry!)

**Comment by georgeroman** [comment]
This can be merged now that the checks pass. cc @gsnedders @jugglinmike @jgraham.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
