### PR TITLE
Add tests for document/window location getters

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds two tests for checking whether documentation and window location getters are null when outside the browser context.

### CODE REVIEW

**Comment by Ms2ger** [comment]
@ashughes1: looking good; I left some comments on critic. Please push new commits to this branch to address those.

**Comment by ashughes1** [comment]
I've made the whitespace/indentation changes but have some follow-up questions.

> https://critic.hoppipolla.co.uk/showcomment?chain=11748

I was following the format of ./html/browsers/history/the-location-interface/location_assign.html. Should I not have the underscore in there for readability?

> https://critic.hoppipolla.co.uk/showcomment?chain=11749
> https://critic.hoppipolla.co.uk/showcomment?chain=11750

I'm not sure what you mean by these comments. Can you please elaborate?

**Comment by Ms2ger** [comment]
Underscores don't belong in titles, IMO, but clearly someone disagrees.

The other comments are for other APIs that create documents; it'd be nice to test that the location getter returns null for those too.

**Comment by ashughes1** [comment]
@Ms2ger 

> Underscores don't belong in titles, IMO, but clearly someone disagrees.

I can remove the underscore if you feel strongly about it. However, I checked and most of the html files in this repository use an underscore. There are certainly some occurrences of camel case and hyphenation but underscore seems to be the dominant syntax. 

> The other comments are for other APIs that create documents

Is there a list of those APIs?

**Comment by Ms2ger** [comment]
I added comments to the two APIs that I think you should add tests for

**Comment by ashughes1** [comment]
@Ms2ger new commits added (see above).

**Pull request closed without merging**
