### PR TITLE
[CSS21] move tests from vendor-imports into the main suite

### PR DESCRIPTION
**Pull request by foolip**
These tests all pass in Firefox but fail lots elsewhere:
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/css21?run_id=5651238622330880&run_id=5763130439237632&run_id=5723050475520000&run_id=5095375432056832&run_id=5668611630825472&run_id=5735193556025344

Print reftests aren't run at all except for on Chrome and Firefox, so
that explains a lot of the failures.

In addition to the move, the "moz-css21-" prefix from pagination tests
is removed.

Part of https://github.com/web-platform-tests/wpt/issues/8615.

### CODE REVIEW

**Comment by foolip** [comment]
The wpt.fyi checks look good, but the print reftests weren't actually run. I've sent https://github.com/web-platform-tests/wpt/pull/27582 to fix that. I'd like to rebase this on top of that fix after it lands to ensure I didn't break anything, but this can still be reviewed pending that.

**Comment by foolip** [comment]
OK, with https://github.com/web-platform-tests/wpt/pull/27582 landed I'm now pretty confident I didn't break the tests:
https://wpt.fyi/results/css/CSS2?diff&filter=ADC&run_id=5722967579295744&run_id=5642007261216768
https://wpt.fyi/results/css/CSS2?diff&filter=ADC&run_id=5670234373488640&run_id=5658100822441984
https://wpt.fyi/results/css/CSS2?diff&filter=ADC&run_id=5184742024544256&run_id=5728836601774080

**Comment by foolip** [comment]
@MatsPalmgren these tests are largely authored by you, would you care to review this?

**Review by MatsPalmgren — APPROVED** [review]
LGTM

**Pull request merged**
