### PR TITLE
Fix most lint errors in resource/ and enable most lints

### PR DESCRIPTION
**Pull request by foolip**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8027)

### CODE REVIEW

**Comment by gsnedders** [comment]
Do we actually want to truly fork WebIDL2? The whitespace changes will make it harder to merge upstream changes.

**Comment by foolip** [comment]
I assumed that was a done deal given d77201112dcfde54e9a51fec2d5245ef989b4a0c, but I didn't look at the contents of the commit, turns out it's just adding .headers.

If we aren't forking, then how are we keeping it in sync?

**Comment by foolip** [comment]
I sent https://github.com/w3c/webidl2.js/pull/99. Depending on how fast that goes and how we update webidl2.js, I'll either wait for that to trickle down or back out the changes from this PR.

**Comment by tobie** [comment]
> Do we actually want to truly fork WebIDL2? The whitespace changes will make it harder to merge upstream changes.

Yeah that seems like a terrible idea that would prevent us from keeping idlharness in sync with the WebIDL spec.

**Comment by foolip** [comment]
Looks like the last upgrade was 960a3d21bab0293630da8919847f87f4af3a3198. @jgraham, what's the procedure?

**Comment by gsnedders** [comment]
@foolip running `git subtree` with whatever option makes it squash it.

**Comment by gsnedders** [comment]
I'm pretty sure it should just be `git subtree pull --prefix=resources/webidl2 https://github.com/w3c/webidl2.js.git v8.1.0` except that doesn't work and I can't figure out why.

**Comment by gsnedders** [comment]
See https://stackoverflow.com/questions/47102565/git-subtree-not-finding-latest-squash for that. :(

**Comment by gsnedders** [comment]
@foolip wait till https://github.com/w3c/web-platform-tests/pull/8063 lands, rebase on top of that.

**Comment by gsnedders** [comment]
@foolip now #8063 has landed, want to try rebasing this?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-29 16:51:48
Finished: 2017-11-29 16:57:51





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21227)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/309070084)

**Comment by gsnedders** [comment]
@foolip the README.md in resources/chromium says:

> The files mojo_bindings.js and *.mojom.js are manually copied from the Chromium build process's generated files and should not be edited manually.

Should we be changing the generation, then, rather than here?

**Comment by foolip** [comment]
@gsnedders I've rebased and backed out the Chromium changes, should be good to go.

**Comment by foolip** [comment]
@gsnedders, I've fixed the new problems that had popped up, speedy merging of this once green would be good to not accumulate more.

**Comment by gsnedders** [comment]
@foolip you've reverted some of my changes again, hence it failing CI again? (Specifically, `resources/webidl2/test/*` needs to be whitelisted as a git submodule, along with the other git submodules we whitelist)

**Comment by foolip** [comment]
I guess I forced push after a rebase.

**Comment by foolip** [comment]
But it did actually pass lint for me, which is weird.

**Comment by gsnedders** [comment]
@foolip do you have all submodules initialised? also: `--force-with-lease` exists, which might be useful.

**Comment by foolip** [comment]
No, I probably never did initialize them. I'm aware of --force-with-lease, but only have it as the default on some machines.

**Comment by foolip** [comment]
@gsnedders fixed yet again, let's see if that works.

**Comment by foolip** [comment]
Yes it did.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
