### PR TITLE
Add tests for where list-style-position: inside is odd today

### PR DESCRIPTION
**Pull request by gsnedders**
@tabatkins can you have a look at these, make sure they don't really need a `.tentative.` in them, given the List spec is such a draft? Pretty sure this is all stuff you told me should *definitely* work.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22224)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/323088082)

**Comment by gsnedders** [comment]
@tabatkins Especially interested in disc, square, and circle here.

**Comment by gsnedders** [comment]
w3c-test:mirror

**Comment by gsnedders** [comment]
@tabatkins c. six month ping for review

**Review by tabatkins — APPROVED** [review]

**Pull request merged**
