### PR TITLE
Revert #15512 due to TC infrastructure/ failure

### PR DESCRIPTION
**Pull request by gsnedders**
Reverts #15512. This should make TC infrastructure/ pass again.

cc @foolip @Hexcles

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by foolip** [comment]
@gsnedders what was the failure? Can you pepper more failing expectations until it works? It did pass CI when the PR was merged.

**Comment by jgraham** [comment]
```
TEST-UNEXPECTED-FAIL | /infrastructure/testdriver/actions/actionsWithKeyPressed.html | TestDriver actions: actions with key pressed - assert_array_equals: lengths differ, expected 3 got 1
@http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:64:34
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:25
Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1627:32
promise callback*@http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:64:6
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:25
async_test@http://web-platform.test:8000/resources/testharness.js:576:22
@http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:39:1
TEST-UNEXPECTED-OK | /infrastructure/testdriver/actions/actionsWithKeyPressed.html | expected ERROR
```

Also having an infrastructure test that all browsers are expected to fail seems pretty odd.

**Comment by gsnedders** [comment]
@foolip It seems to have never run the infrastructure tests prior to merging (they don't appear under Travis or TaskCluster!). Per our revert policy, I'd rather just revert the PR causing breakage on master that landed without ever running infrastructure and let the original authors figure out what to do.

**Comment by foolip** [comment]
@gsnedders merged and I'll send a new PR to see what it does right away.

> Also having an infrastructure test that all browsers are expected to fail seems pretty odd.

This is because ChromeDriver isn't released as often as Chrome itself. At least I think so. In other words, things will break again when ChromeDriver is updated.

**Comment by Hexcles** [comment]
I think infrastructure tests did run in #15512 , but because of Taskcluster Checks migration, @jgraham temporarily stopped requiring Taskcluster checks so the PR slipped through...

**Pull request merged**
