### PR TITLE
Move macOS runs on Azure Pipelines to macOS 12 (Monterey)

### PR DESCRIPTION
**Pull request by gsnedders**

### CODE REVIEW

**Review by jgraham — APPROVED** [review]
I don't know loads about the Azure setup, but this seems simple enough.

**Comment by gsnedders** [comment]
Ergh, infrastructure hasn't run for this.

**Comment by gsnedders** [comment]
FWIW:

Stable: https://wpt.fyi/results/?q=seq%28status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%29%20or%20seq%28status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3Aok%7Cstatus%3Apass%29%20&run_id=5749963815387136&run_id=5768540253585408&run_id=5125661864755200&run_id=5671892248690688&run_id=5740472407425024

STP: https://wpt.fyi/results/?q=seq%28status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3Aok%7Cstatus%3Apass%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%29%20or%20seq%28status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3A%21ok%26status%3A%21pass%26status%3A%21unknown%20status%3Aok%7Cstatus%3Apass%29%20&run_id=5661907926122496&run_id=5733426178031616&run_id=6249745335975936&run_id=5711186166284288&run_id=5678408250949632

**Comment by gsnedders** [comment]
Am gonna split this up, given it seems the infrastructure tests are passing even if the latter commit is making Windows tools tests fail.

**Review by stonigrl — APPROVED** [review]

**Review by stonigrl — APPROVED** [review]

**Pull request merged**
