### PR TITLE
[docs] flesh out the `python -m ensurepip` documentation

### PR DESCRIPTION
**Pull request by foolip**
Drive-by: make the Python download link secure

### CODE REVIEW

**Comment by foolip** [comment]
@Hexcles can you try this and report what it does on macOS? I don't think it'll work without `sudo` per https://github.com/web-platform-tests/wpt/issues/19753 but I'd like to know how it fails.

**Comment by foolip** [comment]
@Hexcles if you could try the `--user` option in https://docs.python.org/2.7/library/ensurepip.html#command-line-interface and see where it adds the binary that'd be helpful.

Whichever method you use, reporting your resulting `pip --version` would be helpful. If it's not a recent version, then was it already installed on the system but just not on `PATH`? Can you figure out where it was?

**Comment by Hexcles** [comment]
This doesn't work: https://github.com/web-platform-tests/wpt/pull/19927#issuecomment-546733677

On my brand new macOS 10.14.6, I have Python 2.7.10 and no pip in my PATH.

`python -m ensurepip --user` installs to `~/Library/Python/2.7/{bin,lib}`. And I got pip 6.1.1. Note that this path is not in PATH by default.

**Comment by foolip** [comment]
Thanks @Hexcles! I have pip 19.3 because I did `sudo pip install --upgrade pip` at one point, but probably that's unnecessary.

**Comment by foolip** [comment]
@Hexcles I'll be working on the macOS stuff specifically in https://github.com/web-platform-tests/wpt/pull/19940, which is very drafty now. But this change works on its own and is ready for review.

**Comment by Hexcles** [comment]
This seems problematic not only on macOS, but also on Linux. Without root permission, I think this command either fails or installs to `.local/` which is not in PATH and the `pip` command below would fail.

**Comment by foolip** [comment]
Yeah, this is more of a clue for what to do than the verbatim steps you need to do.

Maybe we should just fork the steps for installing python, pip and virtualenv per platform and not bother trying to describe shared steps?

**Comment by Hexcles** [comment]
That was the reason why the original instruction simply said "install pip" without any details -- there's no one-size-fit-all solution for all platforms.

Personally I used Homebrew and installed all Python stuff to my user dir.

**Comment by foolip** [comment]
So you're not using the system Python even? Why not?

**Comment by Hexcles** [comment]
> So you're not using the system Python even? Why not?

I did not use system Python on my previous MBP. I had some other Homebrew stuff that were linked to Python 2 (e.g. vim) which did not work well with the system Python. I'm not sure whether that's a best/common practice. I haven't set up Homebrew at all on my new MBP.

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt/pull/19940.

**Pull request closed without merging**
