### PR TITLE
Created 6 improved tests

### PR DESCRIPTION
**Pull request by TalbotG**
active-selection-021.html
active-selection-021-ref.html
active-selection-024.html
active-selection-024-ref.html
active-selection-031.html
active-selection-031-ref.html
active-selection-041.html
active-selection-041-ref.html
active-selection-043.html
active-selection-045.html
support/60x60-red.png
support/60x60-green.png
support/100x100-red.png
reference/ref-filled-green-100px-square.xht
reference/ref-nothing-below.xht

This PR is a followup to 
https://github.com/web-platform-tests/wpt/pull/20028

This PR contains all the corrections and improvements proposed in https://github.com/web-platform-tests/wpt/pull/20028

### CODE REVIEW

**Comment by TalbotG** [comment]
@fantasai , please review .

**Comment by TalbotG** [comment]
@fantasai ,

active-selection-024: improved test, first-letter

active-selection-025: new test, first-letter, no `color` declaration only `background-color`

active-selection-026: new test, first-line

active-selection-027: new test, first-line, no `color` declaration only `background-color`

These 4 tests take into account the resolution in
https://github.com/w3c/csswg-drafts/issues/4625

**Comment by fantasai** [comment]
@TalbotG Remove the replaced element tests from this PR, because the rest of these are are acceptable tests, but 41 and 43 are not. 

The transparency of the color wash is not dictated by the spec and each UA has their own color, so your approach is not valid. See https://github.com/web-platform-tests/wpt/pull/20028#pullrequestreview-335630411 for an approach that will actually work to test this case. File a new, separate PR for the replaced element tests.

**Review by fantasai — CHANGES_REQUESTED** [review]
See comment above.

**Comment by TalbotG** [comment]
I must close this PR and delete this branch now that 
https://github.com/web-platform-tests/wpt/pull/24713
https://github.com/web-platform-tests/wpt/pull/24714
have merged.

I will create a distinct and separate PR for 
active-selection-041.html
active-selection-041-ref.html
active-selection-043.html

I have bookmarked your
web-platform-tests wpt pull 20931#issuecomment-650434204

**Pull request closed without merging**
