### PR TITLE
Remove tests for URL.createFor.

### PR DESCRIPTION
**Pull request by mkruisselbrink**
https://github.com/w3c/FileAPI/pull/62 will remove the URL.createFor method,
this removes the corresponding tests.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please add a check to `FileAPI/historical.html` as well.

**Comment by inexorabletash** [comment]
Sorry the label churn - I thought this was ready to go but looking at the timing @Ms2ger may have added the label after @annevk approved the change and/or the change landed. I'll let @Ms2ger merge.

**Comment by mkruisselbrink** [comment]
> Please add a check to FileAPI/historical.html as well.

Done

**Review by Ms2ger — APPROVED** [review]
Thanks!

**Pull request merged**
