### PR TITLE
Add a test covering order of navigation/fragment/network events

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Review by jrandolf — APPROVED** [review]

**Comment by whimboo** [comment]
Question: Given that this test spans a couple of different commands and events shall we maybe move it up some integration test folder?

**Comment by OrKoN** [comment]
@whimboo I have no preference. Moved the test to the bidi/integration folder as it looks like we had no such tests before?

**Comment by OrKoN** [comment]
@whimboo @juliandescottes does the expectation of the test make sense to you based on the spec?

**Comment by whimboo** [comment]
It's starting with a quite complex scenario (navigation, beforeunload, and history API), and requires (for me) digging into the HTML spec. An easier example would be just a normal navigation with a hash change.

**Comment by OrKoN** [comment]
@whimboo normal navigations produce expected order of events (and are mostly covered by existing single-event tests).

**Comment by OrKoN** [comment]
Let's revisit but for now it looks like this is the correct order according to the HTML spec. cc @jgraham

**Pull request merged**
