### PR TITLE
Add cache for lint results

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6639)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258219806)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258219807)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258219813)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258219814)

# Sauce (MicrosoftEdge) #

**Comment by jgraham** [comment]
Rerunning the lint job with this enabled dropped the job time from 4m 42s to 1m 6s.

Argaubly some tests to ensure that we still catch errors would be nice.

**Comment by jgraham** [comment]
Went for #6663 instead.

**Pull request closed without merging**
