### PR TITLE
[fetch] Correct tentative tests

### PR DESCRIPTION
**Pull request by jugglinmike**
This is in service of https://github.com/web-platform-tests/rfcs/pull/28

### CODE REVIEW

**Comment by jugglinmike** [comment]
According to the stability check running in Taskcluster, one of the tests is flaky in Chrome "dev":

> ### /fetch/corb/script-resource-with-nonsniffable-types.tentative.sub.html ###
> |                    Subtest                     |          Results           |                 Messages                |
> |------------------------------------------------|----------------------------|-----------------------------------------|
> |                                                | OK                         |                                         |
> | `CORB blocks 'application/gzip'`               | PASS                       |                                         |
> | `CORB blocks 'application/x-gzip'`             | PASS                       |                                         |
> | `CORB blocks 'application/x-protobuf'`         | PASS                       |                                         |
> | `CORB blocks 'application/zip'`                | PASS                       |                                         |
> | `CORB blocks 'multipart/byteranges'`           | **FAIL: 1/10, PASS: 9/10** | `assert_false: expected false got true` |
> | `CORB blocks 'text/event-stream'`              | **FAIL: 1/10, PASS: 9/10** | `assert_false: expected false got true` |
> | `CORB does not block 'application/javascript'` | PASS                       |                                         |
> | `CORB does not block 'text/html'`              | PASS                       |                                         |
> | `CORB does not block 'application/blah'`       | PASS                       |                                         |

We won't be able to merge this until we resolve the flakiness.

@anforowicz What do you think about disabling those subtests? Do you think the others are actually more stable? Or did we just get lucky?

**Comment by anforowicz** [comment]
@jugglinmike, thanks for reporting the flakiness.  The test seems to be depending on global state (`window.script_has_run`) even though it also is running tests in parallel (via `async_test`).  Ooops :-(.  

I'll try to fix this tomorrow.  Right now I think that the easiest thing to do might be to replace `async_test` with `promise_test` to sequentialize/serialize the tests.

**Comment by anforowicz** [comment]
I'll track fixing the CORB tests in https://crbug.com/1011410

**Review by yutakahirano — APPROVED** [review]

**Comment by jugglinmike** [comment]
True to their word, @anforowicz has fixed the flakiness that was blocking this patch. Thanks, Lukasz! I've rebased on top of those changes and force-pushed the result. [The original version of this branch is available here.](https://github.com/web-platform-tests/wpt/compare/master...bocoup:not-single-test-fetch-orig)

**Pull request merged**
