### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by marcoscaceres**
Remove @halindrome.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome I'm removing as reviewer, as it seems you are too busy to keep up with reviews.

**Comment by marcoscaceres** [comment]
If you want to be added back, please indicate so - but we need you to be attentive as a lot of stuff is going to be coming in, and it needs you to do a super close reading of the spec with every test that comes in.

**Review by sideshowbarker — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238250287)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238250288)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238250294)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238250295)

# Sauce (MicrosoftEdge) #

**Pull request merged**
