### PR TITLE
HTML: test origin and Window object reuse

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/4126.

### CODE REVIEW

**Review by domenic — COMMENTED** [review]
The actual tests seem OK, but it's really hard to understand why they're correct. Here was my attempt at writing test descriptions, which could be used to clarify:

- Once a frame is navigated, a new Window is created, which does not carry over the domain component of the initial about:blank's origin, so the same-origin domain check for access control fails.

- Setting the domain component of a child does not prevent access to the child, if the child is still on the initial about:blank, because this also sets the domain component of the parent due to the way origins are aliased.

- Setting the domain component of a parent does not prevent access to the child, if the child is still on the initial about:blank, because this also sets the domain component of the child due to the way origins are aliased.

Is there any way to actually assert the domain aliasing directly, e.g. by checking the value of `document.domain`? I am guessing no, because that will just "fall back" to returning the effective domain anyway. But it sure would be nice for test clarity if there were.

I'll also note that this doesn't seem to test https://github.com/whatwg/html/pull/5107 at all. To test that, I'd expect to test for Window object reuse (e.g. by checking if a global variable is still set) in cases that are same-origin-domain but not same-origin. Such a test would involve navigation (like the first test here but unlike the second two.) This just tests https://github.com/whatwg/html/issues/4126.

**Comment by annevk** [comment]
There's no Window reuse if the same-origin domain check yields a different result, right? It's not clear how you could check a variable as that'd throw.

**Comment by annevk** [comment]
Also, I don't know how you could assert that an alias happened. @bzbarsky thoughts?

**Comment by domenic** [comment]
> There's no Window reuse if the same-origin domain check yields a different result, right? It's not clear how you could check a variable as that'd throw.

Right. The case that's missing is two pages that are same-origin domain, but not same-origin. Then you'd assert Window object reuse by checking that a global variable survived.

Note: this is about https://github.com/whatwg/html/pull/5107

> Also, I don't know how you could assert that an alias happened.

Is this in response to my "Is there any way to actually assert the domain aliasing directly, e.g. by checking the value of document.domain? I am guessing no..."?

---

BTW, I guess I wasn't very clear: I think the way to go here is to change all the test descriptions to be more informative, as I attempted in https://github.com/web-platform-tests/wpt/pull/20400#pullrequestreview-322461526, and then do a new pull request with tests for https://github.com/whatwg/html/pull/5107. This pull request can then be only about https://github.com/whatwg/html/issues/4126.

**Comment by annevk** [comment]
I don't think test titles should be that long.

**Comment by domenic** [comment]
OK, well, they are really unclear as of now, so maybe you could add comments of that sort?

**Comment by annevk** [comment]
Alright, done that.

**Comment by annevk** [comment]
> The case that's missing is two pages that are same-origin domain, but not same-origin. Then you'd assert Window object reuse by checking that a global variable survived.

How would this be possible? At the point of the same origin-domain check one of the origins comes from the network, it cannot have been mutated at that point.

**Comment by domenic** [comment]
> How would this be possible? At the point of the same origin-domain check one of the origins comes from the network, it cannot have been mutated at that point.

It's not coming from the network unless we reach step 6 of https://html.spec.whatwg.org/#determining-the-origin ; steps 3, 4, and 5 return origins which could have the domain component set.

Also, just at a meta-level, if it's impossible for the step to be reached such that the two origins are same-origin domain but not same-origin, then isn't it the case that the change in https://github.com/whatwg/html/pull/5107 is a no-op, since SOD and SO are then equivalent?

**Comment by annevk** [comment]
They're not equivalent, because one of the origins doesn't come from the network.

I guess perhaps initial about:blank navigating to about:blank or initial about:blank navigating to a `javascript:` URL might be plausible cases, if not for the fact that both have lots of open issues.

**Comment by domenic** [comment]
> They're not equivalent, because one of the origins doesn't come from the network.

I don't understand this. Can you spell it out in more detail?

Here was my reasoning in more detail. Consider the possibilities for the two origins:

- SO and SOD: doesn't matter which of the two we use
- SO and not SOD: this is impossible by definition (right?)
- not SO and SOD: you say this is impossible
- not SO and not SOD: doesn't matter which of the two we use

So for all possible cases it doesn't matter which of the two we use.

I don't see why network or not would matter in this case.

**Comment by annevk** [comment]
I don't understand your notation. If both are origins created from `https://example.com` then they are same origin and same origin-domain. However, if for one of them you'd set `document.domain` (the one for which this is possible) they are no longer same origin-domain (but they are same origin still).

**Review by domenic — APPROVED** [review]

**Comment by domenic** [comment]
Let's use a new issue to discuss testing https://github.com/whatwg/html/pull/5107. (Or we can use that pull request itself.) I think I'd appreciate if you laid out clearly in what scenario you expect the change in that PR to cause different results.

**Comment by annevk** [comment]
I would expect different results in ` html/browsers/windows/document-domain-nested-navigate.window.js`. In particular, I would expect an older Firefox to not throw there because it performs a same origin check and not a same origin-domain check. I still don't think additional tests are needed.

**Pull request merged**
