### PR TITLE
Add interfaces/css-nav.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/0cb115a/ed/idl/css-nav.idl
Build: https://travis-ci.org/w3c/webref/builds/182613166

### CODE REVIEW

**Comment by foolip** [comment]
This needs a test exercising it to be worth merging.

@jihyerish @frivoal, I see you're the main contributors in https://github.com/w3c/csswg-drafts/commits/master/css-nav-1, can you say something about the implementation status of this? Is it worth adding any test coverage like this yet?

**Comment by jihyerish** [comment]
@foolip Sorry for the late reply. For implementing the IDL, it won't be done by this year.
I think testing on this is a bit early stage for now.
Implementation of spatial navigation is already in progress in blink, but only for the default behavior.
IDL is about the extension APIs on top of the default behavior, so it will be implemented after the implementation of default behavior stabilize.

**Comment by foolip** [comment]
@jihyerish thanks for confirming! If you let us know when the IDL interfaces are about to implemented in some engine we can merge https://github.com/web-platform-tests/wpt/issues/19400 then.

**Comment by jihyerish** [comment]
Okay, I'll make a comment about the update in here or  https://github.com/web-platform-tests/wpt/pull/19400.

**Comment by foolip** [comment]
I've closed https://github.com/web-platform-tests/wpt/pull/19400, but we can get the test there if we later want to land this PR.

**Pull request closed without merging**
