### PR TITLE
Added EventHandler definition

### LINKED ISSUE #5116: page visibility idlharness test is broken
If you implement onvisibilitychange, it will happily tell you "Unrecognized type EventHandler" and fail the test.

Looks like @plehegar forgot to add a definition of EventHandler in https://github.com/w3c/web-platform-tests/commit/47ebaea27fb722d87198e065e18f4216ff6de72e

### PR DESCRIPTION
**Pull request by plehegar**
This should resolved #5116

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5204)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214001353)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 5a9d0ba43e65a1d33453053e7f61314ab74bb929
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5204/page-visibility/idlharness.html">/page-visibility/idlharness.html</a></summary>


|                                                  Subtest                                                  | Results |                                                                               Messages                                                                              |
|-----------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                           | OK      |                                                                                                                                                                     |
| `Document interface: attribute hidden`                                                                    | PASS    |                                                                                                                                                                     |
| `Document interface: attribute visibilityState`                                                           | PASS    |                                                                                                                                                                     |
| `Document interface: attribute onvisibilitychange`                                                        | FAIL    | `assert_true: The prototype object must have a property "onvisibilitychange" expected true got false`                                                               |
| `Document must be primary interface of window.document`                                                   | FAIL    | `assert_equals: window.document's prototype is not Document.prototype expected object "[object DocumentPrototype]" but got object "[object HTMLDocumentPrototype]"` |
| `Stringification of window.document`                                                                      | FAIL    | `assert_equals: class string of window.document expected "[object Document]" but got "[object HTMLDocument]"`                                                       |
| `Document interface: window.document must inherit property "hidden" with the proper type (0)`             | PASS    |                                                                                                                                                                     |
| `Document interface: window.document must inherit property "visibilityState" with the proper type (1)`    | PASS    |                                                                                                                                                                     |
| `Document interface: window.document must inherit property "onvisibilitychange" with the proper type (2)` | FAIL    | `assert_inherits: property "onvisibilitychange" not found in prototype chain`                                                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214001354)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 5a9d0ba43e65a1d33453053e7f61314ab74bb929
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5204/page-visibility/idlharness.html">/page-visibility/idlharness.html</a></summary>


|                                                  Subtest                                                  | Results |                                                                      Messages                                                                     |
|-----------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                           | OK      |                                                                                                                                                   |
| `Document interface: attribute hidden`                                                                    | PASS    |                                                                                                                                                   |
| `Document interface: attribute visibilityState`                                                           | PASS    |                                                                                                                                                   |
| `Document interface: attribute onvisibilitychange`                                                        | FAIL    | `assert_true: The prototype object must have a property "onvisibilitychange" expected true got false`                                             |
| `Document must be primary interface of window.document`                                                   | FAIL    | `assert_equals: window.document's prototype is not Document.prototype expected object "[object Document]" but got object "[object HTMLDocument]"` |
| `Stringification of window.document`                                                                      | FAIL    | `assert_equals: class string of window.document expected "[object Document]" but got "[object HTMLDocument]"`                                     |
| `Document interface: window.document must inherit property "hidden" with the proper type (0)`             | PASS    |                                                                                                                                                   |
| `Document interface: window.document must inherit property "visibilityState" with the proper type (1)`    | PASS    |                                                                                                                                                   |
| `Document interface: window.document must inherit property "onvisibilitychange" with the proper type (2)` | FAIL    | `assert_inherits: property "onvisibilitychange" not found in prototype chain`                                                                     |

</details>
</details>

**Comment by annevk** [comment]
It's defined as callback in HTML. Also, it kinda seems like IDL harness itself should take care of this, as it's such a core definition of the platform. (Just like IDL harness will have to care of various extended attributes defined in HTML.)

**Comment by igrigorik** [comment]
I'll defer to @annevk on the IDL harness bits.. but otherwise, LGTM.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5204/)

**Comment by plehegar** [comment]
The idlharness is way overdue for a refresh and I didn't find someone up for this so far :(

**Review by igrigorik — APPROVED** [review]

**Pull request merged**
