### PR TITLE
Updated parser for spec changes

### PR DESCRIPTION
**Pull request by BenjaminSchaaf**
Spec pull request: https://github.com/w3c/webvtt/pull/337

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5113/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/209727288)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 252389c48f2bc8cf3292c62b5f8a3b58bb26e3d9
Using browser at version BuildID 20170306110339; SourceStamp 966464a68a2cb3ca1125808e34abb5c1d34e3797
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/209727289)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 252389c48f2bc8cf3292c62b5f8a3b58bb26e3d9
Using browser at version 58.0.3029.6 dev
Starting 10 test iterations
No tests run.

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
Rebased to resolve conflict in support/settings-line.test from https://github.com/w3c/web-platform-tests/pull/5062

@BenjaminSchaaf could you sanity-check?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213446861)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 848624007263e11ab9daa6cd9ff890c01ab05290
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5113/webvtt/parsing/file-parsing/tests/settings-line.html">/webvtt/parsing/file-parsing/tests/settings-line.html</a></summary>


|     Subtest      | Results |                                 Messages                                |
|------------------|---------|-------------------------------------------------------------------------|
|                  | OK      |                                                                         |
| `settings, line` | FAIL    | `assert_unreached: got unexpected error event Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5113/webvtt/parsing/file-parsing/tests/settings-position.html">/webvtt/parsing/file-parsing/tests/settings-position.html</a></summary>


|       Subtest        | Results |                               Messages                              |
|----------------------|---------|---------------------------------------------------------------------|
|                      | OK      |                                                                     |
| `settings, position` | FAIL    | `assert_equals: Failed with cue 0 expected "auto" but got "center"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213446862)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 848624007263e11ab9daa6cd9ff890c01ab05290
Using browser at version 59.0.3043.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5113/webvtt/parsing/file-parsing/tests/settings-line.html">/webvtt/parsing/file-parsing/tests/settings-line.html</a></summary>


|     Subtest      | Results |                                     Messages                                    |
|------------------|---------|---------------------------------------------------------------------------------|
|                  | OK      |                                                                                 |
| `settings, line` | FAIL    | `assert_equals: Failed with cue 9 expected 1e+34 but got 9.999999790214768e+33` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5113/webvtt/parsing/file-parsing/tests/settings-position.html">/webvtt/parsing/file-parsing/tests/settings-position.html</a></summary>


|       Subtest        | Results |                                          Messages                                         |
|----------------------|---------|-------------------------------------------------------------------------------------------|
|                      | OK      |                                                                                           |
| `settings, position` | FAIL    | `assert_equals: Failed with cue 0 expected (string) "auto" but got (undefined) undefined` |

</details>
</details>

**Comment by BenjaminSchaaf** [comment]
LGTM

**Pull request merged**
