### PR TITLE
Split selectors test into smaller tests

### PR DESCRIPTION
**Pull request by gsnedders**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19280)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/285788914)

**Comment by foolip** [comment]
@gsnedders, can you rebase this so that the now-existing OWNERS takes effect?

**Review by emilio — APPROVED** [review]
Welp, sorry for missing this one. This looks fine to me, though fine if you want to get the OWNERS to stamp it too.

**Comment by gsnedders** [comment]
Rebased so it doesn't have conflicts!

**Pull request merged**
