### PR TITLE
Added 2 new CSS values tests

### PR DESCRIPTION
**Pull request by TalbotG**

### CODE REVIEW

**Review by FremyCompany — APPROVED** [review]

**Review by frivoal — CHANGES_REQUESTED** [review]
oops, there is one problem here:

cm, in, q, etc are compatible units with px, so they always get combined with px as per https://www.w3.org/TR/css-values-4/#compat

**Comment by frivoal** [comment]
OOps, I'm wrong again. the test doesn't used getComputedStyle, so that last point is wrong

**Comment by TalbotG** [comment]
ligne 64: verifySerialization("calc(11q + 1vh + 12%)", "calc(12% + 11q + 1vh)", "testing calc(11q + 1vh + 12%)"); 

ligne 66: verifySerialization("calc(1em + 2cm + 13% + 3em)", "calc(13% + 2cm + 4em)", "testing calc(1em + 2cm + 13% + 3em)");

are currently wrong and must be adjusted. Absolute lengths: the cm, mm, Q, in, pt, pc, px can always be converted into px unit.

**Comment by TalbotG** [comment]
I am closing this pull request. I will create a new one with all the necessary changes in a min.

**Comment by TalbotG** [comment]
Now the corrected and improved tests from this pull request are now in
https://github.com/web-platform-tests/wpt/pull/15423

**Pull request closed without merging**
