### PR TITLE
fullscreen: convert manual tests to automated tests

### PR DESCRIPTION
**Pull request by marcoscaceres**
Converts from manual tests to promise using tests...

### CODE REVIEW

**Comment by foolip** [comment]
@marcoscaceres some of the tests involving iframes are timing out in Chrome, but I think they do pass in Chromium's CI in their current state. Can you either leave these out of the PR, or keep both the manual and automated tests for now? I don't want to lose regression coverage, and we do run these "manual" tests in Chromium by injecting some special scripts.

**Comment by marcoscaceres** [comment]
I’ll try to get the broken ones working. 

However, some are legit timeouts I think. For instance, Chrome doesn’t reject the promise when an iframe is removed.

**Comment by marcoscaceres** [comment]
(If I can’t get them working I’ll bring back any manual ones, as you suggested… we need the new ones in WebKit somewhat urgently as we are actively implementing.)

**Comment by marcoscaceres** [comment]
@foolip I did some investigating... the reason the (manual) test is passing in Chrome is that it *never* runs the:

```
assert_true(true, "promise is rejected correctly");` 
```

for the promise. 

It's only running the following two asserts, so it's falsely passing the test:

> Pass | assert_equals(null, null)     at Test.<anonymous> ( /fullscreen/api/element-request-fullscreen-and-remove-iframe-manual.html:26:7)
> Pass | assert_equals(null, null)     at Test.<anonymous> ( /fullscreen/api/element-request-fullscreen-and-remove-iframe-manual.html:27:7)

The new test catches this issue, which is why it's timing out. That's a legit failure (though timing out is not great). 

Firefox, and Safari, do the the right thing. 

What I can do is maybe race the promise against a longer timeout. It's a bit gross, but...

**Comment by marcoscaceres** [comment]
Ok, I added a timeout. CI should hopefully like it now.

**Comment by marcoscaceres** [comment]
@foolip, sorry, one more question: For some tests, Chrome seems to "resize" the window in cases where fullscreen rejects (and puts the page into fullscreen, but doesn't apply `::backdrop`). 

This seems to imply something is either wrong with the fullscreen model or there are more serious bugs somewhere. 

I haven't checked what other browsers do... but I wanted to raise it as maybe it warrants some checks?

**Comment by marcoscaceres** [comment]
@foolip, given the fixes I made, cool to merge these? or do you still want the manual tests too?

**Comment by foolip** [comment]
@marcoscaceres in https://wpt.fyi/results/fullscreen/api?label=pr_head&max-count=1&pr=37223 I still see some tests that are failing everywhere, in particular document-exit-fullscreen-nested-in-iframe.html and element-ready-check-not-allowed-cross-origin.sub.html have harness errors, and element-ready-check-allowed-cross-origin.sub.html fails in the same way in Chrome+Firefox.

Are these the tests you looked into? Accounting for tests that fail everywhere would be great before merging this.

**Comment by marcoscaceres** [comment]
@foolip, had another look. The bugs are legit: 

* document-exit-fullscreen-nested-in-iframe.html - bug in both browsers. Chrome reports null, when it should report "inner".  Firefox doesn’t exit fullscreen from the iframe.  Safari can’t fullscreen the inner iframe.  
* element-ready-check-not-allowed-cross-origin.sub.html - Permissions Policy "self" is not being respected.
* element-ready-check-allowed-cross-origin.sub.html - Permissions Policy "self" is not being respected. 

(but I did find an unrelated bug ☺️)

**Comment by marcoscaceres** [comment]
@foolip, please let me know how we can proceed. I'd like to get this merged as we are actively implementing FS API in WebKit so we'd like to ingest all these tests as soon as possible.

**Comment by marcoscaceres** [comment]
Just noting that the stability issues are actually more bugs... the error event doesn't fire sometimes in Chrome or Firefox, it seems.

**Comment by foolip** [comment]
Thanks for looking into the failures! I'll go ahead and merge this and file bugs about the tests that are going to fail in Chrome.

**Pull request merged**
