### PR TITLE
Update interfaces/html.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/205b736/whatwg/idl/html.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/576128771

### CODE REVIEW

**Review by lukebjerring — APPROVED** [review]
Change to default url value only.

**Comment by lukebjerring** [comment]
This seems to regress some tests covering `onloadend`.

**Comment by foolip** [comment]
The `onloadend` subtest is removed, but that's OK because historical tests for it were added in #18499.

Taskcluster is still failing though. On Chrome /media-source/idlharness.any.worker.html was flaky, and in Firefox we got "Task timeout after 7200 seconds. Force killing container."

**Comment by foolip** [comment]
https://wpt.fyi/results/media-source/idlharness.any.worker.html?label=master&label=experimental shows the test is plainly broken :(

@lukebjerring being able to search for tests by failure of a specific subtest or maybe number of subtests would be great, to find if other idlharness tests are also busted.

**Comment by foolip** [comment]
I sent https://github.com/web-platform-tests/wpt/pull/18673 about the broken tests.

**Comment by foolip** [comment]
With https://github.com/web-platform-tests/wpt/pull/18674 landed, the flaky test no longer exists. Firefox was fine this time, rebasing to the Chrome stability job.

**Pull request merged**
