### PR TITLE
Python 3: Port tests in fetch/api [part 1]

### PR DESCRIPTION
**Pull request by ziransun**

### CODE REVIEW

**Comment by ziransun** [comment]
@annevk:   in Python3, a couple of tests in fetch/api/headers/header-values.html returned with error "code 431, message Too many headers". 
I wonder is there any reason we chose 0x100 in [this line](https://github.com/web-platform-tests/wpt/blob/aef9da08fe2fa0b9fa473e2e126cb3cf29fae43e/fetch/api/headers/header-values.html#L23)?

**Comment by annevk** [comment]
That's the upper exclusive limit of the number of distinct bytes.

**Comment by ziransun** [comment]
> That's the upper exclusive limit of the number of distinct bytes.

I've noticed the uplimit for maximum header length at this [line](https://github.com/python/cpython/blame/3.8/Lib/http/client.py#L110). It seemed being introduced in from 3.3. I wonder if that's the reason that caused the complaints in python 3 run?

**Comment by annevk** [comment]
Seems likely.

I suppose we could split this test, but then we wouldn't test whether browsers could deal with that many headers.

cc @Hexcles @jgraham

**Comment by Hexcles** [comment]
That's probably the wrong line (it's the client not the server), but python 3.6 did introduce a change regarding this:
https://github.com/python/cpython/commit/acc03195b0609490a4e5f8b1d9eb504c22c6526e
https://bugs.python.org/issue26586

Is the number 100 of any significance? I understand this is a stress test, but is there any spec that requires browsers to support 100 headers?

**Comment by annevk** [comment]
All I know is that browsers and the Python WPT server had no problem with 256 headers before. HTTP doesn't really say anything one way or another.

**Comment by Hexcles** [comment]
Sigh this is really unfortunate.

I'd say split the tests so that each request has fewer than 100 headers if we don't have to stress test 256 (or >100) headers.

**Comment by annevk** [comment]
That's not really acceptable to me as that'd be a regression in test coverage. 256 headers isn't really a stress test either imo.

**Comment by Hexcles** [comment]
Assigning this to myself to investigate working around the new limitation on the number of headers, potentially through monkey-patching Python stdlib

**Comment by Hexcles** [comment]
https://github.com/web-platform-tests/wpt/pull/24619

**Comment by Hexcles** [comment]
@ziransun could you rebase / merge master and retry?

**Comment by ziransun** [comment]
> @ziransun could you rebase / merge master and retry?

@Hexcles: All tests passed for Python 2 and Python 3 now.

**Review by Hexcles — APPROVED** [review]
LGTM

**Pull request merged**
