### PR TITLE
Add OWNERS to the resources directory

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6016)

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234753887)

# Firefox (nightly) #
Testing web-platform-tests at revision cdabbe858340537c9c4d5e78e0293ba28439ccfd
Ignoring 1 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234753888)

# Sauce (safari) #
Testing web-platform-tests at revision 9dd0c5ecd4914221752b55f8287d2f51776fa97b
Ignoring 1 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234753894)

# Chrome (unstable) #
Testing web-platform-tests at revision 9da88bea41baba47a148d12763bfa67c1cd90640
Ignoring 1 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234753895)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 9da88bea41baba47a148d12763bfa67c1cd90640
Ignoring 1 changed files:
No files changed

**Pull request merged**
