### PR TITLE
Enhancements and fixes to csp reporting mechanisms to allow other tests (manual chrome PR)

### PR DESCRIPTION
**Pull request by andypaicu**
This a manual PR of CL https://chromium-review.googlesource.com/c/552128/
 because the CL did not get upstreamed

CL description:

These changes are done as part of supporting porting the chrome reporting
  tests to wpt

Fixed the cookies part of report.py to save the cookies in the stash and
  retrieve them correctly when "op=cookies"
Added support for checking cookie presence in checkReport.sub.js
Added support for specifying reportID cookie name with fallback on the
  old method of using the test name
Added support for specifying test name in checkReport.sub.js with
  fallback on the hardcoded test name "Violation report status OK."
Adedd an extra image in support that will also be used for the reporting
  tests
Added support for getting the number of reports sent to a reportID
Renamed operations since now there are more of them

Bug: 694525
Change-Id: Ic72b61425f11e9719b21711f20c34ce736f99d77
Reviewed-on: https://chromium-review.googlesource.com/552128
Commit-Queue: Andy Paicu <andypaicu@chromium.org>
Reviewed-by: Mike West <mkwst@chromium.org>
Cr-Commit-Position: refs/heads/master@{#483003}

### CODE REVIEW

**Review by mikewest — APPROVED** [review]
Reviewed upstream. Should have been merged magically, not sure why it wasn't. :(

/cc @jeffcarp, @foolip

**Comment by mikewest** [comment]
(I'll merge it manually once Travis is happy)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248305114)

# Firefox (nightly) #
Testing web-platform-tests at revision aa32f06b0138a62838b6ffa2a72589fd00d565ed
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248305116)

# Sauce (safari) #
Testing web-platform-tests at revision aa32f06b0138a62838b6ffa2a72589fd00d565ed
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248305122)

# Chrome (unstable) #
Testing web-platform-tests at revision aa32f06b0138a62838b6ffa2a72589fd00d565ed
Using browser at version 61.0.3141.7 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248305123)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision aa32f06b0138a62838b6ffa2a72589fd00d565ed
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by andypaicu** [comment]
@jgraham the firefox integration is failing with this error:

```
File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 251, in __call__
    rv = self.func(request, response)
  File "/home/travis/build/w3c/web-platform-tests/content-security-policy/support/report.py", line 49, in main
    request.server.stash.put(key=key, value=report)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/stash.py", line 121, in put
    (internal_key, self.data[str(internal_key)], value))
  File "<string>", line 2, in __getitem__
  File "/opt/python/2.7.13/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
KeyError: "('/content-security-policy/support/report.py', '81ce8b46-c3ec-430a-955c-3c11b85e4cea')"
```

Which suggests that on line 49 of report.py we are using an existing key but the problem is that it should not happen since we remove it just above. Any ideas on what might be going on here?

```
request.server.stash.take(key=key)
request.server.stash.put(key=key, value=report)
```

Thank you very much.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by foolip** [comment]
I restarted that job, let's see if that helps.

**Comment by andypaicu** [comment]
The job keeps failing and I don't know enough about firefox to figure out why. See my comments above.

Could someone that knows more give me a hand?

**Comment by foolip** [comment]
@andypaicu, it looks to me like there's no guarantee that removing something from the stash means that it's not there again on the following line, as the stash is backed by some multiprocessing thing that presumably is using IPC.

If the client (Firefox) were to send two requests at the same time, or if there were a bug that makes it look like it does, would the resulting error look like this? Are you able to reproduce locally with Firefox Nightly?

**Comment by andypaicu** [comment]
Closed in favor of https://github.com/w3c/web-platform-tests/pull/6449

**Pull request closed without merging**
