### PR TITLE
Add tests for customElements.upgrade()

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/html/pull/3535.

Ideas for more tests welcome, although testing against no implementations is a bit rough.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25351)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349698133)

**Review by tkent-google — APPROVED** [review]
lgtm

**Comment by bicknellr** [comment]
Hi, I think the [last test here about upgrading elements inside a template's `content`](https://github.com/w3c/web-platform-tests/pull/9869/files#diff-e950b5134e8f7e7a64c1bd90d9c49d8fR146) might not be correct: https://github.com/webcomponents/custom-elements/pull/150#issuecomment-378001352 . The owner document of the elements inside the template content doesn't have a browsing context, so I don't think they should be upgraded by `customElements.upgrade(template.content)`. Is that true or is there something else I haven't taken into consideration?

**Comment by domenic** [comment]
I don't see anything in the spec about browsing contexts...

**Comment by domenic** [comment]
Oh, I didn't click through to your explanation. Sorry, re-parsing... you're probably right...

**Comment by bicknellr** [comment]
Ok, thanks for confirming!

**Pull request merged**
