### PR TITLE
[webvtt] Test VTTRegion id

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/w3c/webvtt/pull/349

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17395)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264620189)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17395)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264620189)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 05:20:18
Finished: 2017-08-15 05:33:13



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17395)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264620189)

**Comment by zcorpan** [comment]
This should maybe wait for a resolution of https://github.com/w3c/webvtt/issues/353

**Review by silviapfeiffer — APPROVED** [review]
I'm happy for it to land when @zcorpan is on board - w3c/webvtt#353 is agreeable with me

**Comment by zcorpan** [comment]
Proposed spec fix at https://github.com/w3c/webvtt/pull/354

**Pull request merged**
