### PR TITLE
Automate webauthn tests

### PR DESCRIPTION
**Pull request by nsatragno**
This patch uses the testdriver virtual authenticator API to automate all
webauthn tests when the browser running the tests supports it. The
standardSetup() function is repurposed to create a mock authenticator.

Timeout tests are also updated to use a mock authenticator that
simulates a user not being present.

Depends on #20409.

### CODE REVIEW

**Comment by nsatragno** [comment]
@jcjones this is ready to review, please take a look.

**Review by jcjones — APPROVED** [review]
This is an excellent improvement not only for readability but also for future patterning of these tests. Now I need my virtualdriver implementation.

**Comment by nsatragno** [comment]
Looks like since the tests timeout on firefox, `wpt-firefox-nightly-stability` takes too long and times out, which fails Community-TC. wpt.fyi shows no regressions on any browser, so I'll go ahead and merge manually.

**Comment by nsatragno** [comment]
Can we get this admin-merged, @foolip?

**Comment by Hexcles** [comment]
done

**Comment by montydrumzcm-stack** [comment]
[Age Verification API.yaml](https://github.com/user-attachments/files/31133724/Age.Verification.API.yaml)

**Pull request merged**
