### PR TITLE
Test which XSLT functions are defined

### PR DESCRIPTION
**Pull request by gsnedders**
This currently expects only tests defined in XSLT 1.0 (and references) to be defined. This matches what all browsers currently implement.

(I wrote this a while ago, no idea why it never got pushed as a PR.)

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Is this to prevent regressions?

I think it would be even better if you also included some non-functions (maybe especially some XSLT 2.0 stuff) with opposite expectations.

**Comment by annevk** [comment]
Oh, I didn't realize we implemented some XSLT 2.0 stuff. Ideally I'd like to see some stuff we don't support (and therefore shouldn't be adding).

**Comment by gsnedders** [comment]
> Oh, I didn't realize we implemented some XSLT 2.0 stuff. Ideally I'd like to see some stuff we don't support (and therefore shouldn't be adding).

See https://github.com/web-platform-tests/wpt/blob/f9e521edcbae1ba23b51b595979121145146885f/dom/xslt/functions.tentative.window.js#L249

It expects everything _beyond_ XSLT 1.0 is unsupported.

**Comment by annevk** [comment]
Brilliant, thanks for walking me through that!

**Pull request merged**
