### PR TITLE
Add PEP 484 type hints

### PR DESCRIPTION
**Pull request by lukebjerring**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7997)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-10-27 17:15:52
Finished: 2017-10-27 17:28:11


<h2>Failing Jobs</h2>
<ul>

<li>tools_unittest in py27</li>

<li>tools_unittest in pypy</li>

<li>wpt_integration in py27</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19988)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/293786804)

**Comment by Hexcles** [comment]
Sorry but I don't quite get the motivation to switch from `itervalues`/`iteritems` to `values`/`items`. I think they do have a difference in Python 2 and the iterators have much better performance when dicts are big.

**Comment by lukebjerring** [comment]
It's a backward-compatibility lint-fix - reverted.

**Comment by lukebjerring** [comment]
@jgraham reviewer so nice it picked you twice (can't seem to rectify). Note that these are worked out manually, so can you eyeball that they're reasonable?

**Comment by gsnedders** [comment]
If we're adding type hints, can we start running mypy against it? We'll also need to add `typing` as a dependency.

**Comment by lukebjerring** [comment]
@gsnedders Yeah we should eventually add as a Travis build, but it's far too noisy at the moment

**Comment by lukebjerring** [comment]
Changes have fallen out of date.

**Comment by gsnedders** [comment]
Dropbox have released a tool to generate annotations: https://mypy-lang.blogspot.co.uk/2017/11/dropbox-releases-pyannotate-auto.html

Would be interesting to start playing around with this!

**Pull request closed without merging**
