### PR TITLE
Fixes exception during HandshakeException handler

### LINKED ISSUE #27785: Exception when handling HandshakeException _stream_ws_thread
when running 
```./wpt run chrome 'websockets/constructor/010.html?wpt_flags=h2'```
the following error happens

```
  [0/1] /websockets/constructor/010.html?wpt_flags=h2
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/home/arenevier/src/wpt/tools/wptserve/wptserve/server.py", line 479, in _stream_ws_thread
    handshaker.do_handshake()
  File "/home/arenevier/src/wpt/tools/wptserve/wptserve/ws_h2_handshake.py", line 170, in do_handshake
    raise e
  File "/home/arenevier/src/wpt/tools/wptserve/wptserve/ws_h2_handshake.py", line 161, in do_handshake
    raise HandshakeException(
mod_pywebsocket.handshake._base.HandshakeException: ws_protocol must be None when the client didn't request any subprotocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arenevier/src/wpt/tools/wptserve/wptserve/server.py", line 481, in _stream_ws_thread
    self.logger.info('Handshake failed for error: %s', e)
  ▶ TIMEOUT [expected OK] /websockets/constructor/010.html?wpt_flags=h2

  ▶ Unexpected subtest result in /websockets/constructor/010.html?wpt_flags=h2:
  │ TIMEOUT [expected PASS] WebSockets: protocol in response but no requested protocol
  └   → Test timed out

```

This happens because the logger is an instance of NoOpLogger and its methods only accepts one argument.

This does not happen with ```./wpt serve``` because in that case, the logger is an instance of logging.Logger whose methods accept multiple arguments.

### PR DESCRIPTION
**Pull request by arenevier**
Make sure we pass only one argument to logger.info

Fixes #27785

### CODE REVIEW

**Comment by arenevier** [comment]
Something we could do instead (or additionally), to prevent that from happening again is to modify NoOpLogger methods signatures to accept multiple arguments (ie `def info(self, *msg)`)

**Comment by arenevier** [comment]
@Hexcles @ricea @jgraham @stephenmcgruer

**Review by ricea — APPROVED** [review]
lgtm

**Comment by stephenmcgruer** [comment]
> Something we could do instead (or additionally), to prevent that from happening again is to modify NoOpLogger methods signatures to accept multiple arguments (ie def info(self, *msg))

I think that yes, NoOpLogger should have the same signature as the logger we are trying to use (which I believe is just https://docs.python.org/3/library/logging.html ?). So based on e.g. https://docs.python.org/3/library/logging.html#logging.Logger.info, it should be `def info(msg, *args, **kwargs)`, but I'd be interested if @jgraham agrees or knows something otherwise :D

**Comment by jgraham** [comment]
The logger can be a mozlog logger which doesn't support he string interpolation feature so unless we change mozlog, the current signature is correct.

**Comment by stephenmcgruer** [comment]
> The logger can be a mozlog logger which doesn't support he string interpolation feature so unless we change mozlog, the current signature is correct.

Ah, that is great to know! So our current log statements should never use the `_log.info("string %s", argument)` form, then? In which case this PR is 100% correct :)

**Review by stephenmcgruer — APPROVED** [review]

**Pull request merged**
