### PR TITLE
IDL test: Remove title argument for registerProtocolHandler()

### PR DESCRIPTION
**Pull request by fred-wang**
This was discussed in [1] and test added in [2]. This commit updates
the corresponding IDL test.

[1] https://github.com/whatwg/html/pull/5425
[2] https://github.com/web-platform-tests/wpt/pull/22678

### CODE REVIEW

**Comment by Ms2ger** [comment]
This is also in  #23150

**Comment by annevk** [comment]
Yeah, let's close this as IDL changes are handled automatically normally. It's taking a little longer now due to a change in the IDL standard.

**Comment by stephenmcgruer** [comment]
@web-platform-tests/wpt-core-team (and anyone else who cares to comment) - Is there something we should be doing better to stop people modifying these files? They have a big banner at the top saying DO NOT MODIFY, but maybe we should go further? One idea that was floated about was to move them to an explicit `gen` directory, so `interfaces/gen/foo.idl`, for example.

**Comment by Ms2ger** [comment]
Given the size of this idl file, it's likely that the banner is far away. Mozilla ended up with a solution like https://searchfox.org/mozilla-central/rev/41c3ea3ee8eab9ce7b82932257cb80b703cbba67/dom/tests/mochitest/general/test_interfaces.js#128 in one case...

**Comment by stephenmcgruer** [comment]
> Mozilla ended up with a solution like ... in one case...

Let's... not do that, please. In Chromium we use presubmits for 'you probably dont want to modify this', and OWNERS files for cases where someone from a particular group (say security review) really needs to look at your change.

We could do something similar here in WPT, either utilizing the code owners support (I'm not very familiar with it), or just having wpt-pr-bot block non-automated PRs that touch `interfaces/` without a review from a core team person?

**Comment by annevk** [comment]
@stephenmcgruer it seems in both cases the person will still have done redundant work. You can only prevent that by meddling with the file itself in some way.

**Pull request closed without merging**
