### PR TITLE
[css-text] Fix broken links to mplus-1p-regular.woff font

### PR DESCRIPTION
**Pull request by mrego**
Since the tests were distributed into specific folders
(https://github.com/w3c/csswg-test/commit/f3b4ef24617e23a44c4f4c0d646d3c4916600d0c)
some tests under line-break/ had a wrong path to mplus-1p-regular.woff.

This commit fixes it copying the font under line-break/support/
and line-break/reference/support/ and updating the paths in
line-break/reference/ files.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24941)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346776867)

**Review by fred-wang — APPROVED** [review]
LGTM

**Comment by jgraham** [comment]
Adding the same font file in mutliple places in the tree is bad for a number of reasons (higher disk usage, poorer cache story) so we should try to avoid it and put fonts in common top-level directories like `/fonts/` where possible.

**Comment by mrego** [comment]
Yes I understand the problem. I copied it because of the issues we usually have with relative paths and the CSS test suites.
I copied the file to 2 places but it was already repeated in other folders, now it's in 6 places which sounds really wrong as you said:
* `css/css-writing-modes/support/mplus-1p-regular.woff`
* `css/css-text/support/mplus-1p-regular.woff`
* `css/css-text/line-break/support/mplus-1p-regular.woff`
* `css/css-text/line-break/reference/support/mplus-1p-regular.woff`
* `css/css-text/i18n/support/mplus-1p-regular.woff`
* `css/css-text/i18n/reference/support/mplus-1p-regular.woff`

I can move it to `fonts/` or should it be '/css/fonts/'? Maybe @gsnedders can reply about this.

Note that there are more repeated fonts in the repository: `AD.woff`, `CanvasTest.ttf`, `CSSFWOrientationTest.otf`, `CSSHWOrientationTest.otf`, `mplus-1p-regular.woff`, `Revalia.woff`, `sileot-webfont.woff`, `tcu-font.woff`.
Should we move them all to a common folder?

**Comment by gsnedders** [comment]
@mrego We can probably move them all into `/fonts`. Honestly, moving everything to `/fonts` and getting rid of `/css/fonts` probably makes a fair deal of sense.

**Pull request merged**
