### PR TITLE
Adding WebDriver support for Internet Explorer to wptrunner

### PR DESCRIPTION
**Pull request by jimevans**
This commit adds the necessary code to allow wptrunner to execute WebDriver tests against Internet Explorer.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6981)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-23 13:13:52
Finished: 2017-08-23 13:32:39





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17700)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/267576590)

**Comment by jgraham** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/wptrunner/browsers/ie.py, line 63 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6981#-KsE_7P1qQ0vTwcVUWCx:-KsE_7P27sGNCKl2YkJG:b-idsp8h) ([raw file](https://github.com/w3c/web-platform-tests/blob/f961438073087b66a40f107065257554dafb7ba3/tools/wptrunner/wptrunner/browsers/ie.py#L63)):*
> ```Python
> 
>     def start(self, **kwargs):
>         print self.server.url
> ```

Leftover debug print?

---

*[tools/wptrunner/wptrunner/browsers/internetexplorer.py, line 1 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6981#-KsE_PXQG3LWzuoZYO11:-KsE_PXQG3LWzuoZYO12:b-wg4683) ([raw file](https://github.com/w3c/web-platform-tests/blob/f961438073087b66a40f107065257554dafb7ba3/tools/wptrunner/wptrunner/browsers/internetexplorer.py#L1)):*
> ```Python
> from .base import Browser, ExecutorBrowser, require_arg
> ```

This file seems like a duplicate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6981)*

**Comment by gsnedders** [comment]
Do we document what browsers wptrunner supports everywhere? If we do, we should probably note that IE is supported primarily for IEDriver and we don't expect the platform tests to necessarily work in IE (and indeed our policy of "tests must support all up-to-date browsers" inherently means things like ES6 syntax is fine which will totally break them in any version of IE).

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6981)*

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
I don't think that wptrunner support is documented, but the widely-stated but possibly not written down policy on browser support is "latest Firefox, Chrome, Edge, Safari, except for stuff under resources/", and this doesn't change that. It just means that webdriver tests may want to impose additional review requirements, which is always allowed.

**Pull request merged**
