### PR TITLE
moved Samsung's tests

### PR DESCRIPTION
**Pull request by darobin**
These need updating (especially the PHP) but I'm opening a PR so that this branch is tracked as something to be worked on.

### CODE REVIEW

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by annevk** [comment]
It seems the problem with the first test is that `resources/img.jpg` does not have a `Content-Length` header. Is there another WPT resource we could use, @jgraham?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203475311)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 77c812c1cb39686859d47d1944dfe11a29b3add8
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/1914/XMLHttpRequest/firing-events-http-no-content-length.html">/XMLHttpRequest/firing-events-http-no-content-length.html</a></summary>


|                            Subtest                             | Results |
|----------------------------------------------------------------|---------|
|                                                                | OK      |
| `ProgressEvent: firing events for HTTP with no Content-Length` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/1914/XMLHttpRequest/firing-events-http-content-length.html">/XMLHttpRequest/firing-events-http-content-length.html</a></summary>


|                           Subtest                           | Results |
|-------------------------------------------------------------|---------|
|                                                             | OK      |
| `ProgressEvent: firing events for HTTP with Content-Length` | FAIL    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203475326)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 77c812c1cb39686859d47d1944dfe11a29b3add8
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/1914/XMLHttpRequest/firing-events-http-no-content-length.html">/XMLHttpRequest/firing-events-http-no-content-length.html</a></summary>


|                            Subtest                             | Results |
|----------------------------------------------------------------|---------|
|                                                                | OK      |
| `ProgressEvent: firing events for HTTP with no Content-Length` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/1914/XMLHttpRequest/firing-events-http-content-length.html">/XMLHttpRequest/firing-events-http-content-length.html</a></summary>


|                           Subtest                           | Results |
|-------------------------------------------------------------|---------|
|                                                             | OK      |
| `ProgressEvent: firing events for HTTP with Content-Length` | FAIL    |

</details>
</details>

**Comment by annevk** [comment]
I'm going to close this given the issue with these tests and the fact it's also tested by response-data-progress.htm.

**Pull request closed without merging**
