### PR TITLE
Add a test for the legend element

### PR DESCRIPTION
**Pull request by xiaojunwu**

### CODE REVIEW

**Comment by Ms2ger** [comment]
@xiaojunwu reviewed on critic; sorry for the delay.

**Comment by foolip** [comment]
https://critic.hoppipolla.co.uk/r/5820 is gone now, and with it the comments.

**Comment by foolip** [comment]
I've run the test in Chrome, Edge, Firefox and Safari, and found that it's passing 3/3 everywhere, except Edge where the first subtest fails. So, the test does reveal something interesting.

The test appears to match https://html.spec.whatwg.org/multipage/form-elements.html#dom-legend-form, so I'll merge the test. Thanks @xiaojunwu!

**Review by foolip — APPROVED** [review]

**Comment by Ms2ger** [comment]
Fixed in https://github.com/web-platform-tests/wpt/pull/13283.

**Pull request merged**
