### PR TITLE
[docs] Remove myself from the admin docs

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@KyleJu - are you the right person to be listed here nowadays? If not, let me know who to update the docs to point at :)

**Review by sideshowbarker — APPROVED** [review]

**Comment by KyleJu** [comment]
@jcscottiii would you be the right contact for wpt-pr-bot?

**Comment by jcscottiii** [comment]
You can put me for now. Long term: We should have one more person from our team (if not the full team) since our team owns the infrastructure for it now.

**Comment by KyleJu** [comment]
> You can put me for now. Long term: We should have one more person from our team (if not the full team) since our team owns the infrastructure for it now.

Thanks James!

**Pull request merged**
