### PR TITLE
Use Edge 16 in Travis builds

### PR DESCRIPTION
**Pull request by foolip**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9338)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23710)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/336008076)

**Comment by foolip** [comment]
I've filed https://github.com/w3c/wpt-pullresults/issues/58 about the weird thing that seems to be going on with the @w3c-bots comment.

I was hoping that https://pulls.web-platform-tests.org/job/23710.13 (the Edge link) would have shown that this works by listing the tests that ran successfully, but it doesn't work due to https://github.com/w3c/wpt-pullresults/issues/47.

Anyway, expanding https://travis-ci.org/w3c/web-platform-tests/jobs/336008126#L662 shows that this has worked, and the test results show nothing surprising, some things passing some things failing, the same as before.

Assigning to @mattl and @jugglinmike to review and merge.

**Review by Ms2ger — CHANGES_REQUESTED** [review]
LGTM, but revert the REVERTME commit.

**Comment by foolip** [comment]
I have dropped the REVERTME commit.

**Review by Ms2ger — APPROVED** [review]

**Review by jugglinmike — APPROVED** [review]
Progress!

**Comment by foolip** [comment]
As an aside, this means it's also *possible* to run Edge 16 for wpt.fyi without any own hardware. Nice to have that choice I guess.

**Pull request merged**
