### PR TITLE
Update resources submodule to the latest version

### PR DESCRIPTION
**Pull request by NavidZ**
There was a problem in testharness.js which is fixed in the latest version of resources.

### CODE REVIEW

**Comment by RByers** [comment]
Looks like @Ms2ger has just merged [PRs like this in the past](https://github.com/w3c/web-platform-tests/pull/2952) without comment.  @Ms2ger anything I should check before merging a PR to update testharness.js?

**Comment by gsnedders** [comment]
@RByers No. (Well, maybe check it is an update, but except for that, no.)

**Comment by RByers** [comment]
Great, thanks!

**Comment by gsnedders** [comment]
As @jgraham said on IRC, we really want to check that it points to the HEAD of the upstream master branch. If it doesn't (e.g., because it's avoiding a bug on master), we should fix why ever it isn't.

**Pull request merged**
