### PR TITLE
[geometry] Test for more renamed interfaces

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/w3c/fxtf-drafts/pull/166

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233557114)

# Firefox (nightly) #
Testing web-platform-tests at revision 9a6cc99bde23c3ec47a7612c3ce78656b3143c40
Using browser at version BuildID 20170517100341; SourceStamp 6e3ca5b38f7173b214b10de49e58cb01890bf39d
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5975/css/geometry-1/historical.html">/css/geometry-1/historical.html</a></summary>


|                              Subtest                              | Results |                       Messages                       |
|-------------------------------------------------------------------|---------|------------------------------------------------------|
|                                                                   | OK      |                                                      |
| `DOMMatrixReadOnly scaleNonUniform must be nuked`                 | FAIL    | `assert_false: on prototype expected false got true` |
| `DOMMatrix scaleNonUniformSelf must be nuked`                     | FAIL    | `assert_false: on prototype expected false got true` |
| `DOMMatrix multiplyBy must be nuked`                              | PASS    |                                                      |
| `DOMMatrix preMultiplyBy must be nuked`                           | PASS    |                                                      |
| `DOMMatrix translateBy must be nuked`                             | PASS    |                                                      |
| `DOMMatrix scaleBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix scale3dBy must be nuked`                               | PASS    |                                                      |
| `DOMMatrix scaleNonUniformBy must be nuked`                       | PASS    |                                                      |
| `DOMMatrix rotateBy must be nuked`                                | PASS    |                                                      |
| `DOMMatrix rotateFromVectorBy must be nuked`                      | PASS    |                                                      |
| `DOMMatrix rotateAxisAngleBy must be nuked`                       | PASS    |                                                      |
| `DOMMatrix skewXBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix skewYBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix fromString static member must be nuked`                | PASS    |                                                      |
| `DOMMatrixReadOnly fromString static member must be nuked`        | PASS    |                                                      |
| `DOMMatrixReadOnly scale number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix scaleSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly translate number of required arguments`        | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrixReadOnly scale3d number of required arguments`          | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly rotateFromVector number of required arguments` | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrixReadOnly rotateAxisAngle number of required arguments`  | FAIL    | `assert_equals: on prototype expected 0 but got 4`   |
| `DOMMatrixReadOnly skewX number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly skewY number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix translateSelf number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrix scale3dSelf number of required arguments`              | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix rotateFromVectorSelf number of required arguments`     | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrix rotateAxisAngleSelf number of required arguments`      | FAIL    | `assert_equals: on prototype expected 0 but got 4`   |
| `DOMMatrix skewXSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix skewYSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMPointReadOnly matrixTransform number of required arguments`   | FAIL    | `self[interf].prototype[member] is undefined`        |
| `DOMMatrixReadOnly multiply number of required arguments`         | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix multiplySelf number of required arguments`             | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix preMultiplySelf number of required arguments`          | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `CSSMatrix must be nuked`                                         | PASS    |                                                      |
| `DOMMatrixImmutable must be nuked`                                | PASS    |                                                      |
| `ClientRect must be nuked`                                        | PASS    |                                                      |
| `ClientRectList must be nuked`                                    | PASS    |                                                      |
| `WebKitPoint must be nuked`                                       | PASS    |                                                      |
| `MSCSSMatrix must be nuked`                                       | PASS    |                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233557115)

# Sauce (safari) #
Testing web-platform-tests at revision 9a6cc99bde23c3ec47a7612c3ce78656b3143c40
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5975/css/geometry-1/historical.html">/css/geometry-1/historical.html</a></summary>


|                              Subtest                              | Results |                                Messages                               |
|-------------------------------------------------------------------|---------|-----------------------------------------------------------------------|
|                                                                   | OK      |                                                                       |
| `DOMMatrixReadOnly scaleNonUniform must be nuked`                 | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false` |
| `DOMMatrix scaleNonUniformSelf must be nuked`                     | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix multiplyBy must be nuked`                              | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix preMultiplyBy must be nuked`                           | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix translateBy must be nuked`                             | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix scaleBy must be nuked`                                 | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix scale3dBy must be nuked`                               | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix scaleNonUniformBy must be nuked`                       | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix rotateBy must be nuked`                                | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix rotateFromVectorBy must be nuked`                      | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix rotateAxisAngleBy must be nuked`                       | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix skewXBy must be nuked`                                 | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix skewYBy must be nuked`                                 | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix fromString static member must be nuked`                | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrixReadOnly fromString static member must be nuked`        | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false` |
| `DOMMatrixReadOnly scale number of required arguments`            | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix scaleSelf number of required arguments`                | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly translate number of required arguments`        | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly scale3d number of required arguments`          | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly rotateFromVector number of required arguments` | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly rotateAxisAngle number of required arguments`  | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly skewX number of required arguments`            | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly skewY number of required arguments`            | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix translateSelf number of required arguments`            | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix scale3dSelf number of required arguments`              | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix rotateFromVectorSelf number of required arguments`     | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix rotateAxisAngleSelf number of required arguments`      | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix skewXSelf number of required arguments`                | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix skewYSelf number of required arguments`                | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMPointReadOnly matrixTransform number of required arguments`   | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrixReadOnly multiply number of required arguments`         | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix multiplySelf number of required arguments`             | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `DOMMatrix preMultiplySelf number of required arguments`          | FAIL    | `undefined is not an object (evaluating 'self[interf].prototype')`    |
| `CSSMatrix must be nuked`                                         | PASS    |                                                                       |
| `DOMMatrixImmutable must be nuked`                                | PASS    |                                                                       |
| `ClientRect must be nuked`                                        | FAIL    | `assert_false: expected false got true`                               |
| `ClientRectList must be nuked`                                    | FAIL    | `assert_false: expected false got true`                               |
| `WebKitPoint must be nuked`                                       | FAIL    | `assert_false: expected false got true`                               |
| `MSCSSMatrix must be nuked`                                       | PASS    |                                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233557125)

# Chrome (unstable) #
Testing web-platform-tests at revision 9a6cc99bde23c3ec47a7612c3ce78656b3143c40

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233557126)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 9a6cc99bde23c3ec47a7612c3ce78656b3143c40

**Review by foolip — APPROVED** [review]

**Review by peterjoel — APPROVED** [review]

**Pull request merged**
