### PR TITLE
chore(payment-method-id): create dir for incoming tests

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255933952)

# Firefox (nightly) #
Testing web-platform-tests at revision c43c8502b8a7b22d5e195a89cae637dfcf406785
Using browser at version BuildID 20170720100139; SourceStamp 0985725c848ec0cfc6f2f3c3a5aa3d71321e7620
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255933953)

# Sauce (safari) #
Testing web-platform-tests at revision c43c8502b8a7b22d5e195a89cae637dfcf406785
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255933959)

# Chrome (unstable) #
Testing web-platform-tests at revision c43c8502b8a7b22d5e195a89cae637dfcf406785

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255933960)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c43c8502b8a7b22d5e195a89cae637dfcf406785

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
