### PR TITLE
{DUMMY PR- DO NOT MERGE} Add more referrer-policy css-intergration tests

### PR DESCRIPTION
**Pull request by tungnh28**
This is dummy PR to find issue running in new svg referrer test

bugzilla-url: https://bugzilla.mozilla.org/show_bug.cgi?id=1330487
gecko-commit: 0f19433e45b7b53fc30d35c173755124ac6d3788
gecko-integration-branch: autoland
gecko-reviewers: heycam

### CODE REVIEW

**Comment by domfarolino** [comment]
Need any help with this? I've noticed a few of these PRs opening and closing...

**Comment by tungmangtdh3** [comment]
Thank you. There'is an error running in Travis CI, I have no idea how to test locally so I have to create a dummy PR. It's ok now.

**Comment by domfarolino** [comment]
I've seen some Travis CI errors for referrer-policy tests before that only occur because of too many tests being run, and were unrelated to actual changes being made. But the problem you were facing is gone now?

**Comment by tungmangtdh3** [comment]
Ah, I see, thanks. The error was gone, I think the changes were merged by gecko sync bot

**Pull request closed without merging**
