### PR TITLE
Add signed-exchange/META.yml (suggested reviewers)

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@irori @jyasskin can you confirm you're OK with this? @irori, I've sent an invite to the reviewers team that you'll need to accept in order to be able to be added as a reviewer automatically, and to merge PRs.

**Review by irori — APPROVED** [review]
lgtm

**Review by jyasskin — APPROVED** [review]
@nyaxt, are you also a good person to list here?

**Comment by nyaxt** [comment]
Yes. Feel free to add me too.

**Review by nyaxt — APPROVED** [review]

**Pull request merged**
