### PR TITLE
Referrer-Policy: Add 301 redirection tests. Regenerate tests.

### PR DESCRIPTION
**Pull request by kristijanburnik**
**Summary:**
- Added tests for 301 redirections:
  - no-redirect - same as before
  - keep-origin-redirect - final destination is of same origin as initial sub-resource request
  - swap-origin-redirect - final destination is of cross-origin (opposite of the initial request)
- Updated test filenames to include redirection type
- Refactored subresources and templates, better code reuse
- Fixed bug in spec_validator: now validating excluded test expansion patterns against schema as well
- Added sub-resource query parameter for fixing flakiness due to browser caching on redirects
- Extended spec JSON for overriding patterns (e.g. set a default and handle special case later down)
- Removed _referrer attr_ tests for the time being (until agreed if the spec should require it)
- Suppressed overhead of redirection tests for some subresources (spec JSON)
- Polyfilled `document.origin`
- Updated readme

**Stats:**
Test count: 1149 (more than doubled since last PR)

@mikewest

### CODE REVIEW

**Comment by kristijanburnik** [comment]
Included suppressed fetch-requests which lead to XHR vs Fetch confusion about what's the cross-origin behavior when the redirection switches back to the browser context's origin.
```
{
          "name": "cross-origin",
          "expansion": "override",
          "source_protocol": "http",
          "target_protocol": "http",
          "delivery_method": ["http-csp", "meta-referrer", "meta-csp"],
          "redirection": "swap-origin-redirect",
          "origin": "cross-origin",
          "subresource": ["xhr-request", "fetch-request"],
          "referrer_url": "stripped-referrer"
        }
```

**Comment by mikewest** [comment]
Based on our conversation this morning, I don't think we should have this override in the patch. The tests should reflect the expectations; it's perfectly fine to commit tests where Chrome is failing. :)

**Comment by mikewest** [comment]
> Added tests for 301 redirections:
> * no-redirect - same as before
> * keep-origin-redirect - final destination is of same origin as initial sub-resource request
> * swap-origin-redirect - final destination is of cross-origin (opposite of the initial request)
> Updated test filenames to include redirection type

Looking great!

> Extended spec JSON for overriding patterns (e.g. set a default and handle special case later down)

Do we need this for anything other than the Fetch/XHR bug we discussed this morning?

> * Refactored subresources and templates, better code reuse
> * Fixed bug in spec_validator: now validating excluded test expansion patterns against schema as well
> * Added sub-resource query parameter for fixing flakiness due to browser caching on redirects
> * Removed referrer attr tests for the time being (until agreed if the spec should require it)

Next time, I'd suggest splitting these out into separate patches.

> Polyfilled document.origin

Why? Where does it fail?

**Comment by kristijanburnik** [comment]
Here is a more complete picture, I don't believe it's a bug any more:

```json
{
  "name": "cross-origin",
  "expansion": "default",
  "source_protocol": "*",
  "target_protocol": "*",
  "delivery_method": ["http-csp", "meta-referrer", "meta-csp"],
  "redirection": "*",
  "origin": "cross-origin",
  "subresource": "*",
  "referrer_url": "origin"
},
{
  "name": "cross-origin",
  "expansion": "override",
  "source_protocol": "http",
  "target_protocol": "http",
  "delivery_method": ["http-csp", "meta-referrer", "meta-csp"],
  "redirection": "swap-origin-redirect",
  "origin": "cross-origin",
  "subresource": ["xhr-request", "fetch-request"],
  "referrer_url": "stripped-referrer"
}
```

So to conclude, this is specific behavior for XHR and fetch when we're doing swap-redirection:

```a.com/test.html``` --> ```b.com/xhr.py?with_redirection``` --> ```a.com/xhr.py```

yields the stripped-referrer to a.com/xhr.py. 

--

Extended spec JSON for overriding patterns, it's useful in more places and simplifies the spec JSON,
This is the other example:

```json
{
     "name": "same-origin-insecure",
     "expansion": "default",
     "source_protocol": "http",
     "target_protocol": "http",
     "delivery_method": ["http-csp", "meta-referrer", "meta-csp"],
     "redirection": "*",
     "origin": "same-origin",
     "subresource": "*",
     "referrer_url": "stripped-referrer"
},
{
     "name": "same-origin-insecure",
     "expansion": "override",
     "source_protocol": "*",
     "target_protocol": "*",
     "delivery_method": ["http-csp", "meta-referrer", "meta-csp"],
     "redirection": "swap-origin-redirect",
     "origin": "same-origin",
     "subresource": "*",
     "referrer_url": "origin"
}
```

This is actually ok since we're making a cross-origin request at the end:

```a.com/test.html``` --> ```a.com/xhr.py?with_redirection``` --> ```b.com/xhr.py```

--

document.origin fails on Firefox.

**Comment by mikewest** [comment]
> Here is a more complete picture, I don't believe it's a bug any more

If we have distinct behavior for XHR/Fetch on the one hand, and subresource loads on the other, then I think we're doing something wrong. Why wouldn't `` yield the same result as `fetch('http://a.com/xhr.py?with_redirection");`? Or am I misunderstanding?

**Comment by kristijanburnik** [comment]
I was referring that fetch/XHR behave the same, so it's not a specific XHR or a specific fetch bug as I thought. 

For other resources, I agree, we should dig down this issue to see if it's some spec's requirement or in fact a bug.

**Comment by kristijanburnik** [comment]
Just to give more context, these two are the special cases (img vs fetch) which now yield a different result.

**Image:**
https://github.com/kristijanburnik/web-platform-tests/blob/referrer-policy-test-case/referrer-policy/origin-when-cross-origin/http-csp/cross-origin/http-http/img-tag/cross-origin.swap-origin-redirect.http.html

**Fetch:**
https://github.com/kristijanburnik/web-platform-tests/blob/referrer-policy-test-case/referrer-policy/origin-when-cross-origin/http-csp/cross-origin/http-http/fetch-request/cross-origin.swap-origin-redirect.http.html

So currently tests are written to expect this behavior, we should investigate if that shoud remain so or if we should fail one or the other case.

**Comment by mikewest** [comment]
I'm fairly certain that the `` behavior is what we want to be correct. During a redirect, step 5 of the "main fetch" algorithm will have the `referrer` which was passed in 10.5 of the redirect switch in step 4 of https://fetch.spec.whatwg.org/#http-fetch. This referrer will have already been modified in the initial cross-origin request.

I believe it's a bug in Chrome, and the tests should reflect that.

**Comment by kristijanburnik** [comment]
On Tue, May 26, 2015 at 3:54 PM, Mike West <notifications@github.com> wrote:

> I'm fairly certain that the  behavior is what we want to be correct.
> During a redirect, step 5 of the "main fetch" algorithm will have the
> referrer which was passed in 10.5 of the redirect switch in step 4 of
> https://fetch.spec.whatwg.org/#http-fetch. This referrer will have
> already been modified in the initial cross-origin request.
>
> I believe it's a bug in Chrome, and the tests should reflect that.
>
I have removed the exception from the test suite. Chrome 42 now fails those
tests (6 of them).
I'll file the issue on crbug.com and see what I can do.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/web-platform-tests/pull/1856#issuecomment-105533374>
> .
>



-- 

*Kristijan Burnik*

Software Engineering Intern

burnik@google.com

Google Germany GmbH

Dienerstraße 12

80331 München

Geschäftsführer: Graham Law, Christine Elizabeth Flores

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

**Comment by mikewest** [comment]
LGTM % `document.origin`. Please squash the commits, and I'll land this for you.

**Comment by kristijanburnik** [comment]
Not sure what you mean by handling the port, since this is what FF 37.0.2 regards as the host:

```javascript
console.log(location.host)
"web-platform.test:8000"

console.log(location.protocol)
"http:"

console.log(location.protocol + "//" + location.host)
"http://web-platform.test:8000"
```

Hence:
```javascript
document.origin = document.origin || (location.protocol + "//" + location.host);
```

Which browser doesn't support the ```"$host:$port"``` format for ```location.host```?

**Comment by mikewest** [comment]
You're right. `window.location.host` is defined as including the port (https://url.spec.whatwg.org/#dom-urlutils-host). `window.location.hostname` does what I expected `host` to do.

I don't think that makes any sense, but whatever. I'm sure @annevk had good historical reason for doing it that way. :)

**Comment by annevk** [comment]
Before my time :-(

**Comment by kristijanburnik** [comment]
Which part?

On Tue, Jun 9, 2015 at 10:18 AM, Anne van Kesteren <notifications@github.com
> wrote:

> Before my time :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/web-platform-tests/pull/1856#issuecomment-110272025>
> .
>



-- 

*Kristijan Burnik*

Software Engineering Intern

burnik@google.com

Google Germany GmbH

Dienerstraße 12

80331 München

Geschäftsführer: Graham Law, Christine Elizabeth Flores

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

**Comment by annevk** [comment]
The naming of URL properties.

**Pull request merged**
