### PR TITLE
Remove css/css-transitions/properties-value-auto-001.html

### PR DESCRIPTION
**Pull request by graouts**
This test is incorrect in expecting transitions to be performed with `auto` values.

### CODE REVIEW

**Review by dbaron — COMMENTED** [review]
It looks like this is the only user of `getAutoPropertyTests`.  Should that (and things it depends on) be removed?

**Comment by graouts** [comment]
> It looks like this is the only user of `getAutoPropertyTests`. Should that (and things it depends on) be removed?

Nice catch! I've removed that method and code that would no longer be used after its removal in e0e543fbbdb84597859f97ddc96b174ec509d576.

**Review by flackr — APPROVED** [review]
LGTM, agreed we do not expect transitions to/from auto.

**Comment by graouts** [comment]
Is there a command to re-run the checks? I tried clicking on the re-run button after looking into details but nothing has happened yet.

**Comment by stephenmcgruer** [comment]
> Is there a command to re-run the checks? I tried clicking on the re-run button after looking into details but nothing has happened yet.

Sadly not, Taskcluster/etc don't seem to respect the 're-run' button (and we'd probably have to do work in our scripts to properly re-run the sink task too when that happened). Usually folks just close/re-open the PR (which is silly, I know!).

**Pull request merged**
