### PR TITLE
Update interfaces/pointerlock.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/fea9670/ed/idl/pointerlock.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/615198653

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
This one seems strange; can you have a look @foolip ? A space between `Element` and `?` is weird to me, though it is in the original spec (and seems to have been for years, not sure why reffy is picking it up now).

**Comment by foolip** [comment]
@stephenmcgruer https://w3c.github.io/pointerlock/ uses ReSpec, and I've seen whitespace changes in the past when ReSpec changes how it parses Web IDL. I've commented on https://github.com/tidoust/reffy/issues/196#issuecomment-557469187.

**Comment by foolip** [comment]
OK, here's what happened. https://github.com/tidoust/reffy/pull/198 bumped the version of respec used by reffy, and https://github.com/tidoust/reffy-reports/commit/fea9670dcd534a0ed477b42efa5ab39de5430e41 was the first reffy-reports update after that, bringing in a bunch of whitespace changes.

To get all those boring changes out of the way, I'll create a PR to sync just whitespace for lots of IDL files.

**Comment by tidoust** [comment]
Actually, these changes were more triggered by https://github.com/tidoust/reffy/pull/195 but reason is the same: Reffy was stuck to a now pretty old version of Respec before and Respec has indeed adjusted its WebIDL formatting rules since then.

**Comment by foolip** [comment]
@tidoust I linked to https://github.com/tidoust/reffy/pull/198 and not https://github.com/tidoust/reffy/pull/195 but I guess the root cause is the same in any case :)

**Comment by foolip** [comment]
With https://github.com/web-platform-tests/wpt/pull/20393 this should be closed automatically when reffy-reports sync next runs. Waiting for that rather than closing manually to ensure it works.

**Pull request closed without merging**
