### PR TITLE
Update interfaces/wake-lock.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Note: This file was recently manually updated in commit 8ab29ab9f6.
      This commit may revert some of those changes.

Source: https://github.com/tidoust/reffy-reports/blob/e0218fe/whatwg/idl/wake-lock.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/506822321

### CODE REVIEW

**Comment by Honry** [comment]
@foolip, looks like the bot is monitoring the [CR version](https://www.w3.org/TR/wake-lock/) of the spec,  while there's big change of IDL in [ED version](https://w3c.github.io/wake-lock/).

**Comment by foolip** [comment]
@Honry are you sure that's what's going wrong? In header says https://w3c.github.io/wake-lock/, could it instead be that it's not updating correctly? @dontcallmedom or @tidoust might be able to help to debug this.

In the meantime, should this PR be merged?

**Comment by tidoust** [comment]
@Honry @foolip This PR seems wrong and should be ignored.

I'm afraid that, following an apparently innocent update end of January, Reffy completely failed to send the right Authentication header with W3C API requests, meaning it could not retrieve the URL of many Editor's Drafts as a result. That should now be fixed. I updated the IDL files manually in reffy-reports. Hopefully, the crawls will now resume without incident.

**Comment by foolip** [comment]
@tidoust I see a bunch of new PRs today, so whatever you did seems to have had an effect :)

**Comment by foolip** [comment]
This branch was also updated, the change is much smaller now.

**Review by foolip — APPROVED** [review]
small whitespace change only

**Pull request merged**
