### PR TITLE
test PaymentMethodChangeEventInit defaults

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by edenchuang — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Hi, @foolip, any idea why @edenchuang’s approval is insufficient for us to merge? What should we do to fix that?

**Review by romandev — APPROVED** [review]
lgtm

**Comment by foolip** [comment]
@marcoscaceres, @edenchuang wasn't in the reviewers team. I'll fix now so that next time it will work!

**Comment by marcoscaceres** [comment]
Thanks @foolip! Much appreciated.

**Pull request merged**
