### PR TITLE
Fix 2dcontext yaml sub tests

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by youennf** [comment]
I updated yams tests. I needed to change gen tests.py as well. Hope this is ok.
I am not entirely sure what is the benefit of keeping those tests in sync with yaml though.

Note also that one of the test is not in sync (toDataURL...)

**Comment by zcorpan** [comment]
Thanks! I suppose the benefit is that it's theoretically easier to update in the yaml, or at least easier to write a bunch of new tests. We should fix the toDataURL test also.

We discussed in #testing whether we should drop the yaml and just maintain the generated test files, but @Ms2ger said he preferred keeping it around...

**Comment by youennf** [comment]
Is it ok for merging?

**Comment by zcorpan** [comment]
Yes, sorry for the delay.

**Pull request merged**
