### PR TITLE
[fetch] Label non-standard tests

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by annevk** [comment]
We generally don't use .tentative. for acknowledged specification issues.

**Comment by jugglinmike** [comment]
My initial thought was to remove the tests, but that seemed worse because it would tend to obscure the problem. How would you prefer to document this?

**Comment by annevk** [comment]
Maybe a comment pointing to the issue? It also depends a bit on what browsers do I suppose, but I thought they were mostly aligned.

**Comment by jugglinmike** [comment]
[Everybody's different.](https://wpt.fyi/results/fetch/metadata/embed.https.sub.html?run_id=649040001&run_id=670100001&run_id=656960001&run_id=662610004)

Chromium fires an initial load event, adds a child browsing context, and responds to immediate changes to the child's location.

Firefox fires an initial load event, adds a child browsing context, and ignores immediate changes to the child's location.

Safari does not fire a load event.

This highlights the fact that even the initial load event is non-standard, so however we decide to document this, we should use that approach for the entire test (as opposed to splitting it apart).

**Review by annevk — APPROVED** [review]
Okay, let's do it this way then. Thanks.

**Review by annevk — APPROVED** [review]

**Pull request merged**
