### PR TITLE
[WebDriver BiDi] Split DnD mouse tests

### PR DESCRIPTION
**Pull request by jrandolf**

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

**Comment by whimboo** [comment]
@jrandolf can you please check the [results of the Chrome stability job](https://github.com/web-platform-tests/wpt/pull/41580/checks?check_run_id=16102009673)? As it looks like there is something broken with the websocket connection, which is only reported in the wpt.fyi results that are showing that not a single drag and drop test is still passing.

**Comment by whimboo** [comment]
Please do not further split-up but add the META tag for an extended timeout.

**Comment by jrandolf** [comment]
@whimboo Looks like tests are passing finally!

**Review by whimboo — APPROVED** [review]
Thank you. It looks fine to me but maybe you can file an issue on your side to get the slow handling of drag and drop investigated. That feature takes a really long time.

**Comment by jrandolf** [comment]
> you can file an issue on your side to get the slow handling of drag and drop investigated

We are already aware of the reason. It's sadly difficult to fix since we separate our BiDi implementation from Chrome.

**Comment by OrKoN** [comment]
@jgraham @DanielRyanSmith would you mind admin-merging when you get a chance?

**Comment by jrandolf** [comment]
> Out of interest is there a public issue / bug that one could have a look at?

Nope, but since you asked I created one: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1207

**Comment by whimboo** [comment]
> @jgraham @DanielRyanSmith would you mind admin-merging when you get a chance?

With no admin merge since a week could I please ask someone from the @web-platform-tests/admins team to get this PR merged? Thanks!

**Comment by whimboo** [comment]
> > @jgraham @DanielRyanSmith would you mind admin-merging when you get a chance?
> 
> With no admin merge since a week could I please ask someone from the @web-platform-tests/admins team to get this PR merged? Thanks!

Actually wait, there are now merge conflicts that need to be resolved. @jrandolf can you please have a look? Thanks!

**Comment by jrandolf** [comment]
> > > @jgraham @DanielRyanSmith would you mind admin-merging when you get a chance?
> > 
> > 
> > With no admin merge since a week could I please ask someone from the @web-platform-tests/admins team to get this PR merged? Thanks!
> 
> Actually wait, there are now merge conflicts that need to be resolved. @jrandolf can you please have a look? Thanks!

Done!

**Pull request merged**
