### PR TITLE
Add README to document some missing canvas tests

### PR DESCRIPTION
**Pull request by junov**

### CODE REVIEW

**Comment by junov** [comment]
This is a companion PR for https://github.com/whatwg/html/pull/2343

**Comment by junov** [comment]
@annevk

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision af557fe6103f18c7b983784ad3d4741c14615dd0
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision af557fe6103f18c7b983784ad3d4741c14615dd0
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
I don't see the advantage of having this in the repo at all. @annevk? I'd much rather just have an issue on the repo rather than random README files scattered around it.

**Comment by annevk** [comment]
@gsnedders the purpose is for tests that we cannot currently create. Filing issues for them that are unlikely to get solved in the next several years just makes issues less useful, I think.

**Comment by gsnedders** [comment]
@annevk I think that a README in the repo is even less likely to be noticed in future as potential future work compared with a years old issue, and as such it's totally useless. Opinions @jgraham @Ms2ger?

**Comment by Ms2ger** [comment]
I tend towards gsnedders' side

**Comment by annevk** [comment]
Fair enough, filed #4802.

**Pull request closed without merging**
