### PR TITLE
Update easing-tests.js from m-c

### PR DESCRIPTION
**Pull request by jgraham**
It seems like a merge error resulted in this file being incorrectly synced with gecko.
Revert to the gecko version.

### CODE REVIEW

**Review by stephenmcgruer — APPROVED** [review]

**Comment by birtles** [comment]
@jgraham We still appear to be missing the changes to the following files from [same patch](https://hg.mozilla.org/mozilla-central/rev/b46aa2883e42):

* web-animations/testcommon.js
* css/css-typed-om/the-stylepropertymap/properties/animation-timing-function.html
* css/css-typed-om/the-stylepropertymap/properties/transition-timing-function.html

**Review by birtles — CHANGES_REQUESTED** [review]
We still appear to be missing the changes to the following files from [same patch](https://hg.mozilla.org/mozilla-central/rev/b46aa2883e42):
* web-animations/testcommon.js
* css/css-typed-om/the-stylepropertymap/properties/animation-timing-function.html
* css/css-typed-om/the-stylepropertymap/properties/transition-timing-function.html

**Comment by jgraham** [comment]
I added the other changes from the files mentioned.

**Comment by gsnedders** [comment]
TC stability failure partly due to https://github.com/web-platform-tests/wpt/issues/15596 (other failures look genuine?).

**Review by birtles — APPROVED** [review]

**Comment by birtles** [comment]
Thanks! Looks good to me.

**Comment by gsnedders** [comment]
@stephenmcgruer given the changes and the flakiness described at the end of the [wpt-chrome-stability](https://tools.taskcluster.net/groups/bEe7MFRdShqakLj-QpHp4g/tasks/IyCRct5aTr2Y1j6k0-1O8w/runs/0/logs/public%2Flogs%2Flive.log) job, I presume we should treat this as pre-existing flakiness?

**Comment by stephenmcgruer** [comment]
If I understand that job correctly, all the unstable results are AnimationWorklet (why were they run for this change? Is their flakiness blocking changes across all of web-platform-tests?). If so then yes please treat as existing flakiness. @majido owns making the AW tests not flaky.

**Comment by gsnedders** [comment]
@stephenmcgruer because they rely on `/web-animations/testcommon.js`

**Comment by majido** [comment]
I am working on reducing flakiness on these tests but I suggest you disable the flaky ones (here is the [list](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/TestExpectations?g=0&l=5949) in Chromium) until they are fixed.

### Context
AFAICT the standard setup in Chromium is to run wpt tests without threaded compositing. This has masked the flakiness (caused by threaded animation) in some of these tests. I just enabled running these with [threaded compositing](https://chromium-review.googlesource.com/c/chromium/src/+/1492436) which is closer to wpt.fyi configuration (and I assume your bots) which does not use content_shell . This has exposed the flakiness and I am gradually fixing [these](https://chromium-review.googlesource.com/c/chromium/src/+/1495227).

As a side note, I feel we should have at least a FYI bot in chromium that runs the same configuration (or as close as possible) to upstream bots so that we catch these type of issues earlier. @foolip  do you have any ideas if this is possible?

**Comment by majido** [comment]
@gsnedders so the patch changes the common file and bots run all test that include that file which involves these flaky tests.

Removing usage of `/web-animations/testcommon.js` in these tests is not to difficult (just duplicating a few functions) but I think the right solution is to make them as flaky. wdyt?

**Comment by foolip** [comment]
> As a side note, I feel we should have at least a FYI bot in chromium that runs the same configuration (or as close as possible) to upstream bots so that we catch these type of issues earlier. @foolip do you have any ideas if this is possible?

@LukeZielinski is working on using wptrunner in Chromium. It's not clear yet if it'll use the chrome or content_shell binary however.

**Comment by foolip** [comment]
@Hexcles what do you think about running stability checks for new tests in Chromium CQ? The other alternative we've discussed is reflecting back the status from Taskcluster into Gerrit code reviews, which would also show flakiness in other browsers.

**Pull request merged**
