### PR TITLE
[css-images] Test interaction between EXIF density and image-set() without <resolution>

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/w3c/csswg-drafts/issues/6241

@eeeps @noamr @emilio

### CODE REVIEW

**Review by noamr — APPROVED** [review]

**Comment by zcorpan** [comment]
Test results:

It passes in Firefox.
It fails in Chrome because it doesn't support unprefixed `image-set()` ([chromium bug 630597](https://bugs.chromium.org/p/chromium/issues/detail?id=630597)). Prefixed `-webkit-image-set()` works ([demo](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/9310)).
It fails in WebKit because of a rounding error, maybe? Should the test use 0.5x instead of 5x?

**Review by emilio — APPROVED** [review]
This seems a bit more complicated than the relevant `image-set-001.html` and `image-set-002.html`, which I added as part of my work on this feature, but seems fine anyways, thanks.

**Comment by zcorpan** [comment]
@emilio oh, I somehow missed that those tests existed. If this PR doesn't increase the test coverage then we should probably close it.

**Comment by zcorpan** [comment]
However, `image-set()` with omitted resolution is not currently tested. I can update this to test that instead (should act like `1x` if I've understood the discussion correctly).

**Comment by zcorpan** [comment]
Done.

**Review by emilio — APPROVED** [review]

**Pull request merged**
