### PR TITLE
[eme] Updates to multi-session sequential tests

### PR DESCRIPTION
**Pull request by mwatson2**
Update the multi-session sequential test to wait for the video to pause at the point with the second key before requesting the second license.

### CODE REVIEW

**Comment by jdsmith3000** [comment]
These changes are all fairly simple and LGTM.

**Comment by mwatson2** [comment]
I have updated these tests as follows:

- Fix the PSSH problems with the media file (#3447)
- Create all sessions for the multikey test up front since every chunk of this file uses both keys
- Switch the single-session multikey tests to use the basic playback-temporary test

We will need new content to match the original intention of the "multikey sequential" test, which was to have playback start with one key, stop with waitingforkey, and then fetch the second key at this point.

**Comment by jdsmith3000** [comment]
Two questions:

1. What was the pssh issue you worked around in the new mp4 file?
2. What was the overall goal of the multi-key refactoring?  Did it facilitate multi-session testing with same and multi-key?  Or something else?

Changes here in general look fine to me, but I'd like to understand the purpose, mostly for the multi-key change.

**Comment by mwatson2** [comment]
> What was the pssh issue you worked around in the new mp4 file?

#3447 It had two copies of each pssh box.

> What was the overall goal of the multi-key refactoring? Did it facilitate multi-session testing with same and multi-key? Or something else?

It was previously organized around whether there were multiple keys (as well as whether there were multiple session). In fact we do not need to distinguish the single-key single-session case from the multi-key single-session case: the same test script can be used for both with different parameters.

The multi-session script can also be used both for the case of separate keys in audio / video and of multiple keys used in every fragment.

We'll need a new script to re-instate the originally intended case where one key is used for a few seconds followed by another key. This may actually be two cases: one to check we get waitingforkey and can continue playback and another to check that playback can happen seamlessly if both keys are there at the start.

**Pull request merged**
