### PR TITLE
Dir isolation

### PR DESCRIPTION
**Pull request by r12a**
I abandoned https://github.com/w3c/web-platform-tests/pull/2357 because of some wierdness that i didn't know how to fix.  This is a second attempt to submit these tests to the W3C repo.  The files should include all the changes requested in the previous PR, including those changes made by Koji. 

results for these tests for major browsers can be found at 
http://www.w3.org/International/tests/repo/results/the-dir-attribute-isolation

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by zcorpan** [comment]
The original PR had 42 changed files, this has 40. Is something missing?

The linter complains about

> TRAILING WHITESPACE: html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-009a.html line 17

**Comment by kojiishi** [comment]
@r12a, there's a trailing space in `dir-isolation-009a.html`, can you fix this?

**Comment by kojiishi** [comment]
@zcorpan, the missing two files are the `resources` and `tools` subprojects that slipped in accidentally and could not figure out how to eliminate. They are in the bottom of "Files changed" tab of the original PR.

**Comment by zcorpan** [comment]
Ah yes, of course.

**Comment by kojiishi** [comment]
@zcorpan, @r12a fixed the trailing space, and now all lgtm. Could you help us to land this?

**Comment by jgraham** [comment]
Can you squash everything into a single commit?

**Comment by kojiishi** [comment]
@jgraham could you explain a bit more? IIUC we should not modify commits that were already uploaded, correct? Are you recommending to discard this PR, squash to one commit, and create a new PR?

**Comment by zcorpan** [comment]
That's just if you don't want to interrupt critic's review. Once the review is done, it's fine to rewrite history and force push. No need to create a new PR.

**Comment by kojiishi** [comment]
Ok, @r12a, can you do this? See [stackoverflow](http://stackoverflow.com/a/6934882) for how to squash, then I think you can `git push -f`, but I've never squashed once-uploaded-commits, so there may be more tricks.

If it's too much for you, I think creating a new PR is also ok. Ping me anytime if I can help you.

**Comment by zcorpan** [comment]
Landed in https://github.com/w3c/web-platform-tests/commit/ede29f13d822ee3e7adbb75c2d3533a91ed84b36

Thanks!

**Comment by kojiishi** [comment]
Superb, thank you @r12a  and @zcorpan!!

**Pull request closed without merging**
