### PR TITLE
[presentation-api] update idlharness.html for a controlling user agent

### PR DESCRIPTION
**Pull request by tomoyukilabs**
This PR updates `controlling-ua/idlharness.html` as per the current spec.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210400587)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d770b267d564b178b31960472e1b518a03dfad87
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5120/presentation-api/controlling-ua/idlharness.html">/presentation-api/controlling-ua/idlharness.html</a></summary>


|                         Subtest                         | Results |                       Messages                       |
|---------------------------------------------------------|---------|------------------------------------------------------|
|                                                         | OK      |                                                      |
| `Presentation API IDL tests for Controlling User Agent` | FAIL    | `ReferenceError: PresentationRequest is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210400588)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d770b267d564b178b31960472e1b518a03dfad87
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5120/presentation-api/controlling-ua/idlharness.html">/presentation-api/controlling-ua/idlharness.html</a></summary>


|                                                                      Subtest                                                                       | Results |                                                                                                  Messages                                                                                                 |
|----------------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                    | OK      |                                                                                                                                                                                                           |
| `Navigator interface: attribute presentation`                                                                                                      | PASS    |                                                                                                                                                                                                           |
| `Presentation interface: existence and properties of interface object`                                                                             | PASS    |                                                                                                                                                                                                           |
| `Presentation interface object length`                                                                                                             | PASS    |                                                                                                                                                                                                           |
| `Presentation interface object name`                                                                                                               | PASS    |                                                                                                                                                                                                           |
| `Presentation interface: existence and properties of interface prototype object`                                                                   | FAIL    | `assert_equals: class string of Presentation.prototype expected "[object PresentationPrototype]" but got "[object Presentation]"`                                                                         |
| `Presentation interface: existence and properties of interface prototype object's "constructor" property`                                          | PASS    |                                                                                                                                                                                                           |
| `Presentation interface: attribute defaultRequest`                                                                                                 | PASS    |                                                                                                                                                                                                           |
| `Presentation must be primary interface of navigator.presentation`                                                                                 | PASS    |                                                                                                                                                                                                           |
| `Stringification of navigator.presentation`                                                                                                        | PASS    |                                                                                                                                                                                                           |
| `Presentation interface: navigator.presentation must inherit property "defaultRequest" with the proper type (0)`                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: existence and properties of interface object`                                                                      | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface object length`                                                                                                      | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface object name`                                                                                                        | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: existence and properties of interface prototype object`                                                            | FAIL    | `assert_equals: class string of PresentationRequest.prototype expected "[object PresentationRequestPrototype]" but got "[object PresentationRequest]"`                                                    |
| `PresentationRequest interface: existence and properties of interface prototype object's "constructor" property`                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: operation start()`                                                                                                 | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: operation reconnect(USVString)`                                                                                    | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: operation getAvailability()`                                                                                       | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: attribute onconnectionavailable`                                                                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest must be primary interface of navigator.presentation.defaultRequest`                                                           | PASS    |                                                                                                                                                                                                           |
| `Stringification of navigator.presentation.defaultRequest`                                                                                         | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: navigator.presentation.defaultRequest must inherit property "start" with the proper type (0)`                      | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: navigator.presentation.defaultRequest must inherit property "reconnect" with the proper type (1)`                  | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: calling reconnect(USVString) on navigator.presentation.defaultRequest with too few arguments must throw TypeError` | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: navigator.presentation.defaultRequest must inherit property "getAvailability" with the proper type (2)`            | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: navigator.presentation.defaultRequest must inherit property "onconnectionavailable" with the proper type (3)`      | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest must be primary interface of presentation_request`                                                                            | PASS    |                                                                                                                                                                                                           |
| `Stringification of presentation_request`                                                                                                          | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request must inherit property "start" with the proper type (0)`                                       | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request must inherit property "reconnect" with the proper type (1)`                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: calling reconnect(USVString) on presentation_request with too few arguments must throw TypeError`                  | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request must inherit property "getAvailability" with the proper type (2)`                             | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request must inherit property "onconnectionavailable" with the proper type (3)`                       | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest must be primary interface of presentation_request_urls`                                                                       | PASS    |                                                                                                                                                                                                           |
| `Stringification of presentation_request_urls`                                                                                                     | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request_urls must inherit property "start" with the proper type (0)`                                  | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request_urls must inherit property "reconnect" with the proper type (1)`                              | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: calling reconnect(USVString) on presentation_request_urls with too few arguments must throw TypeError`             | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request_urls must inherit property "getAvailability" with the proper type (2)`                        | PASS    |                                                                                                                                                                                                           |
| `PresentationRequest interface: presentation_request_urls must inherit property "onconnectionavailable" with the proper type (3)`                  | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface: existence and properties of interface object`                                                                 | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface object length`                                                                                                 | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface object name`                                                                                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface: existence and properties of interface prototype object`                                                       | FAIL    | `assert_equals: class string of PresentationAvailability.prototype expected "[object PresentationAvailabilityPrototype]" but got "[object PresentationAvailability]"`                                     |
| `PresentationAvailability interface: existence and properties of interface prototype object's "constructor" property`                              | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface: attribute value`                                                                                              | PASS    |                                                                                                                                                                                                           |
| `PresentationAvailability interface: attribute onchange`                                                                                           | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionAvailableEvent interface: existence and properties of interface object`                                                     | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionAvailableEvent interface object length`                                                                                     | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionAvailableEvent interface object name`                                                                                       | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionAvailableEvent interface: existence and properties of interface prototype object`                                           | FAIL    | `assert_equals: class string of PresentationConnectionAvailableEvent.prototype expected "[object PresentationConnectionAvailableEventPrototype]" but got "[object PresentationConnectionAvailableEvent]"` |
| `PresentationConnectionAvailableEvent interface: existence and properties of interface prototype object's "constructor" property`                  | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionAvailableEvent interface: attribute connection`                                                                             | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: existence and properties of interface object`                                                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface object length`                                                                                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface object name`                                                                                                     | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: existence and properties of interface prototype object`                                                         | FAIL    | `assert_equals: class string of PresentationConnection.prototype expected "[object PresentationConnectionPrototype]" but got "[object PresentationConnection]"`                                           |
| `PresentationConnection interface: existence and properties of interface prototype object's "constructor" property`                                | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute id`                                                                                                   | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute url`                                                                                                  | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute state`                                                                                                | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation close()`                                                                                              | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation terminate()`                                                                                          | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute onconnect`                                                                                            | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute onclose`                                                                                              | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute onterminate`                                                                                          | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute binaryType`                                                                                           | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: attribute onmessage`                                                                                            | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation send(DOMString)`                                                                                      | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation send(Blob)`                                                                                           | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation send(ArrayBuffer)`                                                                                    | PASS    |                                                                                                                                                                                                           |
| `PresentationConnection interface: operation send(ArrayBufferView)`                                                                                | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface: existence and properties of interface object`                                                         | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface object length`                                                                                         | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface object name`                                                                                           | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface: existence and properties of interface prototype object`                                               | FAIL    | `assert_equals: class string of PresentationConnectionCloseEvent.prototype expected "[object PresentationConnectionCloseEventPrototype]" but got "[object PresentationConnectionCloseEvent]"`             |
| `PresentationConnectionCloseEvent interface: existence and properties of interface prototype object's "constructor" property`                      | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface: attribute reason`                                                                                     | PASS    |                                                                                                                                                                                                           |
| `PresentationConnectionCloseEvent interface: attribute message`                                                                                    | PASS    |                                                                                                                                                                                                           |

</details>
</details>

**Review by tidoust — APPROVED** [review]
This looks good to me, although I note we'll need to rename most of our test files eventually, including this one, to add `.https` to the file name, given the use of `SecureContext`.

Actually, this raises the question of how to check that the `SecureContext` flags are followed in implementations.

Ideally, IDL tests would run both in a secure context and in a non secure context, and the IDL harness would report an error, should a `SecureContext` interface still be exposed in a non secure context. I created an issue against the IDL harness accordingly: https://github.com/w3c/testharness.js/issues/249

Now, even if the IDL harness supports the flag, running tests both in a secure context and in a non secure context would require duplicating the IDL test files to end up with one name ending up with `.https.html` and another without `.https`. Not sure if there is any other way to do that.

PS: The error reported by Travis seems to be due to the use of `setTimeout` in a `longtask-timing` test, so not related with this test at all.

**Comment by tomoyukilabs** [comment]
Okay. Regarding this PR, I will change the file name into `idlharness.https.html`. If IDL harness supports a `SecureContext` flag, I will be able to add a duplicated test without `.https`.

On the other hand, I consider updating the other tests as another PRs.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5120/)

**Comment by tomoyukilabs** [comment]
@tidoust Thanks a lot!

**Pull request merged**
