### PR TITLE
[dom] Split Range-mutations.html into 10 test files.

### PR DESCRIPTION
**Pull request by tkent-google**
Chromium project has 90 seconds limit for each of test run with Debug
build. Range-mutations.html was too slow, and exceeded the limit.

### CODE REVIEW

**Comment by tkent-google** [comment]
It seems Travis failed because console output were too long.

> The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
>
> The job has been terminated

**Comment by youennf** [comment]
@tkent-google, I am in general in favour of splitting tests. This fits better with WebKit (and it seems Chrome as well) test infrastructure.

We had similar issues in WebKit with slow tests.
We upgraded the W3C test parser script to check for the timeout meta tag.
We upgraded the W3C test importer script to mark these tests as slow in a dedicated test-options.json file. The test timeout limit is increased for those tests.

**Comment by jgraham** [comment]
Please rebase to trigger a fixed travis script. Once that's done r+ from me.

**Comment by tkent-google** [comment]
All checks passed and this PR is now mergeable, however ci_stability.sh threw an exception.

https://travis-ci.org/w3c/web-platform-tests/jobs/170283476
```
ERROR:check_stability:Traceback (most recent call last):
  File "check_stability.py", line 557, in main
    gh_handler.send()
  File "check_stability.py", line 141, in send
    self.github.post_comment(self.pull_number, "\n".join(self.log_data))
  File "check_stability.py", line 119, in post_comment
    return self.post(url, {"body": body})
  File "check_stability.py", line 104, in post
    resp.raise_for_status()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/w3c/web-platform-tests/issues/4049/comments
```

**Pull request merged**
