### PR TITLE
Throw rejection reason in fullscreen test to improve error message

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by upsuper** [comment]
It's not going to make any difference, is it? I don't think our implementation includes any information in the error, the spec doesn't say so, and there may be a good reason not to do that.

**Comment by foolip** [comment]
Oh, I assumed there was more information and I'd just mangled it.

**Comment by upsuper** [comment]
Does Blink expose more information on the error object? Is there privacy concern over exposing them?

**Comment by foolip** [comment]
Thanks to @lukebjerring's magic we can see the effect that this had:
https://staging.wpt.fyi/results/fullscreen/api/element-request-fullscreen.html?diff&run_id=5042056388935680&run_id=6318713171083264

So no more information, actually less, it's harder to tell where the problem came from.

> Does Blink expose more information on the error object? Is there privacy concern over exposing them?

The fullscreen errors don't have very interesting messages. I've considered saying what part of the fullscreen element ready check failed, which would be useful, but I haven't thought of whether that could expose information about the ancestor iframes which otherwise aren't available.

**Comment by foolip** [comment]
Closing this PR, it doesn't help.

**Pull request closed without merging**
