### PR TITLE
Plh/page visibility/onvisibilitychange

### PR DESCRIPTION
**Pull request by plehegar**

### CODE REVIEW

**Comment by toddreifsteck** [comment]
These tests for Page Visibility 2 LGTM. Should we name or subdirectory them to make it clear they are for PV2 and not PV1? (Or is that already done?)

**Comment by plehegar** [comment]
t don't test versioning on web-platform-tests. it's somehow orthogonal and the goal is to test the latest version of the specifications to facilitate implementations.

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by ayg** [comment]
I can't figure out how to restore the branch at this point, so please re-push it if you still have it locally in case I don't wind up finding a solution.

**Comment by igrigorik** [comment]
@siusin looks like @plehegar got us most of the way there.. Any chance you can update this branch and resolve the conflicts?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257771249)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257771250)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257771259)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257771260)

# Sauce (MicrosoftEdge) #

**Review by igrigorik — APPROVED** [review]

**Pull request merged**
