### PR TITLE
streams: change how a buffer is detached

### PR DESCRIPTION
**Pull request by panva**
This would allow the Node.js project one less workaround to get the WPT going.

### CODE REVIEW

**Review by saschanaz — APPROVED** [review]

**Review by ricea — APPROVED** [review]
lgtm, thanks.

I think if you do this you can change it from `window.js` to `any.js`.

**Comment by panva** [comment]
rebased

**Review by saschanaz — COMMENTED** [review]
It's fine, but `// META: global=window,worker` will make this better as by default WPT seemingly only covers window and dedicated worker.

**Comment by panva** [comment]
done.

**Pull request merged**
