### PR TITLE
Add CSP test for protocols that an open wildcard '*' do now allow.

### PR DESCRIPTION
**Pull request by joelweinberger**
cc @mikewest @hillbrad

### CODE REVIEW

**Comment by mikewest** [comment]
@foolip: Is there a mechanism by which we can mark the prefixed bit as a test that just doesn't run in certain browsers? Skimming through `testharness.js`, I see a NOTRUN status (which I've seen pop up in some test results before), but it's not clear to me how it works. You and @hillbrad are my my local experts, so... :)

**Comment by foolip** [comment]
I see there's already a `if (window.webkitRequestFileSystem)` guard, is that not sufficient? When in doubt about these kinds of things, I always ask @jgraham.

The problem here is of course that http://dev.w3.org/2009/dap/file-system/file-dir-sys.html was implemented and then abandoned, and that AFAIK there is no plan to either remove the implementation nor breathe life into a spec and unprefix it.

**Comment by jgraham** [comment]
So the standard answer to this is "don't use prefixed things in tests".

`Not Run` is generally a status indicating that a test was defined but for some reason we didn't get as far as running it (e.g. due to an uncaught exception elsewhere or a timeout). It doesn't mean "this test wasn't relevant to this implementation.

If you really really want to keep this test in I suggest you move the definition outside the if block and have it pass in any implementation that doesn't support the feature.

**Comment by metromoxie** [comment]
I don't feel strongly about keeping the test in; this is a copy from the Blink code, which is the only reason it remains there. It sounds like I should probably remove it? Once I get confirmation from you all of that, I'll happily update the pull request.

**Comment by hillbrad** [comment]
Here's an adapted test from the Blink codebase that checks matching
"filesystem:" URLs against 'self', which shows the voodoo to set the test
automatically to "NOT RUN" if it's not supported in the user agent.  This
pattern is also used e.g. for some of the object-src and media-types tests
where Flash or Java may or may not be available.

https://github.com/w3c/web-platform-tests/blob/master/content-security-policy/blink-contrib/filesystem-urls-do-not-match-self.sub.html

**Comment by jgraham** [comment]
I'm still not thrilled with that use of `Not Run`. Generally `Not Run` means that something went wrong. Overloading it for use in cases where nothing bad happened seems problematic and I would prefer just passing the test in that situation.

**Comment by hillbrad** [comment]
For a feature like filesystem:// that's just not there in some cases,
agreed, passing the test is probably better.  I still think we need a
different solution for something like dependencies on Flash or Java where
behavior is specified and mandatory, but whether the test can run is
determined by user configuration.

**Comment by metromoxie** [comment]
Okay, per our discussion, I just modified the filesystem portion of the test to automatically pass if the API is not present. Please take a look. Thanks!

**Comment by hillbrad** [comment]
@jgraham looks like Critic didn't pick up this and generate a review?

**Comment by metromoxie** [comment]
I've addressed the one nit. @mikewest or @hillbrad, can one of you merge since I don't have the rights to do so? Thanks!

**Pull request merged**
