### PR TITLE
Implemente Categorization for WebVTT

### PR DESCRIPTION
**Pull request by BenjaminSchaaf**
I've implemented a tool that takes the test results in a json format and spits out how many tests of each category passed.

I've added rudimentary categorization of the current tests, focusing on those I've already worked through.
Which other categories would be good?

I've also added a README explaining how to run the tool.
What else would be good to have in the README?

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5181/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213293300)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 6070cf8494197a500ac4d2e70d8a4371efa98a67
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213293301)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 6070cf8494197a500ac4d2e70d8a4371efa98a67
Using browser at version 59.0.3043.0 dev
Starting 10 test iterations
No tests run.

**Review by zcorpan — APPROVED** [review]

**Comment by silviapfeiffer** [comment]
LGTM

Maybe you can pick some of the features groups I'm mentioning at http://www.webvtt.org/ as categories​?

**Comment by zcorpan** [comment]
Let's merge this, we can add more categories as followups.

**Pull request merged**
