### PR TITLE
Let test262 take care of "Typed Arrays"

### LINKED ISSUE #5125: Move typedarrays tests to test262
See https://github.com/tc39/test262/issues/902.

### PR DESCRIPTION
**Pull request by annevk**
Closes #5125. See also analysis in
https://github.com/tc39/test262/issues/902.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5127/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210604161)

# Firefox (nightly channel) #
Testing web-platform-tests at revision b1ccc1d1450f0deb6034c7cbf87dfdcb03f32ddb
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210604162)

# Chrome (unstable channel) #
Testing web-platform-tests at revision b1ccc1d1450f0deb6034c7cbf87dfdcb03f32ddb
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
Are browsers actually running test262 nowadays?

**Comment by annevk** [comment]
I believe so, yes.

**Comment by gsnedders** [comment]
If that's the case, then I'm fine with dropping these.

**Comment by annevk** [comment]
(I got confirmation on the #jslang IRC channel for most engines.)

**Pull request merged**
