### PR TITLE
stops using wrappedJSObject in marionette executor

### LINKED ISSUE #10035: Stopped using wrappedJSObject in marionette executor.
Per @andreastt this may be unnecessary now

### PR DESCRIPTION
**Pull request by kritisingh1**
Closes #10035

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-14 19:48:47
Finished: 2018-03-14 20:01:18





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25987)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/353508438)

**Comment by jgraham** [comment]
Ah, sorry I didn't explain this very well. I think it should be possible to  replace `window.wrappedJSObject` with just `window`, although we may need to change  the way we call `marionette.new_session` if it doesn't work initially.

**Comment by kritisingh1** [comment]
@jgraham I have made the changes. Is there anything else that needs to be done?

**Comment by jgraham** [comment]
Yes, there are some other places that use this including  `tools/wptrunner/wptrunner/executors/testharness_marionette.js`

**Comment by kritisingh1** [comment]
@jgraham Please review. Thanks

**Review by jgraham — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
