### PR TITLE
Add tests for webkitMatchesSelector.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by gsnedders** [comment]
I thought we'd previous decided to not go out of our way to test prefixed implementations?

**Comment by Ms2ger** [comment]
If it's in the spec, it should be tested.

**Comment by gsnedders** [comment]
I'd entirely missed it getting added to the spec. :)

**Comment by gsnedders** [comment]
Why are we awaiting on @Ms2ger?

**Comment by Ms2ger** [comment]
I think someone complained on critic that `Element-webkitMatchesSelector.html ` and `Element-matches.html ` contain too much duplicated code. I have no time to fix that.

**Comment by zcorpan** [comment]
Filed https://github.com/w3c/web-platform-tests/issues/5036 - let's not block on that

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/2266)

**Pull request merged**
