### PR TITLE
Regenerate WOFF2 support fonts

### LINKED ISSUE #9300: css/WOFF2 tests overlap with woff2-compiled-tests repo
These are very similar:
https://github.com/w3c/web-platform-tests/tree/master/css/WOFF2
https://github.com/w3c/woff2-compiled-tests/tree/master/UserAgent/Tests/xhtml1

Someone built from https://github.com/w3c/woff2-tests/blob/master/generators/UserAgentTestCaseGenerator.py

People who have poked at the woff2-compiled-tests repo are @rsheeter and @khaledhosny.

Looks like @svgeesus imported the tests into csswg-test, which has now been merged into this repo, but I can't tell what the origin is.

It would be good if there were one source of truth, and if any divergence between these is resolved.

The situation is a bit similar to WebAssembly I think, and @jgraham might have opinions on how this should work.

### PR DESCRIPTION
**Pull request by fred-wang**
Regenerate the WOFF2 fonts to be sure they are really up-to-date. This makes
the WPT repo in sync with the woff2-tests repo [1] and closes #9300.

[1] https://github.com/w3c/woff2-tests/commit/dc973d0848e738b62d9a8f21e164dc9b6c87d168

### CODE REVIEW

**Comment by svgeesus** [comment]
@fred-wang I think you will need a web-pltform-tests admin to override the travis-ci failure here

**Comment by fred-wang** [comment]
@svgeesus Yes, but I need review approval before an admin can merge it.

**Review by svgeesus — APPROVED** [review]
Thanks for doing this. LGTM.
Not clear why Travis CI is failing.

**Comment by fred-wang** [comment]
It looks like the usual error with Firefox-dev bot timing out when there are too many tests to run.

**Comment by jdm** [comment]
The travis failure log includes at least 135 WOFF2 test failures. Why do you believe that should be ignored?

**Comment by fred-wang** [comment]
@jdm: In similar updates, the Firefox-dev bots was timing out, just because too many tests were running. I agree that it seems a different issue now...

**Comment by fred-wang** [comment]
cc'ing @jfkthame 

@jdm: The tests seem to work for me when I try locally (Firefox 60). I only get the following errors:

!	/css/WOFF2/directory-knowntags-001.xht
!	/css/WOFF2/header-totalsfntsize-001.xht
!	/css/WOFF2/tabledata-glyf-bbox-001.xht
!	/css/WOFF2/tabledata-glyf-origlength-001.xht
!	/css/WOFF2/tabledata-glyf-origlength-002.xht
!	/css/WOFF2/tabledata-glyf-origlength-003.xht

but only the second one shows "FAIL" instead of "PASS" (per the reftest-analyser, the others fail because of some non-obvious pixel diffs). So I suspect the error is due to some setup on the bot, not to the change itself (which is just about regenerating web fonts)?

**Comment by fred-wang** [comment]
cc' @jgraham

**Comment by svgeesus** [comment]
> The travis failure log includes at least 135 WOFF2 test failures. Why do you believe that should be ignored?

Because those failures are not observed when the tests are run manually, and the tests themselves have not changed.

**Pull request closed without merging**
