### PR TITLE
Upstream 'SecurityPolicyViolationEvent' tests.

### PR DESCRIPTION
**Pull request by mikewest**
These are the 'testharness.js'-based tests we have in Blink for
SecurityPolicyViolationEvent. Will add more as we convert them.

### CODE REVIEW

**Comment by mikewest** [comment]
@foolip: Can you stamp/merge these, assuming they pass lint checks? Just upstreaming these from Blink's tests.

**Comment by mikewest** [comment]
(Also, cool!)

**Comment by foolip** [comment]
It sure is great, all thanks to @jgraham!

**Comment by RByers** [comment]
> Are the Chrome results against ToT? 

Yes - the script uses the latest linux chromium build from our bots.

**Pull request merged**
