### PR TITLE
Update to webidl2.js@22.0.0

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #16804, closes #16799

### CODE REVIEW

**Comment by saschanaz** [comment]
Can anyone restart Azure Pipelines test? Clicking re-run does not work for me.

**Comment by gsnedders** [comment]
@jgraham @lukebjerring can one/both of you do a full run against this PR?

**Comment by lukebjerring** [comment]
I'm away - I think @foolip knows how to do this too?

**Comment by foolip** [comment]
I've submitted https://chromium-review.googlesource.com/c/chromium/src/+/1630483

There were the presubmit warnings:

```
* Presubmit Warnings **
Found lines longer than 800 characters (first 5 shown).
  third_party/blink/web_tests/external/wpt/resources/webidl2/dist/webidl2.js, line 1, 25411 chars

Found line ending with white spaces in:

***************
third_party/blink/web_tests/external/wpt/resources/webidl2/lib/productions/helpers.js:2
***************
```

The trailing newline is easy to fix: https://github.com/w3c/webidl2.js/pull/329

The single long line I don't know what to do about. @Hexcles WDYT?

If we're only using the build webidl2.js I wonder if there's any use in us still pulling in the whole history of the repo. It still won't be possible to blame code that is actually run, since it's a single line.

**Comment by gsnedders** [comment]
We also don't have the sourcemap working, which is potentially annoying when debugging things, due to the path rewriting… I don't know what the right solution there is.

**Comment by gsnedders** [comment]
> If we're only using the build webidl2.js I wonder if there's any use in us still pulling in the whole history of the repo. It still won't be possible to blame code that is actually run, since it's a single line.

To be fair, we were only ever pulling in a single file.

I think if anything there's a stronger argument now, because we could commit a non-minified built webidl2.js.

**Comment by foolip** [comment]
https://test-results.appspot.com/data/layout_results/linux-rel/102964/webkit_layout_tests%20%28with%20patch%29/layout-test-results/results.html shows all idlharness.js tests now failing because of `Unexpected token {`.

**Comment by gsnedders** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=211118fed274371548638f3d362e94774d71a19c is it run through Mozilla try; lots of `promise_test: Unhandled rejection with value: object "TypeError: obj.toJSON is not a function"` and some:

```
TEST-UNEXPECTED-FAIL | /workers/interfaces.worker.html | interfaces - Error: Syntax error at line 82, since `interface WindowOrWorkerGlobalScope`:
WorkerGlobalScope implements WindowOrWorkerGlobalScope;
^ Unrecognised tokens
```

**Comment by saschanaz** [comment]
I think I fixed `TypeError: obj.toJSON is not a function` but no idea about `unexpected token {`. `implements` is expected to fail, maybe we should remove it first.

**Comment by Hexcles** [comment]
> The single long line I don't know what to do about. @Hexcles WDYT?

I believe that's just a warning and won't block the CL from landing. Nonetheless, I'll look into if I can exclude these third-party files from the check.

**Comment by foolip** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/1636390 updated our lint, thanks @Hexcles!

@saschanaz is `Unexpected token {`an error that webidl2.js might throw, so that we should look for IDL files with some old syntax?

**Comment by saschanaz** [comment]
@foolip webidl2.js throws with the format `Syntax error at line N:\n[[actual IDL lines]]`, so I don't think it's a webidl2 parser error.

**Comment by gsnedders** [comment]
As I said above:

> I think if anything there's a stronger argument now, because we could commit a non-minified built webidl2.js.

Does anyone think this is a good idea, with moving away from subtree? I think @jgraham at least did?

**Comment by foolip** [comment]
When trying to evaluate `function { () }` I get the very same error, so I guess it's a JS parse error then. Does the built webidl2.js depend on some very new JS syntax features?

**Comment by saschanaz** [comment]
@foolip The built library runs without any syntax error on Chrome 74, so I doubt it. If the error is from webidl2.js, it should be from line 1 rather than 3 because the built one has only two lines.

**Comment by saschanaz** [comment]
>Does anyone think this is a good idea, with moving away from subtree?

I think it's good as the full tree is redundant without sourcemap support.

**Comment by saschanaz** [comment]
external/wpt/IndexedDB/idlharness.any.serviceworker.html from https://github.com/web-platform-tests/wpt/pull/16864#issuecomment-496436957 explicitly says `"Uncaught SyntaxError: Unexpected token {", source: https://web-platform.test:8444/resources/WebIDLParser.js (3)`. Not sure the cause though...

**Review by marcoscaceres — DISMISSED** [review]

**Comment by marcoscaceres** [comment]
Probably needs a rebase now.

**Comment by saschanaz** [comment]
@foolip Could you run the tests again? Now it should at least show the problematic line number.

**Comment by foolip** [comment]
@saschanaz I won't be at my workstation until Monday. Perhaps @lukebjerring can give it a try, otherwise I can next week.

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
I've gone through all the regressions on that try run (all fixed by IDL syntax fixes that have landed here but not been synced into m-c, @jgraham), and I'm happy to land this now. I'll give this a day in case anyone disagrees.

**Comment by Ms2ger** [comment]
@saschanaz can you explain how you generated the webidl2.js file?

**Comment by saschanaz** [comment]
@Ms2ger `npx webpack --mode none` on the webidl2.js directory should do the job.

**Comment by saschanaz** [comment]
Filed https://github.com/w3c/webidl2.js/pull/348 to make it straightforward.

**Pull request merged**
