### PR TITLE
Test URL setters on <a> and <area> too

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Review by zcorpan — APPROVED** [review]

**Comment by annevk** [comment]
Ah shit, I think I might have overlooked something. `pathname` tests won't fail because `<a>` and `<area>` have a base URL, whereas `URL` might not. So we'd need to add `<base href=about:blank>` or some such, I think. Thoughts?

**Comment by zcorpan** [comment]
I don't follow. It sets `href` to the test's `href`. Which tests are affected by the base URL here?

**Comment by annevk** [comment]
When you start out with `mailto:...` and then set pathname to `/foo`. There's at least one such test.

**Comment by zcorpan** [comment]
OK. It seems it doesn't affect the test results in Chromium or Gecko though AFAICT.

**Comment by annevk** [comment]
Look for the results of `Setting <mailto:me@example.net>.pathname = '/foo'` and see how they differ between `URL` and `<a>`/`<area>`.

**Comment by annevk** [comment]
Ooh, only affects Firefox Nightly maybe?

**Comment by annevk** [comment]
Arguably that's a bug, even, so maybe this is all good.

**Pull request merged**
