### PR TITLE
Cleanup CORS URL credentials test

### PR DESCRIPTION
**Pull request by annevk**
See #2801.

### CODE REVIEW

**Comment by annevk** [comment]
@youennf with these changes Chrome passes all the test, including my newly added "test the setup" test, but Safari TP fails most. Firefox never completes running the test locally somehow.

Part of the problem of your setup was that you set credentials to "include", but `redirect.py` only used `*` for `Access-Control-Allow-Origin`, so everything would be rejected by that mismatch alone and credentials in the URL would never end up being tested.

Not really sure what to do about Firefox not completing the test run though. @jdm @wanderview ideas?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203722340)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d8bd3d43a2f21d50f4944627219f026f2849f0aa

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203722342)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d8bd3d43a2f21d50f4944627219f026f2849f0aa
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4930/fetch/api/cors/cors-redirect-credentials-worker.html">/fetch/api/cors/cors-redirect-credentials-worker.html</a></summary>


|                               Subtest                               | Results |
|---------------------------------------------------------------------|---------|
|                                                                     | OK      |
| `Redirect 302 from remote to same remote with user`                 | PASS    |
| `Redirect 307 from remote to same origin with password`             | PASS    |
| `Redirect 303 from same origin to remote without user and password` | PASS    |
| `Redirect 302 from remote to another remote with password`          | PASS    |
| `Redirect 301 from remote to same remote with password`             | PASS    |
| `Redirect 307 from remote to same remote with password`             | PASS    |
| `Redirect 307 from same origin to remote with password`             | PASS    |
| `Redirect 308 from same origin to remote without user and password` | PASS    |
| `Redirect 307 from remote to another remote with user and password` | PASS    |
| `Redirect 303 from remote to another remote with password`          | PASS    |
| `Redirect 301 from same origin to remote without user and password` | PASS    |
| `Redirect 308 from remote to same remote with password`             | PASS    |
| `Redirect 307 from remote to same origin with user and password`    | PASS    |
| `Redirect 307 from remote to same origin with user`                 | PASS    |
| `Redirect 308 from remote to same origin with user and password`    | PASS    |
| `Redirect 301 from remote to same remote with user`                 | PASS    |
| `Redirect 303 from remote to same remote with user and password`    | PASS    |
| `Redirect 303 from remote to same remote with user`                 | PASS    |
| `Redirect 307 from same origin to remote without user and password` | PASS    |
| `Redirect 308 from remote to same origin with password`             | PASS    |
| `Redirect 301 from remote to same remote with user and password`    | PASS    |
| `Redirect 301 from remote to another remote with password`          | PASS    |
| `Redirect 308 from remote to same origin with user`                 | PASS    |
| `Redirect 308 from remote to same remote with user`                 | PASS    |
| `Redirect 301 from remote to same origin with user`                 | PASS    |
| `Redirect 307 from remote to same remote with user and password`    | PASS    |
| `Redirect 308 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from same origin to remote with user`                 | PASS    |
| `Redirect 308 from remote to another remote with user and password` | PASS    |
| `Redirect 301 from remote to another remote with user`              | PASS    |
| `Redirect 303 from remote to same origin with password`             | PASS    |
| `Redirect 303 from same origin to remote with user and password`    | PASS    |
| `Redirect 303 from remote to another remote with user`              | PASS    |
| `Redirect 307 from remote to another remote with user`              | PASS    |
| `Redirect 303 from remote to same origin with user and password`    | PASS    |
| `Redirect 302 from remote to same origin with user`                 | PASS    |
| `Redirect 302 from remote to same remote with user and password`    | PASS    |
| `Redirect 301 from same origin to remote with user and password`    | PASS    |
| `Redirect 307 from remote to same remote with user`                 | PASS    |
| `Redirect 301 from same origin to remote with password`             | PASS    |
| `Redirect 308 from same origin to remote with password`             | PASS    |
| `Redirect 301 from remote to same origin with password`             | PASS    |
| `Redirect 307 from same origin to remote with user and password`    | PASS    |
| `Redirect 307 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from same origin to remote with password`             | PASS    |
| `Redirect 303 from remote to another remote with user and password` | PASS    |
| `Redirect 302 from remote to same origin with user and password`    | PASS    |
| `Redirect 302 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from remote to same remote with password`             | PASS    |
| `Redirect 301 from same origin to remote with user`                 | PASS    |
| `Redirect 302 from same origin to remote with password`             | PASS    |
| `Redirect 302 from same origin to remote with user and password`    | PASS    |
| `Redirect 303 from remote to same origin with user`                 | PASS    |
| `Redirect 302 from remote to same remote with password`             | PASS    |
| `Redirect 302 from remote to another remote with user`              | PASS    |
| `Redirect 308 from remote to same remote with user and password`    | PASS    |
| `Redirect 302 from remote to same origin with password`             | PASS    |
| `Redirect 301 from remote to same origin with user and password`    | PASS    |
| `Redirect 301 from remote to another remote with user and password` | PASS    |
| `Redirect 308 from remote to another remote with user`              | PASS    |
| `Redirect 308 from remote to another remote with password`          | PASS    |
| `Redirect 302 from remote to another remote with user and password` | PASS    |
| `Redirect 308 from same origin to remote with user and password`    | PASS    |
| `Redirect 302 from same origin to remote without user and password` | PASS    |
| `Redirect 307 from remote to another remote with password`          | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4930/fetch/api/cors/cors-redirect-credentials.html">/fetch/api/cors/cors-redirect-credentials.html</a></summary>


|                               Subtest                               | Results |
|---------------------------------------------------------------------|---------|
|                                                                     | OK      |
| `Redirect 302 from remote to same remote with user`                 | PASS    |
| `Redirect 307 from remote to same origin with password`             | PASS    |
| `Redirect 303 from same origin to remote without user and password` | PASS    |
| `Redirect 302 from remote to another remote with password`          | PASS    |
| `Redirect 301 from remote to same remote with password`             | PASS    |
| `Redirect 307 from remote to same remote with password`             | PASS    |
| `Redirect 307 from same origin to remote with password`             | PASS    |
| `Redirect 308 from same origin to remote without user and password` | PASS    |
| `Redirect 307 from remote to another remote with user and password` | PASS    |
| `Redirect 303 from remote to another remote with password`          | PASS    |
| `Redirect 301 from same origin to remote without user and password` | PASS    |
| `Redirect 308 from remote to same remote with password`             | PASS    |
| `Redirect 307 from remote to same origin with user and password`    | PASS    |
| `Redirect 307 from remote to same origin with user`                 | PASS    |
| `Redirect 308 from remote to same origin with user and password`    | PASS    |
| `Redirect 301 from remote to same remote with user`                 | PASS    |
| `Redirect 303 from remote to same remote with user and password`    | PASS    |
| `Redirect 303 from remote to same remote with user`                 | PASS    |
| `Redirect 307 from same origin to remote without user and password` | PASS    |
| `Redirect 308 from remote to same origin with password`             | PASS    |
| `Redirect 301 from remote to same remote with user and password`    | PASS    |
| `Redirect 301 from remote to another remote with password`          | PASS    |
| `Redirect 308 from remote to same origin with user`                 | PASS    |
| `Redirect 308 from remote to same remote with user`                 | PASS    |
| `Redirect 301 from remote to same origin with user`                 | PASS    |
| `Redirect 307 from remote to same remote with user and password`    | PASS    |
| `Redirect 308 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from same origin to remote with user`                 | PASS    |
| `Redirect 308 from remote to another remote with user and password` | PASS    |
| `Redirect 301 from remote to another remote with user`              | PASS    |
| `Redirect 303 from remote to same origin with password`             | PASS    |
| `Redirect 303 from same origin to remote with user and password`    | PASS    |
| `Redirect 303 from remote to another remote with user`              | PASS    |
| `Redirect 307 from remote to another remote with user`              | PASS    |
| `Redirect 303 from remote to same origin with user and password`    | PASS    |
| `Redirect 302 from remote to same origin with user`                 | PASS    |
| `Redirect 302 from remote to same remote with user and password`    | PASS    |
| `Redirect 301 from same origin to remote with user and password`    | PASS    |
| `Redirect 307 from remote to same remote with user`                 | PASS    |
| `Redirect 301 from same origin to remote with password`             | PASS    |
| `Redirect 308 from same origin to remote with password`             | PASS    |
| `Redirect 301 from remote to same origin with password`             | PASS    |
| `Redirect 307 from same origin to remote with user and password`    | PASS    |
| `Redirect 307 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from same origin to remote with password`             | PASS    |
| `Redirect 303 from remote to another remote with user and password` | PASS    |
| `Redirect 302 from remote to same origin with user and password`    | PASS    |
| `Redirect 302 from same origin to remote with user`                 | PASS    |
| `Redirect 303 from remote to same remote with password`             | PASS    |
| `Redirect 301 from same origin to remote with user`                 | PASS    |
| `Redirect 302 from same origin to remote with password`             | PASS    |
| `Redirect 302 from same origin to remote with user and password`    | PASS    |
| `Redirect 303 from remote to same origin with user`                 | PASS    |
| `Redirect 302 from remote to same remote with password`             | PASS    |
| `Redirect 302 from remote to another remote with user`              | PASS    |
| `Redirect 308 from remote to same remote with user and password`    | PASS    |
| `Redirect 302 from remote to same origin with password`             | PASS    |
| `Redirect 301 from remote to same origin with user and password`    | PASS    |
| `Redirect 301 from remote to another remote with user and password` | PASS    |
| `Redirect 308 from remote to another remote with user`              | PASS    |
| `Redirect 308 from remote to another remote with password`          | PASS    |
| `Redirect 302 from remote to another remote with user and password` | PASS    |
| `Redirect 308 from same origin to remote with user and password`    | PASS    |
| `Redirect 302 from same origin to remote without user and password` | PASS    |
| `Redirect 307 from remote to another remote with password`          | PASS    |

</details>
</details>

**Comment by annevk** [comment]
Travis ends up failing because of Firefox.

**Comment by annevk** [comment]
@youennf ping.

**Comment by annevk** [comment]
@youennf new ping.

**Comment by youennf** [comment]
Looks good, thanks!
Not sure what is the style for one-liner ifs in WPT (w/o {}).

**Pull request merged**
