### PR TITLE
Improving hyphens-auto-010 files

### PR DESCRIPTION
**Pull request by TalbotG**
User agents may use U+2010 HYPHEN when the font has the glyph, or may use U+002D HYPHEN-MINUS otherwise. Some fonts will display slightly different glyphs for these code points. Therefore several hyphens tests needed to be redesigned to take under consideration this font reality and they needed 2 possible reference files.

Modified tests
hyphens-auto-010.html
{Edited: and
hyphens-none-012.html
hyphens-none-013.html}

New reference files
reference/hyphens-auto-010M-ref.html
reference/hyphens-auto-010H-ref.html

Removed reference file
reference/hyphens-auto-010-ref.html

### CODE REVIEW

**Comment by TalbotG** [comment]
@gsnedders , @foolip 
Sam or Philip: 
Can you tell me why Community-TC (pull_request) => Lint regarding my PR fails? 
What mistake am I doing? 
How do you or how can you actually read an error message when the CI lint check fails?

**Comment by TalbotG** [comment]
Argh! ... I got it!
hyphens-none-012.html
must be modified too!
@gsnedders , @foolip : please, I still wish I could
understand how you actually read an error message when the CI lint check fails?

**Comment by TalbotG** [comment]
Argh...
ERROR:lint:css/css-text/hyphens/hyphens-none-013.html: Reference test with a non-existent 'match' relationship reference: 'reference/hyphens-auto-010-ref.html' (NON-EXISTENT-REF)

Okay, I think I found the answer to my 3 questions now...

**Comment by frivoal** [comment]
The fix for hyphens-auto-010.html looks correct, but for -012 and -013, that doesn't seem necessary… These are not cases of the browser doing any actual hyphenation, just of line breaking, so there should not be any reason to use different characters.

**Comment by TalbotG** [comment]
hyphens-none-012.html test has only 1 reference file.
I can do the same for hyphens-none-013.html . Coming up in a few min.

**Comment by fantasai** [comment]
@TalbotG I think you need to also remove the comment about hyphen variations in 12 and 13. :)

**Review by fantasai — APPROVED** [review]

**Pull request merged**
