### PR TITLE
Encoding: encodeInto()

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/encoding/pull/166.

### CODE REVIEW

**Comment by ricea** [comment]
Looks good. I think this is a good framework to test `encodeInto()`. I haven't actually checked the byte values, I'm assuming they're correct.

**Review by hsivonen — APPROVED** [review]
Looks good to me. Thanks.

To test an edge case that's hard for encoding_rs, it would be good to add a test whose output buffer size is 4 and whose input is an ASCII character followed by a snowman (or other 3-bytes-as-UTF-8 character).

Also: Output buffer size 4 and input contains two 2-bytes-as-UTF-8 characters.

**Comment by inexorabletash** [comment]
Mentioned on the spec PR but:

Needs cases where the destination view is offset/subset of the backing array buffer, e.g. 
```js
const ab = new ArrayBuffer(5);
const view = new Uint8Array(ab, 1, 2);
new TextEncoder().encodeInto("ABCDE", view);
```

**Comment by annevk** [comment]
I've written all the various tests requested thus far, I think, including some additional ones I thought of myself.

**Comment by foolip** [comment]
FYI, I've rebased this branch to trigger "Travis CI - Pull Request", manually setting things right after the travis-ci.com transition in https://github.com/web-platform-tests/wpt/issues/14499 changed the name of the required check, which applies retroactively.

**Comment by annevk** [comment]
Does someone want to review the additions?

**Comment by hsivonen** [comment]
@foolip, the chrome[experimental] and firefox[experimental] tasks started 20 days ago but don't show up as finished.

**Comment by foolip** [comment]
@lukebjerring can you take a look at what's going on with the wpt.fyi checks? I guess this is https://github.com/web-platform-tests/wpt.fyi/issues/950.

**Review by ricea — APPROVED** [review]
I wrote a slow and dumb polyfill. With the change I noted the tests pass.

**Comment by lukebjerring** [comment]
Yep, attempting to update says:
> Could not find runs to compare: no test run found for firefox @ 60bfa1e with label pr_base

**Comment by annevk** [comment]
I plan to land these tomorrow, together with the change to the Encoding Standard.

**Comment by lukebjerring** [comment]
Looks like @Hexcles has succeeded in uploading empty reports :tada: 
Now we can easily see the outcome is `CRASH` in Chrome and `TIMEOUT` in Safari.
https://staging.wpt.fyi/results/?pr=14505

Please fix that before this lands.

**Comment by annevk** [comment]
@lukebjerring can you reproduce it? I can't.

**Pull request merged**
