### PR TITLE
Add OWNERS file to interfaces directory.

### PR DESCRIPTION
**Pull request by tobie**
/cc @yuki3

### CODE REVIEW

**Comment by jensl** [comment]
I assume the content of this directory primarily serve as input for testing via idlharness.js, and is not for reviewing the actual interface definitions?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242753106)

# Firefox (nightly) #
Testing web-platform-tests at revision 334daf45bd664044c28d91a13421039e54be4709
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242753107)

# Sauce (safari) #
Testing web-platform-tests at revision 334daf45bd664044c28d91a13421039e54be4709
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242753113)

# Chrome (unstable) #
Testing web-platform-tests at revision 334daf45bd664044c28d91a13421039e54be4709
Using browser at version 61.0.3128.3 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242753114)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 334daf45bd664044c28d91a13421039e54be4709

**Review by yuki3 — APPROVED** [review]
Thanks for doing this.

**Comment by domenic** [comment]
> I assume the content of this directory primarily serve as input for testing via idlharness.js, and is not for reviewing the actual interface definitions?

Yes, although people also use the file for other IDL-derived tests; see e.g. https://github.com/w3c/web-platform-tests/blob/baae4d2d4787f79e345ce04fdc2a23cd00b6d704/html/webappapis/scripting/events/event-handler-all-global-events.html

I'm not sure if we're really the right owners here, as changes to this directory are mostly about people syncing specs with web-platform-tests, and less about IDL. But I'm OK being here I guess; I can help merge things when people want to do syncs.

**Review by domenic — APPROVED** [review]
LGTM although we should probably get explicit OK from @jensl before adding him.

**Review by jensl — APPROVED** [review]
I may not be the most qualified to review things here, but I don't mind being in the list.

**Pull request merged**
