### PR TITLE
test element with size 0x0 should be notified

### PR DESCRIPTION
**Pull request by cathiechen**
Added a case to test "When first observing an element with ResizeObserver, lastReportedSize gets initialized with a -1 x -1 size", so element with size 0x0 should be notified
https://github.com/w3c/csswg-drafts/issues/3664

### CODE REVIEW

**Review by atotic — APPROVED** [review]
Suggestion: test what happens when observing a hidden Element. 
0,0 initial size meant that observations did not fire on hidden elements.
-1,-1 means that observation will fire even when element is hidden.

**Comment by cathiechen** [comment]
> Suggestion: test what happens when observing a hidden Element. 0,0 initial size meant that observations did not fire on hidden elements. -1,-1 means that observation will fire even when element is hidden.

Done, thanks!

**Comment by atotic** [comment]
I meant we should test both hidden and visible elements, because implementations might differ in how they handle it.

**Comment by cathiechen** [comment]
> I meant we should test both hidden and visible elements, because implementations might differ in how they handle it.

Ah, sorry for misunderstood it! So we test both `display: none` and `width:0px`, right?

**Comment by Loirooriol** [comment]
Isn't this already checked in `resize-observer/observe.html`?
See https://phabricator.services.mozilla.com/D155710#change-QaEcIRm5LhaH

**Comment by Loirooriol** [comment]
OK, so `observe.html` checks non-replaced inline, `svg.html` checks element with an SVG box, and this checks `display: none`. I guess it's fine.

**Comment by cathiechen** [comment]
> Isn't this already checked in `resize-observer/observe.html`? See https://phabricator.services.mozilla.com/D155710#change-QaEcIRm5LhaH

Test16? I think it tests inline elements.

**Comment by Loirooriol** [comment]
Yes, so different cases that end up reporting a 0x0 size. It's fine.

**Pull request merged**
