### PR TITLE
Update interfaces/service-workers.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/1849604/ed/idl/service-workers.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/654545578

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
So it looks like there is no 'standard' idlharness test for service-workers/. Instead I found `service-workers/service-worker/interfaces-window.https.html` and `service-workers/service-worker/interfaces-sw.https.html`, which partially re-implement some of this, especially in the latter case. It relies on `service-workers/service-worker/resources/interfaces-worker.sub.js, which seems to test `FetchEvents` manually and thus won't pick up any changes to the idl file I think...

@foolip looks like LukeB originally added these; do you know if they just predate modern IDL harness test styles, or was there a reason they are special?

**Comment by foolip** [comment]
@stephenmcgruer `service-workers/service-worker/resources/interfaces-worker.sub.js` does indeed predate `idl_test`, and the reason it hasn't been converted is that the test also tests some other stuff, like constructors. I'll send a PR to add plain idlharness.js tess and see about trimming the other tests to what isn't covered by that.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/22116 but it needs more work. @stephenmcgruer feel free to take it over if you want to :)

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/22116 landed so I'll land this too now.

**Review by foolip — APPROVED** [review]

**Pull request merged**
