### PR TITLE
Revert "Fix the bug that typing in a sticky box scrolls the page unexpectedly."

### PR DESCRIPTION
**Pull request by jeffcarp**
This reverts commit d68795e04b109af32e22118dc1570ee38793ded3 because @jeffcarp mistakenly merged #6575.

The downstream CL ceased having any exportable changes, however the PR was
left around without being closed (see crbug.com/750942).

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260430538)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260430539)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260430546)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260430547)

# Sauce (MicrosoftEdge) #

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
