### PR TITLE
Fix PNG cICP chunk test

### PR DESCRIPTION
**Pull request by ProgramMax**
The PNG cICP test references an image. But it uses an incorrect path to that image. This causes the test harness to fail.

This commit fixes the image path, restoring the PNG cICP test.

### CODE REVIEW

**Comment by ProgramMax** [comment]
I see 4 test bots failing. But looking at their logs, it seems like they are failing for a reason unrelated to this change.

This change works as expected on my local machine. Chrome passes. Firefox fails. But the test fails as expected. It isn't a test harness failure.

Is there a way to re-run the bots?

**Comment by svgeesus** [comment]
Rather than go up a directory, I would put the image in a new support directory. I would also re-name the image to something more specific, like `cicp-display-p3.png` because we will hopefully have more than one such test.

**Comment by ProgramMax** [comment]
By support directory, do you mean a subdirectory within png/ ?
IE not wpt/support/cicp-display-p3.png but wpt/png/support/cicp-display-p3.png

**Review by svgeesus — APPROVED** [review]
LGTM

**Pull request merged**
