### PR TITLE
[WIP] Debugging failing test on Azure

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See e.g.
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=44791&view=results

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Hrm, so `tools/wpt/ tests: macOS` ran but passed here (the failures are unrelated hypothesis test problems), which implies that this is either flaky or only reproduces under certain circumstances.

**Comment by stephenmcgruer** [comment]
Passed on a second run too (annoying...). Next steps: I'm going to trawl recent runs and look for things that failed with this error. If it's particularly rare may just need to land a logging PR to try and catch it in the wild.

**Comment by LukeZielinski** [comment]
Looks like TaskCluster didn't run here, retrying.

**Comment by stephenmcgruer** [comment]
@LukeZielinski this is a draft PR, TC shouldn't run.

**Pull request closed without merging**
