### PR TITLE
Added 7 new CSS4Pseudo tests and 7 references

### PR DESCRIPTION
**Pull request by TalbotG**
selection-contenteditable-011.html 
selection-contenteditable-011-ref.html 
selection-input-011.html 
selection-input-011-ref.html 
selection-intercharacter-011.html 
selection-intercharacter-011-ref.html 
selection-intercharacter-012.html 
selection-intercharacter-012-ref.html 
selection-overlay-and-grammar-001.html 
selection-overlay-and-grammar-001-ref.html 
selection-overlay-and-spelling-001.html 
selection-overlay-and-spelling-001-ref.html 
selection-textarea-011.html 
selection-textarea-011-ref.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
Overall, same comment as before: probably easier to understand “Selected Text” rather than “Text Sample”.

selection-input-011
selection-textarea-011

These two seem to need some changes to the scripting to actually select the text inside the form field.

selection-intercharacter-011
selection-intercharacter-012

These look correct to me. rel=help should include a link to letter-spacing spec, since this is testing the interaction.

selection-overlay-and-grammar-001
selection-overlay-and-spelling-001

These tests are currently passing in UAs that don't support ::spelling-error or ::grammar-error. Let's make them a bit more rigorous by adding some text decoration, e.g. `::spelling-error { text-decoration: underline }`. This will make sure they fail in UAs that don't support these features.

I would also suggest checking background color layering here, using a 50% transparent selection background color.

**Comment by TalbotG** [comment]
> Overall, same comment as before: probably easier to understand “Selected Text” rather than “Text Sample”.

Done in all tests, except in the selection-textarea-011 test.

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-contenteditable-011-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-contenteditable-011-ref-new.html
 
> selection-input-011
> selection-textarea-011
> 
> These two seem to need some changes to the scripting to actually select the text inside the form field.

Done:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-input-011-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-input-011-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-textarea-011-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-textarea-011-ref-new.html


> selection-intercharacter-011
> selection-intercharacter-012
> 
> rel=help should include a link to letter-spacing spec
 
Done:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-intercharacter-011-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-intercharacter-011-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-intercharacter-012-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-intercharacter-012-ref-new.html

> selection-overlay-and-grammar-001
> selection-overlay-and-spelling-001
> 
> These tests are currently passing in UAs that don't support ::spelling-error or ::grammar-error. Let's make them a bit more rigorous by adding some text decoration, e.g. `::spelling-error { text-decoration: underline }`. This will make sure they fail in UAs that don't support these features.

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-grammar-001-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-grammar-001-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-spelling-001-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-spelling-001-ref-new.html

> I would also suggest checking background color layering here, using a 50% transparent selection background color.

I have added a semi-transparent yellow background color to ::selection pseudo-element to the 2 tests.

**Review by fantasai — CHANGES_REQUESTED** [review]
Looks good overall, just an issue on the overlay tests:

- We can't check layering if we only have one layer, so in order to check layering, we need a (solid) background color for ::spelling-error/::grammar-error as well as for ::selection. Does this make sense?

- Technically, we don't know the extent of the background area for text highlights, so simulating them with inline element backgrounds might not create an exact reftest match. I'm not sure what to do about this, but maybe put a comment in the source about this, suggesting that an implementation which is correct but fails the test due to such a mismatch should suggest changes to the test?

**Comment by TalbotG** [comment]
> Looks good overall, just an issue on the overlay tests:
> 
>  * We can't check layering if we only have one layer,
so in order to check layering, we need a (solid) background color for ::spelling-error/::grammar-error 
as well as for ::selection. 

I understand the need for background color for ::spelling-error/::grammar-error as well as for selection. 
When you say **solid** background, do you mean fully opaque background? If we use a fully opaque background for ::selection, then why should we see the underline of ::spelling-error/::grammar-error? Won't (shouldn't) a fully opaque background for ::selection mask, overlap the underline from the layer below?

Also, I am now confused... the test currently says we should see the underline, but then such underline should also be red because "The color property specifies the color of both the text and all line decorations (underline, overline, line-through)" . So, I now think the test was not completely clear or correct...because "not red" is emboldened in the pass-conditions sentence and a red underline was below, under a semi-transparent yellow layer.

**Comment by fantasai** [comment]
> When you say solid background, do you mean fully opaque background?

Yes.

> If we use a fully opaque background for ::selection, then why should we see the underline of ::spelling-error/::grammar-error? Won't (shouldn't) a fully opaque background for ::selection mask, overlap the underline from the layer below?

No, the text *and its decorations* are drawn over the highlight backgrounds (all of them). See https://drafts.csswg.org/css-pseudo-4/#highlight-painting

> the test currently says we should see the underline, but then such underline should also be red

Hm, you're right. Maybe checking that text-decoration shows through should be a separate test. For this one, probably if you at least have a solid background on ::spelling-error underneath the semi-transparent highlight, that will at least prove the background layering, and it will distinguish it from not supporting ::spelling-error.

**Comment by TalbotG** [comment]
> Technically, we don't know the extent of the background area for text highlights, so simulating them with inline element backgrounds might not create an exact reftest match.

I can style the div with `float: left` instead. Wouldn't that suffice/succeed?

**Comment by TalbotG** [comment]
@fantasai,

I will 
1- remove the overlay ( selection-overlay-and-grammar-001.html selection-overlay-and-grammar-001-ref.html selection-overlay-and-spelling-001.html selection-overlay-and-spelling-001-ref.html ) from this PR
2- then submit the other tests
3- and finally create another PR for the overlay tests

**Comment by TalbotG** [comment]
@web-platform-tests/admins , Stephen McGruer or jgraham ,

2 hours ago, I created a commit (9a03c60...)  and the continuous integration checks are still going on: "1 expected, 1 pending, and 18 successful checks" .
"
wpt-decision-task Expected — Waiting for status to be reported
Community-TC (pull_request) Pending — TaskGroup: Pending
" 

What can I do here? Close this PR and create another one?

**Comment by stephenmcgruer** [comment]
> What can I do here? Close this PR and create another one?

Looks like this is an old PR (first created 31st October, and the parent commit is ~3000 commits behind WPT master) so is using the old TC config.

If you're comfortable [rebasing the PR](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to wpt's HEAD, you can do that yourself. If not, then creating a new PR (from an up-to-date branch of wpt) with the same content would also work.

You've run into this a few times - do you have a large number of outstanding pull requests from older branches? If so, maybe we should put aside some time to work together to fix them up.

**Comment by TalbotG** [comment]
Hello Stephen McGruer ,

> If you're comfortable rebasing the PR (see this guide or this guide) to wpt's HEAD, you can do that yourself. If not, then creating a new PR (from an up-to-date branch of wpt) with the same content would also work.

I will create a new PR.

> You've run into this a few times - do you have a large number of outstanding pull requests from older branches?

Yes, I have 10 pull requests from older branches:

https://github.com/web-platform-tests/wpt/pull/18215 July 31st 2019
https://github.com/web-platform-tests/wpt/pull/21450 January 27th 2020
https://github.com/web-platform-tests/wpt/pull/21862 February 18th 2020
https://github.com/web-platform-tests/wpt/pull/21928 February 22nd 2020
https://github.com/web-platform-tests/wpt/pull/22201 March 11th 2020
https://github.com/web-platform-tests/wpt/pull/23627 May 14th 2020
https://github.com/web-platform-tests/wpt/pull/23658 May 16th 2020
https://github.com/web-platform-tests/wpt/pull/23660 May 16th 2020
https://github.com/web-platform-tests/wpt/pull/23808 May 27th 2020
https://github.com/web-platform-tests/wpt/pull/23814 May 27th 2020
and I also have been asked to work on a PR that I did not create... 
which was 2 years old, I think, from Chris Nardi about border-image 
I think...

> old TC config

When did the new TC config start? Just curious...

> If so, maybe we should put aside some time to work together to fix them up.

The thing is I need to be ready to resubmit them and I am not .. but this one, 20032, I was yesterday. I wanted to start with the oldest one.

Stephen, I want to thank you for replying and giving me some explanation. I will just create a new PR for each of the old 10 PRs that I have right now. It is not a big thing.
I am moving on. :)

Closing this PR.

**Comment by stephenmcgruer** [comment]
> When did the new TC config start? Just curious...

July 7th; see https://github.com/web-platform-tests/wpt/issues/14846#issuecomment-644183897 and https://github.com/web-platform-tests/wpt/pull/24151

> Stephen, I want to thank you for replying and giving me some explanation. I will just create a new PR for each of the old 10 PRs that I have right now. It is not a big thing.
> I am moving on. :)

No problem, thanks for being understanding of the situation and sorry again for the inconvenience.

**Pull request closed without merging**
