### PR TITLE
[css-text] Inheritance and initial values

### PR DESCRIPTION
**Pull request by ewilligers**
Test that CSS Text properties inherit.
Test that they have the initial values given in the spec.
https://drafts.csswg.org/css-text/#propdef-white-space

### CODE REVIEW

**Comment by foolip** [comment]
The failing Travis build in this PR was due to https://github.com/web-platform-tests/wpt/issues/13112, which has now been resolved. To recover, rebase the PR on master and push. (Simply restarting the Travis jobs may also work, not tested.)

**Comment by ewilligers** [comment]
@frivoal   Please review

**Review by foolip — APPROVED** [review]
Brief review LGTM

**Comment by frivoal** [comment]
LGTM too.

**Pull request merged**
