### PR TITLE
Fix font paths after #9718

### PR DESCRIPTION
**Pull request by gsnedders**
I broke these in a fixup and didn't notice.

### CODE REVIEW

**Comment by gsnedders** [comment]
Oh wait maybe there was a reason why preload had them separately, and that was caching? I remember @yoavweiss saying something about that ages ago?

**Review by mrego — APPROVED** [review]

**Comment by mrego** [comment]
> Oh wait maybe there was a reason why preload had them separately, and that was caching? I remember @yoavweiss saying something about that ages ago?

If we cannot have them in `/fonts/` we need to copy `CanvasTest.ttf` and `CanvasTest.ttf.sub.headers` back to its folder.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Firefox Nightly"<small></small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/25445.4">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/350296916">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  
  
  
  
  <tr>
    <td><code>/preload/download-resources.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Makes sure that preloaded resources are downloaded</code></td>
    <td>PASS: 8<br />FAIL: 2<br /></td>
    <td><code>assert_equals: resources/foo.vtt expected 1 but got 0</code><br /><code>assert_equals: /fonts/CanvasTest.ttf expected 1 but got 0</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td><code>/preload/onload-event.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Makes sure that preloaded resources trigger the onload event</code></td>
    <td>PASS: 9<br />FAIL: 1<br /></td>
    <td><code>assert_true: style triggered load event expected true got false</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  </table>

**Comment by gsnedders** [comment]
@jgraham I can't reproduce any flakiness locally, either on this branch or before #9718.

**Comment by jgraham** [comment]
This  seems to reliably pass locally for me as well. I guess we'll find out if this actually did cause a problem.

**Pull request merged**
