### PR TITLE
Add ECMAScript 6 Modules test cases from Microsoft Edge

### PR DESCRIPTION
**Pull request by AtOMiCNebula**
Microsoft Edge's current set of tests for an ECMAScript6 Modules implementation via the script element (<script type="module">).

### CODE REVIEW

**Comment by AtOMiCNebula** [comment]
This is a rebased MicrosoftEdge#18, to side-step some housekeeping work that is apparently needed in our own clone.

cc @thejohnjansen @domenic

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 171a94614c00e8731b971f3be03a4d8a33694962
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/errorhandling.html">/html/semantics/scripting-1/the-script-element/module/errorhandling.html</a></summary>


|                       Subtest                        | Results |
|------------------------------------------------------|---------|
|                                                      | TIMEOUT |
| `External root module with non-script mimetype`      | NOTRUN  |
| `IFrame test: 'iframe_parseError_DependentMultiple'` | FAIL    |
| `IFrame test: 'iframe_parseError_Root'`              | FAIL    |
| `Module with imported non-script mimetype`           | NOTRUN  |
| `IFrame test: 'iframe_parseError_Dependent'`         | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/imports.html">/html/semantics/scripting-1/the-script-element/module/imports.html</a></summary>


|                       Subtest                       | Results |
|-----------------------------------------------------|---------|
|                                                     | TIMEOUT |
| `Import a module with a cyclical module dependency` | NOTRUN  |
| `Import a module that tries to import itself`       | NOTRUN  |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/crossorigin.html">/html/semantics/scripting-1/the-script-element/module/crossorigin.html</a></summary>


|                                 Subtest                                 | Results |
|-------------------------------------------------------------------------|---------|
|                                                                         | OK      |
| `Imported module, Error in CORS-same-origin script`                     | FAIL    |
| `Imported module, Blocked script download, missing CORS ACAO header`    | FAIL    |
| `Imported module, Blocked script download, mismatched CORS ACAO header` | FAIL    |
| `Root module, Error in CORS-different-origin script`                    | FAIL    |
| `Root module, Error in CORS-same-origin script`                         | FAIL    |
| `Root module, Blocked script download, missing CORS ACAO header`        | FAIL    |
| `Imported module, Error in CORS-different-origin script`                | FAIL    |
| `Root module, Blocked script download, mismatched CORS ACAO header`     | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/execorder.html">/html/semantics/scripting-1/the-script-element/module/execorder.html</a></summary>


|                                 Subtest                                  | Results |
|--------------------------------------------------------------------------|---------|
|                                                                          | TIMEOUT |
| `Unordered module script execution (parsed, unordered #1)`               | NOTRUN  |
| `Unordered module script execution (dynamic, unordered #1)`              | NOTRUN  |
| `Interlaced module/non-module script execution (parsed, async-ordered)`  | FAIL    |
| `Unordered module script execution (parsed, unordered #2)`               | NOTRUN  |
| `Interlaced module/non-module script execution (dynamic, async-ordered)` | FAIL    |
| `Unordered module script execution (dynamic, unordered #2)`              | NOTRUN  |

</details>
</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 171a94614c00e8731b971f3be03a4d8a33694962
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/errorhandling.html">/html/semantics/scripting-1/the-script-element/module/errorhandling.html</a></summary>


|                       Subtest                        | Results |
|------------------------------------------------------|---------|
|                                                      | TIMEOUT |
| `External root module with non-script mimetype`      | NOTRUN  |
| `IFrame test: 'iframe_parseError_DependentMultiple'` | FAIL    |
| `IFrame test: 'iframe_parseError_Root'`              | FAIL    |
| `Module with imported non-script mimetype`           | NOTRUN  |
| `IFrame test: 'iframe_parseError_Dependent'`         | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/imports.html">/html/semantics/scripting-1/the-script-element/module/imports.html</a></summary>


|                       Subtest                       | Results |
|-----------------------------------------------------|---------|
|                                                     | TIMEOUT |
| `Import a module with a cyclical module dependency` | NOTRUN  |
| `Import a module that tries to import itself`       | NOTRUN  |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/crossorigin.html">/html/semantics/scripting-1/the-script-element/module/crossorigin.html</a></summary>


|                                 Subtest                                 | Results |
|-------------------------------------------------------------------------|---------|
|                                                                         | OK      |
| `Imported module, Error in CORS-same-origin script`                     | FAIL    |
| `Imported module, Blocked script download, missing CORS ACAO header`    | FAIL    |
| `Imported module, Blocked script download, mismatched CORS ACAO header` | FAIL    |
| `Root module, Error in CORS-different-origin script`                    | FAIL    |
| `Root module, Error in CORS-same-origin script`                         | FAIL    |
| `Root module, Blocked script download, missing CORS ACAO header`        | FAIL    |
| `Imported module, Error in CORS-different-origin script`                | FAIL    |
| `Root module, Blocked script download, mismatched CORS ACAO header`     | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4876/html/semantics/scripting-1/the-script-element/module/execorder.html">/html/semantics/scripting-1/the-script-element/module/execorder.html</a></summary>


|                                 Subtest                                  | Results |
|--------------------------------------------------------------------------|---------|
|                                                                          | TIMEOUT |
| `Unordered module script execution (parsed, unordered #1)`               | NOTRUN  |
| `Unordered module script execution (dynamic, unordered #1)`              | NOTRUN  |
| `Interlaced module/non-module script execution (parsed, async-ordered)`  | FAIL    |
| `Unordered module script execution (parsed, unordered #2)`               | NOTRUN  |
| `Interlaced module/non-module script execution (dynamic, async-ordered)` | FAIL    |
| `Unordered module script execution (dynamic, unordered #2)`              | NOTRUN  |

</details>
</details>

**Comment by domenic** [comment]
Thanks so much @AtOMiCNebula!!

**Pull request merged**
