### PR TITLE
Correct serialization of counter()

### PR DESCRIPTION
**Pull request by csnardi**
As discussed in https://github.com/w3c/csswg-drafts/issues/670, the spec states that if the "the last CSS component value if it is "decimal"", it should be omitted when serializing. Correct the test to match the spec.

Fixes https://github.com/w3c/csswg-drafts/issues/670.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-06 01:24:33
Finished: 2018-03-06 01:32:50


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>build_css</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25330)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349544387)

**Review by emilio — APPROVED** [review]
Probably worth also testing `{ actual: 'counter(par-num, decimal)', serialized: 'counter(par-num)' }`?

**Comment by emilio** [comment]
Let me know if you want to adjust the test to also test that case, otherwise looks fine to merge as-is to me.

**Comment by csnardi** [comment]
@emilio Easy enough to add, should be good to merge now.

**Comment by emilio** [comment]
Thanks!

**Comment by emilio** [comment]
https://github.com/servo/servo/pull/20224 is the Firefox / Servo fix.

**Pull request merged**
