### PR TITLE
XMLHttpRequest: overrideMimeType and Blob objects

### PR DESCRIPTION
**Pull request by annevk**
More tests for https://github.com/whatwg/xhr/issues/82.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204550099)

# Firefox (nightly channel) #
Testing web-platform-tests at revision f8e8f1596bf7308b5da2407bbe37d12c85453487
Using browser at version BuildID 20170222110216; SourceStamp 9a9db410f20781076424307265decbc5de1e94cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4993/XMLHttpRequest/overridemimetype-blob.html">/XMLHttpRequest/overridemimetype-blob.html</a></summary>


|                            Subtest                             | Results |                                              Messages                                             |
|----------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------|
|                                                                | OK      |                                                                                                   |
| `Use text/xml as fallback MIME type`                           | FAIL    | `assert_equals: expected "text/xml" but got "application/xml"`                                    |
| `Use text/xml as fallback MIME type, 2`                        | FAIL    | `assert_equals: expected "text/xml" but got "application/xml"`                                    |
| `Bogus MIME type should end up as application/octet-stream`    | FAIL    | `assert_equals: expected "application/octet-stream" but got "application/x-unknown-content-type"` |
| `Bogus MIME type should end up as application/octet-stream, 2` | FAIL    | `assert_equals: expected "application/octet-stream" but got "text/xml"`                           |
| `Valid MIME types need to be normalized`                       | PASS    |                                                                                                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204550102)

# Chrome (unstable channel) #
Testing web-platform-tests at revision f8e8f1596bf7308b5da2407bbe37d12c85453487
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4993/XMLHttpRequest/overridemimetype-blob.html">/XMLHttpRequest/overridemimetype-blob.html</a></summary>


|                            Subtest                             | Results |                          Messages                         |
|----------------------------------------------------------------|---------|-----------------------------------------------------------|
|                                                                | OK      |                                                           |
| `Use text/xml as fallback MIME type`                           | FAIL    | `assert_equals: expected "text/xml" but got ""`           |
| `Use text/xml as fallback MIME type, 2`                        | PASS    |                                                           |
| `Bogus MIME type should end up as application/octet-stream`    | FAIL    | `assert_equals: expected "" but got "bogus"`              |
| `Bogus MIME type should end up as application/octet-stream, 2` | FAIL    | `assert_equals: expected "" but got "text/xml;charset=†"` |
| `Valid MIME types need to be normalized`                       | FAIL    | `assert_equals: expected "" but got "HI/x;test"`          |

</details>
</details>

**Review by foolip — APPROVED** [review]
A lot of failing here, but also failing in different ways, so I'll trust that this is what makes sense without looking closer at the spec issue/PR.

**Comment by foolip** [comment]
(Yes, I did actually read the tests, but they were flawless.)

**Comment by annevk** [comment]
Thanks, trying to make the most of a bad situation. Browser bugs will be filed and then hopefully that will result in convergence.

**Comment by foolip** [comment]
Thanks for cleaning up *this* particular mess :)

**Pull request merged**
