### PR TITLE
[Azure Pipelines] Upgrade macOS VMs to Mojave

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I opened https://github.com/web-platform-tests/wpt/pull/17217 to be able to see if any failures are pre-existing. I'll also push that commit to this branch to this PR to see if everything passes. Additionally, I'll trigger a full run of the same type as runs every 6 hours.

**Comment by foolip** [comment]
The manual build is https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18422.

**Review by gsnedders — APPROVED** [review]

**Comment by foolip** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=266520006&run_id=242570013 compares results from 10.13 and 10.14. Looks OK except for a huge regression in css-grid results. The exact same commit wasn't tested, so I'll try again after the next Safari TP run on master.

**Comment by gsnedders** [comment]
FWIW, those grid results match what I get locally in STP 84.

**Comment by foolip** [comment]
New build on top of commit 38bf3be2f0 in progress:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18475

Sent https://github.com/web-platform-tests/wpt/pull/17225 to be able to do the same for stable.

**Comment by foolip** [comment]
I've rebased and triggered new full runs of both Safaris:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18765
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18766

**Comment by foolip** [comment]
Diff of results compared to the parent commit for those runs:
https://wpt.fyi/results/?diff&filter=ADC&run_id=255090001&run_id=242660007
https://wpt.fyi/results/?diff&filter=ADC&run_id=252540003&run_id=260590004

**Comment by foolip** [comment]
Aha! For both Safaris /infrastructure/assumptions/ahem.html is failing because Ahem appears to not be loaded. This is also the cause of some other failures such as /css/CSS2/text/letter-spacing-004.xht.

Rather than debugging system font installation on Mojave I'll wait for https://github.com/web-platform-tests/rfcs/pull/22 to be resolved, we're pinned to Safari TP 82 anyway so there's no urgency to upgrade.

**Comment by gsnedders** [comment]
Pretty sure 10.14 is the point at which they stopped loading non-system fonts (by default?).

`com.apple.Safari.ContentPageGroupIdentifier.WebKit2ShouldAllowUserInstalledFonts` is the pref to configure it, but I think changing that requires disabling the sandboxing?

**Comment by foolip** [comment]
Oh, I didn't know that changes was coming / has come. Good thing that we went ahead with the Ahem change then! I won't try the setting to get the old behavior, @LukeZielinski's work on Ahem will probably resolve this in a matter of weeks anyway.

**Comment by foolip** [comment]
Since #17173 was merged yesterday I've rebased and triggered another full run of the Safaris to see if the differences are fewer now:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18914

**Comment by foolip** [comment]
New diffs:
https://wpt.fyi/results/?diff&filter=ADC&run_id=255120001&run_id=240740006
https://wpt.fyi/results/?diff&filter=ADC&run_id=231010007&run_id=252590016

First looks about the same, but results for Safari TP seem incomplete :(

**Comment by gsnedders** [comment]
A bunch of the regressions in CSS are just more things needed Ahem

**Comment by foolip** [comment]
It looks like "all tests (Safari Technology Preview) 1" in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18914 silently failed to run all of the tests it should have run. Comparing it to https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18874 where the last test was in /xhr/, that job stopped at  /payment-request/payment-is-showing.https.html:
```
  ▶ ERROR [expected OK] /payment-request/payment-is-showing.https.html
  └   → Traceback (most recent call last):
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 282, in _run
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 373, in do_testharness
    done, rv = handler(result)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 604, in __call__
    return callback(url, payload)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 622, in process_action
    self._send_message("complete", "error")
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 631, in _send_message
    self.protocol.testdriver.send_message(message_type, status, message=message)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 189, in send_message
    self.webdriver.execute_script("window.postMessage(%s, '*')" % json.dumps(obj))
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/webdriver/webdriver/client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/webdriver/webdriver/client.py", line 631, in execute_script
    return self.send_session_command("POST", "execute/sync", body)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/webdriver/webdriver/client.py", line 508, in send_session_command
    return self.send_command(method, url, body)
  File "/Users/vsts/agent/2.152.1/work/1/s/tools/webdriver/webdriver/client.py", line 472, in send_command
    raise err
InvalidSessionIdException: invalid session id (404): 



##[section]Finishing: Run tests
```

@gsnedders is "invalid session id" something from SafariDriver? Is this another case of https://github.com/web-platform-tests/wpt/issues/13073?

**Comment by gsnedders** [comment]
@foolip that should be recoverable; the irrecoverable error should be when we repeatedly fail to restart.

**Comment by gsnedders** [comment]
(Needs a rebase to pass CI, due to #17286. Sorry!)

**Comment by foolip** [comment]
@gsnedders is there a bug for making this case restart properly? We could potentially be getting bad runs already because of this.

**Comment by gsnedders** [comment]
@foolip we should already handle this; I think we really need logs with debug info in them to figure out what's going on (i.e., `--log-mach - --log-mach-level debug`).

**Comment by foolip** [comment]
@gsnedders what more might verbose logging reveal? The problem ought to be that an error is thrown but never catched, would more verbose logs provide more clues?

**Comment by gsnedders** [comment]
@foolip It would reveal if we're trying to restart and failing, for example.

**Comment by gsnedders** [comment]
@foolip And as far as I can tell, it *is* being caught (`executorwebdriver.py` catches it at the top of the stack, and sets the result to ERROR, which seems like the only sensible behaviour given that error), we just aren't restarting afterwards.

**Comment by foolip** [comment]
@gsnedders do you think we should enable verbose mach logging on all builds, or just on this PR? There's no guarantee that the problem will reproduce on the next run, so I don't what we'd concluded if everything looks good.

**Comment by gsnedders** [comment]
@foolip We do on Taskcluster, don't we? I feel like having the same logging mode enabled in both CI systems makes sense. TC seems to be `--log-tbpl-level=info --log-tbpl=-`, which would almost certainly be enough?

**Comment by foolip** [comment]
More verbose logging in https://github.com/web-platform-tests/wpt/pull/17379.

**Comment by foolip** [comment]
@LukeZielinski I've left this idle waiting for the Ahem changes to land. How many tests would still be affected if we don't support Ahem as a system font now? If it's only a handful of tests I think it's fine to land this upgrade?

**Comment by foolip** [comment]
I've started full runs in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=27332 to compare the results against the current ones.

**Comment by foolip** [comment]
The results are in:
- [Diff of Safari 12.1.2 (13607.3.10) on High Sierra and 12.1.2 (14607.3.9) on Mojave](https://wpt.fyi/results/?diff&filter=ADC&run_id=274960001&run_id=280900008): 1779 subtests regressed if you search `seq(status:pass status:!pass)`
- [Diff of Safari 82 preview on High Sierra and Mojave](https://wpt.fyi/results/?diff&filter=ADC&run_id=271190001&run_id=284730004): 2187 subtests regressed if you search `seq(status:pass status:!pass)`
- [All four combined and filtered to High Sierra &rarr; Mojave regressions](https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%20status%3Apass%20status%3A%21pass%29&run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004): 1672 subtests regressed ([wpt.fyi URL bug](https://github.com/web-platform-tests/wpt.fyi/issues/1418))

The first two diffs are noisier, probably due to flakiness, but don't point to any large regressions other than those that are shared. The difference between 1779 and 2187 subtests seems to be explained mostly be different numbers of tests having run in [/css/css-grid/abspos/](https://wpt.fyi/results/css/css-grid/abspos?run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004).

In the shared regressions, we have:
- [/cookies/](https://wpt.fyi/results/cookies?q=seq%28status%3Apass%20status%3A%21pass%20status%3Apass%20status%3A%21pass%29&run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004), something about SameSite=None seems to have changed between 10.13 and 10.14. I see no reason to suspect an infra issue here.
- [/css/](https://wpt.fyi/results/css?q=seq%28status%3Apass%20status%3A%21pass%20status%3Apass%20status%3A%21pass%29&run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004), this is most of the regressions numerically. Breakdown below.
- [/infrastructure/assumptions/ahem.html](https://wpt.fyi/results/infrastructure/assumptions/ahem.html?run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004), as expected
- [/quirks/table-cell-width-calculation-abspos.html](https://wpt.fyi/results/quirks/table-cell-width-calculation-abspos.html?run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004)

In /css/:
- Some of the same tests in https://github.com/web-platform-tests/wpt/pull/17205 that regress due to Ahem not being available, but they are so few that I don't think they need block the upgrade to Mojave.
- Some tests now failing due to minor font rendering differences. We see this in Chrome as well and it's not a high priority type of failure.

[/css/css-values/ex-unit-001.html](https://wpt.fyi/results/css/css-values/ex-unit-001.html?run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004) is actually due to Ahem. [ex-unit-001.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-values/ex-unit-001.html) hasn't been updated to use Ahem as a web font, and the "It doesn't really matter if Arial is not found" is wrong, as the result has to match the ref which does use Ahem. @LukeZielinski was this test missed by your greping?

**Comment by foolip** [comment]
**The good stuff**: still in /css/, there are a lot of testharness.js tests that use Ahem and have regressed. At least css-exclusions, css-grid, css-multicol and css-shapes have tests that are like this, and this where numerically almost all of the regressions are.

@LukeZielinski I think the problem here is that testharness.js tests depending on Ahem either don't wait for the font to be loaded at all, or do `document.fonts.ready.then(...)` too early, before the first layout when the font was found to be needed and it began loading.

Reftests don't have this issue because they [wait for the load event](https://github.com/web-platform-tests/wpt/blob/6c14d36f4ec7979c459a9636a9c086cc486d43da/tools/wptrunner/wptrunner/executors/reftest-wait_webdriver.js) before waiting for the `document.fonts.ready` promise.

Is this a problem you've seen in Chrome as well? Do we need a better helper for testharness.js tests using Ahem, something that would let them wait for Ahem as a one-liner?

**Comment by foolip** [comment]
Okay... so with /css/css-grid/grid-layout-properties.html I found that the problem isn't that `document.font.size` is zero when we start waiting for the `document.font.ready` promise, but that adding a `requestAnimationFrame` after the promise resolves fixes the problem. Reftets already have a double rAF:
https://github.com/web-platform-tests/wpt/blob/6c14d36f4ec7979c459a9636a9c086cc486d43da/tools/wptrunner/wptrunner/executors/reftest-wait_webdriver.js#L28-L32

But, Chrome and Firefox don't need any extra rAF after the `document.fonts.ready` promise resolves, not for this testharness.js test at least. AFAICT, https://drafts.csswg.org/css-font-loading/#font-face-css-connection doesn't define `document.fonts.ready` in enough detail to say that Safari is wrong here.

**Comment by foolip** [comment]
No, actually, https://drafts.csswg.org/css-font-loading/#fontfaceset-pending-on-the-environment has "the document has pending layout operations which might cause the user agent to request a font, or which depend on recently-loaded fonts" as one of the conditions, so I think Safari is wrong then. I'll try to make a smaller test demonstrating this.

**Comment by foolip** [comment]
I've sent a minimized test in https://github.com/web-platform-tests/wpt/pull/18489. However, I think it'll pass in Safari on 10.13 where we still have the system font installed.

**Comment by foolip** [comment]
I think https://bugs.webkit.org/show_bug.cgi?id=174030 is the right WebKit bug for this, commented there.

**Comment by foolip** [comment]
https://bugs.webkit.org/show_bug.cgi?id=174030 has been fixed, but upgrading is still not possible. It's likely going to be necessary to upgrade both the OS and STP at the same time as I've attempted in https://github.com/web-platform-tests/wpt/pull/18925 but still isn't working. This PR won't be merged at any rate, so I'm closing it.

Will try to summarize the state of things in https://github.com/web-platform-tests/wpt/issues/17186.

**Pull request closed without merging**
