### PR TITLE
URL IDNA: Nontransitional_Processing

### PR DESCRIPTION
**Pull request by annevk**
Tests for https://github.com/whatwg/url/issues/239.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision b8678e0d1b745e3c620558f2dad7391418449272
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision b8678e0d1b745e3c620558f2dad7391418449272
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations

**Comment by sideshowbarker** [comment]
Travis failing with:

```
  File "/home/travis/build/w3c/web-platform-tests/tools/sslutils/openssl.py", line 65, in __call__
    env[k.encode("utf8")] = v.encode("utf8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

**Comment by annevk** [comment]
Aah. I think because of my branch name things are failing apart. @jgraham @jugglinmike is this something you can fix?

**Comment by jugglinmike** [comment]
Yes, the error *is* related to the unicode code point in this pull request's
branch name. This is a consequence of the following change to a script in
wpt-tools:

https://github.com/w3c/wpt-tools/pull/139

In this case, the TravisCI environment happens to include the branch name among
the set of pre-defined environment variables.

I would like to resolve this myself, but unfortunately, I can't seem to
reproduce the behavior that motivated the change. I've reported the problem at
https://github.com/w3c/wpt-tools/issues/163 -- hopefully someone with an
effected system will be able to follow through with a patch.

**Comment by annevk** [comment]
I created #4794 as replacement since I need to move on with things. I can leave this open for folks to play with the tooling or I could file an issue against web-platform-tests. Let me know what you'd prefer.

**Comment by jugglinmike** [comment]
The root problem is in the wpt-tools project, so the issue I filed at https://github.com/w3c/wpt-tools/issues/163 may be sufficient to track the problem. Whatever the case, I think that it's safe to close this issue.

**Comment by annevk** [comment]
Thanks. If you want feel free to delete the branch.

**Pull request closed without merging**
