### PR TITLE
Stability script: guard against overridden streams

### PR DESCRIPTION
**Pull request by jugglinmike**
The second commit is intended for demonstration purposes only (sorry for the noise, URL reviewers). I will remove it following a successful build on TravisCI.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204413330)

# Firefox (nightly channel) #
Testing web-platform-tests at revision db495910daf88012e5ac6e74bb1df1c64dd6b1fe

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204413331)

# Chrome (unstable channel) #
Testing web-platform-tests at revision db495910daf88012e5ac6e74bb1df1c64dd6b1fe
Using browser at version 58.0.3018.3 dev

**Comment by jugglinmike** [comment]
The TravisCI jobs ran to completion; the reports are available here:

https://travis-ci.org/w3c/web-platform-tests/builds/204413327

Note that Chrome is reported as failing. That this is due to the browser's
behavior for the test used in the demonstration, not any erroneous behavior on
the part of the stability checker itself.

I have removed the demonstration commit from this branch making it safe to
merge to `master`.

**Comment by annevk** [comment]
Not sure how this affects url/.

**Comment by jugglinmike** [comment]
@annevk The reason you were notified was because the pull request originally
included a "debugging" commit that modified a file in the `url/` directory.
That change was intended to demonstrate the corrected test script behavior
which is the true intent of the patch. I've since removed that commit because
it served its purpose: the build log I referenced in my previous comment shows
how the CI environment will behave with this patch applied.

I'm sorry for the noise. Domenic has proposed a workaround in
https://github.com/w3c/web-platform-tests/issues/4990 . That feature would
certainly let us be more courteous, so I'll see if I can make that a priority.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
