### PR TITLE
Upgrade to Safari Technology Preview 93 on macOS Mojave

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
It still gets stuck on "SessionNotCreatedException: session not created (500): Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver."

I'll have to try this on a real mac tomorrow to see if there's any way around it or if we have to wait for STP 94.

@burg FYI.

**Comment by foolip** [comment]
`sudo safaridriver --enable` still doesn't work (@burg says it'll be fixed in STP 93) but now I can at least run the tests. There are a bunch of failures, the full log of `no_proxy='*' ./wpt run --yes --metadata infrastructure/metadata/ --log-tbpl - --log-tbpl-level info --channel preview safari infrastructure/` is at https://gist.github.com/foolip/9192229d8ebb456231cbd7b1d008e723. (The TBPL logs are too big for a gist, so I redacted the base64 images.)

I expect the fuzzy reftest failure is because of HiDPI, where on Azure Pipelines a regular screen is emulated. These new failures seem potentially serious though:
- /infrastructure/testdriver/actions/elementTiming.html
- /infrastructure/testdriver/bless.html

bless.html was a timeout, but searching for "InvalidArgumentException" in the logs there are some interesting things.

@burg have you checked for regressions in webdriver/tests/? If there's something that breaks `test_driver.click` or `test_driver.bless` quite many tests might be affected.

**Comment by foolip** [comment]
While I can't get this working on Azure Pipelines, I did run just webdriver/tests/ and manually uploaded the results to compare:
https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&run_id=343870004&run_id=332400001

@burg it looks like there are many regressions around clicking, keyboard input and actions, and a few other differences. Some tests have been fixed too, which is great of course. Can you take a look at this, can you repro from wpt directly?

Note that because I was running locally (and didn't use `caffeinate`) I had to occasionally move the mouse a little to prevent it from sleeping. Some surprising results could be because of that, but I think at most 2 or 3 tests.

**Comment by foolip** [comment]
I tried another workaround that worked locally from a fresh `brew cask install`, which is to just start STP, wait a bit and then close it again to make whatever plist refresh happen. But it didn't work in CI. STP was started though, here's a screenshot from within the CI system:

safari

Not sure what else to try...

**Comment by burg** [comment]
> On Oct 3, 2019, at 1:52 AM, Philip Jägenstedt <notifications@github.com> wrote:
> 
> While I can't get this working on Azure Pipelines, I did run just webdriver/tests/ and manually uploaded the results to compare:
> https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&run_id=343870004&run_id=332400001 <https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&run_id=343870004&run_id=332400001>
> @burg <https://github.com/burg> it looks like there are many regressions around clicking, keyboard input and actions, and a few other differences. Some tests have been fixed too, which is great of course. Can you take a look at this, can you repro from wpt directly?
> 
I have been busy with other projects and haven't had time to audit our test results. User-reported issues have taken priority, mainly the `safaridriver --enable` regressions. I'll take a look soon.

**Comment by foolip** [comment]
STP 94 is here: https://github.com/web-platform-tests/wpt/pull/19750

https://developer.apple.com/safari/technology-preview/release-notes/ say:
> Fixed an issue that prevented `sudo safaridriver --enable` from working correctly

Thanks @burg!

**Pull request closed without merging**
