### PR TITLE
[css-fonts] Keep range for expected values for 0 ranged descriptors

### PR DESCRIPTION
**Pull request by tursunova**
Change `expectedValue` from simplified to original value for the following tests:

- with equal upper and lower bounds
- 'oblique' followed by angle in radians
- 'oblique' followed by default 20deg angle

### CODE REVIEW

**Comment by jfkthame** [comment]
Does the spec explicitly require this somewhere, or is the exact serialization unspecified? Currently, I think Gecko would simplify such ranges to single values, and I don't immediately see any reason not to allow that.

(Gecko doesn't yet implement the CSSFontFaceRule getter/setter APIs used by these tests, so that's also a source of failures in Firefox. But given a stylesheet with a rule like `@font-face { font-family: test; src: url(foo.bar); font-weight: 200 200; }`, and then querying `rule.style.getPropertyValue("font-weight")`, we see that it returns simply `200`.)

**Comment by svgeesus** [comment]
> 'oblique' followed by default 20deg angle

But the [spec says](http://w3c.github.io/csswg-drafts/css-fonts-4/#valdef-font-style-oblique-angle-90deg-90deg):

> The lack of an [<angle>](https://w3c.github.io/csswg-drafts/css-values-4/#angle-value) represents 14deg.

**Comment by svgeesus** [comment]
>  is the exact serialization unspecified?

It is, sadly.

**Comment by jfkthame** [comment]
> > is the exact serialization unspecified?
> 
> It is, sadly.

I suspected as much; in which case I think the test should accept either the originally-specified form (e.g. `200 200` for `font-weight`) or a simplified equivalent (just `200`) when the range is zero-length.

Similarly, for a specified `font-style` descriptor of `oblique 14deg`, it should remain valid to return simply `oblique` as this is the default angle.

**Comment by tursunova** [comment]
Thank you for your comments.

Since we don't have a specification for that I have raised an [spec issue #7925](https://github.com/w3c/csswg-drafts/issues/7925). I'm suggesting to wait for the issue to be resolved before making any changes.

**Review by svgeesus — APPROVED** [review]
With the recent spec change this is now explicitly correct

**Review by svgeesus — CHANGES_REQUESTED** [review]
AAArgh I misread the diff here

So, this should **not** be merged because the simplified value is now explicitly correct.

**Pull request closed without merging**
