### PR TITLE
Testharness report fixes

### PR DESCRIPTION
**Pull request by jugglinmike**
@jgraham Mind taking a look?

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6119)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238129741)

# Firefox (nightly) #
Testing web-platform-tests at revision f46f36a77c4a3f92107b4de3189af598b995fef0
Ignoring 21 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238129742)

# Sauce (safari) #
Testing web-platform-tests at revision f46f36a77c4a3f92107b4de3189af598b995fef0
Ignoring 21 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238129748)

# Chrome (unstable) #
Testing web-platform-tests at revision f46f36a77c4a3f92107b4de3189af598b995fef0
Ignoring 21 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238129749)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision f46f36a77c4a3f92107b4de3189af598b995fef0
Ignoring 21 changed files:
No files changed

**Comment by jgraham** [comment]
Reviewed 1 of 21 files at r1.
Review status: 1 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[resources/test/tests/api-tests-1.html, line 181 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6119#-KlsdMZ_CCsOp2DbCR8R:-KlsdMZ_CCsOp2DbCR8S:b5brqp8) ([raw file](https://github.com/w3c/web-platform-tests/blob/822747fb2de8ffa0f9ab8b1c0da5d25d4ae6d156/resources/test/tests/api-tests-1.html#L181)):*
> ```HTML
>     {
>       "status_string": "PASS", 
>       "phase_string": "COMPLETE",
> ```

Is this always `COMPLETE`? Can we jsutt assert that directly rather than copying and psting everywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6119)*

**Comment by jugglinmike** [comment]
> Is this always `COMPLETE`? Can we jsutt assert that directly rather than copying and psting everywhere?

Sure. I've pushed up a "fixup!" commit to modify the first commit along these lines.

**Comment by jgraham** [comment]
Reviewed 6 of 21 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6119)*

**Pull request merged**
