### PR TITLE
Test that document.all() and document.all.item() throws

### PR DESCRIPTION
**Pull request by foolip**
Tests for https://github.com/whatwg/html/issues/1379

### CODE REVIEW

**Comment by foolip** [comment]
Based on https://github.com/w3c/web-platform-tests/pull/4037 and needs rebase + spec change before merging.

**Comment by foolip** [comment]
@ayg, why did you close this?

**Comment by jgraham** [comment]
Aryeh has some workflow that has the tragic side effect of closing all PRs when it goes wrong :)

**Comment by ayg** [comment]
The workflow being "git push --mirror", which is what I want to do to origin, but sometimes git thinks I mean upstream for some reason, and then it deletes all the branches upstream that I don't have.  (My .git/config now has an HTTP URL for upstream instead of SSH, so there should be no way for me to push anything upstream by mistake.)

**Comment by foolip** [comment]
Ah, good times :) I once accidentally deleted the whole whatwg/dom repo, so no biggie.

**Comment by foolip** [comment]
I've closed https://github.com/whatwg/html/issues/1379, so also closing this.

**Pull request closed without merging**
