### PR TITLE
Add RTCPeerConnectionIceEvent IDL test

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5690)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225852556)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225852558)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1e32a50d0aed19a13fe2eeec161d46caa0e495ac
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5690/webrtc/RTCPeerConnectionIceEvent-idl.html">/webrtc/RTCPeerConnectionIceEvent-idl.html</a></summary>


|                                                        Subtest                                                         | Results |                                        Messages                                        |
|------------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------|
|                                                                                                                        | OK      |                                                                                        |
| `RTCPeerConnectionIceEvent interface: existence and properties of interface object`                                    | FAIL    | `this.array.members[this.base] is undefined`                                           |
| `RTCPeerConnectionIceEvent interface object length`                                                                    | PASS    |                                                                                        |
| `RTCPeerConnectionIceEvent interface object name`                                                                      | PASS    |                                                                                        |
| `RTCPeerConnectionIceEvent interface: existence and properties of interface prototype object`                          | FAIL    | `this.array.members[inherit_interface] is undefined`                                   |
| `RTCPeerConnectionIceEvent interface: existence and properties of interface prototype object's "constructor" property` | PASS    |                                                                                        |
| `RTCPeerConnectionIceEvent interface: attribute candidate`                                                             | PASS    |                                                                                        |
| `RTCPeerConnectionIceEvent interface: attribute url`                                                                   | FAIL    | `assert_true: The prototype object must have a property "url" expected true got false` |
| `RTCPeerConnectionIceEvent must be primary interface of iceEvent`                                                      | PASS    |                                                                                        |
| `Stringification of iceEvent`                                                                                          | FAIL    | `this.array.members[this.base] is undefined`                                           |
| `RTCPeerConnectionIceEvent interface: iceEvent must inherit property "candidate" with the proper type (0)`             | PASS    |                                                                                        |
| `RTCPeerConnectionIceEvent interface: iceEvent must inherit property "url" with the proper type (1)`                   | FAIL    | `assert_inherits: property "url" not found in prototype chain`                         |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225852564)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1e32a50d0aed19a13fe2eeec161d46caa0e495ac

**Comment by agouaillard** [comment]
see #5693

**Pull request closed without merging**
