### PR TITLE
webrtc: add third party sdp module

### PR DESCRIPTION
**Pull request by fippo**
adds a third-party module for SDP parsing, mangling and generation to the
webrtc directory. This is going to be used for simulcast tests.

Checks in node_modules as well as a package.json and yarn lock files for
ease of updating. See
  https://github.com/web-platform-tests/rfcs/issues/46
for discussіon on the approach

### CODE REVIEW

**Comment by fippo** [comment]
DO NOT MERGE pending discussion in https://github.com/web-platform-tests/wpt/pull/21933

**Review by snuggs — COMMENTED** [review]
@fippo pardon my ignorance but can we merely use `sdp.js`? 
[Please see my comments](https://github.com/web-platform-tests/rfcs/issues/46#issuecomment-590646051)

P.S. SDP lib rocks!

**Comment by Hexcles** [comment]
We've decided to punt on how to manage npm packages systematically. For now, let's follow this [comment](https://github.com/web-platform-tests/rfcs/issues/46#issuecomment-605098405):

> i. Add a new directory, webrtc/third_party/sdp
> ii. Vendor (copy) sdp.js and its associated LICENSE file into webrtc/third_party/sdp

**Comment by fippo** [comment]
closing this PR then. New one incoming ;-)

**Pull request closed without merging**
