### PR TITLE
selection: Split addRange.html into 15.

### PR DESCRIPTION
**Pull request by tkent-google**
addRange.html exceeds the time limit for a single test in Chromium project, and
also the text dump of its result exceeds the file size limit of code review tool
of Chromium project.

This is similar to https://github.com/w3c/web-platform-tests/pull/4049

### CODE REVIEW

**Comment by TakayoshiKochi** [comment]
To avoid someone reverting the split files into one test, could you add a comment somewhere
of the reason splitting the test?

**Comment by tkent-google** [comment]
> To avoid someone reverting the split files into one test, could you add a comment somewhere
of the reason splitting the test?

Done.

**Comment by TakayoshiKochi** [comment]
LGTM

**Comment by tkent-google** [comment]
travis-ci makes false alarm.  I'll merge manually.

**Comment by tkent-google** [comment]
> I'll merge manually.

It seems it's prohibited.

**Pull request merged**
