### PR TITLE
Font variant caps

### PR DESCRIPTION
**Pull request by svgeesus**
7 tests for font-variant-caps, plus refs. @litherum for review

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230829436)

# Firefox (nightly) #
Testing web-platform-tests at revision 9698e85935953fe6e16ae32708d5b3c4e2f8faba
Using browser at version BuildID 20170509100208; SourceStamp b21b974d60d3075ae24f6fb1bae75d0f122f28fc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>11 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-01.html">/css/css-fonts-3/font-variant-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-02.html">/css/css-fonts-3/font-variant-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-03.html">/css/css-fonts-3/font-variant-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-04.html">/css/css-fonts-3/font-variant-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-01.html">/css/css-fonts-3/font-variant-caps-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-02.html">/css/css-fonts-3/font-variant-caps-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-03.html">/css/css-fonts-3/font-variant-caps-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-04.html">/css/css-fonts-3/font-variant-caps-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-05.html">/css/css-fonts-3/font-variant-caps-05.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-06.html">/css/css-fonts-3/font-variant-caps-06.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5875/css/css-fonts-3/font-variant-caps-07.html">/css/css-fonts-3/font-variant-caps-07.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230829442)

# Chrome (unstable) #
Testing web-platform-tests at revision 9698e85935953fe6e16ae32708d5b3c4e2f8faba

**Comment by svgeesus** [comment]
(stupid git shell for windows turning my unix-ending files into crlf *on commit* sigh.)

**Comment by svgeesus** [comment]
@litherum requesting review, as we discussed. The system won't let me add tou in the reviewer pulldown for some reason

**Comment by litherum** [comment]
r=me.

**Pull request merged**
