### PR TITLE
Adding more complete button & buttons attribute test

### LINKED ISSUE #3180: Add a full test for button & buttons attributes for pointerevents
There is a small test for button and buttons attributes only for pointerover type. It is better to have the test for all types of pointerevents.

### PR DESCRIPTION
**Pull request by NavidZ**
closes #3180

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by Steditor** [comment]
Looks good, but I don't think this closes #3180, as there are still more attributes.

On the other hand, the `check_PointerEvent` function in `pointerevent_support.js` does already check some attributes (e.g. the pressure, and also the `isPrimary` attribute which has a test in `pointerevent_attributes_mouse-manual.html` as well)
I think it would be a good idea, to decide whether those attributes should be tested with `check_PointerEvent` which is used by a set of existing tests, or with a separate test like the one in this PR.

**Comment by NavidZ** [comment]
I intentionally reported that issue to only cover the button & buttons attribute. So technically it does close that issue. However, I need to work on more pull requests for other fields as well. But I wanted to address them separately. As some of them needs some refactoring across the tests. Particularly in that check_PointerEvent function only checks for pointer event specific attributes are done and not the ones inherited from mouse events. At the same time for example for button it really depends on the test scenario on what the expected value is. However, I'll continue refactoring the tests and add more tests and if I see multiple occurrence of button (or any other attribute) test, I will refactor that as well.

**Comment by NavidZ** [comment]
Is this PR good to go in? @RByers can you have a look?

**Pull request merged**
