### PR TITLE
Ttwg

### PR DESCRIPTION
**Pull request by ghost**
added WebVTT files manually generated from ttml/Content during the Sept 2015 TTWG meeting

### CODE REVIEW

**Comment by annevk** [comment]
@zcorpan can this be closed?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/211705768)

# Firefox (nightly channel) #
Testing web-platform-tests at revision a80c5db9bd4c9764bcdd66276c5ed5779c11bd0b
Using browser at version BuildID 20170314110401; SourceStamp 6d38ad302429c98115c354d643e81987ecec5d3c
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/211705769)

# Chrome (unstable channel) #
Testing web-platform-tests at revision a80c5db9bd4c9764bcdd66276c5ed5779c11bd0b
Using browser at version 58.0.3029.19 dev

**Comment by zcorpan** [comment]
Yeah I think so. It's not clear to me that tests for mapping between TTML and WebVTT fit in with the web-platform-tests project, as it's not tests for user agents of either standard.

**Pull request closed without merging**
