### PR TITLE
Update WebSockets library for Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by jgraham** [comment]
Bleh, so this seems to break Python 3.6 :/

**Comment by bwalderman** [comment]
@jgraham , I'm not sure if this is the same break that happens in 3.6, but for 3.10 on Windows, I found that all of the async fixtures in [fixtures.py](https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/support/fixtures.py) needed to be marked with `@pytest_asyncio.fixture` instead of `@pytest.fixture` in order for the WebDriver BiDi tests to run.

**Comment by whimboo** [comment]
Thanks @bwalderman! 

I stumbled over this PR right now and want to note that the `pytest_asyncio.fixture` issue got already fixed 5 months ago via https://github.com/web-platform-tests/wpt/pull/38932.

I'm going to rebase the PR and get the merge conflicts solved. Locally it all passes for me.

**Review by whimboo — APPROVED** [review]
Actually, maybe my approval would be enough and we can merge it.

**Comment by whimboo** [comment]
> Actually, maybe my approval would be enough and we can merge it.

It does not actually look like that my review was enough here. So yes, please have a look. Thanks.

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
