### PR TITLE
URL: remove obsolete README bits

### PR DESCRIPTION
**Pull request by annevk**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5660)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5660/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225188154)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225188156)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 5d0b929c2624c69534a3bc3705b5a6262f7f6bda
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225188162)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 5d0b929c2624c69534a3bc3705b5a6262f7f6bda

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
