### PR TITLE
getContext()'s second argument

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/html/issues/595 and https://github.com/whatwg/html/pull/3370 for context.

### CODE REVIEW

**Comment by tobie** [comment]
Summoning @wpt-pr-bot.

**Comment by annevk** [comment]
Someone else will have to run `update-built-tests.sh` since I'm not super keen on installing virtualenv and such.

**Comment by annevk** [comment]
Can someone help me out with getting `2dcontext/tools/gentest.py` to run? I'm missing cairo, but pip install pycairo and easy_install pycairo are failing, possibly because it no longer supports p2?

**Comment by sideshowbarker** [comment]
> Can someone help me out with getting `2dcontext/tools/gentest.py` to run? I'm missing cairo, but pip install pycairo and easy_install pycairo are failing, possibly because it no longer supports p2?

You might be able to get past that with brew by doing `brew install py2cairo`.

But even when I do that in my environment, and run `python ./2dcontext/tools/gentest.py`, I get `IOError: [Errno 2] No such file or directory: 'templates.yaml'`

**Comment by sideshowbarker** [comment]
>(Alternatively, if you're willing to run it and push a fixup commit, that'd be great!)

Done. `html/semantics/embedded-content/the-canvas-element/2d.getcontext.extraargs.html` seems to be the only (generated) test file that ends up with a substantive change. I guess that’s expected. (The rest of the affected files only have the update `This test has been generated by /2dcontext/tools/gentest.py.` comment change.)

**Comment by sideshowbarker** [comment]
Based on the IRC comment at https://w3.logbot.info/testing/20200208#c542306, I went ahead and split this into two commits (and rewrote the history on the branch and force-pushed it here).

Please doublecheck it all.

**Comment by annevk** [comment]
LGTM, but I cannot approve as I wrote this.

**Pull request merged**
