### PR TITLE
Use .any.js for the getRandomValues() test.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision b8b8e4eba5fd6bb7aae3cd7235f2379335dee6d3

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision b8b8e4eba5fd6bb7aae3cd7235f2379335dee6d3

**Comment by jimsch** [comment]
@Ms2ger  Is this something that is a change based on how the platform works?  Should this be done for the rest of the tests as well?

**Comment by Ms2ger** [comment]
It just reduces the boilerplate around running tests in both window and (dedicated) worker scopes. I think it's generally better to use this feature when writing tests for APIs that exist in both scopes, but rewriting existing tests is probably low priority.

**Pull request merged**
