### PR TITLE
Add a long timeout to the wdspec actions test.

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5024)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205857590)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fd3f27ea15ff5f4198e05c11ad66994f19ad52c9
Using browser at version BuildID 20170225110158; SourceStamp f36062d04d165f6f6e781cf0633ffcbbebe6c273
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205857591)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fd3f27ea15ff5f4198e05c11ad66994f19ad52c9
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
No tests run.

**Comment by andreastt** [comment]
So I guess wptrunner actually picks this up? In any case, that’s great!

**Pull request merged**
