### PR TITLE
Add tests for referrers from sandboxed iframes

### PR DESCRIPTION
**Pull request by jeisinger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 5fecdfde153db0a9390280a6f213e36772275043
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4827/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html">/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | OK      |
| `Sandboxed iframe with tuple origin sends referrers.`         | PASS    |
| `Sandboxed iframe with opaque origin doesn't send referrers.` | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 5fecdfde153db0a9390280a6f213e36772275043
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4827/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html">/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | OK      |
| `Sandboxed iframe with tuple origin sends referrers.`         | PASS    |
| `Sandboxed iframe with opaque origin doesn't send referrers.` | PASS    |

</details>
</details>

**Comment by estark37** [comment]
lgtm. Who has the power to merge these things? @mikewest?

**Comment by mikewest** [comment]
https://www.youtube.com/watch?v=-dJolYw8tnk

:)

**Pull request merged**
