### PR TITLE
Update Safari Technology Preview to 108

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 108, 15610.1.16.3)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1864&view=logs

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I've pushed a trigger run of STP108 to `triggers/safari_preview`; https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=49729&view=results

**Comment by stephenmcgruer** [comment]
Diff URL: https://wpt.fyi/results/?diff&filter=ADC&run_id=596250003&run_id=601810001

**Comment by stephenmcgruer** [comment]
WPT diff looks good; there was a unittest failure that looks unrelated, but retrying the CQ just to see if it reoccurs.

cc @burg since there are some changes in webdriver/ results, but they may be existing flake: https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&run_id=596250003&run_id=601810001 (get_current_url and get_element_rect)

**Comment by stephenmcgruer** [comment]
This time task-cluster is stuck, but azure ran fine so admin-merging.

**Comment by burg** [comment]
As far as I can tell, the progressions and regressions present are simply user prompt handling tests being flaky. It's a known issue.

-B

**Pull request merged**
