### PR TITLE
Update Safari Technology Preview to 98

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 98, 14609.1.13.4)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1248&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18830 shows that "infrastructure/ tests: macOS" and "tools/wpt/ tests: macOS" are already broken on master and I'm trying to fix that.

I've also triggered a full run in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39867 to get a 97&rarr;98 diff.

**Comment by foolip** [comment]
I've rebased this on top of https://github.com/web-platform-tests/wpt/pull/21110 now.

**Comment by foolip** [comment]
No changes in infrastructure/ tests, cool!

@stephenmcgruer can you review this? Before landing, we should compare the results of https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39867 to https://wpt.fyi/results/?run_id=410300014 on which it is based.

**Comment by foolip** [comment]
Here's the diff: https://wpt.fyi/results/?diff&filter=ADC&run_id=410300014&run_id=398610001

That looks good to me, more green than red. @stephenmcgruer please merge as you see fit.

**Review by stephenmcgruer — APPROVED** [review]
LGTM too. I took a quick peek through and it seemed like a good number of wins, mostly around animations (I believe webkit moved css animations/transitions to the new web-animations stack in 98).

**Comment by stephenmcgruer** [comment]
Looking at https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3Apass%20status%3A%21pass%20status%3Apass%29&run_id=410290006&run_id=400510009&run_id=410300014&run_id=398610001, a smaller improvement in browser-specific failures for STP98, but still moving in the right direction! (The inverse direction has 54 tests, 262 subtests).

**Comment by foolip** [comment]
5696 subtests is quite a lot, even if it's that'll count as at most 194 when normalized per test. Good stuff.

**Pull request merged**
