### PR TITLE
Inline testharness.css into testharness.js for better performance

### PR DESCRIPTION
**Pull request by zcorpan**
Loading the stylesheet at the same time as inserting the results
table causes the table to be rendered twice in different layout
modes, which takes a long time for very big tables.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/11143)

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by gsnedders** [comment]
This breaks testharness.js for all browsers that don't support template literals, which seems a bit sad. (Given, e.g., you now can't run any test in Presto to see what it does, for example.)

**Comment by zcorpan** [comment]
How often do you check tests in Presto? Do you avoid newer features when writing tests?

**Comment by jgraham** [comment]
I didn't think about this carefully but typically we have avoided breaking testharness.js itself for older browsers. I would like us to try and find a solution for this and should have noticed in the review; sorry,

**Comment by zcorpan** [comment]
Would a normal string be ok? It would be slightly annoying to edit the stylesheet.

**Comment by zcorpan** [comment]
https://github.com/w3c/web-platform-tests/pull/11159

**Pull request merged**
