### PR TITLE
Upstream timeline-time.html from Blink

### PR DESCRIPTION
**Pull request by suzyh**
Import https://chromium.googlesource.com/chromium/src/+/f92b62a5dd9fa3ce8cb57c6711f52bb14dccd758/third_party/WebKit/LayoutTests/web-animations-api/timeline-time.html

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/3340/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/212003186)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 9b91a8b583d4e36b2aa9818bbeeabdddb16c4cd1
Git command exited with status 128
fatal: Invalid revision range 66bf88245c3d64160aef3797b93043a74a0f1082..

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/212003187)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 9b91a8b583d4e36b2aa9818bbeeabdddb16c4cd1
Git command exited with status 128
fatal: Invalid revision range 66bf88245c3d64160aef3797b93043a74a0f1082..

**Comment by birtles** [comment]
Hmm, maybe the test runner doesn't like such old revisions.

**Pull request merged**
