### PR TITLE
tests for onpayerdetailchange

### PR DESCRIPTION
**Pull request by marcoscaceres**
Tests for https://github.com/w3c/payment-request/pull/724

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@rsolomakhin, one moar 💪🙌

**Comment by marcoscaceres** [comment]
@rsolomakhin, @edenchuang, ping. Currently working on this in Gecko, so would like to land these so I can test against them.

**Review by rsolomakhin — APPROVED** [review]
Thank you for the ping! This flew under my radar for some reason.

**Comment by marcoscaceres** [comment]
Awesome, thanks!

**Pull request merged**
