### PR TITLE
gamepad: Update spec reference links.

### PR DESCRIPTION
**Pull request by rakuco**
Refer to GitHub instead of the old W3C hg repository.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259728942)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259728943)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259728950)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259728951)

# Sauce (MicrosoftEdge) #

**Review by luser — APPROVED** [review]
Thanks!

**Pull request merged**
