### PR TITLE
[storage-access-api] expand on META.yml

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@ehsan @johnwilander, I'm proposing these changes based on @Brandr0id saying in email that you're the primary contacts for Gecko and WebKit. I won't merge this without your explicit approval, and if you do want to review I'll make sure you're in the reviewers team and have write access before I merge this.

**Review by Brandr0id — APPROVED** [review]
LGTM

**Comment by johnwilander** [comment]
Looks good.

**Comment by foolip** [comment]
@johnwilander you have a pending invitation to the org and reviewers team, I think you can see a banner at the top of https://github.com/web-platform-tests or find it in your inbox. After you join, see https://github.com/orgs/web-platform-tests/teams/reviewers/discussions for some tips to avoid excessive mail spam, and some email filter tips.

**Comment by ehsan** [comment]
Thanks, looks good here as well.  Apologies for the delay.

**Comment by foolip** [comment]
Thanks all, I'll merge now.

**Pull request merged**
