### PR TITLE
Add Noto Naskh Arabic regular woff2 font

### PR DESCRIPTION
**Pull request by himorin**
file original from resources.whatwg.org/fonts/NotoNaskhArabic-Regular.woff2

We are planning to add some tests for css-text shaping using Arabic font, so we want to add Noto Naskh Arabic regular woff2 font file to wpt.

cc @fantasai @xfq @r12a

### CODE REVIEW

**Comment by r12a** [comment]
cc @frivoal since this may be relevant for the zwj tests you were working on at https://github.com/web-platform-tests/wpt/pull/14673

**Review by kojiishi — APPROVED** [review]
lgtm

**Review by frivoal — APPROVED** [review]

**Comment by jgraham** [comment]
I assume the intent is that this is only usable as a webfont?

**Comment by frivoal** [comment]
what else do you have in mind?

**Comment by gsnedders** [comment]
@frivoal we install Ahem at a system level, but… that's painful and somewhat fragile.

**Comment by frivoal** [comment]
Right. No need for that. These fonts can be called in explicitly by tests that need them.

**Pull request merged**
