### PR TITLE
[html] Remove a testcase to check case-insensitivity of radio button …

### PR DESCRIPTION
**Pull request by tkent-google**
…group name

The testcase doesn't match to the current specification, and
radio-groupname-case.html covers this feature.

### CODE REVIEW

**Comment by tkent-google** [comment]
@domenic @TakayoshiKochi , would you review this please?

**Comment by zcorpan** [comment]
Can you change it so radio3 and radio4 both have the name `groüp2`?

radio-groupname-case.html doesn't test that two controls with the *same* name with non-ASCII characters are in the same group, as far as I can tell.

**Comment by tkent-google** [comment]
@zcorpan thank you for the comment.  New commit addressed it.

**Comment by zcorpan** [comment]
Thanks!

**Pull request merged**
