### PR TITLE
Add interfaces/webrtc-priority.idl and test

### PR DESCRIPTION
**Pull request by foolip**
Closes https://github.com/web-platform-tests/wpt/pull/21442.

### CODE REVIEW

**Comment by foolip** [comment]
`test_tests_affected_idlharness` is failing. That's an annoying test to have to update :)

**Review by stephenmcgruer — APPROVED** [review]
LGTM modulo fixing that test.

Looks like no browser currently implements this. Do we know if there is an intention to?

**Comment by foolip** [comment]
@dontcallmedom do you know what implementor interest is like for webrtc-identity?

**Comment by stephenmcgruer** [comment]
> @dontcallmedom do you know what implementor interest is like for webrtc-identity?

Ping @dontcallmedom and @alvestrand for this question. As of today, I still can't find a `priority` member in Chrome's `RTCDataChannel` definition (haven't checked other browsers).

**Comment by guest271314** [comment]
Is this similar to or based on `scheduler.postTask()`?

**Comment by alvestrand** [comment]
There's some interest in completing the plumbing on priority for datachannels.
We already have the plumbing in place for RTCRtpEncodingParameters, which is the other place where priority is surfaced.

As for webrtc-identity, there's been some push, mainly from Cisco and Mozilla, to make that happen, but that has so far (AFAIK) not led to either a standards conformant implementation in Firefox or a product that uses this feature on any platform. It's been a while since I last heard someone mention it as something they wanted to work on.

The attitude at Google on identity has been "let's see Mozilla show that it is possible to implement and serves an useful function - then we'll think about adding it".

**Comment by foolip** [comment]
Thanks @alvestrand, that explains why https://wpt.fyi/results/webrtc-priority/idlharness.window.html?label=pr_head&max-count=1&pr=21462 has the tests failing everywhere.

I'm going to close this PR and leave https://github.com/web-platform-tests/wpt/pull/21442 open, with a reference to revive this if implementer interest materializes.

**Pull request closed without merging**
