### PR TITLE
Test empty username and credential in RTCPeerConnection constructor

### PR DESCRIPTION
**Pull request by foolip**
Tests for https://github.com/w3c/webrtc-pc/issues/885

### CODE REVIEW

**Comment by foolip** [comment]
@jan-ivar for review as this will fail in Firefox. If you want to follow all changes here, add yourself to OWNERS :)

**Comment by foolip** [comment]
@ayg, will you run a script to find a reopen all PRs closed by accident?

**Comment by ayg** [comment]
@foolip I already looked at all closed PRs sorted by last update time, opened them all in my browser, and restored branch/reopened on all of them manually (which was faster than writing a script would have been).  I don't know how I missed this one -- now I see a few more I missed.  Problem is, GitHub doesn't let me restore the branch anymore AFAICT, and I don't have the hashes of the commits to restore them manually.  I see that there's some type of events API, but it doesn't seem to go back far enough.

I don't understand why GitHub doesn't make the reflog accessible online.  Surely it must be common enough that someone deletes a repo by mistake?

**Comment by jan-ivar** [comment]
Lgtm. A fix for Firefox is in [bug 1313246](https://bugzil.la/1313246) for my reference.

**Pull request merged**
