### PR TITLE
[geometry] Test stringifier for DOMMatrix

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/w3c/fxtf-drafts/pull/148

---

cc @gogag1

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231088692)

# Firefox (nightly) #
Testing web-platform-tests at revision 7cc946671009d5fbc44c8bbf332f9586a6b44914
Using browser at version BuildID 20170510183715; SourceStamp ce2218406119c36a551e3faea4e192186ee46cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5885/css/geometry-1/DOMMatrix-stringifier.html">/css/geometry-1/DOMMatrix-stringifier.html</a></summary>


|                          Subtest                          | Results |                                                                          Messages                                                                          |
|-----------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                           | OK      |                                                                                                                                                            |
| `DOMMatrix stringifier: identity (2d)`                    | PASS    |                                                                                                                                                            |
| `DOMMatrix stringifier: identity (3d)`                    | FAIL    | `self[constr].fromMatrix is not a function`                                                                                                                |
| `DOMMatrix stringifier: NaN (2d)`                         | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: NaN (3d)`                         | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: Infinity (2d)`                    | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: Infinity (3d)`                    | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: -Infinity (2d)`                   | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: -Infinity (3d)`                   | FAIL    | `assert_throws: function "() => String(matrix)" did not throw`                                                                                             |
| `DOMMatrix stringifier: 1/3 (2d)`                         | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 0.3333333333333333)" but got "matrix(1, 0, 0, 1, 0, 0.333333)"`                                            |
| `DOMMatrix stringifier: 1/3 (3d)`                         | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0.3333333333333333, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 0.333333)"`            |
| `DOMMatrix stringifier: 1/300000 (2d)`                    | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 0.0000033333333333333333)" but got "matrix(1, 0, 0, 1, 0, 0.00000333333)"`                                 |
| `DOMMatrix stringifier: 1/300000 (3d)`                    | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0.0000033333333333333333, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 0.00000333333)"` |
| `DOMMatrix stringifier: 1/300000000 (2d)`                 | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 3.3333333333333334e-9)" but got "matrix(1, 0, 0, 1, 0, 3.33333e-9)"`                                       |
| `DOMMatrix stringifier: 1/300000000 (3d)`                 | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 3.3333333333333334e-9, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 3.33333e-9)"`       |
| `DOMMatrix stringifier: 100000 + (1/3) (2d)`              | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 100000.33333333333)" but got "matrix(1, 0, 0, 1, 0, 100000)"`                                              |
| `DOMMatrix stringifier: 100000 + (1/3) (3d)`              | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 100000.33333333333, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 100000)"`              |
| `DOMMatrix stringifier: Math.pow(2, 53) + 1 (2d)`         | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 9007199254740992)" but got "matrix(1, 0, 0, 1, 0, 9.0072e+15)"`                                            |
| `DOMMatrix stringifier: Math.pow(2, 53) + 1 (3d)`         | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 9007199254740992, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 9.0072e+15)"`            |
| `DOMMatrix stringifier: Math.pow(2, 53) + 2 (2d)`         | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 9007199254740994)" but got "matrix(1, 0, 0, 1, 0, 9.0072e+15)"`                                            |
| `DOMMatrix stringifier: Math.pow(2, 53) + 2 (3d)`         | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 9007199254740994, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 9.0072e+15)"`            |
| `DOMMatrix stringifier: Number.MAX_VALUE (2d)`            | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 1.7976931348623157e+308)" but got "matrix(1, 0, 0, 1, 0, Infinity)"`                                       |
| `DOMMatrix stringifier: Number.MAX_VALUE (3d)`            | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1.7976931348623157e+308, 0, 1)" but got "matrix(1, 0, 0, 1, 0, Infinity)"`       |
| `DOMMatrix stringifier: Number.MIN_VALUE (2d)`            | FAIL    | `assert_equals: expected "matrix(1, 0, 0, 1, 0, 5e-324)" but got "matrix(1, 0, 0, 1, 0, 0)"`                                                               |
| `DOMMatrix stringifier: Number.MIN_VALUE (3d)`            | FAIL    | `assert_equals: expected "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 5e-324, 0, 1)" but got "matrix(1, 0, 0, 1, 0, 0)"`                               |
| `DOMMatrix stringifier: throwing getters (2d)`            | PASS    |                                                                                                                                                            |
| `DOMMatrix stringifier: throwing getters (3d)`            | FAIL    | `self[constr].fromMatrix is not a function`                                                                                                                |
| `DOMMatrixReadOnly stringifier: identity (2d)`            | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: identity (3d)`            | FAIL    | `self[constr].fromMatrix is not a function`                                                                                                                |
| `DOMMatrixReadOnly stringifier: NaN (2d)`                 | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: NaN (3d)`                 | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Infinity (2d)`            | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Infinity (3d)`            | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: -Infinity (2d)`           | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: -Infinity (3d)`           | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/3 (2d)`                 | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/3 (3d)`                 | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/300000 (2d)`            | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/300000 (3d)`            | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/300000000 (2d)`         | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 1/300000000 (3d)`         | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 100000 + (1/3) (2d)`      | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: 100000 + (1/3) (3d)`      | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Math.pow(2, 53) + 1 (2d)` | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Math.pow(2, 53) + 1 (3d)` | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Math.pow(2, 53) + 2 (2d)` | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Math.pow(2, 53) + 2 (3d)` | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Number.MAX_VALUE (2d)`    | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Number.MAX_VALUE (3d)`    | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Number.MIN_VALUE (2d)`    | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: Number.MIN_VALUE (3d)`    | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: throwing getters (2d)`    | FAIL    | `Illegal constructor.`                                                                                                                                     |
| `DOMMatrixReadOnly stringifier: throwing getters (3d)`    | FAIL    | `self[constr].fromMatrix is not a function`                                                                                                                |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231088702)

# Chrome (unstable) #
Testing web-platform-tests at revision 7cc946671009d5fbc44c8bbf332f9586a6b44914

**Comment by cdumez** [comment]
w3c-test:mirror

**Comment by zcorpan** [comment]
@cdumez I think these were on w3c-test already but the bot comment was removed to reduce bot spam. The stability results above have links under All results.

http://w3c-test.org/submissions/5885/css/geometry-1/DOMMatrix-stringifier.html

**Review by peterjoel — APPROVED** [review]

**Pull request merged**
