### PR TITLE
Update tests for whatwg/html#1993

### PR DESCRIPTION
**Pull request by ayg**
Do not accept this PR unless the spec PR is accepted.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/4115)

### CODE REVIEW

**Comment by ayg** [comment]
I added a rendering test too (using getBoundingClientRect()).  Does anyone want additional rendering tests?  They should be easy enough to add.

I don't know if I put the new test in the right directory.

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by jgraham** [comment]
whatwg/html#1993

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4115/)

**Comment by ayg** [comment]
Updated for new spec PR.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225202978)

# Lint #

Passed

**Comment by w3c-bots** [comment]
*This report has been truncated because the total content is 2946532 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225202980)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e431502db6ce118aad7a1a08522beb17f99bb70a
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4115/html/dom/reflection-embedded.html">/html/dom/reflection-embedded.html</a></summary>


|                                                                                        Subtest                                                                                        | Results |                                                                                                 Messages                                                                                                |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                       | OK      |                                                                                                                                                                                                         |
| `img.title: typeof IDL attribute`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL get with DOM attribute unset`                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to ""`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                         | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to undefined`                                                                                                                                              | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to 7`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to 1.5`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to true`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to false`                                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to object "[object Object]"`                                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to NaN`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to Infinity`                                                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to -Infinity`                                                                                                                                              | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to "\0"`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to null`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to object "test-toString"`                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.title: setAttribute() to object "test-valueOf"`                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to ""`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                                | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to undefined`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to 7`                                                                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to 1.5`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to true`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to false`                                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to object "[object Object]"`                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to NaN`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to Infinity`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to -Infinity`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to "\0"`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to null`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to object "test-toString"`                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.title: IDL set to object "test-valueOf"`                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.lang: typeof IDL attribute`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL get with DOM attribute unset`                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to ""`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                          | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to undefined`                                                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to 7`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to 1.5`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to true`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to false`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to object "[object Object]"`                                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to NaN`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to Infinity`                                                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to -Infinity`                                                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to "\0"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to null`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to object "test-toString"`                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.lang: setAttribute() to object "test-valueOf"`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to ""`                                                                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                                 | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to undefined`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to 7`                                                                                                                                                              | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to 1.5`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to true`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to false`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to object "[object Object]"`                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to NaN`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to Infinity`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to -Infinity`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to "\0"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to null`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to object "test-toString"`                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.lang: IDL set to object "test-valueOf"`                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.dir: typeof IDL attribute`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL get with DOM attribute unset`                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to ""`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to undefined`                                                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to 7`                                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to 1.5`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to true`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to false`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to object "[object Object]"`                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to NaN`                                                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to Infinity`                                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to -Infinity`                                                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "\0"`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to null`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to object "test-toString"`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to object "test-valueOf"`                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "ltr"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "xltr"`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "ltr\0"`                                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "tr"`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "LTR"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "rtl"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "xrtl"`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "rtl\0"`                                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "tl"`                                                                                                                                                     | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "RTL"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "auto"`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "xauto"`                                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "auto\0"`                                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "uto"`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.dir: setAttribute() to "AUTO"`                                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to ""`                                                                                                                                                              | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`                                  | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to undefined`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to 7`                                                                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to 1.5`                                                                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to true`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to false`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to object "[object Object]"`                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to NaN`                                                                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to Infinity`                                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to -Infinity`                                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "\0"`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to null`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to object "test-toString"`                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to object "test-valueOf"`                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "ltr"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "xltr"`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "ltr\0"`                                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "tr"`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "LTR"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "rtl"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "xrtl"`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "rtl\0"`                                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "tl"`                                                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "RTL"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "auto"`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "xauto"`                                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "auto\0"`                                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "uto"`                                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.dir: IDL set to "AUTO"`                                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): typeof IDL attribute`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL get with DOM attribute unset`                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to ""`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`       | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to undefined`                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to 7`                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to 1.5`                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to true`                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to false`                                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to object "[object Object]"`                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to NaN`                                                                                                                                  | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to Infinity`                                                                                                                             | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to -Infinity`                                                                                                                            | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to "\0"`                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to null`                                                                                                                                 | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to object "test-toString"`                                                                                                               | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): setAttribute() to object "test-valueOf"`                                                                                                                | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to ""`                                                                                                                                          | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo "`              | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to undefined`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to 7`                                                                                                                                           | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to 1.5`                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to true`                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to false`                                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to object "[object Object]"`                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to NaN`                                                                                                                                         | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to Infinity`                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to -Infinity`                                                                                                                                   | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to "\0"`                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to null`                                                                                                                                        | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to object "test-toString"`                                                                                                                      | PASS    |                                                                                                                                                                                                         |
| `img.className (<img class>): IDL set to object "test-valueOf"`                                                                                                                       | PASS    |                                                                                                                                                                                                         |
| `img.hidden: typeof IDL attribute`                                                                                                                                                    | PASS    |                                                                                                                                                                                                         |
| `img.hidden: IDL get with DOM attribute unset`                                                                                                                                        | PASS    |

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225202986)

# Chrome (unstable channel) #
Testing web-platform-tests at revision e431502db6ce118aad7a1a08522beb17f99bb70a

**Comment by zcorpan** [comment]
w3c-test:mirror

**Review by zcorpan — APPROVED** [review]

**Comment by cdumez** [comment]
I am not 100% sure this updated all the checks. After implementing this, I get a few failures (could be a mistake on my part, still looking):
FAIL td.rowSpan: IDL set to 2147483647 assert_equals: IDL get expected 2147483647 but got 65534
FAIL th.rowSpan: setAttribute() to 2147483647 assert_equals: IDL get expected 2147483647 but got 65534
FAIL th.rowSpan: IDL set to 2147483647 assert_equals: IDL get expected 2147483647 but got 65534

**Comment by ayg** [comment]
The tests were buggy, see #5706.

**Comment by ayg** [comment]
Make that #5707.  Review appreciated.  :)  My Firefox implementation now passes all the tests.

**Pull request merged**
