### PR TITLE
Some work on updateWith-method-pmi-handling-manual.https.html

### PR DESCRIPTION
**Pull request by marcoscaceres**
Related to #15861

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]
LGTM!

**Comment by marcoscaceres** [comment]
@rsolomakhin, still struggling what’s going on with the promise rejection in Chrome. It might require a deeper dive beyond what we can see in JS?

**Comment by rsolomakhin** [comment]
@marcoscaceres : Can you tell me more? This test looks OK as-is...

**Comment by marcoscaceres** [comment]
See @danyao details here: 
https://github.com/web-platform-tests/wpt/issues/15861

**Review by danyao — APPROVED** [review]
Thanks for fixing this one!

**Comment by marcoscaceres** [comment]
This only partially fixes things... you might need to bring out good ol’ gdb to figure out what’s going on with the phantom promise rejection.

**Pull request merged**
