### PR TITLE
Part 2: show(details) resolves tests

### PR DESCRIPTION
**Pull request by marcoscaceres**
Part 1 is https://github.com/w3c/web-platform-tests/pull/9617

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-02-26 06:18:25
Finished: 2018-02-26 06:24:55


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24854)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346154402)

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@rsolomakhin, wow! thanks for the super speedy review.

**Comment by marcoscaceres** [comment]
@sideshowbarker, could you please grant @rsolomakhin write access? Above, GitHub is complaining that his review doesn't count because he is missing write access.

**Comment by sideshowbarker** [comment]
> @sideshowbarker, could you please grant @rsolomakhin write access? 

yup, done

**Pull request merged**
