### PR TITLE
Clarify that assert_equals relies on ===

### PR DESCRIPTION
**Pull request by tobie**
Sorry for creating a branch here for this. The new GH Web interface no longer lets you create branches in your own fork. :(

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5751)

### CODE REVIEW

**Comment by annevk** [comment]
Does it? I thought it still used ==...

**Comment by tobie** [comment]
@annevk: https://github.com/w3c/web-platform-tests/blob/master/resources/testharness.js#L866-L876

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227868489)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 736688fdda88a0d164ac396d4ae6268ab701a2cd
Using browser at version BuildID 20170501100238; SourceStamp 076a7a66096f9e8d102548397254be32eb26bc3d
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227868495)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 736688fdda88a0d164ac396d4ae6268ab701a2cd

**Comment by annevk** [comment]
Oh, cool. Did that change or did I just misremember?

**Comment by tobie** [comment]
I have no idea. I end-up checking every time, which is why I'm documenting it. The name's a bit of a misnomer, as other JS test frameworks tend to associate equal to `==` and identical to `===`.

**Comment by zcorpan** [comment]
testharness.js has always used `===` here.

**Review by zcorpan — APPROVED** [review]

**Comment by gsnedders** [comment]
It should be equivalent to `Object.is`, which just exposes the internal ES `SameValue` function.

**Comment by tobie** [comment]
@gsnedders maybe that's what should be in the doc?

**Comment by gsnedders** [comment]
@tobie IMO yes, especially now there's many sensible things we can link to (like the MDN `Object.is` page), compared with previously where we only could have linked to the formal `SameValue` definition.

**Pull request merged**
