### PR TITLE
[speech-api] add more suggested reviewers

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@andrenatal @marcoscaceres I noticed on https://github.com/web-platform-tests/wpt/pull/20173 that I'm the only reviewer left after https://github.com/web-platform-tests/wpt/pull/14798. Wanna join?

**Comment by guest271314** [comment]
Am willing to review Web Speech API tests and PR's as long as the tests and PR's are under the parent W3C umbrella.

Am banned from contributing from all WICG repositories, ostensibly for the absurb duration of 1000 years 
1000_year_ban

**Comment by marcoscaceres** [comment]
Sure, happy to join.

**Comment by guest271314** [comment]
Am willing to help review PR's related to Web Speech API.

**Comment by foolip** [comment]
Ping @andrenatal

**Review by andrenatal — APPROVED** [review]

**Comment by foolip** [comment]
@andrenatal I've added you to the reviewers team to give you write access. Please see https://github.com/orgs/web-platform-tests/teams/reviewers/discussions for some things you might want to do to avoid excessive email notifications.

**Pull request merged**
