### PR TITLE
Update interfaces/dom.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/ddd881f/ed/idl/dom.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/677384457

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Firefox stability check timed out, not surprising given the number of tests. 

Results on Chrome and FF look good, but Safari didn't run so kicking the PR to see if we can get Safari results.

**Comment by stephenmcgruer** [comment]
Somehow this seems to break `picture-in-picture/idlharness.window.html` on Safari, not sure how yet. It's consistent though (I kicked the checks a few time to make sure).

**Comment by foolip** [comment]
@stephenmcgruer I think I've seen something funny with the picture-in-picture tests in Safari before, but don't remember exactly what it was. How do things look now with STP 105?

**Comment by stephenmcgruer** [comment]
Looks better even on 104... or maybe something changed with the recent force-push. https://wpt.fyi/results/picture-in-picture/idlharness.window.html?diff&filter=ADC&run_id=473550002&run_id=498800003 is the diff from that run, which looks good.

**Review by stephenmcgruer — APPROVED** [review]

**Pull request merged**
