### PR TITLE
Add media-source delaying-the-load-event-flag reset test from Chromium

### PR DESCRIPTION
**Pull request by wolenetz**
See related spec change at
https://github.com/w3c/media-source/pull/85
See also Chromium change from where this test was adapted for wpt at
https://codereview.chromium.org/2021573002/

Note to wpt reviewers: Please don't merge this until the above two changes have landed and I've updated this PR to indicate any necessary changes that result from those two changes, above.

### CODE REVIEW

**Comment by wolenetz** [comment]
https://codereview.chromium.org/2021573002/ is changing, so I'll need to change this PR once https://codereview.chromium.org/2021573002/ has landed. Please await review until I update here.

**Comment by wolenetz** [comment]
Please review this now; I've updated it (https://github.com/w3c/web-platform-tests/pull/3082/commits/3fd1f14f4778fba1a8ce251b2cc3a1d36ab62447).  The Chromium change is landing today (https://codereview.chromium.org/2021573002/).

**Comment by wolenetz** [comment]
Hmm. Hold on review please. I'll update the style w.r.t. https://codereview.chromium.org/2021573002/#msg31 to conform here.

**Comment by wolenetz** [comment]
Ok this is again ready for review.

**Comment by tidoust** [comment]
This looks good, but cannot there be a race condition between the `sourceopen` event on the `MediaSource` and the `load` event on `window`?

[Spinning the event loop](https://www.w3.org/TR/html51/webappapis.html#spinning-the-event-loop) waits until the condition is met (in our case until the flag is reset) in parallel, then queues a task to resume the algorithm that caused it to [delay the load event](https://www.w3.org/TR/html51/syntax.html#delay-the-load-event), which in turn queues a task to fire the `load` event.

The MSE algorithm that resets the delaying-the-load-event-flag also runs in parallel. Why is there a guarantee that task to fire the `sourceopen` event will be queued before it the task to fire the `load` event?

**Comment by wolenetz** [comment]
I admit I'm not fully clear on the task/microtask stuff that's used in HTMLMediaElement.
IIUC, upon attachment: 'sourceopen' must be queued first (even though the `delaying-the-load-event-flag` is reset just prior to queueing 'sourceopen') because the effect of resetting that flag results in a task queued to resume the various 'delay the load' checks (and eventually queue a 'load' event if necessary). That queued task cannot run until after the 'sourceopen' is queued in step 3 of the attachment Otherwise clause, since they are IIUC tasks queued on the same event loop.

So the test is actually testing Chrome's behavior, which is in opposite of the ordering of these two events per the spec. (See https://codereview.chromium.org/2021573002/diff/40001/third_party/WebKit/LayoutTests/http/tests/media/media-source/mediasource-attach-stops-delaying-load-event.html#newcode32). I don't believe there is a race condition, either.

I'll reverse the sequence ordering in the test and file a Chromium bug to get the impl to match. Though I don't expect the precise ordering of 'load' vs 'sourceopen' in implementations to block MSE v1 PR or REC.

**Comment by tidoust** [comment]
I don't think it matters too much, but let me try to reformulate differently because I still don't get why events fire in any precise order. It certainly should not block anything, and seems very low priority to me.

Let's call the thread that runs the event loop `LoopThread`.

The steps defined in MSE in the [Attaching to a media element](https://w3c.github.io/media-source/#mediasource-attach) section run as part of the [resource fetch algorithm](http://www.w3.org/TR/html51/semantics-embedded-content.html#resource-fetch-algorithm). That algorithm is run *in parallel* by the [resource selection algorithm](http://www.w3.org/TR/html51/semantics-embedded-content.html#resource-selection-algorithm), which means that it runs in a separate thread independent of the event loop. Let's call that thread `FetchThread`.

Before it may fire the `load` event, the browser [spins the event loop](http://www.w3.org/TR/html51/webappapis.html#spinning-the-event-loop) until the `delaying-the-load-event-flag`. The step that waits until this condition is met also runs *in parallel*, which means it runs in another thread, again independent of the event loop. Let's call that thread `SpinThread`.

What could happen is:

1. `FetchThread` runs steps 1, 2, 3 of the MSE algorithm, resetting `delaying-the-load-event-flag` and queues a task to fire the `sourceopen` event.
2. The OS interrupts `FetchThread` and resumes `LoopThread`
3. `LoopThread` runs next task, and fires the `sourceopen` event
4. The OS then resumes `SpinThread`
5. `SpinThread` detects the reset flag and queues a task to resume the [stop parsing](http://www.w3.org/TR/html51/syntax.html#stopped) algorithm, which in turn queues a task to fire the `load` event.

In that case, the `sourceopen` event fires before `load`.

Now, I think the following could happen as well:

1. `FetchThread` runs step 1 of the MSE algorithm, resetting `delaying-the-load-event-flag`.
2. The OS interrupts `FetchThread` right after that and resumes `SpinThread`.
3. `SpinThread` detects the reset flag and queues a task to resume the [stop parsing](http://www.w3.org/TR/html51/syntax.html#stopped) algorithm.
4. The OS decides to switch to `LoopThread`
5. `LoopThread` resumes the stop parsing algorithm, which queues a task to fire the `load` event
6. `LoopThread` runs another event loop and fires the `load` event
7. The OS eventually gets back to `FetchThread`
8. `FetchThread` resumes and runs steps 2 and 3 of the MSE algorithm, queueing a task to fire the `sourceopen` event.

In that case, the `load` event fires before `sourceopen`.

What prevents any of these possibilities?

Note that I have no idea whether this applies to Chromium or to any browser implementation in practice (which may perhaps merge `FetchThread` and `SpinThread` into one single thread).

**Comment by wolenetz** [comment]
@tidoust Thanks for the detailed explanation. The "in parallel" of each of the "delaying-the-load" (`SpinThread` in your example) and the "MSE attachment as part of fetch algorithm as part of resource selection algorithm" (`FetchThread`) can result in racing between the firing of `load` and `sourceopen` per current HTML5.1 and MSE v1 spec. As such, I'll update the Chromium bug to indicate this is low priority, and update the MSE test to just make sure that both the `load` and `sourceopen` events fire within the test timeout (and without any of the `suspend`, `stalled, `progress`, or `error` events occurring before these `load` and `sourceopen` are both fired).

**Comment by wolenetz** [comment]
OK. `load` and `sourceopen` can race each other, so long as both are received before test timeout (or other unexpected event). Note that no init segment is appended, so, importantly, this test is still needed and valid for verifying that the load event is no longer delayed with MSE **before HAVE_METADATA**.

I'll merge this shortly. @tidoust if you see anything wrong, please add comment here or file a w-p-t issue in GH with label media-source.

**Pull request merged**
