### PR TITLE
[appmanifest] add basic tests for start_url

### PR DESCRIPTION
**Pull request by christianliebel**

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Hmm... linter failed but it doesn't seem to provide any info (or I can't figure out the UI to get info). We might need lint locally.

**Comment by stephenmcgruer** [comment]
> Hmm... linter failed but it doesn't seem to provide any info (or I can't figure out the UI to get info). We might need lint locally.

It does, but it's unfortunately still a pain to get to until we land support for github actions 'output'. But if you follow 'View task in Taskcluster' and then 'View Live Log' (a complete pain, we know), you get:

```
./wpt lint --all
ERROR:lint:appmanifest/start_url-member/start_url-member-fail.webmanifest:2: Internal web-platform.test domain used (WEB-PLATFORM.TEST)
ERROR:lint:appmanifest/start_url-member/start_url-member-fail-manual.html:4: Internal web-platform.test domain used (WEB-PLATFORM.TEST)
ERROR:lint:appmanifest/start_url-member/start_url-member-fail-manual.html:9: Internal web-platform.test domain used (WEB-PLATFORM.TEST)
ERROR:lint:appmanifest/start_url-member/start_url-member-fail-manual.html:10: Internal web-platform.test domain used (WEB-PLATFORM.TEST)
INFO:lint:
INFO:lint:There were 4 errors (WEB-PLATFORM.TEST: 4)
INFO:lint:You must fix all errors; for details on how to fix them, see
INFO:lint:https://web-platform-tests.org/writing-tests/lint-tool.html
INFO:lint:
INFO:lint:However, instead of fixing a particular error, it's sometimes
INFO:lint:OK to add a line to the lint.ignore file in the root of the
INFO:lint:web-platform-tests directory to make the lint tool ignore it.
INFO:lint:
INFO:lint:For example, to make the lint tool ignore all 'WEB-PLATFORM.TEST'
INFO:lint:errors in the appmanifest/start_url-member/start_url-member-fail-manual.html file,
INFO:lint:you could add the following line to the lint.ignore file.
INFO:lint:
INFO:lint:WEB-PLATFORM.TEST: appmanifest/start_url-member/start_url-member-fail-manual.html
```

Interestingly, that's also not a particularly useful error message from the linter. Clearly doing that is wrong, but it doesn't explain why or importantly what to use instead.

**Comment by marcoscaceres** [comment]
> Clearly doing that is wrong, but it doesn't explain why or importantly what to use instead.

I had a feeling that was the problem :) Yeah, some guidance there would be really helpful specially for these manual tests.

**Comment by stephenmcgruer** [comment]
> I had a feeling that was the problem :) Yeah, some guidance there would be really helpful specially for these manual tests.

I've sent https://github.com/web-platform-tests/wpt/pull/24720 for this

**Comment by marcoscaceres** [comment]
Thanks @stephenmcgruer! @christianliebel is going to take a look and we should hopefully have a fix next week (@christianliebel we can try to work on these together next Monday if the changes look tricky).

**Comment by christianliebel** [comment]
@marcoscaceres Fixed! Thank you, @stephenmcgruer.

**Review by marcoscaceres — APPROVED** [review]
Awesome! nice one @christianliebel.

**Pull request merged**
