### PR TITLE
Roll webidl2.js to master

### LINKED ISSUE #23328: Incorporate latest webidl2.js updates into idlharness
This is a tracking issue. In particular, I am interested in https://github.com/w3c/webidl2.js/commit/4d22d721fa2cc12ca3058d4be79e26e69c736421 and the not-yet-merged https://github.com/w3c/webidl2.js/pull/466 . Presumably once those are finished there will be a new release of webidl2.js, and we can roll that in.

/cc @saschanaz.

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This updates webidl2.js to
https://github.com/w3c/webidl2.js/commit/6107689a9241d2b37e6741b58fa23074623ff23b

Fixes https://github.com/web-platform-tests/wpt/issues/23328

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
cc @saschanaz who would better know than anyone I think if the diff looks right

I'm going to run this through some trigger branches for Chrome Dev, Firefox Nightly, and STP, as the best way I can think of to tease out regressions or issues.

**Comment by stephenmcgruer** [comment]
Pushed to [chrome dev](https://community-tc.services.mozilla.com/tasks/groups/byiGPwLrRXCdvqJPf6lGtw), [firefox nightly](https://community-tc.services.mozilla.com/tasks/groups/Gg4dTNsdQV20T78foRqdOg), and [safari preview](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=47396&view=results) (not 100% sure that last link is the right one).

Will grab the results from wpt.fyi once they're done and post some comparison links.

**Comment by saschanaz** [comment]
Diff looks good to me 👍

**Comment by stephenmcgruer** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=511020001&run_id=532070004 has the diff for Chrome.

https://wpt.fyi/results/?diff&filter=ADC&run_id=511030001&run_id=517030001 has the diff for Firefox.

I do see a number of regressions, but they may be correct, need to dig in.

**Comment by stephenmcgruer** [comment]
From a random sample, looks like they're all failing validation of something from `html`:

```
FAIL message: Validation error at line 1507 in html, inside `argument flags`:
  void setValidity(ValidityStateFlags flags,
                                      ^ Dictionary argument must be optional if it has no required fields
```

**Comment by saschanaz** [comment]
While the validation itself is correct, the "inside `argument flags`:" part should mention ElementInternals to be more informational. I'll fix it.

**Comment by stephenmcgruer** [comment]
> While the validation itself is correct, the "inside argument flags:" part should mention ElementInternals to be more informational. I'll fix it.

Thanks, that would be useful :)

cc @domenic and @annevk - would it be reasonable to change the html spec here (https://html.spec.whatwg.org/multipage/custom-elements.html#elementinternals) to have the 'flags' option for 'setValidity' be optional as per the error message? Otherwise every single idlharness test that depends on `html` will fail its validation checks, or we will need to implement some sort of workaround for it.

**Comment by annevk** [comment]
Very reasonable as that's a bug 😊

**Comment by stephenmcgruer** [comment]
> Very reasonable as that's a bug 😊

I should have been clearer - could I persuade one of you two to sign up to fix it soon? :D

**Comment by stephenmcgruer** [comment]
I have pushed new triggers on d402b3683f45c00a3b2dc720fea8c3b7ac1c9bd8 which should include the HTML update from annevk's (amazingly fast) changes. Hopefully these should have no regressions :)

**Comment by stephenmcgruer** [comment]
Ok, next round! 

https://wpt.fyi/results/?diff&filter=ADC&run_id=524710001&run_id=536060001
https://wpt.fyi/results/?diff&filter=ADC&run_id=524700001&run_id=522530004

Sorting through the flakes, I find 3 idlharness tests that have 'regressions' (looks like 2 root causes). I assume they are actually IDL errors, so it seems reasonable to accept these (along with filing spec issues to fix them). Can you take a quick look @saschanaz ?

`wpt /FileAPI/idlharness.{worker.}html`:
```
FAIL message: promise_test: Unhandled rejection with value: object "WebIDLParseError: Syntax error at line 1:
,Worker)] interface ArrayBuffer {};
                    ^ Missing name in interface"
```

`trusted-types/idlharness.tentative.https.window.html`:
```
FAIL message: Validation error at line 32 in trusted-types.tentative, inside `argument policyOptions`:
(DOMString policyName, TrustedTypePolicyOptions policyOptions);
                                                ^ Dictionary argument must be optional if it has no required fields
```

`wasm/jsapi/idlharness.any.{worker.}html`:
```
FAIL message: promise_test: Unhandled rejection with value: object "WebIDLParseError: Syntax error at line 1:
,Worker)] interface ArrayBuffer {};
                    ^ Missing name in interface"
```

**Comment by domenic** [comment]
@stephenmcgruer the problem is that those tests include a line re-declaring ArrayBuffer as an interface: https://github.com/web-platform-tests/wpt/blob/master/FileAPI/idlharness.worker.js#L12

That's not IDL from the spec, so it's more of a test bug than a spec bug.

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer the problem is that those tests include a line re-declaring ArrayBuffer as an interface: https://github.com/web-platform-tests/wpt/blob/master/FileAPI/idlharness.worker.js#L12
>
> That's not IDL from the spec, so it's more of a test bug than a spec bug.

Great catch, sorry for not checking it myself. ArrayBuffer is a built-in type, right, so those lines are doing nothing currently?

**Comment by domenic** [comment]
They seem likely to be added to try to address https://github.com/web-platform-tests/wpt/issues/23346.

**Comment by saschanaz** [comment]
Replacing the name to `_ArrayBuffer` (`_` as an escaper) should fix it.

**Comment by stephenmcgruer** [comment]
> They seem likely to be added to try to address #23346.

This seems likely. I think at this point we should go ahead with this PR, and let these three tests 'regress'. Then we can follow up with a spec issue for `trusted-types` and test fixes for the other two.

**Review by domenic — APPROVED** [review]
Confirmed I can now use async iterables. Yay!

**Pull request merged**
