### PR TITLE
Revert "Update orientation-sensor IDL file"

### PR DESCRIPTION
**Pull request by Honry**
Reverts w3c/web-platform-tests#9795

### CODE REVIEW

**Comment by foolip** [comment]
No need to revert this, just wait for another automatic update :)

Some differences to show that our tooling is working is a good thing!

**Comment by Honry** [comment]
Oops, I forget the stray whitespace had been remove in latest spec.

**Comment by Honry** [comment]
@foolip, thanks, the tooling is pretty good!

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25421)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350155619)

**Pull request closed without merging**
