### PR TITLE
WebDriver BiDi: fix generator serialization test

### PR DESCRIPTION
**Pull request by OrKoN**
[Generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) is an object that is returned by a generator function.

Make a distinction between generator functions and generator objects.

### CODE REVIEW

**Comment by OrKoN** [comment]
@thiagowfx PTAL first

**Review by thiagowfx — APPROVED** [review]

**Comment by OrKoN** [comment]
@whimboo PTAL

**Review by whimboo — APPROVED** [review]
Good catch. Thanks for the fix.

**Comment by thiagowfx** [comment]
cc @jgraham @gsnedders @DanielRyanSmith please admin merge.

**Pull request merged**
