### PR TITLE
[WebDriver BiDi] Use Meta instead of OS

### PR DESCRIPTION
**Pull request by jrandolf**
Reverts web-platform-tests/wpt#40566

### CODE REVIEW

**Comment by whimboo** [comment]
FYI this will basically re-land the PR 40122.

@jrandolf please rebase to latest main so that we get passing Firefox stability tests. Thanks.

**Comment by whimboo** [comment]
@jrandolf could we maybe make this PR only about the change of the Meta keys and do the numpad keys in a different PR?

**Comment by jrandolf** [comment]
> @jrandolf could we maybe make this PR only about the change of the Meta keys and do the numpad keys in a different PR?

Done.

**Comment by whimboo** [comment]
@jrandolf would you mind rebasing the PR to latest master? The tests as run especially for Chrome look strange, and I don't understand why the network interception ones were run which shouldn't be affected by this change.

**Comment by jrandolf** [comment]
> @jrandolf would you mind rebasing the PR to latest master? The tests as run especially for Chrome look strange, and I don't understand why the network interception ones were run which shouldn't be affected by this change.

Done.

**Comment by whimboo** [comment]
The stability tests are still failing but I assume that this happens again because the change triggered quite too many tests from the wdspec test suite. Nevertheless all the current failures for Firefox will be fixed by this change so for me this looks good.

I would still like to see a review from someone from Google and @gsnedders.

Thanks!

**Review by whimboo — APPROVED** [review]

**Review by OrKoN — APPROVED** [review]

**Review by gsnedders — APPROVED** [review]

**Comment by foolip** [comment]
Force merging at the request of @jrandolf.

**Pull request merged**
