### PR TITLE
Add tests for entries-api

### PR DESCRIPTION
**Pull request by inexorabletash**
These tests cover the file entry, directory entry, directory reader and filesystem types implemented in Chrome, Edge and Firefox to support "directory upload". A draft specification for the common behavior is at: https://wicg.github.io/entries-api/

The tests are primarily manual, requiring dragging particular directories.

Local testing shows a high pass rate in Chrome and Firefox. Chrome throws incorrect errors in several cases, and does not expose the interfaces as named in the draft. Firefox does not implement exactly the same path validation or traversal logic and common ancestor pruning.

### CODE REVIEW

**Comment by inexorabletash** [comment]
I've never been happy with the short name of the spec (or even the need for it to exist), but copying it here for consistency.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238875253)

# Firefox (nightly) #
Testing web-platform-tests at revision ab1594c55feeb7b86b6982a6a5abcd69c17df404
Using browser at version BuildID 20170602100143; SourceStamp aeb3d0ca558f034cbef1c5a68bd07dd738611494
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6142/entries-api/interfaces.html">/entries-api/interfaces.html</a></summary>


|                                                            Subtest                                                             | Results | Messages |
|--------------------------------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                                                | OK      |          |
| `Entries API: IDL`                                                                                                             | PASS    |          |
| `File interface: attribute webkitRelativePath`                                                                                 | PASS    |          |
| `File must be primary interface of new File([], "example.txt")`                                                                | PASS    |          |
| `Stringification of new File([], "example.txt")`                                                                               | PASS    |          |
| `File interface: new File([], "example.txt") must inherit property "webkitRelativePath" with the proper type (0)`              | PASS    |          |
| `HTMLInputElement interface: attribute webkitdirectory`                                                                        | PASS    |          |
| `HTMLInputElement interface: attribute webkitEntries`                                                                          | PASS    |          |
| `HTMLInputElement must be primary interface of document.createElement("input")`                                                | PASS    |          |
| `Stringification of document.createElement("input")`                                                                           | PASS    |          |
| `HTMLInputElement interface: document.createElement("input") must inherit property "webkitdirectory" with the proper type (0)` | PASS    |          |
| `HTMLInputElement interface: document.createElement("input") must inherit property "webkitEntries" with the proper type (1)`   | PASS    |          |
| `DataTransferItem interface: operation webkitGetAsEntry()`                                                                     | PASS    |          |
| `ErrorCallback interface: existence and properties of interface object`                                                        | PASS    |          |
| `ErrorCallback interface: existence and properties of interface prototype object`                                              | PASS    |          |
| `ErrorCallback interface: existence and properties of interface prototype object's "constructor" property`                     | PASS    |          |
| `ErrorCallback interface: operation handleEvent(DOMException)`                                                                 | PASS    |          |
| `FileSystemEntry interface: existence and properties of interface object`                                                      | PASS    |          |
| `FileSystemEntry interface object length`                                                                                      | PASS    |          |
| `FileSystemEntry interface object name`                                                                                        | PASS    |          |
| `FileSystemEntry interface: existence and properties of interface prototype object`                                            | PASS    |          |
| `FileSystemEntry interface: existence and properties of interface prototype object's "constructor" property`                   | PASS    |          |
| `FileSystemEntry interface: attribute isFile`                                                                                  | PASS    |          |
| `FileSystemEntry interface: attribute isDirectory`                                                                             | PASS    |          |
| `FileSystemEntry interface: attribute name`                                                                                    | PASS    |          |
| `FileSystemEntry interface: attribute fullPath`                                                                                | PASS    |          |
| `FileSystemEntry interface: attribute filesystem`                                                                              | PASS    |          |
| `FileSystemEntry interface: operation getParent(FileSystemEntryCallback,ErrorCallback)`                                        | PASS    |          |
| `FileSystemDirectoryEntry interface: existence and properties of interface object`                                             | PASS    |          |
| `FileSystemDirectoryEntry interface object length`                                                                             | PASS    |          |
| `FileSystemDirectoryEntry interface object name`                                                                               | PASS    |          |
| `FileSystemDirectoryEntry interface: existence and properties of interface prototype object`                                   | PASS    |          |
| `FileSystemDirectoryEntry interface: existence and properties of interface prototype object's "constructor" property`          | PASS    |          |
| `FileSystemDirectoryEntry interface: operation createReader()`                                                                 | PASS    |          |
| `FileSystemDirectoryEntry interface: operation getFile(USVString,FileSystemFlags,FileSystemEntryCallback,ErrorCallback)`       | PASS    |          |
| `FileSystemDirectoryEntry interface: operation getDirectory(USVString,FileSystemFlags,FileSystemEntryCallback,ErrorCallback)`  | PASS    |          |
| `FileSystemEntryCallback interface: existence and properties of interface object`                                              | PASS    |          |
| `FileSystemEntryCallback interface: existence and properties of interface prototype object`                                    | PASS    |          |
| `FileSystemEntryCallback interface: existence and properties of interface prototype object's "constructor" property`           | PASS    |          |
| `FileSystemEntryCallback interface: operation handleEvent(FileSystemEntry)`                                                    | PASS    |          |
| `FileSystemDirectoryReader interface: existence and properties of interface object`                                            | PASS    |          |
| `FileSystemDirectoryReader interface object length`                                                                            | PASS    |          |
| `FileSystemDirectoryReader interface object name`                                                                              | PASS    |          |
| `FileSystemDirectoryReader interface: existence and properties of interface prototype object`                                  | PASS    |          |
| `FileSystemDirectoryReader interface: existence and properties of interface prototype object's "constructor" property`         | PASS    |          |
| `FileSystemDirectoryReader interface: operation readEntries(FileSystemEntriesCallback,ErrorCallback)`                          | PASS    |          |
| `FileSystemEntriesCallback interface: existence and properties of interface object`                                            | PASS    |          |
| `FileSystemEntriesCallback interface: existence and properties of interface prototype object`                                  | PASS    |          |
| `FileSystemEntriesCallback interface: existence and properties of interface prototype object's "constructor" property`         | PASS    |          |
| `FileSystemEntriesCallback interface: operation handleEvent([object Object])`                                                  | PASS    |          |
| `FileSystemFileEntry interface: existence and properties of interface object`                                                  | PASS    |          |
| `FileSystemFileEntry interface object length`                                                                                  | PASS    |          |
| `FileSystemFileEntry interface object name`                                                                                    | PASS    |          |
| `FileSystemFileEntry interface: existence and properties of interface prototype object`                                        | PASS    |          |
| `FileSystemFileEntry interface: existence and properties of interface prototype object's "constructor" property`               | PASS    |          |
| `FileSystemFileEntry interface: operation file(FileCallback,ErrorCallback)`                                                    | PASS    |          |
| `FileCallback interface: existence and properties of interface object`                                                         | PASS    |          |
| `FileCallback interface: existence and properties of interface prototype object`                                               | PASS    |          |
| `FileCallback interface: existence and properties of interface prototype object's "constructor" property`                      | PASS    |          |
| `FileCallback interface: operation handleEvent(File)`                                                                          | PASS    |          |
| `FileSystem interface: existence and properties of interface object`                                                           | PASS    |          |
| `FileSystem interface object length`                                                                                           | PASS    |          |
| `FileSystem interface object name`                                                                                             | PASS    |          |
| `FileSystem interface: existence and properties of interface prototype object`                                                 | PASS    |          |
| `FileSystem interface: existence and properties of interface prototype object's "constructor" property`                        | PASS    |          |
| `FileSystem interface: attribute name`                                                                                         | PASS    |          |
| `FileSystem interface: attribute root`                                                                                         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238875254)

# Sauce (safari) #
Testing web-platform-tests at revision ab1594c55feeb7b86b6982a6a5abcd69c17df404
Using browser at version 10.0
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238875267)

# Chrome (unstable) #
Testing web-platform-tests at revision ab1594c55feeb7b86b6982a6a5abcd69c17df404
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238875268)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ab1594c55feeb7b86b6982a6a5abcd69c17df404
Using browser at version 14.14393
Starting 10 test iterations

**Comment by jgraham** [comment]
@jwatt - Is this something you can review?

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18231)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/272659224)

**Comment by inexorabletash** [comment]
Ping? Anyone? Looks like Safari has added support too:

https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by inexorabletash** [comment]
cc: @sideshowbarker

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
