### PR TITLE
Added 13 basic box-shadow tests

### PR DESCRIPTION
**Pull request by TalbotG**
box-shadow-021.html
box-shadow-022.html
box-shadow-023.html
box-shadow-024.html
box-shadow-025.html
box-shadow-026.html

box-shadow-029.html

box-shadow-031.html
box-shadow-032.html
box-shadow-033.html
box-shadow-034.html
box-shadow-035.html
box-shadow-036.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
I'd like us to simplify these tests down to make them more understandable. **The priority in designing tests is not to make tests match a common reference file. It is to make the tests understandable to read, rigorous in their pass conditions, and efficient to run.**

For all the box-shadow-02* tests:

1. Eliminate the red overlapped reference. It is easy enough to evaluate whether we have a square or not, we don't need the red to highlight mispainting.
2. Combine them all into a single file.
3. Use two different semi-transparent colors for the shadow and the background, so that we can be sure that the UA is painting them each in the correct places and not overlapping them.
4. Create a custom reference file for the result.

For all the box-shadow-03* tests:

1. Same as above, eliminate the red overlapped reference.
2. Combine them all into a single file.
3. Use an opaque background and a semi-transparent shadow color, so that we can be sure the UA is painting each in the correct places and overlapping them correctly.
4. Do not use 100% coverage for the inset shadow, otherwise we can't tell what the UA is actually doing. Use different numbers in each axis so we know they are getting assigned correctly, and make it cover less than 100% in each axis so that some of the box is *not* covered by the shadow.
5. Create a custom reference file for the result.

**Comment by TalbotG** [comment]
> 2. Combine them all into a single file.

I can try but I have also to comply with the [600x600 viewport size for reftests constraint](https://github.com/web-platform-tests/wpt/issues/5403)

**Comment by TalbotG** [comment]
> For all the box-shadow-02* tests:

Progress so far: no red overlapped, -021 to -026 combined, 2 different semi-transparent colors for the shadow and the background :

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-021-new.html

a custom reference file:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-021-ref.html

029 is an edge case: I think it would be best to leave it as a lone test.

**Comment by fantasai** [comment]
> I can try but I have also to comply with the 600x600 viewport size for reftests constraint

You can always make them smaller. :) There's no need to use as much as 100px.

You should add a (double or transparent) border to the boxes, so we can be sure the shadow is not painted in the border area.

The pass condition description isn't very precise. I would maybe leave it out, and just let this be a reftest.

**Comment by TalbotG** [comment]
> For all the box-shadow-03* tests:

Progress so far (**still not finished yet on 20200818**): no red overlapped, -031 to -036 combined, an opaque background and a semi-transparent shadow color, not using 100% coverage for the inset shadow:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-031-new.html

a custom reference file:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-031-ref.html

**Comment by TalbotG** [comment]
Smaller (36px by 36px) boxes
with a thick (12px) double border to the boxes and
with pass condition description left out:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-021-newer.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-021-ref-newer.html

**Comment by TalbotG** [comment]
No red overlapped, -031 to -036 combined, an opaque background and a semi-transparent shadow color, not using 100% coverage for the inset shadow, adding a thick (12px) double border on boxes:

http://www.gtalbot.org//BrowserBugsSection/CSS3Backgrounds/box-shadow-031-newer.html

and a custom reference:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-031-ref-newer.html

I will submit these in a new commit tomorrow.

**Pull request closed without merging**
