### PR TITLE
[wptrunner] Cycle testdriver event loop when testharness isn't loaded

### PR DESCRIPTION
**Pull request by jonathan-j-lee**
Workaround for https://crbug.com/340662810 that seems to work without an increase in test runtime or regressions (https://crrev.com/c/5698330/9). On Windows (the affected platform):
* [With patch]: 225 min total shard runtime, 1873 regressions, 322 unexpected timeouts
* [Without patch]: 225 min total shard runtime, 1888 regressions, 326 unexpected timeouts

[With patch]: https://ci.chromium.org/ui/p/chromium/builders/try/win10-wpt-chromium-rel/130/overview
[Without patch]: https://ci.chromium.org/ui/p/chromium/builders/ci/win10-wpt-chromium-rel/3594/overview

Waiting for the `load` event doesn't seem to work (https://crrev.com/c/5698330/7).

### CODE REVIEW

**Review by WeizhongX — APPROVED** [review]
Thanks for the fix.

This does not happen to a lot of tests, so should not have an impact on total test time.

**Comment by jonathan-j-lee** [comment]
> This does not happen to a lot of tests

I was running into a lot of failed flakiness checks, so hopefully this should mitigate that.

> should not have an impact on total test time.

My worry was that `testharnessreport.js` would never load correctly, which would cause the executor to spin indefinitely. But as shown, that does not seem to be the case.

**Comment by WeizhongX** [comment]
> > This does not happen to a lot of tests
> 
> I was running into a lot of failed flakiness checks, so hopefully this should mitigate that.
> 
> > should not have an impact on total test time.
> 
> My worry was that `testharnessreport.js` would never load correctly, which would cause the executor to spin indefinitely. But as shown, that does not seem to be the case.

If this happens, will the test timeout?

**Comment by jonathan-j-lee** [comment]
> If this happens, will the test timeout?

Hypothetically, it would, I think, since even non-testdriver testharness tests use the message queue/testdriver loop to signal completion. The executor process would report `EXTERNAL-TIMEOUT` and need to be killed by its `TestRunnerManager`.

**Pull request merged**
