### PR TITLE
Add tests for named constructors.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by Ms2ger** [comment]
## Unstable results ##
|                      Test                     | Subtest |          Results          | Messages |
|-----------------------------------------------|---------|---------------------------|----------|
| `/css/css-font-loading/idlharness.https.html` |         | **ERROR: 6/10, OK: 4/10** |          |

doesn't seem like ti should block merging.

**Comment by jgraham** [comment]
From Firefox:

## Unstable results ##
|                             Test                             |                                     Subtest                                      |          Results           |                 Messages                |
|--------------------------------------------------------------|----------------------------------------------------------------------------------|----------------------------|-----------------------------------------|
| `/css/geometry/interfaces.worker.html`                       | `Test default toJSON operation of toJSON object`                                 | **FAIL: 60/10**            | `memberHolderObject is undefined`       |
| `/html/dom/interfaces.https.html?include=(Document\|Window)` | `Window interface: window must inherit property "onunload" with the proper type` | **FAIL: 9/10, PASS: 1/10** | `Unrecognized type EventHandlerNonNull` 

From Chrome:
## Unstable results ##
|                      Test                     | Subtest |          Results          | Messages |
|-----------------------------------------------|---------|---------------------------|----------|
| `/css/css-font-loading/idlharness.https.html` |         | **ERROR: 6/10, OK: 4/10** |          |

**Comment by foolip** [comment]
The Chrome flakiness was https://github.com/web-platform-tests/wpt/issues/14862 and should be resolved as of yesterday.

The Firefox issues are https://github.com/web-platform-tests/wpt/issues/14254 and https://github.com/web-platform-tests/wpt/issues/14645.

**Comment by Ms2ger** [comment]
@foolip pls take a look at the failure

**Comment by foolip** [comment]
@Ms2ger the remaining failure is in Firefox, have you checked if it's #14254 or #14645? (The logs are huge, need to download them to check.)

**Comment by Ms2ger** [comment]
Log seems to say

```
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

on line 3.958.598.

**Comment by foolip** [comment]
Huh, I haven't seen that before. @jgraham WDYT?

**Comment by Ms2ger** [comment]
Looks like this keeps timing out in Firefox; probably it can't handle the amount of tests that idlharness changes cause to run. @foolip, could you force-merge?

**Comment by foolip** [comment]
Logs end with "Task timeout after 7200 seconds" so that sounds right. I'll merge.

**Pull request merged**
