### PR TITLE
Added a test in response to Issue 2747813006 (https://codereview.chromium.org/2747813006/) and upstreamed it to wpt


### PR DESCRIPTION
**Pull request by jeffcarp**
BUG=701562

Review-Url: https://codereview.chromium.org/2787103002
Cr-Commit-Position: refs/heads/master@{#461284}

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218158282)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d5b7d5ec89eb59529e38ea2baf3b19578d53c26c
Using browser at version BuildID 20170403100136; SourceStamp 38894655c89e68bcd8f45d31a0d3005f2c2b53db
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218158283)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d5b7d5ec89eb59529e38ea2baf3b19578d53c26c
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by jeffcarp** [comment]
Travis is failing due to lint errors, I will fix them in a bit.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5323/)

**Pull request merged**
