### PR TITLE
Jazh

### PR DESCRIPTION
**Pull request by r12a**
Test format updated to match latest i18n test suite files. Includes fixes for missing lang attributes.
中文 -> 文字
Linked to font at /fonts
CSS font meta tag removed.
Tabs, trailing spaces, and unnecessary newlines removed.
More metadata removed from ref files.
This PR includes and makes redundant https://github.com/w3c/web-platform-tests/pull/9805#issuecomment-370396113

The font at /fonts is not included in this PR. See https://github.com/w3c/web-platform-tests/pull/9818 for that.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2018-03-06 10:00:12
Finished: 2018-03-06 10:35:53


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25353)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349734258)

**Comment by r12a** [comment]
Can someone explain to me what went wrong to produce conflicts? Thanks.

**Comment by gsnedders** [comment]
Probably e45d0cf81b1ed64f877279a75c0ffd112fa7741e landing combined with the whitespace changes on this branch making git unable to merge automatically.

**Comment by r12a** [comment]
Now that https://github.com/w3c/web-platform-tests/pull/9718#issuecomment-371744493 has been reverted, how do i remove the conflict messages from this PR? (Assuming that that was the cause.)

**Comment by gsnedders** [comment]
It wasn't reverted in the end.

**Comment by r12a** [comment]
Yeah. I'm waiting for the dust to settle, then i'll sort this out.
It also depends on https://github.com/w3c/web-platform-tests/pull/9818 - any plans in that regard?

**Comment by r12a** [comment]
Closing this to resubmit a clean version later.

**Pull request closed without merging**
