### PR TITLE
[css-text] Check hanging of trailing white-space with pre-wrap

### PR DESCRIPTION
**Pull request by frivoal**
Tests for https://github.com/w3c/csswg-drafts/issues/3116

### CODE REVIEW

**Comment by frivoal** [comment]
This addresses https://github.com/web-platform-tests/wpt/issues/13019

**Review by foolip — APPROVED** [review]
I've done some pretty light review. Have you run these to see if they pass in any browsers, or fail? (That's a much better review step than someone reading the tests.)

**Comment by frivoal** [comment]
The first one passes in safari and fails in other browsers (did not check edge). Other others fail differently in different browsers (still did not check edge). Interop wasn't expected, since it's an area where the spec is trying to pave the way to sanity out of the current mess.

**Comment by frivoal** [comment]
Anyway, let's merge. We had agreement in the WG, and if implementors want to discagree, they need to discover it, and tests are a good way to do that.

**Pull request merged**
