### PR TITLE
Update Element-classlist.html to cover edge case

### PR DESCRIPTION
**Pull request by cdumez**
Update Element-classlist.html to cover edge case at:
- https://github.com/whatwg/dom/issues/442

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5725)

### CODE REVIEW

**Comment by cdumez** [comment]
@annevk @domenic @ayg r?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5725/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226541925)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226541927)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 5f22c17e2db953c1256cab91522f08d643798e04
Using browser at version BuildID 20170427100655; SourceStamp 0b77ed3f26c5335503bc16e85b8c067382e7bb1e
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5725/dom/nodes/Element-classlist.html">/dom/nodes/Element-classlist.html</a></summary>


|                                                 Subtest                                                 | Results | Messages |
|---------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                         | OK      |          |
| `Element.classList must exist as an object`                                                             | PASS    |          |
| `Element.classList must exist as an object even if the element has no class attribute`                  | PASS    |          |
| `DOMTokenList should be exposed for prototyping`                                                        | PASS    |          |
| `prototyping DOMTokenList should work`                                                                  | PASS    |          |
| `Element.classList must implement DOMTokenList`                                                         | PASS    |          |
| `CSS .foo selectors must not match elements without any class`                                          | PASS    |          |
| `classList must be correct for an element that has classes`                                             | PASS    |          |
| `classList.length must be 0 for an element that has no classes`                                         | PASS    |          |
| `classList must not contain an undefined class`                                                         | PASS    |          |
| `classList.item() must return null for out-of-range index`                                              | PASS    |          |
| `classList.item() must return null for negative index`                                                  | PASS    |          |
| `classList[index] must be undefined for out-of-range index`                                             | PASS    |          |
| `classList[index] must be undefined for negative index`                                                 | PASS    |          |
| `className should contain initial markup whitespace`                                                    | PASS    |          |
| `classList should contain initial markup whitespace`                                                    | PASS    |          |
| `.contains(empty_string) must return false`                                                             | PASS    |          |
| `.add(empty_string) must throw a SYNTAX_ERR`                                                            | PASS    |          |
| `.remove(empty_string) must throw a SYNTAX_ERR`                                                         | PASS    |          |
| `.toggle(empty_string) must throw a SYNTAX_ERR`                                                         | PASS    |          |
| `.replace with empty_string must throw a SYNTAX_ERR`                                                    | PASS    |          |
| `.contains(string_with_spaces) must return false`                                                       | PASS    |          |
| `.add(string_with_spaces) must throw an INVALID_CHARACTER_ERR`                                          | PASS    |          |
| `.remove(string_with_spaces) must throw an INVALID_CHARACTER_ERR`                                       | PASS    |          |
| `.toggle(string_with_spaces) must throw an INVALID_CHARACTER_ERR`                                       | PASS    |          |
| `.replace with string_with_spaces must throw a INVALID_CHARACTER_ERR`                                   | PASS    |          |
| `.replace with an already existing token`                                                               | PASS    |          |
| `computed style must update when setting .className`                                                    | PASS    |          |
| `classList.contains must update when .className is changed`                                             | PASS    |          |
| `classList.contains must be case sensitive`                                                             | PASS    |          |
| `classList.contains must not match when punctuation characters are added`                               | PASS    |          |
| `classList.add must not cause the CSS selector to stop matching`                                        | PASS    |          |
| `classList.add must not remove existing classes`                                                        | PASS    |          |
| `classList.contains case sensitivity must match a case-specific string`                                 | PASS    |          |
| `classList.length must correctly reflect the number of tokens`                                          | PASS    |          |
| `classList.item(0) must return the first token`                                                         | PASS    |          |
| `classList.item must return case-sensitive strings and preserve token order`                            | PASS    |          |
| `classList[0] must return the first token`                                                              | PASS    |          |
| `classList[index] must return case-sensitive strings and preserve token order`                          | PASS    |          |
| `classList[index] must still be undefined for out-of-range index when earlier indexes exist`            | PASS    |          |
| `className must update correctly when items have been added through classList`                          | PASS    |          |
| `classList must stringify correctly when items have been added`                                         | PASS    |          |
| `classList.add should not add a token if it already exists`                                             | PASS    |          |
| `classList.remove removes arguments passed, if they are present.`                                       | PASS    |          |
| `classList.remove must remove existing tokens`                                                          | PASS    |          |
| `classList.remove must not break case-sensitive CSS selector matching`                                  | PASS    |          |
| `classList.remove must remove duplicated tokens`                                                        | PASS    |          |
| `classList.remove must collapse whitespace around removed tokens`                                       | PASS    |          |
| `classList.remove must collapse whitespaces around each token`                                          | PASS    |          |
| `classList.remove must collapse whitespaces around each token and remove duplicates`                    | PASS    |          |
| `classList.remove must collapse whitespace when removing duplicate tokens`                              | PASS    |          |
| `classList.add must collapse whitespaces and remove duplicates when adding a token that already exists` | PASS    |          |
| `classList.toggle must toggle tokens case-sensitively when adding`                                      | PASS    |          |
| `classList.toggle must not break case-sensitive CSS selector matching`                                  | PASS    |          |
| `classList.toggle must be able to remove tokens`                                                        | PASS    |          |
| `classList.toggle must be case-sensitive when removing tokens`                                          | PASS    |          |
| `classList.replace replaces arguments passed, if they are present.`                                     | PASS    |          |
| `classList.replace must replace existing tokens`                                                        | PASS    |          |
| `classList.replace must not break case-sensitive CSS selector matching`                                 | PASS    |          |
| `classList.replace must replace duplicated tokens`                                                      | PASS    |          |
| `classList.replace must collapse whitespace around replaced tokens`                                     | PASS    |          |
| `classList.replace must collapse whitespaces around each token`                                         | PASS    |          |
| `classList.replace must collapse whitespaces around each token and remove duplicates`                   | PASS    |          |
| `classList.replace must collapse whitespace when replacing duplicate tokens`                            | PASS    |          |
| `CSS class selectors must stop matching when all classes have been removed`                             | PASS    |          |
| `className must be empty when all classes have been removed`                                            | PASS    |          |
| `classList must stringify to an empty string when all classes have been removed`                        | PASS    |          |
| `classList.item(0) must return null when all classes have been removed`                                 | PASS    |          |
| `classList[0] must be undefined when all classes have been removed`                                     | PASS    |          |
| `Invoking add or remove should set the class attribute`                                                 | PASS    |          |
| `classList.add should treat " " as a space`                                                             | PASS    |          |
| `classList.add should treat \t as a space`                                                              | PASS    |          |
| `classList.add should treat \r as a space`                                                              | PASS    |          |
| `classList.add should treat \n as a space`                                                              | PASS    |          |
| `classList.add should treat \f as a space`                                                              | PASS    |          |
| `classList.length must be read-only`                                                                    | PASS    |          |
| `classList must have [PutForwards=value]`                                                               | PASS    |          |
| `classList.replace should work`                                                                         | PASS    |          |
| `classList.supports should throw`                                                                       | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226541933)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 5f22c17e2db953c1256cab91522f08d643798e04

**Comment by ayg** [comment]
FTR, I think this change is going to be overwritten by a rewrite of this file incoming from Mozilla.

**Pull request merged**
