### PR TITLE
Revert "Various test fixes for python3 support. (#11769)"

### LINKED ISSUE #13204: Many tests in /cookies/http-state consistently time out on Taskcluster but not on BuildBot
https://staging.wpt.fyi/results/cookies/http-state?sha=b040cb2a07&product=firefox[experimental,taskcluster]&product=firefox[buildbot,experimental]&diff=true
https://staging.wpt.fyi/results/cookies/http-state?sha=b040cb2a07&product=chrome[experimental,taskcluster]&product=chrome[buildbot,experimental]&diff=true

Presumably, the tests are a bit slow. I'll try to give them long timeout.

### PR DESCRIPTION
**Pull request by gsnedders**
This reverts commit 5bd512cdc76f762662915a2d3d9e49b021f14ff6.

Fixes #13204.

### CODE REVIEW

**Review by Ms2ger — DISMISSED** [review]
Given that there are two open PRs that fix the issue, I don't see a point in reverting.

**Comment by jgraham** [comment]
I agree that fixing this makes more sense than reverting.

**Comment by gsnedders** [comment]
My goal here was simply to get these regressed tests working again ASAP, and then it avoids the urgency (of the currently both r-'d) fixes.

**Review by foolip — APPROVED** [review]
Approving per my thoughts in https://github.com/web-platform-tests/wpt/issues/13204#issuecomment-425475729, but will still require @Ms2ger to sign off. Still around?

**Review by Hexcles — APPROVED** [review]
Looks like both attempted fixes have some non-trivial discussions. I agree with @gsnedders ; let's land the revert first.

**Comment by jgraham** [comment]
Sorry, I hadn't realised that the other PRs had outstanding issues.

**Comment by foolip** [comment]
Thanks all, when Travis has finished on this one let's merge ASAP.

@Ms2ger @Hexcles would the best thing be to bake your two changes into a single PR?

**Comment by Hexcles** [comment]
@foolip yeah the duplicate work and bad timing were unfortunate. Once the discussions in the PRs clear up, we'll see how to best proceed.

**Pull request merged**
