### PR TITLE
Split the big test() up into multiple small ones

### PR DESCRIPTION
**Pull request by cbiesinger**
Also test the computed style on a <picture> with a loaded image.

Addresses the review comments in
https://github.com/web-platform-tests/wpt/pull/27745

### CODE REVIEW

**Review by domenic — COMMENTED** [review]
Could you add getComputedStyle().width/height tests for both the img and the source elements, in all cases? I'm not even sure what the result should be, per https://github.com/whatwg/html/pull/5894/files#r582084336 , but probably you are...

**Comment by cbiesinger** [comment]
Nothing should get mapped to `<source>`'s style. I will add tests to ensure that. I can add some more tests for img's width/height mapping, but testing this is annoying since it only works on display:none.

BTW, I am planning to land the blink implementation patch tonight CET together with the test to ensure that it makes it into the branch, but I will certainly make sure to address any further comments afterwards.

**Comment by cbiesinger** [comment]
@domenic I added tests for that now.

**Review by domenic — APPROVED** [review]
Tests LGTM. I would ideally like another set of eyes, such as @emilio or @annevk or @yoavweiss.

**Comment by cbiesinger** [comment]
Thank you!

I am submitting them through the Chrome CQ at https://crrev.com/c/2642939 to make merging simpler. I will continue to address any comments even after landing, of course.

**Review by annevk — COMMENTED** [review]
I have two concerns:

1. Many seemingly unrelated tests are grouped together in a single test. It seems that each time `createPicture()` is used a new test wrapper could also be used to keep the assertions somewhat isolated.
2. The setup doesn't wait for the images to be loaded, so all the style tests are about img elements without images, as far as I can tell.

**Comment by cbiesinger** [comment]
> I have two concerns:
> 
> 1. Many seemingly unrelated tests are grouped together in a single test. It seems that each time `createPicture()` is used a new test wrapper could also be used to keep the assertions somewhat isolated.

Thanks, good point, I will fix this.

> 2. The setup doesn't wait for the images to be loaded, so all the style tests are about img elements without images, as far as I can tell.

Yes. I don't think this should matter for computed style, and the ones where I also assert_ratio will not work once the image is loaded because once an image is loaded its actual dimensions will override the aspect-ratio. However, I can add some computed style checks with a loaded image.

**Comment by cbiesinger** [comment]
@annevk -- I've made the changes in this PR, please take a look

**Review by annevk — APPROVED** [review]
Thanks!

**Pull request merged**
