### PR TITLE
Make outstanding Acid3 updates

### PR DESCRIPTION
**Pull request by gsnedders**
This gets Acid3 passing in at least Chrome/Firefox/Safari.

See http://www.w3.org/mid/CADnb78js2FtmdMBGtOEo=i+YMNa7OzWYiJc96qTM2YpQvG99MQ@mail.gmail.com and http://www.w3.org/mid/995a0241-135f-3bfb-b6da-80edcd6d307e@gmail.com for the emails that led to these changes (also linked from commit messages).

### CODE REVIEW

**Comment by gsnedders** [comment]
Note this matches previous Acid3 updates insofar as it comments out the now expected-to-fail tests. We should have tests elsewhere for the new expected behaviour.

**Review by annevk — COMMENTED** [review]
Can't we check the newly expected result instead?

**Review by Ms2ger — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21033)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/306816972)

**Comment by gsnedders** [comment]
@annevk I was just trying to be consistent with previous edits, rather than particularly caring. (It also means I don't need to figure out how the selector test code works. :))

**Comment by annevk** [comment]
Fair enough, I guess.

**Pull request merged**
