### PR TITLE
WebSocket: also test event origin

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/2568.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233134936)

# Firefox (nightly) #
Testing web-platform-tests at revision 17601c6f0a49a55785ddb907b669fa19fdbebf01
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html">/websockets/opening-handshake/003.html</a></summary>


|       Subtest        | Results |                                                           Messages                                                           |
|----------------------|---------|------------------------------------------------------------------------------------------------------------------------------|
|                      | OK      |                                                                                                                              |
| `WebSockets: origin` | FAIL    | `assert_equals: expected "ws://xn--n8j6ds53lwwkrqhv28a.web-platform.test:8888" but got "ws://å¤©æ°ã®è¯ãæ¥.web-platform.test:8888"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html?wss">/websockets/opening-handshake/003.html?wss</a></summary>


|       Subtest        | Results |                   Messages                   |
|----------------------|---------|----------------------------------------------|
|                      | OK      |                                              |
| `WebSockets: origin` | FAIL    | `assert_unreached: Reached unreachable code` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233134937)

# Sauce (safari) #
Testing web-platform-tests at revision 17601c6f0a49a55785ddb907b669fa19fdbebf01
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html">/websockets/opening-handshake/003.html</a></summary>


|       Subtest        | Results |                   Messages                   |
|----------------------|---------|----------------------------------------------|
|                      | OK      |                                              |
| `WebSockets: origin` | FAIL    | `assert_unreached: Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html?wss">/websockets/opening-handshake/003.html?wss</a></summary>


|       Subtest        | Results |                   Messages                   |
|----------------------|---------|----------------------------------------------|
|                      | OK      |                                              |
| `WebSockets: origin` | FAIL    | `assert_unreached: Reached unreachable code` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233134938)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 17601c6f0a49a55785ddb907b669fa19fdbebf01
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html">/websockets/opening-handshake/003.html</a></summary>


|       Subtest        | Results |                   Messages                   |
|----------------------|---------|----------------------------------------------|
|                      | OK      |                                              |
| `WebSockets: origin` | FAIL    | `assert_unreached: Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5958/websockets/opening-handshake/003.html?wss">/websockets/opening-handshake/003.html?wss</a></summary>


|       Subtest        | Results |                   Messages                   |
|----------------------|---------|----------------------------------------------|
|                      | OK      |                                              |
| `WebSockets: origin` | FAIL    | `assert_unreached: Reached unreachable code` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233134944)

# Chrome (unstable) #

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
