### PR TITLE
Data URL <iframe>s are cross-origin

### PR DESCRIPTION
**Pull request by annevk**
This modifies an XMLHttpRequest test so it runs in more browsers and
removes two DOM tests that can no longer be tested as data URLs are now
considered cross-origin, including per standard.

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1377557.

### CODE REVIEW

**Comment by jdm** [comment]
Couldn't the data URLs include a `<script>` that used postMessage to report their contentType?

**Comment by annevk** [comment]
I suppose we could do that for the second example. I don't see how you'd do it for the first.

**Comment by jdm** [comment]
Yes, I was specifically looking at contenttype_datauri_01.html and contenttype_datauri_02.html when I suggested that.

**Comment by annevk** [comment]
I meant 01 when I said I don't see how that'd work. But I'll do it for 02.

**Review by jdm — APPROVED** [review]

**Comment by annevk** [comment]
Since we're revamping this code in Firefox we might want to land this on our side so I'd appreciate if folks would not land this for now.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by annevk** [comment]
Closing as this will get upstreamed from Mozilla's side eventually.

**Pull request closed without merging**
