### PR TITLE
[css-text] Advance width of a tab must be at least 0.5ch

### PR DESCRIPTION
**Pull request by frivoal**
Relates to https://github.com/w3c/csswg-drafts/issues/2883

### CODE REVIEW

**Comment by upsuper** [comment]
I think there should already be tests upstreamed from Gecko for this behavior.

**Comment by upsuper** [comment]
#13190

**Comment by foolip** [comment]
@upsuper, can you review?

**Review by upsuper — APPROVED** [review]
Looks good to me.

**Pull request merged**
