### PR TITLE
Add tests for the Frame Timing API

### PR DESCRIPTION
**Pull request by ericwoodwork**

### CODE REVIEW

**Comment by hiikezoe** [comment]
The attribute name of frame number is 'sourceFrameNumber', not 'sourceFrame'. I think the chrome implementation is wrong.

**Comment by ericwoodwork** [comment]
I've renamed sourceFrame as sourceFrameNumber, and relaxed the render tests to not rely on strict timing for the startTime

**Comment by foolip** [comment]
@plehegar @igrigorik @mpb @mithro, this is one of the oldest PRs in wpt with no activity. I found you via https://github.com/WICG/frame-timing/graphs/contributors and wonder if the Frame Timing API is still an active idea, or if this PR should just be closed?

**Comment by igrigorik** [comment]
@foolip It's not, we parked FT. Closing. Thanks for catching this one.

**Pull request closed without merging**
