### PR TITLE
XMLHttpRequest: use step_timeout more

### PR DESCRIPTION
**Pull request by annevk**
Also remove various broken URLs and update some code to be a bit more
modern.

See #1816.

### CODE REVIEW

**Comment by annevk** [comment]
The reason this breaks @jgraham @jugglinmike is because Firefox cannot be found.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203750425)

# Firefox (nightly channel) #
Testing web-platform-tests at revision a1c32c98a936cd4ec695d647570cd82c5aa2ab3d

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203750426)

# Chrome (unstable channel) #
Testing web-platform-tests at revision a1c32c98a936cd4ec695d647570cd82c5aa2ab3d
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/status-error.htm">/XMLHttpRequest/status-error.htm</a></summary>


|                     Subtest                      | Results |
|--------------------------------------------------|---------|
|                                                  | OK      |
| `XMLHttpRequest: status error handling GET 410`  | PASS    |
| `XMLHttpRequest: status error handling GET 400`  | PASS    |
| `XMLHttpRequest: status error handling GET 401`  | PASS    |
| `XMLHttpRequest: status error handling PUT 500`  | PASS    |
| `XMLHttpRequest: status error handling GET 699`  | PASS    |
| `XMLHttpRequest: status error handling GET 404`  | PASS    |
| `XMLHttpRequest: status error handling PUT 404`  | PASS    |
| `XMLHttpRequest: status error handling GET 500`  | PASS    |
| `XMLHttpRequest: status error handling POST 404` | PASS    |
| `XMLHttpRequest: status error handling POST 699` | PASS    |
| `XMLHttpRequest: status error handling POST 500` | PASS    |
| `XMLHttpRequest: status error handling HEAD 404` | PASS    |
| `XMLHttpRequest: status error handling HEAD 200` | PASS    |
| `XMLHttpRequest: status error handling GET 200`  | PASS    |
| `XMLHttpRequest: status error handling PUT 699`  | PASS    |
| `XMLHttpRequest: status error handling HEAD 699` | PASS    |
| `XMLHttpRequest: status error handling PUT 200`  | PASS    |
| `XMLHttpRequest: status error handling HEAD 500` | PASS    |
| `XMLHttpRequest: status error handling POST 200` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-timeout-order.htm">/XMLHttpRequest/event-timeout-order.htm</a></summary>


|                       Subtest                       | Results |
|-----------------------------------------------------|---------|
|                                                     | OK      |
| `XMLHttpRequest: event - timeout (order of events)` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-loadstart-upload.htm">/XMLHttpRequest/event-loadstart-upload.htm</a></summary>


|                                                         Subtest                                                         | Results |
|-------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                         | OK      |
| `XMLHttpRequest: The send() method: Fire a progress event named loadstart on upload object (synchronous flag is unset)` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-timeout.htm">/XMLHttpRequest/event-timeout.htm</a></summary>


|             Subtest             | Results |
|---------------------------------|---------|
|                                 | OK      |
| `XMLHttpRequest: timeout event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/abort-after-receive.htm">/XMLHttpRequest/abort-after-receive.htm</a></summary>


|                                     Subtest                                      | Results |
|----------------------------------------------------------------------------------|---------|
|                                                                                  | OK      |
| `XMLHttpRequest: abort() after successful receive should not fire "abort" event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/abort-after-timeout.htm">/XMLHttpRequest/abort-after-timeout.htm</a></summary>


|                                 Subtest                                 | Results |
|-------------------------------------------------------------------------|---------|
|                                                                         | OK      |
| `XMLHttpRequest: abort() after a timeout should not fire "abort" event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/send-sync-blocks-async.htm">/XMLHttpRequest/send-sync-blocks-async.htm</a></summary>


|                                    Subtest                                    | Results |
|-------------------------------------------------------------------------------|---------|
|                                                                               | OK      |
| `XMLHttpRequest: sync requests should block events on pending async requests` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-upload-progress-crossorigin.htm">/XMLHttpRequest/event-upload-progress-crossorigin.htm</a></summary>


|                              Subtest                              | Results |
|-------------------------------------------------------------------|---------|
|                                                                   | OK      |
| `XMLHttpRequest: upload progress event for cross-origin requests` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-load.htm">/XMLHttpRequest/event-load.htm</a></summary>


|                                          Subtest                                          | Results |
|-------------------------------------------------------------------------------------------|---------|
|                                                                                           | OK      |
| `XMLHttpRequest: The send() method: Fire an event named load (synchronous flag is unset)` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-loadend.htm">/XMLHttpRequest/event-loadend.htm</a></summary>


|             Subtest             | Results |
|---------------------------------|---------|
|                                 | OK      |
| `XMLHttpRequest: loadend event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-abort.htm">/XMLHttpRequest/event-abort.htm</a></summary>


|            Subtest            | Results |
|-------------------------------|---------|
|                               | OK      |
| `XMLHttpRequest: abort event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-loadstart.htm">/XMLHttpRequest/event-loadstart.htm</a></summary>


|              Subtest              | Results |
|-----------------------------------|---------|
|                                   | OK      |
| `XMLHttpRequest: loadstart event` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/event-progress.htm">/XMLHttpRequest/event-progress.htm</a></summary>


|                                                Subtest                                                | Results |
|-------------------------------------------------------------------------------------------------------|---------|
|                                                                                                       | OK      |
| `XMLHttpRequest: The send() method: Fire a progress event named progress (synchronous flag is unset)` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/send-sync-timeout.htm">/XMLHttpRequest/send-sync-timeout.htm</a></summary>


|                           Subtest                           | Results |
|-------------------------------------------------------------|---------|
|                                                             | OK      |
| `XMLHttpRequest: timeout during sync send() should not run` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4931/XMLHttpRequest/abort-after-stop.htm">/XMLHttpRequest/abort-after-stop.htm</a></summary>


|                               Subtest                                | Results |
|----------------------------------------------------------------------|---------|
|                                                                      | TIMEOUT |
| `XMLHttpRequest: abort event should fire when stop() method is used` | PASS    |

</details>
</details>

**Comment by jdm** [comment]
Thanks!

**Comment by jugglinmike** [comment]
@annevk Thanks for the heads-up. It looks like this was a transitory
availability issue somewhere along the request path. @jgraham have you seen
`archive.mozilla.org` return 404's before?

For context, here's the failing job on TravisCI:
https://travis-ci.org/w3c/web-platform-tests/jobs/203722340

And relevant output:

    INFO:check_stability:# Firefox (nightly channel) #
    INFO:check_stability:Testing web-platform-tests at revision d8bd3d43a2f21d50f4944627219f026f2849f0aa
    DEBUG:check_stability:Branch point from master: acd3b0862cbaac3cfac1910c526314f3b9ef13bd
    DEBUG:check_stability:python manifest
    DEBUG:check_stability:git clone --depth=1 https://github.com/w3c/wptrunner.git /home/travis/build/w3c/wptrunner
    Cloning into '/home/travis/build/w3c/wptrunner'...
    remote: Counting objects: 170, done.
    remote: Compressing objects: 100% (145/145), done.
    remote: Total 170 (delta 24), reused 78 (delta 14), pack-reused 0
    Receiving objects: 100% (170/170), 137.16 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (24/24), done.
    DEBUG:check_stability:pip install /home/travis/build/w3c/wptrunner
    DEBUG:check_stability:pip install -r /home/travis/build/w3c/wptrunner/requirements_firefox.txt
    DEBUG:check_stability:GET https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-53.0a1.en-US.linux-x86_64.tar.bz2
    Traceback (most recent call last):
      File "check_stability.py", line 761, in <module>
        retcode = main()
      File "check_stability.py", line 701, in main
        browser.install()
      File "check_stability.py", line 186, in install
        resp = get("https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-53.0a1.en-US.linux-x86_64.tar.bz2")
      File "check_stability.py", line 284, in get
        resp.raise_for_status()
      File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-53.0a1.en-US.linux-x86_64.tar.bz2

**Comment by Ms2ger** [comment]
See https://github.com/w3c/web-platform-tests/pull/4933

**Comment by jugglinmike** [comment]
Ahah! Thanks, @Ms2ger

**Pull request merged**
