### PR TITLE
Add Khronos' WebGL conformance test-suite 1.0.3

### PR DESCRIPTION
**Pull request by emilio**
Pretty similar steps to those used in #2449 

There are a few files that could be removed still (mostly READMEs and test lists). I don't think they're a problem though.

cc: KhronosGroup/WebGL#1105
cc: @jdm @Ms2ger

### CODE REVIEW

**Comment by zqzhang** [comment]
Great and glad to see this happen.

Just curious how to make code sync with Khronos' WebGL conformance test-suite, especially when people find issues here or submit new tests? Submit pull requests to both repositories or only one of them? Thanks.

**Comment by ecoal95** [comment]
Ideally versioned test suites are a snapshot, and should not change.

The minor changes applied to a snapshot are mostly backports or tiny
corrections, but they are not common at all (seeing
https://github.com/KhronosGroup/WebGL/commits/master/conformance-suites/1.0.3/
I see less than 20 commits in more than a year).

So... IMO corrections and specially new tests should be upstreamed there
to be included in the next snapshot, and if Khronos decides to backport
the changes into our version, the relevant files should also be updated
here, which should be pretty easy to do since we only modify the test
files to add our harness scripts.

**Comment by jgraham** [comment]
When you say "we only modify the test files to add our harness scripts", how much modification happens? Is it every file? Or a small number of helper files only? Is there a conceivable design with only added files? If not is the modification scripted and are you committing those scripts as part of the PR?

**Comment by ecoal95** [comment]
I'm talking about [this commit](https://github.com/ecoal95/web-platform-tests/commit/d58a33f53753841821df3664ccad5ec384974ac6), which adds two lines to every test file.

The modification was done automatically (the command is in the description of the commit).

We could load them synchronously in both `js-test-pre.js` and `unit.js`, and remove those modifications, but it would depend on the status of synchronous `XMLHttpRequest`, that in servo might be flacky.

**Comment by jgraham** [comment]
I'd be happier if you committed a python script in webgl/tools to automate the import, including this modification.

**Comment by ecoal95** [comment]
Will do :)

Should be easy enough to make a script traverse their test lists and remove all files not in that list, and later add our harness there.

There's no way to automatically modify their harness file for our needs though (what https://github.com/ecoal95/web-platform-tests/commit/f246e427d8f430060d488a93eeae1911a6fb42c4 and https://github.com/ecoal95/web-platform-tests/commit/fcc6a053e7939c995461b3f0612646fbf3da12b2 do).

**Comment by jdm** [comment]
Making diff files and applying them automatically would be better than nothing, I expect.

**Comment by ecoal95** [comment]
Made as suggested, I'm not too experienced in python, so feel free to point any issue with the way I've done it :)

**Pull request merged**
