### PR TITLE
Add RTCCertificate IDL test

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5692)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225858602)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225858604)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 55bf5743590b10276c4b1523a498a28adf2ea41f
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5692/webrtc/RTCCertificate-idl.html">/webrtc/RTCCertificate-idl.html</a></summary>


|                                                   Subtest                                                   | Results |                                                         Messages                                                        |
|-------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                                                         |
| `RTCCertificate IDL Test`                                                                                   | PASS    |                                                                                                                         |
| `RTCCertificate interface: existence and properties of interface object`                                    | PASS    |                                                                                                                         |
| `RTCCertificate interface object length`                                                                    | PASS    |                                                                                                                         |
| `RTCCertificate interface object name`                                                                      | PASS    |                                                                                                                         |
| `RTCCertificate interface: existence and properties of interface prototype object`                          | PASS    |                                                                                                                         |
| `RTCCertificate interface: existence and properties of interface prototype object's "constructor" property` | PASS    |                                                                                                                         |
| `RTCCertificate interface: attribute expires`                                                               | PASS    |                                                                                                                         |
| `RTCCertificate interface: attribute fingerprints`                                                          | FAIL    | `assert_true: The prototype object must have a property "fingerprints" expected true got false`                         |
| `RTCCertificate interface: operation getAlgorithm()`                                                        | FAIL    | `assert_own_property: interface prototype object missing non-static operation expected property "getAlgorithm" missing` |
| `RTCCertificate must be primary interface of rtcCert`                                                       | PASS    |                                                                                                                         |
| `Stringification of rtcCert`                                                                                | PASS    |                                                                                                                         |
| `RTCCertificate interface: rtcCert must inherit property "expires" with the proper type (0)`                | PASS    |                                                                                                                         |
| `RTCCertificate interface: rtcCert must inherit property "fingerprints" with the proper type (1)`           | FAIL    | `assert_inherits: property "fingerprints" not found in prototype chain`                                                 |
| `RTCCertificate interface: rtcCert must inherit property "getAlgorithm" with the proper type (2)`           | FAIL    | `assert_inherits: property "getAlgorithm" not found in prototype chain`                                                 |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225858610)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 55bf5743590b10276c4b1523a498a28adf2ea41f

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5692/)

**Comment by agouaillard** [comment]
see #5693

**Pull request closed without merging**
