### PR TITLE
Fix get-host-info.sub.js so workers can use it.

### PR DESCRIPTION
**Pull request by mfalken**
Access self.location instead of window.location. Fixes #13518 (see https://crbug.com/953873).

### CODE REVIEW

**Comment by mattto** [comment]
cc @Hexcles @yoavweiss

**Review by yoavweiss — APPROVED** [review]
LGTM

**Comment by mattto** [comment]
@Hexcles I think this may need to be force merged for the same reason as #13518. Hopefully it fixes things this time though.

**Comment by Hexcles** [comment]
@gsnedders thanks :) (Also, we got a rare race condition and I got to see a confused GitHub UI lol)

**Pull request merged**
