### PR TITLE
[webdriver] Introduce `assert_same_element`

### PR DESCRIPTION
**Pull request by jugglinmike**
@andreastt This seemed like something that will be helpful as we expand coverage to more element-related tests. It's just an ergonomics thing, but I should still ask: do you think it's too early to justify the complexity?

### CODE REVIEW

**Review by andreastt — APPROVED** [review]
I think this is a good improvement, thanks!

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238778374)

# Firefox (nightly) #
Testing web-platform-tests at revision 45d97ee88276b10cead915eeb27972d32321897e
Using browser at version BuildID 20170602100143; SourceStamp aeb3d0ca558f034cbef1c5a68bd07dd738611494
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6137/webdriver/actions/conftest.py">/webdriver/actions/conftest.py</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | OK      |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6137/webdriver/actions/key.py">/webdriver/actions/key.py</a></summary>


|                                       Subtest                                       | Results | Messages |
|-------------------------------------------------------------------------------------|---------|----------|
|                                                                                     | OK      |          |
| `key.py::test_lone_keyup_sends_no_events`                                           | PASS    |          |
| `key.py::test_single_printable_key_sends_correct_events[0a-KeyA]`                   | PASS    |          |
| `key.py::test_single_printable_key_sends_correct_events[1a-KeyA]`                   | PASS    |          |
| `key PASS    |          |
| `key.py::test_single_nonprintable_key_sends_events[value1-ArrowRight-ArrowRight]`   | PASS    |          |
| `key.py::test_sequence_of_keydown_printable_keys_sends_events`                      | PASS    |          |
| `key.py::test_sequence_of_keydown_character_keys`                                   | PASS    |          |
| `key.py::test_backspace_erases_keys`                                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6137/webdriver/actions/mouse.py">/webdriver/actions/mouse.py</a></summary>


|                  Subtest                  | Results | Messages |
|-------------------------------------------|---------|----------|
|                                           | OK      |          |
| `mouse.py::test_click_at_coordinates`     | PASS    |          |
| `mouse.py::test_click_element_center`     | PASS    |          |
| `mouse.py::test_click_navigation`         | PASS    |          |
| `mouse.py::test_drag_and_drop[20-0-0]`    | PASS    |          |
| `mouse.py::test_drag_and_drop[20-0-300]`  | PASS    |          |
| `mouse.py::test_drag_and_drop[20-0-800]`  | PASS    |          |
| `mouse.py::test_drag_and_drop[0-15-0]`    | PASS    |          |
| `mouse.py::test_drag_and_drop[0-15-300]`  | PASS    |          |
| `mouse.py::test_drag_and_drop[0-15-800]`  | PASS    |          |
| `mouse.py::test_drag_and_drop[10-15-0]`   | PASS    |          |
| `mouse.py::test_drag_and_drop[10-15-300]` | PASS    |          |
| `mouse.py::test_drag_and_drop[10-15-800]` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6137/webdriver/actions/sequence.py">/webdriver/actions/sequence.py</a></summary>


|                                 Subtest                                 | Results | Messages |
|-------------------------------------------------------------------------|---------|----------|
|                                                                         | OK      |          |
| `sequence.py::test_no_actions_send_no_events`                           | PASS    |          |
| `sequence.py::test_release_char_sequence_sends_keyup_events_in_reverse` | PASS    |          |
| `sequence.py::test_release_no_actions_sends_no_events`                  | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6137/webdriver/actions/special_keys.py">/webdriver/actions/special_keys.py</a></summary>


|                                        Subtest                                         | Results | Messages |
|----------------------------------------------------------------------------------------|---------|----------|
|                                                                                        | OK      |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD9-expected0]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[RETURN-expected1]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[HELP-expected2]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[SHIFT-expected3]`           | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_ARROWRIGHT-expected4]`    | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[ESCAPE-expected5]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[PAGE_UP-expected6]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_PAGEUP-expected7]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[UP-expected8]`              | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[DOWN-expected9]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[F12-expected10]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[META-expected11]`           | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[BACKSPACE-expected12]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[MULTIPLY-expected13]`       | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[HOME-expected14]`           | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NULL-expected15]`           | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[SUBTRACT-expected16]`       | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[CONTROL-expected17]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[INSERT-expected18]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_META-expected19]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[SEMICOLON-expected20]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[SPACE-expected21]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD4-expected22]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[RIGHT-expected23]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[TAB-expected24]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_ALT-expected25]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD0-expected26]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[DECIMAL-expected27]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[LEFT-expected28]`           | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_DELETE-expected29]`       | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[PAGE_DOWN-expected30]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[PAUSE-expected31]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[END-expected32]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[DIVIDE-expected33]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_ARROWUP-expected34]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD3-expected35]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[CLEAR-expected36]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_ARROWLEFT-expected37]`    | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[EQUALS-expected38]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_PAGEDOWN-expected39]`     | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[ADD-expected40]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD1-expected41]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_INSERT-expected42]`       | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[ENTER-expected43]`          | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[CANCEL-expected44]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD6-expected45]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[F9-expected59]`             | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD8-expected60]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[NUMPAD5-expected61]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_CONTROL-expected62]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_HOME-expected63]`         | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[ZENKAKUHANKAKU-expected64]` | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_SHIFT-expected65]`        | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[SEPARATOR-expected66]`      | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[ALT-expected67]`            | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[R_ARROWDOWN-expected68]`    | PASS    |          |
| `special_keys.py::test_webdriver_special_key_sends_keydown[DELETE-expected69]`         | PASS    |          |

</details>
<details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238778375)

# Sauce (safari) #
Testing web-platform-tests at revision 45d97ee88276b10cead915eeb27972d32321897e
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238778381)

# Chrome (unstable) #
Testing web-platform-tests at revision 45d97ee88276b10cead915eeb27972d32321897e
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/238778382)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 45d97ee88276b10cead915eeb27972d32321897e
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Pull request merged**
