### PR TITLE
Document .window.js tests.

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5132/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210686772)

# Firefox (nightly channel) #
Testing web-platform-tests at revision f1c596a3000da76d065eaa9a42d176eb242b0615
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210686773)

# Chrome (unstable channel) #
Testing web-platform-tests at revision f1c596a3000da76d065eaa9a42d176eb242b0615
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
No tests run.

**Comment by Ms2ger** [comment]
LGTM when the submodule is updated.

**Review by Ms2ger — APPROVED** [review]

**Comment by annevk** [comment]
https://github.com/w3c/wpt-tools/commit/7ad8c87ebba4f2c79d17b2aee17f226020800e37 was the corresponding commit btw, which I'm pretty sure got synchronized since then.

**Pull request merged**
