### PR TITLE
Add test for ResizeObserver with zoom

### PR DESCRIPTION
**Pull request by cathiechen**
Zoom in/out shouldn't affect ResizeObserver.

### CODE REVIEW

**Comment by atotic** [comment]
The test looks good, but the PR got closed.

In Chrome, I think resize notifications might be possible with zoom. I think Chrome does layout with different font sizes on zoom, and this might cause sizes to change if they are font-size dependent.

**Comment by dholbert** [comment]
The test calls `window.internals.setPageZoomFactor(2);` -- is that an actual web API defined anywhere?

(or is it a Blink and/or WebKit-specific internal API?)

**Comment by smfr** [comment]
> The test calls `window.internals.setPageZoomFactor(2);` -- is that an actual web API defined anywhere?
> 
> (or is it a Blink and/or WebKit-specific internal API?)

It's WebKit-specific, which means this probably can't be a WPT test, unless there's some other way to change the zoom level via web driver.

**Comment by fred-wang** [comment]
There is also https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom but not sure about its interoperability.

**Comment by cathiechen** [comment]
Sorry for the confusing. Yes, I closed this PR because I failed to find a way to change zoom in web driver. Maybe we should add one? https://github.com/w3c/webdriver/issues/1378

> There is also https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom but not sure about its interoperability.

CSS zoom seems not interoperable.

> In Chrome, I think resize notifications might be possible with zoom. I think Chrome does layout with different font sizes on zoom, and this might cause sizes to change if they are font-size dependent.

I also found the approximation for multiplications and divisions might cause resize notifications. For instance: the layout width of a block with `width: 200px`, zoom to 67%, the width ends up 199.98px, and trigger resize notification.

**Comment by smfr** [comment]
> There is also https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom but not sure about its interoperability.

That's a different kind of zoom (pinch-zoom) and is inside the deprecated @viewport rule.

**Pull request closed without merging**
