### PR TITLE
1st batch, double-byte encoder/decoder tests for SC, TC, J and K

### PR DESCRIPTION
**Pull request by r12a**
Covers Big5, GBK, GB18030, EUR-KR, EUC-JP, ISO-2022-JP, SHIFT_JIS

### CODE REVIEW

**Comment by annevk** [comment]
@hsivonen you might find this interesting too.

**Comment by r12a** [comment]
i plan to submit a PR for white-listing of these tests wrt lint failures arising from tabs and (occasional) extra spaces.  May be able to fit it in at the end of the day tomorrow, or the following day.

**Comment by inexorabletash** [comment]
Why white-list rather than fixing whitespace issues? (I assume there's a good reason, just wondering what it is - e.g. these are byte-for-byte copies we want to import and maintain, etc)

**Comment by r12a** [comment]
Sure. The overwhelming majority of the cases are tabs for the somewhat more complex than usual javascript that drives the tests. I wanted to retain those so that i can read the code easily.  There are 361 files in this batch, most of which are not encoded in utf-8, and contain a fair number of lines preceded by tabs each, so it's also going to be quite time consuming to change and then esp check all of them (especially since the test files run something like 750,000 subtests in total). And i've run all those sufficiently often already to believe that these tabs aren't affecting the results, so this would be just for the sake of making the linter happy. (Once i white list the tab check, i'll look to see whether any of the other 6000-odd issues need attention.)

**Comment by inexorabletash** [comment]
Hrm - it doesn't seem that hard to convert the tabs to spaces, just took me a few seconds:
```
for i in encoding/legacy-*/*/*.{html,js}; do cp $i /tmp/tab && expand -i -t 2 /tmp/tab > $i; done
```

I didn't compare output w/ and w/o that change, though.

FWIW, running all of /encoding/ via http://web-platform.test:8000/tools/runner/index.html (i.e. served locally) in Chrome 50 took about 5 minutes and I got 1779148 PASS, 11024 FAIL, and 1 TIMEOUT (although it listed /encoding/legacy-mb-korean/euc-kr/euckr-encode-form-errors-hangul.html as NOT RUN

**Comment by r12a** [comment]
Please don't accept this pull request yet.  I am making some changes to the tests based on changes made to the Encoding spec recently, and i'll commit those once i have them ready.

**Comment by inexorabletash** [comment]
No problem - I'm excited to see this coming! Let me know if I can be of any assistance to get it ready.

**Comment by r12a** [comment]
@inexorabletash @annevk, i think what i'll do is close this PR and open one new PR per encoding as the tests for that encoding have been updated and checked.  That may make it easier for review, but also i'm thinking of raising issues for each encoding separately to summarise the latest results so that we can prompt implementers to fix things (or of course change the spec, if needed), so it will enable me to get started on that sooner.  Does that sound ok?

**Comment by r12a** [comment]
Forgot to say that of course as people look at the issues we may find bugs in the tests too, although i've tried hard to avoid that. Doing that an encoding at a time may also be useful.

**Comment by annevk** [comment]
That sounds fine to me. Whatever you find the easiest way to get this done really; happy to accommodate.

**Pull request closed without merging**
