### PR TITLE
Remove infrastructure/ expectations for Edge classic

### PR DESCRIPTION
**Pull request by foolip**
We're no longer running this configuration:
https://github.com/web-platform-tests/wpt/pull/16920

### CODE REVIEW

**Comment by gsnedders** [comment]
Do we actually entirely want to remove these, even though we aren't at all regularly running Edge any more? I'd rather have some expectations here as long as we support running against Edge, at least?

**Comment by foolip** [comment]
I'd rather not have them, they make it more work to update expectations for other browsers if the expectation was shared and now you're not sure if edge_webdriver should change or not, and you can't run it.

@thejohnjansen @mustjab do you have opinions on whether to keep these?

**Comment by thejohnjansen** [comment]
I don't mind removing them completely because I don't expect us to run WPT.FYI against old Edge. As far as I can tell, the results are not trustworthy anyway because of timeouts and other various issues.

**Comment by foolip** [comment]
Over to you, @gsnedders :)

**Comment by foolip** [comment]
Ping @gsnedders, this will conflict with updates for Safari.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
