### PR TITLE
WebCryptoAPI: extend ecdsa, aes-gcm, avoid uncommon parameters in wrap/unwrap

### PR DESCRIPTION
**Pull request by panva**
- aes-gcm vectors changed to use the recommended 96 bit iv (should we add alternative iv length vectors?)
- ecdsa failure vectors changed to test common curve + hash combinations (the combinations are still extensively tested in the other vectors, they don't need to figure in the failures)
- wrapUnwrap key setup using allSettled to not report failures when individual vectors error
- wrapUnwrap AES-GCM tagLength using the common (and defaulted to) 128 bit length tag (aes-gcm vectors still extensively test other tagLengths, they don't need to figure in wrap/unwrap tests)

These changes allow Deno's daily wpt report to show common and recommended parameters use support rather than uncommon ones.

### CODE REVIEW

**Comment by twiss** [comment]
Hello :wave:

- Since it was tested before I think we should keep testing IV length(s) other than 96 bits, yeah
- I don't entirely understand why the hash matters for invalid test cases?
- Are the failures still reported later?
- I'm not sure I agree, also in this context I think it's valuable to test that the tagLength parameter is respected, and that wrapping/unwrapping doesn't just always use the default, for example.

In general, I don't really agree with the approach of going with the "common" parameters in order to show support in a specific implementation. The point of the tests is not to show off support IMO, but to make sure that all cases are covered. Testing uncommon combinations is more valuable than testing common ones in that sense, I'd say.

**Comment by panva** [comment]
> Since it was tested before I think we should keep testing IV length(s) other than 96 bits, yeah

I can do that in a follow up.

> I don't entirely understand why the hash matters for invalid test cases?

The point of the invalid cases is to show that shortened signatures and empty signatures fail. If the test fails because the combination of crv and hash is not supported it just doesn't tick that box to show conformance. In this case, the different crv/hash combination support is tested extensively elsewhere.

> Are the failures still reported later?

Yes. It just means setup won't fail if one of the vectors it's setting up fails.

> tagLength support for AES-GCM is extensively supported elsewhere. wrapUnwrap should be about wrapping, not AES-GCM specifically.

> Testing uncommon combinations is more valuable than testing common ones in that sense, I'd say.

Testing uncommon combinations at the cost of not showing conformance using common or defaulted to parameter values is not helpful.

**Comment by panva** [comment]
i'm done ✅

**Comment by twiss** [comment]
:+1: Thanks!

> tagLength support for AES-GCM is extensively tested elsewhere. wrapUnwrap tests should be about wrapping, not testing AES-GCM under an uncommon combination of parameters.
> 
> Testing uncommon combinations at the cost of not showing conformance using common or defaulted to parameter values is not helpful.

I still don't really agree with this, tbh. `wrapKey` and `unwrapKey` are separate functions, that have an `[un]wrapAlgorithm` parameter with a `tagLength` property (in the case of GCM), that is now no longer really tested, since the implementer could just hardcode the default tag length. While of course that would be quite a pathological thing to do, I think it's still worth testing it. We could test two variants of GCM with different tag lengths, for example?

**Comment by panva** [comment]
The wrap/unwrap test file's intent as far as i can tell was not to be extensively testing everything, in fact, an existing comment in there reads:

> Generate one key with typical parameters for each kind.

**Comment by panva** [comment]
> I still don't really agree with this, tbh. wrapKey and unwrapKey are separate functions, that have an [un]wrapAlgorithm parameter with a tagLength property (in the case of GCM), that is now no longer really tested, since the implementer could just hardcode the default tag length.

Because the tests are not extensive and don't have expected vectors any parameter being hard coded would not be found out using wrap/unwrap tests anyway. That's what the specific algorithm tests that wrap/unwrap piggybacks on are for.

**Review by twiss — APPROVED** [review]
OK, fair enough :+1:

**Comment by Czarna0000** [comment]
WebCryptoAPI

> **fgj``**

**Pull request merged**
