### PR TITLE
Add feature-policy to battery-status

### PR DESCRIPTION
**Pull request by Honry**
- Add feature-policy tests
 - Disallow using battery in cross-origin iframe
 - Allow using battery in same-origin iframe

Reflect to https://github.com/w3c/battery/pull/13

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19810)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/291510333)

**Review by anssiko — APPROVED** [review]
LGTM.

@clelland to review the Feature Policy tests to ensure we've tested the edge cases correctly.

**Comment by Honry** [comment]
@anssiko, tests have been update-to-date, PTAL again. Thanks!

**Comment by anssiko** [comment]
Thanks @honry, LGTM!

(The only normative change since last update to this PR was https://github.com/w3c/battery/commit/3e089152068c61ae97751af8be1bafaaeecbd768 and that's now baked into this PR.)

**Pull request merged**
