### PR TITLE
Create OWNERS for webxr

### PR DESCRIPTION
**Pull request by offenwanger**
Create the OWNERS file for the new webxr test folder. webxr tests are for the webxr API, which is under construction here: https://immersive-web.github.io/webxr/spec/latest/

### CODE REVIEW

**Review by Hexcles — APPROVED** [review]

**Comment by Hexcles** [comment]
@paezagon I just stamped it. However, keep in mind that OWNERS files are just for wpt-pr-bot to loop in reviewers automatically. Each owner still has to gain write access to this repo (by becoming a collaborator, or a member of github.com/w3c) to be able to give effective approval and merge PRs.

Now, you should be able to merge this PR yourself if you have write access.

**Comment by paezagon** [comment]
It doesn't look like I have write access, I will track down someone who does. 
Thanks!

**Comment by Hexcles** [comment]
@paezagon You'd need to talk to someone who has *admin* power (which I don't) to grant you (and other owners) write access. Perhaps @foolip ?

**Comment by foolip** [comment]
Hi there, @paezagon! I hope this isn't creepy, but I took a look to see your commit history in wpt and didn't find any commits yet. We of course welcome new contributors very much, but may I ask for a PR or two before I flip from read (labels) to write access? There are many pitfalls when writing tests, and having had your tests reviewed by others should help you review others in turn.

Of course, you don't need write access to do the reviews or get notified, so I'll just go ahead and merge this. Please poke me somewhere when it becomes a nuisance that you can't merge yourself.

**Pull request merged**
