### PR TITLE
update python version in build for html/canvas

### PR DESCRIPTION
**Pull request by yiyix**
It's currently building with virtualenv -p python2 .virtualenv, which requires python2 specifically. Updated to use python, so it's compatible with both python2 and python3.

### CODE REVIEW

**Comment by yiyix** [comment]
The concern is initially raised here:
https://github.com/web-platform-tests/wpt/commit/6a531642611c81e83bed58421fdc555e2db1f77a

**Comment by stephenmcgruer** [comment]
Taking notes for my own understanding:

* This is run by `update-built-tests.sh`, which is run by `./tools/ci/ci_built_diff.sh`
* `./tools/ci/ci_built_diff.sh` is run during the CI, in the `update-built` Taskcluster step
* It triggers for pull requests, if they match the `update_built` glob, which expands to:
```
    "update_built": ["update-built-tests\\.sh",
                     "infrastructure/",
                     "html/",
                     "mimesniff/",
                     "css/css-ui/",
                     "WebIDL"],
```

What I'm a little confused by is the conversation in https://github.com/web-platform-tests/wpt/commit/6a531642611c81e83bed58421fdc555e2db1f77a - it seems to imply that one set of people had problems running this in Python 2 (mysteryDate mentioned this) whilst another set had problems running this in Python 3 (yiyix said this).

The goal of **this** change seems to be to let it use whatever the system Python is, but it seems like we aren't sure that will always work?

**Review by stephenmcgruer — COMMENTED** [review]
Speaking to Yi, they believe that the script works with both python 2 and python 3, so it seems like this is the correct change to me. It certainly passes the CI in python 2 at least.

I would like to give @jgraham and @Hexcles 24 hours to object, then I will approve + merge this after that.

**Comment by mysteryDate** [comment]
@jgraham Do you object to this, you thought the CI bots were mad when we made it version agnostic?

**Comment by Hexcles** [comment]
FWIW, I don't object to this if it works in both 2 and 3, but I remember this was pinned to Python 2 specifically because of some issues on (Gecko?) CI.

**Comment by yiyix** [comment]
In my local set up, it works for both python 2 and 3. My teammate @mysteryDate did some refactor [here](https://chromium-review.googlesource.com/c/chromium/src/+/2240038) and he is able to re-generate all script tests with both python2 and python3.

**Comment by stephenmcgruer** [comment]
It could be because Mozilla use an older Python 3 internally (I believe they were still targeting Python 3.5 last time I checked). Let me ping @jgraham again and see if they know - sorry @yiyix to drag this on further :(

That said, I did try locally with 3.5.6 and the build.sh script worked fine for me in that environment.

**Comment by jgraham** [comment]
I don't have any specific concerns about Gecko CI here; I don't think we run this. I'm somewhat wary of getting different results from Python 2 vs 3 in the canvas stuff, but I suppose I'm also pretty wary of getting different results based on a number of other factors there and it seems to work out.

**Review by stephenmcgruer — APPROVED** [review]

**Comment by yiyix** [comment]
@jgraham: in the [cl](https://chromium-review.googlesource.com/c/chromium/src/+/2240038) that i mentioned above, we tried to generate all canvas wpt tests with python2 and python3 and they give exactly the same result. Hopefully, this can give you more confidence in this change.

**Pull request merged**
