### PR TITLE
[geometry-1] improve tests when transform DOMPoint from DOMMatrix.

### PR DESCRIPTION
**Pull request by hwanseung**
Chromium had wrong calculated when transform DOMPoint from DOMMatrix.
unfortunately test could not detect problems.
because there was not test or m12 and m21 values were zero in tests.

### CODE REVIEW

**Comment by hwanseung** [comment]
@zcorpan could you review this patch?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242398257)

# Firefox (nightly) #
Testing web-platform-tests at revision 149a06c7e47672ea19df80c3ebe51c9cd3375275
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6225/css/geometry-1/DOMMatrix-003.html">/css/geometry-1/DOMMatrix-003.html</a></summary>


|                 Subtest                  | Results |                     Messages                     |
|------------------------------------------|---------|--------------------------------------------------|
|                                          | OK      |                                                  |
| `test translate()`                       | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test scale() without offsets`           | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test scale() with offsets`              | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test scale3d()`                         | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test rotate() 2d`                       | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test rotate()`                          | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test rotateFromVector()`                | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test rotateAxisAngle() `                | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test skewX()`                           | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test skewY()`                           | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test multiply with inverse is identity` | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test flipX()`                           | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test flipY()`                           | FAIL    | `DOMMatrixReadOnly.fromMatrix is not a function` |
| `test transformPoint() - 2d matrix`      | FAIL    | `Illegal constructor.`                           |
| `test transformPoint() - 3d matrix`      | FAIL    | `Illegal constructor.`                           |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6225/css/geometry-1/DOMPoint-002.html">/css/geometry-1/DOMPoint-002.html</a></summary>


|                         Subtest                         | Results |                                 Messages                                 |
|---------------------------------------------------------|---------|--------------------------------------------------------------------------|
|                                                         | OK      |                                                                          |
| `test DOMPoint Constructor no args`                     | PASS    |                                                                          |
| `test DOMPoint Constructor one args`                    | FAIL    | `Argument 1 of DOMPoint.constructor can't be converted to a dictionary.` |
| `test DOMPoint Constructor two args`                    | PASS    |                                                                          |
| `test DOMPoint Constructor three args`                  | PASS    |                                                                          |
| `test DOMPoint Constructor four args`                   | PASS    |                                                                          |
| `test DOMPoint Constructor more then four args`         | PASS    |                                                                          |
| `test DOMPoint Constructor with undefined`              | FAIL    | `assert_equals: y is not matched expected 0 but got NaN`                 |
| `test DOMPoint Constructor with string`                 | PASS    |                                                                          |
| `test DOMPoint Constructor with empty object`           | FAIL    | `assert_equals: x is not matched expected NaN but got 0`                 |
| `test DOMPoint fromPoint with empty object`             | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x`                        | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x, y`                     | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x, y, z`                  | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x, y, z, w`               | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x, y, z, w, v`            | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with x, z`                     | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint fromPoint with undefined value`          | FAIL    | `DOMPoint.fromPoint is not a function`                                   |
| `test DOMPoint matrixTransform`                         | FAIL    | `point.matrixTransform is not a function`                                |
| `test DOMPoint Attributes undefined`                    | PASS    |                                                                          |
| `test DOMPoint Attributes NaN Infinity`                 | PASS    |                                                                          |
| `test DOMPointReadOnly Constructor no args`             | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor one args`            | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor two args`            | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor three args`          | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor four args`           | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor more then four args` | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor with undefined`      | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor with string`         | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Constructor with object`         | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly fromPoint with empty object`     | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x`                | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x, y`             | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x, y, z`          | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x, y, z, w`       | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x, y, z, w, v`    | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with x, z`             | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly fromPoint with undefined value`  | FAIL    | `DOMPointReadOnly.fromPoint is not a function`                           |
| `test DOMPointReadOnly matrixTransform`                 | FAIL    | `Illegal constructor.`                                                   |
| `test DOMPointReadOnly Attributes undefined`            | FAIL    | `Illegal constructor.`                                                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242398258)

# Sauce (safari) #
Testing web-platform-tests at revision 149a06c7e47672ea19df80c3ebe51c9cd3375275
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6225/css/geometry-1/DOMMatrix-003.html">/css/geometry-1/DOMMatrix-003.html</a></summary>


|                 Subtest                  | Results |                 Messages                 |
|------------------------------------------|---------|------------------------------------------|
|                                          | OK      |                                          |
| `test translate()`                       | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test scale() without offsets`           | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test scale() with offsets`              | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test scale3d()`                         | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test rotate() 2d`                       | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test rotate()`                          | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test rotateFromVector()`                | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test rotateAxisAngle() `                | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test skewX()`                           | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test skewY()`                           | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test multiply with inverse is identity` | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test flipX()`                           | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test flipY()`                           | FAIL    | `Can't find variable: DOMMatrixReadOnly` |
| `test transformPoint() - 2d matrix`      | FAIL    | `Can't find variable: DOMPointReadOnly`  |
| `test transformPoint() - 3d matrix`      | FAIL    | `Can't find variable: DOMPointReadOnly`  |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6225/css/geometry-1/DOMPoint-002.html">/css/geometry-1/DOMPoint-002.html</a></summary>


|                         Subtest                         | Results |                 Messages                |
|---------------------------------------------------------|---------|-----------------------------------------|
|                                                         | OK      |                                         |
| `test DOMPoint Constructor no args`                     | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor one args`                    | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor two args`                    | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor three args`                  | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor four args`                   | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor more then four args`         | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor with undefined`              | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor with string`                 | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Constructor with empty object`           | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with empty object`             | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x`                        | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x, y`                     | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x, y, z`                  | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x, y, z, w`               | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x, y, z, w, v`            | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with x, z`                     | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint fromPoint with undefined value`          | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint matrixTransform`                         | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Attributes undefined`                    | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPoint Attributes NaN Infinity`                 | FAIL    | `Can't find variable: DOMPoint`         |
| `test DOMPointReadOnly Constructor no args`             | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor one args`            | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor two args`            | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor three args`          | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor four args`           | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor more then four args` | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor with undefined`      | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor with string`         | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Constructor with object`         | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with empty object`     | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x`                | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x, y`             | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x, y, z`          | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x, y, z, w`       | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x, y, z, w, v`    | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with x, z`             | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly fromPoint with undefined value`  | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly matrixTransform`                 | FAIL    | `Can't find variable: DOMPointReadOnly` |
| `test DOMPointReadOnly Attributes undefined`            | FAIL    | `Can't find variable: DOMPointReadOnly` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242398272)

# Chrome (unstable) #
Testing web-platform-tests at revision 149a06c7e47672ea19df80c3ebe51c9cd3375275

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242398273)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 149a06c7e47672ea19df80c3ebe51c9cd3375275

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
