### PR TITLE
Encoding: align encodeInto() test with reality

### PR DESCRIPTION
**Pull request by annevk**
While IDL said this should throw, that was in error: https://github.com/heycam/webidl/pull/605.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by ricea** [comment]
Interesting. My slow and dumb polyfill didn't pass this test, but I assumed it was just because I wasn't trying hard enough.

I will retest once you've fixed @Honry's comments.

**Comment by annevk** [comment]
Thanks @Honry! Out-of-band Henri told me that it didn't work in workers, so I've fixed that too. And Domenic helped me figure out a way to make object destructuring work without a leading let/const. 😊

**Comment by hsivonen** [comment]
With the latest changes changes to the test, my implementation of the feature passes the test, so the detachment part is now reality-aligned at least for Gecko purposes.

**Comment by ricea** [comment]
Retested. All tests pass now, including in a worker.

**Pull request merged**
