### PR TITLE
Minify HTML IDL tests to document.all

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This is in order to investigate https://github.com/w3c/web-platform-tests/pull/5942, please ignore.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233204906)

# Firefox (nightly) #
Testing web-platform-tests at revision dd275d63c5c48eb3abc23f372a95212cbec2ec6d
Using browser at version BuildID 20170517100341; SourceStamp 6e3ca5b38f7173b214b10de49e58cb01890bf39d
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5963/html/dom/interfaces.html">/html/dom/interfaces.html</a></summary>


|                                              Subtest                                               | Results |                                                       Messages                                                       |
|----------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
|                                                                                                    | OK      |                                                                                                                      |
| `Test driver`                                                                                      | PASS    |                                                                                                                      |
| `Document interface: attribute all`                                                                | FAIL    | `assert_true: The prototype object must have a property "all" expected true got false`                               |
| `Stringification of iframe.contentDocument`                                                        | FAIL    | `assert_equals: class string of iframe.contentDocument expected "[object Document]" but got "[object HTMLDocument]"` |
| `Document interface: iframe.contentDocument must inherit property "all" with the proper type (29)` | FAIL    | `Unrecognized type HTMLAllCollection`                                                                                |
| `Document must be primary interface of new Document()`                                             | PASS    |                                                                                                                      |
| `Stringification of new Document()`                                                                | PASS    |                                                                                                                      |
| `Document interface: new Document() must inherit property "all" with the proper type (29)`         | FAIL    | `assert_inherits: property "all" not found in prototype chain`                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233204907)

# Sauce (safari) #
Testing web-platform-tests at revision dd275d63c5c48eb3abc23f372a95212cbec2ec6d
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5963/html/dom/interfaces.html">/html/dom/interfaces.html</a></summary>


|    Subtest    | Results |           Messages           |
|---------------|---------|------------------------------|
|               | OK      |                              |
| `Test driver` | FAIL    | `Can't find variable: fetch` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233204908)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision dd275d63c5c48eb3abc23f372a95212cbec2ec6d
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5963/html/dom/interfaces.html">/html/dom/interfaces.html</a></summary>


|                                              Subtest                                               | Results |                                                         Messages                                                         |
|----------------------------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------|
|                                                                                                    | OK      |                                                                                                                          |
| `Test driver`                                                                                      | PASS    |                                                                                                                          |
| `Document interface: attribute all`                                                                | PASS    |                                                                                                                          |
| `Stringification of iframe.contentDocument`                                                        | FAIL    | `assert_equals: class string of iframe.contentDocument expected "[object Document]" but got "[object HTMLDocument]"`     |
| `Document interface: iframe.contentDocument must inherit property "all" with the proper type (29)` | FAIL    | `Unrecognized type HTMLAllCollection`                                                                                    |
| `Document must be primary interface of new Document()`                                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "TypeError: Function expected"` |
| `Stringification of new Document()`                                                                | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "TypeError: Function expected"` |
| `Document interface: new Document() must inherit property "all" with the proper type (29)`         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "TypeError: Function expected"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233204916)

# Chrome (unstable) #
Testing web-platform-tests at revision e104604e694364903ed2f8d5146594e392893505

**Comment by foolip** [comment]
Closing since the flakines went away, won't be useful in a bug report.

**Pull request closed without merging**
