### PR TITLE
Test document.fullscreenElement.requestFullscreen()

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@upsuper, PTAL. Chrome Edge and Firefox pass, but Chrome follows an older version of the spec where the check is synchronous in `requestFullscreen()` and I wanted something to guard against regressions when refactoring.

**Comment by foolip** [comment]
@upsuper, I noticed a mistake in the test and pushed an update, but it still passes in Firefox. Can you review?

**Comment by foolip** [comment]
Ping @upsuper @aliams @jernoble for review.

**Comment by foolip** [comment]
@mounirlamouri, would you mind reviewing this random Fullscreen test?

**Review by upsuper — APPROVED** [review]

**Review by mounirlamouri — APPROVED** [review]

**Comment by foolip** [comment]
Thanks for the reviews!

**Pull request merged**
