### PR TITLE
Added 7 new CSS4Pseudo tests and 3 references

### PR DESCRIPTION
**Pull request by TalbotG**
cascade-highlight-001.html 
cascade-highlight-001-ref.html 
cascade-highlight-002.html 
cascade-highlight-004.html 
cascade-highlight-004-ref.html 
grammar-error-002-manual.html 
grammar-error-003-manual.html 
highlight-z-index-001.html 
highlight-z-index-001-ref.html 
highlight-z-index-002.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
The rest of the tests look correct, however I think the z-index tests need some changes:

- The descendant comes before the selected text (makes the test stronger, since usually text after paints over anyway).
- The descendant's text is not highlighted. (Currently you are highlighting the entire contents of #test, including the positioned descendant.)

**Comment by TalbotG** [comment]
> the z-index tests need some changes:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-001-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-001-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-002-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-002-ref-new.html

**Review by fantasai — CHANGES_REQUESTED** [review]
Well, now you say you're testing a positioned descendant, but you don't have a descendant. :) I'm not sure which is better, to have a descendant or to have a previous sibling, but either way the comment and the code should match.

I might also suggest combining both tests into one file. They're very closely related, almost all the code is duplicated, so I think it will be easier to understand if they are in one file.

**Comment by TalbotG** [comment]
> Well, now you say you're testing a positioned descendant, but you don't have a descendant. :) I'm not sure which is better, to have a descendant or to have a previous sibling, but either way the comment and the code should match.

The statement that I was trying to test is:

>  Each highlight pseudo-element draws its background over the corresponding portion of the highlight overlay, painting it immediately below any positioned descendants

coming from [§ 3.5 Painting the Highlight](https://www.w3.org/TR/css-pseudo-4/#highlight-painting)

At first, such statement was not (to me) perfectly explicit or clear since a descendant could refer to the body element (as the referring ancestor) or to the highlighted element itself (as the referring ancestor). Anyway... So, I created 2 tests (z-index-001 involving 'position: relative' and z-index-002 involving 'position: absolute'). And now, I have tuned and tweaked accordingly the css identifiers and the meta assert text of those 2 tests at my website:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-001-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-z-index-002-new.html

> I might also suggest combining both tests into one file. They're very closely related, almost all the code is duplicated, so I think it will be easier to understand if they are in one file.

I think it would be difficult and not best to combine both tests (abs pos and rel pos) into 1 ... but it's doable. I prefer **not** to combine both tests into 1.

In a few min., I will try to make the changes into
highlight-z-index-001.html
highlight-z-index-002.html
in this PR. If it fails because of Community-TC integration check and the need to rebase, then I will just close this PR and create a new PR. So, stay tuned ...

**Comment by TalbotG** [comment]
@fantasai , the modifications I did to the PR went as hoped. So, please review the z-index tests one last time. Thank you!

**Review by fantasai — APPROVED** [review]

**Pull request merged**
