### PR TITLE
move the top-level manual tests in 'accname' to an 'accessibility/manual' subdir

### PR DESCRIPTION
**Pull request by cookiecrook**
This will:
1. keep accessibility tests together, and 
2. make room for the automated accname tests as part of the InterOp 2023 Accessibility Investigation.

### CODE REVIEW

**Comment by cookiecrook** [comment]
Since these are all manual, I don't expect any testing fallout, those @zcorpan may have mentioned a non-WPT dependency related to the ARIA-AT project...

Related to https://github.com/web-platform-tests/interop/issues/211 and https://github.com/w3c/accname/issues/174

**Comment by gsnedders** [comment]
> * keep accessibility tests together

I think in general we've considered this an anti-pattern, versus just grouping things by spec. I think the only place where we really do this is "css", and that's partly tied to legacy.

**Comment by cookiecrook** [comment]
This is editorial prep work for [interop-2023-accessibility-testing](https://github.com/web-platform-tests/interop-2023-accessibility-testing)

**Comment by cookiecrook** [comment]
> I think in general we've considered this an anti-pattern, versus just grouping things by spec. I think the only place where we really do this is "css", and that's partly tied to legacy.

Does this mean you think I should move the manual accname tests to a manual subdir of accname, or just commit all the automated accname tests into the same dir with the manual tests?

**Comment by cookiecrook** [comment]
And if the latter, presumably that means get_computed_label.py should live in accname? or should there be an accname subdir of webdriver?

**Comment by cookiecrook** [comment]
I'm going to close this PR and refile as an issue, so we can get on the same page.

**Comment by gsnedders** [comment]
> @gsnedders wrote:
> 
> > I think in general we've considered this an anti-pattern, versus just grouping things by spec. I think the only place where we really do this is "css", and that's partly tied to legacy.
> 
> Does this mean you think I should move the manual accname tests to a manual subdir of accname, or just commit all the automated accname tests into the same dir with the manual tests?

They should be in `accname`; whether they're in a `manual` subdirectory is kinda up to you/others—we don't really have consistent guidelines there.

> And if the latter, presumably that means get_computed_label.py should live in accname instead of webdriver? or should there be an accname subdir of webdriver?

Alas, because of certain bits of magic, I believe all the WebDriver tests are required to be in webdriver, despite violating that rule. So probably `webdriver/tests/accname`?

**Pull request closed without merging**
