### PR TITLE
Python 3: port small test files in various directories

### PR DESCRIPTION
**Pull request by ziransun**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Review by Ms2ger — APPROVED** [review]

**Comment by jdm** [comment]
I don't know what to make of the fact that there are unstable results for /background-fetch/fetch-uploads.https.window.html and this PR modifies background-fetch/resources/upload.py, but the changes look perfectly fine to me.

**Comment by npm1** [comment]
> I don't know what to make of the fact that there are unstable results for /background-fetch/fetch-uploads.https.window.html and this PR modifies background-fetch/resources/upload.py, but the changes look perfectly fine to me.

Just means the test is flaky (even before this change).

**Review by npm1 — APPROVED** [review]

**Comment by ziransun** [comment]
@jdm can we land this? Let me know if there is any further change needed though. Thank you!

**Comment by jdm** [comment]
We can't land as long as there are failing test results. Can you reproduce the failure locally?

**Comment by jdm** [comment]
Oh, I missed the previous comment. I guess we can force-meege, in that case.

**Pull request merged**
