### PR TITLE
Add tests to confirm document's location getter returns null outside of a browsing context.

### PR DESCRIPTION
**Pull request by Ms2ger**
Rebased from #1757.

### CODE REVIEW

**Review by foolip — APPROVED** [review]
LGTM assuming all browsers will pass. If they don't, I'd like to see a reference to what bit of spec defines this.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19129)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/283153796)

**Comment by Ms2ger** [comment]
@ashughes1 It looks like
```js
      assert_equals(win.location, null);
```
is failing in `location_getter.html`. The spec also doesn't seem to support it. Do you remember where that check came from?

CC @annevk

**Comment by annevk** [comment]
@Ms2ger see https://github.com/whatwg/html/issues/2545#issuecomment-299132453. Seems only Firefox fixed its issue thus far.

**Comment by ashughes1** [comment]
> @ashughes1 It looks like
> 
>       assert_equals(win.location, null);
> 
> is failing in location_getter.html. The spec also doesn't seem to support it. Do you remember where that check came from?

I'm sorry, I do not recall. It's been 2.5 years since I looked at this.

**Comment by Ms2ger** [comment]
We're claiming that the window test is covered by https://github.com/w3c/web-platform-tests/pull/5778.

**Review by annevk — APPROVED** [review]

**Pull request merged**
