### PR TITLE
New test for flex-direction: column-reverse on Safari browsers

### PR DESCRIPTION
**Pull request by LeTraceurSnork**

### CODE REVIEW

**Comment by LeTraceurSnork** [comment]
Instead of getting all the gaps between them, Safari seems to place them all at once BEFORE the entire flexbox block, then place all the inner blocks
Smth like this (picrelated via imgur)
https://imgur.com/a/uW3ZgZD

**Comment by LeTraceurSnork** [comment]
@mrego

**Comment by mrego** [comment]
Isn't this test already covered by http://wpt.live/css/css-flexbox/column-reverse-gap.html ?

If that's the case, this seems to have been fixed in Safari, maybe you're testing an old version: https://bugs.webkit.org/show_bug.cgi?id=225278
See results: https://wpt.fyi/results/css/css-flexbox/column-reverse-gap.html

**Comment by LeTraceurSnork** [comment]
Sorry, my bad then

**Pull request closed without merging**
