### PR TITLE
Upstream animation-reverse-end-exclusive.html from Blink

### PR DESCRIPTION
**Pull request by alancutter**
Import https://chromium.googlesource.com/chromium/src/+/3d473d69a3f7fd0d6cb0b01cf2e9d72c4d068b6f/third_party/WebKit/LayoutTests/web-animations-api/animation-reverse-end-exclusive.html

### CODE REVIEW

**Comment by alancutter** [comment]
This is a behaviour we have in Chrome that I don't think appears in the spec. I'm submitting this mainly to get your opinion on whether this is the correct behaviour or not. Firefox Nightly fails this test (possibly rightly so).

**Comment by birtles** [comment]
I had a look into this and I think it makes sense. On the one hand, it seems preferable that changing the playbackRate doesn't instantaneously change the output, however, if the `currentTime` is zero we will report that the `playState` is `finished`. It's odd that the animation should be finished, and `currentTime` be fixed at zero (due to finishing behavior) and yet will appear to apply a fill mode despite there being no fill mode specified.

We need to fix the spec before landing this so I'm not going to merge this now.

(Also, I noticed that the finishing behavior is wrong in that if you set currentTime to -500, then the next time we run the procedure to update the finished state, we'll reset the currentTime to 0. We should fix that too.)

**Comment by birtles** [comment]
For what it's worth, once this is specced, we'll need to add this test to the appropriate place in the tree (which, in this case, should be something like `timing-model/animation-effects/phases-and-state.html`).

**Comment by birtles** [comment]
I've [added this behavior to the spec](https://github.com/w3c/web-animations/commit/21de090dacc56efcc1ef7a7d04913126f96024ae).

I'll also add a much more thoroughgoing test to web-platform-tests that tests the phase algorithm more closely. I intent to land that via the Gecko repository so hopefully it will show up here in a next week or two.

For now, I'm going to close this without merging since I think this puts the test in the wrong place and because there is another test coming that covers this PR.

**Pull request closed without merging**
