### PR TITLE
Ignore test suite third_party/ directories for lint

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See https://github.com/web-platform-tests/rfcs/issues/46

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Tested via:

```
# before PR
$ mkdir -p webrtc/third_party/sdp
$ touch webrtc/third_party/sdp/.gitignore
$ ./wpt lint webrtc
ERROR:lint:webrtc/third_party/sdp/.gitignore: .gitignore found outside the root (GITIGNORE)
INFO:lint:
INFO:lint:There was 1 error (GITIGNORE: 1)
INFO:lint:You must fix all errors; for details on how to fix them, see
INFO:lint:https://web-platform-tests.org/writing-tests/lint-tool.html
INFO:lint:
INFO:lint:However, instead of fixing a particular error, it's sometimes
INFO:lint:OK to add a line to the lint.whitelist file in the root of the
INFO:lint:web-platform-tests directory to make the lint tool ignore it.
INFO:lint:
INFO:lint:For example, to make the lint tool ignore all 'GITIGNORE'
INFO:lint:errors in the webrtc/third_party/sdp/.gitignore file,
INFO:lint:you could add the following line to the lint.whitelist file.
INFO:lint:
INFO:lint:GITIGNORE: webrtc/third_party/sdp/.gitignore
$
# apply changes from PR
$ ./wpt lint webrtc
$
```

**Review by jgraham — APPROVED** [review]
Would be lovely to have an automated test, but I guess none of the other lint rules have one.

**Comment by stephenmcgruer** [comment]
So I think it's mostly covered by `test_parse_whitelist`, plus `test_lint_ignored_file`. Looking at `lint.py`, it ultimately just loops the list of ignored patterns and passes them to [`fnmatch.fnmatch`](https://docs.python.org/2/library/fnmatch.html#fnmatch.fnmatch).

We could add a specific test for this, though it does blur the lines between testing the lint code and verifying the repository. Which might be fine! Let me know what you think.

**Comment by jgraham** [comment]
I think this is fine as is if we're confident that the syntax is covered and we used the right syntax.

**Pull request merged**
