### PR TITLE
Enabling older browsers values for KeyboardEvent.key in WebDriver tests

### PR DESCRIPTION
**Pull request by jimevans**
When propagating keyboard events, older browsers use different strings
for the "key" property of the KeyboardEvent object. This commit enables
the ability of the WebDriver tests for keyboard events to validate the
comparison to these older values in addition to the values used by
modern browsers. See the footnotes in the sections of the following:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

### CODE REVIEW

**Comment by whimboo** [comment]
Please note that Chrome tests are failing. Please have a look at those results:
https://tools.taskcluster.net/groups/WC_kdXw3RSyOhxUdOfK9qA/tasks/axZqmRlzRs2fdtU0NOeEOQ/runs/0/logs/public%2Flogs%2Flive.log#L1278

**Comment by jimevans** [comment]
@whimboo I’m having a challenge seeing how this change caused those failures. The logs indicate an issue around the Meta modifier key, which I never referenced nor modified in my change. I’d really like to understand what happened here, since I have no control over the fact that Chrome seems to be reporting `OSLeft` and `OSRight` as the key values instead of the expected `MetaLeft` and `MetaRight`.

**Comment by andreastt** [comment]
AIUI these are stability tests so it means this change has made Chrome _unstable_, not that Chrome necessarily does the right thing. I don’t entirely understand _what_ part of the change would make Chrome unstable yet…

**Comment by gsnedders** [comment]
The only failure I see there is:

## Slow tests ##
|                      Test                     | Result | Longest duration (ms) | Timeout (ms) |
|-----------------------------------------------|--------|-----------------------|--------------|
| `/webdriver/tests/perform_actions/pointer.py` | `OK`   | `20489`               | `25000`      |

i.e., `/webdriver/tests/perform_actions/pointer.py` is a bit too close to the timeout for comfort. Just bump up the timeout on that?

**Review by andreastt — APPROVED** [review]
Thanks @gsnedders! It sounds like we should increase the timeout of that test to prevent this from cropping up again.

Otherwise, this patch looks good, so: r+wc

**Pull request merged**
