### PR TITLE
Test that MediaQueryList::{add,remove}Listener parameter is optional

### PR DESCRIPTION
**Pull request by shvaikalesh**
Follow-up of #19841.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
_cc_ @zcorpan @jdm

**Comment by shvaikalesh** [comment]
_cc_ @jdm @zcorpan 🙏

**Comment by shvaikalesh** [comment]
@Ms2ger would you please take a look? I am struggling to get attention for this PR 😓.

**Review by zcorpan — APPROVED** [review]

**Comment by Ms2ger** [comment]
Thanks, @zcorpan !

**Pull request merged**
