### PR TITLE
Test prerender opt-out by response code

### PR DESCRIPTION
**Pull request by noamr**
A util to test different responses and how they affect prerendering.
Currently a straw-man until https://github.com/WICG/nav-speculation/issues/138 is resolved

### CODE REVIEW

**Comment by d0iasm** [comment]
Hello @noamr,

Thank you for writing this test!
Can you land this PR since we (Chromium) want to use your test to make sure our implementation is correct.

**Comment by noamr** [comment]
> Hello @noamr,
> 
> Thank you for writing this test! Can you land this PR since we (Chromium) want to use your test to make sure our implementation is correct.

Sure, on it!

**Comment by noamr** [comment]
> Hello @noamr,
> 
> Thank you for writing this test! Can you land this PR since we (Chromium) want to use your test to make sure our implementation is correct.

It's ready. @nyaxt @jeremyroman review?

**Review by nyaxt — APPROVED** [review]

**Comment by d0iasm** [comment]
@noamr Thank you so much for working on this!
Could you kindly write a test for iframes?
I think we agreed that prerendering is cancelled on certain status code for subframe navigations too.
https://github.com/WICG/nav-speculation/issues/138#issuecomment-1043592045

**Comment by noamr** [comment]
> @noamr Thank you so much for working on this! Could you kindly write a test for iframes? I think we agreed that prerendering is cancelled on certain status code for subframe navigations too. [WICG/nav-speculation#138 (comment)](https://github.com/WICG/nav-speculation/issues/138#issuecomment-1043592045)

I think we haven't reached a conclusion on what should happen with errored same-origin iframes (cancel the whole navigation or leave them errored)

**Pull request merged**
