### PR TITLE
Better comment on what this is testing.

### LINKED ISSUE #6062: [css-flexbox-1] Negative margins floored at zero?
PR [#919](https://github.com/w3c/csswg-test/pull/919) added a test requiring negative margins to be floored at zero for intrinsic size calculations. This behaviour doesn't appear to be specified anywhere, however.

Is this behaviour actually specified, or is the negative-margins-001.html test case incorrect?

### PR DESCRIPTION
**Pull request by cbiesinger**
Fixes #6062

### CODE REVIEW

**Review by dholbert — APPROVED** [review]
LGTM.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/246381563)

# Firefox (nightly) #
Testing web-platform-tests at revision 30694e06ad8ee41497ee6eda0e4e0ce158fc1c2e
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6332/css/css-flexbox-1/negative-margins-001.html">/css/css-flexbox-1/negative-margins-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/246381564)

# Sauce (safari) #
Testing web-platform-tests at revision 30694e06ad8ee41497ee6eda0e4e0ce158fc1c2e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6332/css/css-flexbox-1/negative-margins-001.html">/css/css-flexbox-1/negative-margins-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/246381570)

# Chrome (unstable) #
Testing web-platform-tests at revision 30694e06ad8ee41497ee6eda0e4e0ce158fc1c2e

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/246381571)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 30694e06ad8ee41497ee6eda0e4e0ce158fc1c2e

**Pull request merged**
