### PR TITLE
[idlharness] fix [Default] toJSON test

### LINKED ISSUE #6974: [idlharness] toJSON implementation is broken
Currently, the implementation tests the result of calling the toJSON function on the interface rather than on the passed objects.

### PR DESCRIPTION
**Pull request by tobie**
Additionally, handle typedefs in is_json_type method.

Closes #6974.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7308)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-09-10 08:32:38
Finished: 2017-09-10 08:37:21


<h2>Failing Jobs</h2>
<ul>

<li>resources_unittest in py27</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18356)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/273792864)

**Comment by tobie** [comment]
Additionally, I updated the navigation timing idlharness test to make these changes work (and have a testbed for them): https://github.com/tobie/web-platform-tests/commit/dcb13d26a4c84828a0dabd42b3fbc479a43f5ce5

Not sure if you want me to include that in the same PR.

**Comment by marcoscaceres** [comment]
Just tested this patch on PaymentRequest. `.toJSON()` tests now pass 🎉

**Comment by marcoscaceres** [comment]
@tobie, can you explain what the problem was briefly? I can't figure out how you fixed it from the code.

**Comment by tobie** [comment]
> can you explain what the problem was briefly? I can't figure out how you fixed it from the code.

Absolutely. I made incorrect assumptions about the overall architecture of the code base. While I thought the object passed along was a platform object implementing the interface, it was actually the interface prototype object itself. Hence the breakage. Unfortunately this wasn't picked up by the unit tests I added (a first for idlharness). It would have required integration tests. of which they are none. This was also missed by all the reviewers.

The solution to avoid this in the future would be to add more tests, and refactor idlharness so it better matches the terminology and structure of the WebIDL spec, making both keeping it in sync and code reviews easier.

**Review by marcoscaceres — APPROVED** [review]
Just looking at the code, but without much knowledge of  idlharness, lgtm.

**Pull request merged**
