### PR TITLE
[wptrunner] Add regression tests for server config

### PR DESCRIPTION
**Pull request by jugglinmike**
A recent commit [1] organized WPT configuration management into a
dedicated class. In so doing, it unintentionally disabled the default
secure WebSocket server. A subsequent commit [2] corrected the
regression.

Add a set of tests to demonstrate the intended behavior and to help
avoid future regressions.

[1] bfef1f20a419d24633e48d24c14e6a7503e1d48c
[2] a5a8fbfafd075bf290525ad6a433ec5684ea874d

### CODE REVIEW

**Review by zcorpan — APPROVED** [review]
LGTM but leaving open for gsnedders

**Comment by jgraham** [comment]
I don't think this should be under `assumptions/`. ISTM that those tests are for assumptions about the browser configuration and OS environment. I would create a new directory called `server` or something; you could also move the secure context tests there (same comment on the similar websockets tests).

Otherwise, this looks great; thanks for doing it.

**Comment by gsnedders** [comment]
(my view is simply what @jgraham said, given @zcorpan asked for my views)

**Comment by jugglinmike** [comment]
Okay, I've rebased with a new commit to create and document a directory named `infrastructure/server/`. The original version of this branch is available at https://github.com/w3c/web-platform-tests/compare/master...bocoup:re-enable-web-socket-server-tests-prebase

**Review by jgraham — APPROVED** [review]
I guess in general this would be clearer creating the tests in a loop rather than hardcoding everything, but this is fine.

**Pull request merged**
