### PR TITLE
[css-fonts] Add tests for dynamic changes of font-palette property

### PR DESCRIPTION
**Pull request by litherum**
(I haven't updated the test font yet, like I said I would in https://github.com/web-platform-tests/wpt/pull/30910#discussion_r714487080. However, these tests don't require those updates.)

The relevant WebKit bug is https://bugs.webkit.org/show_bug.cgi?id=230673.

### CODE REVIEW

**Review by nt1m — APPROVED** [review]
This was reviewed on the WebKit bug.

**Comment by drott** [comment]
This looks like a duplicate of #30939 on which I left some comment regarding waiting for document.fonts.ready to be resolved before snapshotting.

**Comment by litherum** [comment]
This isn't a dup of https://github.com/web-platform-tests/wpt/pull/30939. That one is for `font-palette-values`, whilst this one is for `font-palette`.

**Comment by litherum** [comment]
The linter error looks bogus - this version of Ahem is customized to include font palettes.

**Comment by litherum** [comment]
This patch is stale now; I've updated the font in https://github.com/web-platform-tests/wpt/pull/31044.

**Pull request merged**
