### PR TITLE
ensure the same value return when get same blob entry from FormData

### LINKED ISSUE #28924: Found some differences in Blob to File conversion in the FormData
```js
fd = new FormData
fd.set('a', new Blob)
fd.get('a') === fd.get('a') // false in chromium - true in FF & Safari (don't have IE on Mac)
```

Looks like there is no test to cover this senario: https://github.com/web-platform-tests/wpt/blob/e45a9f9e65d039c76817ee2a6a1ef02c9311a1cb/xhr/formdata/set-blob.any.js

I think `fd.get('a') === fd.get('a')` should be true

- [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1207298&q=FormData%20file%20blob&can=2) submitted by myself

### PR DESCRIPTION
**Pull request by F3n67u**
fix https://github.com/web-platform-tests/wpt/issues/28924

### CODE REVIEW

**Review by jimmywarting — APPROVED** [review]

**Comment by annevk** [comment]
@F3n67u would you be interested in adding more asserts?

In particular, when passing in a `Blob`, we want to assert that the passed in blob, is not equal to the blob returned. And when passing in a `File`, it should be equal to the one returned (except when a filename parameter is passed, then it's equal to a blob).

This would require changing this test as as well as "file without lastModified or custom name" and "file with lastModified and custom name".  To compare with the passed in value you'd have to assign that to a variable first, e.g., `const value = new Blob()`.

**Comment by F3n67u** [comment]
> @F3n67u thanks! Would you be interested in adding more asserts?
> 
> In particular, when passing in a `Blob`, we want to assert that the passed in blob, is not equal to the blob returned. And when passing in a `File`, it should be equal to the one returned (except when a filename parameter is passed, then it's equal to a blob).
> 
> This would require changing this test as as well as "file without lastModified or custom name" and "file with lastModified and custom name". To compare with the passed in value you'd have to assign that to a variable first, e.g., `const value = new Blob()`.

Certainly yes.

**Comment by F3n67u** [comment]
@amarant done

**Review by annevk — APPROVED** [review]
Great work, thanks so much!

**Pull request merged**
