### PR TITLE
Test priority of cICP over iCCP

### PR DESCRIPTION
**Pull request by svgeesus**
PNG Third edition [says](https://w3c.github.io/PNG-spec/#cICP-chunk):

> When the cICP chunk is present, decoders that recognize it SHALL ignore the following chunks:

>   [iCCP](https://w3c.github.io/PNG-spec/#11iCCP)

The test file is a PNG with solid sRGB green (0, 128, 0) converted to Display P3 (0.21603749037034126, 0.49418159073224005, 0.13151307826427636). The image has a Display P3 `cICP` chunk. It also has an `iCCP` chunk containing a modified sRGB ICC profile; the red and green colorants are swapped so, if used, the result will be a deep red.

The test HTML also starts with a solid red, in case the image is not loaded at all.

The reference uses an sRGB PNG which is  sRGB green (0, 128, 0).

### CODE REVIEW

**Comment by svgeesus** [comment]
@ProgramMax

**Comment by ProgramMax** [comment]
LGTM, except for the lint error.

It says you need a link to the spec. You have two, though. I'm not sure why it doesn't recognize them.

**Comment by svgeesus** [comment]
Yeah I don't understand the lint error either, especially as it mentions an _entirely unrelated_ spec:

> css/css-highlight-api/historical.window.js: Testcase file must have a link to a spec (MISSING-LINK)

**Comment by svgeesus** [comment]
@web-platform-tests/wpt-core-team any help on resolving this apparently unrelated lint error?

**Comment by zcorpan** [comment]
Rebase to the latest `master` (or any commit after https://github.com/web-platform-tests/wpt/commit/b31783e518cd5c95f3143027fd31ab5b11f3bb36 )

**Review by ProgramMax — APPROVED** [review]
LGTM

**Pull request merged**
