### PR TITLE
[mediacapture-streams]follow spec, update ConstraintNotSatisfiedError to OverconstrainedError

### PR DESCRIPTION
**Pull request by xiuqijix**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261753225)

# Firefox (nightly) #
Testing web-platform-tests at revision 2c40b288f4538e43e75e37cba0c4c14f40f3bb43
Using binary /home/travis/build/w3c/web-platform-tests/_venv/firefox/firefox
Starting tests
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6772/mediacapture-streams/GUM-impossible-constraint.https.html">/mediacapture-streams/GUM-impossible-constraint.https.html</a></summary>


|                               Subtest                               | Results |                  Messages                  |
|---------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                     | OK      |                                            |
| `Tests that setting an impossible constraint in getUserMedia fails` | FAIL    | `navigator.getUserMedia is not a function` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261753226)

# Sauce (safari) #
Testing web-platform-tests at revision 2c40b288f4538e43e75e37cba0c4c14f40f3bb43
Using binary None
Starting tests
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6772/mediacapture-streams/GUM-impossible-constraint.https.html">/mediacapture-streams/GUM-impossible-constraint.https.html</a></summary>


|                               Subtest                               | Results |                                                     Messages                                                     |
|---------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------|
|                                                                     | OK      |                                                                                                                  |
| `Tests that setting an impossible constraint in getUserMedia fails` | FAIL    | `navigator.getUserMedia is not a function. (In 'navigator.getUserMedia', 'navigator.getUserMedia' is undefined)` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261753235)

# Chrome (unstable) #
Testing web-platform-tests at revision 2c40b288f4538e43e75e37cba0c4c14f40f3bb43
Using binary None
Starting tests

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261753236)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 2c40b288f4538e43e75e37cba0c4c14f40f3bb43
Using binary None
Starting tests

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by kaixinjxq** [comment]
Has been done in https://github.com/w3c/web-platform-tests/pull/6429, so close this one.

**Pull request closed without merging**
