### PR TITLE
Add a CSS test for radial gradients.

### PR DESCRIPTION
**Pull request by pyfisch**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5647)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224877885)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224877887)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 6906f1ca1de43f7ef9ae561e405229009731af72
Using browser at version BuildID 20170422100218; SourceStamp 7d85b081bfabe91dbf18a421f1eee2a32f335823
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5647/css/css-images-3/gradients-with-border.html">/css/css-images-3/gradients-with-border.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224877893)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 6906f1ca1de43f7ef9ae561e405229009731af72

**Comment by pyfisch** [comment]
This PR replaces #5645. It uses the correct folder.

@jdm I can see no difference between the two files in Chrome  58.0.3029.81. But if I use capture screenshot from the developer tools fine white lines appear between the different divs.

css-images-3-gradients-with-border html
css-images-3-gradients-with-border-ref html

**Comment by jdm** [comment]
Seems reasonable to merge this, given it's a Chrome rendering discrepancy.

**Pull request merged**
