### PR TITLE
Mark manual Infraware form tests as manual,

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: JUNZ0S1I7W9

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1340133

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5074/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979373)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979376)

**Pull request merged**
