### PR TITLE
Renaming test filenames that clash when removing extension 

### PR DESCRIPTION
**Pull request by youennf**
This is based on discussions in w3c/web-platform-tests#2327
Related lint pull request is https://github.com/w3c/wpt-tools/pull/40

[Review on Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/2349)

### CODE REVIEW

**Comment by jgraham** [comment]
OK. I'm not a huge fan of the -x convention, because it's used both to mean a different test and a support file, but there we go. Please add a more informative commit message explaining why you are doing this.

**Comment by youennf** [comment]
@jgraham, I did a "git commit --amend -m" to update the title of the git commit. 
Is it ok like this? Can you review it?

**Comment by jgraham** [comment]
I think I would really prefer -1 to be -xml or -svg or whatever, even if this means duplicating the extension.

**Comment by jgraham** [comment]
OK, please squash.

**Comment by youennf** [comment]
Can it be merged?

**Comment by youennf** [comment]
Thanks a lot!

**Pull request merged**
