### PR TITLE
Rename viewport/ to visual-viewport/

### PR DESCRIPTION
**Pull request by foolip**
Per discussion in https://github.com/WICG/admin/pull/44.

### CODE REVIEW

**Comment by foolip** [comment]
@bokand, is this OK?

**Comment by foolip** [comment]
Also, can you add an OWNERS file?

**Comment by bokand** [comment]
lgtm. OWNERs file added in #7985 but needs review.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19938)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/293295265)

**Comment by foolip** [comment]
I've merged https://github.com/w3c/web-platform-tests/pull/7985 and will rebase this and merge.

**Pull request merged**
