### PR TITLE
Make wptserve not expose irrelevant resources

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change prevents the wptserve web service from exposing resources that aren’t relevant to users — in particular, any git-related files and any YAML and markdown files — thus limiting the set of exposed resources to just those resources that end users of the web service may have an actual use for.

---

Rationale:

On http://wpt.live/ and http://w3c-test.org/ we really don’t need to be (nor should we be) exposing our git-related files (`.git` and `.github` directories, `.mailmap` file, and `.gitattributes` file) nor the YAML files we use for CI (`.azure-pipelines.yml`, `.codecov.yml`, `.taskcluster.yml`) or whatever (`.pyup.yml`) — nor even really our markdown files (users can can read them at github). For people using the web service, those are all just unwanted clutter we’re forcing them to wade through.

So the patch in this PR is mostly just a naïve attempt at preventing all that.

(I seem to sorta vaguely recall we previously had some kind of thing like this — but if so, I can’t now remember where/when…)

### CODE REVIEW

**Comment by Hexcles** [comment]
It sounds like we should use `.gitignore` though unfortunately `tools.gitignore` isn't complete IIRC from @jgraham .

Short of that, I think perhaps a better strategy is to:
* Err on the aggressive side when hiding things in the directory view: we can probably hide all dot files.
* Err on the conservative side when showing 404: maybe either never return 404 for hidden files, or do so for a shorter list (e.g. dot files in the root directory).

**Comment by Hexcles** [comment]
My concern is that the proposed filter is both too stringent and too lax, depending on the scenarios: e.g. there might be (or will be) more dot files that we want to hide by default, and some tests could reasonably depend on a YAML or Markdown resource file.

**Comment by sideshowbarker** [comment]
> Err on the aggressive side when hiding things in the directory view: we can probably hide all dot files.

Yeah, agreed — I can’t see that there’s ever any user need to view any dot files through the web UI.

> Err on the conservative side when showing 404: maybe either never return 404 for hidden files, or do so for a shorter list (e.g. dot files in the root directory).

OK yes, I agree that responding with 404 all hidden files everywhere in the entire tree is too restrictive — but I think it does make sense to do it for the root directory (of course with the exception of the `.well-known` directory and its contents).

> My concern is that the proposed filter is both too stringent and too lax, depending on the scenarios: e.g. there might be (or will be) more dot files that we want to hide by default

OK yeah I see no downside to hiding all dot files in the directory views.

> and some tests could reasonably depend on a YAML or Markdown resource file

Right. Though I did check and found that currently we don’t seem to have any tests that depend on a YAML or Markdown resource, there’s no good reason for us to prohibit any from doing so in the future. So I think for YAML and Markdown files we should only 404 for the ones in the root directory.

So I’ll update the patch to make the changes described above

**Comment by jgraham** [comment]
I'm not a fan of hardcoding this kind of thing into the server; it is used in a number of other scenarios outside of wpt and they might have different requirements. I also feel like using the gitignore rules as the basis for this would make more sense; although tools.gitignore isn't a perfect implementaion of gitignore it's intentionally good enough for wpt.

**Comment by sideshowbarker** [comment]
In the interest of at least having something at this point that’s functionally what we’d like, I’ve gone ahead and pushed a change to the branch which (based on @Hexcles review feedback), refines the behavior to:

* for directory views: in root directory (but not subdirectories) hide YAML and Markdown files, and in all directories, hide all dot files

* for resource requests: in root directory (but not subdirectories), 404 for dot files

**Comment by sideshowbarker** [comment]
> It sounds like we should use `.gitignore` though unfortunately `tools.gitignore` isn't complete IIRC from @jgraham .
>
> I also feel like using the gitignore rules as the basis for this would make more sense; although tools.gitignore isn't a perfect implementaion of gitignore it's intentionally good enough for wpt.

OK then, I’ll look at reimplementing this based on gitignore rules. I wasn’t actually aware of tools.gitignore, so I’ll start by looking at that.

**Pull request closed without merging**
