### PR TITLE
Added 6 background-size tests

### PR DESCRIPTION
**Pull request by TalbotG**
Those 6 tests are a followup to
[[css-backgrounds-3] background-size with "<length-percentage> auto" and gradient image is not interoperably implemented](https://github.com/w3c/csswg-drafts/issues/2675)

background-size-041.html
background-size-042.html
background-size-043.html
background-size-044.html
background-size-045.html
background-size-046.html
reference/ref-filled-green-100px-square.xht
support/green-intrinsic-none.svg

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
Because of the tiling, it cannot be determined from the test whether the background image is correctly sized or not. You are focusing too much on creating a green square, and not enough on making the test precise. It is better to have a precise test, than to have the test look like a green square. Reftests are automated, it is totally fine for each one to have a different reference. It is nice to have it be an easy-for-humans-to-interpret reference, but it is *important* for it to be a sufficiently restrictive test.

Also, to reduce the time spent on test runs and to reduce the duplication of code, I recommend to combine all these tests into a single file.

Lastly, please use a ratio other than 1:1, to ensure that the UA is not defaulting to 1:1.

**Comment by TalbotG** [comment]
> Because of the tiling, it cannot be determined from the test whether the background image is correctly sized or not. (...) it is _important_ for it to be a sufficiently restrictive test.
(...) to ensure that the UA is not defaulting to 1:1.

@fantasai , It took me a while (and several re-reading) to understand your comment ... but now I think I do. I can create a single test page from (or with) all these 6 tests and then add the pitfall ("embûche") of not having a 1:1 background positioning area (for each sub-tests), therefore making the set of these tests more requiring, more demanding, with more 'banana peels' for the rendering engine.
I can also create another single test page with 4 (or 6 sub-tests) and then test with `background-size: auto 10px` (and `background-size: auto 10%`) and `background-repeat: repeat-y` .

**Review by fantasai — CHANGES_REQUESTED** [review]
Again, “Because of the tiling, it cannot be determined from the test whether the background image is correctly sized or not. You are focusing too much on creating a green [rectangle], and not enough on making the test precise.”. Your test does not check whether the gradient is sized correctly. You cannot actually see the size of the background image, because it is completely green and it is tiled, there is no way to see its boundaries.

The original test in the issue did not have this problem. Because it used a radial gradient, it was possible to see the size of the image even though it is tiled.

You can *either* tile the image *or* make it completely green, but you cannot do both and have a viable test.

**Comment by TalbotG** [comment]
Test:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-size-041-newest1.html

Reference:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/background-size-041-ref-newest1.html

With background-size-041-newest1.html test, I believe it checks the actual size of the (linear-gradient) background image. @fantasai Is such version of the test correct?

**Comment by fantasai** [comment]
Ways this test can pass on an incorrect implementation:

- UA doesn't support background-size at all, or ignores the declaration.
- UA handles sizing in the y axis correctly, but not the x axis.
- UA resolves to a size taller than the background positioning area. (We can't tell if the image was sized correctly, or oversized and clipped to the background painting area.)
- UA assumes a 1:1 ratio -- such an incorrect assumption will still pass 4/6 subtests.

**Comment by TalbotG** [comment]
I must close this PR and close this branch. I will create a new PR in a few min. It will have the most important comments from this PR pasted in the new PR, along with 4 new tests, 4 reference files and 1 short SVG file. [A new TC config was implemented on July 7th](https://github.com/web-platform-tests/wpt/pull/20032#issuecomment-664354222) and that forces me to create a new PR.

**Pull request closed without merging**
