### PR TITLE
Test :host(:has(...)) and :host:has(...) selectors

### PR DESCRIPTION
**Pull request by Westbrook**
- `:host(:has(...))` works really well is Safari, sort of well in Firefox and not at all in Chrome. It's not _really_ spec'd (IIUC) but normalizing on the output expected by developers and provided by Safari already seems like a good destination to work towards
- `:host:has(...)` doesn't work anywhere and isn't spec'd anywhere (IIUC) but this is how I would tentatively expect it to work, similar to that way the `:host(.class)` references a class "outside" of the shadow root and `:host:after` references a pseudo element inside of the shadow root.

Both of these types of selectors would likely benefit from various combinator tests and

### CODE REVIEW

**Comment by tabatkins** [comment]
Ooh, good question about `:host:has()`. I agree it *should* work, but the specs currently mandate that it doesn't; I've opened <https://github.com/w3c/csswg-drafts/issues/10693> to confirm and change this.

**Comment by tabatkins** [comment]
Also, I appreciate that you're using the standard reftest for success, but I do prefer tests which fail with red when possible - mind putting the size and a red background on those elements with a lower-specificity selector, so the successful test will just override the color and make it green?

**Comment by Westbrook** [comment]
I can dig into expanding the red/green results next week!

**Comment by Westbrook** [comment]
@tabatkins this should have the good red/green fail => pass delivery now. Let me know if there's anything else I can do to prepare this for merging. 🙏🏼

**Review by tabatkins — APPROVED** [review]

**Comment by byung-woo** [comment]
I've understood the current status of `:host(:has())` as invalid case  (https://github.com/w3c/csswg-drafts/issues/7953#issuecomment-1349535671):
> This means that :host(:has(...)) is invalid, since its arguments are inherently complex selectors (because they're relative, so there's a combinator), so imposing a compound-selector restriction on them makes all possible arguments invalid.

In case of `:host(:has(section))`, even if the argument of `:has()` is expressed as a compound-selector(`selection`), it has the descendant combinator ('` `') at leftmost which represents the ancestor-descendant relationship between the `:has()` anchor element and the subject element of the `:has()` argument selector.

If this understanding is correct (please correct me if I missed something), it seems that the `:host(:has(section)` case need to be treated in the https://github.com/w3c/csswg-drafts/issues/7953 similar to the other cases that violate the compound-selector restriction on `:host()` (e.g. `:host(:has(> .a)`, `:host(:is(.a .b))`).

How about making the test cases as tentative until there are some more clarification on the restriction?

**Pull request merged**
