### PR TITLE
add url host test: Port number is removed if new port is scheme default

### PR DESCRIPTION
**Pull request by AyushG3112**
This commit adds a test for a bug found with the `node.js` implementation of URL, which was not covered by the existing test cases.

Refs: https://github.com/nodejs/node/pull/20479

### CODE REVIEW

**Comment by annevk** [comment]
Ah, we do have "Default port number is removed" tests, but they do not have a non-default port themselves (at least the host setter variants).

**Comment by annevk** [comment]
Could you maybe locate this test closer to those and indicate how it's different from them? I think that'd make things easier for maintainers.

**Comment by AyushG3112** [comment]
@annevk sure, but just to confirm, is the test `comment` alright does it need changing too?

**Review by annevk — APPROVED** [review]
Thanks, this works for me.

**Pull request merged**
