### PR TITLE
Uncomment test cases from WPT test and move to separate case that can be marked expected fail.

### PR DESCRIPTION
**Pull request by jgraham**
Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1339885

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5072/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208978918)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208978919)

**Pull request merged**
