### PR TITLE
Test requestSubmit + autofocus combination

### PR DESCRIPTION
**Pull request by rwlbuis**
Test requestSubmit + autofocus combination.

### CODE REVIEW

**Review by domenic — CHANGES_REQUESTED** [review]
I'm not sure this is correct given the modern autofocus spec and how it delays for an animation frame: https://html.spec.whatwg.org/#the-autofocus-attribute

@tkent-google may be able to confirm in more detail.

**Comment by rwlbuis** [comment]
> `submitter.onfocus` in the test is never called because adding `autofocus` attribute to a connected element has no effect.

Is there an existing test for "adding `autofocus` attribute to a connected element has no effect so onfocus is never called"? I am not sure WebKit behaves that way.

> Also, the order of autofocusing and iframe load completion is not deterministic, I think.

That is possible.

**Comment by tkent-google** [comment]
> Is there an existing test for "adding `autofocus` attribute to a connected element has no effect so onfocus is never called"? I am not sure WebKit behaves that way.

It seems there are no existing tests.

If I remember correctly, WebKit checks the autofocus attribute when an element gets a RenderObject.  It should be changed.

**Comment by rwlbuis** [comment]
Not working on this anymore, closing.

**Pull request closed without merging**
