### PR TITLE
Revert "[css-sizing-3] Add tests for percentage resolution"

### PR DESCRIPTION
**Pull request by foolip**
Invalid per @mstensho:
https://github.com/web-platform-tests/wpt/commit/86097c04c60a22d7eecb6ea524e898f0c3cb90ed#commitcomment-36116934

Reverts web-platform-tests/wpt#5280

### CODE REVIEW

**Comment by foolip** [comment]
@mstensho should this test just be deleted, or could it be fixed with minor tweaking?

**Comment by mstensho** [comment]
Nothing worth keeping here, as long as the spec is the way it is. The test carefully tests the behavior you would get if min-block-size and max-block-size did something special when set to min-content, max-content and fit-content. Which isn't the case.

**Comment by foolip** [comment]
OK, I’ll revert!

**Comment by mstensho** [comment]
Thank you, @foolip !

**Pull request merged**
