### PR TITLE
Add tests for the writingsuggestions attribute

### PR DESCRIPTION
**Pull request by sanketj**
whatwg/html#9065 proposes the introduction of a new attribute to control UA-provided writing assistance. This PR adds WPT test coverage for that attribute.

Corresponding spec PR: https://github.com/whatwg/html/pull/10018

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
These are really thorough! Was great to see.

**Comment by marcoscaceres** [comment]
Only nit is the formatting... could maybe run prettier over js tests, but no big deal if not.

**Comment by sanketj** [comment]
> Only nit is the formatting... could maybe run prettier over js tests, but no big deal if not.

Thanks. I can look into this as a follow up. For now, landing this to support the implementation in Chromium.

**Comment by stephanieyzhang** [comment]
Some of the getAttribute checks may need to be modified to align with the default behavior of missing/invalid content attributes. The content attributes are not affected by inheritance e.g.:
1. If 'writingSuggestions' is missing on the element, then element..getAttribute('writingSuggestions') == null
2. If 'writingSuggestions' is set to an empty string, then element.getAttribute('writingSuggestions') == ''

This aligns with the content attribute behavior of the 'spellcheck' attribute, which 'writingSuggestions' shares a lot of similarities with.

**Review by annevk — COMMENTED** [review]
I'm missing coverage for:

* input types to which the attribute does not apply.
* Elements that are disabled.

**Comment by dandclark** [comment]
> I'm missing coverage for:
> 
> * input types to which the attribute does not apply.
> * Elements that are disabled.

To be clear -- the attribute setting/getting/reflection behavior that's validated in this test would be the same for those elements. The spec's checks for disabled and non-applicable input types only applies to the steps determining whether the user agent actually applies the suggestions or not.

But, still a good idea to have these tests to verify that the attribute setting/getting/reflection behavior is no different.

**Comment by stephanieyzhang** [comment]
Hi all, we've recently [updated these tests](https://github.com/web-platform-tests/wpt/blob/master/html/editing/editing-0/writing-suggestions/writingsuggestions.html) as part of our implementation in Chromium. The tests include coverage for disabled elements and input types where writing suggestions are not applicable. Since there hasn't been a resolute decision about what the attribute should return for these cases, we've aligned the behavior with other elements where writing suggestions are applicable. Thanks!

**Comment by sanketj** [comment]
As mentioned in [this comment](https://github.com/web-platform-tests/wpt/pull/43780#issuecomment-1960554004), tests for the `writingsuggestions` attribute were added as part of implementing in Chromium and those have been merged into WPT [here](https://github.com/web-platform-tests/wpt/blob/master/html/editing/editing-0/writing-suggestions/writingsuggestions.html). Abandoning this PR accordingly.

**Pull request closed without merging**
