### PR TITLE
Update IDL with user timing L2

### PR DESCRIPTION
**Pull request by plehegar**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18865)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/279985150)

**Comment by plehegar** [comment]
Fixing https://github.com/w3c/user-timing/issues/29

**Review by igrigorik — APPROVED** [review]
👍

**Comment by igrigorik** [comment]
@plehegar can't merge due to failing test: "unstable results". Any idea what's going on there?

**Comment by toddreifsteck** [comment]
The Edge failures should not block this commit.

**Comment by plehegar** [comment]
@igrigorik idlharness has a bug. see #7492 . This PR shouldn't be merged until it get fixed.

**Comment by foolip** [comment]
This test was rewritten in https://github.com/web-platform-tests/wpt/pull/9837 to use interfaces/user-timing.idl, which is up to date with the spec. The PerformanceEntry interface which this PR was added is in interfaces/performance-timeline.idl, which is tested here:
https://wpt.fyi/results/performance-timeline/idlharness.any.html?label=stable&aligned=true

**Pull request closed without merging**
