### PR TITLE
Add a note to the css/README.md about where to add new testsuites

### PR DESCRIPTION
**Pull request by gsnedders**
Per previous discussions with @astearns; cc/ @atanassov

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235951356)

# Firefox (nightly) #
Testing web-platform-tests at revision ea67ba171b6023f6760d313a7847cb5bf5700bf0
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235951357)

# Sauce (safari) #
Testing web-platform-tests at revision ea67ba171b6023f6760d313a7847cb5bf5700bf0
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235951363)

# Chrome (unstable) #
Testing web-platform-tests at revision ea67ba171b6023f6760d313a7847cb5bf5700bf0
Using browser at version 60.0.3107.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235951364)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ea67ba171b6023f6760d313a7847cb5bf5700bf0

**Review by jgraham — APPROVED** [review]

**Pull request merged**
