### PR TITLE
Removed duplicate keys from dicts

### PR DESCRIPTION
**Pull request by rleir**
A minor clean-up:
Quantifiedcode noticed there are duplicate keys.

### CODE REVIEW

**Comment by rleir** [comment]
fixes all occurrences of the following issue:

Issue type: Avoid mutable default arguments
"_Passing mutable lists or dictionaries as default arguments can have unforeseen consequences. Usually when a programmer uses a list or dictionary as the default argument to a function, the programmer wants the program to create a new list or dictionary every time that the function is called. However, this is not what Python does. The first time that the function is called, Python creates a persistent object for the list or dictionary. Every subsequent time the function is called, Python uses that same persistent object that was created from the first call to the function."_
https://www.quantifiedcode.com/app/issue_class/3P0qV6OB

**Comment by zcorpan** [comment]
Changes LGTM. Are there any changes to other files by re-running the scripts with these changes?

**Comment by rleir** [comment]
@zcorpan Do you mean the tools/scripts? Or all tests?

Note that the 'mutable defaults' fix is a functional change. Is there an easy way compare test results with a previous run?

**Comment by Ms2ger** [comment]
Can we keep this PR to the duplicate key changes?

**Comment by zcorpan** [comment]
I meant, if you run the scripts that are modified here, does `git status` say something was changed?

**Comment by rleir** [comment]
@Ms2ger as you like, but I suspect the 'mutable defaults' bit is way more important. I do not have time for this, sorry, would someone like to take it and run?

**Comment by sideshowbarker** [comment]
Per https://github.com/w3c/web-platform-tests/pull/3113#issuecomment-225576369 only merged the duplicate-key changes.

**Pull request closed without merging**
