### PR TITLE
Update the webappsec-referrer-policy IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-05 23:30:09
Finished: 2018-03-05 23:34:43


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25308)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349449483)

**Comment by csnardi** [comment]
Could you also add this file as an untested (or I guess dependency would work now) IDL instead of https://github.com/w3c/web-platform-tests/blob/master/fetch/api/idl.any.js#L11?

**Comment by csnardi** [comment]
Actually, any reason not to just merge this as-is @lukebjerring? I can create a PR for the dependency, and I don't believe idlharness.js currently does anything with enums, so a test wouldn't be needed for the spec.

**Comment by lukebjerring** [comment]
SGTM.

**Review by csnardi — APPROVED** [review]

**Pull request merged**
