### PR TITLE
[Payment Handler] s/topLevelOrigin/topOrigin/

### PR DESCRIPTION
**Pull request by ianbjacobs**
Update tests based on this change:
 https://github.com/w3c/payment-handler/pull/301

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
👍... 😎🎵

**Comment by marcoscaceres** [comment]
Will check the failure tomorrow and fix up any issues. Thanks for doing the fix Ian!

**Comment by ianbjacobs** [comment]
I appreciated the musical rap on the knuckles. :)

**Comment by marcoscaceres** [comment]
Duplicate of https://github.com/w3c/web-platform-tests/pull/10872

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/28389)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/375931601)

**Pull request closed without merging**
