### PR TITLE
URL: file: URLs have implementation-defined origins

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/url/pull/780 for context.

### CODE REVIEW

**Comment by rmisev** [comment]
I think it may be useful to add test written in JS, say with two cases:

* `new URL("file:///").origin === new URL("blob:file:///").origin`
* `new URL("file://host/").origin === new URL("blob:file://host/").origin`

**Comment by anonrig** [comment]
These changes are not sufficient enough for us to verify the correctness. Can you also add a Javascript test as well? Additionally, do we need to change any wording in the specification itself?

**Comment by annevk** [comment]
@anonrig see the link in OP.

I'm not sure we can create those tests @rmisev. While I think I agree with them in spirit, in theory at least the specification allows for those to not be equal.

**Comment by rmisev** [comment]
> I'm not sure we can create those tests @rmisev. While I think I agree with them in spirit, in theory at least the specification allows for those to not be equal.

Hmm, after https://github.com/whatwg/url/pull/780 the specification says this about the origin of blob URL:

> 4. If pathURL’s scheme is "http", "https", or "file", then return pathURL’s origin

So for `blob:file://host/` it must return the origin of `file://host/`. In other words:
`new URL("blob:file://host/").origin === new URL("file://host/").origin`
Why do you say that they can be unequal?

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
