### PR TITLE
Remove unused bluetooth-helpers.js

### PR DESCRIPTION
**Pull request by jdm**
This was accidentally upstreamed from Servo.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214694296)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 77f68599baefe924fd85d9c2b8291eed8c7144b8
Using browser at version BuildID 20170323110205; SourceStamp 7513b3f42058e9bcf9950d4acf4647d4ad2240f0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214694297)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 77f68599baefe924fd85d9c2b8291eed8c7144b8
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by annevk** [comment]
@beaufortfrancois touched this file last so maybe Chrome is actually making use of it?

**Comment by beaufortfrancois** [comment]
@annevk Thanks for the ping.
I think @scheib and @g-ortuno might know.

**Review by scheib — APPROVED** [review]
This removal looks OK to me. 

I don't think web platform tests should have anything for web bluetooth yet, we're working now to refactor chromium's layout tests to be WPT ready but it will take some time.

@zakorgy made the initial commit - so perhaps Servo had some need, but chromium does not.

**Comment by jdm** [comment]
As I said, it was an accidental commit on our part.

**Pull request merged**
