### PR TITLE
Update interfaces/encoding.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/8fb603b/ed/idl/encoding.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/589100816

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Azure Pipelines got stuck on this. Very unlikely related to the change, but still need to investigate and file issues.

**Comment by foolip** [comment]
@mustjab Azure Pipelines looks to have finished correctly, but the status wasn't reported correctly back to GitHub. Can you tell the team about this, maybe retries are needed to make communication more resilient to network errors?

**Comment by mustjab** [comment]
@foolip Forwarded issue and request to pipelines team.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I'll merge this as is so that the checks remain in the state they were. Hopefully it's still possible to investigate when it's closed.

**Pull request merged**
