### PR TITLE
Added 3 new box-shadow tests

### PR DESCRIPTION
**Pull request by TalbotG**
This is a followup to
https://github.com/web-platform-tests/wpt/pull/23658

box-shadow-021.html
box-shadow-029.html
box-shadow-031.html

reference/box-shadow-021-ref.html 
reference/box-shadow-031-ref.html

They contain all of the improvements and review comments made in PR23658.

On my website, these 5 files are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-021-newer.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-021-ref-newer.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-029-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-031-newer.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-031-ref-newer.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
It is much easier to review now that you have combined them, thank you. :)

The regular box-shadow tests include different parsings of the same rendering test. But box-shadow-syntax-001.html already covers the parsing variants. What we need to test here are rendering differences. Right?

So the variations we need are:
* offset up/down/left/right with no spread
* double offset with no spread
* both of the above with spread

Same goes for the inset tests.

(If there's any parsing variations missing in the syntax test, just add them there.)

**Comment by fantasai** [comment]
{Npx 0px, Npx Mpx} &times; { zero spread, positive spread, negative spread } &times { inset, not-inset } = 12

**Comment by TalbotG** [comment]
Not inset:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-037.html

With inset:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-038.html

- I have reused the terminology from the previous comment into the 2 meta-tests for easier understanding.
- I made sure that each sub-test renders differently from each and all of the other 11 sub-tests.
- The table uses a width of 586px, barely under the 600px window viewport requirement.
- Each length used in both meta-tests is a factor of 6: 6px, 12px, 18px, 30px, 36px.
- I have not done the reference files yet.

**Comment by TalbotG** [comment]
I have tried to do the reference files for box-shadow-037.html and box-shadow-038.html and I gave up. It's very difficult. Box shadows do not affect layout and this constraint makes it more difficult to create reference files. After a long thought, I came up with a different design which can help the creation of reference files:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-039.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-039-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-040.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-040-ref.html

Sub-test numbers will remain. 
Coming up shortly are box-shadow-041 and 042 along with their respective reference files.

**Comment by TalbotG** [comment]
I will remove:
css/css-backgrounds/box-shadow-021.html
css/css-backgrounds/reference/box-shadow-021-ref.html
css/css-backgrounds/box-shadow-031.html
css/css-backgrounds/reference/box-shadow-031-ref.html

and I will add:
css/css-backgrounds/box-shadow-039.html
css/css-backgrounds/reference/box-shadow-039-ref.html
css/css-backgrounds/box-shadow-040.html
css/css-backgrounds/reference/box-shadow-040-ref.html
css/css-backgrounds/box-shadow-041.html
css/css-backgrounds/reference/box-shadow-041-ref.html
css/css-backgrounds/box-shadow-042.html
css/css-backgrounds/reference/box-shadow-042-ref.html

and normally
css/css-backgrounds/box-shadow-029.html
should remain as is.

**Comment by TalbotG** [comment]
Amazing! Everything seem to have worked accordingly! @fantasai , please review these tests.

**Review by fantasai — APPROVED** [review]
Looks great, @TalbotG ! Thanks!

**Pull request merged**
