### PR TITLE
Test that worker global scope's name is replaceable

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/html/pull/2783.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245935513)

# Firefox (nightly) #
Testing web-platform-tests at revision 2410cb8d18c3e0fd1e2b17565c97badb2939595d
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6319/workers/name-property.html">/workers/name-property.html</a></summary>


|                            Subtest                            | Results |                Messages               |
|---------------------------------------------------------------|---------|---------------------------------------|
|                                                               | ERROR   |                                       |
| `name property value for SharedWorkerGlobalScope`             | PASS    |                                       |
| `name property value for DedicatedWorkerGlobalScope`          | PASS    |                                       |
| `name property is replaceable for SharedWorkerGlobalScope`    | FAIL    | `setting getter-only property "name"` |
| `name property is replaceable for DedicatedWorkerGlobalScope` | FAIL    | `setting getter-only property "name"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245935514)

# Sauce (safari) #
Testing web-platform-tests at revision 2410cb8d18c3e0fd1e2b17565c97badb2939595d
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6319/workers/name-property.html">/workers/name-property.html</a></summary>


|                                         Subtest                                          | Results |                               Messages                               |
|------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------|
|                                                                                          | ERROR   |                                                                      |
| `Test the name property of shared and dedicated workers via the name constructor option` | FAIL    | `ReferenceError: Can't find variable: SharedWorker`                  |
| `name property value for DedicatedWorkerGlobalScope`                                     | FAIL    | `assert_true: property exists on the global expected true got false` |
| `name property is replaceable for DedicatedWorkerGlobalScope`                            | PASS    |                                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245935520)

# Chrome (unstable) #
Testing web-platform-tests at revision 2410cb8d18c3e0fd1e2b17565c97badb2939595d

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245935521)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 2410cb8d18c3e0fd1e2b17565c97badb2939595d

**Review by wanderview — APPROVED** [review]

**Review by jgraham — APPROVED** [review]

**Pull request merged**
