### PR TITLE
HTML: Add test for <input type=tel> matching :dir()

### PR DESCRIPTION
**Pull request by zcorpan**
Part of testing plan #25569

### CODE REVIEW

**Comment by zcorpan** [comment]
Firefox now fails this test. It doesn't seem to implement this part of the spec:

> If the element is an input element whose type attribute is in the Telephone state, and the dir attribute is not in a defined state (i.e. it is not present or has an invalid value)
>
> The directionality of the element is 'ltr'.

https://html.spec.whatwg.org/multipage/dom.html#the-directionality

**Comment by zcorpan** [comment]
Filed bugzilla.mozilla.org/show_bug.cgi?id=1665655

**Review by domenic — APPROVED** [review]
Looks good, seems to match the spec, and sets us up for better testing in the future by splitting lines. Nice!

**Comment by zcorpan** [comment]
Thanks @domenic! I'd like to see a +1 from @emilio before landing this. 🙂

**Review by emilio — APPROVED** [review]
I'm ok with this as it matches the spec as of right now. If we want to change the spec then this test should be tweaked too of course... I'm personally not a fan of the `<input type=tel>` special-case here, but that's no reason to object :)

**Comment by zcorpan** [comment]
Thanks! File a spec issue if you think the spec should change. 🙂

**Pull request merged**
