### PR TITLE
Notifications: update IDL

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5188/)

**Comment by annevk** [comment]
@beverloo it seems nobody removed onshow/onclose. Should we add them back to the standard?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213511786)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fff0ebcc2a6eed35942e468caf62d2780e7a3008
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5188/notifications/historical.html">/notifications/historical.html</a></summary>


|                   Subtest                    | Results |                 Messages                |
|----------------------------------------------|---------|-----------------------------------------|
|                                              | OK      |                                         |
| `Notification.prototype.onshow was dropped`  | FAIL    | `assert_false: expected false got true` |
| `Notification.prototype.onclose was dropped` | FAIL    | `assert_false: expected false got true` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5188/notifications/interfaces.html">/notifications/interfaces.html</a></summary>


|                                                                                   Subtest                                                                                    | Results |                                                       Messages                                                       |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                              | OK      |                                                                                                                      |
| `Notification interface: existence and properties of interface object`                                                                                                       | PASS    |                                                                                                                      |
| `Notification interface object length`                                                                                                                                       | PASS    |                                                                                                                      |
| `Notification interface object name`                                                                                                                                         | PASS    |                                                                                                                      |
| `Notification interface: existence and properties of interface prototype object`                                                                                             | PASS    |                                                                                                                      |
| `Notification interface: existence and properties of interface prototype object's "constructor" property`                                                                    | PASS    |                                                                                                                      |
| `Notification interface: attribute permission`                                                                                                                               | PASS    |                                                                                                                      |
| `Notification interface: operation requestPermission(NotificationPermissionCallback)`                                                                                        | PASS    |                                                                                                                      |
| `Notification interface: attribute maxActions`                                                                                                                               | FAIL    | `assert_own_property: The interface object must have a property "maxActions" expected property "maxActions" missing` |
| `Notification interface: attribute onclick`                                                                                                                                  | PASS    |                                                                                                                      |
| `Notification interface: attribute onerror`                                                                                                                                  | PASS    |                                                                                                                      |
| `Notification interface: attribute title`                                                                                                                                    | PASS    |                                                                                                                      |
| `Notification interface: attribute dir`                                                                                                                                      | PASS    |                                                                                                                      |
| `Notification interface: attribute lang`                                                                                                                                     | PASS    |                                                                                                                      |
| `Notification interface: attribute body`                                                                                                                                     | PASS    |                                                                                                                      |
| `Notification interface: attribute tag`                                                                                                                                      | PASS    |                                                                                                                      |
| `Notification interface: attribute image`                                                                                                                                    | FAIL    | `assert_true: The prototype object must have a property "image" expected true got false`                             |
| `Notification interface: attribute icon`                                                                                                                                     | PASS    |                                                                                                                      |
| `Notification interface: attribute badge`                                                                                                                                    | FAIL    | `assert_true: The prototype object must have a property "badge" expected true got false`                             |
| `Notification interface: attribute sound`                                                                                                                                    | FAIL    | `assert_true: The prototype object must have a property "sound" expected true got false`                             |
| `Notification interface: attribute vibrate`                                                                                                                                  | FAIL    | `assert_true: The prototype object must have a property "vibrate" expected true got false`                           |
| `Notification interface: attribute timestamp`                                                                                                                                | FAIL    | `assert_true: The prototype object must have a property "timestamp" expected true got false`                         |
| `Notification interface: attribute renotify`                                                                                                                                 | FAIL    | `assert_true: The prototype object must have a property "renotify" expected true got false`                          |
| `Notification interface: attribute silent`                                                                                                                                   | FAIL    | `assert_true: The prototype object must have a property "silent" expected true got false`                            |
| `Notification interface: attribute requireInteraction`                                                                                                                       | PASS    |                                                                                                                      |
| `Notification interface: attribute data`                                                                                                                                     | PASS    |                                                                                                                      |
| `Notification interface: attribute actions`                                                                                                                                  | FAIL    | `assert_true: The prototype object must have a property "actions" expected true got false`                           |
| `Notification interface: operation close()`                                                                                                                                  | PASS    |                                                                                                                      |
| `Notification must be primary interface of new Notification("Running idlharness.")`                                                                                          | PASS    |                                                                                                                      |
| `Stringification of new Notification("Running idlharness.")`                                                                                                                 | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "permission" with the proper type (0)`                                                | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "requestPermission" with the proper type (1)`                                         | PASS    |                                                                                                                      |
| `Notification interface: calling requestPermission(NotificationPermissionCallback) on new Notification("Running idlharness.") with too few arguments must throw TypeError`   | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "maxActions" with the proper type (2)`                                                | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "onclick" with the proper type (3)`                                                   | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "onerror" with the proper type (4)`                                                   | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "title" with the proper type (5)`                                                     | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "dir" with the proper type (6)`                                                       | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "lang" with the proper type (7)`                                                      | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "body" with the proper type (8)`                                                      | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "tag" with the proper type (9)`                                                       | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "image" with the proper type (10)`                                                    | FAIL    | `assert_inherits: property "image" not found in prototype chain`                                                     |
| `Notification interface: new Notification("Running idlharness.") must inherit property "icon" with the proper type (11)`                                                     | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "badge" with the proper type (12)`                                                    | FAIL    | `assert_inherits: property "badge" not found in prototype chain`                                                     |
| `Notification interface: new Notification("Running idlharness.") must inherit property "sound" with the proper type (13)`                                                    | FAIL    | `assert_inherits: property "sound" not found in prototype chain`                                                     |
| `Notification interface: new Notification("Running idlharness.") must inherit property "vibrate" with the proper type (14)`                                                  | FAIL    | `assert_inherits: property "vibrate" not found in prototype chain`                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "timestamp" with the proper type (15)`                                                | FAIL    | `assert_inherits: property "timestamp" not found in prototype chain`                                                 |
| `Notification interface: new Notification("Running idlharness.") must inherit property "renotify" with the proper type (16)`                                                 | FAIL    | `assert_inherits: property "renotify" not found in prototype chain`                                                  |
| `Notification interface: new Notification("Running idlharness.") must inherit property "silent" with the proper type (17)`                                                   | FAIL    | `assert_inherits: property "silent" not found in prototype chain`                                                    |
| `Notification interface: new Notification("Running idlharness.") must inherit property "requireInteraction" with the proper type (18)`                                       | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "data" with the proper type (19)`                                                     | PASS    |                                                                                                                      |
| `Notification interface: new Notification("Running idlharness.") must inherit property "actions" with the proper type (20)`                                                  | FAIL    | `assert_inherits: property "actions" not found in prototype chain`                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "close" with the proper type (21)`                                                    | PASS    |                                                                                                                      |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "addEventListener" with the proper type (0)`                                           | PASS    |                                                                                                                      |
| `EventTarget interface: calling addEventListener(DOMString,EventListener,boolean) on new Notification("Running idlharness.") with too few arguments must throw TypeError`    | PASS    |                                                                                                                      |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "removeEventListener" with the proper type (1)`                                        | PASS    |                                                                                                                      |
| `EventTarget interface: calling removeEventListener(DOMString,EventListener,boolean) on new Notification("Running idlharness.") with too few arguments must throw TypeError` | PASS    |                                                                                                                      |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "dispatchEvent" with the proper type (2)`                                              | PASS    |                                                                                                                      |
| `EventTarget interface: calling dispatchEvent(Event) on new Notification("Running idlharness.") with too few arguments must throw TypeError`                                 | PASS    |                                                                                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213511787)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fff0ebcc2a6eed35942e468caf62d2780e7a3008
Using browser at version 59.0.3043.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5188/notifications/historical.html">/notifications/historical.html</a></summary>


|                   Subtest                    | Results |                 Messages                |
|----------------------------------------------|---------|-----------------------------------------|
|                                              | OK      |                                         |
| `Notification.prototype.onshow was dropped`  | FAIL    | `assert_false: expected false got true` |
| `Notification.prototype.onclose was dropped` | FAIL    | `assert_false: expected false got true` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5188/notifications/interfaces.html">/notifications/interfaces.html</a></summary>


|                                                                                   Subtest                                                                                    | Results |                                                              Messages                                                             |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                              | OK      |                                                                                                                                   |
| `Notification interface: existence and properties of interface object`                                                                                                       | PASS    |                                                                                                                                   |
| `Notification interface object length`                                                                                                                                       | PASS    |                                                                                                                                   |
| `Notification interface object name`                                                                                                                                         | PASS    |                                                                                                                                   |
| `Notification interface: existence and properties of interface prototype object`                                                                                             | FAIL    | `assert_equals: class string of Notification.prototype expected "[object NotificationPrototype]" but got "[object Notification]"` |
| `Notification interface: existence and properties of interface prototype object's "constructor" property`                                                                    | PASS    |                                                                                                                                   |
| `Notification interface: attribute permission`                                                                                                                               | PASS    |                                                                                                                                   |
| `Notification interface: operation requestPermission(NotificationPermissionCallback)`                                                                                        | PASS    |                                                                                                                                   |
| `Notification interface: attribute maxActions`                                                                                                                               | PASS    |                                                                                                                                   |
| `Notification interface: attribute onclick`                                                                                                                                  | PASS    |                                                                                                                                   |
| `Notification interface: attribute onerror`                                                                                                                                  | PASS    |                                                                                                                                   |
| `Notification interface: attribute title`                                                                                                                                    | PASS    |                                                                                                                                   |
| `Notification interface: attribute dir`                                                                                                                                      | PASS    |                                                                                                                                   |
| `Notification interface: attribute lang`                                                                                                                                     | PASS    |                                                                                                                                   |
| `Notification interface: attribute body`                                                                                                                                     | PASS    |                                                                                                                                   |
| `Notification interface: attribute tag`                                                                                                                                      | PASS    |                                                                                                                                   |
| `Notification interface: attribute image`                                                                                                                                    | PASS    |                                                                                                                                   |
| `Notification interface: attribute icon`                                                                                                                                     | PASS    |                                                                                                                                   |
| `Notification interface: attribute badge`                                                                                                                                    | PASS    |                                                                                                                                   |
| `Notification interface: attribute sound`                                                                                                                                    | FAIL    | `assert_true: The prototype object must have a property "sound" expected true got false`                                          |
| `Notification interface: attribute vibrate`                                                                                                                                  | PASS    |                                                                                                                                   |
| `Notification interface: attribute timestamp`                                                                                                                                | PASS    |                                                                                                                                   |
| `Notification interface: attribute renotify`                                                                                                                                 | PASS    |                                                                                                                                   |
| `Notification interface: attribute silent`                                                                                                                                   | PASS    |                                                                                                                                   |
| `Notification interface: attribute requireInteraction`                                                                                                                       | PASS    |                                                                                                                                   |
| `Notification interface: attribute data`                                                                                                                                     | PASS    |                                                                                                                                   |
| `Notification interface: attribute actions`                                                                                                                                  | PASS    |                                                                                                                                   |
| `Notification interface: operation close()`                                                                                                                                  | PASS    |                                                                                                                                   |
| `Notification must be primary interface of new Notification("Running idlharness.")`                                                                                          | PASS    |                                                                                                                                   |
| `Stringification of new Notification("Running idlharness.")`                                                                                                                 | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "permission" with the proper type (0)`                                                | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "requestPermission" with the proper type (1)`                                         | PASS    |                                                                                                                                   |
| `Notification interface: calling requestPermission(NotificationPermissionCallback) on new Notification("Running idlharness.") with too few arguments must throw TypeError`   | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "maxActions" with the proper type (2)`                                                | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "onclick" with the proper type (3)`                                                   | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "onerror" with the proper type (4)`                                                   | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "title" with the proper type (5)`                                                     | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "dir" with the proper type (6)`                                                       | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "lang" with the proper type (7)`                                                      | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "body" with the proper type (8)`                                                      | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "tag" with the proper type (9)`                                                       | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "image" with the proper type (10)`                                                    | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "icon" with the proper type (11)`                                                     | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "badge" with the proper type (12)`                                                    | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "sound" with the proper type (13)`                                                    | FAIL    | `assert_inherits: property "sound" not found in prototype chain`                                                                  |
| `Notification interface: new Notification("Running idlharness.") must inherit property "vibrate" with the proper type (14)`                                                  | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "timestamp" with the proper type (15)`                                                | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "renotify" with the proper type (16)`                                                 | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "silent" with the proper type (17)`                                                   | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "requireInteraction" with the proper type (18)`                                       | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "data" with the proper type (19)`                                                     | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "actions" with the proper type (20)`                                                  | PASS    |                                                                                                                                   |
| `Notification interface: new Notification("Running idlharness.") must inherit property "close" with the proper type (21)`                                                    | PASS    |                                                                                                                                   |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "addEventListener" with the proper type (0)`                                           | PASS    |                                                                                                                                   |
| `EventTarget interface: calling addEventListener(DOMString,EventListener,boolean) on new Notification("Running idlharness.") with too few arguments must throw TypeError`    | PASS    |                                                                                                                                   |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "removeEventListener" with the proper type (1)`                                        | PASS    |                                                                                                                                   |
| `EventTarget interface: calling removeEventListener(DOMString,EventListener,boolean) on new Notification("Running idlharness.") with too few arguments must throw TypeError` | PASS    |                                                                                                                                   |
| `EventTarget interface: new Notification("Running idlharness.") must inherit property "dispatchEvent" with the proper type (2)`                                              | PASS    |                                                                                                                                   |
| `EventTarget interface: calling dispatchEvent(Event) on new Notification("Running idlharness.") with too few arguments must throw TypeError`                                 | PASS    |                                                                                                                                   |

</details>
</details>

**Comment by beverloo** [comment]
@annevk Our metrics aren't conclusive (@foolip [suggested an improvement](http://crbug.com/437286#c6)), but I'm aware of various parties still using them and relying on them. The cost of supporting them is low since we need the same infrastructure for persistent notifications, so undeprecating works for us.

**Comment by annevk** [comment]
@beverloo could you have another look at this too?

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24942)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346778494)

**Comment by beverloo** [comment]
This looks good to me, thanks. It matches the IDL in the spec.

Would it be good to update this at some point to notification.idl, and then run the idl harness separately in a document and in the different workers, so that we can test the Service Worker-exposed API too?

**Review by foolip — APPROVED** [review]

**Pull request merged**
