### PR TITLE
make EventHandler its own IDL file

### PR DESCRIPTION
**Pull request by marcoscaceres**
Proposal that might encourage people to test EventHandler properly.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18428)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/274447688)

**Comment by marcoscaceres** [comment]
@domenic maybe ping? Not sure who to ask.

**Review by domenic — CHANGES_REQUESTED** [review]
It seems a bit of a shame that now everyone needs to include this, not just html.idl, hmm.

In any case, missing cssom/interfaces.html update at least. My IDE is still searching for other instances of `html.idl` throughout the project.... can you do that maybe?

**Comment by domenic** [comment]
IDE finished searching. Full list:

- cssom/interfaces.html
- cssom-view/interfaces.html
- dom/interfaces.html
- dom/interfaces.worker.js
- html/webappapis/scripting/events/event-handler-all-global-events.htm

looks like most of these are covered, but please get them all.

**Comment by marcoscaceres** [comment]
@domenic, thanks! argh... my grep foo was out!

**Comment by foolip** [comment]
What's the status of this? It'd conflict with any fix for https://github.com/w3c/web-platform-tests/issues/9026.

And splitting the IDL of any spec would be a slight complication for https://github.com/w3c/web-platform-tests/issues/7784.

**Comment by marcoscaceres** [comment]
I guess it depends if #7784 will happen.

**Comment by foolip** [comment]
That will happen this quarter, is the plan.

**Comment by marcoscaceres** [comment]
I'm ok for this to be closed then. It sounds like splitting this out will cause more harm than good.

**Pull request closed without merging**
