### PR TITLE
Make sure trickle responses aren't cached

### PR DESCRIPTION
**Pull request by gsnedders**
Occasionally, I've seen browsers decide to cache trickle responses; this obviously causes breakage as they then load instantly.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6732)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/wptserve/wptserve/pipes.py, line 234 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6732#-KqcWTYwUaf21hEg3lA2:-KqcWTYxpfOB5yNJBIEl:b1dnab3) ([raw file](https://github.com/w3c/web-platform-tests/blob/41fe1166c8f578623ed85f28cc5cd226ea40b2f3/tools/wptserve/wptserve/pipes.py#L234)):*
> ```Python
>     offset = [0]
> 
>     response.headers.set("Cache-Control", "no-cache, no-store, must-revalidate")
> ```

Should you check these headers aren't already set by the test before setting them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6732)*

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260635263)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260635264)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260635271)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260635272)

# Sauce (MicrosoftEdge) #

**Comment by gsnedders** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/wptserve/wptserve/pipes.py, line 234 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6732#-KqcWTYwUaf21hEg3lA2:-KqcWp06r31rcUItav0f:bgouw4w) ([raw file](https://github.com/w3c/web-platform-tests/blob/41fe1166c8f578623ed85f28cc5cd226ea40b2f3/tools/wptserve/wptserve/pipes.py#L234)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Should you check these headers aren't already set by the test before setting them?
</blockquote></details>

My viewpoint was that for trickle to be at all meaningful, the response must be uncached, which implies that we never want any other caching behaviour, and hence we don't care if they're set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6732)*

**Comment by gsnedders** [comment]
16:19 < jgraham> gsnedders: I think tests should be able to opt out by explicitly setting headers
16:19 < jgraham> Maybe you load a very slow loading resource and then check that the cache worked 
                 by timing a second load e.g.

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-11-24 12:53:35
Finished: 2017-11-24 13:05:08


<h2>Failing Jobs</h2>
<ul>

<li>tools_unittest in py27</li>

<li>tools_unittest in pypy</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21020)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/306747163)

**Review by jgraham — APPROVED** [review]

**Pull request merged**
