### PR TITLE
add origin, same-origin and update no referrer tests

### PR DESCRIPTION
**Pull request by rebstar6**
- Changed 'Origin-Only' tests to 'Origin'
- Added 'Same-Origin' policy
- Updated 'no referrer set' to follow 'No-Referrer-When-Downgrade'
- Updated all reference links

### CODE REVIEW

**Comment by rebstar6** [comment]
@jdm fyi

**Comment by jdm** [comment]
Separate commits would have been nice for each change in isolation :)

**Comment by rebstar6** [comment]
These are quick to change - I can redo.

**Comment by rebstar6** [comment]
...and done.

**Comment by jdm** [comment]
Github's interface isn't allowing me to comment on the relevant files in the commits (since they don't show up because there are too many), so here are my comments:
* https://github.com/rebstar6/web-platform-tests/blob/d3ae399f642f758f2fc8d9fc9bbc834f0cdbed49/referrer-policy/spec.src.json#L134 - shouldn't this be same-origin?
* https://github.com/rebstar6/web-platform-tests/blob/d3ae399f642f758f2fc8d9fc9bbc834f0cdbed49/referrer-policy/spec.src.json#L170 - same-origin-upgrade and same-origin-downgrade are identical (I assume this is due to copying an existing entry that I filed #3158 about)
* https://github.com/w3c/web-platform-tests/pull/3153/commits/8607feae4d800255f71dc3057eba16f844d7b52c#diff-97bd487a11b9ffb6a881c64a052c2077R41 - https->http should have no referrer, per the policy name

Sorry about the delay here; I had to bone up on the format of the JSON file, and I found the expansion overrides particularly confusing.

**Comment by rebstar6** [comment]
No worries on timing!
1. yep, good call.
2. also yep. mmm remove downgrade? The downgrade tests are never created anyway. And same-origin doesn't care about up/downgrading anyway, just origin.
3. Wow, another bug copy/pasted. That's what no-referrer-when-downgrade has, which is clearly also wrong. Another hrmmm from me.

**Comment by jdm** [comment]
Yes, let's remove the upgrade/downgrade tests. Let's fix the no-referrer-when-downgrade case as well.

**Comment by rebstar6** [comment]
Ok to all. This is going to be impossible to rebase given the intermediate files generated...squash into one, or redo as separate commits?

**Comment by jdm** [comment]
Redo as separate commits would be ideal.

**Comment by rebstar6** [comment]
@jdm all set!

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
