### PR TITLE
[xhr] Tolerate expected variation

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Review by annevk — COMMENTED** [review]
You could make this more explicit if you wanted to. It's required to be dispatched whenever progress is dispatched. So those counts would have to be equal.

**Comment by jugglinmike** [comment]
@annevk I agree that would be good to verify, but it also seems sufficiently distinct to warrant a separate test and a separate pull request. I started to write another patch, but there appears to be ambiguity in the spec. [I've filed a pull request to discuss that](https://github.com/whatwg/xhr/pull/246); would you be comfortable merging this and continuing the discussion about the event (and additional tests) there?

**Comment by jugglinmike** [comment]
(discovered while [researching discrepancies in test results for Safari between WPT's various results collectors](https://github.com/web-platform-tests/results-collection/issues/646))

**Comment by jugglinmike** [comment]
Thanks!

**Pull request merged**
