### PR TITLE
P2 Add Client.type to WPT tests.

### PR DESCRIPTION
**Pull request by jgraham**
Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1339844

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5071/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208975944)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208975945)

**Pull request merged**
