### PR TITLE
Cache manifest in travis

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6452)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249690379)

# Firefox (nightly) #
Testing web-platform-tests at revision 0e61d61b79bf8b8ec138a18419064c7cef4fdadf

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249690380)

# Sauce (safari) #
Testing web-platform-tests at revision 0e61d61b79bf8b8ec138a18419064c7cef4fdadf

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249690386)

# Chrome (unstable) #
Testing web-platform-tests at revision 0e61d61b79bf8b8ec138a18419064c7cef4fdadf

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249690387)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 0e61d61b79bf8b8ec138a18419064c7cef4fdadf

**Comment by jgraham** [comment]
@gsnedders This does cache properly in the stability check, so it's all good to land once reviewed.

**Review by bobholt — APPROVED** [review]

**Pull request merged**
