### PR TITLE
fix(resources/testdriver): wait for a document.body

### PR DESCRIPTION
**Pull request by marcoscaceres**
`bless()` is racy with document.body. It should actually wait for there to be a body.

### CODE REVIEW

**Comment by gsnedders** [comment]
We could also in principle not be an HTML document and not have a body (or have the body removed by a script); we should probably more generally handle the case when there is no body.

I'm a bit skeptical about whether we actually want to block tests on DOMContentLoaded, though?

**Comment by jugglinmike** [comment]
This patch introduces ES2017 syntax which bucks the trend in the testdriver.js utility and in the `resources/` directory at large. I don't think that's necessary; is that right?

> We could also in principle not be an HTML document and not have a body (or have the body removed by a script); we should probably more generally handle the case when there is no body.

What do you think about waiting for a test to require support for that?

> I'm a bit skeptical about whether we actually want to block tests on DOMContentLoaded, though?

Can you say more?

**Comment by gsnedders** [comment]
> This patch introduces ES2017 syntax which bucks the trend in the testdriver.js utility and in the resources/ directory at large. I don't think that's necessary; is that right?

Oh that's true, and as long as https://github.com/servo/servo/issues/20585 is yet to land it'll break it on Servo (though AFAIK there's no Servo support for it), so idk how much that matters.

> What do you think about waiting for a test to require support for that?

FWIW, I know we've had previous cases where people have avoided features because "oh that doesn't work unless you're HTML" before without telling us for a long time, so I'd rather have a small workaround for it (`(document.body || document.documentElement)` should do).

> Can you say more?

Normally tests start running before DOMContentLoaded, so this would be a subtle difference when using `bless`, which doesn't seem ideal.

**Comment by jugglinmike** [comment]
> Oh that's true, and as long as servo/servo#20585 is yet to land it'll break it on Servo (though AFAIK there's no Servo support for it), so idk how much that matters.

Consistency matters, but I think the troubling part is we currently advocate for consistency derived from precedence. Without something like gh-6333, all we can really say is, "please don't rock the boat." That's only going to get more discouraging as TC-39 adds more features, but we should talk about that in gh-6333.

> FWIW, I know we've had previous cases where people have avoided features because "oh that doesn't work unless you're HTML" before without telling us for a long time, so I'd rather have a small workaround for it ((document.body || document.documentElement) should do).

That's worth a lot! I'm convinced that we should do this. And test for it.

> Normally tests start running before DOMContentLoaded, so this would be a subtle difference when using `bless`, which doesn't seem ideal.

That would be more concerning if this were testharness-level behavior. As it stands, though, tests will still start running before the event. The delay isn't so much a "subtle difference" among tests of the same type. It's more that the delay is an intentional feature of the API which tests will be explicitly invoking.

I [snuck](https://www.youtube.com/watch?v=q51ld-scMI8) "intentional feature" in there, though. Since this is intended to be used for features that require user activation, then I think it's appropriate to wait for DOMContentLoaded. (Hopefully there's no API that requires users to click prior to document ready :P) If you buy that, then we can update the docs accordingly.

**Comment by marcoscaceres** [comment]
@gsnedders wrote
> We could also in principle not be an HTML document 

I'm a bit confused... I'm not sure how then creating a "button" would work if it's not HTML, as the expectation is that it's a `HTMLButtonElement` and will behave as such?  

> This patch introduces ES2017 syntax which bucks the trend in the testdriver.js utility and in the resources/ directory at large. I don't think that's necessary; is that right?

One could definitely write this using lots of promises, `.then()`s, and the old syntax. However,  that make the code much less maintainable and readable, so seems somewhat irresponsible to do that. As you state, "consistency matters, but I think the troubling part is we currently advocate for consistency derived from precedence." 

I agree is not a good reason to keep using the current style: It be nice to modernize our development practices - there is nothing particularly radical about using async/await or anything else in this patch. For new things, why not just use async/await and new object syntax?

**Comment by jgraham** [comment]
A button will work as a button even if the root is SVG or XHTML or some other type that doesn't necessarily have a body.

We are more conservative in features for this mind of shared infrastructure than we are in features for tests; for tests there's a clear rule which is "latest Blink / EdgeHTML / Gecko / WebKit must support all features", for stuff in `resources` it's more fuzzy, but I would hold off from using `async`/`await` syntax at this time since it doesn't seem worthwhile to break e.g. Servo (I would also avoid discussing this in terms of moral positions, which is unhelpful when it's a question of technical tradeoffs).

**Comment by marcoscaceres** [comment]
Ok, will rewrite it ☺️

**Review by Ms2ger — APPROVED** [review]
This seems reasonable enough.

**Comment by jugglinmike** [comment]
[A separate pull request introduces tests for this method](https://github.com/web-platform-tests/wpt/pull/11840), but it's been overlooked for over a month. I've updated it to include a test for this fix. Hopefully we'll see it in `master` soon!

**Pull request merged**
