### PR TITLE
Add tests for proxying modifier clicks on label to labeled elements

### PR DESCRIPTION
**Pull request by muan**
> On platforms where clicking a label activates the form control, clicking the label in the following snippet could trigger the user agent to fire a click event at the input element, as if the element itself had been triggered by the user ([Spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element:the-label-element-10))

These tests are for a behavior reported in https://bugzilla.mozilla.org/show_bug.cgi?id=559506.

I ran them locally on Safari, Chrome, and Firefox on macOS. They pass in Chrome and Safari, but fail in Firefox.

I've also manually tested this using browserstack on Windows in Chrome, Edge 18/81, Firefox, and Firefox's behavior is slightly different where alt+click will trigger click, but still not the others.

On macOS ctrl clicks are right clicks and trigger context menus, so I just didn't include them.

---

Currently these fail on Firefox as timeouts as the click listeners were never reached. I'd love suggestions on how to make them fail more explicitly.

### CODE REVIEW

**Review by johndai1984 — APPROVED** [review]

**Comment by annevk** [comment]
So these are testing activation behavior (through the synthetic click event) instead. What would the expected result be if the modifiers were unset (activation behavior as specified ignores these)?

To test actual clicks this would have to use the framework whose name I never remember.

**Comment by muan** [comment]
> What would the expected result be if the modifiers were unset (activation behavior as specified ignores these)?

It should behave like the tests in `html/semantics/forms/the-label-element/proxy-click-to-associated-element.html` which calls `.click()` directly. 

> To test actual clicks this would have to use the framework whose name I never remember.

I agree. However, I looked into testdriver/testdriver-actions, which provide `click`/`setPointer`/`pointerDown`/etc functions, but as far as I can see it doesn't let me set modifier keys.

**Comment by annevk** [comment]
Okay, so we should make the descriptions match that, i.e., "modifier key X should be ignored when dispatching a synthetic click event". With that this seems good to me.

**Comment by annevk** [comment]
James suggested that using actions as documented at https://web-platform-tests.org/writing-tests/testdriver.html might be able to do what you want. I guess you'd compose a sequence of clicking modifier key followed by a mouse click and then let the browser do the rest.

**Comment by muan** [comment]
> so we should make the descriptions match that, i.e., "modifier key X should be ignored when dispatching a synthetic click event". With that this seems good to me.

Thanks! I take it you meant the test HTML file's `<title>`? I've made the change.

**Comment by muan** [comment]
> I guess you'd compose a sequence of clicking modifier key followed by a mouse click and then let the browser do the rest.

Oh, thanks! That definitely seems more correct. Let me give that a go.

**Comment by muan** [comment]
@annevk Thanks for the tip. I've rewrote the test now and it seems to work in Chrome (passes) and Firefox(fails) correctly. However, running the test locally with headless Safari I get this error:

```
InvalidArgumentException: invalid argument (400): Encountered pause action with missing or invalid 'duration' in payload: {
    actions =     (
                {
            type = keyDown;
            value = "\Ue008";
        },
                {
            type = pause;
        },
                {
            type = pause;
        },
                {
            type = keyUp;
            value = "\Ue008";
        }
    );
    id = 1;
    type = key;
}
```

which I tried to fix locally by passing in `duration: 0` on these two lines:

https://github.com/web-platform-tests/wpt/blob/01dfc0f42edacd529749fcf543e16431ba7a9490/resources/testdriver-actions.js#L313
https://github.com/web-platform-tests/wpt/blob/01dfc0f42edacd529749fcf543e16431ba7a9490/resources/testdriver-actions.js#L356

This fixes the error, and gets the test passing in Safari `--headless`. **However**, I asserted the modifier keys on the label's click events (`event.altKey` and friends) and they return false, while they return true in Chrome and Firefox as expected. This seems like a deeper problem than just the missing duration.

**Comment by annevk** [comment]
@burg could you help out with the Safari testdriver issue?

**Comment by burg** [comment]
Hello folks,

Based on my understanding of the thread, testdriver is sending Perform Actions with a Keydown for a sticky key modifier, then a Mousedown/Pointerdown. But the modifier isn't actually present as expected on the click event object. Is that correct?

If you can produce a standalone test case, that would help expedite the investigation. My email is bburg [at] apple.com.

**Comment by annevk** [comment]
@burg yeah, is the PR here not sufficient? I don't think any of us know how to use this outside the context of web-platform-tests.

**Comment by burg** [comment]
I can try to investigate further, but I’m quite busy. There is a good chance this corresponds to an existing WebDriver wpt test failure. I’ll look it up in the AM.

**Comment by muan** [comment]
If it helps, here's the test file (and the temporary `duration` fix) I added to assert the modifier keys on click: https://github.com/muan/wpt/pull/1. Tests fail in Safari, pass in Chrome and Firefox.

**Comment by burg** [comment]
Hi friends, it seems like another WebKit developer has posted a patch for a bug which is curiously very similar to what muan encountered. This would likely be shipped in Safari Technology Preview 109 at the earliest.

https://bugs.webkit.org/show_bug.cgi?id=212848

**Comment by muan** [comment]
I merged master, and unfortunately am still getting the errors I mentioned in https://github.com/web-platform-tests/wpt/pull/23781#issuecomment-634862131 when running tests in Safari. [It errors in wpt.fyi checks](https://github.com/web-platform-tests/wpt/runs/1103194657) as well.

1. Testdriver complains the lack of `duration` argument
2. I attempted to fix 1 by adding `duration: 0` and was able to run the tests, but modifier keys weren't registering (https://github.com/muan/wpt/pull/1)

Test command:

```
./wpt run safari html/semantics/forms/the-label-element/proxy-modifier-click-to-associated-element.tentative.html --headless --channel=stable
```

And this still [passes in Chrome](https://github.com/web-platform-tests/wpt/runs/1103364999) and [fails Firefox](https://github.com/web-platform-tests/wpt/runs/1103364079) as expected.

**Comment by burg** [comment]
@muan, I'm testing a fix for the duration issue. I don't have an ETA for the modifier key issue (beyond what already landed).

**Review by domenic — APPROVED** [review]

**Pull request merged**
