### PR TITLE
wpt-export-for-webkit-181330

### PR DESCRIPTION
**Pull request by youennf**
Add testing for redirect URLs containing credentials in CORS mode for images and no cors mode for fetch, image and frame

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22579)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/327262441)

**Comment by annevk** [comment]
It seems the lint check is faiilng, but also, aren't we already testing this somewhere in the /cors directory? It's somewhat surprising to me this would not be covered. Although I guess for "no-cors" we might indeed not cover this. (I haven't yet read all the context though, just a drive-by comment before I have to go for a bit.)

**Comment by youennf** [comment]
> It seems the lint check is faiilng, but also, aren't we already testing this somewhere in the /cors directory?

I saw tests for fetch cors mode and XHR.
I did not see any test for fetch no-cors mode, hence why I added one for cors and no-cors.
I did not see any test related to loading images but I haven't looked at the cors folder.

**Review by annevk — APPROVED** [review]
These match the current specification so I'm happy to land them and then we can change them if https://github.com/whatwg/fetch/pull/465 lands.

It might be good to wait with landing this until @mikewest has had a chance to take a look though given that he wants to change this.

(The only somewhat weird thing I noticed is that the fetch() calls are without credentials but for images you use "use-credentials". It shouldn't matter what that setting is though, but maybe if it did in WebKit you want to test more variants?)

**Review by annevk — CHANGES_REQUESTED** [review]
Actually, the lint issues do need to be fixed.

**Comment by foolip** [comment]
@youennf, I see the commit message for this one looks a bit different from https://github.com/w3c/web-platform-tests/pull/8986 and the other WebKit exports. Is there a format I can grep for, for tracking purposes?

**Comment by mikewest** [comment]
I think these tests all match what the spec says, so LGTM from that perspective.

That said, I expect that Chrome will fail them, and I'm not enthusiastic about not failing them. I apparently dropped the ball on the Fetch patch; I'll try to pick that up again in the near future to try to get other vendors on board.

**Comment by annevk** [comment]
The reason lint is complaining btw is that instead of setTimeout you should use test.step_timeout.

**Review by annevk — APPROVED** [review]

**Pull request merged**
