### PR TITLE
Order both actual and expected in selftests

### LINKED ISSUE #11406: Make fetch_tests_from_worker et al non-racy
See https://github.com/web-platform-tests/wpt/pull/11405

We could investigate making it non-racy to use more than one of these functions in a test.

Files with multiple `fetch_tests_*`:
```
$ grep -rc "fetch_tests_" . | grep -vE ":[01]$"
./tools/serve/serve.pyc:3
./tools/serve/serve.py:3
./tools/serve/__pycache__/serve.cpython-36.pyc:3
./streams/generate-test-wrappers.js:2
./resources/test/tests/functional/iframe-consolidate-errors.html:3
./resources/test/tests/functional/iframe-consolidate-tests.html:3
./resources/testharness.js:10
./docs/_writing-tests/testharness-api.md:9
./content-security-policy/inside-worker/dedicated-inheritance.html:7
./content-security-policy/inside-worker/dedicated-script.html:7
./content-security-policy/inside-worker/shared-inheritance.html:3
./content-security-policy/inside-worker/shared-script.html:3
./fetch/range/sw.https.window.js:2
./workers/name-property.html:4
./workers/opaque-origin.html:2
./service-workers/service-worker/client-navigate.https.html:5
```

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #11406.

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Oops, Travis is unhappy, some tests need updating?

**Comment by zcorpan** [comment]
I don't know why the tests are failing. @jugglinmike any idea?

**Comment by jugglinmike** [comment]
The expected sub-tests results are expressed in a JSON array, so their order is already stable. This change would allow folks authoring testharness.js test to be a little more sloppy in the way they authored the tests, but I don't think it will influence stability.

**Comment by jugglinmike** [comment]
@jgraham Can you help me understand how this patch promotes stability?

**Pull request merged**
