### PR TITLE
Add support for `mixin` in idlharness

### PR DESCRIPTION
**Pull request by romandev**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8727)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-12-18 16:54:03
Finished: 2017-12-18 16:59:33


<h2>Failing Jobs</h2>
<ul>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21937)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/318182387)

**Comment by romandev** [comment]
@annevk, @tobie PTAL
I made a urgent patch to fix the test error metioned in the #8700 issue. This is basically equivalent with NoInterfaceObject. After this patch, we can extend the test range (e.g. mixin members).

**Comment by annevk** [comment]
w3c-test:mirror

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
This fixes the issues @Hexcles found in #8700. The code looks reasonable, but I'm by no means an expert here.

I'm going to land this given that this seems like the most pragmatic way forward, over reverting a bunch of PRs. Post-commit reviews appreciated.

**Comment by Hexcles** [comment]
Thanks! I tested it locally and it seems to work on both Firefox and Chrome. (And I'm also not familiar with IDL. Reviews are much appreciated.)

**Pull request merged**
