### PR TITLE
nonce attribute: no longer tentative

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/pull/5300.

Supersedes #5423.

### CODE REVIEW

**Comment by annevk** [comment]
I'll add at least one test to ensure this nonce attribute also works generically and then I think I've done more than my share on this feature...

**Comment by annevk** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1053496 on the Chrome failures.

**Review by mikewest — APPROVED** [review]
These LGTM. Thank you for putting them together, and for filing the bug against Chromium. I really appreciate your effort.

**Comment by annevk** [comment]
@mikewest I'm going to assume these final changes are okay per your comments elsewhere, but happy to take more feedback. (Including after landing these.)

**Comment by ArthurSonzogni** [comment]
FYI: I updated Chrome to match with the new expectations.
https://chromium-review.googlesource.com/c/chromium/src/+/2075340

**Comment by annevk** [comment]
Thanks @ArthurSonzogni!

**Pull request merged**
