### PR TITLE
HTML: vertical switch

### PR DESCRIPTION
**Pull request by annevk**
For http://github.com/whatwg/html/pull/9546.

### CODE REVIEW

**Review by noamr — APPROVED** [review]
LGTM

**Comment by r12a** [comment]
I think this looks ok, if switches will be rotated like the text, which i assume is fair.  An interesting aside question will be which way to rotate them (left or right).  (In fact for Japanese & Chinese folks there is currently a difference in opinion about this for range controls.) cc @xfq

**Comment by annevk** [comment]
Our plan is for the logical left to be on top when rendered vertically.

**Comment by r12a** [comment]
Logical 'left' in LTR text.  I suppose there's also the question about whether the logical movement for RTL text is reversed. See https://github.com/w3c/alreq/issues/259, where i added a question about this.

**Comment by annevk** [comment]
For RTL the switch control is reversed, at least on Apple platforms.

**Pull request merged**
