### PR TITLE
Add 304 tests for CORS

### PR DESCRIPTION
**Pull request by mnot**
CORS doesn't specify what to do with a 304 response, but
HTTP specifies that its headers should be combined with
the stored response -- i.e., a 304 should be under the
same CORS policy as the original 200 (unless it changes it).

This is testing to make sure that this is the case, since
many servers (including intermediaries) do NOT add CORS
headers (and some can't -- e.g., intermediary caches).

Future tests might include things like updates to CORS in
those 304s (fancy!).

### CODE REVIEW

**Comment by mnot** [comment]
OK, updated to both expand and contract Access-Control-Expose-Headers with a 304. Chrome passes; Firefox does on a soft reload (i.e., not shift key), but interestingly not on a fresh load, and Safari fails header expand/contract (while still passing the base case).

**Comment by mnot** [comment]
bleh. git crashed, submodules in weird state; will close this and start a new one.

**Comment by jgraham** [comment]
The problem with throwing it away and starting a new one is that you also threw away @Velmont's review work.

**Comment by Velmont** [comment]
mnot took a look manually after I pointed him to it.  I was going to say the same, -- but then saw the submodule-mess, knowing I myself haven't really tried switching between old/new branches I thought that might indeed be a bit messy.  Especially if you're not strong in Git.

But I wholly agree, much better to continue a review, even if most things are rewritten.  Critic has a quite nice diff-viewer.  Although in this particular instance doing a new one might be the simplest thing.

**Comment by mnot** [comment]
Yeah, if I'd thought about it a bit more I'd have just pulled the repo again after updating git (to avoid the crash); sorry.

**Comment by mnot** [comment]
Oh, and I *think* I've addressed the feedback -- happy to continue that conversation however you think best.

**Pull request closed without merging**
