### PR TITLE
Merge numbered CSS directories that have re-appeared

### PR DESCRIPTION
**Pull request by foolip**
These came via PRs started before the big merged and merged after:
https://github.com/w3c/web-platform-tests/pull/6969
https://github.com/w3c/web-platform-tests/pull/7529
https://github.com/w3c/web-platform-tests/pull/8133

### CODE REVIEW

**Comment by foolip** [comment]
This is part of https://github.com/w3c/web-platform-tests/issues/7503, but doesn't close it because of documentation still in need of updating.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20628)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/302458501)

**Review by jdm — APPROVED** [review]

**Comment by foolip** [comment]
Thanks @jdm, your speedy reviews of many PRs are much appreciated!

**Comment by foolip** [comment]
As a sanity check I made sure that none of the touched files contain `..`, and they don't. Hopefully no broken URLs here, but who knows...

**Pull request merged**
