### PR TITLE
Added handling for event records

### PR DESCRIPTION
**Pull request by halindrome**
An event record in the wiki will generate corresponding
JSON in the test now.  References #5573 

@joanmarie please review.

### CODE REVIEW

**Review by joanmarie — APPROVED** [review]
Fixes the issue. Thanks!

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241330151)

# Firefox (nightly) #
Testing web-platform-tests at revision 15d4ad812a35d80f90507d5c1299ebf81dacb4cb
Using browser at version BuildID 20170609100251; SourceStamp f4262773c4331d4ae139be536ce278ea9aad3436
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241330153)

# Sauce (safari) #
Testing web-platform-tests at revision 15d4ad812a35d80f90507d5c1299ebf81dacb4cb
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241330164)

# Chrome (unstable) #
Testing web-platform-tests at revision 15d4ad812a35d80f90507d5c1299ebf81dacb4cb
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241330165)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 15d4ad812a35d80f90507d5c1299ebf81dacb4cb
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Pull request merged**
