### PR TITLE
Capture from HTMLMediaElement: move LayoutTests to external/wpt (reland)

### PR DESCRIPTION
**Pull request by jeffcarp**
This CL moves the three standard functionality LayoutTests for
mediacapture-fromelement to the external/wpt folder, adapting
them accordingly and adding the necessary webmfiles.

Also removes the HTMLMediaElementCapture-*.html expectations.

Note: @jeffcarp created this PR as a reland of #6546, which was unstable and had to be closed upstream and reverted in Chromium. The plan is to land this upstream first after resolving the stability issues on Safari, after which it'll be imported into Chromium.

Bug: 619625
Change-Id: If06df91ae918b5f0d3eacc597c88709a83227a82
Reviewed-on: https://chromium-review.googlesource.com/566151
Commit-Queue: Miguel Casas <mcasas@chromium.org>
Reviewed-by: Emircan Uysaler <emircan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#486677}

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253747085)

# Firefox (nightly) #
Testing web-platform-tests at revision fccfb180ae96d882fb12b7b2669d92f06a18a03d
Using browser at version BuildID 20170714100217; SourceStamp 67cd1ee26f2661fa5efe3d952485ab3c89af4271
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/capture.html">/mediacapture-fromelement/capture.html</a></summary>


|    Subtest    | Results |                 Messages                |
|---------------|---------|-----------------------------------------|
|               | OK      |                                         |
| `video-only`  | PASS    |                                         |
| `Untitled`    | FAIL    | `video.captureStream is not a function` |
| `audio-only`  | PASS    |                                         |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function` |
| `video+audio` | PASS    |                                         |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/creation.html">/mediacapture-fromelement/creation.html</a></summary>


|    Subtest    | Results |                 Messages                |
|---------------|---------|-----------------------------------------|
|               | OK      |                                         |
| `video-only`  | PASS    |                                         |
| `Untitled`    | FAIL    | `video.captureStream is not a function` |
| `audio-only`  | PASS    |                                         |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function` |
| `video+audio` | PASS    |                                         |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/ended.html">/mediacapture-fromelement/ended.html</a></summary>


|    Subtest    | Results |                 Messages                |
|---------------|---------|-----------------------------------------|
|               | OK      |                                         |
| `video-only`  | PASS    |                                         |
| `Untitled`    | FAIL    | `video.captureStream is not a function` |
| `audio-only`  | PASS    |                                         |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function` |
| `video+audio` | PASS    |                                         |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253747086)

# Sauce (safari) #
Testing web-platform-tests at revision fccfb180ae96d882fb12b7b2669d92f06a18a03d
Using browser at version 10.0
Starting 10 test iterations
## Unstable results ##


|                    Test                   |    Subtest    |            Results            |                                                  Messages                                                 |
|-------------------------------------------|---------------|-------------------------------|-----------------------------------------------------------------------------------------------------------|
| `/mediacapture-fromelement/creation.html` |               | **OK: 9/10, TIMEOUT: 1/10**   |                                                                                                           |
| `/mediacapture-fromelement/creation.html` | `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/creation.html` | `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `/mediacapture-fromelement/creation.html` | `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/creation.html` | `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `/mediacapture-fromelement/creation.html` | `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/creation.html` | `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `/mediacapture-fromelement/ended.html`    |               | **OK: 9/10, TIMEOUT: 1/10**   |                                                                                                           |
| `/mediacapture-fromelement/ended.html`    | `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/ended.html`    | `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `/mediacapture-fromelement/ended.html`    | `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/ended.html`    | `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `/mediacapture-fromelement/ended.html`    | `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `/mediacapture-fromelement/ended.html`    | `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |

## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/capture.html">/mediacapture-fromelement/capture.html</a></summary>


|    Subtest    | Results |                                                  Messages                                                 |
|---------------|---------|-----------------------------------------------------------------------------------------------------------|
|               | OK      |                                                                                                           |
| `video-only`  | PASS    |                                                                                                           |
| `Untitled`    | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `audio-only`  | PASS    |                                                                                                           |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `video+audio` | PASS    |                                                                                                           |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/creation.html">/mediacapture-fromelement/creation.html</a></summary>


|    Subtest    |            Results            |                                                  Messages                                                 |
|---------------|-------------------------------|-----------------------------------------------------------------------------------------------------------|
|               | **OK: 9/10, TIMEOUT: 1/10**   |                                                                                                           |
| `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6559/mediacapture-fromelement/ended.html">/mediacapture-fromelement/ended.html</a></summary>


|    Subtest    |            Results            |                                                  Messages                                                 |
|---------------|-------------------------------|-----------------------------------------------------------------------------------------------------------|
|               | **OK: 9/10, TIMEOUT: 1/10**   |                                                                                                           |
| `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                                                                                           |
| `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253747092)

# Chrome (unstable) #
Testing web-platform-tests at revision fccfb180ae96d882fb12b7b2669d92f06a18a03d

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253747093)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision fccfb180ae96d882fb12b7b2669d92f06a18a03d

**Comment by yellowdoge** [comment]
FTR: Firefox implements the API being tested here as `mozCaptureStream()` (iso just `captureStream()`; Safari-WebKit doesn't implement it all, so I guess timing out is a correct behaviour (I could polish the tests to detect-api-and-fail) (Nuance: Safari Webkit implements `<canvas>.captureStream()` but not the `<video/audio>.captureStream()` which is exercised by this tests).

**Comment by jeffcarp** [comment]
I fixed the flakiness in Safari by adding `assert_true('captureStream' in video);` in 8f2dc35c9d3e73a660c8b5c508f2787c28285979 (as you suggested above).

Now Travis is passing but the merge button is still red due to required review. Since this was [reviewed in Chromium](https://chromium-review.googlesource.com/c/566151/) (minus the line I added above), I'm going to go ahead and merge.

We can also abandon the [Chromium reland CL](https://chromium-review.googlesource.com/c/571965/) I made for this since once this change lands in WPT it'll get auto-imported into Chromium.

**Pull request merged**
