### PR TITLE
Add @drott

### PR DESCRIPTION
**Pull request by svgeesus**

### CODE REVIEW

**Comment by svgeesus** [comment]
See #9373

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-02-14 22:09:58
Finished: 2018-02-14 22:16:09


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24363)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/341648037)

**Comment by svgeesus** [comment]
@gsnedders please push the button.

**Comment by gsnedders** [comment]
Can we ensure @drott is okay with this first?

**Comment by drott** [comment]
Yes, please, as requested in https://github.com/w3c/web-platform-tests/pull/9373#discussion_r167161579

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
