### PR TITLE
Editorial: cleanup some area opener/noopener tests

### PR DESCRIPTION
**Pull request by annevk**
As pointed out in https://github.com/web-platform-tests/wpt/pull/15188#issuecomment-495917185 it was a bit confusing (and wrong).

### CODE REVIEW

**Comment by annevk** [comment]
cc @ericlaw1979

**Comment by annevk** [comment]
@foolip https://github.com/web-platform-tests/wpt/pull/15188#issuecomment-460192498 onward still applies, so if this looks okay this can be landed. (The stability issue in Chrome remains if I comment out all `area` tests, so that isn't it.)

**Comment by foolip** [comment]
@annevk seems like preexisting flakiness not caused by your changes, right? I'll review and admin merge.

@KyleJu @lukebjerring can you use this as an example of flakiness to annotate in the ongoing metadata project? It's a good one because there's a mix of failures and passes in the same test.

**Review by foolip — APPROVED** [review]

**Comment by annevk** [comment]
Yeah, the test was already flaky in Chrome, this only serves to remove some confusing aspects of the tests that were not relevant. Thanks for merging!

**Pull request merged**
