### PR TITLE
Consolidate all IDL files into interfaces/

### PR DESCRIPTION
**Pull request by foolip**
Closes https://github.com/w3c/web-platform-tests/issues/9026.

### CODE REVIEW

**Comment by foolip** [comment]
@lukebjerring, as an aside, this another typical example where highlighting new test failures would be super helpful. If I've made a single typo here, some test might be broken entirely, and probably nobody would notice for a few weeks or months.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25417)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350153259)

**Review by bsittler — COMMENTED** [review]
cookie-store parts look good to me

**Comment by foolip** [comment]
@jgraham can you rubber stamp? Or carefully review if you like :)

**Review by bsittler — APPROVED** [review]
Thanks, @foolip !

**Review by bsittler — APPROVED** [review]

**Comment by foolip** [comment]
@lukebjerring, can you rebase all the branches that have merge conflicts now? Should see some nice new diffs.

**Comment by lukebjerring** [comment]
Done.

**Pull request merged**
