### PR TITLE
Ensure testharnessreport.js is loaded as utf8

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9393)

### CODE REVIEW

**Comment by gsnedders** [comment]
Why do we need this when we already have https://github.com/w3c/web-platform-tests/blob/master/resources/testharnessreport.js.headers?

**Comment by jgraham** [comment]
Because a `StaticHandler` doesn't look at the `.headers` file, only a a `FileHandler` does. Maybe things should change so that .headers are applied to the URL rather than the fs path, but that is a big change and this is a one-line change.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-02-05 14:16:36
Finished: 2018-02-05 14:30:57





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23890)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/337555659)

**Comment by gsnedders** [comment]
@jgraham Can you add a comment to that affect so I don't end up confused several years down the line?

**Comment by gsnedders** [comment]
@jgraham do we actually want to mark them as immutable? they might change, they aren't actually immutable.

**Comment by jgraham** [comment]
It would certainly be fine on implementations where we have a separate profile per run. AIUI it only means we don't revalidate on reload so maybe it's not worthwhile, and actually it turns out to not work in firefox except over https so it's probably not worthwhile.

**Comment by gsnedders** [comment]
Can you reword the commit message for the second commit on the branch, given it's now totally wrong? :)

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
