### PR TITLE
DOM: test composed/composedPath via IDL

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
Hmm, I didn't mean to remove review requests.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25785)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/352297135)

**Comment by annevk** [comment]
I suspect the reason this breaks the build is because Firefox doesn't implement these features.

**Review by TakayoshiKochi — APPROVED** [review]
LGTM

**Pull request merged**
