### PR TITLE
Add tests for marginwidth/leftmargin et al attributes on body/iframe

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/html/pull/2489

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5276)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217136020)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1d6f9b4a0091400f30ff6f7df979db169ff7ccf5
Using browser at version BuildID 20170331102157; SourceStamp 8df9fabf2587b7020889755acb9e75b664fe13cf
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5276/html/rendering/non-replaced-elements/the-page/iframe-body-margin-attributes.html">/html/rendering/non-replaced-elements/the-page/iframe-body-margin-attributes.html</a></summary>


|                    Subtest                     | Results | Messages |
|------------------------------------------------|---------|----------|
|                                                | OK      |          |
| `body marginwidth vs body leftmargin`          | PASS    |          |
| `iframe marginwidth vs child body leftmargin`  | PASS    |          |
| `iframe marginwidth vs child body marginwidth` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5276/html/rendering/non-replaced-elements/the-page/iframe-marginwidth-marginheight.html">/html/rendering/non-replaced-elements/the-page/iframe-marginwidth-marginheight.html</a></summary>


|                Subtest                | Results | Messages |
|---------------------------------------|---------|----------|
|                                       | OK      |          |
| `iframe marginwidth and marginheight` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217136021)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1d6f9b4a0091400f30ff6f7df979db169ff7ccf5
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5276/html/rendering/non-replaced-elements/the-page/iframe-body-margin-attributes.html">/html/rendering/non-replaced-elements/the-page/iframe-body-margin-attributes.html</a></summary>


|                    Subtest                     | Results |                          Messages                         |
|------------------------------------------------|---------|-----------------------------------------------------------|
|                                                | OK      |                                                           |
| `body marginwidth vs body leftmargin`          | FAIL    | `assert_equals: marginTop expected "20px" but got "10px"` |
| `iframe marginwidth vs child body leftmargin`  | FAIL    | `assert_equals: marginTop expected "20px" but got "10px"` |
| `iframe marginwidth vs child body marginwidth` | FAIL    | `assert_equals: marginTop expected "20px" but got "10px"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5276/html/rendering/non-replaced-elements/the-page/iframe-marginwidth-marginheight.html">/html/rendering/non-replaced-elements/the-page/iframe-marginwidth-marginheight.html</a></summary>


|                Subtest                | Results |                                                 Messages                                                |
|---------------------------------------|---------|---------------------------------------------------------------------------------------------------------|
|                                       | OK      |                                                                                                         |
| `iframe marginwidth and marginheight` | FAIL    | `Uncaught Error: assert_equals: Number of attributes on the child document's body expected 0 but got 2` |

</details>
</details>

**Comment by zcorpan** [comment]
w3c-test:mirror

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5276/)

**Comment by zcorpan** [comment]
Edge 14 passes the tests (tested using browserstack).

**Pull request merged**
