### PR TITLE
[css-ruby] Adding japanese .woff font resource into block-ruby-001 test and reference

### PR DESCRIPTION
**Pull request by TalbotG**
This is a follow-up of [pull request 29806](https://github.com/web-platform-tests/wpt/pull/29806).

On my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-final.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-ref-final.html

### CODE REVIEW

**Comment by TalbotG** [comment]
At my website, the correspondent files to commit [9853a0d](https://github.com/web-platform-tests/wpt/pull/33271/commits/9853a0d34db6302c92b3afda4a3bfbcca67df806) are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-final2.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-ref-final2.html

**Comment by himorin** [comment]
[Looking at results](https://wpt.fyi/results/css/css-ruby/block-ruby-001.html?diff=&filter=ADC&run_id=5696235930386432&run_id=5738059550162944) and diff, I confirm lines for woff inclusion are ok and correctly working.

**Review by himorin — APPROVED** [review]

**Comment by TalbotG** [comment]
Thank you, @himorin .
At the bottom of the results and diff page you mentioned, it is written
https://crbug.com/27659
but I think it should be
https://crbug.com/1079135
Issue 1079135: Support |display: block ruby| behavior

**Comment by himorin** [comment]
> Thank you, @himorin . At the bottom of the results and diff page you mentioned, 

afaiu, that link should come from
https://github.com/web-platform-tests/wpt-metadata/blob/615cb9982b7a19a491515ca5d9e5df0210db13d6/css/css-ruby/META.yml#L21

**Pull request merged**
