### PR TITLE
Test same-URL navigation

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/html/pull/2114 for the change to the HTML
Standard.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Missing some `t.step_func()`s

**Comment by annevk** [comment]
Ah right.

**Comment by annevk** [comment]
I'll fix that, though as I noted in the parent issue I'm not even sure if this test is going to help us.

**Comment by domenic** [comment]
This passes in Edge at least, and looks super-reasonable. I'll file some browser bugs.

**Comment by domenic** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=676050 and https://bugzilla.mozilla.org/show_bug.cgi?id=1324861

**Pull request merged**
