### PR TITLE
Test 'line-height: 1' is consistent with system fallback

### PR DESCRIPTION
**Pull request by kojiishi**
@fantasai @litherum @frivoal @astearns @upsuper @dbaron 

I think we can test height consistency with test like this, can't we?

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5773/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228478333)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 7ff321b9751b92098a3fabdb134ade509ee2aa8a
Using browser at version BuildID 20170502100421; SourceStamp 48c0fd9c9ec5d68061ea7b59358874ae8da72572
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5773/css/CSS2/linebox/line-height-fallback-001.html">/css/CSS2/linebox/line-height-fallback-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228478339)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 7ff321b9751b92098a3fabdb134ade509ee2aa8a
Using browser at version 60.0.3080.5 dev
Starting 10 test iterations

**Comment by dbaron** [comment]
This doesn't actually test the interesting case from w3c/csswg-drafts#1254 that's relevant to w3c/csswg-drafts#938 since there is never more than one element on a line with different fonts.  There's also no guarantee that it's relevant at all, since you have no idea what the font metrics of the fonts used for the Arabic, Devanagari, Myanmar, and Telugu text are; the midpoint between the relevant ascent and descent might be the same as the midpoint of Ahem.

**Comment by kojiishi** [comment]
Closing as we've got "Myles" family now, and tests using system fonts aren't interested in as per the comment.

**Pull request closed without merging**
