### PR TITLE
URL: improve coverage of conditions in the standard

### PR DESCRIPTION
**Pull request by annevk**
@domenic I found:

1. One bug in whatwg-url
2. One check that should be removed from the standard
3. We don’t test empty input to the IPv4 parser. I think that’s fine as it’s currently not possible, but who knows what we do going forward. Alternatively, we add an assert to the standard or some such.
4. There’s some stuff around origins that’s not tested. Blob URLs need to be sorted still and file URLs we don’t have agreement on thus far, though arguably whatever they return should serialize to null.

### CODE REVIEW

**Comment by annevk** [comment]
I get 98.5% with this by the way.

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 548e68ac8e79aaf159ec25d04d210bdcec05d640
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations

**Comment by annevk** [comment]
When committing this we should probably not close #3018 quite yet. I had forgotten to study `URL-impl.js.html` in more detail. I'd rather not block landing this on doing that work though, especially as some of it such as javascript URLs requires quite a bit of work.

**Comment by domenic** [comment]
> One bug in whatwg-url

What's the bug?

**Comment by annevk** [comment]
The stripping of U+FFFD in paths and fragments.

**Pull request merged**
