### PR TITLE
[geometry] Also test new DOMMatrix("") in a worker

### PR DESCRIPTION
**Pull request by zcorpan**
Followup for https://github.com/w3c/web-platform-tests/pull/5769

Relevant spec change: https://github.com/w3c/fxtf-drafts/pull/141

@fserb r?

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231299880)

# Firefox (nightly) #
Testing web-platform-tests at revision e4f79f0ee6d01c8819939f4889396adccad7c1bf
Using browser at version BuildID 20170511133312; SourceStamp 838652a84b76c273e084d0705f3f4f3be89520a8
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5894/css/geometry-1/DOMMatrix-css-string.worker.html">/css/geometry-1/DOMMatrix-css-string.worker.html</a></summary>


|                               Subtest                                | Results |                                Messages                               |
|----------------------------------------------------------------------|---------|-----------------------------------------------------------------------|
|                                                                      | OK      |                                                                       |
| `DOMMatrix constructor with string argument in worker`               | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrix constructor with empty string argument in worker`         | FAIL    | `assert_true: DOMMatrix should exist expected true got false`         |
| `DOMMatrixReadOnly constructor with string argument in worker`       | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false` |
| `DOMMatrixReadOnly constructor with empty string argument in worker` | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false` |
| `DOMMatrix setMatrixValue in worker`                                 | FAIL    | `DOMMatrix is not defined`                                            |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231299886)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233968567)

# Sauce (safari) #
Testing web-platform-tests at revision 1ee67216c91aa72191d24a56bd89f638311325d5
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5894/css/geometry-1/DOMMatrix-css-string.worker.html">/css/geometry-1/DOMMatrix-css-string.worker.html</a></summary>


|                               Subtest                                | Results |                                                Messages                                               |
|----------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------|
|                                                                      | OK      |                                                                                                       |
| `DOMMatrix constructor with string argument in worker`               | FAIL    | `assert_true: DOMMatrix should exist expected true got false`                                         |
| `DOMMatrix constructor with empty string argument in worker`         | FAIL    | `assert_true: DOMMatrix should exist expected true got false`                                         |
| `DOMMatrix stringifier in worker (2d identity)`                      | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                                    |
| `DOMMatrix stringifier in worker (3d identity)`                      | FAIL    | `undefined is not an object (evaluating 'self[constr].fromMatrix')`                                   |
| `DOMMatrix stringifier in worker (non-finite values)`                | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]([1, 0, 0, NaN, Infinity, -Infinity])')` |
| `DOMMatrixReadOnly constructor with string argument in worker`       | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false`                                 |
| `DOMMatrixReadOnly constructor with empty string argument in worker` | FAIL    | `assert_true: DOMMatrixReadOnly should exist expected true got false`                                 |
| `DOMMatrixReadOnly stringifier in worker (2d identity)`              | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                                    |
| `DOMMatrixReadOnly stringifier in worker (3d identity)`              | FAIL    | `undefined is not an object (evaluating 'self[constr].fromMatrix')`                                   |
| `DOMMatrixReadOnly stringifier in worker (non-finite values)`        | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]([1, 0, 0, NaN, Infinity, -Infinity])')` |
| `DOMMatrix setMatrixValue in worker`                                 | FAIL    | `Can't find variable: DOMMatrix`                                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233968574)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 1ee67216c91aa72191d24a56bd89f638311325d5

**Review by peterjoel — APPROVED** [review]

**Pull request merged**
