### PR TITLE
Rename EdgeChromium to Edge

### PR DESCRIPTION
**Pull request by mwjacksonmsft**
Support for the Microsoft Edge Legacy desktop was removed from WPT tests via https://github.com/web-platform-tests/wpt/pull/44233 in Feb 2024. Instead of maintaining edgechromium, we can now simplify usage to just 'edge'. 

This change removes all usages of the term 'edgechromium' in class names, and from the product list. The one remaining reference is to output an error to notify anyone who attempts to use edgechromium that they should now use edge.

```
C:\wpt>python3 wpt run edgechromium
Traceback (most recent call last):
  File "C:\wpt\wpt", line 10, in <module>
    wpt.main()
  File "C:\wpt\tools\wpt\wpt.py", line 233, in main
    rv = script(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wpt\tools\wpt\run.py", line 986, in run
    setup_cls, wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wpt\tools\wpt\run.py", line 913, in setup_wptrunner
    raise WptrunError("edgechromium has been renamed to edge.")
tools.wpt.run.WptrunError: edgechromium has been renamed to edge.
```

### CODE REVIEW

**Comment by DanielRyanSmith** [comment]
We'll need to make sure everything is handled correctly when labeling test results during the ingestion phase for wpt.fyi. [Specifically in instances like this one](https://github.com/web-platform-tests/wpt.fyi/blob/main/results-processor/wptreport.py#L555-L557). Otherwise, this change is probably fine, but we'll need to land and deploy changes in wpt.fyi before this change lands.

**Comment by mwjacksonmsft** [comment]
@DanielRyanSmith, Thanks for highlighting that, I'll take a look, and see if I can get a PR posted in the next day or so.

**Comment by mwjacksonmsft** [comment]
@DanielRyanSmith, I posted this for review. https://github.com/web-platform-tests/wpt.fyi/pull/3808 Would love to get your feedback on it.

**Review by DanielRyanSmith — APPROVED** [review]
The changes required to wpt.fyi have been deployed, and this should be safe to land now. 🙂

**Pull request merged**
