### PR TITLE
Add tests for `script.callFunction` for serialization of primitive values

### PR DESCRIPTION
**Pull request by lutien**
Add tests for `script.callFunction` for serialization of primitive values

### CODE REVIEW

**Comment by sadym-chromium** [comment]
`deserialization`?

**Review by sadym-chromium — APPROVED** [review]
LGTM, but it seems to be a test for `deserialization`

**Comment by juliandescottes** [comment]
It actually asserts both. We deserialize the argument to call the function, and we serialize it back to return it.

**Review by juliandescottes — APPROVED** [review]
As commented this actually asserts both serialization and deserialization. 

We could make the test only about serialization. Basically just have the same test as for evaluate, except that we would use `function_declaration=f"() => {expression}"` instead of `expression=expression`.

Then we could have a dedicated test for various values of `arguments` in either a deserialization.py or arguments.py file.

But we could do that in a followup PR.

**Comment by juliandescottes** [comment]
@sadym-chromium considering my comments above, do you think we should proceed with the current test even if it asserts both serialization and deserialization, or should we specialize it?

**Comment by sadym-chromium** [comment]
I'm fine with testing serialization + deserialization together. What I meant is that in fact we tested pure serialization in `script.evaluate`, and this test I'd call `deserialization`. But I don't insist on it.

**Comment by whimboo** [comment]
Couldn't we use Python's string formatting to construct the actual expression and separate the serialization and deserialization into different tests? Something like:

```
[..]
        ("42n", {"type": "bigint", "value": "42"}),
    ],
)async def test_primitive_values(bidi_session, top_context, remote_value, argument):
    result = await bidi_session.script.call_function(

       function_declaration=f"() => {remote_value}",
```

**Comment by lutien** [comment]
Alright, I guess to keep it consistent with `script.evaluate` tests, I'll switch to the approach suggested by Julian and Henrik to make this test only about serialization

**Comment by lutien** [comment]
@juliandescottes, @sadym-chromium, I've updated the PR to test only the serialization part. 
Maybe you could have another quick look?
Thank you in advance!

**Comment by whimboo** [comment]
For me this looks great. One thing to note would be the file name. Maybe we can use `result.py` so that we have `exception_details.py` for the error counterpart as well later? That would be in alignment with the other PR 34733 from @juliandescottes.

**Review by sadym-chromium — APPROVED** [review]

**Review by juliandescottes — APPROVED** [review]

**Comment by juliandescottes** [comment]
> Maybe we can use result.py so that we have exception_details.py for the error counterpart as well later

Ah, good point! `result.py` sounds like a good name, but we will have to rename `evaluate/serialization.py` for consistency at the same. Probably best to have in another PR?

**Comment by whimboo** [comment]
We could do that right now. It requires only two git commands and should be done pretty fast. Otherwise we might forget about it.

**Review by whimboo — APPROVED** [review]

**Pull request merged**
