### PR TITLE
CORS: change userinfo tests due to URL parser changes

### PR DESCRIPTION
**Pull request by annevk**
In particular empty string password is now the same as not having a
password.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5121/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210473484)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d8c8512ecca9ecff0795698519ab7b88c121a706
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5121/cors/redirect-userinfo.htm">/cors/redirect-userinfo.htm</a></summary>


|                               Subtest                                | Results |                   Messages                   |
|----------------------------------------------------------------------|---------|----------------------------------------------|
|                                                                      | OK      |                                              |
| `Disallow redirect with userinfo (user:pass@)`                       | PASS    |                                              |
| `Disallow redirect with userinfo (user:@)`                           | PASS    |                                              |
| `Disallow redirect with userinfo (user@)`                            | PASS    |                                              |
| `Allow redirect without userinfo (:@ is trimmed during URL parsing)` | FAIL    | `assert_unreached: Reached unreachable code` |
| `Disallow redirect with userinfo (:pass@)`                           | PASS    |                                              |
| `Allow redirect without userinfo (@ is trimmed during URL parsing)`  | PASS    |                                              |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210473485)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d8c8512ecca9ecff0795698519ab7b88c121a706
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5121/cors/redirect-userinfo.htm">/cors/redirect-userinfo.htm</a></summary>


|                               Subtest                                | Results | Messages |
|----------------------------------------------------------------------|---------|----------|
|                                                                      | OK      |          |
| `Disallow redirect with userinfo (user:pass@)`                       | PASS    |          |
| `Disallow redirect with userinfo (user:@)`                           | PASS    |          |
| `Disallow redirect with userinfo (user@)`                            | PASS    |          |
| `Allow redirect without userinfo (:@ is trimmed during URL parsing)` | PASS    |          |
| `Disallow redirect with userinfo (:pass@)`                           | PASS    |          |
| `Allow redirect without userinfo (@ is trimmed during URL parsing)`  | PASS    |          |

</details>
</details>

**Comment by annevk** [comment]
This makes Chrome pass all these tests. Firefox ends up failing one, but will pass that once it fixes its URL parser. WebKit: https://bugs.webkit.org/show_bug.cgi?id=169540.

**Pull request merged**
