### PR TITLE
Test default style for <dialog> without small screen breakpoint

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/whatwg/html/pull/2459

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214213210)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d0e9a8245e0802c37e62bc063c09232e3d3872a0
Using browser at version BuildID 20170322110306; SourceStamp 201231223cd4354a450c3e5d80959f35b8e4cf0c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5209/html/rendering/non-replaced-elements/flow-content-0/dialog.html">/html/rendering/non-replaced-elements/flow-content-0/dialog.html</a></summary>


|                Subtest                 | Results |                                 Messages                                 |
|----------------------------------------|---------|--------------------------------------------------------------------------|
|                                        | OK      |                                                                          |
| `Closed dialog in width: 540px iframe` | FAIL    | `assert_equals: width expected "fit-content" but got "-moz-fit-content"` |
| `Open dialog in width: 540px iframe`   | FAIL    | `assert_equals: right expected "0px" but got "251px"`                    |
| `Modal dialog in width: 540px iframe`  | FAIL    | `assert_equals: display expected "block" but got "none"`                 |
| `Closed dialog in width: 538px iframe` | FAIL    | `assert_equals: width expected "fit-content" but got "-moz-fit-content"` |
| `Open dialog in width: 538px iframe`   | FAIL    | `assert_equals: right expected "0px" but got "250px"`                    |
| `Modal dialog in width: 538px iframe`  | FAIL    | `assert_equals: display expected "block" but got "none"`                 |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214213211)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d0e9a8245e0802c37e62bc063c09232e3d3872a0
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5209/html/rendering/non-replaced-elements/flow-content-0/dialog.html">/html/rendering/non-replaced-elements/flow-content-0/dialog.html</a></summary>


|                Subtest                 | Results | Messages |
|----------------------------------------|---------|----------|
|                                        | OK      |          |
| `Closed dialog in width: 540px iframe` | PASS    |          |
| `Open dialog in width: 540px iframe`   | PASS    |          |
| `Modal dialog in width: 540px iframe`  | PASS    |          |
| `Closed dialog in width: 538px iframe` | PASS    |          |
| `Open dialog in width: 538px iframe`   | PASS    |          |
| `Modal dialog in width: 538px iframe`  | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5209/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214218052)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 3a94d7109d1161b9eb3cba04210ba4dc0b85f6b3
Using browser at version BuildID 20170322110306; SourceStamp 201231223cd4354a450c3e5d80959f35b8e4cf0c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5209/html/rendering/non-replaced-elements/flow-content-0/dialog.html">/html/rendering/non-replaced-elements/flow-content-0/dialog.html</a></summary>


|                Subtest                 | Results |                                 Messages                                 |
|----------------------------------------|---------|--------------------------------------------------------------------------|
|                                        | OK      |                                                                          |
| `Closed dialog in width: 540px iframe` | FAIL    | `assert_equals: width expected "fit-content" but got "-moz-fit-content"` |
| `Open dialog in width: 540px iframe`   | FAIL    | `assert_equals: right expected "0px" but got "251px"`                    |
| `Modal dialog in width: 540px iframe`  | FAIL    | `assert_equals: display expected "block" but got "none"`                 |
| `Closed dialog in width: 538px iframe` | FAIL    | `assert_equals: width expected "fit-content" but got "-moz-fit-content"` |
| `Open dialog in width: 538px iframe`   | FAIL    | `assert_equals: right expected "0px" but got "250px"`                    |
| `Modal dialog in width: 538px iframe`  | FAIL    | `assert_equals: display expected "block" but got "none"`                 |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/214218053)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 3a94d7109d1161b9eb3cba04210ba4dc0b85f6b3
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5209/html/rendering/non-replaced-elements/flow-content-0/dialog.html">/html/rendering/non-replaced-elements/flow-content-0/dialog.html</a></summary>


|                Subtest                 | Results | Messages |
|----------------------------------------|---------|----------|
|                                        | OK      |          |
| `Closed dialog in width: 540px iframe` | PASS    |          |
| `Open dialog in width: 540px iframe`   | PASS    |          |
| `Modal dialog in width: 540px iframe`  | PASS    |          |
| `Closed dialog in width: 538px iframe` | PASS    |          |
| `Open dialog in width: 538px iframe`   | PASS    |          |
| `Modal dialog in width: 538px iframe`  | PASS    |          |

</details>
</details>

**Review by domenic — APPROVED** [review]
I think the test should mention somewhere why these two numbers are chosen (i.e. to test that a previous requirement is no longer enforced). A simple HTML comment or `<link rel="help">` linking to https://github.com/whatwg/html/pull/2459 would suffice.

Otherwise LGTM.

**Pull request merged**
