### PR TITLE
Update payment-request IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25211)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/348440530)

**Review by foolip — CHANGES_REQUESTED** [review]
Indentation

**Comment by lukebjerring** [comment]
Whitespace handled - There's actually a couple of inconsistencies in the source indentation(s), but I don't want to generalize the stripping algorithm; better to tweak the source.

**Comment by foolip** [comment]
Can you see if that is fixed by stripping leading whitespace for each individual IDL fragment before concatenating? If people are indenting to match the nesting in the source one would expect such inconsistencies, and that they'd not want to fix them either.

**Comment by lukebjerring** [comment]
Changed to per-snippet in https://github.com/GoogleChromeLabs/webidl-diff/commit/71954d82cf13f1d39ef389d012a4cf48a4609cfb  which resolves the problem.

**Review by foolip — APPROVED** [review]

**Pull request merged**
