### PR TITLE
Add interfaces/portals.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/7583df5/ed/idl/portals.idl
Build: https://travis-ci.org/w3c/webref/builds/729569825

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Sent an idlharness test at https://github.com/web-platform-tests/wpt/pull/25760, but I suspect portals isn't exposed via Chrome's `--enable-experimental-web-platform-features` yet (cc @jeremyroman to confirm)

**Comment by jeremyroman** [comment]
That's correct; it's only exposed in Chrome if the Portals feature is enabled.

**Review by stephenmcgruer — CHANGES_REQUESTED** [review]
[Blocking submission]

Ok. So its still reasonable to merge the test then (at the very least Chromium will pick up the import and you'll have a new idlharness test in Chromium which is hopefully useful), or we can just leave it if it seems like a long time before portals moves to a flag that would actually run on wpt.fyi. Either works for me :)

**Comment by jeremyroman** [comment]
It will be some time before this flag is on by default in Chrome. I'm not sure what WPT's preferred policy for idlharness tests in such cases is; it seems like this would not be difficult to land either now or later. (For our behavior tests, on the other hand, we naturally land them so that they exist somewhere.)

**Comment by foolip** [comment]
Added as part of https://github.com/web-platform-tests/wpt/pull/28474, but no test added yet.

**Pull request closed without merging**
