### PR TITLE
Get rid of /common/vendor-prefix.js

### PR DESCRIPTION
**Pull request by foolip**
Tests should follow what the specs say, and unless the specs define
the prefixed APIs [1] the right this is to assume the per-spec names
and to add historical.html tests asserting the absense of prefixed
APIs that have existed somewhere.

Based on web-confluence.appspot.com, navigator.vibrate was never
prefixed, but mozSrcObject is in Firefox. A test is added for
mozSrcObject, and the others APIs are already covered by existing
tests, or one of these:
https://github.com/w3c/web-platform-tests/pull/7507
https://github.com/w3c/web-platform-tests/pull/7508

[1] https://dom.spec.whatwg.org/#dom-element-webkitmatchesselector
    https://url.spec.whatwg.org/#url-class
    and others

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18903)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/280442657)

**Comment by foolip** [comment]
Many reviewers, no review :) @JKereliuk, can you rubber stamp?

**Comment by JKereliuk** [comment]
+r LGTM

**Comment by foolip** [comment]
Thanks @JKereliuk! Note that for GitHub to be impressed one has to go to the "Files changed" and do the review there. I'll use my merging powers here though.

**Pull request merged**
