### PR TITLE
Invoke the staging.wpt.fyi Azure hook at the end of daily run

### PR DESCRIPTION
**Pull request by foolip**
This needs to be changed to use wpt.fyi when verified.

Towards https://github.com/web-platform-tests/wpt/issues/14836.

### CODE REVIEW

**Comment by foolip** [comment]
The Taskcluster failure is because of https://github.com/web-platform-tests/wpt/issues/14617.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=4663 is a scheduled build started from the foolip/test-azure-post-wpt.fyi branch in the same way as the epochs/daily builds. It should be a realistic test of the whole setup. It'll take ~2 hours.

**Comment by foolip** [comment]
Alright, the results made it all the way: https://staging.wpt.fyi/results/?sha=d174e85d9c

However, empty runs for Chrome and Firefox have also been created, I'll file an issue.

**Review by gsnedders — APPROVED** [review]

**Comment by foolip** [comment]
Ignoring the Taskcluster failure...

**Comment by foolip** [comment]
Yeah, I sort of realized that after the fact. Tried wpt.fyi and it returns 307, so that'll need to wait.

**Comment by lukebjerring** [comment]
Deploying the required endpoint in https://github.com/web-platform-tests/wpt.fyi/issues/1059

**Pull request merged**
