### PR TITLE
Update interfaces/payment-method-basic-card.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/a74aa91/whatwg/idl/payment-method-basic-card.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/455362278

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@lukebjerring the diff from the custom check doesn't make sense to me:
https://staging.wpt.fyi/results/payment-method-basic-card?product=chrome%5Bmaster%5D&product=chrome%407b3dd729a1&diff

Perhaps caused by comparing to something not close enough to the merge base? (If so, I'm surprised this happened so fast, I thought it'd be a very rare occurrence.)

**Comment by lukebjerring** [comment]
I think it makes sense if you ignore the unaffected tests that were run on master:
https://staging.wpt.fyi/results/payment-method-basic-card?product=chrome%5Bmaster%5D&product=chrome%407b3dd729a1&diff&filter=ACU

(Note that this is the check link provided since https://github.com/web-platform-tests/wpt.fyi/pull/770)

**Comment by foolip** [comment]
But why is historical.https.html or payment-request-canmakepayment-method.https.html affected? (They still show up in the link you gave.)

**Comment by foolip** [comment]
Oh, clicking through I see the results are MISSING, but then why aren't they filtered out by `filter=ACU`?

**Comment by foolip** [comment]
Anyway, this was the first time I saw before and after views for affected tests (idlharness.window.html) and this feature is going to be *the best*. I can see right away that the test must be broken, because there's just a "idl_test setup" test and nothing interesting.

**Comment by lukebjerring** [comment]
I suspect your confusion stems for the fact that we currently treat 0/0 in the UI as actual numbers, when we should be putting MISSING for any zero-sum directory.

**Review by foolip — APPROVED** [review]

**Pull request merged**
