### PR TITLE
Python 3: port xhr tests [part 4]

### PR DESCRIPTION
**Pull request by ziransun**

### CODE REVIEW

**Comment by ziransun** [comment]
Hi @annevk Any chance to review this patch when you find time? Many thanks!

**Review by annevk — APPROVED** [review]
This looks okay. Haven't tried to run anything though.

**Comment by ziransun** [comment]
Thanks @annevk !

**Comment by stephenmcgruer** [comment]
Stability failure on Firefox:

```
3:49.83 INFO ## Unstable results ##
 3:49.83 INFO |                                  Test                                  |                                                       Subtest                                                       |          Results           |                      Messages                     |
 3:49.83 INFO |------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|----------------------------|---------------------------------------------------|
 3:49.83 INFO | `/xhr/send-authentication-basic-setrequestheader-existing-session.htm` | `XMLHttpRequest: send() - "Basic" authenticated request using setRequestHeader() when there is an existing session` | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected "DID" but got "DID-NOT"` |
 3:49.83 INFO 
```

wpt.fyi history doesn't show any flake, and is usually passing (whereas this is FAIL 9/10), so let me try to reproduce this locally before/after this PR.

**Comment by ziransun** [comment]
Just did a local run with the following command at the branch:

`./wpt  run  --stability --yes --no-manifest-update --manifest MANIFEST.json --log-mach-level=debug --log-mach=- firefox xhr/send-authentication-basic-setrequestheader-existing-session.htm`

And here is the result:

```
0:30.55 INFO ::: Running tests in a loop with restarts 10 times : PASS
 0:30.55 INFO :::
 0:30.55 INFO ::: Test verification PASS
```

**Comment by stephenmcgruer** [comment]
I can reproduce on ToT before this PR, so seems safe to land.

**Pull request merged**
