### PR TITLE
Move CSS Fonts Module Level 4 tests to /css-fonts

### LINKED ISSUE #6434: Where should font tests live?
In https://github.com/w3c/web-platform-tests/pull/6350 and https://github.com/w3c/web-platform-tests/pull/6360 some new tests by drott@ (yay!) were upstreamed under the fonts/ directory, where there previously were only font files.

I haven't looked too closely, but it looks like these are at least in part tests for CSS features. @gsnedders, can you advise on whether fonts/ is a good place for these, and close this issue if you think it's OK?

### PR DESCRIPTION
**Pull request by drott**
Fixes #6434.

### CODE REVIEW

**Comment by drott** [comment]
CC @foolip

**Review by foolip — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248888372)

# Firefox (nightly) #
Testing web-platform-tests at revision 63f67230ea8f4a5c68b23914750fbecbd0b250b3
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248888374)

# Sauce (safari) #
Testing web-platform-tests at revision 63f67230ea8f4a5c68b23914750fbecbd0b250b3
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248888398)

# Chrome (unstable) #
Testing web-platform-tests at revision 63f67230ea8f4a5c68b23914750fbecbd0b250b3

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248888401)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 63f67230ea8f4a5c68b23914750fbecbd0b250b3

**Pull request merged**
