### PR TITLE
Add more isEqualNode tests

### PR DESCRIPTION
**Pull request by domenic**
These are being upstreamed from https://github.com/tmpvar/jsdom/blob/master/test/web-platform-tests/to-upstream/dom/nodes/Node-isEqualNode.html

### CODE REVIEW

**Comment by domenic** [comment]
Someone commented in some system I don't understand about using `const`. `const` works in Safari now.

**Comment by jgraham** [comment]
Hmm, any particular difficulty you are having with critic?

Anyway if you look at the review there, it's now 100% with one issue (use of arrow functions, which I don't think are universally supported).

**Comment by domenic** [comment]
Critic doesn't fit with my workflow, and I was meant to understand it is optional. Is that not the case? I prefer normal GitHub pull requests.

Arrow functions are universally supported in modern engines. Regardless, I don't really plan to re-do all my tests to the lowest common denominator when upstreaming, so if that's a prerequisite for submission then I guess I'll put a hold on my upstreaming plans and come back when all browsers have the same level of support for ES features. Let me know.

**Comment by jgraham** [comment]
Well it is optional, but since you're a regular contributor in general I have motivation to push you toward the less-sucky tools, and GitHub is a truly sucky code-review tool.

https://kangax.github.io/compat-table/es6/#safari9 suggests that arrow functions are not in released Safari. Is that wrong? I would *love* to use them since they cut down on the boilerplate, but it seems unreasonable to break these tests in a major browser over something so entirely unrelated to what's being tested, and entirely replaceable.

**Comment by domenic** [comment]
> https://kangax.github.io/compat-table/es6/#safari9 suggests that arrow functions are not in released Safari

My apologies, somehow I double-checked that chart but both times misread the "WK" as "Safari 9".

In any case it sounds like I should wait to upstream my tests until Apple releases Safari 10.

**Comment by Ms2ger** [comment]
If you're unwilling to do the work, please push your branches to the w3c repo rather than your fork, so I can fix them up. Let me or MikeSmith know if you don't have access yet.

**Comment by domenic** [comment]
I do not have access yet.

**Comment by Ms2ger** [comment]
You should have access now.

**Pull request closed without merging**
