### PR TITLE
Generic Sensor: import tests from Chromium Layout test suite

### PR DESCRIPTION
**Pull request by Honry**
- Import tests about losing focus and frequency hint
 - Did some optimization to suit WPT

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18725)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/278026955)

**Comment by Honry** [comment]
@alexshalamov, @pozdnyakov, would you PTAL?

**Review by pozdnyakov — APPROVED** [review]
lgtm

**Comment by Honry** [comment]
@pozdnyakov, thanks for your review.

**Pull request merged**
