### PR TITLE
css-tables branch from csswg-test

### PR DESCRIPTION
**Pull request by gsnedders**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5540)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5540/)

**Comment by gsnedders** [comment]
cc/ @davidsgrogan as well

**Comment by gsnedders** [comment]
Given this PR only alters things in `css/work-in-progress`, I'm happy to merge this without review, given this affects no tests (as far any tooling is concerned).

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221381237)

# Firefox (nightly channel) #
Testing web-platform-tests at revision de533d2f875f45b8827a220c66d67faf6896f72e
Using browser at version BuildID 20170412100254; SourceStamp f40e24f40b4c4556944c762d4764eace261297f5
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221381241)

# Chrome (unstable channel) #
Testing web-platform-tests at revision de533d2f875f45b8827a220c66d67faf6896f72e
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
No tests run.

**Pull request merged**
