### PR TITLE
Add/update tests for cross-realm Error serialization

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/html/pull/5150.

### CODE REVIEW

**Review by yutakahirano — COMMENTED** [review]
I think we need to fix "Cloning a modified Error" as well.

**Review by yutakahirano — APPROVED** [review]
Thank you!

**Comment by annevk** [comment]
I don't see a test where you change the name and the prototype changes based on that.

**Comment by domenic** [comment]
> I don't see a test where you change the name and the prototype changes based on that.

That's "Cloning a modified Error".

**Review by annevk — APPROVED** [review]

**Pull request merged**
