### PR TITLE
 Update "resources" submodule prior to merge

### PR DESCRIPTION
**Pull request by jugglinmike**
The "resources" submodule is planned to be merged into the Web Platform
Tests repository. Prior to that, update the submodule to the latest
commit available on the repository's "master" branch.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5591)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5591/)

**Comment by jugglinmike** [comment]
@jgraham I'm recommending this update prior to updating and landing https://github.com/w3c/web-platform-tests/pull/5536 .

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222842311)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222842313)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 73eadf52df5acb2816cb203e056ec9222f114531
Using browser at version BuildID 20170416100136; SourceStamp ce69b6e1773e9e0d0a190ce899f34b1658e66ca4
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222842314)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 73eadf52df5acb2816cb203e056ec9222f114531
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
No tests run.

**Pull request merged**
