### PR TITLE
Allow metadata to expect any subtest statuses for a test.

### PR DESCRIPTION
**Pull request by LukeZielinski**
This introduces a new key into metadata called `expect_any_subtest_status`. This can be set on the top-most test level. When this key is present, all subtest status will be treated as expected without having to enumerate every failing subtest.

This PR also updates the chromium formatter to better handle unexpected results.

### CODE REVIEW

**Comment by jgraham** [comment]
It's unclear to me what the expected deployment scenario is here. Do you have a requirement to switch this on a per-test basis? If not why not have a command line switch `--test-status-only` or whatever, which does the same but for all tests?

**Comment by LukeZielinski** [comment]
Yes this would be on a per-test basis. Here is an example of a [test](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/2dcontext/imagebitmap/no-coop-coep.https.window.js) (and it's [corresponding failing subtests](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/2dcontext/imagebitmap/no-coop-coep.https.window-expected.txt)). If we used a flag for all tests it wouldn't allow us to see *unexpected* subtest failures.

**Comment by LukeZielinski** [comment]
@jgraham ping?

**Comment by jgraham** [comment]
So, mechanically this patch looks OK. But i"m worried about the implication that you're unable to handle expected fails in subtests. In the absence of this patch what does Blink do with cases where there are 1000 subtests and 999 pass but one fails?

**Comment by LukeZielinski** [comment]
The plan is to eventually support subtest-level failures, but there are some hurdles we have to overcome on the Chromium side before we can do that. The point of this PR is to give us a shortcut to ignore those 999/1000 cases for the time being until we can properly support them.

To answer your question, today, a test with 999/1000 passes will have a companion file that lists all 1000 subtests and their statuses (mostly PASS with one of them being a FAIL). If that test behaviour changes (say, to 1/1000 passes) then we detect an unexpected result by comparing against that companion file. Very similar to how metadata works.

This PR will ignore that change in test behaviour and continue to treat that test as "failing as expected". Yes this is a limitation but it's one we plan to resolve later on.

**Comment by jgraham** [comment]
So I still don't fully understand; the subtest behaviour that you describe in the absence of this flag sounds correct (the failing subtests change and the system detects a regression). However if this is needd for Blink-CI reasons and we don't want other projects using it (and certainly I don't want gecko engineers setting this property), I wonder if we can at least prefix the name with `blink-`.

**Review by jgraham — CHANGES_REQUESTED** [review]
Please update the name to indicate that this is for Blnk CI only and not intended for general use.

**Review by jgraham — APPROVED** [review]

**Comment by LukeZielinski** [comment]
Thanks James.

**Pull request merged**
