### PR TITLE
Delete test_valid_but_unmatchable_key webdriver test

### PR DESCRIPTION
**Pull request by julianrkung**
This test is designed with the assumption that the first set of capabilities should be rejected during the [matching capabilities algorithm](https://w3c.github.io/webdriver/#dfn-matching-capabilities) at step 3 when following the "otherwise" substep due to the extension capability "foo:unmatchable". 

> If name is the key of an extension capability, let value be the result of trying implementation-specific steps to match on name with value. If the match is not successful, return success with data null.

However, the test incorrectly assumes that the implementation-specific steps will result in an unsuccessful match. The test therefore is no longer strictly adhering to the defined spec. 

No browsers are currently passing this tests so I propose that it should be removed.

### CODE REVIEW

**Comment by jgraham** [comment]
That's the wrong bit of spec. I think the spec is unclear here, but the relevant part is the [validate capabilites](https://w3c.github.io/webdriver/#dfn-validate-capabilities) algorithm. In this case the question is "is foo:unmatched the name of an extension capability"? I think the spec is unclear about whether any capability including the `:` matches that condition. My understanding is that the intent is in fact that only implementation-recognised extension capabilites are matched there. So I think the test is correct to the extent that it's trying to test something meaningful, but there ought to be a spec clarification to be sure.

**Comment by JohnChen0** [comment]
Note that this test is also in conflict with https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/new_session/support/create.py#L38, where "test:extension" is considered to be a valid capability. If we decide to interpret the spec as intending to reject all unrecognized extension capabilities, then "test:extension" should be moved to invalid_data section.

**Comment by andreastt** [comment]
To your last point, we can’t reject unknown extension capabilities because they may not all be meant for the endpoint node. For example, there may exist extension capabilities in the new session request that are meant for intermediary nodes, so the design of the capabilities matching is meant for them to be passed through uninterrupted. This is why we test that `test:extension` is not being rejected.

**Comment by JohnChen0** [comment]
If `test:extension` is allowed, then shouldn't `foo:unmatchable` also be allowed?

**Comment by julianrkung** [comment]
I also do not understand the reasoning behind `test:extension` being allowed if `foo:unmatchable` must be rejected. An explanation would be really appreciated!

**Comment by julianrkung** [comment]
Updates on this? Would like to not forget about this PR

**Review by JohnChen0 — APPROVED** [review]

**Comment by JohnChen0** [comment]
This issue was discussed during TPAC (https://www.w3.org/2019/09/19-webdriver-minutes.html#item11), and the resolution was to always accept unknown extension capabilities. So I believe this PR should be merged. Could someone with write access to the repo handle it? Thanks.

**Review by Hexcles — APPROVED** [review]
Although not a part of the WG, I was at the meeting and @JohnChen0 's summary matches my understanding.

I'm going to approve and merge this now to not let the PR go stale. If I missed anything, feel free to revert it.

**Comment by Hexcles** [comment]
@JohnChen0 is going to send a PR to clarify the spec.

**Comment by andreastt** [comment]
@JohnChen0 In light of https://github.com/w3c/webdriver/pull/1454#pullrequestreview-305806314, perhaps this should be changed to reject unknown extension capabilities instead of beng deleted?

**Comment by JohnChen0** [comment]
> @JohnChen0 In light of [w3c/webdriver#1454 (review)](https://github.com/w3c/webdriver/pull/1454#pullrequestreview-305806314), perhaps this should be changed to reject unknown extension capabilities instead of beng deleted?

@andreastt Please see my comment at https://github.com/w3c/webdriver/pull/1454#discussion_r338225315, and the [TPAC minutes](https://www.w3.org/2019/09/19-webdriver-minutes.html#resolution04). My understanding is unknown extension capabilities should be accepted instead of rejected.

**Comment by JohnChen0** [comment]
WebDriver spec has been updated for clarification (w3c/webdriver#1454). Can this PR be merged now? Thanks.

**Comment by Hexcles** [comment]
Retriggered tests. We can merge once they pass.

**Comment by Hexcles** [comment]
Ahh we need a rebase.

**Comment by Hexcles** [comment]
Done, and thanks for the patience!

**Comment by JohnChen0** [comment]
Thanks!

**Pull request merged**
