### PR TITLE
Add RTCIceCandidate IDL test

### PR DESCRIPTION
**Pull request by soareschen**
This PR tests the conformance to IDL definition of `RTCIceCandidate`.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5688)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225846021)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225846023)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 52006c59335d3384f624c1e5ce9c92e8399c4880
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5688/webrtc/RTCIceCandidate-idl.html">/webrtc/RTCIceCandidate-idl.html</a></summary>


|                                                   Subtest                                                    | Results |                                                                                       Messages                                                                                      |
|--------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                              | OK      |                                                                                                                                                                                     |
| `RTCIceCandidate interface: existence and properties of interface object`                                    | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface object length`                                                                    | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface object name`                                                                      | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: existence and properties of interface prototype object`                          | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: existence and properties of interface prototype object's "constructor" property` | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: attribute candidate`                                                             | FAIL    | `assert_equals: setter must be undefined for readonly attributes expected (undefined) undefined but got (function) function "function set candidate() {\n    [native code]\n}"`     |
| `RTCIceCandidate interface: attribute sdpMid`                                                                | FAIL    | `assert_equals: setter must be undefined for readonly attributes expected (undefined) undefined but got (function) function "function set sdpMid() {\n    [native code]\n}"`        |
| `RTCIceCandidate interface: attribute sdpMLineIndex`                                                         | FAIL    | `assert_equals: setter must be undefined for readonly attributes expected (undefined) undefined but got (function) function "function set sdpMLineIndex() {\n    [native code]\n}"` |
| `RTCIceCandidate interface: attribute foundation`                                                            | FAIL    | `assert_true: The prototype object must have a property "foundation" expected true got false`                                                                                       |
| `RTCIceCandidate interface: attribute priority`                                                              | FAIL    | `assert_true: The prototype object must have a property "priority" expected true got false`                                                                                         |
| `RTCIceCandidate interface: attribute ip`                                                                    | FAIL    | `assert_true: The prototype object must have a property "ip" expected true got false`                                                                                               |
| `RTCIceCandidate interface: attribute protocol`                                                              | FAIL    | `assert_true: The prototype object must have a property "protocol" expected true got false`                                                                                         |
| `RTCIceCandidate interface: attribute port`                                                                  | FAIL    | `assert_true: The prototype object must have a property "port" expected true got false`                                                                                             |
| `RTCIceCandidate interface: attribute type`                                                                  | FAIL    | `assert_true: The prototype object must have a property "type" expected true got false`                                                                                             |
| `RTCIceCandidate interface: attribute tcpType`                                                               | FAIL    | `assert_true: The prototype object must have a property "tcpType" expected true got false`                                                                                          |
| `RTCIceCandidate interface: attribute relatedAddress`                                                        | FAIL    | `assert_true: The prototype object must have a property "relatedAddress" expected true got false`                                                                                   |
| `RTCIceCandidate interface: attribute relatedPort`                                                           | FAIL    | `assert_true: The prototype object must have a property "relatedPort" expected true got false`                                                                                      |
| `RTCIceCandidate interface: attribute ufrag`                                                                 | FAIL    | `assert_true: The prototype object must have a property "ufrag" expected true got false`                                                                                            |
| `RTCIceCandidate must be primary interface of iceCandidate`                                                  | PASS    |                                                                                                                                                                                     |
| `Stringification of iceCandidate`                                                                            | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "candidate" with the proper type (0)`         | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "sdpMid" with the proper type (1)`            | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "sdpMLineIndex" with the proper type (2)`     | PASS    |                                                                                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "foundation" with the proper type (3)`        | FAIL    | `assert_inherits: property "foundation" not found in prototype chain`                                                                                                               |
| `RTCIceCandidate interface: iceCandidate must inherit property "priority" with the proper type (4)`          | FAIL    | `assert_inherits: property "priority" not found in prototype chain`                                                                                                                 |
| `RTCIceCandidate interface: iceCandidate must inherit property "ip" with the proper type (5)`                | FAIL    | `assert_inherits: property "ip" not found in prototype chain`                                                                                                                       |
| `RTCIceCandidate interface: iceCandidate must inherit property "protocol" with the proper type (6)`          | FAIL    | `assert_inherits: property "protocol" not found in prototype chain`                                                                                                                 |
| `RTCIceCandidate interface: iceCandidate must inherit property "port" with the proper type (7)`              | FAIL    | `assert_inherits: property "port" not found in prototype chain`                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "type" with the proper type (8)`              | FAIL    | `assert_inherits: property "type" not found in prototype chain`                                                                                                                     |
| `RTCIceCandidate interface: iceCandidate must inherit property "tcpType" with the proper type (9)`           | FAIL    | `assert_inherits: property "tcpType" not found in prototype chain`                                                                                                                  |
| `RTCIceCandidate interface: iceCandidate must inherit property "relatedAddress" with the proper type (10)`   | FAIL    | `assert_inherits: property "relatedAddress" not found in prototype chain`                                                                                                           |
| `RTCIceCandidate interface: iceCandidate must inherit property "relatedPort" with the proper type (11)`      | FAIL    | `assert_inherits: property "relatedPort" not found in prototype chain`                                                                                                              |
| `RTCIceCandidate interface: iceCandidate must inherit property "ufrag" with the proper type (12)`            | FAIL    | `assert_inherits: property "ufrag" not found in prototype chain`                                                                                                                    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225846029)

# Chrome (unstable channel) #

**Comment by agouaillard** [comment]
see #5693

**Pull request closed without merging**
