### PR TITLE
Do not test non-exposed event constructors

### PR DESCRIPTION
**Pull request by domenic**
As seen from https://wpt.fyi/results/dom/events/EventTarget-dispatchEvent.html?label=master&label=experimental&aligned all browsers fail TouchEvent for this test

### CODE REVIEW

**Review by annevk — CHANGES_REQUESTED** [review]
I suggest making a commit equivalent to https://github.com/web-platform-tests/wpt/commit/0ad973f918c533d2474ebf6f8f8d18c3179fdf55.

**Comment by domenic** [comment]
That commit is solving a different problem. TouchEvent is creatable on mobile, and DeviceOrientationEvent is creatable on non-Safari. So moving them to the non-creatable list would be incorrect. Instead this is about dealing with the step in the createEvent algorithm which allows throwing a NotSupportedError if the interface is not exposed.

**Comment by annevk** [comment]
Oh hmm, I had forgotten about that weirdness. I wonder if we should make that more specific rather than having it rather open-ended.

**Comment by domenic** [comment]
It makes sense to me from the perspective that not all browsers implement all events. I guess since the table is legacy and not growing, we could make the spec step specific to DeviceOrientationEvent, DeviceMotionEvent, and TouchEvent, but I dunno. I still think this is a reasonable test change.

**Comment by annevk** [comment]
Looking at https://github.com/whatwg/dom/pull/230 we made the change for TouchEvent only. Having said that, I don't think Firefox really supports device motion/orientation on desktop either so not sure what's going on there.

I'd rather restrict this to those events and have some kind of follow-up filed so it's less likely we regress on the remainder.

**Comment by domenic** [comment]
Alright. I was just doing this from the GitHub UI to try to fix a fails-in-all-browsers test, so I'll leave more work here to someone else.

**Pull request closed without merging**
