### PR TITLE
[css-tables] Convert tabs to spaces in css-tables-3

### PR DESCRIPTION
**Pull request by davidsgrogan**
And remove a line from lint.whitelist

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6058)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236157144)

# Firefox (nightly) #
Testing web-platform-tests at revision 89c5f784c89eae27af31747a355094296cb3dcee
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6058/css/css-tables-3/floats/floats-wrap-bfc-006b.xht">/css/css-tables-3/floats/floats-wrap-bfc-006b.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6058/css/css-tables-3/floats/floats-wrap-bfc-006c.xht">/css/css-tables-3/floats/floats-wrap-bfc-006c.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236157145)

# Sauce (safari) #
Testing web-platform-tests at revision 89c5f784c89eae27af31747a355094296cb3dcee
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6058/css/css-tables-3/floats/floats-wrap-bfc-006b.xht">/css/css-tables-3/floats/floats-wrap-bfc-006b.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6058/css/css-tables-3/floats/floats-wrap-bfc-006c.xht">/css/css-tables-3/floats/floats-wrap-bfc-006c.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236157151)

# Chrome (unstable) #
Testing web-platform-tests at revision 89c5f784c89eae27af31747a355094296cb3dcee

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236157152)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 89c5f784c89eae27af31747a355094296cb3dcee

**Review by dbaron — APPROVED** [review]

**Pull request merged**
