### PR TITLE
Remove TODO from remote-playback/README.md

### PR DESCRIPTION
**Pull request by mounirlamouri**
The idltestharness have been added.

### CODE REVIEW

**Comment by Honry** [comment]
@mounirlamouri, It's better to add OWNERS file with owners/reviewers of this folder, i.e. you and @avayvod.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242352450)

# Firefox (nightly) #
Testing web-platform-tests at revision 0a2b94ed5c61010d49eec1fd5528666c98ec142f
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242352451)

# Sauce (safari) #
Testing web-platform-tests at revision 0a2b94ed5c61010d49eec1fd5528666c98ec142f
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242352457)

# Chrome (unstable) #
Testing web-platform-tests at revision 0a2b94ed5c61010d49eec1fd5528666c98ec142f
Using browser at version 61.0.3124.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242352458)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 0a2b94ed5c61010d49eec1fd5528666c98ec142f

**Comment by anssiko** [comment]
Non-owner LGTM :-)

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Review by Honry — APPROVED** [review]

**Pull request merged**
