### PR TITLE
chore(webmessaging/broadcastchannel): html -> js

### PR DESCRIPTION
**Pull request by bnoordhuis**
Change two BroadcastChannel tests from .html to .any.js in order to
make them runnable under Deno.

Refs: https://github.com/denoland/deno/issues/10354

### CODE REVIEW

**Comment by lucacasonato** [comment]
Test result seems to suggest an issue in Chromium implementation for dedicated workers, or a flaky test when running in dedicated workers.

**Comment by annevk** [comment]
@mkruisselbrink could you take a look?

**Comment by lucacasonato** [comment]
Friendly ping on this :-)

**Comment by annevk** [comment]
@lucacasonato perhaps a way to make progress here is to file a Chromium bug.

**Comment by lucacasonato** [comment]
@annevk Just took another look, and it seems this test has always been broken in Chromium: https://wpt.fyi/results/webmessaging/broadcastchannel?diff&filter=ADC&run_id=5680842594582528&run_id=5758173145202688. It is now just exaggerated because it runs twice (once on main thread, once in dedicated worker). Hence the check failure. I think that shouldn't block this PRs merge.

**Review by annevk — APPROVED** [review]
Agreed.

**Comment by annevk** [comment]
Can you rebase and force push to get the status checks running again?

**Comment by bnoordhuis** [comment]
Rebased + force-pushed.

**Comment by annevk** [comment]
Thanks!

**Comment by mkruisselbrink** [comment]
Sorry for not seeing this earlier. I think the chromium flakiness was actually fixed a while ago in chrome, but wpt.fyi seems to be running a rather old dev-channel version of chrome for some reason...

**Pull request merged**
