### PR TITLE
Fixes the test and uses proper idl definition

### PR DESCRIPTION
**Pull request by plehegar**
With latest known IDL techniques

### CODE REVIEW

**Review by lukebjerring — APPROVED** [review]
Looks good. One step further is to change the file to a '.window.js', e.g. [audio-output](https://github.com/web-platform-tests/wpt/blob/master/audio-output/idlharness.window.js) (less HTML boilerplate, and if the `wpt serve` behaviour is updated, its generated file would be updated.

And, even further, I'm also working on a more succinct `test_idl` helper function, e.g. [pointerlock](https://github.com/web-platform-tests/wpt/blob/master/pointerlock/interfaces.window.js)

**Review by NavidZ — APPROVED** [review]
@lukebjerring would you be able to update pointerevents to something similar  to pointerlock one later on?

**Comment by lukebjerring** [comment]
Absolutely. Throw a card in the to-do column of https://github.com/web-platform-tests/wpt/projects/1 :)

**Comment by lukebjerring** [comment]
This PR was made redundant by #11922 - sorry for clobbering it!

**Pull request closed without merging**
