### PR TITLE
Fix a file descriptor and thread leak in wptserver

### LINKED ISSUE #23905: Vertical alignment of inline-table
It seems like we have a bunch of issues here, and we probably need to do a deeper look into this.

 - `css/CSS2/linebox/vertical-align-applies-to-014.xht` claims to test vertical-align does not apply to inline-table (but the spec says ["The baseline of an 'inline-table' is the baseline of the first row of the table"](https://www.w3.org/TR/CSS21/visudet.html#propdef-vertical-align)). Furthermore, it doesn't actually do _anything_, given it'll be rendered the same regardless of value of vertical-align.
 - `css/CSS2/normal-flow/min-height-applies-to-014.xht` with the ref I added in #23903 fails in Chromium due to its choice of alignment. However, AFAICT empty table alignment isn't specified (see https://github.com/w3c/csswg-drafts/issues/439).

### LINKED ISSUE #27072: wptserve can fail with "[Errno 24] Too many open files"
Just noticed that when working on improvements for Marionette, and setting up a testcase for Marionette with the `pageLoadStrategy` set to `none`. If a huge amount of WebDriver navigation requests are send in parallel, wptserve will give-up after a short while with serving the wanted URL when it comes from a file on disk (no handler). In such a case it just returns a 404. Manually reloading the page doesn't make a difference.

Trying to get a index list of all the files from the parent directory gives me a 500 error:

```
[Errno 24] Too many open files: '/Users/henrik/code/gecko/testing/marionette/harness/marionette_harness/www/'
Traceback (most recent call last):
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/server.py\", line 287, in finish_handling
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 212, in __call__
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 84, in __call__
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 101, in list_items\nOSError: [Errno 24] Too many open files: '/Users/henrik/code/gecko/testing/marionette/harness/marionette_harness/www/'
```

As @jgraham said on Matrix: It could be a "we should have a size-limited threadpool, rather than try to spawn an indefinite number of threads" bug. If each thread uses a file handle we can certainly leak them.

### PR DESCRIPTION
**Pull request by mrobinson**
Always ensure that wptserve closes file descriptors that it opens for HTTP2 requests. For the WebSocket handler, use Python contexts. This isn't possible for non-WebSocket requests so make sure to close them manually. In addition, when frame.stream_ended always end the stream's thread. The code which spawns the thread assumes this is the case and will forget about the thread as soon as it sees this property.

Probably fixes #27072.

### CODE REVIEW

**Comment by mrobinson** [comment]
Looks like there are still some issues with this pull request. I'll address them and upload a new version.

**Comment by mrobinson** [comment]
Okay. This is ready to review, I think.

**Review by jgraham — COMMENTED** [review]
This looks good to me, thanks!

Just to be extra careful with the infrastructure change, I've pushed to https://github.com/web-platform-tests/wpt/tree/triggers/firefox_nightly which will do a full run and we can use to check for unexpected regressions.

**Comment by mrobinson** [comment]
@jgraham Thank you very much for the review and pushing this to https://github.com/web-platform-tests/wpt/tree/triggers/firefox_nightly for testing! It looks like all the jobs are green there?

**Comment by jgraham** [comment]
So the key thing is not that the jobs are green, but that there's no obvious h2 regressions when comparing to the master branch: https://wpt.fyi/results/?diff&filter=ADC&run_id=5107253175123968&run_id=5123299340713984.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
