### PR TITLE
webrtc: Fix RTCSctpTransport.maxMessageSize default value

### PR DESCRIPTION
**Pull request by adam-be**
Align test with spec change requested in https://github.com/w3c/webrtc-pc/issues/1700

### CODE REVIEW

**Comment by foolip** [comment]
@tobie, any idea why @wpt-pr-bot didn't add labels here?

**Comment by foolip** [comment]
Well that was weird. Seems like just commenting brought the attention of bots.

@mattl, I think that this will probably stay pending forever, because the Travis job has already finished. If that's the case, can you file an issue to deal with the case where the first comment is posted after Travis is finished?

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
This should not be merged yet, wait for a spec PR for https://github.com/w3c/webrtc-pc/issues/1700.

**Comment by foolip** [comment]
@mattl, I just restarted the Travis job because the Firefox stability check had failed with no information, so that'll probably cause the comment to be updated now.

**Comment by tobie** [comment]
Possibly linked to the recent GH outage.

**Comment by tobie** [comment]
> Well that was weird. Seems like just commenting brought the attention of bots.

Yeah, @wpt-pr-bot looks for any kind of change to the PR to see if it needs to be adapted. There's no built-in system to ping the repo regularly in case an whole PR was missed due to an issue, however.

**Comment by foolip** [comment]
Merged and linked https://github.com/w3c/webrtc-pc/pull/1713 in the commit message.

**Pull request merged**
