### PR TITLE
XMLHttpRequest: create more base URL tests

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
Note: only Firefox passes all of these. But what Chrome and Safari do doesn't seem reasonable.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230365117)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 6b12e559db265852dbb8110ffd3c1660a2a1eb73
Using browser at version BuildID 20170508100218; SourceStamp 1fda52a1f3b81cf1a821155998dca637bb64e3d9
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5863/XMLHttpRequest/responsexml-document-properties.htm">/XMLHttpRequest/responsexml-document-properties.htm</a></summary>


|                                Subtest                                | Results |                               Messages                              |
|-----------------------------------------------------------------------|---------|---------------------------------------------------------------------|
|                                                                       | OK      |                                                                     |
| `domain`                                                              | PASS    |                                                                     |
| `URL`                                                                 | PASS    |                                                                     |
| `documentURI`                                                         | PASS    |                                                                     |
| `baseURI`                                                             | PASS    |                                                                     |
| `referrer`                                                            | PASS    |                                                                     |
| `title`                                                               | PASS    |                                                                     |
| `contentType`                                                         | PASS    |                                                                     |
| `readyState`                                                          | PASS    |                                                                     |
| `location`                                                            | PASS    |                                                                     |
| `defaultView`                                                         | PASS    |                                                                     |
| `body`                                                                | PASS    |                                                                     |
| `images`                                                              | PASS    |                                                                     |
| `doctype`                                                             | PASS    |                                                                     |
| `forms`                                                               | PASS    |                                                                     |
| `all`                                                                 | PASS    |                                                                     |
| `links`                                                               | PASS    |                                                                     |
| `cookie`                                                              | FAIL    | `assert_equals: expected (string) "" but got (undefined) undefined` |
| `Test document URL properties after redirect`                         | PASS    |                                                                     |
| `Test document URL properties of document with <base> after redirect` | PASS    |                                                                     |
| `lastModified set to time of response if no HTTP header provided`     | PASS    |                                                                     |
| `lastModified set to related HTTP header if provided`                 | PASS    |                                                                     |
| `cookie (after setting it)`                                           | FAIL    | `assert_equals: expected "" but got "thisshouldbeignored"`          |
| `styleSheets`                                                         | PASS    |                                                                     |
| `implementation`                                                      | PASS    |                                                                     |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230365129)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 6b12e559db265852dbb8110ffd3c1660a2a1eb73
Using browser at version 60.0.3088.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5863/XMLHttpRequest/responsexml-document-properties.htm">/XMLHttpRequest/responsexml-document-properties.htm</a></summary>


|                                Subtest                                | Results |                                                                                                                                                                                                                                                                                                          Messages                                                                                                                                                                                                                                                                                                         |
|-----------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                       | OK      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `domain`                                                              | FAIL    | `assert_equals: expected (undefined) undefined but got (string) "web-platform.test"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| `URL`                                                                 | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `documentURI`                                                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `baseURI`                                                             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `referrer`                                                            | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `title`                                                               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `contentType`                                                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `readyState`                                                          | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `location`                                                            | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `defaultView`                                                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `body`                                                                | FAIL    | `assert_equals: expected (undefined) undefined but got (object) null`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| `images`                                                              | FAIL    | `assert_equals: expected (undefined) undefined but got (object) object "[object HTMLCollection]"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| `doctype`                                                             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `forms`                                                               | FAIL    | `assert_equals: expected (undefined) undefined but got (object) object "[object HTMLCollection]"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| `all`                                                                 | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `links`                                                               | FAIL    | `assert_equals: expected (undefined) undefined but got (object) object "[object HTMLCollection]"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| `cookie`                                                              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `Test document URL properties after redirect`                         | FAIL    | `assert_equals: expected "http://web-platform.test:8000/XMLHttpRequest/resources/well-formed.xml" but got "http://web-platform.test:8000/XMLHttpRequest/resources/redirect.py?location=well-formed.xml"`                                                                                                                                                                                                                                                                                                                                                                                                                  |
| `Test document URL properties of document with <base> after redirect` | FAIL    | `assert_equals: expected "http://web-platform.test:8000/XMLHttpRequest/resources/base.xml" but got "http://web-platform.test:8000/XMLHttpRequest/resources/redirect.py?location=base.xml"`                                                                                                                                                                                                                                                                                                                                                                                                                                |
| `lastModified set to time of response if no HTTP header provided`     | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `lastModified set to related HTTP header if provided`                 | FAIL    | `assert_equals: expected 1494340573000 but got 1494340379000;assert_equals: expected 1494340565000 but got 1494340379000;assert_equals: expected 1494340574000 but got 1494340379000;assert_equals: expected 1494340572000 but got 1494340379000;assert_equals: expected 1494340571000 but got 1494340379000;assert_equals: expected 1494340568000 but got 1494340379000;assert_equals: expected 1494340566000 but got 1494340379000;assert_equals: expected 1494340575000 but got 1494340379000;assert_equals: expected 1494340569000 but got 1494340379000;assert_equals: expected 1494340567000 but got 1494340379000` |
| `cookie (after setting it)`                                           | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `styleSheets`                                                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `implementation`                                                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |

</details>
</details>

**Comment by foolip** [comment]
@nyaxt @sof @tyoshino @yutakahirano, might any of you be interested in reviewing this and seeing if any of the Chrome failures are things that *wouldn't* be a good idea to change? (Adding yourselves to XMLHttpRequest/OWNERS in this repo is the way to keep track of all upstream changes before they are imported into Blink.)

**Comment by yutakahirano** [comment]
Maybe https://crbug.com/379676?

**Comment by annevk** [comment]
@yutakahirano yeah, that seems like the basic issue from which all other problems derive.

**Comment by annevk** [comment]
@youennf thoughts?

**Comment by yutakahirano** [comment]
OK, I fixed https://crbug.com/379676.

**Review by jdm — APPROVED** [review]

**Pull request merged**
