### PR TITLE
Add CSS Shadow Parts IDL tests

### PR DESCRIPTION
**Pull request by foolip**
Closes https://github.com/web-platform-tests/wpt/pull/19290.

### CODE REVIEW

**Comment by foolip** [comment]
https://wpt.fyi/results/css/css-shadow-parts/idlharness.html?sha=74220b0f12&label=pr_head shows this is already implemented in Chrome and Firefox, so a new Safari-only failure. Didn't expect that, but revealing that is good.

**Review by lukebjerring — APPROVED** [review]

**Comment by foolip** [comment]
Good morning, @lukebjerring! Apologies if I was too quick to merge https://github.com/web-platform-tests/wpt/pull/19722, if you do want to keep reviewing here I'll revert it!

**Comment by lukebjerring** [comment]
No, I think the reviewer list should have some level of expectations implied, and I can’t guarantee any attention, so it’s the right move.

**Comment by foolip** [comment]
Alright, that is what I expected. Thanks for the review here, and hope to see you around!

**Pull request merged**
