### PR TITLE
[wptserve] Preserve semicolons in query parameters

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by gsnedders** [comment]
Honestly, to me this seems incredibly hackish; I think I'd rather we just implement `parse_qs`/`qsl` ourselves based on the URL spec?

**Comment by jugglinmike** [comment]
That could be a nice side-project, but this patch will unblock new tests today. Is your objection only aesthetic?

**Review by Hexcles — COMMENTED** [review]
So I've never read the URL spec... Is Python's handling of `;` as a separator consistent with the specs? Or is it a Python custom behaviour?

**Comment by jugglinmike** [comment]
It's custom. [When parsing query strings, URL doesn't assign any meaning to `;`.](https://url.spec.whatwg.org/#concept-urlencoded-parser)

**Comment by jgraham** [comment]
This code is almost as long as the underlying Python function, minus the parts we aren't using. Literally copying from `parse_qs` and `parse_qsl`, removing the `;` handling and the parts we don't use and cleaning up the resulting code a bit, we get:
```
def parse_qs(qs):
    pairs = [item.split("=", 1) for item in qs.split('&') if item]
    rv = defaultdict(list)
    for name, value in pairs:
        if len(value):
            name = unquote(name.replace('+', ' '))
            value = unquote(value.replace('+', ' '))
            rv[name].append(value)
    return dict(rv)
```

**Comment by jugglinmike** [comment]
Thanks, @jgraham. Your suggested implementation needed a small tweak to handle parameters without values, and we needed to extend the test suite since we'll be absorbing the contract. I've done both of those things and pushed the result to this branch.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
