### PR TITLE
Fix endpoint URLs for COOP navigation reporting tests so that these t…

### PR DESCRIPTION
**Pull request by cdumez**
…ests are runnable with WebKit test infrastructure

The tests were hardcoding `https://{{hosts[][www]}}:{{ports[https][0]}}/reporting/resources/report.py` for the endpoint URLs.
This resolved to `https://www.localhost:9443/reporting/resources/report.py` but the `https://www.localhost:9443` host is not
supported by the WebKit layout test infrastructure (we only have https://localhost:9443 & https://127.0.0.1:9443). To make
the tests runnable with the WebKit test infrastructure, I updating the headers files to use relative URLs instead of endpoints.

### CODE REVIEW

**Comment by cdumez** [comment]
cc @camillelamy @annevk

**Comment by mikewest** [comment]
These aren't on the same host, though. Isn't testing `host` => `www.host` part of the test? That seems like something WebKit's infrastructure needs to support... what do y'all do with the other aliases (documented at https://web-platform-tests.org/writing-tests/server-features.html#tests-involving-multiple-origins)?

**Comment by mikewest** [comment]
(That said, I'm of course fine with changing these specific tests if the `www` subdomain isn't actually part of what's under test. I do think the broader question is important, though; we use those host aliases in tests all over the place.)

**Comment by cdumez** [comment]
> These aren't on the same host, though. Isn't testing `host` => `www.host` part of the test? That seems like something WebKit's infrastructure needs to support... what do y'all do with the other aliases (documented at https://web-platform-tests.org/writing-tests/server-features.html#tests-involving-multiple-origins)?

Yes, they are not the same host, which is kinda the point since the WebKit infrastructure doesn't support the www.localhost.
Tests are usually written using get-host-info.sub.js and that script has special casing when `ORIGINAL_HOST === 'localhost'` to use `127.0.0.1` as `REMOTE_HOST` and `NOTSAMESITE_HOST`. This makes most of the tests work with our infrastructure even though it isn't perfect. Supporting other hosts in WebKit layout tests would be great but I don't see this happening soon sadly.

It is not clear to me why these tests need to use endpoint URIs on different domains. Each of these tests seems to be testing valuable behavior that has nothing to do with which host the endpoint URI has.

For example, this test: cross-origin-opener-policy/reporting/navigation-reporting/report-only-four-reports.https.html.
It seems it was written by @ParisMeuleman and reviewed by @ArthurSonzogni. The change log says:
> This adds basic tests of the report-only features for the navigation
> case, where the report-only headers would cause a browsing context
> group switch.

From the changelog, it doesn't seem to me that the endpoint needs to be on another host.

If for some reason, these tests do really need to use an endpoint URI from another host, we can still make them compatible with the WebKit infrastructure by having them end up on the 127.0.0.1 host somehow?

**Comment by mikewest** [comment]
Long-term, it would be ideal for WebKit to support the substitution mechanism here across all the named hosts; there are certainly tests (cookies' `domain`, for instance) that use more than two names to validate behavior (set on `a.whatever`, not visible on `whatever` and `b.whatever`). Is there a bug filed against WebKit on this topic that I could follow? Or should I file one?

For these specific tests, I think I agree with you that they don't depend on the reporting endpoint being cross-origin. I'd like @ArthurSonzogni to take a quick look to confirm that I'm not missing a dependency somewhere, but I think changing them to relative URLs wouldn't change the meaning of the tests.

**Comment by cdumez** [comment]
I totally agree that long term, WebKit needs to support more hosts and we do have a bug tracking this (assigned to @gsnedders iirc).

**Comment by mikewest** [comment]
Ok, then we're on the same page. :) For posterity, I think it's https://bugs.webkit.org/show_bug.cgi?id=127676.

I poked Arthur; if he's ok with the patch, maybe he can merge it in?

**Comment by ArthurSonzogni** [comment]
Thanks! I don't see any good reason to hardcode the origin. This patch looks reasonnable to me.
Those test are inside "/navigation-reporting/", Pâris Meuleman should know, but he is OOO. I didn't followed the same path when writting tests for "/access-reporting/", COEP or COEP:credentialless. 

Maybe this was to ensure all the reports are sent to the same origin, independently of the origin of the document which triggered the report? I know there are tests expecting multiple reports and this might be affected?

I took a look at the history and I don't see any clear reasons explained. I think we should go with this patch. I just would like to ensure this won't immediately break the Chrome CQ. I sent it:
https://chromium-review.googlesource.com/c/chromium/src/+/3151876/
If everything is green, I won't have anything against landing this patch.

**Review by ArthurSonzogni — APPROVED** [review]
LGTM!

**Pull request merged**
