### PR TITLE
Stability script: reimplement support for timeouts

### LINKED ISSUE #4985: Stability checker doesn't handle TIMEOUT
see, e.g., https://travis-ci.org/w3c/web-platform-tests/jobs/204278553

```
Traceback (most recent call last):
  File "check_stability.py", line 810, in <module>
    retcode = main()
  File "check_stability.py", line 792, in main
    results, inconsistent = process_results(log, args.iterations)
  File "check_stability.py", line 560, in process_results
    reader.handle_log(reader.read(log), handler)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/mozlog/reader.py", line 77, in handle_log
    handler(item)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/mozlog/reader.py", line 71, in __call__
    return handler(data)
  File "check_stability.py", line 522, in test_status
    subtest["status"][data["status"]] += 1
KeyError: u'TIMEOUT'
```

cc/ @bobholt @jgraham @sideshowbarker

### PR DESCRIPTION
**Pull request by jugglinmike**
This should resolve gh-4985

### CODE REVIEW

**Comment by jugglinmike** [comment]
(I will remove the "debugging" commit once the CI job has completed and demonstrated proper functioning.)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204327834)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 661062fadbf73e549cc4adb6e167a80b7664426e
Using browser at version BuildID 20170221110300; SourceStamp d84beb192e57e26846c82d3df3599381f4663792
Starting 10 test iterations
## Unstable results ##


|                              Test                              |                 Subtest                  |            Results            |     Messages     |
|----------------------------------------------------------------|------------------------------------------|-------------------------------|------------------|
| `/html/browsers/offline/application-cache-api/api_update.html` | `Offline Application Cache - API_update` | **PASS: 5/10, TIMEOUT: 5/10** | `Test timed out` |

## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4987/html/browsers/offline/application-cache-api/api_update.html">/html/browsers/offline/application-cache-api/api_update.html</a></summary>


|                 Subtest                  |            Results            |     Messages     |
|------------------------------------------|-------------------------------|------------------|
|                                          | **OK: 5/10, TIMEOUT: 5/10**   |                  |
| `Offline Application Cache - API_update` | **PASS: 5/10, TIMEOUT: 5/10** | `Test timed out` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4987/html/browsers/offline/application-cache-api/api_update_error.html">/html/browsers/offline/application-cache-api/api_update_error.html</a></summary>


|            Subtest             | Results |     Messages     |
|--------------------------------|---------|------------------|
|                                | TIMEOUT |                  |
| `INVALID_STATE_ERR error test` | TIMEOUT | `Test timed out` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204327835)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 661062fadbf73e549cc4adb6e167a80b7664426e
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
## Unstable results ##


|                              Test                              |                 Subtest                  |            Results            |     Messages     |
|----------------------------------------------------------------|------------------------------------------|-------------------------------|------------------|
| `/html/browsers/offline/application-cache-api/api_update.html` | `Offline Application Cache - API_update` | **PASS: 7/10, TIMEOUT: 3/10** | `Test timed out` |

## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4987/html/browsers/offline/application-cache-api/api_update.html">/html/browsers/offline/application-cache-api/api_update.html</a></summary>


|                 Subtest                  |            Results            |     Messages     |
|------------------------------------------|-------------------------------|------------------|
|                                          | **OK: 7/10, TIMEOUT: 3/10**   |                  |
| `Offline Application Cache - API_update` | **PASS: 7/10, TIMEOUT: 3/10** | `Test timed out` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4987/html/browsers/offline/application-cache-api/api_update_error.html">/html/browsers/offline/application-cache-api/api_update_error.html</a></summary>


|            Subtest             | Results |     Messages     |
|--------------------------------|---------|------------------|
|                                | TIMEOUT |                  |
| `INVALID_STATE_ERR error test` | TIMEOUT | `Test timed out` |

</details>
</details>

**Comment by jugglinmike** [comment]
The initial version of this branch included a commit that introduced two test
timeouts. One was written to occur consistently, and the other was written to
only occur based on a non-deterministic condition. The stability script
correctly reported the test results for both cases. The relevant logs for those
builds are available on TravisCI here:

https://travis-ci.org/w3c/web-platform-tests/builds/204327829

Here is a screen capture of the resulting comments on GitHub.com:

17 02 22-4985-stability-timeout

I have since removed the debugging commit so that this branch may be merged
directly (and the comment has subsequently updated to report the lack of
changed test files).

**Pull request merged**
