### PR TITLE
Test Depth Stream with MediaStream interface

### PR DESCRIPTION
**Pull request by xiuqijix**
Reuse tests from https://github.com/w3c/web-platform-tests/blob/master/mediacapture-streams/
 to test Depth Stream with some optimizations:
  - Move proper tests into one file to reduce testing effort
  - Rewrite most tests with `promise_test`

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-09-25 02:33:07
Finished: 2017-09-25 02:38:25


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18796)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/279357742)

**Comment by foolip** [comment]
@kaixinjxq, can you add an OWNERS file given that this is a new directory? Add whoever you think would be a good review and see if they complain :)

**Comment by kaixinjxq** [comment]
This PR is blocked on the required "Travis CI - Pull Request" check after #14499. In order to trigger it, I will close and reopen this PR.

**Comment by anssiko** [comment]
We [retired](https://lists.w3.org/Archives/Public/public-webrtc/2022Feb/0001.html) this spec and deprecated the implementation. Anyway, thanks for this contribution!

**Pull request closed without merging**
