### PR TITLE
Remove origin policy testing infrastructure

### LINKED ISSUE #34707: Remove Origin Policy infrastructure
Per https://github.com/web-platform-tests/rfcs/pull/113

### PR DESCRIPTION
**Pull request by domenic**
Closes #34707.

### CODE REVIEW

**Comment by foolip** [comment]
@domenic can you check if the failure in https://community-tc.services.mozilla.com/tasks/d9IN_UANTrG29Eav08BPaA/runs/0/logs/public/logs/live.log is plausible caused by the changes?

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I pushed https://github.com/web-platform-tests/wpt/pull/28759 and the infrastructure/ tests are passing there. I'll try rebasing onto the exact same commit (4e1dddf5a4bbd613747f04af48d9f150ff0a1df6) to see if it still fails here.

**Comment by foolip** [comment]
The errors looks a lot like the cert is broken and the tests don't load at all. @domenic how did you update the certs here?

**Comment by domenic** [comment]
I followed the instructions in https://github.com/web-platform-tests/wpt/blob/master/tools/certs/README.md#regenerating-the-pregenerated-certificates on my Windows Subsystem for Linux. Hmm.... I'll try again, I guess?

**Comment by domenic** [comment]
Alright, well, I regenerated the certs on real-Linux and that doesn't seem to have worked. That's all I can do at this point; turning this over to others.

**Comment by foolip** [comment]
Looks like CI passes now, is this good to go then?

**Pull request merged**
