### PR TITLE
[css-ui] Remove incorrect stray flag

### PR DESCRIPTION
**Pull request by frivoal**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 17:29:58
Finished: 2017-08-18 17:38:16



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17562)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266056307)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 17:29:58
Finished: 2017-08-18 17:38:16



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17562)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266056307)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 17:29:58
Finished: 2017-08-18 17:38:16



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17562)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266056307)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 17:29:58
Finished: 2017-08-18 17:38:16



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17562)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266056307)

**Review by sideshowbarker — APPROVED** [review]
OK

**Pull request merged**
