### PR TITLE
Web NFC: Align Web IDL tests to latest spec

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240205488)

# Firefox (nightly) #
Testing web-platform-tests at revision 6f8a03728a62113e9700cf1225b67acb0375296e
Using browser at version BuildID 20170606100219; SourceStamp 58ce95bc58ce4ba200413c8bed87786dccf3d105
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6173/web-nfc/idlharness.https.html">/web-nfc/idlharness.https.html</a></summary>


|                                                           Subtest                                                            | Results |                                           Messages                                           |
|------------------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------|
|                                                                                                                              | OK      |                                                                                              |
| `Navigator interface: attribute nfc`                                                                                         | FAIL    | `assert_true: The prototype object must have a property "nfc" expected true got false`       |
| `NFC interface: existence and properties of interface object`                                                                | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface object length`                                                                                                | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface object name`                                                                                                  | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: existence and properties of interface prototype object`                                                      | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: existence and properties of interface prototype object's "constructor" property`                             | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation push(NFCPushMessage,NFCPushOptions)`                                                               | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation cancelPush(NFCPushTarget)`                                                                         | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation watch(MessageCallback,NFCWatchOptions)`                                                            | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation cancelWatch(long)`                                                                                 | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: navigator.nfc must inherit property "push" with the proper type (0)`                                         | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling push(NFCPushMessage,NFCPushOptions) on navigator.nfc with too few arguments must throw TypeError`    | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "cancelPush" with the proper type (1)`                                   | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling cancelPush(NFCPushTarget) on navigator.nfc with too few arguments must throw TypeError`              | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "watch" with the proper type (2)`                                        | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling watch(MessageCallback,NFCWatchOptions) on navigator.nfc with too few arguments must throw TypeError` | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "cancelWatch" with the proper type (3)`                                  | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling cancelWatch(long) on navigator.nfc with too few arguments must throw TypeError`                      | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240205489)

# Sauce (safari) #
Testing web-platform-tests at revision 6f8a03728a62113e9700cf1225b67acb0375296e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6173/web-nfc/idlharness.https.html">/web-nfc/idlharness.https.html</a></summary>


|                                                           Subtest                                                            | Results |                                           Messages                                           |
|------------------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------|
|                                                                                                                              | OK      |                                                                                              |
| `Navigator interface: attribute nfc`                                                                                         | FAIL    | `assert_true: The prototype object must have a property "nfc" expected true got false`       |
| `NFC interface: existence and properties of interface object`                                                                | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface object length`                                                                                                | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface object name`                                                                                                  | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: existence and properties of interface prototype object`                                                      | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: existence and properties of interface prototype object's "constructor" property`                             | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation push(NFCPushMessage,NFCPushOptions)`                                                               | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation cancelPush(NFCPushTarget)`                                                                         | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation watch(MessageCallback,NFCWatchOptions)`                                                            | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: operation cancelWatch(long)`                                                                                 | FAIL    | `assert_own_property: self does not have own property "NFC" expected property "NFC" missing` |
| `NFC interface: navigator.nfc must inherit property "push" with the proper type (0)`                                         | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling push(NFCPushMessage,NFCPushOptions) on navigator.nfc with too few arguments must throw TypeError`    | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "cancelPush" with the proper type (1)`                                   | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling cancelPush(NFCPushTarget) on navigator.nfc with too few arguments must throw TypeError`              | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "watch" with the proper type (2)`                                        | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling watch(MessageCallback,NFCWatchOptions) on navigator.nfc with too few arguments must throw TypeError` | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: navigator.nfc must inherit property "cancelWatch" with the proper type (3)`                                  | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |
| `NFC interface: calling cancelWatch(long) on navigator.nfc with too few arguments must throw TypeError`                      | FAIL    | `assert_equals: wrong typeof object expected "object" but got "undefined"`                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240205495)

# Chrome (unstable) #
Testing web-platform-tests at revision 6f8a03728a62113e9700cf1225b67acb0375296e

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240205496)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 6f8a03728a62113e9700cf1225b67acb0375296e

**Comment by Honry** [comment]
@kenchris or @zolkis, could you PTAL?

**Review by zolkis — APPROVED** [review]
Looks good. Thanks!

**Comment by Honry** [comment]
@tobie, could you also approve this one?

**Comment by tobie** [comment]
Oh, sorry, I thought you wanted a review. Hadn't realized @zolkis had already reviewed and approved it.

**Review by tobie — APPROVED** [review]
Rubber-stamping @zolkis's review.

**Comment by Honry** [comment]
Thanks @tobie, I will merge it directly.

**Pull request merged**
