### PR TITLE
Add tests for the removal of <button type=menu>

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/html/pull/2342

I am told Firefox on Mac OS will fail the reftest per https://github.com/whatwg/html/issues/237#issuecomment-275724486

### CODE REVIEW

**Comment by domenic** [comment]
@jgraham not sure why bots are not happy. Maybe because I modified interfaces.html and that makes the log too long?

**Comment by Ms2ger** [comment]
Yeah. Feel free to ping me or James when this is ready to land.

**Review by zcorpan — APPROVED** [review]

**Comment by domenic** [comment]
@Ms2ger this is ready to land.

**Comment by zcorpan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1338166

**Pull request merged**
