### PR TITLE
Tests for caching of PATCH and POST responses

### PR DESCRIPTION
**Pull request by zbjornson**
This doesn't appear to be implemented by any browser, but is permitted by the spec.

### CODE REVIEW

**Review by mnot — CHANGES_REQUESTED** [review]
edit - sorry, I forgot that it defaulted to GET in the subsequent requests. I think this is fine.

**Review by mnot — CHANGES_REQUESTED** [review]
Content-Location needs to have a value that's equivalent to the request-URI

**Comment by zbjornson** [comment]
Both of those are already the case. Here's what the network requests look like for the first test:

```
// First request:
200 OK PATCH      http://localhost:8000/fetch/http-cache/resources/http-cache.py?token=7245d2ca-0572-47bf-9fa8-06bfcc17b223&info=W3sicmVxdWVzdF9tZXRob2QiOiJQQVRDSCIsInJlcXVlc3RfYm9keSI6ImFiYyIsInJlc3BvbnNlX3N0YXR1cyI6WzIwMCwiT0siXSwicmVzcG9uc2VfaGVhZGVycyI6W1siQ2FjaGUtQ29udHJvbCIsInByaXZhdGUsIG1heC1hZ2U9MTAwMCJdLFsiQ29udGVudC1Mb2NhdGlvbiIsIiJdXSwicmVzcG9uc2VfYm9keSI6ImFiYyJ9LHsiZXhwZWN0ZWRfdHlwZSI6ImNhY2hlZCJ9XQ==
Content-Location: http://localhost:8000/fetch/http-cache/resources/http-cache.py?token=7245d2ca-0572-47bf-9fa8-06bfcc17b223&info=W3sicmVxdWVzdF9tZXRob2QiOiJQQVRDSCIsInJlcXVlc3RfYm9keSI6ImFiYyIsInJlc3BvbnNlX3N0YXR1cyI6WzIwMCwiT0siXSwicmVzcG9uc2VfaGVhZGVycyI6W1siQ2FjaGUtQ29udHJvbCIsInByaXZhdGUsIG1heC1hZ2U9MTAwMCJdLFsiQ29udGVudC1Mb2NhdGlvbiIsIiJdXSwicmVzcG9uc2VfYm9keSI6ImFiYyJ9LHsiZXhwZWN0ZWRfdHlwZSI6ImNhY2hlZCJ9XQ==

// 2nd request
GET 200 OK        http://localhost:8000/fetch/http-cache/resources/http-cache.py?token=7245d2ca-0572-47bf-9fa8-06bfcc17b223&info=W3sicmVxdWVzdF9tZXRob2QiOiJQQVRDSCIsInJlcXVlc3RfYm9keSI6ImFiYyIsInJlc3BvbnNlX3N0YXR1cyI6WzIwMCwiT0siXSwicmVzcG9uc2VfaGVhZGVycyI6W1siQ2FjaGUtQ29udHJvbCIsInByaXZhdGUsIG1heC1hZ2U9MTAwMCJdLFsiQ29udGVudC1Mb2NhdGlvbiIsIiJdXSwicmVzcG9uc2VfYm9keSI6ImFiYyJ9LHsiZXhwZWN0ZWRfdHlwZSI6ImNhY2hlZCJ9XQ==
```

**Comment by mnot** [comment]
Ah, missed that, sorry (jet lag :).

LGTM.

**Review by mnot — APPROVED** [review]

**Comment by gsnedders** [comment]
Is there any reason this hasn't landed? Well, except for the fact it now has merged conflicts, but with them resolved, is there any reason it can't land? :)

**Comment by zbjornson** [comment]
Merge conflicts fixed, rebased on master. I think it can land... :)

**Comment by zbjornson** [comment]
Is there anything else needed for this to land?

**Pull request merged**
