### PR TITLE
Remove some odd old files

### PR DESCRIPTION
**Pull request by foolip**
scopedname.widl~ is from commit 4f2bd89c86d106fcf39fbc96ad401108157ade65
and looks like a backup file accidentally committed.

.ttwf-reftest-tutorial-starter-ref.html.swp is from commit
28f39052cf48124442ebe5dca0c4172bb2f33b9d and is something similar.

.hgignore and .hgtags files are leftovers from mercurial.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-09-10 21:23:45
Finished: 2017-09-10 21:37:23





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18360)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/273951464)

**Review by tobie — APPROVED** [review]
LGTM on the WebIDL side of things.

**Comment by gsnedders** [comment]
We should probably not change the `tools/` stuff; they're just imported git repositories (using `git subtree`) and the git repositories include those files. Will make updating them painful, given potential delete/modified conflicts.

**Comment by foolip** [comment]
@gsnedders, https://github.com/w3c/wpt-tools suggests that we'll not be using the separate repo any more, I presume `git subtree` was just used to merge it in because it's easy to get the rename bit right that way.

**Review by jgraham — DISMISSED** [review]
@gsnedders is right (sorry ;) We don't want to change things in things that we don't own like py and six, so we can update those easily in the future.

**Comment by foolip** [comment]
That's fine and I will back those changes out. It's not easy to tell this from the state of the repo, but tools/py/README.txt is a good clue if one reads it.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
