### PR TITLE
Update 2d.pattern.image.broken

### PR DESCRIPTION
**Pull request by guest271314**

### CODE REVIEW

**Comment by guest271314** [comment]
Firefox 72 and Nightly 74 do not throw an exception for the same code. Instead `null` is the result of `createPattern()` when the image source `width` and `height` is `0`.

**Comment by annevk** [comment]
This PR is modifying a generated file.

**Comment by guest271314** [comment]
Ok.

What is the issue with substituting a hand-written file for a generated file where the generated file does not perform the intended task?

Further, by modifying the generated file found that Firefox does not throw as the specification states should occur in that case.

If there are special concerns to be considered when modifying a generated file at WPT can you kindly list them in one place officially so that such documentation can be referenced?

**Comment by jdm** [comment]
We covered this previously in https://github.com/web-platform-tests/wpt/pull/19818#pullrequestreview-333702057. The file is currently automatically generated by a python script, and it is acceptable to remove that generation if the generated file is not useful.

**Comment by guest271314** [comment]
One least intrusive modification that can present for review right now is to substitute `"data:,"` for `"/images/broken.png"` at ``.

**Comment by guest271314** [comment]
Can the Python script be adjusted to perform the above proposed substitution without removing the file? The original image file used is not "Broken" enough per the specification (for Chrome, Chromium). Firefox needs to fix either `canvas` or `DOM` or both implementations for an exception to be thrown.

**Comment by guest271314** [comment]
Also, the error name is `"InvalidStateError"` not `"INVALID_STATE_ERR"`, unless there is a map of various error names that are also generated which reflects `"INVALID_STATE_ERR"` as  `"InvalidStateError"`?

**Comment by jdm** [comment]
https://github.com/web-platform-tests/wpt/blob/79cedaf762e2eeeecc0d583746ad08a26da4d308/2dcontext/tools/tests2d.yaml#L2899-L2906

Theoretically it could instead be
```
var img = new Image();
img.src = "data:,";
```

**Comment by guest271314** [comment]
Ok. 

Should the error name be changed or is `INVALID_STATE_ERR` mapped to `InvalidStateError` in another location?

**Comment by guest271314** [comment]
```
- name: 2d.pattern.image.broken
  testing:
    - 2d.pattern.incomplete.image
  code: |
    var img = new Image();
    img.src = "data:,";
    @assert throws IInvalidStateError ctx.createPattern(img, 'repeat');
```
?

**Comment by jdm** [comment]
The INVALID_STATE_ERR is recognized by a regex in [this code](https://github.com/web-platform-tests/wpt/blob/master/2dcontext/tools/gentestutils.py#L231-L233), but also it's a string that is part of the web platform: https://heycam.github.io/webidl/#idl-DOMException

**Comment by guest271314** [comment]
Will the change to the `yaml` file (https://github.com/web-platform-tests/wpt/pull/21686#issuecomment-584217991), excluding the change to exception name, suffice?

**Comment by annevk** [comment]
You also need to run the script to generate the generated files (or get someone to do it for you).

**Comment by guest271314** [comment]
Ok.

Am not exactly following how the error `InvalidStateError` which Chromium has set as the `name` gets converted to `INVALID_STATE_ERR`.

Should this PR be closed in lieu of editing the `yaml` file?

**Comment by jdm** [comment]
No need to close the PR. You can reset the branch to master, make the change, and force push the new commit.

**Comment by guest271314** [comment]
@annevk @jdm Updated

**Comment by guest271314** [comment]
However the "generated test" does not throw at Chromium. Why?

**Comment by guest271314** [comment]
@annevk 

> You also need to run the script to generate the generated files (or get someone to do it for you).

How to do that step now? To make sure the generated test does throw an error?

**Pull request closed without merging**
