### PR TITLE
CSS color-contrast() tests are testing the version of color-contrast() remove from the spec

### PR DESCRIPTION
**Pull request by weinig**
https://github.com/web-platform-tests/wpt/issues/46640

Removes tests for color-contrast() that use a syntax no longer in the spec.

### CODE REVIEW

**Comment by dbaron** [comment]
What these tests are testing clearly isn't a valid *syntax* any longer after (at least) the changes in https://github.com/w3c/csswg-drafts/commit/36594e9e8496a5ca83f1f1ee2b4a83bcdf28753b and https://github.com/w3c/csswg-drafts/commit/57fe5008cdf6c9f977e0df859b90566152f4fdb1 .  But it's not completely clear to me that the semantics underlying that syntax are no longer present in the spec... or whether the tests should instead be updated to a new (still yet TBD!) syntax.

**Comment by dbaron** [comment]
(Though what they're testing is certainly no longer [part of css-color-5](https://drafts.csswg.org/css-color-5/#contrast-color).)

**Comment by weinig** [comment]
Oh, heh, I didn't realize there was already a css-color 6!

**Comment by weinig** [comment]
Though, given CSS Color 6 seems to be marked "not ready for implementation", I still think removing these for now makes sense.

(To be clear, I authored most of them, and when css color 6 is ready, I will happily bring them back and update them).

**Comment by dbaron** [comment]
OK, just adding @LeaVerou so she's aware as well.

**Review by dbaron — APPROVED** [review]

**Pull request merged**
