### PR TITLE
HighlightRegister was renamed to HighlightRegistry

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Review by nt1m — APPROVED** [review]

**Review by megangardner — APPROVED** [review]

**Comment by WeizhongX** [comment]
This PR added a new test (css/css-highlight-api/historical.window.js) and it triggered a lint error, and consequently blocks chromium's importer.

The error message:
`wpt lint` failed:
ERROR:lint:css/css-highlight-api/historical.window.js: Testcase file must have a link to a spec (MISSING-LINK)
INFO:lint:
INFO:lint:There was 1 error (MISSING-LINK: 1)
INFO:lint:You must fix all errors; for details on how to fix them, see
INFO:lint:https://web-platform-tests.org/writing-tests/lint-tool.html

Looks like the spec linked is "// https://drafts.csswg.org/css-highlight-api-1/". If the spec is a draft, should we rename this test to tentative?

However I do not know why there is no lint error in css/css-highlight-api/idlharness.window.js

**Comment by annevk** [comment]
The other tests are not tentative either. You'd either have to mark all of css-highlight-api as tentative or none of it.

**Comment by WeizhongX** [comment]
Thanks for the prompt response, and I see there had been a discussion in matrix.

In that case, we will just ignore the lint error in chromium.

**Comment by nt1m** [comment]
I opened https://github.com/web-platform-tests/wpt/pull/44655 to fix the lint error

**Pull request merged**
