### PR TITLE
Use IDL harness tests for Screen Orientation API

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@marcoscaceres, this PR replaces the old API tests with IDL harness tests, PTAL.

**Review by marcoscaceres — APPROVED** [review]
Looks good. Thanks for doing this!

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23069)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/331635383)

**Comment by marcoscaceres** [comment]
@Honry, let me know if you need me to merge. Otherwise, please go ahead and merge.

**Comment by Honry** [comment]
@marcoscaceres, thanks for your quick response and review. I will merge it.

**Pull request merged**
