### PR TITLE
IndexedDB: Fix exception type expected for invalid transaction() mode

### PR DESCRIPTION
**Pull request by inexorabletash**

### CODE REVIEW

**Comment by inexorabletash** [comment]
For https://github.com/w3c/web-platform-tests/issues/5313

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218605810)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fc9152dc6c41ce6f53e2630392bac98c02474690
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5369/IndexedDB/idbdatabase-transaction-exception-order.html">/IndexedDB/idbdatabase-transaction-exception-order.html</a></summary>


|                                       Subtest                                       | Results | Messages |
|-------------------------------------------------------------------------------------|---------|----------|
|                                                                                     | OK      |          |
| `IDBDatabase.transaction exception order: InvalidStateError vs. NotFoundError`      | PASS    |          |
| `IDBDatabase.transaction exception order: InvalidStateError vs. InvalidAccessError` | PASS    |          |
| `IDBDatabase.transaction exception order: NotFoundError vs. TypeError`              | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218605811)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fc9152dc6c41ce6f53e2630392bac98c02474690
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5369/IndexedDB/idbdatabase-transaction-exception-order.html">/IndexedDB/idbdatabase-transaction-exception-order.html</a></summary>


|                                       Subtest                                       | Results | Messages |
|-------------------------------------------------------------------------------------|---------|----------|
|                                                                                     | OK      |          |
| `IDBDatabase.transaction exception order: InvalidStateError vs. NotFoundError`      | PASS    |          |
| `IDBDatabase.transaction exception order: InvalidStateError vs. InvalidAccessError` | PASS    |          |
| `IDBDatabase.transaction exception order: NotFoundError vs. TypeError`              | PASS    |          |

</details>
</details>

**Review by pwnall — APPROVED** [review]
LGTM

**Comment by pwnall** [comment]
FWIW, I verified that we already check the TypeError exception. We do that in IndexedDB/idbdatabase_transaction4.htm

**Pull request merged**
