### PR TITLE
Update Document-characterSet-normalization.html

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
https://github.com/w3c/web-platform-tests/issues/2453
- update encoding names (correct case) and labels
- stop using expected_case() and uncomment it
- add under the comment solution with Blob and URL.createObjectURL so, if necessary, can be test local with file: scheme
- not uncomment upper case, mixed case and white space but if you want then do this (654 tests jump to 2589 test)

### CODE REVIEW

**Comment by annevk** [comment]
This looks okay to me. @inexorabletash?

**Comment by inexorabletash** [comment]
If there's a reason to keep commented-out blocks of code it should be documented in the file itself ("can be test local with file: scheme" ?). We have version control for a reason. :) And personally I don't think it's that helpful - many tests fail with file: and the commented out code will quickly rot.

Otherwise, lgtm

**Comment by ArkadiuszMichalski** [comment]
@inexorabletash OK, I remove this comments, anything else?

**Comment by inexorabletash** [comment]
looks good to me, but I'm not a reviewer for this directory, so I don't want to hit the merge button. Anyone else?

**Comment by annevk** [comment]
Sure.

**Comment by annevk** [comment]
Thanks @ArkadiuszMichalski!

**Pull request merged**
