### PR TITLE
XMLHttpRequest: text/html sniffing is not used for text

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203787856)

# Firefox (nightly channel) #
Testing web-platform-tests at revision ccaa50080f99de159e6d96c707961a918789316c
Using browser at version BuildID 20170220215957; SourceStamp d0462b0948e0b1147dcce615bddcc46379bdadb2
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4935/XMLHttpRequest/responsetext-decoding.htm">/XMLHttpRequest/responsetext-decoding.htm</a></summary>


|                                                                   Subtest                                                                   | Results |
|---------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                             | OK      |
| `XMLHttpRequest: responseText decoding (application/xml %3C%3Fxml%20version%3D'1.0'%20encoding%3D'windows-1252'%3F%3E%3Cx%3E%FF%3C%2Fx%3E)` | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FF)`                                                                                    | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FE%FF)`                                                                                 | FAIL    |
| `XMLHttpRequest: responseText decoding (text/xml %3C%3Fxml%20version%3D'1.0'%20encoding%3D'windows-1252'%3F%3E%3Cx%3E%E3%81%B2%3C%2Fx%3E)`  | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain;charset=windows-1252 %FF)`                                                               | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %FE%FF%FE%FF)`                                                                             | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %C2)`                                                                                    | FAIL    |
| `XMLHttpRequest: responseText decoding (text/xml %EF%BB%BF)`                                                                                | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %EF%BB%BF)`                                                                              | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FE%FF%FE%FF)`                                                                           | FAIL    |
| `XMLHttpRequest: responseText decoding (text/xml %EF%BB%BF%EF%BB%BF)`                                                                       | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %FE%FF)`                                                                                   | PASS    |
| `XMLHttpRequest: responseText decoding (text/html %3C!doctype%20html%3E%3Cmeta%20charset%3Dwindows-1252%3E%FF)`                             | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %E3%81%B2)`                                                                              | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %EF%BB%BF%EF%BB%BF)`                                                                     | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/203787857)

# Chrome (unstable channel) #
Testing web-platform-tests at revision ccaa50080f99de159e6d96c707961a918789316c
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4935/XMLHttpRequest/responsetext-decoding.htm">/XMLHttpRequest/responsetext-decoding.htm</a></summary>


|                                                                   Subtest                                                                   | Results |
|---------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                             | OK      |
| `XMLHttpRequest: responseText decoding (application/xml %3C%3Fxml%20version%3D'1.0'%20encoding%3D'windows-1252'%3F%3E%3Cx%3E%FF%3C%2Fx%3E)` | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FF)`                                                                                    | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FE%FF)`                                                                                 | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %3C%3Fxml%20version%3D'1.0'%20encoding%3D'windows-1252'%3F%3E%3Cx%3E%E3%81%B2%3C%2Fx%3E)`  | FAIL    |
| `XMLHttpRequest: responseText decoding (text/plain;charset=windows-1252 %FF)`                                                               | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %FE%FF%FE%FF)`                                                                             | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %C2)`                                                                                    | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %EF%BB%BF)`                                                                                | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %EF%BB%BF)`                                                                              | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %FE%FF%FE%FF)`                                                                           | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %EF%BB%BF%EF%BB%BF)`                                                                       | PASS    |
| `XMLHttpRequest: responseText decoding (text/xml %FE%FF)`                                                                                   | PASS    |
| `XMLHttpRequest: responseText decoding (text/html %3C!doctype%20html%3E%3Cmeta%20charset%3Dwindows-1252%3E%FF)`                             | FAIL    |
| `XMLHttpRequest: responseText decoding (text/plain %E3%81%B2)`                                                                              | PASS    |
| `XMLHttpRequest: responseText decoding (text/plain %EF%BB%BF%EF%BB%BF)`                                                                     | PASS    |

</details>
</details>

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1341260.

**Comment by annevk** [comment]
Should also file a bug against WebKit/Chromium once this is reviewed I suppose.

**Comment by annevk** [comment]
Bugs filed:

* https://bugs.webkit.org/show_bug.cgi?id=168724
* https://bugs.chromium.org/p/chromium/issues/detail?id=695045

**Pull request merged**
