### PR TITLE
expand tests to test in reverse direction

### PR DESCRIPTION
**Pull request by kritisingh1**
Reference to issue #2314. 
The tests can now test in the opposite direction too as suggested by @Ms2ger . 
However, there is a minor fix required regarding the duplicacy of handlers. Please review and suggest any changes required. Thanks :)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26426)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/358007984)

**Review by Ms2ger — COMMENTED** [review]
Now that I look at the test, it might be better to copy the test file and make the changes there; that would prevent any interaction between the tests.

**Comment by kritisingh1** [comment]
@Ms2ger I have updated and the tests seem to pass normally. Please have a look. Thanks :)

**Review by Ms2ger — CHANGES_REQUESTED** [review]
Looks good, but could you also add the part where the attributes are set to null / checked to be null?

**Review by Ms2ger — APPROVED** [review]
Thanks!

**Pull request merged**
