### PR TITLE
Tests for dir attribute isolation

### PR DESCRIPTION
**Pull request by r12a**

### CODE REVIEW

**Comment by r12a** [comment]
For results of these tests on major browsers see http://www.w3.org/International/tests/repo/results/the-dir-attribute-isolation

**Comment by zcorpan** [comment]
See comments in critic

**Comment by kojiishi** [comment]
@r12a, did you address all review comments but forgot to press "Resolve Issue" button in critic? I'm not familiar with critic, but it looks like two issues are still open.

**Comment by kojiishi** [comment]
Played with Critic for a while without figuring out how to start review, maybe I'm not allowed to review?

Anyway, I loaded the patch locally and reviewed, here's my results:

1. ref files do not have "Test passes if the two boxes are identical." text that they do not match.
2. By adding `<p class="instructions" dir="ltr">Test passes if the two boxes are identical.</p>` to every ref file, all tests in this PR pass for Blink with [my WIP patch](https://codereview.chromium.org/1463473002/) applied.

@r12a, could you please fix them? With that fix, this PR looks good to me.

**Comment by zcorpan** [comment]
@kojiishi you first have to add yourself as a reviewer with the "Add Reviewer" button. I've added you.

**Comment by kojiishi** [comment]
@zcorpan, I reviewed them, and the commits above are the result of @r12a and my work offline.

Now `resources` and `tools` submodules seem to conflict, Richard seems to have made something, but we could not figure out how to reset that. Should we discard this PR and create another? Richard is asking some people how to solve that, but if you happen to know, that'd be appreciated.

**Comment by zcorpan** [comment]
@jgraham ^

**Comment by r12a** [comment]
because some spurious files have crept into this pull request and i don't know how to remove them, i am closing the PR and will resubmit the files in a new PR.

**Comment by jgraham** [comment]
Oh, sorry, I missed this. It should have been enough to checkout the upstream versions of those directories like `git checkout origin/master tools resources` (or whatever your upstream is called) and then commit the change.

**Pull request closed without merging**
