### PR TITLE
FetchEvent.prototype.isReload is no longer part of the specification

### PR DESCRIPTION
**Pull request by cdumez**
Drop it from interfaces-worker.sub.js.

### CODE REVIEW

**Comment by cdumez** [comment]
cc @beidson

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21772)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/315466252)

**Comment by jdm** [comment]
Could we add a test that it does not exist? We do this for other legacy parts of specifications.

**Review by jdm — APPROVED** [review]

**Comment by wanderview** [comment]
FYI there are existing SW spec issues about this open.  It was removed from the spec but not removed from implementations because there are not good alternatives yet.  We are trying to define a replacement in w3c/ServiceWorker#1167.  We had tentatively agreed in F2F meetings to leave this in WPT until the new spec feature was defined.

**Comment by cdumez** [comment]
My understanding is that WPT is supposed to match the spec, not browsers. If browsers do not match the spec, then this is an issue with the spec.

**Comment by wanderview** [comment]
Sure, but if you see the WPT passes in every shipping implementation, but doesn't match the spec, maybe it would be worth filing a spec issue.

Same reason I haven't written a WPT checking that `document.open()` creates a new window.  Currently firefox and the spec agree, but no other implementation does it.  We have a spec issue open instead.

**Comment by wanderview** [comment]
And I'll just note I'm not really upset.  It sucks that spec stuff was changed without implementation happening.  I've been encouraging folks to either put the spec back or actually make the change.  I've also tried to give warning about known stuff like this to edge/webkit implementation folks.

**Comment by cdumez** [comment]
In this case though, it *was* in an earlier version of the spec and was dropped in a more recent version of the spec. Therefore, my understanding was that the test was outdated and thus did not file an issue with the spec.

**Pull request merged**
