### PR TITLE
Replace os.path.split with .dirname or .basename where appropriate

### PR DESCRIPTION
**Pull request by foolip**
Most of the changes made by:

> git grep -lF os.path.split | xargs sed -i '' 's/os\.path\.split(\(.*\))\[0\]/os.path.dirname(\1)/g'

That gets some things wrong, so all changes were vetted and some fixed
or simplified.

### CODE REVIEW

**Comment by foolip** [comment]
I believe that https://github.com/web-platform-tests/wpt/pull/25008/checks?check_run_id=984077316 can be ignored, these tests even say "Note: this test will only work as expected once per browsing session. Restart browser to re-test".

@stephenmcgruer @jgraham I've seen this kind of stability failure many times, but this is the first time I've spotted it documented in the tests. Should we have some way of marking such tests as needing restart to avoid these failures?

**Review by Hexcles — COMMENTED** [review]
Maybe we shouldn't touch `tools/third_party`?

**Comment by foolip** [comment]
> Maybe we shouldn't touch `tools/third_party`?

Oops, I wasn't paying attention to where the changes were.

**Comment by foolip** [comment]
I've sent most of the tools/third_party changes in https://github.com/html5lib/html5lib-python/pull/508 + https://github.com/GoogleChromeLabs/pywebsocket3/pull/11 and reverted them here.

**Review by Hexcles — APPROVED** [review]
Looks safe to me

**Comment by foolip** [comment]
Looking for regressions from this, it seems OK:
https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%29&run_id=657990001&run_id=661940001
https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%29&run_id=633480001&run_id=657990002

@stephenmcgruer this is fewer failures due to flakiness than I remember typically seeing. Might that mean it's more feasible to label the remaining flakiness and make it possible to search excluding flaky tests?

**Comment by stephenmcgruer** [comment]
@foolip I think you more want `is:different` rather than `seq(status:pass status:!pass)` if you're trying to look for all flake:

https://wpt.fyi/results/?diff&filter=ADC&q=is%3Adifferent&run_id=657990001&run_id=661940001
https://wpt.fyi/results/?diff&filter=ADC&q=is%3Adifferent&run_id=633480001&run_id=657990002

Its still not huge (25 vs 50 subtests for Chrome, 10 vs 46 for Firefox), albeit this is only across two runs, but if we're saying flake is rare then it almost feels like a disincentive to add infrastructure around it rather than a reason to do it?

**Comment by foolip** [comment]
I was looking for regressions and flakes were getting in the way. Filtering to just PASS&rarr;!PASS gets rid of the flakes that can't be regressions at least :)

**Pull request merged**
