### PR TITLE
Added more Request.destination tests

### LINKED ISSUE #8810: Test values of `Request.destination`
There are multiple tests that check if `Request.destination` is exposed, but none I could find that check if the returned value is the right one (other than https://github.com/w3c/web-platform-tests/blob/master/preload/fetch-destination.https.html which tests the destination value for `<link rel=preload as=fetch>`.

We need more tests to make sure the values returned by the different engines are compatible with the spec and with each other.

### PR DESCRIPTION
**Pull request by yoavweiss**
Partially resolves #8810 

This adds tests for `<link rel=preload>` for all `as` values, SVGImageElement, img with srcset and `<picture>`, XHR, and EventSource.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22398)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/325236981)

**Comment by yoavweiss** [comment]
Added tests also for background images, fonts, sendBeacon, importScripts, and CSS import.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22420)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/325393343)

**Comment by yoavweiss** [comment]
Also added a test for `Cache.add()`.

**Review by wanderview — APPROVED** [review]
Thanks!

**Pull request merged**
