### PR TITLE
test incremental updates with updateWith()

### LINKED ISSUE #9119: PaymentRequestUpdateEvent.updateWith() insufficiently tested
The tests currently lack checks for incremental data updates, without trashing the data the `request` holds. Missing: 

- [x] if only the total is passed.
- [x] If the displayItems member of details is present
- [x] If the shippingOptions member of details is present
- [x] If the modifiers member of details is present

And combinations of the above.

### PR DESCRIPTION
**Pull request by marcoscaceres**
* closes #9119

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@MSFTkihans once these merge, it would be great if you can confirm if they work in Edge. 

@rsolomakhin, these are all fail in Chrome unfortunately.

**Comment by marcoscaceres** [comment]
@mnoorenberghe, unfortunately, it doesn't seem we have enough UI yet in Firefox Nightly to check these... close tho :)

**Comment by marcoscaceres** [comment]
@edenchuang, you might want to just double check in Gecko if these would work as expected nevertheless.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-04-16 11:38:14
Finished: 2018-04-16 11:44:26





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/27440)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/367111369)

**Review by rsolomakhin — APPROVED** [review]
> These are all fail in Chrome unfortunately.

No worries! Will fix in Chrome.

**Comment by marcoscaceres** [comment]
Ok, so, @MSFTkihans, just checked in Edge, and it passes all except the last test with the modifier: neither the new display item is shown, nor is the total updated.

**Comment by marcoscaceres** [comment]
Linked from spec.

**Comment by marcoscaceres** [comment]
@MSFTkihns this one: https://github.com/w3c/web-platform-tests/blob/master/payment-request/PaymentRequestUpdateEvent/updateWith-incremental-update-manual.https.html#L159

**Pull request merged**
