### PR TITLE
Add a lint rule for /> syntax on non-void HTML elements

### PR DESCRIPTION
**Pull request by zcorpan**
See #40473

### CODE REVIEW

**Comment by zcorpan** [comment]
How do I run the lint tests locally?

**Comment by foolip** [comment]
@zcorpan running `tox` in tools/ will probably run those tests. Then you probably have to read the source to figure out how to narrow it down to just run the tests you want.

**Comment by zcorpan** [comment]
I needed to run `flake8 -v --append-config=/Users/simonpieters/git/web-platform-tests/wpt/tools/flake8.ini` (with `-v`) to see what caused the failure.

> ./lint/rules.py:508:142: E501 line too long (542 > 141 characters)

Now fixed. Also removed `wbr` from the regexp since it's a void element.

**Review by foolip — APPROVED** [review]
Changes look good. Should be possible to write a test for this by copying other lint rule tests, but I'll leave it to you to judge if that's worthwhile or not.

**Comment by zcorpan** [comment]
Done, and confirmed that it works locally with:
```
pytest --cov=tools --cov-report=term
```
Changing the test to expect no errors makes it fail.

**Review by foolip — APPROVED** [review]

**Pull request merged**
