### PR TITLE
Added 8 inactive-selection-* tests and 4 support files [css-pseudo]

### PR DESCRIPTION
**Pull request by TalbotG**
Added 8 inactive-selection-* tests and 4 support files [css-pseudo]

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
So, I think the spec has an error here. Based on the behavior I'm observing in Firefox and Chrome, ::selection applies to inactive selections as well. I think we need to spec that correctly: that ::selection continues to apply, and ::inactive-selection overrides it.

And these these tests, because they are so manual, will need to incorporate multiple aspects of the interaction between ::selection and ::inactive-selection so that we minimize the number of manual tests necessary for this feature.

Specifically, I think the changes that are needed are:

* Swap the order of declarations so that ::selection comes after ::inactive-selection so we can verify the cascade.
* Add a `background: <color>` declaration to ::selection in addition to `color`.
* Alternate the tests between having background or color on ::inactive-selection. Having a declaration on both lets us test which one "wins". Having a declaration only on ::selection lets us verify that ::selection is also matching while ::inactive-selection is matching. Alternating between the two means we effectively test these qualities on both 'background' and 'color' without doubling the number of manual tests.

I'll file an issue on the spec and get it verified by the CSSWG. Maybe let's put a hold on this PR until the CSSWG can resolve on it. [Done: https://github.com/w3c/csswg-drafts/issues/4579 ]

Lastly, I suggest using the text “Select This Text” instead of “Sample Text”, since it's a little more helpful to the tester. :)

**Comment by TalbotG** [comment]
> changes that are needed are:
> 
> * Swap the order of declarations so that ::selection comes after ::inactive-selection so we can verify the cascade.

Done in the following list of 16 tests.

> * Add a `background: <color>` declaration to ::selection in addition to `color`.
> 

Done in the following list of 16 tests.

> * Alternate the tests between having background or color on ::inactive-selection. Having a declaration on both lets us test which one "wins". Having a declaration only on ::selection lets us verify that ::selection is also matching while ::inactive-selection is matching. Alternating between the two means we effectively test these qualities on both 'background' and 'color' without doubling the number of manual tests.

I am confused by the paragraph above. Anyway... here's the list of 16 new tests:

**Ordinary `<div>`:**

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-001-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-002-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-003-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-004-manual-new.html

- - - - - -

**`<input>`:**

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-005-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-006-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-007-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-008-manual-new.html

- - - - - -

**`<textarea>`:**

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-009-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-010-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-011-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-012-manual-new.html

- - - - - -

**`<div contenteditable="true">`:**

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-013-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-014-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-015-manual-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-016-manual-new.html

> I suggest using the text “Select This Text” instead of “Sample Text”

Done in the above list of 16 tests.

**Comment by fantasai** [comment]
OK, so firstly, *don't work on these tests yet*. The issue is still unresolved by CSSWG! I'm leaving comments for later, once we figure out the technical issue.

> I am confused by the paragraph above.

Secondly it seems like you understood very well the concerns about testing the cascade. :)

Lastly, the tests seem correct overall, however they are a bit confusing to run. I suggest the following improvements:
- Start with blue text on a white background.
- End with green text on a lime background.
- Use red (foreground #f00 or background #f88) as the intermediate color that should be overwritten.

Whether the green or lime or red is set on ::selection or ::inactive-selection will vary by the test. But in all cases, the intermediate state (::selection) will include red and the final result will be all green. It makes it easier to see that the test passed or failed this way, because the coloring across the entire series is more consistent.

**Comment by TalbotG** [comment]
I will close this PR since [Issue 4719: [css-pseudo-4] Clarify when selections are inactive](https://github.com/w3c/csswg-drafts/issues/4719) has settled this question:
[::inactive-selection has been removed](https://www.w3.org/TR/css-pseudo-4/#changes) . 

The 8 tests and 4 reference files on my website will continue to be accessible though.

**Pull request closed without merging**
