### PR TITLE
Update Web IDL README

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
@Ms2ger it seems you modified these last in #16797 and @dontcallmedom added them originally. Do either of you know if these syntax tests are still in use somewhere? @plinss do you have any insight here?

(For context about the other change here, see https://github.com/heycam/webidl/issues/1016.)

**Comment by Ms2ger** [comment]
I have no idea whether the syntax tests are used.

**Review by Ms2ger — APPROVED** [review]

**Comment by dontcallmedom** [comment]
I have no idea if they're still being used anywhere; I've stopped maintaining widlproc, the WebIDL parser that originally had these tests.

**Comment by annevk** [comment]
Thanks!

@saschanaz @CYBAI does webidl2.js use these?

Perhaps I should remove these files...

**Comment by saschanaz** [comment]
webidl2.js has its own test files, so no.

**Review by foolip — APPROVED** [review]

**Pull request merged**
