### PR TITLE
Capturing event listeners should be called before non capturing ones

### PR DESCRIPTION
**Pull request by cdumez**
as per https://github.com/whatwg/dom/issues/685.

### CODE REVIEW

**Comment by cdumez** [comment]
cc @domenic @rniwa @annevk

**Comment by domenic** [comment]
@Zirro and/or @pmdartus may be able to review this from the perspective of jsdom, which has recently been re-doing its event model to follow the spec and run into similar test/spec mismatches.

**Review by annevk — APPROVED** [review]
Was this only tested here? I was hoping we'd have more coverage of this.

**Comment by annevk** [comment]
This helps https://github.com/whatwg/dom/issues/742.

**Pull request merged**
