### PR TITLE
Fix typo that made error event handler test unpassable

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410187)

# Firefox (nightly) #
Testing web-platform-tests at revision 139900a97a58a9ac9ee7dd8aea6cefc1e386bba5
Using browser at version BuildID 20170520182312; SourceStamp 8d60d0f825110cfb646ac31dc16dc011708bcf34
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6009/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-late.html">/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-late.html</a></summary>


|                                      Subtest                                       | Results | Messages |
|------------------------------------------------------------------------------------|---------|----------|
|                                                                                    | OK      |          |
| `Invalid uncompiled raw handlers should only be compiled when about to call them.` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410188)

# Sauce (safari) #
Testing web-platform-tests at revision 139900a97a58a9ac9ee7dd8aea6cefc1e386bba5
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6009/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-late.html">/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-late.html</a></summary>


|                                      Subtest                                       | Results |                         Messages                        |
|------------------------------------------------------------------------------------|---------|---------------------------------------------------------|
|                                                                                    | OK      |                                                         |
| `Invalid uncompiled raw handlers should only be compiled when about to call them.` | FAIL    | `assert_array_equals: lengths differ, expected 3 got 4` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410194)

# Chrome (unstable) #
Testing web-platform-tests at revision 139900a97a58a9ac9ee7dd8aea6cefc1e386bba5

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410195)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 139900a97a58a9ac9ee7dd8aea6cefc1e386bba5

**Review by jgraham — APPROVED** [review]

**Pull request merged**
