### PR TITLE
Update interfaces/longtasks.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/087652c/whatwg/idl/longtasks.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/545077302

### CODE REVIEW

**Comment by foolip** [comment]
Need to look into "FAIL message: Type DOMHighResTimeStamp not found" before this is merged...

**Comment by foolip** [comment]
Blocked on https://github.com/web-platform-tests/wpt/pull/17344.

**Comment by foolip** [comment]
Rebased, but the error remains, seems like there's a problem with `idl_test` that needs to be resolved. In short, adding 'hr-time' as a dependency isn't enough, the `typedef double DOMHighResTimeStamp` isn't picked up. Including 'hr-time' as a source fixes this, but that's not right, and it needs even more dependencies to make it work.

@lukebjerring I think the problem is that `add_dependency_idls` doesn't do anything with `typedef`s. Unconditionally including them would probably be fine, since they don't do anything unless used. I've taken a look at `add_dependency_idls` but can't quickly see where this should fit, can you take a look?

**Comment by lukebjerring** [comment]
Typedef issue attacked here:
https://github.com/web-platform-tests/wpt/pull/18006

**Pull request closed without merging**
