### PR TITLE
[eme] Rename all encrypted-media tests to use https

### LINKED ISSUE #4716: [eme] Update tests so that automated test runners run them as https
navigator.requestMediaKeySystemAccess() is supposed to only run on secure contexts [1]. w3c-test.org lets you run the tests as http or https, depending on how you connect to the server. However, automated test runners (e.g. the one in Chromium) by default run the tests as http.

It appears that one way to do this is to rename the tests to test.https.html.

[1] http://w3c.github.io/encrypted-media/#navigator-extension-requestmediakeysystemaccess

### PR DESCRIPTION
**Pull request by jrummell-chromium**
Fixes #4716. As the EME spec requires https, rename all the tests to .https.html so that
automated test runners will run them as https.

Replaces https://github.com/w3c/web-platform-tests/pull/4717 since I'm unable to rebase it.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-17 01:16:25
Finished: 2017-08-17 02:05:48



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17480)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265396438)

**Review by joeyparrish — APPROVED** [review]
LGTM

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-20 14:40:58
Finished: 2017-08-20 15:30:11


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

<li>chrome:unstable</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  
  
  
  
  
  
  
  
  
  <h3>Browser: "Chrome Unstable"<small></small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/17480.4">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/265396442">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  
  
  <tr>
    <td><code>/encrypted-media/drm-mp4-playback-temporary-expired.https.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>drm, temporary, mp4, expired license</code></td>
    <td>FAIL: 9<br />PASS: 1<br /></td>
    <td><code>assert_unreached: Playback should not start with expired license Reached unreachable code</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  </table>

**Comment by jrummell-chromium** [comment]
Looks like this was done (by JamesWCCheng) as https://github.com/w3c/web-platform-tests/commit/85f088f444f64584722c2c584023651e7dac81cd.

**Pull request closed without merging**
