### PR TITLE
[WebNN] Support MLOperandDataType to align with latest WebNN API Spec

### PR DESCRIPTION
**Pull request by BruceDai**
@fdwr @Honry This is PR is to update tests to address https://github.com/webmachinelearning/webnn/pull/464, PTAL, thanks.

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
Thank you Bruce.

**Review by Honry — APPROVED** [review]
LGTM, let's hold it until the spec change landed.

**Comment by fdwr** [comment]
> LGTM, let's hold it until the spec change landed.

https://github.com/webmachinelearning/webnn/pull/464 is merged now 🙂.

@BruceDai - what do you think of temporarily adding a duplicate key, in case you want to run WPT to run on both slightly older and newer versions? I recall you set up a local test machine, and I wouldn't want that to break.

`inputOperands.push(builder.input(input.name, {dataType: input.type, type: input.type, dimensions: input.shape}));`

**Comment by BruceDai** [comment]
> > LGTM, let's hold it until the spec change landed.
> 
> [webmachinelearning/webnn#464](https://github.com/webmachinelearning/webnn/pull/464) is merged now 🙂.
> 
> @BruceDai - what do you think of temporarily adding a duplicate key, in case you want to run WPT to run on both slightly older and newer versions? I recall you set up a local test machine, and I wouldn't want that to break. e.g.
> 
> `inputOperands.push(builder.input(input.name, {dataType: input.type, type: input.type, dimensions: input.shape}));`

Thanks @fdwr. Yes, I workaround these tests as same as your suggestion on my local WPT service.

I just rebased this pr, and also fixed style issue mentioned on https://chromium-review.googlesource.com/c/chromium/src/+/4997551, please take another look, thanks.

**Review by fdwr — APPROVED** [review]
👍

**Pull request merged**
