### PR TITLE
Update interfaces/html.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/d920ea7/ed/idl/html.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/720023372

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@foolip I was surprised to find that both Worker and SharedWorker are empty in the html/dom idlharness file; are they tested elsewhere?

```
      Worker: [],
      SharedWorker: [],
```

**Comment by foolip** [comment]
@stephenmcgruer I suspect the original expectations was that they'd be tested in workers/. That split was undone in https://github.com/web-platform-tests/wpt/pull/18690, and it looks like they weren't tested there, so it's just an oversight.

**Comment by foolip** [comment]
This introduced [new failures](https://wpt.fyi/results/secure-contexts/idlharness.any.html?diff&filter=ADC&run_id=614080002&run_id=591570003) because `isSecureContext` is added.

That is the only IDL defined by https://w3c.github.io/webappsec-secure-contexts/ so the end result should be to remove those tests. It would be nice to not have failures in the interim though.

@annevk @domenic I see this change came from https://github.com/whatwg/html/pull/5659 but is there also a PR somewhere to update https://w3c.github.io/webappsec-secure-contexts/? It looks like not, but should there be?

**Comment by domenic** [comment]
As per that PR,

> I was planning to send a PR to update the Secure Context spec to point to this (while preserving existing IDs), but given how many open PRs on it have been sitting with no response, I'm feeling discouraged. (And I'd want to wait for at least w3c/webappsec-secure-contexts#76 to land before doing mine.) /cc @mikewest

**Pull request closed without merging**
