### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=273031

### PR DESCRIPTION
**Pull request by mdubet**

### CODE REVIEW

**Comment by mustaqahmed** [comment]
This is testing `pointer-events: none` CSS attributes, right?  In that case, `css/css-ui/` seems to be the appropriate folder for this test.

FYI: only WPTs for the PointerEvents spec lives in `pointerevents/` folder.

**Comment by mdubet** [comment]
I've put it next to the others tests about `pointer-events`  CSS property ; like this test https://github.com/web-platform-tests/wpt/blob/61a0206ad3/pointerevents/pointerevent_hit_test_scroll_visible_descendant.html

Should we move all of them ?

**Comment by mustaqahmed** [comment]
You are right, there are [quite a few](https://source.chromium.org/search?q=file:external%2Fwpt%2Fpointerevents%2F%20%3Ctitle%3E.*pointer-events:) WPTs like this.  All of them (except possibly the event bubbling one) are _only_ about the `pointer-events` CSS property which is defined in the [CSS Basic User Interface Module Level 4](https://drafts.csswg.org/css-ui/#pointer-events-control) spec.

@flackr @wangxianzhu What do you think about moving them to `css/css-ui/` folder?

**Comment by wangxianzhu** [comment]
I agree to move these tests, but I'm not sure how to prevent future errors. People (e.g. previous me) may intuitively think `pointer-events` belongs to `wpt/pointerevents`.

I have a basic question: Can the `PointerEvents` spec define `pointer-events`? My first thought was that the `PointerEvents` spec is not a css spec, but I found it defines a css property `touch-action`.

**Pull request closed without merging**
