### PR TITLE
Create a testcase for claim() should affect other registrations.

### PR DESCRIPTION
**Pull request by jgraham**
Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1175163

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5090/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208980988)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208980989)

**Pull request merged**
