### PR TITLE
Use actual files in meta refresh tests instead of 404s

### PR DESCRIPTION
**Pull request by zcorpan**
Ref. https://github.com/w3c/web-platform-tests/pull/2361#issuecomment-159381451
Ref. https://github.com/w3c/web-platform-tests/issues/2358

r=@domenic

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by zcorpan** [comment]
This relies on https://github.com/w3c/wptserve/issues/69

**Comment by zcorpan** [comment]
The wptserve issue is fixed now.

**Comment by domenic** [comment]
LGTM; tested locally this time.

If this still doesn't help we may want to investigate using promise_test instead of async_test in order to get the tests to run sequentially instead of in parallel.

**Comment by zcorpan** [comment]
Thanks!

**Comment by Ms2ger** [comment]
Fwiw, @mikewest has something for serial async tests in https://github.com/w3c/web-platform-tests/pull/2385

**Pull request merged**
