### PR TITLE
'background-clip-content-box-001.html' has blue edge.

### PR DESCRIPTION
**Pull request by tgraham-antenna**
The text and the reference file both differ.  Red commonly means an error condition, so using blue all around.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254790201)

# Firefox (nightly) #
Testing web-platform-tests at revision ac87cb9f28d38d31217de6270cc71c525ef062e4
Using browser at version BuildID 20170717100212; SourceStamp aff336ac161daa3ea350e59a288963edbd58ed39
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6573/css/css-backgrounds-3/background-clip-content-box-001.html">/css/css-backgrounds-3/background-clip-content-box-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254790202)

# Sauce (safari) #
Testing web-platform-tests at revision ac87cb9f28d38d31217de6270cc71c525ef062e4
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6573/css/css-backgrounds-3/background-clip-content-box-001.html">/css/css-backgrounds-3/background-clip-content-box-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254790210)

# Chrome (unstable) #
Testing web-platform-tests at revision ac87cb9f28d38d31217de6270cc71c525ef062e4

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254790211)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ac87cb9f28d38d31217de6270cc71c525ef062e4
Using browser at version 14.14393
Starting 10 test iterations

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
