### PR TITLE
Improve tests for extra arguments to getContext().

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by Cwiiis — COMMENTED** [review]
This looks good to me, but I'm not sure about the 2d-getcontext-options.any test - it looks like it's checking to see that all the options are respected(?), but I don't know that that's necessarily a useful test. At the least, I think each option should be tested separately, as some are much more useful than others, and others are exposing implementation details that might not make a difference depending on renderer implementation.

**Comment by Ms2ger** [comment]
It would be good to have tests for each of the options' behaviour as well, yeah, but I'm no longer enough of a domain expert to write those. I still wanted to check that the options are converted as defined in the IDL spec, though.

**Comment by Cwiiis** [comment]
Makes sense - I still think it might be worth splitting them into separate tests (it seems wrong to me that if the spec was changed to add or remove any options that a user agent would suddenly fail this test entirely until it's updated)

**Comment by Ms2ger** [comment]
I can only test the order if they're all passed, though

**Comment by Cwiiis** [comment]
Ah, ignore me in that case, guess we'll just have to make sure these stay in sync (or never change options :))

**Review by Cwiiis — APPROVED** [review]

**Pull request merged**
