### PR TITLE
Add test to check rendering of children of mspace

### PR DESCRIPTION
**Pull request by rwlbuis**
Test adopted from WebKit.

### CODE REVIEW

**Review by fred-wang — APPROVED** [review]
LGTML This is how all web engines handle children in mspace. For the record, my original review was https://github.com/web-platform-tests/wpt/pull/15722#pullrequestreview-211885618

**Comment by rwlbuis** [comment]
@foolip @Ms2ger any idea what could be wrong with Taskcluster/Firefox check? I think the test is valid MathML.

**Comment by foolip** [comment]
@rwlbuis at the end of the logs you can find this:

## All results ##

### /mathml/presentation-markup/spaces/mspace-children.html ###
| Subtest |         Results          | Messages |
|---------|--------------------------|----------|
|         | **FAIL: 1/5, PASS: 4/5** |          |

## Unstable results ##

|                            Test                           | Subtest |         Results          | Messages |
|-----------------------------------------------------------|---------|--------------------------|----------|
| `/mathml/presentation-markup/spaces/mspace-children.html` |         | **FAIL: 1/5, PASS: 4/5** |          |

So it looks like the test is flaky in Firefox. Is that a problem with the test, or a problem with Firefox?

**Comment by fred-wang** [comment]
> So it looks like the test is flaky in Firefox. Is that a problem with the test, or a problem with Firefox?

Probably a firefox bug. I believe it should either always fail (if Firefox accepts children in mspace) or always pass (if it does not accept children).

**Comment by foolip** [comment]
@jgraham do you need to do something to prepare for an incoming flaky test? Can you admin merge this?

**Comment by rwlbuis** [comment]
This landed in pr 15947.

**Pull request closed without merging**
