### PR TITLE
WIP: updateWith() tests

### PR DESCRIPTION
**Pull request by marcoscaceres**
Lost more tests to come... first shot at this... ignore whitespace issues please

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239931776)

# Firefox (nightly) #
Testing web-platform-tests at revision caf8b43d77b618d9434fbad7eeba540f87c194bc
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6162/payment-request/payment-request-update-event-updatewith-method.https.html">/payment-request/payment-request-update-event-updatewith-method.https.html</a></summary>


|                                        Subtest                                         | Results |                                                Messages                                                |
|----------------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------|
|                                                                                        | OK      |                                                                                                        |
| `Let target be the request which is dispatching the event.`                            | FAIL    | `PaymentRequest is not defined`                                                                        |
| `If event.target is not a PaymentRequest object, then throw a TypeError.`              | FAIL    | `PaymentRequestUpdateEvent is not defined`                                                             |
| `If event.[[waitForUpdate]] is true, then throw an "InvalidStateError" DOMException.`  | FAIL    | `PaymentRequest is not defined`                                                                        |
| `If request.[[state]] is "created", then throw an "InvalidStateError" DOMException.`   | FAIL    | `PaymentRequest is not defined`                                                                        |
| `If request.[[state]] is "closed", then throw an "InvalidStateError" DOMException.`    | FAIL    | `promise_test: Unhandled rejection with value: object "ReferenceError: PaymentRequest is not defined"` |
| `Upon rejection of detailsPromise, abort the update with an "AbortError" DOMException` | FAIL    | `promise_test: Unhandled rejection with value: object "ReferenceError: PaymentRequest is not defined"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239931777)

# Sauce (safari) #
Testing web-platform-tests at revision caf8b43d77b618d9434fbad7eeba540f87c194bc
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6162/payment-request/payment-request-update-event-updatewith-method.https.html">/payment-request/payment-request-update-event-updatewith-method.https.html</a></summary>


|                     Subtest                      | Results |               Messages               |
|--------------------------------------------------|---------|--------------------------------------|
|                                                  | OK      |                                      |
| `Test for PaymentRequestUpdateEvent Constructor` | FAIL    | `SyntaxError: Unexpected token '=>'` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239931783)

# Chrome (unstable) #
Testing web-platform-tests at revision caf8b43d77b618d9434fbad7eeba540f87c194bc

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239931784)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision caf8b43d77b618d9434fbad7eeba540f87c194bc
Using browser at version 14.14393

**Comment by marcoscaceres** [comment]
Let's start with these... these get really complicated very quickly, so I'd like to land one just a few at a time or it will be hard to review.

**Review by edenchuang — APPROVED** [review]
LGTM.

**Review by domenic — APPROVED** [review]
LGTM modulo error type question I raised in https://github.com/w3c/browser-payment-api/pull/547#pullrequestreview-43520200. Feel free to merge straight away if you want to keep NotAllowedError, or tweak and then merge if you switch.

**Comment by marcoscaceres** [comment]
Ok, switched to "InvalidStateError".

**Pull request merged**
