### PR TITLE
Send screenshots from Azure to wpt.fyi

### PR DESCRIPTION
**Pull request by Hexcles**
Towards https://github.com/web-platform-tests/wpt.fyi/issues/57

### CODE REVIEW

**Comment by Hexcles** [comment]
@foolip the only interesting change is https://github.com/web-platform-tests/wpt/pull/15765/commits/f8774bc1aec5ef6746963f1276dd7c5c273787c1

**Comment by Hexcles** [comment]
It works! https://staging.wpt.fyi/results/css/css-flexbox?run_id=5429338749009920&run_id=4762797283999744

I'm going to revert the test change (sorry for spamming all the css reviewers).

**Comment by gsnedders** [comment]
Can you make `test_end` build `output` as a list and join it at the end?

**Comment by Hexcles** [comment]
@foolip this is ready for review; note that the extension for the screenshot file may be changed following discussions in #15771 for consistency (I don't really like `.db`, either.), so don't merge it right now.

**Review by foolip — APPROVED** [review]

**Pull request merged**
