### PR TITLE
Use interfaces/web-nfc.idl file

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@lukebjerring, @foolip, it's a fixed in web-nfc/idlharness.https.html to reflect https://github.com/w3c/web-platform-tests/pull/9842, PTAL.

**Comment by foolip** [comment]
Oh, sweet, thank you! Let's see how to combine these then...

**Comment by foolip** [comment]
Must merged https://github.com/w3c/web-platform-tests/pull/9842, so the Travis jobs that are running are kind of pointless. @Honry, can you rebase this?

**Review by foolip — APPROVED** [review]
Please go ahead and land once Travis jobs after rebasing haven't blown up. (Manually confirming that the tests still work would be nice too, if you can.)

**Comment by Honry** [comment]
@foolip, yes, I've confirmed manually.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25418)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350153623)

**Pull request merged**
