### PR TITLE
[META] Update URL of WebRTC Encoded Transform

### PR DESCRIPTION
**Pull request by tidoust**
Shortname of the spec changed recently.

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Thanks!

**Comment by tidoust** [comment]
> Hmm, the directory itself should also be renamed though... feeling up for that?

Sure, now done! I wasn't sure what was the policy, and decided to err on the safe side to start with.

**Comment by foolip** [comment]
With directory renames it's always possible that some other directory references files in it, so I did `git grep -l webrtc-insertable-streams` on this PR branch and found:
```
interfaces/webrtc-insertable-streams.idl
tools/wpt/tests/test_wpt.py
webrtc-encoded-transform/idlharness.https.window.js
```

It would be great if you could also rename `interfaces/webrtc-insertable-streams.idl` and the string in `webrtc-encoded-transform/idlharness.https.window.js`.

Then it just so happens that this file is used in a unit test, so if you could update the string in `tools/wpt/tests/test_wpt.py` that should take care of it. (The tests aren't run if only tests are changed, that's why CI is still passing.)

**Comment by tidoust** [comment]
OK, I updated the files mentioned.

I also thought that this would be a good time to refresh the IDL in `interfaces` to match the current spec, but maybe that should be handled separately?

**Comment by tidoust** [comment]
Tests don't seem to like the update to `tools/wpt/tests/test_wpt.py`. I don't know how to fix that :)

**Comment by foolip** [comment]
@tidoust I think it was just a problem with the order. I've tried a fix.

**Comment by foolip** [comment]
I've looked at the remaining failures and they aren't due to these changes. They're also not blocking. Things are in a fairly bad state with failures in CI by default right now...

**Pull request merged**
