### PR TITLE
Import a Mozilla Crypto API test.

### PR DESCRIPTION
**Pull request by Ms2ger**
If people like this, I'll probably continue importing them one by one as time permits.

I haven't reviewed these tests for correctness. They don't run in Chrome for lack of HTTPS support, but they all pass in Gecko.

[Review on Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/1490)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@sleevi: any news?

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by jimsch** [comment]
@Ms2ger My inclination is to close this without prejudice as we now have test cases that cover this.  Do you have any objections?

**Comment by Ms2ger** [comment]
Sad but fair.

**Pull request closed without merging**
