### PR TITLE
Test header values

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/fetch/issues/332 for details.

Unless https://github.com/w3c/wptserve/issues/111 is fixed soon we may have to apply a temporary exception for 0x0B and 0x0C.

### CODE REVIEW

**Comment by annevk** [comment]
@jgraham this test runs fine locally. Is 500 fetches really too much? What should happen instead here?

**Comment by jgraham** [comment]
Try adding `<meta name=timeout content=long>` to the test (500 fetches in 10s seems like a lot to me).

**Comment by youennf** [comment]
IIRC, wptserve does not support pipeline so basically, 500 fetches means creating 500 connections.
Why not adding support for it?

**Comment by youennf** [comment]
See https://github.com/w3c/wptserve/pull/86 and https://github.com/w3c/wptserve/issues/108

**Comment by annevk** [comment]
@youennf pipelining is not web-compatible I believe. Even so, this test seems to work fine for me locally and since the longer timeout it also runs fine on Travis.

**Comment by annevk** [comment]
@youennf are you okay with this test and the change to the standard?

**Comment by youennf** [comment]
Sounds ok

**Comment by ricea** [comment]
500 fetches is going to cause masses of timeouts on Chromium's bots. As a rule of thumb, the slowest bots can be 100 times slower than running locally.

I suggest only testing the characters that have been known to cause problems.

**Comment by annevk** [comment]
@ricea I could remove 0-9, a-Z. But there's a lot of code points here that cause a problem of sorts.

**Comment by ricea** [comment]
@annevk Based on my experience, you have a budget of about 50 connections to play with. It looks like you should be able to test multiple headers on a single connection; would that work?

**Comment by annevk** [comment]
That's a reasonable idea. I'll work on a PR.

**Comment by annevk** [comment]
Created two PRs that do just that.

**Pull request merged**
