### PR TITLE
Add tests for slot.assignedElements() method

### PR DESCRIPTION
**Pull request by cyrilletuzi**
As requested in whatwg/html#2269

### CODE REVIEW

**Comment by hayatoito** [comment]
Hmm. I think we do not want to duplicate every tests where assignedNodes() is used. We wouldn't get benefits from this kind of duplicated tests.

You might want to add a minimum test for assignedElements(), instead of duplicating every tests which use assignedNodes().

**Comment by cyrilletuzi** [comment]
I followed @annevk instructions in whatwg/html/#2269

Which makes sense as `assignedElements()` will be considered as ShadowDOM v2, so previous test with only `assignedNodes()` should continue to succeed while the new ones with `assignedElements()` should fail until implementation.

But if it's better to group them, just tell me, I just need to know who has the final word on this.

**Comment by cyrilletuzi** [comment]
(Just a note to mention that previous tests for `assignedNodes()` should have raised a problem, as all tests needed to do `removeWhiteSpaceOnlyTextNodes()`, which is what is solved by `assignedElements()`.)

**Comment by annevk** [comment]
I tend to disagree with @hayatoito. Tests are rather cheap and it's better to be exhaustive since you don't know what implementation decisions everyone will make. If at some point it turns out that one of these methods needs some kind of fast path due to wide usage, having tests for all scenarios in both will help catch subtle bugs.

**Comment by hayatoito** [comment]
Okay. We should judge this kind of *exhaustive*-ness case by case, however, in this particular case, I am not a fan of this kind of duplications. I got an impression that this duplication happened only because the usage of `assignedNodes()` were *spotted* in the original tests. Is my understanding correct? Is there any existing test which uses `assignedNodes()` API, but it was not *duplicated*, with a reason?

Now we have doubled the number of tests. Then, later, if we add yet another new API, we would double the number again, having 4 x N tests? I think we want to avoid this kind of exponential-ness so that tests can be maintenance-friendly.

Could we spend more efforts to reduce this kind of explosion by making tests more orthogonal, or having more maintenance-friendly way? For example, I think @rniwa parameterized some tests so that we can test both cases, open or closed, without *copy and pasting piece of code*.

Can we do that? or is that too early optimization? Maybe I am worrying too much on this kind of duplication. :(

@rniwa, WDYT? Is this okay for you?

**Comment by cyrilletuzi** [comment]
There are some tests which add text node child to check they are filtered by `assignedElements()`. But most of them are just duplicated.

If we group tests, we will need to be careful to do `assignedElements()` tests before calling `removeWhiteSpaceOnlyTextNodes()`.

**Comment by hayatoito** [comment]
@cyrilletuzi Thank you. I understand your intention. I appreciate your efforts.  :)

I prefer non-duplication and more orthogonal tests, but If @annevk and @rniwa is okay to this change, please merge this without waiting me.

I might try to refactor tests so that they can be more maintenance-friendly, but that can be done later.

**Comment by annevk** [comment]
Ah, I misunderstood your concern @hayatoito. Deduplication of code does seem worthwhile, even in tests. You would still get 4 * N tests, but the amount of changes needed for that will be lower (just update an array and maybe some conditionals).

**Comment by cyrilletuzi** [comment]
Any news ? Merge or regroup ?

**Comment by annevk** [comment]
So I think the main question is whether you think it's feasible to parameterize the existing assignedNodes tests so that they can be reused for assignedElements without as much duplication as the current patch.

**Comment by rniwa** [comment]
Oh yeah, we certainly don't want to duplicate tests like this. We should at minimum extract helper functions that create trees to test things.

Note that I usually prefer not having logics for assertions since I prefer test assertions being duplicated over test assertions dependent on complicated logic prone to bugs.

**Comment by annevk** [comment]
@cyrilletuzi are you still interested in working on this?

**Comment by cyrilletuzi** [comment]
Yes but I need a clear direction.

**Comment by annevk** [comment]
That is fair. What I'd do is something like
```
["assignedNodes", "assignedElements"].forEach(prop => {
   test(...);

   ...
}
```
as a wrapper around the existing tests. Perhaps with slightly more complex elements in the array depending on all the parts of the tests that need templating.

@hayatoito should probably confirm that's acceptable, but I suspect it is.

**Comment by hayatoito** [comment]
> ```["assignedNodes", "assignedElements"].forEach(```

Yeah, that's one of the ways to remove code duplication, which is acceptable.

**Pull request closed without merging**
