### PR TITLE
Service worker: updating ready tests

### PR DESCRIPTION
**Pull request by jakearchibald**
For https://github.com/w3c/ServiceWorker/pull/1487.

I took the opportunity to modernise the tests so they're easier to follow. The only behavioural change is I removed the last test, which was the only test that asserted the old spec behaviour.

### CODE REVIEW

**Comment by jakearchibald** [comment]
@asutherland if I'm reading the logs correctly, it looks like there's instability in Firefox. Is that a Firefox bug here or have I created a race that I don't see?

**Comment by cdumez** [comment]
I see the following flaky failure in WebKit:
-PASS resolve ready after unregistering
+FAIL resolve ready after unregistering promise_test: Unhandled rejection with value: object "TypeError: null is not an object (evaluating 'reg2.active.scriptURL')"

I don't know if this is an issue with the test or our implementation.

**Comment by cdumez** [comment]
It looks like the flaky failure in Firefox and WebKit are identical so 2 separate implementations failing is not a good sign.

Looking at the test, I think the issue may be as follows:
```
  await wait_for_state(t, reg1.installing, 'activating');
  await reg1.unregister();
  // Ready promise should be pending, waiting for a new registration to arrive
  const readyPromise = frame.contentWindow.navigator.serviceWorker.ready;
```

I think this is inherently racy. In some cases, the ready promise will have time to get resolved here  so it will no longer be pending.

**Comment by mattto** [comment]
Sorry for the extreme delay. The tests look good to me, but @cdumez's comment seems to mean Firefox and WebKit are doing something different than "don't try to figure the value until .ready is accessed".

**Comment by jakearchibald** [comment]
@cdumez I'm trying to figure out where the race is coming from. 

We can assume `readyReg` and `reg2` are different objects, else `readyReg.active.scriptURL` would throw.

I guess that means `readyReg` is sometimes referring to the old registration.

`reg.unregister()` should not resolve until after it has been removed from the scope to registration map https://w3c.github.io/ServiceWorker/#unregister-algorithm.

The getter for `navigator.serviceWorker.ready` determines which registration to use by reading the scope to registration map.

If the above is correct, this seems like a bug in WebKit and Mozilla. Developers should be able to rely on `reg.unregister()` resolving when the registration is unregistered.

**Comment by cdumez** [comment]
@jakearchibald You're right, I see what you mean now. I'll investigate further today to try and figure out what's going wrong with WebKit.

**Comment by asutherland** [comment]
The Firefox stability test flakiness says it's 1/5 on `promise_test: Unhandled rejection with value: object "TypeError: reg2.active is null"` [in the log](https://community-tc.services.mozilla.com/tasks/ACBLuF7oTuqDOnRaj0ScxQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FACBLuF7oTuqDOnRaj0ScxQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log).

It appears the problem here is that `reg2` comes from the test's global and `readyPromise` comes from the iframe's global.  Firefox's implementation maintains separate registrations per-global, each with their own IPC actor, which mean that separate globals constitute separate consistent ordering domains.

The [definition of the service worker registration object map](https://w3c.github.io/ServiceWorker/#environment-settings-object-service-worker-registration-object-map) is per global, and all spec terminology is either "For each client of matchedClients, queue a task on client’s responsible event loop" or "Let registrationObjects be an array containing all the ServiceWorkerRegistration objects associated with registration." with "For each registrationObject in registrationObjects:" with "Queue a task".  This does suggest that, per spec, this exact situation is one that can occur and the test needs to wait for the registration from the ready promise and register() to be equivalent/stabilize.

That said, Firefox could just unify our backing registrations and their actors on a "unit of related browsing contexts" under our [BrowserContextGroup](https://searchfox.org/mozilla-central/source/docshell/base/BrowsingContextGroup.h) abstraction instead of per-global.  It's already very complex and hard to write ServiceWorker tests, and it seems like letting same-origin globals that are synchronously reachable see logically equivalent registrations in different states just makes everyone's lives harder.

**Comment by cdumez** [comment]
Looking into this more, I am convinced this is indeed a WebKit bug and I will work on fixing it ASAP.
Some of our operations (registration update / service worker update / promise resolution) may happen out-of-order due to event loop bugs.

Test test looks good to me as is.

**Comment by mattto** [comment]
Thanks @cdumez for the investigation and fix in WebKit!

I think @asutherland has a point too, though, looks like the test should wait for `reg2.active` to be set independently of waiting for `readyPromise` to resolve.

**Comment by jakearchibald** [comment]
Yeah, I also agree with @asutherland. Ugh, we're using far too many queued items to update state in a single event loop. I still wish we could sort it with something in the direction of https://github.com/w3c/ServiceWorker/pull/1416/files.

I'll update the tests as @matto suggested.

**Comment by jakearchibald** [comment]
Changes made!

**Review by mfalken — APPROVED** [review]
LGTM. Great teamwork everyone!

**Pull request merged**
