### PR TITLE
Test Ed25519 with small- and mixed-order points

### PR DESCRIPTION
**Pull request by javifernandez**
Tests to ensure that the EdDSA Verify implementation performs checks for small-order key sand signature's point R.

### CODE REVIEW

**Comment by panva** [comment]
Tests 1,2,3,4, and 12 all fail on existing implementations while the others pass. Begs the question, are the failing ones correct?

**Comment by panva** [comment]
>  now all the test cases should pass in both WebKit and Blink engines, which are the only ones implementing the Ed25519 algorithm for now.

Node.js and other non-browser vendors implement this too (see https://github.com/WICG/webcrypto-secure-curves/issues/20). I can confirm the latest status of this PR passes on Node.js (backed by openssl).

**Comment by javifernandez** [comment]
Now the question is whether these tests matches the spec or not, since in the lat draft it's stated:

>  If the key data of key represents an invalid point or a small-order element on the Elliptic Curve of Ed25519, return false. 

And vectors [0, 1] have small order key data and still are verified by most of the implementations. 

> If the point R, encoded in the first half of signature, represents an invalid point or a small-order element on the Elliptic Curve of Ed25519, return false. 

At least vector 2 has an small-order R point, is validated by most of the implementations.

Should we add additional checks in the WebCrypto API implementation to match the spec, rejecting signatures generated by any small-order public keys ?

**Comment by panva** [comment]
> Should we add additional checks in the WebCrypto API implementation to match the spec, rejecting signatures generated by any small-order public keys ?

I'm not aware of any more OpenSSL APIs we could employ to aid in the process. The status quo is IIRC as far as we can go on the Node.js side of things without resorting to introspecting the signature & key bytes ourselves.

**Comment by panva** [comment]
> Should we add additional checks in the WebCrypto API implementation to match the spec, rejecting signatures generated by any small-order public keys ?

I'm not aware of any more OpenSSL APIs we could employ to aid in the process. The status quo is IIRC as far as we can go on the Node.js side of things without resorting to introspecting the signature & key bytes ourselves.

cc @tniessen

**Comment by javifernandez** [comment]
> > Should we add additional checks in the WebCrypto API implementation to match the spec, rejecting signatures generated by any small-order public keys ?
> 
> I'm not aware of any more OpenSSL APIs we could employ to aid in the process. The status quo is IIRC as far as we can go on the Node.js side of things without resorting to introspecting the signature & key bytes ourselves.
> 
> cc @tniessen

According to [this paper](https://eprint.iacr.org/2020/1244.pdf#section.A.2) a check to reject small order key data could be implemented just looking for matches with the 14 small order points defined there. Additionally, given that non-cannonical points relevant for this check are all of small-order, there is no need to add specific checks for this.

**Comment by twiss** [comment]
Hello :wave: I haven't manually checked the values but if the quoted paper is correct, all the tests in `kSmallOrderTestCases` should have `verified: false`, I think.

Indeed the implementation could check for small-order points manually, or perhaps we could request OpenSSL to add a function to check this?

FWIW, I personally don't think it's super urgent to modify existing implementations that would currently fail these tests, since applications that don't require consistent validation criteria are unlikely to be vulnerable in some way because of this.

*However*, I do think it's best to make the specification explicit about which signatures are expected to be valid; and ideally try to get the implementations to be consistent on this point, otherwise it could inadvertently cause interoperability failures in the future, and/or it might become a fingerprinting signal. And so I would merge these tests with `verified: false` for all of them, so that implementations can work towards that goal.

---

Note that, technically speaking, an implementation that validates the signature with ID 11 in a TLS context is strictly speaking not compliant with RFC8446, which also refers to RFC8032 (which requires rejecting non-canonical points).

Whether or not that matters for TLS I don't know - I suspect not much, except again perhaps for fingerprinting? - but it might be an argument to get OpenSSL to care about that part.

**Comment by javifernandez** [comment]
> And so I would merge these tests with verified: false for all of them, so that implementations can work towards that goal.

Some of the verification inconsistencies (vectors [4. 5]),come from the cofactored vs cofactorless implementation, which the spec is still not clear about which one is preferred; this is discussed in [issue 19](https://github.com/WICG/webcrypto-secure-curves/issues/19).

If we want to expect all these vectors to be verified as false, wouldn't we need to solve issue 19 and change the spec accordingly ?

**Comment by twiss** [comment]
Oh, I see, I misread the tests; I thought all of them were small-order (coming from Table 1 in the paper).

Then yeah, at the moment the draft doesn't say which verification equation to use, so strictly speaking both `false` and `true` would be acceptable in those cases, which is of course not ideal. So yeah, we should discuss that in https://github.com/WICG/webcrypto-secure-curves/issues/19. Perhaps if we want this PR to strictly test https://github.com/WICG/webcrypto-secure-curves/pull/21, we could leave out those cases for now (or allow either result)?

**Comment by javifernandez** [comment]
Based on this  [comment](https://github.com/web-platform-tests/wpt/pull/43751#issuecomment-1934753041) I've submitted changes to expect failures in all the test cases, expect vector 5 which would require mixed-point checks. This implies that the WebCrypto API implementation should add checks for rejecting small-order points.

In order to pass the test case 5 we would require the spec to request for a cofactorless implementation, as suggested in [PR #25](https://github.com/WICG/webcrypto-secure-curves/pull/25). 

These tests provide cases for non-canonical points, but all of them are small-order and definitively some implementations (eg BoringSSL) fail to detect them and refuse to verify the signatures. Adding checks for small-order points would imply we may miss some cases of non-canonical points that are not small-order and should be rejected.

Finally, test cases 12 and 13 detect scenarios that breaking non-repudiation; a canonical key and signature is verified against 2 different messages. 

If we accept this tests, we would diverge from what other implementations do, especially regarding the rejection of any small-order point.

**Comment by twiss** [comment]
Thanks! This looks good to me now, but I'll hold off on approving until https://github.com/WICG/webcrypto-secure-curves/pull/25 is approved and merged.

> These tests provide cases for non-canonical points, but all of them are small-order and definitively some implementations (eg BoringSSL) fail to detect them and refuse to verify the signatures. Adding checks for small-order points would imply we may miss some cases of non-canonical points that are not small-order and should be rejected.

I think it would be reasonable to add more test cases for non-canonical points, but we could also do so later in a separate PR, IMO.

> If we accept this tests, we would diverge from what other implementations do, especially regarding the rejection of any small-order point.

From [these results](https://github.com/novifinancial/ed25519-speccheck?tab=readme-ov-file#results), it looks like we would match the results of libsodium, libra-crypto, and dalek strict, right? Obviously it's a shame we don't match the others, but the results diverge quite a lot, and we can't match all of them (if we want to strictly define the results, in order to be able to have tests like this at all). And, out of the available options, erring on the side of strictness looks most reasonable to me - also because while it's possible to add a check, it isn't possible to remove one (without patching the underlying library).

**Review by twiss — APPROVED** [review]
https://github.com/WICG/webcrypto-secure-curves/pull/25 has been merged, so I'll merge this as well :blush:

**Pull request merged**
