### PR TITLE
Inexorabletash/encoding api

### PR DESCRIPTION
**Pull request by inexorabletash**
Test for the Encoding Standard's API (TextEncoder/TextDecoder), ported from Chromium/Blink's layout tests.

### CODE REVIEW

**Comment by Ms2ger** [comment]
@inexorabletash: something weird seems to have happened to the history here; could you try to squash everything into one simple commit?

**Comment by inexorabletash** [comment]
Ugh, sorry - thought I had squashed.

Take a peek now? I'm not sure if I need to do more on the critic side of things.

**Comment by inexorabletash** [comment]
Per the "...to help critic track your changes..." I may need to drop/resubmit a request. LMK.

**Comment by hillbrad** [comment]
Critic is very confused by this, showing thousands of lines needing review. Is it possible to drop/resubmit this with just the relevant changes, please?

**Pull request closed without merging**
