### PR TITLE
ReadableStream: pipeThrough() is not fooled by a fake Promise

### PR DESCRIPTION
**Pull request by ricea**
If an implementation used "instanceof" to detect a Promise in the implementation
of pipeThrough(), it would be fooled by Object.create(Promise). Add a test for
this.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5519)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/220440271)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 64b44087958e718ee48f027ff57ebf19eac7d281
Using browser at version BuildID 20170409194145; SourceStamp 45692c884fdd5136a64fb2f8a61a0c8183b69331
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.dedicatedworker.html">/streams/piping/pipe-through.dedicatedworker.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.html">/streams/piping/pipe-through.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5519/streams/piping/pipe-through.serviceworker.https.html">/streams/piping/pipe-through.serviceworker.https.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Service worker test setup`                                                                            | PASS    |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.sharedworker.html">/streams/piping/pipe-through.sharedworker.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `ReadableStream is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/220440272)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 64b44087958e718ee48f027ff57ebf19eac7d281
Using browser at version 59.0.3063.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.dedicatedworker.html">/streams/piping/pipe-through.dedicatedworker.html</a></summary>


|                                                Subtest                                                 | Results |                            Messages                           |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                                        | OK      |                                                               |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `Cannot read property 'call' of undefined`                    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.html">/streams/piping/pipe-through.html</a></summary>


|                                                Subtest                                                 | Results |                            Messages                           |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                                        | OK      |                                                               |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `Cannot read property 'call' of undefined`                    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5519/streams/piping/pipe-through.serviceworker.https.html">/streams/piping/pipe-through.serviceworker.https.html</a></summary>


|                                                Subtest                                                 | Results |                            Messages                           |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                                        | OK      |                                                               |
| `Service worker test setup`                                                                            | PASS    |                                                               |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `Cannot read property 'call' of undefined`                    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5519/streams/piping/pipe-through.sharedworker.html">/streams/piping/pipe-through.sharedworker.html</a></summary>


|                                                Subtest                                                 | Results |                            Messages                           |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                                        | OK      |                                                               |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `sequentialReadableStream(...).pipeThrough is not a function` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined`                    |
| `pipeThrough should not be fooled by an object whose instanceof Promise returns true`                  | FAIL    | `Cannot read property 'call' of undefined`                    |

</details>
</details>

**Comment by jugglinmike** [comment]
I don't see where either method would be invoked even if `fakePromise` were a
true Promise instance. Wouldn't this test pass in that case, as well?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5519/)

**Comment by ricea** [comment]
@jugglinmike My intent was to catch implementations like the reference implementation that call .catch() (or then()) on the Promise to mark it as handled. But your comment made me realise that I can do just as well by not implementing then() and catch() at all.

**Comment by domenic** [comment]
Hmm, I liked the original test better. In addition to catching crashy implementations, it would catch implementations that attempt to mark-as-handled by doing `returnValue.catch(() => {})`.

**Comment by ricea** [comment]
I've gone back to explicitly checking .then() and .catch(), but added comments to hopefully make it clearer why it does that.

**Review by domenic — APPROVED** [review]

**Comment by jugglinmike** [comment]
My comment was not so much about asserting method invocation (or lack thereof)
but about the object under test.  Whether or not it is a "fake" Promise (e.g.
created via `Object.create` and lacking the Promise's internal slots), the
expectations stated here hold. Using `Object.create` seems like an irrelevant
condition. I may be mistaken, but it seems to confuse the intent of the test
and also make it less generic.

**Comment by domenic** [comment]
Fake promises will crash the browser if you try to look at their [[PromiseIsHandled]] internal slot. That is what this is testing.

**Comment by ricea** [comment]
@jugglinmike
Would it help to remove the assertion `assert_true(fakePromise instanceof Promise, 'fakePromise fools instanceof');`? The only purpose of this is to make it clear to the reader that we do have an object that passes the `instanceof` test. But maybe it creates confusion about the real purpose of the test.

**Comment by jugglinmike** [comment]
My confusion was due to there being two behaviors under test here:

1. Invocation of various Promise instance methods (or the lack thereof)
2. Referencing of the [[PromiseHandled]] internal slot (or lack thereof)

There are in-line comments that explain each (thanks for those), but they are
actually orthogonal behaviors, and their pre-conditions are likewise unrelated.
This is what confused me. I would have understood this initially if this were
expressed as two distinct tests: one that used a "true" Promise with overridden
instance methods, and one that used a "fake" Promise.

Thanks for following up with this! I really appreciate your making the effort
to iterate on this... But now that I understand the intent, I can see that my
feedback does not effect the test's efficacy, so I'm happy to let this
go. You've documented the code well, after all.

**Pull request merged**
