### PR TITLE
Block scripts with text/csv, audio/*, video/* and image/* mime types

### PR DESCRIPTION
**Pull request by jdm**
Upstreamed from https://github.com/servo/servo/pull/16126 [ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5584)

### CODE REVIEW

**Comment by jdm** [comment]
Code reviewed upstream.

**Comment by annevk** [comment]
fetch/api seems like the wrong place for this. This should have gone into fetch/script-blocking or some such.

**Comment by annevk** [comment]
And we should also make sure this happens for workers and importScripts().

**Comment by jdm** [comment]
I've filed https://github.com/w3c/web-platform-tests/issues/5588 about those comments.

**Pull request merged**
