### PR TITLE
Extend cssom/CSSKeyframeRule.html to test that style attribute has [P…

### PR DESCRIPTION
**Pull request by cdumez**
…utForwards]

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240624175)

# Firefox (nightly) #
Testing web-platform-tests at revision 927e6088ed22aa21a916ea7fc2d446a70289a2d7
Using browser at version BuildID 20170607100302; SourceStamp 5801aa478de12a62b2b2982659e787fcc4268d67
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6184/cssom/CSSKeyframeRule.html">/cssom/CSSKeyframeRule.html</a></summary>


|                       Subtest                       | Results |                          Messages                          |
|-----------------------------------------------------|---------|------------------------------------------------------------|
|                                                     | OK      |                                                            |
| `CSSKeyframeRule: style property`                   | PASS    |                                                            |
| `CSSKeyframeRule: style property has [PutForwards]` | FAIL    | `assert_equals: margin-left expected "50%" but got "100%"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240624176)

# Sauce (safari) #
Testing web-platform-tests at revision 927e6088ed22aa21a916ea7fc2d446a70289a2d7
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6184/cssom/CSSKeyframeRule.html">/cssom/CSSKeyframeRule.html</a></summary>


|                       Subtest                       | Results |                          Messages                          |
|-----------------------------------------------------|---------|------------------------------------------------------------|
|                                                     | OK      |                                                            |
| `CSSKeyframeRule: style property`                   | PASS    |                                                            |
| `CSSKeyframeRule: style property has [PutForwards]` | FAIL    | `assert_equals: margin-left expected "50%" but got "100%"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240624182)

# Chrome (unstable) #
Testing web-platform-tests at revision 927e6088ed22aa21a916ea7fc2d446a70289a2d7

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240624183)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 927e6088ed22aa21a916ea7fc2d446a70289a2d7

**Review by ghost — APPROVED** [review]

**Review by dbaron — APPROVED** [review]

**Pull request merged**
