### PR TITLE
Add wasm/OWNERS

### PR DESCRIPTION
**Pull request by zcorpan**
cc @mtrofin

### CODE REVIEW

**Comment by mtrofin** [comment]
I switched teams and don't work on wasm. You'd probably want to add @flagxor and @titzer from the v8 side instead.

**Comment by gsnedders** [comment]
Is @Ms2ger not working on WASM now?

**Comment by Ms2ger** [comment]
Feel free to put me in, but no promises

**Comment by zcorpan** [comment]
@flagxor @titzer are you OK with being listed in the OWNERS file here? It means you’ll get notified any time someone submits a PR with Media Capture tests, or changes to existing tests. And the tests could only be merged to the master branch after review from one of the OWNERS.

**Comment by titzer** [comment]
Ok with me.

**Pull request merged**
