### PR TITLE
Add tests for the MathML Operator dictionary

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by fred-wang** [comment]
This is still WIP

**Comment by fred-wang** [comment]
This is now ready for review

**Review by rwlbuis — COMMENTED** [review]
Seems one needs to be lspace and maybe consider reordering.

**Review by rwlbuis — APPROVED** [review]
lgtm.

**Comment by jgraham** [comment]
The CI failure is 


## Slow tests ##

|                                 Test                                 | Result | Longest duration (ms) | Timeout (ms) |
|----------------------------------------------------------------------|--------|-----------------------|--------------|
| `/mathml/presentation-markup/operators/operator-dictionary-001.html` | `OK`   | `8143`                | `10000`      |

So this is being detected as a test that could intermittently time out. Ideally we add `<meta name=timeout content=long>` to the test to avoid the potential instability.

**Comment by fred-wang** [comment]
Thanks will try that

**Pull request merged**
