### PR TITLE
Revert "Collapse mozilla-central Ahem lint exception to one line"

### PR DESCRIPTION
**Pull request by foolip**
See https://github.com/web-platform-tests/wpt/pull/18877#discussion_r322158938

Reverts web-platform-tests/wpt#18901

### CODE REVIEW

**Comment by foolip** [comment]
@dbaron @jgraham do with this as you will :)

**Comment by dbaron** [comment]
I think we're probably better off with this as they are (one line), since as far as I can tell, it's not possible for a test in that directory to pass this particular lint rule since the absolute file paths required wouldn't work for running in both reftest harnesses.

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
However I think we should stop adding tests to that directory, so this stops being a problem. Going forward, if we are adding tests that depend on system Ahem and there are configurations where Ahem isn't present on the system because wpt no longer considers that a requirement, these tests will get broken anyway, so I think the general lint rule (and indeed having exceptions) is just going to hide a real problem.

**Comment by dbaron** [comment]
The issue here isn't that tests are depending on system Ahem; they're just loading the Ahem webfont at a different path and not the canonical path for the rest of WPT.

**Comment by foolip** [comment]
@jgraham does that clarify such that it's fine to merge this? You approved, but then there was discussion :)

**Comment by jgraham** [comment]
Per @dbaron's previous comment it sounds like the correct way forward is to fix the lint to allow what gecko's doing and remove all the exceptions related to this issue.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/19218 for that change. I'm going to close this one for now.

**Pull request closed without merging**
