### PR TITLE
[css-grid] Reference all grid tests to css/support/grid.css

### PR DESCRIPTION
**Pull request by RMonteR**
* Cosmetic changes to grid.css
* All grid tests using grid.css point now to the same file, located under css/support
* Local grid.css versions removed

### CODE REVIEW

**Comment by RMonteR** [comment]
@javifernandez @foolip

**Comment by foolip** [comment]
@mrego can you review this?

**Review by mrego — APPROVED** [review]
As it seems `grid.css` is only used in `css-grid`, the file could go into `css/css-grid/support/` instead of `css/support/`. WDYT?

Either way I think this is really a great change, so thank you very much for killing all this duplicates.

**Comment by javifernandez** [comment]
> As it seems `grid.css` is only used in `css-grid`, the file could go into `css/css-grid/support/` instead of `css/support/`. WDYT?

I think non-grid tests may use this file as well, so I don't see any problem on having it in the css/ roo folder.

**Comment by mrego** [comment]
Ok, sounds good to me.

**Pull request merged**
