### PR TITLE
Install aioquic to more fully type check webtransport with mypy

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by bashi — APPROVED** [review]
I'm more than happy to approve, thank you!

**Comment by jgraham** [comment]
This is a somewhat breaking change in that it requires anyone who wants to be able to run unittests to non-optionally be able to install aioquic, which wasn't previously the case. Per the original [QUIC RFC](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/quic.md) the intent was to make the quic server fully optional.

In practice gecko doesn't yet have the ability to run the quic server, but we also don't run the wpt unit tests in our own CI. However we probably ought to, and this would be an additional barrier to that.

**Comment by foolip** [comment]
@jgraham do you mean that you wouldn't want any installed dependencies for running unit tests, so that everything would have to be vendored? Or is there some other problem?

**Comment by foolip** [comment]
FWIW, I'm working on a follow-up change to just install all dependencies for everything when running mypy, which together with https://github.com/web-platform-tests/wpt/pull/33325 would make sense to me.

As recently discussed somewhere (I forget where) it's probably not worth trying to run mypy in vendor CI, as we'd all need exactly the same version of mypy for it to not wreck havoc, and even then upgrading mypy would become more difficult.

So if we just abandon any hope of running mypy in vendor CI, is this fine?

**Comment by jgraham** [comment]
The problem is specifically dependencies that require compiled components, since they require more than just vendoring to support (you also need the correct toolchain, headers, etc. so that you can build them, or you need to have access to precompiled binaries in a way that allows them to be kept in sync with upstream changes, which probably means pypi or an automatically updated local mirror thereof.)

Not being able to run unit tests in vendor CI is problematic for two way sync, because it means that either you always need to run upstream CI before the code lands in the vendor repo (which is what blink does, but is harder for gecko for various reasons), or you need people to accept that sometimes upstream CI will fail on their PRs and they have to make a post-hoc change to their patch to get it to land upstream (which is the defacto situation for gecko, but it's definitely not ideal). mypy does make this harder (because basically every update finds additional type errors), but in principle the same situation exists for e.g. pytest.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/33418 isn't doing the same thing, but achieves something similar of making more of webtransport tested by mypy.

**Comment by foolip** [comment]
Abandoning in favor of https://github.com/web-platform-tests/wpt/pull/33418.

**Pull request closed without merging**
