### PR TITLE
Update OWNERS - adds mnoorenberghe

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@sideshowbarker, could you also kindly grant @mnoorenberghe write access for review purposes? @mnoorenberghe is working on the Payments front-end implementation on the Mozilla side.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-02-28 05:18:56
Finished: 2018-02-28 05:30:05


<h2>Failing Jobs</h2>
<ul>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24986)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/347118319)

**Comment by sideshowbarker** [comment]
> @sideshowbarker, could you also kindly grant @mnoorenberghe write access for review purposes?

Yup, invitation sent

**Comment by Ms2ger** [comment]
@mnoorenberghe: please confirm you want to be notified about changes in `payment-request/`.

**Review by mnoorenberghe — APPROVED** [review]

**Comment by mnoorenberghe** [comment]
I approve

**Pull request merged**
