### PR TITLE
Various fixes to complete-method-manual.https.html

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Thanks for the speedy review! @rsolomakhin, I tried this in Chrome Canary but it’s telling me that “basic-card” is not supported? Did I maybe screw something up in about:flags?

**Comment by rsolomakhin** [comment]
Is https://rsolomakhin.github.io/pr/cc/ working for you?

**Comment by marcoscaceres** [comment]
Will try it first thing tomorrow and let you know. Doing sneaky merges on my phone just before bed 🛌

**Comment by marcoscaceres** [comment]
> Is https://rsolomakhin.github.io/pr/cc/ working for you?

Yep. Must be something when running off localhost.

**Pull request merged**
