### PR TITLE
Cleanup border-radius-* tests

### PR DESCRIPTION
**Pull request by csnardi**
Removes extraneous parts of border-radius-* tests. Also corrects reference for border-radius-011.html.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22165)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/320910746)

**Comment by gsnedders** [comment]
https://gist.github.com/8e81bf29ded7935efd81125b0c789be6 is a diff with a lower than default similarity index and ignoring whitespace. (@csnardi for future, there's not really any need to move XHTML files to being HTML, though if you do it would be better to do it in a separate commit for the sake of a more readable history, and whitespace changes are also nicer if they're a separate commit)

**Comment by csnardi** [comment]
Hopefully that looks a little better. I separated out the reference correction into another commit, and I undid the .xht -> .html changes. I still kept the whitespace changes, since these tests were pretty messy before and hard to read.

**Comment by gsnedders** [comment]
@csnardi I wasn't really asking you to redo it, but thanks!

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
