### PR TITLE
Move x-frame-options/ into content-security-policy/

### PR DESCRIPTION
**Pull request by annevk**
The plan of record is for CSP to define X-Frame-Options (with small parts of it in HTML). Moving this directory there to reduce top-level directories (without owner).

Helps with #5915.

### CODE REVIEW

**Comment by mikewest** [comment]
Is that the plan of record? :) It's not clear to me that anyone would ever think to look in the CSP spec to determine how XFO is defined... Isn't that what RFC7034 is there for?

Less practically, defining the behavior in terms of `frame-ancestors` means that we need to do some sort of work to make sure we're not firing events/sending violation reports, etc. That seems strange.

**Comment by mikewest** [comment]
(If we actually define a `From-Origin` mechanism, perhaps we could combine it with XFO into some sort of "Limit your embedders" document?)

**Comment by annevk** [comment]
I thought that RFC didn't really match implementations for certain values and also doesn't define things in enough detail (e.g., doesn't integrate with HTML). (Pretty common for RFCs unfortunately...)

And CSP has an inline issue on addressing that, so that's why I thought that was the plan, but I'd be happy with other solutions.

**Comment by zcorpan** [comment]
@mikewest @annevk status on this?

**Comment by annevk** [comment]
It needs to be properly defined in something other than that RFC as that RFC doesn't really go into sufficient detail. My thinking was that CSP would be a good place as it already needs an equivalent algorithm for frame-ancestors.

**Comment by zcorpan** [comment]
Ok. Should I add an OWNERS file meanwhile?

**Comment by annevk** [comment]
Yeah, I guess that's reasonable unless @mikewest is ready to fix all the things here soon.

**Comment by annevk** [comment]
I'm happy to own this directory, FWIW.

**Comment by mikewest** [comment]
@mikewest is not going to fix all the things here soon. I think it's probably worth doing in the context of `from-origin`, since that seems quite related, but it's way down at the bottom of my todo list.

**Comment by annevk** [comment]
FWIW, I no longer think `From-Origin` should do ancestor checks.

**Pull request closed without merging**
