### PR TITLE
10 reftests for font-variant-east-asian

### PR DESCRIPTION
**Pull request by svgeesus**
To see these tests live, look at https://www.w3.org/People/chris/fwf/

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233017610)

# Firefox (nightly) #
Testing web-platform-tests at revision da648c575636b6db0cb15acafd54fb4dee8e6d46
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-01.html">/css/css-fonts-3/font-variant-east-asian-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-02.html">/css/css-fonts-3/font-variant-east-asian-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-03.html">/css/css-fonts-3/font-variant-east-asian-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-04.html">/css/css-fonts-3/font-variant-east-asian-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-05.html">/css/css-fonts-3/font-variant-east-asian-05.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-06.html">/css/css-fonts-3/font-variant-east-asian-06.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-07.html">/css/css-fonts-3/font-variant-east-asian-07.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-08.html">/css/css-fonts-3/font-variant-east-asian-08.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-09.html">/css/css-fonts-3/font-variant-east-asian-09.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-10.html">/css/css-fonts-3/font-variant-east-asian-10.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233017611)

# Sauce (safari) #
Testing web-platform-tests at revision da648c575636b6db0cb15acafd54fb4dee8e6d46
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-01.html">/css/css-fonts-3/font-variant-east-asian-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-02.html">/css/css-fonts-3/font-variant-east-asian-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-03.html">/css/css-fonts-3/font-variant-east-asian-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-04.html">/css/css-fonts-3/font-variant-east-asian-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-05.html">/css/css-fonts-3/font-variant-east-asian-05.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-06.html">/css/css-fonts-3/font-variant-east-asian-06.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-07.html">/css/css-fonts-3/font-variant-east-asian-07.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-08.html">/css/css-fonts-3/font-variant-east-asian-08.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-09.html">/css/css-fonts-3/font-variant-east-asian-09.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-10.html">/css/css-fonts-3/font-variant-east-asian-10.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233017612)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 59bb58dbb7983a41af5b82a6cfe91492e7bd8ece
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-01.html">/css/css-fonts-3/font-variant-east-asian-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-02.html">/css/css-fonts-3/font-variant-east-asian-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-03.html">/css/css-fonts-3/font-variant-east-asian-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-04.html">/css/css-fonts-3/font-variant-east-asian-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-05.html">/css/css-fonts-3/font-variant-east-asian-05.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-06.html">/css/css-fonts-3/font-variant-east-asian-06.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-07.html">/css/css-fonts-3/font-variant-east-asian-07.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-08.html">/css/css-fonts-3/font-variant-east-asian-08.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-09.html">/css/css-fonts-3/font-variant-east-asian-09.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-10.html">/css/css-fonts-3/font-variant-east-asian-10.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233017618)

# Chrome (unstable) #
Testing web-platform-tests at revision 59bb58dbb7983a41af5b82a6cfe91492e7bd8ece
Using browser at version 60.0.3100.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-01.html">/css/css-fonts-3/font-variant-east-asian-01.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-02.html">/css/css-fonts-3/font-variant-east-asian-02.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-03.html">/css/css-fonts-3/font-variant-east-asian-03.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-04.html">/css/css-fonts-3/font-variant-east-asian-04.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-05.html">/css/css-fonts-3/font-variant-east-asian-05.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-06.html">/css/css-fonts-3/font-variant-east-asian-06.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-07.html">/css/css-fonts-3/font-variant-east-asian-07.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-08.html">/css/css-fonts-3/font-variant-east-asian-08.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-09.html">/css/css-fonts-3/font-variant-east-asian-09.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5950/css/css-fonts-3/font-variant-east-asian-10.html">/css/css-fonts-3/font-variant-east-asian-10.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by svgeesus** [comment]
Nudge to @litherum for review :)

**Review by litherum — APPROVED** [review]

**Review by gsnedders — APPROVED** [review]
r=@litherum

**Pull request merged**
