### PR TITLE
Add a check if `substitutions` exists

### LINKED ISSUE #46940: `testharness.js` throws in some cases
When I tried to update wpt for jsdom, I noticed that `testharness.js` throws an exception in some tests.
``` console
TypeError: Cannot read properties of undefined (reading 'arguments.length')
    at do_substitution (http://web-platform.test:10000/resources/testharness.js:4417:49)
    at substitute_children (http://web-platform.test:10000/resources/testharness.js:4448:32)
    at substitute_single (http://web-platform.test:10000/resources/testharness.js:4461:13)
    at substitute (http://web-platform.test:10000/resources/testharness.js:4399:20)
    at substitute_children (http://web-platform.test:10000/resources/testharness.js:4439:39)
    at substitute_single (http://web-platform.test:10000/resources/testharness.js:4461:13)
    at substitute (http://web-platform.test:10000/resources/testharness.js:4399:20)
    at substitute_children (http://web-platform.test:10000/resources/testharness.js:4439:39)
    at substitute_single (http://web-platform.test:10000/resources/testharness.js:4461:13)
    at substitute (http://web-platform.test:10000/resources/testharness.js:4399:20)
```

On line 4417, it tries to extract an element from the `substitutions[]` array, but there are cases where `substitutions` is not an `array` but `undefined`, so the error occurred there.

This can be fixed by changing line 4407 to set a default value.
```` javascript
function substitute_single(template, substitutions = [])
{
  // snip
}
````

### PR DESCRIPTION
**Pull request by asamuzaK**
Fix #46940

### CODE REVIEW

**Comment by Ms2ger** [comment]
Why is the argument undefined, though?

**Comment by asamuzaK** [comment]
I do not know why.
It may be a jsdom specific issue.

Here's a simple way to reproduce the issue.
* Save a clone of [jsdom](https://github.com/jsdom/jsdom) to your local PC.
* Copy the latest source of `https://raw.githubusercontent.com/web-platform-tests/wpt/master/resources/testharness.js` and paste it into local `jsdom/test/web-platform-tests/tests/resources/testharness.js`.
* Run `npm test`.

**Comment by asamuzaK** [comment]
I took a brief look at the source.

In L4514:
``` javascript
    function render(template, substitutions, output_document)
```
`render()` accepts 3 arguments, and the 2nd is the `substitutions`.

However, for example, in L4290, only 1 argument is specified.
So `substitutions` will be `undefined`.
```javascript
            const asserts_output = render(
                ["details", {},
                    ["summary", {}, "Asserts run"],
                    ["table", {}, ""] ]);
```

By the way, the previous PR had an array as the default value, which was a mistake.
`substitutions[components[i + 1]]` is a property of `substitutions`.
```javascript
substitutions = {
  [components[i + 1]]: foo
}
```

So, fixed default value to `substitutions = {}`.
Also, removed capture in regexp which is not used.

**Comment by asamuzaK** [comment]
Added check that `substitutions` exists and `break` if not.

**Comment by asamuzaK** [comment]
Ready for review now.
Please take a look.

**Review by domenic — APPROVED** [review]
Since this is blocking jsdom from using the WPT framework, and @asamuzaK has explained how the existing code is buggy (e.g. sometimes calling a 3-argument function with one argument), let me merge this. It is still somewhat mysterious that we haven't seen the bug trigger outside of jsdom contexts, but this is still worth merging.

Edit: well, I guess I'm blocked by code-owners from actually merging. But let me _request_ that this be merged...

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
