### PR TITLE
Add tests for PaymentResponse.retry()

### PR DESCRIPTION
**Pull request by marcoscaceres**
* Tests for https://github.com/w3c/payment-request/pull/720

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@mnoorenberghe, when possibly, would appreciate review of these tests - so I can land the first part of `retry()`.

**Comment by marcoscaceres** [comment]
@domenic, I added two manual (😿) tests for "fully active", based on `PaymentRequest.show()`'s tests... 

 1.  Immediate check `.retry()` being called on document that is not fully active.
 1.  After `.retry()` is called, the then document becomes not fully active.

**Comment by marcoscaceres** [comment]
Gentle ping, fellow reviewers 🍰

**Comment by domenic** [comment]
Sorry, I don't have the bandwidth for this :(. Hopefully anyone who's planning to implement would be willing to review?

**Comment by marcoscaceres** [comment]
Np, maybe @rsolomakhin?

**Review by rsolomakhin — APPROVED** [review]

**Pull request merged**
