### PR TITLE
Update metadata for http2-websocket.sub.h2.any.js

### PR DESCRIPTION
**Pull request by WeizhongX**
PR 37496 is blocked due to an unexpected pass on this test. Update metadata to reflect the state of the art.

### CODE REVIEW

**Comment by WeizhongX** [comment]
Hi @KyleJu @DanielRyanSmith, can either of you help approve this PR so that we can unblock #37496? Thanks!

**Review by DanielRyanSmith — APPROVED** [review]

**Comment by WeizhongX** [comment]
self._send_message(cmd_id, "complete", "error")
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 757, in _send_message
    self.protocol.testdriver.send_message(cmd_id, message_type, status, message=message)
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 267, in send_message
    self.webdriver.execute_script("window.postMessage(%s, '*')" % json.dumps(obj))
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 782, in execute_script
    return self.send_session_command("POST", "execute/sync", body)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 661, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 625, in send_command
    raise err
webdriver.error.InvalidSessionIdException: invalid session id (404): invalid session id

Remote-end stacktrace:

0   chromedriver                        0x0000000100d89562 chromedriver + 4961634
1   chromedriver                        0x0000000100d0bce3 chromedriver + 4447459
2   chromedriver                        0x000000010090094d chromedriver + 207181
3   chromedriver                        0x000000010092e745 chromedriver + 395077
4   chromedriver                        0x000000010092fca7 chromedriver + 400551
5   chromedriver                        0x0000000100d44151 chromedriver + 4677969
6   chromedriver                        0x0000000100d5d13a chromedriver + 4780346
7   chromedriver                        0x0000000100d5c96b chromedriver + 4778347
8   chromedriver                        0x0000000100d5d955 chromedriver + 4782421
9   chromedriver                        0x0000000100d64659 chromedriver + 4810329
10  chromedriver                        0x0000000100d5dd2d chromedriver + 4783405
11  chromedriver                        0x0000000100d35abe chromedriver + 4618942
12  chromedriver                        0x0000000100d7c998 chromedriver + 4909464
13  chromedriver                        0x0000000100d7cabd chromedriver + 4909757
14  chromedriver                        0x0000000100d9282d chromedriver + 4999213
15  libsystem_pthread.dylib             0x00007ff8198724e1 _pthread_start + 125
16  libsystem_pthread.dylib             0x00007ff81986df6b thread_start + 15
 5:51.69 INFO Got 3 unexpected results, with 0 unexpected passes

**Comment by WeizhongX** [comment]
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 358 checks (208 subtests, 150 tests)
Expected results: 354 (2 known intermittents)
Skipped: 1 tests
Unexpected results: 3
  test: 3 (3 error)

Known Intermittent Results
--------------------------
/infrastructure/testdriver/actions/crossOrigin.sub.html
  KNOWN-INTERMITTENT-FAIL Actions in cross-origin iframe - Uncaught Error: assert_unreached: actions failed Reached unreachable code
    at http://web-platform.test:8000/infrastructure/testdriver/actions/crossOrigin.sub.html:17:9
/infrastructure/testdriver/click_iframe_crossorigin.sub.html
  KNOWN-INTERMITTENT-FAIL TestDriver click on a document in an iframe - Uncaught Error: assert_unreached: click failed Reached unreachable code
    at http://web-platform.test:8000/infrastructure/testdriver/click_iframe_crossorigin.sub.html:15:9

Unexpected Results
------------------
/infrastructure/testdriver/actions/multiTouchPointsReleaseSecondPoint.html
  ERROR /infrastructure/testdriver/actions/multiTouchPointsReleaseSecondPoint.html - invalid session id
Traceback (most recent call last):
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 740, in process_action
    result = action_handler(payload)
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/actions.py", line 112, in __call__
    self.protocol.action_sequence.send_actions({"actions": actions})
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 249, in send_actions
    self.webdriver.actions.perform(actions['actions'])
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 283, in perform
    actions = self.session.send_session_command("POST", "actions", body)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 661, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 625, in send_command
    raise err
webdriver.error.UnknownErrorException: unknown error (500): unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=110.0.5478.5)

Remote-end stacktrace:

**Comment by WeizhongX** [comment]
The test passed after retry.

**Pull request merged**
