### PR TITLE
Fix resource-timing.html document.domain test - take 2

### PR DESCRIPTION
**Pull request by yoavweiss**
Replaces https://github.com/web-platform-tests/wpt/pull/14636
Because [we can't make sure a test loads onto the right domain](https://github.com/web-platform-tests/wpt/pull/14636#discussion_r243443726), I extracted the document.domain tests from the larger file and only loaded that test on the right domain, as an external document.

### CODE REVIEW

**Comment by Hexcles** [comment]
Just to double check the domain setup here: we have a test page that loads `http://www.web-platform.test:PORT/...` in a new window, which then loads another `http://www.web-platform.test:PORT/...` in an iframe, and finally the iframe sets its `document.domain` to `web-platform.test` (without `www`). Is this what you want?

**Comment by yoavweiss** [comment]
> Just to double check the domain setup here: we have a test page that loads `http://www.web-platform.test:PORT/...` in a new window, which then loads another `http://www.web-platform.test:PORT/...` in an iframe, and finally the iframe sets its `document.domain` to `web-platform.test` (without `www`). Is this what you want?

Indeed. The test makes sure that a same domain resource without TAO remains visible even after it changed its document.domain to a different origin.

**Review by Hexcles — APPROVED** [review]
Alright, then this fix LGTM.

(I was going to save my approval because I don't know about resource timing, but after a closer look, the PR mostly just restructured the test to achieve the desired domain setup.)

**Comment by yoavweiss** [comment]
Thanks for reviewing! :)

**Pull request merged**
