### PR TITLE
Update the cssom IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by lukebjerring** [comment]
Note that the `namespace` chunk is manually commented out, as it's blocked by https://github.com/web-platform-tests/wpt/issues/7583

**Comment by lukebjerring** [comment]
This is now ready for review.

**Comment by foolip** [comment]
Tried the changes locally and it looks good, there are slightly fewer tests but it seems to be because tests like "Unscopable handled correctly for escape(CSSOMString) on CSS" no longer exist. ("CSS namespace: operation escape(CSSOMString)" does.) The number of failing tests is the same.

I expected the switch from `interface CSS` to `namespace CSS` to break other tests because css-conditional.idl and css-paint-api.idl still have `partial interface CSS`, but that didn't happen for either test, the test names just changed and still work. Filed: https://github.com/web-platform-tests/wpt/issues/12123

Also updated some specs:
https://github.com/w3c/css-houdini-drafts/pull/784
https://github.com/WICG/CSS-Parser-API/pull/12

@lukebjerring, do you think we should just merge this and let the IDL files be in an inconsistent state for a while as long as it doesn't break things, or line up a bunch of PRs and merge them at once?

**Comment by lukebjerring** [comment]
Probably a good idea for this to update all of the `partial namespace` defs at the same time.

**Comment by foolip** [comment]
The two spec PRs have landed. https://github.com/w3c/css-houdini-drafts/pull/784 has propagated to reffy in https://github.com/tidoust/reffy-reports/commit/ee634c9a84ed4f0ae281cdbdf118dbafec2ac8e8 but https://github.com/WICG/CSS-Parser-API/pull/12 will need @tabatkins to regenerate index.html first.

**Comment by tabatkins** [comment]
Regenerated CSS-Parser-API

**Comment by foolip** [comment]
Cool, in 24 hours or so https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/CSS-Parser-API.idl ought to be updated.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Tested locally, it works!

**Pull request merged**
