### PR TITLE
[css-ui-3] Add tests for the resize property

### PR DESCRIPTION
**Pull request by gsnedders**
Originally posted as https://github.com/w3c/csswg-test/pull/1193 by @frivoal on 31 Jan 2017, 08:09 UTC:

> Not a whole lot of automated tests in this Pull Request, but I think we're going to have to live with this due to the nature of the feature.
> 
> 
> ---
> This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1193)
>

### CODE REVIEW

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1193#issuecomment-276299940 by @syncbot on 31 Jan 2017, 08:09 UTC:

> ### Automatic validation checks of commit 3141120 passed.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1193#issuecomment-289359610 by @syncbot on 27 Mar 2017, 05:49 UTC:

> ### Automatic validation checks of commit f0ec05b discovered the following problem:
> 
> In [css-ui-3/support/orange.svg](https://github.com/w3c/csswg-test/blob/f0ec05b6a91cbda4c42df759c577a5386361c132/css-ui-3/support/orange.svg):
> * Missing &lt;g id='testmeta'> element
>

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1193#issuecomment-289360522 by @frivoal on 27 Mar 2017, 05:56 UTC:

> @fantasai 
> 
> All the issues you reported should be addressed now, including the missing tests for min/max-width/height.
> 
> The missing `<g id='testmeta'>` that syncbot is complaining about is not as far as I know an actuall requirement we have, and we already have svg images without it, so I'm ignoring this warning. If I should not ignore it, is there documentation of what I'm supposed to put there?

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1193#issuecomment-289361373 by @syncbot on 27 Mar 2017, 06:03 UTC:

> ### Automatic validation checks of commit e550a85 discovered the following problem:
> 
> In [css-ui-3/support/orange.svg](https://github.com/w3c/csswg-test/blob/e550a8516f47c3d4cdc42a6262467703736e0a0f/css-ui-3/support/orange.svg):
> * Missing &lt;g id='testmeta'> element
>

**Comment by csswg-test-issue-mover** [comment]
**Out of order; should follow https://github.com/w3c/web-platform-tests/pull/5386#issuecomment-291919561.**

Originally posted as https://github.com/w3c/csswg-test/pull/1193#pullrequestreview-29039478 by @fantasai on 25 Mar 2017, 04:18 UTC:

> You misspelled resize in all of the titles.

**Comment by csswg-test-issue-mover** [comment]
**Out of order; should follow the above after https://github.com/w3c/web-platform-tests/pull/5386#issuecomment-291919561.**

Originally posted as https://github.com/w3c/csswg-test/pull/1193#pullrequestreview-29039622 by @fantasai on 25 Mar 2017, 04:28 UTC:

> * Need to fix typos in titles.
> * It would be better if all of the tests used a blue (or orange) box instead of the sheep. This way the tester doesn't need to be distracted by how the image resizes (e.g. aspect ratio skews or not, whether the sheep adjusts with the size of the iframe boundaries or not, etc).
> * The verification in resize-015 needs to check whether the width/height was actually changed -- they need to be not equal to the sizes set in the CSS.
> * resize-15, resize-016, etc. need their titles updated to reflect what's being tested.
> * resize-016, resize-17 need to test that the non-resizable dimension is not resizable.
> * since we can, resize-018 should check that the size is actually maintained by storing the size and then comparing it before/after resetting
> * you're missing tests that include min/max-width/height (but that can be a separate PR, just mentioning it here)

**Comment by gsnedders** [comment]
Sorry for copying this over out-of-order like this, but it was by far the easiest way.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218949006)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 6cea3e3d72e6c84fe5df05037cc51c852075b6f3
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218949007)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 6cea3e3d72e6c84fe5df05037cc51c852075b6f3
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Review by fantasai — APPROVED** [review]

**Pull request merged**
