### PR TITLE
[idlharness.js] Support subsetTestByKey in idlharness

### LINKED ISSUE #11413: /dom/interfaces.html is disabled in webkit
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate+what's+up+with+this+test:

Path | Products | Results | Bugs
-- | -- | -- | --
/dom/interfaces.html | webkit | [ Skip ] | https://webkit.org/b/148546

This and html/dom/interfaces.https.html could be split up using `subsetTest`.

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #11413.

### CODE REVIEW

**Comment by gsnedders** [comment]
Will this not easily result in subtests moving, given idlharness.js adding/removing tests will change the number produced? A bit painful for expectation management, IMO.

**Comment by zcorpan** [comment]
Yes. Could split more semantically.

**Comment by zcorpan** [comment]
@gsnedders PTAL

**Review by gsnedders — APPROVED** [review]
This LGTM. Would be interested in opinions from others, though?

**Comment by gsnedders** [comment]
One quick thought: I wonder if `subtestByName` is really the best name? To me, that made me think it used `test.name` at first glance, which it doesn't. I wonder if something like `subtestByKey(key, callback, ...)` makes more sense?

**Comment by zcorpan** [comment]
Renamed to key.

**Pull request merged**
