### PR TITLE
Remove @boggydigital as SVG reviewer

### PR DESCRIPTION
**Pull request by foolip**
@boggydigital has not accepted the org invite and thus cannot be assigned by @wpt-pr-bot.

### CODE REVIEW

**Comment by foolip** [comment]
@bobbydigital please speak up if this was an oversight. You should be able to see/accept the invite at https://github.com/web-platform-tests.

**Review by dirkschulze — APPROVED** [review]
Approving so that the PR is unblocked. However, we should wait a week at least before merging. CC @boggydigital

**Comment by boggydigital** [comment]
My bad - must have left the org when I briefly left Microsoft last year. Now that I'm back - I would be happy to help with the reviews as much as I can.

**Comment by AmeliaBR** [comment]
Closing then, as no change required.

**Comment by foolip** [comment]
Thanks @boggydigital, looks like you've accepted the invite now and can be assigned.

**Pull request closed without merging**
