### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=169194

### PR DESCRIPTION
**Pull request by youennf**
The following changes since commit 51916efd137dc7e1d36eb6f7db497fde2c274ab8:

  Merge pull request #5189 from fippo/sld-test (2017-03-21 20:29:03 +0100)

are available in the git repository at:

  https://github.com/youennf/web-platform-tests.git webkit-169194

for you to fetch changes up to bbb149e95d357660f10974c6fd2ec24b4b22a2ec:

  WebKit export of https://bugs.webkit.org/show_bug.cgi?id=169194 (2017-03-21 21:24:51 -0700)

----------------------------------------------------------------
Youenn Fablet (1):
      WebKit export of https://bugs.webkit.org/show_bug.cgi?id=169194

 fetch/api/cors/cors-preflight.js | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/fetch/api/cors/cors-preflight.js b/fetch/api/cors/cors-preflight.js
index e95a93f8de..55b524050e 100644
--- a/fetch/api/cors/cors-preflight.js
+++ b/fetch/api/cors/cors-preflight.js
@@ -99,4 +99,6 @@ corsPreflight("CORS [GET] [several headers], server refuses", corsUrl, "GET", fa
 corsPreflight("CORS [PUT] [several headers], server allows", corsUrl, "PUT", true, headers, safeHeaders);
 corsPreflight("CORS [PUT] [several headers], server refuses", corsUrl, "PUT", false, headers, safeHeaders);
 
+corsPreflight("CORS [PUT] [only safe headers], server allows", corsUrl, "PUT", true, null, safeHeaders);
+
 done();

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5190/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213697976)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 28729538f4d838b0c8ef0c9823b4b34af1d56a5c
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-worker.html">/fetch/api/cors/cors-preflight-worker.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    | `{}`     |
| `CORS [DELETE], server refuses`                       | PASS    | `{}`     |
| `CORS [PUT], server allows`                           | PASS    | `{}`     |
| `CORS [PUT], server refuses`                          | PASS    | `{}`     |
| `CORS [PATCH], server allows`                         | PASS    | `{}`     |
| `CORS [PATCH], server refuses`                        | PASS    | `{}`     |
| `CORS [NEW], server allows`                           | PASS    | `{}`     |
| `CORS [NEW], server refuses`                          | PASS    | `{}`     |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    | `{}`     |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    | `{}`     |
| `CORS [GET] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [GET] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [PUT] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [only safe headers], server allows`       | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight.html">/fetch/api/cors/cors-preflight.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    |          |
| `CORS [DELETE], server refuses`                       | PASS    |          |
| `CORS [PUT], server allows`                           | PASS    |          |
| `CORS [PUT], server refuses`                          | PASS    |          |
| `CORS [PATCH], server allows`                         | PASS    |          |
| `CORS [PATCH], server refuses`                        | PASS    |          |
| `CORS [NEW], server allows`                           | PASS    |          |
| `CORS [NEW], server refuses`                          | PASS    |          |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    |          |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    |          |
| `CORS [GET] [several headers], server allows`         | PASS    |          |
| `CORS [GET] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [several headers], server allows`         | PASS    |          |
| `CORS [PUT] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [only safe headers], server allows`       | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213697977)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 28729538f4d838b0c8ef0c9823b4b34af1d56a5c
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-worker.html">/fetch/api/cors/cors-preflight-worker.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    | `{}`     |
| `CORS [DELETE], server refuses`                       | PASS    | `{}`     |
| `CORS [PUT], server allows`                           | PASS    | `{}`     |
| `CORS [PUT], server refuses`                          | PASS    | `{}`     |
| `CORS [PATCH], server allows`                         | PASS    | `{}`     |
| `CORS [PATCH], server refuses`                        | PASS    | `{}`     |
| `CORS [NEW], server allows`                           | PASS    | `{}`     |
| `CORS [NEW], server refuses`                          | PASS    | `{}`     |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    | `{}`     |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    | `{}`     |
| `CORS [GET] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [GET] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [PUT] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [only safe headers], server allows`       | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight.html">/fetch/api/cors/cors-preflight.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    |          |
| `CORS [DELETE], server refuses`                       | PASS    |          |
| `CORS [PUT], server allows`                           | PASS    |          |
| `CORS [PUT], server refuses`                          | PASS    |          |
| `CORS [PATCH], server allows`                         | PASS    |          |
| `CORS [PATCH], server refuses`                        | PASS    |          |
| `CORS [NEW], server allows`                           | PASS    |          |
| `CORS [NEW], server refuses`                          | PASS    |          |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    |          |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    |          |
| `CORS [GET] [several headers], server allows`         | PASS    |          |
| `CORS [GET] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [several headers], server allows`         | PASS    |          |
| `CORS [PUT] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [only safe headers], server allows`       | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213700301)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 9b448987f6039ecacb22f0a5709f582e6782eaff
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-star-worker.html">/fetch/api/cors/cors-preflight-star-worker.html</a></summary>


|                                                   Subtest                                                    | Results |                                                       Messages                                                      |
|--------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------|
|                                                                                                              | OK      |                                                                                                                     |
| `CORS that succeeds with credentials: false; method: GET (allowed: get); header: X-Test,1 (allowed: x-test)` | PASS    | `{}`                                                                                                                |
| `CORS that succeeds with credentials: false; method: SUPER (allowed: *); header: X-Test,1 (allowed: x-test)` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: NetworkError when attempting to fetch resource."` |
| `CORS that succeeds with credentials: false; method: OK (allowed: *); header: X-Test,1 (allowed: *)`         | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: NetworkError when attempting to fetch resource."` |
| `CORS that fails with credentials: true; method: OK (allowed: *); header: X-Test,1 (allowed: *)`             | PASS    | `{}`                                                                                                                |
| `CORS that fails with credentials: true; method: PUT (allowed: *); header: undefined (allowed: )`            | PASS    | `{}`                                                                                                                |
| `CORS that fails with credentials: true; method: PUT (allowed: put); header: undefined (allowed: *)`         | PASS    | `{}`                                                                                                                |
| `CORS that fails with credentials: true; method: GET (allowed: get); header: X-Test,1 (allowed: *)`          | PASS    | `{}`                                                                                                                |
| `CORS that fails with credentials: true; method: GET (allowed: *); header: X-Test,1 (allowed: *)`            | PASS    | `{}`                                                                                                                |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-star.html">/fetch/api/cors/cors-preflight-star.html</a></summary>


|                                                   Subtest                                                    | Results |                                                       Messages                                                      |
|--------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------|
|                                                                                                              | OK      |                                                                                                                     |
| `CORS that succeeds with credentials: false; method: GET (allowed: get); header: X-Test,1 (allowed: x-test)` | PASS    |                                                                                                                     |
| `CORS that succeeds with credentials: false; method: SUPER (allowed: *); header: X-Test,1 (allowed: x-test)` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: NetworkError when attempting to fetch resource."` |
| `CORS that succeeds with credentials: false; method: OK (allowed: *); header: X-Test,1 (allowed: *)`         | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: NetworkError when attempting to fetch resource."` |
| `CORS that fails with credentials: true; method: OK (allowed: *); header: X-Test,1 (allowed: *)`             | PASS    |                                                                                                                     |
| `CORS that fails with credentials: true; method: PUT (allowed: *); header: undefined (allowed: )`            | PASS    |                                                                                                                     |
| `CORS that fails with credentials: true; method: PUT (allowed: put); header: undefined (allowed: *)`         | PASS    |                                                                                                                     |
| `CORS that fails with credentials: true; method: GET (allowed: get); header: X-Test,1 (allowed: *)`          | PASS    |                                                                                                                     |
| `CORS that fails with credentials: true; method: GET (allowed: *); header: X-Test,1 (allowed: *)`            | PASS    |                                                                                                                     |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213700302)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 9b448987f6039ecacb22f0a5709f582e6782eaff
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-star-worker.html">/fetch/api/cors/cors-preflight-star-worker.html</a></summary>


|                                                   Subtest                                                    | Results |                                       Messages                                      |
|--------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------|
|                                                                                                              | OK      |                                                                                     |
| `CORS that succeeds with credentials: false; method: GET (allowed: get); header: X-Test,1 (allowed: x-test)` | PASS    | `{}`                                                                                |
| `CORS that succeeds with credentials: false; method: SUPER (allowed: *); header: X-Test,1 (allowed: x-test)` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"` |
| `CORS that succeeds with credentials: false; method: OK (allowed: *); header: X-Test,1 (allowed: *)`         | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"` |
| `CORS that fails with credentials: true; method: OK (allowed: *); header: X-Test,1 (allowed: *)`             | PASS    | `{}`                                                                                |
| `CORS that fails with credentials: true; method: PUT (allowed: *); header: undefined (allowed: )`            | PASS    | `{}`                                                                                |
| `CORS that fails with credentials: true; method: PUT (allowed: put); header: undefined (allowed: *)`         | PASS    | `{}`                                                                                |
| `CORS that fails with credentials: true; method: GET (allowed: get); header: X-Test,1 (allowed: *)`          | PASS    | `{}`                                                                                |
| `CORS that fails with credentials: true; method: GET (allowed: *); header: X-Test,1 (allowed: *)`            | PASS    | `{}`                                                                                |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5190/fetch/api/cors/cors-preflight-star.html">/fetch/api/cors/cors-preflight-star.html</a></summary>


|                                                   Subtest                                                    | Results |                                       Messages                                      |
|--------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------|
|                                                                                                              | OK      |                                                                                     |
| `CORS that succeeds with credentials: false; method: GET (allowed: get); header: X-Test,1 (allowed: x-test)` | PASS    |                                                                                     |
| `CORS that succeeds with credentials: false; method: SUPER (allowed: *); header: X-Test,1 (allowed: x-test)` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"` |
| `CORS that succeeds with credentials: false; method: OK (allowed: *); header: X-Test,1 (allowed: *)`         | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"` |
| `CORS that fails with credentials: true; method: OK (allowed: *); header: X-Test,1 (allowed: *)`             | PASS    |                                                                                     |
| `CORS that fails with credentials: true; method: PUT (allowed: *); header: undefined (allowed: )`            | PASS    |                                                                                     |
| `CORS that fails with credentials: true; method: PUT (allowed: put); header: undefined (allowed: *)`         | PASS    |                                                                                     |
| `CORS that fails with credentials: true; method: GET (allowed: get); header: X-Test,1 (allowed: *)`          | PASS    |                                                                                     |
| `CORS that fails with credentials: true; method: GET (allowed: *); header: X-Test,1 (allowed: *)`            | PASS    |                                                                                     |

</details>
</details>

**Comment by annevk** [comment]
This was replaced with #5191?

**Pull request closed without merging**
