### PR TITLE
Recurse to nested arrays in reading arrays

### PR DESCRIPTION
**Pull request by Honry**
Use assert_object_equals instead of assert_array_equals
  which would compare individual values in nested arrays

### CODE REVIEW

**Comment by Honry** [comment]
@kenchris, PTAL.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22171)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/321283356)

**Review by pozdnyakov — APPROVED** [review]
lgtm

**Comment by Honry** [comment]
@pozdnyakov, thanks for your review.

**Pull request merged**
