### PR TITLE
Add Reporting API IDL file + test

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@dcreager @igrigorik @mikewest @paulmeyer90, you are listed as editors on https://w3c.github.io/reporting/, can you confirm you're OK with getting reviews for changes in the test suite?

**Comment by dcreager** [comment]
:+1: for me

**Review by lukebjerring — APPROVED** [review]

**Comment by paulmeyer90** [comment]
Yes, sounds good!

**Comment by foolip** [comment]
I've confirmed that @igrigorik is OK with this over chat, and @mikewest is on a mountain, so I'll just drop him to get this landed. (It blocks https://github.com/web-platform-tests/wpt/pull/12497.)

**Pull request merged**
