### PR TITLE
Move old-tests/submission/Opera/script_scheduling/ into html/

### PR DESCRIPTION
**Pull request by foolip**
Some of these tests may not be correct per spec, but vetting them all is
more work than moving them and improving by investigating as they come
up naturally.

Fixes https://github.com/w3c/web-platform-tests/issues/3850.

### CODE REVIEW

**Review by gsnedders — APPROVED** [review]

**Review by domenic — APPROVED** [review]
If @gsnedders thinks moving them all is the right move, then that works for me.

**Comment by gsnedders** [comment]
@foolip I wonder if with a small bit of scripting someone can sit down with a table of `<title>` elements and come up with new filenames in not too long? Maybe worth doing that before the move, but I'll leave that up to you and @domenic as to whether that's worthwhile?

**Comment by foolip** [comment]
Everything has a pretty title, here they are:
- 001.html: scheduler: inline in markup 
- 002.html: scheduler: external in markup 
- 003.html: scheduler: inline+external in markup 
- 004.html: scheduler: external+inline in markup 
- 005.html: scheduler: document.write inline in markup 
- 006.html: scheduler: document.write inline - multiple
- 007.html: scheduler: document.write external
- 008.html: scheduler: document.write external - multiple
- 009.html: scheduler: document.write external - multiple with doc.write
- 010.html: scheduler: document.write external + inline - multiple with doc.write
- 011.html: scheduler: document.write external + inline - multiple with doc.write + subsequent markup
- 012.html: scheduler: document.write external and onload events 
- 013.html: scheduler: DOM added inline script earlier in document
- 014.html: scheduler: SCRIPT elements that move themselves in DOM 
- 015.html: scheduler: DOM added inline+external+inline script earlier in document
- 015a.html: scheduler: DOM added inline+external+inline script earlier in document
- 016.html: scheduler: DOM added inline script later in document
- 017.html: scheduler: multiple DOM added scripts later in document
- 018.html: scheduler: DOM added scripts and doc.write
- 019.html: scheduler: DOM added scripts and event handling 
- 020.html: scheduler: DOM added script with data: URL 
- 021.html: scheduler: DOM added script with javascript: URL 
- 022.html: scheduler: DOM added script, late .src 
- 023.html: scheduler: DOM added script, even later .src 
- 024.html: scheduler: DOM added script, .src set twice
- 025.html: scheduler: DOM added script, .src set on script with content
- 026.html: scheduler: doc write added script, .src set later
- 027.html: scheduler: doc write added script with content, .src set later
- 028.html: scheduler: javascript: URL
- 029.html: scheduler: javascript: URL in HREF
- 030.html: scheduler: javascript: URL in HREF, onclick handler
- 031.html: scheduler: focus and blur events
- 032.html: scheduler: innerHTML and scripts
- 033.html: scheduler: innerHTML and scripts moved in DOM
- 034.html: scheduler: innerHTML adding frames with JS in
- 035.html: scheduler: innerHTML adding frames with JS in and moving scripts
- 036.html: scheduler: DOM cloning
- 037.html: scheduler: DOM movement with appendChild, inline
- 038.html: scheduler: DOM movement with appendChild, external
- 039.html: scheduler: IFRAMEs added with DOM
- 040.html: scheduler: IFRAMEs added with DOM (innerHTML), javascript: URL
- 041.html: scheduler: document.write scripts that write scripts
- 042.html: scheduler: DOM mutation events when adding scripts: DOMNodeInserted 
- 043.html: scheduler: DOM mutation events when adding external scripts: DOMNodeInserted 
- 044.html: scheduler: DOM mutation events when adding scripts: DOMNodeInsertedIntoDocument 
- 045.html: scheduler: DOM mutation events when adding external scripts: DOMNodeInsertedIntoDocument 
- 046.html: scheduler: no readystatechange events when adding external scripts 
- 047.html: scheduler: adding and removing external script 
- 048.html: scheduler: adding inline script which sets its own .src 
- 049.html: scheduler: adding external script but removeAttribute( src ) before it runs
- 050.html: scheduler: adding external script that removes all scripts from document
- 051.html: scheduler: interaction of parsing and script execution - script added through DOM
- 052.html: scheduler: interaction of parsing and script execution - external script 
- 053.html: scheduler: adding external script that removes itself from document when loading
- 054.html: scheduler: removing newly inserted script from DOMNodeInserted handler - external script 
- 055.html: scheduler: removing newly inserted script from DOMNodeInserted handler - inline script 
- 056.html: scheduler: appending code to initially empty SCRIPT tag in DOM 
- 057.html: scheduler: appending code to initially non-empty SCRIPT tag in DOM (whitespace only) 
- 058.html: scheduler: appending code to initially non-empty SCRIPT tag in DOM (comment only) 
- 059.html: scheduler: appending code to initially non-empty SCRIPT tag in DOM after removing its initial child 
- 060.html: scheduler: appending code to initially non-empty SCRIPT tag in DOM after setting textContent/innerHTML
- 061.html: scheduler: cloneNode and script execution
- 062.html: scheduler: cloneNode (shallow) and script execution
- 063.html: scheduler: cloneNode (deep) of the currently executing script 
- 064.html: scheduler: cloneNode with external script
- 065.html: scheduler: cloneNode with external script, changed .src
- 066.html: scheduler: cloneNode with external script, removing .src and adding content
- 067.html: scheduler: is a script with syntax error marked as "has run"? 
- 068.html: scheduler: external script and parsing of markup added with document.write 
- 069.html: scheduler: external files added through DOM should not block further parsing while loading
- 070.html: scheduler: document.write into IFRAME a script that adds a SCRIPT through DOM
- 071.html: scheduler: document.write several scripts into IFRAME 
- 072.html: scheduler: document.write into IFRAME a script that creates new inline script in parent 
- 073.html: scheduler: document.write into IFRAME a script that creates new external script in parent 
- 074.html: scheduler: document.write into IFRAME a script that creates new inline script in parent that again adds script to IFRAME 
- 075.html: dispatchEvent from child frame during document.write :-o 
- 076.html: scheduler: adding and removing external and inline scripts 
- 077.html: adding several types of scripts through the DOM and removing some of them confuses scheduler 
- 078.html: adding several types of scripts through the DOM and removing some of them confuses scheduler (slow-loading scripts) 
- 079.html: setting location to javascript URL from event handler 
- 080.html: scheduler: IFRAMEs added with DOM (appendChild), javascript: URL
- 081.html: scheduler: slow loading external script added with DOM (appendChild)
- 082.html: scheduler: multiple slow loading external scripts added with DOM (appendChild)
- 083.html: scheduler: event listener defined by script in a document in history
- 084.html: scheduler: event listener defined by script in a removed IFRAME
- 085.html: scheduler: async script and slow-loading defer script
- 086.html: scheduler: async script and slow-loading async script
- 087.html: scheduler: multiple defer scripts, one slow loading
- 088.html: scheduler: multiple scripts with defer and async attributes
- 089.html: scheduler: async attribute on inline script
- 090.html: scheduler: defer attribute on inline script
- 091.html: scheduler: force-async off on non-parser-inserted script
- 092.html: scheduler: defer script and slow-loading non-async external script
- 094.html: scheduler: parser-created defer script after document load
- 095.html: scheduler: slow-loading script added from defer blocking load event
- 096.html: scheduler: defer script added from document.write relative to DOMContentLoaded
- 097.html: scheduler: slow-loading async script added from document.write
- 099.html: scheduler: defer adding iframe containing script
- 101.html: scheduler: defer script after initial onload event
- 102.html: scheduler: defer script after initial onload event
- 103.html: scheduler: removing defer attribute at runtime
- 104.html: scheduler: adding defer attribute at runtime
- 105.html: scheduler: adding async attribute at runtime
- 106-import.html: scheduler: stylesheets blocking scripts
- 106-noimport.html: scheduler: stylesheets blocking scripts
- 107-import.html: scheduler: stylesheets blocking scripts document.write
- 107-noimport.html: scheduler: stylesheets blocking scripts document.write
- 108.html: scheduler: javascript URL in iframe
- 109.html: scheduler: javascript URL in iframe, src set via DOM
- 110.html: scheduler: removing defer script at runtime
- 111.html: scheduler: removing async attribute at runtime
- 112.html: scheduler: removing async attribute at runtime, script also has defer attribute
- 113.html: scheduler: Altering DOM using innerHTML during parse 
- 114.html: scheduler: Changing src of defer script before it runs 
- 115.html: scheduler: Removing src of defer script before it runs 
- 116.html: scheduler: adding script to head of frameset document
- 117.html: scheduler: inline script created with createContextualFragment
- 118.html: scheduler: external script created with createContextualFragment
- 119.html: scheduler: external defer script created with createContextualFragment
- 120.html: scheduler: script created without a window 
- 121.html: scheduler: altering the type attribute 
- 122.html: scheduler: altering the type attribute and adding/removing external script 
- 123.html: scheduler: altering the type attribute and adding/removing external script with async=false 
- 124.html: scheduler: altering the type attribute and changing script data inline script 
- 125.html: scheduler: altering the type attribute and changing script data external script 
- 126.html: scheduler: altering the type attribute and changing script data external script async=false 
- 127.html: scheduler: appending non-text children to script 
- 128.html: scheduler: appending script element to script 
- 129.html: scheduler: appending multiple script elements
- 130.html: scheduler: appending external script element to script 
- 131.html: scheduler: inline svg script 
- 132.html: scheduler: external svg script 
- 133.html: scheduler: inline HTML script added by SVG script 
- 134.html: scheduler: external HTML script added by SVG script 
- 135.html: scheduler: external SVG script added by SVG script 
- 136.html: scheduler: DOM added external SVG script, force-async? 
- 137.html: scheduler: SVG script empty xlink:href
- 138.html: scheduler: SVG script nested inlines
- 139.html: scheduler: SVG script nested external in inline
- 140.html: scheduler: SVG script nested inline in external
- 141.html: scheduler: SVG inline script that document.writes inline script 
- 142.html: scheduler: SVG inline script that document.writes external script 
- 143.html: scheduler: SVG nested inline script that document.writes inline script 
- 144.html: scheduler: SVG inline script changing the type attribute 
- 145.html: scheduler: SVG inline script adding text to empty script 
- 146.html: scheduler: SVG script adding src attribute 
- 147.html: scheduler: insert multiple inline scripts; first script moves subsequent scripts 
- 148.html: scheduler: insert multiple inline scripts; first script deletes subsequent script 
- 149.html: scheduler: event/for attribute on script

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19037)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/282383503)

**Comment by foolip** [comment]
I could rename all the files based on the title, but that seems kinda pointless. I see some potential buckets like SVG, but think there would inevitably be a frustrating misc bucket. So I think it's better to leave it alone until someone comes along and wants to organize them.

**Comment by gsnedders** [comment]
@foolip We have failing lints which are previously whitelisted. I'd suggest just having a second commit that gets rid of the tabs and trailing whitespace, given anything changing them will have merge conflicts anyway.

**Comment by foolip** [comment]
OK, I've spent more time than I'd like to admit on getting the whitespace in better shape. I've added lint suppressions in the PR and will submit a separate PR to fix it after merging.

**Comment by foolip** [comment]
Or, actually, I'll put it in this PR but be sure to rebase and merge as two separate commits.

**Pull request merged**
