### PR TITLE
Update Safari Technology Preview to 99

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 99, 14610.1.1)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1310&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
I've triggered a full run of this in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=40671&view=results

It should be compared against https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=40667&view=results when that's done.

**Comment by foolip** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=416830016&run_id=393600011 shows significant regressions in pointerevents/ and webdriver/. @burg it looks like there might be a safaridriver regression here.

A bunch of tests in /infrastructure/testdriver/actions now appear as CRASH, although I doubt there's actually a crash here. I think I'll need to revive https://github.com/web-platform-tests/wpt/pull/18444 to debug this.

**Comment by foolip** [comment]
In https://github.com/web-platform-tests/wpt/pull/21369 I went over the verbose logs and filed https://bugs.webkit.org/show_bug.cgi?id=206646 based on that.

This appears serious enough that we shouldn't upgrade to STP 99, since it breaks more tests than it fixes. However, the run does finish, so if WebKit folks things having the results is still useful, we could merge this.

@burg @smfr WDYT?

**Comment by gsnedders** [comment]
From @burg in the WebKit bug:

> Unfortunately there is no workaround for this issue in STP99.

**Comment by foolip** [comment]
PR for STP 100 is up now: https://github.com/web-platform-tests/wpt/pull/21627

**Pull request closed without merging**
