### PR TITLE
Add interfaces/local-font-access.idl and test

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by foolip** [comment]
Per https://wpt.fyi/results/local-font-access/idlharness.any.html?sha=44c9ba5152&label=pr_head nobody has implemented this. https://github.com/WICG/local-font-access doesn't look abandoned, but I wonder what the implementation plans are. @inexorabletash do you know? Would it be useful to have this test added now?

**Comment by inexorabletash** [comment]
Implementation is in progress in Chrome, it's behind a flag and the API shape is in flux. I wouldn't bother to add IDL tests just yet.

**Comment by inexorabletash** [comment]
Implementation is in progress in Chrome, it's behind a flag and the API shape is in flux. I wouldn't bother to add IDL tests just yet.

**Comment by stephenmcgruer** [comment]
Ack, lets close this and let reffy keep updating https://github.com/web-platform-tests/wpt/pull/24207 but not merge it.

Once the API stabilizes a bit and Chromium ships an implementation, we can bring something like this back using the latest version from reffy.

**Pull request closed without merging**
