### PR TITLE
Increase maximum open files for each server process on Darwin (WebKit export)

### PR DESCRIPTION
**Pull request by gsnedders**
Export of https://bugs.webkit.org/show_bug.cgi?id=215829 & its regression fix https://bugs.webkit.org/show_bug.cgi?id=216823.

Delayed export to verify that this stopped the failures from happening, and we've not seen any over the past three days so I'm assume this fixed it.

### CODE REVIEW

**Review by Hexcles — COMMENTED** [review]
IIUC, RLIMIT_NOFILE is the limit on file descriptors. Do we not close the files after serving them? Or do we actually have 256 files opened together?

**Comment by Hexcles** [comment]
Note that this might have been answered in the WebKit issue which timed out loading for me...

**Comment by gsnedders** [comment]
@Hexcles remember that sockets are also FDs; it's quite possibly https://github.com/web-platform-tests/wpt/issues/8369 showing its face again (where the majority of FDs are TCP sockets in the TIME_WAIT state) combined with Darwin having a much lower default RLIMIT_NOFILE (256, versus 1024 on most of the Linux systems I've looked on) and the iOS bots running with multiple bots hitting a single server.

**Review by Hexcles — APPROVED** [review]
LGTM

Yeah and if we indeed never close the file descriptors, we'd run out of 2048 fairly quickly too...

**Pull request merged**
