### PR TITLE
Selection and document.open()

### PR DESCRIPTION
**Pull request by annevk**
Chrome fails this, interestingly enough, but Firefox and Safari both pass.

cc @bzbarsky @TimothyGu @domenic

### CODE REVIEW

**Comment by bzbarsky** [comment]
Which test assertion does Chrome fail?

**Comment by annevk** [comment]
That the object must be the same. Presumably also the final assertion as it passes the current test.

**Review by domenic — APPROVED** [review]
LGTM. Curious result. A Chrome bug would be great :).

**Comment by annevk** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=941913

**Comment by yosinch** [comment]
As of today, Blink's Selection comes from `document.getSelection()`. `window.getSelection()` calls `document.getSelection()`. This is reason why Blink have new selection object after `document.open()`.

To fix this issue, we need to get rid `getSelection()` from `DocumentOrShadowRoot` interface.

**Comment by annevk** [comment]
I don't really see why that matters here. Neither the Window nor the Document object change here. I also strongly suspect that setup is the same in all implementations as it's what https://w3c.github.io/selection-api/#dom-window-getselection requires.

**Comment by TimothyGu** [comment]
Currently, Chromium has an [explicit call]( https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/dom/document.cc?l=3109&rcl=7a4a97842daad111dd16019dd37f6d6d01dc6c38) to reset the `Selection` object in `document.open()`. That call was added in chromium/chromium@bff9c922e36599cb97e47c0e8f1f190cc97e69ad for https://crbug.com/683066 in order to pass the older version of `selection/Document-open.html`, which was changed in this PR. It seems like the fix should just be to revert that commit.

**Pull request merged**
