### PR TITLE
Fix the Stash Lock to be unique

### LINKED ISSUE #28662: request.server.stash.lock not working?
In bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1198255

I have issue with the file:
[html/cross-origin-embedder-policy/credentialless/resources/dispatcher.py](https://github.com/web-platform-tests/wpt/blob/7b0ebaccc62b566a1965396e5be7bb2bc06f841f/html/cross-origin-embedder-policy/credentialless/resources/dispatcher.py)

It can be summarized by:

```python
def main(request, response):
    # [...]
    stash = request.server.stash
    # The stash is accessed concurrently by many clients. A lock is used to
    # avoid interleaved read/write from different clients.
    with stash.lock:
        queue = stash.take(uuid) or []
        # [...] Modify |queue|.
        stash.put(uuid, queue)
    return ret;
```

Theoricaly, every `stash.put()` is  preceded by `stash.take()`. `stash.lock()` prevents concurrent access.

Despite this, there are errors sometimes:
https://github.com/web-platform-tests/wpt/pull/28575/checks?check_run_id=2391872015

```
Traceback (most recent call last):
File \"/home/test/web-platform-tests/tools/wptserve/wptserve/handlers.py\", line 362, in __call__
rv = self.func(request, response)
File \"/home/test/web-platform-tests/html/cross-origin-embedder-policy/credentialless/resources/dispatcher.py\", line 48, in main
stash.put(uuid, queue)
File \"/home/test/web-platform-tests/tools/wptserve/wptserve/stash.py\", line 177, in put
raise StashError(\"Tried to overwrite existing shared stash value \"
wptserve.stash.StashError: Tried to overwrite existing shared stash value for key (b'/html/cross-origin-embedder-policy/credentialless/resources/dispatcher.py', b'\\xb0q@h\\xfcL\\x1b\\xb8E\\xfd\\xe3U\\xe1\\xca\\xa5') (old value was [b'done'], new value is [])
```

This sounds like a bug in `stash.lock`.

@stephenmcgruer Do you expect this code to be correct? Or there is something obviously wrong I don't understand? I have seen you made many changes about stash in the recent past.

### PR DESCRIPTION
**Pull request by antosart**
I believe this fixes https://github.com/web-platform-tests/wpt/issues/28662

### CODE REVIEW

**Comment by antosart** [comment]
@ArthurSonzogni

**Comment by ArthurSonzogni** [comment]
Awesome! Thank Antonio!

I verified your patch. I tried the reproducer 10 times. It was working consistently all the time.
I also tried to remove all the "mitigation" to reduce the concurrency like the "concurrencyLimiter" and setTimeout and it was also working perfectly in this case.

**Comment by antosart** [comment]
Looks like some tests are failing. I am wondering how they can be related. Anyway, I can't find documentation on how to run them locally at the moment. I guess I'll have a look tomorrow.

**Review by LukeZielinski — APPROVED** [review]
I've seen these errors in several PRs - they seem unrelated. I logged #28745 to track that.
LGTM for this change.

<edit> you can ignore the failures and merge this, they are non-blocking.

**Comment by antosart** [comment]
@LukeZielinski I have no write access to the repo, can you merge it? Thanks!

**Pull request merged**
