### PR TITLE
Use a shorter name for test

### PR DESCRIPTION
**Pull request by WeizhongX**
The paths of baselines for tests in this file exceed 200 charactors,
which is not allowed for Windows.

Use a shorter name instead

### CODE REVIEW

**Comment by masayuki-nakano** [comment]
Sorry for naming it so long. However, the new name looks like not explaining what the file does.

Perhaps, tentative tests should be moved into a specific path and remove `.tentative`?

**Comment by WeizhongX** [comment]
Hi, thanks for the comment. I do not really understand the test, so was just trying my best to give it a sensible and shorter name. Can you pls suggest one?

Move tentative tests to a different folder would be a bigger refactor, if everyone agrees. But it will only make the name a little bit shorter...

**Comment by WeizhongX** [comment]
Folks, can you pls suggest a better name?

**Comment by masayuki-nakano** [comment]
how about just drop `-or-insertlinebreak` for now? It's not important part to explain the test.

**Comment by WeizhongX** [comment]
> how about just drop `-or-insertlinebreak` for now? It's not important part to explain the test.

Thanks, updated

**Comment by WeizhongX** [comment]
@KyleJu can you help approve this PR? thanks!

**Comment by WeizhongX** [comment]
@DanielRyanSmith, can you also help with this one? Thanks!

**Review by DanielRyanSmith — APPROVED** [review]

**Pull request merged**
