### PR TITLE
Remove reviewers who have not joined the web-platform-tests org

### LINKED ISSUE #11293: Remove OWNERS who have not joined the web-platform-tests org
As reported in https://github.com/web-platform-tests/wpt/pull/11201#issuecomment-393226129, everyone who is currently in any OWNERS file has been invited to the web-platform-tests org.
 
Currently, 74 people have not accepted the invite, and cannot be added to reviews by wpt-pr-bot.

Plan:
1. Ping those 74 people on this issue and ask them to accept the invite
1. After 2 weeks, ping the remaining people once more
1. After 2 more weeks, remove the non-responders from OWNERS files.

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/web-platform-tests/wpt/issues/11293.

Reminder also in https://github.com/web-platform-tests/wpt/issues/11568.

This does not fully resolve #11293, as a few non-responders where
there would be no remaining reviewers are left, and one known to be
out-of-office. These will be handled separately to finish this.

### CODE REVIEW

**Comment by foolip** [comment]
@youennf @thejohnjansen @rakuco, I've sent email about some folks being removed here if you want to go poking and not make this change.

@jgraham, care to review the change itself?

**Review by marcoscaceres — APPROVED** [review]
LGTM from payments side (@edenchuang will rejoin next month, so we can add him back then).

Same on the manifest side.

**Review by sideshowbarker — APPROVED** [review]
LGTM

**Review by rakuco — APPROVED** [review]
Intel lgtm

**Comment by foolip** [comment]
Thanks all, I'll go ahead and merge.

To anyone who was removed here and finds out later, fear not, you can ask here or on IRC to get another invite to the web-platform-tests org and get yourself added back.

**Pull request merged**
