### PR TITLE
[taskcluster] Schedule Chrome Nightly epochs/daily

### PR DESCRIPTION
**Pull request by Hexcles**
as well as triggers/chrome_nightly

The task will install Chromium ToT automatically.

### CODE REVIEW

**Comment by Hexcles** [comment]
Currently running on `triggers/chrome_nightly`: https://community-tc.services.mozilla.com/tasks/groups/HvbHQp7cTjW-46_3A15wHw

**Comment by stephenmcgruer** [comment]
It looks like this is generating the wrong WPT command line for `wpt-chrome-dev-results-without-changes`?

From https://github.com/web-platform-tests/wpt/pull/24904/checks?check_run_id=954285882, emphasis mine:

python ./wpt run **dev** --channel=dev --no-fail-on-unexpected --log-wptreport=../artifacts/wpt_report.json --log-wptscreenshot=../artifacts/wpt_screenshot.txt --affected task_head --log-mach-level=info --log-mach=- -y --no-pause --no-restart-on-unexpected --install-fonts --no-headless --verify-log-full chrome

**Comment by Hexcles** [comment]
This is really weird. Locally, running the same command from https://community-tc.services.mozilla.com/tasks/d1jQlw5UTNmG2A2-5kE1oA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fd1jQlw5UTNmG2A2-5kE1oA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L321

I got
> Executing command: python ./wpt run --channel=dev --no-fail-on-unexpected --log-wptreport=../artifacts/wpt_report.json --log-wptscreenshot=../artifacts/wpt_screenshot.txt --affected task_head --log-mach-level=info --log-mach=- -y --no-pause --no-restart-on-unexpected --install-fonts --no-headless --verify-log-full chrome

It seems as if the change in `taskcluster-run.py` wasn't picked up.

**Comment by Hexcles** [comment]
Oh sorry. This only happens in "without-changes", which of course does not have my change, so this is expected.

**Review by stephenmcgruer — APPROVED** [review]
Ah of course, sorry I should have realized -_-.

LGTM, but please confirm with @jgraham that we have resources for another daily runner.

**Comment by Hexcles** [comment]
Right, by the way, this doesn't have to be daily. A weekly run perhaps also suffices for now.

**Comment by jgraham** [comment]
No objections from me.

**Comment by Hexcles** [comment]
Thanks! Admin-merging, ignoring the without-changes failures.

**Pull request merged**
