### PR TITLE
Comcast's submission

### PR DESCRIPTION
**Pull request by darobin**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision c348bd8c91911f63e9e81ef873de8213e51dd39c
Using browser at version 57.0.2987.19 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4/dom/collections/HTMLCollection-empty-name.html">/dom/collections/HTMLCollection-empty-name.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Empty string as a name for Document.getElementsByClassName` | PASS    |
| `Empty string as a name for Document.getElementsByTagName`   | PASS    |
| `Empty string as a name for Element.children`                | PASS    |
| `Empty string as a name for Element.getElementsByTagNameNS`  | PASS    |
| `Empty string as a name for Document.getElementsByTagNameNS` | PASS    |
| `Empty string as a name for Element.getElementsByClassName`  | PASS    |
| `Empty string as a name for Element.getElementsByTagName`    | PASS    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision c348bd8c91911f63e9e81ef873de8213e51dd39c
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4/dom/collections/HTMLCollection-empty-name.html">/dom/collections/HTMLCollection-empty-name.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Empty string as a name for Document.getElementsByClassName` | PASS    |
| `Empty string as a name for Document.getElementsByTagName`   | PASS    |
| `Empty string as a name for Element.children`                | PASS    |
| `Empty string as a name for Element.getElementsByTagNameNS`  | PASS    |
| `Empty string as a name for Document.getElementsByTagNameNS` | PASS    |
| `Empty string as a name for Element.getElementsByClassName`  | PASS    |
| `Empty string as a name for Element.getElementsByTagName`    | PASS    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision c348bd8c91911f63e9e81ef873de8213e51dd39c
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4/dom/collections/HTMLCollection-empty-name.html">/dom/collections/HTMLCollection-empty-name.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Empty string as a name for Document.getElementsByClassName` | PASS    |
| `Empty string as a name for Document.getElementsByTagName`   | PASS    |
| `Empty string as a name for Element.children`                | PASS    |
| `Empty string as a name for Element.getElementsByTagNameNS`  | PASS    |
| `Empty string as a name for Document.getElementsByTagNameNS` | PASS    |
| `Empty string as a name for Element.getElementsByClassName`  | PASS    |
| `Empty string as a name for Element.getElementsByTagName`    | PASS    |

</details>

**Comment by bobholt** [comment]
Sorry for the w3c-bots comment noise. I could explain how that happened, but it wouldn't be interesting.

**Pull request closed without merging**
