### PR TITLE
Add a test that window[@@iterator] does not exist.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by zcorpan** [comment]
@domenic @annevk r?

**Comment by annevk** [comment]
Seems correct. Small test, but I guess there's a reason for adding it.

**Comment by Ms2ger** [comment]
Mostly "I wouldn't be surprised to see someone regress this"

**Comment by domenic** [comment]
I guess this is because we moved indexed access to the WindowProxy, so the automatic "length + indexed getter = iterable" clause no longer applies?

Should WindowProxy not have `@@iterator`?

It seems weird that we regressed the spec and the first reaction was to add a test for it instead of file a bug about the regression.

**Comment by annevk** [comment]
I think since Gecko already had those on WindowProxy it never had @@iterator on Window/WindowProxy to begin with and would not get them automatically through IDL.

Not sure how that setup was in other browsers. Given that this indexed access is very much legacy, I'm not sure we should be adding extra features on top. Only increases the chances for subtle cross-origin bugs.

**Comment by domenic** [comment]
Well, they were certainly present in Blink, and now we are removing them. https://codereview.chromium.org/1778773002/

It seems weird to make WindowProxy inconsistent with every other indexed object. But I don't care that much.

**Comment by annevk** [comment]
@bzbarsky / @bholley / @heycam, any opinion? Since I also don't care that much.

**Comment by Ms2ger** [comment]
Curious, I thought I tested Chrome and it didn't support it.

**Comment by domenic** [comment]
Hmm looking at the CL further maybe it is behind a flag? @caitp?

**Comment by caitp** [comment]
yeah, it needs the experimental web platform features flag enabled

**Comment by bzbarsky** [comment]
My take on this is that no shipping browser supports @@iterator on window right now.  So adding it is has some compat risk, and not much upside that I can see.

We _could_ add it.  It's not hard to spec, and it's not that hard to implement either, at least in Gecko.  I would be curious to hear what Edge and WebKit plan to do here, if anything.

**Pull request merged**
