### PR TITLE
Create OWNERS for Bluetooth.

### PR DESCRIPTION
**Pull request by g-ortuno**
fyi: @scheib, @jyasskin

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5394)

### CODE REVIEW

**Comment by annevk** [comment]
If you'll could help with removing the two Bluetooth entries from #5317 that'd be great.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219143981)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219143982)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219143981)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 0d2472572968bcad868877268c2cd5d7ae00a4bb
Using browser at version BuildID 20170405115424; SourceStamp b043233ec04f06768d59dcdfb9e928142280f3cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5394/css/css-rhythm-1/line-height-step-valign-001.html">/css/css-rhythm-1/line-height-step-valign-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219143982)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 0d2472572968bcad868877268c2cd5d7ae00a4bb
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations

**Comment by foolip** [comment]
The Chrome stability check failed:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> The build has been terminated

This cannot be because of the change itself. @bobholt, can you investigate?

I'll merge this manually.

**Pull request merged**
