### PR TITLE
[service-workers] Refactor tautological tests

### PR DESCRIPTION
**Pull request by jugglinmike**
Previously, these tests created Promise values which would be fulfilled
even when expectations were violated. This would cause the test harness
to interpret them as "passing" regardless of implementation status.

Remove the use of `Promise.prototype.catch` to ensure that promise
rejections which occur during test execution lead to test failure.

### CODE REVIEW

**Comment by mkruisselbrink** [comment]
Doesn't this still have the problem that some errors (for example in service_worker_unregister_and_register or wait_for_state) are silently swallowed? It seems like the better fix would be to wrap whatever operation is actually expected to fail in a promise_rejects() call, rather than adding explicit assert_unreached/promise rejection handlers like the test is doing today.

**Comment by jugglinmike** [comment]
This test actually creates the Promise that is expected to reject. I think a
simpler solution would be to reserve the "fulfillment" path for expected
behavior, even when that involves a DOM error. I pushed up a commit along these
lines, taking care to document the suspicious-looking code as intentional. What
do you think?

**Comment by mkruisselbrink** [comment]
> This test actually creates the Promise that is expected to reject. I think a
> simpler solution would be to reserve the "fulfillment" path for expected
> behavior, even when that involves a DOM error. I pushed up a commit along these
> lines, taking care to document the suspicious-looking code as intentional. What
> do you think?

Ah, now I see what the test is trying to do. Maybe somehow using `EventWatcher` could make the code nicer? I.e. something like
```js
var w = new Worker(worker_url);
var watcher = new EventWatcher(t, w, ['message', 'error']);
return watcher.wait_for('error');
```

**Comment by jugglinmike** [comment]
Works for me! That's implemented by the latest commit

**Review by mkruisselbrink — APPROVED** [review]
Thanks, lgtm!

**Pull request merged**
