### PR TITLE
Clean up click-cancel.html a bit

### PR DESCRIPTION
**Pull request by foolip**
As the first testdriver.js test, people might look. So:
 * Remove the manual instructions (which were wrong anyway)
 * Don't use a variable called done, that's confusing
 * Make the test fail fast if test_driver.click() rejects
 * Make the indentation a bit more reasonable

### CODE REVIEW

**Comment by foolip** [comment]
I may well have broken the test here. Even if stability checks pass, need to check that the test is actually passing too.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-07 07:51:03
Finished: 2017-11-07 08:02:31


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20251)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/298411320)

**Review by jdm — APPROVED** [review]

**Comment by gsnedders** [comment]
Someone had suggested using a `promise_test` for this but I don't know if that works here?

**Comment by foolip** [comment]
> Someone had suggested using a `promise_test` for this but I don't know if that works here?

This is actually rather a big problem, I spend maybe 30 minutes trying to decide between `async_test` and `promise_test` before concluding that all options would suck. With `async_test` we need to catch promise rejections, and propagating the error message is quite some work.

And with `promise_test`, after the second click, a promise would have be created which resolved in an event handler later, in a way that'd look quite ugly.

When we've written some more ugly tests, we should probably fix this somehow.

**Pull request merged**
