### PR TITLE
css-values-3/attr-invalid-type-003.html is a duplicate.

### PR DESCRIPTION
**Pull request by tgraham-antenna**
css-values-3/attr-invalid-type-003.html is identical to css-values-3/attr-invalid-type-002.html.

### CODE REVIEW

**Comment by gsnedders** [comment]
@FremyCompany any idea how this happened?

**Comment by FremyCompany** [comment]
Probably thought I had changed something and "saved as" while I didn't

**Review by FremyCompany — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 16:35:12
Finished: 2017-08-15 16:51:34



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17424)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264814044)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 16:35:12
Finished: 2017-08-15 16:51:34



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17424)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264814044)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 16:35:12
Finished: 2017-08-15 16:51:34



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17424)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264814044)

**Review by gsnedders — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 16:35:12
Finished: 2017-08-15 16:51:34


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17424)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264814044)

**Pull request merged**
