### PR TITLE
[css-ui] Remove leftover

### PR DESCRIPTION
**Pull request by frivoal**
This code was added to the test to during the code review, and
accidentally committed.

### CODE REVIEW

**Review by plinss — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260497394)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260497396)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260497420)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260497425)

# Sauce (MicrosoftEdge) #

**Pull request merged**
