### PR TITLE
Auto-update the appmanifest IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Review by marcoscaceres — COMMENTED** [review]
I'm still not super comfortable with this... it's all just dictionaries and there is nothing to actually test.

**Comment by marcoscaceres** [comment]
(except the event)

**Comment by marcoscaceres** [comment]
Oops, wrong button.

**Comment by lukebjerring** [comment]
> I'm still not super comfortable with this...

re: "still" - Was this test proposed at another time (I can't find any closed PRs), or are you referring to a similar test?

I realize it doesn't have a large number of tests, but not testing an API because the API is small isn't really a great argument, so only testing a small portion of the IDL is worth it for the same reason IMHO. There should also be other (functional) tests, which will flesh out the dir.

**Comment by marcoscaceres** [comment]
> re: "still" - Was this test proposed at another time (I can't find any closed PRs), or are you referring to a similar test?

Apologies, we've been discussing elsewhere how we are actually going to test this spec. 

>  but not testing an API because the API is small isn't really a great argument,

Sorry, that's not the argument I'm making. I'm saying that most of the dictionaries are not part of an API at all.   

> so only testing a small portion of the IDL is worth it for the same reason IMHO.

I agree. It's why I think we should only include the IDL associated with the BIP event. I'd be totally ok with that and think that's the right thing to do here.

**Comment by lukebjerring** [comment]
Feel free to link to the thread from here where relevant.

By pulling in all the IDL, there are just some basic assertions made about `partial` dictionaries (e.g. that the original dictionary exists somewhere, exposure set is valid, ...), which I think have value.

**Comment by marcoscaceres** [comment]
> Feel free to link to the thread from here where relevant.

https://github.com/w3c/manifest/issues/666

> By pulling in all the IDL, there are just some basic assertions made about partial dictionaries (e.g. that the original dictionary exists somewhere, exposure set is valid, ...), which I think have value.

Ok, but only in as far as they relate to the BIP event (if at all), or am I missing something?

**Comment by lukebjerring** [comment]
Yeah you're totally right, nothing special about these dicts.
Though, side-note, I am missing a `BeforeInstallPromptEvent` object.

**Comment by lukebjerring** [comment]
Test which fails in Chrome is fixed by https://github.com/w3c/manifest/pull/698

**Comment by mgiuca** [comment]
I think there is value to this, but as Marcos says, most of this IDL is not actually exposed and so probably shouldn't be tested. Just the `BeforeInstallPromptEvent` and `Window` parts should be tested.

Note that this not only tests `BeforeInstallPromptEvent` object, but also the presence of the two attributes `onbeforeinstallprompt` and `onappinstalled`, so that's valuable.

Luke, will we have to manually update the WPT copy of the IDL when we change the manifest spec, or will there be some automated process? How will the automated process know not to copy the non-exposed dictionaries? (Perhaps "`Exposed=Window`" is explicitly required, and nothing without that is exposed.)

**Comment by lukebjerring** [comment]
This is a PR that moves __towards__ automatically scraping and updating the IDL, but that flow isn't ready yet, so updates like this will be irregular. I wouldn't be concerned about manually updating the IDL in this case - the scrape will eventually keep it up to date.

Not testing the dictionaries is how idlharness behaves as-is so I wouldn't think anything special needs to be done. The only idlharness tests are that if it's a partial dict, the original dict exists, and if it's a dict that extends another dict, the other dict exists. Neither applies here so those dicts are ignored in the test output.

**Review by mgiuca — APPROVED** [review]
OK, so you're saying that it's *correct* to import all the dictionaries into the WPT file, even though idlharness will ignore them? Sounds fine to me.

If this isn't actually establishing automatically scraping, perhaps reword the title (removing "Auto-").

LGTM, though wait for @marcoscaceres to chime in also.

**Comment by lukebjerring** [comment]
Yep that's what I'm saying! 
Good point - "auto" is the scrape part. Update is still manual.

**Review by marcoscaceres — APPROVED** [review]
I can live with it... but maybe we need so way to tell the scraper "not this IDL".

**Pull request merged**
