### PR TITLE
Move css-font-display/ directory to css-fonts/font-display/

### PR DESCRIPTION
**Pull request by foolip**
The tests are for https://drafts.csswg.org/css-fonts-4/#font-display-desc

### CODE REVIEW

**Comment by foolip** [comment]
@drott @irori, can you review? Should it be in a subdirectory of css-fonts/, and if not who should be in css-fonts/OWNERS?

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-09-09 13:39:41
Finished: 2017-09-09 13:44:20


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

<li>firefox:nightly</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18340)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/273612234)

**Comment by irori** [comment]
How about having css-fonts/loading subdirectory, where tests specific to downloadable webfonts will go?

**Comment by gsnedders** [comment]
@irori I'd rather we followed the ID of the spec section, so `font-resources`.

**Comment by drott** [comment]
I would suggest `css-fonts/font-display`. The other subsections under `font-resources` are quite unrelated to `font-display`, having tests in the same directory would be confusing imho.

**Comment by foolip** [comment]
> How about having css-fonts/loading subdirectory, where tests specific to downloadable webfonts will go?

@irori, I must admit I haven't looked closely at the tests I'm moving, do you mean that some of these are testing downloadable web fonts and belong there, or just that future tests could go there?

**Comment by irori** [comment]
> @irori, I must admit I haven't looked closely at the tests I'm moving, do you mean that some of these are testing downloadable web fonts and belong there, or just that future tests could go there?

These font-display tests are testing behavior while fonts are loading / when fonts finished loading.
No strong opinion, I'm happy with `font-resources` or `font-display`.

**Comment by foolip** [comment]
OK, moved to css-fonts/font-display/ and fix the lint issue.

**Review by svgeesus — APPROVED** [review]
lgtm

**Pull request merged**
