### PR TITLE
Use the checks API with taskcluster jobs

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by foolip** [comment]
@lukebjerring this will require rejigging the results receiver, right?

@jgraham do you know what the triggers for Taskcluster are with this integration, i.e. if this will cause epochs/* branches to stop working?

**Comment by jgraham** [comment]
AFAIK it doesn't change anything about the integration other than where the results go. But @owlishDeveloper is the expert here and should confirm.

**Comment by foolip** [comment]
If it doesn't change anything, it suggests that Taskcluster is using the Checks API in an unconventional way. At least when GitHub creates the check suites (this is configurable) GitHub will send a webhook notifying about this and I think this event is what GitHub intends to be used to trigger check runs. If push events (or something) is also used, then epochs/* will continue to work, but check runs will presumably be overwritten.

Not sure if any of this is a problem, just want to make sure we're not taken by surprise if something like https://github.com/web-platform-tests/wpt/issues/14836#issuecomment-453953098 happens.

**Comment by jgraham** [comment]
Per @owlishDeveloper on irc, enabling checks on GitHub doesn't affect what events we respond to (which makes sense because that's exposed directly in the `.taskcluster.yml` file). So I don't think anything will break by enabling this. Presumably tc looks up the check for the commit later on. Which seems at least as reasonable as looking for the `check_suite` event and seems to be recommended in the docs for cases like ours.

**Comment by lukebjerring** [comment]
Shouldn't be difficult at all, we already have working code for the statuses API and example code for azure.

**Comment by foolip** [comment]
@lukebjerring should I file an issue for that? This PR ought not be filed until that's done, but making the switch is also not particularly urgent I think.

**Comment by lukebjerring** [comment]
Sure, Feel free.

**Comment by lukebjerring** [comment]
Sure, Feel free.

**Comment by Hexcles** [comment]
FWIW, the runs did end up on staging: https://staging.wpt.fyi/results/?sha=f7794b4158fe42dde511108112c4df4cae0ba0fd

so it seems like we don't even need to change the event our webhook is listening to ?

**Comment by foolip** [comment]
@Hexcles this PR hasn't been merged :)

**Comment by Hexcles** [comment]
@foolip the runs I pointed at came from the Taskcluster runs of this exact PR, so I assumed it'd use the Checks API.

**Comment by foolip** [comment]
Ah, that makes sense :)

**Review by foolip — APPROVED** [review]
Let's try it!

**Comment by foolip** [comment]
@jgraham do avoid blocking all new PRs I made the "Taskcluster (pull_request)" check not required. wpt-firefox-nightly-stability and wpt-chrome-dev-stability will need to be made blocking instead, but doing it right away will block all *old* PRs instead. Is a gap of testing for a week or so acceptable, or should we revert this PR and reconsider?

**Comment by foolip** [comment]
Relanding this is blocked on https://github.com/web-platform-tests/wpt.fyi/issues/1182.

@jgraham do you think we can request check names to be configurable? Changing which checks are required results in a painful transition, so getting them right the first time would be very good.

**Comment by jgraham** [comment]
The names are configurable I think? They are coming from the `.taskcluster.yml` file.

**Comment by foolip** [comment]
Oh, I assumed that name had to be identifier-like, could we make it something like "Firefox Nightly stability" then? @lukebjerring @Hexcles that would mess with logic used to get results into the results receiver I guess?

@lukebjerring note also Taskcluster splitting tasks into individual checks, which you thought was a bad idea for Azure Pipelines, in case you think it'll cause trouble here as well.

**Comment by lukebjerring** [comment]
Well, revised opinion: Each task being its own check run actually is an advantage (can react to individual results faster - see https://github.com/web-platform-tests/wpt.fyi/issues/730).

https://github.com/web-platform-tests/wpt.fyi/pull/1183 covers reacting.

**Comment by foolip** [comment]
Cool :)

Are you having to bake the names of the checks into wpt.fyi? What do you think about the naming: human readable or not, prefixed with "Taskcluter -" or not?

**Comment by lukebjerring** [comment]
We rely on _specific_ names, but those specific names can be changed (as long as they are deterministic). The GitHub UI groups by CheckRun name, so not-prefixed is fine.

**Comment by foolip** [comment]
Would "Sta

**Comment by foolip** [comment]
Right now everything starts with "wpt-" so it's grouped together. The names I was thinking of were "stability - Chrome" or something like that, grouping things that are likely fail together. Sound OK?

**Comment by foolip** [comment]
And doing that wouldn't group all Taskcluster things together.

**Pull request merged**
