### PR TITLE
Make @toddreifsteck Edge's owner for Fullscreen

### PR DESCRIPTION
**Pull request by foolip**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/4664)

### CODE REVIEW

**Comment by foolip** [comment]
@toddreifsteck, can you confirm that you're comfortable being asked to occasionally review changes in fullscreen tests? Occasionally, we I use the test PRs themselves as a place to ask what Edge does or wants to do, since unfortunately things still need to change in the spec to actually get this shipped in Chrome...

**Comment by toddreifsteck** [comment]
It isn't yet clear that I should be an owner on Fullscreen. @aliams and I are talking to determine who the next owner should be and will reply here.

**Comment by foolip** [comment]
Ping @toddreifsteck, have you found an Edge owner for this yet?

**Comment by foolip** [comment]
@toddreifsteck, should I close this PR?

**Comment by toddreifsteck** [comment]
Please cancel this PR. I am not the owner. Until a new owner is chosen, it should stay on Ali.

**Comment by foolip** [comment]
Sure thing!

**Pull request closed without merging**
