### PR TITLE
Move the tests of input range outside [0, 1] into css-timing-1.

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: 8AMdaABvxaF

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1248340 [ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5348)

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5348/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218517114)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218517115)

**Pull request merged**
