### PR TITLE
HTML: ensure serializing SharedArrayBuffer throws without COOP+COEP

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/pull/4734.

### CODE REVIEW

**Comment by annevk** [comment]
#17760 and #17761 should probably land first as otherwise we end up with contradictory state.

**Review by foolip — COMMENTED** [review]
Can you add tests for when the "allow sidechannel attacks" flag is true?

Have you also searched for tests that already try to postMessage SABs? Those will need updating.

**Comment by annevk** [comment]
@foolip see the PRs I referenced and also #17690. This is part of a larger set of changes that addresses those concerns.

**Comment by foolip** [comment]
@annevk I see, that's being tracked then.

**Review by foolip — APPROVED** [review]

**Pull request merged**
