### PR TITLE
[css-values] Added 3 complex getComputedStyle tests with calc()

### PR DESCRIPTION
**Pull request by TalbotG**
This PR is a followup-to [Pull Request 16598](https://github.com/web-platform-tests/wpt/pull/16598/) .

At my website:
http://www.gtalbot.org/BrowserBugsSection/CSS3Values/getComputedStyle-calc-background-position-percent-012.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/getComputedStyle-calc-height-percent-014.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/getComputedStyle-calc-background-size-percent-016.html

### CODE REVIEW

**Comment by fantasai** [comment]
There must be a file somewhere that contains tests similar to these. These should each be a line in that test file, rather than each a test file by itself.

**Comment by fantasai** [comment]
Also, background-size can take a single value that defaults to auto, so it should serialize out without the auto (if it's the second value).

(I admit that this was a stupid design, and it should have duplicated the single value like every other property in CSS. It is my mistake.)

**Comment by TalbotG** [comment]
> There must be a file somewhere that contains tests similar to these. These should each be a line in that test file, rather than each a test file by itself.

I intend to merge the 3 tests into 1.

**Comment by TalbotG** [comment]
> background-size can take a single value that defaults to auto, so it should serialize out without the auto

I will make appropriate adjustments then.

**Review by fantasai — APPROVED** [review]
I would recommend renaming the file to getComputedStyle-calc-mixed-units-001.html but otherwise it seems fine.

**Comment by TalbotG** [comment]
> I would recommend renaming the file to getComputedStyle-calc-mixed-units-001.html but otherwise it seems fine.

Done over at [Pull Request 39054](https://github.com/web-platform-tests/wpt/pull/39054)

**Pull request merged**
