### PR TITLE
Rename "safari_webdriver" to "safari", get rid of "safari"

### PR DESCRIPTION
**Pull request by gsnedders**
@jugglinmike you don't use `safari_webdriver` do you? therefore this should be landable without breaking anything

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by gsnedders** [comment]
To be clear: the "do not merge yet" label is pending @jugglinmike responding to the above; Mike: feel free to remove it when you do.

**Comment by jugglinmike** [comment]
I wasn't aware that `safari_webdriver` existed. Thanks for the heads-up, Geoffrey!

**Review by jugglinmike — APPROVED** [review]

**Comment by foolip** [comment]
Yay! Let's hope that the Safari runs from @jugglinmike's setup still finish, if they don't we should immediately revert this.

**Comment by gsnedders** [comment]
Most of the apparent regressions are things going from ERROR -> OK at a harness level and getting new failures like that. Looking through it relatively quickly I can't see anything that looks actively bad?

**Pull request merged**
