### PR TITLE
Move all Webdriver tests under tests/

### PR DESCRIPTION
**Pull request by jgraham**
This changed upstream to allow import from subdirectories of the top
level without creating a `webdriver` module that would clash with the
client. But obviously it didn't affect files that were added in
subsequent PRs, but did break them. This commit moves those files and
updates the imports to match.

### CODE REVIEW

**Review by shs96c — APPROVED** [review]
Kind of a pity that there needs to be a `tests` directory, but I understand the logic.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260555879)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260555880)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260555887)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260555888)

# Sauce (MicrosoftEdge) #

**Comment by andreastt** [comment]
> Kind of a pity that there needs to be a tests directory, but I understand the logic.

@shs96c If we rename the _webdriver_ Python client to _wdclient_, _wptwebdriver_ or some such there’s no need for a tests directory.

**Comment by jgraham** [comment]
Right, there's more than one way to skin this cat. I'm not a bug fan of this solution either, but it's the one we got a patch for. Happy to take more patches, but at this point I suggest that the churn isn't worth it.

**Comment by andreastt** [comment]
I am not particularly inclined to submit patches either, but I find it slightly horrendous how much ‘test’ there is in testing/web-platform/tests/webdriver/tests/conftest.py.

**Pull request merged**
