### PR TITLE
Add test for scrollend event of programmatic scrolling

### PR DESCRIPTION
**Pull request by cathiechen**
Tests scrollend event for instant and smooth programmatic scroll.

### CODE REVIEW

**Review by NavidZ — APPROVED** [review]
Seems reasonable. Thanks

**Comment by cathiechen** [comment]
@NavidZ Thanks for the review:)

**Comment by cathiechen** [comment]
Sorry, I tried to rebase mine, but it seems I mess this up... I'll close this one, and reopen a new PR.

**Comment by cathiechen** [comment]
Moved to https://github.com/web-platform-tests/wpt/pull/22768

**Pull request closed without merging**
