### PR TITLE
[REFERRER] Tests for CSS integration

### PR DESCRIPTION
**Pull request by jeisinger**
still wip

### CODE REVIEW

**Comment by jeisinger** [comment]
When I run http://web-platform.test:8000/referrer-policy/css-integration/external-stylesheet.html locally, I see e.g. the following logs

```
DEBUG:web-platform-tests:GET /referrer-policy/generic/subresource/stylesheet.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658
DEBUG:web-platform-tests:Found handler PythonScriptHandler
DEBUG:web-platform-tests:200 GET /referrer-policy/generic/subresource/stylesheet.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658 (http://web-platform.test:8000/referrer-policy/css-integration/external-stylesheet.html) 0
DEBUG:web-platform-tests:GET /referrer-policy/generic/subresource/image.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658
DEBUG:web-platform-tests:Found handler PythonScriptHandler
DEBUG:web-platform-tests:GET /referrer-policy/generic/subresource/image.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658&report-headers
DEBUG:web-platform-tests:Found handler PythonScriptHandler
application/json
DEBUG:web-platform-tests:200 GET /referrer-policy/generic/subresource/image.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658 (None) 0
ERROR:web-platform-tests:Traceback (most recent call last):
  File "/usr/local/google/home/eisinger/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 246, in __call__
    rv = self.func(request, response)
  File "/usr/local/google/home/eisinger/web-platform-tests/referrer-policy/generic/subresource/image.py", line 114, in main
    access_control_allow_origin = "*")
  File "/usr/local/google/home/eisinger/web-platform-tests/referrer-policy/generic/subresource/subresource.py", line 100, in respond
    response.writer.write(payload)
  File "/usr/local/google/home/eisinger/web-platform-tests/tools/wptserve/wptserve/response.py", line 439, in write
    self._wfile.write(self.encode(data))
  File "/usr/local/google/home/eisinger/web-platform-tests/tools/wptserve/wptserve/response.py", line 465, in encode
    raise ValueError
ValueError

DEBUG:web-platform-tests:500 GET /referrer-policy/generic/subresource/image.py?id=6143e7ad-83db-4cd1-8433-3654b5f1f658&report-headers (None) 0

```

So it looks like the stash.take() call in /referrer-policy/generic/subresource/image.py's generate_report_headers_payload returns None (but also doesn't raise an exception), even though the image already was successfully loaded by the browser before the second request was initiated.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5160/)

**Comment by jgraham** [comment]
FTR, per our converstation on irc, these tests are assuming that the external url is a critical subresource of the stylesheet, and so the load event on the link element implies that the image must have loaded. But testing in browsers suggests that's not actually happening because adding logging to the server clearly shows that we are trying to take from the stash before we put anything into the stash.

Depending on what you want to test, it might be possible to `step_timeout` a reasonable delay after the load event and then check the headers from the image. It's not elegant but ought to work well enough with an appropriate delay (e.g. at least 1s).

**Comment by jeisinger** [comment]
ok, using step_timeout appears to work.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215497794)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 2838ab3b163fa65fc4e4462fcd726d38b9f9974d
Git command exited with status 128
fatal: Invalid revision range 5db343c5cba7120195de13f6759c4935bdcc0daa..

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215497795)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 2838ab3b163fa65fc4e4462fcd726d38b9f9974d
Git command exited with status 128
fatal: Invalid revision range 5db343c5cba7120195de13f6759c4935bdcc0daa..

**Comment by jeisinger** [comment]
closing this as I'll include the tests in the upstream code changes

**Pull request closed without merging**
