### PR TITLE
Css contain

### PR DESCRIPTION
**Pull request by frivoal**
Here are a bunch of tests to cover the normative spec changes made since last CR.

These should cover:
https://github.com/w3c/csswg-drafts/issues/2527
https://github.com/w3c/csswg-drafts/issues/2512
https://github.com/w3c/csswg-drafts/issues/2510
https://github.com/w3c/csswg-drafts/issues/2483
https://github.com/w3c/csswg-drafts/issues/2349
https://github.com/w3c/csswg-drafts/issues/2223
https://github.com/w3c/csswg-drafts/issues/1887
https://github.com/w3c/csswg-drafts/issues/1872
https://github.com/w3c/csswg-drafts/issues/1809
https://github.com/w3c/csswg-drafts/issues/1457

### CODE REVIEW

**Review by eaenet — APPROVED** [review]

**Comment by eaenet** [comment]
This is a really good set of tests and you captured all the things we resolved in Berlin. Thank you!

**Comment by frivoal** [comment]
@jgraham @Ms2ger @foolip @gsnedders: Can @eaenet be granted the necessary permissions for his review to count as allowing this PR to be merged?

Thanks.

(Also, if pinging you individually about this sort of thing is not the correct approach, please let me know what is).

**Review by kojiishi — APPROVED** [review]
lgtm, thank you.

**Comment by foolip** [comment]
@eaenet I've sent you two invites, both to this repo and the new org. See https://bit.ly/wpt-transition for why that's the case.

**Pull request merged**
