### PR TITLE
Fixing link ref="match" in some reference files

### PR DESCRIPTION
**Pull request by youennf**
Reference files should probably refer to themselves.

[Review on Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/2350)

### CODE REVIEW

**Comment by jdm** [comment]
Reference files shouldn't refer to anything, since that's just confusing :)

**Comment by youennf** [comment]
Ah...
That may explain https://github.com/w3c/web-platform-tests/issues/2351

**Comment by gsnedders** [comment]
Reference files can refer to other things, it's how we express A == B == C. Referring to yourself is just redundant, though.

**Comment by youennf** [comment]
What's the advantage of A==B==C?
(A==C, B==C) allows clearly identifying which files are test (A, B) or reference (C).

**Comment by zcorpan** [comment]
IIRC we allow that to be compatible with [csswg-test](https://github.com/w3c/csswg-test), which at some point we want to merge with. cc @jgraham

**Comment by jgraham** [comment]
Yes, this is intentionally designed to mimic the CSSWG design. See the public-test-infra archive for more details.

**Comment by zcorpan** [comment]
This PR is incorrect as I understand it, so closing.

**Comment by youennf** [comment]
I think this should be r- as this is intentional (although still misleading to me...).
The thing that could be done is to remove the <link rel="match"> tags that reference themselves (useless and misleading too). This happens in some documents in html folder.

**Comment by r12a** [comment]
@Ms2ger, these tests weren't submitted by me (i ended up creating a separate version of them for the i18n test suite), so i can't help much.  I am rather surprised that test files point to themselves for reference, since i'd have thought that that defeats the object of the exercise, but i haven't given a lot of thought.

**Pull request closed without merging**
