### PR TITLE
Remove instance of 'whitelist' in webdriver/

### PR DESCRIPTION
**Pull request by stephenmcgruer**
As per https://whatwg.org/style-guide

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
This is a documentation-only change, but failed both Firefox and Chrome stability checks. On Firefox it timed out, whilst on Chrome it seems like there were a bunch of flaky setup-errors, at about a 50% flake rate.

50% flake is pretty bad; are these cases known and being looked at? (cc @JohnChen0)

**Comment by JohnChen0** [comment]
> This is a documentation-only change, but failed both Firefox and Chrome stability checks. On Firefox it timed out, whilst on Chrome it seems like there were a bunch of flaky setup-errors, at about a 50% flake rate.
> 
> 50% flake is pretty bad; are these cases known and being looked at? (cc @JohnChen0)

I'm not aware of these cases. I poked around the test results, and the only failures I saw were in interface.html at https://wpt.fyi/results/webdriver/tests?product=chrome-81.0.4033.2%20dev-linux-18.04%5Bpr_head%5D%40acf6a48715&product=chrome%5Bexperimental%2Cmaster%5D&diff&filter=ACU, but I don't see any cause of the failure. Anywhere else I should be looking at?

**Comment by stephenmcgruer** [comment]
If you look at the github checks for this PR, 'Community-TC' is red. The details link leads to the TaskCluster page, https://community-tc.services.mozilla.com/tasks/groups/bfRyF8HWQ3CIoJoIhWhBzw, where we can click into 'wpt-chrome-dev-stability', then 'View Live Log'. At the bottom is:

```
93:54.72 INFO ## Unstable results ##
93:54.72 INFO |                          Test                         |                        Subtest                         |           Results           |    Messages   |
93:54.72 INFO |-------------------------------------------------------|--------------------------------------------------------|-----------------------------|---------------|
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept[capabilities0-alert-None]`                | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept[capabilities0-confirm-True]`              | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept[capabilities0-prompt-]`                   | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept_and_notify[capabilities0-alert-None]`     | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept_and_notify[capabilities0-confirm-True]`   | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_accept_and_notify[capabilities0-prompt-]`        | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss[capabilities0-alert-None]`               | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss[capabilities0-confirm-False]`            | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss[capabilities0-prompt-None]`              | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss_and_notify[capabilities0-alert-None]`    | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss_and_notify[capabilities0-confirm-False]` | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_dismiss_and_notify[capabilities0-prompt-None]`   | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_ignore[capabilities0-alert]`                     | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_ignore[capabilities0-confirm]`                   | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_ignore[capabilities0-prompt]`                    | **ERROR: 6/10, PASS: 4/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_default[alert-None]`                             | **ERROR: 7/10, PASS: 3/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_default[confirm-False]`                          | **ERROR: 7/10, PASS: 3/10** | `setup error` |
93:54.72 INFO | `/webdriver/tests/get_active_element/user_prompts.py` | `test_default[prompt-None]`                            | **ERROR: 7/10, PASS: 3/10** | `setup error` |
93:54.72 INFO 
```

There are a couple of notes to make here:

- It fails on both Firefox and Chrome, which points to the test having a problem rather than an implementation.
- Stability checks are a bit weird. We run the same test in a row 10 times, without restarting the browser. This can reveal problems that might not appear in 'normal' runs of the test (where it would only run once).

That said, I can't reproduce it locally so I wouldn't be super worried.

**Comment by stephenmcgruer** [comment]
(And all this should have nothing to do with this PR!)

**Comment by JohnChen0** [comment]
I see many instances of the following error: `ValueError: filedescriptor out of range in select()`. I suppose that means the test is opening too many connections.

**Comment by stephenmcgruer** [comment]
(Kicking the CI to run again)

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
(this is one of the files which modifying causes… every single wdspec test to be run in stability mode; it will always time out)

**Pull request merged**
