### PR TITLE
Add STAT table, fix name IDs, suppress font-synthesis, add fvar instance

### LINKED ISSUE #22355: css/css-fonts/matching/ tests refresh to pass on FF, Safari?
Judging [from the results pages](https://wpt.fyi/results/?label=master&label=experimental&aligned&q=css%2Fcss-fonts%2Fmatching%2F
) css/css-fonts/matching/ is only passing on Chromium based browsers. 

In the process of fixing the issue raised in https://arrowtype.github.io/vf-slnt-test/ (application of `slnt` values needs sign inversion from CSS to OpenType values, [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=859869), [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1611997), [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=200369)) I am now updating the test font so that its `slnt` axis is turned around and the bar for the test glyph is short at 90, and long at -90 axis values, which means it's short at `-90 deg` CSS value, and long at `90 deg` CSS value. 

The test setup is perhaps a little complicated, but I still find it useful to test font matching and application of variable style values, and I would expect Safari and FF to be compatible with the principles, but somehow the test does not pass for those. 

@jfkthame, @litherum - would you be ready to help by reviewing the test and providing some insights? Is there something we can do for this test to work better in your systems? Or are there perhaps issues with the test, or would you have other improvement suggestions? Thanks in advance.

### PR DESCRIPTION
**Pull request by drott**
Concluding from the discussion in #22355 name ids should have values
greater than 255, and the font should have a STAT table. The name id
issue is something the Firefox prints out as an error on the command
line. Add a STAT table, add a named instance for the regular instance,
and move name ids in this change. Also add encoding headers in tests and
references, and suppress font-synthesis as this is needed to help the
test pass on Firefox.

Fixes #22355 for Firefox.

### CODE REVIEW

**Comment by drott** [comment]
CC @jfkthame - this should be sufficient to make it pass in Firefox, I assume? Thanks for your review.

**Comment by jfkthame** [comment]
Yes, LGTM.

**Comment by drott** [comment]
CC @kojiishi - can you LGTM WPT changes, too?

**Review by litherum — APPROVED** [review]

**Comment by drott** [comment]
Thanks for the quick review, Myles!

**Pull request merged**
