### PR TITLE
Interop: correct invalid nbsp trimming label tests

### PR DESCRIPTION
**Pull request by cookiecrook**
Resolves https://github.com/web-platform-tests/interop-accessibility/issues/115

Correcting invalid tests that are skewing Interop results.

### CODE REVIEW

**Comment by cookiecrook** [comment]
CI bot didn't get teh WPT.fyi results, but I ran this locally on Chrome, Firefox, and Safari with the modified tests passing in all three, so I'm confident enough to auto-merge without CI previews once there's an approving review.

**Comment by nmlapre** [comment]
This change looks good to me, and I agree it's in line with the spec to avoid trimming non-breaking spaces here. I implemented a non-breaking space trimmer in Gecko for this situation to conform to the tests (thinking they were right), which I'll remove when this merges.

RE:
> I ran this locally on Chrome, Firefox, and Safari with the modified tests passing in all three

If I'm not mistaken, these changes should cause Firefox (and Safari?) to fail these five tests, since those browsers are currently trimming non-breaking spaces.

**Comment by cookiecrook** [comment]
Sorry for the extra work... @twilco, did you also have this patched before we spotted the error?

**Comment by cookiecrook** [comment]
> these changes should cause Firefox (and Safari?) to fail these five tests,

Yes, the CI bots must've woken up since then. You are correct that those two engines fail now but should pass.

**Comment by twilco** [comment]
> @twilco, did you also have this patched in WebKit nightly before we spotted the error? If so, that could roll back too.
Yeah. I'll roll it back after this PR lands.

**Review by nmlapre — APPROVED** [review]

**Pull request merged**
