### PR TITLE
[url] Test more whitespace stripping intricacies

### PR DESCRIPTION
**Pull request by TimothyGu**
Cf. https://github.com/nodejs/node/issues/12825

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228965012)

# Firefox (nightly channel) #
Testing web-platform-tests at revision c3fa1c9793550db0f010a9626582b768cdb9851f
Using browser at version BuildID 20170503100422; SourceStamp 82c2d17e74ef9cdf38a5d5ac4eb3ae846ec30ba4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/a-element-origin-xhtml.xhtml">/url/a-element-origin-xhtml.xhtml</a></summary>


|     Subtest     | Results |      Messages      |
|-----------------|---------|--------------------|
|                 | OK      |                    |
| `Loading data…` | FAIL    | `urltests is null` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/a-element-origin.html">/url/a-element-origin.html</a></summary>


|     Subtest     | Results |      Messages      |
|-----------------|---------|--------------------|
|                 | OK      |                    |
| `Loading data…` | FAIL    | `urltests is null` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/a-element-xhtml.xhtml">/url/a-element-xhtml.xhtml</a></summary>


|     Subtest     | Results |      Messages      |
|-----------------|---------|--------------------|
|                 | OK      |                    |
| `Loading data…` | FAIL    | `urltests is null` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/a-element.html">/url/a-element.html</a></summary>


|     Subtest     | Results |      Messages      |
|-----------------|---------|--------------------|
|                 | OK      |                    |
| `Loading data…` | FAIL    | `urltests is null` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/failure.html">/url/failure.html</a></summary>


|     Subtest     | Results |                                                                     Messages                                                                    |
|-----------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------|
|                 | OK      |                                                                                                                                                 |
| `Loading data…` | FAIL    | `promise_test: Unhandled rejection with value: object "SyntaxError: JSON.parse: bad escaped character at line 3564 column 16 of the JSON data"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/url-constructor.html">/url/url-constructor.html</a></summary>


|                            Subtest                            | Results |      Messages      |
|---------------------------------------------------------------|---------|--------------------|
|                                                               | OK      |                    |
| `URL.searchParams getter`                                     | PASS    |                    |
| `URL.searchParams updating, clearing`                         | PASS    |                    |
| `URL.searchParams setter, invalid values`                     | PASS    |                    |
| `URL.searchParams and URL.search setters, update propagation` | PASS    |                    |
| `Loading data…`                                               | FAIL    | `urltests is null` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5792/url/url-origin.html">/url/url-origin.html</a></summary>


|     Subtest     | Results |      Messages      |
|-----------------|---------|--------------------|
|                 | OK      |                    |
| `Loading data…` | FAIL    | `urltests is null` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228965020)

# Chrome (unstable channel) #
Testing web-platform-tests at revision c3fa1c9793550db0f010a9626582b768cdb9851f

**Comment by annevk** [comment]
FWIW, I somewhat prefer "URL: ..."-style commit messages.

**Comment by TimothyGu** [comment]
@domenic ping.

**Pull request merged**
