### PR TITLE
Add http/README.md

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Reviewers, I assume that this is actually wrong, so please tell which IETF specs should actually be tested in this directory :)

**Comment by annevk** [comment]
The RFCs that replace that RFC: 7230, 7231, 7232, 7233, 7234, 7235. And maybe we put H/2 and such here too once we have the server-side story for that.

**Comment by mnot** [comment]
There are already HTTP tests in /fetch; is the idea to move them here, or...?

**Comment by foolip** [comment]
> There are already HTTP tests in /fetch; is the idea to move them here, or...?

I have no such ambition. I just noticed that this directory exists, and presumably tests something about HTTP :) @mnot, is the list of RFCs @annevk listed right, should I just put that in the README?

**Comment by annevk** [comment]
We should probably stop using `http/` having seen what's in it. Fetch is probably a better place.

**Comment by foolip** [comment]
OK, to just merge the directories, or is some finesse required here?

**Comment by foolip** [comment]
Finesse attempted in https://github.com/w3c/web-platform-tests/pull/10870.

**Review by berniefyfe — APPROVED** [review]

**Pull request closed without merging**
