### PR TITLE
SVG: Check that required properties are supported

### PR DESCRIPTION
**Pull request by ewilligers**
https://svgwg.org/svg2-draft/styling.html#RequiredProperties
The following properties must be supported by all SVG user agents:
...

We check that each property is supported.

### CODE REVIEW

**Comment by AmeliaBR** [comment]
This test isn't really an effective test, because in user agents that support both HTML and SVG (AKA, web browsers), it will only test that the CSS parser recognizes the property, not that it applies the properties to SVG rendering.  E.g., some browsers (thankfully, no longer any of the latest versions) will recognize `transform` as a CSS property name, but not apply it to an SVG element. Even still, most browsers won't apply it to patterns and gradients.

It's a first step, but not sufficient.

Also, this is probably an SVG spec issue: but why is `z-index` not in either of those lists?

**Comment by ewilligers** [comment]
I have added a Note with your concern about the limitations of this test.

The test is effective in identifying properties that an implementation has no support for, e.g. Blink gave
```
FAIL Property "font-variant-position" is supported assert_true: expected true got false
FAIL Property "glyph-orientation-vertical" is supported assert_true: expected true got false
FAIL Property "text-align-all" is supported assert_true: expected true got false
FAIL Property "text-space-collapse" is supported assert_true: expected true got false
```

The test also doesn't check that implementations support the full grammar for each property. I have been writing CSS parsing/serialization tests for all the CSS specs referenced, and contributing them to the relevant CSS test suites.

**Review by svgeesus — APPROVED** [review]
With the caveat that this only tests the property is known, not that it gets applied to SVG content, this basic test LGTM

**Comment by ewilligers** [comment]
`Also, this is probably an SVG spec issue: but why is `z-index` not in either of those lists?`

I have uploaded a [test](https://github.com/web-platform-tests/wpt/pull/11583). If z-index has SVG implementation support, we can add it to the list and the tests, otherwise we should remove the z-index section from the 2.0 draft.

**Pull request merged**
