### PR TITLE
Update docs related to CSS tests

### PR DESCRIPTION
**Pull request by xfq**
Some initial updates for the documentation as csswg-test is now merged into web-platform-tests.

/cc @gsnedders

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/216591484)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e36615340a198f8192193b7a246b31272f44ba40
Using browser at version BuildID 20170329100319; SourceStamp 272ce6c2572164f5f6a9fba2a980ba9ccf50770c
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/216591485)

# Chrome (unstable channel) #
Testing web-platform-tests at revision e36615340a198f8192193b7a246b31272f44ba40
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5265/)

**Comment by annevk** [comment]
Thanks!

Can you maybe also update the main README while you're at it?

(I restarted the build process, not sure why it was failing in Firefox since you only changed documentation...)

**Review by annevk — APPROVED** [review]

**Pull request merged**
