### PR TITLE
Test document.body and document.bgColor when root is not <html>

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/html/issues/3403

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23418)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/334734459)

**Review by annevk — APPROVED** [review]
It might also be worth testing with a document inside an `<iframe>`. Sometimes a browsing context ends up mattering somehow (and it probably shouldn't here).

**Review by bzbarsky — APPROVED** [review]
This is generally good, but we should also have a test for the "frameset in html" case, where .fgColor is _not_ propagated to the frameset, even though document.body is the frameset.

**Comment by zcorpan** [comment]
I've address comments and rebased to resolve conflict with https://github.com/w3c/web-platform-tests/commit/08cb16810a35273e5f400acd1fbdc352559addfe (which wasn't much of a conflict, just us adding new tests in the same place).

**Review by annevk — APPROVED** [review]

**Comment by zcorpan** [comment]
https://bugs.webkit.org/show_bug.cgi?id=182484
https://bugs.chromium.org/p/chromium/issues/detail?id=809059
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15806109/
Firefox Nightly passes these tests.

**Pull request merged**
