### PR TITLE
HTML: ensure BarProps are visible for noopener/noreferrer

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/pull/3297.

### CODE REVIEW

**Comment by annevk** [comment]
@bzbarsky so I thought this would be an easy way to test https://github.com/whatwg/html/pull/3297, but Chrome passes the test for noopener, so...

**Comment by bzbarsky** [comment]
Yeah, I have no idea what's going on here.  The visual display in Chome is the same whether I pass `"locationbar"` or `"noopener"` as the feature string (on Chrome dev 75.0.3759.4), but the barprops return values look different.  Seems like a Chrome bug.

@npm1 any idea what's going on here?

**Comment by npm1** [comment]
> @npm1 any idea what's going on here?

Nope, this is something the DOM team could dig into. You can contact them at their Chromium email: dom-dev.

**Comment by annevk** [comment]
cc @tkent-google

**Comment by tkent-google** [comment]
Though I don't know the details, according to [crbug.com/310691](http://crbug.com/310691), Chrome always returns true for BarProp.visible.

**Comment by annevk** [comment]
@tkent-google I get `assert_true: expected true got false` for the noreferrer test of this PR.

**Comment by tkent-google** [comment]
Sorry for my previous useless comment. 
I investigated the difference between "noopener" and "noreferer" (currently invalid keyword).
Chrome has the code to propagate parsed window features values to BarProp.visible, and it seems we miss to propagate it in the "noopener" case because it returns null for window.open(). It's an implementation bug definitely.

**Comment by annevk** [comment]
Okay, so this would show the issue, once that's fixed.

Another thing I could potentially assert is viewport width. That is, requiring it to be identical to the opener. I'm not sure how ideal that is though. Thoughts?

**Comment by foolip** [comment]
@tkent-google can I assign this over to you for review? Sounds like you have more context than me. (I was picked at random by the bot.)

**Review by tkent-google — APPROVED** [review]
The current test doesn't work well only on Chrome due to the Chrome bug, but the test makes sense on other browsers.  We fixed the noopener-popup issue of Chrome yesterday, and we have a non-WPT tests.    So I think it's ok to merge this as is.

**Comment by tkent-google** [comment]
I filed the BarProp issue of Chrome; https://bugs.chromium.org/p/chromium/issues/detail?id=954033

**Pull request merged**
