### PR TITLE
self.origin: return IDNA in ASCII

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/2568.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233118022)

# Firefox (nightly) #
Testing web-platform-tests at revision c8bb4d28380661ee7e2dec73c53c36c89969520c
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5955/html/dom/self-origin.sub.html">/html/dom/self-origin.sub.html</a></summary>


|                                        Subtest                                         | Results |                                                       Messages                                                       |
|----------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
|                                                                                        | OK      |                                                                                                                      |
| `Assigning blob url`                                                                   | PASS    |                                                                                                                      |
| `Should have the right origin for cross-origin subframe`                               | PASS    |                                                                                                                      |
| `Should have the right origin for cross-origin subframe after setting document.domain` | PASS    |                                                                                                                      |
| `Should have the right origin for IDN subframe`                                        | FAIL    | `assert_equals: expected "http://xn--lve-6lad.web-platform.test:8001" but got "http://Ã©lÃ¨ve.web-platform.test:8001"` |
| `Should have the right origin for IDN subframe after setting document.domain`          | FAIL    | `assert_equals: expected "http://xn--lve-6lad.web-platform.test:8001" but got "http://Ã©lÃ¨ve.web-platform.test:8001"` |
| `Should have the right origin for sandboxed iframe`                                    | PASS    |                                                                                                                      |
| `We should have the right origin for our page`                                         | PASS    |                                                                                                                      |
| `about:blank subframe origins`                                                         | PASS    |                                                                                                                      |
| `blob: subframe origins`                                                               | PASS    |                                                                                                                      |
| `javascript: subframe origins`                                                         | PASS    |                                                                                                                      |
| `srcdoc subframe origins`                                                              | PASS    |                                                                                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233118023)

# Sauce (safari) #
Testing web-platform-tests at revision c8bb4d28380661ee7e2dec73c53c36c89969520c
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5955/html/dom/self-origin.sub.html">/html/dom/self-origin.sub.html</a></summary>


|                                        Subtest                                         | Results |                                                                       Messages                                                                       |
|----------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                        | TIMEOUT |                                                                                                                                                      |
| `Assigning blob url`                                                                   | PASS    |                                                                                                                                                      |
| `Should have the right origin for cross-origin subframe`                               | NOTRUN  |                                                                                                                                                      |
| `Should have the right origin for cross-origin subframe after setting document.domain` | NOTRUN  |                                                                                                                                                      |
| `Should have the right origin for IDN subframe`                                        | NOTRUN  |                                                                                                                                                      |
| `Should have the right origin for IDN subframe after setting document.domain`          | NOTRUN  |                                                                                                                                                      |
| `Should have the right origin for sandboxed iframe`                                    | NOTRUN  |                                                                                                                                                      |
| `We should have the right origin for our page`                                         | FAIL    | `assert_equals: expected (string) "http://web-platform.test:8000" but got (undefined) undefined`                                                     |
| `about:blank subframe origins`                                                         | FAIL    | `assert_equals: Should have the right origin for about:blank iframe expected (string) "http://web-platform.test:8000" but got (undefined) undefined` |
| `blob: subframe origins`                                                               | FAIL    | `assert_equals: Should have the right location origin for blob: iframe expected "http://web-platform.test:8000" but got "null"`                      |
| `javascript: subframe origins`                                                         | FAIL    | `assert_equals: Should have the right origin for javascript: iframe expected (string) "http://web-platform.test:8000" but got (undefined) undefined` |
| `srcdoc subframe origins`                                                              | FAIL    | `assert_equals: Should have the right origin for srcdoc iframe expected (string) "http://web-platform.test:8000" but got (undefined) undefined`      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233118024)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c8bb4d28380661ee7e2dec73c53c36c89969520c
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5955/html/dom/self-origin.sub.html">/html/dom/self-origin.sub.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233118030)

# Chrome (unstable) #
Testing web-platform-tests at revision c8bb4d28380661ee7e2dec73c53c36c89969520c
Using browser at version 60.0.3100.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5955/html/dom/self-origin.sub.html">/html/dom/self-origin.sub.html</a></summary>


|                                        Subtest                                         | Results | Messages |
|----------------------------------------------------------------------------------------|---------|----------|
|                                                                                        | OK      |          |
| `Assigning blob url`                                                                   | PASS    |          |
| `Should have the right origin for cross-origin subframe`                               | PASS    |          |
| `Should have the right origin for cross-origin subframe after setting document.domain` | PASS    |          |
| `Should have the right origin for IDN subframe`                                        | PASS    |          |
| `Should have the right origin for IDN subframe after setting document.domain`          | PASS    |          |
| `Should have the right origin for sandboxed iframe`                                    | PASS    |          |
| `We should have the right origin for our page`                                         | PASS    |          |
| `about:blank subframe origins`                                                         | PASS    |          |
| `blob: subframe origins`                                                               | PASS    |          |
| `javascript: subframe origins`                                                         | PASS    |          |
| `srcdoc subframe origins`                                                              | PASS    |          |

</details>
</details>

**Comment by zcorpan** [comment]
The stability checker got TIMEOUT results for Edge and Safari. Is that new with this change? I don't get a TIMEOUT for /html/dom/self-origin.sub.html on master in Safari TP when testing locally.

Otherwise the change LGTM.

**Comment by annevk** [comment]
@zcorpan are you sure? It says everything is okay other than you not having used the review tool.

**Comment by zcorpan** [comment]
A TIMEOUT result does not fail the check, but it's still a TIMEOUT result. Expand the "all results" from @w3c-bots comments above. If the test status changed relate to master, it would be good to file bugs about that at least.

**Review by zcorpan — APPROVED** [review]

**Comment by annevk** [comment]
I misunderstood. I'm not sure if this is new since when we checked this in initially these bots did not exist. @bobholt is this common with the new bots?

**Comment by bobholt** [comment]
@annevk: This is the first time I've seen it.

**Pull request merged**
