### PR TITLE
Improve assert_array_equals to recurse into the nested arrays

### LINKED ISSUE #8769: assert_array_equals should recurse into nested arrays
When comparing arrays with nested arrays, `assert_array_equals` should recurse into the nested arrays.

### PR DESCRIPTION
**Pull request by Honry**
also improve the desc to showing the actual/expected array contents
  and fix issue in assertion of array object

  Fix #8769

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8781)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-12-22 03:02:34
Finished: 2017-12-22 03:08:25


<h2>Failing Jobs</h2>
<ul>

<li>resources_unittest in py27</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22118)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/320039400)

**Comment by domenic** [comment]
This seems very bad. There are many existing tests that depend on the behavior of comparing object identity inside the arrays; it should not be changed.

If you have a specific test that needs to recurse, you can create your own function. But I think we should close this.

**Comment by Honry** [comment]
@domenic, thanks for your comment. 

>There are many existing tests that depend on the behavior of comparing object identity inside the arrays; it should not be changed.

I only recurse array object in my commit, other object identity inside the arrays should be the same as the one before. But I agree with you that it's a big risk for existing tests.

So let's go back to the requirement, shall we recurse into the nested arrays in "assert_array_equals"?

**Comment by domenic** [comment]
No. As I said, if you need this behavior in some test (please give an example), you can write your own separate helper.

**Comment by Honry** [comment]
OK, let me close it.

**Pull request closed without merging**
