### PR TITLE
Convert shapes-rect-01-t-manual.svg to reftests.

### PR DESCRIPTION
**Pull request by heycam**
This is my first attempt at converting a test from the SVG 1.1 test suite to web-platform-tests reftest format.  I'm looking for feedback that the approach I'm using here is correct.  There are very few SVG reftests in the tree to copy from.  While ugly, I think the structure and namespacing of the `metadata` element and its contents is what Shepherd expects, so I assume that's what we want here too.

Note that I haven't slavishly copied the test; instead I've added simpler reftests that cover what the original test was going for.

Also note that I've pointed the `<link rel=help>` elements to the undated SVG 2 TR/ link.  Hopefully that's the right thing to do.

### CODE REVIEW

**Comment by Ms2ger** [comment]
We don't care at all about Shepherd, it's a useless distraction.

@jgraham, maybe you could check the manifest code picks this up correctly?

**Comment by jgraham** [comment]
Seems like it:
      {
        "path": "svg/shapes/rect-01.svg",
        "references": [
          [
            "/svg/shapes/rect-01-ref.html",
            "=="
          ]
        ],
        "url": "/svg/shapes/rect-01.svg"
      },
      {
        "path": "svg/shapes/rect-02.svg",
        "references": [
          [
            "/svg/shapes/rect-02-ref.html",
            "=="
          ]
        ],
        "url": "/svg/shapes/rect-02.svg"
      },
      {
        "path": "svg/shapes/rect-03.svg",
        "references": [
          [
            "/svg/shapes/rect-03-ref.html",
            "=="
          ]
        ],
        "url": "/svg/shapes/rect-03.svg"
      },
      {
        "path": "svg/shapes/rect-04.svg",
        "references": [
          [
            "/svg/shapes/rect-04-ref.html",
            "=="
          ]
        ],
        "url": "/svg/shapes/rect-04.svg"
      },

**Comment by sideshowbarker** [comment]
Not sure if this is waiting on review or what. @Ms2ger

**Comment by Ms2ger** [comment]
Needs review, preferably from someone who knows SVG.

**Comment by sideshowbarker** [comment]
> Needs review, preferably from someone who knows SVG.

@nikosandronikos?

**Comment by nikosandronikos** [comment]
Functionality of the test is fine, so I think this is ok to merge. Agree with Cam that the structure is a bit ugly. SVG 2 allows html:link and html:meta elements so I prefer to just use them without the `metadata` element.

**Pull request merged**
