### PR TITLE
[wpt] Remove a redundant channel arg

### PR DESCRIPTION
**Pull request by Hexcles**
from Chrome.find_nightly_binary and fix call sites.

### CODE REVIEW

**Review by stephenmcgruer — APPROVED** [review]
Is there a reason the broken callsite didn't trip any test, and if so can we add one?

**Comment by Hexcles** [comment]
Yeah it wasn't used in the default code path. I've added a unit test to cover it specifically.

**Comment by stephenmcgruer** [comment]
> Yeah it wasn't used in the default code path. I've added a unit test to cover it specifically.

Thanks!

**Comment by Hexcles** [comment]
Of course it doesn't work on macOS...

**Pull request merged**
