### PR TITLE
Add tests for transformed-progress and input progress outside [0, 1].

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: 4t3fx3Adkhj

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1248340 [ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5349)

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5349/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218517920)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218517921)

**Pull request merged**
