### PR TITLE
Update font-size-adjust-interpolation.html

### PR DESCRIPTION
**Pull request by shahid-code-svg**
I done the changes please please please!accept it

### CODE REVIEW

**Comment by jfkthame** [comment]
I don't understand the purpose of this. What problem is it intended to fix?

**Comment by svgeesus** [comment]
@shahid-code-svg please explain what these changes are intended to accomplish.

**Comment by ChristianCiach** [comment]
He's a spammer. Just look at his other PRs like https://github.com/openjdk/jdk/pull/470/files

I think it has something to do with the current Hacktoberfest.  See https://hacktoberfest.digitalocean.com/hacktoberfest-update

You should probably just close this PR.

**Comment by monzturreminem** [comment]
I’m developing I’m not hacking or spamming I send what I need to to my bounce back address to get the info I refer cunt
Excuse my language but I am Eminem after all look at my name bitch
Love satoshi muthufucking Nakamoto welcome to my world hoe

Eminem

On Oct 1, 2020, at 10:52 AM, ChristianCiach <notifications@github.com> wrote:

﻿

He's a spammer. Just look at his other PRs like https://github.com/openjdk/jdk/pull/470/files

I think it has something to do with the current Hacktoberfest. See https://hacktoberfest.digitalocean.com/hacktoberfest-update

You should probably just close this PR.

**Comment by charlesfinley** [comment]
> @shahid-code-svg please explain what these changes are intended to accomplish.

Label these spam PRs as "invalid" and "spam" and they will not receive credit for these and it will deter further Hacktoberfest spam PRs.

**Pull request closed without merging**
