### PR TITLE
Make SRI crossorigin tests cross platform

### PR DESCRIPTION
**Pull request by joelweinberger**
The SRI tests had a bug in that they relied on the presence of a www1 prefix for domains in order to do cross-origin testing. This updates the SRI cross-origin tests to, instead, use the alternate port defined in the configuration. This is especially important for cross-platform testing that make use different configs.

### CODE REVIEW

**Comment by metromoxie** [comment]
Thanks for the fast review, Brad!

**Comment by hillbrad** [comment]
Thanks, Joel!

**Comment by jgraham** [comment]
OOI what was wrong with relying on the subdomain? That's supposed to exist in the environment where wpt runs.

**Comment by metromoxie** [comment]
Well, the first problem was that I wrote the original test to rely on a hard-coded subdomain. That was no good because the domains can change platform to platform.

As for using ports vs subdomains from the config for alternate origins, frankly it was just easier for me to figure out how to get the right port from the config, but not how to get the subdomain, so that's just on me :-/

**Pull request merged**
