### PR TITLE
Don't try to use blobs as CanvasImageSource for OffscreenCanvas tests

### PR DESCRIPTION
**Pull request by Cwiiis**
Several OffscreenCanvas tests try to directly pass the result of an
XMLHttpRequest directly into 2d canvas context functions that take
CanvasImageSource as an argument. As blob is not a valid CanvasImageSource,
these tests all fail with TypeError. This fixes issue #20867.

### CODE REVIEW

**Review by Ms2ger — CHANGES_REQUESTED** [review]
You also need to change `offscreen-canvas/tools/tests2d.yaml`

**Review by Ms2ger — APPROVED** [review]
The chrome failures seem spurious. CC @foolip

**Comment by guest271314** [comment]
What is the expected result of /offscreen-canvas/drawing-images-to-the-canvas/2d.drawImage.zerosource.html ?

**Comment by guest271314** [comment]
`"INDEX_SIZE_ERR"` does not appear in the current specification, `"IndexSizeError" DOMException` does appear in the specification, though not in `drawImage()` https://html.spec.whatwg.org/multipage/canvas.html#drawing-images and at step 3. of `convertToBlob()` of 

> 3. If this OffscreenCanvas object's bitmap has no pixels (i.e., either its horizontal dimension or its vertical dimension is zero) then return a promise rejected with an "IndexSizeError" DOMException.

The image used to create the `ImageBitmap` has pixels.

Therefore the question remains, what is the expected result of this test https://github.com/web-platform-tests/wpt/blob/d57d3ac856ee9c9fa4519c9692f1226ddf124c70/offscreen-canvas/drawing-images-to-the-canvas/2d.drawImage.zerosource.html in its current form?

**Comment by guest271314** [comment]
Am not certain what the parameter `p` is used for at `_assertPixelApprox(` function https://github.com/web-platform-tests/wpt/commit/f1b6e73dd019131333937f50b5101efecb5e1f1e#diff-8bab056587214c383696b6578a55150cL49 ? The argument is not used within the function body or in `_getPixels()`.

In order for the exception to be thrown `getImageData()` of `OffscreenCanvas` needs to be executed - which appears to be what is being tested - with the same parameters passed to `drawImage()`

    promise.then(function(response) {
      createImageBitmap(response).then(async bitmap => {
        try {
          ctx.drawImage(bitmap, 10, 10, 0, 1, 0, 0, 100, 50);
          ctx.getImageData(10, 10, 0, 1, 0, 0, 100, 50);
        } catch (e) {
          console.assert(e.name !== "IndexSizeError", [e.name]);
        }
        try {
          ctx.drawImage(bitmap, 10, 10, 1, 0, 0, 0, 100, 50);
          ctx.getImageData(10, 10, 1, 0, 0, 0, 100, 50);
        } catch (e) {
          console.assert(e.name !== "IndexSizeError", [e.name]);
        }
        try {
          ctx.drawImage(bitmap, 10, 10, 0, 0, 0, 0, 100, 50);
          ctx.getImageData(10, 10, 0, 0, 0, 0, 100, 50)
        } catch (e) {
          console.assert(e.name !== "IndexSizeError", [e.name]);
        }
        _assertPixelApprox(offscreenCanvas, 50, 25, 0, 255, 0, 255, "50,25", "0,255,0,255", 2);
      }).catch(console.error);
    }).then(console.log, console.error);

https://plnkr.co/edit/toM0bjvXwOY6n6uYbUti?p=preview

**Comment by guest271314** [comment]
Nightly 73 does throw `"IndexSizeError"` for `drawImage()`, however the current iteration of the specification https://html.spec.whatwg.org/multipage/canvas.html#drawing-images does not appear to explitly state that should occur.

**Pull request merged**
