### PR TITLE
Experiment with infrastructure fix

### PR DESCRIPTION
**Pull request by jugglinmike**
This branch is not intended to be merged to `master`.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5371)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218663083)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 3c5fe19974714299048008efb38bee8f566b61e5
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5371/tmp/demo.html">/tmp/demo.html</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| `this is a demonstration` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218663085)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 3c5fe19974714299048008efb38bee8f566b61e5
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5371/tmp/demo.html">/tmp/demo.html</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| `this is a demonstration` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5371/)

**Comment by jugglinmike** [comment]
Experiment complete.

**Pull request closed without merging**
