### PR TITLE
Remove interfaces/pointerevents-extension.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/34de77a/ed/idl/pointerevents-extension.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/611777172

### CODE REVIEW

**Comment by foolip** [comment]
This is blocked on https://chromium-review.googlesource.com/c/chromium/src/+/1906903 landing.

**Comment by NavidZ** [comment]
The Chromium CL is now merged.

**Comment by foolip** [comment]
Excellent, thanks @NavidZ!

**Comment by foolip** [comment]
It was exported in https://github.com/web-platform-tests/wpt/pull/20202

**Review by foolip — APPROVED** [review]

**Pull request merged**
