### PR TITLE
HTML: fieldset should have min-inline-size: min-content

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/html/issues/2078.

### CODE REVIEW

**Comment by annevk** [comment]
This doesn't test what happens if you change it. Presumably that should also be tested here?

**Comment by zcorpan** [comment]
There is a test already for min-width, but I could change it to be part of this test instead so overriding in the vertical case is also covered.

**Comment by annevk** [comment]
@bzbarsky or @emilio should probably review this as I'm not really familiar with these new CSS properties.

**Review by emilio — APPROVED** [review]

**Comment by B3ebec89** [comment]
@bzbarsky on @emilio should probably review this as I'm not really familiar with these new properties

**Pull request merged**
