### PR TITLE
[CSP] drop unnecessary check in Python handler

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This is from https://github.com/web-platform-tests/wpt/pull/6449 and appears to be a mutation of previous code where maybe it was needed? @jgraham can you give this a quick review? (I think the only way it could be wrong is if `request` isn't a [`Request`](https://github.com/web-platform-tests/wpt/blob/490e3894d4735b8f8771c3ead6c944e35659e901/tools/wptserve/wptserve/request.py#L160).

**Comment by foolip** [comment]
I've rebased this now, ping all reviewers :)

**Comment by foolip** [comment]
@stephenmcgruer can you review this? (Going through my open PRs.)

**Comment by stephenmcgruer** [comment]
Given this is for Python file handlers, assigning to @Hexcles to review.

**Review by Hexcles — APPROVED** [review]

**Pull request merged**
