### PR TITLE
HTML: Test CRLF/CR/LF and NULL in input.value

### PR DESCRIPTION
**Pull request by zcorpan**
Inspired by #5272

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239571004)

# Firefox (nightly) #
Testing web-platform-tests at revision 88461125cf6ca89b7493e20d6d6f59b6fc8684f2
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6149/html/semantics/forms/the-input-element/valueMode.html">/html/semantics/forms/the-input-element/valueMode.html</a></summary>


|                                  Subtest                                   | Results | Messages |
|----------------------------------------------------------------------------|---------|----------|
|                                                                            | OK      |          |
| `value IDL attribute of input type hidden without value attribute`         | PASS    |          |
| `value IDL attribute of input type hidden with value attribute`            | PASS    |          |
| `value IDL attribute of input type submit without value attribute`         | PASS    |          |
| `value IDL attribute of input type submit with value attribute`            | PASS    |          |
| `value IDL attribute of input type image without value attribute`          | PASS    |          |
| `value IDL attribute of input type image with value attribute`             | PASS    |          |
| `value IDL attribute of input type reset without value attribute`          | PASS    |          |
| `value IDL attribute of input type reset with value attribute`             | PASS    |          |
| `value IDL attribute of input type button without value attribute`         | PASS    |          |
| `value IDL attribute of input type button with value attribute`            | PASS    |          |
| `value IDL attribute of input type checkbox without value attribute`       | PASS    |          |
| `value IDL attribute of input type checkbox with value attribute`          | PASS    |          |
| `value IDL attribute of input type radio without value attribute`          | PASS    |          |
| `value IDL attribute of input type radio with value attribute`             | PASS    |          |
| `value IDL attribute of input type text without value attribute`           | PASS    |          |
| `value IDL attribute of input type text with value attribute`              | PASS    |          |
| `value IDL attribute of input type search without value attribute`         | PASS    |          |
| `value IDL attribute of input type search with value attribute`            | PASS    |          |
| `value IDL attribute of input type tel without value attribute`            | PASS    |          |
| `value IDL attribute of input type tel with value attribute`               | PASS    |          |
| `value IDL attribute of input type url without value attribute`            | PASS    |          |
| `value IDL attribute of input type url with value attribute`               | PASS    |          |
| `value IDL attribute of input type email without value attribute`          | PASS    |          |
| `value IDL attribute of input type email with value attribute`             | PASS    |          |
| `value IDL attribute of input type password without value attribute`       | PASS    |          |
| `value IDL attribute of input type password with value attribute`          | PASS    |          |
| `value IDL attribute of input type datetime-local without value attribute` | PASS    |          |
| `value IDL attribute of input type datetime-local with value attribute`    | PASS    |          |
| `value IDL attribute of input type date without value attribute`           | PASS    |          |
| `value IDL attribute of input type date with value attribute`              | PASS    |          |
| `value IDL attribute of input type month without value attribute`          | PASS    |          |
| `value IDL attribute of input type month with value attribute`             | PASS    |          |
| `value IDL attribute of input type week without value attribute`           | PASS    |          |
| `value IDL attribute of input type week with value attribute`              | PASS    |          |
| `value IDL attribute of input type time without value attribute`           | PASS    |          |
| `value IDL attribute of input type time with value attribute`              | PASS    |          |
| `value IDL attribute of input type number without value attribute`         | PASS    |          |
| `value IDL attribute of input type number with value attribute`            | PASS    |          |
| `value IDL attribute of input type range without value attribute`          | PASS    |          |
| `value IDL attribute of input type range with value attribute`             | PASS    |          |
| `value IDL attribute of input type color without value attribute`          | PASS    |          |
| `value IDL attribute of input type color with value attribute`             | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239571005)

# Sauce (safari) #
Testing web-platform-tests at revision 88461125cf6ca89b7493e20d6d6f59b6fc8684f2
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6149/html/semantics/forms/the-input-element/valueMode.html">/html/semantics/forms/the-input-element/valueMode.html</a></summary>


|                                  Subtest                                   | Results |                      Messages                     |
|----------------------------------------------------------------------------|---------|---------------------------------------------------|
|                                                                            | OK      |                                                   |
| `value IDL attribute of input type hidden without value attribute`         | PASS    |                                                   |
| `value IDL attribute of input type hidden with value attribute`            | PASS    |                                                   |
| `value IDL attribute of input type submit without value attribute`         | PASS    |                                                   |
| `value IDL attribute of input type submit with value attribute`            | PASS    |                                                   |
| `value IDL attribute of input type image without value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type image with value attribute`             | PASS    |                                                   |
| `value IDL attribute of input type reset without value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type reset with value attribute`             | PASS    |                                                   |
| `value IDL attribute of input type button without value attribute`         | PASS    |                                                   |
| `value IDL attribute of input type button with value attribute`            | PASS    |                                                   |
| `value IDL attribute of input type checkbox without value attribute`       | PASS    |                                                   |
| `value IDL attribute of input type checkbox with value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type radio without value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type radio with value attribute`             | PASS    |                                                   |
| `value IDL attribute of input type text without value attribute`           | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type text with value attribute`              | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type search without value attribute`         | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type search with value attribute`            | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type tel without value attribute`            | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type tel with value attribute`               | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type url without value attribute`            | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type url with value attribute`               | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type email without value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type email with value attribute`             | PASS    |                                                   |
| `value IDL attribute of input type password without value attribute`       | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type password with value attribute`          | FAIL    | `assert_equals: expected "foo\0" but got "foo"`   |
| `value IDL attribute of input type datetime-local without value attribute` | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type datetime-local with value attribute`    | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type date without value attribute`           | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type date with value attribute`              | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type month without value attribute`          | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type month with value attribute`             | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type week without value attribute`           | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type week with value attribute`              | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type time without value attribute`           | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type time with value attribute`              | FAIL    | `assert_equals: expected "" but got "foo"`        |
| `value IDL attribute of input type number without value attribute`         | PASS    |                                                   |
| `value IDL attribute of input type number with value attribute`            | PASS    |                                                   |
| `value IDL attribute of input type range without value attribute`          | PASS    |                                                   |
| `value IDL attribute of input type range with value attribute`             | PASS    |                                                   |
| `value IDL attribute of input type color without value attribute`          | FAIL    | `assert_equals: expected "#000000" but got "foo"` |
| `value IDL attribute of input type color with value attribute`             | FAIL    | `assert_equals: expected "#000000" but got "foo"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239571011)

# Chrome (unstable) #
Testing web-platform-tests at revision 88461125cf6ca89b7493e20d6d6f59b6fc8684f2

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239571012)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 88461125cf6ca89b7493e20d6d6f59b6fc8684f2

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by zcorpan** [comment]
https://bugs.webkit.org/show_bug.cgi?id=173048
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12263595/

**Comment by zcorpan** [comment]
The spec is as follows, if we take `type=text`:

https://html.spec.whatwg.org/multipage/forms.html#dom-input-value

mode is *value* per https://html.spec.whatwg.org/multipage/forms.html#text-(type=text)-state-and-search-state-(type=search):dom-input-value-value

So on setting, step 4 invokes https://html.spec.whatwg.org/multipage/forms.html#text-(type=text)-state-and-search-state-(type=search):value-sanitization-algorithm

> The value sanitization algorithm is as follows: Strip newlines from the value.

https://infra.spec.whatwg.org/#strip-newlines is defined as

> To strip newlines from a string, remove any U+000A LF and U+000D CR code points from the string.

So U+0000 should not be removed from the value.

**Review by cvrebert — APPROVED** [review]

**Pull request merged**
