### PR TITLE
Add interfaces/screen-wake-lock.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/9cdbf49/ed/idl/screen-wake-lock.idl
Build: https://travis-ci.org/w3c/webref/builds/732950411

### CODE REVIEW

**Comment by rakuco** [comment]
@stephenmcgruer The IDL looks fine, but we already have `wake-lock.idl` here, so I have a few questions:

- Was this one created because we published a new TR with the new short name last week?
- How should one deal with both IDL files? Does `wake-lock.idl` have to be deleted manually and will tests need to be adjusted?
- If this file was created because of the TR, does it mean it won't be updated with changes to the ED?

**Comment by rakuco** [comment]
> * If this file was created because of the TR, does it mean it won't be updated with changes to the ED?

I guess it will given the change that was pushed to this PR an hour ago.

**Comment by stephenmcgruer** [comment]
These questions seems more to do with how reffy syncs specs, so assigning to @foolip if he doesn't mind :)

**Comment by rakuco** [comment]
@foolip friendly ping. I've got a CL in Chromium that depends on the IDL changes in this PR, so I'd appreciate some guidance on which IDL file to use.

**Comment by foolip** [comment]
@rakuco the creation of https://www.w3.org/TR/screen-wake-lock/ is indeed what led to this, as Reffy uses the TR shortname if one exists. Furthermore, Reffy never deletes files in webref, so one has to manually delete the old ones. I'm doing that in https://github.com/w3c/webref/pull/65.

The script that sync IDL with WPT does delete files ([example](https://github.com/web-platform-tests/wpt/pull/25768)) but deleting the old and adding the new separately is not useful, so the right way to resolve it is to manually do the renaming: https://github.com/web-platform-tests/wpt/pull/26024

**Comment by rakuco** [comment]
Thanks for the clarification, @foolip! The only follow-up question I have is whether the IDL sync infrastructure will later send another PR to sync IDL changes to `screen-wake-lock.idl` after #26024 (the file being renamed is still missing a change to the `WakeLock.request()` method that was present in this PR).

**Comment by foolip** [comment]
Yep, the bot will always create new PRs when the files don't match.

**Pull request closed without merging**
