### PR TITLE
SVG Geometry Properties - parsing

### PR DESCRIPTION
**Pull request by ewilligers**
The properties cx cy r rx ry x y have the specified initial values,
grammar and inheritance behavior.
https://svgwg.org/svg2-draft/geometry.html

### CODE REVIEW

**Comment by ewilligers** [comment]
Builds on https://github.com/web-platform-tests/wpt/pull/13943

**Review by dirkschulze — APPROVED** [review]
Tests look good. Could we get additional tests for the computed value? `auto` computes to different things in different properties. Same for geometry properties with percentage values on paint servers.

**Comment by ewilligers** [comment]
I will create a separate PR for computed values.

**Comment by foolip** [comment]
@ewilligers, the stability checks on Travis create rather a lot of trouble and I'd like to disable them sooner rather than later, see https://github.com/web-platform-tests/wpt/pull/14033.

I don't know if it's expected that there's no output at all while this script is running, or if "travis_wait 30" would just lead to it failing in the same way after 30 minutes.

For now please just ignore the check, I'll override and admin merge this.

**Pull request merged**
