### PR TITLE
Improve MediaQueryListEvent coverage

### PR DESCRIPTION
**Pull request by shvaikalesh**
Related: #18390, #19841.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
CC @annevk.

**Comment by annevk** [comment]
@svgeesus could you find a reviewer for this in the CSS WG? I wasn't really involved in changing this from callbacks to events I think.

**Comment by shvaikalesh** [comment]
@zcorpan and @skynavga are listed as former editors of [CSSOM View Module spec](https://drafts.csswg.org/cssom-view), perhaps they could perform a review?

**Review by zcorpan — APPROVED** [review]
Per https://wpt.fyi/results/css/cssom-view/MediaQueryListEvent.html?label=pr_head&max-count=1&pr=18389 the tests pass in Chrome & Firefox, fail in Safari. Is there a bug filed for WebKit?

**Comment by shvaikalesh** [comment]
WebKit issue: [MediaQueryList should extend EventTarget](https://bugs.webkit.org/show_bug.cgi?id=203288).

I've filed more general issue (instead of specific to `MediaQueryListEvent`) so one could fix all Safari incompatibilities in one patch (that would be rather small).

**Pull request merged**
