### PR TITLE
Added parsing tests for properties in CSS Borders 4

### PR DESCRIPTION
**Pull request by SebastianZ**
This adds an initial set of parsing tests related to the CSS properties introduced in [CSS Borders 4](https://drafts.csswg.org/css-borders-4/).

Sebastian

### CODE REVIEW

**Comment by TalbotG** [comment]
This Pull Request is the continuation of [Pull Request 42345](https://github.com/web-platform-tests/wpt/pull/42345) and is related to it.

**Comment by gsnedders** [comment]
> This Pull Request is the continuation of [Pull Request 42345](https://github.com/web-platform-tests/wpt/pull/42345) and is related to it.

Does this supersede the earlier PR? If so, that should be closed.

**Comment by gsnedders** [comment]
In general, we don't have versioned directories (c.f. https://github.com/web-platform-tests/wpt/issues/44527); given the draft spec isn't ready for implementation, a file like `css/css-borders-4/parsing/border-block-end-radius-computed.html` in this PR should probably be renamed to `css/css-borders/parsing/border-block-end-radius-computed.tentative.html`.

**Comment by SebastianZ** [comment]
> > This Pull Request is the continuation of [Pull Request 42345](https://github.com/web-platform-tests/wpt/pull/42345) and is related to it.
> 
> Does this supersede the earlier PR? If so, that should be closed.

It doesn't. @TalbotG just [asked me to split the parsing tests from the rest (point 20)](https://github.com/web-platform-tests/wpt/pull/42345#issuecomment-1924935613), so it's easier to review them.

> In general, we don't have versioned directories (c.f. #44527);

I saw that there are basically no versioned directories. Though being able to check which tests are for which level of the spec. is required to see how well that spec. level is covered by tests. So how do you distinguish the tests between the different spec. levels then?

Also note that there _is already_ a css-borders folder with tests that actually target features of CSS Backgrounds 3. So I assume those should be moved to css-backgrounds then, right?

Though I guess that's something to discuss in the other issue.

> given the draft spec isn't ready for implementation, a file like `css/css-borders-4/parsing/border-block-end-radius-computed.html` in this PR should probably be renamed to `css/css-borders/parsing/border-block-end-radius-computed.tentative.html`.

Disregarding the versioning issue, I can add a "tentative" suffix as suggested as long as the spec. doesn't have a FPWD yet, if that's required.

Sebastian

**Comment by SebastianZ** [comment]
> > there is already a css-borders folder with tests that actually target features of CSS Backgrounds 3.
> 
> It was decided to split future levels of CSS Backgrounds and Borders into `css/css-backgrounds/` and `css/css-borders/`

Well, it was [my request to split the specs](https://github.com/w3c/csswg-drafts/issues/7664). Though the tests in the css-borders folder were created by some people long before that split and cover features introduced in CSS Backgrounds 3 (and which are not yet added to CSS Borders 4 as it is still a delta specification).

Sebastian

**Comment by SebastianZ** [comment]
> " .tentative : Indicates that a test makes assertions not yet required by any specification, (...) This flag can be enabled for an entire directory (and all its descendents), by naming the directory ‘tentative’. For example, every test underneath ‘foo/tentative/’ will be considered tentative. " coming from http://web-platform-tests.org/writing-tests/file-names.html#test-features

Well, the assertions _are_ required by the specification. Though the specification itself isn't mature yet, because there's no FPWD yet. So I guess I should put all the tests in a `tentative/` folder, right?

Sebastian

**Comment by TalbotG** [comment]
> So I guess I should put all the tests in a `tentative/` folder, right?

Yes. Only the tests though. Not the reference files. Not the support files.

**Comment by TalbotG** [comment]
Your parsing tests:

http://www.gtalbot.org/BrowserBugsSection/CSS4BordersBoxDecorations/parsing/

Note that .js files are not at "/" but at "./" which is different from when tests are git-submitted and approved.
I also appended "-SZ" to your tests.
I need to double-check these tests, just in case I made a copy-&-paste error.

**Comment by TalbotG** [comment]
In
parsing/box-shadow-color-computed.html
at line 14, I see
`test_computed_value("box-shadow-color", "currentcolor", "rgb(255, 0, 0)");`
but I can not find where the spec would suggests this. In my opinion, line 14 should be
`test_computed_value("box-shadow-color", "currentcolor", "rgb(0, 0, 0)");`

"The initial value of color is black."
coming from
http://web-platform-tests.org/writing-tests/assumptions.html

**Comment by TalbotG** [comment]
In
parsing/box-shadow-position-valid.html
and in
parsing/box-shadow-position-computed.html
you can add
`test_valid_value("box-shadow-position", "outset, inset");`
and
`test_computed_value("box-shadow-position", "outset, inset");`

**Comment by TalbotG** [comment]
In
parsing/box-shadow-blur-valid.html
at line 12
test_valid_value("box-shadow-blur", "0", "0px");
should be
test_valid_value("box-shadow-blur", "0");

**Comment by SebastianZ** [comment]
I think I've addressed all the issues and concerns. So @TalbotG @gsnedders, could you please have a look again?

Sebastian

**Comment by TalbotG** [comment]
Sebastian,
I looked at your 2c6cc45 commit and at your a762890 commit and everything seems correct and fine. I will approve your Pull request as soon as @gsnedders Sam gives his Okay.

If later we find something wrong with a test or 2, we can then create another PR.

Gérard

**Comment by SebastianZ** [comment]
@gsnedders Did you already have time to look at this?

Sebastian

**Comment by TalbotG** [comment]
The only small doubt I have - and that is why I thought we should have a second opinion on this - is where the /tentative/ folder should be (assuming that it does matter). 
E.g. should the test files be moved to
/css/css-borders/**tentative**/parsing/test-filename.html

or moved to

/css/css-borders/parsing/**tentative**/test-filename.html

It may even not matter anyway... but @gsnedders would know that for sure.
I have never created tentative tests or use a /tentative/ folder .

Sebastian, your tests as far as I am concerned are good, worthy, correct, precise and compliant with all kinds of formating recommandations. I will wait a few more days and if we do not hear from Sam, then I will approve PR44525 .

Gérard

**Comment by TalbotG** [comment]
I approve the commits.

**Review by TalbotG — APPROVED** [review]
I approve these tests and the commits.

**Comment by TalbotG** [comment]
Sebastian,

If later there is a problem or complaint or issue with any of those 48 /parsing/ tests, then please let me know about it.

Gérard

**Comment by SebastianZ** [comment]
Thank you a lot for the reviews, help, and patience!

Sebastian

**Pull request merged**
