### PR TITLE
Move Travis CI to Xenial (16.04 LTS)

### PR DESCRIPTION
**Pull request by gsnedders**

### CODE REVIEW

**Comment by gsnedders** [comment]
Largely trying this to see if it fixes #15728, given nobody can repro it locally and it doesn't happen on TC (running 18.04 LTS).

**Comment by gsnedders** [comment]
see https://github.com/travis-ci/docs-travis-ci-com/issues/2233 for the Xvfb changes.

**Comment by gsnedders** [comment]
still hitting #15728 sadly, so this doesn't fix that :/

**Review by jgraham — CHANGES_REQUESTED** [review]
I think we should drop this and move off travis instead.

**Pull request closed without merging**
