### PR TITLE
Removing sub filename prefix for tests no longer needing it

### PR DESCRIPTION
**Pull request by youennf**
Follow-up of PR 3543 and PR 3544

### CODE REVIEW

**Comment by youennf** [comment]
Follow up of https://github.com/w3c/web-platform-tests/pull/3544 and https://github.com/w3c/web-platform-tests/pull/3543

**Comment by youennf** [comment]
@zcorpan

**Comment by zcorpan** [comment]
The canvas tests have this comment

```
<!-- DO NOT EDIT! This test has been generated by tools/gentest.py. -->
```

I think that would be in https://github.com/w3c/web-platform-tests/tree/master/2dcontext/tools and in particular tests.yaml. I should have pointed this out for the previous PRs but missed it. Do you want to take a stab at changing tests.yaml and re-generating?

**Comment by youennf** [comment]
I'll check that, if it is only about changing tests.yaml, that should be fine.

**Comment by youennf** [comment]
Refreshing of yams tests is done at https://github.com/w3c/web-platform-tests/pull/3631

**Comment by sideshowbarker** [comment]
@zcorpan see update

**Comment by zcorpan** [comment]
Thanks!

**Pull request merged**
