### PR TITLE
Call done() correctly in /workers/nested_worker.worker.js

### LINKED ISSUE #11195: /workers/nested_worker.worker.html is slow/disabled in chromium webkit
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/workers/nested_worker.worker.html | chromium webkit | [ Timeout ] [ Skip ] | https://crbug.com/709227 None

This test should call `done()` after `async_test()` and should call `t.done()` where it's currently calling `done()`.

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #11195.

### CODE REVIEW

**Review by jugglinmike — CHANGES_REQUESTED** [review]
> I don't understand why this makes a difference. The onmessage handler uses step_func_done which should have the same effect as explicitly calling t.done() in this case.

I agree that the `t.done` invocation is superfluous. @zcorpan would you mind removing it for clarity's sake?

The relocation of `done` is important because it de-couples the test status from the harness status. In other words: if the assertion fails, the test will fail instead of timing out.

**Comment by zcorpan** [comment]
Ah yes, I missed that it was using `step_func_done`.

**Review by jugglinmike — APPROVED** [review]
I did, too. It was a good catch on @jdm's part.

Awaiting TravisCI report...

**Comment by jugglinmike** [comment]
Thanks, Simon!

**Pull request merged**
