### PR TITLE
CSS Transforms 2: Web Platform Tests for translate,rotate,scale parsing


### PR DESCRIPTION
**Pull request by jeffcarp**
These are the first Web Platform Tests for the Individual Transform
Properties.

Spec:
https://drafts.csswg.org/css-transforms-2/#individual-transforms

BUG=722696

Review-Url: https://codereview.chromium.org/2882153004
Cr-Commit-Position: refs/heads/master@{#473775}

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723748)

# Firefox (nightly) #
Testing web-platform-tests at revision 51efb58ed062eaa6e0500c8b233688cd3ff05192
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-invalid.html">/css/css-transforms-2/parsing/rotate-parsing-invalid.html</a></summary>


|                                     Subtest                                      | Results |                            Messages                           |
|----------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                  | OK      |                                                               |
| `e.style['rotate'] = "100px" should not set the property value`                  | FAIL    | `assert_equals: expected "" but got "100px"`                  |
| `e.style['rotate'] = "100 400deg" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100 400deg"`             |
| `e.style['rotate'] = "100 200 400deg" should not set the property value`         | FAIL    | `assert_equals: expected "" but got "100 200 400deg"`         |
| `e.style['rotate'] = "100 200 300 500 400deg" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 500 400deg"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-valid.html">/css/css-transforms-2/parsing/rotate-parsing-valid.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `e.style['rotate'] = "none" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "none"`                | PASS    |          |
| `e.style['rotate'] = "0deg" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "0deg"`                | PASS    |          |
| `e.style['rotate'] = "100 200 300 400grad" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "100 200 300 400grad"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-invalid.html">/css/css-transforms-2/parsing/scale-parsing-invalid.html</a></summary>


|                                 Subtest                                  | Results |                        Messages                        |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------|
|                                                                          | OK      |                                                        |
| `e.style['scale'] = "100px" should not set the property value`           | FAIL    | `assert_equals: expected "" but got "100px"`           |
| `e.style['scale'] = "100 200 300 400" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 400"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-valid.html">/css/css-transforms-2/parsing/scale-parsing-valid.html</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `e.style['scale'] = "none" should set the property value`                        | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "none"`        | PASS    |          |
| `e.style['scale'] = "1" should set the property value`                           | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "1"`           | PASS    |          |
| `e.style['scale'] = "100 200" should set the property value`                     | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200"`     | PASS    |          |
| `e.style['scale'] = "100 200 300" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200 300"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-invalid.html">/css/css-transforms-2/parsing/translate-parsing-invalid.html</a></summary>


|                                          Subtest                                          | Results |                               Messages                              |
|-------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------|
|                                                                                           | OK      |                                                                     |
| `e.style['translate'] = "100deg" should not set the property value`                       | FAIL    | `assert_equals: expected "" but got "100deg"`                       |
| `e.style['translate'] = "100px 200px 300%" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100px 200px 300%"`             |
| `e.style['translate'] = "100px 200px calc(30px + 30%)" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100px 200px calc(30px + 30%)"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-valid.html">/css/css-transforms-2/parsing/translate-parsing-valid.html</a></summary>


|                                                           Subtest                                                            | Results |                           Messages                          |
|------------------------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------|
|                                                                                                                              | OK      |                                                             |
| `e.style['translate'] = "none" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "none"`                                                | PASS    |                                                             |
| `e.style['translate'] = "0px" should set the property value`                                                                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0px"`                                                 | PASS    |                                                             |
| `e.style['translate'] = "100%" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100%"`                                                | PASS    |                                                             |
| `e.style['translate'] = "100px 200%" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200%"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100% 200px" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200px"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100px 200px 300px" should set the property value`                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200px 300px"`                                   | PASS    |                                                             |
| `e.style['translate'] = "100% 200% 300px" should set the property value`                                                     | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200% 300px"`                                     | PASS    |                                                             |
| `e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)" should set the property value`                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)"` | PASS    |                                                             |
| `e.style['translate'] = "0" should set the property value`                                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0"`                                                   | FAIL    | `assert_equals: expected "0px" but got "0"`                 |
| `e.style['translate'] = "1px 2px 0" should set the property value`                                                           | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "1px 2px 0"`                                           | FAIL    | `assert_equals: expected "1px 2px 0px" but got "1px 2px 0"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723749)

# Sauce (safari) #
Testing web-platform-tests at revision 51efb58ed062eaa6e0500c8b233688cd3ff05192
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-invalid.html">/css/css-transforms-2/parsing/rotate-parsing-invalid.html</a></summary>


|                                     Subtest                                      | Results |                            Messages                           |
|----------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                  | OK      |                                                               |
| `e.style['rotate'] = "100px" should not set the property value`                  | FAIL    | `assert_equals: expected "" but got "100px"`                  |
| `e.style['rotate'] = "100 400deg" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100 400deg"`             |
| `e.style['rotate'] = "100 200 400deg" should not set the property value`         | FAIL    | `assert_equals: expected "" but got "100 200 400deg"`         |
| `e.style['rotate'] = "100 200 300 500 400deg" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 500 400deg"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-valid.html">/css/css-transforms-2/parsing/rotate-parsing-valid.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `e.style['rotate'] = "none" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "none"`                | PASS    |          |
| `e.style['rotate'] = "0deg" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "0deg"`                | PASS    |          |
| `e.style['rotate'] = "100 200 300 400grad" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "100 200 300 400grad"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-invalid.html">/css/css-transforms-2/parsing/scale-parsing-invalid.html</a></summary>


|                                 Subtest                                  | Results |                        Messages                        |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------|
|                                                                          | OK      |                                                        |
| `e.style['scale'] = "100px" should not set the property value`           | FAIL    | `assert_equals: expected "" but got "100px"`           |
| `e.style['scale'] = "100 200 300 400" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 400"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-valid.html">/css/css-transforms-2/parsing/scale-parsing-valid.html</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `e.style['scale'] = "none" should set the property value`                        | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "none"`        | PASS    |          |
| `e.style['scale'] = "1" should set the property value`                           | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "1"`           | PASS    |          |
| `e.style['scale'] = "100 200" should set the property value`                     | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200"`     | PASS    |          |
| `e.style['scale'] = "100 200 300" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200 300"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-invalid.html">/css/css-transforms-2/parsing/translate-parsing-invalid.html</a></summary>


|                                          Subtest                                          | Results |                               Messages                              |
|-------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------|
|                                                                                           | OK      |                                                                     |
| `e.style['translate'] = "100deg" should not set the property value`                       | FAIL    | `assert_equals: expected "" but got "100deg"`                       |
| `e.style['translate'] = "100px 200px 300%" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100px 200px 300%"`             |
| `e.style['translate'] = "100px 200px calc(30px + 30%)" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100px 200px calc(30px + 30%)"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-valid.html">/css/css-transforms-2/parsing/translate-parsing-valid.html</a></summary>


|                                                           Subtest                                                            | Results |                           Messages                          |
|------------------------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------|
|                                                                                                                              | OK      |                                                             |
| `e.style['translate'] = "none" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "none"`                                                | PASS    |                                                             |
| `e.style['translate'] = "0px" should set the property value`                                                                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0px"`                                                 | PASS    |                                                             |
| `e.style['translate'] = "100%" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100%"`                                                | PASS    |                                                             |
| `e.style['translate'] = "100px 200%" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200%"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100% 200px" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200px"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100px 200px 300px" should set the property value`                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200px 300px"`                                   | PASS    |                                                             |
| `e.style['translate'] = "100% 200% 300px" should set the property value`                                                     | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200% 300px"`                                     | PASS    |                                                             |
| `e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)" should set the property value`                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)"` | PASS    |                                                             |
| `e.style['translate'] = "0" should set the property value`                                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0"`                                                   | FAIL    | `assert_equals: expected "0px" but got "0"`                 |
| `e.style['translate'] = "1px 2px 0" should set the property value`                                                           | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "1px 2px 0"`                                           | FAIL    | `assert_equals: expected "1px 2px 0px" but got "1px 2px 0"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723755)

# Chrome (unstable) #
Testing web-platform-tests at revision 51efb58ed062eaa6e0500c8b233688cd3ff05192
Using browser at version 60.0.3107.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-invalid.html">/css/css-transforms-2/parsing/rotate-parsing-invalid.html</a></summary>


|                                     Subtest                                      | Results |                            Messages                           |
|----------------------------------------------------------------------------------|---------|---------------------------------------------------------------|
|                                                                                  | OK      |                                                               |
| `e.style['rotate'] = "100px" should not set the property value`                  | FAIL    | `assert_equals: expected "" but got "100px"`                  |
| `e.style['rotate'] = "100 400deg" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100 400deg"`             |
| `e.style['rotate'] = "100 200 400deg" should not set the property value`         | FAIL    | `assert_equals: expected "" but got "100 200 400deg"`         |
| `e.style['rotate'] = "100 200 300 500 400deg" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 500 400deg"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/rotate-parsing-valid.html">/css/css-transforms-2/parsing/rotate-parsing-valid.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `e.style['rotate'] = "none" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "none"`                | PASS    |          |
| `e.style['rotate'] = "0deg" should set the property value`                                | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "0deg"`                | PASS    |          |
| `e.style['rotate'] = "100 200 300 400grad" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['rotate'] = "100 200 300 400grad"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-invalid.html">/css/css-transforms-2/parsing/scale-parsing-invalid.html</a></summary>


|                                 Subtest                                  | Results |                        Messages                        |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------|
|                                                                          | OK      |                                                        |
| `e.style['scale'] = "100px" should not set the property value`           | FAIL    | `assert_equals: expected "" but got "100px"`           |
| `e.style['scale'] = "100 200 300 400" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100 200 300 400"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/scale-parsing-valid.html">/css/css-transforms-2/parsing/scale-parsing-valid.html</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `e.style['scale'] = "none" should set the property value`                        | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "none"`        | PASS    |          |
| `e.style['scale'] = "1" should set the property value`                           | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "1"`           | PASS    |          |
| `e.style['scale'] = "100 200" should set the property value`                     | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200"`     | PASS    |          |
| `e.style['scale'] = "100 200 300" should set the property value`                 | PASS    |          |
| `Serialization should round-trip after setting e.style['scale'] = "100 200 300"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-invalid.html">/css/css-transforms-2/parsing/translate-parsing-invalid.html</a></summary>


|                                          Subtest                                          | Results |                               Messages                              |
|-------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------|
|                                                                                           | OK      |                                                                     |
| `e.style['translate'] = "100deg" should not set the property value`                       | FAIL    | `assert_equals: expected "" but got "100deg"`                       |
| `e.style['translate'] = "100px 200px 300%" should not set the property value`             | FAIL    | `assert_equals: expected "" but got "100px 200px 300%"`             |
| `e.style['translate'] = "100px 200px calc(30px + 30%)" should not set the property value` | FAIL    | `assert_equals: expected "" but got "100px 200px calc(30px + 30%)"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6038/css/css-transforms-2/parsing/translate-parsing-valid.html">/css/css-transforms-2/parsing/translate-parsing-valid.html</a></summary>


|                                                           Subtest                                                            | Results |                           Messages                          |
|------------------------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------|
|                                                                                                                              | OK      |                                                             |
| `e.style['translate'] = "none" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "none"`                                                | PASS    |                                                             |
| `e.style['translate'] = "0px" should set the property value`                                                                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0px"`                                                 | PASS    |                                                             |
| `e.style['translate'] = "100%" should set the property value`                                                                | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100%"`                                                | PASS    |                                                             |
| `e.style['translate'] = "100px 200%" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200%"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100% 200px" should set the property value`                                                          | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200px"`                                          | PASS    |                                                             |
| `e.style['translate'] = "100px 200px 300px" should set the property value`                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100px 200px 300px"`                                   | PASS    |                                                             |
| `e.style['translate'] = "100% 200% 300px" should set the property value`                                                     | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "100% 200% 300px"`                                     | PASS    |                                                             |
| `e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)" should set the property value`                 | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "calc(10px + 10%) calc(20px + 20%) calc(30px + 30em)"` | PASS    |                                                             |
| `e.style['translate'] = "0" should set the property value`                                                                   | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "0"`                                                   | FAIL    | `assert_equals: expected "0px" but got "0"`                 |
| `e.style['translate'] = "1px 2px 0" should set the property value`                                                           | PASS    |                                                             |
| `Serialization should round-trip after setting e.style['translate'] = "1px 2px 0"`                                           | FAIL    | `assert_equals: expected "1px 2px 0px" but got "1px 2px 0"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723756)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 51efb58ed062eaa6e0500c8b233688cd3ff05192

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
