### PR TITLE
HTML: document.open() and the document's encoding

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Review by domenic — APPROVED** [review]
Still don't understand why you keep testing document.close() in your document.open() tests, but this will test the issue, I suppose.

**Comment by domenic** [comment]
w3c-test:mirror

**Comment by annevk** [comment]
Did you try removing it and running it in all browsers?

**Comment by domenic** [comment]
Nope. I just think if there is some reason, a comment would help explain it, instead of relying on the reader to do such experimentation.

**Pull request merged**
