### PR TITLE
Fetch KeepAlive Quota Tests

### PR DESCRIPTION
**Pull request by Brandr0id**
Initial add of quota tests for keepalive fetch requests.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 9e878bdf7bd72882d6251a820d128748772719d5
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4878/fetch/api/request/request-keepalive-quota.html">/fetch/api/request/request-keepalive-quota.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `A Keep-Alive fetch() with a body over the Quota Limit should reject.`                  | FAIL    |
| `A Keep-Alive fetch() should not be allowed if the Quota is used up.`                   | FAIL    |
| `A Keep-Alive fetch() should return only it's allocated Quota upon promise resolution.` | PASS    |
| `A Keep-Alive fetch() with a body at the Quota Limit should succeed.`                   | PASS    |
| `A Keep-Alive fetch() should return it's allocated Quota upon promise resolution.`      | PASS    |
| `A Keep-Alive fetch() with a small body should succeed.`                                | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 9e878bdf7bd72882d6251a820d128748772719d5
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4878/fetch/api/request/request-keepalive-quota.html">/fetch/api/request/request-keepalive-quota.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `A Keep-Alive fetch() with a body over the Quota Limit should reject.`                  | FAIL    |
| `A Keep-Alive fetch() should not be allowed if the Quota is used up.`                   | FAIL    |
| `A Keep-Alive fetch() should return only it's allocated Quota upon promise resolution.` | PASS    |
| `A Keep-Alive fetch() with a body at the Quota Limit should succeed.`                   | PASS    |
| `A Keep-Alive fetch() should return it's allocated Quota upon promise resolution.`      | PASS    |
| `A Keep-Alive fetch() with a small body should succeed.`                                | PASS    |

</details>
</details>

**Comment by annevk** [comment]
Thanks, I already reviewed these in #4788 and they still look good. I'd like to land them together with https://github.com/whatwg/fetch/pull/419 which still needs a bit of rebasing work.

**Comment by annevk** [comment]
Thanks again for writing these!

**Pull request merged**
