### PR TITLE
[Azure Pipelines] Differentiate manual triggers for Edge Dev/Canary

### PR DESCRIPTION
**Pull request by foolip**
As it is, it's only possible to run both of them:
https://github.com/web-platform-tests/wpt/issues/17342#issuecomment-521534275

### CODE REVIEW

**Comment by thejohnjansen** [comment]
This implies a subsequent change to add "Dev" and then "Stable" I presume?

**Comment by foolip** [comment]
Yeah, when Edge stable is added, I'd suggest adding -dev/_dev to the Edge Dev configuration. I could do that now though, if you prefer.

**Comment by thejohnjansen** [comment]
It would be awesome if you could add that now for dev just so we continue running both. We will add stable when that time comes.

**Comment by foolip** [comment]
They would both have kept running every 6 hours per the `eq(variables['Build.Reason'], 'Schedule')` part of the condition, but I've now renamed the Edge Dev job and artifacts so that Edge stable can later be added without further renaming.

**Review by thejohnjansen — APPROVED** [review]

**Pull request merged**
