### PR TITLE
[geometry] DOMMatrix a-f getters don't invoke m11-m42 getters

### PR DESCRIPTION
**Pull request by zcorpan**
Test for https://github.com/w3c/fxtf-drafts/commit/fc9cbb2eaaca015a08ff25f15c3b5992e99ed0a6

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231101665)

# Firefox (nightly) #
Testing web-platform-tests at revision 7f255e5d80e3038feb1701f68ea12fe9c0aa2026
Using browser at version BuildID 20170510183715; SourceStamp ce2218406119c36a551e3faea4e192186ee46cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5886/css/geometry-1/DOMMatrix-a-f-alias.html">/css/geometry-1/DOMMatrix-a-f-alias.html</a></summary>


|                          Subtest                           | Results |        Messages        |
|------------------------------------------------------------|---------|------------------------|
|                                                            | OK      |                        |
| `DOMMatrix getting a with throwing getter for m11`         | PASS    |                        |
| `DOMMatrix getting m11 with throwing getter for a`         | PASS    |                        |
| `DOMMatrix getting b with throwing getter for m12`         | PASS    |                        |
| `DOMMatrix getting m12 with throwing getter for b`         | PASS    |                        |
| `DOMMatrix getting c with throwing getter for m21`         | PASS    |                        |
| `DOMMatrix getting m21 with throwing getter for c`         | PASS    |                        |
| `DOMMatrix getting d with throwing getter for m22`         | PASS    |                        |
| `DOMMatrix getting m22 with throwing getter for d`         | PASS    |                        |
| `DOMMatrix getting e with throwing getter for m41`         | PASS    |                        |
| `DOMMatrix getting m41 with throwing getter for e`         | PASS    |                        |
| `DOMMatrix getting f with throwing getter for m42`         | PASS    |                        |
| `DOMMatrix getting m42 with throwing getter for f`         | PASS    |                        |
| `DOMMatrixReadOnly getting a with throwing getter for m11` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m11 with throwing getter for a` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting b with throwing getter for m12` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m12 with throwing getter for b` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting c with throwing getter for m21` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m21 with throwing getter for c` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting d with throwing getter for m22` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m22 with throwing getter for d` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting e with throwing getter for m41` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m41 with throwing getter for e` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting f with throwing getter for m42` | FAIL    | `Illegal constructor.` |
| `DOMMatrixReadOnly getting m42 with throwing getter for f` | FAIL    | `Illegal constructor.` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231101673)

# Chrome (unstable) #
Testing web-platform-tests at revision 023624cd00ca81146a09878365e4f0698601ee1d

**Comment by zcorpan** [comment]
Chrome with experimental web platform features passes all tests. Firefox passes all tests for `DOMMatrix`, fails all for `DOMMatrixReadOnly` since it doesn't support the constructor there.

**Review by foolip — APPROVED** [review]

**Comment by zcorpan** [comment]
You should have squashed 😊

**Comment by foolip** [comment]
Yes, I noticed too late. When I first tried to squash, it failed with some red banner at the top, and then I reloaded and clicked the green button too quickly.

**Comment by zcorpan** [comment]
Huh, weird. Don't think I've seen such failures (maybe only for lack of connectivity)... Anyway, no biggie.

**Pull request merged**
