### PR TITLE
[py3] convert conformance-checkers/tools/*.py

### PR DESCRIPTION
**Pull request by foolip**
Because dicts are ordered in Python 3, the order of the tests generated
by url.py change. It was confirmed that exactly the same set of lines
have been added and removed, with this command:
```sh
diff <(git diff | grep '^+[^+]' | cut -c 2- | sort) <(git diff | grep '^-[^-]' | cut -c 2- | sort)
```

Also ensure update-built-tests.sh is run when conformance-checkers/ is
updated, missed in https://github.com/web-platform-tests/wpt/pull/28832.

### CODE REVIEW

**Comment by foolip** [comment]
@sideshowbarker this doesn't work yet, but before I spend any more time on it I'd like to ask if these scripts are actually used? Even the py2 variants produce lots of changes, so maybe they were once used to create lots of tests, but those tests have then been edited by hand? Should they be brought into sync again?

**Comment by sideshowbarker** [comment]
> @sideshowbarker this doesn't work yet, but before I spend any more time on it I'd like to ask if these scripts are actually used?

The `build-svg-tests.py` one is the only that’s not used. I think. I suppose we could just remove it.

The others are still used, though not often. @zcorpan developed some of them (maybe most).

> Even the py2 variants produce lots of changes, so maybe they were once used to create lots of tests, but those tests have then been edited by hand?

If any of the test files those script generate — other than the SVG tests — were edited by hand, then that’s an oversight and a bug. In all cases, what should happen is that the code for generating them is edited instead.

> Should they be brought into sync again?

They should be brought into sync again, yes.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/28832 to first get this into a good state with Python 2.7.

**Review by zcorpan — APPROVED** [review]

**Comment by foolip** [comment]
@zcorpan after your review I made some more fixes. The order of some files now changes a lot. Is that OK?

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
Yep!

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
