### PR TITLE
HTML: simplify self.navigator test and correct User-Agent subtest

### PR DESCRIPTION
**Pull request by annevk**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5620)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5620/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223948351)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223948356)

# Firefox (nightly channel) #
Testing web-platform-tests at revision a2727362ec6eb1bfb26a9cd1559e56b1ea3a4a15
Using browser at version BuildID 20170420100256; SourceStamp 27311156637f9b5d4504373967e01c4241902ae7
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5620/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.worker.html">/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.worker.html</a></summary>


|      Subtest      | Results | Messages |
|-------------------|---------|----------|
|                   | OK      |          |
| `appCodeName`     | PASS    | `{}`     |
| `appName`         | PASS    | `{}`     |
| `appVersion`      | PASS    | `{}`     |
| `platform`        | PASS    | `{}`     |
| `product`         | PASS    | `{}`     |
| `productSub`      | PASS    | `{}`     |
| `userAgent type`  | PASS    | `{}`     |
| `userAgent value` | PASS    | `{}`     |
| `vendor`          | PASS    | `{}`     |
| `vendorSub`       | PASS    | `{}`     |
| `taintEnabled`    | PASS    | `{}`     |
| `oscpu`           | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5620/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.html">/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.html</a></summary>


|      Subtest      | Results | Messages |
|-------------------|---------|----------|
|                   | OK      |          |
| `appCodeName`     | PASS    |          |
| `appName`         | PASS    |          |
| `appVersion`      | PASS    |          |
| `platform`        | PASS    |          |
| `product`         | PASS    |          |
| `productSub`      | PASS    |          |
| `userAgent type`  | PASS    |          |
| `userAgent value` | PASS    |          |
| `vendor`          | PASS    |          |
| `vendorSub`       | PASS    |          |
| `taintEnabled`    | PASS    |          |
| `oscpu`           | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223948358)

# Chrome (unstable channel) #
Testing web-platform-tests at revision a2727362ec6eb1bfb26a9cd1559e56b1ea3a4a15
Using browser at version 59.0.3071.9 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5620/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.worker.html">/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.worker.html</a></summary>


|      Subtest      | Results | Messages |
|-------------------|---------|----------|
|                   | OK      |          |
| `appCodeName`     | PASS    | `{}`     |
| `appName`         | PASS    | `{}`     |
| `appVersion`      | PASS    | `{}`     |
| `platform`        | PASS    | `{}`     |
| `product`         | PASS    | `{}`     |
| `productSub`      | PASS    | `{}`     |
| `userAgent type`  | PASS    | `{}`     |
| `userAgent value` | PASS    | `{}`     |
| `vendor`          | PASS    | `{}`     |
| `vendorSub`       | PASS    | `{}`     |
| `taintEnabled`    | PASS    | `{}`     |
| `oscpu`           | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5620/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.html">/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.html</a></summary>


|      Subtest      | Results | Messages |
|-------------------|---------|----------|
|                   | OK      |          |
| `appCodeName`     | PASS    |          |
| `appName`         | PASS    |          |
| `appVersion`      | PASS    |          |
| `platform`        | PASS    |          |
| `product`         | PASS    |          |
| `productSub`      | PASS    |          |
| `userAgent type`  | PASS    |          |
| `userAgent value` | PASS    |          |
| `vendor`          | PASS    |          |
| `vendorSub`       | PASS    |          |
| `taintEnabled`    | PASS    |          |
| `oscpu`           | PASS    |          |

</details>
</details>

**Review by foolip — APPROVED** [review]

**Pull request merged**
