### PR TITLE
Make Mozilla's sync-tests.sh work with git. 

### PR DESCRIPTION
**Pull request by emilio**
I needed this for #11714.

### CODE REVIEW

**Review by dbaron — APPROVED** [review]
I tend to put the `then` on its own line rather than sticking a semicolon before it and putting it on the same line as the `if`, but I'm probably a bit unusually in preferring that style for shell scripts...

Otherwise looks great.

**Comment by dbaron** [comment]
Also not sure why this would trigger this lint failure (unless maybe your branchpoint is old?):
```
ERROR:lint:css/vendor-imports/mozilla: Directory is missing META.yml file. (MISSING-META-YML)
```

**Comment by emilio** [comment]
Looks like I'm on top of master, which has 93dceabca4f79ced2a35fa480f78d30d4123ffaa. @zcorpan do you know why?

**Comment by emilio** [comment]
That is, why CI is failing with this patch, and what should be done for it not to complain? :)

**Comment by zcorpan** [comment]
Rebase, something was wrong with the linter.

**Pull request merged**
