### PR TITLE
Update of PR6424

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6449)

### CODE REVIEW

**Review by mikewest — APPROVED** [review]
Thank you for digging into this, @jgraham. Let's see what the bots say, but this LGTM. :)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249617604)

# Firefox (nightly) #
Testing web-platform-tests at revision addf1f7eae6c4b9d329f77c3ea52721d47619c7b
Using browser at version BuildID 20170702100334; SourceStamp 4d3de12dcdc539f14fcb06539da39fa7176c8955
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249617605)

# Sauce (safari) #
Testing web-platform-tests at revision addf1f7eae6c4b9d329f77c3ea52721d47619c7b
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249617611)

# Chrome (unstable) #
Testing web-platform-tests at revision addf1f7eae6c4b9d329f77c3ea52721d47619c7b
Using browser at version 61.0.3141.7 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249617612)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision addf1f7eae6c4b9d329f77c3ea52721d47619c7b
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by jgraham** [comment]
The tests seemed to time out in Fx, and other browsers aren't working due to #6450, so it's hard to be sure this is right, but I can't see anything in the log to suggest it's still failing (although one test does look broken).

**Comment by mikewest** [comment]
@andypaicu: Mind taking a look?

**Comment by gsnedders** [comment]
Updates #6424.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22779)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/328997025)

**Comment by andypaicu** [comment]
This has been stuck behind https://github.com/w3c/web-platform-tests/issues/7638 but now it can be merged. And it only took me 6 months to get it sorted :).

**Comment by gsnedders** [comment]
This seems to have added a `third_party/WebKit/LayoutTests/external/wpt/content-security-policy/support/passs.png`, which seems like something went wrong somewhere. I know obviously the commit history has been rewritten, so it might not be the exporter, but can someone (@andypaicu, @Hexcles) fix this and check what happened?

**Comment by andypaicu** [comment]
@gsnedders Argh... yeah that file is supposed to be part of a later commit in the pipeline of commits that is blocked on this, a commit that adds tests that use the file.

**Comment by andypaicu** [comment]
Oh and it also copied the chrome folder structure.... I don't know how that happened

**Pull request merged**
