### PR TITLE
[taskcluster] Disable Chrome sandboxing in Docker

### PR DESCRIPTION
**Pull request by Hexcles**
According to the [theory](https://github.com/web-platform-tests/wpt/issues/20133#issuecomment-550521698), we used to be able to run Chrome without privileged mode because user namespace was not supported in the old github-worker. Let's try disabling it and see if it works on the new worker. If it does, we are not really losing any security compared with before.

### CODE REVIEW

**Comment by Hexcles** [comment]
Hmm, `--disable-namespace-sandbox` does not do what I thought it did. Besides, it's an undocumented flag. Let me try `--no-sandbox`.

**Comment by Hexcles** [comment]
Alright, it works.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Leaving merging to you Robert!

**Comment by Hexcles** [comment]
Note: I'm not sure if we did not have sandboxing on the old Taskcluster instance.

Regardless, I'm checking with Chrome Security to see if `--no-sandbox` would cause any web-observable change. If not, this is the preferred fix.

**Comment by Hexcles** [comment]
This doesn't work. `run_tc.py` passses `--binary-arg=--no-sandbox` to `ci/*.sh`, some of which don't further pass that arg along while the others don't understand that arg (e.g. tox).

**Pull request closed without merging**
