### PR TITLE
[css-pseudo] Added a basic ::target-text highlight test

### PR DESCRIPTION
**Pull request by TalbotG**
/css/css-pseudo/highlight-target-text-001.html
/css/css-pseudo/reference/highlight-target-text-001-ref.html

On my website:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/highlight-target-text-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/highlight-target-text-001-ref.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
::target-text highlights text directly targetted (e.g. via https://wicg.github.io/scroll-to-text-fragment/ ), not elements that are targetted. So this test is incorrect, but probably also it means the spec needs clarification. :)

It does make me wonder if https://wicg.github.io/scroll-to-text-fragment/ is standards-track yet though.

**Comment by TalbotG** [comment]
The test could be modified and adapted to check the `:target` pseudo-class, like this:

http://www.gtalbot.org/BrowserBugsSection/Selectors4/target-pseudo-class-001.html

I most likely assumed :target pseudo-class was ::target-text pseudo-element . 

> ::target-text highlights text directly targetted (...). So this test is incorrect

Then I am not sure how to test ::target-text right now. 
The user has to do a "Find text" within the test webpage, right?

**Comment by fantasai** [comment]
No, I think it's about things like this: https://wicg.github.io/scroll-to-text-fragment/

**Comment by TalbotG** [comment]
I am closing this PR because there are now approx. 20 `::target-text` highlight tests and about a dozen tests doing basic testing in:

http://wpt.live/css/css-pseudo/

**Pull request closed without merging**
