### PR TITLE
[Azure Pipelines] Enable experimental Server Timing in Safari TP

### PR DESCRIPTION
**Pull request by foolip**
Like https://github.com/web-platform-tests/results-collection/pull/621.

### CODE REVIEW

**Comment by foolip** [comment]
@cvazac can you review? I've only enabled it for Safari Technology Preview to match what we do for other browsers &ndash; experimental features enabled in experimental/preview channels only.

**Comment by foolip** [comment]
I've started https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=11891 to see what the difference in results will be.

**Comment by foolip** [comment]
Results are in, but the Server Timing tests seem unaffected:
https://wpt.fyi/results/server-timing?diff&filter=ADC&run_id=5471855615934464&run_id=4825746438619136

@cvazac have you confirmed this setting to work locally?

**Comment by foolip** [comment]
I might have found a fix, trying https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=12008 again.

**Comment by foolip** [comment]
Sweet, that worked!

https://wpt.fyi/results/server-timing?diff&filter=ADC&run_id=5471855615934464&run_id=5475323030274048

Also no regression in infrastructure/ tests, so I didn't mess that up either.

**Comment by foolip** [comment]
@jgraham the failure to run lint in https://tools.taskcluster.net/groups/Kh4_OybISQuKNPB4YITH1A/tasks/U2P2bZSHQMaKzY6yazHi9g/runs/0/logs/public%2Flogs%2Flive.log is a bit mysterious to me. Have you seen this before?

I'm going to squash and rebase this branch and see what happens, since I don't see the same failure on all other PRs.

**Comment by foolip** [comment]
Now it's fine. @gsnedders can you review?

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
