### PR TITLE
Use any.js approach to simplify testing

### PR DESCRIPTION
**Pull request by plehegar**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5199)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5199/)

**Comment by annevk** [comment]
FYI: you can use `self.performance`.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213933101)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 74df46c1174f450aab3b3a75d4ff7e7f77886770
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213933102)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 74df46c1174f450aab3b3a75d4ff7e7f77886770
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by plehegar** [comment]
@annevk thanks! updated.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213981215)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1579625f6f753b4af018eb69d5940a90d6207c4a
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213981216)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1579625f6f753b4af018eb69d5940a90d6207c4a
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213982671)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1579625f6f753b4af018eb69d5940a90d6207c4a
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213982672)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1579625f6f753b4af018eb69d5940a90d6207c4a
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by igrigorik** [comment]
LGTM

**Pull request merged**
