### PR TITLE
Add tests for image.onerror

### LINKED ISSUE #3688: Add a test for <img src=404-that's-really-an-image>
See #3675

### PR DESCRIPTION
**Pull request by xiuqijix**
Fix #3688, @Ms2ger, PTAL.

### CODE REVIEW

**Comment by kaixinjxq** [comment]
This PR is blocked on the required "Travis CI - Pull Request" check after #14499. In order to trigger it, I will close and reopen this PR.

**Review by jdm — APPROVED** [review]

**Comment by kaixinjxq** [comment]
@jdm, CI checks are all pass, it's ready for merge. :)

**Comment by jdm** [comment]
@kaixinjxq Actually, I looked closer at #3688 and this doesn't actually address it. The two tests for 404 and 404.png are redundant as far as I can tell since it doesn't matter if the URL contains an image extension or not. https://github.com/web-platform-tests/wpt/pull/3675#issuecomment-245859505 indicated that if the sever provides a 404 response that actually contains image data, the image element should render it and fire the load event instead.

**Comment by kaixinjxq** [comment]
@jdm, many thanks for your review! I just submit a new commit to address your comments, PTAL.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
