### PR TITLE
Added active-selection-041.html and active-selection-043.html

### PR DESCRIPTION
**Pull request by TalbotG**
active-selection-041.html

active-selection-043.html

reference/active-selection-041-ref.html

This is a followup of 
https://github.com/web-platform-tests/wpt/pull/20931#issuecomment-650434204
and of comments made in
https://github.com/web-platform-tests/wpt/pull/20028
where @fantasai wrote
{
active-selection-041

So... the problem wth this test is that we don't actually know the exact color that the UA will use. It could be an 0.5 wash, but it doesn't have to be. We can make what you have as a MAY test, and it will be correct. I would use a blue highlight, though, to make the color purple. This will be more clearly not red than the warm brown that results from mixing the green and red.

You should also add another test for what happens if the highlight has 'color' but not 'background-color'.

Now, we want to also write a test for the full SHOULD, we will need to take a different approach.

Here is my suggestion: write two tests using your square image as the base, as follows:

 -  For the first test, mask over the image with an inline element that has 4px top+bottom padding and a background. (If the UA highlights only this area, as if it was a regular inline element, it's insufficient. I think this would be the most likely error.) Use a "mismatch" reference against a version of the test without the highlight. This ensures that the UA has highlighted the image somehow, including outside the masked area.

 -  For the second test, mask over the entire square image. Use a "match" reference against a version of the test without the highlight. This ensures the highlight doesn't leak outside the image area.

Think about this, and let me know if you think it is a good approach or if you have some other ideas. It's a tricky thing to test because we don't know what will be the exact rendering. :)
}

### CODE REVIEW

**Comment by TalbotG** [comment]
To facilitate review, these tests are on my website (with slightly different filenames: "-new" is added):

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-041-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/active-selection-041-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-043-new.html

http://www.gtalbot.org/BrowserBugsSection/reference/ref-filled-green-100px-square.xht

**Comment by fantasai** [comment]
Chrome uses a different transparency for its color wash, so its rendering doesn't match -041. I think that's acceptable, and we shouldn't add a test that it fails. So I don't think we should add -041.

-043 is incorrect because the spec says “This wash should be of the specified background-color if that is not transparent, else of the specified color; however the UA may adjust the alpha channel.”

**Review by fantasai — CHANGES_REQUESTED** [review]
(See suggestions / comments above.)

**Comment by TalbotG** [comment]
Elika,
On my website, the correspondent 3 files in 1bb592d commit are:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-041-newest.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/active-selection-041-notref.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-043-newest.html

**Review by fantasai — APPROVED** [review]
Looks great

**Pull request merged**
