### PR TITLE
add webdriver element_click tests

### PR DESCRIPTION
**Pull request by alchiem**

### CODE REVIEW

**Comment by alchiem** [comment]
The old pr with comments:
https://github.com/w3c/web-platform-tests/pull/8379

**Review by andreastt — APPROVED** [review]
This basically looks OK to me now. I’m sorry for how long it has taken to get to this point, but I’m satisfied with the end result.

My only point of worry at this point is that the stability/infrastructure tests were not run on this PR. @jgraham?

**Comment by alchiem** [comment]
Hey @andreastt, thank you for your time, patience, and guidance. This has been a great learning experience for me and I understand you been really busy with getting webdriver into recommendation.

**Comment by andreastt** [comment]
Sorry, I missed the green checkmark above. The tests did run and look fine: https://travis-ci.org/web-platform-tests/wpt/builds/390608701?utm_source=github_status&utm_medium=notification

**Comment by andreastt** [comment]
@alchiem Thanks for your patch (-:

**Comment by alchiem** [comment]
Ok perfect. Thanks again for your help and patience.

**Pull request merged**
