### PR TITLE
Workaround marionette 3.1.0 switch_to_window bug in Firefox 79

### LINKED ISSUE #24924: Firefox stable daily runs are failing with NoSuchWindowException
See https://github.com/web-platform-tests/wpt/commits/epochs/daily

Example run: https://community-tc.services.mozilla.com/tasks/groups/X50KGIpZSMq0Ag7vQhbM6A

Example task log: https://community-tc.services.mozilla.com/tasks/T13biD2PSOWC73kPlvymBw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FT13biD2PSOWC73kPlvymBw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```
 0:13.61 SUITE_START: web-platform-test - running 856 tests
 0:47.36 INFO Running testharness tests
 0:47.39 INFO Setting up ssl
 0:47.44 certutil Full command: /usr/bin/certutil -N -d /tmp/tmprYMnHs.mozrunner -f /tmp/tmprYMnHs.mozrunner/.crtdbpw
certutil 
 0:47.48 certutil 
 0:47.50 certutil 
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

web-platform-tests                                           CT,, 

 0:47.52 INFO Application command: /home/test/build/firefox/firefox --marionette about:blank -profile /tmp/tmpogOO9n
 0:47.53 INFO Application command: /home/test/build/firefox/firefox --marionette about:blank -profile /tmp/tmprbo6jv
 0:47.54 INFO Starting runner
Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value
 0:49.75 pid:1275 Full command: /home/test/build/firefox/firefox --marionette about:blank -profile /tmp/tmpogOO9n
pid:1275 console.error: SearchCache: "_readCacheFile: Error reading cache file:" (new Error("", "(unknown module)"))
 0:51.05 pid:1275 1596676421960	Marionette	INFO	Listening on port 47423
 0:51.40 TEST_START: /WebCryptoAPI/derive_bits_keys/ecdh_bits.https.any.worker.html
 0:51.42 ERROR Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 126, in run_test
    return self.executor.run_test(test)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 285, in run_test
    self.on_environment_change(test.environment)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 776, in on_environment_change
    self.protocol.testharness.load_runner(new_environment["protocol"])
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 140, in load_runner
    self._close_windows()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 180, in _close_windows
    self.marionette.switch_to_window(runner_handle)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/marionette.py", line 1360, in switch_to_window
    self._send_message("WebDriver:SwitchToWindow", {"handle": handle, "focus": focus})
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/marionette.py", line 602, in _send_message
    self._handle_error(err)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/marionette.py", line 622, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
NoSuchWindowException: Unable to locate window: undefined
stacktrace:
	WebDriverError@chrome://marionette/content/error.js:175:5
	NoSuchWindowError@chrome://marionette/content/error.js:409:5
	GeckoDriver.prototype.switchToWindow@chrome://marionette/content/driver.js:1602:11
	despatch@chrome://marionette/content/server.js:305:40
	execute@chrome://marionette/content/server.js:275:16
	onPacket/<@chrome://marionette/content/server.js:248:20
	onPacket@chrome://marionette/content/server.js:249:9
	_onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20
```

They've been failing since July 23rd (we didn't notice for a while since wpt.fyi was ingesting the partially complete results; I found the start point by looking where the # of results fell from ~34k to ~17k).

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes https://github.com/web-platform-tests/wpt/issues/24924

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I intend to move this to a method on the protocol, and the documentation needs some work.

It's not clear to me still what exactly we're working around here; https://bugzilla.mozilla.org/show_bug.cgi?id=1588424 appears to state in https://bugzilla.mozilla.org/show_bug.cgi?id=1588424#c1 that geckodriver should support this already, and https://bugzilla.mozilla.org/show_bug.cgi?id=1588424#c7 implies we should just be on geckodriver 0.27.0 and maybe this wouldn't be a problem then?

**Comment by jgraham** [comment]
geckodriver isn't involved here, we're using the underlying marionette connection directly. It's just that marionette is very close to WebDriver in a way that e.g. CDP isn't.

**Review by jgraham — APPROVED** [review]
Thanks for doing this!

**Review by Hexcles — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
> geckodriver isn't involved here, we're using the underlying marionette connection directly. It's just that marionette is very close to WebDriver in a way that e.g. CDP isn't.

Ah, that makes sense. Thanks.

**Comment by stephenmcgruer** [comment]
https://community-tc.services.mozilla.com/tasks/groups/cOUzpDt-RS-n9DyiMCIYTQ is the stable trigger run

**Comment by stephenmcgruer** [comment]
Stable run succeeded, and tests all are green except for an azure pipelines infra error. Merging.

**Pull request merged**
