### PR TITLE
[csp] Wait for more tests to be defined

### PR DESCRIPTION
**Pull request by foolip**
Like https://github.com/web-platform-tests/wpt/pull/15631

### CODE REVIEW

**Comment by foolip** [comment]
This is to fix a problem with https://wpt.fyi/results/content-security-policy/style-src/inline-style-allowed-while-cloning-objects.sub.html?sha=2e21093960&label=master&label=experimental that @jugglinmike found while looking for "late tests", tests registered after testharness.js considers the page's tests complete.

I guess the reason for the difference between Chrome and Firefox is the timing of the securitypolicyviolation event.

**Comment by foolip** [comment]
It worked! https://wpt.fyi/results/content-security-policy/style-src/inline-style-allowed-while-cloning-objects.sub.html?diff&filter=ADC&run_id=260820004&run_id=256890004

**Comment by jugglinmike** [comment]
@foolip gh-15631 includes a fix for this test along with others that suffer from the same problem.

**Review by hillbrad — APPROVED** [review]
LGTM.

**Comment by foolip** [comment]
@jugglinmike, oh, didn't notice that PR was still open :(

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt/pull/15631.

**Pull request closed without merging**
