### PR TITLE
Add idlharness test for CSS Layout API

### PR DESCRIPTION
**Pull request by lukebjerring**
Builds on https://github.com/web-platform-tests/wpt/pull/12912.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-02 21:36:26
Finished: 2018-03-02 21:45:48


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25169)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/348381607)

**Comment by lukebjerring** [comment]
Note that test is currently broken by `sequence` instead of iterable (which I replaced locally to work out all the correct deps).

**Comment by lukebjerring** [comment]
Related: https://github.com/w3c/css-houdini-drafts/issues/758

**Comment by foolip** [comment]
I've updated the test to use `idl_test`, but it's still entirely broken by the use of `sequence<T>`. @bfgeek @tabatkins, can you take a look at https://github.com/w3c/css-houdini-drafts/issues/758 to unblock this PR? Thanks!

**Comment by foolip** [comment]
Sent a PR for it: https://github.com/w3c/css-houdini-drafts/pull/786

**Review by foolip — COMMENTED** [review]
Because of `[Exposed=LayoutWorklet]` this test isn't going to do much. We'll presumably have to teach idlharness.js about LayoutWorklet, and create a LayoutWorklet here for the tests. Didn't notice the same problem in https://github.com/web-platform-tests/wpt/pull/9773/, but added a note to https://github.com/web-platform-tests/wpt/projects/1 about this.

**Pull request closed without merging**
