### PR TITLE
EventSource: IDNA origin should be in ASCII

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/2568.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232900407)

# Firefox (nightly) #
Testing web-platform-tests at revision 6da2eed6ce0d7171fa933b09e990f8c091771ad1
Using browser at version BuildID 20170516100213; SourceStamp 3e166b6838931b3933ca274331f9e0e115af5cc0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5946/eventsource/eventsource-cross-origin.htm">/eventsource/eventsource-cross-origin.htm</a></summary>


|                                 Subtest                                  | Results |                                                       Messages                                                       |
|--------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
|                                                                          | OK      |                                                                                                                      |
| `EventSource: cross-origin basic use`                                    | FAIL    | `assert_equals: expected "http://xn--lve-6lad.web-platform.test:8000" but got "http://Ã©lÃ¨ve.web-platform.test:8000"` |
| `EventSource: cross-origin redirect use`                                 | FAIL    | `assert_equals: expected "http://xn--lve-6lad.web-platform.test:8000" but got "http://Ã©lÃ¨ve.web-platform.test:8000"` |
| `EventSource: cross-origin redirect use recon`                           | FAIL    | `assert_equals: expected "http://xn--lve-6lad.web-platform.test:8000" but got "http://Ã©lÃ¨ve.web-platform.test:8000"` |
| `EventSource: cross-origin allow-origin: http://example.org should fail` | PASS    |                                                                                                                      |
| `EventSource: cross-origin allow-origin:'' should fail`                  | PASS    |                                                                                                                      |
| `EventSource: cross-origin No allow-origin should fail`                  | PASS    |                                                                                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232900408)

# Sauce (safari) #
Testing web-platform-tests at revision 6da2eed6ce0d7171fa933b09e990f8c091771ad1
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5946/eventsource/eventsource-cross-origin.htm">/eventsource/eventsource-cross-origin.htm</a></summary>


|                                 Subtest                                  | Results |     Messages     |
|--------------------------------------------------------------------------|---------|------------------|
|                                                                          | TIMEOUT |                  |
| `EventSource: cross-origin basic use`                                    | TIMEOUT | `Test timed out` |
| `EventSource: cross-origin redirect use`                                 | TIMEOUT | `Test timed out` |
| `EventSource: cross-origin redirect use recon`                           | TIMEOUT | `Test timed out` |
| `EventSource: cross-origin allow-origin: http://example.org should fail` | PASS    |                  |
| `EventSource: cross-origin allow-origin:'' should fail`                  | PASS    |                  |
| `EventSource: cross-origin No allow-origin should fail`                  | PASS    |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232900409)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 6da2eed6ce0d7171fa933b09e990f8c091771ad1
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5946/eventsource/eventsource-cross-origin.htm">/eventsource/eventsource-cross-origin.htm</a></summary>


|                                 Subtest                                  | Results |           Messages           |
|--------------------------------------------------------------------------|---------|------------------------------|
|                                                                          | OK      |                              |
| `EventSource: cross-origin basic use`                                    | FAIL    | `'EventSource' is undefined` |
| `EventSource: cross-origin redirect use`                                 | FAIL    | `'EventSource' is undefined` |
| `EventSource: cross-origin redirect use recon`                           | FAIL    | `'EventSource' is undefined` |
| `EventSource: cross-origin allow-origin: http://example.org should fail` | FAIL    | `'EventSource' is undefined` |
| `EventSource: cross-origin allow-origin:'' should fail`                  | FAIL    | `'EventSource' is undefined` |
| `EventSource: cross-origin No allow-origin should fail`                  | FAIL    | `'EventSource' is undefined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232900415)

# Chrome (unstable) #
Testing web-platform-tests at revision 6da2eed6ce0d7171fa933b09e990f8c091771ad1

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
