### PR TITLE
[css-display-3] Add tests for display: contents state changes that affect text children.

### PR DESCRIPTION
**Pull request by emilio**
Reviewed upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1351339

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229931238)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 56bb43e047f92fb54572ed196f70adc0de962b81
Using browser at version BuildID 20170507100239; SourceStamp 37a5b7f6f101df2eb292b1b6baaf1540c9920e20
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5848/css/css-display-3/display-contents-state-change-001.html">/css/css-display-3/display-contents-state-change-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229931244)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 56bb43e047f92fb54572ed196f70adc0de962b81

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230763600)

# Firefox (nightly) #
Testing web-platform-tests at revision 2d2ab0e056d1822c1c80b426e06dd64542e46c96
Using browser at version BuildID 20170509100208; SourceStamp b21b974d60d3075ae24f6fb1bae75d0f122f28fc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5848/css/css-display-3/display-contents-state-change-001.html">/css/css-display-3/display-contents-state-change-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230763606)

# Chrome (unstable) #
Testing web-platform-tests at revision 2d2ab0e056d1822c1c80b426e06dd64542e46c96
Using browser at version 60.0.3088.3 dev
Starting 10 test iterations

**Comment by mrego** [comment]
Ok, thanks.

**Pull request merged**
