### PR TITLE
Add Protected Audiences real time reporting routes to RoutesBuilder

### PR DESCRIPTION
**Pull request by qingxinwu**
Protected Audience's Real Time Reporting (RTR) API supports sending auction monitoring data to the buyer and seller as quickly as possible (e.g. < 5 mins). Adding RTR routes as a well-known route to the RoutesBuilder so that the WPT server can receive and return RTR reports.

Explainer: https://github.com/WICG/turtledove/blob/main/PA_real_time_monitoring.md#sending-reports-after-an-auction

### CODE REVIEW

**Comment by qingxinwu** [comment]
friendly ping :)

**Comment by qingxinwu** [comment]
another ping :)

**Comment by qingxinwu** [comment]
@DanielRyanSmith @foolip @jgraham May I get some updates on this? Thanks!

**Comment by foolip** [comment]
@qingxinwu I'm afraid I'm on parental leave right now, so I'll have to defer to others on this.

**Review by DanielRyanSmith — APPROVED** [review]

**Comment by qingxinwu** [comment]
@DanielRyanSmith Thanks a lot! Can someone with write access help merge this if it's ready?

**Pull request merged**
