### PR TITLE
Add @font-face rules to load TrueType and OpenType test fonts.

### PR DESCRIPTION
**Pull request by fred-wang**
This commit removes the support/FontsToInstall directory and moves the
TrueType and OpenType test fonts directly into the support/ directory.
It attaches a support/test-fonts.css stylesheet to test pages so that
these test fonts are loaded via @font-face rules. Finally, the
instructions to install test fonts, the CSS rule for the installation
note as well as the "flags" meta tags are removed.

See discussions in issue #8440 ; note that these changes have essentially be done automatically using sed but be sure to check the following files:

     css/WOFF2/available-001.xht                          |   2 --
     .../{FontsToInstall => }/SFNT-CFF-Fallback.otf       | Bin
     .../{FontsToInstall => }/SFNT-CFF-Reference.otf      | Bin
     .../{FontsToInstall => }/SFNT-TTF-Fallback.ttf       | Bin
     .../{FontsToInstall => }/SFNT-TTF-Reference.ttf      | Bin
     css/WOFF2/support/available-001a.xht                 |   2 +-
     css/WOFF2/support/available-001b.xht                 |   2 +-
     css/WOFF2/support/index.css                          |  11 -----------
     css/WOFF2/support/test-fonts.css                     |  19 +++++++++++++++++++
     css/WOFF2/testcaseindex.xht                          |   1 -

See also issue #8482 for the available test.

### CODE REVIEW

**Comment by fred-wang** [comment]
cc'ing @litherum @gsnedders @jfkthame

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-29 09:46:05
Finished: 2017-11-29 09:57:39


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21194)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/308882163)

**Comment by gsnedders** [comment]
Bah, none of these actually have `<link rel=match href=foo-ref.xht>`, I'll fix that in a new commit in a second.

**Comment by gsnedders** [comment]
OK, after those extra changes this LGTM.

**Comment by fred-wang** [comment]
@khaledhosny, @svgeesus, @rsheeter Can one of you please review this PR?

**Comment by gsnedders** [comment]
reviewers: ping!

**Review by svgeesus — APPROVED** [review]
Yes, this looks correct.

**Comment by fred-wang** [comment]
@gsnedders @svgeesus Thanks for your help on this!

**Pull request merged**
