### PR TITLE
[Azure Pipelines] Use more verbose TBPL logging for full runs

### PR DESCRIPTION
**Pull request by foolip**
This is to help diagnose problems if they occur, such as this failure
to run all of the tests:
https://github.com/web-platform-tests/wpt/pull/17219#issuecomment-501272482

### CODE REVIEW

**Comment by foolip** [comment]
I will manually trigger full runs from the branch to see if it works.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=19588

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
Hitting the same issue as we hit in #17219, but at least now we can see we're asserting when trying to restart.

**Comment by foolip** [comment]
@gsnedders oh cool, can you tell what the root cause might be?

**Comment by gsnedders** [comment]
"something in the state machine is wrong" 🙂

**Comment by foolip** [comment]
I didn't base this on an epochs branch, but here are the runs compared to the previous one:
https://wpt.fyi/results/?diff&filter=ADC&run_id=233280005&run_id=233300006
https://wpt.fyi/results/?diff&filter=ADC&run_id=252810011&run_id=239070008
https://wpt.fyi/results/?diff&filter=ADC&run_id=266670008&run_id=248800004

There's some noise in the diffs, but small numbers, this didn't break the world. It's possible the much more verbose logs will cause some trouble down the line, but hopefully Azure Pipelines fails in some nice way and doesn't just fall over without providing clues.

**Comment by gsnedders** [comment]
@foolip Hah, it's https://github.com/web-platform-tests/wpt/issues/13276. I presume we didn't think there were missing results before?

**Pull request merged**
