### PR TITLE
Rename /common/utils.js's token() to make_token()

### PR DESCRIPTION
**Pull request by zcorpan**
Rationale: it's annoying that the function name is `token()` because it means I can't use `const token = token();`

```
Uncaught ReferenceError: Cannot access 'token' before initialization
```

This renames to `make_token()` so it's consistent with the other utility `make_absolute_url()`.

Method: 
```
git grep -l "token()" | xargs sed -i '' 's/token()/make_token()/g'
```
(with macOS `sed`)

I looked at each instance to see if it was using some other `token()` and found 2 `.py` files that shouldn't be changed and I reverted them.

### CODE REVIEW

**Comment by annevk** [comment]
Why would the variable name be token though? At least in my experience it makes more sense for that to be key/id/etc. Not really convinced this is worth it.

**Review by jgraham — DISMISSED** [review]
Did you cross check for users of utils.js that also include the string `token` but not `token()`? I guess there could also be people doing things like `opener.token()` which perhaps is less likely but possible.

**Comment by zcorpan** [comment]
Same reason as using `?token=` for it in the URL, which various tests already do. For clarity and consistency I wanted to use the same name everywhere for the same thing, but I can't use `token`. I could use `uuid` or something instead, though.

I figured the rename would be easy, which it was, but the CI checks timed out which makes this a bit difficult to verify results.

**Comment by zcorpan** [comment]
@jgraham 

```
git grep -l "/common/utils.js" | xargs grep -l token | xargs grep -L 'token()'
```
gives nothing. `opener.token()` variants should be covered.

**Comment by zcorpan** [comment]
After thinking about this some more today, I agree it's not worth it to change this, in particular since CI times out here. Let's close. Thanks for pushing back :)

**Pull request closed without merging**
