### PR TITLE
Add functional tests for LinearAccelerationSensor

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261679217)

# Firefox (nightly) #
Testing web-platform-tests at revision 58f6e837c260a1cce4d0d0428e7467a786436ffb
Using binary /home/travis/build/w3c/web-platform-tests/_venv/firefox/firefox
Starting tests
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6769/accelerometer/Accelerometer.https.html">/accelerometer/Accelerometer.https.html</a></summary>


|       Subtest        | Results |                    Messages                    |
|----------------------|---------|------------------------------------------------|
|                      | OK      |                                                |
| `Accelerometer Test` | FAIL    | `ReferenceError: Accelerometer is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6769/accelerometer/Accelerometer_insecure_context.html">/accelerometer/Accelerometer_insecure_context.html</a></summary>


|                Subtest                 | Results |                    Messages                    |
|----------------------------------------|---------|------------------------------------------------|
|                                        | OK      |                                                |
| `Accelerometer Test: insecure context` | FAIL    | `ReferenceError: Accelerometer is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261679218)

# Sauce (safari) #
Testing web-platform-tests at revision 58f6e837c260a1cce4d0d0428e7467a786436ffb
Using binary None
Starting tests
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6769/accelerometer/Accelerometer.https.html">/accelerometer/Accelerometer.https.html</a></summary>


|       Subtest        | Results |                       Messages                       |
|----------------------|---------|------------------------------------------------------|
|                      | OK      |                                                      |
| `Accelerometer Test` | FAIL    | `ReferenceError: Can't find variable: Accelerometer` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6769/accelerometer/Accelerometer_insecure_context.html">/accelerometer/Accelerometer_insecure_context.html</a></summary>


|                Subtest                 | Results |                       Messages                       |
|----------------------------------------|---------|------------------------------------------------------|
|                                        | OK      |                                                      |
| `Accelerometer Test: insecure context` | FAIL    | `ReferenceError: Can't find variable: Accelerometer` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261679227)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/261679228)

# Sauce (MicrosoftEdge) #

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by Honry** [comment]
@alexshalamov, @pozdnyakov, friendly ping. :-)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19666)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/289790717)

**Review by pozdnyakov — APPROVED** [review]
lgtm

**Comment by Honry** [comment]
@pozdnyakov, thanks for your review.

**Pull request merged**
