### PR TITLE
Add a CSS test for radial gradients.

### PR DESCRIPTION
**Pull request by pyfisch**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5645)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224765279)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224765281)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 7a6f6b476214f3bcb345539d6c744f59bb186afa
Using browser at version BuildID 20170422100218; SourceStamp 7d85b081bfabe91dbf18a421f1eee2a32f335823
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5645/css/css-backgrounds-3/gradients-with-border.htm">/css/css-backgrounds-3/gradients-with-border.htm</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224765287)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 7a6f6b476214f3bcb345539d6c744f59bb186afa
Using browser at version 59.0.3071.15 dev
Starting 10 test iterations

**Comment by jdm** [comment]
@pyfisch Can you reproduce the failure in Chrome locally?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5645/)

**Pull request closed without merging**
