### PR TITLE
Test box-shadow serialization

### PR DESCRIPTION
**Pull request by csnardi**
Following https://github.com/w3c/csswg-drafts/issues/2305, the canonical serialization for box-shadow was changed from `inset? && <length>{2,4} && <color>?` to `<color>? && <length>{2,4} && inset?`. Convert an existing box-shadow text into a testharness.js test in order to test serialization as well.

I added `parsing-testcommon.js` as a copy of https://github.com/w3c/web-platform-tests/blob/master/css/css-transforms/parsing/resources/parsing-testcommon.js (this should probably be moved into a css/resources directory), and also renamed the file as it seems the testharness reporting does not play nicely with XHTML (it had no styling).

### CODE REVIEW

**Comment by csnardi** [comment]
@fantasai Since you made the edits and originally wrote this test, could you take a look?

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24348)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/341586970)

**Comment by fantasai** [comment]
I defer to @gsnedders on this one.

**Comment by gsnedders** [comment]
> also renamed the file as it seems the testharness reporting does not play nicely with XHTML (it had no styling)

Hmm, that's odd; it should definitely work. http://w3c-test.org/css/cssom-view/media-query-list-interface.xht for example looks fine here? And having copied and renamed your file it works too once I add in the optional tags?

Otherwise this LGTM.

**Review by gsnedders — APPROVED** [review]

**Comment by csnardi** [comment]
@gsnedders Huh, I probably just messed up something then. Should I change this back to XHTML, or leave it as-is?

**Comment by gsnedders** [comment]
@csnardi No need; not sure why I didn't merge before?

**Pull request merged**
