### PR TITLE
Separate metadata_root and expectation_root

### PR DESCRIPTION
**Pull request by lukebjerring**
WIP for https://github.com/w3c/web-platform-tests/issues/7959

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7975)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-25 22:43:12
Finished: 2017-10-25 23:04:57





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19903)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/292872634)

**Comment by jgraham** [comment]
Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[tools/ci/check_stability.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7975#-KxNE7Byb-SnEtuJZSQD:-KxNE7BzuWknhnFBq4h5:bfd23d1) ([raw file](https://github.com/w3c/web-platform-tests/blob/f3f091fc1c7f426475f2f94cdeb0258096e15eeb/tools/ci/check_stability.py#L167)):*
> ```Python
>                         action="store",
>                         default=wpt_root,
>                         help="Directory that will contain MANIFEST.json")
> ```

I wonder if we should change so that there's an explicit argument that's the path to the manifest file, rather than a directory.

---

*[tools/ci/check_stability.py, line 168 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7975#-KxNEAV795wX3fF62ZVx:-KxNEAV795wX3fF62ZVy:b-prwidw) ([raw file](https://github.com/w3c/web-platform-tests/blob/f3f091fc1c7f426475f2f94cdeb0258096e15eeb/tools/ci/check_stability.py#L168)):*
> ```Python
>                         default=wpt_root,
>                         help="Directory that will contain MANIFEST.json")
>     parser.add_argument("--expectation_root",
> ```

Should be `expectation-root`.

---

*[tools/ci/check_stability.py, line 168 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7975#-KxNEl7B67fzlfx9Btk_:-KxNEl7CslWrUkyounJw:b-niyydi) ([raw file](https://github.com/w3c/web-platform-tests/blob/f3f091fc1c7f426475f2f94cdeb0258096e15eeb/tools/ci/check_stability.py#L168)):*
> ```Python
>                         default=wpt_root,
>                         help="Directory that will contain MANIFEST.json")
>     parser.add_argument("--expectation_root",
> ```

Need to add all these arguments to `tools/wptrunner/wptrunner/wptcommandline.py` in several places.

---

*[tools/wpt/run.py, line 66 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7975#-KxNDwKldaRC5gkbVSF_:-KxNDwKldaRC5gkbVSFa:b3ngy3j) ([raw file](https://github.com/w3c/web-platform-tests/blob/f3f091fc1c7f426475f2f94cdeb0258096e15eeb/tools/wpt/run.py#L66)):*
> ```Python
>     kwargs.set_if_none("tests_root", wpt_root)
>     kwargs.set_if_none("metadata_root", wpt_root)
>     kwargs.set_if_none("expectation_root", kwargs.get("metadata_root"))
> ```

I think this should go in `wptcommandline.py` in wptrunner, so it applies to all users of wptrunner, not just people going through the wpt frontend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7975)*

**Review by jgraham — CHANGES_REQUESTED** [review]
This looks like a reasonable start, but there are still a bunch of places where the metadata path is used for expectation metadata e.g in `testloader.py`.

**Comment by gsnedders** [comment]
this was done in #9676

**Pull request closed without merging**
