### PR TITLE
Remove dupe media/CanvasTest.ttf and unused fonts/CanvasTest.sfd

### PR DESCRIPTION
**Pull request by foolip**
Most tests that use either already use fonts/CanvasTest.ttf
No tests at all use fonts/CanvasTest.sdf

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5678)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5678/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225330338)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225330342)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 4257eafe51732b6033a1804c44c05ff383bf5e0b
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5678/preload/download-resources.html">/preload/download-resources.html</a></summary>


|                       Subtest                        | Results |                           Messages                           |
|------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                      | OK      |                                                              |
| `Makes sure that preloaded resources are downloaded` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5678/preload/onload-event.html">/preload/onload-event.html</a></summary>


|                            Subtest                             | Results |                           Messages                           |
|----------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                | OK      |                                                              |
| `Makes sure that preloaded resources trigger the onload event` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5678/preload/preload-with-type.html">/preload/preload-with-type.html</a></summary>


|                                       Subtest                                        | Results |                           Messages                           |
|--------------------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                                      | OK      |                                                              |
| `Makes sure that preloaded resources with a type attribute trigger the onload event` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5678/preload/single-download-preload.html">/preload/single-download-preload.html</a></summary>


|                                 Subtest                                  | Results |                           Messages                           |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                          | OK      |                                                              |
| `Makes sure that preloaded resources are not downloaded again when used` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225330351)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 4257eafe51732b6033a1804c44c05ff383bf5e0b

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
