### PR TITLE
Overcome antialias fuzziness in 5 box-shadow tests with meta name=fuzzy

### PR DESCRIPTION
**Pull request by TalbotG**
I added a
`<meta name="fuzzy" content="maxDifference=0-m;totalPixels=0-n" />`
in 5 box-shadow tests so that **Edge 120+** passes those tests, like this:

box-shadow-table-border-collapse-001.html
`<meta name="fuzzy" content="maxDifference=0-49;totalPixels=0-600">`

Current test result:
https://wpt.fyi/results/css/css-backgrounds/box-shadow-table-border-collapse-001.html

- - -

box-shadow-overlapping-001.html
`<meta name="fuzzy" content="maxDifference=0-30;totalPixels=0-800">`

Current test result:
https://wpt.fyi/results/css/css-backgrounds/box-shadow-overlapping-001.html

- - -
 
box-shadow-overlapping-002.html
`<meta name="fuzzy" content="maxDifference=0-30;totalPixels=0-1400">`

Current test result:
https://wpt.fyi/results/css/css-backgrounds/box-shadow-overlapping-002.html

- - -
 
box-shadow-overlapping-003.html
`<meta name="fuzzy" content="maxDifference=0-30;totalPixels=0-1600">`

Current test result:
https://wpt.fyi/results/css/css-backgrounds/box-shadow-overlapping-003.html

- - -

box-shadow-overlapping-004.html
`<meta name="fuzzy" content="maxDifference=0-30;totalPixels=0-2800">`

Current test result:
https://wpt.fyi/results/css/css-backgrounds/box-shadow-overlapping-004.html

### CODE REVIEW

**Review by dbaron — COMMENTED** [review]
I'm really not sure the edge results should count as passing -- particularly the last 4 -- given the test descriptions.

(Also, as a side comment, I generally think it's good to put the `<meta name=fuzzy>` close to the `<link rel=match>`, since to some degree it's a modifier to that.)

**Comment by TalbotG** [comment]
> I'm really not sure the edge results should count as passing -- particularly the last 4 -- given the test descriptions.

I am trying to be sure I understand your review comment in order to make appropriate modifications. The last 4: the last 4 what? The last 4 tests? The 4 box-shadow-overlapping tests? Or the last one: the box-shadow-overlapping-004 test?

There is a green rectangle and there is no red (visible by a human) in the Microsoft Edge results for the 4 box-shadow-overlapping tests. There is though tiny white lines and tiny darker lines in such 4 tests.

> (Also, as a side comment, I generally think it's good to put the `<meta name=fuzzy>` close to the `<link rel=match>`, since to some degree it's a modifier to that.)

I can make such adjustments. No problem.

**Comment by dbaron** [comment]
I meant the 4 `box-shadow-overlapping-*.html` tests.

**Comment by TalbotG** [comment]
Closing PR to trigger Continuous Integration checks

**Comment by TalbotG** [comment]
Reopening to trigger CI checks.

**Comment by TalbotG** [comment]
Reclosing to trigger CI checks...

**Comment by TalbotG** [comment]
Reopening to trigger CI checks...

**Comment by fantasai** [comment]
Closing based on dbaron's comment, and the fact that only Edge is failing these tests. If Edge wants to dispute whether their results are correct, that's up to them... but they should fail the tests until they investigate whether it's appropriate to have seams here (which it doesn't seem like it should be).

**Comment by TalbotG** [comment]
+1 :)

**Pull request closed without merging**
