### PR TITLE
Location: test IDNA behavior of origin

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/2568.

### CODE REVIEW

**Comment by annevk** [comment]
@jgraham this test is rather small and demonstrates my issue with the substitution feature rather clearly. You can use the feature to build up a URL, but this is a) somewhat cumbersome (you need to take care of scheme and port yourself if you want a custom domain) and b) buggy (the port bit doesn't work on w3c-test.org as it uses the default port).

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232810845)

# Firefox (nightly) #
Testing web-platform-tests at revision f47581f96ae2c1d0082511d9ca5692d09b0b7626
Using browser at version BuildID 20170516100213; SourceStamp 3e166b6838931b3933ca274331f9e0e115af5cc0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5939/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html">/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html</a></summary>


|                  Subtest                  | Results |                                                             Messages                                                             |
|-------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------|
|                                           | OK      |                                                                                                                                  |
| `Test that location.origin returns ASCII` | FAIL    | `assert_equals: expected "http://xn--n8j6ds53lwwkrqhv28a.web-platform.test:8000" but got "http://å¤©æ°ã®è¯ãæ¥.web-platform.test:8000"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232810847)

# Sauce (safari) #
Testing web-platform-tests at revision f47581f96ae2c1d0082511d9ca5692d09b0b7626
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5939/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html">/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html</a></summary>


|                  Subtest                  | Results |     Messages     |
|-------------------------------------------|---------|------------------|
|                                           | TIMEOUT |                  |
| `Test that location.origin returns ASCII` | TIMEOUT | `Test timed out` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232810849)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision f47581f96ae2c1d0082511d9ca5692d09b0b7626
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5939/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html">/html/browsers/history/the-location-interface/location-origin-idna.sub.window.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232810856)

# Chrome (unstable) #
Testing web-platform-tests at revision f47581f96ae2c1d0082511d9ca5692d09b0b7626

**Comment by zcorpan** [comment]
I restarted the Safari and Edge stability checker jobs since the results were TIMEOUT (but I didn't get a TIMEOUT in Safari locally).

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
