### PR TITLE
Improve the README.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-02-27 14:36:21
Finished: 2018-02-27 14:47:01


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24946)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346798387)

**Review by jgraham — CHANGES_REQUESTED** [review]
This was discussed on IRC. I think the contributing section should be under the details of how to run the existing tests, but there are several possible ways to make the overall organisation better.

**Comment by Ms2ger** [comment]
I'll look at it some more when I next have some free time :)

**Comment by jgraham** [comment]
Is there a plan to resurrect this PR or should it be closed?

**Pull request closed without merging**
