### PR TITLE
Add tests for input and change event properties

### PR DESCRIPTION
**Pull request by domenic**
See https://github.com/whatwg/html/issues/5453.

I think this is my first testdriver test!

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I see there's just one failure, in Safari: https://wpt.fyi/results/html/semantics/forms/input-change-event-properties.html?sha=4639b08e10&label=pr_head

Additional asserts might make it clearer which event didn't fire as expected.

**Comment by domenic** [comment]
Hmm, that's probably my bad; I assumed pressing down arrow on a select would be enough to change it in every browser, but that's rather UI dependent. This will be hard to fix without a Mac...

**Comment by foolip** [comment]
I made a [recording](https://drive.google.com/file/d/1ipW4ZFovi0PJHsivZJ7yC40BMJeKvbXA/view?usp=sharing) which might help figure out how to make this work on macOS. I clicked the select element with the mouse, then the down arrow only changes the selected option in the popup, it doesn't commit that change. Pressing space does.

Maybe sending a down and space key will work? If not then I'm not sure. Is it necessary for the change event to be triggered by use interaction with the form element, or could that one be done programatically?

**Comment by domenic** [comment]
> I made a recording which might help figure out how to make this work on macOS

Thank you very much!!

> Maybe sending a down and space key will work?

From your description, I should send a click first, right?

> Is it necessary for the change event to be triggered by use interaction with the form element, or could that one be done programatically?

Yes; programmatic changes do not trigger these events.

**Comment by domenic** [comment]
I give up; I can't manage to get Safari to trigger. Maybe it is an actual Safari bug! I'll merge and folks who own Macs can try to fix it...

**Pull request merged**
