### PR TITLE
BroadcastChannel: origin of events

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/pull/2689.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233132853)

# Firefox (nightly) #
Testing web-platform-tests at revision bf94009248a3aac6036a2b29a900f7530df129ee
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5957/webmessaging/broadcastchannel/origin.window.html">/webmessaging/broadcastchannel/origin.window.html</a></summary>


|                  Subtest                   | Results | Messages |
|--------------------------------------------|---------|----------|
|                                            | OK      |          |
| `Serialization of BroadcastChannel origin` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233132854)

# Sauce (safari) #
Testing web-platform-tests at revision bf94009248a3aac6036a2b29a900f7530df129ee
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5957/webmessaging/broadcastchannel/origin.window.html">/webmessaging/broadcastchannel/origin.window.html</a></summary>


|                  Subtest                   | Results |     Messages     |
|--------------------------------------------|---------|------------------|
|                                            | TIMEOUT |                  |
| `Serialization of BroadcastChannel origin` | TIMEOUT | `Test timed out` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233132855)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision bf94009248a3aac6036a2b29a900f7530df129ee
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5957/webmessaging/broadcastchannel/origin.window.html">/webmessaging/broadcastchannel/origin.window.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233132861)

# Chrome (unstable) #

**Review by mkruisselbrink — APPROVED** [review]

**Pull request merged**
