### PR TITLE
Import Opera XPath tests.

### PR DESCRIPTION
**Pull request by gsnedders**
These are from https://github.com/operasoftware/presto-testo/tree/master/core/standards/xpath.

They are converted to use `testharness.js` and `document.evaluate` rather than relying on XSLT magic and reftests.

I'm not entirely happy with having thousands of support files, but I'm not sure what would be better. Also not sure what the best solution as to how to store the Path queries is. The huge object in the test file seems kinda difficult to maintain…

### CODE REVIEW

**Comment by gsnedders** [comment]
Given @sideshowbarker asked what you guys should be reviewing, I'm mostly interested in the high-level overview of how this works and detail of the runner; so I want feedback on the structure of having thousands of XML files, but having all the XPath queries in `domxpath/xml_xpath_runner.html`.

I think we can assume the tests are correct without too much review (I presume somehow they were programmatically generated!) given they pass in at least WebKit, Blink, and Gecko (Edge is untested).

The tests undoubtedly could be better (they all are wrapped with the XPath `boolean()` function!), testing what is actually found and adding cases where there are similar but not-quite matching nodes, but they are a vast improvement on our almost non-existent XPath testing currently.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by gsnedders** [comment]
This times out for me on http://w3c-test.org/submissions/2124/domxpath/xml_xpath_runner.html because of the sheer number of XHR requests. Bah.

**Comment by gsnedders** [comment]
Bumping the timeout up seems to make Edge fail them all. Not investigated why. Still, we have interop with everyone else.

**Comment by gsnedders** [comment]
@jgraham r-'d this on IRC. I mostly agree. About to be replaced.

**Pull request closed without merging**
