### PR TITLE
Add interfaces/layers.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/8ee1b05/ed/idl/layers.idl
Build: https://travis-ci.org/w3c/webref/builds/203694231

### CODE REVIEW

**Comment by alcooper91** [comment]
Hi @stephenmcgruer or @foolip What would it take to get this merged and the appropriate test added under webxr/layers?

**Comment by stephenmcgruer** [comment]
> Hi @stephenmcgruer or @foolip What would it take to get this merged and the appropriate test added under webxr/layers?

Someone to send a PR that does that :). We usually send out a PR that is a copy of these initial 'Add' ones that also adds a test at the same time, so we can validate the idlharness. Doing that often falls on Philip or I when we have free time, but if someone else is willing to sign up then yes please! :D

b1d0f5495d39d36b7853d0c53a9fd096abba226d is a reasonably recent example (PR https://github.com/web-platform-tests/wpt/pull/25774, which closed https://github.com/web-platform-tests/wpt/pull/25766)

**Comment by alcooper91** [comment]
And it looks like the "add" PR's like this one (and presumably any updates after the "add") happen as a result of specs being added to: https://github.com/w3c/browser-specs/blame/master/specs.json ?

**Comment by stephenmcgruer** [comment]
> And it looks like the "add" PR's like this one (and presumably any updates after the "add") happen as a result of specs being added to: https://github.com/w3c/browser-specs/blame/master/specs.json ?

I defer to @foolip on that question :)

**Pull request closed without merging**
