### PR TITLE
Prevent false positives

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by mnoorenberghe — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-21 04:48:14
Finished: 2018-03-21 04:54:39





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26262)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/356193027)

**Comment by marcoscaceres** [comment]
So, um, I'm little embarrassed to admit that I thought Chrome had implemented requiring click on `.show()`... turns out, as of this test, not yet. 

So we don't actually know if Chrome will be able to do the `postMessage()` either ☺️.

Oh hai, @rsolomakhin!

**Comment by rsolomakhin** [comment]
Hai, @marcoscaceres! We are waiting for `.show()` promise work to be finished before requiring user gesture for `.show()`. This avoid breaking some existing merchants.

**Comment by marcoscaceres** [comment]
@rsolomakhin sounds good. I know Chrome recently landed support for "triggered by user activation" surviving a `promise.then()`, but do you know if  `postMessage()`? Stripe folks were asking, as their iframe is hidden, and it's the iframe that actually calls `show()`.

**Comment by rsolomakhin** [comment]
@marcoscaceres: @mounirlamouri says it should work, but it's behind a flag at the moment.

**Comment by marcoscaceres** [comment]
Excellent, thanks for the update. If there is a bug I can cc myself on let me know. We’ll need both Firefox and Chrome to pass this test to get us out of CR.

**Pull request merged**
