### PR TITLE
Sync Mozilla reftests as of 2017-05-24

### PR DESCRIPTION
**Pull request by dbaron**
Sync Mozilla tests as of  https://hg.mozilla.org/mozilla-central/rev/d93182f36b3c134a3b1c6718f09eb87c2913e364 .

These changes have been reviewed in https://bugzilla.mozilla.org/show_bug.cgi?id=1366434

### CODE REVIEW

**Comment by dbaron** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6035)*

**Review by jgraham — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235640734)

# Firefox (nightly) #
Testing web-platform-tests at revision ab622f0365731efc9813be39f62213b1f449234c
Using browser at version BuildID 20170523100217; SourceStamp 5bc1c758ab57c1885dceab4e7837e58af27b998c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235640735)

# Sauce (safari) #
Testing web-platform-tests at revision ab622f0365731efc9813be39f62213b1f449234c
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235640741)

# Chrome (unstable) #
Testing web-platform-tests at revision ab622f0365731efc9813be39f62213b1f449234c
Using browser at version 60.0.3107.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235640742)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ab622f0365731efc9813be39f62213b1f449234c
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-composite-1d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6035/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html">/css/vendor-imports/mozilla/mozilla-central-reftests/masking/mask-mode-d.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Pull request merged**
