### PR TITLE
SharedArrayBuffer and blob:/data: worker

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/html/issues/5198 and https://github.com/whatwg/html/issues/4916. `blob:` has to work, not sure about `data:` URLs again.

### CODE REVIEW

**Comment by annevk** [comment]
The problem with the data URL case is that it needs to use a blob URL for its nested worker as otherwise the nested worker would not be same-origin with it. (See also https://github.com/whatwg/html/issues/5254 for how it's a bit more complex therefore.)

**Comment by annevk** [comment]
That's now addressed. @hemeryar @ParisMeuleman @camillelamy please review!

**Comment by annevk** [comment]
If this seems reasonable I could maybe make this more generic to also test blob/data frames this way.

**Review by ParisMeuleman — APPROVED** [review]
Thanks @annevk for this.

Overall lgtm.

Although adding a few comments, especially in the dataWorkerScript could improve readability IMO (e.g. view was not a very clear name to me, likewise for L52 the handling of the 2 messages from the sub-worker) .
I reckon doing the work to make it generic could solve this point.

**Comment by annevk** [comment]
@ParisMeuleman do you want to have another look?

**Comment by annevk** [comment]
@ParisMeuleman ping.

**Review by ParisMeuleman — APPROVED** [review]
Thanks LGTM!

**Pull request merged**
