### PR TITLE
Flatten the webrtc/ directory to make it less confusing

### PR DESCRIPTION
**Pull request by foolip**
All tests in webrtc/ invoke `new RTCPeerConnection`, whether in
rtcpeerconnection/ or outside of it. Move the test to just webrtc/ and
capitalize them in a way more like in mediacapture-streams/.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5657)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225169846)

# Lint #

Passed

**Comment by w3c-bots** [comment]
*This report has been truncated because the total content is 77882 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225169848)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 05a3bb81c32e747ab9f20f07c482d54ff98b618f
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5657/webrtc/RTCConfiguration-iceCandidatePoolSize.html">/webrtc/RTCConfiguration-iceCandidatePoolSize.html</a></summary>


|                          Subtest                           | Results |                                               Messages                                              |
|------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------|
|                                                            | OK      |                                                                                                     |
| `Setting iceCandidatePoolSize to a valid value: 10`        | FAIL    | `assert_equals: expected (number) 10 but got (undefined) undefined`                                 |
| `Setting iceCandidatePoolSize to a valid value: 0`         | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                  |
| `Setting iceCandidatePoolSize to a valid value: null`      | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                  |
| `Setting iceCandidatePoolSize to a valid value: undefined` | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                  |
| `Setting iceCandidatePoolSize to an invalid value: -1`     | FAIL    | `assert_throws: function "() => new RTCPeerConnection({iceCandidatePoolSize: size})" did not throw` |
| `Setting iceCandidatePoolSize to an invalid value: 1000`   | FAIL    | `assert_throws: function "() => new RTCPeerConnection({iceCandidatePoolSize: size})" did not throw` |
| `Setting iceCandidatePoolSize to an invalid value: string` | FAIL    | `assert_throws: function "() => new RTCPeerConnection({iceCandidatePoolSize: size})" did not throw` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5657/webrtc/RTCPeerConnection-canTrickleIceCandidates.html">/webrtc/RTCPeerConnection-canTrickleIceCandidates.html</a></summary>


|                                               Subtest                                                | Results | Messages |
|------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                      | OK      |          |
| `canTrickleIceCandidates property is null prior to setRemoteDescription`                             | PASS    |          |
| `canTrickleIceCandidates property is true after setRemoteDescription with a=ice-options:trickle`     | PASS    |          |
| `canTrickleIceCandidates property is false after setRemoteDescription without a=ice-options:trickle` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5657/webrtc/RTCPeerConnection-constructor.html">/webrtc/RTCPeerConnection-constructor.html</a></summary>


|                                                                    Subtest                                                                     | Results |                                                                                                                         Messages                                                                                                                        |
|------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                | OK      |                                                                                                                                                                                                                                                         |
| `RTCPeerConnection.length`                                                                                                                     | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection()`                                                                                                                      | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection(null)`                                                                                                                  | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection(undefined)`                                                                                                             | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({})`                                                                                                                    | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: null })`                                                                                                  | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: undefined })`                                                                                             | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [] })`                                                                                                    | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{}] })`                                                                                                  | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" threw object "InvalidAccessError: RTCPeerConnection constructor passed invalid RTCConfiguration - missing urls" ("InvalidAccessError") expected object "TypeError" ("TypeError")` |
| `new RTCPeerConnection({ iceServers: [null] })`                                                                                                | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" threw object "InvalidAccessError: RTCPeerConnection constructor passed invalid RTCConfiguration - missing urls" ("InvalidAccessError") expected object "TypeError" ("TypeError")` |
| `new RTCPeerConnection({ iceServers: [undefined] })`                                                                                           | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" threw object "InvalidAccessError: RTCPeerConnection constructor passed invalid RTCConfiguration - missing urls" ("InvalidAccessError") expected object "TypeError" ("TypeError")` |
| `new RTCPeerConnection({ iceServers: [{ urls: "stun:stun1.example.net" }] })`                                                                  | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: [] }] })`                                                                                        | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: ["stun:stun1.example.net"] }] })`                                                                | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: ["stun:stun1.example.net", "stun:stun2.example.net"] }] })`                                      | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turns:turn.example.org", username: "user", credential: "cred" }] })`                            | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turn:turn.example.net", username: "user", credential: "cred" }] })`                             | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turns:turn.example.org", username: "", credential: "" }] })`                                    | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turn:turn.example.net", username: "", credential: "" }] })`                                     | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: ["turns:turn.example.org", "turn:turn.example.net"], username: "user", credential: "cred" }] })` | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "stun:stun1.example.net", credentialType: "password" }] })`                                      | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "stun:stun1.example.net", credentialType: "token" }] })`                                         | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turn:turn.example.net" }] })`                                                                   | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turn:turn.example.net", username: "user" }] })`                                                 | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turn:turn.example.net", credential: "cred" }] })`                                               | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turns:turn.example.org" }] })`                                                                  | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turns:turn.example.org", username: "user" }] })`                                                | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "turns:turn.example.org", credential: "cred" }] })`                                              | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "relative-url" }] })`                                                                            | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: "http://example.com" }] })`                                                                      | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: [], credentialType: "password" }] })`                                                            | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: [], credentialType: "token" }] })`                                                               | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ urls: [], credentialType: "invalid" }] })`                                                             | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceServers: [{ url: "stun:stun1.example.net" }] })`                                                                   | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" did not throw`                                                                                                                                                                    |
| `new RTCPeerConnection({ iceTransportPolicy: null })`                                                                                          | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransportPolicy: undefined })`                                                                                     | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransportPolicy: "relay" })`                                                                                       | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransportPolicy: "all" })`                                                                                         | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransportPolicy: "invalid" })`                                                                                     | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransportPolicy: "none" })`                                                                                        | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransports: "invalid" })`                                                                                          | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceTransports: "none" })`                                                                                             | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: null })`                                                                                                | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: undefined })`                                                                                           | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: "balanced" })`                                                                                          | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: "max-compat" })`                                                                                        | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: "max-bundle" })`                                                                                        | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ bundlePolicy: "invalid" })`                                                                                           | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ rtcpMuxPolicy: null })`                                                                                               | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" did not throw`                                                                                                                                                                    |
| `new RTCPeerConnection({ rtcpMuxPolicy: undefined })`                                                                                          | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ rtcpMuxPolicy: "negotiate" })`                                                                                        | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ rtcpMuxPolicy: "require" })`                                                                                          | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ rtcpMuxPolicy: "invalid" })`                                                                                          | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" did not throw`                                                                                                                                                                    |
| `new RTCPeerConnection({ peerIdentity: toStringThrows })`                                                                                      | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: null })`                                                                                                | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: undefined })`                                                                                           | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: [] })`                                                                                                  | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: [null] })`                                                                                              | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: [undefined] })`                                                                                         | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ iceCandidatePoolSize: toNumberThrows })`                                                                              | FAIL    | `assert_throws: function "function() {\n        eval(expr);\n      }" did not throw`                                                                                                                                                                    |
| `new RTCPeerConnection({ certificates: [certificate] })`                                                                                       | PASS    |                                                                                                                                                                                                                                                         |
| `new RTCPeerConnection({ certificates: [expiredCertificate] })`                                                                                | FAIL    | `assert_throws: function "function() {\n          new RTCPeerConnection({ certificates: [certificate] });\n        }" did not throw`                                                                                                                    |
| `localDescription initial value`                                                                                                               | PASS    |                                                                                                                                                                                                                                                         |
| `currentLocalDescription initial value`                                                                                                        | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                                                                                   |
| `pendingLocalDescription initial value`                                                                                                        | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                                                                                   |
| `remoteDescription initial value`                                                                                                              | PASS    |                                                                                                                                                                                                                                                         |
| `currentRemoteDescription initial value`                                                                                                       | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                                                                                   |
| `pendingRemoteDescription initial value`                                                                                                       | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                                                                                   |
| `signalingState initial value`                                                                                                                 | PASS    |                                                                                                                                                                                                                                                         |
| `iceGatheringState initial value`                                                                                                              | PASS    |                                                                                                                                                                                                                                                         |
| `iceConnectionState initial value`                                                                                                             | PASS    |                                                                                                                                                                                                                                                         |
| `connectionState initial value`                                                                                                                | FAIL    | `assert_equals: expected (string) "new" but got (undefined) undefined`                                                                                                                                                                                  |
| `canTrickleIceCandidates initial value`                                                                                                        | PASS    |                                                                                                                                                                                                                                                         |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5657/webrtc/RTCPeerConnection-iceGatheringState.html">/webrtc/RTCPeerConnection-iceGatheringState.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `Tests that the ICE gathering state ends up as "completed" after applying a local offer.` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5657/webrtc/RTCPeerConnection-idl.html">/webrtc/RTCPeerConnection-idl.html</a></summary>


|                                                                                      Subtest                                                                                       | Results |                                                                            Messages                                                                           |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                    | OK      |                                                                                                                                                               |
| `EventTarget interface: existence and properties of interface object`                                                                                                              | PASS    |                                                                                                                                                               |
| `EventTarget interface object length`                                                                                                                                              | PASS    |                                                                                                                                                               |
| `EventTarget interface object name`                                                                                                                                                | PASS    |                                                                                                                                                               |
| `EventTarget interface: existence and properties of interface prototype object`                                                                                                    | PASS    |                                                                                                                                                               |
| `EventTarget interface: existence and properties of interface prototype object's "constructor" property`                                                                           | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: existence and properties of interface object`                                                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface object length`                                                                                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface object name`                                                                                                                                          | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: existence and properties of interface prototype object`                                                                                              | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: existence and properties of interface prototype object's "constructor" property`                                                                     | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation createOffer(RTCOfferOptions)`                                                                                                              | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation createAnswer(RTCAnswerOptions)`                                                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation setLocalDescription(RTCSessionDescription)`                                                                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute localDescription`                                                                                                                          | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute currentLocalDescription`                                                                                                                   | FAIL    | `assert_true: The prototype object must have a property "currentLocalDescription" expected true got false`                                                    |
| `RTCPeerConnection interface: attribute pendingLocalDescription`                                                                                                                   | FAIL    | `assert_true: The prototype object must have a property "pendingLocalDescription" expected true got false`                                                    |
| `RTCPeerConnection interface: operation setRemoteDescription(RTCSessionDescription)`                                                                                               | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute remoteDescription`                                                                                                                         | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute currentRemoteDescription`                                                                                                                  | FAIL    | `assert_true: The prototype object must have a property "currentRemoteDescription" expected true got false`                                                   |
| `RTCPeerConnection interface: attribute pendingRemoteDescription`                                                                                                                  | FAIL    | `assert_true: The prototype object must have a property "pendingRemoteDescription" expected true got false`                                                   |
| `RTCPeerConnection interface: operation addIceCandidate(RTCIceCandidate)`                                                                                                          | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute signalingState`                                                                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute iceGatheringState`                                                                                                                         | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute iceConnectionState`                                                                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute canTrickleIceCandidates`                                                                                                                   | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation getConfiguration()`                                                                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation setConfiguration(RTCConfiguration)`                                                                                                        | FAIL    | `assert_own_property: interface prototype object missing non-static operation expected property "setConfiguration" missing`                                   |
| `RTCPeerConnection interface: operation close()`                                                                                                                                   | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute onnegotiationneeded`                                                                                                                       | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute onicecandidate`                                                                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute onsignalingstatechange`                                                                                                                    | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute oniceconnectionstatechange`                                                                                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute onicegatheringstatechange`                                                                                                                 | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation createOffer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback,RTCOfferOptions)`                                                 | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation setLocalDescription(RTCSessionDescription,VoidFunction,RTCPeerConnectionErrorCallback)`                                                    | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation createAnswer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback)`                                                                | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation setRemoteDescription(RTCSessionDescription,VoidFunction,RTCPeerConnectionErrorCallback)`                                                   | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation addIceCandidate(RTCIceCandidate,VoidFunction,RTCPeerConnectionErrorCallback)`                                                              | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation getStats(MediaStreamTrack,RTCStatsCallback,RTCPeerConnectionErrorCallback)`                                                                | FAIL    | `assert_throws: calling operation with this = null didn't throw TypeError function "function() {\n            fn.apply(obj, args);\n        }" did not throw` |
| `RTCPeerConnection interface: operation generateCertificate(AlgorithmIdentifier)`                                                                                                  | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation getSenders()`                                                                                                                              | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation getReceivers()`                                                                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation addTrack(MediaStreamTrack,MediaStream)`                                                                                                    | FAIL    | `assert_equals: property has wrong .length expected 1 but got 2`                                                                                              |
| `RTCPeerConnection interface: operation removeTrack(RTCRtpSender)`                                                                                                                 | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute ontrack`                                                                                                                                   | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation createDataChannel(DOMString,RTCDataChannelInit)`                                                                                           | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute ondatachannel`                                                                                                                             | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute dtmf`                                                                                                                                      | FAIL    | `assert_true: The prototype object must have a property "dtmf" expected true got false`                                                                       |
| `RTCPeerConnection interface: operation getStats(MediaStreamTrack)`                                                                                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation setIdentityProvider(DOMString,DOMString,DOMString)`                                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: operation getIdentityAssertion()`                                                                                                                    | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute peerIdentity`                                                                                                                              | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: attribute idpLoginUrl`                                                                                                                               | PASS    |                                                                                                                                                               |
| `RTCPeerConnection must be primary interface of pc`                                                                                                                                | PASS    |                                                                                                                                                               |
| `Stringification of pc`                                                                                                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "createOffer" with the proper type (0)`                                                                                     | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: calling createOffer(RTCOfferOptions) on pc with too few arguments must throw TypeError`                                                              | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "createAnswer" with the proper type (1)`                                                                                    | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: calling createAnswer(RTCAnswerOptions) on pc with too few arguments must throw TypeError`                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "setLocalDescription" with the proper type (2)`                                                                             | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: calling setLocalDescription(RTCSessionDescription) on pc with too few arguments must throw TypeError`                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "localDescription" with the proper type (3)`                                                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "currentLocalDescription" with the proper type (4)`                                                                         | FAIL    | `assert_inherits: property "currentLocalDescription" not found in prototype chain`                                                                            |
| `RTCPeerConnection interface: pc must inherit property "pendingLocalDescription" with the proper type (5)`                                                                         | FAIL    | `assert_inherits: property "pendingLocalDescription" not found in prototype chain`                                                                            |
| `RTCPeerConnection interface: pc must inherit property "setRemoteDescription" with the proper type (6)`                                                                            | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: calling setRemoteDescription(RTCSessionDescription) on pc with too few arguments must throw TypeError`                                               | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "remoteDescription" with the proper type (7)`                                                                               | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "currentRemoteDescription" with the proper type (8)`                                                                        | FAIL    | `assert_inherits: property "currentRemoteDescription" not found in prototype chain`                                                                           |
| `RTCPeerConnection interface: pc must inherit property "pendingRemoteDescription" with the proper type (9)`                                                                        | FAIL    | `assert_inherits: property "pendingRemoteDescription" not found in prototype chain`                                                                           |
| `RTCPeerConnection interface: pc must inherit property "addIceCandidate" with the proper type (10)`                                                                                | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: calling addIceCandidate(RTCIceCandidate) on pc with too few arguments must throw TypeError`                                                          | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "signalingState" with the proper type (11)`                                                                                 | FAIL    | `Unrecognized type RTCSignalingState`                                                                                                                         |
| `RTCPeerConnection interface: pc must inherit property "iceGatheringState" with the proper type (12)`                                                                              | FAIL    | `Unrecognized type RTCIceGatheringState`                                                                                                                      |
| `RTCPeerConnection interface: pc must inherit property "iceConnectionState" with the proper type (13)`                                                                             | FAIL    | `Unrecognized type RTCIceConnectionState`                                                                                                                     |
| `RTCPeerConnection interface: pc must inherit property "canTrickleIceCandidates" with the proper type (14)`                                                                        | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "getConfiguration" with the proper type (15)`                                                                               | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "setConfiguration" with the proper type (16)`                                                                               | FAIL    | `assert_inherits: property "setConfiguration" not found in prototype chain`                                                                                   |
| `RTCPeerConnection interface: calling setConfiguration(RTCConfiguration) on pc with too few arguments must throw TypeError`                                                        | FAIL    | `assert_inherits: property "setConfiguration" not found in prototype chain`                                                                                   |
| `RTCPeerConnection interface: pc must inherit property "close" with the proper type (17)`                                                                                          | PASS    |                                                                                                                                                               |
| `RTCPeerConnection interface: pc must inherit property "onnegotiationneeded" with the proper type (18)`                                                                            | FAIL    | `Unrecognized type EventHandler`                                                                                                                              |
| `RTCPeerConnection interface: pc must inherit property "onicecandidate" with the proper type (19)`                                                                                 | FAIL    | `Unrecognized type EventHandler`                                                                                                                              |
| `RTCPeerConnection interface: pc must inherit property "onsignalingstatechange" with the proper type (20)`                                                                         | FAIL    | `Unrecognized type EventHandler`                                                                                                                              |
| `RTCPeerConnection interface: pc must inherit property "oniceconnectionstatechange" with the proper type (21)`

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225169854)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 05a3bb81c32e747ab9f20f07c482d54ff98b618f

**Comment by foolip** [comment]
@agouaillard, can you merge this before new tests start coming in?

**Comment by foolip** [comment]
Thanks!

**Pull request merged**
