### PR TITLE
Replace usage of setTimeout with step_timeout.

### PR DESCRIPTION
**Pull request by jgraham**
This is expected to help test stability on slow configurations, as the
timeouts will be multiplied by the timeout multiplier.

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/1816)

### CODE REVIEW

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by sideshowbarker** [comment]
Linting fails for this with `SET TIMEOUT` linting errors https://travis-ci.org/w3c/web-platform-tests/builds/61842038

**Comment by sideshowbarker** [comment]
Just noting that this is waiting on https://github.com/w3c/testharness.js/pull/127 to be merged.

**Comment by sideshowbarker** [comment]
Note that https://github.com/w3c/testharness.js/pull/127 has landed but I see that at this point this PR has merge conflicts. Would be nice to get this updated and landed so that we can merge https://github.com/w3c/wpt-tools/issues/5

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by wolenetz** [comment]
media-source/URL-createObjectURL-revoke.html has another occurrence of setTimeout, currently.

**Comment by annevk** [comment]
Do you still want to proceed with this or should I try fixing this for directories I'm willing to take some ownership over?

**Comment by annevk** [comment]
I went ahead and changed this for CORS and XMLHttpRequest.

**Pull request closed without merging**
