### PR TITLE
[css-grid] Add @javifernandez and @svillar as OWNERS

### PR DESCRIPTION
**Pull request by mrego**
They both are working on the CSS Grid Layout implementation
in Blink and WebKit and will help with reviews of tests in this folder.

### CODE REVIEW

**Comment by gsnedders** [comment]
Can the pair of you confirm you're okay with this?

**Comment by javifernandez** [comment]
> Can the pair of you confirm you're okay with this?
I'm ok.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235812857)

# Firefox (nightly) #
Testing web-platform-tests at revision 8b77de9ac7722d3e74e1b9cd26ca404b460d6384
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235812859)

# Sauce (safari) #
Testing web-platform-tests at revision 8b77de9ac7722d3e74e1b9cd26ca404b460d6384
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235812869)

# Chrome (unstable) #
Testing web-platform-tests at revision 8b77de9ac7722d3e74e1b9cd26ca404b460d6384

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235812870)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 8b77de9ac7722d3e74e1b9cd26ca404b460d6384

**Comment by svillar** [comment]
Yep I'm fine too

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
