### PR TITLE
script.evaluate: invalid.py: fix duplicate function names

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Review by jrandolf — APPROVED** [review]

**Review by whimboo — CHANGES_REQUESTED** [review]
Sorry, but I do not see the problem here. Which tests have the same name? We have once invalid type and then invalid value.

**Comment by thiagowfx** [comment]
@whimboo It's very subtle:

https://github.com/web-platform-tests/wpt/blob/c47d47783f71e75a4868d5944e117afa0602dcae/webdriver/tests/bidi/script/evaluate/invalid.py#L119

There are 4 functions in the screenshot. Functions 1 and 3 have the same name, as well as 2 and 4.

image

**Comment by thiagowfx** [comment]
The last two functions refer to shadow root, but they kept `max_object_depth` in their names by mistake.

**Comment by whimboo** [comment]
> The last two functions refer to shadow root, but they have `max_object_depth` in their names by mistake.

Oh, I see. Thanks for pointing it out.

**Pull request merged**
