### PR TITLE
Update Safari Technology Preview to 119

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 119, 15611.1.10.1)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=2659&view=logs

### CODE REVIEW

**Review by stephenmcgruer — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
`resources/` test failures are unrelated (there's a PR out to fix them), and the single azure failure is unrelated too (its from a test that doesn't even run safari)

**Comment by foolip** [comment]
I came to check for interesting changes between 118 and 119, but it looks like no runs have succeeded since this landed. Known issue?

**Comment by stephenmcgruer** [comment]
> I came to check for interesting changes between 118 and 119, but it looks like no runs have succeeded since this landed. Known issue?

I noticed this earlier. We've had a spate of failed runs on Azure with no clear cause it seems. The current one is running (https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=60184&view=results) and we'll see how that does.

**Comment by stephenmcgruer** [comment]
> I came to check for interesting changes between 118 and 119, but it looks like no runs have succeeded since this landed. Known issue?

Latest run succeeded. There's a bit of gap between them, but https://wpt.fyi/results/?diff&filter=ADC&q=is%3Adifferent&run_id=5705922615705600&run_id=5087823168274432 is the best diff we have.

**Comment by foolip** [comment]
Thanks @stephenmcgruer! Looks like a bunch of improvements in CSS and something's happening with WebAssembly. Cool!

**Pull request merged**
