### PR TITLE
Comment out SVGElement dependency from html.idl

### PR DESCRIPTION
**Pull request by annevk**
Fixes regression caused by #10110.

### CODE REVIEW

**Review by Hexcles — APPROVED** [review]
LGTM, although I too am not sure what is the best approach here given you said "it seems svg/interfaces.html hasn't really been converted to use mixins thus far and also duplicates some stuff (GlobalEventHandlers)"

**Comment by Hexcles** [comment]
BTW I'm also fixing the affected tests from the Chromium side https://crrev.com/c/978508

Both this PR and my CL can fix the current regression independently. And we may also have them both, especially since my CL narrows down the dependencies in a few tests by using `add_untested_idls(..., { only: [...] })` so it's good to have anyway.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26406)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/357512667)

**Comment by annevk** [comment]
@Hexcles @foolip I'll let you merge this (please use "rebase and merge") if you think this is needed.

**Comment by foolip** [comment]
Since the problem has been fixed I think we should close this and fix https://github.com/w3c/web-platform-tests/blob/master/svg/interfaces.html by creating a new interfaces/svg.idl that matches the current spec. If the current SVG spec's IDL doesn't mix with the current HTML spec's IDL, that's a problem to fix spec-side first.

@lukebjerring, I guess that SVG isn't one of the specs that we have complete IDL to auto-update with?

**Pull request closed without merging**
