### PR TITLE
Update the geometry IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25202)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/348438425)

**Review by foolip — APPROVED** [review]
Yay for removing `[NoInterfaceObject]` \o/

**Comment by foolip** [comment]
These changes are good, but looking at https://pulls.web-platform-tests.org/build/25659 I realize we have a problem: we're not running any tests when updating the IDL files even though locally `wpt tests-affected` does list css/cssom-view/interfaces.html. It doesn't list css/geometry/interfaces.html because an indirection via css/geometry/support/interfaces.js.

So, um... filed https://github.com/w3c/wpt-pullresults/issues/61 for the fact that the results for Firefox weren't saved even though they did run. Tested https://web-platform.test:8443/css/geometry/interfaces.html locally, and we get new harness error:

3 duplicate test names: "Test default toJSON operation of DOMPointReadOnly", "Test default toJSON operation of DOMRectReadOnly", "Test default toJSON operation of DOMMatrixReadOnly"

**Comment by lukebjerring** [comment]
https://github.com/w3c/web-platform-tests/pull/9787/commits/7ab9a09b3cc56ba3b10831ef0694a9f99d78448e handles one of the duplicate test name causes, and 
https://github.com/w3c/web-platform-tests/pull/10029 handles the other, though needs review.

**Pull request merged**
