### PR TITLE
Update the cors-rfc1918 IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The Spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-07 23:06:21
Finished: 2018-03-07 23:16:10


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25494)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350508998)

**Comment by lukebjerring** [comment]
@foolip - Added a test. PTAL.

**Review by annevk — CHANGES_REQUESTED** [review]
I'm not sure this should be inside the `cors/` directory. `fetch` is probably more suitable if we don't want this as its own top-level thing. @mikewest?

**Comment by mikewest** [comment]
Putting them under `/fetch/cors-rfc1918/` seems right to me. I'd also name them as `.tentative`, since I don't think we're anywhere near consensus that it's the right thing to do. :)

**Comment by lukebjerring** [comment]
Alrighty, moved as requested.

**Review by annevk — APPROVED** [review]

**Pull request merged**
