### PR TITLE
Add @r12a as an owner to all i18n directories

### PR DESCRIPTION
**Pull request by gsnedders**
cc/ @r12a

### CODE REVIEW

**Review by r12a — COMMENTED** [review]
Noted.

**Comment by gsnedders** [comment]
@r12a I presume I can take that to mean you're okay with this?

**Comment by gsnedders** [comment]
(Let me know if anyone else should be added!)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255308467)

# Firefox (nightly) #
Testing web-platform-tests at revision fa9d18ef3e21a27f77f463dc3ff2499be759fc19
Using browser at version BuildID 20170719100147; SourceStamp 1b065ffd8a535a0ad4c39a912af18e948e6a42c1
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255308468)

# Sauce (safari) #
Testing web-platform-tests at revision fa9d18ef3e21a27f77f463dc3ff2499be759fc19
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255308474)

# Chrome (unstable) #
Testing web-platform-tests at revision fa9d18ef3e21a27f77f463dc3ff2499be759fc19
Using browser at version 61.0.3159.5 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255308475)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision fa9d18ef3e21a27f77f463dc3ff2499be759fc19

**Comment by r12a** [comment]
@gsnedders i guess it makes sense, though i don't really have spare cycles for this, so i'm hoping it won't involve much work. It's possible that @kojiishi and/or @fantasai could be added for the CSS tests...(?)

**Review by jgraham — APPROVED** [review]

**Pull request merged**
