### PR TITLE
Add more window.history.replaceState tests

### PR DESCRIPTION
**Pull request by xingri**
Co-authored-by: Harnoor Singh <harnoors@nvidia.com>

Discussed through: https://bugs.webkit.org/show_bug.cgi?id=263635

### CODE REVIEW

**Review by domenic — CHANGES_REQUESTED** [review]
I believe this is incorrect, per https://html.spec.whatwg.org/#shared-history-push/replace-state-steps step 6 which special-cases the empty string to do nothing.

**Comment by xingri** [comment]
> I believe this is incorrect, per https://html.spec.whatwg.org/#shared-history-push/replace-state-steps step 6 which special-cases the empty string to do nothing.

Thanks for the review @domenic  We will look into the spec and will back to you.

**Comment by xingri** [comment]
> > I believe this is incorrect, per https://html.spec.whatwg.org/#shared-history-push/replace-state-steps step 6 which special-cases the empty string to do nothing.
> 
> Thanks for the review @domenic We will look into the spec and will back to you.

@domenic as I shared through the webkit bugzilla, the fix was made on <https://bugs.webkit.org/show_bug.cgi?id=276375> patched by @TingPing. 

I think we have to go back the the patch and see what is the right path for the issue.

**Comment by xingri** [comment]
To add some more testing results on different variation of the browsers. 

1. Safari: Except STP #202, it does nothing on the empty string.
2. Chrome/Edge: Up to 130 nightly release, it changes the URL as described in the current PR.
3. Mozilla:  Up to 130 release, t does nothing on the empty string.

**Comment by xingri** [comment]
@domenic , @TingPing and @sideshowbarker  any suggestions? 
Should we change the current PR to check on doing nothing on the empty string? 
And then fix the WebKit & Chrome to do the right, is it a right understanding?

**Comment by domenic** [comment]
Yes, the PR should match the specification. Chromium already has an open bug. https://bugs.chromium.org/p/chromium/issues/detail?id=1450466

**Comment by domenic** [comment]
Tests for this case were already added in https://github.com/web-platform-tests/wpt/pull/40269 so I don't think more are necessary.

**Comment by xingri** [comment]
@domenic  Thanks for the advice. Per our discussion, closing the PR.

**Pull request closed without merging**
