### PR TITLE
HTML: Change <td hidden> and <th hidden> to expect display: none

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/whatwg/html/pull/3736.

### CODE REVIEW

**Comment by annevk** [comment]
Why would we only change these? Browsers fail for the other table elements too.

**Comment by zcorpan** [comment]
Because `visibility: collapse` "works" on the other table elements, but acts like `visibility: hidden` on table cells.

**Comment by annevk** [comment]
Do we expect implementations to align for those though?

**Comment by zcorpan** [comment]
Quoting @FremyCompany in

> I understand the value of using visibility:collapse for table rows and table columns, as visibility:collapse is some sort of smart display:none, and I think a breaking change there is acceptable for these.

https://github.com/whatwg/html/issues/3728#issuecomment-394020407

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17718818/ is assigned; I hope the rest will follow.

**Review by annevk — APPROVED** [review]
Since you filed bugs, I guess we can see how it goes.

**Pull request merged**
