### PR TITLE
Add an historical test for getMatchedCSSRules()

### PR DESCRIPTION
**Pull request by foolip**
Chromium issue to Deprecate and Remove:
https://bugs.chromium.org/p/chromium/issues/detail?id=437569

### CODE REVIEW

**Comment by foolip** [comment]
@miketaylr, are you OK with using compat/historical.html for features we're trying to remove from the web platform? @darrnshn @RByers FYI.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17458)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265156712)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17458)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265156712)

**Comment by RByers** [comment]
Yeah for APIs that were never standardized in any spec, this seems like the best place to add historical tests to me.  In case others aren't aware - we're already following this pattern of historical.html tests in other directories when a spec has been changed to remove an API.

**Review by Ms2ger — APPROVED** [review]

**Comment by miketaylr** [comment]
> @miketaylr, are you OK with using compat/historical.html for features we're trying to remove from the web platform?

Yes! SGTM.

(working on mail filters, it turns out I've missed quite a bit... 🙈)

**Pull request merged**
