### PR TITLE
Remove giant unused ttf file.

### PR DESCRIPTION
**Pull request by jgraham**
AFAICT only the woff version of this font is actually used in any
tests, so there's no point in keeping the almost-2Mb ttf version as well.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5328)

### CODE REVIEW

**Comment by r12a** [comment]
Don't we have CSS fonts tests that test downloads of normal fonts, rather than woff fonts?

**Comment by r12a** [comment]
Um, on reflection, such tests would probably not need such a large font.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218168858)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 06e3a49e22060525bed69bbf5d9bf7ef23579793
Using browser at version BuildID 20170403100136; SourceStamp 38894655c89e68bcd8f45d31a0d3005f2c2b53db
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5328/service-workers/service-worker/fetch-event.https.html">/service-workers/service-worker/fetch-event.https.html</a></summary>


|                                   Subtest                                    | Results |                                                      Messages                                                      |
|------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------|
|                                                                              | OK      |                                                                                                                    |
| `Service Worker responds to fetch event with string`                         | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with blob body`                      | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the referrer URL`               | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the referrer policy`            | FAIL    | `assert_unreached: unexpected rejection: NetworkError when attempting to fetch resource. Reached unreachable code` |
| `Service Worker responds to fetch event with an existing client id`          | PASS    |                                                                                                                    |
| `Service Worker does not respond to fetch event`                             | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with null response body`             | PASS    |                                                                                                                    |
| `Service Worker fetches other file in fetch event`                           | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with POST form`                      | PASS    |                                                                                                                    |
| `Multiple calls of respondWith must throw InvalidStateErrors`                | PASS    |                                                                                                                    |
| `Service Worker event.respondWith must set the used flag`                    | PASS    |                                                                                                                    |
| `Service Worker should expose FetchEvent URL fragments.`                     | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the correct cache types`        | PASS    |                                                                                                                    |
| `Service Worker should intercept EventSource`                                | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the correct integrity_metadata` | PASS    |                                                                                                                    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5328/service-workers/service-worker/navigation-preload/redirect.https.html">/service-workers/service-worker/navigation-preload/redirect.https.html</a></summary>


|                            Subtest                            | Results |     Messages     |
|---------------------------------------------------------------|---------|------------------|
|                                                               | TIMEOUT |                  |
| `Navigation Preload redirect response.`                       | TIMEOUT | `Test timed out` |
| `Navigation Preload no-location redirect response.`           | NOTRUN  |                  |
| `Navigation Preload no-location redirect response with body.` | NOTRUN  |                  |
| `Navigation Preload redirect to the same scope.`              | NOTRUN  |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218168859)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 06e3a49e22060525bed69bbf5d9bf7ef23579793
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5328/service-workers/service-worker/fetch-event.https.html">/service-workers/service-worker/fetch-event.https.html</a></summary>


|                                   Subtest                                    | Results |                                                                                                                                                                                                                                                   Messages                                                                                                                                                                                                                                                   |
|------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                              | OK      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with string`                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with blob body`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with the referrer URL`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with the referrer policy`            | FAIL    | `assert_unreached: unexpected rejection: assert_equals: Service Worker should respond to fetch with the referrer URL when a member of RequestInit is present expected "Referrer: https://web-platform.test:8443/service-workers/service-worker/resources/simple.html?referrerPolicy\nReferrerPolicy: no-referrer-when-downgrade" but got "Referrer: https://web-platform.test:8443/service-workers/service-worker/resources/undefined\nReferrerPolicy: no-referrer-when-downgrade" Reached unreachable code` |
| `Service Worker responds to fetch event with an existing client id`          | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker does not respond to fetch event`                             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with null response body`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker fetches other file in fetch event`                           | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with POST form`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Multiple calls of respondWith must throw InvalidStateErrors`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker event.respondWith must set the used flag`                    | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker should expose FetchEvent URL fragments.`                     | FAIL    | `assert_unreached: unexpected rejection: assert_equals: Service worker should expose URL fragments in request. expected "Fragment Found :#/some/fragment" but got "Fragment Not Found" Reached unreachable code`                                                                                                                                                                                                                                                                                             |
| `Service Worker responds to fetch event with the correct cache types`        | FAIL    | `assert_unreached: unexpected rejection: assert_equals: expected "default" but got "" Reached unreachable code`                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker should intercept EventSource`                                | FAIL    | `assert_unreached: unexpected rejection: assert_equals: EventSource should bypass the http cache. expected (string) "no-store" but got (undefined) undefined Reached unreachable code`                                                                                                                                                                                                                                                                                                                       |
| `Service Worker responds to fetch event with the correct integrity_metadata` | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5328/service-workers/service-worker/navigation-preload/redirect.https.html">/service-workers/service-worker/navigation-preload/redirect.https.html</a></summary>


|                            Subtest                            | Results |     Messages     |
|---------------------------------------------------------------|---------|------------------|
|                                                               | TIMEOUT |                  |
| `Navigation Preload redirect response.`                       | TIMEOUT | `Test timed out` |
| `Navigation Preload no-location redirect response.`           | NOTRUN  |                  |
| `Navigation Preload no-location redirect response with body.` | NOTRUN  |                  |
| `Navigation Preload redirect to the same scope.`              | NOTRUN  |                  |

</details>
</details>

**Comment by foolip** [comment]
What's going on with reviewable? Looks like if nobody cares about it, it stays yellow/golden, which is also reflected in a list view of PRs. That's annoying, I want PRs that are ready to be merged to be green at a glance.

**Pull request merged**
