### PR TITLE
Revert "Implement HTMLMenuItemElement.label (#6608)"

### PR DESCRIPTION
**Pull request by jeffcarp**
This reverts commit f1aca770c16c252414b6ef34154dc7b09846df96.

Reason: that commit was originally skipped by the exporter earlier
this year but a fix to patch the gap was made recently. However,
@GPHemsley reported that this test is no longer applicable, so reverting.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258171581)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258171582)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258171588)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258171589)

# Sauce (MicrosoftEdge) #

**Comment by GPHemsley** [comment]
This looks fine to me.

@domenic Do you have anything to add here?

**Review by GPHemsley — APPROVED** [review]

**Comment by GPHemsley** [comment]
This file had previously removed as part of #6167.

**Review by foolip — APPROVED** [review]

**Pull request merged**
