### PR TITLE
Split Selection API tests out of dom/ranges/Range-mutations.html

### PR DESCRIPTION
**Pull request by cdumez**
Move the Selection API tests to selection/Range-mutations.html instead as
they are not part of DOM.

This closes issue #3444.

### CODE REVIEW

**Comment by cdumez** [comment]
@annevk @rniwa @Ms2ger Is this better? I tried to duplicate code as little as possible.

**Comment by Ms2ger** [comment]
Looks a lot better, thank you! I'll try to find time to review carefully.

**Comment by cdumez** [comment]
Ok, I'll rework the patch then.

**Comment by cdumez** [comment]
Superseded by https://github.com/w3c/web-platform-tests/pull/3468

**Pull request closed without merging**
