### PR TITLE
Upstream animation-ready-promise.html from Blink

### PR DESCRIPTION
**Pull request by suzyh**
Import
https://chromium.googlesource.com/chromium/src/+/f8f67bb5d779485ad13daa1ee42268a2e90642b7/third_party/WebKit/LayoutTests/web-animations-api/animation-ready-promise.html

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/3330)

### CODE REVIEW

**Comment by birtles** [comment]
The format of these tests looks great. However, I think this is testing from the wrong angle. I think it's better if we approach this by writing tests for each procedure in the timing model, and, for each one that is supposed to touch the ready promise, test it there. I think that's the direction we want to go moving forwards and it's the easiest way to make sure we're giving the spec full coverage without adding redundant tests. What do you think?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/3330/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218771945)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fc6af47715796891529597ae68d728d616389cba
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/3330/web-animations/interfaces/Animation/ready.html">/web-animations/interfaces/Animation/ready.html</a></summary>


|                                                  Subtest                                                   | Results |                               Messages                              |
|------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------|
|                                                                                                            | OK      |                                                                     |
| `A new ready promise is created when play()/pause() is called`                                             | PASS    |                                                                     |
| `Redundant calls to play() do not generate new ready promise objects`                                      | PASS    |                                                                     |
| `The ready promise is fulfilled with its Animation`                                                        | PASS    |                                                                     |
| `ready promise is rejected when a play-pending animation is canceled by calling cancel()`                  | PASS    |                                                                     |
| `ready promise is rejected when a pause-pending animation is canceled by calling cancel()`                 | PASS    |                                                                     |
| `The ready attribute should be a Promise`                                                                  | PASS    |                                                                     |
| `The ready promise should be resolved when an animation is in the idle play state`                         | PASS    |                                                                     |
| `The ready promise should be replaced when the animation is canceled`                                      | FAIL    | `assert_not_equals: got disallowed value object "[object Promise]"` |
| `The ready promise should be replaced when the animation enters the pending state`                         | PASS    |                                                                     |
| `A pending ready promise should be rejected when the animation is canceled`                                | PASS    |                                                                     |
| `A pending ready promise should be resolved and not replaced when the animation enters the running state`  | PASS    |                                                                     |
| `A pending ready promise should be resolved and not replaced when the animation enters the finished state` | PASS    |                                                                     |
| `A pending ready promise should be resolved and not replaced when the animation enters the paused state`   | PASS    |                                                                     |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218771946)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fc6af47715796891529597ae68d728d616389cba
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations

**Pull request merged**
