### PR TITLE
Created border-image-width-009.html test and its reference

### PR DESCRIPTION
**Pull request by TalbotG**
This is a followup of
https://github.com/web-platform-tests/wpt/pull/23627

border-image-width-009.html

reference/border-image-width-009-ref.html

Here are the review comments over in PR23627:

{

fantasai: Please combine these into a single file and refactor the code so that it is easy to see which part is common and which part is the variation.

fantasai: You are referencing this bug, but the test is not testing this scenario because you explicitly set the border-width to zero.

GT: I have removed the reference to such www-style/2015Nov/0258.html message but I have made the new border-image-width-009.html meta-test
to specifically check such scenario (a missing border-style inside a border shorthand declaration).

fantasai: These three [longhand border] declarations should be collapsed using the shorthand. There's no need to expand it here.

GT: The border shorthand I have used in the new border-image-width-009.html meta-test is
`border: red 100px`
deliberately leaving out `border-style` so that it must use the default `border-style` which is `none`.

}

The 3 review comments about the incorrect dimensions of the center (fill) areas have been corrected accordingly.

On my website, this meta-test and its reference are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-width-009-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-width-009-ref-new.html

### CODE REVIEW

**Comment by fantasai** [comment]
So, I think this test is *correct*. My concern is there seem to be many ways the UA can do the wrong thing, but still get a green box. I wonder if it wouldn't be better to use an image like this?

outline-5px-10px-15px-20px-green

**Comment by fantasai** [comment]
I guess I'm not entirely sure what your goals are for this test. Another adjustment that could be made would be making the center part show through, so at least you know where the edges of each border image edge actually is.

**Comment by TalbotG** [comment]
After quite a lot of time, I come up with

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-width-009-final.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-width-009-ref-final.html

which covers 3 code scenarios, not 4 as originally intended. I think this should suffice.
I will try to submit a PR and replace the previous files and add new images in a few min.

**Comment by TalbotG** [comment]
I will work again on that test as I am not happy with using images for the reference. Most likely, the reference will have to use border-image too.

**Comment by TalbotG** [comment]
I will work again on that test as I am not happy with using images for the reference. Most likely, the reference will have to use border-image too.

**Comment by TalbotG** [comment]
The latest test is now:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-width-009-final2.html

and latest reference file is:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-width-009-ref-final2.html

**Comment by TalbotG** [comment]
I have decided to replace 
line 53: border-image-width: 70% 30%;
with
line 53: border-image-width: 50% 30%;
to avoid complications (negative height) about the computed size (width and height) of the center (fill area). So, another PR coming up soon...

**Comment by TalbotG** [comment]
So again..
the latest test is now:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-width-009-final3.html

and latest reference file is:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-width-009-ref-final3.html

**Review by fantasai — APPROVED** [review]

**Pull request merged**
