### PR TITLE
[html] Merge html/user-interaction/ to html/editing/.

### PR DESCRIPTION
**Pull request by tkent-google**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17889)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/269841628)

**Review by TakayoshiKochi — APPROVED** [review]
I think originally this was intended to map the HTML spec "user interaction" section to its own directory - so ideally if we want to map the structure of the HTML spec to web platform tests directory hierarchy, moving top-level "editing" under "user-interaction" directory should make more sense.

But considering the current directory situation, this would not make things worse.

LGTM.

**Comment by tkent-google** [comment]
Thank you for the review.

I think 'editing' came from a section URL of W3C HTML.  https://www.w3.org/TR/html5/editing.html#editing

**Comment by TakayoshiKochi** [comment]
Aha, okay.  Thanks for the explanation.

**Pull request merged**
