### PR TITLE
SVG: Parsing of stop-color

### PR DESCRIPTION
**Pull request by ewilligers**
stop-color accepts `<color>` values.
https://svgwg.org/svg2-draft/pservers.html#StopColorProperty

### CODE REVIEW

**Comment by ewilligers** [comment]
@svgeesus please review

**Comment by ewilligers** [comment]
@AmeliaBR please review

**Comment by ewilligers** [comment]
@BorisChiou please review

**Review by BorisChiou — APPROVED** [review]
Looks ok to me.
It seems `<icccolor>` is pretty new so no one implements it.

**Pull request merged**
