### PR TITLE
Add tests using Request/fetch similar to the XHR ones added in #4953

### PR DESCRIPTION
**Pull request by mkruisselbrink**
As far as I can tell the Request spec has the same behavior where on creating the Request we're supposed to parse the URL and get a reference to the underlying blob, and as such this test is supposed to pass.

### CODE REVIEW

**Comment by mkruisselbrink** [comment]
@annevk does my understanding here match yours?

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19573)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/288701098)

**Review by annevk — APPROVED** [review]
Maybe also test passing the URL directly to `fetch()`? Did you file implementation bugs?

**Comment by gsnedders** [comment]
This is approved, is there any reason why it isn't merged? (Had CI not finished when it was approved?)

**Comment by annevk** [comment]
The reason I didn't merge it is because I asked questions. It's easier to get questions answered if something isn't marked as resolved.

**Comment by mkruisselbrink** [comment]
Sorry for the delay, I somehow missed the earlier approval/comments. Added a test passing url directly to fetch(). Haven't filed any implementation bugs, no, as I wasn't sure this was actually the behavior we want to specs to describe. But I think I now agree that it probably is the right behavior.

**Pull request merged**
