### PR TITLE
added two tests for window#open

### PR DESCRIPTION
**Pull request by LoonyBean**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5229/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215577850)

# Firefox (nightly channel) #
Testing web-platform-tests at revision f04c74258c149b911e2cfd124aa1d87c9773c37d
Using browser at version BuildID 20170326110231; SourceStamp f5e214144799889e2408c4841351f4053f00544e
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215577851)

# Chrome (unstable channel) #
Testing web-platform-tests at revision f04c74258c149b911e2cfd124aa1d87c9773c37d
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by LoonyBean** [comment]
PR closed as tests are written in CL (https://codereview.chromium.org/2755773002/) instead.

**Pull request closed without merging**
