### PR TITLE
Updating Server creation for localhost

### PR DESCRIPTION
**Pull request by thejohnjansen**
In my last change, I missed this line of code. Adding the host parameter and removing the base_path param.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9202)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-26 01:07:55
Finished: 2018-01-26 01:22:41





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23318)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/333538526)

**Comment by jgraham** [comment]
Why does this have to be `localhost` not `127.0.0.1`?

**Comment by thejohnjansen** [comment]
@jgraham : I should have included it in my initial PR. It's because of a feature missing in our webdriver. Same thing goes for IEDriver, which is why that one matches the Edge code. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3901350/

**Comment by thejohnjansen** [comment]
@gsnedders  and @jgraham Anything else to do here? I keep having to send this url to people who are trying to run these tests... :-)

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
@thejohnjansen I was waiting for @jgraham given he has more of an idea about this. :)

**Pull request merged**
