### PR TITLE
[css-ruby] Created basic test on rbc and rtc elements

### PR DESCRIPTION
**Pull request by TalbotG**
On my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/rbc-rtc-basic-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/rbc-rtc-basic-001-ref.html

### CODE REVIEW

**Comment by TalbotG** [comment]
Since this test should use only 1 line box, then there is no need or no specific purpose for `line-height: 3`. 

I will be (or am) working on renewing the test entirely...

**Review by upsuper — APPROVED** [review]
Looks reasonable to me. I would be surprised if there aren't any existing tests covering this, though.

**Comment by TalbotG** [comment]
I have not yet commited version 2.

Indeed, there are existing tests covering this but 
- they are not simple, basic tests and/or
- the reference files are not able (reliable enough) to report test failures in Chromium 94 (and lower; Safari 14 and lower). And so the reference files contribute to false positive test results.

**Comment by TalbotG** [comment]
Okay. I have committed version 2 into the 34d7340 commit. The 19 Continuous Integration checks passed. And now I can see the Squash and merge green button. @upsuper Xidorn, do you need or want to review this... or should I/can I just push that Squash and merge green button ?

**Comment by TalbotG** [comment]
Since you approved 28 days ago version 2, I do not see why you would need to review 34d7340 commit again. So here goes..

**Comment by TalbotG** [comment]
I do not see the test and reference in
https://wpt.fyi/results/css/css-ruby?label=master

Something did not succeed ...

**Comment by TalbotG** [comment]
There was indeed something wrong. The test does not have, is missing
`<link rel="match" href="reference/rbc-rtc-basic-001-ref.html">`

I will create a new PR in a few min.

**Pull request merged**
