### PR TITLE
Add @TimothyGu to url/OWNERS

### PR DESCRIPTION
**Pull request by TimothyGu**

### CODE REVIEW

**Review by domenic — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254683122)

# Firefox (nightly) #
Testing web-platform-tests at revision b9c7b86111a5b4ed1cd9e9a9af92f180a0209091
Using browser at version BuildID 20170717100212; SourceStamp aff336ac161daa3ea350e59a288963edbd58ed39
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254683123)

# Sauce (safari) #
Testing web-platform-tests at revision b9c7b86111a5b4ed1cd9e9a9af92f180a0209091
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254683129)

# Chrome (unstable) #
Testing web-platform-tests at revision b9c7b86111a5b4ed1cd9e9a9af92f180a0209091

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254683130)

# Sauce (MicrosoftEdge) #

**Pull request merged**
