### PR TITLE
Update the encrypted-media IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The Spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-08 01:36:29
Finished: 2018-03-08 01:46:40





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25509)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350509859)

**Comment by lukebjerring** [comment]
So, while I can't vouch for the changes in the IDL, the tests are passing 107/107, so... seems legit. @foolip - who'd be best to eyeball the update?

**Review by foolip — APPROVED** [review]
Looks good to my eyeballs.

**Comment by jrummell-chromium** [comment]
The only real difference I see is the old IDL had MediaKeySessionType::persistent-usage-record, which is no longer in the spec. So no problems with the change.

However, there are several current tests that use "persistent-usage-record". It looks like that is coming back into the next version of the spec, so the tests might as well remain.

**Pull request merged**
