### PR TITLE
Move non-test HTML files to support/.

### PR DESCRIPTION
**Pull request by tkent-google**

### CODE REVIEW

**Comment by tkent-google** [comment]
Similar to PR#1918, this change will help Chromium project to automate web-platform-tests.

**Comment by jgraham** [comment]
So… I'm really not excited about making this a requirement for all tests. Having too many arbitrary requirements just increases the bar for test authors. Isn't there some other way we can solve whatever the issue with the Google test infrastructure is? There's a manifest file that tells you exactly which files are tests and therefore, by omission, which are support files. Can we plug that in to your harness?

**Comment by tkent-google** [comment]
It's ok to reject this PR if you think enforcing support/  on test authors is not reasonable.  The motivation of this PR is Chromium-specific.  There are some other ways to solve the issue, and I wanted to try the cheapest solution first :)

**Comment by Ms2ger** [comment]
I'm with jgraham, let's not do this.

**Pull request closed without merging**
