### PR TITLE
Add tests for content-dpr, separate from client-hints

### PR DESCRIPTION
**Pull request by noamr**
Using simple ref-tests to assert that the browser renders natural-size correctly for content-dpr images.

### CODE REVIEW

**Comment by noamr** [comment]
@yoava333 can you review?

**Comment by noamr** [comment]
@yoavweiss can you review please? :)

**Comment by noamr** [comment]
> @yoavweiss can you review please? :)

Or @igrigorik @tarunban ?

**Comment by yoavweiss** [comment]
Thanks for working on those tests!

Maybe it would be possible to trim down the number of files this spans?

e.g. Could you create a single test HTML that loads all these images, and a single ref HTML that shows you how they are supposed to be displayed?

For the images, maybe you can reuse [dpr.py](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/client-hints/resources/dpr.py?q=Content-DPR&sq=package:chromium&dr=C&l=1)?

Otherwise, when searching the above, I stumbled on [image-with-dpr-header.html](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/client-hints/image-with-dpr-header.html?q=dpr.py&sq=package:chromium&dr=C). Maybe you can add whatever test cases this has on top of that test to it directly, and move it to its own directory? (as it should be decoupled from client-hints)

**Comment by noamr** [comment]
> Thanks for working on those tests!
> 
> Maybe it would be possible to trim down the number of files this spans?
> e.g. Could you create a single test HTML that loads all these images, and a single ref HTML that shows you how they are supposed to be displayed?

I tried to follow the wpt guidelines to keep the tests concise to the specific thing they're testing... should I be following a different guideline?
Is that really preferred? I tried to go by the guidelines of keeping tests atomic-ish.

> For the images, maybe you can reuse [dpr.py]
I preferred to keep the headers very straightforward with the .png.header file, that python file doesn't do anything special... is that for avoiding code duplication?

> Otherwise, when searching the above, I stumbled on [image-with-dpr-header.html](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/client-hints/image-with-dpr-header.html?q=dpr.py&sq=package:chromium&dr=C). Maybe you can add whatever test cases this has on top of that test to it directly, and move it to its own directory? (as it should be decoupled from client-hints)
I will anyway move it to content-dpr directory.

Thanks!

**Comment by noamr** [comment]
@yoavweiss you're right,
 I consolidated rendering to one test, since a lot of the cases are already covered by image-with-dpr-header.

**Review by yoavweiss — APPROVED** [review]
LGTM

Please avoid adding another binary and just use `dpr.py?name=square.png&mimeType=image/png&dpr=4.0`

**Comment by noamr** [comment]
@yoavweiss can you merge as well? Thx!

**Pull request merged**
