### PR TITLE
Fix tests for clamping to 0 with keyframes with calc() values

### PR DESCRIPTION
**Pull request by graouts**
Addresses issue #37053.

### CODE REVIEW

**Comment by flackr** [comment]
Long term I would like to see chrome's behavior spec'd since i think it supports more use cases, but I can see this is what the spec currently says to do, so it seems reasonable to test.

Can you also add tests showing the expectations for an animation of both relative size affecting property (e.g. font-size or height) and a clamped property depending on that property?

**Comment by flackr** [comment]
+@kevers-google FYI

**Comment by graouts** [comment]
> Long term I would like to see chrome's behavior spec'd since i think it supports more use cases, but I can see this is what the spec currently says to do, so it seems reasonable to test.

Yes, this may make sense, I agree. But at it stands better to have the tests reflect the specs than wait for the specs to catch up.

> Can you also add tests showing the expectations for an animation of both relative size affecting property (e.g. font-size or height) and a clamped property depending on that property?

I'm sorry but I don't get what you mean. Can you write an example? I'm happy to then expand it to the various tests.

**Review by birtles — APPROVED** [review]

**Comment by graouts** [comment]
I'm merging now because there is a clear scope and @birtles reviewed, but when @flackr gets back to me to help me understand his request, I'll make sure to make a followup pull request.

**Comment by flackr** [comment]
> I'm sorry but I don't get what you mean. Can you write an example? I'm happy to then expand it to the various tests.

In particular, I was thinking we should have testing for the interpolation of some cases like these:
```js
element.animate([{minHeight: '30px', fontSize: '10px'}, {minHeight: 'calc(30px - 2em)', fontSize: '40px'}], 1000);
```

Or
```js
element.animate([{minHeight: '30px'}, {minHeight: 'calc(30px - 2em)'}], 1000);
element.animate([{fontSize: '10px'}, {fontSize: '40px'}], 1000);
// Or ancestor.animate(...)
```

Or
```js
window.CSS.registerProperty({
  name: '--min-height',
  syntax: '<length>',
  inherits: false,
  initialValue: '0px',
});
element.style.minHeight = 'var(--min-height)';
element.style.fontSize = '40px';
element.animate([{'--min-height': '30px'}, {'--min-height': 'calc(30px - 2em)'}], 1000);
```

**Pull request merged**
