### PR TITLE
 Convert Microsoft's selection tests to testharness.js

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19206)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/283740436)

**Comment by foolip** [comment]
@patrickkettner, might I trouble you to find a reviewer for this? The tests as they were don't even run, so this should at any rate be an improvement.

**Review by Ms2ger — APPROVED** [review]

**Comment by jgraham** [comment]
Looks like /old-tests/submission/Microsoft/selection/insertNodeIntoSelection.htm fails on Windows (everyone loves irony right?) since it assumes that the line terminator is `\n` rather than `\r\n`.

**Comment by foolip** [comment]
@jgraham, how did you notice?

Looks like results are now at https://wpt.fyi/results/old-tests/submission/Microsoft/selection and these tests do reveal a lack of interop, although the "0 / 1" for Edge are actually timeouts and more likely to be runner infra bugs than anything else, as at least the first passes for me locally. Poked https://github.com/web-platform-tests/results-collection/issues/563 about that.

**Comment by jgraham** [comment]
I noticed because for some reason the gecko sync failed to correctly set the expectation to FAIL on Windows and I had to do a manual fixup. When doing that I saw the error message which suggested a problem with line endings.

**Comment by foolip** [comment]
Failures are in https://bugzilla.mozilla.org/show_bug.cgi?id=1481213 for future investigation.

**Pull request merged**
