### PR TITLE
Add interfaces/hit-test.idl and test

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Due to the difficulty in testing webxr until test-only APIs are
supported in WPT (see
https://github.com/web-platform-tests/wpt/issues/16455#issuecomment-532040838),
the added test only tests the XRSession interface additions for now.

Closes https://github.com/web-platform-tests/wpt/pull/22155

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
It seems like the webxr folks have been naming their specs `foo-bar` without a `webxr` prefix, but placing them inside `webxr/foo-bar` instead. So this likely should be moved, but wanted to see how it ran on TaskCluster first.

Similar to https://github.com/web-platform-tests/wpt/pull/22851 I could find no way to easily get an XRFrame today, so most of these are still `TODOs` until then. Also, I couldn't create a XRTransientInputHitTestSource because the XRSession method to create it failed when I tried (error was approximately 'hit-test not supported on this platform').

One thing I'm not sure about; I'm getting one error with `Float32Array` undefined, but can't find an IDL file where it would be - isn't that just part of base IDL?

**Review by foolip — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
... uh, as I said above, we likely want to move this (which I can do in a follow up).

Also, do you happen to know anything about the `Float32Array` problem I ran into?

> One thing I'm not sure about; I'm getting one error with Float32Array undefined, but can't find an IDL file where it would be - isn't that just part of base IDL?

**Comment by foolip** [comment]
Sorry, I scrolled right past comments and merged :-/

The `Float32Array` and similar IDL types are defined in https://heycam.github.io/webidl/#idl-buffer-source-types while https://tc39.es/ecma262/#sec-typedarray-objects defines the corresponding (underlying) ES bits.

Knowledge of these types is baked into idlharness.js:
https://github.com/web-platform-tests/wpt/blob/603ea91ccada76c2796bc51d1cf027882582cd83/resources/idlharness.js#L681

If there's an error because `Float32Array` isn't defined, then we have an idlharness bug.

**Comment by Manishearth** [comment]
> It seems like the webxr folks have been naming their specs `foo-bar` without a `webxr` prefix, but placing them inside `webxr/foo-bar` instead. So this likely should be moved, but wanted to see how it ran on TaskCluster first.

@stephenmcgruer The repo is named hit-test but the [spec is still named webxr-hit-test](https://github.com/immersive-web/hit-test/blob/09bf18a44912d1ae809ec4acc9b1c9435a4d694c/index.bs#L2). It's a bug if the tooling is still detecting the name as hit-test.

This should be a subfolder.

> Due to the difficulty in testing webxr until test-only APIs are supported in WPT

I don't understand what you mean by this, the test-only APIs are working fine for us (Servo)? The chrome-only stuff ideally should not exist, but it just gets ignored if the browser implements the test API.

We already have tests under `webxr/hit-test`

**Comment by stephenmcgruer** [comment]
Thanks for the info @Manishearth !

> @stephenmcgruer The repo is named hit-test but the spec is still named webxr-hit-test. It's a bug if the tooling is still detecting the name as hit-test.

@foolip - should reffy be reading the spec-name rather than the repo name? (Which is what I assume it uses atm?)

> I don't understand what you mean by this, the test-only APIs are working fine for us (Servo)? The chrome-only stuff ideally should not exist, but it just gets ignored if the browser implements the test API.

Sorry, probably being lose with terminology, or I have an incorrect understanding. My understanding is that currently the webxr tests generally only work in the downstream repositories, and are not available to people running `wpt run ...` using the normal WPT infrastructure? I could be wrong, but basing this on https://wpt.fyi/results/webxr?label=experimental&label=master&aligned having mostly test failures.

**Comment by Manishearth** [comment]
I don't know much about wpt run. In the case of Chrome, yes, you need some build-time generated stuff to run these tests (cc @alcooper91). 

In the case of Servo, you just need to enable the appropriate flags for getting the test API. I believe Firefox is working on an implementation of the test API and would be in a similar situation.

So the linked issue only matters for Chrome, all the other browsers just don't have the test API implemented right now. Servo does, but Servo isn't on that list :smile:

**Comment by Manishearth** [comment]
@stephenmcgruer So [it seems like Servo shows up red as well](https://wpt.fyi/results/webxr?label=master&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=servo&aligned) -- what do I need to do to get the appropriate preferences enabled for this subfolder for Servo?

**Comment by stephenmcgruer** [comment]
> In the case of Servo, you just need to enable the appropriate flags for getting the test API. I believe Firefox is working on an implementation of the test API and would be in a similar situation.

I see, thanks for clarifying! That's actually great, it should mean I can download servo locally and use it when working on tests like these (that's the major blocking factor - it was really hard to write tests when both Chrome and Firefox could never pass).

> @stephenmcgruer So it seems like Servo shows up red as well -- what do I need to do to get the appropriate preferences enabled for this subfolder for Servo?

I would defer that question to @jgraham, who I believe did most of the WPT executor work for Servo (based on `git log tools/wptrunner/wptrunner/browsers/servo.py`)

**Comment by Manishearth** [comment]
In this case _ideally_ we'd like `dom.webxr.enabled` and `dom.webxr.test` to only be enabled for `webxr/`, and I don't see an easy way to do that.

**Comment by jgraham** [comment]
Yeah, in an ideal world we could mirror per-directory prefs from vendor infra to GitHub runs. There isn't any mechanism to do that at the moment; we'd have to either enable those prefs always or hardcode something in the runner, or start manually adding prefs-only metadata files to this repo.

**Comment by alcooper91** [comment]
> I don't know much about wpt run. In the case of Chrome, yes, you need some build-time generated stuff to run these tests 
IIRC @foolip or @Hexcles was working on this, but I don't remember where the work was tracked/what the status was

**Comment by Manishearth** [comment]
@jgraham I'm okay with manually adding per directory prefs we care about for servo. Is there an easy way to do this?

**Pull request merged**
