### PR TITLE
Add Comments

### PR DESCRIPTION
**Pull request by nexuspcs**
I have added a few small changes to these files in order to provide clarity and some understanding of specific lines.
_*I am a new contributor on GitHub, please be easy on me*_

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks for your contribution and welcome to w-p-t. I reviewed the `html-media-capture` bits.

**Comment by nexuspcs** [comment]
Thankyou!

**Review by domenic — COMMENTED** [review]
I do not think this is a helpful change to the project. If you'd like to contribute, please look at existing issues. This change was not requested.

**Comment by anssiko** [comment]
@nexuspcs for your reference, some of the issues with a label https://github.com/web-platform-tests/wpt/labels/good%20first%20issue may be a good start. The documentation is at https://web-platform-tests.org/

**Pull request closed without merging**
