### PR TITLE
Update html/semantics/embedded-content/the-img-element/usemap-casing.…

### PR DESCRIPTION
**Pull request by cdumez**
…html to fit in 800x600 viewport

Without this change, the last 4 checks fail if the viewport has 800x600 dimension.

### CODE REVIEW

**Comment by cdumez** [comment]
@domenic

**Comment by cdumez** [comment]
Found via https://bugs.webkit.org/show_bug.cgi?id=178053.

**Comment by cdumez** [comment]
The test relies on document.elementFromPoint() API which returns null when the coordinates are outside the viewport.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19279)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/285747768)

**Comment by gsnedders** [comment]
see also #7642

**Review by domenic — APPROVED** [review]
Thanks for fixing up my mistake. I'm not sure exactly how to avoid this in the future for other contributors, besides maybe sticking a sentence in the docs and hoping people stumble across it before writing such tests. I guess @gsnedders is on the case though.

**Pull request merged**
