### PR TITLE
Add tests for script.callFunction for serialization of complex objects with simple value field.

### PR DESCRIPTION
**Pull request by lutien**
Add tests for script.callFunction for serialization of complex objects with simple value field (objects which don't require strong reference)

### CODE REVIEW

**Comment by sadym-chromium** [comment]
Maybe use the same expectations as in https://github.com/web-platform-tests/wpt/pull/34770?

**Comment by lutien** [comment]
@sadym-chromium, makes sense!
I've extended parameters with values from your PR.

**Review by sadym-chromium — APPROVED** [review]

**Comment by sadym-chromium** [comment]
Nice work, thanks!

**Review by juliandescottes — APPROVED** [review]
lgtm! Thanks @lutien

**Comment by lutien** [comment]
@sadym-chromium, I think you could start working on deserialization tests, we don't plan working on them in the next couple of weeks.

**Pull request merged**
