### PR TITLE
use context manager instead of prerun script

### LINKED ISSUE #255: Use Context Managers in browser environments instead of keeping track of the prerun script process
From @jgraham:

> _wptrunner/environment.py, line 99 at r1 (raw file):_
>
> ```
>             self.cache_manager = multiprocessing.Manager()
>             self.stash = serve.stash.StashServer()
>             self.prerun_process = prerun()
> ```
>
>So this is pretty nitpicky, but I think this has become over-specialized. I wonder if we could make this a list of context managers called e.g. env_extras or something and then in __enter__ have code like
>
> ```
> for cm in self.env_extras:
>     cm.__enter__()
> ```
> 
> and similarly in `__exit__`.

### PR DESCRIPTION
**Pull request by bobholt**
This addresses feedback on https://github.com/w3c/wptrunner/pull/253 that was merged without this enhancement (fixes https://github.com/w3c/wptrunner/issues/255)

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5771)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5771/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228389830)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 51e4c93434dd945ca0a651bf9b58d8d4952965d6
Using browser at version BuildID 20170502100421; SourceStamp 48c0fd9c9ec5d68061ea7b59358874ae8da72572
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228389836)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 51e4c93434dd945ca0a651bf9b58d8d4952965d6

**Comment by jgraham** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/wptrunner/environment.py, line 99 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2kAMwZ1MCr0_edvL:-KjF2kAMwZ1MCr0_edvM:bgga3pa) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/environment.py#L99)):*
> ```Python
> 
>     def __enter__(self):
>         for cm in self.env_extras:
> ```

I might put these last in the list, in case they depend on any other state. Clearly other state should not depend on these things.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 139 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2XKggMVMy3R3A-d-:-KjF2XKhKrPY85l5-8PI:b-5kedhk) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/browsers/sauce.py#L139)):*
> ```Python
>         self.sauce_connect_binary = kwargs.get("sauce_connect_binary")
> 
>         if not self.sauce_connect_binary:
> ```

I think this shoud go in `__enter__` since it allocates resources.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2dYWvZELhGVUm0D6:-KjF2dYWvZELhGVUm0D7:byqc3t4) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/browsers/sauce.py#L167)):*
> ```Python
> 
>     def __exit__(self, *args):
>         self.sc_process.terminate()
> ```

Also delete the tempdir, if any.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by bobholt** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[tools/wptrunner/wptrunner/environment.py, line 99 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2kAMwZ1MCr0_edvL:-KjII_p69rTTW4jLZQg6:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/environment.py#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I might put these last in the list, in case they depend on any other state. Clearly other state should not depend on these things.
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 139 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2XKggMVMy3R3A-d-:-KjIIbR5XH0q7rLMVwC3:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/browsers/sauce.py#L139)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I think this shoud go in `__enter__` since it allocates resources.
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjF2dYWvZELhGVUm0D6:-KjIIcuS5gDYPLmUpfdV:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd58b81d82ac63d963c38f05827deb68b236cead/tools/wptrunner/wptrunner/browsers/sauce.py#L167)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Also delete the tempdir, if any.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 169 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjITF5gLqXtAFay_1PK:-KjITF5gLqXtAFay_1PL:b-p1nl73) ([raw file](https://github.com/w3c/web-platform-tests/blob/6ecdaa1c05a81233bdf08aabc935f9f51c61100b/tools/wptrunner/wptrunner/browsers/sauce.py#L169)):*
> ```Python
>         self.sc_process.terminate()
>         try:
>             os.remove(glob.glob(os.path.join(temp_path, "sc-*-linux")))
> ```

`temp_path` seems to be undefined here always. Using `try/except` isn't great; it's better to check if the dir was actually created and then try to delete it (with `try/except` just catching the `OSError` for the directory not exisitng anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by bobholt** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 169 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjITF5gLqXtAFay_1PK:-KjIUWGTxb2_cIV_9j9X:b-mff07n) ([raw file](https://github.com/w3c/web-platform-tests/blob/6ecdaa1c05a81233bdf08aabc935f9f51c61100b/tools/wptrunner/wptrunner/browsers/sauce.py#L169)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

`temp_path` seems to be undefined here always. Using `try/except` isn't great; it's better to check if the dir was actually created and then try to delete it (with `try/except` just catching the `OSError` for the directory not exisitng anymore.
</blockquote></details>

Done. Ah yeah, I forgot to replace that name with `tempfile.gettempdir()`, and of course ignoring all errors didn't cause it to break my build. Consider my wrist slapped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by jgraham** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 169 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjITF5gLqXtAFay_1PK:-KjNTGXPb7HO2yxjsCHQ:b-auxjk2) ([raw file](https://github.com/w3c/web-platform-tests/blob/6ecdaa1c05a81233bdf08aabc935f9f51c61100b/tools/wptrunner/wptrunner/browsers/sauce.py#L169)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

Done. Ah yeah, I forgot to replace that name with `tempfile.gettempdir()`, and of course ignoring all errors didn't cause it to break my build. Consider my wrist slapped.
</blockquote></details>

I'm nervous about using a glob here. I would prefer that we store the actual name of the directory we create higher up and ensure that we only delete that directory. One way to do that better might be to use `tmpfile.mkdirtemp` to create a new temporary directory and then delete that rather than trying to glob inside `/tmp` which can conflict with files created by any random process.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by bobholt** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 169 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjITF5gLqXtAFay_1PK:-KjNdPkV2JwI5Hj8G2On:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/6ecdaa1c05a81233bdf08aabc935f9f51c61100b/tools/wptrunner/wptrunner/browsers/sauce.py#L169)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I'm nervous about using a glob here. I would prefer that we store the actual name of the directory we create higher up and ensure that we only delete that directory. One way to do that better might be to use `tmpfile.mkdirtemp` to create a new temporary directory and then delete that rather than trying to glob inside `/tmp` which can conflict with files created by any random process.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 171 at r4](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjNe0ZRep6RmCoz6j7I:-KjNe0ZRep6RmCoz6j7J:b-f5o1az) ([raw file](https://github.com/w3c/web-platform-tests/blob/fd8e4b873d66fc3c18c294260abe94185907dd5a/tools/wptrunner/wptrunner/browsers/sauce.py#L171)):*
> ```Python
>         if os.path.exists(self.temp_dir):
>             try:
>                 os.remove(self.temp_dir)
> ```

I think you need `shutil.rmtree`. Apologies for not noticing earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by bobholt** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/wptrunner/wptrunner/browsers/sauce.py, line 171 at r4](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771#-KjNe0ZRep6RmCoz6j7I:-KjNniRiNEKlAULVtk5M:b-gpok4c) ([raw file](https://github.com/w3c/web-platform-tests/blob/fd8e4b873d66fc3c18c294260abe94185907dd5a/tools/wptrunner/wptrunner/browsers/sauce.py#L171)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I think you need `shutil.rmtree`. Apologies for not noticing earlier.
</blockquote></details>

Done. No apologies necessary. I think I noticed that at one point, forgot, and since we're ignoring OSErrors, it didn't pose a build issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5771)*

**Pull request merged**
