### PR TITLE
Web NFC: Update OWNERS

### PR DESCRIPTION
**Pull request by Honry**
add @kenchris and @zolkis as OWNERS

### CODE REVIEW

**Comment by Honry** [comment]
@kenchris, @zolkis, could you please take a look? Hope you would like to be the OWNER.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240206785)

# Firefox (nightly) #
Testing web-platform-tests at revision 634c8ebe86bd126495809be352d22700f7cb4a1b
Using browser at version BuildID 20170606100219; SourceStamp 58ce95bc58ce4ba200413c8bed87786dccf3d105
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240206786)

# Sauce (safari) #
Testing web-platform-tests at revision 634c8ebe86bd126495809be352d22700f7cb4a1b
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240206792)

# Chrome (unstable) #
Testing web-platform-tests at revision 634c8ebe86bd126495809be352d22700f7cb4a1b
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240206793)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 634c8ebe86bd126495809be352d22700f7cb4a1b
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by kenchris** [comment]
We want to add Alexander as well

**Comment by Honry** [comment]
@kenchris, we have Alexander now.

**Comment by Honry** [comment]
@haoxli, could you help review and approve this PR? As I can't find @kenchris and @zolkis in the reviewers list, need another one to approve this PR.

**Review by haoxli — APPROVED** [review]
+1

**Review by haoxli — COMMENTED** [review]
@Honry sorry, I have no write permission.

**Comment by Honry** [comment]
@dontcallmedom, could you help approve this PR? We need a reviewer with write access.

**Review by tobie — APPROVED** [review]

**Comment by Honry** [comment]
Thanks @tobie, I will merge it directly.

**Pull request merged**
