### PR TITLE
XMLHttpRequest: loadstart and state

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/xhr/issues/101.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204592832)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fa6e0e3ab584a00b76b3817e7a13c0af128a36c7
Using browser at version BuildID 20170222110216; SourceStamp 9a9db410f20781076424307265decbc5de1e94cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4996/XMLHttpRequest/loadstart-and-state.html">/XMLHttpRequest/loadstart-and-state.html</a></summary>


|          Subtest           | Results |
|----------------------------|---------|
|                            | OK      |
| `open() during loadstart`  | PASS    |
| `abort() during loadstart` | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204592833)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fa6e0e3ab584a00b76b3817e7a13c0af128a36c7
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4996/XMLHttpRequest/loadstart-and-state.html">/XMLHttpRequest/loadstart-and-state.html</a></summary>


|          Subtest           | Results |
|----------------------------|---------|
|                            | OK      |
| `open() during loadstart`  | PASS    |
| `abort() during loadstart` | PASS    |

</details>
</details>

**Comment by annevk** [comment]
@sof interested in reviewing this?

**Review by sof — APPROVED** [review]
lgtm, covers the two kinds of side-effecting operations that should cause a bailout upon return from the 'loadstart' dispatch. i.e., appears complete.

**Pull request merged**
