### PR TITLE
webrtc/dictionary-helper.js: fix assertion function

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258183379)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258183380)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258183387)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/258183391)

# Sauce (MicrosoftEdge) #

**Review by bobholt — APPROVED** [review]

**Comment by rwaldron** [comment]
@bobholt any ideas about that travis failure? https://travis-ci.org/w3c/web-platform-tests/jobs/258186303#L1035

**Comment by bobholt** [comment]
@rwaldron This may be related to a change @jgraham just landed. Those files got changed yesterday and today. I just pinged him on IRC.

**Comment by jgraham** [comment]
I'm not sure what's going on with the metadata path not existing thing. If you  rebase on master that job shouldn't run at all :) Maybe I need to `mkdir` somewhere to ensure that path exists.

I restarted the chrome job; I'm happy to merge in spite of the failed test_wpt job.

**Comment by rwaldron** [comment]
@jgraham I'm ok with you landing this sans-green-CI

**Comment by rwaldron** [comment]
Thanks!

**Pull request merged**
