### PR TITLE
Update Safari Technology Preview to 109

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 109, 15610.1.17.2)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1940&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
@burg @stephenmcgruer I expect this won't be possible to land before https://github.com/web-platform-tests/wpt/pull/21628, making the problems with Catalina somewhat urgent, if it means we can't have any new results for Safari STP until it's resolved.

**Comment by stephenmcgruer** [comment]
Thanks Philip, I had not realized that STP 109 was Catalina-and-up only. That certainly raises the priority; as a note the tracking issue for the problem is actually https://github.com/web-platform-tests/wpt/issues/21751, not https://github.com/web-platform-tests/wpt/pull/21628 (the latter is the pull request where we have been debugging).

cc @othermaciej as an FYI that if we are unable to resolve the Catalina issue here, we will no longer be able to get WPT results on new Safari Tech Preview versions.

@mustjab - is there someone from the Azure Pipelines team we could talk to about this issue? As per https://github.com/web-platform-tests/wpt/issues/21751#issuecomment-652457867, no-one has been able to reproduce this issue on anything outside of the Azure Pipeline images, and notably @burg found when looking at the `sysdiagnose` dump that "no error is returned on the file write operation" - but the plist file still isn't written. This all makes it seem like there's something special about the Azure Pipelines setup that we're failing to account for in our attempts to reproduce.


In the meantime, I'm going to try both the Catalina upgrade + STP 109 at the same time, just in case something new and wonderful has happened and the problem has gone away...

**Comment by foolip** [comment]
If there's a suspicion that this is something about Azure Pipelines, then it would be worth trying to run a few tests on other CI systems, like GitHub Actions, which doesn't appear to use the same underlying infra for macOS. We might not have enough capacity there to actually use it for our runs, but it might help form a better hypothesis of the problem.

**Comment by mustjab** [comment]
@stephenmcgruer Sent mail to Azure Pipelines MacOS team, will let you know when I hear back.

**Comment by foolip** [comment]
I just tried my own suggestion in https://github.com/foolip/safari-ci-starter-kit/commit/ecaf066ee4660dcd1fa94b649d7b8d69544612ce and it seems to me the problem is not specific to Azure Pipelines. Using macOS Catalina in all of Azure Pipelines, CircleCI, Cirrus CI, GitHub Actions, Travis CI, all of them fail in the same way: "Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver"

Is there something that everyone has to do with macOS in a CI environment that isn't the case on a developer machine? What's going on? :D

**Comment by burg** [comment]
The only thing I could think of is whether it's a UI session or a remote session (screen sharing / SSH). There are some restrictions associated with a non-UI login, but I did not think that part of it was being unable to read/write restricted files. Can someone confirm if the CI logins are SSH or UI?

**Comment by foolip** [comment]
Is there a command to test for that difference?

**Comment by stephenmcgruer** [comment]
> Is there a command to test for that difference?

To literally check for SSH we could look for SSH_TTY, SSH_CONNECTION, etc.

For other approaches, I'm not sure. Seems like we would be better off asking the Azure Pipelines team how the sessions work?

**Comment by foolip** [comment]
Obsoleted by https://github.com/web-platform-tests/wpt/pull/24631 (STP 110)

**Pull request closed without merging**
