### PR TITLE
Fix a bunch of links to specs that are not or no longer correct

### PR DESCRIPTION
**Pull request by frivoal**

### CODE REVIEW

**Comment by TalbotG** [comment]
@frivoal Florian,

In your 3f02197 patch and in
 css/css-transitions/transitioncancel-001.html
we can see:
line 8: `<link rel="help" href="https://drafts.csswg.org/css-transitions-2/##event-dispatch">`

there are 2 # .

I am looking again at the patch and checking some random links...

**Comment by TalbotG** [comment]
In
css/css-ui/outline-023.html 
line 6: `https://www.w3.org/TR/CSS2*2*/zindex.html#painting-order`
is better than
`https://www.w3.org/TR/CSS2*1*/zindex.html#painting-order`
but that should not trigger Continuous Integration check to fail.

**Comment by TalbotG** [comment]
In  css/geometry/DOMPoint-001.html
line 6: `<link rel="help" href="http://www.w3.org/TR/geometry-1/#DOMPoint">`
line 9: `<link rel="help" href="https://www.w3.org/TR/geometry-1/#DOMPoint">`
that could (or would) be considered as a duplicate link. The 2nd link uses http**s**

Still looking ...

**Comment by TalbotG** [comment]
In  css/selectors/invalidation/selectorText-dynamic-001.html
line 6: `<link rel="help" href="https://bugzilla.mozilla.org/show_bug.cgi?id=1432850">`

Would that cause a problem?

Before, when we were using HTML 4.01, I would use rel="bookmark" for such kind of links. But now, HTML5 does not support rel="bookmark" .

 css/selectors/invalidation/sheet-going-away-001.html 

 css/selectors/invalidation/sheet-going-away-002.html 

also use link rel="help" to link to a Mozilla bug report.

**Comment by TalbotG** [comment]
In css/css-transitions/transition-background-position-with-edge-offset.html

Line 6: `https://www.w3.org/TR/CSS1/#background-position`

has be wrong. 

Replacement:
`https://drafts.csswg.org/css-backgrounds-3/#background-position`

**Comment by TalbotG** [comment]
In css/css-transitions/transitioncancel-001.html
line 9: `<link rel="help" href="https://lists.w3.org/Archives/Public/www-style/2015Apr/0405.html" data-section-title="AnimationEnd events and display: none">`
is not a link to a spce and data-section-title attribute is not usual, familiar.

**Comment by frivoal** [comment]
@TalbotG I've made https://github.com/web-platform-tests/wpt/pull/22639 to address the comments you've made above, except that I have (at least for now) left alone the links to bugzilla and to the mailing list.

**Pull request merged**
