### PR TITLE
HTML: window.focus() sans browsing context

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by zcorpan** [comment]
I think it would be good to add a test for `blur()` also (to assert that it doesn't throw or crash the browser I guess).

**Comment by annevk** [comment]
You mean add a line somewhere that invokes it? Where? I guess that would also need a comment to indicate why it's there...

**Comment by zcorpan** [comment]
How about a separate test for `blur()` to assert that it does nothing, with or without a browsing context. When I write this I think it makes sense to have the spec just say that it does nothing, also. At least in Chromium it seems it does nothing.

**Comment by annevk** [comment]
Dealing with `blur()` is https://github.com/whatwg/html/issues/4381 now.

**Pull request merged**
