### PR TITLE
Stop mentioning the Test Runner

### PR DESCRIPTION
**Pull request by annevk**
It’s a trap.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5176/)

**Comment by annevk** [comment]
I think removing it is best for now. Moving it to the end doesn't make much sense since folks might have a habit (like me) to scroll there and follow the documentation links.

**Review by jgraham — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213095582)

# Firefox (nightly channel) #
Testing web-platform-tests at revision ef57c58238a450ad6cb0ae474cc7e637195a3499
Using browser at version BuildID 20170319110229; SourceStamp e1576dd8bd9d3a4ca418cf347133b8a4957ddeca
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213095583)

# Chrome (unstable channel) #
Testing web-platform-tests at revision ef57c58238a450ad6cb0ae474cc7e637195a3499
Using browser at version 59.0.3043.0 dev
Starting 10 test iterations
No tests run.

**Pull request merged**
