### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by agouaillard**
On request from Apple.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-19 03:48:38
Finished: 2017-10-19 03:56:15


<h2>Failing Jobs</h2>
<ul>

<li>safari:10.0</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19667)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/289792378)

**Comment by foolip** [comment]
@youennf, OK with you?

**Review by foolip — APPROVED** [review]
Pre-approving, but please wait for @youennf to confirm.

**Comment by youennf** [comment]
Good to me.
ccing @eric-carlson who might be interested as well.

**Comment by eric-carlson** [comment]
Yes, please!

**Pull request merged**
