### PR TITLE
Remove printing/ test

### PR DESCRIPTION
**Pull request by jgraham**
This test ends up spawning a print dialog in non-Blink based browsers,
which causes an unnecessary test timeout. It also doesn't seem to match
a requirement in the HTML spec, and the description of the test doesn't
seem to match its actual behaviour.

### CODE REVIEW

**Comment by annevk** [comment]
I agree with your analysis, but given we can ping the author perhaps @chrishtr can chime in.

**Comment by jgraham** [comment]
I sent @chrishtr an email a couple of days ago, but didn't hear back. But you're right that I should also have pinged them here.

The TC failure is just `pip install` failing on a stability job that would otherwise have done nothing, so not a problem imo.

**Review by annevk — APPROVED** [review]
I'll leave it up to you then.

**Comment by chrishtr** [comment]
I will write a Chromium CL that moves the test out of that directory and into a Chromium-specific one.

Please don't delete this test just now, it adds test coverage for Chromium.

**Comment by chrishtr** [comment]
FYI: https://chromium-review.googlesource.com/c/chromium/src/+/2187174

**Comment by chrishtr** [comment]
My CL landed. You can abandon this PR.

**Comment by stephenmcgruer** [comment]
For the record, https://github.com/web-platform-tests/wpt/pull/23464 is the Chromium export that removed these files.

**Pull request closed without merging**
