### PR TITLE
Look for lib_path when checking _venv existence

### LINKED ISSUE #22042: Improve _venv creation/update to support multiple python versions
The `_venv` directory is created among others by the tools/wpt test suite. It includes some packages that are a must for running wpt tests like the mozbase ones.

The problem is that it is not properly updated/recreated when using different python versions. The mozbase libraries mentioned above are for example installed under `_venv/lib/pythonx.x/site-packages`. If you happen to run the test suite with python2.7 first, then any following run with python3.x will fail because the `_venv/` won't be recreated for python3 packages and thus, the required mozbase packages won't be ever found. The opposite is also true, if the first execution that creates the `_venv` directory is made with python3.x then any following run with python2.x will fail as well.

### PR DESCRIPTION
**Pull request by svillar**
Fixes #22042

### CODE REVIEW

**Review by LukeZielinski — APPROVED** [review]

**Comment by jgraham** [comment]
It's sort of unclear to me why this works, but I think we could just create a `_venv<version>` directory where `<version>` is the `sys.version_info.major`

**Comment by svillar** [comment]
> It's sort of unclear to me why this works, but I think we could just create a `_venv<version>` directory where `<version>` is the `sys.version_info.major`

It basically works because we were avoiding creating a new venv if and only if the _venv dir was present. That was not enough because each python version requires its own libraries under `_venv/lib/pythonx.x/`. If you create that dir with python2 for example, any execution with python3 won't work, because the libs would be under `_venv/lib/python2.7/`. It is clear now?

**Comment by jgraham** [comment]
Oh I see. Are we confident that's enough separation? Can we end up with scripts with the same name in `_venv/bin` for example?

**Comment by svillar** [comment]
> Oh I see. Are we confident that's enough separation? Can we end up with scripts with the same name in `_venv/bin` for example?

Right, I thought exactly the same and in the first version of the patch I was also checking the bin and pip dirs. But then I verified that when running a different major version the whole _venv is recreated. I thought that we'd end up having libs with multiple versions cohabiting under the same directory, but that is not the case.

**Comment by jgraham** [comment]
Right, then I think we should do the `_venv2` `_venv3` thing to allow running them side-by-side without constantly recreating the venv.

**Comment by svillar** [comment]
> Right, then I think we should do the `_venv2` `_venv3` thing to allow running them side-by-side without constantly recreating the venv.

https://github.com/web-platform-tests/wpt/issues/22069

Actually I think we should even create a different one per version (_venv27, _venv37...) as I don't think lib/python3.7/ path for example, is accesible for let's say python3.9...

**Pull request merged**
