### PR TITLE
Css ui 3 fixes

### PR DESCRIPTION
**Pull request by dblachut-adb**
Fixes for following issues are proposed:
- incorrect test instructions
- syntax error - frame name should be a string
- wrong element order in *012* tests that could make false positive results due to spatial navigation.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5419)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219610026)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 2f1820d52070e69c1f0d0159e3cb71551e192658
Using browser at version BuildID 20170406100208; SourceStamp 3c68d659c2b715f811708f043a1e7169d77be2ba
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219610027)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 2f1820d52070e69c1f0d0159e3cb71551e192658
Using browser at version 59.0.3063.4 dev
Starting 10 test iterations
No tests run.

**Comment by frivoal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[css/css-ui-3/support/nav-down-012-frame.html, line 12 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5419#-KhLjcQqyBycoh69b3UI:-KhLjcQqyBycoh69b3UJ:b-nuu0p7) ([raw file](https://github.com/w3c/web-platform-tests/blob/694c83d3ea919db8a79e5689ea3327ee0b7b4952/css/css-ui-3/support/nav-down-012-frame.html#L12)):*
> ```HTML
> <body>
>     <p><a href="" id="finish">FINISH</a></p>
>     <p><a href="" id="start">START</a></p>
> ```

I am not entirely sure this change is as justified as the rest, but it isn't wrong, and I guess on a very narrow screen the line might wrap, bringing FINISH bellow START by accident. I guess it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5419)*

**Comment by frivoal** [comment]
Thank you for the fixes. I is a bit worrying that the test could be wrong for so long without anyone noticing, but it's good we caught it now.

**Comment by dblachut-adb** [comment]
No problem, thank you for the merge.

**Pull request merged**
