### PR TITLE
Delete css/css-color/t451-system-colors-a.xht

### LINKED ISSUE #8684: css/css-color/t451-system-colors-a.xht should be updated or removed
[CSS Color 4](https://drafts.csswg.org/css-color/#system-colors) states that:

> Earlier versions of CSS defined several additional named color keywords, the <deprecated-system-color>s, which were meant to take their value from operating system themes. These color names have been deprecated, however, as they are insufficient for their original purpose (making website elements look like their native OS counterparts), and represent a security risk, as it makes it easier for a webpage to "spoof" a native OS dialog.
> 
> User agents must support these keywords, but should map them to "default" values, not based on the user’s OS settings (for example, mapping all the "background" colors to white and "foreground" colors to black). Authors must not use these keywords.

css/css-color/t451-system-colors-a.xht tests this behavior, so it should either be updated or removed. Since the spec doesn't specify exact mappings from system colors, it should probably be removed as this appears to be up to the implementation.

### PR DESCRIPTION
**Pull request by csnardi**
This test tested behavior that was changed in the current specification, and is now untestable. Fixes #8684.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-12-15 04:03:42
Finished: 2017-12-15 04:08:31


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21861)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/316751591)

**Comment by annevk** [comment]
FWIW, I'd prefer it if @dbaron agreed as well.

**Comment by csnardi** [comment]
@dbaron Any thoughts?

**Comment by csnardi** [comment]
#8684 describes this more in depth, but Color 4 depreciates the system colors, and says that they should be  mapped to "default" values (up to the UA). Color 3 also noted that they were depreciated, but didn't include the requirement to map to "default" values.

**Review by svgeesus — APPROVED** [review]
As agreed https://github.com/w3c/web-platform-tests/issues/8684 this is no longer testable, test must be deleted

**Pull request merged**
