### PR TITLE
FetchEvent.clientID is an empty string by default and no longer nullable

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20771)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/303301935)

**Comment by jungkees** [comment]
It looks good. I think it's better to change the error message from "non-null" to "non-empty string" or similar too.

**Comment by youennf** [comment]
Ping review?

**Comment by youennf** [comment]
ping review? See related https://github.com/w3c/web-platform-tests/pull/8507

**Review by beidson — APPROVED** [review]

**Pull request closed without merging**
