### PR TITLE
URL: stripping of tab and newlines in setters

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/url/issues/419.

### CODE REVIEW

**Comment by domenic** [comment]
This does not match jsdom/whatwg-url in several ways. I'll collate them here, then we can dig into whether they're implementation issues or test issues...

```
Setting hash with leading U+000

    Expected value to strictly be equal to:
      "#%00test"
    Received:
      "#test"
```

```
Setting username with leading U+0009

    Expected value to strictly be equal to:
      "test"
    Received:
      "%09test"
```

and then the last one again for U+000A, U+000D, and all three cases again for password

**Comment by domenic** [comment]
> Setting hash with leading U+0000

This test is incorrect. https://url.spec.whatwg.org/#fragment-state does a validation error, and then does nothing, for U+0000

**Comment by domenic** [comment]
> Setting username with leading U+0009

These also appear to be incorrect. E.g. https://url.spec.whatwg.org/#dom-url-username goes to https://url.spec.whatwg.org/#set-the-username which percent-encodes using https://url.spec.whatwg.org/#userinfo-percent-encode-set which includes U+0009, U+000A, U+000D.

**Comment by domenic** [comment]
>> Setting hash with leading U+0000
>
> This test is incorrect. https://url.spec.whatwg.org/#fragment-state does a validation error, and then does nothing, for U+0000

Well, OK, I think this is correct now that the latest spec changes have landed :).

**Comment by annevk** [comment]
I could have sworn I made an intermediate commit for trailing stuff before adding non-special scheme support. Oh well.

@domenic want to verify again? This now is about as exhaustive as I imagined it. Trailing caught new failures, non-special scheme only caught failures in implementations that don't have good support for those anyway.

**Comment by domenic** [comment]
I'm now getting a lot of failures in the "Setting protocol with trailing X" tests. The setters change the result in whatwg-url but the test expects them to stay unchanged.

I don't see any reason why the protocol would stay unchanged. Note that step 3 of [basic URL parse](https://url.spec.whatwg.org/#concept-basic-url-parser) removes all ASCII tab and newline from the input, not just trailing/leading ones.

Also, if you wouldn't mind rebasing this on master, that would help me testing a bit.

**Comment by annevk** [comment]
Thanks for highlighting that! I should also add a "middle" variant then.

**Comment by domenic** [comment]
The latest commit (c0d8a8413dc030062fcb02fd5f3c51d653a2ce2e) passes entirely with whatwg-url. Happy to test again if you add a middle variant.

**Review by domenic — APPROVED** [review]

**Comment by annevk** [comment]
The middle variant found port setter bugs in Safari, provided I did it correctly.

**Review by domenic — APPROVED** [review]
Still passes

**Pull request merged**
