### PR TITLE
Create portals/ directory and metadata.

### PR DESCRIPTION
**Pull request by jeremyroman**
We might as well land some of our tests upstream and write them in WPT style from the get go since we intend for this feature to be on the standards track.

### CODE REVIEW

**Comment by jeremyroman** [comment]
@foolip PTAL? @Hexcles suggested I ask you to review this.

@lucasgadani @a4sriniv fyi

**Review by lucasgadani — APPROVED** [review]

**Review by Ms2ger — APPROVED** [review]

**Comment by foolip** [comment]
@jeremyroman, LGTM, and thanks for flying with web-platform-tests!

**Comment by Hexcles** [comment]
@foolip I think we also need to invite @jeremyroman and @lucasgadani to the org and add them to reviewers?

**Comment by foolip** [comment]
@Hexcles done! @jeremyroman @lucasgadani see https://github.com/orgs/web-platform-tests/teams/reviewers/discussions for some things you'll want to after you accept the invite to not get lots of email.

**Pull request merged**
