### PR TITLE
Implement the inert attribute: https://github.com/WICG/inert#tldr


### PR DESCRIPTION
**Pull request by jeffcarp**
https://discourse.wicg.io/t/inert-attribute/1838/

BUG=692360

Review-Url: https://codereview.chromium.org/2088453002
Cr-Commit-Position: refs/heads/master@{#474153}

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723924)

# Firefox (nightly) #
Testing web-platform-tests at revision 97a94a7244097d556ce68f930b36d8b1c23e40c0
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6041/html/dom/elements/elements-in-the-dom/historical.html">/html/dom/elements/elements-in-the-dom/historical.html</a></summary>


|                       Subtest                       | Results | Messages |
|-----------------------------------------------------|---------|----------|
|                                                     | OK      |          |
| `HTMLElement member must be nuked: commandType`     | PASS    |          |
| `HTMLElement member must be nuked: commandLabel`    | PASS    |          |
| `HTMLElement member must be nuked: commandIcon`     | PASS    |          |
| `HTMLElement member must be nuked: commandHidden`   | PASS    |          |
| `HTMLElement member must be nuked: commandDisabled` | PASS    |          |
| `HTMLElement member must be nuked: commandChecked`  | PASS    |          |
| `HTMLElement member must be nuked: commandTriggers` | PASS    |          |
| `HTMLElement member must be nuked: dropzone`        | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723925)

# Sauce (safari) #
Testing web-platform-tests at revision 97a94a7244097d556ce68f930b36d8b1c23e40c0
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6041/html/dom/elements/elements-in-the-dom/historical.html">/html/dom/elements/elements-in-the-dom/historical.html</a></summary>


|                       Subtest                       | Results | Messages |
|-----------------------------------------------------|---------|----------|
|                                                     | OK      |          |
| `HTMLElement member must be nuked: commandType`     | PASS    |          |
| `HTMLElement member must be nuked: commandLabel`    | PASS    |          |
| `HTMLElement member must be nuked: commandIcon`     | PASS    |          |
| `HTMLElement member must be nuked: commandHidden`   | PASS    |          |
| `HTMLElement member must be nuked: commandDisabled` | PASS    |          |
| `HTMLElement member must be nuked: commandChecked`  | PASS    |          |
| `HTMLElement member must be nuked: commandTriggers` | PASS    |          |
| `HTMLElement member must be nuked: dropzone`        | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723934)

# Chrome (unstable) #
Testing web-platform-tests at revision 97a94a7244097d556ce68f930b36d8b1c23e40c0

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235723935)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 97a94a7244097d556ce68f930b36d8b1c23e40c0

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
