### PR TITLE
HTML: assert ErrorEventInit defaults

### PR DESCRIPTION
**Pull request by annevk**
This accounts for the change in https://github.com/whatwg/html/pull/7983 as well.

### CODE REVIEW

**Review by domenic — APPROVED** [review]

**Review by domenic — COMMENTED** [review]
I might prefer adding a second test to the same file which just constructs `const e = new ErrorEvent("error")` directly, and tests that. This is pretty indirect and now we're mixing up two things (error event is normal, and error event defaults) into one test.

**Comment by annevk** [comment]
I can add that, but it seems we should keep this as well? We wouldn't want dispatch to change these fields.

**Comment by domenic** [comment]
I guess, but we've never worried about dispatch changing properties of event classes before. I don't object to keeping it but there's an unlimited number of wierd out-of-spec things a platform method call could do and I'm not sure how many of them we should test against.

**Comment by annevk** [comment]
I think we do in a large number of contexts, such as with shadow trees, a large number of UI events, etc. I agree that in this specific case it might be a little more undeserving, but it won't hurt.

**Pull request merged**
