### PR TITLE
Update Safari Technology Preview to 106

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 106, 15610.1.12.2)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1742&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
This PR wasn't created as fast as it usually is because https://github.com/foolip/safari-technology-preview-updater had broken due to an incompatible Octokit change, and I had to push a bunch of changes to get it in order again.

**Comment by stephenmcgruer** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=48261&view=results

**Comment by stephenmcgruer** [comment]
Diff - https://wpt.fyi/results/?diff&filter=ADC&run_id=533110002&run_id=527540003

**Comment by stephenmcgruer** [comment]
Overall the diff looks ok, but seems like there's a regression in css-grid ? https://wpt.fyi/results/css/css-grid?diff&filter=ADC&run_id=533110002&run_id=527540003 - not something that would block this upgrade, but cc @mrego as an FYI

**Review by stephenmcgruer — APPROVED** [review]

**Comment by mrego** [comment]
I'm not aware of grid layout related changes recently, I guess we might need to check what's going on here, maybe @Loirooriol can take a look at some point. Thanks for the heads up

**Comment by mrego** [comment]
Mmm, ok there was a change that it seems got into this release, that was a revert that had to be done in all browsers (https://github.com/w3c/csswg-drafts/issues/4475). And these tests are also failing in Chromium https://wpt.fyi/results/css/css-grid/grid-layout-properties.html?label=experimental&label=master&aligned

@Loirooriol do we need to update these tests after the change has been discarded from the spec?

**Comment by Loirooriol** [comment]
I hope the we can reland the changes after adding an API to get the sizes of implicit tracks, but I guess the WPT should be reverted for now, yes.

**Comment by mrego** [comment]
> I hope the we can reland the changes after adding an API to get the sizes of implicit tracks, but I guess the WPT should be reverted for now, yes.

Yes that will take a while, so it seems we need to revert those changes for now.

**Comment by stephenmcgruer** [comment]
If they are in separate files, you could consider using the 'tentative' file name flag (if you believe the spec will change back to having this behavior): https://web-platform-tests.org/writing-tests/file-names.html?highlight=tentative#test-features

**Comment by Hexcles** [comment]
Thanks for taking care of this, Stephen.

**Comment by mrego** [comment]
Things are way better now, after @Loirooriol updated the tests in #23675:
https://wpt.fyi/results/css/css-grid?diff&filter=ADC&run_id=527540003&run_id=554370001

**Pull request merged**
