### PR TITLE
Allow uncaught exceptions when testing error handler

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410938)

# Firefox (nightly) #
Testing web-platform-tests at revision 2d6f2bc40570ffeabc83de5d28a9506b4486d92e
Using browser at version BuildID 20170520182312; SourceStamp 8d60d0f825110cfb646ac31dc16dc011708bcf34
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6010/html/webappapis/scripting/events/inline-event-handler-ordering.html">/html/webappapis/scripting/events/inline-event-handler-ordering.html</a></summary>


|                                          Subtest                                           | Results | Messages |
|--------------------------------------------------------------------------------------------|---------|----------|
|                                                                                            | OK      |          |
| `Inline event handlers retain their ordering when invalid and force-compiled`              | PASS    |          |
| `Inline event handlers retain their ordering when invalid and force-compiled via dispatch` | PASS    |          |
| `Inline event handlers retain their ordering when invalid and lazy-compiled`               | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410939)

# Sauce (safari) #
Testing web-platform-tests at revision 2d6f2bc40570ffeabc83de5d28a9506b4486d92e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6010/html/webappapis/scripting/events/inline-event-handler-ordering.html">/html/webappapis/scripting/events/inline-event-handler-ordering.html</a></summary>


|                                          Subtest                                           | Results |                              Messages                             |
|--------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------|
|                                                                                            | OK      |                                                                   |
| `Inline event handlers retain their ordering when invalid and force-compiled`              | FAIL    | `assert_array_equals: property 1, expected "TWO" but got "THREE"` |
| `Inline event handlers retain their ordering when invalid and force-compiled via dispatch` | FAIL    | `assert_array_equals: property 3, expected "TWO" but got "THREE"` |
| `Inline event handlers retain their ordering when invalid and lazy-compiled`               | FAIL    | `assert_array_equals: property 1, expected "TWO" but got "THREE"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410945)

# Chrome (unstable) #
Testing web-platform-tests at revision 2d6f2bc40570ffeabc83de5d28a9506b4486d92e

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234410946)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 2d6f2bc40570ffeabc83de5d28a9506b4486d92e

**Review by Sebmaster — APPROVED** [review]

**Review by jdm — APPROVED** [review]
Interesting test results!

**Pull request merged**
