### PR TITLE
Add triggers/* branches to support triggering full runs

### LINKED ISSUE #13263: Ability to run all tests for some PRs
In https://github.com/web-platform-tests/wpt/pull/11769 a handful of tests were broken accidentally. This was reported in https://github.com/web-platform-tests/wpt/issues/13204 and also some of the same tests were found to fail in an [attempt to roll into Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/1249141/1).
<details>
<pre>
 cookie-store/http_cookie_and_set_cookie_headers.tentative.https.html
 cookies/http-state/charset-tests.html
 eventsource/format-field-id-2.htm
 eventsource/format-field-id.htm
 fetch/api/headers/header-values.html
</pre>
</details>

Relatedly, many changes in resources/ by @lukebjerring, @jugglinmike and me have been put through Chromium's CQ first to see if they would break existing tests.

To help prevent accidental regressions and make it easier to look for anticipated regressions, the ability to run *all* tests in Taskcluster for some PRs would be very good.

Strawman: including the magic string "Taskcluster-Full-Run" somewhere would cause Taskcluster to treat all tests as affected.

Lots of similar solutions might be possible.

@jgraham

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt/issues/13263.

### CODE REVIEW

**Comment by foolip** [comment]
I've already created all branches except two of them. To verify that this works, I'll push the head of this PR to the two that remain: firefox_nightly and safari_preview.

**Comment by foolip** [comment]
STP succesfully triggered: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=29824

Taskcluster didn't work, will iterate...

**Comment by foolip** [comment]
https://tools.taskcluster.net/groups/Qwz3vIzuQlGW5SWf9JREnQ is looking better, I think this works now.

**Review by jgraham — APPROVED** [review]
Nice approach! Probably doesn't scale to many more configurations, but I think it's fine for our requirements.

**Comment by foolip** [comment]
https://wpt.fyi/results/?sha=c8ea6db4f7&max-count=1 shows two of the runs successfully triggered by this, so merging now :)

**Pull request merged**
