### PR TITLE
[css-sizing] Intrinsic percentage non-replaced widths

### PR DESCRIPTION
**Pull request by fantasai**
Pending resolutions / edits for https://github.com/w3c/csswg-drafts/issues/1132 
Wasn't sure how to make it self-describing (other than copying the reference into the test, for a fairly long and complicated reference) without compromising understandability.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23984)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/338286185)

**Review by FremyCompany — APPROVED** [review]
It seems those tests pass in all browsers, so I don't think there is anything controversial about them.

**One question though**: why do the test have `calc(80px + 0%)` entries but no `calc(40px + 50%)` entries? I would think that latter case is actually more complex that one where percentages are zero and can be safely ignored.

**Comment by FremyCompany** [comment]
https://wptest.center/#/ejals5 has a test for latter case

**Comment by FremyCompany** [comment]
https://wptest.center/#/l13fr2 for a test case with padding

**Comment by FremyCompany** [comment]
And, just for good measure, a test that no browser passes:
https://wptest.center/#/f5atx4 for margin

**Pull request merged**
