### PR TITLE
XMLHttpRequest: manipulate Content-Type a little more

### PR DESCRIPTION
**Pull request by annevk**
99f4fdcd906411c036e96c055e28b3e6ca84a1cc was not entirely correct unfortunately.

### CODE REVIEW

**Review by wisniewskit — COMMENTED** [review]
It's probably worth having two tests, one for leading and one for trailing space (since leading spaces aren't stripped by MimeSniff.serial, but trailing ones are, so charsets ending with spaces will be normalized, but ones beginning with spaces will not).

**Comment by annevk** [comment]
Fair, pushed a commit.

**Review by wisniewskit — CHANGES_REQUESTED** [review]
Heh, sorry, this is the inverse of what I meant :)

>"charset= utf-8" --> will not change because leading spaces are not stripped by serialize.
>"charset=utf-8 " --> will become "charset=UTF-8", because trailing spaces *are* stripped.

**Comment by annevk** [comment]
If it is an ASCII case-insensitive match for UTF-8, we won't change the value. So if the spaces are stripped, it'll be a match, meaning the value won't change, right?

**Review by wisniewskit — APPROVED** [review]
Ah, right. I was getting myself mixed up (busy day). This should be fine.

**Pull request merged**
