### PR TITLE
📖  Fix meta documentation issue with custom elements child node test

### PR DESCRIPTION
**Pull request by snuggs**
Addresses https://github.com/w3c/web-platform-tests/blob/master/custom-elements/reactions/ChildNode.html#L6-L7

- [x] 📖 Remove duplication in ChildNode assertion statement
- [x] 📖 Fix broken help link in custom-elements/reactions/ChildNode.html

Starting to see these more and more @TakayoshiKochi. Let me know if i should keep going. This is fun 😸  /cc @rniwa

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248759694)

# Firefox (nightly) #
Testing web-platform-tests at revision 0f39d61cd83085c6dde550738cd885cc4f80ae8a
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6435/custom-elements/reactions/ChildNode.html">/custom-elements/reactions/ChildNode.html</a></summary>


|                                                                            Subtest                                                                             | Results |                         Messages                        |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------|
|                                                                                                                                                                | OK      |                                                         |
| `before on ChildNode must enqueue a connected reaction`                                                                                                        | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `before on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`      | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `after on ChildNode must enqueue a connected reaction`                                                                                                         | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `after on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`       | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `replaceWith on ChildNode must enqueue a connected reaction`                                                                                                   | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `replaceWith on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document` | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `remove on ChildNode must enqueue a disconnected reaction`                                                                                                     | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248759695)

# Sauce (safari) #
Testing web-platform-tests at revision 0f39d61cd83085c6dde550738cd885cc4f80ae8a
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248759701)

# Chrome (unstable) #
Testing web-platform-tests at revision 0f39d61cd83085c6dde550738cd885cc4f80ae8a

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248759702)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 0f39d61cd83085c6dde550738cd885cc4f80ae8a

**Review by TakayoshiKochi — APPROVED** [review]
LGTM

**Pull request merged**
