### PR TITLE
Update IDL for Payment Request and add a historical.html

### PR DESCRIPTION
**Pull request by zcorpan**
Test update for https://github.com/w3c/browser-payment-api/pull/419

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 0f3973ddcf817c59df2e7a1d83895fa6f5ea111e
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="https://w3c-test.org/submissions/4806/payment-request/historical.https.html">/payment-request/historical.https.html</a></summary>


|                Subtest                | Results |
|---------------------------------------|---------|
|                                       | OK      |
| `careOf in PaymentAddress`            | FAIL    |
| `paymentRequestID in PaymentResponse` | FAIL    |
| `totalAmount in PaymentResponse`      | FAIL    |
| `paymentRequestID in PaymentRequest`  | FAIL    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/4806/payment-request/interfaces.https.html">/payment-request/interfaces.https.html</a></summary>


|                                                                                                        Subtest                                                                                                         | Results |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                                                                                                        | OK      |
| `PaymentRequest interface: existence and properties of interface prototype object`                                                                                                                                     | FAIL    |
| `PaymentAddress interface: attribute phone`                                                                                                                                                                            | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "show" with the proper type (0)`                    | FAIL    |
| `PaymentRequestUpdateEvent interface object name`                                                                                                                                                                      | FAIL    |
| `PaymentResponse interface: attribute shippingOption`                                                                                                                                                                  | FAIL    |
| `Stringification of new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}})`                                                                                 | FAIL    |
| `PaymentAddress interface: attribute organization`                                                                                                                                                                     | FAIL    |
| `PaymentResponse interface: operation complete(PaymentComplete)`                                                                                                                                                       | FAIL    |
| `PaymentRequestUpdateEvent interface: operation updateWith([object Object])`                                                                                                                                           | FAIL    |
| `PaymentRequestUpdateEvent interface object length`                                                                                                                                                                    | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "onshippingaddresschange" with the proper type (7)` | FAIL    |
| `PaymentRequest interface: attribute onshippingoptionchange`                                                                                                                                                           | FAIL    |
| `PaymentRequest interface: attribute paymentRequestId`                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: existence and properties of interface object`                                                                                                                                               | FAIL    |
| `PaymentRequest interface object name`                                                                                                                                                                                 | FAIL    |
| `PaymentAddress interface: attribute sortingCode`                                                                                                                                                                      | FAIL    |
| `PaymentRequest interface: operation canMakePayment()`                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: existence and properties of interface prototype object's "constructor" property`                                                                                                            | FAIL    |
| `PaymentAddress interface object name`                                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: attribute shippingAddress`                                                                                                                                                                  | FAIL    |
| `PaymentResponse interface: attribute details`                                                                                                                                                                         | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "abort" with the proper type (1)`                   | FAIL    |
| `PaymentAddress interface: attribute country`                                                                                                                                                                          | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface object`                                                                                                                                    | FAIL    |
| `PaymentResponse interface: attribute payerName`                                                                                                                                                                       | FAIL    |
| `PaymentAddress interface object length`                                                                                                                                                                               | FAIL    |
| `PaymentRequest interface object length`                                                                                                                                                                               | FAIL    |
| `PaymentAddress interface: existence and properties of interface prototype object`                                                                                                                                     | FAIL    |
| `PaymentAddress interface: attribute dependentLocality`                                                                                                                                                                | FAIL    |
| `PaymentAddress interface: attribute postalCode`                                                                                                                                                                       | FAIL    |
| `PaymentResponse interface: existence and properties of interface prototype object`                                                                                                                                    | FAIL    |
| `PaymentResponse interface: attribute payerEmail`                                                                                                                                                                      | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface prototype object's "constructor" property`                                                                                                 | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "onshippingoptionchange" with the proper type (8)`  | FAIL    |
| `PaymentResponse interface object length`                                                                                                                                                                              | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "paymentRequestId" with the proper type (3)`        | FAIL    |
| `PaymentAddress interface: attribute addressLine`                                                                                                                                                                      | FAIL    |
| `PaymentResponse interface: attribute payerPhone`                                                                                                                                                                      | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface prototype object`                                                                                                                          | FAIL    |
| `PaymentAddress interface: existence and properties of interface prototype object's "constructor" property`                                                                                                            | FAIL    |
| `PaymentResponse interface: existence and properties of interface object`                                                                                                                                              | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingType" with the proper type (6)`            | FAIL    |
| `PaymentAddress interface: attribute region`                                                                                                                                                                           | FAIL    |
| `PaymentRequest interface: attribute shippingOption`                                                                                                                                                                   | FAIL    |
| `PaymentResponse interface: existence and properties of interface prototype object's "constructor" property`                                                                                                           | FAIL    |
| `PaymentResponse interface: attribute methodName`                                                                                                                                                                      | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingAddress" with the proper type (4)`         | FAIL    |
| `PaymentRequest interface: operation show()`                                                                                                                                                                           | FAIL    |
| `PaymentAddress interface: attribute city`                                                                                                                                                                             | FAIL    |
| `PaymentResponse interface: attribute paymentRequestId`                                                                                                                                                                | FAIL    |
| `PaymentResponse interface: attribute shippingAddress`                                                                                                                                                                 | FAIL    |
| `PaymentResponse interface object name`                                                                                                                                                                                | FAIL    |
| `PaymentAddress interface: attribute recipient`                                                                                                                                                                        | FAIL    |
| `PaymentRequest interface: attribute shippingType`                                                                                                                                                                     | FAIL    |
| `PaymentRequest interface: attribute onshippingaddresschange`                                                                                                                                                          | FAIL    |
| `PaymentAddress interface: existence and properties of interface object`                                                                                                                                               | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingOption" with the proper type (5)`          | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "canMakePayment" with the proper type (2)`          | FAIL    |
| `PaymentAddress interface: attribute languageCode`                                                                                                                                                                     | FAIL    |
| `PaymentRequest must be primary interface of new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}})`                                                        | FAIL    |
| `PaymentRequest interface: operation abort()`                                                                                                                                                                          | FAIL    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 0f3973ddcf817c59df2e7a1d83895fa6f5ea111e
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="https://w3c-test.org/submissions/4806/payment-request/historical.https.html">/payment-request/historical.https.html</a></summary>


|                Subtest                | Results |
|---------------------------------------|---------|
|                                       | OK      |
| `careOf in PaymentAddress`            | FAIL    |
| `paymentRequestID in PaymentResponse` | FAIL    |
| `totalAmount in PaymentResponse`      | FAIL    |
| `paymentRequestID in PaymentRequest`  | FAIL    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/4806/payment-request/interfaces.https.html">/payment-request/interfaces.https.html</a></summary>


|                                                                                                        Subtest                                                                                                         | Results |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                                                                                                        | OK      |
| `PaymentRequest interface: existence and properties of interface prototype object`                                                                                                                                     | FAIL    |
| `PaymentAddress interface: attribute phone`                                                                                                                                                                            | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "show" with the proper type (0)`                    | FAIL    |
| `PaymentRequestUpdateEvent interface object name`                                                                                                                                                                      | FAIL    |
| `PaymentResponse interface: attribute shippingOption`                                                                                                                                                                  | FAIL    |
| `Stringification of new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}})`                                                                                 | FAIL    |
| `PaymentAddress interface: attribute organization`                                                                                                                                                                     | FAIL    |
| `PaymentResponse interface: operation complete(PaymentComplete)`                                                                                                                                                       | FAIL    |
| `PaymentRequestUpdateEvent interface: operation updateWith([object Object])`                                                                                                                                           | FAIL    |
| `PaymentRequestUpdateEvent interface object length`                                                                                                                                                                    | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "onshippingaddresschange" with the proper type (7)` | FAIL    |
| `PaymentRequest interface: attribute onshippingoptionchange`                                                                                                                                                           | FAIL    |
| `PaymentRequest interface: attribute paymentRequestId`                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: existence and properties of interface object`                                                                                                                                               | FAIL    |
| `PaymentRequest interface object name`                                                                                                                                                                                 | FAIL    |
| `PaymentAddress interface: attribute sortingCode`                                                                                                                                                                      | FAIL    |
| `PaymentRequest interface: operation canMakePayment()`                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: existence and properties of interface prototype object's "constructor" property`                                                                                                            | FAIL    |
| `PaymentAddress interface object name`                                                                                                                                                                                 | FAIL    |
| `PaymentRequest interface: attribute shippingAddress`                                                                                                                                                                  | FAIL    |
| `PaymentResponse interface: attribute details`                                                                                                                                                                         | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "abort" with the proper type (1)`                   | FAIL    |
| `PaymentAddress interface: attribute country`                                                                                                                                                                          | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface object`                                                                                                                                    | FAIL    |
| `PaymentResponse interface: attribute payerName`                                                                                                                                                                       | FAIL    |
| `PaymentAddress interface object length`                                                                                                                                                                               | FAIL    |
| `PaymentRequest interface object length`                                                                                                                                                                               | FAIL    |
| `PaymentAddress interface: existence and properties of interface prototype object`                                                                                                                                     | FAIL    |
| `PaymentAddress interface: attribute dependentLocality`                                                                                                                                                                | FAIL    |
| `PaymentAddress interface: attribute postalCode`                                                                                                                                                                       | FAIL    |
| `PaymentResponse interface: existence and properties of interface prototype object`                                                                                                                                    | FAIL    |
| `PaymentResponse interface: attribute payerEmail`                                                                                                                                                                      | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface prototype object's "constructor" property`                                                                                                 | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "onshippingoptionchange" with the proper type (8)`  | FAIL    |
| `PaymentResponse interface object length`                                                                                                                                                                              | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "paymentRequestId" with the proper type (3)`        | FAIL    |
| `PaymentAddress interface: attribute addressLine`                                                                                                                                                                      | FAIL    |
| `PaymentResponse interface: attribute payerPhone`                                                                                                                                                                      | FAIL    |
| `PaymentRequestUpdateEvent interface: existence and properties of interface prototype object`                                                                                                                          | FAIL    |
| `PaymentAddress interface: existence and properties of interface prototype object's "constructor" property`                                                                                                            | FAIL    |
| `PaymentResponse interface: existence and properties of interface object`                                                                                                                                              | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingType" with the proper type (6)`            | FAIL    |
| `PaymentAddress interface: attribute region`                                                                                                                                                                           | FAIL    |
| `PaymentRequest interface: attribute shippingOption`                                                                                                                                                                   | FAIL    |
| `PaymentResponse interface: existence and properties of interface prototype object's "constructor" property`                                                                                                           | FAIL    |
| `PaymentResponse interface: attribute methodName`                                                                                                                                                                      | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingAddress" with the proper type (4)`         | FAIL    |
| `PaymentRequest interface: operation show()`                                                                                                                                                                           | FAIL    |
| `PaymentAddress interface: attribute city`                                                                                                                                                                             | FAIL    |
| `PaymentResponse interface: attribute paymentRequestId`                                                                                                                                                                | FAIL    |
| `PaymentResponse interface: attribute shippingAddress`                                                                                                                                                                 | FAIL    |
| `PaymentResponse interface object name`                                                                                                                                                                                | FAIL    |
| `PaymentAddress interface: attribute recipient`                                                                                                                                                                        | FAIL    |
| `PaymentRequest interface: attribute shippingType`                                                                                                                                                                     | FAIL    |
| `PaymentRequest interface: attribute onshippingaddresschange`                                                                                                                                                          | FAIL    |
| `PaymentAddress interface: existence and properties of interface object`                                                                                                                                               | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "shippingOption" with the proper type (5)`          | FAIL    |
| `PaymentRequest interface: new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}}) must inherit property "canMakePayment" with the proper type (2)`          | FAIL    |
| `PaymentAddress interface: attribute languageCode`                                                                                                                                                                     | FAIL    |
| `PaymentRequest must be primary interface of new PaymentRequest([{supportedMethods: ['foo']}], {total: {label: 'bar', amount: {currency: 'BAZ', value: '0'}}})`                                                        | FAIL    |
| `PaymentRequest interface: operation abort()`                                                                                                                                                                          | FAIL    |

</details>

**Comment by zcorpan** [comment]
@marcoscaceres r?

**Comment by marcoscaceres** [comment]
@zcorpan, I've not done a web platform test review before. Is the IDL copy/pasted from the spec? Anything in particular I should look for?

**Comment by zcorpan** [comment]
Yes, it is. I suppose my copy/paste skills should be good enough that the IDL doesn't need particular review (and the test runs fine so should be a-OK).

Did I miss something in `historical.html` that has once been in the spec, or some implementation supports but should not be supported in the spec?

(Docs for reviewing: http://web-platform-tests.org/reviewing-tests/index.html )

**Comment by marcoscaceres** [comment]
Sorry for the delay @zcorpan. Not sure if you are still watching the Payment Request repo, but some of the IDL is going to be changing next week (some dictionaries are getting renamed, and `.paymentRequestId` is becoming `.id`, etc.).  

Let's hold on this till that's done, as this will need to be updated.

**Comment by marcoscaceres** [comment]
@zcorpan, the IDL in the spec has been updated.

**Review by marcoscaceres — CHANGES_REQUESTED** [review]
Relevant changes are in https://github.com/w3c/browser-payment-api/pull/426

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4806/)

**Comment by zcorpan** [comment]
OK updated.

**Review by marcoscaceres — APPROVED** [review]

**Pull request merged**
