### PR TITLE
[css-ui-3] Fixes incorrect test instructions

### PR DESCRIPTION
**Pull request by frivoal**
Whether a typo or an hasty copy&pate, this made the test instructions
wrong.

See https://lists.w3.org/Archives/Public/public-css-testsuite/2017Apr/0003.html

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5377)

### CODE REVIEW

**Comment by frivoal** [comment]
Pinging for review:
- @therealglazou (this is a test you co-authored)
- @gsnedders

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218782002)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 39ba4d96ea272a6d566bf7fea3b59c62ad44a802
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218782003)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 39ba4d96ea272a6d566bf7fea3b59c62ad44a802
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5377/)

**Review by therealglazou — APPROVED** [review]
+1

**Comment by frivoal** [comment]
Thanks Daniel for the review. Merging.

**Pull request merged**
