### PR TITLE
Remove useless README files

### PR DESCRIPTION
**Pull request by zqzhang**

### CODE REVIEW

**Comment by Velmont** [comment]
Why do you mean the README files are useless?

They link to w3c-test and to the actual specs, how is that useless?

**Comment by zqzhang** [comment]
> They link to w3c-test and to the actual specs, how is that useless?

Per the overall README file at https://github.com/w3c/web-platform-tests#finding-things, default

> Each top-level directory represents a W3C specification: the name matches the shortname used after the canonical address of the said specification under http://www.w3.org/TR/ 

See also @Ms2ger's comment at https://github.com/w3c/web-platform-tests/pull/1904#issuecomment-112307079

**Comment by Velmont** [comment]
Well, at least I disagree @Ms2ger. The README is shown at the end of the page when you browse around.  Though I don't feel strongly about it, -- I also don't really see why we shouldn't have README files and I think it's a good idea keeping them up to date.

It's convenient and also somewhat simpler to discover the links when they are at the end of the GitHub page.

**Comment by AFBarstow** [comment]
FWIW, I agree with @Velmont. 

I think there is more benefit than harm although I do agree it is important for the README's to be accurate, which should be relatively easy. 

The mimimum contents: 1) link to the ED; 2) link to the `live` version of the tests within w3c-test.org. Additionally, if the spec has test data in w3c/test-results, include a link.

**Comment by sideshowbarker** [comment]
@zqzhang Based on other comments here, it seems clear we don't have consensus on merging this PR. So I suggest just closing it. If there are particular READMEs in the tree that aren't useful at all, let's identify just those and remove them (if any).

**Pull request closed without merging**
