### PR TITLE
Use ahem.css in css-grid tests.

### PR DESCRIPTION
**Pull request by LukeZielinski**
This is part of the transition to using Ahem as a web font. These tests were broken by this transition but seem to work now.

Carving these tests out from #17205 for individual review.

### CODE REVIEW

**Comment by LukeZielinski** [comment]
@foolip Looks like the css-grid tests benefited from reftest-wait, even if we don't do a delayed screenshot. Can these be submitted like this?

**Comment by foolip** [comment]
@LukeZielinski looks like the test are timing out now because the reftest-wait class is never removed. That makes them pass the stability check, but it's still breaking the tests. Oops :)

**Comment by LukeZielinski** [comment]
> @LukeZielinski looks like the test are timing out now because the reftest-wait class is never removed. That makes them pass the stability check, but it's still breaking the tests. Oops :)

Doh! didn't click enough buttons. Abandoning.

**Comment by LukeZielinski** [comment]
> > @LukeZielinski looks like the test are timing out now because the reftest-wait class is never removed. That makes them pass the stability check, but it's still breaking the tests. Oops :)
> 
> Doh! didn't click enough buttons. Abandoning.

..Actually, I realize I just needed to takeScreenshot call - so it looks like this passes if we do takeScrenshot (without the delay)?

**Comment by LukeZielinski** [comment]
So the latest on this is that these tests do seem to pass by simply loading ahem stylesheet, without any explicit waiting or screenshotting. @foolip WDYT?

**Comment by foolip** [comment]
Well that's pretty funny, wasn't that the original change carved out from https://github.com/web-platform-tests/wpt/pull/17205?

When we were debugging this a Chrome bug seemed somewhat plausible, so *maybe* Chrome actually changed and that's why it's now passing.

@LukeZielinski is this a case you were ever able to repro locally by opening the test in a browser manually? If so could you use https://www.chromium.org/developers/bisect-builds-py to verify that the change is due to a Chromium change? If not, then I say let's just merge this since it passes :)

**Review by foolip — APPROVED** [review]

**Comment by LukeZielinski** [comment]
> @LukeZielinski is this a case you were ever able to repro locally by opening the test in a browser manually? If so could you use https://www.chromium.org/developers/bisect-builds-py to verify that the change is due to a Chromium change? If not, then I say let's just merge this since it passes :)

This is one of the test that behaves differently than on CI unfortunately, so I'm inclined to just submit.

**Pull request merged**
