### PR TITLE
Add OWNERS for the Properties and Values API

### PR DESCRIPTION
**Pull request by csnardi**
Add an OWNERS file for the Properties and Values API.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-12 18:16:33
Finished: 2018-03-12 18:23:33


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25811)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/352474075)

**Comment by csnardi** [comment]
@tabatkins @shans

**Comment by csnardi** [comment]
@gsnedders Would you mind merging this?

**Comment by gsnedders** [comment]
@csnardi we normally ask people to okay being added as OWNERS

@tabatkins @shans you okay with being added as OWNERS here?

**Comment by foolip** [comment]
If nobody volunteers I'd suggest closing this. Or poke people by other means, GitHub mail is ignored by many.

**Comment by csnardi** [comment]
Superseded by #10522.

**Pull request closed without merging**
