### PR TITLE
Assert correct ordering of click, input, and change events when clicking checkboxes or radios

### PR DESCRIPTION
**Pull request by cvrebert**
Background: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28985

### CODE REVIEW

**Comment by zcorpan** [comment]
LGTM. (Would you like to check if radio button tests need this change as well?)

**Comment by cvrebert** [comment]
@zcorpan They do indeed. Added a commit to update the radio button test. LGTY?

**Comment by zcorpan** [comment]
Yeah, LGTM as far as matching the spec goes, BUT it seems Chrome and Gecko and WebKit don't fire an input event at all for radio buttons or checkboxes. I think we should merge this and file a new issue on the html spec about removing the input event. (Does Edge fire the input event?)

**Comment by cvrebert** [comment]
> Does Edge fire the input event?

No, it doesn't:
* https://connect.microsoft.com/IE/feedback/details/1883692
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10182111

**Comment by cvrebert** [comment]
@zcorpan Do you think an issue should be raised regarding the ordering of `click` and `change`?

**Comment by zcorpan** [comment]
@cvrebert Not necessary unless we think the spec should be changed for that, but I agree with your analysis in https://www.w3.org/Bugs/Public/show_bug.cgi?id=28985 so I suppose we should just wait for it to be fixed in the remaining browsers.

**Pull request merged**
