### PR TITLE
Update the encoding IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Confirmed no interesting differences. Please review the idlharness.html change I've pushed.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25428)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350164395)

**Comment by inexorabletash** [comment]
Why isn't [encoding/idlharness.html](https://github.com/w3c/web-platform-tests/blob/master/encoding/idlharness.html) updated to use this instead of inlining the IDL?

Or phrased differently: can you update the test to reference this, or explain why that's not appropriate here?

**Comment by lukebjerring** [comment]
You're right, it should, and Philip did, but the script blundered over the changes. @foolip can you dig them up and re-apply them. Sorry!

**Comment by foolip** [comment]
I found it in my reflog and pushed it again. @inexorabletash, can you review the change as a whole?

**Review by inexorabletash — APPROVED** [review]
Yay, lgtm.

We should make it an 'any.js' test and should probably scrub all the idlharness tests to figure out which actually need "untested" stuff but as long as this passes (it does, right?) then it's a good improvement - thanks!

**Comment by foolip** [comment]
> as long as this passes (it does, right?)

Figuring that out is unfortunately not straightforward. From https://pulls.web-platform-tests.org/build/25890 it looks like no tests were run, but that's wrong, from the Travis logs we can see that they were. Filed https://github.com/w3c/wpt-pullresults/issues/62. And yes, the tests do work still, as far as eyeballing differences goes.

**Pull request merged**
