### PR TITLE
HTML: Test negative timeout in setTimeout/setInterval

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/whatwg/html/pull/2506

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5380)

### CODE REVIEW

**Comment by annevk** [comment]
Note that you could use the .window.js convention as well though I'm not sure where the title should go in that case. (Might require async_test wrapper I suppose.)

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5380/)

**Comment by zcorpan** [comment]
@annevk yeah... seems like a wash though. Also can everyone run `.window.js` tests?

**Comment by annevk** [comment]
What you have is probably better. I think Chrome doesn't run them automatically just yet. Not sure about Firefox.

**Review by domenic — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218795768)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 36712423da0dc1bf424bd36d6c7193f5f953e40f
Using browser at version BuildID 20170404100210; SourceStamp b5d8b27a753725c1de41ffae2e338798f3b5cacd
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5380/html/webappapis/timers/negative-setinterval.html">/html/webappapis/timers/negative-setinterval.html</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| `Negative timeout in setInterval` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5380/html/webappapis/timers/negative-settimeout.html">/html/webappapis/timers/negative-settimeout.html</a></summary>


|             Subtest              | Results | Messages |
|----------------------------------|---------|----------|
|                                  | OK      |          |
| `Negative timeout in setTimeout` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218795769)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 36712423da0dc1bf424bd36d6c7193f5f953e40f
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations

**Comment by annevk** [comment]
@jugglinmike @bobholt is there a known issue with the Chrome bot? Unclear why it fails.

**Comment by bobholt** [comment]
@annevk: Unsure. After my change to `wptrunner` was merged yesterday, one PR (#5343) didn't run Chrome tests at all. All PRs since then, except this one, seem to have run correctly on Chrome. In this PR, the "push" build times out while the "pr" build passed as expected.

I'd like to believe this is a result of us pulling latest for both chrome-unstable and chromedriver and catching a bug. But, I'm not ready to write it off as that, yet. I'll do some more digging.

**Pull request merged**
