### PR TITLE
Move directional navigation tests from css-ui level 3 to level 4

### PR DESCRIPTION
**Pull request by frivoal**
Move tests for nav-* from l3 to l4

Change to match w3c/csswg-drafts@4e5fae0

### CODE REVIEW

**Comment by frivoal** [comment]
@FremyCompany, can you have a quick look at this? This should be trivial: just moving files and correcting white-space warnings from the linter. Thanks.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-10 13:01:31
Finished: 2017-08-10 13:07:21



View more information about this build on:

- [WPT Results Dashboard](http://pulls.web-platform-tests.org/build/17201)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263075124)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-10 13:01:31
Finished: 2017-08-10 13:07:21



View more information about this build on:

- [WPT Results Dashboard](http://pulls.web-platform-tests.org/build/17201)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263075124)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-10 13:01:31
Finished: 2017-08-10 13:07:21



View more information about this build on:

- [WPT Results Dashboard](http://pulls.web-platform-tests.org/build/17201)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263075124)

**Comment by gsnedders** [comment]
I think the current somewhat fuzzy policy is that we should be using unlevelled top-level directories for anything new, including new levels of existing specs.

**Comment by frivoal** [comment]
@gsnedders Isn't that in conflict with the idea that the top level directory should unambiguously designate a particular spec?

**Review by FremyCompany — APPROVED** [review]

**Comment by frivoal** [comment]
@jgraham or @gsnedders, can you add MS's @FremyCompany to the list of approved reviewers?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-10 13:21:04
Finished: 2017-08-10 13:25:14





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17204)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263076627)

**Pull request merged**
