### PR TITLE
Fix Edge installer

### PR DESCRIPTION
**Pull request by sadym-chromium**
Address "[Downloading msedgedriver fails on macOS](https://github.com/web-platform-tests/wpt/issues/36042)"

### CODE REVIEW

**Review by foolip — COMMENTED** [review]
Did this code work in the past, or did it never work?

We don't have a setup for Edge on macOS, but I guess you tried this locally?

**Comment by sadym-chromium** [comment]
> Did this code work in the past, or did it never work?

According to the issue, I assume the endpoint was removed for some reason.

> We don't have a setup for Edge on macOS, but I guess you tried this locally?

With the change applied, the command instsalls and runs the WPT tests correctly:
```
./wpt run --channel canary edgechromium
```

**Comment by mustjab** [comment]
Change looks fine, asked @bwalderman to help review as well as he added this code.

**Comment by sadym-chromium** [comment]
> LATEST_DEV isn't very useful. It's the latest Dev build of _any_ platform that was released, and it may not be a Mac build. We should understand why the driver installer fails to find an exact version match and falls back to trying LATEST_*_DEV.

Hopefully the PR https://github.com/web-platform-tests/wpt/pull/36372 should fix wpt.fyi for Edge. So I'm leaving this PR to you. Feel free either to merge it as an intermediate see l solution, or implement the proper one.

**Comment by bwalderman** [comment]
Thanks, I'll take a closer look today and verify #36372 solves the issue or implement an appropriate fix.

**Comment by mustjab** [comment]
Proper fix is tracked in #36382, closing this PR

**Pull request closed without merging**
