### PR TITLE
fix(WebCryptoAPI): remove unhandled rejections

### PR DESCRIPTION
**Pull request by panva**
This change 

- removes possible unhandled rejections (caused Deno's wpt runner to abort)
- allows CFRG and ECDH suites to run even when not all algorithms are supported (by handling import/generate key rejection)

### CODE REVIEW

**Comment by twiss** [comment]
Hey :wave: Apologies for the delay.

I agree that not supporting X448 shouldn't prevent the X25519 tests from running, for example, however, this change hides the X448 import error entirely, and replaces it with (imo) confusing failures in the subsequent X448 tests. I think it would be better to have a failing test (or setup) with the X448 import failure, and separately have the X25519 test results.

One (sort of brute force) way to do that would be to split the file in two, one for X25519 and one for X448. That might also simplify the helper functions a bit, since then there's only one key pair per test. (But, it might still be nice to split them out into a helper file, to share them between all curves. Or, we could do that later.)

**Comment by panva** [comment]
The approach follows other existing test files. Furthermore import errors need not to be prevailed given there are other import export specific tests in other files.

**Comment by panva** [comment]
I would propose to land this and I can then refactor all these in all files to assert import was successful before running the rest of the operations.

**Comment by twiss** [comment]
OK, fair enough. Sounds good :+1:

**Review by twiss — APPROVED** [review]

**Comment by panva** [comment]
@twiss thank you

**Pull request merged**
