### PR TITLE
Update link to Web Audio spec

### PR DESCRIPTION
**Pull request by foolip**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5618)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5618/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223897410)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223897412)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 4a45684deecbc0a28560e721f64e775959208f6f
Using browser at version BuildID 20170418100213; SourceStamp bb38d935d699e0529f9e0bb35578d381026415c4
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223897413)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 4a45684deecbc0a28560e721f64e775959208f6f
Using browser at version 59.0.3071.9 dev
Starting 10 test iterations
No tests run.

**Comment by foolip** [comment]
Ping @chrislo.

@padenot @rtoy, do you want to be in the OWNERS file for this test suite?

**Comment by padenot** [comment]
Yes, please.

**Comment by foolip** [comment]
Done in https://github.com/w3c/web-platform-tests/pull/5655. @padenot, in the meantime, can you review and merge this?

**Comment by padenot** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5618#-:-KiU4DJVCNYxq1Q2vkXw:bnfp4nl)*

**Comment by padenot** [comment]
@foolip, it looks like I don't have the right to merge this, but it looks fine.

**Pull request merged**
