### PR TITLE
CI on fork fixes

### PR DESCRIPTION
**Pull request by jeremypoulter**
These are changes I had to make to get Travis CI to  run without errors on a fork of the W3C repository.

1) removed some of the hard coded references to the W3C repository
2) require sudo needed for updating the hosts file

FYI the failure condition is;
1) Fork the W3C repository
2) Enable Travis CI on the fork
3) Travis CI fails on the fork where the w3c/master is succeeding

### CODE REVIEW

**Comment by jgraham** [comment]
So, I'm confused. This seems to work OK in e.g. https://github.com/w3c/web-platform-tests/pull/4289 ?

**Comment by jeremypoulter** [comment]
I am referring to running the CI on the actual fork of the repo, eg https://travis-ci.org/dlna/web-platform-tests/builds/181636271 not on a PR.

**Comment by jeremypoulter** [comment]
I have added additional changes to fix issues with the CI running on the master branch of the repository and also added the ability to change the repository used as a base when looking for changed files.

**Comment by jeremypoulter** [comment]
@jgraham Do you need any more explanation of the changes and the reasons for this change?

**Comment by jeremypoulter** [comment]
The same issue looks to have been fixed by #4566 so I am closing this PR. Personally I think this is a bit cleaner as it did not add globals, but no worries. I think there are still some other fixes that may be needed from this PR not in #4566 but I will raise a new PR if I see still see those.

**Pull request closed without merging**
