### PR TITLE
[css-multicol] Adjust tests to match spec

### PR DESCRIPTION
**Pull request by frivoal**
This commit updates the multicol test suite to match the spec after this
edit:
https://github.com/w3c/csswg-drafts/commit/2aa159022be731c2c95b06a267ecc7f1375590be

This is not an attempt at full coverage of this part of the spec. It is
only updating the tests that would otherwise be in contradiction with
the updated specification.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by frivoal** [comment]
@gsnedders @sideshowbarker I don't understand what travis is complaining about. Is this yet another problem in the build infrastructure, or is there something wrong with my tests?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245664788)

# Firefox (nightly) #
Testing web-platform-tests at revision 15e58aa6ca7b40177a150e25ca7cf959de90728b
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-001.xht">/css/css-multicol-1/multicol-block-no-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-002.xht">/css/css-multicol-1/multicol-block-no-clip-002.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-clip-001.xht">/css/css-multicol-1/multicol-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-003.xht">/css/css-multicol-1/multicol-count-computed-003.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-005.xht">/css/css-multicol-1/multicol-count-computed-005.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-gap-large-001.xht">/css/css-multicol-1/multicol-gap-large-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-width-small-001.xht">/css/css-multicol-1/multicol-width-small-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245664789)

# Sauce (safari) #
Testing web-platform-tests at revision 15e58aa6ca7b40177a150e25ca7cf959de90728b
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-001.xht">/css/css-multicol-1/multicol-block-no-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-002.xht">/css/css-multicol-1/multicol-block-no-clip-002.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-clip-001.xht">/css/css-multicol-1/multicol-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-003.xht">/css/css-multicol-1/multicol-count-computed-003.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-005.xht">/css/css-multicol-1/multicol-count-computed-005.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-gap-large-001.xht">/css/css-multicol-1/multicol-gap-large-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-width-small-001.xht">/css/css-multicol-1/multicol-width-small-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245664795)

# Chrome (unstable) #
Testing web-platform-tests at revision 15e58aa6ca7b40177a150e25ca7cf959de90728b
Using browser at version 61.0.3135.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-001.xht">/css/css-multicol-1/multicol-block-no-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-002.xht">/css/css-multicol-1/multicol-block-no-clip-002.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-clip-001.xht">/css/css-multicol-1/multicol-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-003.xht">/css/css-multicol-1/multicol-count-computed-003.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-005.xht">/css/css-multicol-1/multicol-count-computed-005.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-gap-large-001.xht">/css/css-multicol-1/multicol-gap-large-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-width-small-001.xht">/css/css-multicol-1/multicol-width-small-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245664796)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 15e58aa6ca7b40177a150e25ca7cf959de90728b
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-001.xht">/css/css-multicol-1/multicol-block-no-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-block-no-clip-002.xht">/css/css-multicol-1/multicol-block-no-clip-002.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-clip-001.xht">/css/css-multicol-1/multicol-clip-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-003.xht">/css/css-multicol-1/multicol-count-computed-003.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-count-computed-005.xht">/css/css-multicol-1/multicol-count-computed-005.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-gap-large-001.xht">/css/css-multicol-1/multicol-gap-large-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6312/css/css-multicol-1/multicol-width-small-001.xht">/css/css-multicol-1/multicol-width-small-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by sideshowbarker** [comment]
> I don't understand what travis is complaining about. Is this yet another problem in the build infrastructure, or is there something wrong with my tests?

Not a problem with your tests, so this can otherwise be merged after review as long as there is nothing else legitimate to block it.

The travis issue is this:

pypy is not installed; attempting download

Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2

```
pypy is not installed; attempting download
Downloading archive:
https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2
$ sudo tar xjf -.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf -.tar.bz2 --directory /" failed and exited with 2 during .
```

**Comment by gsnedders** [comment]
@frivoal Travis updated what Ubuntu VM we were using… and broke what their docs say works. :\

**Comment by frivoal** [comment]
Hi @rachelandrew, could you give a look at these test updates? I made these to make sure the tests did not get out of sync with the spec after changing to spec to match a WG resolution.

**Review by rachelandrew — APPROVED** [review]
I've tested this change locally and it looks good to me as a representation of the change to the spec, happy to approve.

**Comment by frivoal** [comment]
@rachelandrew Thanks. You need to use the "Review Changes" button on the "Files Changes" tab to let github know about your review to unlock the ability to merge the Pull Request.

I presume you have the right access rights for this. If not, let me know and we'll try to find a way to get you these access rights.

**Comment by rachelandrew** [comment]
@frivoal yeah - that's what I did. Marked it as approved, and the comment says "approved" so I'm not sure what I did wrong or if I don't have the rights to do so (but then perhaps I wouldn't have the button).

**Comment by frivoal** [comment]
@gsnedders @plinss @jgraham (not sure who's in charge), can you add @rachelandrew to the list of approved reviewers? As the co-editor of the css-multicol spec, she needs to be able to review & approve PR.

**Comment by jgraham** [comment]
>  can you add @rachelandrew to the list of approved reviewers?

Done

**Pull request merged**
