### PR TITLE
Meta-test on computed value of calc() functions inside [ linear | radial | conic ]-gradient functions

### PR DESCRIPTION
**Pull request by TalbotG**
At my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/calc-linear-radial-conic-gradient-001.html

More subtests can be, of course, added into this test.

  Blink (Chromium) Bug report 947377: [css-values-3] Values inside `<image>`s are not computed correctly / reflected correctly from getComputedStyle
  https://bugs.chromium.org/p/chromium/issues/detail?id=947377

  WebKit (Safari) Bug report 196389: [css-values-3] Computed value of calc() expression in linear-gradient function incorrect
  https://bugs.webkit.org/show_bug.cgi?id=196389

### CODE REVIEW

**Comment by fantasai** [comment]
Should there be any tests that combine units, e.g. `calc(10% + 10pc)`? Do we have such tests already?

**Comment by TalbotG** [comment]
> Should there be any tests that combine units, e.g. `calc(10% + 10pc)`? Do we have such tests already?

Testing calc() with mixed values is indeed rare or missing in the current css-values tests directory. There is only

http://wpt.live/css/css-values/getComputedStyle-calc-mixed-units-001.html

and

http://wpt.live/css/css-values/calc-background-position-002.html

So, I will create a test testing computed style (getComputedStyle()) of calc() with mixed length values (%, em, ex, pc, pt, px, cm, mm, Q, in,  vw, vh, vmin, vmax) . It is now on my to-do-list.

- - -

Regarding computed style of calc() functions inside [ linear | radial | conic ]-gradient with mixed values, it is also possible to do that only for the angle term.
eg `linear-gradient(calc(200grad - 90deg), rgb(0, 128, 0), rgb(0, 0, 255))`

A commit coming up in a few min...

**Comment by TalbotG** [comment]
New test is

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/calc-linear-radial-conic-gradient-001-new.html

I added line breaks inside the function.

I inserted the 'initial' value reset inside the nested function.

I added 2 linear-gradient sub-tests.

All 8 sub-tests use green and blue colors with rgb() functions. **Only percentages and angle values are tested with calc() functions.**

**Comment by TalbotG** [comment]
Now, I am going to close and reopen this pull request...

**Pull request closed without merging**
