### PR TITLE
Add initial test for peer connection state changes

### PR DESCRIPTION
**Pull request by soareschen**
~This is a work in progress.~ (Update: done)

I added few basic tests for the various connection state changes for the case when there is only one data channel. In this case there should be only one `RTCDtlsTransport` and one `RTCIceTransport` exist, accessible through the `sctp` attribute. With that we should be able to test for some states such as `completed`.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242363270)

# Firefox (nightly) #
Testing web-platform-tests at revision 412ab3e09876c7eb8df197c33654397c59b20161
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-connectionState.html">/webrtc/RTCPeerConnection-connectionState.html</a></summary>


|                                       Subtest                                        | Results |                                                           Messages                                                          |
|--------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------|
|                                                                                      | OK      |                                                                                                                             |
| `Initial connectionState should be new`                                              | FAIL    | `assert_equals: expected (string) "new" but got (undefined) undefined`                                                      |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `assert_equals: Expect connection to have connectionstatechange event expected (object) null but got (undefined) undefined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-iceConnectionState.html">/webrtc/RTCPeerConnection-iceConnectionState.html</a></summary>


|                                       Subtest                                        | Results |         Messages        |
|--------------------------------------------------------------------------------------|---------|-------------------------|
|                                                                                      | OK      |                         |
| `Initial iceConnectionState should be new`                                           | PASS    |                         |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `pc1.sctp is undefined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-iceGatheringState.html">/webrtc/RTCPeerConnection-iceGatheringState.html</a></summary>


|                                       Subtest                                        | Results |         Messages        |
|--------------------------------------------------------------------------------------|---------|-------------------------|
|                                                                                      | OK      |                         |
| `Initial iceGatheringState should be new`                                            | PASS    |                         |
| `iceGatheringState should eventually become complete after setLocalDescription`      | PASS    |                         |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `pc2.sctp is undefined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242363271)

# Sauce (safari) #
Testing web-platform-tests at revision 412ab3e09876c7eb8df197c33654397c59b20161
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-connectionState.html">/webrtc/RTCPeerConnection-connectionState.html</a></summary>


|                                       Subtest                                        | Results |                 Messages                 |
|--------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                      | OK      |                                          |
| `Initial connectionState should be new`                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-iceConnectionState.html">/webrtc/RTCPeerConnection-iceConnectionState.html</a></summary>


|                                       Subtest                                        | Results |                 Messages                 |
|--------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                      | OK      |                                          |
| `Initial iceConnectionState should be new`                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6224/webrtc/RTCPeerConnection-iceGatheringState.html">/webrtc/RTCPeerConnection-iceGatheringState.html</a></summary>


|                                       Subtest                                        | Results |                 Messages                 |
|--------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                      | OK      |                                          |
| `Initial iceGatheringState should be new`                                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `iceGatheringState should eventually become complete after setLocalDescription`      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `connection with one data channel should eventually have connected connection state` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242363279)

# Chrome (unstable) #
Testing web-platform-tests at revision 412ab3e09876c7eb8df197c33654397c59b20161
Using browser at version 61.0.3124.4 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242363280)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 412ab3e09876c7eb8df197c33654397c59b20161
Using browser at version 14.14393
Starting 10 test iterations

**Comment by soareschen** [comment]
I have reorganized the comments to report coverage. If my interpretation for the state changes is correct, this PR is ready for review and merging.

**Review by rwaldron — APPROVED** [review]

**Pull request merged**
