### PR TITLE
Generic Sensor: Update Web IDL tests to align with latest spec

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@tobie, Could you PTAL?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240620074)

# Firefox (nightly) #
Testing web-platform-tests at revision 84e79841224f94981de2dd9163222448fcc6ae8d
Using browser at version BuildID 20170607100302; SourceStamp 5801aa478de12a62b2b2982659e787fcc4268d67
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6182/magnetometer/idlharness.https.html">/magnetometer/idlharness.https.html</a></summary>


|                                                           Subtest                                                            | Results |                                                                       Messages                                                                      |
|------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                              | OK      |                                                                                                                                                     |
| `Magnetometer interface: existence and properties of interface object`                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface object length`                                                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface object name`                                                                                         | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: existence and properties of interface prototype object`                                             | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: existence and properties of interface prototype object's "constructor" property`                    | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute x`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute y`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute z`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: new Magnetometer(); must inherit property "x" with the proper type (0)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "y" with the proper type (1)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "z" with the proper type (2)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `UncalibratedMagnetometer interface: existence and properties of interface object`                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface object length`                                                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface object name`                                                                             | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object`                                 | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object's "constructor" property`        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute x`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute y`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute z`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute xBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute yBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute zBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "x" with the proper type (0)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "y" with the proper type (1)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "z" with the proper type (2)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "xBias" with the proper type (3)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "yBias" with the proper type (4)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "zBias" with the proper type (5)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6182/orientation-sensor/idlharness.https.html">/orientation-sensor/idlharness.https.html</a></summary>


|                                                                          Subtest                                                                          | Results |                                                                       Messages                                                                       |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                           | OK      |                                                                                                                                                      |
| `OrientationSensor interface: existence and properties of interface object`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface object length`                                                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface object name`                                                                                                                 | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: existence and properties of interface prototype object`                                                                     | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                            | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: attribute quaternion`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: operation populateMatrix(RotationMatrixType)`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `AbsoluteOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new AbsoluteOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `RelativeOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new RelativeOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240620075)

# Sauce (safari) #
Testing web-platform-tests at revision 84e79841224f94981de2dd9163222448fcc6ae8d
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6182/magnetometer/idlharness.https.html">/magnetometer/idlharness.https.html</a></summary>


|                                                           Subtest                                                            | Results |                                                                          Messages                                                                         |
|------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                              | OK      |                                                                                                                                                           |
| `Magnetometer interface: existence and properties of interface object`                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface object length`                                                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface object name`                                                                                         | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: existence and properties of interface prototype object`                                             | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: existence and properties of interface prototype object's "constructor" property`                    | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: attribute x`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: attribute y`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: attribute z`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                            |
| `Magnetometer interface: new Magnetometer(); must inherit property "x" with the proper type (0)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: Magnetometer"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "y" with the proper type (1)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: Magnetometer"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "z" with the proper type (2)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: Magnetometer"`             |
| `UncalibratedMagnetometer interface: existence and properties of interface object`                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface object length`                                                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface object name`                                                                             | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object`                                 | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object's "constructor" property`        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute x`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute y`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute z`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute xBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute yBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: attribute zBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`                    |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "x" with the proper type (0)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "y" with the proper type (1)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "z" with the proper type (2)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "xBias" with the proper type (3)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "yBias" with the proper type (4)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "zBias" with the proper type (5)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: UncalibratedMagnetometer"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6182/orientation-sensor/idlharness.https.html">/orientation-sensor/idlharness.https.html</a></summary>


|                                                                          Subtest                                                                          | Results |                                                                          Messages                                                                          |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                           | OK      |                                                                                                                                                            |
| `OrientationSensor interface: existence and properties of interface object`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface object length`                                                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface object name`                                                                                                                 | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface: existence and properties of interface prototype object`                                                                     | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                            | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface: attribute quaternion`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `OrientationSensor interface: operation populateMatrix(RotationMatrixType)`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                                   |
| `AbsoluteOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`                   |
| `AbsoluteOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`                   |
| `AbsoluteOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`                   |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`                   |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`                   |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: AbsoluteOrientationSensor"` |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: AbsoluteOrientationSensor"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new AbsoluteOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: AbsoluteOrientationSensor"` |
| `RelativeOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`                   |
| `RelativeOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`                   |
| `RelativeOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`                   |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`                   |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`                   |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: RelativeOrientationSensor"` |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: RelativeOrientationSensor"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new RelativeOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Can't find variable: RelativeOrientationSensor"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240620081)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240620082)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 84e79841224f94981de2dd9163222448fcc6ae8d

**Comment by Honry** [comment]
@alexshalamov or @pozdnyakov, PTAL.

**Review by alexshalamov — APPROVED** [review]

**Comment by Honry** [comment]
@alexshalamov, thanks, I'd like to merge it directly.

**Pull request merged**
