### PR TITLE
Switch to in-tree wptrunner for stability_check

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5722)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5722/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226484921)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226484923)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 4c03d47702e239f9d1576da14c0aee8635567aff

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226484929)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 4c03d47702e239f9d1576da14c0aee8635567aff

**Review by jugglinmike — APPROVED** [review]
[Here's the relevant output from the build log](https://travis-ci.org/w3c/web-platform-tests/jobs/226496615#L395):

>     DEBUG:check_stability:pip install /home/travis/build/w3c/web-platform-tests/tools/wptrunner

Meaning this patch works as intended. Thanks, @jgraham!

**Pull request merged**
