### PR TITLE
Make screen-orientation tests fail early if orientation is unsupported

### PR DESCRIPTION
**Pull request by zcorpan**
Part of #11269.

---

The tests still time out if orientation is supported but the event is not fired or so; not sure if anything can be done about that, assuming the tests are correct.

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
Looks ok... if it's still being problematic, we can try some refactoring.

**Comment by zcorpan** [comment]
@kaixinjxq does #10701 also happen to address the same issue we're trying to fix here?

**Comment by kaixinjxq** [comment]
@zcorpan, not exactly, but I just added a new commit to fix the timeout issue if `screen.orientation.lock` is not supported.

**Comment by zcorpan** [comment]
OK let's close this in favor of your PR :)

**Pull request closed without merging**
