### PR TITLE
Add retry logic for downloading Chrome in TaskCluster

### PR DESCRIPTION
**Pull request by stephenmcgruer**
In `run_tc.py`, we install Chrome by downloading a deb package from
https://dl.google.com/linux/direct/{package_name}. This download has been
flaking heavily lately, so this PR changes that code to use `download_url_to_descriptor`
which retries (by default) 3 times before giving up on the download. This works
around underlying network flake but doesn't actually fix anything.

See https://github.com/web-platform-tests/wpt/issues/21529

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I'm going to kick this a few times in a row, to try and reproduce one of the cases where downloading Chrome fails and check that the retry logic works. Excuse the spam :)

**Comment by stephenmcgruer** [comment]
Excellent, success in reproducing: https://community-tc.services.mozilla.com/tasks/cFdt42QVTeyKQ1sEZ6CLgA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FcFdt42QVTeyKQ1sEZ6CLgA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

@Hexcles - PTAL

**Review by foolip — APPROVED** [review]
Can you add to the description an explanation of why this causes the retry to kick in? It's not easy to spot, where run_tc.py is called there's no explicit retry wrapping.

**Review by Hexcles — APPROVED** [review]
Funny branch name :)

**Comment by Hexcles** [comment]
Grrh and now it's hypothesis again. Yikes. I'll suppress the warning even more, and force-merge this PR.

https://community-tc.services.mozilla.com/tasks/CV29mIv_RWCSwFiXm3LKAA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FCV29mIv_RWCSwFiXm3LKAA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L344-350

**Comment by foolip** [comment]
It looks like this didn't work, it's not retrying:
https://community-tc.services.mozilla.com/tasks/ft2jPkzhSGWgEUoa76j2pQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fft2jPkzhSGWgEUoa76j2pQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by foolip** [comment]
Oh wait, ignore me. It's retrying but not at the layer I thought it would. It even got to "Try 4/3" before giving up :)

**Comment by stephenmcgruer** [comment]
> It looks like this didn't work, it's not retrying:

It is retrying. It clearly says in those logs:

> INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 1/3
> ERROR: Connection reset by peer. Retrying ...
> INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 2/3
> ERROR: Connection reset by peer. Retrying ...
> INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 3/3
> ERROR: Connection reset by peer. Retrying ...
> INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 4/3
> Traceback (most recent call last):

It just failed every time it tried. See my update in https://github.com/web-platform-tests/wpt/issues/21529#issuecomment-613974062

**Pull request merged**
