### PR TITLE
[WebDriver BiDi] fix `test_release_mouse_sequence_resets_dblclick_state`

### PR DESCRIPTION
**Pull request by sadym-chromium**
* Move test to tentative, as the expected behavior is not clear yet.
* Remove parameter, as the double click is tested in [`test_dblclick_at_coordinates`](https://github.com/web-platform-tests/wpt/blob/077700f9850d358be790ff1fb86b79871f2ccf9a/webdriver/tests/bidi/input/perform_actions/pointer_mouse_multiclick.py#L66C35-L66C43).

### CODE REVIEW

**Comment by whimboo** [comment]
@sadym-chromium could you maybe explain what is/was broken with the test?

**Comment by sadym-chromium** [comment]
> @sadym-chromium could you maybe explain what is/was broken with the test?

sure!
1. The test `test_release_mouse_sequence_resets_dblclick_state` checks both with and without release, which is confusing. 
2. Moving it to tentative until the https://github.com/w3c/webdriver/issues/1772 is clarified.

**Comment by sadym-chromium** [comment]
> @sadym-chromium could you maybe explain what is/was broken with the test?

3. If there is no `release` actions, why the `dblclick` should be absent at all?

**Comment by whimboo** [comment]
>     2. Moving it to tentative until the [Clarify how the double click tracking should work in the actions w3c/webdriver#1772](https://github.com/w3c/webdriver/issues/1772) is clarified.

Would you mind renaming the test so that it includes `tentative` in its name?

**Comment by sadym-chromium** [comment]
> Would you mind renaming the test so that it includes `tentative` in its name?

done

**Comment by whimboo** [comment]
You moved the test below a `tentative` folder which is not what we usually do for tentative wpt tests. As mentioned in my review please add the word to the test name: `webdriver/tests/bidi/input/release_actions/sequence_tentative.py`

Otherwise I assume (didn't check the changes directly) it is just moving the existing tests without any further changes?

**Comment by sadym-chromium** [comment]
> You moved the test below a `tentative` folder which is not what we usually do for tentative wpt tests. As mentioned in my review please add the word to the test name: `webdriver/tests/bidi/input/release_actions/sequence_tentative.py`

Got it. Done.

> Otherwise I assume (didn't check the changes directly) it is just moving the existing tests without any further changes?

Yes.

**Comment by sadym-chromium** [comment]
@whimboo any other concerns?

**Review by whimboo — APPROVED** [review]

**Pull request merged**
