### PR TITLE
#19326 resolved

### PR DESCRIPTION
**Pull request by prsmahajan**

### CODE REVIEW

**Review by foolip — CHANGES_REQUESTED** [review]
I notice this doesn't change the path data, so the problem isn't fixed.

**Comment by prsmahajan** [comment]
What problems are you facing now?

**Comment by foolip** [comment]
@prsmahajan I'm sorry but I don't have the bandwidth to guide you to a fix for this in the details, if you don't feel like you can tackle the original size mismatch issue without further hints, then I'd suggest looking for another issue that you can see clearly how to solve without assistance.

**Comment by prsmahajan** [comment]
@foolip There is no sizing problem, I have checked senior. Can you send me any gif or ss you're seeing or facing?

**Comment by prsmahajan** [comment]
]

**Comment by zcorpan** [comment]
If you compare https://github.com/web-platform-tests/wpt/blob/master/images/wpt-logo/wpt-logo-darkblue.svg to e.g. https://github.com/web-platform-tests/wpt/blob/master/images/wpt-logo/wpt-logo-darkblue-bg.svg you'll notice the latter has more spacing around it. That's the issue described in #19326.

My suggestion would be to take https://github.com/web-platform-tests/wpt/blob/master/images/wpt-logo/wpt-logo-darkblue.svg as the basis for the other logos  (`viewBox` and `path` values for all logos should match this one), and change the colors to match those of the other logos. The ones with a background still need a `rect` element for the background color, and its `width` and `height` attributes should match what's in `viewBox`.

**Comment by foolip** [comment]
Closing this PR due to inactivity. @prsmahajan feel free to open a new PR if you'd like to continue this work.

**Pull request closed without merging**
