### PR TITLE
Move XMLHttpRequest/ to xhr/

### PR DESCRIPTION
**Pull request by foolip**
Like https://github.com/w3c/web-platform-tests/pull/8895 for quirks,
this adapts to https://github.com/whatwg/xhr/pull/184, after which the
wpt links are generated and match the shortname.
https://xhr.spec.whatwg.org/ currently has a 404 link to
https://github.com/w3c/web-platform-tests/tree/master/xhr.

Steps taken:
 * rename the directory
 * sed 's#/XMLHttpRequest#/xhr#g' everywhere
 * manually handle a few remaining cases of "XMLHttpRequest/"
 * look at ouput of grep -E '\SXMLHttpRequest' and 'XMLHttpRequest[^(;]'

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8937)

### CODE REVIEW

**Comment by foolip** [comment]
Split into a few commits for ease of review, please squash as a single commit using the description of the PR. (The sed step is split more than described, but just for ease of review.)

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2018-01-05 23:17:46
Finished: 2018-01-06 00:07:16


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:dev</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22440)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/325651411)

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
@jgraham it seems you might need to land this because of the Firefox bot timing out.

**Comment by foolip** [comment]
Jobs for the other browsers are also failing, but those failures aren't blocking. Root cause is https://github.com/w3c/web-platform-tests/issues/7660.

I'll merge.

**Pull request merged**
