### PR TITLE
Revert "Reland #2 "Implement CSSTransitionDiscrete which enables transitions on discrete properties.""

### PR DESCRIPTION
**Pull request by graouts**
Reverts web-platform-tests/wpt#38812

This made at least two tests fail across all browsers:

[css/css-transitions/animations/vertical-align-interpolation.html](https://wpt.fyi/results/css/css-transitions/animations/vertical-align-interpolation.html?label=master&label=experimental&product=chrome&product=firefox&product=safari-164%20preview&product=safari-165%20preview&view=subtest)
[css/css-transitions/animations/z-index-interpolation.html](https://wpt.fyi/results/css/css-transitions/animations/z-index-interpolation.html?label=master&label=experimental&product=chrome&product=firefox&product=safari-164%20preview&product=safari-165%20preview&view=subtest)
This was caught by the checks on this PR but somehow they appeared green, maybe because the WPT.fyi checks are in beta. It appears there are a lot of regressions:

https://wpt.fyi/results/css?diff&filter=ADC&run_id=5094539348410368&run_id=5077352225177600

Either this change is correct and a fair few tests need to be updated to have new expectations, or this test is wrong. Either way, I think this should be reverted until this is addressed.

Cc @josepharhar and @flackr

### CODE REVIEW

**Review by gsnedders — APPROVED** [review]

**Comment by josepharhar** [comment]
These test changes were based on this CSSWG resolution: https://github.com/w3c/csswg-drafts/issues/4441#issuecomment-1351867996
Can we add them back?

**Comment by dbaron** [comment]
Also worth noting the spec edits for this happened in https://github.com/w3c/csswg-drafts/pull/8520

**Comment by graouts** [comment]
> These test changes were based on this CSSWG resolution: [w3c/csswg-drafts#4441 (comment)](https://github.com/w3c/csswg-drafts/issues/4441#issuecomment-1351867996)
> Can we add them back?

I should think the tests ought to be fixed to match the spec so that there are no failures, even if the failures are now expected.

**Comment by dbaron** [comment]
What class of failures do you want to avoid?  (That is, what do you mean by "no failures, even if the failures are now expected"?)

I think it's normal that if a spec changes so that an implementation no longer conforms to the spec, that implementation *should* start failing tests -- it's a good way to notice that the spec has changed.

**Comment by graouts** [comment]
I'm expecting that the tests related to transitions and discrete properties are modified to produce PASS results when the implementation is correct. Right now there are heaps of tests yielding FAIL results. I just want to be sure this is correct and the tests will PASS once implementations implement the spec change. An example are the two tests highlighted in my original PR message.

If those tests now FAIL'ing are doing so correctly, then this PR should be landed back, by all means.

**Comment by dbaron** [comment]
Based on https://chromium-review.googlesource.com/c/chromium/src/+/4308075 those tests were passing in patched Chromium.  (There's no entry for them in `TestExpectations` and no `*-expected.txt` file.)

The Chromium you see on the "experimental" channel for wpt.fyi is dev channel, which can often be a week or two behind.

**Comment by graouts** [comment]
OK, then I guess this is good. Thanks for providing all the extra information, this helped.

**Comment by josepharhar** [comment]
I made a PR to re-add the test changes: https://github.com/web-platform-tests/wpt/pull/38936

**Pull request merged**
