### PR TITLE
[css-ui] Inheritance and initial value

### PR DESCRIPTION
**Pull request by ewilligers**
Test that CSS Basic User Interface properties inherit.
Test that initial values match the spec.
https://drafts.csswg.org/css-ui/#property-index

### CODE REVIEW

**Comment by foolip** [comment]
The failing Travis build in this PR was due to https://github.com/web-platform-tests/wpt/issues/13112, which has now been resolved. To recover, rebase the PR on master and push. (Simply restarting the Travis jobs may also work, not tested.)

**Review by svgeesus — COMMENTED** [review]
LGTM

**Comment by ewilligers** [comment]
@svgeesus can you please merge this. GitHub tells me "Review required".

**Review by foolip — APPROVED** [review]
Glossy review LGTM

**Comment by frivoal** [comment]
Hmmm. Sorry for the slow review. I think we should actually revert / fix this:
* For color properties, getComputedStyle returns the used value, not the computed value. They are different, but your asserts are written assuming the computed value. Hence why you get `rgb(…)` when you were expecting `auto`.
* For the `invert` color of the outline-color property, you should check if the `invert` keyword is supported at all. If it is, it should be the initial value, but if it is not, having `currentColor` be the initial value is spec compliant, and should not cause the test to fail.

**Comment by frivoal** [comment]
Just noticed you had filed a follow up in #13748 will continue discussing there.

**Pull request merged**
