### PR TITLE
Allow tests in test group to be a partial list

### PR DESCRIPTION
**Pull request by WeizhongX**
Run with a partial list, now test can run to complete
Bug: 1175457

### CODE REVIEW

**Review by stephenmcgruer — CHANGES_REQUESTED** [review]
As someone who doesn't know much about test groups, it isn't clear to me what is actually changing here. ("Now the test can run to complete" in the description does not explain much to a reader.)

Can you clarify what the old and new behavior is here, and why we want to change?

Separately, the fact that no unittest (e.g. in `tools/wptrunner/wptrunner/tests/test_testloader.py`) failed here is very concerning, and I would like to see a test added for this case (that would have failed before and passes now).

**Comment by WeizhongX** [comment]
Hi Stephen, thanks for the comments, and sorry for being not clear at the beginning.

For the "run to complete", I mean the line "raise" is not reached, if I run wpt with arguments "--test-groups foo.json", with foo.json with below content:
{
    "badging": [
        "/badging/badge-error.https.html",
        "/badging/badge-success.https.html",
        "/badging/idlharness.https.any.html",
        "/badging/idlharness.https.any.worker.html"
    ]
}

Looks old code requires each id be in at least one group, so that it won't met KeyError. Given the fact new test cases are added from time to time, I would argue this is not possible.

One use is to use this capability to exclude some test cases.

For the unittest, I did not see how to add it with an initial glance. Let me check with offline.

thanks!

**Comment by stephenmcgruer** [comment]
> if I run wpt with arguments "--test-groups foo.json", with foo.json with below content:

Pre-amble: In this case I am assuming you mean a command-line like `./wpt run --log-mach=- --test-groups=foo.json --channel=dev chrome`. Most importantly that this command-line implicitly asks wpt to run **all** tests (by not specifying any via `--include` or via listing them as command args).

This seems like a fundamental change in how `--test-groups` works, and so I would like to hear from @jgraham as I believe Mozilla are the ones currently using this flag. 

To be clear, I believe the high-level change that WeizhongX is trying to add to WPT is the ability to run a set of tests based on an input file, rather than listing them on the command-line. I initially suggested they look at augmenting `--test-groups` as it seemed to be involved in shaping test loading, which may or may not have been misleading (apologies if it was). It is possible we will need to add a new flag (e.g. `--include-file`?) instead.

**Comment by jgraham** [comment]
So, for gecko, we generate the test groups json as part of the decision task for CI, so it's fully up to date with the tests in that commit. We then pass in the list of groups for a specific chunk via the command line. So the check being removed is a useful integrity check for us.

There are already an "interesting" number of ways to specify tests so it's possible that something already exists that meets your needs depending on what they are. For example the "include manifest" format allows passing in a file that causes only certain directories to run (servo uses this; see https://github.com/servo/servo/blob/master/tests/wpt/include.ini ).

**Comment by WeizhongX** [comment]
Thank you, @jgraham! I am actually interested in how "--test-groups" can be used. The help message says "Path to json file containing a mapping {group_name: [test_ids]}". Is group_name used in any places?

**Comment by jgraham** [comment]
If you pass `--test-groups` and then group names on the command line we convert the group name into a list of paths: https://searchfox.org/mozilla-central/source/testing/web-platform/tests/tools/wptrunner/wptrunner/testloader.py#62

**Comment by WeizhongX** [comment]
Thanks, I will close this pull request.

**Pull request closed without merging**
