### PR TITLE
Update WebIDL2

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5665)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5665/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225250808)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225250810)

# Firefox (nightly channel) #
Testing web-platform-tests at revision f1bb3f0d65066fcd1eb8f80c87d4121eb2323473
Ignoring 26 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225250818)

# Chrome (unstable channel) #

**Comment by annevk** [comment]
I don't think I can review this. I'm not familiar with this code at all. @marcosc touched it a few times?

**Comment by jgraham** [comment]
@ayg Can you review this?

**Comment by ayg** [comment]
I ran all the idlharness tests through Firefox as suggested by @jgraham on IRC, and the only one whose results changed was a syntax error that I submitted a fix for in #5703.

**Pull request merged**
