### PR TITLE
wpt run for chome on android

### PR DESCRIPTION
**Pull request by kereliuk**
This allows running wpt for Chrome on android devices.

Not sure how we want to document this since it currently requires the additional step of starting adb manually and changing a system file on the android device. In the future we want to remove these constraints somehow.

Also I am not sure whether it makes more sense to refer to Chrome on android as Chrome on another platform, or as a different product. Currently this is implemented as if it was another product.

cc/ @Hexcles

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8987)

### CODE REVIEW

**Comment by kereliuk** [comment]
This is still experimental and things like automatically port forwarding to and from the android device haven't been done yet.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-10 23:19:19
Finished: 2018-01-10 23:35:07





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22616)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/327461414)

**Comment by jgraham** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/_running-tests/chrome_android.md, line 18 at r3](https://reviewable.io:443/reviews/w3c/web-platform-tests/8987#-L2_s1xaQ12kB_2TWlYJ:-L2_s1xbXMYSIq1CuVjJ:b-9caijx) ([raw file](https://github.com/w3c/web-platform-tests/blob/996017fe817be6161b892d5940ce64155a78510f/docs/_running-tests/chrome_android.md#L18)):*
> ```Markdown
> 
> ```
> adb start-server
> ```

Seems like this part and the port forwarding could be part of the setup code in wptrunner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/8987)*

**Review by jgraham — APPROVED** [review]
Sure, although I would like to see more of the setup moved into the code rather than being manual steps.

istr with FirefoxOS that we had a similar problem with the hosts and maybe wrote the hosts file on the (rooted) device during setup? But it's a long time ago :)

**Comment by jgraham** [comment]
https://github.com/w3c/wptrunner/blob/20c17b59ccaab4f849bab75f807cb4a8855e212c/wptrunner/browsers/b2g.py#L62 is what we used for b2g (FirefoxOS).

**Comment by kereliuk** [comment]
@jgraham Thanks! I'll check these out and send a follow up PR later with some more stuff in the code and not manual.

**Pull request merged**
