### PR TITLE
Add wptrun support for servo.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6029)

### CODE REVIEW

**Review by AutomatedTester — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235182963)

# Firefox (nightly) #
Testing web-platform-tests at revision a5c8cb46885c52ce51b14a5ad4f96877df9835d1
Using browser at version BuildID 20170523100217; SourceStamp 5bc1c758ab57c1885dceab4e7837e58af27b998c
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235182964)

# Sauce (safari) #
Testing web-platform-tests at revision a5c8cb46885c52ce51b14a5ad4f96877df9835d1
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235182970)

# Chrome (unstable) #
Testing web-platform-tests at revision a5c8cb46885c52ce51b14a5ad4f96877df9835d1
Using browser at version 60.0.3100.0 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235182971)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision a5c8cb46885c52ce51b14a5ad4f96877df9835d1
Using browser at version 14.14393
Starting 10 test iterations

**Pull request merged**
