### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mattl**
Added link to BrowserStack.

This can be merged in once we are using BrowserStack (See https://github.com/w3c/wptdashboard/issues/112)

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7961)

### CODE REVIEW

**Comment by mattl** [comment]
Making this now for open ticket with BrowserStack, but don't merge until we're actually using them please.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-23 21:28:29
Finished: 2017-10-23 21:44:51


<h2>Failing Jobs</h2>
<ul>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19831)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/291752825)

**Comment by jgraham** [comment]
I think this kind of thing would be better on the `wpt.fyi` website, since the infrastructure is specifically for that service.

**Comment by foolip** [comment]
@mattl, I'm guessing this should be closed now?

**Pull request closed without merging**
