### PR TITLE
add Response test for propagating underlying ReadableStream error

### PR DESCRIPTION
**Pull request by anthumchris**
When a Response is constructed with ReadableStream, errors originating in that
ReadableStream are not propagated to the Response during a Promise rejection.
Tests throw errors in start() and pull() methods.

https://github.com/whatwg/fetch/issues/676

### CODE REVIEW

**Comment by AnthumChris** [comment]
This is my first experience writing WPT.  Please let me know if this should be moved/renamed/changed

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25640)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350922237)

**Comment by annevk** [comment]
Thanks for these! Much appreciated. Would you mind updating them to use the `return promise_rejects` pattern documented at http://web-platform-tests.org/writing-tests/testharness-api.html? That would make them a little easier to read. There's also no need to document the issue in the test itself. We can do that as part of the commit message.

**Comment by AnthumChris** [comment]
@annevk All set. Thanks for the recommendation.

**Comment by annevk** [comment]
@yutakahirano could you have a final look at these?

**Review by annevk — APPROVED** [review]

**Comment by yutakahirano** [comment]
lgtm

**Comment by annevk** [comment]
@AnthumChris did you happen to file browser bugs on the browsers that fail these tests?

**Comment by AnthumChris** [comment]
@annevk I have not filed browser bugs for these and could do that if needed.  Please let me know if there's an official workflow to follow too

**Comment by annevk** [comment]
@AnthumChris there's no templates at the moment though maybe I should create some guidance somewhere. Basically file a bug and say http://w3c-test.org/fetch/api/response/response-error-from-stream.html fails. I think at this point only Chrome and Safari need a bug because the other browsers haven't shipped `ReadableStream` yet.

**Comment by AnthumChris** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=821049
https://bugreport.apple.com/web/?problemID=38379432
https://bugzilla.mozilla.org/show_bug.cgi?id=1444944

@annevk Firefox offers support when flags are enabled, and I reported to ensure they catch it.

**Comment by annevk** [comment]
Great, thanks! For Safari you can file public bugs over at https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=HTML%20DOM btw.

**Comment by annevk** [comment]
It seems we have advice for this over at https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#handling-pull-requests. I'll try to remember linking that going forward.

**Pull request merged**
