### PR TITLE
Updating Safari executor to be able to execute wdspec tests

### PR DESCRIPTION
**Pull request by jimevans**

### CODE REVIEW

**Comment by jimevans** [comment]
@burg Can you see if this is the right way to enable Safari's driver for `wdspec` tests?

**Review by jgraham — APPROVED** [review]

**Comment by burg** [comment]
@jimevans What's the simplest way to test that out from wpt trunk?

**Comment by jimevans** [comment]
@burg Easiest is to do something like this:

    ./wpt run safari webdriver --test-type wdspec --webdriver-binary /path/to/safaridriver 

If things run in the browser, you’re good.

**Comment by burg** [comment]
It seems to work:

Ran 1146 checks (89 tests, 1057 subtests)
Expected results: 833
Unexpected results: 313
  test: 1 (1 timeout)
  subtest: 312 (308 fail, 4 error)

**Pull request merged**
