### PR TITLE
Only do travis branch builds on master

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5704)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5704/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226044939)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226044943)

# Firefox (nightly channel) #
Testing web-platform-tests at revision c9287170e88df9e5157303667eaa85bdbaeb06e4
Using browser at version BuildID 20170426100344; SourceStamp 0f5ba06c4c5959030a05cb852656d854065e2226
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226044949)

# Chrome (unstable channel) #
Testing web-platform-tests at revision c9287170e88df9e5157303667eaa85bdbaeb06e4

**Review by jugglinmike — APPROVED** [review]
Documentation for this functionality is available here: https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches

So this looks good to me!

**Pull request merged**
