### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by LukeZielinski**

### CODE REVIEW

**Review by lukebjerring — APPROVED** [review]

**Review by jugglinmike — APPROVED** [review]

**Review by foolip — APPROVED** [review]

**Comment by jugglinmike** [comment]
The failure reported by TravisCI is unrelated. It seems to be a flaky test, though I can't reproduce it locally. I've filed a separate issue to track that and restarted the CI job for this patch. I'll merge this once that passes (fingers crossed).

**Comment by jugglinmike** [comment]
Failed again, only this time with a time out. More data for gh-14179, but still not something that should block this patch. Let's try once more.

**Comment by jugglinmike** [comment]
And another failure. This may be blocked by gh-14179. @foolip has admin privileges, and I think those allow him to merge despite the failure.

**Comment by foolip** [comment]
Yep, I'll merge. Note that the Azure Pipelines failure is due to https://github.com/web-platform-tests/wpt/issues/13803.

**Pull request merged**
