### PR TITLE
s/NFC/NDEF/g in NFC interfaces and dictionaries

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This CL renames NFCReader to NDEFReader, NFCWriter to NDEFWriter,
NFCReadingEvent to NDEFReadingEvent, NFCScanOptions to NDEFScanOptions,
NFCPushOptions to NDEFPushOptions, and NFCError to NDEFError as
suggested in Web NFC spec at https://github.com/w3c/web-nfc/pull/392

Bug: 520391
Change-Id: Ifc7d26d68b76bbf771a83cba94fc275819c28cfb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1869227
Reviewed-by: Mike West <mkwst@chromium.org>
Reviewed-by: Rijubrata Bhaumik <rijubrata.bhaumik@intel.com>
Commit-Queue: François Beaufort <beaufort.francois@gmail.com>
Cr-Commit-Position: refs/heads/master@{#707736}

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Attempting to unblock the Chromium WPT exporter, which is blocked on this CL due to conflicting upstream changes in WPT: https://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket.appspot.com/8898990248848418704/+/steps/Export_Chromium_commits_and_in-flight_CLs_to_WPT/0/stdout

It looks like interfaces/web-nfc.idl was modified manually in the patch (uh-oh), and simultaneously automatically updated in WPT. This PR reverts the interfaces/web-nfc.idl changes in favour of the upstream version, since that should match the spec.

**Review by foolip — APPROVED** [review]
Rubber stamp

**Comment by foolip** [comment]
@stephenmcgruer to make sure nothing unexpected is happening here, 9f8e5f67582ccdef98faa436aa5996f2b6ffe207 didn't touch interfaces/web-nfc.idl. The intention is that this will cause the changes to be reverted by import on the Chromium side, right?

**Comment by foolip** [comment]
@stephenmcgruer it also looks like the original committer (and date) wasn't preserved. Did you see https://github.com/foolip/ecosystem-infra-rotation/blob/master/docs/export.md or skip them because they're too verbose? Nothing bad will happen as a result, just checking.

**Comment by stephenmcgruer** [comment]
> The intention is that this will cause the changes to be reverted by import on the Chromium side, right?

Correct; the expectation is that the upstream reffy-generated changes should override the downstream changes. My understanding is that those files should not be changed downstream; the only correct way to modify them is via changing the spec.

> it also looks like the original committer (and date) wasn't preserved.

It's not clear to me how this happened. I followed the instructions in the tool for generating the patch, which includes the commit message as far as I can tell. What did I miss?

**Pull request merged**
