### PR TITLE
Remove empty CSS requirement tags from files in CSS directory

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
#31946 
Removes all `meta flags` tags with empty `contents` attributes from files in the `css` directory.

According to the removal script, these were the unique formats of the tags that were detected and removed:
```
<meta name="flags" content=''/>
<meta name='flags' content=''>
<meta name="flags" content="" />
<meta name='flags' content='' />
<meta name="flags" content="">
<meta name="flags" content=""/>
<meta content="" name="flags" />
<meta content="" name="flags">
```

### CODE REVIEW

**Comment by DanielRyanSmith** [comment]
It seems like so many files/tests are being touched by this change that the stability checks cannot be completed without reaching a timeout. This might change have to be split into smaller PRs.

**Comment by frivoal** [comment]
Presumably, some of the time, an empty flags meta means "I have thought about this, and no flags are needed", while not flags meta might mean that, or it might mean "I haven't considered whether flags were appropriate". That said, it is far from sure that this is being applied consistently, so maybe dropping them all actually doesn't cause any loss of usable information.

**Comment by svgeesus** [comment]
I suspect it may mean "my tooling adds this and I don't care either way" so removing them seems fine.

Looks like a set of smaller PRs would let the checks complete without hours of stability check

**Review by svgeesus — APPROVED** [review]

**Comment by DanielRyanSmith** [comment]
I wanted to make sure that these changes passed all tests so I split this into 8 draft PRs. It looks like we're mostly good in terms of the tests. Most of the empty tags existed in the `css/CSS2` directory.

[Part 1](https://github.com/web-platform-tests/wpt/pull/32087)
[Part 2](https://github.com/web-platform-tests/wpt/pull/32088)
[Part 3](https://github.com/web-platform-tests/wpt/pull/32090)
[Part 4](https://github.com/web-platform-tests/wpt/pull/32091)
[Part 5](https://github.com/web-platform-tests/wpt/pull/32125)
[Part 6](https://github.com/web-platform-tests/wpt/pull/32126)
[Part 7](https://github.com/web-platform-tests/wpt/pull/32150)
[Part 8](https://github.com/web-platform-tests/wpt/pull/32151)

**Comment by DanielRyanSmith** [comment]
Closing this pull request in lieu of [a group of smaller pull requests mentioned here](https://github.com/web-platform-tests/wpt/pull/31993#issuecomment-998534105).

**Pull request closed without merging**
