### PR TITLE
Rename many idlharness.js tests to idlharness.*

### PR DESCRIPTION
**Pull request by foolip**
idlharness.window.js and similar is already by far the most common
naming for idlharness.js tests, and that's a good unique name for
findings tests, on wpt.fyi in partiuclar.

This renames all files that contain both `/resources/idlharness.js`
and `idl_test`. The remaining may be renamed when they're converted to
use `idl_test`.

This also renames the domparsing tests from .any.js to .window.js
since those are main thread APIs. Testing for the absense of the
interface objects in workers isn't practically useful, and the
instance tests will always fail:
https://wpt.fyi/results/domparsing/interfaces.any.worker.html?run_id=295100002&run_id=296880003&run_id=277130001&run_id=296870004

### CODE REVIEW

**Comment by foolip** [comment]
@Ms2ger care to review?

**Review by Ms2ger — APPROVED** [review]
I wonder why domparsing was any.js in the first place.

**Comment by foolip** [comment]
@Ms2ger added by @lukebjerring in #9752, most likely by copying another test as he was doing it in batches then.

**Comment by foolip** [comment]
wpt.fyi status checks suggest no horrible mistakes made, tests still passing with same numbers, except for the removed domparsing/interfaces.any.worker.html.

**Pull request merged**
