### PR TITLE
Fix #34493 - Adds missing tests for the compat spec

### LINKED ISSUE #34493: Missing tests for the legacy aliases of the compat spec
The compat spec has a section called [legacy name aliases](https://compat.spec.whatwg.org/#css-simple-aliases). These are the properties which are necessary to support for a browser to be able to work with the Web.

* [x] Do we have tests for each of these aliases?
* [x] Should they be in their own compat section? Or in each thematic individual section?
* [x] `-webkit-align-items` `align-items`
* [x] `-webkit-align-content` `align-content`
* [x] `-webkit-align-self` `align-self`
* [x] `-webkit-animation-name` `animation-name`
* [x] `-webkit-animation-duration` `animation-duration`
* [x] `-webkit-animation-timing-function` `animation-timing-function`
* [x] `-webkit-animation-iteration-count` `animation-iteration-count`
* [x] `-webkit-animation-direction` `animation-direction`
* [x] `-webkit-animation-play-state` `animation-play-state`
* [x] `-webkit-animation-delay` `animation-delay`
* [x] `-webkit-animation-fill-mode` `animation-fill-mode`
* [x] `-webkit-animation` `animation`
* [x] `-webkit-backface-visibility` `backface-visibility`
* [ ] `-webkit-background-clip` `background-clip`
* [x] `-webkit-background-origin` `background-origin`
* [x] `-webkit-border-bottom-left-radius` `border-bottom-left-radius`
* [x] `-webkit-border-bottom-right-radius` `border-bottom-right-radius`
* [x] `-webkit-border-top-left-radius` `border-top-left-radius`
* [x] `-webkit-border-top-right-radius` `border-top-right-radius`
* [x] `-webkit-border-radius` `border-radius`
* [x] `-webkit-box-shadow` `box-shadow`
* [x] `-webkit-box-sizing` `box-sizing`
* [x] `-webkit-flex` `flex`
* [x] `-webkit-flex-basis` `flex-basis`
* [x] `-webkit-flex-direction` `flex-direction`
* [x] `-webkit-flex-flow` `flex-flow`
* [x] `-webkit-flex-grow` `flex-grow`
* [x] `-webkit-flex-shrink` `flex-shrink`
* [x] `-webkit-flex-wrap` `flex-wrap`
* [x] `-webkit-filter` `filter`
* [x] `-webkit-justify-content` `justify-content`
* [x] `-webkit-mask` `mask`
* [x] `-webkit-mask-box-image` `mask-border`
* [x] `-webkit-mask-box-image-outset` `mask-border-outset`
* [x] `-webkit-mask-box-image-repeat` `mask-border-repeat`
* [x] `-webkit-mask-box-image-slice` `mask-border-slice`
* [x] `-webkit-mask-box-image-source` `mask-border-source`
* [x] `-webkit-mask-box-image-width` `mask-border-width`
* [x] `-webkit-mask-clip` `mask-clip`
* [x] `-webkit-mask-composite` `mask-composite`
* [x] `-webkit-mask-image` `mask-image`
* [x] `-webkit-mask-origin` `mask-origin`
* [x] `-webkit-mask-position` `mask-position`
* [x] `-webkit-mask-repeat` `mask-repeat`
* [x] `-webkit-mask-size` `mask-size`
* [x] `-webkit-order` `order`
* [x] `-webkit-perspective` `perspective`
* [x] `-webkit-perspective-origin` `perspective-origin`
* [x] `-webkit-transform-origin` `transform-origin`
* [x] `-webkit-transform-style` `transform-style`
* [x] `-webkit-transform` `transform`
* [x] `-webkit-transition-delay` `transition-delay`
* [x] `-webkit-transition-duration` `transition-duration`
* [x] `-webkit-transition-property` `transition-property`
* [x] `-webkit-transition-timing-function` `transition-timing-function`
* [x] `-webkit-transition` `transition`

### PR DESCRIPTION
**Pull request by karlcow**
Fixing the tests related to compat which went through the net when editing the spec.

### CODE REVIEW

**Review by miketaylr — APPROVED** [review]
LGTM - but I don't know why Safari Tech Preview is refusing to run this.

**Comment by miketaylr** [comment]
@karlcow do you want me to merge, or wait on figuring out the Safari failure (seems unrelated to the tests...)?

**Comment by karlcow** [comment]
@miketaylr probably we can merge here. The tests are not really modifying anything touchy.

**Comment by karlcow** [comment]
thanks

**Pull request merged**
