### PR TITLE
Test radio button interaction between groups

### PR DESCRIPTION
**Pull request by s0lidstate**
Greetings,

This is my first GitHub pull request ever.  I have been looking through the wpt issues labeled with 'good first issue' and I thought I would give [issue #1551](https://github.com/web-platform-tests/wpt/issues/2551) a shot.   @kaixinjxq already has a [PR](https://github.com/web-platform-tests/wpt/pull/11849) created in 2018 for this issue, and it looks like good work, but I thought I would try something a little different.  I will appreciate any review comments and advice that you can give me.  Hoping to make my first contribution!

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Thanks, this looks good to me. Would you be willing to file bugs against Firefox and Safari for their one failure? (It seems they do not group buttons that are not associated with a form.)

I'll leave this open to see if someone else has concerns.

**Comment by s0lidstate** [comment]
I tried to reproduce the bug whereby Firefox and Safari seem to not correctly group buttons that are not associated with a form.  When I created an HTML file on my computer that was similar to the test scenario, Safari automatically added body and html tags and the radio buttons worked per the spec.

I then updated the test scenario to use the createHTMLDocument method and the test passed in both Firefox and Safari.  So apparently my original test setup was not realistic.  I would certainly be willing to file bugs if necessary but I now believe that things are working correctly!

Thank you for your review and comments @annevk!

**Comment by domenic** [comment]
Eek, no, I don't think you want to hide failures by making the tests "more realistic"! The point is to ensure that all browsers behave the same in all cases, not just in "realistic" cases. I think the old test was better!

**Comment by s0lidstate** [comment]
Thank you for the feedback @domenic.  Upon further consideration, I appreciate your point that the goal of the web platform tests is to ensure consistent behavior between browsers.  Creating realistic test scenarios is not as important as ensuring consistent behavior.  I will change the tests back to the prior design.

Having said that, now I am wondering how I would document this bug in Firefox and Safari.  I was not able to reproduce the bug earlier which is what led me to changing my test in aaf8531822adfa05898995f315a29a84c987ba5a.  Should I put a link to the relevant [wpt.fyi results](https://wpt.fyi/results/html/semantics/forms/the-input-element/radio.html?run_id=5689020619161600) and the relevant portion of the [spec](https://html.spec.whatwg.org/multipage/input.html#radio-button-group)?  Is there a standard procedure for creating bugs resulting from wpt tests?

**Comment by annevk** [comment]
You can file bugs at https://bugzilla.mozilla.org/enter_bug.cgi?product=Core for Firefox and https://bugs.webkit.org/enter_bug.cgi?product=WebKit for Safari. Adding a link to this pull request is sufficient.

**Comment by s0lidstate** [comment]
I have created a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1685926) and a [Safari bug](https://bugs.webkit.org/show_bug.cgi?id=220502) for this issue.  Would anyone be willing to take a look to make sure that I filled these out properly?  Thanks again for your help!

**Comment by annevk** [comment]
Thanks for doing all that @s0lidstate! Great first PR too!

**Pull request merged**
