### PR TITLE
Remove test payment-request-in-iframe.html

### PR DESCRIPTION
**Pull request by bentian**
We should remove outdated test [payment-request-in-iframe.html](https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-in-iframe.html) since

- "top-level browsing context only" restriction is removed from spec, and 
- [no-attribute-same-origin-bc-containers.https.html](https://github.com/w3c/web-platform-tests/blob/master/payment-request/allowpaymentrequest/no-attribute-same-origin-bc-containers.https.html) already covers the test case.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253538303)

# Firefox (nightly) #
Testing web-platform-tests at revision 334c3df27970351035398654abc81c2d6bcef6c8
Using browser at version BuildID 20170713100259; SourceStamp 30ea2905130e85f9e1d8d56fa3097901eec6514b
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253538304)

# Sauce (safari) #
Testing web-platform-tests at revision 334c3df27970351035398654abc81c2d6bcef6c8
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253538310)

# Chrome (unstable) #
Testing web-platform-tests at revision 334c3df27970351035398654abc81c2d6bcef6c8

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253538311)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 334c3df27970351035398654abc81c2d6bcef6c8

**Review by alphan102 — APPROVED** [review]
I agree that we should remove this test.

**Review by marcoscaceres — APPROVED** [review]

**Pull request merged**
