### PR TITLE
Computing cross origin URL for gum test with get_host_info

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19482)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/288047797)

**Comment by youennf** [comment]
ping review

**Review by soareschen — CHANGES_REQUESTED** [review]
Can the .sub extension be dropped now that it uses get-host-info.sub.js?

Otherwise LGTM.

**Review by soareschen — APPROVED** [review]

**Comment by youennf** [comment]
Thanks!

**Pull request merged**
