### PR TITLE
Fix playbackRate tests to redirect exceptions into test harness.

### PR DESCRIPTION
**Pull request by japacible**
Changes per @domenic's [recommendation](https://github.com/w3c/web-platform-tests/pull/6522#pullrequestreview-50716659).

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255810988)

# Firefox (nightly) #
Testing web-platform-tests at revision 32cafbc5f27682a6aec03e642bb8bdb022c1fa01
Using browser at version BuildID 20170720100139; SourceStamp 0985725c848ec0cfc6f2f3c3a5aa3d71321e7620
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6593/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html">/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html</a></summary>


|                  Subtest                   | Results |                                     Messages                                     |
|--------------------------------------------|---------|----------------------------------------------------------------------------------|
|                                            | OK      |                                                                                  |
| `playbackRate initial value`               | PASS    |                                                                                  |
| `playbackRate set to small positive value` | PASS    |                                                                                  |
| `playbackRate set to large positive value` | FAIL    | `assert_equals: expected 100 but got 16`                                         |
| `playbackRate set to small negative value` | FAIL    | `assert_equals: expected "NotSupportedError" but got "NS_ERROR_NOT_IMPLEMENTED"` |
| `playbackRate set to large negative value` | FAIL    | `assert_equals: expected "NotSupportedError" but got "NS_ERROR_NOT_IMPLEMENTED"` |
| `playbackRate set to 0`                    | PASS    |                                                                                  |
| `playbackRate set to -1`                   | FAIL    | `assert_equals: expected "NotSupportedError" but got "NS_ERROR_NOT_IMPLEMENTED"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255810989)

# Sauce (safari) #
Testing web-platform-tests at revision 32cafbc5f27682a6aec03e642bb8bdb022c1fa01
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6593/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html">/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html</a></summary>


|                  Subtest                   | Results | Messages |
|--------------------------------------------|---------|----------|
|                                            | OK      |          |
| `playbackRate initial value`               | PASS    |          |
| `playbackRate set to small positive value` | PASS    |          |
| `playbackRate set to large positive value` | PASS    |          |
| `playbackRate set to small negative value` | PASS    |          |
| `playbackRate set to large negative value` | PASS    |          |
| `playbackRate set to 0`                    | PASS    |          |
| `playbackRate set to -1`                   | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255810997)

# Chrome (unstable) #
Testing web-platform-tests at revision 32cafbc5f27682a6aec03e642bb8bdb022c1fa01

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255810998)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 32cafbc5f27682a6aec03e642bb8bdb022c1fa01

**Review by domenic — APPROVED** [review]

**Pull request merged**
