### PR TITLE
Add note to CaptureFacingMode tests

### PR DESCRIPTION
**Pull request by Honry**
For the situation when the user-agent is unable to support the preferred facing mode

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5697)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5697/)

**Comment by Honry** [comment]
@riju/@anssiko, could you help review it?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225903407)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225903409)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 63347b92d1a9de13b916b0d41b16c6fcee80fb3f
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225903415)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 63347b92d1a9de13b916b0d41b16c6fcee80fb3f

**Comment by anssiko** [comment]
LGTM.

**Pull request merged**
