### PR TITLE
Most Typed OM objects have mutable members.

### PR DESCRIPTION
**Pull request by tabatkins**

### CODE REVIEW

**Comment by tobie** [comment]
Pinging @wpt-pr-bot.

**Comment by foolip** [comment]
@tabatkins, if this test is still relevant, can you rebase it and rename into css/? I can review if https://github.com/w3c/web-platform-tests/pull/9214 has no resolution soonish.

**Comment by foolip** [comment]
@darrnshn can you review this? Needs moving into css/ before merging.

**Comment by darrnshn** [comment]
I don't think this needs to be merged in anymore. It's quite outdated and I think it's already covered by the existing tests.

**Comment by foolip** [comment]
Thanks @darrnshn, I'll close it then.

**Pull request closed without merging**
