### PR TITLE
Upstream reject-hyphen.html from Blink

### PR DESCRIPTION
**Pull request by suzyh**
Import
https://chromium.googlesource.com/chromium/src/+/356ff3329424333a5dd0d8f971bbee648ed5d9ad/third_party/WebKit/LayoutTests/web-animations-api/reject-hyphen.html

(Duplicating https://github.com/suzyh/web-platform-tests/pull/20 because it didn't cherry-pick cleanly)

### CODE REVIEW

**Comment by birtles** [comment]
Oh, I don't know what I did there. I was just trying to rebase the PR...

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 32e848e8a94667c0f4451500a26b136600776923
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/3344/web-animations/animation-model/keyframe-effects/the-effect-value-of-a-keyframe-effect.html">/web-animations/animation-model/keyframe-effects/the-effect-value-of-a-keyframe-effect.html</a></summary>


|                                                  Subtest                                                   | Results |
|------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                            | OK      |
| `Test visibility clamping behavior.`                                                                       | PASS    |
| `Overlapping keyframes at 0 and 1 use the appropriate value when the progress is outside the range [0, 1]` | PASS    |
| `Hyphenated CSS property names are ignored in keyframes`                                                   | FAIL    |
| `Overlapping keyframes between 0 and 1 use the appropriate value on each side of the overlap point`        | PASS    |
| `Test visibility clamping behavior with an easing that has a negative component`                           | PASS    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 32e848e8a94667c0f4451500a26b136600776923
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/3344/web-animations/animation-model/keyframe-effects/the-effect-value-of-a-keyframe-effect.html">/web-animations/animation-model/keyframe-effects/the-effect-value-of-a-keyframe-effect.html</a></summary>


|                                                  Subtest                                                   | Results |
|------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                            | OK      |
| `Test visibility clamping behavior.`                                                                       | PASS    |
| `Overlapping keyframes at 0 and 1 use the appropriate value when the progress is outside the range [0, 1]` | PASS    |
| `Hyphenated CSS property names are ignored in keyframes`                                                   | PASS    |
| `Overlapping keyframes between 0 and 1 use the appropriate value on each side of the overlap point`        | PASS    |
| `Test visibility clamping behavior with an easing that has a negative component`                           | PASS    |

</details>

**Comment by birtles** [comment]
@suzyh I've converted this to a test that checks we never access hyphenated properties, however the w3c-bots triggered test run here says Chrome fails all these checks for accessing object properties. Is the test runner wrong or has Chrome yet to implement this part of the spec?

**Comment by suzyh** [comment]
@birtles The tests in processing-a-keyframes-argument.html are passing on Chrome with --enable-experimental-web-platform-features, but not in vanilla Chrome because we haven't shipped KeyframeEffectReadOnly. Is that the issue you're seeing?

**Comment by birtles** [comment]
Oh, that would be it! Thanks!

**Pull request merged**
