### PR TITLE
Add console IDL to interface directory

### PR DESCRIPTION
**Pull request by domfarolino**
/cc @domenic You mentioned this directory was a centralization of some of the IDL files so I figured I'd throw console's in here.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-03 07:29:49
Finished: 2017-10-03 07:36:08


<h2>Failing Jobs</h2>
<ul>

<li>chrome:unstable</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19058)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/282606332)

**Review by tobie — APPROVED** [review]

**Comment by foolip** [comment]
@domfarolino, can you also add a idlharness.js test that ingests this?

It may interest you to learn that @mdittmer is planning to do auto-updating of the IDL files in the directory, so hopefully you won't have to touch this manually again :)

**Comment by domenic** [comment]
idlharness may generate incorrect tests here due to the paragraph at the bottom of https://console.spec.whatwg.org/#console-namespace

**Comment by tobie** [comment]
Mmm. What should we do with that?

**Comment by domenic** [comment]
Add an exception to idlharness, is I think the usual answer

**Comment by tobie** [comment]
I guess that explains part of the sorry state idlharness is in. :D

**Comment by domfarolino** [comment]
Alright so after adding an `interfaces.html` file to the console directory to consume and test the added IDL, I get

screen shot 2017-10-04 at 12 38 29 pm

Is this the failure you're referring to @domenic and if so, how can I help fix this?

**Comment by tobie** [comment]
> Is this the failure you're referring to @domenic and if so, how can I help fix this?

Nope. I don't think namespace are supported in idlharness _at all_ for now.

**Comment by domenic** [comment]
Yeah... making this work seems like it would take a decent amount of work on idlharness.js. Maybe finding where that error is thrown from, and then hacking the code nearby, would be the way to go.

**Comment by domfarolino** [comment]
Hm sorry could I get a little more guidance on that? Like hack around in the idlharness file to make it not totally blow up upon namespaces for now you mean?

**Comment by tobie** [comment]
Repeating the comments made over irc. Adding namespace support to idlharness is going to be a bit involved.

1. Create a dedicated `IdlNamespace` constructor that inherits from `IdlObject` [just like `IdlInterface` does](https://github.com/w3c/web-platform-tests/blob/master/resources/idlharness.js#L880). You might even want to create some kind of extra abstract class that both `IdlNamespace` and `IdlInterface` inherit from depending on how much method `IdlNamespace` and `IdlInterface` end-up sharing.

2. Make sure it defines all the methods that are going to get called by `IdlArray` (notably `test()`). *(Note that the oddly-named `IdlArray` is the library's entry point and orchestrator.)*

3. Hook it in `IdlArray` properly, notably in the [`IdlArray.internal_add_idls()`](https://github.com/w3c/web-platform-tests/blob/master/resources/idlharness.js#L198).

**Pull request merged**
