### PR TITLE
Add more suggested reviewers for Priority Hints

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@addyosmani @yoavweiss, I sent this after noticing just one reviewer (@domfarolino) on https://github.com/web-platform-tests/wpt/pull/12304. You're listed as spec editors, so are you OK with reviewing changes to the test suite?

@addyosmani, you'll need to accept the org invite at the top of https://github.com/web-platform-tests for this to work.

(Won't merge changes without explicit OK.)

**Review by domfarolino — APPROVED** [review]
Am OK with this given they are. Thanks

**Comment by addyosmani** [comment]
@foolip Thanks for the invite. I've just accepted :) More than happy to review changes to the test suite.

**Comment by yoavweiss** [comment]
Yeah, happy to review changes to the test suite

**Review by yoavweiss — APPROVED** [review]
LGTM

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
