### PR TITLE
[css-flexbox] rename flex-direction visual tests to -visual

### PR DESCRIPTION
**Pull request by foolip**
This is to allow renaming the ttwf-reftest-* tests, two of which
conflict with the tests being renamed here.

These tests come from two places:
commit 7514440110ea848d49f1d95c6368e8c5965f8460 from TTWG Beijing, 2012
commit 887f7cf96c4c9afb028c9c3f877d79fd61af50cc from TTWF Seattle, 2013

They're now named *-001-visual.html and *-002-visual.html respectively.

There's a lot more potential renaming/cleanup to be done, but limiting
to the smallest group of things that leave things more consistent.

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/commit/5e0bf30ba44af1d9d05bdd371ef29b8bf5700f80 is the renaming I'd like to do on top of this.

**Comment by foolip** [comment]
@web-platform-tests/wpt-core-team this would be first case of visual tests named *-visual.html inside of css/. https://web-platform-tests.org/writing-tests/visual.html suggests this and there's a lint exception for css/ suggesting this is the way we want to go. Still, if you think this shouldn't be done piecemeal, please shout now!

**Comment by gsnedders** [comment]
this is part of #5381 really

**Comment by foolip** [comment]
Yeah, I found that issue while searching for an existing one today. But it does look like it's already allowed (by lint) to name things -visual in css/, so I figure the only impact is of the renaming itself, the same as any other renaming. Or is there more impact than that on the CSS build system?

**Comment by cbiesinger** [comment]
I'd rather let Sam or someone review this instead of me, since they know the policy here better

**Comment by foolip** [comment]
@web-platform-tests/wpt-core-team would anyone care to have an opinion about this?

**Review by stephenmcgruer — APPROVED** [review]
Assuming none of these are paged reftests (havent checked them all because github Files Changes doesnt show their contents...), this LGTM. I understand the desire in https://github.com/web-platform-tests/wpt/issues/5381 to avoid a double-rename, but in this case these wouldn't be renamed again as far as I can see.

**Pull request merged**
