### PR TITLE
Fix manifest regeneration differences

### LINKED ISSUE #16125: wpt manifest -r produces different result to updating from current download
```
rm MANIFEST.json
./wpt manifest
mv MANIFEST.json MANIFEST-from-download.json
./wpt manifest --no-download -r
diff -u MANIFEST-from-download.json MANIFEST.json
```

This should produce an empty diff, it doesn't (not by a long shot!). We have bugs.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #16125.

### CODE REVIEW

**Comment by jgraham** [comment]
Do we have any way to add testing here?

**Comment by gsnedders** [comment]
@jgraham this now has a test (really a whole set of unit tests for `TypeData` would be good)

**Review by jgraham — APPROVED** [review]

**Comment by gsnedders** [comment]
@Hexcles are you okay with us just landing this, given it bumps the version? the manifest format shouldn't change, though note the `url_base` is never included in the `url` for items now (it was previously, but that was a bug)

**Comment by gsnedders** [comment]
(These force-pushes just tidy up the commit messages a bit)

**Comment by Hexcles** [comment]
@gsnedders IIUC, the manifest version bump will force wpt-manifest to regenerate the manifest from scratch, disregarding the existing manifest. Do you have any estimation how big the diff would be?

We'll need to manually roll this change into Chromium and regenerate the base manifest, but nothing too complicated.

**Comment by gsnedders** [comment]
@Hexcles you haven't done a clean generation in a long time, I assume? every single URL will change therefore to not include the url_base. so, uh, "big".

**Comment by gsnedders** [comment]
@Hexcles but we can just land this, therefore?

**Comment by Hexcles** [comment]
Yes. If the diff is big we'd actually prefer a bump in version number, so this is good.

**Comment by Hexcles** [comment]
@gsnedders so you said `url_base` was removed from paths, but the reference URLs still have it (e.g. `css/foo.html == /css/foo-ref.html`). Is this intentional?

**Comment by gsnedders** [comment]
@Hexcles So, uh, "yes". I'm not super happy about it, but all other URLs (aside from test URLs) in the manifest appear as absolute paths. :/

**Pull request merged**
