### PR TITLE
Fix OffscreenCanvas RTL tests

### LINKED ISSUE #26381: OffscreenCanvas RTL tests don't seem to set RTL anywhere
OffscreenCanvas duplicates a bunch of tests from canvas element, including some RTL tests, but none of these tests actually set text direction.

You can see an example of this in the test `offscreen/text/2d.text.draw.align.end.rtl.html`, which is derived from the test of the same name in the `drawing-text-to-the-canvas` tests for the Canvas element.

I suppose text direction could be set using the font string.

Am I missing something here?

### PR DESCRIPTION
**Pull request by Cwiiis**
There's no canvas element to set direction on with OffscreenCanvas, so
explicitly set direction in the font string. Should fix #26381.

### CODE REVIEW

**Review by kenrussell — APPROVED** [review]
I don't often review test changes in this repository, but this improvement looks good to me.

CC'ing @Juanmihd who also works on OffscreenCanvas in Chrome.

**Comment by annevk** [comment]
Is that a CSS feature? Is `font` the only impacted property?

**Comment by Cwiiis** [comment]
> Is that a CSS feature? Is `font` the only impacted property?

Not sure what you mean? The problem here is there's no canvas element to set direction on (because this is OffscreenCanvas, which isn't an element)

**Comment by annevk** [comment]
I understand the problem, but I don't follow the solution. What does putting `ltr` or `rtl` mean in the `font` property shorthand? How is that equivalent to the `dir` attribute?

**Comment by Cwiiis** [comment]
You're perfectly right, I misread the spec - this should just set direction on the context... Let me update. (I also misread my testing results thinking this fixed things)

**Comment by Cwiiis** [comment]
@annevk does this look ok to merge now?

**Review by annevk — APPROVED** [review]
Thanks, yeah, this looks good. I guess if this is all we still lack coverage for quite a number of scenarios. (Note that I don't see a new notification in `/notifications` for a push.)

**Comment by Cwiiis** [comment]
Thanks - yeah, I was sort of thinking that it's a shame that canvas and OffscreenCanvas tests don't share a bit more than they do right now.

**Pull request merged**
