### PR TITLE
chore: rename dom/events/Event-constructors to .js

### PR DESCRIPTION
**Pull request by lucacasonato**

### CODE REVIEW

**Comment by foolip** [comment]
https://wpt.fyi/results/dom/events/Event-constructors.any.worker.html?label=pr_head&max-count=1&pr=29237 reveals something novel in Chrome, would you mind checking out what the failure is?

**Comment by lucacasonato** [comment]
Looks like a legitimate Chrome bug. `new Event("").timeStamp` always returns `0` in dedicated workers in Chrome. Can't even find where `timeStamp` is initialized in the spec (https://dom.spec.whatwg.org/#event). Also can't find the constructor steps for `Event`...

**Comment by lucacasonato** [comment]
Yup, definitly a bug. Per spec timestamp is initalied to time since time origin: https://dom.spec.whatwg.org/#inner-event-creation-steps, which is "the official moment of creation of the worker" for DedicatedWorker: https://w3c.github.io/hr-time/#dfn-time-origin

**Comment by foolip** [comment]
@lucacasonato good find! I couldn't find an existing bug about this, so let's merge and let one be filed when this rolls into Chromium.

**Review by foolip — APPROVED** [review]

**Pull request merged**
