### PR TITLE
wai-aria: update tests

### PR DESCRIPTION
**Pull request by joanmarie**
* Fix bugs in platform-accessibility-API assertion statements
* Fix bugs in test cases (e.g. missing required attribute, typo in id, etc.)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245585985)

# Firefox (nightly) #
Testing web-platform-tests at revision 46651a4f995e14b50128d7338f01f2444885b221
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245585986)

# Sauce (safari) #
Testing web-platform-tests at revision 46651a4f995e14b50128d7338f01f2444885b221
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245585998)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245585999)

# Sauce (MicrosoftEdge) #

**Review by halindrome — APPROVED** [review]
Glad to see these tests maturing so nicely.  LGTM!

**Pull request merged**
