### PR TITLE
Consistently quote ETags

### LINKED ISSUE #5097: ETags not being checked properly
In `fetch/api/request/resources/cache.py`, the request is checked for a conditional request like this:

~~~ python
    elif ((inm is not None and inm == tag) or
          (ims is not None and ims == date)):
        response.status = (304, "Not Modified")
        return ""
~~~

`tag` and `inm` come from:

~~~ python
    tag = request.GET.first("tag", None)
...
    inm = request.headers.get("If-None-Match", None)
~~~

However, `tag` is the raw entity tag (e.g., `0.23423524232`), whereas the value of the `If-None-Match` header is always quoted (e.g., `"0.23423524232"`).

This results in the `304` never being generated for conditional requests based upon `If-None-Match`. This can be confirmed by examining the network tab in a tested browser and observing that the response status code is `200`. I've also confirmed using tcpdump.

### PR DESCRIPTION
**Pull request by mnot**
Fixes #5097

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/209195919)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 8663c97dbdda9563a11b198240cd9dc3ad3d8be1
Using browser at version BuildID 20170306110339; SourceStamp 966464a68a2cb3ca1125808e34abb5c1d34e3797
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/209195920)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 8663c97dbdda9563a11b198240cd9dc3ad3d8be1
Using browser at version 58.0.3029.6 dev
Starting 10 test iterations
No tests run.

**Comment by annevk** [comment]
LGTM, but does this cause new browser failures? If so I'd like to file bugs.

**Comment by mnot** [comment]
I can check; the old behaviour caused failures in new tests I was writing.

**Comment by mnot** [comment]
Checked Chrome, Safari TP and Firefox; didn't see any. That said, I started to need more invasive changes, so I'm not relying on this library any more. So, no urgency from me here.

**Pull request merged**
