### PR TITLE
Upstream IDBCursor.continuePrimaryKey exception test to WPT.


### PR DESCRIPTION
**Pull request by jeffcarp**
BUG=683463

Review-Url: https://codereview.chromium.org/2652463002
Cr-Commit-Position: refs/heads/master@{#445616}

### CODE REVIEW

**Comment by inexorabletash** [comment]
Hey @RByers @foolip - check this out! 

(Fails in Chrome because the feature is still experimental.)

**Comment by foolip** [comment]
That seems OK, but I guess it might be confusing? Trying to use this process for not-yet-enabled features won't work, but I suppose we could have a separate run with experimental features enabled?

**Comment by inexorabletash** [comment]
I should have made my point clearer - I was dancing with excitement about the process being (semi)functional and awesome. :)

But yeah, maybe we do want a run with experimental features enabled.

**Comment by foolip** [comment]
Ah, consider yourself a beta tester! This process will be announced for general usage real soon now, thanks for helping test it, and feel free to keep at it :)

**Pull request merged**
