### PR TITLE
[SPC] Add test for SPC authentication in a hidden document

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See https://github.com/w3c/secure-payment-confirmation/pull/238

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
cc @ianbjacobs 

One note is that Chrome currently throws an `AbortError` for this - this is likely due to either step 5 or 12.1 of https://w3c.github.io/payment-request/#show-method . The actual SPC spec change (https://github.com/w3c/secure-payment-confirmation/pull/238) would _technically_ throw a `NotSupportedError`, because of what happens when the 'steps to check a payment can be made' fail: https://w3c.github.io/payment-request/#ref-for-dfn-steps-to-check-if-a-payment-can-be-made-1

**Comment by nickburris** [comment]
> One note is that Chrome currently throws an `AbortError` for this - this is likely due to either step 5 or 12.1 of https://w3c.github.io/payment-request/#show-method . The actual SPC spec change ([w3c/secure-payment-confirmation#238](https://github.com/w3c/secure-payment-confirmation/pull/238)) would _technically_ throw a `NotSupportedError`, because of what happens when the 'steps to check a payment can be made' fail: https://w3c.github.io/payment-request/#ref-for-dfn-steps-to-check-if-a-payment-can-be-made-1

What does a non-SPC PaymentRequest throw? Should this WPT expect a NotSupportedError then, and we update our implementation to throw that?

**Comment by stephenmcgruer** [comment]
Codewise, it also throws an AbortError.

Specwise, the two possible places Chrome is choosing to throw an AbortError here (steps 5 or 12.1 of show()) both come before when SPC would have a chance to cause a NotSupportedError to be thrown (during step 17 iirc). So Chrome is perfectly within spec here. This is why we should fix this in Payment Request instead, and maybe we should just do that rather than land the SPC spec PR - thoughts Ian?

I think I'll go check if Safari allows Payment Request in a background tab today. If not maybe we can easily spec something in Payment Request quickly.

**Comment by stephenmcgruer** [comment]
> I think I'll go check if Safari allows Payment Request in a background tab today. If not maybe we can easily spec something in Payment Request quickly.

Based on my testing, Safari also throws an AbortError if you try to trigger it when the tab is in the background. Reproduction:

1. Visit https://rsolomakhin.github.io/pr/applepay/ in Safari, and have another tab ready
2. Click the Apple Pay button (the code will wait 1s before calling Payment Request's show() method), and then very quickly switch to the other tab
3. Observe an AbortError is thrown

**Review by nickburris — APPROVED** [review]
LGTM, thanks for confirming the implementation consistency!

**Pull request merged**
