### PR TITLE
Add a test for form.elements exact filter

### PR DESCRIPTION
**Pull request by domenic**
This tests the exact list of elements included ("listed elements" except image buttons), plus tests that the form="" attribute works; see https://github.com/whatwg/html/issues/2764.

### CODE REVIEW

**Comment by domenic** [comment]
I guess this is "needs-spec-decision" until we fix https://github.com/whatwg/html/issues/2764

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/243396027)

# Firefox (nightly) #
Testing web-platform-tests at revision f8ceb389a1db5ac546350919b03762036d959939
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6255/html/semantics/forms/the-form-element/form-elements-filter.html">/html/semantics/forms/the-form-element/form-elements-filter.html</a></summary>


|                               Subtest                                | Results | Messages |
|----------------------------------------------------------------------|---------|----------|
|                                                                      | OK      |          |
| `form.elements must contain all listed elements with the form owner` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/243396028)

# Sauce (safari) #
Testing web-platform-tests at revision f8ceb389a1db5ac546350919b03762036d959939
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6255/html/semantics/forms/the-form-element/form-elements-filter.html">/html/semantics/forms/the-form-element/form-elements-filter.html</a></summary>


|                               Subtest                                | Results | Messages |
|----------------------------------------------------------------------|---------|----------|
|                                                                      | OK      |          |
| `form.elements must contain all listed elements with the form owner` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/243396034)

# Chrome (unstable) #
Testing web-platform-tests at revision f8ceb389a1db5ac546350919b03762036d959939

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/243396035)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision f8ceb389a1db5ac546350919b03762036d959939

**Comment by domenic** [comment]
Spec fixed, ready for review

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
EdgeHTML 15 fails in the same way as EdgeHTML 14 (assert_array_equals: lengths differ, expected 81 got 27).

**Pull request merged**
