### PR TITLE
Test SpeechSynthesisUtterance volume attribute

### PR DESCRIPTION
**Pull request by guest271314**
TODO: automate test to verify audio output of speechSynthesis.speak() using Web Audio API.

### CODE REVIEW

**Comment by guest271314** [comment]
@foolip Can you review this pull request?

**Comment by guest271314** [comment]
@foolip Can you review this pull request? How to delete https://github.com/w3c/web-platform-tests/pull/9642/commits/b5a666a7fb195a10681d99208f86d11961c47a08 from the PR? The commit necessary is https://github.com/w3c/web-platform-tests/pull/9642/commits/2391cff96179101947f46cbd2762abcab1ec6f45

**Comment by guest271314** [comment]
@annevk What is necessary for this test PR to be incorporated into the Web Platform Tests?

**Comment by annevk** [comment]
You'll need to fix the CI failure.

And it seems you'll need review from one of the OWNERS: @andrenatal @fleizach @gshires @jdsmith3000. Not sure why they were not pinged.

**Comment by guest271314** [comment]
@annevk Not certain how to adjust the existing PR to remove the commit  https://github.com/w3c/web-platform-tests/commit/b5a666a7fb195a10681d99208f86d11961c47a08 (which was the first PR attempt) using github interface. Should the PR be deleted then resubmitted without that commit that failed continuous intergration?

**Comment by annevk** [comment]
You could rebase and force push.

**Comment by guest271314** [comment]
@annevk Unfortunately was not able to clone this repository (200MB+) at the command line, due to device capacity. Instead forked the repository, created this PR and compared changed to the fork. Is it possible to rebase and force push using GitHub interface? 

Should an issue be filed concerning the ever-increasing size of this repository? 

Is there some means to clone and push only specific folders; for example https://github.com/w3c/web-platform-tests/tree/master/speech-api, and create a PR at the command line for only that repository?

**Comment by annevk** [comment]
I don't really know the answers to those questions.

**Comment by foolip** [comment]
Try `git clone --depth 10` to see if that might cut down enough on the size.

**Comment by guest271314** [comment]
@foolip What does that option do?

**Comment by guest271314** [comment]
@foolip Did not make it to speech-api folder

```
$ git clone --depth 10 https://github.com/w3c/web-platform-tests.git
Cloning into 'web-platform-tests'...
remote: Counting objects: 57700, done.
remote: Compressing objects: 100% (29262/29262), done.
remote: Total 57700 (delta 32113), reused 41654 (delta 27113), pack-reused 0
Receiving objects: 100% (57700/57700), 48.34 MiB | 686.00 KiB/s, done.
Resolving deltas: 100% (32113/32113), done.
Checking connectivity... done.
fatal: cannot create directory at 'html/infrastructure/fetching-resources/processing-model': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Pull request closed without merging**
