### PR TITLE
Update interfaces/css-typed-om.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/5c53f34/ed/idl/css-typed-om.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/672386095

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
... for some reason this didn't run the tests properly. I'm going to kick it and see what happens.

**Comment by stephenmcgruer** [comment]
There's something funky here. Now the tests aren't running in either the before or after set. It's not clear to me why those aren't being picked up, I see a `css/css-typed-om/idlharness.html` file in the tree. Needs investigation.

**Comment by foolip** [comment]
https://travis-ci.org/github/tidoust/reffy-reports/jobs/672645963#L441 shows it was deleted because the branch wasn't created locally. That'd be because the copy in wpt and reffy-reports are already in sync.

**Comment by foolip** [comment]
Hmm, probably because https://github.com/web-platform-tests/wpt/pull/22774 brought in the changes. But why were two PRs created? That'd be the real bug here.

**Comment by stephenmcgruer** [comment]
Could there have been a spec change that was then reverted?

**Comment by foolip** [comment]
Starting from https://travis-ci.org/github/tidoust/reffy-reports/builds, the PR creation happened here:
https://travis-ci.org/github/tidoust/reffy-reports/builds/672386095#L431
https://travis-ci.org/github/tidoust/reffy-reports/builds/672492747#L417

Looks like there was a race condition. https://github.com/web-platform-tests/wpt/pull/22774 was merged at 2020-04-08T12:43:33Z and this PR (https://github.com/web-platform-tests/wpt/pull/22785) was created 9 seconds later, at 2020-04-08T12:43:42Z. The [build that created it](https://travis-ci.org/github/tidoust/reffy-reports/builds/672492747) was started before the merge and must have fetch before since the branch was still there:
> Remote branch is up to date: reffy-reports/css-typed-om
> Created PR: https://github.com/web-platform-tests/wpt/pull/22785

When I wrote the code I decided to create a PR in this condition in case the branch had been created but the PR creation failed, since otherwise a lone branch might be left sitting indefinitely.

I'll file an issue on https://github.com/tidoust/reffy-reports.

**Comment by foolip** [comment]
Additionally and importantly, I expect that when we looked for open PRs, none was found for the branch, because it had just been deleted due to being merged.

**Comment by foolip** [comment]
Filed https://github.com/tidoust/reffy-reports/issues/46.

**Pull request closed without merging**
