### PR TITLE
[css-writing-modes] Remove text-orientation-script-001*

### PR DESCRIPTION
**Pull request by kojiishi**
This patch removes `text-orientation-script-001*` tests.

At the point this set of tests were developed, UA had to
implement computing the Vertical_Orientation property as
defiend in UTR#50.

Since then, UTR#50 turned to UAX#50 and ICU63 added this
property that the benefit of testing all code points became
less important.

This set of tests have following downsides:
1. Specific to a version of UAX#50 that the tests and all UA
   must be in sync.
2. Takes very long time, often timeouts in Edge and WebKit.
3. Is sensitive to the undefined behavior of
   `getBoundingClientRect`.
4. It's not easy to maintain on every revision update.

Given the benefit went down, and we have tests for specific
cases (other `text-orientation-*` tests), this set of tests
has done its role hence removing.

### CODE REVIEW

**Comment by kojiishi** [comment]
@fantasai @dbaron @frivoal PTAL.

**Comment by kojiishi** [comment]
Note this test has stopped updating since revision 16, and I'm no longer able to keep maintaining this. The [UAX#50] is currently at revision 22.

[UAX#50]: https://www.unicode.org/reports/tr50/

**Comment by frivoal** [comment]
Seems reasonable to me that these are no longer needed for CSS if they're covered by something else. But are they? UAX50 defines them, and ICU63 implements them, but we don't require that everybody uses ICU, in so it feels useful to still have some kind of test for that behavior somewhere. Do we?

**Comment by frivoal** [comment]
Anyway, if this is buggy in various browsers and out of date, getting rid of it make sense regardless.

**Review by frivoal — APPROVED** [review]

**Pull request merged**
