### PR TITLE
test PaymentValidationErrors' `payer` member

### PR DESCRIPTION
**Pull request by marcoscaceres**
Tests for:  https://github.com/w3c/payment-request/pull/721

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@foolip any ideas why @rsolomakhin might not be showing as an authorized reviewer? He is listen in the META.yml file.

**Comment by foolip** [comment]
Oh, that's because it's possible to be a member of the org without being in the reviewers team, which gets you write access. So far I've only tried to align org membership with META.yml listings. Will add @rsolomakhin to reviewers team now.

**Comment by foolip** [comment]
There, review checkbox is now green.

**Comment by marcoscaceres** [comment]
Awesome, thanks @foolip!

**Review by bosniltd-a11y — APPROVED** [review]

**Pull request merged**
