### PR TITLE
Add WebCodecs full cycle test using realtime `latencyMode`

### PR DESCRIPTION
**Pull request by mehagar**
I noticed that encoding and decoding in Safari did not properly work when using `latencyMode: "realtime"`. This adds a new test to run the full cycle tests using the realtime mode.

### CODE REVIEW

**Review by Djuffin — APPROVED** [review]

**Comment by mehagar** [comment]
@youennf , @sandersdan , friendly ping on this 🙂

**Comment by sandersdan** [comment]
I don't think I can add anything beyond @Djuffin as we both work on Chrome's implementation. FWIW, the change looks fine to me.

**Comment by Djuffin** [comment]
Given that this test is part of Interop 23 and you say that it's not working on Safari. I can't merge it without an approval from @youennf

**Review by youennf — APPROVED** [review]

**Comment by youennf** [comment]
Sorry for the delay, I missed this one. Thanks for this addition

**Comment by youennf** [comment]
The test passes locally for me on macOS, but it does not seem it passes in bots, according https://wpt.fyi/results/webcodecs/full-cycle-test.https.any.html%3Fh264_avc?label=experimental&label=master&aligned.
As can be seen: `frames_encoded expected 16 but got 4`. We appear to have frame dropping which is allowed in realtime mode. I believe we should change a bit the test to check for `frames_decoded == frames_encoded` instead of `frames_decoded == frames_to_encode`. We should also probably have `frames_encoded > 0`.

**Pull request merged**
