### PR TITLE
Create idlharness tests for Network Information API

### PR DESCRIPTION
**Pull request by zqzhang**
https://wicg.github.io/netinfo/

### CODE REVIEW

**Comment by Ms2ger** [comment]
Why the separate idl files? `Exposed` should work now.

**Comment by zqzhang** [comment]
> Why the separate idl files? Exposed should work now.

Seems Chrome doesn't work on my phone.

**Comment by tobie** [comment]
Ping @wpt-pr-bot.

**Comment by foolip** [comment]
Sorry this was never reviewed. In the end the same test coverage was added in https://github.com/web-platform-tests/wpt/pull/11857, so I'm going to close this now.

**Pull request closed without merging**
