### PR TITLE
Update interfaces/native-file-system.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/14fca71/ed/idl/native-file-system.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/692042822

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Fun, this introduces a dependency on 'WritableStream', but we don't have any such interface in `interfaces/`:

```
$ grep -r WritableStream interfaces/
interfaces/encoding.idl:  readonly attribute WritableStream writable;
```

Looking at the spec (https://wicg.github.io/native-file-system/) and then following the link for WritableStream (https://streams.spec.whatwg.org/#ws-class), it's non-normative and has no IDL!

**Comment by mkruisselbrink** [comment]
What can be done to unblock this? Not having any idlharness tests for the native file system API seems better than the current state where the tests in way reflect what is actually in the spec. And that will only diverge more and more as the spec and implementation get updated...

**Comment by stephenmcgruer** [comment]
I believe @domenic was looking into converting streams to IDL, which would trivially fix the issue. Failing that, I need to look at how fatal an error this is for idlharness and how we might work around it...

**Comment by domenic** [comment]
Streams IDL conversion is almost ready to merge in #22982.

**Pull request closed without merging**
