### PR TITLE
[geometry] Test structured serialization for 2d matrix with m13=-0

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/w3c/fxtf-drafts/pull/162

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232760092)

# Firefox (nightly) #
Testing web-platform-tests at revision e80b2146f6e2f848e99947a96bb81dac1f06e894
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5937/css/geometry-1/structured-serialization.html">/css/geometry-1/structured-serialization.html</a></summary>


|                      Subtest                       | Results |                                                 Messages                                                 |
|----------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------|
|                                                    | OK      |                                                                                                          |
| `DOMPointReadOnly clone: basic`                    | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMPointReadOnly clone: custom property`          | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMPointReadOnly clone: throwing getters`         | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMPointReadOnly clone: non-initial values`       | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMPoint clone: basic`                            | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMPoint clone: custom property`                  | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMPoint clone: throwing getters`                 | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMPoint clone: non-initial values`               | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMRectReadOnly clone: basic`                     | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMRectReadOnly clone: custom property`           | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMRectReadOnly clone: throwing getters`          | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMRectReadOnly clone: non-initial values`        | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMRect clone: basic`                             | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMRect clone: custom property`                   | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMRect clone: throwing getters`                  | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMRect clone: non-initial values`                | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMQuad clone: basic`                             | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMQuad clone: custom property`                   | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMQuad clone: throwing getters`                  | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMQuad clone: non-initial values`                | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMMatrixReadOnly clone: basic`                   | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMMatrixReadOnly clone: custom property`         | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMMatrixReadOnly clone: throwing getters`        | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMMatrixReadOnly clone: non-initial values (2d)` | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMMatrixReadOnly clone: non-initial values (3d)` | FAIL    | `Illegal constructor.`                                                                                   |
| `DOMMatrix clone: basic`                           | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMMatrix clone: custom property`                 | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMMatrix clone: throwing getters`                | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMMatrix clone: non-initial values (2d)`         | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |
| `DOMMatrix clone: non-initial values (3d)`         | FAIL    | `promise_test: Unhandled rejection with value: object "DataCloneError: The object could not be cloned."` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232760093)

# Sauce (safari) #
Testing web-platform-tests at revision e80b2146f6e2f848e99947a96bb81dac1f06e894
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5937/css/geometry-1/structured-serialization.html">/css/geometry-1/structured-serialization.html</a></summary>


|                      Subtest                       | Results |                                            Messages                                            |
|----------------------------------------------------|---------|------------------------------------------------------------------------------------------------|
|                                                    | OK      |                                                                                                |
| `DOMPointReadOnly clone: basic`                    | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPointReadOnly clone: custom property`          | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPointReadOnly clone: throwing getters`         | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPointReadOnly clone: non-initial values`       | FAIL    | `undefined is not a constructor (evaluating 'new self[constr](1, -0, Infinity, NaN)')`         |
| `DOMPoint clone: basic`                            | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPoint clone: custom property`                  | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPoint clone: throwing getters`                 | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMPoint clone: non-initial values`               | FAIL    | `undefined is not a constructor (evaluating 'new self[constr](1, -0, Infinity, NaN)')`         |
| `DOMRectReadOnly clone: basic`                     | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRectReadOnly clone: custom property`           | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRectReadOnly clone: throwing getters`          | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRectReadOnly clone: non-initial values`        | FAIL    | `undefined is not a constructor (evaluating 'new self[constr](1, -0, Infinity, NaN)')`         |
| `DOMRect clone: basic`                             | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRect clone: custom property`                   | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRect clone: throwing getters`                  | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMRect clone: non-initial values`                | FAIL    | `undefined is not a constructor (evaluating 'new self[constr](1, -0, Infinity, NaN)')`         |
| `DOMQuad clone: basic`                             | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMQuad clone: custom property`                   | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMQuad clone: throwing getters`                  | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMQuad clone: non-initial values`                | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]')`                               |
| `DOMMatrixReadOnly clone: basic`                   | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrixReadOnly clone: custom property`         | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrixReadOnly clone: throwing getters`        | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrixReadOnly clone: non-initial values (2d)` | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]([1, -0, Infinity, NaN, 5, 6])')` |
| `DOMMatrixReadOnly clone: non-initial values (3d)` | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]')`                               |
| `DOMMatrix clone: basic`                           | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrix clone: custom property`                 | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrix clone: throwing getters`                | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]()')`                             |
| `DOMMatrix clone: non-initial values (2d)`         | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]([1, -0, Infinity, NaN, 5, 6])')` |
| `DOMMatrix clone: non-initial values (3d)`         | FAIL    | `undefined is not a constructor (evaluating 'new self[constr]')`                               |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232760094)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision e80b2146f6e2f848e99947a96bb81dac1f06e894
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5937/css/geometry-1/structured-serialization.html">/css/geometry-1/structured-serialization.html</a></summary>


|                      Subtest                       | Results |               Messages               |
|----------------------------------------------------|---------|--------------------------------------|
|                                                    | OK      |                                      |
| `DOMPointReadOnly clone: basic`                    | FAIL    | `Object doesn't support this action` |
| `DOMPointReadOnly clone: custom property`          | FAIL    | `Object doesn't support this action` |
| `DOMPointReadOnly clone: throwing getters`         | FAIL    | `Object doesn't support this action` |
| `DOMPointReadOnly clone: non-initial values`       | FAIL    | `Object doesn't support this action` |
| `DOMPoint clone: basic`                            | FAIL    | `Object doesn't support this action` |
| `DOMPoint clone: custom property`                  | FAIL    | `Object doesn't support this action` |
| `DOMPoint clone: throwing getters`                 | FAIL    | `Object doesn't support this action` |
| `DOMPoint clone: non-initial values`               | FAIL    | `Object doesn't support this action` |
| `DOMRectReadOnly clone: basic`                     | FAIL    | `Object doesn't support this action` |
| `DOMRectReadOnly clone: custom property`           | FAIL    | `Object doesn't support this action` |
| `DOMRectReadOnly clone: throwing getters`          | FAIL    | `Object doesn't support this action` |
| `DOMRectReadOnly clone: non-initial values`        | FAIL    | `Object doesn't support this action` |
| `DOMRect clone: basic`                             | FAIL    | `Object doesn't support this action` |
| `DOMRect clone: custom property`                   | FAIL    | `Object doesn't support this action` |
| `DOMRect clone: throwing getters`                  | FAIL    | `Object doesn't support this action` |
| `DOMRect clone: non-initial values`                | FAIL    | `Object doesn't support this action` |
| `DOMQuad clone: basic`                             | FAIL    | `Object doesn't support this action` |
| `DOMQuad clone: custom property`                   | FAIL    | `Object doesn't support this action` |
| `DOMQuad clone: throwing getters`                  | FAIL    | `Object doesn't support this action` |
| `DOMQuad clone: non-initial values`                | FAIL    | `Object doesn't support this action` |
| `DOMMatrixReadOnly clone: basic`                   | FAIL    | `Object doesn't support this action` |
| `DOMMatrixReadOnly clone: custom property`         | FAIL    | `Object doesn't support this action` |
| `DOMMatrixReadOnly clone: throwing getters`        | FAIL    | `Object doesn't support this action` |
| `DOMMatrixReadOnly clone: non-initial values (2d)` | FAIL    | `Object doesn't support this action` |
| `DOMMatrixReadOnly clone: non-initial values (3d)` | FAIL    | `Object doesn't support this action` |
| `DOMMatrix clone: basic`                           | FAIL    | `Object doesn't support this action` |
| `DOMMatrix clone: custom property`                 | FAIL    | `Object doesn't support this action` |
| `DOMMatrix clone: throwing getters`                | FAIL    | `Object doesn't support this action` |
| `DOMMatrix clone: non-initial values (2d)`         | FAIL    | `Object doesn't support this action` |
| `DOMMatrix clone: non-initial values (3d)`         | FAIL    | `Object doesn't support this action` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232760100)

# Chrome (unstable) #
Testing web-platform-tests at revision 8c40bb6cb0c3b1dc344ab2fed0f3003ff72b7b39
Using browser at version 60.0.3095.5 dev
Starting 10 test iterations

**Review by domenic — APPROVED** [review]

**Pull request merged**
