### PR TITLE
Add test to ensure FileReaderSync isn't supported in service workers.

### PR DESCRIPTION
**Pull request by mkruisselbrink**
This was removed from the spec in https://github.com/w3c/FileAPI/issues/16.

### CODE REVIEW

**Comment by mkruisselbrink** [comment]
Possibly it makes more sense to add this to the FileAPI/historical.html test instead (and rename that to historical.https.html)...

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision e95d113b75a273f2d073e5087c56648203a4a527
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="https://w3c-test.org/submissions/4766/service-workers/service-worker/historical.https.html">/service-workers/service-worker/historical.https.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | ERROR   |
| `Service worker test setup`                                   | PASS    |
| `"FileReaderSync" should not be supported in service workers` | FAIL    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision e95d113b75a273f2d073e5087c56648203a4a527
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="https://w3c-test.org/submissions/4766/service-workers/service-worker/historical.https.html">/service-workers/service-worker/historical.https.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | OK      |
| `Service worker test setup`                                   | PASS    |
| `"FileReaderSync" should not be supported in service workers` | FAIL    |

</details>

**Comment by Ms2ger** [comment]
> Possibly it makes more sense to add this to the FileAPI/historical.html test instead (and rename that to historical.https.html)...

Yes, I think so. Would you mind doing that?

**Comment by mkruisselbrink** [comment]
I'll make that change. One reason I didn't originally was that it seemed a bit weird to have a file API test fall for service workers not being implemented. But this test does really belong there.

**Comment by mkruisselbrink** [comment]
Okay, I moved the test to FileAPI/historical.https.html, but only run the service worker related tests if service workers are actually supported.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4766/)

**Comment by mkruisselbrink** [comment]
@Ms2ger are you happy with the current status of this PR?

**Pull request merged**
