### PR TITLE
Remove css/css-color/LICENSE

### PR DESCRIPTION
**Pull request by foolip**
The rationale for this is the same as previous license cleanup:
https://github.com/web-platform-tests/wpt/pull/23593
https://github.com/web-platform-tests/wpt/pull/28677
https://github.com/web-platform-tests/wpt/pull/33415

### CODE REVIEW

**Review by weinig — APPROVED** [review]

**Comment by foolip** [comment]
@jgraham can you perhaps ask Mozilla legal to rubberstamp it?

**Review by svgeesus — APPROVED** [review]

**Comment by svgeesus** [comment]
Kicking the bot

**Review by svgeesus — APPROVED** [review]

**Comment by svgeesus** [comment]
> @jgraham can you perhaps ask Mozilla legal to rubberstamp it?

**Review by jgraham — APPROVED** [review]
My understanding is we are OK with this change.

**Pull request merged**
