### PR TITLE
Correct CSS2/syntax tests

### PR DESCRIPTION
**Pull request by csnardi**
Some css/CSS2/syntax tests were failing, either due to an incorrect reference or due to relying on `.htaccess` to provide encodings. This change fixes the incorrect references, and creates headers files so the tests can pass.

This also removes `ident-020.xht`, as it tests for identifiers with two dashes which is now defined as the syntax for CSS variables.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22762)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/328533555)

**Review by dbaron — COMMENTED** [review]
So far I've looked over everything *except* for:
* the removal of ident-020
* the .htaccess/.headers changes

and it looks fine.  I or someone else still needs to do those two.

**Comment by csnardi** [comment]
For clarity in reviewing: I used https://github.com/w3c/web-platform-tests/blob/7ea7d829111a24d65cb447d4770532a286f0f618/approved/css2.1/src/support/.htaccess for what I added to the .headers files.

**Comment by gsnedders** [comment]
r=me for the ident-020 change.

I agree ident-020 is invalid, given they're valid identifiers per CSS Syntax Level 3 and Selectors Level 4 just references that. As such, can you move it to `css/selectors` and invert the pass condition (and give it a more descriptive name, like class-name-double-hyphen or something)?

**Comment by gsnedders** [comment]
(Unless @tabatkins or someone feels like that should go into `css/syntax`?)

**Review by gsnedders — CHANGES_REQUESTED** [review]
Per above, please move ident-020 with pass condition inverted into css/syntax.

**Comment by csnardi** [comment]
I realized when I moved the file that https://github.com/w3c/web-platform-tests/blob/master/css/css-syntax/ident-three-code-points.html is actually very similar; while it doesn't test with class names it tests the first condition with id names. Given this, what do you think about moving it?

**Comment by gsnedders** [comment]
No,  probably not.

If anyone strongly disagrees, they can add tests for it.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
