### PR TITLE
WebCryptoAPI: add EC public key raw import vectors and spki compresed import vectors

### PR DESCRIPTION
**Pull request by panva**
This adds

- `raw` EC public key import vectors. Both mandatory to implement uncompressed point as well as the optional to implement compressed point.
- `spki` compressed point EC public key import vectors.

The compressed point vector round trip checks that the export is uncompressed as per the `Export Key` steps.

Unique test names continue being generated thanks to the different buffer length.

For both `raw` and `spki` the compressed point import support is optional per the specification.

### CODE REVIEW

**Comment by panva** [comment]
I have also verified all these vectors with the Node.js WPT runner.

**Review by twiss — COMMENTED** [review]
Hey :wave: Thanks! Some minor comments below.

**Comment by panva** [comment]
@twiss both great suggestions, addressed.

**Comment by panva** [comment]
all 3 wpt.fyi indicate this worked fine.

1) chrome implements all correctly
2) firefox doesn't implement compressed points and reports PRECONDITION_FAILED on the compressed tests
3) safari implements compressed points with `spki` format but fails the round trip to always export uncompressed

Example generated compressed test name

```
Good parameters: P-256 bits (spki, buffer(59, compressed), {name: ECDSA, namedCurve: P-256}, true, [])
```

**Review by twiss — APPROVED** [review]
Looks great, thanks!

**Comment by panva** [comment]
I was thinking of omitting the `bits` in the test names but I figured stability in test names is more important?

**Comment by twiss** [comment]
Yeah, maybe. I guess some implementations might have expected results that would have to be changed, so maybe it's not worth it to change, indeed.

**Pull request merged**
