### PR TITLE
Update permission-policy headers for payment

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@clelland ping 🛎️

**Comment by marcoscaceres** [comment]
@annevk, maybe you can approve this?

**Review by annevk — COMMENTED** [review]
We should remove the `Feature-Policy` headers at the same time, no? And perhaps there should be a negative test for them?

Also, we should probably rename these files at the same time.

**Comment by marcoscaceres** [comment]
Yeah, I was a bit unsure if we were prepare to break em all. 

If so, I'ld like to do them all in one go. I can take that on if that's the case.

**Comment by annevk** [comment]
Given that https://w3c.github.io/webappsec-permissions-policy/ no longer defines `Feature-Policy` I think that would be correct. I'll DM Ian to see if I can get him to comment on this directly.

**Comment by clelland** [comment]
I'm really sorry I missed this, @marcoscaceres -- I need to do something with my email filters, it seems 😬 

I agree with @annevk, removing `Feature-Policy` headers SGTM; the spec no longer defines them, and the sooner we can get developers on the Permissions-Policy train, the better.

Chrome still supports both, because of [existing usage](https://chromestatus.com/metrics/feature/timeline/popularity/2027) -- it's still too high to remove, although we're trying to discourage new usage.

**Comment by marcoscaceres** [comment]
Closing. Will be updated with mass removal.

**Comment by marcoscaceres** [comment]
@clelland, @annevk... I had a look at doing the mass removal... it's actually not possible to automate (or would take me a few weeks of manual work).

I've sent branches that update the header files... but then a lot of tests are quite arbitrary. 

So, I think the only realistic option is to start reaching out to all the test maintainers and getting them to update their tests.

**Comment by marcoscaceres** [comment]
Some examples:
https://github.com/web-platform-tests/wpt/pull/37105
https://github.com/web-platform-tests/wpt/pull/37104

As you can see... they are quite different... there is a lot file renaming and there are files being pulled from various directories, etc.... so way too much work for one tiny human.

**Pull request closed without merging**
