### PR TITLE
Add CODEOWNERS to prevent submodule issues

### PR DESCRIPTION
**Pull request by annevk**
b8ef676615e230a09023e02ce4f0b0f8b1f6c2a1 accidentially touched a submodule. This would greatly diminish the chance of that happening and it landing on master again.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/11070)

### CODE REVIEW

**Comment by annevk** [comment]
To make this work an admin will have to enable CODEOWNERS checks too.

**Comment by annevk** [comment]
See https://help.github.com/articles/about-codeowners/ for more details.

**Comment by gsnedders** [comment]
@annevk from the documentation, it sounds like all it does it trigger a review request? how does this improve the situation over @wpt-pr-bot? (does it just work better with submodules?)

**Comment by annevk** [comment]
@gsnedders an admin can check a box to require a code owner approval.

**Comment by jgraham** [comment]
I think this is reasonable. I don't know if @foolip has any objections?

**Review by foolip — APPROVED** [review]
Seems fine to me. I'm curious is CODEOWNERS is flexible enough to replace our use of OWNERS, but suspect not.

**Pull request merged**
