### PR TITLE
Tests for Document#currentScript

### PR DESCRIPTION
**Pull request by koustuvsinha**
Adding tests for Document#currentScript according to issue #1636

### CODE REVIEW

**Comment by jgraham** [comment]
Comments on critic

**Comment by koustuvsinha** [comment]
@jgraham updated few more tests, plz review! :)

**Comment by jgraham** [comment]
Squash?

**Comment by koustuvsinha** [comment]
yes @jgraham i will, but after putting a few more test cases which are left to implement :)

**Pull request merged**
