### PR TITLE
gb18030 encoding and decoding tests

### PR DESCRIPTION
**Pull request by r12a**
Results for these tests can be found at
https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en#gb18030

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 16:27:42
Finished: 2017-08-15 16:51:00



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17423)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264812448)

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 16:27:42
Finished: 2017-08-15 16:51:00



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17423)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264812448)

**Comment by domenic** [comment]
@hsivonen @r12a what's the status of this? Is @hsivonen happy with them vis-a-vis Firefox 57/encoding_rs? If so I can work on getting it merge-ready.

**Comment by hsivonen** [comment]
Sorry about the delay. I'll take another look at the remaining failure.

**Comment by hsivonen** [comment]
As [commented](https://github.com/whatwg/encoding/issues/57) on the spec repo issue, I think the tests reflect a spec bug. I think the spec should change and then the tests be changed to reflect the changed spec.

Again, sorry about the delay.

**Comment by r12a** [comment]
hi @domenic. Thanks for your help. This is currently pending a resolution on https://github.com/whatwg/encoding/issues/57#issuecomment-322540517 ff, i believe.

**Comment by annevk** [comment]
Note that the latest here is that there is a bug in these tests that needs to be fixed. I was going to look into fixing it, but it seems the branch has been removed.

@r12a can you look into it?

**Comment by annevk** [comment]
Please continue at #20361.

**Pull request closed without merging**
