### PR TITLE
Update Safari Technology Preview to 102

### PR DESCRIPTION
**Pull request by foolip**
Closes https://github.com/web-platform-tests/wpt/pull/22107.

### CODE REVIEW

**Comment by foolip** [comment]
I've kicked off a full run in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=43408&view=results to check for regressions before this is merged. It should be compared against https://wpt.fyi/results/?run_id=436640016.

**Comment by foolip** [comment]
@svillar I see Python 3 failures on Windows due to "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 8: ordinal not in range(128)"

Are these tests expected to be passing at all times? I'm pretty sure I didn't break them with these changes.

**Comment by svillar** [comment]
> @svillar I see Python 3 failures on Windows due to "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 8: ordinal not in range(128)"
> 
> Are these tests expected to be passing at all times? I'm pretty sure I didn't break them with these changes.

I haven't landed the py3 changes (PR 22061) for test_wpt yet. Unfortunatelly the error log is not very descriptive. I'll take a look next week.

**Comment by foolip** [comment]
Diff at https://wpt.fyi/results/?diff&filter=ADC&run_id=436640016&run_id=425090003 looks like an overall improvement, especially lots of encodings tests were fixed.

**Review by KyleJu — APPROVED** [review]

**Pull request merged**
