### PR TITLE
Use manifest downloading when running tests

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7930)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-20 18:34:02
Finished: 2017-10-20 18:37:48


<h2>Failing Jobs</h2>
<ul>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19766)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/290559299)

**Comment by jgraham** [comment]
@mjzffr want to review this?

**Comment by mjzffr** [comment]
@jgraham sure, will get to it late Friday

**Comment by mjzffr** [comment]
lgtm, just a couple of questions. 

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 34 at r3](https://reviewable.io:443/reviews/w3c/web-platform-tests/7930#-KxVSMPy04ObakYL-jYq:-KxVSMPy04ObakYL-jYr:bj15fcg) ([raw file](https://github.com/w3c/web-platform-tests/blob/7b8785b3141953ecf6bb181f056281b360daaed6/.travis.yml#L34)):*
> ```YAML
>         api_key:
>           secure: "EljDx50oNpDLs7rzwIv+z1PxIgB5KMnx1W0OQkpNvltR0rBW9g/aQaE+Z/c8M/sPqN1bkvKPybKzGKjb6j9Dw3/EJhah4SskH78r3yMAe2DU/ngxqqjjfXcCc2t5MKxzHAILTAxqScPj2z+lG1jeK1Z+K5hTbSP9lk+AvS0D16w="
>         file: $MANIFEST_FILE
> ```

Should this be WPT_MANIFEST_FILE?

---

*[tools/manifest/download.py, line 81 at r3](https://reviewable.io:443/reviews/w3c/web-platform-tests/7930#-KxVYkxWp2INU5zPIYWM:-KxVYkxX4APOpFqkRrby:b-xxa4vj) ([raw file](https://github.com/w3c/web-platform-tests/blob/7b8785b3141953ecf6bb181f056281b360daaed6/tools/manifest/download.py#L81)):*
> ```Python
>         resp = urllib2.urlopen(url)
>     except Exception:
>         logger.warning("Downloading pregenreated manifest failed")
> ```

pregenerated

---

*[tools/manifest/download.py, line 129 at r3](https://reviewable.io:443/reviews/w3c/web-platform-tests/7930#-KxVZlQAckAnSmtEQ1qy:-KxVZlQAckAnSmtEQ1qz:b3crb7b) ([raw file](https://github.com/w3c/web-platform-tests/blob/7b8785b3141953ecf6bb181f056281b360daaed6/tools/manifest/download.py#L129)):*
> ```Python
>     else:
>         path = kwargs["path"]
>     download_from_github(path, kwargs["tests_root"], kwargs["force"])
> ```

Do you want to exit with non-zero status if download fails?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7930#-:-KxVazKX8Wb2b5rzD4Zi:b-8sbab4)*

**Review by mjzffr — APPROVED** [review]

**Pull request merged**
