### PR TITLE
Revert "Move the config into its own class (#10231)"

### LINKED ISSUE #10667: wptserve sometimes throws IndexError when {{sub}} is used
Example test: `html/semantics/scripting-1/the-script-element/module/crossorigin.html`
which refers to this resource that uses server-side substitution: [`html/semantics/scripting-1/the-script-element/module/crossorigin-root-wrongheader.sub.html`](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/scripting-1/the-script-element/module/crossorigin-root-wrongheader.sub.html)

Loading this resource a few times, you will soon find wptserve returning 500 with the following traceback:
```
Traceback (most recent call last):                                                                                                                                                                                                                             
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/server.py", line 256, in handle_one_request                                                                                                                          
    handler(request, response)                                                                                                                                                                                                                                 
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 151, in __call__                                                                                                                                  
    response = wrap_pipeline(path, request, response)                                                                                                                                                                                                          
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 117, in wrap_pipeline                                                                                                                             
    response = pipeline(request, response)                                                                                                                                                                                                                     
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 36, in __call__                                                                                                                                      
    response = func(request, response, *args)                                                                                                                                                                                                                  
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 129, in inner
    return f(request, response, *arg_values)
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 375, in sub
    new_content = template(request, content, escape_type=escape_type)
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 489, in template
    new_content = template_regexp.sub(config_replacement, content)
  File "/usr/local/google/home/robertma/github/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 472, in config_replacement
    value = value[item[1]]
IndexError: list index out of range
```

The error seems non-deterministic. Refresh the page and you can see the error comes and goes. This is a relatively new bug. Based on Chromium CI, we think it was introduced between d00f7bab7aecadbc2fc9a47172d090b4ba7e2ef2 and 507af0c03617714bfd4134c54da4d534906ee52b (the last two wptserve rolls in Blink).

@gsnedders perhaps related to your recent refactor of config?

### PR DESCRIPTION
**Pull request by Hexcles**
This reverts commit bfef1f20a419d24633e48d24c14e6a7503e1d48c (#10231)

Confirmed that this revert would fix #10667 locally by requesting `html/semantics/scripting-1/the-script-element/module/crossorigin-root-wrongheader.sub.html` 100 times. No exception was seen, whereas currently almost half of the requests fail because of IndexError (see #10667 for full details).

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10696)

### CODE REVIEW

**Comment by Hexcles** [comment]
cc @foolip

**Comment by jgraham** [comment]
I'm pretty worried that reverting this will cause just as many problems :/

**Comment by Hexcles** [comment]
I thought the original CL was just a code-health refactor, no? Did it actually try to fix any issues?

I can run this revert in Chromium CI to minimize the risk of breaking things.

**Comment by jgraham** [comment]
The problem is that there was a lot of fallout resulting in followup, and unless we carefully reverted everything, it's likely that we miss some callers or whatever and so end up with another broken state.

**Comment by gsnedders** [comment]
And some of the fallout that was caught was things that were subtly broken before and then became a fatal error, though presumably we could live with that breakage.

**Comment by Hexcles** [comment]
Abandoned (replaced by a proper fix #10723 )

**Pull request closed without merging**
