### PR TITLE
HTML: document.open() and the unload event

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/pull/3918.

### CODE REVIEW

**Comment by annevk** [comment]
This strongly suggests browsers don't run

> Unload document, with the recycle parameter set to true.

unless I'm missing something.

**Comment by annevk** [comment]
cc @bzbarsky @jeisinger

**Review by foolip — APPROVED** [review]
Test itself is straightforward, but I presume this should be merged together with a spec PR related to https://github.com/whatwg/html/pull/3651?

**Comment by TimothyGu** [comment]
@foolip Yes.

**Review by foolip — APPROVED** [review]

**Pull request merged**
