### PR TITLE
Add interfaces/box-tree-api.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/5c53f34/ed/idl/box-tree-api.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/672386095

### CODE REVIEW

**Comment by foolip** [comment]
@bfgeek what is the status of this spec? Will it be useful to have the idlharness tests in WPT?

**Comment by tabatkins** [comment]
This spec should not be considered implementable yet, afaik, so we shouldn't commit any tests for it.

**Comment by stephenmcgruer** [comment]
As of 2020/04/10, I believe this API is still very much not implemented.

@foolip - is there any consideration to removing this from reffy? Not that it matters to have these PRs lying around, it's just cruft that builds up.

**Comment by tabatkins** [comment]
It can def be removed.

**Comment by foolip** [comment]
I've sent https://github.com/tidoust/reffy/pull/282 but anticipate some skepticism, let's discuss there.

**Pull request closed without merging**
