### PR TITLE
Replacing inline style with css rules in 8 origin-*-ref.html files

### PR DESCRIPTION
**Pull request by TalbotG**
If you look at

https://wpt.fyi/results/css/css-backgrounds/background-origin

now, you will see that several tests fail but this is - I believe - because there is inline style in the reference files. This PR attempts to fix this in 8 reference files. I believe the remaining test failures are due to fuzziness anti-aliasing and I will correct those later and in another PR.

So, over at my website, the 8 reference files (preceded by their associated tests) are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-border-box-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-border-box-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-border-box_with_position-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-border-box_with_position-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-border-box_with_radius-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-border-box_with_radius-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-border-box_with_size-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-border-box_with_size-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-content-box_with_position-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-content-box_with_position-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-content-box_with_size-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-content-box_with_size-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-padding-box_with_position-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-padding-box_with_position-new-ref.html

- - -

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-origin/origin-padding-box_with_size-new-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/origin-padding-box_with_size-new-ref.html

### CODE REVIEW

**Review by fantasai — APPROVED** [review]
Not sure what this fixes, but it seems correct and makes the test a little more readable so OK.

**Comment by TalbotG** [comment]
@fantasai ,

The patch (commit 3386780) in this PR did **not** succeed. So, I did not fix the problem with and/or in the reference files.

**I have created Issue #43329 hoping to find out what I can do and should be doing to those reference files.**

**Comment by dbaron** [comment]
You don't need to wait for a PR to be merged to see wpt.fyi results.  You can go to the "Checks" tab for the PR, and then choose from the following checks in the sidebar on the left:

> wpt.fyi
> wpt.fyi - chrome[experimental]
> wpt.fyi - firefox[experimental]
> wpt.fyi - safari[experimental]

**Comment by TalbotG** [comment]
> You don't need to wait for a PR to be merged to see wpt.fyi results. (...)

Indeed, I can now see the wpt.fyi results with comparison of screenshots. Thank you, David, for this tip.

**Pull request merged**
