### PR TITLE
Make expectations optional when testing the framework

### PR DESCRIPTION
**Pull request by tobie**
This provides more consistency with the rest of the test suite and greatly simplifies test authoring.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6233)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242746999)

# Firefox (nightly) #
Testing web-platform-tests at revision 5b00d44d10c652116fd42853c646e6aa9c02ff16
Ignoring 2 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242747001)

# Sauce (safari) #
Testing web-platform-tests at revision 5b00d44d10c652116fd42853c646e6aa9c02ff16
Ignoring 2 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242747010)

# Chrome (unstable) #
Testing web-platform-tests at revision 5b00d44d10c652116fd42853c646e6aa9c02ff16
Ignoring 2 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242747011)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 5b00d44d10c652116fd42853c646e6aa9c02ff16
Ignoring 2 changed files:
No files changed

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6233)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
