### PR TITLE
Encoding: ensure buffer modifications do not affect results

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/encoding/issues/92.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5172/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/212682426)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e331c587a0a354cf3e730d8b2ae8b30c11b70934
Using browser at version BuildID 20170318110156; SourceStamp 23a4b7430dd7e83a2809bf3dc41471f154301eda
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/212682427)

# Chrome (unstable channel) #
Testing web-platform-tests at revision e331c587a0a354cf3e730d8b2ae8b30c11b70934
Using browser at version 59.0.3043.0 dev
Starting 10 test iterations
No tests run.

**Comment by inexorabletash** [comment]
lgtm

**Pull request merged**
