### PR TITLE
Move ci scripts to tools/ci

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5724)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5724/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226501076)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226501078)

# Firefox (nightly channel) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226501084)

# Chrome (unstable channel) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236005441)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236005442)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236005448)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236005449)

# Sauce (MicrosoftEdge) #

**Comment by bobholt** [comment]
Current state: Various errors in pytest jobs. This has been rebased on top of current (b369eca1d18725d94f7ce99862de113de393b69f) master.

The last 2 commits (fb027a750506550b0d4be01bf547f30b4aedd2ef and 782863d1d05768786611bb6d735611b6ac86acc5) were added due to Travis being unable to find the `mozinfo` and `mozlog` modules. This occurred after rebasing on top of eb03407caedc4847867be415db35e1bba5bdb74b.

**Comment by jgraham** [comment]
This was done as part of the `wpt` work.

**Pull request closed without merging**
