### PR TITLE
[testharness.js] Remove code working around issues in IE

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by jgraham — APPROVED** [review]
I guess this is safe enough to land without a full trigger run, but please check the results on master in case we missed something.

**Comment by foolip** [comment]
When the runs are done we should compare these:

Before: https://wpt.fyi/runs?sha=8ad2ee6048fea07eea25bd597653b9d4932c2a14
After: https://wpt.fyi/runs?sha=f0d3621b1a7981b26229568c093b2a2f508eef90

**Comment by foolip** [comment]
Oh, I was confused, this wasn't idlharness.js cleanup, it's testharness.js. Taking a closer look.

**Comment by foolip** [comment]
I've stepped through all of the diffs and can't spot anything obviously suspicious.

**Comment by foolip** [comment]
I've also searched for the string "Stack trace unavailable" in these full reports to confirm it's not there:
https://storage.googleapis.com/wptd-results/f0d3621b1a7981b26229568c093b2a2f508eef90/chrome-101.0.4929.5_dev-linux-20.04-05c43953b9/report.json
https://storage.googleapis.com/wptd-results/f0d3621b1a7981b26229568c093b2a2f508eef90/firefox-100.0a1-linux-20.04-a30657139a/report.json
https://storage.googleapis.com/wptd-results/6250e992ac750edc5994a0712fdb6e6f6636ffe3/safari-141_preview-mac-11.6-e453c09500/report.json

**Pull request merged**
