### PR TITLE
Add interfaces/intervention-reporting.idl and test

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Closes https://github.com/web-platform-tests/wpt/pull/24193

### CODE REVIEW

**Comment by foolip** [comment]
Per https://wpt.fyi/results/intervention-reporting?sha=bbfa81ff2b&label=pr_head no implementation supports any of this. Is this intended to be exposed to the web?

**Comment by stephenmcgruer** [comment]
> Is this intended to be exposed to the web?

cc @clelland for this question

**Comment by clelland** [comment]
Chromium's IDL has this marked as NoInterfaceObject, so that's not exposed. That's been deprecated in WebIDL though, so we should probably remove that attribute.

Objects of this type are web-exposed; they're what you'd see as the `body` attribute of an intervention report delivered via a reporting observer.

**Comment by stephenmcgruer** [comment]
Thanks Ian; we should merge this then and let Chromium fail it until its IDL is fixed.

Ping @foolip for review :)

**Review by foolip — APPROVED** [review]

**Pull request merged**
