### PR TITLE
Check [NewObject] on show(), use webdriver

### LINKED ISSUE #12082: Refactor PaymentRequest button tests to use `test_driver.bless()`
We could refactor a bunch of payment-request tests: 

- [x] payment-request/payment-request-abort-method.https.html
- [x] payment-request/payment-request-show-method.https.html

### PR DESCRIPTION
**Pull request by marcoscaceres**
Tests for: https://github.com/w3c/payment-request/pull/746/

closes #12082

PaymentRequest: 

- [x] show()
- [x] canMakePayment()
- [x] abort()

PaymentResponse: 

- [x] complete()
- [x] retry() - included it in https://github.com/web-platform-tests/wpt/pull/11101

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Yay! we can automate .show() 💃 🕺

**Comment by marcoscaceres** [comment]
Ok, @lukebjerring. I've updated to use bless(). The rest of the tests should be the same.

**Review by lukebjerring — APPROVED** [review]
Rubber stamping (on a mobile device so can't verify the tests locally) but the switches to `bless` LGTM

**Comment by marcoscaceres** [comment]
> Rubber stamping

Good enough for me :) Thanks @lukebjerring!!!

**Pull request merged**
