### PR TITLE
Adding tests to ensure fetch Response body chunks are cloned

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by annevk** [comment]
This needs to be rebased. I'm probably also not the best person to review this. Maybe @domenic or @yutakahirano.

**Comment by domenic** [comment]
Hmm. I am not sure I like this outcome, in particular that `stream1` is different from `response.body` and that all the data within it is cloned. That makes sense when you pass the response across a worker -> main thread boundary. But it seems very wasteful when operating within the same thread.

Does this mean that we mandate two buffer copies in the service worker case? One from the bodyInit stream passed in to `response.body` in the service worker; then a second one from the service worker `response.body` to the main thread `response.body`? That seems wrong.

**Comment by youennf** [comment]
Response clone is using ReadableStream teeing with shouldClone=true.

Teeing could probably be optimized since it creates two copies of the original streamed object, one for each branch. But this looks bad to have one teed branch with cloned data and the other with original data.

If ReadableStream spec could support a clone operation that fetch would use instead of teeing...

**Comment by annevk** [comment]
@domenic if that's a serious concern please file issues against Fetch and Streams (and maybe fetch-with-streams). It seems like we should sort those out with the community there and rather quickly.

**Comment by domenic** [comment]
This is now fixed in streams, with fetch inheriting the fix. @youennf would you mind updating the tests? I'm happy to be the reviewer.

Really glad you caught this!

**Comment by youennf** [comment]
Sure, I'll update the tests

**Pull request merged**
