### PR TITLE
Add interfaces/svg-markers.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/0cb115a/ed/idl/svg-markers.idl
Build: https://travis-ci.org/w3c/webref/builds/723814389

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
This will need an equivalent idlharness.html test

**Comment by stephenmcgruer** [comment]
cc @foolip 

Ah, there's a problem here. `SVGMarkerElement` is already defined in SVG (https://svgwg.org/svg2-draft/painting.html#InterfaceSVGMarkerElement), which this spec depends on (for SVGLineElement, etc)... which means you then get duplicate definitions of `SVGMarkerElement`. 

@heycam (editor of svg-markers) - do you know why `SVGMarkerElement` seems to have its own spec but also be defined in https://svgwg.org/svg2-draft/painting.html#InterfaceSVGMarkerElement ? Is there a plan to consolidate these?

**Comment by heycam** [comment]
> @heycam (editor of svg-markers) - do you know why `SVGMarkerElement` seems to have its own spec but also be defined in https://svgwg.org/svg2-draft/painting.html#InterfaceSVGMarkerElement ? Is there a plan to consolidate these?

The separate svg-markers spec was split off from SVG 2, since it added some new features that nobody implemented, and we didn't want to burden SVG 2 with speculative features like this. I suppose the accepted way to build modules in specs that define interfaces like this would be to have svg-markers use a `mixin interface`, rather than copy the definitions from SVG 2. It looks like svg-markers doesn't make any changes to `SVGMarkerElement`, so perhaps we can just remove that section, and leave all the links to automatically go to SVG 2.

**Comment by heycam** [comment]
Also, confusingly, there are two copies of the SVG Markers spec: https://svgwg.org/specs/markers/ (the one I originally wrote, using the old SVG spec markup system), and https://svgwg.org/specs/marker/ (the Bikeshed conversion that Dirk made).

**Comment by stephenmcgruer** [comment]
> perhaps we can just remove that section, and leave all the links to automatically go to SVG 2.

That would be great if you can find the time :)

> Also, confusingly, there are two copies of the SVG Markers spec: https://svgwg.org/specs/markers/ (the one I originally wrote, using the old SVG spec markup system), and https://svgwg.org/specs/marker/ (the Bikeshed conversion that Dirk made).

Could one of them be removed? It isn't causing problems but might be confusing for readers (especially if/when they get out of sync). Looks like currently reffy is using https://svgwg.org/specs/markers/, and [explicitly ignores](https://github.com/w3c/browser-specs/blob/aea894c904d36b3317a0a30bbb4b73c3fde6ad71/src/data/ignore.json#L119) https://svgwg.org/specs/marker/

**Pull request closed without merging**
