### PR TITLE
Move MS table tests out of work-in-progress

### PR DESCRIPTION
**Pull request by gsnedders**
see @FremyCompany's comment in #7453 

Also fix lints we allowed in work-in-progress given there's not been that much work on them recently so we may as well just fix them now.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7454)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>chrome:unstable</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Chrome Unstable"<small> (failures allowed)</small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/18790.10">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/279087729">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  <tr>
    <td><code>/css/css-tables-3/html5-table-formatting-3.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Anonymous consecutive columns spanned by the same set of cells are merged</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Anonymous consecutive rows spanned by the same set of cells are merged</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: expected 100 but got 75</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Control test for table-cell padding and border-spacing, etc (width)</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Control test for table-cell padding and border-spacing (height)</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Explicitely-defined consecutive columns spanned by the same set of cells are not merged</code></td>
    <td>FAIL: 8<br />PASS: 2<br /></td>
    <td><code>assert_equals: expected 75 but got 50</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Explicitely-defined consecutive columns spanned by the same set of cells are not merged, and cells span across border-spacing</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: expected 12.5 but got 0</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Explicitely-defined consecutive rows spanned by the same set of cells are not merged</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>Explicitely-defined consecutive rows spanned by the same set of cells are not merged, and cells span across border-spacing</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: expected 12.5 but got 12</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  </table>

**Comment by gsnedders** [comment]
No clear reason for Chrome to flaky here, FYI.

**Comment by FremyCompany** [comment]
I'll take a look at the flaky test next week. That's weird.

Otherwise, I just spotted `tools/markup-generator.html` which I think is not a test but a small thing I had built to generate random tables and explore differences between browsers; if that's right it shouldn't be committed as test collateral at all, feel free to delete entirely.

**Comment by gsnedders** [comment]
@FremyCompany Yeah, there's no obvious cause for the flakiness when I looked into it a bit. It's a really simple test so I'm definitely blaming Blink there.

And yeah, that tool does appear to be that.

**Comment by gsnedders** [comment]
(Like, I mean, I'm 99.9% sure it's a Blink problem so we should just land this)

**Review by Ms2ger — APPROVED** [review]
Please autosquash, and rebase&merge.

**Pull request merged**
