### PR TITLE
adds test coverage for the html ul@type

### PR DESCRIPTION
**Pull request by common-nighthawk**

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by Ms2ger** [comment]
(Testing.)

Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by zcorpan** [comment]
Thanks! Next up `li`? :-)

**Comment by common-nighthawk** [comment]
sounds good!  yeah--ill create tests for `li` tomorrow.

**Pull request merged**
