### PR TITLE
Sort stability test results by execution order

### LINKED ISSUE #4515: wpt-stability-bot: report results in test order rather than Python (unordered) dict order
That would make it easier to scan the results. Especially for generated tests that have some kind of sequence.

### PR DESCRIPTION
**Pull request by jugglinmike**
This should resolve gh-4515.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision efe5cfecd7702d9720e9f8be601cb6f03a204a91
Using browser at version 58.0.3000.4 dev
Starting 10 test iterations
## Unstable results ##


|          Test          |                 Subtest                 |          Results           |
|------------------------|-----------------------------------------|----------------------------|
| `/url/historical.html` | `URL.domainToASCII should be undefined` | **FAIL: 2/10, PASS: 8/10** |

## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4745/url/historical.html">/url/historical.html</a></summary>


|                   Subtest                    |          Results           |
|----------------------------------------------|----------------------------|
|                                              | OK                         |
| `searchParams on location object`            | PASS                       |
| `searchParams on a element`                  | PASS                       |
| `searchParams on area element`               | PASS                       |
| `Setting URL's href attribute and base URLs` | FAIL                       |
| `URL.domainToASCII should be undefined`      | **FAIL: 2/10, PASS: 8/10** |
| `URL.domainToUnicode should be undefined`    | PASS                       |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision efe5cfecd7702d9720e9f8be601cb6f03a204a91
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
## Unstable results ##


|          Test          |                 Subtest                 |          Results           |
|------------------------|-----------------------------------------|----------------------------|
| `/url/historical.html` | `URL.domainToASCII should be undefined` | **FAIL: 3/10, PASS: 7/10** |

## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4745/url/historical.html">/url/historical.html</a></summary>


|                   Subtest                    |          Results           |
|----------------------------------------------|----------------------------|
|                                              | OK                         |
| `searchParams on location object`            | PASS                       |
| `searchParams on a element`                  | PASS                       |
| `searchParams on area element`               | PASS                       |
| `Setting URL's href attribute and base URLs` | PASS                       |
| `URL.domainToASCII should be undefined`      | **FAIL: 3/10, PASS: 7/10** |
| `URL.domainToUnicode should be undefined`    | PASS                       |

</details>

**Comment by jugglinmike** [comment]
This is an infrastructure-related patch; the modification to the URL test is intended for demonstration purposes only and should be removed prior to landing. Sorry for the noise, reviewers!

**Comment by zcorpan** [comment]
From @w3c-bots comments above, looks like it works!

**Comment by bobholt** [comment]
@jgraham: Chiming in asking for a review when you have a moment. I'd love to see this landed before I continue working on surfacing test failure messages in the build bot (I need to make the same nested `defaultdict` refactor @jugglinmike has helpfully already done here).

**Comment by jugglinmike** [comment]
@jgraham Bob let me know that GitHub is reporting that there is a merge
conflict here, but I just rebased locally without any issue. I'm happy to
force-push that rebased version anyway in case it helps, but I'll wait until I
hear from you (I don't want to disrupt you if you've already started reviewing
the current version).

**Comment by jugglinmike** [comment]
Thanks, Michael!

**Pull request closed without merging**
