### PR TITLE
Update Safari Technology Preview to 114

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 114, 15611.1.1.3)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=2209&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
@gsnedders FYI https://github.com/foolip/safari-technology-preview-updater/commit/ab839ffafb96fd7ad4672e2ded0bc2e19001bba8 is what I had to do to make the updater create this PR.

**Comment by stephenmcgruer** [comment]
Looks like we have two unexpected-oks from infrastructure tests, which is awesome:

```
------------------
/infrastructure/testdriver/actions/actionsWithKeyPressed.html
  UNEXPECTED-OK /infrastructure/testdriver/actions/actionsWithKeyPressed.html
/infrastructure/testdriver/actions/multiDevice.html
  UNEXPECTED-OK /infrastructure/testdriver/actions/multiDevice.html
```

They'll need their metadata updated.

**Review by gsnedders — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
@gsnedders @foolip 113 / 114 diff - https://wpt.fyi/results/?diff&filter=ADC&run_id=719940001&run_id=706900002

**Comment by stephenmcgruer** [comment]
And this is the impact on browser-specific failures from https://github.com/ecosystem-Infra/wpt-results-analysis

image

Notice the jump in Firefox; that means STP 114 fixed a number of tests that previously only passed in Chrome. This can be seen by comparing Chrome against STP directly (dropping Firefox):

```
sha,date,chrome-version,chrome,safari-version,safari
411d1bfc11c5779664101d938b290e0dd26d812d,2020-10-09,87.0.4280.11 dev,670.931708587382,113 preview,8043.940419927994
ce0c9bd2cafd34910fc00d30a8210b3402b08860,2020-10-10,87.0.4280.11 dev,678.2155166128903,114 preview,7715.741673697199
```

**Comment by foolip** [comment]
Thanks @stephenmcgruer, that's good progress. Triaging the new Firefox-only failures would be interesting I think, especially if there are existing Gecko bugs where the change in implementation status can be communicated.

**Pull request merged**
