### PR TITLE
Test that setTransform and addPath ignore infinite and NaN values

### PR DESCRIPTION
**Pull request by wisniewskit**
Changes requested in https://github.com/whatwg/html/pull/2975

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18565)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/275690962)

**Comment by zcorpan** [comment]
https://github.com/w3c/web-platform-tests/pull/7355/files#diff-a626627910bf17165ba8b9d76af434daR26

Can you include `setTransform` in the test name, and also test `addPath` for these inputs?

https://github.com/w3c/web-platform-tests/pull/7355/files#diff-a626627910bf17165ba8b9d76af434daR34

Similarly here. A sanity check for `addPath` could be to omit the second argument.

**Comment by wisniewskit** [comment]
@zcorpan, any chance that you'll be able to review this anytime soon?

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
Commits c7ed55ce2abeb789797a04b108f097c4bf94a4a1 plus 94aa0f951cbdbdcfa234e18db7af2edda66cf93a LGTM; this branch includes 3 other commits also. Can you clean up this branch so that it has only your additions, maybe squashed and rebased on latest master?

**Review by marcoscaceres — CHANGES_REQUESTED** [review]
Any idea why paymentRequest stuff was included here? was it a bad rebase or did something actually change. I'd prefer this not get merged till we clarify that?

**Comment by sideshowbarker** [comment]
> Any idea why paymentRequest stuff was included here? was it a bad rebase or did something actually change. I'd prefer this not get merged till we clarify that?

See the https://github.com/w3c/web-platform-tests/pull/7355#issuecomment-331377410 from @zcorpan. Looks like the commits on this branch other than c7ed55c and 94aa0f9 need to be deleted and this branch rebased — and then re-reviewed to make sure it’s then in the right state to merge to master

**Comment by marcoscaceres** [comment]
ah, sorry... thanks for the clarification @sideshowbarker. Will wait to see those, then unblock merging.

**Comment by wisniewskit** [comment]
@zcorpan, something was strange with my local repo, so I ended up making a new pull request with the squashed+rebased patches in #7473.

**Comment by marcoscaceres** [comment]
Closing, as this is now obsolete.

**Pull request closed without merging**
