### PR TITLE
[webrtc-stats] add META.yml

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/w3c/web-platform-tests/pull/10577 (cc @dontcallmedom)

### CODE REVIEW

**Review by vr000m — APPROVED** [review]

**Comment by zcorpan** [comment]
@alvestrand are you OK with being listed in the OWNERS file here? It means you’ll get notified any time someone submits a PR. And the tests could only be merged to the master branch after review from one of the OWNERS.

**Comment by foolip** [comment]
@henbos you'd be the best reviewer on the Chromium side for this, right?

**Review by henbos — COMMENTED** [review]
Me being owner of testing of webrtc-stats spec SGTM, but what is this webrtc-stats/ directory?

Currently stats are tested as part of the webrtc/ directory. We have two specs, like so:

webrtc spec: Defines RTCPeerConnection.getStats(), RTCRtpSender.getStats(), RTCRtpReceiver.getStats(), RTCStatsReport, RTCStats.

webrtc-stats spec: Defines all RTCStats-derived dictionaries that an RTCStatsReport may contain.

We could move tests to a webrtc-stats/ directory there but there would be overlap of behaviors of the two specs and of helpers utils etc, so I don't think we want to do that.

**Comment by foolip** [comment]
@vr000m, can you accept the invite to the web-platform-tests org? Otherwise @wpt-pr-bot will not be able to assign you as a reviewer to any PRs.

**Review by alvestrand — APPROVED** [review]

**Pull request merged**
