### PR TITLE
Map tests for 3D transforms

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by jcscottiii — APPROVED** [review]
Feature Name exists at https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/transforms3d.yml

LGTM

**Review by dbaron — COMMENTED** [review]
Does the `css/css-transforms/` one apply to subdirectories?

If so, why does the `animation/` subdirectory need another one?

If not, don't some of the other subdirectories need one too?

**Comment by dbaron** [comment]
(In particular, `parsing/` and `crashtests/` both appear to have relevant tests, although maybe `crashtests/` doesn't matter.)

**Comment by foolip** [comment]
@dbaron only the special "**" rule applies recursively, so one file per directory is needed here.

A lot of tests seem to cover parts of both 2D and 3D transforms, so there are many that I don't know what to do with. But I'll take a look at all of the subdirectories and see if there are any that I missed.

**Comment by dbaron** [comment]
I think it's just the 2 I mentioned above -- and I'm not sure whether we care about `crashtests` directories for these mappings.

**Comment by foolip** [comment]
@dbaron I've mapped parsing/ now as well. There's nothing preventing mapping of crashtests, but I think that when I look at tests for a feature on wpt.fyi, I'll probably filter out tentative tests and crashtests. So I'm not spending the time to exclude crashtests if they happen to be caught by a pattern, but also am not taking the time to look through crashtests in subdirectories.

**Review by dbaron — APPROVED** [review]

**Pull request merged**
