### PR TITLE
Add tests for elementsFromPoint

### PR DESCRIPTION
**Pull request by alijuma**
This adds more test coverage for elementsFromPoint. These tests are currently under review downstream in WebKit, as part of https://bugs.webkit.org/show_bug.cgi?id=153137.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254576939)

# Firefox (nightly) #
Testing web-platform-tests at revision caeea16ddb20a4931544a89b1767b61880281a50
Using browser at version BuildID 20170717100212; SourceStamp aff336ac161daa3ea350e59a288963edbd58ed39
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-iframes.html">/cssom-view/elementsFromPoint-iframes.html</a></summary>


|                                Subtest                                 | Results | Messages |
|------------------------------------------------------------------------|---------|----------|
|                                                                        | OK      |          |
| `elementsFromPoint on the root document for points in iframe elements` | PASS    |          |
| `elementsFromPoint on inner documents`                                 | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-invalid-cases.html">/cssom-view/elementsFromPoint-invalid-cases.html</a></summary>


|                                             Subtest                                             | Results | Messages |
|-------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                 | OK      |          |
| `The root element is the last element returned for otherwise empty queries within the viewport` | PASS    |          |
| `The root element is the last element returned for valid queries`                               | PASS    |          |
| `An empty sequence is returned for queries outside the viewport`                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-shadowroot.html">/cssom-view/elementsFromPoint-shadowroot.html</a></summary>


|  Subtest   | Results |                     Messages                     |
|------------|---------|--------------------------------------------------|
|            | OK      |                                                  |
| `Untitled` | FAIL    | `TypeError: host.attachShadow is not a function` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-simple.html">/cssom-view/elementsFromPoint-simple.html</a></summary>


|                                             Subtest                                             | Results | Messages |
|-------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                 | OK      |          |
| `elementsFromPoint for each corner of a simple div`                                             | PASS    |          |
| `elementsFromPoint for each corner of a div that has a pseudo-element`                          | PASS    |          |
| `elementsFromPoint for each corner of a div that is between another div and its pseudo-element` | PASS    |          |
| `elementsFromPoint for each corner of a div that has a margin`                                  | PASS    |          |
| `elementsFromPoint for each corner of a div with pointer-events:none`                           | PASS    |          |
| `elementsFromPoint for each corner of a div with a 3d transform`                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-svg.html">/cssom-view/elementsFromPoint-svg.html</a></summary>


|                                Subtest                                 | Results | Messages |
|------------------------------------------------------------------------|---------|----------|
|                                                                        | OK      |          |
| `elementsFromPoint for a point inside two rects`                       | PASS    |          |
| `elementsFromPoint for a point inside two rects that are inside a <g>` | PASS    |          |
| `elementsFromPoint for a point inside two images`                      | PASS    |          |
| `elementsFromPoint for a point inside transformed rects and <g>`       | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-table.html">/cssom-view/elementsFromPoint-table.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `elementsFromPoint for points inside table cells`                                         | PASS    |          |
| `elementsFromPoint for points between table cells`                                        | PASS    |          |
| `elementsFromPoint for points inside cells in a right-to-left table`                      | PASS    |          |
| `elementsFromPoint for points inside cells in a flipped (writing-mode:vertical-lr) table` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254576940)

# Sauce (safari) #
Testing web-platform-tests at revision caeea16ddb20a4931544a89b1767b61880281a50
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-iframes.html">/cssom-view/elementsFromPoint-iframes.html</a></summary>


|                                Subtest                                 | Results |                                                                                                                           Messages                                                                                                                           |
|------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                        | OK      |                                                                                                                                                                                                                                                              |
| `elementsFromPoint on the root document for points in iframe elements` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(1,1)', 'document.elementsFromPoint' is undefined)`                                                                                                                            |
| `elementsFromPoint on inner documents`                                 | FAIL    | `document.getElementById('iframe').contentDocument.elementsFromPoint is not a function. (In 'document.getElementById('iframe').contentDocument.elementsFromPoint(1,1)', 'document.getElementById('iframe').contentDocument.elementsFromPoint' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-invalid-cases.html">/cssom-view/elementsFromPoint-invalid-cases.html</a></summary>


|                                             Subtest                                             | Results |                                                                Messages                                                               |
|-------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                 | OK      |                                                                                                                                       |
| `The root element is the last element returned for otherwise empty queries within the viewport` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(300,300)', 'document.elementsFromPoint' is undefined)` |
| `The root element is the last element returned for valid queries`                               | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(199,199)', 'document.elementsFromPoint' is undefined)` |
| `An empty sequence is returned for queries outside the viewport`                                | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(801,563)', 'document.elementsFromPoint' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-shadowroot.html">/cssom-view/elementsFromPoint-shadowroot.html</a></summary>


|                                       Subtest                                       | Results |                                                                   Messages                                                                   |
|-------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                     | OK      |                                                                                                                                              |
| `elementsFromPoint on the document root should not return elements in shadow trees` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(50,45)', 'document.elementsFromPoint' is undefined)`          |
| `elementsFromPoint on a shadow root should include elements in that shadow tree`    | FAIL    | `shadowRoot.elementsFromPoint is not a function. (In 'shadowRoot.elementsFromPoint(x12, y12)', 'shadowRoot.elementsFromPoint' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-simple.html">/cssom-view/elementsFromPoint-simple.html</a></summary>


|                                             Subtest                                             | Results |                                                                Messages                                                               |
|-------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                 | OK      |                                                                                                                                       |
| `elementsFromPoint for each corner of a simple div`                                             | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(1,1)', 'document.elementsFromPoint' is undefined)`     |
| `elementsFromPoint for each corner of a div that has a pseudo-element`                          | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(51,51)', 'document.elementsFromPoint' is undefined)`   |
| `elementsFromPoint for each corner of a div that is between another div and its pseudo-element` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(101,101)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for each corner of a div that has a margin`                                  | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(1,186)', 'document.elementsFromPoint' is undefined)`   |
| `elementsFromPoint for each corner of a div with pointer-events:none`                           | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(51,51)', 'document.elementsFromPoint' is undefined)`   |
| `elementsFromPoint for each corner of a div with a 3d transform`                                | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(41,41)', 'document.elementsFromPoint' is undefined)`   |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-svg.html">/cssom-view/elementsFromPoint-svg.html</a></summary>


|                                Subtest                                 | Results |                                                                Messages                                                               |
|------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------|
|                                                                        | OK      |                                                                                                                                       |
| `elementsFromPoint for a point inside two rects`                       | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(125,125)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for a point inside two rects that are inside a <g>` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(225,225)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for a point inside two images`                      | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(125,325)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for a point inside transformed rects and <g>`       | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(325,325)', 'document.elementsFromPoint' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-table.html">/cssom-view/elementsFromPoint-table.html</a></summary>


|                                          Subtest                                          | Results |                                                                Messages                                                               |
|-------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                           | OK      |                                                                                                                                       |
| `elementsFromPoint for points inside table cells`                                         | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(125,125)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for points between table cells`                                        | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(100,100)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for points inside cells in a right-to-left table`                      | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(125,125)', 'document.elementsFromPoint' is undefined)` |
| `elementsFromPoint for points inside cells in a flipped (writing-mode:vertical-lr) table` | FAIL    | `document.elementsFromPoint is not a function. (In 'document.elementsFromPoint(125,275)', 'document.elementsFromPoint' is undefined)` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254576946)

# Chrome (unstable) #
Testing web-platform-tests at revision caeea16ddb20a4931544a89b1767b61880281a50
Using browser at version 61.0.3153.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-iframes.html">/cssom-view/elementsFromPoint-iframes.html</a></summary>


|                                Subtest                                 | Results | Messages |
|------------------------------------------------------------------------|---------|----------|
|                                                                        | OK      |          |
| `elementsFromPoint on the root document for points in iframe elements` | PASS    |          |
| `elementsFromPoint on inner documents`                                 | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-invalid-cases.html">/cssom-view/elementsFromPoint-invalid-cases.html</a></summary>


|                                             Subtest                                             | Results | Messages |
|-------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                 | OK      |          |
| `The root element is the last element returned for otherwise empty queries within the viewport` | PASS    |          |
| `The root element is the last element returned for valid queries`                               | PASS    |          |
| `An empty sequence is returned for queries outside the viewport`                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-shadowroot.html">/cssom-view/elementsFromPoint-shadowroot.html</a></summary>


|                                       Subtest                                       | Results | Messages |
|-------------------------------------------------------------------------------------|---------|----------|
|                                                                                     | OK      |          |
| `elementsFromPoint on the document root should not return elements in shadow trees` | PASS    |          |
| `elementsFromPoint on a shadow root should include elements in that shadow tree`    | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-simple.html">/cssom-view/elementsFromPoint-simple.html</a></summary>


|                                             Subtest                                             | Results | Messages |
|-------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                 | OK      |          |
| `elementsFromPoint for each corner of a simple div`                                             | PASS    |          |
| `elementsFromPoint for each corner of a div that has a pseudo-element`                          | PASS    |          |
| `elementsFromPoint for each corner of a div that is between another div and its pseudo-element` | PASS    |          |
| `elementsFromPoint for each corner of a div that has a margin`                                  | PASS    |          |
| `elementsFromPoint for each corner of a div with pointer-events:none`                           | PASS    |          |
| `elementsFromPoint for each corner of a div with a 3d transform`                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-svg.html">/cssom-view/elementsFromPoint-svg.html</a></summary>


|                                Subtest                                 | Results | Messages |
|------------------------------------------------------------------------|---------|----------|
|                                                                        | OK      |          |
| `elementsFromPoint for a point inside two rects`                       | PASS    |          |
| `elementsFromPoint for a point inside two rects that are inside a <g>` | PASS    |          |
| `elementsFromPoint for a point inside two images`                      | PASS    |          |
| `elementsFromPoint for a point inside transformed rects and <g>`       | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6568/cssom-view/elementsFromPoint-table.html">/cssom-view/elementsFromPoint-table.html</a></summary>


|                                          Subtest                                          | Results | Messages |
|-------------------------------------------------------------------------------------------|---------|----------|
|                                                                                           | OK      |          |
| `elementsFromPoint for points inside table cells`                                         | PASS    |          |
| `elementsFromPoint for points between table cells`                                        | PASS    |          |
| `elementsFromPoint for points inside cells in a right-to-left table`                      | PASS    |          |
| `elementsFromPoint for points inside cells in a flipped (writing-mode:vertical-lr) table` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254576947)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision caeea16ddb20a4931544a89b1767b61880281a50
Using browser at version 14.14393
Starting 10 test iterations

**Comment by alijuma** [comment]
The downstream patch in WebKit has been reviewed. Can this PR be merged now?

(Note: WebKit's workflow right now is that the upstream PR needs to be merged before the downstream patch lands, see [this webkit-dev message](https://lists.webkit.org/pipermail/webkit-dev/2017-July/029265.html) for more.)

**Comment by alijuma** [comment]
@youennf @RByers, these tests are part of a [WebKit patch](https://bugs.webkit.org/show_bug.cgi?id=153137) that has already been reviewed (and landing that patch is blocked on this PR getting merged first). Would one of you be willing to stamp/merge this?

**Review by jgraham — APPROVED** [review]

**Pull request merged**
