### PR TITLE
Add the tests for click-related events' order, bubble up, and

### PR DESCRIPTION
**Pull request by sunyunjia**
cancellation.

### CODE REVIEW

**Comment by dtapuska** [comment]
I can't find checkOrder anywhere.  Some of this seems duplicated in EventRecorder. I think we really should just expand out that class to have another function that asserts on some type of sequence of events.

**Comment by dtapuska** [comment]
@jdm Who is actively reviewing these changes? I'd like to ensure that Sandra isn't blocked waiting for reviews that aren't coming. Is there anyone that can be elected as an owner on the uievents repo? Like @garykac or myself or @RByers

**Comment by Ms2ger** [comment]
@dtapuska if you feel qualified to review those changes, go ahead and review them. Feel free to ping me on IRC (irc.w3.org, #testing) to merge any PRs you've approved.

**Comment by RByers** [comment]
Yes, fairly soon we will be using a similar process to Mozilla where any
chromium member who feels comfortable can review web-platform-test changes
(as part of the normal CR) and then we'll auto-push to GitHub.  So in the
interim, we can follow this "reviewed upstream" process manually rather
than wait for OWNERS in specific WPT directories (although if they have
feedback then we will of course want to hear it or be happy to submit
improvements after-the-fact).

**Comment by dtapuska** [comment]
Can we close this out? I think it is superseded by #3857

**Pull request closed without merging**
