### PR TITLE
Make some worker tests fail faster

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by Ms2ger** [comment]
I don't understand how the first commit helps.

**Comment by jdm** [comment]
Servo doesn't support SharedWorker, so a JS exception occurs and the harness doesn't see it.

**Comment by Ms2ger** [comment]
In my mental model of the code, an exception in the setup function should cause a harness error and finish immediately; does it not?

**Comment by jdm** [comment]
That does not appear to be the case - Servo timed out when running the tests before these changes.

**Comment by jdm** [comment]
https://github.com/web-platform-tests/wpt/blob/20a395098e9eeea523b38c36dbcf8a474b3be206/resources/testharness.js#L2190-L2196 certainly looks like it's supposed to do that, however.

**Comment by jdm** [comment]
Ok, I was wrong - it's not a harness timeout; the harness does identify the error correctly, but it then takes 10 seconds before the harness decides that the test is complete. This is inefficient compared to failing immediately.

**Comment by Ms2ger** [comment]
> Ok, I was wrong - it's not a harness timeout; the harness does identify the error correctly, but it then takes 10 seconds before the harness decides that the test is complete. This is inefficient compared to failing immediately.

@jgraham that doesn't sound like the behaviour I'd expect; what do you think?

**Comment by jdm** [comment]
@jgraham Ping on the question in the previous comment.

**Comment by jdm** [comment]
Even setting aside the question, I argue that my changes to the tests in question make them both more idiomatic and easier to understand @Ms2ger :)

**Comment by Ms2ger** [comment]
Alternative proposal for the SharedWorker tests: https://github.com/web-platform-tests/wpt/pull/19242

I'd still like feedback from @jgraham though

**Comment by jgraham** [comment]
Yeah, it definitely seems like a bug if the harness is taking 10s to decide the tests are done after recieving an error. We should call `this.complete()` in that catch block.

**Comment by jdm** [comment]
Addressed the review comments.

**Comment by jdm** [comment]
How do I tell what the actual failure is in the taskcluster log, @jgraham?

**Comment by Ms2ger** [comment]
Thanks for bearing with me, @jdm!

**Pull request merged**
