### PR TITLE
Update META.yml

### PR DESCRIPTION
**Pull request by svgeesus**
Add Sam Weinig to CSS Color reviewers

### CODE REVIEW

**Comment by svgeesus** [comment]
@smfr @tabatkins @foolip could someone please review and merge? Sam Weinig is implementing CSS Color 4 in Webkit, and also creating WPT tests. I can review his tests, but he can't review mine [like this one](https://github.com/web-platform-tests/wpt/pull/27337) so they sit for weeks waiting for review.

**Comment by foolip** [comment]
@svgeesus in addition to being listed in `META.yml`, one must also be a member of the reviewers team to have write access. @weinig I've sent an invite to you, which you should see at the top of https://github.com/web-platform-tests. After accepting, you'll probably want to follow the instructions at https://github.com/orgs/web-platform-tests/teams/reviewers/discussions/1 to unwatch the repositories, since you'll otherwise get way too many notifications.

This change would make sense to merge after @weinig has accepted the invite. The reviewer assigner bot can't assign anyone who isn't an org member, so just being listed in `META.yml` doesn't do much.

**Comment by svgeesus** [comment]
@weinig  did you accept the invite?

**Comment by weinig** [comment]
> @weinig did you accept the invite?

I did (I think anyway).

**Comment by foolip** [comment]
@weinig, I can confirm you're now in the reviewers team. You can try out your powers by approving and merging this PR :)

**Review by weinig — APPROVED** [review]

**Pull request merged**
