### PR TITLE
[html] Correct test resources

### PR DESCRIPTION
**Pull request by jugglinmike**
The modified resources signal correct execution by defining a global
binding. Prior to this commit, they attempted to do this by assigning to
an unresolvable reference. Because that produces a ReferenceError in
strict mode and because conforming implementations are expected to
interpret module code in strict mode, these tests could not pass.

Update the resources to define the binding using a pattern that is not
disallowed by strict mode (i.e. assignment to a property of the global
object).

This is in service of https://github.com/web-platform-tests/rfcs/pull/28

### CODE REVIEW

**Comment by annevk** [comment]
Which tests could not pass? Did all implementations fail them appropriately?

**Comment by jugglinmike** [comment]
@annevk [`html/semantics/scripting-1/the-script-element/module/charset-02.html`](https://github.com/web-platform-tests/wpt/blob/66a2fe2ae02b32e910ff091904653e62ec0c9060/html/semantics/scripting-1/the-script-element/module/charset-02.html) is the only test that references these files.

    $ git grep bom-utf-
    html/semantics/scripting-1/the-script-element/module/charset-02.html:<script type="module" src="../serve-with-content-type.py?fn=resources/bom-utf-8.js&ct=text/javascript"></script>
    html/semantics/scripting-1/the-script-element/module/charset-02.html:<script type="module" src="../serve-with-content-type.py?fn=resources/bom-utf-16be.js&ct=text/javascript"></script>
    html/semantics/scripting-1/the-script-element/module/charset-02.html:<script type="module" src="../serve-with-content-type.py?fn=resources/bom-utf-16le.js&ct=text/javascript"></script>

Today, all implementations incorrectly interpret the results of this test. Specifically, [they report it as a passing single-page test](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/module/charset-02.html?run_id=320840002&run_id=343890001&run_id=308810002&run_id=343870007). It's a little confusing for me to claim that they can't pass--sorry about that.

Anyway, this is due to the early error from these modules. The error doesn't cause a test failure because the test is configured with the `allow_uncaught_exception` option, and that is why the subtests are ignored.

**Comment by annevk** [comment]
Wouldn't there continue to be an error of sorts as the UTF-16 tests cannot be decoded as UTF-8? And wouldn't that continue to affect the subtests? I feel like I'm missing something here.

cc @hiroshige-g

**Comment by jugglinmike** [comment]
It depends on if/how the UA reports the failure to decode.

If it silently continues to parse and execute scripts, then testharness.js will wait for the subtests to be defined, and they will pass/fail as intended.

If it produces a runtime exception, then testharness.js will finish early, without defining any subtests. Today, the test will continue to be incorrectly reported as a passing single-page test. When we disable the implicit opt-in, it will instead be reported as a harness error. That's slightly better, but it's still inaccurate.

You may want to restructure this test to avoid that (for example, by defining it as three separate single-page tests). The assignment to an unresolvable reference will need to be removed in any event.

**Comment by jugglinmike** [comment]
@annevk Is there anything more I can do to see this merged?

**Comment by annevk** [comment]
So I checked this out and ran the affected test (`html/semantics/scripting-1/the-script-element/module/charset-02.html`) and this change doesn't seem to change much. It still only finds one test.

**Comment by jugglinmike** [comment]
In short: I rebased this on the latest revision of `master` to demonstrate its effect following merge. [The prior version of this branch is available here.](https://github.com/web-platform-tests/wpt/compare/master...bocoup:not-single-test-html-orig)

Explanation:

We've since changed the behavior of `allow_uncaught_exception` (see gh-19612). Tests that enable `allow_uncaught_exceptions` no longer immediately transition to COMPLETE when an uncaught exception occurs.

The impact on this test is that it is no longer interpreted as a single-page test. In `master` today, conforming engines:

- fail the first subtest (because the unintended early error blocks the script that is expected to execute successfully)
- pass the second and third subtests (though non-conforming engines may also pass spuriously if they incorrectly tolerate the BOM but correctly observe the early error)

With this patch applied, conforming engines pass all three subtests, and the risk of spurious passing is reduced.

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Thanks! Filed https://bugs.webkit.org/show_bug.cgi?id=203481 on Safari.

**Comment by jugglinmike** [comment]
Great!

**Pull request merged**
