### PR TITLE
Add RTCPeerConnectionIceErrorEvent IDL test

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5691)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225854141)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225854143)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 85f6e8f26b8d77661ad48580914cd8ddaf1719c6
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5691/webrtc/RTCPeerConnectionIceErrorEvent-idl.html">/webrtc/RTCPeerConnectionIceErrorEvent-idl.html</a></summary>


|                    Subtest                    | Results |                             Messages                            |
|-----------------------------------------------|---------|-----------------------------------------------------------------|
|                                               | OK      |                                                                 |
| `IDL check of RTCPeerConnectionIceErrorEvent` | FAIL    | `ReferenceError: RTCPeerConnectionIceErrorEvent is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225854149)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 85f6e8f26b8d77661ad48580914cd8ddaf1719c6

**Comment by agouaillard** [comment]
see #5693

**Pull request closed without merging**
