### PR TITLE
Added 4 background-position tests with min() max() functions with %tages

### PR DESCRIPTION
**Pull request by TalbotG**
… %tages

background-position-calc-minmax-001.html
background-position-calc-minmax-002.html
background-position-calc-minmax-003.html
background-position-calc-minmax-004.html
support/pattern-rg-rr-200x200.png
support/pattern-rr-rg-200x200.png
support/pattern-rr-gr-200x200.png
support/pattern-gr-rr-200x200.png
reference/ref-filled-green-100px-square.xht

Those tests spun from [Issue 4227](https://github.com/w3c/csswg-drafts/issues/4227)
and are related to [Bug 1689244]( https://bugzilla.mozilla.org/show_bug.cgi?id=1689244)

At my website, the tests are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-position-calc-minmax-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-position-calc-minmax-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-position-calc-minmax-003.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-position-calc-minmax-004.html

### CODE REVIEW

**Comment by TalbotG** [comment]
Mozilla bug report:
[Bug 1689244: Don't eagerly resolve min() expressions that have a percent value (at least not if the percent value could be resolved against a negative percent basis)](https://bugzilla.mozilla.org/show_bug.cgi?id=1689244)

**Comment by fantasai** [comment]
@TalbotG The tests seem correct, but, why do we need four of them? Shouldn't one be enough?

**Comment by TalbotG** [comment]
Tomorrow, I will merge all 4 tests into 1 test but it will not have as much comments, explanations and ascii layout as those 4 tests. It may have only minimal comments and explanations.

**Comment by TalbotG** [comment]
I stumbled on this test on my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/background-position-calc-minmax-005.html

So, I have already done such meta-test.

**Review by fantasai — APPROVED** [review]

**Pull request merged**
