### PR TITLE
Add test for capture EventListenerOption

### PR DESCRIPTION
**Pull request by RByers**
Based on [the blink tests for this feature](https://codereview.chromium.org/1412263002) written by @dtapuska

### CODE REVIEW

**Comment by RByers** [comment]
@Ms2ger can you please take a look?  These all pass on Chrome 49+.  I've verified that they fail in Firefox 46, except for the "capture boolean" test which passes as expected.  I haven't tested it on other browsers yet.

If this approach seems good then I'll upload a 2nd test for the `passive` option.

/cc @smaug---- who was waiting for us to land this to use it in Gecko.

**Comment by smaug----** [comment]
@bakulf did you land the patch to mozilla-inbound already? Want to test this. Though, I guess we'll get this stuff to our tree anyhow soon.

**Comment by RByers** [comment]
@smaug----, @bakulf if @Ms2ger is too busy to review, do one of you guys want to (though we'll still need someone with push access)?

**Comment by jgraham** [comment]
If this was reviewed upstream we can just merge it, per policy.

**Comment by dtapuska** [comment]
lgtm

**Pull request merged**
