### PR TITLE
Add more tests for data: URLs with space in body

### PR DESCRIPTION
**Pull request by foolip**
This is to bring attention to the surprising difference between
application/xml, application/javascript and text/javascript. In Chrome
and Firefox, only the application/javascript case fails.

### CODE REVIEW

**Review by annevk — APPROVED** [review]
@domenic should probably r+ too.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24947)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346824582)

**Review by domenic — APPROVED** [review]
All tests pass with jsdom/data-urls, implying they most likely match the spec.

Maybe wroth adding a comment as to why we're testing these variations which should theoretically be redundant.

**Comment by foolip** [comment]
Can't add comments in JSON, or did you have a trick in mind?

**Comment by domenic** [comment]
Hmm, usually in these data files we do a thing where a line that is just a string (instead of an object/array or whatever) is skipped by the processing code. But I guess I don't see that here. Oh well, might as well merge as-is.

**Comment by foolip** [comment]
Do you have an example of that? I was thinking of using https://github.com/json5/json5, but dependencies that we have to keep updating are annoying.

**Comment by domenic** [comment]
https://github.com/w3c/web-platform-tests/blob/3678c44dfe811f93a796285e9531ee34d7d15682/url/urltestdata.json#L2 plus https://github.com/w3c/web-platform-tests/blob/3678c44dfe811f93a796285e9531ee34d7d15682/url/a-element.js#L28

**Comment by foolip** [comment]
I see, I can try to do the same here if you like.

**Comment by domenic** [comment]
Seems nice, but I don't insist on blocking the review :)

**Comment by foolip** [comment]
Oh, and instead I just left this sitting. Retracting my promise, I'll just merge as is.

**Pull request merged**
