### PR TITLE
Add interfaces/custom-state-pseudo-class.idl and test

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Closes https://github.com/web-platform-tests/wpt/pull/24204

### CODE REVIEW

**Comment by foolip** [comment]
Per https://wpt.fyi/results/custom-state-pseudo-class/idlharness.window.html?sha=e345bf321a&label=pr_head no browser passes the important subtest. Is there implementer interest for this?

**Comment by stephenmcgruer** [comment]
> Is there implementer interest for this?

@tkent-google @domenic  - do you happen to know?

**Comment by tkent-google** [comment]
> > Is there implementer interest for this?
> 
> @tkent-google @domenic - do you happen to know?

Chrome has its implementation behind the experimental flag.
I think the feature is a part of Custom Elements, so I created `custom-elements/state.tentative/` in WPT some months ago.

**Comment by stephenmcgruer** [comment]
> Chrome has its implementation behind the experimental flag.
> I think the feature is a part of Custom Elements, so I created custom-elements/state.tentative/ in WPT some months ago.

Interesting, this appears to be the case: [idl file](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/html/custom/element_internals.idl;l=29;drc=3a592dbe9403c25dbde9f70b8ec39c22143b8f87?originalUrl=https:%2F%2Fcs.chromium.org%2F), and the [CustomStatePseudoClass flag](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=588;drc=dd0e3e67a3dc240efd2eab19d6496de0319b6118?originalUrl=https:%2F%2Fcs.chromium.org%2F) is marked as 'experimental' (so should be enabled with `--enable-experimental-web-platform-features`, which we run with).


Oh, I think we're misreading the error here @foolip:

`FAIL message: assert_equals: setter must be function for PutForwards, Replaceable, or non-readonly attributes expected "function" but got "undefined"`

This looks like idlharness is looking for a setter function, but `states` is marked `readonly` in the idl. Either having `PutForwards` and `readonly` is a contradiction, or this is a bug in idlharness...

**Comment by foolip** [comment]
Aha, so having this test would be a good idea then. It does still seem worth finding out why it's failing before landing, though.

**Review by foolip — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
cc @domenic as my go-to WebIDL smart person. Do you know what the correct behavior is if a spec has `readonly` and `PutForwards` on something - should a setter function be defined or not? (See the comment above - https://github.com/web-platform-tests/wpt/pull/24209#issuecomment-649575369)

**Comment by domenic** [comment]
`[PutForwards]` can _only_ be used in combination with `readonly`. And yes, it generates a setter, so the setter should be defined. (That's why it can only be used with `readonly`; since it generates a setter, we can't let spec authors specify their own setter, as that would conflict with the generated one.)

**Comment by stephenmcgruer** [comment]
Thanks Domenic - looks like this is an actual Chrome bug then, and we should merge this :)

**Pull request merged**
