### PR TITLE
Update Safari Technology Preview to 105

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 105, 15610.1.10)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1718&view=logs

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I should really write this down somewhere, but reminder of the process for consuming a new STP release:

1. Pull the PR down:
```
git fetch origin refs/pull/23218/head
git checkout -b autofoolip/safari-technology-preview-105 FETCH_HEAD
```
2. Push it to the trigger branch:
```
git push --force-with-lease origin HEAD:triggers/safari_preview
```
3. Once it finishes, go fish the right run_ids out of wpt.fyi for the new run as well as the closest parent that had a run (so lots of digging around in `https://wpt.fyi/api?sha=...`), and grab a diff view URL
4. Check the diff for any very suspicious changes. Pay close attention to `webdriver/`.
5. Post a summary of results to the PR.
6. If no suspicious findings, merge it.

As the assignee (sorry, short straw!), can you try this out tomorrow @LukeZielinski and maybe we can then document this somewhere? (And perhaps link to it in autofoolip's commit description.)

**Comment by Hexcles** [comment]
> Once it finishes, go fish the right run_ids out of wpt.fyi for the new run as well as the closest parent that had a run (so lots of digging around in https://wpt.fyi/api?sha=...), and grab a diff view URL

You should be able to find the runs on https://wpt.fyi/runs?product=safari-105%20preview . However, this doesn't seem to work with older versions; I've filed https://github.com/web-platform-tests/wpt.fyi/issues/1913 .

**Comment by foolip** [comment]
I've pushed https://github.com/foolip/safari-technology-preview-updater/commit/a72bc5368bec1374d213c8e4bd0e3d7c38da173e so that these PRs will be created on epochs/three_hourly going forward, so that there aren't any other changes getting mixed into the comparison.

It would be pretty easy to have the bot push to a branch directly in this repo instead, and we could also add a trigger for that branch.

**Comment by foolip** [comment]
I'm anxious to see the results, so I've triggered a full run in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=46831&view=results

**Comment by foolip** [comment]
Oh no, one of the jobs failed with "We stopped hearing from agent Azure Pipelines 6. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610"

I haven't seen this in a while, but also haven't been monitoring. @LukeZielinski are we now monitoring runs, so that we could see how often they fail on master and check if this failure is already occurring? It's not unlikely that trying again would fix the problem, but if it hasn't happened before it might be a new "flake" of sorts.

**Comment by LukeZielinski** [comment]
I'll run through Stephen's instructions now, so will retry the run anyway.

As for monitoring, we're not monitoring master runs to that granularity. All we can see at the moment is the history of the "number of recent [stable|experimental] runs" value, which doesn't give insight into which runs failed, and for what reason.

**Comment by stephenmcgruer** [comment]
Not sure if Luke did the thing, but I see a result for STP 105. https://wpt.fyi/results/?run_id=483790002&run_id=503240003&diff seems to be the diff against the previous commit.

**Comment by foolip** [comment]
What I've done in the past to see if a problem is systemic is to look through recent failures in https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=9077 and see if I can easily find an instance of the same problem. (I haven't done so, just pasting the link.)

**Comment by LukeZielinski** [comment]
Thanks @foolip - I opened your link and clicked through the last 10 red "X"es I saw, and 6 of them were this "stopped hearing from agent" error, but they were only for Edge - STP never showed this problem before. So systemic, or not?

**Comment by LukeZielinski** [comment]
As for diffs, I believe this is my run compared to the latest master run: https://wpt.fyi/results/?diff&filter=ADC&run_id=504820002&run_id=481730002

Re: Stephen's link, that looks like the results from Philip's earlier trigger branch run but the diffs seem pretty close to mine.

**Comment by LukeZielinski** [comment]
General impression of the diff is it seems mostly neutral, maybe slightly positive. webdriver/ ([diff link](https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&run_id=504820002&run_id=481730002)) seems to be slightly negative but only 15 tests changed state.

So seems ok to merge, but first time looking at this so no frame of reference. @foolip wdyt?

**Review by stephenmcgruer — APPROVED** [review]
Yeah, the errors in `webdriver/` from safaridriver there seem consistent with the flake we tend to see. LGTM to merge.

**Pull request merged**
