### PR TITLE
Remove Travis stability checks (Chrome Dev + Firefox Nightly)

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt/issues/7660.

### CODE REVIEW

**Comment by foolip** [comment]
I'm sending this PR now because these stability checks create seemingly endless trouble, just today on a bunch of Chromium export PRs and also on https://github.com/web-platform-tests/wpt/pull/13951. Some of the problems it catches are real, but enough are just timeouts and the like that I find myself distrusting the checks and not wanting to ask anyone else to look into failures either.

Disabling the checks will make it harder to verify that the Taskcluster equivalent is working, and at this point that is the main value of these checks. Perhaps we're at a point where we can flip things around to make the Taskcluster checks blocking and keep running Travis in a non-blocking way for a while to verify?

**Comment by jgraham** [comment]
We need to make the TC checks actually fail when there's a problem.

**Comment by jugglinmike** [comment]
[Here is some more analysis](https://github.com/web-platform-tests/wpt/issues/13194#issuecomment-438500438)

**Comment by sideshowbarker** [comment]
I’m not sure what this PR is waiting on, but short of merging this, is there any reason not to go ahead and update .travis.yml to move the stability checks to being allow_failures cases?

**Comment by foolip** [comment]
Sent https://github.com/web-platform-tests/wpt/pull/14096 instead.

**Comment by foolip** [comment]
@jugglinmike, can any information be extracted by comparing the results in the period where this was an allowed failure?

I've seen way more PRs blocked on flakiness lately, so I strongly suspect the new setup is just better at finding flakiness. If nobody suspects otherwise I think it's fine to not spend much time looking for cases where Travis failed but Taskcluster passed.

**Review by gsnedders — APPROVED** [review]
Though we should probably wait for more feedback than just from me. 🙂

**Review by jgraham — APPROVED** [review]

**Pull request merged**
