### PR TITLE
Update the webauthn IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-05 23:47:06
Finished: 2018-03-05 23:53:13


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>build_css</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25311)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349450502)

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Before merging, can you check if the test still works?

**Review by jcjones — APPROVED** [review]
Test changes look good. And thanks for taking a stab at fixing the `partial dictionary` test issue!

**Comment by lukebjerring** [comment]
Ran locally with https://github.com/w3c/web-platform-tests/pull/10159, and we get 51 subtests (of which 33 fail), so looks like that fix will help point out issues!

**Pull request merged**
