### PR TITLE
auto-install Ahem font with flag

### PR DESCRIPTION
**Pull request by bobholt**
Not quite sure where the install/remove stuff should be invoked. Put it here because it bookends the test-run and can keep track of the same instance (so whether or not it installed itself).

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7227)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-09-01 17:22:31
Finished: 2017-09-01 17:40:17





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18103)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/270916921)

**Comment by jgraham** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/setup.py, line 59 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTavwAz1nZ3Uh3MGw:-KsyTavxRt4rdqW6UNTn:b3oq2i8) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/setup.py#L59)):*
> ```Python
>                                   "browsers/sauce_setup/*",
>                                   "prefs/*",
>                                   "AHEM____.TTF"]},
> ```

Can't we just use the copy in web-paltform-tests/fonts rather than adding an N+1th copy? 

---

*[tools/wptrunner/wptrunner/ahem.py, line 10 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTzYuR5b8BEc0up_c:-KsyTzYvad0fw7mzsi6-:b-90g5qo) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L10)):*
> ```Python
> 
> 
> class Ahem(object):
> ```

Can we make this more generic so it's 

```
class FontInstaller(object):
   def __init__(self, **fonts):
```
Where the arguments are `name=<path>` e.g. `ahem=os.path.join(tests_root, "fonts/Ahem.ttf")`

---

*[tools/wptrunner/wptrunner/ahem.py, line 16 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUYJE5yqcy5rJ5GfO:-KsyUYJF9ogfFVSzf15H:b1qfyiu) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L16)):*
> ```Python
>         self.installed_ahem = False
> 
>     def install(self):
> ```

Seems like this should be a context manager and `__enter__()`

---

*[tools/wptrunner/wptrunner/ahem.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyX-RNq8qr0WJb3euw:-KsyX-RNq8qr0WJb3eux:b-t7gsqb) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L18)):*
> ```Python
>     def install(self):
>         if SYSTEM == 'Linux':
>             from shutil import copy2
> ```

Let's just put these imports at the  top level even thought they aren't always used.

---

*[tools/wptrunner/wptrunner/ahem.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUjBypA89nJFUEGj4:-KsyUjBypA89nJFUEGj5:byffqfl) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L21)):*
> ```Python
>             from subprocess import call
> 
>             self.font_dir = os.path.join(os.path.expanduser('~'),
> ```

So… I don't know if this directory is always right and certainly it seems to be configurable. But I can't figure out how to query the supported paths, so I guess this is fine for now. DO we care about systems without fontconfig? They will fail in the call below.

---

*[tools/wptrunner/wptrunner/ahem.py, line 30 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyWvZtNIdcmf2NsLcC:-KsyWvZuqA3JKnosaUV6:b-eyaxlg) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L30)):*
> ```Python
>                 copy2(AHEM_PATH, self.font_dir)
>                 self.installed_ahem = True
>             return not call('fc-cache')
> ```

It seems like we basically ignore failure here. 

---

*[tools/wptrunner/wptrunner/ahem.py, line 31 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXBssOT20C4Z90Qxw:-KsyXBssOT20C4Z90Qxx:bp1lygj) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L31)):*
> ```Python
>                 self.installed_ahem = True
>             return not call('fc-cache')
>         if SYSTEM == 'Darwin':
> ```

Can we make each case a separate method rather than having a long chain of ifs?

---

*[tools/wptrunner/wptrunner/ahem.py, line 35 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXOgVeWxcCfhuANCz:-KsyXOgVeWxcCfhuAND-:b95hmms) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L35)):*
> ```Python
> 
>             self.font_dir = os.path.join(os.path.expanduser('~'),
>                                          'Library/Fonts')
> ```

What if that path doesn't exist?

---

*[tools/wptrunner/wptrunner/ahem.py, line 52 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXw0qtEo2UFddjz6a:-KsyXw0qtEo2UFddjz6b:brmrp0j) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L52)):*
> ```Python
>         return False
> 
>     def remove(self):
> ```

__exit__

---

*[tools/wptrunner/wptrunner/ahem.py, line 56 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXtyVueSQ_YNnNxme:-KsyXtyVueSQ_YNnNxmf:btulrmy) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L56)):*
> ```Python
>             return False
> 
>         if SYSTEM == 'Linux':
> ```

More methods, here. Or a subclass per platform.

---

*[tools/wptrunner/wptrunner/wptrunner.py, line 134 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTrp3SJmHkvr01vOF:-KsyTrp3SJmHkvr01vOG:b-71fk07) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/wptrunner.py#L134)):*
> ```Python
>     ahem = Ahem()
>     with wptlogging.CaptureIO(logger, not kwargs["no_capture_stdio"]):
>         if kwargs["install_fonts"]:
> ```

I feel like this should be part of the environment setup/teardown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Comment by gsnedders** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/wptrunner/ahem.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUjBypA89nJFUEGj4:-KtCrqtE9M2Z-LQQXEsB:bfighmo) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L21)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

So… I don't know if this directory is always right and certainly it seems to be configurable. But I can't figure out how to query the supported paths, so I guess this is fine for now. DO we care about systems without fontconfig? They will fail in the call below.
</blockquote></details>

Pretty sure there's no other way to test this than by reading all fc config files, though there is a strong assumption that `/etc/fonts/fonts.conf` won't be changed except by upstream virtually everywhere..

The default seems to be `$XDG_DATA_HOME/fonts` or `$HOME/.local/share/fonts` if `$XDG_DATA_HOME` isn't set or is empty, so we should probably do that.

---

*[tools/wptrunner/wptrunner/ahem.py, line 59 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtCsxgAvLK3aEXC3R-A:-KtCsxgBKEMCRp5FZGDL:b-sjhfdj) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L59)):*
> ```Python
>             from subprocess import call
> 
>             os.remove('%s/%s' % (self.font_dir, AHEM_NAME))
> ```

Do we not want to delete any folders we created?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Comment by bobholt** [comment]
Addressed all comments in this commit. Running through testing on all of my machines again.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/setup.py, line 59 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTavwAz1nZ3Uh3MGw:-KtMTC3tKOivDt9Iwvy9:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/setup.py#L59)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Can't we just use the copy in web-paltform-tests/fonts rather than adding an N+1th copy? 
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 10 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTzYuR5b8BEc0up_c:-KtM4GnCGzUpAJmAj4Y4:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L10)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Can we make this more generic so it's 

```
class FontInstaller(object):
   def __init__(self, **fonts):
```
Where the arguments are `name=<path>` e.g. `ahem=os.path.join(tests_root, "fonts/Ahem.ttf")`
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 16 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUYJE5yqcy5rJ5GfO:-KtM3wq-HmEf86ylWJ2Z:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L16)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Seems like this should be a context manager and `__enter__()`
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyX-RNq8qr0WJb3euw:-KtM3xcnbyksDaJid988:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L18)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Let's just put these imports at the  top level even thought they aren't always used.
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUjBypA89nJFUEGj4:-KtRLInSqJOXqftTDm6E:b-iasxuf) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L21)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Pretty sure there's no other way to test this than by reading all fc config files, though there is a strong assumption that `/etc/fonts/fonts.conf` won't be changed except by upstream virtually everywhere..

The default seems to be `$XDG_DATA_HOME/fonts` or `$HOME/.local/share/fonts` if `$XDG_DATA_HOME` isn't set or is empty, so we should probably do that.
</blockquote></details>

`$HOME/.fonts` appears to be more universal (applying at least to Ubuntu and Fedora systems, if not more), so I'll switch to that. I'll catch the `OSError` if `fc-cache`doesn't exist and return `False` on being able to install the font.

---

*[tools/wptrunner/wptrunner/ahem.py, line 30 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyWvZtNIdcmf2NsLcC:-KtRLqm6ssOSsPmeWRVO:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L30)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

It seems like we basically ignore failure here. 
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 31 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXBssOT20C4Z90Qxw:-KtRQHLLelPfg6M9cwL7:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L31)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Can we make each case a separate method rather than having a long chain of ifs?
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 35 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXOgVeWxcCfhuANCz:-KtRRh7NWC0Zmx2DArJr:b-9nnbb4) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L35)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

What if that path doesn't exist?
</blockquote></details>

I would be very surprised, but I'll add in the `os.makedirs` to be sure.

---

*[tools/wptrunner/wptrunner/ahem.py, line 52 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXw0qtEo2UFddjz6a:-KtRS7I69NkYepMbU4vS:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L52)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

__exit__
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 56 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyXtyVueSQ_YNnNxme:-KtRS849hLGpbiuFgUAl:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L56)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

More methods, here. Or a subclass per platform.
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/ahem.py, line 59 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtCsxgAvLK3aEXC3R-A:-KtRTYNNJoFqkta8Dx7M:b-cnzvba) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L59)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Do we not want to delete any folders we created?
</blockquote></details>

I'll add a flag for if we create a directory and remove the tail if we did. At this point that would be `~/.fonts` for Linux and `~/Library/Fonts` for OSX. I could track each level of directory creation and remove `~/Library` if we had to create that too. I'm comfortable assuming it should already exist, but are you?

---

*[tools/wptrunner/wptrunner/wptrunner.py, line 134 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyTrp3SJmHkvr01vOF:-KtRU58DwLayOovfd0pJ:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/wptrunner.py#L134)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I feel like this should be part of the environment setup/teardown.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-:-KtRU8HeNi4NncHqaDr_:b-qm2mwi)*

**Comment by jgraham** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[tools/wptrunner/setup.py, line 59 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtR_rNffhJiojZb9y5j:-KtR_rNffhJiojZb9y5k:bb2vc66) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/setup.py#L59)):*
> ```Python
>                                   "browsers/sauce_setup/*",
>                                   "prefs/*",
>                                   "AHEM____.TTF"]},
> ```

This can/should be deleted and the file removed, right?

---

*[tools/wptrunner/wptrunner/font.py, line 14 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtRZffOok39N6dopkZD:-KtRZffOok39N6dopkZE:b-e0o0fx) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/wptrunner/font.py#L14)):*
> ```Python
> 
> class FontInstaller(object):
> ```

Remove this blank line.

---

*[tools/wptrunner/wptrunner/wptrunner.py, line 180 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtR_ak8z_bYQHF-bkr6:-KtR_ak8z_bYQHF-bkr7:b-tsxsc5) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/wptrunner/wptrunner.py#L180)):*
> ```Python
>                                  kwargs["pause_after_test"],
>                                  kwargs["debug_info"],
>                                  kwargs["install_fonts"],
> ```

This seems potentially wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tools/wptrunner/wptrunner/font.py, line 14 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtRZffOok39N6dopkZD:-KtRszxc_EDTbRfgpl9B:b-r8hq25) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/wptrunner/font.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Remove this blank line.
</blockquote></details>

Why is pycodestyle not catching this?

---

*[tools/wptrunner/wptrunner/ahem.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KsyUjBypA89nJFUEGj4:-KtRt59VqzfUUHweDSRn:b-o4374a) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L21)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

`$HOME/.fonts` appears to be more universal (applying at least to Ubuntu and Fedora systems, if not more), so I'll switch to that. I'll catch the `OSError` if `fc-cache`doesn't exist and return `False` on being able to install the font.
</blockquote></details>

`$HOME/.fonts` is [deprecated](https://bugs.freedesktop.org/show_bug.cgi?id=20411) ([commit](https://cgit.freedesktop.org/fontconfig/commit/fonts.conf.in?id=8c255fb185d5651b57380b0a9443001e8051b29d)) though., and raises a warning. If they do remove it in some future release, we need to cope with this.

Could try posting on their mailing list or something and ask how to check which path to use (whether you just need to parse the config file or whatever) or whether version-sniffing is as good as anything…

---

*[tools/wptrunner/wptrunner/ahem.py, line 59 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtCsxgAvLK3aEXC3R-A:-KtRuhPmsfgC7Qw9wNiR:b-j16vea) ([raw file](https://github.com/w3c/web-platform-tests/blob/ea9293a535a6180f5ccc5d3e4fbce587d7fd258d/tools/wptrunner/wptrunner/ahem.py#L59)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

I'll add a flag for if we create a directory and remove the tail if we did. At this point that would be `~/.fonts` for Linux and `~/Library/Fonts` for OSX. I could track each level of directory creation and remove `~/Library` if we had to create that too. I'm comfortable assuming it should already exist, but are you?
</blockquote></details>

We can probably rely on `~/Library`, at least. (I think hypothetically you could delete it, but it'll be recreated at login time and probably by other things too. Not that I've tested that. :))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Comment by bobholt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tools/wptrunner/setup.py, line 59 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtR_rNffhJiojZb9y5j:-KtWEVDMpkblWQxncMrV:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/setup.py#L59)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

This can/should be deleted and the file removed, right?
</blockquote></details>

Done.

---

*[tools/wptrunner/wptrunner/font.py, line 14 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtRZffOok39N6dopkZD:-KtWEsAddUZABFn9COJS:bcy5ezj) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/wptrunner/font.py#L14)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Why is pycodestyle not catching this?
</blockquote></details>

@gsnedders: PEP 8 says "Method definitions inside a class are surrounded by a single blank line." Removing the blank line doesn't seem to create a style error in my IDE (where I have PEP8 linting), but if there were a docstring here, it would require the blank line between the class definition and the docstring.

---

*[tools/wptrunner/wptrunner/wptrunner.py, line 180 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227#-KtR_ak8z_bYQHF-bkr6:-KtWFuOZT5AhXAH4lcxN:b-5pr23d) ([raw file](https://github.com/w3c/web-platform-tests/blob/8279cf858b4bfae8b974a73b343b1da47e0ab3d2/tools/wptrunner/wptrunner/wptrunner.py#L180)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

This seems potentially wrong?
</blockquote></details>

Ah, that's where that went.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7227)*

**Review by jgraham — APPROVED** [review]

**Review by jgraham — APPROVED** [review]

**Pull request merged**
