### PR TITLE
Rename pending_beacon/ to page-unload-beacon/

### PR DESCRIPTION
**Pull request by foolip**
This is to match the (unofficial) spec name:
https://clelland.github.io/page-unload-beacon/spec.html

### CODE REVIEW

**Comment by foolip** [comment]
@mingyc I see that you wrote these tests, should I list you as a reviewer as well?

**Review by Ms2ger — APPROVED** [review]

**Comment by Ms2ger** [comment]
You'll need to rebase over  #36069

**Comment by foolip** [comment]
Will do!

**Comment by mingyc** [comment]
Note: the spec has been moved to https://wicg.github.io/unload-beacon/

**Comment by foolip** [comment]
Alright, I'll rename again...

**Comment by foolip** [comment]
Renamed in https://github.com/web-platform-tests/wpt/pull/36430

**Pull request merged**
