### PR TITLE
[testharness.js] remove superfluous `test.done()` call

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@jugglinmike what sort of things should I watch out for when judging if this will regress anything? If it were unambiguously dead code I imagine you would've already removed it...

**Comment by jugglinmike** [comment]
> @jugglinmike what sort of things should I watch out for when judging if this will regress anything? 

We can have a high degree of confidence in this change because the relevant code is very close:

```diff
 if (tests.file_is_test) {
     var test = tests.tests[0];
     if (test.phase >= test.phases.HAS_RESULT) {
         return;
     }
     test.set_status(test.FAIL, e.message, stack);
     test.phase = test.phases.HAS_RESULT;
-    // The following function invocation is superfluous.
-    // TODO: Remove.
-    test.done();
 } else if (!tests.allow_uncaught_exception) {
     tests.status.status = tests.status.ERROR;
     tests.status.message = e.message;
     tests.status.stack = stack;
 }
 done();
```

And the definition of `done`:

```js
function done() {
    if (tests.tests.length === 0) {
        tests.set_file_is_test();
    }
    if (tests.file_is_test) {
        // file is test files never have asynchronous cleanup logic,
        // meaning the fully-synchronous `done` function can be used here.
        tests.tests[0].done();
    }
    tests.end_wait();
}
```

> If it were unambiguously dead code I imagine you would've already removed it...

I didn't remove it immediately because [I discovered it in the context of a very involved patch](https://github.com/web-platform-tests/wpt/commit/f8ff0b704c6) and wanted to avoid superfluous change. I didn't remove it following that because I simply forgot.

**Comment by foolip** [comment]
The `done` you linked is the global done, not the one that this call would invoke. (On phone now and can't check what the other one does.)

**Comment by jugglinmike** [comment]
Agreed. It's not that `test.done()` calls the global `done`. It's that the global `done` calls `tests.tests[0].done()`. Since the error handler calls the global `done` unconditionally, we can be confident that removing `tests.tests[0].done()` from the error handler will not change any behavior.

Put in drastically oversimplified terms, the removal looks like this:

```diff
 function handle_error() {
-  tests.tests[0].done();
   done();
 }
 
 function done() {
   tests.tests[0].done();
 }
```

**Review by jugglinmike — APPROVED** [review]

**Comment by foolip** [comment]
Thanks Mike, with that I feel I need not put this through a full CI run.

**Pull request merged**
