### PR TITLE
Add a couple more test cases to urltestdata.txt

### PR DESCRIPTION
**Pull request by frewsxcv**
From https://github.com/servo/rust-url/pull/108

### CODE REVIEW

**Comment by frewsxcv** [comment]
Dont merge this yet, I actually have a couple more to add

**Comment by frewsxcv** [comment]
Okay, should be ready to go

**Comment by sideshowbarker** [comment]
For future reference, please don't squash/rebase on review branches (for one reason, because the external "critic" code-review system we use isn't smart enough to deal with it as expected)

**Comment by sideshowbarker** [comment]
@annevk might want to review this (post-commit) & see https://github.com/servo/rust-url/pull/108 for the context

**Comment by annevk** [comment]
These two tests make sense to me.

**Pull request merged**
