### PR TITLE
Add tests for document scrollingElement property

### LINKED ISSUE #5473: Add tests for Document#scrollingElement.
Originally posted as https://github.com/w3c/csswg-test/issues/947 by @Ms2ger on 18 Nov 2015, 08:20 UTC:

> https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement
> 
> Blocks #942.

### PR DESCRIPTION
**Pull request by life777**
Fixes #5473

There are two files for two modes: Standards and Quirks.
Thanks in advance for your feedback.

### CODE REVIEW

**Comment by life777** [comment]
@gsnedders @plinss @AutomatedTester 
Should I change something in my PR?

**Comment by zcorpan** [comment]
@life777 there are tests for `scrollingElement` already, have you reviewed them before writing these tests? Do the new tests test things that are not already covered?

```
$ grep -lr scrollingElement css/cssom-view
css/cssom-view/scrollingElement-quirks-dynamic-002.html
css/cssom-view/scrolling-quirks-vs-nonquirks.html
css/cssom-view/scroll-behavior-subframe-window.html
css/cssom-view/position-sticky-root-scroller-with-scroll-behavior.html
css/cssom-view/HTMLBody-ScrollArea_quirksmode.html
css/cssom-view/scroll-behavior-element.html
css/cssom-view/scroll-behavior-default-css.html
css/cssom-view/scroll-behavior-subframe-root.html
css/cssom-view/support/scroll-behavior.js
css/cssom-view/scroll-behavior-main-frame-root.html
css/cssom-view/scrollingElement.html
css/cssom-view/scroll-behavior-main-frame-window.html
css/cssom-view/scrollingElement-quirks-dynamic-001.html
```

It's possible that #5473 should have been closed already; sorry about that!

**Comment by life777** [comment]
@zcorpan Yes, you are right it's there. Thanks. #5473 case can be closed.

**Comment by gsnedders** [comment]
@life777 I'm sorry that we had something (especially something labelled as somewhere to start contributing!) bogusly open thus making the PR unneeded. I hope you've at least learnt something useful from the exercise, and that you'll contribute again in future. Thanks for putting the effort in, though!

**Comment by life777** [comment]
@gsnedders no worries, It's my fault. I should check existence of such tests before start developing))Thanks a lot

**Pull request closed without merging**
