### PR TITLE
Add more test for setting rollback description

### PR DESCRIPTION
**Pull request by soareschen**
This adds test for performing rollback from stable state and also setting rollback with invalid SDP.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253479717)

# Firefox (nightly) #
Testing web-platform-tests at revision fdd5ea65e19ce9f04f597d05fd9be80707823c3e
Using browser at version BuildID 20170713100259; SourceStamp 30ea2905130e85f9e1d8d56fa3097901eec6514b
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6547/webrtc/RTCPeerConnection-setLocalDescription-rollback.html">/webrtc/RTCPeerConnection-setLocalDescription-rollback.html</a></summary>


|                                                               Subtest                                                               | Results |                                                                                Messages                                                                                |
|-------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                     | TIMEOUT |                                                                                                                                                                        |
| `setLocalDescription(rollback) from have-local-offer state should reset back to stable state`                                       | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."` |
| `setLocalDescription(rollback) from stable state should reject with InvalidStateError`                                              | PASS    |                                                                                                                                                                        |
| `setLocalDescription(rollback) after setting answer description should reject with InvalidStateError`                               | PASS    |                                                                                                                                                                        |
| `setLocalDescription(rollback) should ignore invalid sdp content and succeed`                                                       | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."` |
| `Test onsignalingstatechange event for setLocalDescription(rollback) from have-local-offer state should reset back to stable state` | TIMEOUT | `Test timed out`                                                                                                                                                       |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6547/webrtc/RTCPeerConnection-setRemoteDescription-rollback.html">/webrtc/RTCPeerConnection-setRemoteDescription-rollback.html</a></summary>


|                                                             Subtest                                                             | Results |                                Messages                               |
|---------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------|
|                                                                                                                                 | TIMEOUT |                                                                       |
| `setRemoteDescription(rollback) in have-remote-offer state should revert to stable state`                                       | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined` |
| `setRemoteDescription(rollback) from stable state should reject with InvalidStateError`                                         | PASS    |                                                                       |
| `setRemoteDescription(rollback) should ignore invalid sdp content and succeed`                                                  | PASS    |                                                                       |
| `Test onsignalingstatechange event for setRemoteDescription(rollback) in have-remote-offer state should revert to stable state` | TIMEOUT | `Test timed out`                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253479718)

# Sauce (safari) #
Testing web-platform-tests at revision fdd5ea65e19ce9f04f597d05fd9be80707823c3e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6547/webrtc/RTCPeerConnection-setLocalDescription-rollback.html">/webrtc/RTCPeerConnection-setLocalDescription-rollback.html</a></summary>


|                                                Subtest                                                | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                       | OK      |                                          |
| `setLocalDescription(rollback) from have-local-offer state should reset back to stable state`         | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription(rollback) from stable state should reject with InvalidStateError`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription(rollback) after setting answer description should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription(rollback) should ignore invalid sdp content and succeed`                         | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6547/webrtc/RTCPeerConnection-setRemoteDescription-rollback.html">/webrtc/RTCPeerConnection-setRemoteDescription-rollback.html</a></summary>


|                                          Subtest                                          | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                           | OK      |                                          |
| `setRemoteDescription(rollback) in have-remote-offer state should revert to stable state` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(rollback) from stable state should reject with InvalidStateError`   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(rollback) should ignore invalid sdp content and succeed`            | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253479724)

# Chrome (unstable) #
Testing web-platform-tests at revision fdd5ea65e19ce9f04f597d05fd9be80707823c3e
Using browser at version 61.0.3153.4 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253479725)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision fdd5ea65e19ce9f04f597d05fd9be80707823c3e

**Review by rwaldron — APPROVED** [review]

**Pull request merged**
