### PR TITLE
Test form.action reflection and form submission URLs

### PR DESCRIPTION
**Pull request by domenic**
(Edited since first posted)

This adds tests form form.action reflection and the actual URL a form is submitted to, focusing on the cases of empty-string or missing attributes. Per spec they should be the same; however, browsers generally do not implement form.action correctly, so they fail the reflection tests.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232600025)

# Firefox (nightly) #
Testing web-platform-tests at revision 2826ad9ae8d9323ead01a302015d468c1a1e08aa
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action-base-url.html">/html/semantics/forms/the-form-element/form-action-base-url.html</a></summary>


|                                                   Subtest                                                   | Results |                                        Messages                                        |
|-------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                        |
| `An action URL should be resolved relative to the document's base URL`                                      | PASS    |                                                                                        |
| `An empty-string action content attribute should cause the IDL attribute to return the document's base URL` | FAIL    | `assert_equals: expected "http://web-platform.test:8000/common/blank.html" but got ""` |
| `A missing action content attribute should cause the IDL attribute to return the empty string`              | PASS    |                                                                                        |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action.html">/html/semantics/forms/the-form-element/form-action.html</a></summary>


|                                                Subtest                                                 | Results |                                                           Messages                                                          |
|--------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------|
|                                                                                                        | OK      |                                                                                                                             |
| `An action URL should be resolved relative to the document's URL`                                      | PASS    |                                                                                                                             |
| `An empty-string action content attribute should cause the IDL attribute to return the document's URL` | FAIL    | `assert_equals: expected "http://web-platform.test:8000/html/semantics/forms/the-form-element/form-action.html" but got ""` |
| `A missing action content attribute should cause the IDL attribute to return the empty string`         | PASS    |                                                                                                                             |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232600026)

# Sauce (safari) #
Testing web-platform-tests at revision 2826ad9ae8d9323ead01a302015d468c1a1e08aa
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action-base-url.html">/html/semantics/forms/the-form-element/form-action-base-url.html</a></summary>


|                                                   Subtest                                                   | Results | Messages |
|-------------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                             | OK      |          |
| `An action URL should be resolved relative to the document's base URL`                                      | PASS    |          |
| `An empty-string action content attribute should cause the IDL attribute to return the document's base URL` | PASS    |          |
| `A missing action content attribute should cause the IDL attribute to return the empty string`              | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action.html">/html/semantics/forms/the-form-element/form-action.html</a></summary>


|                                                Subtest                                                 | Results | Messages |
|--------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                        | OK      |          |
| `An action URL should be resolved relative to the document's URL`                                      | PASS    |          |
| `An empty-string action content attribute should cause the IDL attribute to return the document's URL` | PASS    |          |
| `A missing action content attribute should cause the IDL attribute to return the empty string`         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232600027)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 2826ad9ae8d9323ead01a302015d468c1a1e08aa
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action-base-url.html">/html/semantics/forms/the-form-element/form-action-base-url.html</a></summary>


|                                                   Subtest                                                   | Results |                                                                                       Messages                                                                                      |
|-------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                                                                                                                     |
| `An action URL should be resolved relative to the document's base URL`                                      | PASS    |                                                                                                                                                                                     |
| `An empty-string action content attribute should cause the IDL attribute to return the document's base URL` | FAIL    | `assert_equals: expected "http://web-platform.test:8000/common/blank.html" but got "http://web-platform.test:8000/html/semantics/forms/the-form-element/form-action-base-url.html"` |
| `A missing action content attribute should cause the IDL attribute to return the empty string`              | PASS    |                                                                                                                                                                                     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5925/html/semantics/forms/the-form-element/form-action.html">/html/semantics/forms/the-form-element/form-action.html</a></summary>


|                                                Subtest                                                 | Results | Messages |
|--------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                        | OK      |          |
| `An action URL should be resolved relative to the document's URL`                                      | PASS    |          |
| `An empty-string action content attribute should cause the IDL attribute to return the document's URL` | PASS    |          |
| `A missing action content attribute should cause the IDL attribute to return the empty string`         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232600033)

# Chrome (unstable) #

**Review by annevk — APPROVED** [review]
Thanks!

**Comment by domenic** [comment]
Bugs:

- https://bugs.chromium.org/p/chromium/issues/detail?id=724596
- https://bugzilla.mozilla.org/show_bug.cgi?id=1366361
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12075543/
- https://bugs.webkit.org/show_bug.cgi?id=172376

**Pull request merged**
