### PR TITLE
EUC-jp encoding and decoding tests

### PR DESCRIPTION
**Pull request by r12a**
Results for these tests can be found at
https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en#eucjp

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 13:43:24
Finished: 2017-08-15 14:05:51



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17419)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264744384)

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 13:43:24
Finished: 2017-08-15 14:05:51



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17419)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264744384)

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 13:43:24
Finished: 2017-08-15 14:05:51



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17419)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264744384)

**Comment by r12a** [comment]
The new commits fix the bug mentioned at https://github.com/whatwg/encoding/issues/59. 

It also adds editorial changes added by @domenic elsewhere.

Now all tests pass for Firefox 57. See updated results for FF Nightly at https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en#eucjp (other results to be updated soon).  Hopefully it's now good to go.

**Pull request closed without merging**
