### PR TITLE
Replace old CSS2 color parsing tests with JS

### PR DESCRIPTION
**Pull request by gsnedders**
There are over a thousand near identical tests testing parsing of `<color>` values across various properties; these cumulatively end up taking several minutes to run which is almost certainly not worthwhile.

Instead, have a single testharness.js test that checks we get the specified value we expect for all the various combinations of property/value.

Note this does keep `*-129.xht` of each of these to maintain coverage that we do, in fact, render the specified color for each property.

This is practically an alternative to #[44728](https://github.com/web-platform-tests/wpt/pull/44728).

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
We could quibble about the details here, but I think the cost/benefit ratio strongly leans towards merging this. I certainly wouldn't want to merge the reverse change.

I'm happy to approve this now, but you might consider waiting a little while to merge in case someone disagrees.

**Comment by gsnedders** [comment]
I'm somewhat confused because the lint passed locally, but maybe I'm forgetting what it defaults to (things changed v. the index, perhaps).

**Review by zcorpan — APPROVED** [review]

**Review by svgeesus — APPROVED** [review]
Yeah someone was being paid by the word here.

**Comment by dbaron** [comment]
I'm not actually going to review the code since I'll assume at least some of the other three reviewers have done that, but I'll just say that this sounds like a good idea to me.

**Pull request merged**
