### PR TITLE
Auto-update the webrtc IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by lukebjerring** [comment]
To see the changes to the IDL itself, they're shown in the separated commit here:
https://github.com/web-platform-tests/wpt/pull/11700/commits/87b2d2a23ab0212adcd375972bf80979b67fa715

GitHub seems to not be able to aggregate the rename and updates in the full overview.

**Comment by foolip** [comment]
Filed https://github.com/tidoust/reffy-reports/issues/15 about the missing space you had to put back.

**Comment by foolip** [comment]
Some commits have gotten included on this PR by accident, I'll rebase to get rid of them.

**Review by foolip — APPROVED** [review]
Tested locally in Chrome and Firefox and compared to http://web-platform-tests.live/webrtc/interfaces.https.html.

There are much more subtests now, 494 instead of 18, and lots are failing, but skimming through the failures they mostly look the kinds of things in the WebRTC spec that haven't been implemented yet.

There are probably a few bugs left in this very complex test setup, but this is a huge improvement!

**Pull request merged**
