### PR TITLE
Split XHR's IDL into a standalone interfaces/xhr.idl

### PR DESCRIPTION
**Pull request by foolip**
This does not make any changes to the IDL, and the test results
are not (should not be) affected.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22525)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/326808009)

**Comment by foolip** [comment]
@mdittmer @lukebjerring FYI

**Review by annevk — APPROVED** [review]
Assuming before/after results are identical, go ahead.

**Comment by foolip** [comment]
> Assuming before/after results are identical, go ahead.

For the record, I tested the before/after manually in Chrome/Firefox.

**Pull request merged**
