### PR TITLE
Fix broken IDL resources in html/dom/interfaces.worker.js

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/w3c/web-platform-tests/issues/6621.

### CODE REVIEW

**Comment by foolip** [comment]
Tested locally with http://web-platform.test:8000/html/dom/interfaces.worker.html

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259412851)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259412852)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259412858)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259412860)

# Sauce (MicrosoftEdge) #

**Review by jdm — APPROVED** [review]

**Pull request merged**
