### PR TITLE
Test SVGUnitTypes changes (no longer a mixin)

### PR DESCRIPTION
**Pull request by foolip**
Tests for https://github.com/w3c/svgwg/issues/291 and
https://github.com/w3c/fxtf-drafts/issues/90

### CODE REVIEW

**Comment by foolip** [comment]
@nikosandronikos, can you review?

**Comment by nikosandronikos** [comment]
@foolip Test looks good. Looks like the Filter Effects drafts still have `SVGFilterElement implements SVGUnitTypes`. Would you be able to submit a PR on Filter Effects Level 1?

**Comment by foolip** [comment]
How do you edit that spec? I filed https://github.com/w3c/fxtf-drafts/issues/90 because it looked complicated.

**Comment by nikosandronikos** [comment]
@foolip That's fair. As long as there's an issue raised.

**Comment by foolip** [comment]
Thanks @nikosandronikos!

**Pull request merged**
