### PR TITLE
Update README for submodule changes

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5607)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5607/)

**Comment by gsnedders** [comment]
I managed to get this the other way:

```
fatal: No url found for submodule path 'resources/webidl2/test/widlproc' in .gitmodules
Failed to recurse into submodule path 'resources/webidl2'
fatal: No url found for submodule path 'tools/html5lib' in .gitmodules
Failed to recurse into submodule path 'resources'
Failed to recurse into submodule path 'tools'
```

I can't repro this any more, but I was going across that with submodules on both sides. idk.

Maybe worth noting in case anyone else hits that? Just want to rm -r them, again.

**Comment by gsnedders** [comment]
Also I'll claim you need a comma before "i.e.".

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223601141)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223601143)

# Firefox (nightly channel) #
Testing web-platform-tests at revision b32e5d590066fdf968179e2a01735fa625e14b16
Using browser at version BuildID 20170418100213; SourceStamp bb38d935d699e0529f9e0bb35578d381026415c4
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223601144)

# Chrome (unstable channel) #
Testing web-platform-tests at revision b32e5d590066fdf968179e2a01735fa625e14b16
Using browser at version 59.0.3071.9 dev
Starting 10 test iterations
No tests run.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
