### PR TITLE
Adds basic `color-contrast()` test

### PR DESCRIPTION
**Pull request by argyleink**
to help with https://github.com/web-platform-tests/interop-2022/issues/20

### CODE REVIEW

**Comment by weinig** [comment]
I have an other set of color contrast tests up for review - https://github.com/web-platform-tests/wpt/pull/31903

**Comment by svgeesus** [comment]
This test looks fine. I [checked the calculation](https://colorjs.io/notebook/?storage=https%3A%2F%2Fgist.github.com%2Fsvgeesus%2F32e6d50771a2b5fd8ffb9a92e2bb6517)

@weinig you do have tests, but for parsing while this is also testing the result gets displayed. Its good to have both.

**Review by svgeesus — APPROVED** [review]
Checked, is correct (1.29 > 1.1)

**Comment by weinig** [comment]
> This test looks fine. I [checked the calculation](https://colorjs.io/notebook/?storage=https%3A%2F%2Fgist.github.com%2Fsvgeesus%2F32e6d50771a2b5fd8ffb9a92e2bb6517)
> 
> @weinig you do have tests, but for parsing while this is also testing the result gets displayed. Its good to have both.

Sorry, I didn't mean to imply that we shouldn't also have this, it was more just meant to as a comment. The more tests the merrier.

**Pull request merged**
