### PR TITLE
[presentation-api] Update the test for getAvailability

### PR DESCRIPTION
**Pull request by tomoyukilabs**
This PR updates the test for PresentationRequest.getAvailability.

- Wait until the value of the presentation availability object is set to true, since the value is initially set to false if the object is newly created (https://github.com/w3c/presentation-api/pull/392)
- Check if a presentation availability object is newly created for new presentationUrls

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5731)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226710521)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226710523)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 5774089498178e13f98ef67161b07f5412a25d26
Using browser at version BuildID 20170427100655; SourceStamp 0b77ed3f26c5335503bc16e85b8c067382e7bb1e
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5731/presentation-api/controlling-ua/getAvailability.https.html">/presentation-api/controlling-ua/getAvailability.https.html</a></summary>


|                            Subtest                            | Results |               Messages               |
|---------------------------------------------------------------|---------|--------------------------------------|
|                                                               | OK      |                                      |
| `Getting the presentation displays availability information.` | FAIL    | `PresentationRequest is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226710529)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 5774089498178e13f98ef67161b07f5412a25d26
Using browser at version 60.0.3080.5 dev
Starting 10 test iterations

**Review by tidoust — APPROVED** [review]
LGTM

**Pull request merged**
