### PR TITLE
[docs] Deprecate some requirement flags

### LINKED ISSUE #5293: Deprecate some requirement flags
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6 by @frivoal on 09 Jan 2017, 01:19 UTC:

> The [list of requirement flags](https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#requirement-flags) looks like it lists all of the historical ones.
> 
> We should keep on documenting the old ones, so that when people run into them they know what they mean, but we should move these to a "historical" subsection, and only keep the ones we actually expect people to in the main section.
> 
> Based on previous discussions, I believe we had agreed that the following ones could be deprecated:
> * ahem: treat ahem as a requirement for the entire test suite, and stop flagging individual tests
> * animated: no need to distinguish from manual tests flagged as "interact"
> * dom: can be inferred from the test using javascript
> * image / svg: modern UAs all support this, and it can be inferred form the test itself anyway
> * userstyle: no need to distinguish from manual tests, unless we also adopt a convention for linking to the user style sheet that automated tests runners can use to pick up the test file, in which case we will also not need the flag. For instance we could require the use of something like `Prior to running this test, <a rel="user-style-sheet" href="path/to/style-sheet.css">this user style sheet </a> must be <a href="doc/to/how-to-use/user/style-sheets/">installed</a>`.
> * 32bit: historical, inconsistently used anyway
> * 96dpi: required by the specs anyway.

### PR DESCRIPTION
**Pull request by jugglinmike**
This is intended to resolve gh-5293.

@frivoal @gsnedders [in a subsequent issue](https://github.com/web-platform-tests/wpt/issues/5381), Sam listed a few more flags: history, paged, and speech. Should this patch deprecate those as well?

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by frivoal** [comment]
* `history` probably, but it might be worth checking the tests that actually use this, to see how they do so.
* `paged` I'd rather not. See https://github.com/web-platform-tests/wpt/issues/7760#issuecomment-389216902
* `speech` I don't feel qualified to say one way or another. I don't know who speech tests work, either in theory or in practice.

**Comment by gsnedders** [comment]
`paged` we can't remove till #7760 is fixed.

I think what we can deprecate in favour of `-manual` is: animated, font, history, interact (because it's literally equivalent!), speech, and userstyle. (This all those that affect the manifest except for `paged`.)

The other flags fall into four categories: those that control the old CSS build system (asis, HTMLonly, nonHTML), those that might be useful when creating implementation reports (may, should), those that might be useful to non-browser implementations (scroll), and, uh, the `invalid` flag which is useful I don't know when.

@frivoal:

> * `history` probably, but it might be worth checking the tests that actually use this, to see how they do so.

None of them do anything very complicated.

> * `speech` I don't feel qualified to say one way or another. I don't know who speech tests work, either in theory or in practice.

They don't exist in practice. No one does end-to-end testing of CSS speech in any form.

**Comment by jugglinmike** [comment]
I've moved the `history` and `speech` tokens to the new "deprecated" section. Thanks, you two!

**Review by sideshowbarker — APPROVED** [review]

**Comment by jugglinmike** [comment]
Do you folks think this is ready for `master`?

**Comment by sideshowbarker** [comment]
> Do you folks think this is ready for `master`?

LGTM

**Comment by jugglinmike** [comment]
Rebased over `master`. Original version available here:

https://github.com/web-platform-tests/wpt/compare/master...bocoup:docs-ahem-install-orig

**Pull request merged**
