### PR TITLE
Sync Mozilla tests as of 2018-06-28

### PR DESCRIPTION
**Pull request by emilio**
Sync Mozilla tests as of https://hg.mozilla.org/mozilla-central/rev/6041c030780420b6205cf2d6640513606609884c

This contains two changes:

 * One by Mihir Iyer from [bug 1398483](https://bugzil.la/1398483), reviewed by
   @dholbert, adding flexbox column-{row,gap} reftests.

 * One by myself from [bug 1464782](https://bugzil.la/1464782), replacing the
   usage of offset-* logical properties by the standard name inset-*, reviewed
   by @upsuper.

### CODE REVIEW

**Comment by emilio** [comment]
r? @dbaron

I need this to be able to turn off the offset- properties on mozilla-central, so I figured I'd learn to do the sync instead of bothering you :P

**Review by dbaron — APPROVED** [review]

**Comment by dbaron** [comment]
This looks fine, but:
* I'm not sure why the bot didn't auto-approve; it does so for me.
* I'm not sure what's up with the lint failure (i.e., I don't know why anything in this PR would trigger it):
```
ERROR:lint:css/vendor-imports/mozilla: Directory is missing META.yml file. (MISSING-META-YML)
```

**Comment by Ms2ger** [comment]
> I'm not sure why the bot didn't auto-approve; it does so for me.

To prevent abuse, only particular people (i.e., you) get their PRs auto-approved.

> I'm not sure what's up with the lint failure (i.e., I don't know why anything in this PR would trigger it):

https://github.com/web-platform-tests/wpt/issues/11722 ; @emilio, please rebase

**Comment by emilio** [comment]
Done, thanks @Ms2ger

**Pull request merged**
