### PR TITLE
[wake-lock] Add tests for AbortSignal

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
Close it since `AbortSignal` has been replaced with `abort()` in latest spec(https://github.com/w3c/wake-lock/pull/178).

**Comment by Honry** [comment]
Reopen, as `Aboriginal` is added back at https://github.com/w3c/wake-lock/pull/183.

**Comment by Honry** [comment]
@rakuco, @kenchris, could you PTAL?

**Review by rakuco — APPROVED** [review]
lgtm. The wpt.fyi failures are all caused by either lack of an implementation or, in Chrome's case, an older implementation being present in the latest Dev release.

**Pull request merged**
