### PR TITLE
Submit Opera's before/afterscriptexecute events tests.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by Ms2ger** [comment]
This is probably wontfix due to https://github.com/whatwg/html/pull/1103

**Comment by gsnedders** [comment]
Presume you closed it because of whatwg/html#1103?

**Comment by Ms2ger** [comment]
Yep, see https://github.com/w3c/web-platform-tests/pull/1647#issuecomment-256591722

**Comment by gsnedders** [comment]
Just wanted it noted at the bottom for clarity given that was six months ago.

**Pull request closed without merging**
