### PR TITLE
[wdspec] Adopt `wait_for_future_safe` in network tests

### PR DESCRIPTION
**Pull request by thiagowfx**
Follow-up-of: #42845

### CODE REVIEW

**Review by sadym-chromium — APPROVED** [review]
LGTM

One note: I just noticed, the `wait_for_future_safe` is always used with the future returned by `wait_for_event`. So consider extending `wait_for_event` with `timeout: int` or `with_timeout: bool` parameter.

**Comment by thiagowfx** [comment]
> One note: I just noticed, the wait_for_future_safe is always used with the future returned by wait_for_event. So consider extending wait_for_event with timeout: int or with_timeout: bool parameter.

This is reasonable. I'll consider this in a follow-up.

**Comment by thiagowfx** [comment]
> This is reasonable. I'll consider this in a follow-up.

Ah, the issue is that there's usually some other command between `wait_for_event` and `wait_for_future_safe`. A new argument for `wait_for_event` will not suffice.

**Review by whimboo — APPROVED** [review]
I think that looks fine and all the Firefox tests are still passing. Thanks.

**Comment by thiagowfx** [comment]
@DanielRyanSmith could you merge this?

**Pull request merged**
