### PR TITLE
Improve content-visibility-svg.html

### PR DESCRIPTION
**Pull request by rwlbuis**
Test more SVG idl methods that measure layout and return layout values.

### CODE REVIEW

**Comment by rwlbuis** [comment]
@josepharhar let me know if you like this or prefer a separate test.

**Comment by josepharhar** [comment]
Considering that this test is interop2023 tracked and chrome fails some of the new test cases, it would be more ideal for me if this was in a separate test file. If I knew exactly how to patch chrome to make them pass then I'd just do that now and we'd be fine, but I'm not sure. Is there a corresponding WebKit patch to make these test cases pass?

**Comment by rwlbuis** [comment]
> Considering that this test is interop2023 tracked and chrome fails some of the new test cases, it would be more ideal for me if this was in a separate test file. If I knew exactly how to patch chrome to make them pass then I'd just do that now and we'd be fine, but I'm not sure. Is there a corresponding WebKit patch to make these test cases pass?

How about the following:
- rename content-visibility-svg.html to content-visibility-svg-getbbox.html since it is specific to getBBox
- add a subtest there for getBBox on path, since in WebKit it is a different code path
- keep the rest in content-visibility-svg.html, since it is a generic test

I do have a WebKit patch for it involving lazy layout, but right now the tests pass in WebKit anyway.
Note though that these are old SVG interfaces (some are marked as such in MDN) and they may not
be well supported and there may be some subtle differences (like DOMPoint vs SVGPoint usage). But yeah chromium can be forgiven for missing some of these :)

**Comment by josepharhar** [comment]
I ran these new tests on my machine, and I found that removing the content-visibility style from the test resulted in the exact same output, so I don't think that these are really testing content-visibility as much as they are testing some SVG stuff...

I'm generally OK with anything as long as it doesn't impact chrome's interop2023 score. Adding/changing stuff in content-visibility-svg.html that chrome fails without updating the interop2023 tracking metadata will impact chrome's score, which it looks like the latest commit is doing.

**Comment by rwlbuis** [comment]
> I ran these new tests on my machine, and I found that removing the content-visibility style from the test resulted in the exact same output, so I don't think that these are really testing content-visibility as much as they are testing some SVG stuff...
> 
> I'm generally OK with anything as long as it doesn't impact chrome's interop2023 score. Adding/changing stuff in content-visibility-svg.html that chrome fails without updating the interop2023 tracking metadata will impact chrome's score, which it looks like the latest commit is doing.

Would it work to skip the new test in chromium (probably with a bug filed to fix it) and/or keep content-visibility-svg.html as-is and move the new subtests to a differently named test (probably skipping that one in chromium)?

**Comment by josepharhar** [comment]
> move the new subtests to a differently named test

That sounds perfect!

**Comment by rwlbuis** [comment]
> > move the new subtests to a differently named test
> 
> That sounds perfect!

Since I found it hard to come up with a new name, I split the tests over three files, and am leaving content-visibility-svg.html  as-is :)

**Comment by rwlbuis** [comment]
@josepharhar so, do you think you can okay this one? :)

**Review by josepharhar — APPROVED** [review]

**Pull request merged**
