### PR TITLE
Convert manual test for input events to use testdriver

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by jgraham** [comment]
@masayuki-nakano I hear you may be interested in this.

**Comment by jgraham** [comment]
Oops, no I just forgot it. Hopefully it's fixed now.

**Comment by jgraham** [comment]
@johanneswilm ping? I updated this to pass CI.

**Comment by johanneswilm** [comment]
@jgraham I'm not sure it makes sense to keep the instructions for doing manual tests now, but yes,t his looks good now.

**Review by johanneswilm — APPROVED** [review]

**Comment by jgraham** [comment]
I think there's a general feeling that it should be possible to run this kind of test by hand. But I don't recall if there's policy for it or not.

Are you able to mark as approved?

**Pull request merged**
