### PR TITLE
WorkerLocation: ensure IDNA origin is in ASCII

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/html/issues/2568.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232816485)

# Firefox (nightly) #
Testing web-platform-tests at revision 58f6b6e2ebec4e8e5c8b8f297c289ad70071bf6e
Using browser at version BuildID 20170516100213; SourceStamp 3e166b6838931b3933ca274331f9e0e115af5cc0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation-origin.sub.window.html">/workers/WorkerLocation-origin.sub.window.html</a></summary>


|                      Subtest                       | Results |                                                             Messages                                                             |
|----------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------|
|                                                    | OK      |                                                                                                                                  |
| `workerLocation.origin must use ASCII code points` | FAIL    | `assert_equals: expected "http://xn--n8j6ds53lwwkrqhv28a.web-platform.test:8000" but got "http://å¤©æ°ã®è¯ãæ¥.web-platform.test:8000"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation.htm">/workers/WorkerLocation.htm</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| ` WorkerLocation object ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash.htm">/workers/WorkerLocation_hash.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hash ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_encoding.htm">/workers/WorkerLocation_hash_encoding.htm</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| ` WorkerLocation.hash with url encoding string ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_nonexist.htm">/workers/WorkerLocation_hash_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.hash with no <fragment> component ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_host.htm">/workers/WorkerLocation_host.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: host ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hostname.htm">/workers/WorkerLocation_hostname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hostname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_href.htm">/workers/WorkerLocation_href.htm</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| ` WorkerLocation href attribute ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_pathname.htm">/workers/WorkerLocation_pathname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: pathname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_port.htm">/workers/WorkerLocation_port.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: port ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_protocol.htm">/workers/WorkerLocation_protocol.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: protocol ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search.htm">/workers/WorkerLocation_search.htm</a></summary>


|                          Subtest                           | Results | Messages |
|------------------------------------------------------------|---------|----------|
|                                                            | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: search ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_empty.htm">/workers/WorkerLocation_search_empty.htm</a></summary>


|                   Subtest                    | Results | Messages |
|----------------------------------------------|---------|----------|
|                                              | OK      |          |
| ` WorkerLocation.search with empty <query> ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_fragment.htm">/workers/WorkerLocation_search_fragment.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search with <fragment> in <query> ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_nonexist.htm">/workers/WorkerLocation_search_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search  with no <query> component ` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232816486)

# Sauce (safari) #
Testing web-platform-tests at revision 58f6b6e2ebec4e8e5c8b8f297c289ad70071bf6e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation-origin.sub.window.html">/workers/WorkerLocation-origin.sub.window.html</a></summary>


|                      Subtest                       | Results |     Messages     |
|----------------------------------------------------|---------|------------------|
|                                                    | TIMEOUT |                  |
| `workerLocation.origin must use ASCII code points` | TIMEOUT | `Test timed out` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation.htm">/workers/WorkerLocation.htm</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| ` WorkerLocation object ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash.htm">/workers/WorkerLocation_hash.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hash ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_encoding.htm">/workers/WorkerLocation_hash_encoding.htm</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| ` WorkerLocation.hash with url encoding string ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_nonexist.htm">/workers/WorkerLocation_hash_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.hash with no <fragment> component ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_host.htm">/workers/WorkerLocation_host.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: host ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hostname.htm">/workers/WorkerLocation_hostname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hostname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_href.htm">/workers/WorkerLocation_href.htm</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| ` WorkerLocation href attribute ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_pathname.htm">/workers/WorkerLocation_pathname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: pathname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_port.htm">/workers/WorkerLocation_port.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: port ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_protocol.htm">/workers/WorkerLocation_protocol.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: protocol ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search.htm">/workers/WorkerLocation_search.htm</a></summary>


|                          Subtest                           | Results | Messages |
|------------------------------------------------------------|---------|----------|
|                                                            | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: search ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_empty.htm">/workers/WorkerLocation_search_empty.htm</a></summary>


|                   Subtest                    | Results | Messages |
|----------------------------------------------|---------|----------|
|                                              | OK      |          |
| ` WorkerLocation.search with empty <query> ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_fragment.htm">/workers/WorkerLocation_search_fragment.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search with <fragment> in <query> ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_nonexist.htm">/workers/WorkerLocation_search_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search  with no <query> component ` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232816487)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 58f6b6e2ebec4e8e5c8b8f297c289ad70071bf6e
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation-origin.sub.window.html">/workers/WorkerLocation-origin.sub.window.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation.htm">/workers/WorkerLocation.htm</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| ` WorkerLocation object ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash.htm">/workers/WorkerLocation_hash.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hash ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_encoding.htm">/workers/WorkerLocation_hash_encoding.htm</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| ` WorkerLocation.hash with url encoding string ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hash_nonexist.htm">/workers/WorkerLocation_hash_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.hash with no <fragment> component ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_host.htm">/workers/WorkerLocation_host.htm</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: host ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_hostname.htm">/workers/WorkerLocation_hostname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: hostname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_href.htm">/workers/WorkerLocation_href.htm</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| ` WorkerLocation href attribute ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_pathname.htm">/workers/WorkerLocation_pathname.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: pathname ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_port.htm">/workers/WorkerLocation_port.htm</a></summary>


|                         Subtest                          | Results |                             Messages                            |
|----------------------------------------------------------|---------|-----------------------------------------------------------------|
|                                                          | OK      |                                                                 |
| ` WorkerLocation URL decomposition IDL attribute: port ` | FAIL    | `assert_equals: expected (string) "8000" but got (number) 8000` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_protocol.htm">/workers/WorkerLocation_protocol.htm</a></summary>


|                           Subtest                            | Results | Messages |
|--------------------------------------------------------------|---------|----------|
|                                                              | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: protocol ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search.htm">/workers/WorkerLocation_search.htm</a></summary>


|                          Subtest                           | Results | Messages |
|------------------------------------------------------------|---------|----------|
|                                                            | OK      |          |
| ` WorkerLocation URL decomposition IDL attribute: search ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_empty.htm">/workers/WorkerLocation_search_empty.htm</a></summary>


|                   Subtest                    | Results |                 Messages                 |
|----------------------------------------------|---------|------------------------------------------|
|                                              | OK      |                                          |
| ` WorkerLocation.search with empty <query> ` | FAIL    | `assert_equals: expected "" but got "?"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_fragment.htm">/workers/WorkerLocation_search_fragment.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search with <fragment> in <query> ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5940/workers/WorkerLocation_search_nonexist.htm">/workers/WorkerLocation_search_nonexist.htm</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| ` WorkerLocation.search  with no <query> component ` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232816493)

# Chrome (unstable) #
Testing web-platform-tests at revision 58f6b6e2ebec4e8e5c8b8f297c289ad70071bf6e

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
