### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=181404

### PR DESCRIPTION
**Pull request by youennf**
Make imported/w3c/web-platform-tests/service-workers/service-worker/fetch-canvas-tainting-cache.https.html robust to quota error

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22520)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/326753561)

**Comment by foolip** [comment]
@youennf looks like these changes were landed in https://trac.webkit.org/changeset/226651/webkit but this export still remains open. Now there are conflicts. Can you resolve somehow?

**Comment by foolip** [comment]
It's possible these changes were accidentally reverted by https://trac.webkit.org/changeset/238592/webkit, it's hard to tell.

**Comment by nt1m** [comment]
Let's close this, we can't merge it with the newer tests: https://searchfox.org/wubkat/search?q=fetch-canvas-tainting&path=&case=false&regexp=false

**Pull request closed without merging**
