### PR TITLE
[css-flexbox] delete flex-minimum-width-flex-items-007.xht

### PR DESCRIPTION
**Pull request by foolip**
It's failing in the same way in all browsers we test, with a 60x100
green rectangle, with the 100x100 red showing behind it:
https://wpt.fyi/results/css/css-flexbox/flex-minimum-width-flex-items-007.xht?run_id=711240001&run_id=697770002&run_id=737900001&run_id=715540002&run_id=705490001
https://storage.googleapis.com/wptd-screenshots/sha1:a523515765355d9b677ae16706b1832c4ef65830.png

The only difference between flex-minimum-width-flex-items-007.xht and
-008.xht is that -007.xht uses 60x60-green.png and -008.xht uses
100x100-green.png. -008.xht passes everywhere:
https://wpt.fyi/results/css/css-flexbox/flex-minimum-width-flex-items-008.xht?run_id=711240001&run_id=697770002&run_id=737900001&run_id=715540002&run_id=705490001

The assumption of the test appeared to be that the image aspect ratio
would be preserved. It seems things are not that simple, but a number
of other tests around aspect ratio were added in
https://github.com/w3c/csswg-test/pull/1028.

### CODE REVIEW

**Comment by foolip** [comment]
This screenshot of the test in Firefox DevTools might help clarify what's happening:
image

**Comment by foolip** [comment]
@mrego would you mind reviewing this? I'm really a Flexbox novice, so it's hard for me to figure out if this is properly tested by some other test.

@davidsgrogan maybe you can check this too? I see that flex-minimum-width-flex-items-009.html which you added in https://github.com/web-platform-tests/wpt/pull/19533 is a very similar test, except that it uses `min-height: 100px` instead of  `height: 100px`.

**Comment by mrego** [comment]
TBH I haven't been following this part of the spec closely, my tests there are quite old and I'm sure things have changed spec wise.

I'd like to know what @dholbert or @aethanyc think about these tests, as there were some recent changes in Firefox related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1316534#c24

**Comment by mrego** [comment]
Note also that `flex-minimum-height-flex-items-007.xht` only pass on Firefox which is suspicious too: https://wpt.fyi/results/css/css-flexbox/flex-minimum-height-flex-items-007.xht?run_id=711240001&run_id=697770002&run_id=737900001&run_id=715540002&run_id=705490001

**Comment by mrego** [comment]
CC @svillar and @Loirooriol just in case you have a better understanding of the expected behavior for these tests.

**Comment by cbiesinger** [comment]
I think this test is correct? See https://drafts.csswg.org/css-flexbox/#min-size-auto:
> However, if the box has an aspect ratio and no specified size suggestion, its content-based minimum size is the smaller of its content size suggestion and its transferred size suggestion

In this case, the transferred size suggestion is 100px (from height:100px and aspect-ratio), and the content size suggestion is the same thing because the min-content size of a replaced element is the one calculated from the aspect ratio. (cc @fantasai  -- why does the spec separate transferred size and content size suggestions when they should always be identical?)

**Comment by foolip** [comment]
@cbiesinger All implementations appear to be failing this test in the same way, but it's a correct interpretation of the spec, is that what you mean? Should the spec change in this case, or what should we do?

**Comment by Loirooriol** [comment]
Note the test was passing in Firefox until https://bugzilla.mozilla.org/show_bug.cgi?id=1316534
Then it started failing because of https://bugzilla.mozilla.org/show_bug.cgi?id=1665532
So Mozilla seems to think the test is correct:

> The root cause is that when we calculating content size suggestion of a flex item image, we take the image's intrinsic size as the min-content width, and the width is currently not affected by the image's intrinsic aspect ratio and height. See the attached testcase for comparision.
> https://github.com/w3c/csswg-drafts/issues/5032 has more discussion on this topic.

**Comment by tabatkins** [comment]
Yes, this test is correct due to the 'min-width/height: auto' default; the 100px height gets transferred across the ratio and should thus resolve to effectively "min-width: 100px".

**Comment by tabatkins** [comment]
> (cc @fantasai -- why does the spec separate transferred size and content size suggestions when they should always be identical?)

I don't understand what you mean by this - I don't see any reason they should be identical?

**Comment by cbiesinger** [comment]
@tabatkins : 
> I don't understand what you mean by this - I don't see any reason they should be identical?

Because:
1. Transferred size suggestion is the size computed using the aspect ratio
2. Content size suggestion is the min-content size. The min-content size for an element with aspect-ratio is also calculated using the aspect-ratio, as per https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263

So, whenever a transferred size suggestion exists, it should be identical to the content size suggestion. No?

**Comment by tabatkins** [comment]
Ah, right, ok, the Flexbox text predates that Sizing resolution. ^_^

**Comment by cbiesinger** [comment]
So wait, are you saying that text is incorrect now? Because if min-content
should actually be the natural width of the image, the test is incorrect.

**Comment by davidsgrogan** [comment]
I think both flex-minimum-width-flex-items-007.xht and flex-minimum-height-flex-items-007.xht are correct.

Today's chrome dev release fixes flex-minimum-height-flex-items-007.xht.

I have a local patch that fixes flex-minimum-width-flex-items-007.xht.

But, similar to what cbiesinger mentioned above, I was going to submit a spec issue about the redundancy in the flex spec between transferred size suggestion and content size suggestion, so I am very interested in Tab's answer to https://github.com/web-platform-tests/wpt/pull/26250#issuecomment-715483015 because that could affect my understanding here.

**Comment by tabatkins** [comment]
No, I'm saying the redundancy is due to it being written before the Sizing resolution made it always occur.

**Comment by aethanyc** [comment]
Re: @Loirooriol 
As noted in [Firefox bug 1665532](https://bugzilla.mozilla.org/show_bug.cgi?id=1665532), I think the test is correct, and we shouldn't delete it. It's failing in currently Firefox Nightly 84 because of [Bug 1665532](https://bugzilla.mozilla.org/show_bug.cgi?id=1665532).

Re: @davidsgrogan  @cbiesinger 
Coincidentally, I'm also trying to make Firefox pass `flex-minimum-width-flex-items-007.xht`, and [`flex-minimum-width-flex-items-013.html`](http://wpt.live/css/css-flexbox/flex-minimum-width-flex-items-013.html) now looks wrong to me.

I'm also interested in the spec issue your going to file regarding the redundancy between transferred size suggestion and content size suggestion. It seems to me per #5032, content size suggestion is the transferred size suggestion clamped by the definite max main size property in today's spec, so it makes transferred size suggestion redundant, doesn't it?

**Comment by davidsgrogan** [comment]
@aethanyc Agreed that flex-minimum-width-flex-items-013.html is wrong. I'm glad you came to the same conclusion :)

Also agreed that transferred size suggestion is redundant. I disabled it locally in Blink and no tests failed.

**Comment by davidsgrogan** [comment]
@aethanyc I also have .flexbox 5 in flex-aspect-ratio-img-column-011.html being wrong. Have you seen that one?

**Comment by aethanyc** [comment]
> Also agreed that transferred size suggestion is redundant. I disabled it locally in Blink and no tests failed.

@davidsgrogan I'm now less sure whether the transferred size suggestion is redundant, because flexbox has extra rules about the definiteness of a flex item's cross-size per spec [here](https://drafts.csswg.org/css-flexbox-1/#definite-sizes). Consider [the following example](https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8622):

```
<div style="display:flex; width:0; height: 50px;">
  <img style="" src="https://placehold.it/300x100" >
</div>
```

The image's cross-size is not specified, but it is definite because the flex container has `height:50px`. So the image's transfer size suggestion is 150px, and content size suggestion is its natural size 300px. The final size of the image should be 150x50, but removing transfer size suggestion yields 300x50.

> I also have .flexbox 5 in flex-aspect-ratio-img-column-011.html being wrong. Have you seen that one?

Yes, I have! Do you have any plan to fix it?

**Comment by davidsgrogan** [comment]
Oh, interesting example. Today FF Nightly gives the image 150px width but Chrome gives it 300px width. For transferred size, the spec says:
> If the item has a preferred aspect ratio and its **computed cross size property** is definite

In 9.8, the definite rule says:

> the **outer cross size** of any stretched flex items ... is considered definite.

Are **computed cross size property** and **outer cross size** equivalent for the purposes of this example? I don't know. Chrome considers them different. Firefox considers them the same. csswg-drafts issue needed!

For the broken tests, I have them fixed locally but haven't uploaded the patch for review yet. Hopefully tomorrow, but feel free to fix before me if you want.

**Comment by aethanyc** [comment]
> For the broken tests, I have them fixed locally but haven't uploaded the patch for review yet. Hopefully tomorrow, but feel free to fix before me if you want.

@davidsgrogan I haven't looked closely to the failed test yet, still hacking my implementation. I'm happy to wait for your fix sync to wpt since you've invested some efforts fixing them.

@foolip Sorry for hijack this issue to discuss other things. Shall we proceed with not deleting the test and closing this issue?

**Comment by foolip** [comment]
@aethanyc this sort of discussion is the best I could hope for when sending a naive PR like this, much better than it just being approved and merged :)

It sounds like additional cases were discovered, are tests for that being added somewhere now? (Sorry, didn't everything carefully.)

**Comment by davidsgrogan** [comment]
Agreed, this was fantastic.

When https://github.com/w3c/csswg-drafts/issues/5663 is resolved, I will ensure that the relevant test is added.

**Comment by foolip** [comment]
Thanks @davidsgrogan, I'll go ahead and close this now.

**Comment by davidsgrogan** [comment]
@aethanyc Those test fixes were merged an hour ago in https://github.com/web-platform-tests/wpt/pull/26299

**Comment by aethanyc** [comment]
@davidsgrogan Wonderful! The fixed tests now pass with my patch!

**Comment by foolip** [comment]
Wow, that went well. I'm encouraged, so I filed another naive issue making guesses about what might be wrong with another test: https://github.com/web-platform-tests/wpt/issues/26326

**Pull request closed without merging**
