### PR TITLE
Make fetch_tests_from_worker return a promise

### PR DESCRIPTION
**Pull request by jakearchibald**
Extracted from https://github.com/w3c/web-platform-tests/pull/10348#discussion_r186408609.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10978)

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
As I mentioned on IRC, I'm not terribly excited, but let's go ahead anyway.

**Comment by jakearchibald** [comment]
I think I missed the IRC discussion. What can I do to improve this?

**Comment by Ms2ger** [comment]
Sorry, I confused myself, the IRC conversation was about another change. All good here :)

**Comment by jakearchibald** [comment]
Haha phew, I thought I'd finally lost my loose grip on reality

**Pull request merged**
