### PR TITLE
Add test for image-set parsing

### PR DESCRIPTION
**Pull request by noamr**

### CODE REVIEW

**Review by yoavweiss — APPROVED** [review]
LGTM

Maybe you can also add some pathological broken cases and see that they're invalid:
"url(example.png) url(gibrish)", "example.png dfglkdngofdngo", etc

**Comment by noamr** [comment]
> LGTM
> 
> Maybe you can also add some pathological broken cases and see that they're invalid:
> "url(example.png) url(gibrish)", "example.png dfglkdngofdngo", etc

Sure, will add more tests

**Comment by noamr** [comment]
What do I need for merge rights? @yoavweiss can you click merge in the meantime?

**Comment by yoavweiss** [comment]
Dunno what are the conditions for getting write access. @foolip ?

**Comment by foolip** [comment]
We are pretty liberal with giving people write access, but there's no process or list of conditions. @noamr I've sent you and invite to the org and the reviewers team. If you'd like to add yourself to a META.yml file to get reviews in some directory, feel free to just send a PR doing that.

**Pull request merged**
