### PR TITLE
Update test to match IDL change

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

### CODE REVIEW

**Review by lukebjerring — COMMENTED** [review]
This is a breaking change. @foolip what's the go in these situations ( if it's an intended breaking change )?

**Comment by foolip** [comment]
@lukebjerring isn't it just that the test needs updating?

**Comment by foolip** [comment]
Oh, attributes were renamed. In that case it'd be good to have an historical test that fails until it's renamed in impls, and then just land this PR and the needed test updates.

**Comment by lukebjerring** [comment]
@foolip tweaked the test. PTAL.

**Review by foolip — APPROVED** [review]

**Pull request merged**
