### PR TITLE
Add interfaces/crash-reporting.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/0cb115a/ed/idl/crash-reporting.idl
Build: https://travis-ci.org/w3c/webref/builds/182613166

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I suspect we wouldn't be able to test this, given that the browser has to crash for it to be sent 😆 . It's actually addressed in the spec:

> Note: Crash reports are not observable to JavaScript, as the page which would receive them is, by definition, not able to. The IDL description of CrashReportBody exists in this spec to provide a JSON-seriaizable interface whose serialization can be embedded in the out-of-band reports.

Perhaps if there was a webdriver hook for it, but that depends on how they want to approach their testing strategy in general. cc @clelland

**Comment by foolip** [comment]
Hmm, that sounds like a use of Web IDL similar to https://w3c.github.io/sensors/#automation, or is the interface object supposed to be exposed but just never instantiated?

**Comment by stephenmcgruer** [comment]
> Hmm, that sounds like a use of Web IDL similar to https://w3c.github.io/sensors/#automation, or is the interface object supposed to be exposed but just never instantiated?

Oh right, if its not exposed then we can never test anything. Should it be (is it?) in a non-normative section? Would that stop reffy from exporting it?

**Comment by foolip** [comment]
Yeah, marking it non-normative would work, or one can add the `exclude` class to the IDL block.

**Comment by foolip** [comment]
The selector used for this is here:
https://github.com/tidoust/reffy/blob/7c8c139e86e4f6712cf2d326be58c0bac32705ce/src/browserlib/extract-webidl.js#L106-L112

**Comment by stephenmcgruer** [comment]
https://github.com/WICG/crash-reporting/pull/8 has landed, reffy should hopefully close this automatically soon?

**Pull request closed without merging**
