### PR TITLE
Test the 'unusual behaviors' of document.all

### PR DESCRIPTION
**Pull request by frewsxcv**
See the spec for more information

### CODE REVIEW

**Comment by zcorpan** [comment]
Critic stopped tracking this branch (maybe you did `--amend`?), but I'll review here instead.

Can you add tests for `if (document.all)`, `if (!document.all)`, `!=` and `===`.

Can you add tests where you first set the value of `document.all` to a variable and check that?

**Comment by frewsxcv** [comment]
Addressed your comments

**Comment by zcorpan** [comment]
Thanks. The code now checks `document.all` twice, and doesn't use the `all` argument. To actually test the behaviors for both bare `document.all` and a variable (or argument), it seems best to just repeat the assertions.

**Comment by frewsxcv** [comment]
@zcorpan Look better?

**Comment by zcorpan** [comment]
Yes, thank you!

**Pull request merged**
