### PR TITLE
Rewrite self.html as an any.js test.

### PR DESCRIPTION
**Pull request by Ms2ger**
Bonus: this adds coverage for shared and service workers.

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by annevk** [comment]
Does the tooling do the .https. magic for service workers?

**Comment by Ms2ger** [comment]
> Does the tooling do the .https. magic for service workers?

Looking at another test that does it: <https://wpt.fyi/results/workers?label=master&label=experimental&q=worker-replace-global-constructor>. It seems to all work fine.

**Comment by jgraham** [comment]
You can also confirm that this does what you expect by looking at the wpt.fyi links in the status checks e.g. https://wpt.fyi/results/workers/interfaces/WorkerGlobalScope?sha=8f6fa9cfe0

**Comment by annevk** [comment]
Hmm, so does `.serviceworker.` imply `.https.` these days? https://web-platform-tests.org/writing-tests/general-guidelines.html does not mention it.

**Comment by jgraham** [comment]
Yeah, see https://github.com/web-platform-tests/wpt/blob/master/tools/manifest/sourcefile.py#L79 It was fixed in https://github.com/web-platform-tests/wpt/pull/6792 I assume the docs don't mention it because it "just works", but you're right that they should.

**Comment by annevk** [comment]
Well, that commit added `https` to the filename as well, but it seems that's no longer the case so there was another change made since then that did not address the documentation.

**Pull request merged**
