### PR TITLE
Update referrer-policy tests to test the `referrerpolicy` attribute

### PR DESCRIPTION
**Pull request by estark37**
This PR does the following things:
- changes the referrer-policy attribute name from `referrer` to `referrerpolicy` to match recent changes in the spec
- updates the common referrer-policy test case code to support the `referrerpolicy` attribute for `img` and `iframe`
- generates tests for the range of `referrerpolicy` attribute values and supported elements

Chrome Canary passes these new tests for the `referrerpolicy` attribute when run with --enable-experimental-web-platform-features to enable the attribute.

This is my first time working on this repo so please let me know if I've done anything silly!

cc @jeisinger @franziskuskiefer

### CODE REVIEW

**Comment by jeisinger** [comment]
could you add a test that checks that only valid policies are reflected?

**Comment by estark37** [comment]
@jeisinger: Done. (This test doesn't pass in Chrome yet because I think the attribute isn't fully implemented for `area` yet.)

**Comment by franziskuskiefer** [comment]
awesome, thanks Emily, the tests are looking good. I'll test them against Firefox to see what we have to fix yet.

**Comment by estark37** [comment]
@franziskuskiefer: I should note that there a ~6 referrer-policy tests unrelated to this PR that are failing in  both Chrome and Firefox right now (the swap-origin-redirect.http.html ones). I think it's a bug in the tests. I can look into it separately.

**Comment by franziskuskiefer** [comment]
Yes that seems to be a bug in the tests. Firefox is also failing a couple of other tests such as the `cross-origin.no-redirect.http.html`. Similar to the `swap-origin-redirect.http.html` I can't actually see any referrer policy being set in those tests and some other tests.

**Comment by jeisinger** [comment]
sorry for the long delay, and thanks for adding the test

This PR LGTM

@franziskuskiefer are you also ok with merging this?

**Comment by franziskuskiefer** [comment]
The patch looks good in general. We should check what's going on with the errors though. But maybe we can do that in a follow up.

**Comment by estark37** [comment]
Yeah, I'd prefer to figure out the swap-origin-redirect failures in a separate patch, if it's okay with you two. (Since they're not related to the `referrerpolicy` attribute which is what I'm focusing on in this patch.)

**Comment by jeisinger** [comment]
summoning @mikewest to merge

**Pull request merged**
