### PR TITLE
Use /fonts/ahem.css over similar support/ahem.css in vendor-imports

### PR DESCRIPTION
**Pull request by foolip**
This is to make moving the tests easier, with fewer relative paths and
less lint errors to ignore.

As a drive-by fix, make use of XHTML-style <link /> markup more
consistent within tests, which in every case meant dropping it.

Part of https://github.com/web-platform-tests/wpt/issues/8615.

### CODE REVIEW

**Comment by foolip** [comment]
This is based on https://github.com/web-platform-tests/wpt/pull/26854, which should be merged before this.

**Comment by cbiesinger** [comment]
Probably better if someone from Mozilla reviews this, to ensure this doesn't break their CI

**Comment by foolip** [comment]
@cbiesinger good idea. This directory should be like anything else in WPT now, but some special behavior might remain on accident. @jgraham can you take a look?

**Review by Ms2ger — APPROVED** [review]
Feel free to wait for James, if you prefer.

**Review by jgraham — APPROVED** [review]

**Comment by foolip** [comment]
I regressed some tests, so I attempted to fix those as part of rebasing this.

**Pull request merged**
