### PR TITLE
[css-typed-om] CSSMatrixComponent mutable matrix test.

### PR DESCRIPTION
**Pull request by shans**
Tests <https://github.com/w3c/css-houdini-drafts/issues/352>

### CODE REVIEW

**Comment by tobie** [comment]
@wpt-pr-bot, you there?

**Comment by tobie** [comment]
@wpt-pr-bot, you there?

**Comment by tobie** [comment]
@wpt-pr-bot, you there?

**Comment by tobie** [comment]
@wpt-pr-bot, you there?

**Comment by tobie** [comment]
@wpt-pr-bot, you there?

**Comment by tobie** [comment]
@wpt-pr-bot, are you here?

**Comment by tobie** [comment]
@wpt-pr-bot, are you here?

**Comment by tobie** [comment]
@wpt-pr-bot, what's up?

**Comment by tobie** [comment]
@wpt-pr-bot, what's up?

**Comment by tobie** [comment]
@wpt-pr-bot hey!

**Comment by tobie** [comment]
Sorry for the comment spam. @wpt-pr-bot had a weird issue with your PR, and I accidentally generated a endless loop while debugging it. :-/ Apologies.

**Review by kojiishi — APPROVED** [review]
lgtm

**Pull request merged**
