### PR TITLE
Add option to show test types to |wpt tests-affected|

### PR DESCRIPTION
**Pull request by mjzffr**
Example:

```
 ./wpt tests-affected --show-type 50837d450dc9f851eb04542a41b1d58dc9b43c98..HEAD
reftest	css-paint-api/parse-input-arguments-018.html
reftest	css/css-position-3/position-sticky-nested-bottom.html
reftest	css/css-position-3/position-sticky-nested-left.html
reftest	css/css-position-3/position-sticky-nested-right.html
reftest	css/css-position-3/position-sticky-nested-top.html
reftest	css/vendor-imports/mozilla/mozilla-central-reftests/multicol3/multicol-height-002.xht
testharness	html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html
testharness	html/semantics/forms/the-textarea-element/value-defaultValue-textContent.html
testharness	mediacapture-fromelement/capture.html
testharness	mediacapture-fromelement/creation.html
testharness	mediacapture-fromelement/ended.html
testharness	payment-request/payment-request-show-method.https.html
```

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6667)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259612438)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259612439)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259612445)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259612446)

# Sauce (MicrosoftEdge) #

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[tools/wpt/testfiles.py, line 118 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqS0nh33GROPNsd-Kmf:-KqS0nh33GROPNsd-Kmg:b-8y7lla) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd2ef9764aa9f04ae13e8f7339adbab394c7a96b/tools/wpt/testfiles.py#L118)):*
> ```Python
>     test_types = ["testharness", "reftest", "wdspec"]
> 
>     global wpt_manifest
> ```

Not sure this should be a global. Maybe create a `load_manifest` function that caches its result?

---

*[tools/wpt/testfiles.py, line 236 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqS0ErUPwpHsq9wx7T4:-KqS0ErVaomHlTIxW9dW:b-uq5hyb) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd2ef9764aa9f04ae13e8f7339adbab394c7a96b/tools/wpt/testfiles.py#L236)):*
> ```Python
>         }
>         if kwargs["show_type"]:
>             message = "{item_type}\t{path}"
> ```

Can we swap the order here so that it consistently has path first?a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Comment by mjzffr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/wpt/testfiles.py, line 118 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqS0nh33GROPNsd-Kmf:-KqTRNI3OcOrhz1HWkEl:b-266d6r) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd2ef9764aa9f04ae13e8f7339adbab394c7a96b/tools/wpt/testfiles.py#L118)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Not sure this should be a global. Maybe create a `load_manifest` function that caches its result?
</blockquote></details>

Done, I guess. Maybe you had something else in mind...

---

*[tools/wpt/testfiles.py, line 236 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqS0ErUPwpHsq9wx7T4:-KqTRcKBZGfHF3gWNfh7:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/cd2ef9764aa9f04ae13e8f7339adbab394c7a96b/tools/wpt/testfiles.py#L236)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Can we swap the order here so that it consistently has path first?a
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/wpt/testfiles.py, line 110 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqTSZconQS1rjGUiLSn:-KqTSZcpJThc7Ts_V_WI:b815wq9) ([raw file](https://github.com/w3c/web-platform-tests/blob/6294be6eb76a0dd5a5d1d648758d29ef4f2c06e2/tools/wpt/testfiles.py#L110)):*
> ```Python
> 
>     def load(manifest_path=None):
>         print("loading manifest")
> ```

Remove the print statements.

---

*[tools/wpt/testfiles.py, line 114 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqTSc74jLykPH968T_4:-KqTSc74jLykPH968T_5:b-4g6hr1) ([raw file](https://github.com/w3c/web-platform-tests/blob/6294be6eb76a0dd5a5d1d648758d29ef4f2c06e2/tools/wpt/testfiles.py#L114)):*
> ```Python
>             manifest_path = os.path.join(wpt_root, "MANIFEST.json")
>         if c.get(manifest_path):
>             print("we used the cache yay!")
> ```

(also here)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Comment by mjzffr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/wpt/testfiles.py, line 110 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqTSZconQS1rjGUiLSn:-KqTXBhOLPGW4ByRTxRm:b-tcvpos) ([raw file](https://github.com/w3c/web-platform-tests/blob/6294be6eb76a0dd5a5d1d648758d29ef4f2c06e2/tools/wpt/testfiles.py#L110)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Remove the print statements.
</blockquote></details>

Done. whoops!

---

*[tools/wpt/testfiles.py, line 114 at r2](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667#-KqTSc74jLykPH968T_4:-KqTXDV6jYXvlhOLVseq:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/6294be6eb76a0dd5a5d1d648758d29ef4f2c06e2/tools/wpt/testfiles.py#L114)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

(also here)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6667)*

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
Need to fix the merge conflict (sorry, my fault).

**Pull request merged**
