### PR TITLE
Use .any.js for html/webappapis/timers tests

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Thanks! I asked on IRC about the Chrome failure.

**Comment by annevk** [comment]
@domenic @foolip it seems that `/html/webappapis/timers/negative-settimeout.any.worker.html` which is
```js
setup({ single_test: true });
setTimeout(done, -100);
setTimeout(assert_unreached, 10);
```
ends up failing in Chrome 7 out of 10 times. Do either of you know if this is a known problem?

**Comment by domenic** [comment]
I'm not aware of a bug on file, and a quick search doesn't turn one up.

**Comment by annevk** [comment]
@stephenmcgruer what's the protocol for landing with known intermittents when there's a browser bug?

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer what's the protocol for landing with known intermittents when there's a browser bug?

We prefer that there's a bug on file with the browser (is there here? I wasn't sure.), but once that's happened we are happy to admin-merge these cases. The stability checks exist to guard against bad tests, not bad browsers! :)

**Comment by annevk** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1164398 on Chrome.

**Pull request merged**
