### PR TITLE
Adjust XHR CORS test to allow custom Content-Type

### PR DESCRIPTION
**Pull request by sideshowbarker**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision b18cb2fd8ae0673b1ee987e1e6b1ee41a4f67c88
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/timeout-cors-async.htm">/XMLHttpRequest/timeout-cors-async.htm</a></summary>


|                         Subtest                          | Results |
|----------------------------------------------------------|---------|
|                                                          | OK      |
| `XMLHttpRequest: timeout event and cross-origin request` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/event-upload-progress-crossorigin.htm">/XMLHttpRequest/event-upload-progress-crossorigin.htm</a></summary>


|                              Subtest                              | Results |
|-------------------------------------------------------------------|---------|
|                                                                   | OK      |
| `XMLHttpRequest: upload progress event for cross-origin requests` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/send-redirect-to-cors.htm">/XMLHttpRequest/send-redirect-to-cors.htm</a></summary>


|                                         Subtest                                          | Results |
|------------------------------------------------------------------------------------------|---------|
|                                                                                          | OK      |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with null)`        | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (301)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (303)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (302)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with string)`      | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with typed array)` | PASS    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision b18cb2fd8ae0673b1ee987e1e6b1ee41a4f67c88
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/timeout-cors-async.htm">/XMLHttpRequest/timeout-cors-async.htm</a></summary>


|                         Subtest                          | Results |
|----------------------------------------------------------|---------|
|                                                          | OK      |
| `XMLHttpRequest: timeout event and cross-origin request` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/event-upload-progress-crossorigin.htm">/XMLHttpRequest/event-upload-progress-crossorigin.htm</a></summary>


|                              Subtest                              | Results |
|-------------------------------------------------------------------|---------|
|                                                                   | OK      |
| `XMLHttpRequest: upload progress event for cross-origin requests` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4801/XMLHttpRequest/send-redirect-to-cors.htm">/XMLHttpRequest/send-redirect-to-cors.htm</a></summary>


|                                         Subtest                                          | Results |
|------------------------------------------------------------------------------------------|---------|
|                                                                                          | OK      |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with null)`        | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (301)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (303)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (302)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with string)`      | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307)`                       | PASS    |
| `XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with typed array)` | PASS    |

</details>

**Comment by annevk** [comment]
Can you explain what you are making this change for? Hard to tell without corresponding test.

**Comment by sideshowbarker** [comment]
See https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/send-redirect-to-cors.htm#L53

As far as I can see, those tests are failing in Blink and WebKit due to the `Access-Control-Allow-Headers` response header generated from `XMLHttpRequest/resources/corsenabled.py` not including `Content-Type`. (Why they pass in Gecko anyway without this change I don’t understand.)

**Comment by annevk** [comment]
I think what we should do instead is invert the pass condition there and file a bug against Gecko as Gecko violates CORS there.

**Comment by annevk** [comment]
Because https://fetch.spec.whatwg.org/#cors-preflight-fetch-0 step 6.9 only allows it to be omitted if its safelisted, which that particular value is not.

**Comment by annevk** [comment]
Closing this in favor of my PR to solve this issue, which ends up highlighting the problem in Firefox. Two tests still fail in WebKit but that seems like a bug.

**Pull request closed without merging**
