### PR TITLE
Referrer Policy: Test image loads inside srcdoc frames.

### PR DESCRIPTION
**Pull request by mikewest**
This patch teaches the 'img-tag'-style tests to load an image both
in the top-level document, and inside a 'srcdoc' frame. The referrer
should be the same in both places.

Addresses w3c/web-platform-tests#2851.

### CODE REVIEW

**Comment by mikewest** [comment]
@bzbarsky: Are you happy with this? If so, I'll merge it.

**Comment by bzbarsky** [comment]
Yes, this seems reasonable in general.

For dynamic referrer policy changes (e.g. dynamic meta tag insertion?), it would be nice to test the situation in which the srcdoc iframe is created and loaded _before_ the dynamic mutation happens.  But we can push that off into a separate issue; it seems like a good bit of work to do.

**Comment by estark37** [comment]
@mikewest ping -- is this ready to merge? It addresses https://github.com/w3c/webappsec-referrer-policy/issues/57.

**Comment by mikewest** [comment]
Thanks for the ping, Emily!

**Pull request merged**
