### PR TITLE
Don't decode arbitrary %2e during URL parsing after all

### PR DESCRIPTION
**Pull request by annevk**
This reverts commit 47d2089cb11d5f5047f3bd2f183eecd471bc2d07.

See https://github.com/whatwg/url/issues/87 for discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/4104)

### CODE REVIEW

**Comment by annevk** [comment]
Note that Firefox already WONTFIXED their corresponding bug (and therefore agrees with this change) and Safari advocated for it. We don't really know what the other browsers will do unfortunately.

**Review by zcorpan — APPROVED** [review]

**Comment by annevk** [comment]
I suggest we keep this open for now given that Google is not okay with going in this direction.

**Comment by annevk** [comment]
I suggest we land this per https://github.com/whatwg/url/issues/87#issuecomment-269635883 since what's currently defined isn't really implemented anywhere.

**Comment by domenic** [comment]
After updating whatwg-url per https://github.com/whatwg/url/pull/156/files the following tests additionally fail:

```
  1) Web platform tests setters pathname <view-source+http://example.net/home?lang=fr#nav>.pathname = "\a\%2E\b\%2e.\c" \ is *not* a segment delimiter for non-'special' URLs:

      AssertionError: 'view-source+http://example.net/\\a\\%2E\\b\\%2e.\\c?lang=fr#nav' == 'view-source+http://example.net/\\a\\.\\b\\..\\c?lang=fr#nav'
      + expected - actual

      -view-source+http://example.net/\a\%2E\b\%2e.\c?lang=fr#nav
      +view-source+http://example.net/\a\.\b\..\c?lang=fr#nav
```

```
  2) Web platform tests setters pathname <http://example.net>.pathname = "%2e%2E%c3%89té" Bytes already percent-encoded are left as-is, except %2E.:

      AssertionError: 'http://example.net/%2e%2E%c3%89t%C3%A9' == 'http://example.net/..%c3%89t%C3%A9'
      + expected - actual

      -http://example.net/%2e%2E%c3%89t%C3%A9
      +http://example.net/..%c3%89t%C3%A9
```

**Review by domenic — APPROVED** [review]

**Pull request merged**
