### PR TITLE
Revise and add to <meta> refresh tests

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/html/pull/2852, and also adds some extra coverage for other weird floating point numbers.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255870746)

# Firefox (nightly) #
Testing web-platform-tests at revision f0d1bd71252878351840c827ffd81aeeb1b56260
Using browser at version BuildID 20170720100139; SourceStamp 0985725c848ec0cfc6f2f3c3a5aa3d71321e7620
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6595/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html">/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html</a></summary>


|         Subtest         | Results |                                          Messages                                         |
|-------------------------|---------|-------------------------------------------------------------------------------------------|
|                         | TIMEOUT |                                                                                           |
| `""`                    | PASS    |                                                                                           |
| `"1"`                   | PASS    |                                                                                           |
| `"1 "`                  | PASS    |                                                                                           |
| `"1\t"`                 | PASS    |                                                                                           |
| `"1\r"`                 | PASS    |                                                                                           |
| `"1\n"`                 | PASS    |                                                                                           |
| `"1\f"`                 | TIMEOUT | `Test timed out`                                                                          |
| `"1;"`                  | PASS    |                                                                                           |
| `"1,"`                  | PASS    |                                                                                           |
| `"1; url=foo"`          | PASS    |                                                                                           |
| `"1, url=foo"`          | PASS    |                                                                                           |
| `"1 url=foo"`           | PASS    |                                                                                           |
| `"1;\turl=foo"`         | PASS    |                                                                                           |
| `"1,\turl=foo"`         | PASS    |                                                                                           |
| `"1\turl=foo"`          | PASS    |                                                                                           |
| `"1;\rurl=foo"`         | PASS    |                                                                                           |
| `"1,\rurl=foo"`         | PASS    |                                                                                           |
| `"1\rurl=foo"`          | PASS    |                                                                                           |
| `"1;\nurl=foo"`         | PASS    |                                                                                           |
| `"1,\nurl=foo"`         | PASS    |                                                                                           |
| `"1\nurl=foo"`          | PASS    |                                                                                           |
| `"1;\furl=foo"`         | FAIL    | `assert_equals: expected "foo" but got "{\"error\": {\"message\": \"\", \"code\": 404}}"` |
| `"1,\furl=foo"`         | FAIL    | `assert_equals: expected "foo" but got "{\"error\": {\"message\": \"\", \"code\": 404}}"` |
| `"1\furl=foo"`          | TIMEOUT | `Test timed out`                                                                          |
| `"1url=foo"`            | PASS    |                                                                                           |
| `"1x;url=foo"`          | PASS    |                                                                                           |
| `"1 x;url=foo"`         | PASS    |                                                                                           |
| `"1;;url=foo"`          | PASS    |                                                                                           |
| `"  1  ;  url  =  foo"` | PASS    |                                                                                           |
| `"  1  ,  url  =  foo"` | PASS    |                                                                                           |
| `"  1  ;  foo"`         | PASS    |                                                                                           |
| `"  1  ,  foo"`         | PASS    |                                                                                           |
| `"  1  url  =  foo"`    | PASS    |                                                                                           |
| `"1; url=foo "`         | PASS    |                                                                                           |
| `"1; url=f\to\no"`      | PASS    |                                                                                           |
| `"1; url=\"foo\"bar"`   | PASS    |                                                                                           |
| `"1; url='foo'bar"`     | PASS    |                                                                                           |
| `"1; url=\"foo'bar"`    | FAIL    | `assert_equals: expected "foo'bar" but got "foo"`                                         |
| `"1; url foo"`          | PASS    |                                                                                           |
| `"1; urlfoo"`           | PASS    |                                                                                           |
| `"1; urfoo"`            | PASS    |                                                                                           |
| `"1; ufoo"`             | PASS    |                                                                                           |
| `"1; \"foo\"bar"`       | PASS    |                                                                                           |
| `"; foo"`               | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `", foo"`               | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"foo"`                 | PASS    |                                                                                           |
| `"+1; url=foo"`         | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"-1; url=foo"`         | PASS    |                                                                                           |
| `"+0; url=foo"`         | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"-0; url=foo"`         | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"0; url=foo"`          | PASS    |                                                                                           |
| `"+1; foo"`             | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"-1; foo"`             | PASS    |                                                                                           |
| `"+0; foo"`             | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"-0; foo"`             | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |
| `"0; foo"`              | PASS    |                                                                                           |
| `"+1"`                  | FAIL    | `assert_unreached: Got > 1 load events Reached unreachable code`                          |
| `"-1"`                  | FAIL    | `assert_unreached: Got > 1 load events Reached unreachable code`                          |
| `"+0"`                  | FAIL    | `assert_unreached: Got > 1 load events Reached unreachable code`                          |
| `"-0"`                  | FAIL    | `assert_unreached: Got > 1 load events Reached unreachable code`                          |
| `"0"`                   | PASS    |                                                                                           |
| `"1.9; url=foo"`        | PASS    |                                                                                           |
| `"1.9..5.; url=foo"`    | PASS    |                                                                                           |
| `".9; url=foo"`         | PASS    |                                                                                           |
| `"0.9; url=foo"`        | PASS    |                                                                                           |
| `"1e0; url=foo"`        | PASS    |                                                                                           |
| `"1e1; url=foo"`        | PASS    |                                                                                           |
| `"10e-1; url=foo"`      | PASS    |                                                                                           |
| `"-0.1; url=foo"`       | FAIL    | `assert_equals: expected "refresh.sub.html" but got "foo"`                                |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255870747)

# Sauce (safari) #
Testing web-platform-tests at revision f0d1bd71252878351840c827ffd81aeeb1b56260
Using browser at version 10.0
Starting 10 test iterations
## Unstable results ##


|                                                       Test                                                       |         Subtest         |                  Results                  |                             Messages                             |
|------------------------------------------------------------------------------------------------------------------|-------------------------|-------------------------------------------|------------------------------------------------------------------|
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `""`                    | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1"`                   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1 "`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\t"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\r"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\n"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\f"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1,"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1, url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1 url=foo"`           | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;\turl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1,\turl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\turl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;\rurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1,\rurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\rurl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;\nurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1,\nurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\nurl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;\furl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1,\furl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1\furl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1url=foo"`            | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1x;url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1 x;url=foo"`         | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1;;url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"  1  ;  url  =  foo"` | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"  1  ,  url  =  foo"` | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"  1  ;  foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"  1  ,  foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"  1  url  =  foo"`    | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url=foo "`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url=f\to\no"`      | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url=\"foo\"bar"`   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url='foo'bar"`     | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url=\"foo'bar"`    | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; url foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; urlfoo"`           | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; urfoo"`            | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; ufoo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1; \"foo\"bar"`       | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"; foo"`               | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `", foo"`               | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"foo"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+1; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-1; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+0; url=foo"`         | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-0; url=foo"`         | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"0; url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+1; foo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-1; foo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+0; foo"`             | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-0; foo"`             | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"0; foo"`              | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+1"`                  | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-1"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"+0"`                  | **FAIL: 4/10, MISSING: 6/10**             | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-0"`                  | **FAIL: 4/10, MISSING: 6/10**             | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"0"`                   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1.9; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1.9..5.; url=foo"`    | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `".9; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"0.9; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1e0; url=foo"`        | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"1e1; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"10e-1; url=foo"`      | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html` | `"-0.1; url=foo"`       | **PASS: 4/10, MISSING: 6/10**             |                                                                  |

## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6595/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html">/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html</a></summary>


|         Subtest         |                  Results                  |                             Messages                             |
|-------------------------|-------------------------------------------|------------------------------------------------------------------|
|                         | TIMEOUT                                   |                                                                  |
| `""`                    | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1"`                   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1 "`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\t"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\r"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\n"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\f"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1;"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1,"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1, url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1 url=foo"`           | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1;\turl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1,\turl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\turl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1;\rurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1,\rurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\rurl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1;\nurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1,\nurl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\nurl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1;\furl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1,\furl=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1\furl=foo"`          | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1url=foo"`            | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1x;url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1 x;url=foo"`         | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1;;url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"  1  ;  url  =  foo"` | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"  1  ,  url  =  foo"` | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"  1  ;  foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"  1  ,  foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"  1  url  =  foo"`    | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `"1; url=foo "`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url=f\to\no"`      | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url=\"foo\"bar"`   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url='foo'bar"`     | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url=\"foo'bar"`    | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; url foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; urlfoo"`           | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; urfoo"`            | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; ufoo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1; \"foo\"bar"`       | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"; foo"`               | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `", foo"`               | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"foo"`                 | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+1; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"-1; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+0; url=foo"`         | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"-0; url=foo"`         | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"0; url=foo"`          | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+1; foo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"-1; foo"`             | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+0; foo"`             | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"-0; foo"`             | **FAIL: 4/10, MISSING: 6/10**             | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"0; foo"`              | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+1"`                  | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `"-1"`                  | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"+0"`                  | **FAIL: 4/10, MISSING: 6/10**             | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `"-0"`                  | **FAIL: 4/10, MISSING: 6/10**             | `assert_unreached: Got > 1 load events Reached unreachable code` |
| `"0"`                   | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1.9; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1.9..5.; url=foo"`    | **TIMEOUT: 4/10, MISSING: 6/10**          | `Test timed out`                                                 |
| `".9; url=foo"`         | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"0.9; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"1e0; url=foo"`        | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"1e1; url=foo"`        | **PASS: 4/10, MISSING: 6/10**             |                                                                  |
| `"10e-1; url=foo"`      | **FAIL: 1/10, PASS: 3/10, MISSING: 6/10** | `assert_equals: expected "refresh.sub.html" but got "foo"`       |
| `"-0.1; url=foo"`       | **PASS: 4/10, MISSING: 6/10**             |                                                                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255870755)

# Chrome (unstable) #
Testing web-platform-tests at revision d7e52b17fc98e09e65a6467b25faacab54c3365b
Using browser at version 61.0.3159.5 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255870757)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision d7e52b17fc98e09e65a6467b25faacab54c3365b
Using browser at version 14.14393
Starting 10 test iterations

**Review by tkent-google — APPROVED** [review]
lgtm

**Comment by domenic** [comment]
The Safari flakiness seems to be consistent; I've re-started the build several times. I'm not sure I'm equipped to fix it, however. Should it block these additional tests, or perhaps be logged somewhere and dealt with later, e.g. by someone with a Mac dev machine?

**Comment by sideshowbarker** [comment]
> The Safari flakiness seems to be consistent; I've re-started the build several times. However, it is pre-existing in this file, and I'm not sure I'm equipped to fix it.

@tkent-google this looks like the same thing you run into with #6578

> Should it block these additional tests, or perhaps be logged somewhere and dealt with later, e.g. by someone with a Mac dev machine?

I went ahead and raised #6602 and can ahead and merge the PR whenever you let me know it's ready (seems 8ca0924 still needs review).

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Reviewed the remaining cases.

**Pull request merged**
