### PR TITLE
Remove assert_throws usage in IndexedDB tests.

### PR DESCRIPTION
**Pull request by bzbarsky**

### CODE REVIEW

**Review by inexorabletash — APPROVED** [review]
awesome, thanks!

**Comment by bzbarsky** [comment]
Hmm.  The Chrome stability failure is in a test that I didn't even touch.... @stephenmcgruer @jgraham any idea what's going on there?

**Comment by inexorabletash** [comment]
Ah, our old friend keypath-exceptions.htm - hey @jugglinmike it's back!

Maybe useful links https://github.com/web-platform-tests/wpt/pull/19713 and https://bugs.chromium.org/p/chromium/issues/detail?id=1014780 - any chance an older ChromeDriver is in use?

Otherwise... I still think https://github.com/web-platform-tests/wpt/pull/19985 would be an improvement...

**Comment by stephenmcgruer** [comment]
This would be using the Chromedriver from Chrome Dev, which is ~81 at this point and definitely should contain code from Nov 2019. So I think the answer might be that resolving that bug did not fix the problem.

Anyhow, since its unrelated and this has been approved, I will admin merge.

**Pull request merged**
