### PR TITLE
Make it possible to run webdriver-based Servo from wpt tool

### PR DESCRIPTION
**Pull request by jdm**
These are changes that were required when I was experimenting with running webdriver-enabled Servo from the `wpt` tool instead of Servo's custom automation.

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by jdm** [comment]
@jgraham Do you know what to make of https://travis-ci.org/web-platform-tests/wpt/jobs/442371998 ?

**Comment by gsnedders** [comment]
That is… an interesting failure.

**Comment by jdm** [comment]
That failure is affecting other PRs too: https://github.com/web-platform-tests/wpt/pull/13567

**Comment by gsnedders** [comment]
fixed by #13565 if you want to rebase onto that

**Comment by jgraham** [comment]
You don't need to rebase in cases like this fwiw; you just need to retrigger the job. Because Travis tests the merge of the PR into master rather than the PR itself and doesn't actually record the SHA for a single job but fetches the current version of the merge commit for each run.

**Pull request merged**
