### PR TITLE
Use get-host-info to run fetch/abort test in CI

### PR DESCRIPTION
**Pull request by youennf**
Use method.py to get a response without any body

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by annevk** [comment]
How does https://github.com/youennf/web-platform-tests/blob/master/fetch/api/resources/empty.txt contain a body?

**Comment by jdm** [comment]
@annevk I'm not sure I understand the question or why it's relevant.

**Comment by jdm** [comment]
Oh, the implication being that empty.txt used to somehow provide a body and was changed to method.py for this reason.

**Comment by annevk** [comment]
Yeah, I don't understand that change. And if it's needed presumably other files referencing empty.txt need to be modified too (or empty.txt can be removed).

**Comment by youennf** [comment]
Right, this is a change specific for WebKit as we are missing the empty.txt file.
I'll fix it on our side.

**Comment by youennf** [comment]
PR https://github.com/web-platform-tests/wpt/pull/14778 is reverting empty.txt change.

**Pull request merged**
