### PR TITLE
[storage-access-api] create META.yml

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@Brandr0id are you a good reviewer for this directory? It looks like there's no spec at all for this, is that right?

**Review by Brandr0id — APPROVED** [review]
LGTM

**Comment by foolip** [comment]
@Brandr0id I see you don't have write access to the repo, which will be a problem because your reviews won't result in a green checkmark and a mergable PR. I've invited you to the reviewers team, you should see a banner at the top of https://github.com/web-platform-tests or find something in your inbox.

I'll hold off merging this, because wpt-pr-bot won't be able to assign you as a reviewer unless you're a member of the org.

**Comment by Brandr0id** [comment]
Thanks, should be all good now. Looks like the status on this PR has updated already.

**Comment by foolip** [comment]
Yep, I've merged now, thanks!

**Pull request merged**
