### PR TITLE
Fix UTF-16 HTML parsing tests

### PR DESCRIPTION
**Pull request by Alcaro**
The byte dumps are all kinds of wrong in the UTF-16 tests, they keep thinking they're each other, and the UTF16-BE test somehow got encoded as UTF16-LE. Let's fix that.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248865673)

# Firefox (nightly) #
Testing web-platform-tests at revision 90fb94fed709c04ba2070f535d3cbf6bf066f879
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6438/html/syntax/parsing-html-fragments/the-input-byte-stream-003.html">/html/syntax/parsing-html-fragments/the-input-byte-stream-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6438/html/syntax/parsing-html-fragments/the-input-byte-stream-004.html">/html/syntax/parsing-html-fragments/the-input-byte-stream-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248865674)

# Sauce (safari) #
Testing web-platform-tests at revision 90fb94fed709c04ba2070f535d3cbf6bf066f879
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248865680)

# Chrome (unstable) #
Testing web-platform-tests at revision 90fb94fed709c04ba2070f535d3cbf6bf066f879

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248865681)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 90fb94fed709c04ba2070f535d3cbf6bf066f879

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Review by gsnedders — APPROVED** [review]
This is all correct, though the tests still don't run because of https://github.com/w3c/web-platform-tests/issues/6683.

**Comment by gsnedders** [comment]
Sorry for being slow to review this; just a bit awkward to make sure everything is correct with encoding tests. Thanks for catching this and fixing this!

**Comment by Alcaro** [comment]
Idea for a follow-up: Check document.characterSet in each of those tests.

I would've done it myself, but unfortunately [it varies between browsers](https://stackoverflow.com/a/42072440) (I don't trust case to be the only difference) and two of the browsers won't run on my Linux, so I couldn't produce a proper test for that.

Your choice if it's worthwhile.

**Comment by gsnedders** [comment]
I thought of that too. Realistically, given the extra complexity of that (esp. whether it returns UTF-16 v. UTF-16BE/LE) I think we should only test that in a test for document.characterSet itself.

**Pull request merged**
