### PR TITLE
Make Azure Pipelines green again

### LINKED ISSUE #26131: "tools/wpt/ tests: Windows" and "tools/ unittests: Windows + Python 3.8" fail on Azure Pipelines
These two tests have been failing consistently on Azure Pipelines. e.g. 
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56032&view=logs&j=47b03e2b-d31e-537f-c8cf-66c80d147ca1
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56041&view=logs&j=802ce073-f5e3-5667-fac8-56b586b322fa

The failures all seem similar.

"tools/wpt/ tests: Windows":
> test_run_verify_unstable
> CRITICAL Max restarts exceeded
> CRITICAL No tests ran

"tools/ unittests: Windows + Python 3.8":
> Traceback (most recent call last):
>  File "D:\a\1\s\tools\ci\tests\..\pr_preview.py", line 18, in <module>
>    import requests
> ModuleNotFoundError: No module named 'requests'

### PR DESCRIPTION
**Pull request by Hexcles**
This PR fixes #26131 and works around #26295 .

There are a bunch of different issues at hand. Each commit addresses one, so please review them individually.

This PR should probably be rebase-merged.

### CODE REVIEW

**Review by mutza974 — CHANGES_REQUESTED** [review]
@wpt-pr-bot

**Comment by Hexcles** [comment]
Full logs: https://pastebin.com/KTHqJ9FE
Or a different one (for Py3.8): https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56473&view=logs&j=3cbe1e9e-37dd-5d57-923f-2a18a6d81786&t=0a2b014d-9e02-5b85-0f63-5d8fe7679ef1&l=154

There's nothing that immediately stands out to me. It seems that chromedriver keeps restarting (see the repeated startup logs and changing PIDs) but there's nothing from Chrome. In the end, without any explicit error from either Chrome or chromedriver, wptrunner eventually fails due to `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`. @stephenmcgruer I'm using `chromedriver.exe -port=50206 -url-base=/ -enable-chrome-logs --verbose --disable-build-check`; is that the right way to ask for Chrome logs?

**Comment by stephenmcgruer** [comment]
@Hexcles - did you typo there with `-enable-chrome-logs`? It should be `--enable-chrome-logs` (two `-` at the front), but probably you just typo'd in the GitHub comment)

**Comment by Hexcles** [comment]
This is from
https://github.com/web-platform-tests/wpt/blob/080385a6d06fe04feaf857ccc6e29b97f9caee24/tools/wptrunner/wptrunner/webdriver_server.py#L135

`cmd_arg` produces `-` on Windows, which seems to work at least for the other flags.

**Comment by stephenmcgruer** [comment]
Ah, I see. That should be fine.

Looking at the logs, it certainly is passing the right flag to chrome, so that's annoying that it just goes away without any output. You could maybe poke around at some other places to see if there are logs, see https://docs.google.com/document/d/1DsvGXPri3exlQupj3d5IbOvI1tzIw2ePWbePDZVp1Cc/edit#

I can also try to reproduce the failing tests on my Windows machine, given a bit of time to get things running first :D

**Comment by Hexcles** [comment]
Oh so headless seems to have different behaviours? Let me try `--enable-logging=stderr`.

**Comment by stephenmcgruer** [comment]
Oh, we're running in headless? Yes, that's problematic on Windows; you will likely need to check the log file. See the 'Headless Chrome' section.

**Review by stephenmcgruer — APPROVED** [review]
Thank you for your diligent work in burning this set of issues down!

**Pull request merged**
