### PR TITLE
Added 4 selection tests on text-shadow with 3 references

### PR DESCRIPTION
**Pull request by TalbotG**

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
selection-text-shadow-*

These can all be collapsed to one test. We don't need a separate test for each possible offset! If you're concerned about errors in paint invalidation, place offsets in all four directions. Also, I think an 0.5em offset should be sufficient here: multiple copies of the text is a bit confusing.

Lastly, I suggest using the text “Selected Text” instead of “Sample Text”, since it's a little more helpful to the tester. :)

**Comment by TalbotG** [comment]
> selection-text-shadow-*
> 
> These can all be collapsed to one test. 


http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-text-shadow-015.html
does all 4 directions

> We don't need a separate test for each possible offset! 

Chromium 78 (stable version) and Chromium 81 (latest build) "struggle" with selection-text-shadow-014.html
Try this:
Double-click each word or triple-click or mousedrag the blue words in 
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-text-shadow-014.html
and the red text shadow will not disappear. Though, the failures are erratic, not easy to reproduce consistently ...

> If you're concerned about errors in paint invalidation, 
> place offsets in all four directions. Also, I think an 0.5em 
> offset should be sufficient here: multiple copies of the 
> text is a bit confusing.

If the test as designed is passed, then there is only 1 "Text sample" readable, viewable and it must be green.

I will use a 0.5em offset for each direction in
selection-text-shadow-015 .

I will remove 
selection-text-shadow-011
selection-text-shadow-012
selection-text-shadow-013
selection-text-shadow-014 .

> Lastly, I suggest using the text “Selected Text” instead of “Sample Text”, since it's a little more helpful to the tester. :)

I will replace "Sample text" with "Selected Text".

**Comment by TalbotG** [comment]
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-text-shadow-015-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-text-shadow-015-new-ref.html

I will create another Pull Request and remove the "-new" from filenames.

**Comment by TalbotG** [comment]
I am closing this pull request and invite you in #20802
which addresses your feedback in this PR ... My weak current github "skills" prevent me from doing this in here... :(

**Pull request closed without merging**
