### PR TITLE
Make the normalized wptserve config a class

### PR DESCRIPTION
**Pull request by gsnedders**
This should make it easier once we have static typing to make sure we don't end up with non-normalized configs anywhere. This is essentially a subset of #10166, so this can land faster. (Though hopefully that'll land soon too.)

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10231)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-29 04:40:35
Finished: 2018-03-29 04:54:05


<h2>Failing Jobs</h2>
<ul>

<li>tools_unittest in py27</li>

<li>tools_unittest in py36</li>

<li>tools_unittest in pypy</li>

<li>wptrunner_infrastructure</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26607)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/359683717)

**Comment by jgraham** [comment]
Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[tools/serve/config.py, line 14 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LCIAQ4SScadj5nsRF:-L9LCIAQ4SScadj5nsRG:b-wmjrdx) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L14)):*
> ```Python
> 
> 
> with open(os.path.join(repo_root, "config.default.json"), "rb") as _fp:
> ```

I'm not thrilled by having this IO at the top level. Put it on the class and cache the result.

---

*[tools/serve/config.py, line 41 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LC0Mz-PN4CHmyyvvr:-L9LC0N-3zbQ5h5gicpY:b-cubwn3) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L41)):*
> ```Python
> 
>     def __init__(self, logger=None, **kwargs):
>         if logger is None:
> ```

I don't think a config class should eb setting up logging.

---

*[tools/serve/config.py, line 65 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LC_2i1VJ8S3C2rDfW:-L9LC_2i1VJ8S3C2rDfX:bncqun3) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L65)):*
> ```Python
>         if kwargs:
>             k = next(iter(kwargs))
>             raise TypeError("__init__() got an unexpected keyword argument '%s'" % k)
> ```

I would provide the full list of unexpected arguments (i.e. `kwargs.keys()` even though it's less like the built in message.

---

*[tools/serve/config.py, line 74 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LCpcA7P-AStd-f0xg:-L9LCpcA7P-AStd-f0xh:b-87w2km) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L74)):*
> ```Python
> 
>     def __iter__(self):
>         return iter([x for x in dir(self) if not x.startswith("_")])
> ```

Isn't this also going to return `logger`? It seems pretty fragile. One option would be to reverse the setup  so the config is still stored in a dict and we override the attribute getters and setters to use that dict if nothing is present on the class.

---

*[tools/serve/config.py, line 79 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LDefq4VO8MWF8AVKJ:-L9LDefrEyrCsGL4nZXT:b7qtl15) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L79)):*
> ```Python
>         return len([x for x in dir(self) if not x.startswith("_")])
> 
>     def load_overrides(self, override):
> ```

This could be called `update`

---

*[tools/serve/config.py, line 116 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LEJKG2sLonDTXGpV4:-L9LEJKH7Qa1VzUfilQ9:bnji4k4) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L116)):*
> ```Python
>                     port = None
>                 if port == "auto":
>                     port = serve.get_port()
> ```

Is this actually giving a consistent answer back if it's called multiple times?

---

*[tools/serve/config.py, line 156 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGRL3BHOuhZT1ZMLk:-L9LGRL4B64KK6WSEBL2:blefo0h) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L156)):*
> ```Python
>     def domains(self):
>         domains = {k: ".".join(v)
>                    for k, v in serve.get_subdomains(self.browser_host).iteritems()}
> ```

I wonder whehter it makes sense to make these functions part of the config object.

---

*[tools/serve/config.py, line 173 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGa3k-LIRp8nyyEna:-L9LGa3l-JLAI4cGEV-J:bbi5m93) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L173)):*
> ```Python
> 
>     @property
>     def domains_set(self):
> ```

I don't love having a separate property just to perform a type conversion.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
I'm increasingly convinced that this actually belongs in `wptserve` and not in `serve`? `wptserve` relies on the config, so it should probably live there rather than in `serve`.

However, we currently have a few things that rely on serve:

* `serve.get_subdomains` (and `get_not_subdomains`), but these are easily moved to config.py and made private (there's no need for them to be public, I don't think?)
* `serve.get_port`, which is used both by the config to return the generated ports and by `serve` when checking the hosts are set up and when starting the stash server. The latter of these could potentially be moved into the config as a default "auto" port, but that still leaves the former?

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[tools/serve/config.py, line 41 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LC0Mz-PN4CHmyyvvr:-L9U_XZe50Yy6HHYJ1BK:b-upbfvf) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L41)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I don't think a config class should eb setting up logging.
</blockquote></details>

So where should we get the logger from before running `__init__`, given it depends on configuration options (`log_level`) and we want to log if you use a deprecated config option?

---

*[tools/serve/config.py, line 116 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LEJKG2sLonDTXGpV4:-L9UhSiHDdkV7gJqcVXZ:bwy8r5o) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L116)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Is this actually giving a consistent answer back if it's called multiple times?
</blockquote></details>

No. 🙁

---

*[tools/serve/config.py, line 156 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGRL3BHOuhZT1ZMLk:-L9UhXRT4NRw1lEfN-Uo:b-47q5d8) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L156)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I wonder whehter it makes sense to make these functions part of the config object.
</blockquote></details>

IMO, yes. Where else does it make sense to put them?

---

*[tools/serve/config.py, line 173 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGa3k-LIRp8nyyEna:-L9Uhdhg1y18GxHSYM7V:b-7co7a7) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L173)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I don't love having a separate property just to perform a type conversion.
</blockquote></details>

To be fair, they originally made more sense on the `alternate-hosts` branch, but I think now don't? So yeah, should probably go.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-:-L9UhqBRB_tsUr3DpQIi:b-27bt00)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[tools/serve/config.py, line 41 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LC0Mz-PN4CHmyyvvr:-L9aWicE6TV8dfbrl_P-:b-t9oegi) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L41)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

So where should we get the logger from before running `__init__`, given it depends on configuration options (`log_level`) and we want to log if you use a deprecated config option?
</blockquote></details>

OK, I guess. It still seems weird for something that looks like a pure view of data to set up logging, but I guess that makes sense.

---

*[tools/serve/config.py, line 156 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGRL3BHOuhZT1ZMLk:-L9aWuczBXWZgOWNsoKe:bcpj1mz) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L156)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

IMO, yes. Where else does it make sense to put them?
</blockquote></details>

I mean `serve.get_subdomains` &c. Although I'm not sure what actually works well here; as you say this class feels like it belongs in wptserve. Possibly they should be passed in since presumably they get passed to the server as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[tools/serve/config.py, line 42 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9dW5qj2X6xbfVNEe3Z:-L9dW5qj2X6xbfVNEe3_:b-n7cok1) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L42)):*
> ```Python
>     def __init__(self, logger=None, **kwargs):
>         if logger is None:
>             logger = logging.getLogger("web-platform-tests")
> ```

@jgraham You mentioned on IRC you didn't like this, though I justified why. I think there's three other options: one is we make every warning into a (fatal) exception with no logger, another is we make everything into a Python warning (which IMO makes little sense), and the final is to just silently ignore the warning. I think I'm happy with the first or last? It does mean that usage of the Config class will need to create their own Logger, reading the object themself.

---

*[tools/serve/config.py, line 116 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LEJKG2sLonDTXGpV4:-L9dX1hc4BBKGBqahv6W:bx567d) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L116)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

No. 🙁
</blockquote></details>

Also moving the class to `wptserve` means we add a dependency to `serve` for `get_port`, or perhaps more sensibly move all of the get_port stuff to somewhere in wptserve (where, though?).

---

*[tools/serve/config.py, line 156 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGRL3BHOuhZT1ZMLk:-L9dXisxCPFvmumlig1R:b-flkl36) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L156)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I mean `serve.get_subdomains` &c. Although I'm not sure what actually works well here; as you say this class feels like it belongs in wptserve. Possibly they should be passed in since presumably they get passed to the server as well.
</blockquote></details>

I'm unconvinced by things that are essentially "get this computed config value", which `get_subdomains` is. My feeling is we have a `subdomains` and `not_subdomains` config option that `serve` sets for us (though nothing actually ever reads it; everything always just reads `domains`, but that's not unique—there's other places where the computed value is always the one used).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Review status: 3 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[tools/wptserve/tests/test_config.py, line 26 at r3](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9dw8qcBF4LfggYw9Ob:-L9dw8qcBF4LfggYw9Oc:b-edlqsd) ([raw file](https://github.com/w3c/web-platform-tests/blob/ce02f621b1ba703971a29e9df61a3a9410d25331/tools/wptserve/tests/test_config.py#L26)):*
> ```Python
>     ({"a": {"b": 1}}, {"a": {"b": 2, "c": 3}}, {"a": {"b": 2}}),
>     pytest.param({"a": {"b": 1}}, {"a": 2}, {"a": 1}, marks=pytest.mark.xfail),
>     pytest.param({"a": 1}, {"a": {"b": 2}}, {"a": 1}, marks=pytest.mark.xfail),
> ```

FYI: these xfails already exist on `master`, we just don't have tests for it before.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Now in `wptserve`.

---

Review status: 3 of 9 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[tools/serve/serve.py, line 380 at r3](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9eFHX43hCRLvJGkPhi:-L9eFHX43hCRLvJGkPhj:b-tcanun) ([raw file](https://github.com/w3c/web-platform-tests/blob/95992cd324d80acc68707b203be8c6cc2aebc6d5/tools/serve/serve.py#L380)):*
> ```Python
>         if not bad_port(port):
>             break
>     logger.debug("Going to use port %s" % port)
> ```

Note moving this to wptserve has lost this logging (because wptserve.utils doesn't have a global logger). We should probably move this elsewhere and give a better message in general (as to what we're going to use the port for!).

---

*[tools/serve/config.py, line 74 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LCpcA7P-AStd-f0xg:-L9eF_NT2eABRcRfg78l:b-a087rk) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L74)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Isn't this also going to return `logger`? It seems pretty fragile. One option would be to reverse the setup  so the config is still stored in a dict and we override the attribute getters and setters to use that dict if nothing is present on the class.
</blockquote></details>

If we want to view `logger` as a config item (given it's used by various things), then surely it should be present here.

---

*[tools/serve/config.py, line 79 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LDefq4VO8MWF8AVKJ:-L9eFkvLD3RxapB9IIEy:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L79)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

This could be called `update`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-:-L9eErUQ0eqhZeowZgoX:b-cekskq)*

**Comment by jgraham** [comment]
Reviewed 4 of 10 files at r3, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[tools/serve/serve.py, line 581 at r4](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9eIESX5g-54Cg8TCA_:-L9eIESX5g-54Cg8TCAa:bf4r0p9) ([raw file](https://github.com/w3c/web-platform-tests/blob/951ade940eacfdad4de7530058690a10637a277d/tools/serve/serve.py#L581)):*
> ```Python
> _not_subdomains = {u"nonexistent-origin"}
> 
> def set_serve_config(config):
> ```

Why don't we just pass these in through the constructor?

---

*[tools/serve/config.py, line 156 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LGRL3BHOuhZT1ZMLk:-L9eI0Pe8d3njqvnwRxm:b-oic749) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L156)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

I'm unconvinced by things that are essentially "get this computed config value", which `get_subdomains` is. My feeling is we have a `subdomains` and `not_subdomains` config option that `serve` sets for us (though nothing actually ever reads it; everything always just reads `domains`, but that's not unique—there's other places where the computed value is always the one used).
</blockquote></details>

This is fine now subdomains are stored on this object.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[tools/serve/serve.py, line 581 at r4](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9eIESX5g-54Cg8TCA_:-L9eL9hn0wmnNdIi34xT:b-ttc3n3) ([raw file](https://github.com/w3c/web-platform-tests/blob/951ade940eacfdad4de7530058690a10637a277d/tools/serve/serve.py#L581)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Why don't we just pass these in through the constructor?
</blockquote></details>

Because we also construct it in `wptrunner.environment.TestEnvironment.load_config`; we don't necessarily get the config from `serve.load_config`.

---

*[tools/serve/config.py, line 65 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LC_2i1VJ8S3C2rDfW:-L9eN77N9Pm8v3yPH1OC:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L65)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I would provide the full list of unexpected arguments (i.e. `kwargs.keys()` even though it's less like the built in message.
</blockquote></details>

Done.

---

*[tools/serve/config.py, line 116 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LEJKG2sLonDTXGpV4:-L9eJklh1vTln-ya2E1Z:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L116)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Also moving the class to `wptserve` means we add a dependency to `serve` for `get_port`, or perhaps more sensibly move all of the get_port stuff to somewhere in wptserve (where, though?).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Review status: 7 of 9 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[tools/serve/config.py, line 14 at r2](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9LCIAQ4SScadj5nsRF:-L9eNiNQ8aj5vZZexN4Z:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/47c97a405921a671c3ca6ce73818f3a8b5bd8b25/tools/serve/config.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I'm not thrilled by having this IO at the top level. Put it on the class and cache the result.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by gsnedders** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[tools/serve/serve.py, line 581 at r4](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231#-L9eIESX5g-54Cg8TCA_:-L9ees8BCQvuUkCRIgRH:bn2oejb) ([raw file](https://github.com/w3c/web-platform-tests/blob/951ade940eacfdad4de7530058690a10637a277d/tools/serve/serve.py#L581)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Because we also construct it in `wptrunner.environment.TestEnvironment.load_config`; we don't necessarily get the config from `serve.load_config`.
</blockquote></details>

Done. Moved everything to use `serve.Config` which is a subclass of `wptserve.config.Config` which sets all the `serve` config correctly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Comment by jgraham** [comment]
Reviewed 4 of 6 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/w3c/web-platform-tests/10231)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
