### PR TITLE
Add new tests and remove obsolete ones as per PR13499

### PR DESCRIPTION
**Pull request by youennf**
This PR takes changes from PR #13499 and regroup the newly added files and removed files.

### CODE REVIEW

**Comment by youennf** [comment]
PR not ready to be merged.
This PR probably requires #14417 and #14418 to be merged first.
This PR probably also needs to remove the files that would not easily run in browser CI

**Comment by alvestrand** [comment]
Not ready to merge yet, says @youennf

**Comment by youennf** [comment]
PR for RTCDataChannel-binaryType.html tests uploaded at https://github.com/web-platform-tests/wpt/pull/16043

**Comment by youennf** [comment]
PR for RTCSctpTransport-onstatechange.html test uploaded at https://github.com/web-platform-tests/wpt/pull/16044

**Comment by youennf** [comment]
Last test of RTCPeerConnection-close.html is probably redundant with RTCSctpTransport-events.html (once RTCSctpTransport-events.html is removing the last commented check).

**Comment by youennf** [comment]
Other RTCPeerConnection-close.html tests uploaded as a separate PR in https://github.com/web-platform-tests/wpt/pull/16045

**Comment by alvestrand** [comment]
Supplanted by single-file test submissions.

**Pull request closed without merging**
