### PR TITLE
Remove erroneous return from "setRemoteDescription(offer) with invalid SDP..."

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Review by bobholt — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239683039)

# Firefox (nightly) #
Testing web-platform-tests at revision dd5bed1036d10a44e8bc14cde97565418615b295
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
## Unstable results ##


|                          Test                         |                                        Subtest                                         |          Results           |                                                                                                              Messages                                                                                                             |
|-------------------------------------------------------|----------------------------------------------------------------------------------------|----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `/webrtc/RTCPeerConnection-setRemoteDescription.html` | `setRemoteDescription(offer) should never resolve if connection is closed in parallel` | **FAIL: 9/10, PASS: 1/10** | `assert_unreached: Pending promise should never be resolved. Instead it is rejected with: InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel. Reached unreachable code` |

## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6152/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                                                 Subtest                                                                  |          Results           |                                                                                                              Messages                                                                                                             |
|------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                          | TIMEOUT                    |                                                                                                                                                                                                                                   |
| `setRemoteDescription with valid offer should succeed`                                                                                   | FAIL                       | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Setting remote description multiple times with different offer should succeed`                                                          | FAIL                       | `promise_test: Unhandled rejection with value: object "InvalidStateError: Cannot set remote offer or answer in current state have-remote-offer"`                                                                                  |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                                                   | **FAIL: 9/10, PASS: 1/10** | `assert_unreached: Pending promise should never be resolved. Instead it is rejected with: InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel. Reached unreachable code` |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                                                               | FAIL                       | `assert_equals: Expect error detail field to set to sdp-syntax-error expected (string) "sdp-syntax-error" but got (undefined) undefined`                                                                                          |
| `setRemoteDescription with invalid type and invalid SDP should reject with TypeError`                                                    | PASS                       |                                                                                                                                                                                                                                   |
| `setRemoteDescription() with invalid SDP and stable state should reject with InvalidStateError`                                          | PASS                       |                                                                                                                                                                                                                                   |
| `setRemoteDescription() with valid state and answer should succeed`                                                                      | FAIL                       | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed`                                       | FAIL                       | `promise_test: Unhandled rejection with value: object "InvalidSessionDescriptionError: Remote description changes the media type of m-line 0"`                                                                                    |
| `Switching role from offerer to answerer after going back to stable state should succeed`                                                | FAIL                       | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`                                            | FAIL                       | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError`                                   | FAIL                       | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError`                                 | FAIL                       | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `setRemoteDescription should trigger ontrack event when the MSID of the stream is is parsed.`                                            | FAIL                       | `assert_own_property: Expect pc to have ontrack event handler attribute expected property "ontrack" missing`                                                                                                                      |
| `Test onsignalingstatechange event for setRemoteDescription with valid offer should succeed`                                             | PASS                       |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Setting remote description multiple times with different offer should succeed`                    | PASS                       |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for setRemoteDescription() with valid state and answer should succeed`                                | PASS                       |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed` | TIMEOUT                    | `Test timed out`                                                                                                                                                                                                                  |
| `Test onsignalingstatechange event for Switching role from offerer to answerer after going back to stable state should succeed`          | PASS                       |                                                                                                                                                                                                                                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239683040)

# Sauce (safari) #
Testing web-platform-tests at revision dd5bed1036d10a44e8bc14cde97565418615b295
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6152/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                                 Subtest                                                  | Results |                 Messages                 |
|----------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                          | OK      |                                          |
| `setRemoteDescription with valid offer should succeed`                                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Setting remote description multiple times with different offer should succeed`                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription with invalid type and invalid SDP should reject with TypeError`                    | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription() with invalid SDP and stable state should reject with InvalidStateError`          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription() with valid state and answer should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed`       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Switching role from offerer to answerer after going back to stable state should succeed`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError`   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription should trigger ontrack event when the MSID of the stream is is parsed.`            | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239683046)

# Chrome (unstable) #
Testing web-platform-tests at revision dd5bed1036d10a44e8bc14cde97565418615b295
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6152/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                                                 Subtest                                                                  | Results |                                                                                                                         Messages                                                                                                                        |
|------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                          | OK      |                                                                                                                                                                                                                                                         |
| `setRemoteDescription with valid offer should succeed`                                                                                   | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                         |
| `Setting remote description multiple times with different offer should succeed`                                                          | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                         |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                                                   | PASS    |                                                                                                                                                                                                                                                         |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                                                               | FAIL    | `assert_equals: Expect error detail field to set to sdp-syntax-error expected (string) "sdp-syntax-error" but got (undefined) undefined`                                                                                                                |
| `setRemoteDescription with invalid type and invalid SDP should reject with TypeError`                                                    | PASS    |                                                                                                                                                                                                                                                         |
| `setRemoteDescription() with invalid SDP and stable state should reject with InvalidStateError`                                          | FAIL    | `assert_throws: function "function () { throw e }" threw object "OperationError: Failed to parse SessionDescription. invalid Expect line: v=" that is not a DOMException InvalidStateError: property "code" is equal to 0, expected 11`                 |
| `setRemoteDescription() with valid state and answer should succeed`                                                                      | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                         |
| `Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed`                                       | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                         |
| `Switching role from offerer to answerer after going back to stable state should succeed`                                                | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                         |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`                                            | FAIL    | `assert_throws: function "function () { throw e }" threw object "OperationError: Failed to set remote answer sdp: Called in wrong state: STATE_INIT" that is not a DOMException InvalidStateError: property "code" is equal to 0, expected 11`          |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError`                                   | FAIL    | `assert_throws: function "function () { throw e }" threw object "OperationError: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER" that is not a DOMException InvalidStateError: property "code" is equal to 0, expected 11`      |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError`                                 | FAIL    | `assert_throws: function "function () { throw e }" threw object "OperationError: Failed to set remote answer sdp: Called in wrong state: STATE_RECEIVEDOFFER" that is not a DOMException InvalidStateError: property "code" is equal to 0, expected 11` |
| `setRemoteDescription should trigger ontrack event when the MSID of the stream is is parsed.`                                            | FAIL    | `assert_own_property: Expect pc to have ontrack event handler attribute expected property "ontrack" missing`                                                                                                                                            |
| `Test onsignalingstatechange event for setRemoteDescription with valid offer should succeed`                                             | PASS    |                                                                                                                                                                                                                                                         |
| `Test onsignalingstatechange event for Setting remote description multiple times with different offer should succeed`                    | PASS    |                                                                                                                                                                                                                                                         |
| `Test onsignalingstatechange event for setRemoteDescription() with valid state and answer should succeed`                                | PASS    |                                                                                                                                                                                                                                                         |
| `Test onsignalingstatechange event for Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed` | PASS    |                                                                                                                                                                                                                                                         |
| `Test onsignalingstatechange event for Switching role from offerer to answerer after going back to stable state should succeed`          | PASS    |                                                                                                                                                                                                                                                         |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239683047)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision dd5bed1036d10a44e8bc14cde97565418615b295
Using browser at version 14.14393
Starting 10 test iterations

**Pull request merged**
