### PR TITLE
Replace tabs with spaces in html/editing/dnd/

### PR DESCRIPTION
**Pull request by foolip**
In every *.html, *.svg and *.xhtml file, each tab is replaced with two spaces, as this is the indentation that was most used in these test.

After replacing tabs with spaces, some odd indentation remains. Mostly found by reindenting in Emacs web-mode and looking at the differences. Most were ignored, but some are actual mistakes.

### CODE REVIEW

**Comment by foolip** [comment]
Split into two commits for easier reviewing, the first is produced by simple replacement and the second contains the fixups. It's fine to squash when merging though, nobody will care after the fact.

**Comment by foolip** [comment]
I did this so that moving https://github.com/w3c/web-platform-tests/tree/master/old-tests/submission/Microsoft/dragdrop would require fixing any lint errors as well.

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-10-10 19:50:29
Finished: 2017-10-10 20:01:58


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19294)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/286192128)

**Comment by foolip** [comment]
I've filed https://github.com/w3c/web-platform-tests/issues/7660 for the Travis problem and will merge this manually if approved. @gsnedders, can you review?

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
