### PR TITLE
Add tests for PaymentRequest.shippingOption attr

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18126)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/271553950)

**Review by edenchuang — CHANGES_REQUESTED** [review]
Because the fix on the spec https://github.com/w3c/payment-request/pull/610 is approved, I think we need to modify this test to consider the effect of options.requestShipping.

**Comment by marcoscaceres** [comment]
> Because the fix on the spec w3c/payment-request#610 is approved, I think we need to modify this test to consider the effect of options.requestShipping.

Agree. On it!

**Review by edenchuang — CHANGES_REQUESTED** [review]
We should add a test for the case that one shippingOption is set selected as true, but options.requestShipping is false.

**Review by edenchuang — APPROVED** [review]
Have the case in the ctor test, approve this PR.

**Pull request merged**
