### PR TITLE
Sort stability test results according to test name

### LINKED ISSUE #4515: wpt-stability-bot: report results in test order rather than Python (unordered) dict order
That would make it easier to scan the results. Especially for generated tests that have some kind of sequence.

### PR DESCRIPTION
**Pull request by jugglinmike**
This should resolve gh-4515

### CODE REVIEW

**Comment by gsnedders** [comment]
That's still test name rather than test-order (i.e., order the test objects are created by the test function being called).

Also it's unstable, you could really do with reverting that last commit. :P

**Comment by domenic** [comment]
This isn't quite what you want. You want the original *test* order, as written, not lexicographic order. Shuffling them around lexicographically isn't much better than shuffling them around randomly, IMO.

**Comment by jgraham** [comment]
Right, if you want sorted output you'll need to change wptrunner not to use an object to communicate subtest results, but a list of lists, or similar.

**Comment by jugglinmike** [comment]
Thanks for the feedback, all. Looks like my understanding of the problem was a bit naive. A true solution won't have much in common with this approach, so I'll close this pull request.

**Comment by gsnedders** [comment]
@jgraham I think `OrderedDict` would be better than lists.

**Pull request closed without merging**
