### PR TITLE
Sop

### PR DESCRIPTION
**Pull request by Immortalem**
Added the test cases from your-sop.com

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Chrome Dev"<small> (failures allowed)</small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/25367.12">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/349824918">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  <tr>
    <td><code>/sop/TRACK.sub.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>TRACK - cross-origin read</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>TRACK - same-origin read</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>TRACK - same-origin write</code></td>
    <td>PASS: 2<br />FAIL: 8<br /></td>
    <td><code>assert_equals: expected "object" but got "undefined"</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  </table>

**Comment by annevk** [comment]
Thanks for submitting these tests! And sorry for taking so long to get back to you.

It seems like these tests are generated, is that the case? In that case it might be more beneficial to commit the script that generates these so it's easier to fix things up.

There's also a lot of code duplication making this hard to review.

When I run these in nightly builds of browsers there's also a couple of timeouts here and there. Are there bugs for those on file?

I think we also don't want to put these in a top-level sop/ directory, given how web-platform-tests is structured. If they're all related to fetching we could potentially put them in fetch/same-origin-policy/, but otherwise I'd just put them in the respective HTML directories.

**Comment by Immortalem** [comment]
You're right spot of the code was generated with a python script. But that's only for the boiler plate code. The code for the specific behavior (assertions or using onload vs. not doing so) were fixed up manually. 

But obviously it wouldn't be a problem to also submit the file used to generate some of the code.

Honestly I didn't test it on the nightly builds. I'll do that tomorrow when I got time. But if there are timeouts it could be due to the resources not being loaded.

And I'm not quite sure regarding the placement. I don't think fetch is the right place either since the test cases do not test if the resources are loaded but which privileges are obtained when loading them.

Well in some way that might even relate to fetch. So yeah I'm not entirely sure where to put them.

**Comment by zcorpan** [comment]
Should these be somewhere under `html/` instead? Should this set of tests have its own `OWNERS` file?

**Comment by annevk** [comment]
Yeah, I think we should put them in `html/` somewhere given the features it's testing.

**Comment by Immortalem** [comment]
Ok, so I ran the test cases in  Chrome Version 68.0.3406.0 (Official Build) canary (64-bit) [Windows] but there weren't any timeouts. Which version did you use annevk, and how did you run the test cases ? 

It seems the general census is to move the test cases to their respective HTML elements. I totally agree with that. A question that still persists is how I should handle the python resources I created and need. Should I place them somewhere central or have them multiple times, once for every HTML element.

Another question is: While the test cases are specific in some parts I think it should be possible to remove some boiler plate code by generating the test cases with python. That said there won't be a mapping of one file HTML (currently) to one file python (then). It would be more like 2-3 files. But that shouldn't be  a problem, since it after all reduces the boiler plate code. There might be even a solution with a one to one mapping I'd have to look into it.
Anyway, getting to the point, shall I commit the current version into the respective HTML directories and rework the code afterwards or should I rework the code first and commit then ? 

Kind Regards
Mario

**Comment by annevk** [comment]
Chrome 68.0.3406.0 (with experimental features enabled) on macOS (latest stable). I get timeouts on CANVAS_png.sub.html, CANVAS_svg.sub.html, IFRAME_html_sandbox.sub.html (a harness timeout, no test timeout), and LINK.sub.html.

You should feel free to put the common files for these tests in https://github.com/w3c/web-platform-tests/tree/master/html/resources.

**Comment by annevk** [comment]
> Anyway, getting to the point, shall I commit the current version into the respective HTML directories and rework the code afterwards or should I rework the code first and commit then ?

That's really up to you I think. I'd like to start reviewing again once all is in order though, but happy to assist with further questions.

**Comment by Immortalem** [comment]
Due to several reasons I'm currently running a bit short on time. Never the less, I'm trying to slowly change to code and move it to where it belongs. I looked in html/ and now I'm not quite sure how exactly I should place the test cases inside.

I couldn't find any specific folders like CANVAS or IMG. Therefore I was wondering if I should I place them in html/sop/ or in html/dom/sop ? (Testing the DOM-SOP).

Kind Regards
Mario

**Comment by annevk** [comment]
You'll find directories for the elements you're looking for in `html/semantics/embedded-content/`.

**Comment by Immortalem** [comment]
closed since repository was too old. Will open a new PR soon

**Pull request closed without merging**
