### PR TITLE
Update wptserve dependency for mod_pywebsocket and bump version to 4.0.1

### LINKED ISSUE #35978: New release of `wptserve` on PyPI
The latest version of `wptserve v3.0.0` on PyPI [1] is pinned on `h2 v3.0.1` https://github.com/web-platform-tests/wpt/pull/22412, which is not compatible with Python 3.10, it would be great if a new release of `wptserve` is made.

It is required for `mozdownload` to support Python 3.10 https://github.com/mozilla/mozdownload/pull/623. 

Here is the link to the failing test. [2]

[1] - https://pypi.org/project/wptserve/3.0/
[2] - https://github.com/mozilla/mozdownload/actions/runs/3049402854/jobs/4915434407

### PR DESCRIPTION
**Pull request by whimboo**
Closes #35978.

Follow-up from #42910 which had a missing dependency for mod_pywebsocket.

### CODE REVIEW

**Comment by whimboo** [comment]
Given that we have to download the package from GitHub via HTTPS I've also added the sha256 checksum to the download link.

@jgraham can you please review?

**Comment by jgraham** [comment]
```
./wptserve/setup.py:6:142: E501 line too long (198 > 141 characters)
```

**Comment by whimboo** [comment]
> ```
> ./wptserve/setup.py:6:142: E501 line too long (198 > 141 characters)
> ```

The problem here is the long line for the mod_pywebsocket dependency. I've added `# noqa` now, so lets if that is enough.

**Comment by whimboo** [comment]
It's all fine now and I've also successfully updated the mozdownload tests, and I can confirm that everything works fine now. @jgraham please re-review. Thanks.

**Comment by whimboo** [comment]
I actually missed to check if the mod_pywebsocket version that we have in wpt is actually the latest version on the GitHub repository. @jgraham created #42964 which should be merged first.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
