### PR TITLE
Update interfaces/css-typed-om.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/398ec92/whatwg/idl/css-typed-om.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/423853333

### CODE REVIEW

**Comment by foolip** [comment]
This change is from https://github.com/w3c/css-houdini-drafts/commit/5261c1a323ea062d69cb5a3f1e69734fd176948a. @tabatkins, is it still on some other level? It's still in https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/cssom/css_position_value.idl, FWIW.

**Comment by tabatkins** [comment]
No, it's been removed from this level due to it being known to be inconsistent with already-specced upgrades to `<position>` values (to accommodate logical directions). The design assumed that the position could always be expressed in physical coordinates, which absolutely isn't true for specified values, and isn't necessarily true even for computed values.

I need to remove it from some other places that still reference it, but it won't return until we fix the object's shape.

**Comment by foolip** [comment]
@tabatkins, can you file bugs for unshipping the interface in Chrome and removing tests for it here in WPT?

**Comment by tabatkins** [comment]
yeah

**Review by foolip — APPROVED** [review]

**Pull request merged**
