### PR TITLE
Fetch/XHR: test parsing of WWW-Authenticate response header

### PR DESCRIPTION
**Pull request by annevk**
Context: https://bugzilla.mozilla.org/show_bug.cgi?id=1491010.

### CODE REVIEW

**Comment by annevk** [comment]
Curiously Chrome fails the fetch() test in the same manner as Firefox, but passes the XMLHttpRequest tests.

**Comment by jobisoft** [comment]
Have you run this test already? The tests for XHR will probably fail, because XHR returns them "as is"

1\n2\n3,4

**Comment by annevk** [comment]
Yeah, that's a bug in Firefox. Other browsers don't have that problem.

**Comment by annevk** [comment]
There's no standard that supports the behavior you want and I don't think it'd be a good idea to special case headers or pass through the server data as-is (as proxies and such could also have meddled with it).

**Comment by jobisoft** [comment]
Ok, but then you need to get this in the official MDN documentation of XHR as fast as possible, so that coders like me do not rely on the current behaviour. 

I was actually thinking about switching from fetch() to XHR because of the *current* behaviour.

**Review by youennf — APPROVED** [review]

**Pull request merged**
