### PR TITLE
Add css-nav IDL and test

### PR DESCRIPTION
**Pull request by lukebjerring**
Supersedes https://github.com/web-platform-tests/wpt/pull/19289

Let's let the tests inform of implementation status?

### CODE REVIEW

**Comment by lukebjerring** [comment]
No passing tests for implementation.
https://wpt.fyi/results/css/css-nav/idlharness.window.html?sha=a60f6bd8c5&label=pr_head

**Comment by foolip** [comment]
If there's no reaction to https://github.com/web-platform-tests/wpt/pull/19289#issuecomment-535916395 I'd like to leave this open until someone is interested in implementing.

**Comment by foolip** [comment]
See https://github.com/web-platform-tests/wpt/pull/19289#issuecomment-536890306.

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt/pull/19289, we can revive this when there's implementer interest.

**Pull request closed without merging**
