### PR TITLE
Document the .tentative file name flag test feature

### PR DESCRIPTION
**Pull request by foolip**
Discussed in
https://lists.w3.org/Archives/Public/public-test-infra/2017AprJun/thread.html#msg59
and now already in use, with 30 tentative tests currently existing.

### CODE REVIEW

**Comment by foolip** [comment]
@mikewest I think you may be the most active user of tentative tests. Is this documentation accurate?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-10 22:21:10
Finished: 2017-10-10 22:28:58


<h2>Failing Jobs</h2>
<ul>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19304)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/286261263)

**Comment by annevk** [comment]
Can we require such tests to point to a corresponding specification issue?

**Review by Ms2ger — APPROVED** [review]

**Comment by foolip** [comment]
@annevk, I was hoping that "It should be apparent in context why the test is tentative and what needs to be resolved to make it non-tentative" would be enough here. Do you want me to also spell out that a link to an issue is the easiest way of doing that?

I think that if we really wanted to require it, we should have a lint checking for the existence of "https://" somewhere in tentative tests, but I'm pretty sure it would occasionally be annoying. For example, the problem with domxpath/interfaces.tentative.html is that there's no spec, and the comment clearly states so. However, the link isn't to an issue, it's to https://wiki.whatwg.org/wiki/DOM_XPath

**Comment by annevk** [comment]
@foolip mkay, I guess we can revisit if it becomes a problem.

**Comment by foolip** [comment]
Thanks! Merging now so that it can be linked to, happy to keep tweaking as needed.

**Pull request merged**
