### PR TITLE
Update the media-source IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Tested manually, fewer failures now because `changeType` went away.

**Comment by wolenetz** [comment]
LGTM. Thanks! This is much cleaner, solves also crbug 633669 (though many of those ancient failures may have been fixed in interim).

The SourceBuffer.changetype() method is in WICG incubation (see WICG/media-source spec repo's codec-switching branch: https://github.com/WICG/media-source/tree/codec-switching). At what point can/should it be added back to the IDL checks in wpt?

**Comment by foolip** [comment]
@wolenetz, publishing https://github.com/WICG/media-source/tree/codec-switching as a separate spec would be the most straightforward way to get it tested, since we get the IDL files from https://github.com/tidoust/reffy-reports, which is scraped from spec.

If you want some proper test coverage, adding tentative tests for it, and you could do a manual idlharness.js test as well.

**Comment by wolenetz** [comment]
@foolip Thanks - I'd already added some functional tests (not just IDL) for codec-switching. They're in media-source/mediasource-changetype*.html.  I suppose I could add some manual IDL check until the spec goes to a WG beyond incubation, though perhaps such IDL reverification could be added then.

**Comment by foolip** [comment]
It looks like the media-source/mediasource-changetype*.html tests already cover about as much as an idlharness test would. idlharness.js does very shallow testing, helpful in revealing things which aren't implemented and which have no other tests, or small mistakes in IDL bindings, but for this case I think you wouldn't gain much by adding back that coverage ahead of it being included in the main spec.

**Pull request merged**
