### PR TITLE
Add css-align/OWNERS

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@emilio, @javifernandez, this is like https://github.com/w3c/web-platform-tests/pull/9214 except that I went looking for directories in css/ without OWNERS as well. Not a lot of activity here, but both of you showed up.

I won't land anything without an explicit yes, so if you'd rather not be listed here, please say no or nothing :)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-27 16:44:37
Finished: 2018-01-27 16:53:02


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23365)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/334138687)

**Comment by foolip** [comment]
@MatsPalmgren, @dholbert, should I list you?

@javifernandez, should I remove you?

**Comment by dholbert** [comment]
Sure, I'm happy to be listed. (AFAIK this is my first time being listed in OWNERS in this repo, so I'm not sure what this means. :)  Does it mean I might sometimes get asked to review new tests in this directory? That's fine with me.)

**Pull request merged**
