### PR TITLE
streams/piping/pipe-through.js: Tiny grammar fix

### PR DESCRIPTION
**Pull request by ricea**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5396)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5396/)

**Review by tyoshino — APPROVED** [review]
lgtm

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219160997)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 12ac0f4b54f388a3da4a16d5d5df8619949f463d
Using browser at version BuildID 20170405115424; SourceStamp b043233ec04f06768d59dcdfb9e928142280f3cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.dedicatedworker.html">/streams/piping/pipe-through.dedicatedworker.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.html">/streams/piping/pipe-through.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5396/streams/piping/pipe-through.serviceworker.https.html">/streams/piping/pipe-through.serviceworker.https.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Service worker test setup`                                                                            | PASS    |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.sharedworker.html">/streams/piping/pipe-through.sharedworker.html</a></summary>


|                                                Subtest                                                 | Results |             Messages            |
|--------------------------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                                        | OK      |                                 |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `ReadableStream is not defined` |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined` |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `ReadableStream is not defined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `ReadableStream is not defined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `ReadableStream is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219160998)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 12ac0f4b54f388a3da4a16d5d5df8619949f463d
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.dedicatedworker.html">/streams/piping/pipe-through.dedicatedworker.html</a></summary>


|                                                Subtest                                                 | Results |                  Messages                  |
|--------------------------------------------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                                                        | OK      |                                            |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `WritableStream is not defined`            |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined`            |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.html">/streams/piping/pipe-through.html</a></summary>


|                                                Subtest                                                 | Results |                  Messages                  |
|--------------------------------------------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                                                        | OK      |                                            |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `WritableStream is not defined`            |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined`            |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5396/streams/piping/pipe-through.serviceworker.https.html">/streams/piping/pipe-through.serviceworker.https.html</a></summary>


|                                                Subtest                                                 | Results |                  Messages                  |
|--------------------------------------------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                                                        | OK      |                                            |
| `Service worker test setup`                                                                            | PASS    |                                            |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `WritableStream is not defined`            |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined`            |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5396/streams/piping/pipe-through.sharedworker.html">/streams/piping/pipe-through.sharedworker.html</a></summary>


|                                                Subtest                                                 | Results |                  Messages                  |
|--------------------------------------------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                                                        | OK      |                                            |
| `Piping through a duck-typed pass-through transform stream should work`                                | FAIL    | `WritableStream is not defined`            |
| `Piping through a transform errored on the writable end does not cause an unhandled promise rejection` | FAIL    | `WritableStream is not defined`            |
| `pipeThrough generically calls pipeTo with the appropriate args`                                       | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise object`                            | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough can handle calling a pipeTo that returns a non-promise thenable object`                   | FAIL    | `Cannot read property 'call' of undefined` |
| `pipeThrough should mark a real promise from a fake readable as handled`                               | FAIL    | `Cannot read property 'call' of undefined` |

</details>
</details>

**Pull request merged**
