### PR TITLE
[css-logical-properties-1] Add test case margin{-block,-inline}

### PR DESCRIPTION
**Pull request by gsnedders**
Originally posted as https://github.com/w3c/csswg-test/pull/1170 by @axinging on 10 Jan 2017, 07:59 UTC:

> Spec is here: https://drafts.csswg.org/css-logical-props-1/#logical-prop.
> This depends on https://github.com/w3c/csswg-test/pull/1165.
> 
>

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5284/)

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-271509841 by @syncbot on 10 Jan 2017, 07:59 UTC:

> ### Automatic validation checks of commit 651e930 passed.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-271511807 by @syncbot on 10 Jan 2017, 08:11 UTC:

> ### Automatic validation checks of commit 5403438 passed.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-271566745 by @axinging on 10 Jan 2017, 12:47 UTC:

> @rune-opera @cbiesinger, PTAL.
> 
> BTW, it seems Firefox can not get  marginBlockStart with getComputedStyle:
> getComputedStyle(document.getElementById("div_htb")).marginBlockStart ==>return "".
> Sample code is here: https://jsfiddle.net/xuvy4ago/
> 
> Any idea about his?

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-271732824 by @cbiesinger on 10 Jan 2017, 23:36 UTC:

> @dbaron see comment above re Gecko computed style for margin-block-start

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-271739080 by @dbaron on 11 Jan 2017, 00:13 UTC:

> We [deferred implementing it until later](https://bugzilla.mozilla.org/show_bug.cgi?id=649142#c31) and [still haven't fixed the followup bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1116638).  But it's not clear that we *should* implement it unless there's a clear spec for it.  For example, https://github.com/w3c/csswg-drafts/issues/384 is currently open, and would lead to significantly different behavior depending on the response.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-272111002 by @mrego on 12 Jan 2017, 09:07 UTC:

> Actually w3c/csswg-drafts#384 is closed and the spec has been updated:
> https://drafts.csswg.org/cssom/#resolved-value
> 
> According to it "*the resolved value is the used value*" like for the other properties.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1170#issuecomment-272261749 by @cbiesinger on 12 Jan 2017, 19:42 UTC:

> OK -- based on that:
> @axinging, can you add tests for percentages that make sure that a) they're resolved against the right axis and b) that the computed style has the resolved value, not the used value?

**Comment by foolip** [comment]
@gsnedders can you rebase and get this passing, or close if no longer relevant?

**Comment by gsnedders** [comment]
@foolip Still relevant.

**Comment by gsnedders** [comment]
With apologies to @axinging that we never reviewed this, according to @Loirooriol:

> It seems your PR is about flow-relative margin longhands, which should now be covered by https://github.com/web-platform-tests/wpt/pull/11324

**Comment by mrego** [comment]
Yes these are covered with more cases by #11324, also the script they rely on `style-check.js` is not around anymore (see #11196).

In any case the change here in `css/css-logical/logicalprops-quirklength.html` still seems interesting. Could we modify these commits somehow to get only that? (I'm not sure if that's possible without @axinging intervetion, and I'm not sure @axinging is longer working on these topics at this stage).

**Comment by gsnedders** [comment]
@mrego the branch is on this repo (as with all those moved over from csswg-test), but let's split that out into a new PR given it's only a small part of this.

**Pull request closed without merging**
