### PR TITLE
rename file, as tests are https only

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241067775)

# Firefox (nightly) #
Testing web-platform-tests at revision 840f53171489bafafe1129cb697f411a66ba3ab9
Using browser at version BuildID 20170608100220; SourceStamp 7efda263a842e60cd0cc00b3c4a7058c65590702
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241067776)

# Sauce (safari) #
Testing web-platform-tests at revision 840f53171489bafafe1129cb697f411a66ba3ab9
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241067782)

# Chrome (unstable) #
Testing web-platform-tests at revision 4a5243164c700174eb4d57931bd2b3d0744620e8
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241067783)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 4a5243164c700174eb4d57931bd2b3d0744620e8

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
