### PR TITLE
Test that console is a namespace

### PR DESCRIPTION
**Pull request by domenic**
Tests for https://github.com/whatwg/console/commit/9a0792da2037f988efc3374bc53ef51e59544d4c.

### CODE REVIEW

**Comment by domenic** [comment]
Passes in Firefox and Safari Tech Preview. Chrome fails the propdesc test, and Edge fails a lot of tests.

We need owners (i.e. reviewers) for this new top-level directory. Here is a list of people who have been involved in various issue threads:

- @terinjokes
- @robertkowalski
- @paulirish
- @pwnall 
- @JosephPecoraro
- @bzbarsky 

Reply if you would like to become a reviewer for console web platform tests, and if so I'll add you to an owners file. Also, as your first act as a reviewer, maybe review these tests :)

**Comment by pwnall** [comment]
I'd like to become a reviwer.

**Comment by pwnall** [comment]
Would you consider making this an .html test, so I can pretend it's a layout test and debug it easily in Chromium? :smile: 

If you're willing to go down that route, here is [an example](https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/idbindex-rename.html), and can you please put the spec URLs in link tags with rel="help"?

**Comment by domenic** [comment]
I'd rather keep it environment-agnostic if possible :). I put the spec links in comments at the top because yeah, with the .any.js setup, there is no good place for that.

You should be able to debug in Chrome with http://w3c-test.org/submissions/3994/console/console-is-a-namespace.any.html though :)

I filed https://monorail-prod.appspot.com/p/chromium/issues/detail?id=656826 BTW.

**Comment by pwnall** [comment]
Thank you for explaining, LGTM.

If you add me to the repository, I can merge your tests.

**Comment by domenic** [comment]
Awesome \o/. Let me ping the repo owners about adding you.

**Comment by zcorpan** [comment]
I've invited @pwnall as a collaborator.

**Comment by pwnall** [comment]
Thank you very much for this opportunity, @domenic and @zcorpan!

**Comment by robertkowalski** [comment]
a bit late -- thanks <3

**Pull request merged**
