### PR TITLE
Deflake ReadableStream piping flow control test

### PR DESCRIPTION
**Pull request by ricea**
Test 'Piping to a WritableStream that does not consume the writes fast
enough exerts backpressure on the ReadableStream' in
streams/piping/flow-control.js is flaky on Chromium
memory sanitizer bots due to its use of timers.

Change to use an interleaved step design. Each step does not start until the
previous one has completed.

Relevant to https://github.com/whatwg/streams/issues/548.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5662)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5662/)

**Comment by ricea** [comment]
I don't know whether this is the clearest way to express the ordering contraints in the test. PTAL.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225212507)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225212513)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 6e82a56166504fb85f1a5017217a7e15d4fac223
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5662/streams/piping/flow-control.dedicatedworker.html">/streams/piping/flow-control.dedicatedworker.html</a></summary>


|                                                                                        Subtest                                                                                         | Results |                Messages               |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                                                                                                                        | OK      |                                       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks`                                                                                             | FAIL    | `ReadableStream is not defined`       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks, but then does`                                                                              | FAIL    | `ReadableStream is not defined`       |
| `Piping from an empty ReadableStream into a WritableStream that does not desire chunks, but then the readable stream becomes non-empty and the writable stream starts desiring chunks` | FAIL    | `ReadableStream is not defined`       |
| `Piping from a ReadableStream to a WritableStream that desires more chunks before finishing with previous ones`                                                                        | FAIL    | `CountQueuingStrategy is not defined` |
| `Piping to a WritableStream that does not consume the writes fast enough exerts backpressure on the ReadableStream`                                                                    | FAIL    | `ReadableStream is not defined`       |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5662/streams/piping/flow-control.html">/streams/piping/flow-control.html</a></summary>


|                                                                                        Subtest                                                                                         | Results |                Messages               |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                                                                                                                        | OK      |                                       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks`                                                                                             | FAIL    | `ReadableStream is not defined`       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks, but then does`                                                                              | FAIL    | `ReadableStream is not defined`       |
| `Piping from an empty ReadableStream into a WritableStream that does not desire chunks, but then the readable stream becomes non-empty and the writable stream starts desiring chunks` | FAIL    | `ReadableStream is not defined`       |
| `Piping from a ReadableStream to a WritableStream that desires more chunks before finishing with previous ones`                                                                        | FAIL    | `CountQueuingStrategy is not defined` |
| `Piping to a WritableStream that does not consume the writes fast enough exerts backpressure on the ReadableStream`                                                                    | FAIL    | `ReadableStream is not defined`       |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5662/streams/piping/flow-control.serviceworker.https.html">/streams/piping/flow-control.serviceworker.https.html</a></summary>


|                                                                                        Subtest                                                                                         | Results |                Messages               |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                                                                                                                        | OK      |                                       |
| `Service worker test setup`                                                                                                                                                            | PASS    |                                       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks`                                                                                             | FAIL    | `ReadableStream is not defined`       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks, but then does`                                                                              | FAIL    | `ReadableStream is not defined`       |
| `Piping from an empty ReadableStream into a WritableStream that does not desire chunks, but then the readable stream becomes non-empty and the writable stream starts desiring chunks` | FAIL    | `ReadableStream is not defined`       |
| `Piping from a ReadableStream to a WritableStream that desires more chunks before finishing with previous ones`                                                                        | FAIL    | `CountQueuingStrategy is not defined` |
| `Piping to a WritableStream that does not consume the writes fast enough exerts backpressure on the ReadableStream`                                                                    | FAIL    | `ReadableStream is not defined`       |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5662/streams/piping/flow-control.sharedworker.html">/streams/piping/flow-control.sharedworker.html</a></summary>


|                                                                                        Subtest                                                                                         | Results |                Messages               |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                                                                                                                        | OK      |                                       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks`                                                                                             | FAIL    | `ReadableStream is not defined`       |
| `Piping from a non-empty ReadableStream into a WritableStream that does not desire chunks, but then does`                                                                              | FAIL    | `ReadableStream is not defined`       |
| `Piping from an empty ReadableStream into a WritableStream that does not desire chunks, but then the readable stream becomes non-empty and the writable stream starts desiring chunks` | FAIL    | `ReadableStream is not defined`       |
| `Piping from a ReadableStream to a WritableStream that desires more chunks before finishing with previous ones`                                                                        | FAIL    | `CountQueuingStrategy is not defined` |
| `Piping to a WritableStream that does not consume the writes fast enough exerts backpressure on the ReadableStream`                                                                    | FAIL    | `ReadableStream is not defined`       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225212520)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 6f36f1558759adc5eea74ab183fff24892b9a025

**Review by domenic — APPROVED** [review]
This seems pretty elegant to me; thanks for taking the time to do this. The end result isn't super easy to understand, but it seems at least as good as the previous version, so I'm happy.

**Comment by ricea** [comment]
Super easy-to-understand would be nice. Still, let's land this for now and hope someone comes along with an improvement.

**Pull request merged**
