### PR TITLE
Flip expectations for maplike/setlike method enumerability

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/whatwg/webidl/pull/1166.

### CODE REVIEW

**Comment by domenic** [comment]
The failure on `/infrastructure/testdriver/actions/multiTouchPointsSimultaneousMove.html` seems unlikely to be my fault...

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I've pushed https://github.com/web-platform-tests/wpt/pull/28759 to see if infrastructure/ tests are broken generally.

**Comment by foolip** [comment]
Nope, the tests passed on https://github.com/web-platform-tests/wpt/pull/28759. I'll close and reopen, maybe tests were broken last week, but now fixed.

**Comment by domenic** [comment]
So I think a different set of tests are broken this time, right? What should we do?

**Comment by past** [comment]
@domenic could you try rebasing and pushing again? The infrastructure tests should be fixed now after c9caf3f2cf6ce6605e371fde8b24ab8acf1dc6e4 and 44af645bfadd209518fc63c3bf142ed25e9af857, so we can see if the idl test breakage is related or not.

**Comment by domenic** [comment]
Still no good...

**Comment by foolip** [comment]
I'll just admin merge this.

**Pull request merged**
