### PR TITLE
Make webdriver/tests/support changes trigger infrastructure/ tests

### LINKED ISSUE #22936: webdriver/tests/support should trigger infrastructure tests
https://github.com/web-platform-tests/wpt/pull/22927 did not trigger infra tests https://community-tc.services.mozilla.com/tasks/groups/KLQpcAtAQyyheGz5K9Bo-w so the regression (caused by a non-ASCII character in the comment) was not caught: https://github.com/web-platform-tests/wpt/pull/22935

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes https://github.com/web-platform-tests/wpt/issues/22936

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Hah, I included a change to webdriver/ for testing, not bothering to think that I'm changing tools/ anyway, so infrastructure/ is always going to run -_-. I guess we just rely on the unittest? (which I have definitely run locally... ahem.)

**Review by Hexcles — APPROVED** [review]
LGTM

**Comment by Hexcles** [comment]
And to confirm, yes I'm happy with relying on the unittest.

**Comment by stephenmcgruer** [comment]
Hypothesis checks! *shakes fist*

**Comment by Hexcles** [comment]
I'm force-merging this. The error from hypothesis should go away with #22943...

**Pull request merged**
