### PR TITLE
Fetch: add return statement to cors-preflight-status.any.js

### PR DESCRIPTION
**Pull request by annevk**
Supersedes #5228.

### CODE REVIEW

**Comment by annevk** [comment]
This fixes #5138.

**Comment by jugglinmike** [comment]
Here's hoping we can avoid this kind of mistake in the future :) https://github.com/w3c/testharness.js/pull/252

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215593645)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 0b59e712dcacd856a621d93cc6edff7ba383b19e
Using browser at version BuildID 20170326110231; SourceStamp f5e214144799889e2408c4841351f4053f00544e
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215593646)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 0b59e712dcacd856a621d93cc6edff7ba383b19e
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Pull request merged**
