### PR TITLE
Update css-backgrounds/border-image tests

### PR DESCRIPTION
**Pull request by csnardi**
This change:
- Reformats and renames border-image-* tests from 001 to 016
- Adds in references for all border-image-* tests except for 015 and 016
- Corrects border-image-005 and border-image-006's references

This is in two commits for easier reviewing.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22154)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/320375371)

**Comment by gsnedders** [comment]
https://gist.github.com/8e81bf29ded7935efd81125b0c789be6 is a diff with a lower than default similarity index and ignoring whitespace. (@csnardi for future, there's not really any need to move XHTML files to being HTML, though if you do it would be better to do it in a separate commit for the sake of a more readable history, and whitespace changes are also nicer if they're a separate commit)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22463)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/326218173)

**Comment by gsnedders** [comment]
@TalbotG I see you've done a bunch of borders & backgrounds stuff recently; you might be interested in reviewing this PR?

**Comment by TalbotG** [comment]
Actually, amazingly, 12 of Jérémie Patonnier's border-image tests were on my radar, as you can see in my notes:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/CSS3Backgrounds-notes.txt

Yes, I can review Chris Nardi's PR.

-----

`background-color: #009900;`
Normally green is `#008000` and only "green" is `#008000`. If tests start using slight variations (`#008500`, `#009000`, etc... or `#289900`), then we reduce opportunities of reusing reference files and then number of reference files unneedlessly grows: we want to avoid that.

Pass if the square is fully green.
Why not just say:
Test passes if there is a filled green square and **no red**.
By doing so, we increase chances of reusing the reference file and testers will also be familiar, accustomed with a very frequently encountered sentence (increasing predictability). In that sentence, the **no red** is actually the strongest pass condition of tests.


"fully green" is not necessary. Nor saying "perfectly green" or "completely green". If there is a tiny area of red in a rendered layout and if people can see it, then a wide majority of people would/will push the FAIL button.


`<strong>no</strong>` red:
Imagine that humans are testers, running the tests (thousands of tests) and clicking PASS or FAIL buttons. You want to increase text scannability for them. Then, as a test author, I would embold the most important test condition. In such cases, it would be the "no red" condition. Even better: imagine that humans running those tests only see bold words after a few hours. If "no red" is emboldened, then they still will be able to correctly push the PASS or FAIL buttons. If they only see the "no", then they won't. Anyway, this is a detail. **You want to attract vision (text scannability) and accelerate decisions of humans taking manually tests by emboldening the only, sole words indicating the most important pass/fail test conditions.** That is how I tried to word the pass-fail conditions sentence. Also, making the pass-fail conditions sentence as short and clear as possible. Again, taking into consideration humans manually taking hundreds, thousands of tests.

In css-backgrounds/border-image-012.html
I think you need to add the scroll flag
http://web-platform-tests.org/writing-tests/css-metadata.html#requirement-flags

**Comment by TalbotG** [comment]
I would do several small improvements to the 2 commits... 

I do not understand why nothing happened between 7 Jan 2018 and today with regards to those commits.

I was asked to prioritize the examination of tests that
- were failed by all browsers
- had missing images
- could not fail (therefore unreliable, not trustworthy)
- were not testing what they claimed to be testing (therefore not trustworthy)

Those Jérémie Patonnier's border-image tests were not on my top priority list. Those Jérémie Patonnier's border-image tests appear to be basic tests, not edge tests, not complex tests, not compound tests.

**Comment by TalbotG** [comment]
@csnardi Chris,  @gsnedders Sam

I will work on this PR soon (no later than March 31st 2023): it's now on my to-do list. I will reuse as much as possible what Chris has already coded.

**Comment by TalbotG** [comment]
There is a problem with **border-image-014 test**.

First, [the spec on border-image-repeat: round](https://www.w3.org/TR/css-backgrounds-3/#valdef-border-image-repeat-round) states
"
round
    The image is tiled (repeated) to fill the area. If it does not fill the area with a whole number of tiles, the image is rescaled so that it does. 
"
and Jérémie Patonnier coded
```
        #test {
            border : 10px solid red;
            width  : 39px;
            height : 39px;
            border-image-source: url(support/img-ref-2.png);
            border-image-slice : 10;
            border-image-repeat: round;
```
Since 39px would indeed cause the area to **not** be filled with a whole number of tiles, then the image would need to be rescaled ... which is exactly what `border-image-repeat: round` is supposed to trigger. But then Chris Nardi wanted to create a reference file. So, he changed [in the commit regarding border-image-014](https://github.com/web-platform-tests/wpt/commit/45fad16a113cdbf4d407d8defa6f6d5831909ce0?diff=split#diff-a285c010219038ff6043f4fbebb0de4aa622a2bdef9babe92b226834df149418) the `39px` values to `40px` and created a reference file. **But now, with `40px`, there is no rescaling needed or triggered**. Therefore the border-image-014 test with `40px` values does not verify if the `round` value is implemented and how well or accurately the `round` value is implemented. 

Because of all this, I think we should drop the border-image-014 test altogether for now ... unless - and this is the only possibility here - someone can eventually create a test where 
a) the image needs to be rescaled and 
b) we can create a reliable, trustworthy reference file for such test.

**Comment by TalbotG** [comment]
While examining border-image-013 test, I found incompatible rendering between Firefox and Chromium. I have not had the time to figure out which one is correct. 

Here's the test:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-013all-GT.html

Reference:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-013all-GT-ref.html

**Comment by TalbotG** [comment]
Another example of Chromium-versus-Firefox incompatible rendering of border-image-repeat implementation, this time with a green versus red test:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-fill-special-002-GT.html

**Comment by TalbotG** [comment]
The following 11 tests (001-004, 006-012) are ready to be submitted:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-003.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-004.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-006.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-007.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-008.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-009.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-010.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-011.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-012.html

References:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/ref-filled-green-100px-square.xht

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-006-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-007-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-008-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-009-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-010-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-012-ref.html

Tests 007, 008, 009 and 010 could be merged into 1 test.

**Comment by TalbotG** [comment]
Okay. A commit upcoming in a few min...

**Comment by TalbotG** [comment]
[Pull Request 40477](https://github.com/web-platform-tests/wpt/pull/40477) is handling the first 12 tests from Jérémie Patonnier. I will try to improve his 4 other remaining border-image tests as soon as [Pull Request 40477](https://github.com/web-platform-tests/wpt/pull/40477) is approved and merged.

**Comment by TalbotG** [comment]
The 3 new tests, which are replacing border-image-14, border-image-15 and border-image-16, have unfortunately subpixel antialias fuzziness, despite conscious efforts to avoid/overcome them:

https://wpt.fyi/results/css/css-backgrounds/border-image-repeat-round-003.html

https://wpt.fyi/results/css/css-backgrounds/border-image-repeat-round-stretch-001.html

https://wpt.fyi/results/css/css-backgrounds/border-image-repeat-stretch-round-001.html

**Comment by TalbotG** [comment]
@fantasai just emailed me 2 possible solutions in order to work around the subpixel antialias fuzziness in the beforementioned 3 tests.

`image-rendering: pixelated;`

if it does not work, then I will go with a suitable, appropriate

`<meta name=fuzzy content="..., ...">`

So this is on my to-do list for later this week.

Cheers!

**Pull request closed without merging**
