### PR TITLE
Update tests for Fullscreen of an iframe's child element

### PR DESCRIPTION
**Pull request by foolip**
Tests for https://github.com/whatwg/fullscreen/issues/45

### CODE REVIEW

**Comment by foolip** [comment]
@aliams, @upsuper, these two tests now pass in Edge and Firefox but fail in Chrome, can either of you review?

@aliams, could we put your or someone else on the Edge team in the fullscreen/OWNERS file, so you see all test changes?

**Comment by aliams** [comment]
Yeah, you can add me for seeing changes.

**Comment by foolip** [comment]
Thanks @aliams, I'll add it in this PR then.

**Comment by foolip** [comment]
@jernoble, can I add you to OWNERS as well, or who is most likely to work on Fullscreen in WebKit going forward?

**Comment by jernoble** [comment]
@foolip Please do add me to OWNERS, thanks.

**Comment by foolip** [comment]
@jernoble, done! Would you also mind reviewing these test changes? The tests will fail in Chrome and Safari. It's a pretty silly corner case, but I intend to fix it in Chrome after implementing Fullscreen in terms of top layer, since the restrictions then don't serve any purpose.

**Comment by foolip** [comment]
Ping @upsuper, @aliams or @jernoble for review.

**Review by upsuper — APPROVED** [review]
LGTM

**Pull request merged**
