### PR TITLE
Allow marcoscaceres to monitor varous test directories

### LINKED ISSUE #36941: Can we add CODEOWNERS?
Over on the WebKit repo, we are using CODEOWNERS file to allow individuals to monitoring certain directories: https://github.com/WebKit/WebKit/blob/main/.github/CODEOWNERS

Could we use the same mechanism here for some of the larger nested directories (e.g., in html/)? For instance, I'm interested in watching only some of the html/ directories - or can META.yml handle that too? 

Or, maybe CODEOWNERS could do away with META.yml entirely?

### PR DESCRIPTION
**Pull request by marcoscaceres**
As WebKit doesn't automatically ingest WPT changes, I need a means to check changes that are relevant to my work across various specs I'm involved with. 

Closes #36941

### CODE REVIEW

**Comment by gsnedders** [comment]
The above lines make it look like we're deliberately using the "enforce reviews from owners"; is there any reason why you can't use the normal META.yml flow here?

**Comment by marcoscaceres** [comment]
For instance, I don’t want to monitor the entire html directory - only user activation. For the others, I could make due with META.yml so long as I have visibility to all automated/exported changes coming from downstream.

**Comment by marcoscaceres** [comment]
@gsnedders ... would this work?

**Comment by marcoscaceres** [comment]
@gsnedders, ping 🙏

**Comment by gsnedders** [comment]
> @gsnedders ... would this work? (i.e., targeting a sub-directory inside html/)

yes.

**Review by gsnedders — APPROVED** [review]
yolo it's a meta.yml change

**Pull request merged**
