### PR TITLE
Update Safari Technology Preview to 103

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 103, 15610.1.7.3.2)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1595&view=logs

### CODE REVIEW

**Comment by foolip** [comment]
I've triggered https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=44422&view=results to see how this will change results.

**Comment by foolip** [comment]
That can be compared with https://wpt.fyi/results/?run_id=448800002, with just two flexbox changes being merged to master in the meantime, #22465 and #22408.

**Comment by stephenmcgruer** [comment]
Diff should be https://wpt.fyi/results/?diff&filter=ADC&run_id=448800002&run_id=462410002

Looks mostly good at a glance; more positives than negatives and no obvious issues being introduced.

**Comment by foolip** [comment]
Filtering a bit it looks to me like this release is actually an overall regression. Comparing just STP 102 to 103 there are [61 fixed subtests](https://wpt.fyi/results/?q=none%28status%3Amissing%29%20and%20seq%28status%3A%21pass%20status%3Apass%29&run_id=448800002&run_id=462410002) but [108 regressed subtests](https://wpt.fyi/results/?q=none%28status%3Amissing%29%20and%20seq%28status%3Apass%20status%3A%21pass%29&run_id=448800002&run_id=462410002).

Looking at Safari-specific failures, there are [32 fixes](https://wpt.fyi/results/?q=none%28status%3Amissing%29%20and%20seq%28status%3Apass%20status%3Apass%20status%3A%21pass%20status%3Apass%29&run_id=464020001&run_id=458700001&run_id=448800002&run_id=462410002) but [54 new failures](https://wpt.fyi/results/?q=none%28status%3Amissing%29%20and%20seq%28status%3Apass%20status%3Apass%20status%3Apass%20status%3A%21pass%29&run_id=464020001&run_id=458700001&run_id=448800002&run_id=462410002).

I don't know what the influence of flakiness here, having the ability to easily filter out historically flaky tests would really help. *nudge nudge wink wink*

Numerically, most of the regressions are in [html](https://wpt.fyi/results/html/semantics/embedded-content/the-img-element/sizes?q=none%28status%3Amissing%29%20and%20seq%28status%3Apass%20status%3A%21pass%29&run_id=448800002&run_id=462410002) and [webdriver](https://wpt.fyi/results/webdriver/tests?q=none%28status%3Amissing%29%20and%20seq%28status%3Apass%20status%3A%21pass%29&run_id=448800002&run_id=462410002).

**Comment by foolip** [comment]
I've filed https://bugs.webkit.org/show_bug.cgi?id=209646 for the webdriver regressions.

@stephenmcgruer can you have a look at what happened in HTML? I'll go ahead and merge this since there's nothing to suggest the results are incorrect. Having more complete runs should also confirm the regressions and rule out flakiness as the cause.

**Comment by foolip** [comment]
@svillar the tools/ unittests are failing on macOS and Windows with Python 3.8 in this PR. Can you check if they're already failing on master? I'm going to merge anyway since I strongly suspect they just aren't in a good state, and this PR is not the cause of it anyway.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
This landed right on top of the current epochs/three_hourly and I triggered another full run. When both are done the results from commits a11782a293251324be969b6ad59d4e99a9850dfa and e0ed4e000c6b1b6347ab5521fbeb0ad54e806ec0 can be compared to verify the regressions.

**Comment by stephenmcgruer** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=439350003&run_id=435310001 is the diff from those two SHAs.

Diffing that against the previous comparison shows:

* The `webdriver/` failures seem flaky; the only overlap from the [first run](https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&q=seq%28status%3Apass%20status%3A%21pass%29&run_id=448800002&run_id=462410002) and the [second run](https://wpt.fyi/results/webdriver/tests?diff&filter=ADC&q=seq%28status%3Apass%20status%3A%21pass%29&run_id=439350003&run_id=435310001) is `get_active_element/user_prompts.py`.

* The regression in `html/semantics/embedded-content` seems consistent. `html/semantics/embedded-content/media-elements/track/track-element/track-cue-rendering-after-controls-removed.html`, is existing flake. `html/semantics/embedded-content/the-img-element/sizes/parse-a-sizes-attribute-display-none.html` appears to be a new regression (no previously reported flakes).

**Pull request merged**
