### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=202311

### PR DESCRIPTION
**Pull request by rwlbuis**

### CODE REVIEW

**Comment by domfarolino** [comment]
Is this the "new way" of getting a cross-origin URL?

**Comment by rwlbuis** [comment]
> Is this the "new way" of getting a cross-origin URL?

I would not say "new way", but this is needed on WebKit to make WPT test runs work locally.

**Comment by annevk** [comment]
This seems wrong as both of these syntaxes are supposed to work per the documentation. If we actually need to avoid one this doesn't seem like the way to go about making such a change.

cc @jgraham

**Comment by domfarolino** [comment]
Probably you're interested in https://github.com/web-platform-tests/wpt/issues/15692 @annevk, which I think is the issue that spawned this PR (and maybe other like it)

**Comment by annevk** [comment]
Closing as this was abandoned upstream.

**Pull request closed without merging**
