### PR TITLE
Added 6 white-space-applies-to-text tests and references

### PR DESCRIPTION
**Pull request by TalbotG**
css/css-text/white-space/white-space-applies-to-text-001.html 
css/css-text/white-space/reference/white-space-applies-to-text-001-ref.html 
css/css-text/white-space/white-space-applies-to-text-002.html 
css/css-text/white-space/reference/white-space-applies-to-text-002-ref.html 
css/css-text/white-space/white-space-applies-to-text-003.html 
css/css-text/white-space/reference/white-space-applies-to-text-003-ref.html 
css/css-text/white-space/white-space-applies-to-text-004.html 
css/css-text/white-space/reference/white-space-applies-to-text-004-ref.html 
css/css-text/white-space/white-space-applies-to-text-005.html 
css/css-text/white-space/reference/white-space-applies-to-text-005-ref.html 
css/css-text/white-space/white-space-applies-to-text-006.html 
css/css-text/white-space/reference/white-space-applies-to-text-006-ref.html

This spun from [Issue 5303](https://github.com/w3c/csswg-drafts/issues/5303) .
Credits should go to @Loirooriol for initially bringing this issue up and making an initial test.

At my website, these 12 files are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-001-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-002-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-003.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-003-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-004.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-004-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-005.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-005-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-006.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-006-ref.html

### CODE REVIEW

**Comment by TalbotG** [comment]
Over at my website, the newer and combined tests and references are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-007.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-007-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-008.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-008-ref.html

**Review by fantasai — CHANGES_REQUESTED** [review]
I think it should be possible to reduce the font size a bit and combine these all into a single test file.
Also it should have a rel=help to https://www.w3.org/TR/css-display-3/#box-generation

Otherwise looks good.

**Comment by TalbotG** [comment]
> combine these all into a single test file.

This may not be possible if we want tests to comply with the
[600px wide by 600px tall window viewport requirement](https://github.com/web-platform-tests/wpt/issues/5403)

**Comment by TalbotG** [comment]
**I finally merged all 6 tests into 1 test.** I used a **font-size of 14px and a line-height of 1** and then made sure that the meta-6-subtests file and its reference were both complying with the [600px wide by 600px tall window viewport requirement](https://github.com/web-platform-tests/wpt/issues/5403).

Over at my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-009.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-009-ref.html

**Review by fantasai — APPROVED** [review]

**Pull request merged**
