### PR TITLE
Added Performance Observer tests

### PR DESCRIPTION
**Pull request by mpb**
Added tests for http://www.w3.org/TR/performance-timeline-2/#the-performance-observer-interface

### CODE REVIEW

**Comment by igrigorik** [comment]
Awesome work, thanks Michael! 

/cc @Ms2ger @plehegar @toddreifsteck @eliperelman

**Comment by Ms2ger** [comment]
Seems like this contains a lot of unnecessary harness code and little actual tests.

**Comment by mpb** [comment]
True. All web-platform-tests/* that use it seem to include a /resources subdirectory with webperftestharnessextension.js and webperftestharness.js, it doesn't seem to be anywhere universally accessible. performance-timeline didn't (yet) have this pair.

**Comment by igrigorik** [comment]
*bump*

**Comment by Ms2ger** [comment]
@igrigorik do you know anyone who would be qualified to review those tests?

**Comment by igrigorik** [comment]
I'm assuming @plehegar is :)

**Comment by igrigorik** [comment]
*bump*

**Comment by plehegar** [comment]
Totally forgot about that one. I think I supercede this with #2884

**Comment by plehegar** [comment]
@igrigorik ok to drop this one?

**Comment by igrigorik** [comment]
Yes, I believe so.

**Pull request closed without merging**
