### PR TITLE
Add a warning when running ./serve when tools.serve cannot be imported

### PR DESCRIPTION
**Pull request by qyearsley-zz**
This is similar to the warning in https://github.com/w3c/web-platform-tests/blob/master/lint.

@jgraham Does this look okay?

A similar change could also be made in https://github.com/w3c/web-platform-tests/blob/master/manifest, which I could make in a separate patch.

Also, am I following the right process in creating this pull request?

### CODE REVIEW

**Comment by jgraham** [comment]
You need to fix the indentation and add an exception to the linter to cover this case.

**Comment by jgraham** [comment]
Please squash.

**Comment by qyearsley** [comment]
Sure -- should I squash with `git rebase -i` and `git push my-repo serve-warn --force`? The message from hoppipolla-critic-bot says not to make in-place history rewrites via `git rebase -i`; is it preferred to do this after the change has been reviewed?

**Comment by qyearsley** [comment]
Hi @jgraham, according to ayg in https://github.com/w3c/web-platform-tests/pull/2951:
> web-platform-tests is configured so that merging pull requests via the web interface always squashes into one commit anyway

So this could also be merged without squash? Or, if you think the change is unnecessary, I could also close this pull request.

**Comment by qyearsley** [comment]
Closing because reviewer is unresponsive.

**Comment by jgraham** [comment]
Why close this? Why not squash as requested? The GH configuration does not match what is mostly used for wpt which is a single functional commit + a merge commit.

**Comment by qyearsley** [comment]
Hi jgraham, I was unsure of exactly how I should squash -- please see my questions above.

**Pull request merged**
