### PR TITLE
Update generated tests due to upstream html5lib changes

### PR DESCRIPTION
**Pull request by stephenmcgruer**
It turns out that html/tools/build.sh clones html5lib-python directly at
HEAD, and uses that to generate tests. Upstream recently updated with
some new behavior, which then changes the generated tests; bring them
into WPT to stop the 'update-build-scripts' check from failing on
unrelated PRs.

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
Haven't looked at it, but the CI should not remain broken. Can you update `html/tools/build.sh` to pin the commit until we move the source data into wpt?

**Comment by gsnedders** [comment]
FWIW, given @stephenmcgruer pinged @annevk on IRC about this:

 * the blocks changes are, I think, Blink/WebKit not having implemented https://github.com/whatwg/html/commit/2fb24fcf3f916236e8767e2cb72b23e5c75b77e9
 * the tests25 changes are, I think, Blink/WebKit not having implemented https://github.com/whatwg/html/commit/7512c0d2375e573dfc5c3341662c887237a44459

**Comment by stephenmcgruer** [comment]
> Can you update html/tools/build.sh to pin the commit until we move the source data into wpt?

I think this is a very good idea, but I want to check with @gsnedders - are you expecting to vendor html5lib soon? At which point I believe you mentioned you were going to switch html/tools/build.sh to use the vendored version. (Or maybe I have this all wrong :D)

**Comment by Ms2ger** [comment]
> > Can you update html/tools/build.sh to pin the commit until we move the source data into wpt?
> 
> I think this is a very good idea, but I want to check with @gsnedders - are you expecting to vendor html5lib soon? At which point I believe you mentioned you were going to switch html/tools/build.sh to use the vendored version. (Or maybe I have this all wrong :D)

I'm guessing that pinning the commit should take no more than an hour; I expect the merge will take a little longer.

**Comment by stephenmcgruer** [comment]
> I'm guessing that pinning the commit should take no more than an hour; I expect the merge will take a little longer.

How reasonable; https://github.com/web-platform-tests/wpt/pull/24131

**Comment by gsnedders** [comment]
> At which point I believe you mentioned you were going to switch html/tools/build.sh to use the vendored version. (Or maybe I have this all wrong :D)

No, the plan is to migrate the source files into wpt; see https://github.com/html5lib/html5lib-tests/issues/127.

**Pull request merged**
