### PR TITLE
Add tests to deserialize remote references

### PR DESCRIPTION
**Pull request by juliandescottes**
Note that this is based on the approved changes from the bidi-script-target-realm branch, reviewed at https://github.com/web-platform-tests/wpt/pull/35878

On mozilla's side, this was reviewed at https://phabricator.services.mozilla.com/D156531

### CODE REVIEW

**Comment by juliandescottes** [comment]
@sadym-chromium this was already reviewed by mozilla peers, can you take a look? Thanks!

**Comment by juliandescottes** [comment]
And to add some context, those tests were useful for us because the current deserialization tests never assert that we actually deserialize the exact same object which was returned as a remote value.

In our first implementation we ended up cloning the objects without realizing it, whereas with the new tests, we really check that we get the exact same object after deserialization.

**Review by sadym-chromium — APPROVED** [review]
Makes sense. Thanks!

**Comment by juliandescottes** [comment]
Thanks for the review! I'm landing the corresponding stack on mozilla-central and closing this PR.

**Comment by whimboo** [comment]
Note that there was an [issue with creating the PR for the upstream merge](https://bugzilla.mozilla.org/show_bug.cgi?id=1788861#c11). @jgraham will have to take care of it.

**Pull request closed without merging**
