### PR TITLE
Fix css-values/vh-support-margin.html

### LINKED ISSUE #13834: vh-support-margin test incorrect
@FremyCompany 

[vh-support-margin.html](http://w3c-test.org/css/css-values/vh-support-margin.html)

[vh-support-margin.html](http://test.csswg.org/suites/css-values-3_dev/nightly-unstable/html/vh-support-margin.htm)

I propose to
a) add html, body {height: 100%;} 
or 
b) add #target {height: 100vh;}
to your test.

### PR DESCRIPTION
**Pull request by FremyCompany**
Closes #13834

### CODE REVIEW

**Comment by TalbotG** [comment]
@FremyCompany 

I have been trying to approve your pull request. **I have no idea what went wrong :(** . See:

> $ git checkout -b FremyCompany-master master
fatal: Une branche nommée 'FremyCompany-master' existe déjà.

> $ git pull https://github.com/FremyCompany/wpt.git master
Depuis https://github.com/FremyCompany/wpt
 * branch                  master     -> FETCH_HEAD
Déjà à jour.

> $ git checkout master
Déjà sur 'master'
Votre branche est en avance sur 'origin/master' de 5 commits.
  (utilisez "git push" pour publier vos commits locaux)

> $ git merge --no-ff FremyCompany-master
Déjà à jour.

> $ git push origin master
Username for 'https://github.com': TalbotG
Password for 'https://TalbotG@github.com': 
Décompte des objets: 23, fait.
Delta compression using up to 2 threads.
Compression des objets: 100% (14/14), fait.
Écriture des objets: 100% (23/23), 5.15 KiB | 0 bytes/s, fait.
Total 23 (delta 14), reused 14 (delta 9)
remote: Resolving deltas: 100% (14/14), completed with 10 local objects.
To https://github.com/TalbotG/web-platform-tests.git
   f84da96541..c50169dc6b  master -> master

**Comment by TalbotG** [comment]
> $ git push
Username for 'https://github.com': TalbotG
Password for 'https://TalbotG@github.com': 
Everything up-to-date

?

**Review by TalbotG — APPROVED** [review]

**Comment by TalbotG** [comment]
Trying to merge pull request 13930 from François Remy

**Comment by FremyCompany** [comment]
@TalbotG I don't think anyone can do this, you have to merge from the website using the button below
image

**Pull request merged**
