### PR TITLE
Change some async_tests in webrtc/ to use promise_test

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See https://github.com/web-platform-tests/wpt/issues/21435

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I'm not sure the construct I created here is valid:

```
    await new Promise(resolve => pc.onnegotiationneeded = resolve);
    pc.onnegotiationneeded = t.step_func(() => {
      assert_unreached('onnegotiationneeded misfired');
    });
    ...
```

It's possible that this may need to happen inside the callback, to make sure not to yield before resetting `pc.onnegotiationneeded`:

```
    await new Promise(resolve => {
      pc.onnegotiationneeded = () => {
        pc.onnegotiationneeded = t.step_func(() => {
          assert_unreached('onnegotiationneeded misfired');
        });
        resolve();
      };
    });
    ...
```

**Comment by jan-ivar** [comment]
> ... make sure not to yield before resetting pc.onnegotiationneeded

We're only yielding on the microtask queue here, and browsers generally don't fire events on the microtask queue.

I think I'd rather we avoid the [promise constructor anti-pattern](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it).

**Comment by stephenmcgruer** [comment]
> I think I'd rather we avoid writing too much code inside promise constructors, where error handling is error-prone.

Yes, definitely agree with that (after bitter experience!). 

@foolip - are you ok to review this or would you prefer someone with webrtc/ experience does so?

**Comment by foolip** [comment]
@jan-ivar or perhaps @guidou would be good reviewers for this, but I can review if nobody else will. Let me know :)

**Review by jan-ivar — APPROVED** [review]
Great! This removes a false positive if `negotiationneeded` doesn't fire at all. Thanks!

**Pull request merged**
