### PR TITLE
[tools] Add wptrunner log summarization script

### PR DESCRIPTION
**Pull request by jeffcarp**
Here's a script I'm using to create a JSON summary of wptrunner results. @gsnedders said it'd be useful to have in the main repo.

Questions:
- [ ] I'm not sure whether this should live in `tools/wptrunner` or in a new directory.
- [ ] I added `#!/usr/bin/python3` but I can make this applicable to Python 2+3 if needed.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5900)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231408049)

# Firefox (nightly) #
Testing web-platform-tests at revision c7b653dfe37dbd48b2b8cf30bc20e5be509a206b
Using browser at version BuildID 20170511133312; SourceStamp 838652a84b76c273e084d0705f3f4f3be89520a8
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/231408055)

# Chrome (unstable) #
Testing web-platform-tests at revision c7b653dfe37dbd48b2b8cf30bc20e5be509a206b

**Comment by jgraham** [comment]
I think the wptrunner directory doesn't make much sense here.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[tools/wptrunner/summarize_logs.py, line 1 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5900#-KjvtiN2_bkvZ5_K5Sir:-KjvtiN3s4w-KmODdgrA:bipoxcd) ([raw file](https://github.com/w3c/web-platform-tests/blob/793d9563bc4d74b2e763e6e0cc65e437ac3e663c/tools/wptrunner/summarize_logs.py#L1)):*
> ```Python
> #!/usr/bin/python3
> ```

Everything else here is Python 2.7 compatible. I certainly don't object to supporting both, but it must be both.

---

*[tools/wptrunner/summarize_logs.py, line 23 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5900#-KjvtytRjTqh9XDEhJCv:-KjvtytRjTqh9XDEhJCw:b-1efk95) ([raw file](https://github.com/w3c/web-platform-tests/blob/793d9563bc4d74b2e763e6e0cc65e437ac3e663c/tools/wptrunner/summarize_logs.py#L23)):*
> ```Python
>     """
>     summary_filename = sys.argv[1]
>     assert summary_filename, 'Required argument: summary file path'
> ```

Won't this have already died if that doesn't exist with an `IndexError` in the line above.

---

*[tools/wptrunner/summarize_logs.py, line 32 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5900#-KjwR7Iaa7RG1FPG3SD6:-KjwR7IbKyfJN5bt_s42:bkro6yk) ([raw file](https://github.com/w3c/web-platform-tests/blob/793d9563bc4d74b2e763e6e0cc65e437ac3e663c/tools/wptrunner/summarize_logs.py#L32)):*
> ```Python
>         # To guard against irrelevant test lines
>         # Maybe warn if we find too many?
>         if test_status["action"] != "test_status":
> ```

Note that `test_end` can also contain statuses, either the overall file status for testharness tests or the test result for reftests.

---

*[tools/wptrunner/summarize_logs.py, line 45 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/5900#-KjwRRO76T-6p6IhQiWJ:-KjwRRO76T-6p6IhQiWK:bpc3t5k) ([raw file](https://github.com/w3c/web-platform-tests/blob/793d9563bc4d74b2e763e6e0cc65e437ac3e663c/tools/wptrunner/summarize_logs.py#L45)):*
> ```Python
> 
>         if status == 'PASS':
>             results[test_file][0] += 1
> ```

Just counting passes without knowing which tests passed doesn't seem that useful. What's using this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5900#-:-KjwRd6lO6OYb-JpQO78:b59hop8)*

**Comment by jeffcarp** [comment]
Thanks for catching those, updated the PR

> I think the wptrunner directory doesn't make much sense here.

Where is a more appropriate place to put this? I put it into `tools/` for now.

> Just counting passes without knowing which tests passed doesn't seem that useful. What's using this?

I'm using this to generate a file with just directory and test file level passing numbers. Sub-test results for specific files will be stored separately - this script is for summarizing the results and shipping a searchable version to the browser.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233047305)

# Sauce (safari) #
Testing web-platform-tests at revision 18eaa388e434f5e9bd8cf704138a21f7087ae881
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233047306)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 18eaa388e434f5e9bd8cf704138a21f7087ae881
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
> I'm using this to generate a file with just directory and test file level passing numbers. Sub-test results for specific files will be stored separately - this script is for summarizing the results and shipping a searchable version to the browser.

IMO if we want something upstream it should provide all the subtest results (unless, I guess, if the parent fails in some way, given the results received may be bogus); it's then possible to use that JSON to generate whatever output at whatever level you want.

**Comment by gsnedders** [comment]
Also, it'd be nice for this to have some way to deal with multiple results for a test (e.g., from wptrunner's `--repeat`) to be able to have some stability test built on top of it. (Not that the initial PR needs to address this!)

**Comment by jeffcarp** [comment]
Closing in favor of #6356

**Pull request closed without merging**
