### PR TITLE
HTML: Add tentative tests for speculative HTML parsing

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/html/issues/5624

### CODE REVIEW

**Comment by zcorpan** [comment]
I'm done with adding new tests for now. If someone is interested in reviewing, I believe this is in a reviewable state (though there's no spec proposal yet).

**Comment by zcorpan** [comment]
Test results: https://wpt.fyi/results/html/syntax/speculative-parsing/generated?label=pr_head&max-count=1&pr=24521

Safari is not included currently due to https://github.com/web-platform-tests/wpt/issues/26329

**Comment by zcorpan** [comment]
Rebased today, and now Safari test results are up: https://wpt.fyi/results/html/syntax/speculative-parsing/generated?label=pr_head&max-count=1&pr=24521

**Comment by zcorpan** [comment]
@mfreed7 can you review, please? The spec change has now been approved by @hsivonen : https://github.com/whatwg/html/pull/5959

**Comment by zcorpan** [comment]
Rebased again to resolve conflicts.

The [`wpt-firefox-nightly-stability` check now failed](https://github.com/web-platform-tests/wpt/pull/24521/checks?check_run_id=3542320011) for test `img-srcset`

Test | Subtest | Results | Messages
-- | -- | -- | --
/html/syntax/speculative-parsing/generated/page-load/img-srcset.tentative.html | Speculative parsing, page load: img-srcset | FAIL: 1/10, PASS: 9/10 | Unhandled rejection: assert_not_equals: speculative case did not fetch got disallowed value ""

I could reproduce this locally by reloading the test a couple of times in Firefox Nightly. @hsivonen is this a known issue? Or is 1500ms for the blocking script insufficient for stable test results?

**Comment by zcorpan** [comment]
Increasing the time to 3000ms doesn't fix the flakiness when testing locally. I can submit a bug for Gecko.

**Comment by hsivonen** [comment]
Not known. I'll try to catch this is rr. Thanks.

**Comment by mfreed7** [comment]
Sorry for the delay re-reviewing the speculative parser stuff! These tests LGTM.

So Chromium has about 15 tests that fail and would need attention.

This one ([meta-charset-script-src.tentative.html](https://wpt.fyi/results/html/syntax/speculative-parsing/generated/page-load/meta-charset-script-src.tentative.html?label=pr_head&max-count=1&pr=24521)) passes for `document.write()` for all browsers, but fails page load on all browsers. Any clues there?

**Comment by zcorpan** [comment]
Thanks, @mfreed7 !

> This one ([meta-charset-script-src.tentative.html](https://wpt.fyi/results/html/syntax/speculative-parsing/generated/page-load/meta-charset-script-src.tentative.html?label=pr_head&max-count=1&pr=24521)) passes for `document.write()` for all browsers, but fails page load on all browsers. Any clues there?

Good catch.

So Firefox fails with this message:
> `Unhandled rejection: assert_not_equals: speculative case did not fetch got disallowed value ""`

Chrome and Safari:
> `Unhandled rejection: assert_equals: expected `param-encodingcheck` values to match between speculative and non-speculative expected "%26%23286%3B" but got "%D0"`

See this comment for how `encodingcheck` works: https://github.com/web-platform-tests/wpt/pull/24521/files#diff-4035c7e78333e9b93cce273d96a8235c5a4db3d498f4731ea225166187e5ec34R494-R504

So in Chrome and Safari, the URL character encoding for the `script src` fetch is windows-1252, even though there's a `<meta charset=windows-1254>` before it. That is, the speculative parser seems to ignore encoding declarations.

I'm not sure why Firefox doesn't fetch here. @hsivonen do you know?

**Comment by zcorpan** [comment]
@mfreed7 can you approve this PR with GitHub's review feature (in the [Files Changed](https://github.com/web-platform-tests/wpt/pull/24521/files) tab), please? Then we can merge. Thanks!

**Review by mfreed7 — APPROVED** [review]
LGTM!

**Comment by zcorpan** [comment]
On the document-write/meta-charset test:

In https://github.com/whatwg/html/pull/5959/files#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947dR110885 it's specced that the speculative parser ignores the encoding declaration (because, changing the encoding can cause a re-navigation per spec). There was a bug in the test that I had fixed before but accidentally reverted, and now have fixed again (https://github.com/web-platform-tests/wpt/pull/24521/commits/fc10383def5586b4ed008d1a76c47988582173a1) -- the charset scanner shouldn't find the encoding declaration nested in a `document.write()`.

**Pull request merged**
