### PR TITLE
[SPC] Add missing rpId field to a bunch of tests

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by nickburris** [comment]
LGTM, thanks for updating these!

**Review by nickburris — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
(close, re-open to see if the stability checks pass)

**Review by rsolomakhin — APPROVED** [review]
rubber-stampity-stamp lgtm

**Comment by past** [comment]
Offline discussion concluded that the stability check failures are due to an unrelated webdriver issue.

**Pull request merged**
