### PR TITLE
Test format updated to match latest i18n test suite files. 

### PR DESCRIPTION
**Pull request by r12a**
Includes fixes for missing lang attributes.
中文 -> 文字
Linked to font at /fonts
CSS font meta tag removed.
Tabs, trailing spaces, and unnecessary newlines removed.
More metadata removed from ref files.

### CODE REVIEW

**Comment by r12a** [comment]
This PR replaces https://github.com/w3c/web-platform-tests/pull/9871

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2018-03-13 12:03:03
Finished: 2018-03-13 12:52:35


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25852)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/352803678)

**Comment by r12a** [comment]
Am i right in understanding that the checks failed because of a timeout?

**Comment by frivoal** [comment]
@r12a that looks correct. I've restarted the job that hanged.

**Comment by r12a** [comment]
I'm putting this on hold.  I may be able to come up with a set of tests that use testharness.js to replace them.

**Comment by frivoal** [comment]
@r12a https://github.com/web-platform-tests/wpt/pull/10860 replaced this. Closing.

**Pull request closed without merging**
