### PR TITLE
[css-logical] Inheritance, initial values

### PR DESCRIPTION
**Pull request by ewilligers**
Test that CSS Logical Properties and Values properties do not inherit.

Test that initial values match the spec.
https://www.w3.org/TR/css-logical-1/#property-index

### CODE REVIEW

**Comment by ewilligers** [comment]
Tests pass on Blink/Edge/Safari.

Firefox fails 4 tests:-

> Fail	Property border-block-end-width has initial value 2.5px	assert_equals: expected "2.5px" but got "3px"
> Fail	Property border-block-start-width has initial value 2.5px	assert_equals: expected "2.5px" but got "3px"
> Fail	Property border-inline-end-width has initial value 2.5px	assert_equals: expected "2.5px" but got "3px"
> Fail	Property border-inline-start-width has initial value 2.5px	assert_equals: expected "2.5px" but got "3px"

I don't understand why the inline-size test passes when these tests fail.

**Comment by ewilligers** [comment]
@fantasai please review

**Comment by ewilligers** [comment]
@atanassov please review

**Comment by ewilligers** [comment]
@tabatkins Would you be happy to be a [test reviewer](https://github.com/web-platform-tests/wpt/blob/master/css/css-logical/META.yml) for css-logical?

**Review by tabatkins — APPROVED** [review]

**Pull request merged**
