### PR TITLE
WIP: SharedArrayBuffer structured cloning tests

### PR DESCRIPTION
**Pull request by domenic**
This is for https://github.com/whatwg/html/pull/2518 which is ready to land.

Test plan (please suggest more!):

Success cases (test that modifying on both sides is reflected on the other):

- [x] postMessage between window and dedicated worker
- [x] postMessage between window and same-origin iframe
- [x] postMessage between window and same-origin-domain, but not same-origin, iframe
- [x] postMessage between window and its opener
- [x] postMessage between dedicated worker and nested dedicated worker
- [x] postMessage between shared worker and nested dedicated worker
- [x] postMessage between window and nested-nested-nested same-origin iframe
- [x] MessageChannel version of postMessage between window and dedicated worker
- [x] Every clone creates a distinct SAB object, that is not ===, even though the backing memory is shared
- [x] Test using BroadcastChannel where it all succeeds
- [x] All of the above with Uint8Array and DataView wrappers instead of directly using SABs.
- [x] Structured serialization via pushState/replaceState
- [x] postMessage between window and non-same-origin-domain iframe that is still in the same URSOBC

Failure cases that cause error behavior on the receiver side (messageerror event):

- [ ] postMessage between window and another window not in the same URSOBC (blocked on #2669)
- [x] Test using BroadcastChannel where some succeed and some fail
- [x] postMessage between window and shared worker
- [x] postMessage between window and service worker
- [ ] postMessage between window and same-URSOBC iframe that is nested through an intermediate non-same-URSOBC iframe (blocked on #2669)

Failure cases that cause synchronous failure:

- [x] Putting the SAB in the transfer list
- [x] Structured serialization via Notifications API's data member
- [x] Writing a SAB to IDB

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5003)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204802374)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 013c96ad40408690e91102fe09580d09801fb004
Using browser at version BuildID 20170223110219; SourceStamp 32dcdde1fc64fc39a9065dc4218265dbc727673f
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-domain-success.sub.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-domain-success.sub.html</a></summary>


|                                                      Subtest                                                       | Results |
|--------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                    | OK      |
| `postMessaging to a same-origin-domain (but not same-origin) iframe allows them to see each others' modifications` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-simple-success.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-simple-success.html</a></summary>


|                                               Subtest                                               | Results |
|-----------------------------------------------------------------------------------------------------|---------|
|                                                                                                     | OK      |
| `postMessaging to a dedicated worker allows them to see each others' modifications`                 | PASS    |
| `postMessaging to a same-origin opened window allows them to see each others' modifications`        | PASS    |
| `postMessaging to a same-origin deeply-nested iframe allows them to see each others' modifications` | PASS    |
| `postMessaging to a same-origin iframe allows them to see each others' modifications`               | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.dedicatedworker.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.dedicatedworker.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `postMessaging to a dedicated sub-worker allows them to see each others' modifications` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/no-transferring.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/no-transferring.html</a></summary>


|                                Subtest                                | Results |
|-----------------------------------------------------------------------|---------|
|                                                                       | OK      |
| `Trying to transfer a SharedArrayBuffer to a worker throws`           | PASS    |
| `Trying to transfer a SharedArrayBuffer through a MessagePort throws` | PASS    |
| `Trying to transfer a SharedArrayBuffer to this window throws`        | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-messagechannel-success.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-messagechannel-success.html</a></summary>


|                                                Subtest                                                 | Results |
|--------------------------------------------------------------------------------------------------------|---------|
|                                                                                                        | OK      |
| `postMessaging to a dedicated worker via MessageChannel allows them to see each others' modifications` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.sharedworker.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.sharedworker.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `postMessaging to a dedicated sub-worker allows them to see each others' modifications` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/identity-not-preserved.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/identity-not-preserved.html</a></summary>


|                                       Subtest                                       | Results |
|-------------------------------------------------------------------------------------|---------|
|                                                                                     | OK      |
| `postMessaging to this window does not give back the same SharedArrayBuffer`        | PASS    |
| `postMessaging to a worker and back does not give back the same SharedArrayBuffer`  | PASS    |
| `postMessaging to an iframe and back does not give back the same SharedArrayBuffer` | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204802375)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 013c96ad40408690e91102fe09580d09801fb004
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-domain-success.sub.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-domain-success.sub.html</a></summary>


|                                                      Subtest                                                       | Results |
|--------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                    | OK      |
| `postMessaging to a same-origin-domain (but not same-origin) iframe allows them to see each others' modifications` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-simple-success.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-simple-success.html</a></summary>


|                                               Subtest                                               | Results |
|-----------------------------------------------------------------------------------------------------|---------|
|                                                                                                     | OK      |
| `postMessaging to a dedicated worker allows them to see each others' modifications`                 | FAIL    |
| `postMessaging to a same-origin opened window allows them to see each others' modifications`        | FAIL    |
| `postMessaging to a same-origin deeply-nested iframe allows them to see each others' modifications` | FAIL    |
| `postMessaging to a same-origin iframe allows them to see each others' modifications`               | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.dedicatedworker.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.dedicatedworker.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `postMessaging to a dedicated sub-worker allows them to see each others' modifications` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/no-transferring.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/no-transferring.html</a></summary>


|                                Subtest                                | Results |
|-----------------------------------------------------------------------|---------|
|                                                                       | OK      |
| `Trying to transfer a SharedArrayBuffer to a worker throws`           | FAIL    |
| `Trying to transfer a SharedArrayBuffer through a MessagePort throws` | FAIL    |
| `Trying to transfer a SharedArrayBuffer to this window throws`        | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-messagechannel-success.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/window-messagechannel-success.html</a></summary>


|                                                Subtest                                                 | Results |
|--------------------------------------------------------------------------------------------------------|---------|
|                                                                                                        | OK      |
| `postMessaging to a dedicated worker via MessageChannel allows them to see each others' modifications` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.sharedworker.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/nested-worker-success.sharedworker.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `postMessaging to a dedicated sub-worker allows them to see each others' modifications` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5003/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/identity-not-preserved.html">/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/identity-not-preserved.html</a></summary>


|                                       Subtest                                       | Results |
|-------------------------------------------------------------------------------------|---------|
|                                                                                     | OK      |
| `postMessaging to this window does not give back the same SharedArrayBuffer`        | FAIL    |
| `postMessaging to a worker and back does not give back the same SharedArrayBuffer`  | FAIL    |
| `postMessaging to an iframe and back does not give back the same SharedArrayBuffer` | FAIL    |

</details>
</details>

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5003/)

**Comment by annevk** [comment]
These tests all look good. (I rebased them across the landing of css/.)

To test the agent cluster boundary between Window objects we need #2669 fixed. But I suppose we can add a test where a Window attempts to share with a SharedWorker and vice versa. As I understand it there is supposed to be such a boundary there. For those tests I'll assume the `messageerror` for the receiver design, which still seems best all things considered.

@lars-t-hansen thoughts on other things to test?

**Comment by domenic** [comment]
Moved the test plan to this thread's OP. We can of course land some tests before having exhaustive tests.

**Comment by domenic** [comment]
Tests are nearing completion (and running ahead of the spec a bit). The history/IDB/Notification tests have caught crash bugs in Chrome. In Firefox they are using TypeErrors instead of "DataCloneError" DOMExceptions, which seem more appropriate to me.

Note that a new test reveals that both Firefox and Chrome use similar-origin, not same-origin or same-origin-domain, for agent clusters. This is as specced.

This revealed that we'll need to do some spec work for messageerror in service workers, as noted in https://github.com/whatwg/html/pull/2530#issuecomment-294625506 .

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222978295)

# Lint #

Passed

**Comment by annevk** [comment]
So TypeError follows from using IDL, but I guess we can use it for StructuredSerializeForStorage too for that specific case.

**Comment by domenic** [comment]
Wait, why would it follow from IDL? history/IDB/Notifications use `any`; IDL won't get involved.

StructuredSerializeForStorage should do "DataCloneError" IMO.

**Comment by annevk** [comment]
Oops, misread. If you pass this to XHR, TextDecoder, or Blob you'll get a TypeError though, I assume.

**Comment by domenic** [comment]
Ah, yes. I hear @binji is working on tests for that as part of safelisting SAB for certain APIs.

**Comment by binji** [comment]
I added a bunch of Blink layout tests to make sure the SAB typed arrays throw. Some of them use the new WPT-like testing infrastructure, so shouldn't be too hard to port, but many others use various ad-hoc testing harnesses, so might be trickier. Didn't realize someone put my name in for doing it... :-)

**Comment by domenic** [comment]
Added a BroadcastChannel test broadcasting to different iframes. In a now-familiar pattern, Firefox disallows and Chrome crashes. (It should work.)

> Test using BroadcastChannel where some succeed and some fail

I'm not sure such a test is possible. To go outside the agent cluster using BroadcastChannel, we need to use shared/service workers. (BroadcastChannel doesn't work cross-origin, so windows cannot work, #2669 notwithstanding.) But it seems like BroadcastChannel only works with "suspendable workers", and I don't know how to create one of those.

**Comment by annevk** [comment]
@domenic you can have two same-origin Window objects that are not in the same cluster, but you need some privileged API to get that automated.

**Comment by annevk** [comment]
I rebased this to work around the Chrome bot failure.

**Comment by annevk** [comment]
@domenic should we s/.dedicatedworker.html/-dedicatedworker.html/ and s/.sharedworker.html/-sharedworker.html/? It seems wrong to use dots in filenames when not triggering some kind framework feature.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225952984)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225955561)

# Lint #

Passed

**Comment by annevk** [comment]
Also, s/serialization-via-notifications-api.any.js/serialization-via-notifications-api-manual.any.js/ since permissions cannot be automated yet?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225976344)

# Lint #

Passed

**Comment by domenic** [comment]
> should we s/.dedicatedworker.html/-dedicatedworker.html/ and s/.sharedworker.html/-sharedworker.html/? It seems wrong to use dots in filenames when not triggering some kind framework feature.

I've been using this for streams, but sure, I see your point. Renaming works fine.

> Also, s/serialization-via-notifications-api.any.js/serialization-via-notifications-api-manual.any.js/ since permissions cannot be automated yet?

Somehow I still got these tests to crash Chrome and produce an error in Firefox in their current form. I guess because per https://notifications.spec.whatwg.org/#constructors the "create a notification" step runs before the in-parallel permission business.

> BroadcastChannel that partially fails and partially succeeds

How are you sure that these two workers are "suspendable workers", per https://html.spec.whatwg.org/#dom-broadcastchannel-postmessage step 7 bullet 1 sub-bullet 2?

Assumign the test is OK, can we also test the other properties of the MessageEvent for the messageerror case?

**Comment by annevk** [comment]
It's not okay. I guess we can only test it once #2669 is fixed. I wonder though why BroadcastChannel basically cannot work in a shared worker. Seems like a bug of sorts.

**Comment by annevk** [comment]
Yeah, I think you're right that the Notification test is fine as automated, since we don't actually care about what happens with the permission thing. And spawning a permission dialog doesn't violate automation I think.

**Comment by domenic** [comment]
I can't figure out how BroadcastChannel could work in workers, basically; I don't understand what a "suspendable worker" is supposed to map to in the real world, or why you might want to broadcast to them.

**Comment by annevk** [comment]
I went digging, it was a typo that was introduced when this feature was added. Compare https://www.w3.org/Bugs/Public/show_bug.cgi?id=24414 with https://github.com/whatwg/html/commit/300e7def9f9c31b25b995445bed87bfcdad3a3d7.

**Comment by annevk** [comment]
We now have limited coverage for all different views as well, including DataView, and including that they're successfully "cloning" their backing shared buffer.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5003/)

**Comment by domenic** [comment]
This LGTM to merge and file bugs.

**Pull request merged**
