### PR TITLE
Improve compatibility of manifest tool with Python3

### LINKED ISSUE #19836: Bytes vs str incompatibility between manifest and gitignore tools
Hello everyone,

I am trying to improve compatibility for Python3 in servo (see https://github.com/servo/servo/issues/23607) and that leads me to also improve compatibility in wpt too.
I noticed that `tools/manifest` uses `tools/gitignore` to parse `.gitignore` files but the former expects to receive path as `bytes` whereas the latter expects path as `str`.
In Python2 those two types are the same but not in Python3 anymore.

I think we have 3 choices to fix this issue:
1. Change `tools/gitignore` to expect `bytes`
2. Change `tools/manifest` to expect `str`
3. Decode all strings when calling `tools/gitignore` from `tools/manifest`

I think option 1. is the one we should go for, and i am willing to work on it, but i would like your opinion on that matter.

Thank you in advance!

### PR DESCRIPTION
**Pull request by marmeladema**
Should fix #19836 and help with https://github.com/servo/servo/issues/23607

### CODE REVIEW

**Review by jgraham — COMMENTED** [review]
I'm going to leave review of this to @gsnedders since they are most knowledgable about this code. Decoding shell output to a string under the assumption it's valid UTF8 is at least a little suspect, but maybe in practice we rely on that anyway?

**Comment by marmeladema** [comment]
> Decoding shell output to a string under the assumption it's valid UTF8 is at least a little suspect, but maybe in practice we rely on that anyway?

I thought about that too but because everything else is considered utf8 valid, if the output of a git command is not, i don't really know what we can do about it.

**Comment by marmeladema** [comment]
And fyi, with this change, i was able to run the full `test-tidy` command from servo build system using python3.
cc @jdm

**Comment by marmeladema** [comment]
Friendly ping @gsnedders @jgraham :-)

**Comment by gsnedders** [comment]
Hi. Yes. Sorry for the delay. (And further delayed by https://github.com/orgs/web-platform-tests/teams/reviewers/discussions/4 happening in the middle of me writing this comment!)

My memory from when I wrote the type annotations here is that we really want some of this to be text_type, `vcs.FileSystem.__iter__` especially (because then those values get compared with  JSON strings, which are invariably text_type, within `manifest.Manifest.update`). `str` is obviously an improvement insofar as it gets the right behaviour on Py3, though.

That said, from when I played around with this before, I think decoding here (as we now do in Py3) has a fair perf cost?

**Comment by jgraham** [comment]
This seems to be conflicting with other changes. Is there some reason to keep this open (i.e. might it get rebased and completed) or should we just close it?

**Comment by ExE-Boss** [comment]
This was fixed in commits [`b402397`](https://github.com/web-platform-tests/wpt/commit/b4023970550ce0d454e700fad25e957ad1366ceb#diff-9c76a08d73cbcbaa19c0adedcaa3242e) and [`d4cdf40`](https://github.com/web-platform-tests/wpt/commit/d4cdf4021ab48c66b052fb62d91da1a06c8cbcf7#diff-9c76a08d73cbcbaa19c0adedcaa3242e).

**Pull request closed without merging**
