### PR TITLE
[css-ui] expect resolved color in inheritance test

### PR DESCRIPTION
**Pull request by ewilligers**
getComputedStyle returns the resolved color or 'invert', not 'auto'
https://drafts.csswg.org/cssom/#resolved-value

### CODE REVIEW

**Comment by frivoal** [comment]
For the invert color of the outline-color property, you should check if the invert keyword is supported at all. If it is, it should be the initial value, but if it is not, having currentColor be the initial value is spec compliant.

**Review by frivoal — DISMISSED** [review]
Looks good, except for the comment I made in https://github.com/web-platform-tests/wpt/pull/13748#issuecomment-435116605.

Once that's fixed, this should be merged.

**Comment by ewilligers** [comment]
outline-color test now checks if 'invert' is supported. 

Blink/Firefox/Safari pass the outline-color test by not supporting 'invert', and returning the current rgb() color.

Edge fails the outline-color test by accepting 'invert' but returning 'invert' from getComputedStyle() instead of the inverted background color.

**Comment by frivoal** [comment]
> Edge fails the outline-color test by [...] returning 'invert' from getComputedStyle() instead of the inverted background color.

That's actually a pass. returning the inverted background color isn't actually possible, since background may not be a single color. returning 'invert' as a keyword is the right thing to do.

**Comment by frivoal** [comment]
> Does that mean the UA should check whether the background is a single, opaque solid color (and if so, return that) or should it always return invert?

It should always return `invert`. Happy to go clarify that in level 4, but that's the intention behind level 3, and is what microsoft & presto implemented.

**Comment by svgeesus** [comment]
@ewilligers waiting for your changes to address comments before we merge.

**Review by svgeesus — COMMENTED** [review]
Look good except for the point already raised by Florian

**Comment by ewilligers** [comment]
Test updated, thank you for explaining.

**Comment by ewilligers** [comment]
@frivoal's comments have been addressed.

**Comment by ewilligers** [comment]
Ping. I believe this is ready for merging.

**Review by frivoal — APPROVED** [review]

**Pull request merged**
