### PR TITLE
Fix Acid2 to take the screenshot after it loads

### PR DESCRIPTION
**Pull request by gsnedders**

### CODE REVIEW

**Comment by gsnedders** [comment]
(Note the reftest still fails everywhere due to #8423.)

**Comment by gsnedders** [comment]
Hopefully this is enough for it to pass everywhere on wpt.fyi.

**Comment by jgraham** [comment]
Isn't taking the screenshot after load the default behviour? Why is something special needed here?

**Comment by gsnedders** [comment]
> Isn't taking the screenshot after load the default behviour? Why is something special needed here?

Yeah, that's true. Ergh. I have no idea what's up. :/

**Comment by gsnedders** [comment]
Oh, maybe it's the fact it has to scroll the test page before the screenshot can happen?

**Comment by gsnedders** [comment]
Okay, so synchronously scrolling seems to work.

**Comment by gsnedders** [comment]
Okay something weird is up, three Travis PR jobs?!

**Review by Ms2ger — APPROVED** [review]
If it passes, who am I to complain?

**Pull request merged**
