### PR TITLE
[cssom] Add test for synchronization between css declaration block and style attribute

### PR DESCRIPTION
**Pull request by upsuper**
This is test for proposed spec change in w3c/csswg-drafts#2269.

### CODE REVIEW

**Comment by upsuper** [comment]
Currently, Firefox fails one test that it generates mutation record even when removing non-existing property from the CSS declaration block. We are going to fix this in [Gecko bug 1435139](https://bugzilla.mozilla.org/show_bug.cgi?id=1435139).

WebKit and Blink both fail a test that they don't generate mutation record when setting the same value to CSS declaration block. Based on my reasoning in [w3c/csswg-drafts#2269 (comment)](https://github.com/w3c/csswg-drafts/pull/2269#issuecomment-362869138), I tend to keep the proposed behavior as-is, and ask those browsers to change their behavior here.

WebKit fails another test in addition that it doesn't clear the declaration block when the style attribute is removed. This is definitely a bug for them should be fixed.

I haven't tested Edge because I'm not using my Windows laptop at the moment.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23842)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/337084028)

**Comment by upsuper** [comment]
Hmmm, after fixing that issue, Gecko will fail the same test as Blink :/

(The test itself matches the proposed spec change, but we may want to decide what should we do for `setProperty`.)

**Comment by zcorpan** [comment]
I added a commit to test
https://github.com/w3c/csswg-drafts/pull/2269/commits/03cef6ebb54f0c45fb06b6fec96ef059e4989ee2
by testing what bz suggested in
https://github.com/w3c/csswg-drafts/issues/1559#issuecomment-363132747

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
