### PR TITLE
Update the-offscreen-canvas/2d.getcontext.exists.html

### LINKED ISSUE #19799: [OffscreenCanvasRenderingContext2D] the-offscreen-canvas/2d.getcontext.exists.html contains redundant code that will not be reached when OffscreenCanvasRenderingContext2D is undefined
At https://github.com/web-platform-tests/wpt/blob/master/offscreen-canvas/the-offscreen-canvas/2d.getcontext.exists.html the current code is

```
var t = async_test("The 2D context is implemented");
t.step(function() {
var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');
var offscreenCanvas2 = new OffscreenCanvas(100, 50);
_assertDifferent(offscreenCanvas2.getContext('2d'), null, "offscreenCanvas2.getContext('2d')", "null");
t.done();
});
```
If `OffscreenCanvasRenderingContext2D` is `undefined` an exception will be thrown at Firefox and Nightly

`[Exception... "Method not implemented"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line <Line No>"  data: no]`

before reaching the next line which again attempts to create a `OffscreenCanvasRenderingContext2D` that is not implemented.

Instead of trying to create the context twice the test can be modified to output `true` or `false`

`"OffscreenCanvasRenderingContext2D" in globalThis // true or false` 

or 

`typeof OffscreenCanvasRenderingContext2D === "function" // true or false` (https://stackoverflow.com/a/57304946)

### PR DESCRIPTION
**Pull request by guest271314**
Fixes https://github.com/web-platform-tests/wpt/issues/19799

### CODE REVIEW

**Comment by annevk** [comment]
I don't see how it's a problem that it throws in Firefox. And you're changing the pass condition drastically which might end up hiding a bug in user agents that don't throw for the initial thing.

**Comment by guest271314** [comment]
That the previous code throws in Firefox is not a problem. The second instance of `OffscreenCanvas()` is not necessary to observe that result. The current displayed result is 

> FAIL message: assert_not_equals: offscreenCanvas2.getContext('2d') !== null (got [object], expected not [object]) got disallowed value null

however, the `OffscreenCanvas` algorithm does not state `null` is an expected output. The output should either throw stating "not implemented" message as Firefox does, or be `undefined` when `OffscreenCanvasRenderingContext2D` is not defined at the global object.

Where is `null` mentioned in the `OffscreenCanvas` algorithm https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-getcontext?

Why does a second `OffscreenCanvas` instance need to be created to determine if the first `OffscreenCanvas` created does or does not throw when `getContext()` is executed to get a  `OffscreenCanvasRenderingContext2D`, which could be tested for being defined without creating an `OffscreenCanvas` (it might be more thorough to check for the function and `"2d"` passed to `getContext()`)?

**Comment by guest271314** [comment]
One pattern that can be used to test `"2d"` by executing `getContext()` and checking if `OffscreenCanvasRenderingContext2D` is defined

```
function testOffscreenCanvas2D() {
  let ctx, osc2D = "OffscreenCanvasRenderingContext2D";
  try {
    ctx = (new OffscreenCanvas(100, 50)).getContext("2d");
  } catch(e) {
    ctx = e.message;
  } finally {
    result = ctx.toString() === `[object ${osc2D}]`;
    assert_true(ctx, `${osc2D} is defined: ${result}`);
  }
}
```

**Comment by annevk** [comment]
There are many instances of return null in that algorithm.

**Comment by guest271314** [comment]
Perhaps the grid is not immediately clear. 

Do not see where `new OffscreenCanvas(100, 50).getContext("2d")` is expected to return `null` if `OffscreenCanvasRenderingContext2D` is not defined? Should Firefox be returning `null` instead of throwing an exception?

What is the purpose of creating 2 instances of `OffscreenCanvas()` to test if `OffscreenCanvasRenderingContext2D` is defined once?

In code run in the browser, for example, at `console`, the second `new OffscreenCanvas(100, 50).getContext("2d")` will not be reached, correct?

**Comment by guest271314** [comment]
@annevk Note also, this test https://wpt.fyi/results/imagebitmap-renderingcontext/tranferFromImageBitmap-TransferToImageBitmap-offscreen.html?label=master&label=experimental&aligned&q=imagebitmap-renderingcontext%2Ftranferfromimagebitmap-transfertoimagebitmap-offscreen.html outputs the result 

> PROMISE_REJECT(object "ReferenceError: OffscreenCanvas is not defined")

for Firefox, which is incorrect. Firefox does implement `OffscreenCanvas`. The problem is that `2d` is not implemented for `OffscreenCanvas` and `bitmaprenderer` presently only draws transparent images when `transferFromImageBitmap()` is used https://bugzilla.mozilla.org/show_bug.cgi?id=1590030. That fact is what led to reviewing the current WPT tests for `OffscreenCanvas` and noticing that `getContext()` is called twice, for no immediately clear reason where it only takes one or no calls to determine if `2d` context is defined.

**Comment by AmeliaBR** [comment]
I don't see a problem with using an assert to confirm that offscreen canvas 2D context exists as a constructor in the global scope, but  I think that's a separate test from confirming that it can be initialized correctly.

However, I agree that there doesn't seem to be a reason to create two distinct offscreenCanvas objects, and two distinct 2D context objects, just to test that one of those contexts is non-null.

I will say that, as I read the [current spec text](https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-getcontext), it is pretty clear that when a canvas with a `getContext()` method is supported, the correct behavior for an unsupported context type is to return `null`.  But if a browser is returning something else (e.g., undefined, or throwing an error), that needs to be detected as a separate test, with clear error message.

Anyway, unassigning myself in hopes that someone else will take a look!

PS @guest271314, could you update the PR to fix the merge conflicts related to the async test changes.

**Comment by guest271314** [comment]
@AmeliaBR 

> PS @guest271314, could you update the PR to fix the merge conflicts related to the async test changes.

Can you kindly advise explicitly what needs to be done?

**Comment by jdm** [comment]
@guest271314 You need to fetch the latest master branch from the upstream repository, then rebase your branch on top of those changes and fix the merge conflicts.

**Comment by guest271314** [comment]
> @guest271314 You need to fetch the latest master branch from the upstream repository, then rebase your branch on top of those changes and fix the merge conflicts.
@jdm 

Am not sure what "rebase" means. Do you mean delete and clone the entire repository again? Will that affect this PR https://github.com/web-platform-tests/wpt/pull/20776?

**Comment by jdm** [comment]
Here are two references that look like they explain the concept of rebasing a branch in git:
https://benmarshall.me/git-rebase/
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by AmeliaBR** [comment]
> Am not sure what "rebase" means. Do you mean delete and clone the entire repository again?

No, you shouldn't have to do that! And you don't even have to [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) if that's too confusing, you can [merge](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) in the master branch with a separate merge commit; they can be “squashed” together when the PR is merged into the main repo.

At the bottom of this page, GitHub will have a warning "This branch has conflicts that must be resolved."

There will be a "resolve conflicts" button beside it. It's disabled for me, but if it's active for you, [see these help instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github).

If that's not an option, you'll need to use git directly:

Selecting "use the command line" displays the necessary git commands for running in a terminal/command prompt on your computer (after installing git, if you need to).  Because of the conflicts, the merge will create a file with both the old and new lines of code, separated by lines with `<<<<<` and `>>>>>`. You need to edit to remove the incorrect lines and those separator lines, before retrying the merge commit. [more details](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line)

You can also do this in most desktop git apps, but the details will be specific to that app.

If you're still lost, let us know & someone else can work on it (assuming you checked ["allow edits from project maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).

**Comment by guest271314** [comment]
@AmeliaBR 

Clicked "Resolve conflicts", twice. Still reading the links. Yes, edits from maintainers is checked. What specifically needs to be deleted?

**Comment by guest271314** [comment]
What is the conflict? 

What needs to be edited or deleted?

```
<<<<<<< guest271314-patch-1
  var osc2D = "OffscreenCanvasRenderingContext2D";
  assert_own_property(globalThis, osc2D, osc2D + " is defined");
=======

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');

var offscreenCanvas2 = new OffscreenCanvas(100, 50);
_assertDifferent(offscreenCanvas2.getContext('2d'), null, "offscreenCanvas2.getContext('2d')", "null");
>>>>>>> master
```

**Comment by jdm** [comment]
The code that you added is after the >>> and before the ===. The code that exists on the upstream master branch is after the === and before the <<<. It's up to you as the author of your changes to determine if your code requires any modification based on the most recent code from upstream. You should remove any lines that do not belong in the file.

**Review by jdm — COMMENTED** [review]
One thing that concerns me is the `<!-- DO NOT EDIT! This test has been generated by tools/gentest.py. -->` header in this test.

**Comment by guest271314** [comment]
> One thing that concerns me is the `<!-- DO NOT EDIT! This test has been generated by tools/gentest.py. -->` header in this test.

What does that mean? 

Is the inference that the test should not ever be edited by a PR?

**Comment by guest271314** [comment]
@jdm The same code which "generated" 

```
var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');
```

for no apparent reason left us a note to not edit the code?

**Comment by jdm** [comment]
That test file is generated from [this yaml](https://github.com/web-platform-tests/wpt/blob/84da29d5c8d721647133da9c87fb8399c4a9d2b6/offscreen-canvas/tools/tests2d.yaml#L9364-L9371) by running [build.sh](https://github.com/web-platform-tests/wpt/blob/master/offscreen-canvas/tools/build.sh).

**Comment by guest271314** [comment]
@jdm 

That does not answer the questions of how this code


```

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');
```
got "generated" at all from the first link, and what the purpose of the code is?

Nor does that answer the question if PR's are forbidden to edit that specific file based on a comment header, where the generated test includes code that serves no clear purpose, and this PR adds code to actually test for the constructor, without modifying any of the code that serves no clear purpose?

**Comment by jdm** [comment]
Someone wrote that code and put it in the yml file. Instead of editing the generated test file, you will want to edit the yml file and run build.sh to regenerate the test file.

**Comment by jdm** [comment]
My mistake, the code you are concerned about comes from the [test template](https://github.com/web-platform-tests/wpt/blob/84da29d5c8d721647133da9c87fb8399c4a9d2b6/offscreen-canvas/tools/templates.yaml#L21-L22) that is used when generating each of the tests.

**Comment by jdm** [comment]
If you do not believe the test file should contain that generated code, you will need to remove the yml block that generates that test file and turn it into a hand-written test by removing the header that says not to modify it. This will ensure that any future changes to that file will not be overwritten when regenerating tests.

**Comment by AmeliaBR** [comment]
Well, this starts to explain some of the issues with this file. The JS code is weird and redundant because it's defined in text blocks in two completely separate YAML files! Ugh! This is not easy to review at all.

**Pull request closed without merging**
