### PR TITLE
Fix expectations for multiTouchPointsWithPause.html

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
As far as I can tell, these tests pass with db7735a94c60d9b04d80035d76a723762de38c5c reverted. @gsnedders - please review. I will revert the wptrunner.py change before landing.

**Comment by gsnedders** [comment]
@stephenmcgruer These were intermittent failures, and I'd rather hold off till we can at least revert this if need be (I'll be offline from this evening for about 24 hours).

**Comment by jgraham** [comment]
Please remove the do not merge commit

**Comment by stephenmcgruer** [comment]
@jgraham : Done

**Review by jgraham — APPROVED** [review]

**Pull request merged**
