### PR TITLE
Split up editing/run/* with `variant`

### PR DESCRIPTION
**Pull request by zcorpan**
Part of #11269.

### CODE REVIEW

**Comment by Ms2ger** [comment]
```
 1:04.86 TEST_START: /editing/run/backcolor.html
 1:05.17 pid:5269 JavaScript error: http://web-platform.test:8000/editing/include/tests.js, line 5610: ReferenceError: subsetTest is not defined
 1:05.23 TEST_STATUS: Test OK. Subtests passed 0/1. Unexpected 1
backcolor - HTML editing conformance tests
------------------------------------------
Expected PASS, got FAIL
ReferenceError: subsetTest is not defined
```

**Comment by zcorpan** [comment]
Oops, fixed.

**Comment by zcorpan** [comment]
Guessing CI failed because of too many tests being changed.

**Comment by foolip** [comment]
The Firefox job failed because "Log reached capacity (3145728 bytes); output disabled." and then "No output has been received in the last 10m0s", which is possibly because of https://github.com/web-platform-tests/wpt/issues/12166.

Chrome *also* failed in this way. We just have too much output. @jugglinmike FYI.

**Review by foolip — APPROVED** [review]

**Pull request merged**
