### PR TITLE
Make `internalId` integer

### PR DESCRIPTION
**Pull request by sadym-chromium**
Align WPT with [the specification](https://w3c.github.io/webdriver-bidi/#type-script-RemoteValue): `script.InternalId = js-uint;`.

### CODE REVIEW

**Comment by whimboo** [comment]
So that was an oversight on our side then. We have it implemented as string given that all the other id related fields are of type `string`. Generating unique numbers will be harder. So maybe we should change it to string type as well in the spec to be compliant with the other id's?

@jgraham what do you think? Is that fine with you?

**Comment by juliandescottes** [comment]
Good find

> So that was an oversight on our side then. We have it implemented as string given that all the other id related fields are of type `string`. Generating unique numbers will be harder. So maybe we should change it to string type as well in the spec to be compliant with the other id's?

I think this id only has to be unique per serialization (ie per serializationMap), and not globally? In that case, it should be relatively easy to do, in case we want to keep js-uint here.

**Comment by sadym-chromium** [comment]
> I think this id only has to be unique per serialization (ie per serializationMap), and not globally? In that case, it should be relatively easy to do, in case we want to keep js-uint here.

Yes, `internalId` only has to be unique per serialization.

**Comment by whimboo** [comment]
Given that all the other ids that we use are UUIDs I would personally find it better to also align the `internalId` appropriately.

**Comment by sadym-chromium** [comment]
> Given that all the other ids that we use are UUIDs I would personally find it better to also align the `internalId` appropriately.

String is more preferable over UUID from our side

**Comment by whimboo** [comment]
> String is more preferable over UUID from our side

Right which is type `text` as well. So yes we could do that.

**Pull request closed without merging**
