### PR TITLE
Move orphaned role tests to tentative.

### PR DESCRIPTION
**Pull request by cookiecrook**
Closes https://github.com/web-platform-tests/interop-accessibility/issues/120

### CODE REVIEW

**Review by spectranaut — APPROVED** [review]
I hate to push back after you did all this work, and ultimately I defer to you here, but I think make so many tentative files makes it hard to see how the the browsers are doing at a glance: https://wpt.fyi/results/wai-aria/role?label=pr_head&max-count=1&pr=46769

For this reason, I think one tentative file per directory might make more sense. It might also be less to maintain, if we want to move things from tentative back into the original test file.

But again, up to you, if you prefer the tests are organized this way -- go ahead and merge!

**Comment by cookiecrook** [comment]
> I hate to push back after you did all this work, and ultimately I defer to you here, but I think make so many tentative files makes it hard to see how the the browsers are doing at a glance: https://wpt.fyi/results/wai-aria/role?label=pr_head&max-count=1&pr=46769

Can't you get the "at a glance" view you want from a higher level directory view like this?
https://wpt.fyi/results/wai-aria

**Comment by cookiecrook** [comment]
but even in the sub level view, the last row indicates the total percentage

**Comment by spectranaut** [comment]
> > I hate to push back after you did all this work, and ultimately I defer to you here, but I think make so many tentative files makes it hard to see how the the browsers are doing at a glance: https://wpt.fyi/results/wai-aria/role?label=pr_head&max-count=1&pr=46769
> 
> Can't you get the "at a glance" view you want from a higher level directory view like this? https://wpt.fyi/results/wai-aria

I see, you are right!

**Pull request merged**
