### PR TITLE
Modified and improved considerably calc-serialization-002.html

### PR DESCRIPTION
**Pull request by TalbotG**
The modifications and improvements are related to discussion we have (and are still having) in issue 3741
https://github.com/w3c/csswg-drafts/issues/3741

### CODE REVIEW

**Comment by TalbotG** [comment]
**Elika and/or Tab should be reviewing this Pull Request.**

One sub-test should trigger feedbacks. At line 87:

`  verifySerialization("calc(8pt + calc(9rem + 10px))", "calc(8pt + 10px + 9rem)", "testing calc(8pt + calc(9rem + 10px))");`

How to serialize `calc(8pt + calc(9rem + 10px))` ? I see 3 possible answers, after carefully reading the current spec:

a) `calc(8pt + calc(10px + 9rem)) `
b) `calc(8pt + (10px + 9rem))` 
c) `calc(8pt + 10px + 9rem) `

**Comment by TalbotG** [comment]
> I think flattening nested calc() to parentheses seems reasonable. (...) I agree with this.

coming from
[Re: [css-values] Serialization of nested calc()](https://lists.w3.org/Archives/Public/www-style/2016Apr/0238.html)
So, possible answer a) is ruled out. There is still b) and c) left.

**Review by fantasai — APPROVED** [review]

**Comment by fantasai** [comment]
I think this test needs to be largely rewritten after the changes to serialization rules (which, for better or worse, seems like they collapse all the absolute units at specified value time). But the changes in this PR are good, so my suggestion is to merge this and then apply the serialization rule changes in a separate PR.

**Comment by TalbotG** [comment]
New calc-serialization test:

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/calc-serialization-002-new.html

**Comment by TalbotG** [comment]
In a few min., I will be git-submitting the new calc-serialization-002 test. It will have to be reviewed since it is an entirely updated test.

**Comment by TalbotG** [comment]
I will create another pull request as I do not understand what to do and how to fix whatever needs to be fixed here.

**Pull request closed without merging**
