### PR TITLE
[webdriver-client] Use the type field to differentiate message types

### PR DESCRIPTION
**Pull request by whimboo**
These changes are a follow-up from https://github.com/w3c/webdriver-bidi/pull/484. Specfic tests aren't really needed but the BiDi client can handle the various messages by type now instead of checking arbitrary fields.

Note that merging this PR might be blocked because [newer chromedriver binaries cannot be downloaded](https://github.com/web-platform-tests/wpt/issues/40119). At least that is happening for me locally and this change would break my local testing.

### CODE REVIEW

**Comment by whimboo** [comment]
An additional code review from Google folks would be good. We already did one downstream at https://phabricator.services.mozilla.com/D185173.

CC @mathiasbynens, @jrandolf

**Review by mathiasbynens — APPROVED** [review]

**Comment by whimboo** [comment]
Changing the client code only doesn't trigger any BiDi tests. As such I just pushed a small change to a BiDi event test to verify the functionality. This 2nd commit is not for landing and will be removed once the tests have been run.

**Comment by whimboo** [comment]
@mathiasbynens the modified test [times out with chromedriver](https://community-tc.services.mozilla.com/tasks/UUUGceDgRKSpS84Cpqyl-Q/runs/0/logs/public/logs/live.log#L669) which indicates that the type field is not correctly handled and sadly the BiDi client fails to report correctly if an async method fails and as such hangs. For [Firefox it works correctly](https://community-tc.services.mozilla.com/tasks/fbOxtp7fTM6OCAf4DFUCyw/runs/0/logs/public/logs/live.log#L546) because support for `type` does exist.

In the following line it can be seen that [a different chromedriver is downloaded](https://community-tc.services.mozilla.com/tasks/UUUGceDgRKSpS84Cpqyl-Q/runs/0/logs/live/public/logs/live.log#L586) which is most likely pre 115 even. So it really seems all kinda busted and we should not merge this PR until the download situation for chromedriver has been solved.

Can you please check? It would be good to get this solved quickly.

**Comment by whimboo** [comment]
Actually it downloads 116 from the old location:

> Starting ChromeDriver 116.0.5792.0 (23143cc366fb10aa0e95a2fb3913797e5212b204-refs/heads/main@{#1148911}) on port 33271

**Comment by whimboo** [comment]
I force pushed an update after a rebase so that the Firefox Stability job will pass as well.

**Review by jrandolf — APPROVED** [review]

**Comment by jrandolf** [comment]
@whimboo The `type` field was added into Chromedriver 117 which is why it's not visible at the moment.

**Review by jgraham — APPROVED** [review]

**Comment by whimboo** [comment]
The fix to download chromedriver has landed. I've rebased the PR and hopefully it will pass now.

**Comment by whimboo** [comment]
@jgraham the stability job for Firefox is failing here. It tries to [start geckodriver on a port which is already taken](https://community-tc.services.mozilla.com/tasks/dQfGtDVcTfqVboTitku-uw/runs/0/logs/live/public/logs/live.log#L568-576) and as such only the first test out of 10 can be run successful. Could you please check?

**Pull request merged**
