### PR TITLE
Add infrastructure test for uncaught exception

### PR DESCRIPTION
**Pull request by foolip**
To make current behavior clear.

This would change with https://github.com/web-platform-tests/wpt/pull/11024.

### CODE REVIEW

**Comment by foolip** [comment]
It looks like I got the expectations right, the Azure Pipelines failure is another test, attempting to fix in https://github.com/web-platform-tests/wpt/pull/18795.

**Comment by foolip** [comment]
Haha, neat, looks like this PR revealed a race condition on GitHub whereby it was was possible to add @jgraham for review twice :)

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
I can only review it once, however ;)

**Comment by foolip** [comment]
@jgraham thanks thanks twice anyway!

**Comment by foolip** [comment]
Oops, turns out there are lots of tests like this in resources/test/tests/functional/.

@jugglinmike updating the expections of those is even trickier than the .ini expectations we use for infrastructure/. Do those tests do anything that we couldn't just as well test under infrastructure/?

**Comment by jugglinmike** [comment]
@foolip They do test additional concerns. They verify assertion messages and the description of the harness status. I support relocating the tests to the `infrastructure/` directory, but I recommend reformatting them so they can be executed as traditional testharness.js tests. Specifically: verifying failures and timeouts via an instance of testharness.js running in an iframe, and using the framework's callback API to verify the result. [This test for "exceptional cases"](https://github.com/web-platform-tests/wpt/blob/4ca7001dcf130f8dad3d831acf0336d889e5c49a/resources/test/tests/unit/exceptional-cases.html) demonstrates that approach.

**Comment by foolip** [comment]
Some of what they test can already be tested by .ini files, as I did here. If we added assertion message patterns or something like that to the metadata, would that be enough to use a single mechanism?

A benefit of the .ini files is that in principle they could be generated by tooling, where updating the test expectations in resources/test/tests/functional/ is harder to see how to automate.

**Comment by jugglinmike** [comment]
You're right: extending the .ini file format would let us reach equivalent coverage using an existing mechanism. I wouldn't recommend it, though. [Assertion messages are not considered stable](https://github.com/web-platform-tests/wpt/issues/17974), so we shouldn't support that practice generally.

Also, specifying expectations through .ini files is a little indirect. This is usually justified by the ability to express different expectations for different browsers/platforms. In this case, the expectations are not browser- or platform-dependent, so there's less of a reason to tolerate the indirection.

In my previous comment, I suggested testing timeouts and assertion failures using nested testharness.js instances. Since the tests would otherwise be "traditional" testharness.js tests, this approach should work without any modification to the infrastructure. Is there some reason we shouldn't refactor the tests along those lines?

**Comment by foolip** [comment]
The thing that isn't stable is error messages originating from the browser. We can test this in a way that doesn't involve that, and then there shouldn't be a problem.

**Comment by foolip** [comment]
> Is there some reason we shouldn't refactor the tests along those lines?

Just to take the most direct approach possible. Anything that can be written as a plain testharness.js test like the existing tests in infrastructure/ I'd like to be plain tests. Some things will probably be better suited to unit tests than full integration tests, and that perhaps can be achieved by loading testharness.js in an iframe.

**Pull request merged**
