### PR TITLE
Webdriver test fixes to work with current wdclient

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5022)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205855496)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 3fe0964d39062430fa157ce69bef767d7cf8947e
Using browser at version BuildID 20170225110158; SourceStamp f36062d04d165f6f6e781cf0633ffcbbebe6c273
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205855497)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 3fe0964d39062430fa157ce69bef767d7cf8947e
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
No tests run.

**Review by lukeis — APPROVED** [review]
lgtm

**Pull request merged**
