### PR TITLE
[css-contain] the contain property is not animatable

### PR DESCRIPTION
**Pull request by frivoal**
Tests for https://github.com/w3c/csswg-drafts/issues/2737

### CODE REVIEW

**Review by birtles — APPROVED** [review]
I'm not so familiar with css-contains but from what I understand it looks good to me.

Also I'm not sure how well the w3c reftest harness waits for animations (I always just write testharness tests), so might it be worth adding `reftest-wait` then dropping it in `requestAnimationFrame` callback?

For css-logical we just used the animation API:
https://github.com/web-platform-tests/wpt/blob/3c6c9350988f98c8fac94fab8174bc4729cd6755/css/css-logical/animation-001.html#L302-L321

**Comment by frivoal** [comment]
@birtles 

> Also I'm not sure how well the w3c reftest harness waits for animations

Is there anything to wait for? the animation is paused, and the initial state is supposed to apply immediately.

The reftest system wouldn't wait for an animation to complete, so if that's what we wanted, we'd need `refttest-wait` followed signaling when it is ready, but with this test, I believe the initial state should already be correct.

Am I missing something?

**Comment by birtles** [comment]
> Is there anything to wait for? the animation is paused, and the initial state is supposed to apply immediately.

Right, the `animation-*` properties will be resolved immediately generating a new animation. In Gecko at least we'll restyle again immediately applying the starting values of the animation even while the animation has yet to begin running. The spec doesn't strictly require this (only the opposite, that an animation does _not_ affect computed style outside of when it is applied) but hopefully everyone does that. There was certainly something in this area where Edge was different but I suspect it was specific to compositor animations.

> The reftest system wouldn't wait for an animation to complete, so if that's what we wanted, we'd need refttest-wait followed signaling when it is ready, but with this test, I believe the initial state should already be correct.
> 
> Am I missing something?

No, my initial reaction came from working on SMIL reftests where the animation doesn't start until onload (hence you need to remove `reftest-wait` on onload). I wasn't suggesting we wait for the animation to end, just that if not all user agents are applying the animated style on the same frame, we might need to wait for the next animation frame.

**Comment by frivoal** [comment]
I think it's fine. If it turns out someone does it differently and fail the test due to that, they can open a bug at that point and we'll look into it then.

**Pull request merged**
