### PR TITLE
[docs] Remove ambiguity

### PR DESCRIPTION
**Pull request by jugglinmike**
@foolip I couldn't infer what you meant from context. Would you prefer to reword this clause rather than remove it?

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by foolip** [comment]
@jugglinmike I mean that if you're only going to run on of the two Safaris then only one of the steps will be needed. But this LGTM anyway, people can probably figure out what steps they need.

**Review by gsnedders — APPROVED** [review]
I don't think that clause really adds anything, and if it confused @jugglinmike we should probably get rid of it.

**Comment by jugglinmike** [comment]
@foolip Ah, maybe the clause is missing a single word: "in which case only **one** step is needed." However, that is still a little confusing since there are multiple steps, each with two substeps. It would be more like, "only one version of each step is needed," but the substeps make that clear.

**Comment by foolip** [comment]
Sure, let's just drop this.

**Pull request merged**
