### PR TITLE
Release the mozlog lock when starting test runner processes

### PR DESCRIPTION
**Pull request by jdm**
This is a follow up to #17433 which addresses a deadlock observed in Servo's CI in a PR that introduces the first fuzzy reftest results. The thread responsible for interpreting the pixels in the images deadlocks when initializing PIL which makes logging calls. Since this is in a separate process from the main wptrunner overseer, it seems logical that ensuring the mutex is released after spawning the test runner processes would make the deadlock disappear. I was able to successfully run the reftest in question many times in a row without deadlocking after making this change, whereas previously I would hit it on the first or second try.

### CODE REVIEW

**Comment by jdm** [comment]
cc @Hexcles 
r? @jgraham

**Comment by jdm** [comment]
Turns out jgraham is gone for a while. @Hexcles, can you review this change?

**Review by Hexcles — APPROVED** [review]
The workaround in `tools/serve` also reloads the `logging` module. Is that not necessary?

Otherwise, this is indeed the same as the other workaround and the explanation makes sense to me (releasing a mutex in subprocess).

**Comment by jdm** [comment]
@Hexcles testrunner.py does not already import the logging module, so I was unsure if I needed to import it in order to reload it. I admit that the details of how it's related escape me.

**Comment by jgraham** [comment]
God I hate multiprocessing.

**Pull request merged**
