### PR TITLE
Replace some assert_throws('Something', stuff) calls with assert_throws_dom

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This a piece-by-piece landing of #21350 due to the size of the original PR. Please excuse the email spam when wpt-pr-bot cc's you to this PR.

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@bzbarsky FYI

**Comment by stephenmcgruer** [comment]
Another resource/ test reverted; `resources/test/tests/unit/basic.html` (cc @bzbarsky )

**Comment by bzbarsky** [comment]
Yep, gotcha.

How do I run those tests locally?  They apparently don't get run in the Firefox CI.... :(

**Comment by stephenmcgruer** [comment]
> How do I run those tests locally?

Great question. I'm not sure offhand, I'll dig into it tomorrow and see. You can look at `tools/ci/tc/tasks/test.yml` to see what commands it runs for `resources/ tests` if you want to be eager ;)

**Comment by stephenmcgruer** [comment]
As for this PR, stability check failures are the expected flakes, and the browser diffs look good (no change in any). Merging!

**Comment by stephenmcgruer** [comment]
@bzbarsky following up on `resources/` tests, I believe running ./tools/ci/ci_resources_unittest.sh should work. It ultimately runs `tox` in the `resources/test` directory, so you could possibly just do that manually too (and thus filter to specific tests).

**Comment by bzbarsky** [comment]
@stephenmcgruer I tried running that and ran into the same problem I've run into every time I try to run these tests:
```
Exception: Could not start wptserve on http://web-platform.test:8000
```
@jgraham

**Comment by stephenmcgruer** [comment]
Do you have a server already running on port 8000?

**Comment by bzbarsky** [comment]
Nope.

**Comment by bzbarsky** [comment]
Ah, if I manually run `wpt serve` I at least get an actionable error message:
```
CRITICAL:web-platform-tests:Failed probing domain www1.xn--n8j6ds53lwwkrqhv28a.web-platform.test. Please ensure all the necessary WPT subdomains are mapped to a loopback device in /etc/hosts. See https://github.com/web-platform-tests/wpt#running-the-tests for instructions.
```
Lemme see about that...

**Comment by bzbarsky** [comment]
Yeah, there we go.  Doing the hosts file thing gets me up and running.

**Comment by bzbarsky** [comment]
I filed https://github.com/web-platform-tests/wpt/issues/21613 on improving the error reporting.

**Pull request merged**
