### PR TITLE
Canvas: no need for assert_throws(null, ...)

### PR DESCRIPTION
**Pull request by annevk**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5400)

### CODE REVIEW

**Comment by annevk** [comment]
(This PR doesn't work as-is, someone has to run the corresponding script. Created for #5317.)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219188514)

# Firefox (nightly channel) #
Testing web-platform-tests at revision aa954efbbd5495437bd077e685c7827e14d331ca
# Firefox (nightly channel) #
Testing web-platform-tests at revision aa954efbbd5495437bd077e685c7827e14d331ca
Using browser at version BuildID 20170405115424; SourceStamp b043233ec04f06768d59dcdfb9e928142280f3cc
Starting 10 test iterations
Using browser at version BuildID 20170405115424; SourceStamp b043233ec04f06768d59dcdfb9e928142280f3cc
Starting 10 test iterations
No tests run.
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/219188515)

# Chrome (unstable channel) #
Testing web-platform-tests at revision aa954efbbd5495437bd077e685c7827e14d331ca
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
@annevk seems like there's no need to run the script given as you suspected it doesn't change anything (Travis would've failed if it did change anything)

**Pull request merged**
