### PR TITLE
Add tests for "script.callFunction" for deserialization of complex objects with container value fields.

### PR DESCRIPTION
**Pull request by lutien**
- extends `test_remote_value_argument` with more object types

These code was already reviewed in Mozilla repo (https://phabricator.services.mozilla.com/D158032), after being reviewed here, it will be synced from there.

### CODE REVIEW

**Comment by lutien** [comment]
Hey @sadym-chromium, when you have a minute, could you have a look?

**Comment by sadym-chromium** [comment]
on it

**Review by sadym-chromium — APPROVED** [review]
Cannot run it in Chromium yet, but eyeballing didn't show any problems.

**Comment by lutien** [comment]
Thanks a lot for the review! Going to close it here and land in Mozilla repo.

**Comment by lutien** [comment]
This tests will be synced via https://github.com/web-platform-tests/wpt/pull/36195

**Pull request closed without merging**
