### PR TITLE
Remove outdated copyright notices / license claims

### PR DESCRIPTION
**Pull request by foolip**
This removes most references to the W3C Test Suite License. In
https://github.com/web-platform-tests/wpt/pull/11191, everything
originally contributed under that license was relicensed to the 3-clause
BSD license in LICENSE.md.

All the modified files existed at the time at their current paths, with
the exception of html/canvas/tools/ which was then 2dcontext/tools/, but
the same files were there.

### CODE REVIEW

**Review by KG-G-W-A-BOLES-PHD-ENG-INC — COMMENTED** [review]
Yeah when are you all going to start using my real name Walter Allen Boles, Original Master GATOR BOLES LLC, JSON BOLES

**Review by annevk — APPROVED** [review]
Do you think we can remove the year from LICENSE.md? (Now tracked in #28682.)

**Comment by foolip** [comment]
> Do you think we can remove the year from LICENSE.md?

I think so, but I'd ask @web-platform-tests/wpt-core-team for concerns.

Speaking of which... @web-platform-tests/wpt-core-team here's a PR to clarify the licensing of a bunch of files in WPT. I'll leave this open until Friday April 30 to give you a chance to react if you disagree with this change.

**Review by sideshowbarker — APPROVED** [review]

**Comment by foolip** [comment]
It's Friday, merging!

**Pull request merged**
