### PR TITLE
`Window Handle` and `browsingContext` are interoperable

### PR DESCRIPTION
**Pull request by sadym-chromium**
Verify `Window Handle` and `browsingContext` are the very same in BiDi and Classic.

### CODE REVIEW

**Comment by whimboo** [comment]
@sadym-chromium I wonder if we could just have a new test for that interoparability checks within the corresponding BiDi module. So in this case `bidi/browsing_context/classic_interop/window_handle.py`. That way the parts of the spec that are getting tested are right next to the other tests of that particular module. Then we can have different test modules as well for element id's and whatever else that we need. I would suggest a folder as well in case that there will be too many tests in a file and we might have to split it up. That way we would be in sync with the other folder organization. What do you think?

**Comment by sadym-chromium** [comment]
done

**Review by whimboo — APPROVED** [review]
I assume that we should further enhance this test module for "frame handles" and check that those are equal to the non top-level browsing context id. Note that `Execute Script` can return those similar to window instances with the `handle` as value.

In Firefox both fail right now so I'm ok with having such tests as a follow-up but if you feel strongly about them we could get them added right away as well.

Thanks!

**Review by whimboo — APPROVED** [review]
Looks good. We can add more tests once the underlying serialization of window and frame will work. I'll have something for Firefox ready in the next weeks.

**Pull request merged**
