### PR TITLE
Add codecov configuration.

### PR DESCRIPTION
**Pull request by jgraham**
Ignore cases where the coverage doesn't change. Ignore all paths not
under tools.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5623)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5623/)

**Comment by jgraham** [comment]
@gsnedders I'm not really sure if this does the right thing.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223994034)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223994036)

# Firefox (nightly channel) #
Testing web-platform-tests at revision eb49527206956b289b23c917dab1b62a4d148332
Using browser at version BuildID 20170420100256; SourceStamp 27311156637f9b5d4504373967e01c4241902ae7
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223994037)

# Chrome (unstable channel) #
Testing web-platform-tests at revision eb49527206956b289b23c917dab1b62a4d148332
Using browser at version 59.0.3071.9 dev
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
Uh, why did we get a coverage report? Um…

**Comment by jgraham** [comment]
Hah.

**Review by Andrewjlucas1 — COMMENTED** [review]
#26030

**Pull request merged**
