### PR TITLE
A named properties object returns named properties from OwnPropertyKeys.

### PR DESCRIPTION
**Pull request by petervanderbeken**
A Window's named properties object doesn't have a custom `[OwnPropertyKeys]` (see https://webidl.spec.whatwg.org/#named-properties-object), so it uses [`OrdinaryOwnPropertyKeys`](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys) which simply adds all property keys. So `[OwnPropertyKeys]` on a named properties object returns all named properties and `@@toStringTag`. `Object.getOwnPropertyNames` then filters out the strings, leaving the named properties.

### CODE REVIEW

**Comment by domenic** [comment]
I'm not sure I follow this. The [default `[[OwnPropertyKeys]]()`](https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) collects keys using language like

> For each own [property key](https://tc39.es/ecma262/#sec-object-type) P of O

But there are actually no own property keys of the named properties object. All of its properties are "virtual", i.e., generated by a custom `[[GetOwnProperty]]()` implementation. It doesn't have anything which the above would successfully loop over, in other words.

It may or may not have a `Symbol.toStringTag` own property, depending on how you interpret

> The [class string](https://webidl.spec.whatwg.org/#dfn-class-string) of a [named properties object](https://webidl.spec.whatwg.org/#dfn-named-properties-object) is the concatenation of the [interface](https://webidl.spec.whatwg.org/#dfn-interface)'s [identifier](https://webidl.spec.whatwg.org/#dfn-identifier) and the string "Properties".

which isn't super-clear because of how the "class string" definition is sort of retrofitted.

But I can't see any evidence that the object itself has own property keys. So I think this change is incorrect.

**Comment by petervanderbeken** [comment]
> I'm not sure I follow this. The [default `[[OwnPropertyKeys]]()`](https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) collects keys using language like
> 
> > For each own [property key](https://tc39.es/ecma262/#sec-object-type) P of O
> 
> But there are actually no own property keys of the named properties object. All of its properties are "virtual", i.e., generated by a custom `[[GetOwnProperty]]()` implementation. It doesn't have anything which the above would successfully loop over, in other words.

So you're saying that even though `[[GetOwnProperty]]()` returns a property for a property key, the object doesn't actually _have_ an own property with that key? 

> It may or may not have a `Symbol.toStringTag` own property, depending on how you interpret

I don't think it can not have a `Symbol.toStringTag` own property.

> If an object has a [class string](https://webidl.spec.whatwg.org/#dfn-class-string) classString, then the object must, at the time it is created, have a property whose name is the [@@toStringTag](https://tc39.es/ecma262/#sec-well-known-symbols) symbol with PropertyDescriptor{[[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true, [[Value]]: classString}

Named properties objects fall back to [OrdinaryGetOwnProperty](https://tc39.es/ecma262/#sec-ordinarygetownproperty) for this property, which explicitly checks for an own property with a key.

**Comment by domenic** [comment]
> So you're saying that even though `[[GetOwnProperty]]()` returns a property for a property key, the object doesn't actually _have_ an own property with that key?

Correct. Another example of this is if you create a `Proxy` object wrapping an an empty target object. If you leave its `ownKeys` trap as the default, it will try to find actual own keys, of which there are none. But you can override its `getOwnPropertyDescriptor` trap to return whatever you want.

**Comment by petervanderbeken** [comment]
But for proxies that behaviour is defined exactly in the various internal methods, that seems entirely different.

The named properties object uses `OrdinaryOwnPropertyKeys`, which returns _own property keys_. That's worded weirdly, objects do not have property keys, they have properties and those properties have keys. For example, `[[GetOwnProperty]]` is the internal method that returns [**the own property of this object whose key is propertyKey**](https://tc39.es/ecma262/#table-essential-internal-methods). So I don't think I agree with your interpretation that the object doesn't have an own property with that property key, or that it doesn't have _own property keys_.

If we do want this behaviour for the named properties object (I'm not sure why anyway), it should probably have its own `[[OwnPropertyKeys]]` internal method.

**Comment by domenic** [comment]
> But for proxies that behaviour is defined exactly in the various internal methods, that seems entirely different.

I don't think the case is at all different. The internal method of the named properties object are fully defined.

> For example, `[[GetOwnProperty]]` is the internal method that returns [**the own property of this object whose key is propertyKey**](https://tc39.es/ecma262/#table-essential-internal-methods).

That's the definition of OrdinaryGetOwnProperty. But the named properties object does not use OrdinaryGetOwnProperty. Instead it synthesizes totally different descriptors to return.

> If we do want this behaviour for the named properties object (I'm not sure why anyway), it should probably have its own `[[OwnPropertyKeys]]` internal method.

It's not necessary. It would just do what OrdinaryOwnPropertyKeys does anyway, and return only the `@@toStringTag`.

**Comment by annevk** [comment]
I tend to agree with @domenic. Just because `[[GetOwnProperty]]` returns something, doesn't mean that would be matched by `OrdinaryOwnPropertyKeys`. Because the latter is not defined in terms of the former. And the former can definitely "lie" or generate virtual things.

**Comment by petervanderbeken** [comment]
> > For example, `[[GetOwnProperty]]` is the internal method that returns [**the own property of this object whose key is propertyKey**](https://tc39.es/ecma262/#table-essential-internal-methods).
> 
> That's the definition of OrdinaryGetOwnProperty.

Actually it isn't, it's the generic description of the `[[GetOwnProperty]]` internal method.

**Comment by petervanderbeken** [comment]
Also, why exactly would we want this behaviour for the named properties object? What's the benefit?

**Comment by bakkot** [comment]
I agree with the interpretation of @domenic and @annevk.

To be precise, an object is logically a collection of properties. The default implementations of meta-object protocol methods like `[[GetOwnProperty]]` are defined in terms of that collection, but exotic objects a named properties object can override those methods to have arbitrary other behaviors up to the limits of the [essential invariants](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-invariants-of-the-essential-internal-methods). And the default behavior of `[[OwnPropertyKeys]]` reflects _that collection_, not whatever `[[GetOwnProperty]]` reports. The description of `[[OwnPropertyKeys]]` you've quoted above is informative, not normative.

(That said, I agree it's kind of weird not to also customize `[[OwnPropertyKeys]]`.)

**Comment by domenic** [comment]
Closing since this is incorrect, and per https://github.com/whatwg/webidl/pull/1285 the spec has been updated to be clearer about why.

**Pull request closed without merging**
