### PR TITLE
Fetch: use a less confusing value to pass to Response.redirect()

### LINKED ISSUE #6144: Improper use of Response.redirect in fetch/api/response/response-consume-stream.html
fetch/api/response/response-consume-stream.html improperly uses Response.redirect in the following code:
```
promise_test(function(test) {
    assert_equals(Response.redirect(301).body, null);
}, "Getting a redirect Response stream");
```
According to the standard, a url must be passed to the function.
 [NewObject] static Response redirect(USVString url, optional unsigned short status = 302);

### PR DESCRIPTION
**Pull request by annevk**
Fixes #6144.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253631788)

# Firefox (nightly) #
Testing web-platform-tests at revision 0d2e7c5063895a172ffcb2a3df14cd762691fa16
Using browser at version BuildID 20170714100217; SourceStamp 67cd1ee26f2661fa5efe3d952485ab3c89af4271
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6555/fetch/api/response/response-consume-stream.html">/fetch/api/response/response-consume-stream.html</a></summary>


|                         Subtest                          | Results |                                Messages                               |
|----------------------------------------------------------|---------|-----------------------------------------------------------------------|
|                                                          | OK      |                                                                       |
| `Read empty text response's body as readableStream`      | FAIL    | `response.body is undefined`                                          |
| `Read empty blob response's body as readableStream`      | FAIL    | `response.body is undefined`                                          |
| `Read blob response's body as readableStream`            | FAIL    | `response.body is undefined`                                          |
| `Read text response's body as readableStream`            | FAIL    | `response.body is undefined`                                          |
| `Read URLSearchParams response's body as readableStream` | FAIL    | `response.body is undefined`                                          |
| `Read array buffer response's body as readableStream`    | FAIL    | `(new Response(...)).body is undefined`                               |
| `Read form data response's body as readableStream`       | FAIL    | `response.body is undefined`                                          |
| `Getting an error Response stream`                       | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined` |
| `Getting a redirect Response stream`                     | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253631789)

# Sauce (safari) #
Testing web-platform-tests at revision 0d2e7c5063895a172ffcb2a3df14cd762691fa16
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6555/fetch/api/response/response-consume-stream.html">/fetch/api/response/response-consume-stream.html</a></summary>


|                       Subtest                       | Results |             Messages            |
|-----------------------------------------------------|---------|---------------------------------|
|                                                     | ERROR   |                                 |
| `Read empty text response's body as readableStream` | FAIL    | `Can't find variable: Response` |
| `Read empty blob response's body as readableStream` | FAIL    | `Can't find variable: Response` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253631795)

# Chrome (unstable) #
Testing web-platform-tests at revision 0d2e7c5063895a172ffcb2a3df14cd762691fa16
Using browser at version 61.0.3153.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6555/fetch/api/response/response-consume-stream.html">/fetch/api/response/response-consume-stream.html</a></summary>


|                         Subtest                          | Results |                                        Messages                                       |
|----------------------------------------------------------|---------|---------------------------------------------------------------------------------------|
|                                                          | OK      |                                                                                       |
| `Read empty text response's body as readableStream`      | PASS    |                                                                                       |
| `Read empty blob response's body as readableStream`      | PASS    |                                                                                       |
| `Read blob response's body as readableStream`            | PASS    |                                                                                       |
| `Read text response's body as readableStream`            | PASS    |                                                                                       |
| `Read URLSearchParams response's body as readableStream` | PASS    |                                                                                       |
| `Read array buffer response's body as readableStream`    | PASS    |                                                                                       |
| `Read form data response's body as readableStream`       | FAIL    | `assert_array_equals: Retrieve and verify stream lengths differ, expected 10 got 140` |
| `Getting an error Response stream`                       | PASS    |                                                                                       |
| `Getting a redirect Response stream`                     | FAIL    | `assert_not_equals: got disallowed value undefined`                                   |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253631796)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 0d2e7c5063895a172ffcb2a3df14cd762691fa16

**Review by jdm — APPROVED** [review]

**Pull request merged**
