### PR TITLE
Fix #9012: Add an MP4 copy of images/pattern.png

### LINKED ISSUE #9012: Add pattern.mp4 video
See <https://github.com/w3c/web-platform-tests/pull/8950>.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #9012. Encoded using the baseline profile.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-15 15:33:06
Finished: 2018-01-15 15:40:41


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22794)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/329102505)

**Comment by Ms2ger** [comment]
Please also use `getVideoURI` in `2dcontext/imagebitmap/common.js`

**Comment by gsnedders** [comment]
@Ms2ger done

**Review by Ms2ger — APPROVED** [review]
Thanks!

**Pull request merged**
