### PR TITLE
Add .well-known/idp-proxy/OWNERS

### PR DESCRIPTION
**Pull request by zcorpan**
cc @hueniverse

### CODE REVIEW

**Comment by hueniverse** [comment]
Thanks, but I'll pass. Try @mnot.

**Comment by zcorpan** [comment]
@mnot are you OK with being listed in the OWNERS file here? It means you’ll get notified any time someone submits a PR with Media Capture tests, or changes to existing tests. And the tests could only be merged to the master branch after review from one of the OWNERS.

**Comment by mnot** [comment]
I think what you want is an owner per subdirectory; the mechanisms tested are going to diverge pretty widely.

**Comment by mnot** [comment]
I don't think I'm going to add much value there.

**Comment by zcorpan** [comment]
OK. Can you nominate someone else?

**Comment by mnot** [comment]
As I said, I think that ownership needs to be at a finer level than this directory.

**Comment by zcorpan** [comment]
Yes, I moved it to `.well-known/idp-proxy/OWNERS`.

**Comment by zcorpan** [comment]
@ekr would you be willing to be listed in the OWNERS file for `.well-known/idp-proxy`? It means you’ll get notified any time someone submits a PR. And the tests could only be merged to the master branch after review from one of the OWNERS.

**Review by nils-ohlmeier — APPROVED** [review]
LGTM

**Pull request merged**
