### PR TITLE
Payment request handlers

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239873755)

# Firefox (nightly) #
Testing web-platform-tests at revision 85f35381f238e8f748b37de45d2a193b7959787e
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6159/payment-request/payment-request-onshippingaddresschange-attribute.https.html">/payment-request/payment-request-onshippingaddresschange-attribute.https.html</a></summary>


|                                       Subtest                                        | Results |             Messages            |
|--------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                      | OK      |                                 |
| `onshippingaddresschange attribute is a generic handler for "shippingaddresschange"` | FAIL    | `PaymentRequest is not defined` |
| `onshippingaddresschange attribute is a handler for PaymentRequestUpdateEvent`       | FAIL    | `PaymentRequest is not defined` |
| `onshippingaddresschange attribute and listeners both work`                          | FAIL    | `PaymentRequest is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6159/payment-request/payment-request-onshippingoptionchange-attribute.https.html">/payment-request/payment-request-onshippingoptionchange-attribute.https.html</a></summary>


|                                      Subtest                                       | Results |             Messages            |
|------------------------------------------------------------------------------------|---------|---------------------------------|
|                                                                                    | OK      |                                 |
| `onshippingoptionchange attribute is a generic handler for "shippingoptionchange"` | FAIL    | `PaymentRequest is not defined` |
| `onshippingoptionchange attribute is a handler for PaymentRequestUpdateEvent`      | FAIL    | `PaymentRequest is not defined` |
| `onshippingoptionchange attribute and listeners both work`                         | FAIL    | `PaymentRequest is not defined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239873756)

# Sauce (safari) #
Testing web-platform-tests at revision a8be5ceab679293191d241d919a1bed9b67f4360
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6159/payment-request/payment-request-onshippingaddresschange-attribute.https.html">/payment-request/payment-request-onshippingaddresschange-attribute.https.html</a></summary>


|                                       Subtest                                        | Results |                Messages               |
|--------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                      | OK      |                                       |
| `onshippingaddresschange attribute is a generic handler for "shippingaddresschange"` | FAIL    | `Can't find variable: PaymentRequest` |
| `onshippingaddresschange attribute is a handler for PaymentRequestUpdateEvent`       | FAIL    | `Can't find variable: PaymentRequest` |
| `onshippingaddresschange attribute and listeners both work`                          | FAIL    | `Can't find variable: PaymentRequest` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6159/payment-request/payment-request-onshippingoptionchange-attribute.https.html">/payment-request/payment-request-onshippingoptionchange-attribute.https.html</a></summary>


|                                      Subtest                                       | Results |                Messages               |
|------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                    | OK      |                                       |
| `onshippingoptionchange attribute is a generic handler for "shippingoptionchange"` | FAIL    | `Can't find variable: PaymentRequest` |
| `onshippingoptionchange attribute is a handler for PaymentRequestUpdateEvent`      | FAIL    | `Can't find variable: PaymentRequest` |
| `onshippingoptionchange attribute and listeners both work`                         | FAIL    | `Can't find variable: PaymentRequest` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239873762)

# Chrome (unstable) #
Testing web-platform-tests at revision a8be5ceab679293191d241d919a1bed9b67f4360

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239873763)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision a8be5ceab679293191d241d919a1bed9b67f4360

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
