### PR TITLE
Add tests to css-timing-1.

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: HszNpNTCM1N

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1248340 [ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5345)

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by gsnedders** [comment]
@jgraham @foolip this introduces a css-timing-1 directory at the top level; I'm pretty sure we don't want versioned folders at the top level at all.

**Comment by foolip** [comment]
@birtles @BorisChiou, can you rename it?

**Comment by BorisChiou** [comment]
Sure. I can update the folder name to "css-timing" in Gecko.

**Comment by BorisChiou** [comment]
file bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1364004

**Comment by birtles** [comment]
This should remain css-timing-1 but move under the css directory.
I spoke to James about doing this a while back but don't remember what direction was going to be easiest to do it in (m-c or wpt)

**Comment by gsnedders** [comment]
@birtles I don't think there's any need to move anything into the css directory. The only advantage of the css directory is that it remains things needed for the CSS test harness, which we're meant to be moving away from. We should also be following the normal WPT habit and not having versioned folders going forward.

**Comment by birtles** [comment]
@gsnedders Ok, I didn't know that. That makes sense then.
Do we plan to move other folders out of 'css' when possible?

**Comment by gsnedders** [comment]
@birtles Basically the answer is no. Basically:

 * We want to make it possible to use both the old CSS WG test harness and the WPT tools in the short term for progress along the REC-track.
 * Moving files breaks vendors expectation files as to what tests fail/crash/etc.

**Comment by birtles** [comment]
Ok. It feels a bit awkward that when I work on transitions I need to touch files in 'css/css-transitions-1' and 'css-timing', but, oh well.

**Comment by gsnedders** [comment]
Yeah, it's kinda ugly, but it was the agreed compromise to avoid delaying merging the repos for another year or more… :\

**Pull request merged**
