### PR TITLE
📝Editorial: Update resources/README.md

### PR DESCRIPTION
**Pull request by snuggs**
Make prose for resources more friendly to new adopters.  (i.e., `testharness.js`).

I have been educating the community on the benefits of aligning testing
with WPT. However, testharness is a little difficult to get head wrapped around
from the feedback I am receiving. Also have recently been doing some prose
updates in documentation over @ WHATWG. I am revisiting the WPT setup process
and believe one should always leave code better than when they saw it.

If this is not of value please let me know the best way to contribute to improving documentation.

🙏 

References:
  - https://github.com/whatwg/meta/issues/48
  - (in particular) https://github.com/whatwg/meta/issues/48#issuecomment-342737876

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8140)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-10 01:42:44
Finished: 2017-11-10 01:48:20


<h2>Failing Jobs</h2>
<ul>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20449)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/299961232)

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
I think the titles should ideally all be in title case, but sure we can merge this.

**Comment by snuggs** [comment]
@jgraham  titles ARE in title case. Headers are not. 
  # title

  #(n) header

I referenced this multiple times above...
https://github.com/whatwg/meta/issues/48#issuecomment-342737876

**Comment by snuggs** [comment]
CI appears to be stuck... @jgraham @gsnedders

**Comment by snuggs** [comment]
OK CI cleared @jgraham @gsnedders

**Comment by gsnedders** [comment]
@snuggs FWIW, we don't necessarily follow WHATWG policies here.

**Pull request merged**
