### PR TITLE
Corrected and improved 4 box-shadow-[inset | outset] tests

### LINKED ISSUE #10013: [css-backgrounds] 4 box-shadow tests that can not fail
http://wpt.live/css/css-backgrounds/box-shadow-inset-spread-without-border-radius.html
  
http://wpt.live/css/css-backgrounds/box-shadow-inset-without-border-radius.html
  
http://wpt.live/css/css-backgrounds/box-shadow-outset-spread-without-border-radius.html
  
http://wpt.live/css/css-backgrounds/box-shadow-outset-without-border-radius.html

In those 4 box-shadow tests, if you toggle off the box-shadow 
declarations, you still get a green square. Those 4 tests are wrongly 
designed. The .test should display green and overlap the .ref which 
would be red.

[Update February 20th 2023]
These 4 tests (which I updated their links) still need to be revisited and eventually adjusted so that they can become reliable, useful and trustworthy.
[/Update]

### PR DESCRIPTION
**Pull request by TalbotG**
This pull request is a followup-to/consequence of  [Issue 10013](https://github.com/web-platform-tests/wpt/issues/10013).

At my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-inset-without-border-radius.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-outset-without-border-radius-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-outset-without-border-radius-002.html

Reference file:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-inset-without-border-radius-ref.html

This pull request will close [Issue 10013](https://github.com/web-platform-tests/wpt/issues/10013)

I have double-checked that the removed reference files are not referenced by any other test.

### CODE REVIEW

**Comment by TalbotG** [comment]
Work in progress:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-inset-without-border-radius-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-inset-without-border-radius-new-ref.html

In this new test of 8 sub-tests, each of the 4 targeted areas uses a specific, dedicated color:

Color meaning
= = = = = =

yellow is the content area only

orange is the padding belt only

black is the inset box shadow only

blue is the border belt only

Dimensions of those areas and offsets
= = = = = = = = = = = = = = = =

content area is 64px by 64px

padding belt is 32px

border belt is 16px

box shadow horizontal and vertical offsets are 20px in all 4 directions

spread is always +30px

a spread of minus 30px has **not** been tested, is not part of this test ...

This new test will comply as well with the 600x600 maximum viewport requirement.

**Comment by TalbotG** [comment]
More work in progress:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-outset-without-border-radius-001-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-outset-without-border-radius-001-new-ref.html


http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-outset-without-border-radius-002-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-outset-without-border-radius-002-new-ref.html

In these 2 new tests of 4 sub-tests each, each of the 4 targeted areas uses a specific, dedicated color:

Color meaning
= = = = = =

yellow is the content area only

orange is the padding belt only

black is the outset box shadow only

blue is the border belt only

Dimensions of those areas and offsets
= = = = = = = = = = = = = = = =

content area is 64px by 64px

padding belt is 32px

border belt is 16px

box shadow horizontal and vertical offsets are 20px in all 4 directions

spread is always +30px

a spread of minus 30px has **not** been tested, is not part of this test ...

These 2 new tests will comply as well with the 600x600 maximum viewport requirement.

**Comment by TalbotG** [comment]
In the 2 **out**set tests only, the comment (at line 93)

   black is the inset box shadow only

should be instead/rather

   black is the outset box shadow only

**Comment by fantasai** [comment]
```
  body
    {
      overflow-y: hidden;
      /*
      We want to neutralize the generation of a
      vertical scrollbar in case of an 600x600
      viewport size
      */
    }
```

Why not just make the everything smaller, so that you don't run into this problem?
Then you can also fit all eight tests onto a single page (since they're all variants on the same thing, right?).

```
      background-color: orange; /* padding belt is orange */
      background-image: linear-gradient(yellow, yellow); /* content area is yellow */
      background-origin: content-box;
      background-repeat: no-repeat;
      border: blue solid 16px; /* border belt is blue */
```

I think this is useful for development and debugging, but in the actual test we should keep these all transparent, to make sure the shadow doesn't paint under these areas (since it's not supposed to).

Otherwise the tests look good. So to summarize, the feedback is:
* Shrink everything down a bit and put them all on one page.
* Make the border/padding/content areas transparent, not colored.

**Comment by TalbotG** [comment]
> * Shrink everything down a bit and put them all on one page.
> 
> * Make the border/padding/content areas transparent, not colored.

Done:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-outset-without-border-radius-001-newer.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/box-shadow-outset-without-border-radius-001-newer-ref.html

Upcoming commit in a few min..

**Review by fantasai — APPROVED** [review]

**Pull request merged**
