### PR TITLE
Add long timeouts to some IndexedDB tests, a=testonly

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: L9l68yZ55eT

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1340474

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5073/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979245)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979246)

**Pull request merged**
