### PR TITLE
List functions from RTCPeerConnection-helper.js in use in each file

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240477486)

# Firefox (nightly) #
Testing web-platform-tests at revision b505ce7ac82ec1d88a970cc3c21fc86f7491c01d
Using browser at version BuildID 20170607100302; SourceStamp 5801aa478de12a62b2b2982659e787fcc4268d67
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>5 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-createAnswer.html">/webrtc/RTCPeerConnection-createAnswer.html</a></summary>


|                                      Subtest                                      | Results | Messages |
|-----------------------------------------------------------------------------------|---------|----------|
|                                                                                   | OK      |          |
| `createAnswer() with null remoteDescription should reject with InvalidStateError` | PASS    |          |
| `createAnswer() after setting remote description should succeed`                  | PASS    |          |
| `createAnswer() when connection is closed reject with InvalidStateError`          | PASS    |          |
| `createAnswer() when connection is closed in parallel should never resolve`       | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-createOffer.html">/webrtc/RTCPeerConnection-createOffer.html</a></summary>


|                                                               Subtest                                                               | Results |                                                                                Messages                                                                                |
|-------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                     | OK      |                                                                                                                                                                        |
| `createOffer() with no argument from newly created RTCPeerConnection should succeed`                                                | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."` |
| `createOffer() and then setLocalDescription() should succeed`                                                                       | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                        |
| `createOffer() after connection is closed should reject with InvalidStateError`                                                     | PASS    |                                                                                                                                                                        |
| `createOffer() when connection is closed halfway should never resolve`                                                              | PASS    |                                                                                                                                                                        |
| `When media stream is added when createOffer() is running in parallel, the result offer should contain the new media stream`        | FAIL    | `pc.addTransceiver is not a function`                                                                                                                                  |
| `createOffer() with offerToReceiveAudio should add audio line to all subsequent created offers`                                     | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."` |
| `createOffer() with offerToReceiveVideo should add video line to all subsequent created offers`                                     | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."` |
| `createOffer() with offerToReceiveAudio:true then offerToReceiveVideo:true should have result offer with both audio and video line` | FAIL    | `assert_equals: Expect audio line to remain in created offer expected 1 but got 0`                                                                                     |
| `Test onsignalingstatechange event for createOffer() and then setLocalDescription() should succeed`                                 | PASS    |                                                                                                                                                                        |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-setLocalDescription.html">/webrtc/RTCPeerConnection-setLocalDescription.html</a></summary>


|                                                                          Subtest                                                                          | Results |                                                                                                                              Messages                                                                                                                             |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                           | OK      |                                                                                                                                                                                                                                                                   |
| `setLocalDescription with type offer and null sdp should use lastOffer generated from createOffer`                                                        | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                                                            |
| `setLocalDescription() with offer not created by own createOffer() should reject with InvalidModificationError`                                           | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidStateError: Calling SetLocal without first calling CreateOffer/Answer is not supported." that is not a DOMException InvalidModificationError: property "code" is equal to 11, expected 13` |
| `Set created offer other than last offer should reject with InvalidModificationError`                                                                     | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidSessionDescriptionError: Changing the media-type of m-sections is not allowed" that is not a DOMException InvalidModificationError: property "code" is equal to 0, expected 13`            |
| `Creating and setting offer multiple times should succeed`                                                                                                | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidStateError: Cannot create offer in state have-local-offer"`                                                                                                                                         |
| `setLocalDescription(offer) should never resolve if connection is closed in parallel`                                                                     | FAIL    | `assert_unreached: Pending promise should never be resolved. Instead it is rejected with: InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel. Reached unreachable code`                                 |
| `setLocalDescription() with valid answer should succeed`                                                                                                  | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                                   |
| `setLocalDescription() with type answer and null sdp should use lastAnswer generated from createAnswer`                                                   | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidParameterError: Empty or null SDP provided to setLocalDescription"`                                                                                                                                 |
| `setLocalDescription() with answer not created by own createAnswer() should reject with InvalidModificationError`                                         | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidStateError: Calling SetLocal without first calling CreateOffer/Answer is not supported." that is not a DOMException InvalidModificationError: property "code" is equal to 11, expected 13` |
| `Calling createOffer() and setLocalDescription() again after one round of local-offer/remote-answer should succeed`                                       | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                                   |
| `Switching role from answerer to offerer after going back to stable state should succeed`                                                                 | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                                   |
| `Calling setLocalDescription(answer) from stable state should reject with InvalidStateError`                                                              | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                                                            |
| `Calling setLocalDescription(answer) from have-local-offer state should reject with InvalidStateError`                                                    | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                                                            |
| `Test onsignalingstatechange event for Creating and setting offer multiple times should succeed`                                                          | PASS    |                                                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for setLocalDescription() with valid answer should succeed`                                                            | PASS    |                                                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Calling createOffer() and setLocalDescription() again after one round of local-offer/remote-answer should succeed` | PASS    |                                                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Switching role from answerer to offerer after going back to stable state should succeed`                           | PASS    |                                                                                                                                                                                                                                                                   |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                                                 Subtest                                                                  | Results |                                                                                                              Messages                                                                                                             |
|------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                          | TIMEOUT |                                                                                                                                                                                                                                   |
| `setRemoteDescription with valid offer should succeed`                                                                                   | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Setting remote description multiple times with different offer should succeed`                                                          | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidStateError: Cannot set remote offer or answer in current state have-remote-offer"`                                                                                  |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                                                   | FAIL    | `assert_unreached: Pending promise should never be resolved. Instead it is rejected with: InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel. Reached unreachable code` |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                                                               | FAIL    | `assert_equals: Expect error detail field to set to sdp-syntax-error expected (string) "sdp-syntax-error" but got (undefined) undefined`                                                                                          |
| `setRemoteDescription with invalid type and invalid SDP should reject with TypeError`                                                    | PASS    |                                                                                                                                                                                                                                   |
| `setRemoteDescription() with invalid SDP and stable state should reject with InvalidStateError`                                          | PASS    |                                                                                                                                                                                                                                   |
| `setRemoteDescription() with valid state and answer should succeed`                                                                      | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed`                                       | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidSessionDescriptionError: Remote description changes the media type of m-line 0"`                                                                                    |
| `Switching role from offerer to answerer after going back to stable state should succeed`                                                | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                   |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`                                            | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError`                                   | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError`                                 | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                            |
| `setRemoteDescription should trigger ontrack event when the MSID of the stream is is parsed.`                                            | FAIL    | `assert_own_property: Expect pc to have ontrack event handler attribute expected property "ontrack" missing`                                                                                                                      |
| `Test onsignalingstatechange event for setRemoteDescription with valid offer should succeed`                                             | PASS    |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Setting remote description multiple times with different offer should succeed`                    | PASS    |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for setRemoteDescription() with valid state and answer should succeed`                                | PASS    |                                                                                                                                                                                                                                   |
| `Test onsignalingstatechange event for Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed` | TIMEOUT | `Test timed out`                                                                                                                                                                                                                  |
| `Test onsignalingstatechange event for Switching role from offerer to answerer after going back to stable state should succeed`          | PASS    |                                                                                                                                                                                                                                   |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCSctpTransport-constructor.html">/webrtc/RTCSctpTransport-constructor.html</a></summary>


|                                       Subtest                                        | Results |                                Messages                               |
|--------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------|
|                                                                                      | OK      |                                                                       |
| `setRemoteDescription() with answer containing data media should initialize pc.sctp` | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined` |
| `setLocalDescription() with answer containing data media should initialize pc.sctp`  | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240477487)

# Sauce (safari) #
Testing web-platform-tests at revision b505ce7ac82ec1d88a970cc3c21fc86f7491c01d
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>5 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-createAnswer.html">/webrtc/RTCPeerConnection-createAnswer.html</a></summary>


|                                      Subtest                                      | Results |                 Messages                 |
|-----------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                   | OK      |                                          |
| `createAnswer() with null remoteDescription should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createAnswer() after setting remote description should succeed`                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createAnswer() when connection is closed reject with InvalidStateError`          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createAnswer() when connection is closed in parallel should never resolve`       | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-createOffer.html">/webrtc/RTCPeerConnection-createOffer.html</a></summary>


|                                                               Subtest                                                               | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                                     | OK      |                                          |
| `createOffer() with no argument from newly created RTCPeerConnection should succeed`                                                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() and then setLocalDescription() should succeed`                                                                       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() after connection is closed should reject with InvalidStateError`                                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() when connection is closed halfway should never resolve`                                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `When media stream is added when createOffer() is running in parallel, the result offer should contain the new media stream`        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() with offerToReceiveAudio should add audio line to all subsequent created offers`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() with offerToReceiveVideo should add video line to all subsequent created offers`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createOffer() with offerToReceiveAudio:true then offerToReceiveVideo:true should have result offer with both audio and video line` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-setLocalDescription.html">/webrtc/RTCPeerConnection-setLocalDescription.html</a></summary>


|                                                       Subtest                                                       | Results |                 Messages                 |
|---------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                     | OK      |                                          |
| `setLocalDescription with type offer and null sdp should use lastOffer generated from createOffer`                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with offer not created by own createOffer() should reject with InvalidModificationError`     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Set created offer other than last offer should reject with InvalidModificationError`                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Creating and setting offer multiple times should succeed`                                                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription(offer) should never resolve if connection is closed in parallel`                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with valid answer should succeed`                                                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with type answer and null sdp should use lastAnswer generated from createAnswer`             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with answer not created by own createAnswer() should reject with InvalidModificationError`   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling createOffer() and setLocalDescription() again after one round of local-offer/remote-answer should succeed` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Switching role from answerer to offerer after going back to stable state should succeed`                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setLocalDescription(answer) from stable state should reject with InvalidStateError`                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setLocalDescription(answer) from have-local-offer state should reject with InvalidStateError`              | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                                 Subtest                                                  | Results |                 Messages                 |
|----------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                          | OK      |                                          |
| `setRemoteDescription with valid offer should succeed`                                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Setting remote description multiple times with different offer should succeed`                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription with invalid type and invalid SDP should reject with TypeError`                    | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription() with invalid SDP and stable state should reject with InvalidStateError`          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription() with valid state and answer should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription() again after one round of remote-offer/local-answer should succeed`       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Switching role from offerer to answerer after going back to stable state should succeed`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError`   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription should trigger ontrack event when the MSID of the stream is is parsed.`            | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6180/webrtc/RTCSctpTransport-constructor.html">/webrtc/RTCSctpTransport-constructor.html</a></summary>


|                                       Subtest                                        | Results |                 Messages                 |
|--------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                      | OK      |                                          |
| `setRemoteDescription() with answer containing data media should initialize pc.sctp` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with answer containing data media should initialize pc.sctp`  | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240477493)

# Chrome (unstable) #
Testing web-platform-tests at revision b505ce7ac82ec1d88a970cc3c21fc86f7491c01d
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240477494)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision b505ce7ac82ec1d88a970cc3c21fc86f7491c01d

**Review by soareschen — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
