### PR TITLE
Updating OS identifier in WebDriver control+click tests

### PR DESCRIPTION
**Pull request by jimevans**
The identifier for the platform/OS should be "windows", not "windows_nt".

### CODE REVIEW

**Review by andreastt — APPROVED** [review]
This is already fixed in a downstream patch in central, but I don’t suppose there will be any merge conflicts.

cc @jgraham

**Comment by whimboo** [comment]
There are even more places which have the wrong platformName listed in the wdspec tests. All of those got fixed via https://hg.mozilla.org/integration/autoland/rev/16ba5f9ae84e which hopefully gets synced upstream soon. I would just close this PR.

**Comment by andreastt** [comment]
It appears that Chrome is flipping between error and fail here, which I’m not sure is a blocker for landing this as it is mostly likely an implementation problem. https://bugzilla.mozilla.org/show_bug.cgi?id=1470646 that @whimboo referred to would presumably exhibit the same problem.

**Comment by jimevans** [comment]
Closing as subsequent changes have made this PR obsolete.

**Pull request closed without merging**
