### PR TITLE
Remove deadlock from payment-is-showing test

### PR DESCRIPTION
**Pull request by danyao**
payment-is-show.https.html tests that if multiple contexts try to call `PaymentRequest.show()`, all but the first one rejects.

Before this patch, each `PaymentRequest.show()` is wrapped inside its own `test_driver.bless()`. This creates a deadlock when running the tests directly in the browser: the first payment sheet prevents the user from interacting with the test page to click on the button generated by `test_driver.bless()`, which in turn blocks the test from proceeding, which will eventually abort the payment sheet. This deadlock breaks the web test runner.

This patch combines all `PaymentRequset.show()` calls of a single test case inside a single `test_driver.bless()` call. This way, each test only requires user to click on a single block.

The only exceptions are the two tests that trigger popups and call `.show()` from the main test page. The test requires a user gesture to bring the main page back into foreground. User has to click on two buttons to make these tests proceed.

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
Thanks for fixing this. As an aside, we should get agreement on them quotes and some way of enforcing that to avoid unnecessary changes.

**Comment by danyao** [comment]
Thanks @marcoscaceres for the review! I used https://prettier.io which you recommended in an earlier thread to format the code. It replaced the quotes. What do you prefer? I'll figure out how to configure prettier default to match.

**Comment by marcoscaceres** [comment]
I’m a double-quotes semicolon kinda person.

**Comment by danyao** [comment]
SG. I'll follow that convention in the future, and see if there's a way to get a style enforcer added to the presubmit.

**Pull request merged**
