### PR TITLE
Add --verbose flag for chromedriver

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Full run triggered at https://tools.taskcluster.net/groups/DENXznB-TzuKv5zSbKGQ-Q.

@JohnChen0 FYI

**Comment by foolip** [comment]
The logs are huge but eventually there "Task timeout after 7200 seconds. Force killing container." The chromedriver log output right before that doesn't say anything obviously suspicious, but I'm not sure what I'm looking for either.

**Comment by foolip** [comment]
I've tried short-circuiting the logic to wait for reftests to finish and triggered https://tools.taskcluster.net/groups/NhOWfWZlSHC6T1BATbhdWA to see if that helps. If it does it suggests something has changed in one of the APIs used in https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/reftest-wait_webdriver.js.

Also... @gsnedders why don't we eventually timeout if a reftest fails to take a screenshot?

**Comment by foolip** [comment]
> why don't we eventually timeout if a reftest fails to take a screenshot?

Actually this might be what is happening. The tests all seem to take about 15 seconds, and running 2000+ tests would then take 8+ hours.

**Comment by foolip** [comment]
That didn't help, still timeouts. I see "screenshot failed, retrying" over and over in the logs, so it seems like it's waiting for the screenshot that times out? @JohnChen0 does that help narrow down the possible cause?

**Comment by JohnChen0** [comment]
The new run is different from the old run.

* In the old run, Execute Async Script times out. Apparently the script never signaled its completion.
* In the new run, the script has been modified so that Execute Async Script completes quickly. However, the subsequence Screenshot command fails.

ChromeDriver did make some adjustment to its screenshot code in 78, but no further changes in 79. Since 78 appears to work correctly while 79 times out, this is probably not related.

Still no real clue about what is causing all these timeouts.

**Comment by foolip** [comment]
Closing this, it was for debugging.

**Pull request closed without merging**
