### PR TITLE
Add test for script.disown

### PR DESCRIPTION
**Pull request by juliandescottes**
WPT test changes for script.disown support, reviewed by mozilla peers at https://phabricator.services.mozilla.com/D155635

### CODE REVIEW

**Comment by juliandescottes** [comment]
Tagging @foolip for review

As with other similar PRs, we might just land it in mozilla-central once we reached an agreement on the content here.
  
cc @sadym-chromium @whimboo @lutien @jgraham

**Comment by foolip** [comment]
Sorry I didn't get a chance to review this. I'm going on a short vacation and will be back on Friday, hopefully someone else can take a look.

**Comment by whimboo** [comment]
Thanks @foolip! We reviewed these changes internally already. So maybe we could get it already landed in our repository given that it's blocking our work and it's not clear if @sadym-chromium will be back soon? If there are issues we could still handle them after landing?

**Review by foolip — APPROVED** [review]
Since it's already been reviewed I just skimmed the diff.

**Comment by juliandescottes** [comment]
Thanks @foolip ! I will proceed to land this on mozilla-central, and close this here. The tests could be coming with an upcoming sync

**Pull request closed without merging**
