### PR TITLE
Add coverage report and tools for WebRTC tests

### PR DESCRIPTION
**Pull request by soareschen**
This PR is an experimental attempt to better keep track of the test coverage status of web platform tests for WebRTC.

### Motivation

Keeping track of the coverage status of specs can be difficult. Specs and tests are often updated independently and can get out of sync quickly. When reviewing tests or specs, we'd like readers from both sides to quickly determine how a normative statement is linked to a test case. A test reviewer should be able to find out which statement in the spec a test case is testing on, without having to read through the entire spec. Similarly a spec reviewer should be able to find out whether a normative statement has been tested and which test file contain the test cases, without having to read through all test cases.

When the spec is updated, the corresponding tests may not be updated immediately to reflect the changes. Contributors should be able to find out which test need to be updated since the last update, so that they can work on updating the tests.

Adding coverage status to version control system can help us keep track of whether the test coverage has improved over time as new tests are added, or whether coverage get worse if the tests lag too far behind the spec.

At the same time, a "test as you commit" policy is being adopted in WebRTC (w3c/webrtc-pc#1617). Ideally we'd like a future where tests are added as soon as the spec is updated. But until then we still have to keep track of the existing statements and add new tests until we reach 100% coverage.

### Coverage Report

A `coverage` directory is added under `webrtc` containing YAML files that report the test status of each normative statement in WebRTC. The YAML format is chosen so that it is friendly to human readers, software tools, and version control systems.

### Coverage Tools

A `tools` directory is added with simple Node.js scripts to report the coverage status of the tests. Following is the overall coverage status as of now:

```bash
$ cd webrtc/tools
$ node scripts/overview.js 
Overall Coverage
====================
todo        |    248
tested      |    315
trivial     |    173
untestable  |     79
====================
total       |    815
coverage    | 69.57%
====================
```

### Previous Work

This PR does several improvement over the current coverage report done by @rwaldron at https://rwaldron.github.io/webrtc-pc/. Writing the report in YAML enable us to better parsing, editing, version control, and helps keep in sync with the spec updates. We also link tested statements to the particular test files that contain the tests. I also feel that decluttering the coverage report with non-essential parts of the spec improves readability for the purpose of test development.

### Discussion

The approach I tried here is not perfect. There may be many unresolved issues and thus is not suited for the broader projects in WPT. As for now, the major contribution for this is for the first time we are able to tell that the coverage for WebRTC is around 69.57%, and that there are around 248 normative statements that still need to be tested.

There may be disagreement on whether the status of a normative statement is classified correctly in the coverage report. We also haven't updated the references in the existing test files to the latest editor's draft. All these can be done in separate PR/issues if we decide to merge this.

Any suggestion or feedback is welcomed. If anything we can have discussions during the upcoming TPAC.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-11-03 07:01:23
Finished: 2017-11-03 07:06:55


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20131)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/296645547)

**Comment by alvestrand** [comment]
Looks like a good tool to have.

Would like to have comments from @rwaldron on whether the overall approach is sound, based on his experience.

Why are there several yaml files included here that show part of the coverage? Is it intended that these be checked in and that submitters of PRs submit coverage changes? If so, this needs a README update to show what submitters of PRs need to do - and won't work for automatic submits like the ones from Chromium.

If coverage status shouldn't be in the repo, please delete these files.

**Comment by soareschen** [comment]
I think this can be closed since there has been lack of interest and the coverage is out of sync for a while now. If anyone is interested they can submit a new PR base on this one updated to latest spec.

**Comment by agouaillard-cosmo** [comment]
please re-open. Let's see what rick says, and then let's discuss.

**Comment by soareschen** [comment]
Ok

**Comment by alvestrand** [comment]
Closing as OBE, given @dontcallmedom 's work and the age of the PR.

**Pull request closed without merging**
