### PR TITLE
Convert WebSocket tests to .any.js format

### LINKED ISSUE #2557: Make websocket tests run in workers
This could follow the same pattern as the tests for the Fetch API: https://github.com/w3c/web-platform-tests/tree/master/fetch/api/basic - have two HTML files (one for workers, one for non-workers) that load the same JS file that contains the actual test.

### PR DESCRIPTION
**Pull request by annevk**
Take 2 (see #5148 for take 1), fixes #2557.

### CODE REVIEW

**Comment by annevk** [comment]
(Rebasing the old PR was too annoying. I omitted the `<meta name=variant>` test here and also fixed up the Unicode error and the `window.WebSocket` bits. I think this should be good now.)

**Comment by Ms2ger** [comment]
Does the unicode string need to be literal unicode, or would `\u` escapes work?

**Review by zcorpan — APPROVED** [review]
Optional nice-to-have would be to re-indent the files e.g. using `js-beautify`

**Comment by annevk** [comment]
@zcorpan I think that would be better as a follow-up. I suspect if I did that everything would be seen as delete/add rather than a move-with-changes.

**Pull request merged**
