### PR TITLE
Fix a spec link for css-break

### PR DESCRIPTION
**Pull request by foolip**
This was the cause of confusion in https://github.com/w3c/web-platform-tests/pull/8311.

### CODE REVIEW

**Comment by foolip** [comment]
@fantasai like this instead?

**Comment by foolip** [comment]
@fantasai, this directory is missing an owners file, do you know some people I could put in it? Maybe @mstensho?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-21 23:20:13
Finished: 2017-11-21 23:26:00


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20951)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/305538162)

**Comment by foolip** [comment]
Per out-of-band discussion with @mstensho, adding him to OWNERS of css-break and css-multicol, so hw can now review this instead :)

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
