### PR TITLE
Adds bentian as owner

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Was missing @bentian from owners list, so I'm prevented to from merging some tests

**Review by alphan102 — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259666209)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259666210)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259666216)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259666217)

# Sauce (MicrosoftEdge) #

**Review by edenchuang — APPROVED** [review]

**Review by jgraham — APPROVED** [review]

**Pull request merged**
