### PR TITLE
SVG2: Test bearing path commands

### PR DESCRIPTION
**Pull request by ewilligers**
Bearing commands are described in
https://www.w3.org/TR/svg-paths/#PathDataBearingCommands
https://www.w3.org/TR/SVG2/paths.html#PathDataBearingCommands

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20479)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/300220440)

**Review by boggydigital — APPROVED** [review]
I don't seem to be able to test this in Chrome canary with experimental web platform features flag enabled, but otherwise the tests seem correct with manual tracing of the commands.

**Comment by boggydigital** [comment]
I believe this issue tracks bearing path commands in Blink: crbug.com/366548

**Comment by ewilligers** [comment]
These aren't implemented in Chrome. I am suggesting we still merge these tests, to show if implementations support bearing commands. zero.svg is a trivial test comparing
```
M 25 50 h 10 B 0 m 10 0 h 10 b 0 m 10 0 h 10
M 25 50 h 10     m 10 0 h 10     m 10 0 h 10

```

**Comment by boggydigital** [comment]
@ewilligers I agree with you - those look like good tests to have
@gsnedders - I don't seem to be a reviewer with write access as I see "At least one approved review is required by reviewers with write access" - can you please help here?

**Comment by gsnedders** [comment]
@boggydigital and if by magic you now do

**Pull request merged**
