### PR TITLE
Rename some manual css-backgrounds tests

### PR DESCRIPTION
**Pull request by clopez**
* Make clearer that this tests are manual by renaming them.

### CODE REVIEW

**Comment by gsnedders** [comment]
see also https://github.com/web-platform-tests/wpt/issues/5381

let me write some brief RFC so we can at least move all the paged media tests out of the general manual category in the near term and can achieve something here even if we in the short term just fall into "unsupported test type" for them in all runners?

**Comment by TalbotG** [comment]
@clopez , @gsnedders ,

There are no border-image-source loaded nor fetched and no reference file for the following 7 tests:

1- http://wpt.live/css/css-backgrounds/border-image-image-type-001.htm (missing ../support/9grid40-30-20-10-red.svg)

2- http://wpt.live/css/css-backgrounds/border-image-image-type-002.htm (missing ../support/9grid40-30-20-10-red.svg)

3- http://wpt.live/css/css-backgrounds/border-image-repeat-001.htm (missing ../support/border81x81.png)

4- http://wpt.live/css/css-backgrounds/border-image-repeat-002.htm (missing ../support/border81x81.png)

5- http://wpt.live/css/css-backgrounds/border-image-repeat-003.htm (missing ../support/border81x81.png)

6- http://wpt.live/css/css-backgrounds/border-image-repeat-004.htm (missing ../support/border81x81.png)

7- http://wpt.live/css/css-backgrounds/border-image-slice-004.htm (missing ../support/9grid20-40-red.png)


The following next 5 tests have a border-image-source loaded and fetched but no reference file:

8- http://wpt.live/css/css-backgrounds/border-image-slice-006.htm

9- http://wpt.live/css/css-backgrounds/border-image-width-001.htm

10- http://wpt.live/css/css-backgrounds/border-image-width-002.htm

11- http://wpt.live/css/css-backgrounds/border-image-width-003.htm

12- http://wpt.live/css/css-backgrounds/border-image-width-004.htm

I presume that, originally, all these 12 tests were not intended to be manual tests. Some of these tests (or all of them) are basic tests.

**Comment by TalbotG** [comment]
This Pull Request 21446 is now in my to-do-list. I intend to correct or upgrade these 12 tests (by providing a border-image-source and a reference file) assuming I can understand what they are testing before September 1st 2023.

**Comment by TalbotG** [comment]
> 1- http://wpt.live/css/css-backgrounds/border-image-image-type-001.htm (missing ../support/9grid40-30-20-10-red.svg)

> 2- http://wpt.live/css/css-backgrounds/border-image-image-type-002.htm (missing ../support/9grid40-30-20-10-red.svg)

I am ready to replace these 2 with

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-001-GT.htm

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-002-GT.htm

and with this reference:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-image-type-001-ref.html

**Comment by TalbotG** [comment]
> http://wpt.live/css/css-backgrounds/border-image-repeat-001.htm (missing ../support/border81x81.png)

We can remove
http://wpt.live/css/css-backgrounds/border-image-repeat-001.htm
because we already have 
http://wpt.live/css/css-backgrounds/css3-border-image-repeat-repeat.html
that checks this.

> http://wpt.live/css/css-backgrounds/border-image-repeat-002.htm (missing ../support/border81x81.png)

I am ready to rehabilitate this test with 
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-repeat-002-GT.html
and
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-repeat-002-ref.html

> http://wpt.live/css/css-backgrounds/border-image-repeat-003.htm (missing ../support/border81x81.png)

We can remove
http://wpt.live/css/css-backgrounds/border-image-repeat-003.htm
because we already have more than 10 tests checking
specifically `border-image-repeat: space`

> http://wpt.live/css/css-backgrounds/border-image-repeat-004.htm (missing ../support/border81x81.png)

I am ready to rehabilitate this test with 
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-repeat-004-GT.html
and
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-repeat-004-ref.html

> http://wpt.live/css/css-backgrounds/border-image-slice-004.htm (missing ../support/9grid20-40-red.png)

I am ready to rehabilitate this test with 
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-004-GT.html
and
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-slice-004-ref.html

**Comment by TalbotG** [comment]
As soon as #42229 is reviewed and approved, I will close #21446

**Comment by TalbotG** [comment]
#42229 has been reviewed and approved, so closing this PR now.

**Pull request closed without merging**
