### PR TITLE
P2 Add a WPT test verifying Clients.matchAll() only returns Clients controlled by calling worker.

### PR DESCRIPTION
**Pull request by jgraham**
Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1343308

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5091/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208981092)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208981093)

**Pull request merged**
