### PR TITLE
custom-elements: Add a test for customized built-in elements coverage.

### PR DESCRIPTION
**Pull request by tkent-google**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23205)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/332659438)

**Review by TakayoshiKochi — COMMENTED** [review]
LGTM

**Review by TakayoshiKochi — APPROVED** [review]

**Comment by snuggs** [comment]
@tkent-google @TakayoshiKochi first would like to say AMAZING work on this. Been a long time coming. 🎉 

Looking at ways can contribute more here. Am good at refactoring. Was wondering could we `foreach` the elements instead of explicitly defining each one? Also did notice a few edge cases towards the end of the setup.

At minimum I believe `constructor () { super () }` is supperfluous and can just use `class extends HTML...Element {}`.

At least for `HTMLElement` Which theoretically should mean the rest. I don't see why native elements would require a constructor.

Just a thought FWIW.

Great work nonetheless. And FAST too!

**Comment by tkent-google** [comment]
Yeah, the test has a lot of rooms for improvement.  Feel free to change it!

**Comment by snuggs** [comment]
> Yeah, the test has a lot of rooms for improvement
Indeed. However reminds me of one of my favorite quotes. "Better to have a finished stick figure than an unfinished Picasso". I need to print that by my IDE lolz. 

> Feel free to change it!

[You don't have to ask me twice!](https://github.com/w3c/web-platform-tests/blob/master/webrtc/OWNERS#L1)

Happy Friday @tkent-google !

**Pull request merged**
