### PR TITLE
Moved webm files from mediacapture-fromelement/webm/ to media/

### PR DESCRIPTION
**Pull request by yell0wd0g**
This PR moves those 3 files out of  mediacapture-fromelement/webm/ to media/ so they can be reused by other tests, namely media-source/.

### CODE REVIEW

**Comment by yellowdoge** [comment]
@jeffcarp FYI/ please review

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255560640)

# Firefox (nightly) #
Testing web-platform-tests at revision 124a6095dfa207a5191a310b5af94f5da598a301
Using browser at version BuildID 20170719100147; SourceStamp 1b065ffd8a535a0ad4c39a912af18e948e6a42c1
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/capture.html">/mediacapture-fromelement/capture.html</a></summary>


|    Subtest    | Results |                 Messages                |
|---------------|---------|-----------------------------------------|
|               | OK      |                                         |
| `video-only`  | PASS    |                                         |
| `Untitled`    | FAIL    | `video.captureStream is not a function` |
| `audio-only`  | PASS    |                                         |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function` |
| `video+audio` | PASS    |                                         |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/creation.html">/mediacapture-fromelement/creation.html</a></summary>


|    Subtest    | Results |                Messages                |
|---------------|---------|----------------------------------------|
|               | OK      |                                        |
| `video-only`  | PASS    |                                        |
| `Untitled`    | FAIL    | `assert_true: expected true got false` |
| `audio-only`  | PASS    |                                        |
| `Untitled 1`  | FAIL    | `assert_true: expected true got false` |
| `video+audio` | PASS    |                                        |
| `Untitled 2`  | FAIL    | `assert_true: expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/ended.html">/mediacapture-fromelement/ended.html</a></summary>


|    Subtest    | Results |                Messages                |
|---------------|---------|----------------------------------------|
|               | OK      |                                        |
| `video-only`  | PASS    |                                        |
| `Untitled`    | FAIL    | `assert_true: expected true got false` |
| `audio-only`  | PASS    |                                        |
| `Untitled 1`  | FAIL    | `assert_true: expected true got false` |
| `video+audio` | PASS    |                                        |
| `Untitled 2`  | FAIL    | `assert_true: expected true got false` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255560643)

# Sauce (safari) #
Testing web-platform-tests at revision 124a6095dfa207a5191a310b5af94f5da598a301
Using browser at version 10.0
Starting 10 test iterations
## Unstable results ##


|                    Test                   |    Subtest    |            Results            |                Messages                |
|-------------------------------------------|---------------|-------------------------------|----------------------------------------|
| `/mediacapture-fromelement/creation.html` |               | **OK: 9/10, TIMEOUT: 1/10**   |                                        |
| `/mediacapture-fromelement/creation.html` | `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                        |
| `/mediacapture-fromelement/creation.html` | `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |
| `/mediacapture-fromelement/creation.html` | `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                        |
| `/mediacapture-fromelement/creation.html` | `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |
| `/mediacapture-fromelement/creation.html` | `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                        |
| `/mediacapture-fromelement/creation.html` | `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |

## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/capture.html">/mediacapture-fromelement/capture.html</a></summary>


|    Subtest    | Results |                                                  Messages                                                 |
|---------------|---------|-----------------------------------------------------------------------------------------------------------|
|               | OK      |                                                                                                           |
| `video-only`  | PASS    |                                                                                                           |
| `Untitled`    | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `audio-only`  | PASS    |                                                                                                           |
| `Untitled 1`  | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |
| `video+audio` | PASS    |                                                                                                           |
| `Untitled 2`  | FAIL    | `video.captureStream is not a function. (In 'video.captureStream()', 'video.captureStream' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/creation.html">/mediacapture-fromelement/creation.html</a></summary>


|    Subtest    |            Results            |                Messages                |
|---------------|-------------------------------|----------------------------------------|
|               | **OK: 9/10, TIMEOUT: 1/10**   |                                        |
| `video-only`  | **PASS: 9/10, MISSING: 1/10** |                                        |
| `Untitled`    | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |
| `audio-only`  | **PASS: 9/10, MISSING: 1/10** |                                        |
| `Untitled 1`  | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |
| `video+audio` | **PASS: 9/10, MISSING: 1/10** |                                        |
| `Untitled 2`  | **FAIL: 9/10, MISSING: 1/10** | `assert_true: expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6588/mediacapture-fromelement/ended.html">/mediacapture-fromelement/ended.html</a></summary>


|    Subtest    | Results |                Messages                |
|---------------|---------|----------------------------------------|
|               | OK      |                                        |
| `video-only`  | PASS    |                                        |
| `Untitled`    | FAIL    | `assert_true: expected true got false` |
| `audio-only`  | PASS    |                                        |
| `Untitled 1`  | FAIL    | `assert_true: expected true got false` |
| `video+audio` | PASS    |                                        |
| `Untitled 2`  | FAIL    | `assert_true: expected true got false` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255560652)

# Chrome (unstable) #
Testing web-platform-tests at revision 124a6095dfa207a5191a310b5af94f5da598a301

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255560653)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 124a6095dfa207a5191a310b5af94f5da598a301

**Comment by jeffcarp** [comment]
lgtm however it looks like `creation.html` is getting a `TIMEOUT` 9 times out of 10? Unsure what could be causing that.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Review by jeffcarp — APPROVED** [review]
(forgot to approve)

**Comment by yellowdoge** [comment]
Can someone merge this change pretty please?

**Comment by sideshowbarker** [comment]
Added this to list at https://github.com/w3c/web-platform-tests/issues/6602

**Pull request merged**
