### PR TITLE
fix id attribute test (closes #6580)

### LINKED ISSUE #6580: Bad test in payment-request-id.https.html
[payment-request-id.https.html](https://w3c-test.org/payment-request/payment-request-id.https.html) contains a number of issues. 

* [ ] it doesn't check construction directly in the window object. 
* [ ] it should be clear that it's going to check inside an iframe.
* [ ] it makes assumption about the default length of a generated id. This is not in the spec (presumedly, it's checking for UUID length, but it's only RECOMMENDED that UUID be used).

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by edenchuang — APPROVED** [review]
LGTM

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17617)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266717463)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-21 08:47:07
Finished: 2017-08-21 08:57:54



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17617)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266717463)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-21 08:47:07
Finished: 2017-08-21 08:57:54



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17617)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266717463)

**Pull request merged**
