### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by marcoscaceres**
Add @alphan102 from Mozilla.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239893560)

# Firefox (nightly) #
Testing web-platform-tests at revision 165b8aff066b87761989b03fffe42fa92e511662
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239893561)

# Sauce (safari) #
Testing web-platform-tests at revision 165b8aff066b87761989b03fffe42fa92e511662
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239893567)

# Chrome (unstable) #
Testing web-platform-tests at revision 165b8aff066b87761989b03fffe42fa92e511662
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239893568)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 165b8aff066b87761989b03fffe42fa92e511662
Using browser at version 14.14393
Starting 10 test iterations

**Comment by marcoscaceres** [comment]
Just adds additional owners, please merge :)

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
