### PR TITLE
Remove test-003.html

### PR DESCRIPTION
**Pull request by TakayoshiKochi**
http://www.w3.org/TR/2013/WD-shadow-dom-20130514/#event-dispatch
had the following sentence, which no longer exists in the latest spec.

> If the relatedTarget and target are the same
> for a given node, its the event listeners must not be invoked.

### CODE REVIEW

**Comment by TakayoshiKochi** [comment]
@hayatoito PTAL

**Comment by Ms2ger** [comment]
Would it be better to keep the test and change the expectation?

**Comment by hayatoito** [comment]
@TakayoshiKochi 
No, don't remove the test.

The paragraph was just replaced by an event path trimming algorithm:
https://w3c.github.io/webcomponents/spec/shadow/#event-path-trimming

**Comment by TakayoshiKochi** [comment]
Will fix the test.

**Pull request closed without merging**
