### PR TITLE
Update pointerevents test pointerevent_coordinates_when_locked.html

### LINKED ISSUE #16406: [pointerevents] pointerlock/pointerevent_coordinates_when_locked.html assumes pointerlockchange event is synchronous
Cc'ing @EiraGe as the author of this test.

I wonder if there is an issue in the way the test at pointerevents/pointerlock/pointerevent_coordinates_when_locked.html is written. The pointer commands (via `new test_driver.Actions()`) are all dispatched in one command and thus rely on the `pointerlockchange` events to be delivered synchronously after calling `div1.requestPointerLock()` in the `pointerdown` event handler.

The [spec for `pointerlockchange`](https://w3c.github.io/pointerlock/#pointerlockchange-and-pointerlockerror-events) says this:

> Two events are used to communicate pointer lock state change or an error in changing state. They are named pointerlockchange and pointerlockerror. If pointer lock is entered or exited for any reason a pointerlockchange event must be sent.
>
> User agents must deliver these events by queuing a task to fire an event of the appropriate name with its bubbles attribute [DOM4] set to false to the pointer lock target element's node document.

As such I think the test is in error and the pointer commands should be split in two batches:

1. First, pointermove and pointerdown
1. Second, after pointer lock was granted, fire additional pointermove and the final pointerup.

If that is deemed correct, I'm happy to file a PR to rectify this.

### PR DESCRIPTION
**Pull request by EiraGe**
close #16406

### CODE REVIEW

**Comment by Steditor** [comment]
I've only done a quick reading so far (more to come later); first thing that caught my attention: If `click` is the new event to be used, the test instructions have to be updated.

**Comment by EiraGe** [comment]
Oops, I forgot to update it. Updated now

**Comment by EiraGe** [comment]
Do you know why it's showing failure on chrome-dev? I can't find what is failed. (It passed for me locally)

**Review by Steditor — APPROVED** [review]
With all tests passing now and the updated description I think this can be merged.

**Review by NavidZ — APPROVED** [review]

**Pull request merged**
