### PR TITLE
📖 Fix duplication issue from copy & paste

### PR DESCRIPTION
**Pull request by snuggs**
- https://github.com/w3c/web-platform-tests/blob/master/custom-elements/reactions/ChildNode.html#L31
  - @rniwa 

My first PR to `web-platform-tests`. Please let me know what conventions are missing and I'll be sure to update ASAP. Look forward to contributing more to such a great piece of work.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247798642)

# Firefox (nightly) #
Testing web-platform-tests at revision 590f35c03b2f60a8f4dec4b853526984e1d7c05f
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6352/custom-elements/reactions/ChildNode.html">/custom-elements/reactions/ChildNode.html</a></summary>


|                                                                            Subtest                                                                             | Results |                         Messages                        |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------|
|                                                                                                                                                                | OK      |                                                         |
| `before on ChildNode must enqueue a connected reaction`                                                                                                        | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `before on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`      | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `after on ChildNode must enqueue a connected reaction`                                                                                                         | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `after on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`       | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `replaceWith on ChildNode must enqueue a connected reaction`                                                                                                   | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `replaceWith on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document` | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |
| `remove on ChildNode must enqueue a disconnected reaction`                                                                                                     | FAIL    | `assert_array_equals: lengths differ, expected 1 got 0` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247798643)

# Sauce (safari) #
Testing web-platform-tests at revision 590f35c03b2f60a8f4dec4b853526984e1d7c05f
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6352/custom-elements/reactions/ChildNode.html">/custom-elements/reactions/ChildNode.html</a></summary>


|                                                                            Subtest                                                                             | Results |                Messages               |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                                                                                                | OK      |                                       |
| `before on ChildNode must enqueue a connected reaction`                                                                                                        | FAIL    | `Can't find variable: customElements` |
| `before on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`      | FAIL    | `Can't find variable: customElements` |
| `after on ChildNode must enqueue a connected reaction`                                                                                                         | FAIL    | `Can't find variable: customElements` |
| `after on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document`       | FAIL    | `Can't find variable: customElements` |
| `replaceWith on ChildNode must enqueue a connected reaction`                                                                                                   | FAIL    | `Can't find variable: customElements` |
| `replaceWith on ChildNode must enqueue a disconnected reaction, an adopted reaction, and a connected reaction when the custom element was in another document` | FAIL    | `Can't find variable: customElements` |
| `remove on ChildNode must enqueue a disconnected reaction`                                                                                                     | FAIL    | `Can't find variable: customElements` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247798649)

# Chrome (unstable) #
Testing web-platform-tests at revision 590f35c03b2f60a8f4dec4b853526984e1d7c05f

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247798650)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 590f35c03b2f60a8f4dec4b853526984e1d7c05f

**Comment by TakayoshiKochi** [comment]
LGTM

**Review by TakayoshiKochi — APPROVED** [review]
LGTM

**Pull request merged**
