### PR TITLE
Support virtual test suites in Wptrunner

### PR DESCRIPTION
**Pull request by WeizhongX**
This is an illustrative implementation for virtual test support in
wptrunner.
    
When a virtual configuration file is passed in through command line,
Wptrunner will load the virtual tests and their metadata after that of
the real tests. Virtual tests will have their own ids in the form:
virtual/prefix/.../some.html. Wpt server will strip 'virtual/prefix/'
and route the rest part of the id as usual.
    
Virtual metadata will be sitting at the corresponding place under
virtual/prefix/. If there is a separate wpt directory, for example,
/wpt_internal/ which is mapped to /wpt_internal/, the metadata for those
tests will be put under /wpt_internal/virtual/prefix/, while test ids
will be in the form: virtual/prefix/wpt_internal/.../some.html.
    
The corresponding RFC is RFC 110. In addition to the parameters listed
there, we now supports two additional parameters:
platforms: It is a list with possible values from 'Win', 'Mac' or
'Linux'.
expires: It can be either 'never' or some dates from future. The virtual
tests won't be run once they are expired.

### CODE REVIEW

**Comment by WeizhongX** [comment]
@jgraham, as we once discussed in the wpt monthly meeting, I uploaded an illustrative implementation of the virtual tests support in wptrunner. Can you pls take a look, and see if we can go this route if it does not complicate the data model too much?

There could still be bugs and I will work on the fix at the same time.

**Comment by jgraham** [comment]
FYI I have looked at this. I still think that without the existing Google precedent we wouldn't consider this behaviour in wptrunner. Having a seperate kind of test configuration that's reflected in the URL not the RunInfo feels like it's fighting the way wptrunner wants to work, and means that the output doesn't actually tell you what was run without out-of-band information. More trivially, I don't think we can reserve the top-level `virtual` path.

However I'd like @gsnedders or someone else not working on Gecko / Blink to look at this. Their outside perspective will be useful calibration.

**Comment by WeizhongX** [comment]
jgraham@, thanks for the review.

I thought virtual tests are going to be used by each vendor in their own CI system to detect regressions, so as long as the devs working on the feature understand what configures they are using, it might be ok?

We are currently using our old test runner to run WPTs in chromium. We want to switch to wptrunner so that we don't need to maintain two test runners, and run tests exactly the same way as upstream. Besides the test runner, we also have other backend systems, for example, the Result Database will store test history for all sorts of tests. If virtual tests do not have their own test ids, those backend systems need to be extended to accept another dimension. Developers work daily with the tests need make a change also. For example, in our proposal, devs can run `wpt run virtual/prefix/some/test.html` to run a virtual test. If a virtual test does not have test id, they need to pass in additional parameters, and it is going to be awkward they want to run both the virtual and non virtual version.

We can add a wrapper at our side to make a bridge between other systems and wptrunner, but this will degrade the performance and introduce overhead. Also such wrapper will be only available in chromium. Other vendors will need to do this again. Instead if virtual tests have their own ids, once configured, they will behave exactly the same as the non virtual tests, which makes them much easier to be adopted.

**Comment by foolip** [comment]
@jgraham what would you think about a setup where a virtual test suite _can_ have URL prefix, but this isn't required to use the feature, and not used in our shared CI or in Gecko's CI? That would mean some code in wptrunner to support this, but the prefix isn't what uniquely identifies the test+config, it's just a convenience for how Chromium wants to arrange virtual tests.

**Comment by WeizhongX** [comment]
@jgraham, I later realized that to support running virtual tests through command line, we would need to make change to the TestFilter class. This should be still doable, but is a scenario we need to consider when virtual tests do not have their own ids.

**Comment by WeizhongX** [comment]
@gsnedders Here is the virtual config file we used in chromium: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/VirtualTestSuites

For the actually format of the virtual config to be used in upstream, we will need to discuss with each vendor.

**Comment by jonathan-j-lee** [comment]
> For the actually format of the virtual config to be used in upstream, we will need to discuss with each vendor.

`wpt run` already has `--config` to declare other test/manifest roots in an `.ini` file; these other roots are a form of test subsetting. WDYT about reusing this format for virtual tests instead of introducing a new one from Chromium (which is opinionated about using command-line arguments for configuration)?

It could look like:

```ini
[manifest:internal]
tests = %(pwd)s/wpt_internal
metadata = %(pwd)s/wpt_internal
url_base = /wpt_internal/

[suite:threaded]
tests = animation-worklet, css/css-animations
# The remaining keys are vendor-specific.
args = --enable-threaded-compositing
expiry = 2023-07-01
prefs = ...
```

There would then be plumbing to pass this through to each product via the `__wptrunner__` API.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/rfcs/pull/110#issuecomment-1460259606 contains details of my proposal here.

**Pull request closed without merging**
