### PR TITLE
Move `check-layout-th.js` to `css/support/`

### PR DESCRIPTION
**Pull request by mrego**
This is going to be useful for some CSS Grid Layout tests,
and probably many other layout tests as it's widely used in Chromium and WebKit.

This file was originally upstreamed by @cbiesinger for a Flexbox test,
but we think it'd be useful for more cases. So this patch moves it to a more generic
folder `css/support/` dunno if that's the right one or not.

Please @gsnedders take a look and share your thoughts on this. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5698)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5698/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225906616)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225906618)

# Firefox (nightly channel) #
Testing web-platform-tests at revision bf63603c5b6438609e7158c0bc133ae87f213dca
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5698/css/css-flexbox-1/percentage-heights-000.html">/css/css-flexbox-1/percentage-heights-000.html</a></summary>


|   Subtest    | Results | Messages |
|--------------|---------|----------|
|              | OK      |          |
| `.flexbox 1` | PASS    |          |
| `.flexbox 2` | PASS    |          |
| `.flexbox 3` | PASS    |          |
| `.flexbox 4` | PASS    |          |
| `.flexbox 5` | PASS    |          |
| `.flexbox 6` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225906624)

# Chrome (unstable channel) #
Testing web-platform-tests at revision bf63603c5b6438609e7158c0bc133ae87f213dca

**Comment by gsnedders** [comment]
@mrego We still need support files to be in adjacent directories to the files they are support because of the build system, sadly, so yay we need duplicated copies :\

**Comment by mrego** [comment]
Wow, ok :disappointed:. We'll duplicate it then.

**Pull request closed without merging**
