### PR TITLE
Revert "Add SecureContext to WebUSB interfaces"

### PR DESCRIPTION
**Pull request by reillyeon**
Reverts w3c/web-platform-tests#6037 as the Chromium CL it was based on has not yet landed and has pending comments that need to be addressed.

### CODE REVIEW

**Comment by reillyeon** [comment]
I don't understand why GitHub generated so many commits for this revert but the end result seems to still be to only revert the commit that I intended.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236491543)

# Firefox (nightly) #
Testing web-platform-tests at revision 5d8ae0f080ca2f59f332257d3674245c4b1a8cc1
Using browser at version BuildID 20170526150217; SourceStamp 9104506c0a5eaac89b6c22c804c83ccee7d6e662
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236491544)

# Sauce (safari) #
Testing web-platform-tests at revision 5d8ae0f080ca2f59f332257d3674245c4b1a8cc1
Using browser at version 10.0
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236491550)

# Chrome (unstable) #
Testing web-platform-tests at revision 5d8ae0f080ca2f59f332257d3674245c4b1a8cc1
Using browser at version 60.0.3107.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/236491551)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 5d8ae0f080ca2f59f332257d3674245c4b1a8cc1
Using browser at version 14.14393
Starting 10 test iterations

**Review by mkruisselbrink — APPROVED** [review]

**Comment by foolip** [comment]
The branch really does have all those extra commits, but all except one are empty. I'll squash and merge so that only the one remains.

**Pull request merged**
