### PR TITLE
Revert "[css-viewport] Remove assert for offsetTop after modifying zoom property"

### PR DESCRIPTION
**Pull request by chrishtr**
Reverts web-platform-tests/wpt#45927

Oops, accidentally pressed merge.

### CODE REVIEW

**Comment by chrishtr** [comment]
Emilio you said:

@chrishtr doesn't it? The scroll* values should (and do, afaict) return the unzoomed coordinates, that's what was resolved on isn't it? In fact https://drafts.csswg.org/css-viewport/#zoom-om clarifies that when propagated to the viewport it shouldn't.

I agree that the css-viewport spec says that scroll should not be affected by zoom (I think that's what you are saying above?)

Therefore isn't the assert in this test valid?

**Comment by emilio** [comment]
But this assert is not about what coordinates the API returns (the APIs return the right coordinates on Firefox for example).

This is about which scroll position gets preserved when zoom dynamically changes, which afaict isn't well defined... In fact, the assert just kinda works because there's no scroll anchoring involved in this test-case, but AIUI which scroll position you end up with when the scroll area changes isn't particularly well defined.

Firefox uses un-zoomed CSS coordinates to store the scroll position, while presumably blink / WebKit store zoomed CSS coordinates, which is what explains this difference, right?

**Comment by emilio** [comment]
I guess the chrome (and WebKit maybe?) behavior is slightly more consistent with page zoom, which makes sense, but I still think it's not particularly well defined that scroll offsets should be preserved when zoom changes, just like they might not be preserved when width / height changes...

**Comment by chrishtr** [comment]
> This is about which scroll position gets preserved when zoom dynamically changes, which afaict isn't well defined... In fact, the assert just kinda works because there's no scroll anchoring involved in this test-case, but AIUI which scroll position you end up with when the scroll area changes isn't particularly well defined.

Fair enough that changes to scroll after zoom aren't fully defined.

**Pull request closed without merging**
