### PR TITLE
Fixing response clone test and ironing utils.js for different UInt8Array behavior

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by jdm** [comment]
It's not clear to me that papering over differences in the Uint8ArrayBuffer constructor is helpful. That's a standard API with well-defined semantics; if it's not implemented according to the specification, why do we want to hide that fact?

**Comment by youennf** [comment]
I believe all browsers accept "new Uint8Array()".
Some browsers seem to accept "new Uint8Array(undefined)" while others do not.
From a quick reading of the spec, the second behavior seems compliant.
Given that, since for empty streams, undefined may be passed to Uint8Array, I added a check in this method. I am fine changing the caller function though.

**Comment by youennf** [comment]
If needed, I can split the patch to at least fix the response clone test

**Comment by jdm** [comment]
Thinking about it further, I'm fine with this change. There are other tests that can focus on ES type specification behaviour.

**Pull request merged**
