### PR TITLE
Create new top-level dir, OWNERS for CSS Paint API

### PR DESCRIPTION
**Pull request by bfgeek**
This is for beginning to import the blink-tests into web-platform-tests for the CSS Paint API[1]

[1] https://drafts.css-houdini.org/css-paint-api/

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5723)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226498782)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226498784)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d93389a219bf8e038bc77068dd122c5b98ad4c8f
Using browser at version BuildID 20170427100655; SourceStamp 0b77ed3f26c5335503bc16e85b8c067382e7bb1e
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226498791)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d93389a219bf8e038bc77068dd122c5b98ad4c8f

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5723/)

**Comment by bfgeek** [comment]
So I placed under top level `css-paint-api-1`, this could also go under `css/css-paint-api-1`.

`css-typed-om` is under top level which i copied for now. @gsnedders thoughts?

**Comment by gsnedders** [comment]
@bfgeek the intent, AIUI, has been to have Houdini stuff following wpt norms, so top-level and no `-1` in the directory; @asterns can clarify if I'm wrong.

Do we want other editors to be owners too?

**Comment by bfgeek** [comment]
sgtm, done & done.

**Comment by kojiishi** [comment]
Discussed with @foolip in other place but JFYI
* For CSS build system to pick tests, CSS meta header is needed.
* Currently, lint checks CSS meta data only for files under css/
* CSS build is still needed for specs to move rec-track forward in CSSWG afaiu.

**Comment by gsnedders** [comment]
My understanding from six months ago was the intention for Houdini was to use the same tooling as everyone else has been using around wpt to move along the REC-track (i.e., to fulfil the CR exit criteria requirement of demonstrating interoperability) instead of the CSSWG's old tooling that relies on the build system and all of its metadata.

**Comment by bfgeek** [comment]
Yeah the above is correct from my memory, this also matches `css-typed-om`, ok to merge?

**Review by kojiishi — APPROVED** [review]
lgtm

**Pull request merged**
