### PR TITLE
pywebsocket: Add and update to pywebsocket3

### PR DESCRIPTION
**Pull request by quasi-mod**
This commit adds pywebsocket3 as a subtree to //tools/third_party.
It also updates //tools/serve/serve.py to use pywebsocket 3 by updating localpaths, and also removing the use of deprecated functions.

Issue: #21749

### CODE REVIEW

**Review by ricea — APPROVED** [review]
Although this change looks enormous, all of the changes under third_party/pywebsocket3 have already been reviewed as part of the pywebsocket3 project, and so it is not necessary to review them again.

**Comment by Ms2ger** [comment]
Thanks! Let's give this a few days, though.

**Comment by jgraham** [comment]
https://community-tc.services.mozilla.com/tasks/groups/Mozwbk1DQv2OUePi94vpyA is a trial run on Firefox nightly; we need to be careful that we don't end up accidentality regressing tests.

**Comment by jgraham** [comment]
Really I think we should make changes to pywebsocket automatically run the websockets tests.

**Comment by ricea** [comment]
> Really I think we should make changes to pywebsocket automatically run the websockets tests.

This would be a really useful! It's easy for us to test new versions against Chromium, but different browsers have subtly different behaviour.

**Comment by jgraham** [comment]
It's sort of unclear what the best approach is there. Currently we have two kinds of tests that we run in CI:
* Infrastructure tests, where all the tests have to match the expected outcome.
* Affected tests, where we don't have strict requirements on the expected outcome, but we check the tests for stability. We also produce wpt.fyi links for doing before/after comparisons.

In the case of changes to pywebsocket I think we want something that runs the websockets tests, doesn't expect a specific outcome, produces a wpt.fyi link for human verification, and doesn't try to stability check the tests, makes sense. But that's not quite like either of the things we are currently doing. Does anyone have an opinion on the best way forward here?

**Comment by jgraham** [comment]
https://wpt.fyi/results/?diff&filter=ADC&q=websockets&run_id=426970002&run_id=411710023 seems to be the Firefox diff from this branch vs the base; that suggests this upgrade isn't causing too many problems, although there is one timeout in `wpt /websockets/opening-handshake/005.html` that should be investigated; that test isn't marked as intermittent in the gecko infrastructure.

**Comment by Hexcles** [comment]
I wonder whether we keep a list of all the subtrees (and their upstream repos) somewhere. I know at least we have `WebIDL`. AFAIK, subtree commit messages do not record the upstream repo URL, which we need when doing `git subtree pull` in the future.

Also FWIW, this PR does a `git subtree add --squash`, which I think is the right call here, but I just wanted to point that out in case some may disagree.

**Comment by quasi-mod** [comment]
It seems like the failure in `wpt /websockets/opening-handshake/005.html` is due to a small API difference in pywebsocket and pywebsocket3. `compute_accept` used to return `(accept bytes string, accept binary)`. Since we rarely use accept binary, we only return accept bytes string in pywebsocket3. I'll fix this immediately.

**Comment by quasi-mod** [comment]
Fixed the corresponding websocket handler. I have manually checked `wpt /websockets/opening-handshake/005.html` and it seems to pass.

**Comment by stephenmcgruer** [comment]
I have similarly pushed a trigger for Chrome Dev; https://community-tc.services.mozilla.com/tasks/groups/dxM3fcEbQBilzQ62CSDelg is the task group (which is still underway).

**Comment by stephenmcgruer** [comment]
I may have messed up the trigger run, but the results from https://wpt.fyi/results/?diff&filter=ADC&q=websockets&run_id=424710003&run_id=419330010 are quite surprising; they show 231 *newly passing* websocket tests in Chrome with pywebsocket3. This is worth investigating (at the very least, trying to reproduce locally).

**Comment by Hexcles** [comment]
That matches the results I observed in #21868 , i.e. the difference is caused by removing our local modification.

**Comment by quasi-mod** [comment]
It seems like the tests used to fail since it had the bug reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=949763). 

I tried running wpt tests locally (using `./wpt serve` and trying `websockets` tests locally on chrome), and was not able to reproduce the failure that should occur (tests are passing correctly). I set up the server both on the original pywebsocket and the new pywebsocket3, both with and without the patch. I used the tests in `websockets/closing_handshake`, and all of the tests passed.

From this, I assume that it might be a bug in wpt.fyi, which I am afraid I am not familiar with.

**Comment by stephenmcgruer** [comment]
@quasi-mod That is not what I see on my local desktop. I checked out both your change:

```
git fetch origin refs/pull/21845/head
git checkout -b quasi-mod/update-to-pywebsocket3 FETCH_HEAD
```

As well as the change you are based on (643567332831222c8589c47a4bf8bb6e1c9112d2), and saw the following results.

```
$ git checkout quasi-mod/update-to-pywebsocket3
$ ./wpt run --channel=experimental chrome websockets/
...
Ran 425 tests finished in 298.7 seconds.
  • 400 ran as expected. 0 tests skipped.
  • 25 tests had unexpected subtest results
```

```
$ git checkout before_pywebsocket3_change
$ ./wpt run --channel=experimental chrome websockets/
...
Ran 425 tests finished in 1026.1 seconds.
  • 281 ran as expected. 0 tests skipped.
  • 4 tests timed out unexpectedly
  • 144 tests had unexpected subtest results
```

So I also see a bunch of new passes. In https://github.com/web-platform-tests/wpt/pull/21868#issuecomment-588582492 ricea is theorizing that this is due to crbug.com/949763. That seems to make sense; https://github.com/web-platform-tests/wpt/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a likely keeps the server alive and then Chrome considers it an unclean shutdown. Your upgrade to pywebsocket3 reverts that commit, and so the server is no longer kept alive.

I think we should fix crbug.com/949763 (and add a WPT test for a server keeping the connection open!), but I don't think doing so blocks this PR. As I understand it, there are now no new failures in Firefox, so it seems like https://github.com/web-platform-tests/wpt/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a is not required for their use-case, and I consider crbug.com/949763 a separate issue to be fixed.

@Hexcles @jgraham any objections?

**Comment by Hexcles** [comment]
I agree with both the theory and the action plan.

**Comment by jgraham** [comment]
That sounds good to me.

**Comment by stephenmcgruer** [comment]
Close/opening this to re-run the CI.

**Review by stephenmcgruer — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
Ah, this needs code owner review from @jgraham (TIL we have that turned on for some directories!)

**Review by jgraham — APPROVED** [review]

**Comment by jgraham** [comment]
I think this requires a manual push because GitHub doesn't have a way to preserve the unusual shape of the git subtree history.

**Comment by stephenmcgruer** [comment]
I have manually pushed the subtree add of pywebsocket3 (the first two commits), via:

```
$ git subtree add --prefix tools/third_party/pywebsocket3 https://github.com/GoogleChromeLabs/pywebsocket3.git master --squash
$ git push origin master
```

And then force-pushed this branch to bring it on-top of master:

```
$ git checkout -b smcgruer/pywebsocket3
$ git fetch origin refs/pull/21845/head
$ git cherry-pick 771a03aea9ee5a87db3f8c76a45d2983659ee667 c9a5a2df9905ca61af120a69a2127cdb7496b5d4 bc16f91c5d365700747f61663fa1c42af79e4309
$ git push git@github.com:quasi-mod/wpt.git HEAD:update-to-pywebsocket3 --force
```

Once the checks are green, we should be able to land this PR :)

**Pull request merged**
