### PR TITLE
XMLHttpRequest: fix broken authentication test

### LINKED ISSUE #3429: XMLHttpRequest/resources/auth2/corsenabled.py is broken
It assumes the current working directory is the root of the WPT tests, but that does not appear to be the case.

### LINKED ISSUE #4547: XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm is a bogus test
The test does a GET to corsenabled.py and expects `.responseText` to contain something interesting (like the things it put in the x-user and x-pass headers).

But corsenabled.py always returns "Test" as the response body, so there is no way this test can pass.

I have no idea whether the script (shared with other tests, note!) or the test is wrong.

### PR DESCRIPTION
**Pull request by annevk**
Fixes #3429 and fixes #4547.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5156/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/211697163)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 94f3d622b56b02b252aabd584b49c5d9fbae6edf
Using browser at version BuildID 20170314110401; SourceStamp 6d38ad302429c98115c354d643e81987ecec5d3c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5156/XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm">/XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm</a></summary>


|                                                   Subtest                                                   | Results |           Messages          |
|-------------------------------------------------------------------------------------------------------------|---------|-----------------------------|
|                                                                                                             | OK      |                             |
| `XMLHttpRequest: send() - "Basic" authenticated CORS request using setRequestHeader() (expects to succeed)` | FAIL    | `A network error occurred.` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/211697164)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 94f3d622b56b02b252aabd584b49c5d9fbae6edf
Using browser at version 58.0.3029.19 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5156/XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm">/XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm</a></summary>


|                                                   Subtest                                                   | Results |                                                                      Messages                                                                      |
|-------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                                                                                    |
| `XMLHttpRequest: send() - "Basic" authenticated CORS request using setRequestHeader() (expects to succeed)` | FAIL    | `Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://www1.web-platform.test:8000/XMLHttpRequest/resources/auth2/corsenabled.py'.` |

</details>
</details>

**Comment by annevk** [comment]
Hmm, I don't understand why this test fails in the bot but passes locally. @jgraham?

**Comment by annevk** [comment]
Seems the bot problem resolved itself.

**Pull request merged**
