### PR TITLE
Add Web Audio API editors to webaudio/OWNERS

### PR DESCRIPTION
**Pull request by foolip**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5655)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5655/)

**Comment by foolip** [comment]
@padenot @rtoy, please confirm and feel free to add anyone else who might want to review tests.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225098469)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225098471)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 09682127b6be5b3b055e8746028039201a978a1a
Using browser at version BuildID 20170422100218; SourceStamp 7d85b081bfabe91dbf18a421f1eee2a32f335823
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225098477)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 09682127b6be5b3b055e8746028039201a978a1a

**Comment by rtoy** [comment]
lgtm.

**Pull request merged**
