### PR TITLE
URL: file and non-special URL setters

### PR DESCRIPTION
**Pull request by annevk**
Also file URL host parsing.

See https://github.com/whatwg/url/pull/224 for the corresponding URL Standard change.

### CODE REVIEW

**Comment by domenic** [comment]
whatwg-url PR: https://github.com/jsdom/whatwg-url/pull/71

All the new tests appear to pass, but a bunch of old ones have become invalidated, for the host and hostname setters. I'll only list host since hostname is analogous. As usual, "expected" = new WPTs, "actual" = jsdom/whatwg-url with the spec patch applied.

```
  1) Web platform tests setters host <sc://x/>.host = " " :

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///

  2) Web platform tests setters host <sc://x/>.host = "
" :

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///
" :) Web platform tests setters host <sc://x/>.host = "

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///

  4) Web platform tests setters host <sc://x/>.host = "#" :

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///

  5) Web platform tests setters host <sc://x/>.host = "/" :

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///

  6) Web platform tests setters host <sc://x/>.host = "?" :

      AssertionError: 'sc://x/' == 'sc:///'
      + expected - actual

      -sc://x/
      +sc:///

  7) Web platform tests setters host <view-source+http://example.net/foo>.host = "" The empty host is OK for non-special schemes:

      AssertionError: 'view-source+http://example.net/foo' == 'view-source+http:///foo'
      + expected - actual

      -view-source+http://example.net/foo
      +view-source+http:///foo
```

**Comment by annevk** [comment]
It turns out those are still valid. I found a small glitch in your jsdom/whatwg-url code.

**Comment by domenic** [comment]
Dang, I'm really losing my touch.

**Review by domenic — APPROVED** [review]

**Comment by annevk** [comment]
I'll wait with landing these until the changes in URL and HTML are also reviewed. Would be nice to keep everything synchronized somewhat.

**Pull request merged**
