### PR TITLE
Add "0xCA <=> U+05BA" mapping to windows-1255 (spec change)

### PR DESCRIPTION
**Pull request by jungshik**
In whatwg/encoding#73, the encoding spec was changed to add "0xCA<=>U+05BA" mapping to 
windows-1255. 

@annevk , can you review? Thanks

### CODE REVIEW

**Comment by Ms2ger** [comment]
Also submitted independently in https://bugzilla.mozilla.org/show_bug.cgi?id=1312384

**Comment by annevk** [comment]
@jgraham which should we land with this kind of conflict?

**Comment by jungshik** [comment]
I'm confused. wpt is getting an automatic push from hg.mozilla.org ? 
Anyway, https://hg.mozilla.org/integration/mozilla-inbound/rev/6963f5ab0000 seems identical to my pull request.

**Comment by inexorabletash** [comment]
> wpt is getting an automatic push from hg.mozilla.org ? 

Yes - isn't that awesome? (Hopefully coming soon to chromium/blink, too.)

**Comment by jungshik** [comment]
>>wpt is getting an automatic push from hg.mozilla.org ?
> Yes - isn't that awesome? (Hopefully coming soon to chromium/blink, too.)

I see. Thank you. In that case, feel free to close this one if the automatic push from hg.mozilla.org is gonna be done soon (say, in a couple of days).

**Comment by jgraham** [comment]
I can start a new one today.

**Comment by annevk** [comment]
Sorry about the conflict @jungshik, hope we don't get too many of these. 😊

**Comment by jungshik** [comment]
No problem, @annevk 

BTW, was the change (mozilla's : identical to mine) landed? I don't see it in the tree.

**Comment by annevk** [comment]
@jgraham can best answer that. Syncing is manual still.

**Comment by jungshik** [comment]
Gee. I thought it's automatic and pretty frequent (if not daily). Given that it's neither, just merging this world have been quicker.

**Comment by annevk** [comment]
Agreed, I went ahead and did so, given that I can't seem to chat with @jgraham.

**Pull request merged**
