### PR TITLE
adds test coverage for the html li@type

### PR DESCRIPTION
**Pull request by common-nighthawk**

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by zcorpan** [comment]
comments in critic

**Comment by common-nighthawk** [comment]
thanks for the detailed comments in critic.  i misunderstood the documentation, and made changes to the tests accordingly.

unfortunately, i made a mistake using git.  i went to squash some of my commits before updating the PR, and was off by one in my count.  i combined some of my new updates with the initial one.  because that seemed extra-messy, i just went back and combined all of my commits (starting from the original) into one.

bleh!  i know this messes up critic.  im sorry about that.  the changes in this PR are correct, just combined.  let me know if you want me to submit anything in a different way to fix this.

**Comment by zcorpan** [comment]
Lgtm

**Pull request merged**
