### PR TITLE
Fixes #6073: flaky animated flexbox test

### LINKED ISSUE #6073: /css/css-flexbox-1/css-flexbox-height-animation-stretch.html is flaky
#6071 made a zero-effect change to this test and the stability bot reported it as flaky. Needs investigation.

cc/ @gregwhitworth @jugglinmike

### PR DESCRIPTION
**Pull request by gsnedders**
fixes #6073

### CODE REVIEW

**Review by mrego — APPROVED** [review]
Let's see if this fixes the issue.
The change LGTM.

**Comment by cbiesinger** [comment]
While the patch seems good, will it actually fix anything? That is, do the various test runners pay attention to the flag?

**Comment by gsnedders** [comment]
@cbiesinger The manifest generator does, and it'll make it get picked up as a manual test in all the test runners.

**Comment by cbiesinger** [comment]
Ah OK. Thanks for the explanation, though it's unfortunate that we won't be able to run this automated :(

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/237564169)

# Firefox (nightly) #
Testing web-platform-tests at revision bd81d8f6a8a613d460f12afc8d91394c6a1fd502
Using browser at version BuildID 20170530100155; SourceStamp 286f71223256cbb3a769432fd860f563c4886e81
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/237564170)

# Sauce (safari) #
Testing web-platform-tests at revision bd81d8f6a8a613d460f12afc8d91394c6a1fd502
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/237564176)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/237564177)

# Sauce (MicrosoftEdge) #

**Pull request merged**
