### PR TITLE
IndexedDB: Tests should self-cleanup

### PR DESCRIPTION
**Pull request by inexorabletash**
Ensure connections are closed before the test is done so that test cleanup can run.

For https://github.com/w3c/web-platform-tests/issues/4560

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5676)

### CODE REVIEW

**Comment by inexorabletash** [comment]
@brettz9 - can you review?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5676/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225320297)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225320299)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 67deb5935974c1e58aaa685b133566c1acdd2ae9
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>9 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbdatabase_close.htm">/IndexedDB/idbdatabase_close.htm</a></summary>


|                                              Subtest                                               | Results | Messages |
|----------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                    | OK      |          |
| `IDBDatabase.close() - unblock the version change transaction created by an open database request` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbfactory_open10.htm">/IndexedDB/idbfactory_open10.htm</a></summary>


|                        Subtest                         | Results | Messages |
|--------------------------------------------------------|---------|----------|
|                                                        | ERROR   |          |
| `IDBFactory.open() - error in upgradeneeded resets db` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbfactory_open11.htm">/IndexedDB/idbfactory_open11.htm</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `IDBFactory.open() - second open's transaction is available to get objectStores` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbfactory_open3.htm">/IndexedDB/idbfactory_open3.htm</a></summary>


|                         Subtest                         | Results | Messages |
|---------------------------------------------------------|---------|----------|
|                                                         | OK      |          |
| `IDBFactory.open() - no version opens current database` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbfactory_open6.htm">/IndexedDB/idbfactory_open6.htm</a></summary>


|                                Subtest                                | Results | Messages |
|-----------------------------------------------------------------------|---------|----------|
|                                                                       | OK      |          |
| `IDBFactory.open() - open database with a lower version than current` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbfactory_open7.htm">/IndexedDB/idbfactory_open7.htm</a></summary>


|                                Subtest                                 | Results | Messages |
|------------------------------------------------------------------------|---------|----------|
|                                                                        | OK      |          |
| `IDBFactory.open() - open database with a higher version than current` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbobjectstore_deleteIndex.htm">/IndexedDB/idbobjectstore_deleteIndex.htm</a></summary>


|                       Subtest                       | Results | Messages |
|-----------------------------------------------------|---------|----------|
|                                                     | OK      |          |
| `IDBObjectStore.deleteIndex() - removes the index ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbrequest-onupgradeneeded.htm">/IndexedDB/idbrequest-onupgradeneeded.htm</a></summary>


|                                  Subtest                                   | Results | Messages |
|----------------------------------------------------------------------------|---------|----------|
|                                                                            | ERROR   |          |
| `indexedDB.delete called from upgradeneeded handler`                       | PASS    |          |
| `Abort transaction before deleting database in upgradeneeded handler`      | PASS    |          |
| `Abort transaction after deleting database in upgradeneeded event handler` | PASS    |          |
| `transaction oncomplete ordering relative to open request onsuccess`       | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5676/IndexedDB/idbtransaction_objectStoreNames.html">/IndexedDB/idbtransaction_objectStoreNames.html</a></summary>


|                            Subtest                             | Results | Messages |
|----------------------------------------------------------------|---------|----------|
|                                                                | ERROR   |          |
| `IDBTransaction.objectStoreNames - during upgrade transaction` | PASS    |          |
| `IDBTransaction.objectStoreNames - value after close`          | PASS    |          |
| `IDBTransaction.objectStoreNames - transaction scope`          | PASS    |          |
| `IDBTransaction.objectStoreNames - value after commit`         | PASS    |          |
| `IDBTransaction.objectStoreNames - value after abort`          | PASS    |          |
| `IDBTransaction.objectStoreNames - sorting`                    | PASS    |          |
| `IDBTransaction.objectStoreNames - no duplicates`              | PASS    |          |
| `IDBTransaction.objectStoreNames - unusual names`              | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225320307)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 67deb5935974c1e58aaa685b133566c1acdd2ae9

**Review by pwnall — COMMENTED** [review]
LGTM.

I expanded the diffs and checked that the var names do point to databases that should be closed.

**Review by pwnall — APPROVED** [review]

**Comment by brettz9** [comment]
Yup, all good to me as well...

**Pull request merged**
