### PR TITLE
window.open() should throw for URL parser failures

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/html/issues/2490.

### CODE REVIEW

**Comment by annevk** [comment]
The downside of this test is that it ends up opening a lot of windows in browsers with bugs. How problematic is that?

**Comment by w3c-bots** [comment]
*This report has been truncated because the total content is 110306 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228601972)

# Firefox (nightly channel) #
Testing web-platform-tests at revision fb619b47a523ede1143ec6cc656aa1a9fdda084c
Using browser at version BuildID 20170502100421; SourceStamp 48c0fd9c9ec5d68061ea7b59358874ae8da72572
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5776/url/failure.html">/url/failure.html</a></summary>


|                              Subtest                              | Results |                                                                                                                                                                                              Messages                                                                                                                                                                                              |
|-------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                   | OK      |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Loading dataâ¦`                                                   | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `URL's href: file://example:1/ should throw`                      | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: file://example:1/ should throw`                             | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): file://example:1/ should throw`                    | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: file://example:1/ should throw`                 | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "Error: Access to 'file:///' from script denied" ("Error") expected object "TypeError" ("TypeError")`                                                                                                                                                                                                                  |
| `window.open(): file://example:1/ should throw`                   | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "Error: Access to 'file:///' from script denied" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                                                                                                                                                                                   |
| `URL's href: file://example:test/ should throw`                   | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: file://example:test/ should throw`                          | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): file://example:test/ should throw`                 | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: file://example:test/ should throw`              | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "Error: Access to 'file:///' from script denied" ("Error") expected object "TypeError" ("TypeError")`                                                                                                                                                                                                                  |
| `window.open(): file://example:test/ should throw`                | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "Error: Access to 'file:///' from script denied" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                                                                                                                                                                                   |
| `URL's href: file://example%/ should throw`                       | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: file://example%/ should throw`                              | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): file://example%/ should throw`                     | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: file://example%/ should throw`                  | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "Error: Access to 'file:///' from script denied" ("Error") expected object "TypeError" ("TypeError")`                                                                                                                                                                                                                  |
| `window.open(): file://example%/ should throw`                    | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "Error: Access to 'file:///' from script denied" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                                                                                                                                                                                   |
| `URL's href: file://[example]/ should throw`                      | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: file://[example]/ should throw`                             | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): file://[example]/ should throw`                    | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: file://[example]/ should throw`                 | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "Error: Access to 'file:///' from script denied" ("Error") expected object "TypeError" ("TypeError")`                                                                                                                                                                                                                  |
| `window.open(): file://[example]/ should throw`                   | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "Error: Access to 'file:///' from script denied" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                                                                                                                                                                                   |
| `URL's href: http://user:pass@/ should throw`                     | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://user:pass@/ should throw`                            | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://user:pass@/ should throw`                   | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://user:pass@/ should throw`                | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://user:pass@/ should throw`                  | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http://foo:-80/ should throw`                        | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://foo:-80/ should throw`                               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://foo:-80/ should throw`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://foo:-80/ should throw`                   | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://foo:-80/ should throw`                     | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http:/:@/www.example.com should throw`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:/:@/www.example.com should throw`                      | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:/:@/www.example.com should throw`             | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:/:@/www.example.com should throw`          | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:/:@/www.example.com should throw`            | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http://user@/www.example.com should throw`           | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://user@/www.example.com should throw`                  | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://user@/www.example.com should throw`         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://user@/www.example.com should throw`      | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://user@/www.example.com should throw`        | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http:@/www.example.com should throw`                 | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:@/www.example.com should throw`                        | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:@/www.example.com should throw`               | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:@/www.example.com should throw`            | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:@/www.example.com should throw`              | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http:/@/www.example.com should throw`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:/@/www.example.com should throw`                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:/@/www.example.com should throw`              | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:/@/www.example.com should throw`           | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:/@/www.example.com should throw`             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http://@/www.example.com should throw`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://@/www.example.com should throw`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://@/www.example.com should throw`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://@/www.example.com should throw`          | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://@/www.example.com should throw`            | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: https:@/www.example.com should throw`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: https:@/www.example.com should throw`                       | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): https:@/www.example.com should throw`              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: https:@/www.example.com should throw`           | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): https:@/www.example.com should throw`             | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http:a:b@/www.example.com should throw`              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:a:b@/www.example.com should throw`                     | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:a:b@/www.example.com should throw`            | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:a:b@/www.example.com should throw`         | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:a:b@/www.example.com should throw`           | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http:/a:b@/www.example.com should throw`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:/a:b@/www.example.com should throw`                    | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:/a:b@/www.example.com should throw`           | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:/a:b@/www.example.com should throw`        | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:/a:b@/www.example.com should throw`          | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http://a:b@/www.example.com should throw`            | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://a:b@/www.example.com should throw`                   | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://a:b@/www.example.com should throw`          | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://a:b@/www.example.com should throw`       | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://a:b@/www.example.com should throw`         | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http::@/www.example.com should throw`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http::@/www.example.com should throw`                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http::@/www.example.com should throw`              | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http::@/www.example.com should throw`           | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http::@/www.example.com should throw`             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http:@:www.example.com should throw`                 | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:@:www.example.com should throw`                        | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:@:www.example.com should throw`               | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:@:www.example.com should throw`            | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:@:www.example.com should throw`              | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http:/@:www.example.com should throw`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http:/@:www.example.com should throw`                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): http:/@:www.example.com should throw`              | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: http:/@:www.example.com should throw`           | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): http:/@:www.example.com should throw`             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: http://@:www.example.com should throw`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://@:www.example.com should throw`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://@:www.example.com should throw`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://@:www.example.com should throw`          | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://@:www.example.com should throw`            | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: https://ï¿½ should throw`                              | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: https://ï¿½ should throw`                                     | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): https://ï¿½ should throw`                            | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: https://ï¿½ should throw`                         | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): https://ï¿½ should throw`                           | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: https://%EF%BF%BD should throw`                      | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: https://%EF%BF%BD should throw`                             | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): https://%EF%BF%BD should throw`                    | FAIL    | `assert_throws: function "() => self.navigator.sendBeacon(test.input)" did not throw`                                                                                                                                                                                                                                                                                                              |
| `Location's href: https://%EF%BF%BD should throw`                 | FAIL    | `assert_throws: function "() => self[0].location = test.input" did not throw`                                                                                                                                                                                                                                                                                                                      |
| `window.open(): https://%EF%BF%BD should throw`                   | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: https://x x:12 should throw`                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: https://x x:12 should throw`                                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): https://x x:12 should throw`                       | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: https://x x:12 should throw`                    | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): https://x x:12 should throw`                      | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: http://[www.google.com]/ should throw`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `XHR: http://[www.google.com]/ should throw`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `sendBeacon(): http://[www.google.com]/ should throw`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: http://[www.google.com]/ should throw`          | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_MALFORMED_URI") expected object "TypeError" ("TypeError")`                                            |
| `window.open(): http://[www.google.com]/ should throw`            | FAIL    | `assert_throws: function "() => self.open(test.input)" threw object "[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 38"  data: no]" that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                              |
| `URL's href: sc:/// should throw`                                | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: sc:/// should throw`                                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): sc:/// should throw`                              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: sc:/// should throw`                           | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI scheme corresponds to an unknown protocol handler"  nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_UNKNOWN_PROTOCOL") expected object "TypeError" ("TypeError")` |
| `window.open(): sc:/// should throw`                             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: sc:// / should throw`                                | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: sc:// / should throw`                                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): sc:// / should throw`                              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: sc:// / should throw`                           | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI scheme corresponds to an unknown protocol handler"  nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_UNKNOWN_PROTOCOL") expected object "TypeError" ("TypeError")` |
| `window.open(): sc:// / should throw`                             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: sc://@/ should throw`                                | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: sc://@/ should throw`                                       | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): sc://@/ should throw`                              | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: sc://@/ should throw`                           | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI scheme corresponds to an unknown protocol handler"  nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_UNKNOWN_PROTOCOL") expected object "TypeError" ("TypeError")` |
| `window.open(): sc://@/ should throw`                             | FAIL    | `assert_throws: function "() => self.open(test.input)" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `URL's href: sc://te@s:t@/ should throw`                          | FAIL    | `assert_throws: function "() => url.href = test.input" did not throw`                                                                                                                                                                                                                                                                                                                              |
| `XHR: sc://te@s:t@/ should throw`                                 | FAIL    | `assert_throws: function "() => client.open("GET", test.input)" did not throw`                                                                                                                                                                                                                                                                                                                     |
| `sendBeacon(): sc://te@s:t@/ should throw`                        | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                    |
| `Location's href: sc://te@s:t@/ should throw`                     | FAIL    | `assert_throws: function "() => self[0].location = test.input" threw object "[Exception... "The URI scheme corresponds to an unknown protocol handler"  nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)"  location: "JS frame :: http://web-platform.test:8000/url/failure.html :: runTests/</< :: line 34"  data: no]" ("NS_ERROR_UNKNOWN_PROTOCOL") expected object "TypeError" ("TypeError")` |
| `window.open(): sc://te@s:t@/ should throw`                       | FAIL    | `assert_throws: function "() =>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228601978)

# Chrome (unstable channel) #
Testing web-platform-tests at revision fb619b47a523ede1143ec6cc656aa1a9fdda084c

**Comment by zcorpan** [comment]
I'm not aware of it being particularly problematic, and the same is true for other `window.open` tests.

A problem I noticed when testing `window.open` is that Firefox is relatively slow with opening new windows (possibly by design), which can cause the test to time out. Setting a meta timeout to long helps with that.

You can use `add_cleanup` to close any windows opened (I guess only works for same origin, but still).

**Comment by annevk** [comment]
There's no same-origin windows really since they're all erroneous URLs.

I didn't get a timeout for this test locally, did you?

**Comment by zcorpan** [comment]
No timeout here.

Since there's no *features*  argument, Firefox opens tabs, which appears to be much faster than opening popups.

It appears that WebKit/Chromium/Gecko all actually allow closing all of the opened tabs with
```
      assert_throws("SyntaxError", () => {
        const win = self.open(test.input)
        win.close()
      })
```

**Comment by annevk** [comment]
I added some cleanup.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5776/)

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
