### PR TITLE
manual tests for PaymentResponse.methodName attr

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-21 05:44:35
Finished: 2017-08-21 05:49:18



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17584)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266683886)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-21 05:44:35
Finished: 2017-08-21 05:49:18



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17584)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266683886)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-21 05:44:35
Finished: 2017-08-21 05:49:18



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17584)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/266683886)

**Review by edenchuang — APPROVED** [review]
LGTM

**Pull request merged**
