### PR TITLE
user activation must survive postMessage() to call show()

### PR DESCRIPTION
**Pull request by marcoscaceres**
Check that we can call pr.show() in an iframe via postMessage(), which
is triggered by user activation.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This passes in Chrome, but fails in Firefox ATM.

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-19 05:51:36
Finished: 2018-03-19 06:00:14


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

<li>chrome:dev</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26164)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/355223371)

**Comment by marcoscaceres** [comment]
May help make progress on https://github.com/whatwg/html/issues/1903 ?

**Review by mnoorenberghe — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@domenic wrote the spec text in HTML, so he can confirm :)

**Comment by domenic** [comment]
Sorry, I'm on vacation until April :)

**Comment by marcoscaceres** [comment]
> Sorry, I'm on vacation until April :)

Np! Enjoy! 🏖⛰🏙

**Pull request merged**
