### PR TITLE
[html] Avoid race condition in test

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 9de55244bab4bcb41f97216f1cabd2a95f16c0bd
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4914/html/browsers/the-window-object/window-open-noopener.html">/html/browsers/the-window-object/window-open-noopener.html</a></summary>


|                             Subtest                              | Results |
|------------------------------------------------------------------|---------|
|                                                                  | TIMEOUT |
| `noopener needs to be present as a token on its own yet again`   | PASS    |
| `noopener window.open targeting _parent`                         | NOTRUN  |
| `noopener needs to be present as a token on its own`             | FAIL    |
| `noopener window.open targeting _self`                           | NOTRUN  |
| `noopener needs to be present as a token on its own again`       | FAIL    |
| `Trailing noopener should work`                                  | PASS    |
| `Leading noopener should work`                                   | PASS    |
| `Interior noopener should work`                                  | PASS    |
| `noopener window.open targeting _top`                            | NOTRUN  |
| `window.open() with 'noopener' should not reuse existing target` | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 9de55244bab4bcb41f97216f1cabd2a95f16c0bd
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4914/html/browsers/the-window-object/window-open-noopener.html">/html/browsers/the-window-object/window-open-noopener.html</a></summary>


|                             Subtest                              | Results |
|------------------------------------------------------------------|---------|
|                                                                  | OK      |
| `noopener needs to be present as a token on its own yet again`   | PASS    |
| `noopener window.open targeting _parent`                         | PASS    |
| `noopener needs to be present as a token on its own`             | PASS    |
| `noopener window.open targeting _self`                           | PASS    |
| `noopener needs to be present as a token on its own again`       | PASS    |
| `Trailing noopener should work`                                  | PASS    |
| `Leading noopener should work`                                   | PASS    |
| `Interior noopener should work`                                  | PASS    |
| `noopener window.open targeting _top`                            | PASS    |
| `window.open() with 'noopener' should not reuse existing target` | PASS    |

</details>
</details>

**Comment by jugglinmike** [comment]
Thanks, @zcorpan!

**Comment by zcorpan** [comment]
Thank *you*!

**Pull request merged**
