### PR TITLE
html/cross-origin-opener-policy/coop-csp-sandbox-navigate.https.html …

### PR DESCRIPTION
**Pull request by cdumez**
…is flaky

Increase the timeout inside the test from 1.5 seconds to 10 seconds as this is causing
flakiness on some of the WebKit bots.

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
Unless you also add https://web-platform-tests.org/writing-tests/testharness-api.html#harness-timeout I think this will result in a harness timeout, no?

**Comment by foolip** [comment]
> Unless you also add https://web-platform-tests.org/writing-tests/testharness-api.html#harness-timeout I think this will result in a harness timeout, no?

Since the default timeout is 10 seconds, I might even be a race between different kinds of timeouts. So yes, `<meta name="timeout" content="long">` seems like a good idea here.

**Comment by cdumez** [comment]
Oh, I didn't realize the default timeout was only 10 seconds. I added the meta tag.

**Review by annevk — APPROVED** [review]

**Comment by cdumez** [comment]
Not sure what is up with the sink-task  / update-built  failures and how to fix them.

**Comment by annevk** [comment]
@cdumez I think if you rebase and force push it should go away. It seems to be related to a Web IDL change I made that got corrected in a later commit.

**Pull request merged**
