### PR TITLE
Add tests for the base URL in workers.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by plehegar** [comment]
w3c-test:mirror

**Comment by plehegar** [comment]
w3c-test:mirror

**Comment by plehegar** [comment]
w3c-test:mirror

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by Ms2ger** [comment]
Note: this tests for Gecko's behaviour; IE and Chrome follow the spec in all its craziness.

**Comment by Ms2ger** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28835

**Pull request merged**
