### PR TITLE
Added 5 manual tests on selection and text-shadow

### PR DESCRIPTION
**Pull request by TalbotG**

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
We need to keep manual tests to a minimum, and afaict these don't add anything that isn't well-tested elsewhere. These tests should not be added.

**Comment by TalbotG** [comment]
Chromium 78.0.3904.108 (stable release) and Chromium 81.0.3992.0 (latest build) do not perform well, do not perform consistently (when dragging the mouse) in those manual tests. 
Chromium 78 and Chromium 81 also perform incorrectly when double-clicking a word in those manual tests. These failures are not noticeable with the javascript tests.

1 time out of 3 (approximation), Chromium 81 fails
selection-text-shadow-014.html .

Firefox 68+ and Epiphany 3.32.1.2 (WebKitGTK+ 2.26.2) perform reliably and consistently (and succeed) in both the manual and the javascript text-shadow tests.

**Comment by fantasai** [comment]
OK, I see the bug. Let's keep just the last one, with all four variations, then. And make it clear in the directions that one should try partial selections, because I can't reproduce it with a full selection.

Did you try reproducing the bug with a partial selection via JS?

**Comment by TalbotG** [comment]
I am closing this pull request and then create another one
which will address your proposed modifications to the tests ... My current github "skills" prevent me from doing this in here... :(

**Pull request closed without merging**
