### PR TITLE
Create compat/OWNERS

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@miketaylr, this is to avoid the "status:needs-owners" label that you can see in this very PR. If you like I could add myself as well, but only if you like :)

**Comment by foolip** [comment]
@patrickkettner, do you know who might be a good owner for this for Edge? For WebKit, maybe @cdumez?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-23 15:30:57
Finished: 2017-08-23 15:35:30


<h2>Failing Jobs</h2>
<ul>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17709)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/267623635)

**Comment by cdumez** [comment]
Sure, I can be an OWNER on behalf of WebKit. Thanks for thinking of me.

**Comment by miketaylr** [comment]
> If you like I could add myself as well, but only if you like :)

SGTM, thanks! @foolip -- happy to have you on the list as well, no issue from me.

**Comment by foolip** [comment]
OK, I'll go ahead with the three of us on this thread. @patrickkettner, feel free to add yourself or anyone on the Edge team later.

**Pull request merged**
