### PR TITLE
Move css-transforms-2 tests into their own directory

### PR DESCRIPTION
**Pull request by smfr**
Moved all the css-transforms-1 tests which relate to css-transforms-2 into a new css-transforms-2 directory, along with their required refs. lint passes.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5603)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223375145)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223375147)

# Firefox (nightly channel) #
Testing web-platform-tests at revision b951b0c2c490d5e28cac4cf8f81c47e2268d70b4
Using browser at version BuildID 20170417100236; SourceStamp c697e756f738ce37abc56f31bfbc48f55625d617
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>100 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/backface-visibility-hidden-001.html">/css/css-transforms-2/backface-visibility-hidden-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-rotate-2d-3d-001.html">/css/css-transforms-2/css-rotate-2d-3d-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-X-negative.html">/css/css-transforms-2/css-transform-3d-rotate3d-X-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-X-positive.html">/css/css-transforms-2/css-transform-3d-rotate3d-X-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-Y-negative.html">/css/css-transforms-2/css-transform-3d-rotate3d-Y-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-Y-positive.html">/css/css-transforms-2/css-transform-3d-rotate3d-Y-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-Z-negative.html">/css/css-transforms-2/css-transform-3d-rotate3d-Z-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotate3d-Z-positive.html">/css/css-transforms-2/css-transform-3d-rotate3d-Z-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateX-negative.html">/css/css-transforms-2/css-transform-3d-rotateX-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateX-positive.html">/css/css-transforms-2/css-transform-3d-rotateX-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateY-negative.html">/css/css-transforms-2/css-transform-3d-rotateY-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateY-positive.html">/css/css-transforms-2/css-transform-3d-rotateY-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateZ-negative.html">/css/css-transforms-2/css-transform-3d-rotateZ-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-rotateZ-positive.html">/css/css-transforms-2/css-transform-3d-rotateZ-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transform-3d-transform-style.html">/css/css-transforms-2/css-transform-3d-transform-style.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css-transforms-3d-on-anonymous-block-001.html">/css/css-transforms-2/css-transforms-3d-on-anonymous-block-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css3-transform-perspective.html">/css/css-transforms-2/css3-transform-perspective.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/css3-transform-rotateY.html">/css/css-transforms-2/css3-transform-rotateY.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-001.html">/css/css-transforms-2/perspective-origin-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-002.html">/css/css-transforms-2/perspective-origin-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-003.html">/css/css-transforms-2/perspective-origin-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-004.html">/css/css-transforms-2/perspective-origin-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-005.html">/css/css-transforms-2/perspective-origin-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-006.html">/css/css-transforms-2/perspective-origin-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-x.html">/css/css-transforms-2/perspective-origin-x.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-origin-xy.html">/css/css-transforms-2/perspective-origin-xy.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-translateZ-0.html">/css/css-transforms-2/perspective-translateZ-0.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-translateZ-negative.html">/css/css-transforms-2/perspective-translateZ-negative.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/perspective-translateZ-positive.html">/css/css-transforms-2/perspective-translateZ-positive.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/rotateY.html">/css/css-transforms-2/rotateY.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/rotate_x_45deg.html">/css/css-transforms-2/rotate_x_45deg.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/rotate_y_45deg.html">/css/css-transforms-2/rotate_y_45deg.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform-3d-rotateY-stair-above-001.xht">/css/css-transforms-2/transform-3d-rotateY-stair-above-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform-3d-rotateY-stair-below-001.xht">/css/css-transforms-2/transform-3d-rotateY-stair-below-001.xht</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-001.html">/css/css-transforms-2/transform3d-backface-visibility-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-002.html">/css/css-transforms-2/transform3d-backface-visibility-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-003.html">/css/css-transforms-2/transform3d-backface-visibility-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-004.html">/css/css-transforms-2/transform3d-backface-visibility-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-005.html">/css/css-transforms-2/transform3d-backface-visibility-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-006.html">/css/css-transforms-2/transform3d-backface-visibility-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-007.html">/css/css-transforms-2/transform3d-backface-visibility-007.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-backface-visibility-008.html">/css/css-transforms-2/transform3d-backface-visibility-008.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-image-scale-001.html">/css/css-transforms-2/transform3d-image-scale-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-image-scale-002.html">/css/css-transforms-2/transform3d-image-scale-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-matrix3d-001.html">/css/css-transforms-2/transform3d-matrix3d-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-matrix3d-002.html">/css/css-transforms-2/transform3d-matrix3d-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-matrix3d-003.html">/css/css-transforms-2/transform3d-matrix3d-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-matrix3d-004.html">/css/css-transforms-2/transform3d-matrix3d-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-matrix3d-005.html">/css/css-transforms-2/transform3d-matrix3d-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-001.html">/css/css-transforms-2/transform3d-perspective-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-002.html">/css/css-transforms-2/transform3d-perspective-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-003.html">/css/css-transforms-2/transform3d-perspective-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-004.html">/css/css-transforms-2/transform3d-perspective-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-005.html">/css/css-transforms-2/transform3d-perspective-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-006.html">/css/css-transforms-2/transform3d-perspective-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-007.html">/css/css-transforms-2/transform3d-perspective-007.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-008.html">/css/css-transforms-2/transform3d-perspective-008.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-009.html">/css/css-transforms-2/transform3d-perspective-009.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-perspective-origin-001.html">/css/css-transforms-2/transform3d-perspective-origin-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-001.html">/css/css-transforms-2/transform3d-preserve3d-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-002.html">/css/css-transforms-2/transform3d-preserve3d-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-003.html">/css/css-transforms-2/transform3d-preserve3d-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-004.html">/css/css-transforms-2/transform3d-preserve3d-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-005.html">/css/css-transforms-2/transform3d-preserve3d-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-006.html">/css/css-transforms-2/transform3d-preserve3d-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-007.html">/css/css-transforms-2/transform3d-preserve3d-007.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-008.html">/css/css-transforms-2/transform3d-preserve3d-008.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-009.html">/css/css-transforms-2/transform3d-preserve3d-009.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-010.html">/css/css-transforms-2/transform3d-preserve3d-010.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-011.html">/css/css-transforms-2/transform3d-preserve3d-011.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-012.html">/css/css-transforms-2/transform3d-preserve3d-012.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-preserve3d-013.html">/css/css-transforms-2/transform3d-preserve3d-013.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotate3d-001.html">/css/css-transforms-2/transform3d-rotate3d-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotate3d-002.html">/css/css-transforms-2/transform3d-rotate3d-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotatex-001.html">/css/css-transforms-2/transform3d-rotatex-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotatex-perspective-002.html">/css/css-transforms-2/transform3d-rotatex-perspective-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotatex-perspective-003.html">/css/css-transforms-2/transform3d-rotatex-perspective-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotatex-transformorigin-001.html">/css/css-transforms-2/transform3d-rotatex-transformorigin-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-rotatey-001.html">/css/css-transforms-2/transform3d-rotatey-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-001.html">/css/css-transforms-2/transform3d-scale-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-002.html">/css/css-transforms-2/transform3d-scale-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-003.html">/css/css-transforms-2/transform3d-scale-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-004.html">/css/css-transforms-2/transform3d-scale-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-005.html">/css/css-transforms-2/transform3d-scale-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-006.html">/css/css-transforms-2/transform3d-scale-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-scale-007.html">/css/css-transforms-2/transform3d-scale-007.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-001.html">/css/css-transforms-2/transform3d-sorting-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-002.html">/css/css-transforms-2/transform3d-sorting-002.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-003.html">/css/css-transforms-2/transform3d-sorting-003.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-004.html">/css/css-transforms-2/transform3d-sorting-004.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-005.html">/css/css-transforms-2/transform3d-sorting-005.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-sorting-006.html">/css/css-transforms-2/transform3d-sorting-006.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-translate3d-001.html">/css/css-transforms-2/transform3d-translate3d-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transform3d-translatez-001.html">/css/css-transforms-2/transform3d-translatez-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transforms-rotateY-degree-60.html">/css/css-transforms-2/transforms-rotateY-degree-60.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transofrmed-preserve-3d-1.html">/css/css-transforms-2/transofrmed-preserve-3d-1.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transofrmed-rotateX-3.html">/css/css-transforms-2/transofrmed-rotateX-3.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/transofrmed-rotateY-1.html">/css/css-transforms-2/transofrmed-rotateY-1.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/ttwf-css-3d-polygon-cycle-mismatch.html">/css/css-transforms-2/ttwf-css-3d-polygon-cycle-mismatch.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5603/css/css-transforms-2/ttwf-css-3d-polygon-cycle.html">/css/css-transforms-2/ttwf-css-3d-polygon-cycle.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223375148)

# Chrome (unstable channel) #
Testing web-platform-tests at revision b951b0c2c490d5e28cac4cf8f81c47e2268d70b4
Using browser at version 59.0.3071.9 dev
Starting 10 test iterations

**Comment by gsnedders** [comment]
@smfr If we want them to show up in the right place in test harness, which AFAIK the CSS WG cares about, these all need the `<link rel='help'>` links updated, which *hopefully* is just a global find & replace operation…

**Comment by smfr** [comment]
Ah, right. Will fix. Why didn't the linter catch this?

**Comment by gsnedders** [comment]
@smfr because it didn't seem worthwhile writing such a thing to catch "wrong directories" when we're meant to be making it optional entirely, and because some tests will still have links to other specs for interaction tests, etc.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5603/)

**Pull request merged**
