### PR TITLE
Proposal: load Ahem as webfont everywhere

### PR DESCRIPTION
**Pull request by LukeZielinski**
Update all tests using Ahem font to load it as a webfont. The fonts/ahem.css stylesheet is added to mark Ahem as a webfont, pointing to fonts/Ahem.ttf. The vast majority of the updated tests just link to this stylesheet.

The following 11 tests are non-reftests that use Ahem, so they also
explicitly preload the WebFont:
- css/css-grid/grid-definition/grid-inline-support-flexible-lengths-001.html
- css/css-grid/grid-definition/grid-inline-support-grid-template-columns-rows-001.html
- css/css-grid/grid-definition/grid-inline-support-named-grid-lines-001.html
- css/css-grid/grid-definition/grid-inline-support-repeat-001.html
- css/css-grid/grid-definition/grid-inline-template-columns-rows-resolved-values-001.html
- css/css-grid/grid-definition/grid-support-flexible-lengths-001.html
- css/css-grid/grid-definition/grid-support-grid-template-columns-rows-001.html
- css/css-grid/grid-definition/grid-support-named-grid-lines-001.html
- css/css-grid/grid-definition/grid-support-repeat-001.html
- css/css-grid/grid-definition/grid-template-columns-rows-resolved-values-001.html
- css/css-shapes/spec-examples/shape-outside-018.html

One test also checks the list of resources that are loaded, so it was updated to expect
the ahem.css stylesheet to load as well:
- resource-timing/resource_initiator_types.html

### CODE REVIEW

**Comment by LukeZielinski** [comment]
@jgraham Hi James, what do you think of this change? Can you try it on Mozilla CI to see if it breaks anything?

**Comment by LukeZielinski** [comment]
@foolip Regarding the check failure, a [documented assumption](https://github.com/web-platform-tests/wpt/blob/master/docs/writing-tests/assumptions.md) is that Ahem is installed on the device. I guess we'd need to break this assumption, or relax it to say that Ahem is available as a webfont (and fix the test generator [here](https://github.com/web-platform-tests/wpt/blob/master/infrastructure/assumptions/tools/ahem-generate-table.py))?

**Comment by gsnedders** [comment]
see also #9105 for earlier discussion of this

**Comment by gsnedders** [comment]
> @foolip Regarding the check failure, a [documented assumption](https://github.com/web-platform-tests/wpt/blob/master/docs/writing-tests/assumptions.md) is that Ahem is installed on the device. I guess we'd need to break this assumption, or relax it to say that Ahem is available as a webfont (and fix the test generator [here](https://github.com/web-platform-tests/wpt/blob/master/infrastructure/assumptions/tools/ahem-generate-table.py))?

If we're changing behaviour to always load Ahem as a web font, we have no need for that "assumption" and should drop it and the related test (don't even bother changing it: there's no point; it would just become a tautology that the web font is equal to the web font).

That said, more generally as I think was clear in #9105 I'm generally in favour of this but have never been able to justify anyone spending their time on it (so, uh, thanks!), but I do think we need an RFC for this change (which shouldn't be too hard to get through!).

I'd be interested in whether this made any notable difference to overall test execution time, but I'd hope the web font would get cached quite easily.

**Comment by cbiesinger** [comment]
Don't you have to ensure to wait until the webfont is actually loaded?

**Comment by gsnedders** [comment]
> Don't you have to ensure to wait until the webfont is actually loaded?

One of the guarantees of WPT is that the reftest is taken after the `document.fonts.ready` promise resolves (though see also #11476).

**Comment by drott** [comment]
What's the intention of the change? To make the tests more robust due to issue with Ahem not being available from the system? 

I don't have objections to this change in particular, but I think it'd be beneficial to improve our system font testing story, as outlined in https://github.com/web-platform-tests/wpt/issues/13203#issuecomment-463979709 or it would generally help if control over system fonts available to WPT became more reliable, or just .. available.

**Comment by LukeZielinski** [comment]
Regarding the motivation for this change: it's to allow us to run WPT on systems where it's unlikely or difficult to have a system font installed (specifically Chromium CI).

**Comment by LukeZielinski** [comment]
I've created an RFC for this here: https://github.com/web-platform-tests/rfcs/pull/22

**Comment by gsnedders** [comment]
More generally, I think it's a big help for people running tests locally in their own browser, as that's a situation where it's much less likely they'll have Ahem installed versus (e.g.) fonts with decent coverage of characters.

**Comment by LukeZielinski** [comment]
Discarding this PR, will split as per [RFC discussion](https://github.com/web-platform-tests/rfcs/pull/22)

**Pull request closed without merging**
