### PR TITLE
Fix root README.md whitespace at EOL

### PR DESCRIPTION
**Pull request by qyearsley-zz**
Reason: wpt lint compains about whitespace at the end of the line here.

This PR also removes another extra space and makes capitalization of the section title consistent with other sections.

@ianbjacobs does this look OK?

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6748)

### CODE REVIEW

**Review by ianbjacobs — APPROVED** [review]

**Comment by ianbjacobs** [comment]
Thanks for the cleanup! 

Ian

**Comment by qyearsley** [comment]
Is something up with travis?
Could somebody with merge permissions in wpt merge this, since this is currently blocking the auto-import into Chromium (https://crbug.com/752199)?

@jeffcarp @foolip fyi

**Comment by ianbjacobs** [comment]
I went ahead to merge. I hope that helps. Sorry again for creating problems; I will refrain from more editing until I have a better understanding of the implications.

Ian

**Comment by qyearsley** [comment]
No problem, and thanks :-)

**Pull request merged**
