### PR TITLE
Remove @jkereliuk from OWNERS file

### PR DESCRIPTION
**Pull request by tobie**
@jkereliuk isn't a user.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9206)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-26 09:46:36
Finished: 2018-01-26 09:49:34


<h2>Failing Jobs</h2>
<ul>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23325)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/333646550)

**Comment by Ms2ger** [comment]
Supposed to be @kereliuk?

**Comment by tobie** [comment]
Perhaps?

**Review by andreastt — APPROVED** [review]

**Comment by andreastt** [comment]
@kereliuk looks correct.

**Comment by kereliuk** [comment]
Was OOO, thanks for catching this!

**Pull request merged**
