### PR TITLE
[html] Omit empty COOP/COEP reporting HTTP headers

### PR DESCRIPTION
**Pull request by jugglinmike**
Prior to this patch, when a test made a request to the `coop-coep.py`
and did not specify a desired value for the "report only" headers, the
response would include the headers without values.

Only include "report only" headers when they have been explicitly
specified. Should tests require empty values for these headers (as in
the original behavior), they may specify query string parameters without
values, e.g.

    coop-coep.py?coop-report-only=

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Are you also going to test the distinction? I guess empty string fails to parse which we treat identically to not setting it?

**Comment by jugglinmike** [comment]
No immediate plans for such a test, but I found the extraneous headers confusing.

Chrome failed the stability check, presumably due to existing flakiness. I'll push up an empty commit to trigger another trial.

**Comment by stephenmcgruer** [comment]
Based on wpt.fyi history, I believe the flake is pre-existing. @jugglinmike lmk if you want this admin-merged, happy to do so.

**Comment by jugglinmike** [comment]
I fixed the merge conflicts introduced by gh-24409, but it looks like that flaky test is still giving us static. I'd like to take you up on your offer, @stephenmcgruer :)

**Review by annevk — APPROVED** [review]

**Comment by jugglinmike** [comment]
Thanks!

**Pull request merged**
