### PR TITLE
Update Safari Technology Preview to 107

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 107, 15610.1.14.1)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1802&view=logs

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Pushed ca351892afad4b1be8477b12d76f66a69a70a4ce to `triggers/safari_preview`; https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=48889&view=results should be the run.

The parent SHA for comparison is eae38fb69ecc9efdfc60de1a10e888b55e4031bb, which should be wpt.fyi run id 550970002.

**Comment by foolip** [comment]
Comparison views:
- [`diff`](https://wpt.fyi/results/?diff&filter=ADC&run_id=550970002&run_id=570330001)
- [`is:different`](https://wpt.fyi/results/?q=is%3Adifferent&run_id=550970002&run_id=570330001)
- [`seq(status:pass status:!pass)`](https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%29&run_id=550970002&run_id=570330001) (regressions or flakes)

Differences that seem interesting:
- [/css/css-fonts/variations/at-font-face-font-matching](https://wpt.fyi/results/css/css-fonts/variations/at-font-face-font-matching.html?run_id=550970002&run_id=570330001)
- [/css/css-values/](https://wpt.fyi/results/css/css-values?q=is%3Adifferent&run_id=550970002&run_id=570330001)
- [/custom-elements/](https://wpt.fyi/results/custom-elements?q=is%3Adifferent&run_id=550970002&run_id=570330001)

@stephenmcgruer since it's not an overall regression I'll go ahead and merge, but how much checking of seeming regressions do you think we should do? Perhaps we should triage those failures, whether Safari-specific or not?

**Review by foolip — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer since it's not an overall regression I'll go ahead and merge, but how much checking of seeming regressions do you think we should do? Perhaps we should triage those failures, whether Safari-specific or not?

I'm not sure we have the bandwidth to add more manual checking to our workload. I would be happier building out a new view on say https://wpt.fyi/insights which can show version-regressions (views like you linked above), and let folks from Safari look at those if they want.

I'm also happy to proactively make someone (whoever that someone would be) from Safari aware of these updates and the (untriaged) changes we see (or a regular email to webkit-dev, the WebKit slack, etc), if that would be useful. cc @othermaciej to see if that would be useful.

**Comment by foolip** [comment]
Making the information more readily available sounds good. It's a shame that we look at it for each release to avoid large regressions, but unintended small regressions could probably be spotted by someone on the WebKit team.

**Comment by Hexcles** [comment]
> I would be happier building out a new view on say https://wpt.fyi/insights which could show version-regressions (views like you linked above), and let folks from Safari look at those if they want (cc @Hexcles ).

That sounds like a good idea and is quite easy to implement.

**Pull request merged**
