### PR TITLE
Extend document.open tests to cover implicitly opening via document.write

### PR DESCRIPTION
**Pull request by jeisinger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204137944)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 18506f86e92a9cdd8970bea5840fd2fcb92ff5ad
Using browser at version BuildID 20170221110300; SourceStamp d84beb192e57e26846c82d3df3599381f4663792
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4954/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html</a></summary>


|                              Subtest                              | Results | Messages |
|-------------------------------------------------------------------|---------|----------|
|                                                                   | OK      |          |
| `It should be possible to open same origin documents.`            | PASS    |          |
| `It should be possible to implicitly open same origin documents.` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4954/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain.sub.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain.sub.html</a></summary>


|                                              Subtest                                               | Results | Messages |
|----------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                    | OK      |          |
| `It should not be possible to open same origin-domain (but not same origin) documents.`            | PASS    |          |
| `It should not be possible to implicitly open same origin-domain (but not same origin) documents.` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204137945)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 18506f86e92a9cdd8970bea5840fd2fcb92ff5ad
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4954/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html</a></summary>


|                              Subtest                              | Results | Messages |
|-------------------------------------------------------------------|---------|----------|
|                                                                   | OK      |          |
| `It should be possible to open same origin documents.`            | PASS    |          |
| `It should be possible to implicitly open same origin documents.` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4954/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain.sub.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain.sub.html</a></summary>


|                                              Subtest                                               | Results |                                                                            Messages                                                                           |
|----------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                    | OK      |                                                                                                                                                               |
| `It should not be possible to open same origin-domain (but not same origin) documents.`            | FAIL    | `assert_throws: Opening a same origin-domain (but not same origin) document doesn't throw. function "function () { [native code] }" did not throw`            |
| `It should not be possible to implicitly open same origin-domain (but not same origin) documents.` | FAIL    | `assert_throws: Implicitly opening a same origin-domain (but not same origin) document doesn't throw. function "function () { [native code] }" did not throw` |

</details>
</details>

**Comment by mikewest** [comment]
Would you mind making these changes as part of https://codereview.chromium.org/2707113005 so we can verify that it makes Chrome pass? :)

**Comment by jeisinger** [comment]
ok, will do

**Pull request closed without merging**
