### PR TITLE
HTML: -webkit-appearance: fieldset/legend: auto on replaced elements

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/html/pull/3934

### CODE REVIEW

**Review by mstensho — COMMENTED** [review]
General note: I think it's wrong to use -webkit- prefixed properties.

**Comment by annevk** [comment]
@mstensho is there a good place to discuss that? I think we should go with -webkit-appearance for now since that's what implementations use. As I mentioned elsewhere I don't think we can remove it. We might at some point support an unprefixed alias as well, but if it's an alias it shouldn't matter that the prefixed version is tested here.

**Comment by mstensho** [comment]
No, we can't remove it. But I'd like to have a proper (unprefixed, of course) spec for this first. I'd prefer to live with the fieldset / legend magic until we have that spec. We're doing things in the wrong order here.

**Comment by annevk** [comment]
How does it matter if the end state is the same?

**Comment by mstensho** [comment]
Because in the meantime the web will have been polluted with even more -webkit- stuff, and that can be avoided.

**Comment by zcorpan** [comment]
You can keep it behind a flag in the meantime, though?

I concur with Anne, FWIW.

**Comment by zcorpan** [comment]
@mstensho @MatsPalmgren do you think it helps to unprefix 'appearance' now (with -webkit-appearance as a simple alias, ignoring css-ui for now)?

**Comment by zcorpan** [comment]
See https://github.com/whatwg/html/pull/4035#issuecomment-1476330098

**Pull request closed without merging**
