### PR TITLE
Assert that an unnecessary exitFullscreen()'s promise is resolved

### PR DESCRIPTION
**Pull request by foolip**
This is a test for https://github.com/whatwg/fullscreen/pull/81

### CODE REVIEW

**Comment by foolip** [comment]
Nobody implements promises yet, so this test deliberately doesn't fail if so. I've verified that the test still passes in Firefox with the changes, but beyond that the test may need tweaking once promises are supported. This is the only way that the change in https://github.com/whatwg/fullscreen/pull/81 would be observable.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230744876)

# Firefox (nightly) #
Testing web-platform-tests at revision 0da3aff7bf1d157314957d9c24a4d8bdace1def3
Using browser at version BuildID 20170509100208; SourceStamp b21b974d60d3075ae24f6fb1bae75d0f122f28fc
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/230744882)

# Chrome (unstable) #
Testing web-platform-tests at revision 0da3aff7bf1d157314957d9c24a4d8bdace1def3

**Comment by upsuper** [comment]
I think this is fine.

**Comment by foolip** [comment]
Thanks @upsuper!

**Pull request merged**
