### PR TITLE
Add wptrunner to web-platform-tests

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5638)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5638/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224416487)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224416489)

# Firefox (nightly channel) #
Testing web-platform-tests at revision cb1111e5cdeb4272358fd4472cdc85e6270ee3c7
Using browser at version BuildID 20170420100256; SourceStamp 27311156637f9b5d4504373967e01c4241902ae7
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224416496)

# Chrome (unstable channel) #
Testing web-platform-tests at revision cb1111e5cdeb4272358fd4472cdc85e6270ee3c7
Using browser at version 59.0.3071.15 dev
Starting 10 test iterations
No tests run.

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
