### PR TITLE
Change PaymentRequest.abort() to manual test

### PR DESCRIPTION
**Pull request by marcoscaceres**
Show now triggered by user activation: https://github.com/w3c/payment-request/pull/655

### CODE REVIEW

**Review by mnoorenberghe — COMMENTED** [review]
Hmm… any idea why git's move detection work here?

**Comment by marcoscaceres** [comment]
Not sure, tbh... I definitely did a `git mv` to move it... but then did a `git commit -am` which maybe confused it.

**Comment by marcoscaceres** [comment]
(not super worried about the move history, tbh)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-13 05:05:33
Finished: 2018-03-13 05:10:43


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25836)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/352677128)

**Review by rsolomakhin — APPROVED** [review]

**Pull request merged**
