### PR TITLE
Update Safari Technology Preview to 104

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 104, 15610.1.8.3)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1652&view=logs

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Reminder of our process for new STP releases (since we're still getting that codified):

1. Fire a trigger run for the new release.
1. Compare results with the immediately preceding commit.
1. Land if good (where good equals no obvious new errors, not necessarily an improvement in passes).

**Comment by stephenmcgruer** [comment]
This commit has been pushed to `triggers/safari_preview`. The nearest commit with an STP 103 run before this is `bca2d6eb63630a1fc4b8aa271868afab5f180be7`; two `dom/events/scrolling tests` and one `css/filter-effects` tests have been added since then.

**Comment by foolip** [comment]
If intervening commits become a problem for comparison, what we could do is to always base these branches off of the epochs/three_hourly branches. That wouldn't increase the risk of conflicts, these PRs change only one file after all.

**Comment by stephenmcgruer** [comment]
Diff: https://wpt.fyi/results/?diff&filter=ADC&run_id=467230002&run_id=470870003

**Comment by foolip** [comment]
Diff looks like an overall improvement, I'll merge this now.

**Review by foolip — APPROVED** [review]

**Pull request merged**
