### PR TITLE
[fetch] Refactor helper function

### PR DESCRIPTION
**Pull request by jugglinmike**
Remove reference to global variable from `assert_no_headers` and instead
require the value as a parameter.

### CODE REVIEW

**Comment by jdm** [comment]
I don't understand what's happening here - the new `expected` argument is never referenced, is it?

**Comment by jugglinmike** [comment]
Yeah, it's a bit unclear. `expected` is indeed referenced in the `assert_no_headers` function, just a little beyond what's available in the diff's context. The reason this already works is that `expected` is *also* a globally-defined binding in the one test that used `assert_no_headers`. This change just makes the relationship between the function and its input more explicit and facilitates future reuse.

**Comment by jdm** [comment]
Ah, whoops, I overlooked the one line where it's used when expanding the diff.

**Comment by domfarolino** [comment]
What does the mozilla:gecko-blocked label mean exactly?

**Comment by jdm** [comment]
@jgraham ^

**Comment by zcorpan** [comment]
I've rebased this to the current `master`.

**Comment by jgraham** [comment]
> What does the mozilla:gecko-blocked label mean exactly?

It means that the bot that imports changes into gecko couldn't apply this to mozilla-central for some reason. You can ignore it; it turned out to be less helpful than anticipated.

**Comment by mikewest** [comment]
Chromium's CQ is happ_ier_, but still points out a few issues: https://test-results.appspot.com/data/layout_results/linux_layout_tests_composite_after_paint/35270/blink_web_tests%20%28with%20patch%29/layout-test-results/results.html.

**Comment by zcorpan** [comment]
@mikewest I assume you meant to comment in #25247. 🙂

**Comment by mikewest** [comment]
> @mikewest I assume you meant to comment in #25247. 🙂

Ahem. Yes. :)

**Comment by zcorpan** [comment]
Rebased again.

For reference, these are the files using `helper.js`:

```
$ git grep --files-with-matches "/fetch/metadata/resources/helper.js"
fetch/metadata/download.https.sub.html
fetch/metadata/embed.https.sub.tentative.html
fetch/metadata/favicon.https.sub.html
fetch/metadata/fetch-preflight.https.sub.any.js
fetch/metadata/fetch-via-serviceworker--fallback.https.sub.html
fetch/metadata/fetch-via-serviceworker--respondWith.https.sub.html
fetch/metadata/fetch.https.sub.any.js
fetch/metadata/fetch.sub.html
fetch/metadata/font.https.sub.html
fetch/metadata/form.https.sub.html
fetch/metadata/history.https.sub.html
fetch/metadata/iframe.https.sub.html
fetch/metadata/iframe.sub.html
fetch/metadata/img.https.sub.html
fetch/metadata/navigation.https.sub.html
fetch/metadata/object.https.sub.html
fetch/metadata/portal.https.sub.html
fetch/metadata/prefetch.https.sub.html
fetch/metadata/preload.https.sub.html
fetch/metadata/redirect/cross-site-redirect.https.sub.html
fetch/metadata/redirect/multiple-redirect-cross-site.https.sub.html
fetch/metadata/redirect/multiple-redirect-https-downgrade-upgrade-prefetch.optional.sub.html
fetch/metadata/redirect/multiple-redirect-https-downgrade-upgrade.sub.html
fetch/metadata/redirect/multiple-redirect-same-site.https.sub.html
fetch/metadata/redirect/redirect-http-upgrade-prefetch.optional.sub.html
fetch/metadata/redirect/redirect-http-upgrade.sub.html
fetch/metadata/redirect/redirect-https-downgrade-prefetch.optional.sub.html
fetch/metadata/redirect/redirect-https-downgrade.sub.html
fetch/metadata/redirect/same-origin-redirect.https.sub.html
fetch/metadata/redirect/same-site-redirect.https.sub.html
fetch/metadata/report.https.sub.html
fetch/metadata/script.https.sub.html
fetch/metadata/script.sub.html
fetch/metadata/serviceworker-accessors.https.sub.html
fetch/metadata/serviceworker.https.sub.html
fetch/metadata/sharedworker.https.sub.html
fetch/metadata/style.https.sub.html
fetch/metadata/track.https.sub.html
fetch/metadata/trailing-dot.https.sub.any.js
fetch/metadata/unload.https.sub.html
fetch/metadata/window-open.https.sub.html
fetch/metadata/worker.https.sub.html
fetch/metadata/xslt.https.sub.html
```

**Comment by annevk** [comment]
I could not update the remote branch here so I moved this to #36456.

**Pull request closed without merging**
