### PR TITLE
cc Do some follow-up for PR #2838

### PR DESCRIPTION
**Pull request by sideshowbarker**
The changes here are all follow-ups to PR #2838.

@dd8 please review if possible and comment—in particular about the files that had been previously merged as `novalid` but that this PR changes to `valid`.

### CODE REVIEW

**Comment by dd8** [comment]
I'll go through each of the renamed files in turn, but that might take a few days, although all looks good so far:

animate-dom-01-f-isvalid.html
animate-dom-02-f-isvalid.html
DTD validation errors are due to script/@src being optional in SVG-in-HTML spec but not in SVG spec (I think I filed a related issue with the Relax schemas a while back)

animate-elem-40-t-isvalid.html
The DTD validation error is on <font-face font-family="MyDecFont"/> not being complete and looks like an known error in the SVG DTD: https://www.w3.org/2011/08/REC-SVG11-20110816-errata 

It looks like uploaded .SVG files auto-detect as 'Doctype:	SVG 1.1 + XHTML + MathML 3.0' - is this a RelaxNG schema or an SGML DTD?

**Comment by sideshowbarker** [comment]
> animate-dom-01-f-isvalid.html
> animate-dom-02-f-isvalid.html
> DTD validation errors are due to script/@src being optional in SVG-in-HTML spec but not in SVG spec (I think I filed a related issue with the Relax schemas a while back)

OK yeah I vaguely recall something about that but anyway given that these are HTML files we should be testing against the conformance requirements in the HTML spec for SVG-in-HTML.

> animate-elem-40-t-isvalid.html
> The DTD validation error is on not being complete and looks like an known error in the SVG DTD: https://www.w3.org/2011/08/REC-SVG11-20110816-errata

OK so yeah we should ignore the DTD problem and just follow the spec

> It looks like uploaded .SVG files auto-detect as 'Doctype: SVG 1.1 + XHTML + MathML 3.0' - is this a RelaxNG schema or an SGML DTD?

RelaxNG

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by dd8** [comment]
I've checked through all files named from from -invalid to -isvalid. Everything looks good.

Most of the changes were due to SCRIPT TYPE being mandatory in the DTD but optional in HTML5
https://github.com/validator/validator/issues/217

Two files were marked as invalid by the DTD validator due to a bug in the DTD in the SVG 1.1 Recommendation - just reported:
https://lists.w3.org/Archives/Public/www-svg/2016Sep/0043.html

And another 2 were originally marked as invalid due to spaces in data: URLs - the various URI specs have different opinions on whether this is valid or not. That was the motivation for filing this issue:
https://github.com/validator/validator/issues/216

So just to confirm - the changes to my pull request look correct

**Comment by sideshowbarker** [comment]
@dd8 Thanks much!

**Pull request merged**
