### PR TITLE
Remove legacy command line tools to prevent confusion

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6751)

### CODE REVIEW

**Comment by gsnedders** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[docs/_writing-tests/lint-tool.md, line 7 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6751#-KqhBVYNAOLYqKyLmT4F:-KqhBVYNAOLYqKyLmT4G:bdbl1j5) ([raw file](https://github.com/w3c/web-platform-tests/blob/880843b6ac76f5f04b762c6f115bf381ca6dd1b4/docs/_writing-tests/lint-tool.md#L7)):*
> ```Markdown
> ---
> We have a lint tool for catching common mistakes in test files. You can run
> it manually by starting the `lint` executable from the root of your local
> ```

Do we not want to change this line too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6751)*

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260985781)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260985782)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260985789)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260985790)

# Sauce (MicrosoftEdge) #

**Comment by gsnedders** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[docs/_writing-tests/lint-tool.md, line 7 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6751#-KqhBVYNAOLYqKyLmT4F:-KqhKjhT9msoYixLgbJb:bb6ywmx) ([raw file](https://github.com/w3c/web-platform-tests/blob/880843b6ac76f5f04b762c6f115bf381ca6dd1b4/docs/_writing-tests/lint-tool.md#L7)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Do we not want to change this line too?
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6751)*

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
