### PR TITLE
Code of conduct suggestion

### PR DESCRIPTION
**Pull request by boazsender**
Suggesting in the Contributors Covenant. Further discussion at https://github.com/web-platform-tests/rfcs/issues/21 and https://github.com/web-platform-tests/rfcs/issues/17.

If merged, this PR would replace https://github.com/web-platform-tests/wpt/pull/7520.

### CODE REVIEW

**Comment by boazsender** [comment]
Please excuse the noise, I opened this PR with a dirty git tree.

**Comment by rniwa** [comment]
Not sure why this was assigned to me. Since I don't know the relevant context, I'm the right assignee for this PR.

**Comment by boazsender** [comment]
Sorry about that @rniwa, I think that was the pr-bot assigning it to you. I'm going to leave it unassigned for now.

**Comment by boazsender** [comment]
After a further look at the RFC for the Code of Conduct, I'm going to close this PR which uses the contributor covenant as a template in favor of @plehegar's https://github.com/web-platform-tests/wpt/pull/7520 and https://github.com/web-platform-tests/wpt/pull/18950 (based on the Rust CoC).

Extra sorry for the noise with this patch, folks.

**Comment by foolip** [comment]
@rniwa the reason you were assigned was because the PR accidentally touched lots of directories, some of which you're a suggested reviewer for. The review bot then picks one of the reviewers randomly as the assignee, to give one single person more of a signal to review than the rest and avoid everyone looking away. (The approach doesn't seem to be very effective though, TBH.)

**Pull request closed without merging**
