### PR TITLE
Dispatch pointerDown and pointerUp actions for mouse; r=ato+446296

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: FC0lF0S2Mzz

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1337133

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5085/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208980497)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208980499)

**Pull request merged**
