### PR TITLE
Run DOM IDL tests in workers and convert to `idl_test`

### PR DESCRIPTION
**Pull request by foolip**
Because of the use of variants it's unfortunately not possible to
merge this into a single test, but the duplication is not very
significant. Note that the use of `document.createEvent("Event")`
would make a merged test have non-trivial conditional setup too.

More details on the setup can be found in the [documentation for idl_test helper method](https://github.com/web-platform-tests/wpt/blob/53cca8d2a406fb06028b4e6eac25d648da02f801/resources/idlharness.js#L3271)

### CODE REVIEW

**Comment by foolip** [comment]
@lukebjerring FYI, or if you want to review.

**Review by annevk — APPROVED** [review]
This seems fine to me. Maybe a comment explaining the setup would help, but if you put it in the commit message that's probably okay as well.

**Comment by annevk** [comment]
Yes, as it's not immediately clear why the redundancy is needed.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/18708.

**Pull request merged**
