### PR TITLE
[css-variables-1] Test border-* shorthand serialization with variable reference in border

### PR DESCRIPTION
**Pull request by gsnedders**
Originally posted as https://github.com/w3c/csswg-test/pull/1197 by @kbabbitt on 01 Feb 2017, 22:44 UTC:

> Test for correct serialization of border-* shorthands when the border shorthand is set and has a variable reference.
> 
> 
> ---
> This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1197)
>

### CODE REVIEW

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/pull/1197#issuecomment-276807745 by @syncbot on 01 Feb 2017, 22:45 UTC:

> ### Automatic validation checks of commit d173f54 passed.

**Comment by SimonSapin** [comment]
Looks good to me. (Waiting for the Travis-CI build to finish.)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217159244)

# Firefox (nightly channel) #
Testing web-platform-tests at revision edfeb18203526671ef3933bd21ea395456666303
Using browser at version BuildID 20170331102157; SourceStamp 8df9fabf2587b7020889755acb9e75b664fe13cf
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5286/css/css-variables-1/vars-border-shorthand-serialize.html">/css/css-variables-1/vars-border-shorthand-serialize.html</a></summary>


|                                        Subtest                                        | Results | Messages |
|---------------------------------------------------------------------------------------|---------|----------|
|                                                                                       | OK      |          |
| `border-color should serialize to the empty string when border references a variable` | PASS    |          |
| `border-style should serialize to the empty string when border references a variable` | PASS    |          |
| `border-width should serialize to the empty string when border references a variable` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217159245)

# Chrome (unstable channel) #
Testing web-platform-tests at revision edfeb18203526671ef3933bd21ea395456666303
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5286/css/css-variables-1/vars-border-shorthand-serialize.html">/css/css-variables-1/vars-border-shorthand-serialize.html</a></summary>


|                                        Subtest                                        | Results |                       Messages                       |
|---------------------------------------------------------------------------------------|---------|------------------------------------------------------|
|                                                                                       | OK      |                                                      |
| `border-color should serialize to the empty string when border references a variable` | FAIL    | `assert_equals: expected "" but got "var(--border)"` |
| `border-style should serialize to the empty string when border references a variable` | FAIL    | `assert_equals: expected "" but got "var(--border)"` |
| `border-width should serialize to the empty string when border references a variable` | FAIL    | `assert_equals: expected "" but got "var(--border)"` |

</details>
</details>

**Pull request merged**
