### PR TITLE
Upgrade to Safari Technology Preview 92 on macOS Mojave

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
https://twitter.com/webkit/status/1174376925160230914 (saw that, did this)

**Comment by foolip** [comment]
Hrm, judging by version (14609.1.4) this still probably doesn't include https://bugs.webkit.org/show_bug.cgi?id=174030. Will do a full run and see what the results are.

**Comment by graouts** [comment]
The release notes indicate that the fix for this bug is included in STP 92, in fact it's specifically called out.

**Comment by foolip** [comment]
That's great! Is there a way I one can work out which webkit revision 14609.1.4 was branched from? I assumed it'd be the same as 14609.1.3 (STP 91) since only the minor... oh wait that last number is also bumped in the WebKit trunk. (In Chromium the last digit increases on branches.)

**Comment by foolip** [comment]
Alright now to see if what abuse I need to do to the VM to make safaridriver work :) @burg the `sudo safaridriver --enable` bug will be fixed in STP 93, right?

**Comment by foolip** [comment]
@burg this is now blocked on `sudo safaridriver --enable` not working. My wonderful plist workaround that worked in STP 91 also no longer works, so I don't think there's anything more I can do.

If that's the case, we'll have to wait for STP 93 to get this updated. Too bad, I wanted to have a fresh run on the frontpage by morning for TPAC.

**Comment by foolip** [comment]
The plist hack worked with STP 91 here:
https://github.com/web-platform-tests/wpt/pull/18925/commits/f31328c4c2fd102f8a39208e90e2f1f88f441284
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30493&view=logs&jobId=c092c851-ddde-53a1-8da2-b0c5715821df

The job didn't succeed, but the tests did run.

**Comment by graouts** [comment]
> That's great! Is there a way I one can work out which webkit revision 14609.1.4 was branched from?

Yes! I usually just look at the [webkit.org blog post](https://webkit.org/blog/9568/release-notes-for-safari-technology-preview-92/) which lists the revision range, which in this case is [r249190-249750](https://trac.webkit.org/log?stop_rev=249190&&rev=249750&limit=999).

Another way is to look at the svn tag for it under `releases/Apple/Safari Technology Preview`, for instance for this release: https://trac.webkit.org/browser/webkit/releases/Apple/Safari%20Technology%20Preview/Safari%20Technology%20Preview%2092.

**Comment by graouts** [comment]
> @burg this is now blocked on `sudo safaridriver --enable` not working. My wonderful plist workaround that worked in STP 91 also no longer works, so I don't think there's anything more I can do.

Is there a WebKit.org bug for this?

**Comment by foolip** [comment]
Per https://github.com/web-platform-tests/wpt/issues/17186#issuecomment-530548827 it's rdar://problem/55272284.

If it's possible, running the WPT infrastructure/ and webdriver/ tests using safaridriver _before_ STP is released would greatly reduce the likelihood of this sort of problem. I could help suggest how to distill that into a few steps for CI, but I guess you'd need a private CI system if you don't want the builds in a public CI system.

**Comment by foolip** [comment]
@clopez @psaavedra see https://github.com/web-platform-tests/wpt/pull/19142#issuecomment-533079685 for how to find the WebKit revision for STP. This will come in handy when trying to compare results to WebKitGTK I think.

**Comment by clopez** [comment]
Yes, thats handy. The way to check this for WebKitGTK stable releases is looking at this wiki:
* WebKitGTK 2.26.x was branched at r249195 https://trac.webkit.org/wiki/WebKitGTK/2.26.x
* WebKitGTK 2.24.x was branched at r241292 https://trac.webkit.org/wiki/WebKitGTK/2.24.x

For the unstable releases there is no wiki, but you can also look at the SVN branches at https://trac.webkit.org/browser/webkit/releases/WebKitGTK 
Note that when looking at the SVN it is a bit tricky to get the SVN revision number where it has been branched, as the number it appears there is the revision number of the last commit on that branch (which usually is different from the revision number where the branch was created/forked)

**Comment by foolip** [comment]
Do you know if WebKitGTK stable releases are usually branches from the same point as Safari? How about for Technology Preview? If they aren't currently in sync, maybe that could be achieved with some coordination?

**Comment by clopez** [comment]
They are not synced, and I don't think that can be achieved as the timelines for the products are different.

I don't know which criteria uses Apple for Safari stable releases but I can imagine it can be somehow related with the releases of MacOS. Regarding Safari Tech Preview it seems they release one new each few weeks.

For WebKitGTK, the releases are done on a time-based schedule that follow the GNOME release schedule. As WebKitGTK is a central component of GNOME, it makes sense that the releases are done in sync with GNOME. This means a new major stable release is done each 6 months (usually in March and September). Check: https://trac.webkit.org/wiki/WebKitGTK/StableRelease

Regarding WebKitGTK unstable releases those are done on a best effort basis without a specific schedule (AFAIK): usually a new one is done each month, but it can vary.

**Comment by foolip** [comment]
STP 93 is here: https://github.com/web-platform-tests/wpt/pull/19482

**Pull request closed without merging**
