### PR TITLE
Multicol width tests

### PR DESCRIPTION
**Pull request by rachelandrew**
A set of cleaned up tests for multicol:

1. Added asset where it was missing.
2. Added a description to the page on tests to explain what a pass was.
3. Removed CSS that wasn't required (orphans and widows properties)
4. Tidied up multicol-width-003 as discussed in https://github.com/web-platform-tests/wpt/issues/7470
5. Changed multicol-width-count-002 so that it fails if column-count is ignored and column-width used otherwise it appears to test the same thing as multicol-width-count-001

### CODE REVIEW

**Review by mstensho — APPROVED** [review]

**Comment by gsnedders** [comment]
Is there any reason this hasn't landed?

**Comment by mstensho** [comment]
There's a mistake in this change; got automatically reported in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=880084

I'll fix it shortly (via the Chromium repo). But my question is: Aren't automatic tests run before landing pull requests?

**Comment by gsnedders** [comment]
@mstensho we don't currently do any differential comparison between how browsers pass/fail before/after a change (that's #7475), mostly because we don't store the results in the Travis environment anywhere to do a comparison against the merge base, and we don't even do the stability checking properly for reference changes (#5319).

**Comment by mstensho** [comment]
@gsnedders That's a pity. Such mistakes are so easy to make, and could be so easy to detect as well.

Landing a fix now: https://chromium-review.googlesource.com/c/chromium/src/+/1203250

**Pull request merged**
