### PR TITLE
Add "Do not edit" warning to all HTML pages.

### PR DESCRIPTION
**Pull request by fred-wang**
This aligns with the woff2-tests generator:
w3c/woff2-tests#12
w3c/woff2-tests#14

WARNING: This branch includes the following PRs, please review them first:
https://github.com/web-platform-tests/wpt/pull/11313
https://github.com/web-platform-tests/wpt/pull/11326 

Only the last commit is important here.

### CODE REVIEW

**Review by svgeesus — APPROVED** [review]
LGTM

**Comment by svgeesus** [comment]
Huh. I restarted the Travis CI which had failed, but now it says there are conflicts.

**Comment by fred-wang** [comment]
@svgeesus Thanks I'll rebase this branch. Anyway, I think like what happened in #11311 the Firefox bot will probably time out because too many tests are modified. Hence we'll need to ask an admin to merge...

**Comment by fred-wang** [comment]
cc @jgraham

**Pull request merged**
