### PR TITLE
Update interfaces/wake-lock.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/5c13fe9/ed/idl/wake-lock.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/599621610

### CODE REVIEW

**Comment by rakuco** [comment]
lgtm from a spec and tests perspective. The existing tests in `wake-lock/` have already been updated in #19600  and #19756

**Comment by foolip** [comment]
@rakuco I think the `idl_array.add_objects` bit of the enclosing test for this will also need updating.

**Comment by rakuco** [comment]
No worries, I can take care of that.

**Comment by foolip** [comment]
Alright, I'll go ahead an merge that, it'll be easier to fix afterwards.

**Review by foolip — APPROVED** [review]

**Comment by rakuco** [comment]
> @rakuco I think the `idl_array.add_objects` bit of the enclosing test for this will also need updating.

Done in #19826!

**Pull request merged**
