### PR TITLE
Add tests for GeolocationSensor.read()

### PR DESCRIPTION
**Pull request by Honry**
covers:
  - verify sensor reading when call read() method
  - verify sensor reading when signal is set to null
  - throw AbortError when singal's abort flag is set
  - throw SecurityError when disabled by Feature Policy
  - AbortError takes priority when disabled by Feature Policy

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24853)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/346140681)

**Comment by Honry** [comment]
@anssiko, @pozdnyakov, @alexshalamov, PTAL. And please let me know if there's coverage gap. Thanks!

**Comment by anssiko** [comment]
PTAL @kenchris

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
@Honry I think this can be landed.

**Pull request merged**
