### PR TITLE
Add a test for :autofill.

### PR DESCRIPTION
**Pull request by emilio**
There's no way to trigger autofilling from WPT so this is as much as we
can test.

### CODE REVIEW

**Review by lilles — APPROVED** [review]

**Comment by annevk** [comment]
I think we can also test how `-webkit-autofill` shows up in `selectorText`.

**Comment by emilio** [comment]
> I think we can also test how `-webkit-autofill` shows up in `selectorText`.

Sure, though I made `:-webkit-autofill` not normative intentionally...

**Comment by emilio** [comment]
I added a test for `:-webkit-autofill` following the discussion in the HTML PR. I didn't test the specific serialization because we have no precedent (which I know of) in the selectors spec about how aliases are serialized. E.g.:

> As previous drafts of this specification used the name :matches() for this pseudo-class, UAs may additionally implement this obsolete name as an alias for :is() if needed for backwards-compatibility.

(without details on how that works).

I also expect it to matter little to nothing wrt compat. We implement most other -webkit-/moz things as parse-time changes into the standard thing, though at least in WebKit there's precedent for preserving the serialization of some legacy things (like `::-webkit-input-placeholder`).

**Comment by domenic** [comment]
I do think we should figure out the serialization of such aliases, and get it specced somewhere and tested, but I can understand if that's a low priority for the CSSWG and various browsers. (And it doesn't block adding these to HTML, IMO.)

We may also want to file a bug (on this repo) about making autofill more testable, just so the WPT team has a good insight into what untestable things are out there.

**Comment by emilio** [comment]
> I do think we should figure out the serialization of such aliases, and get it specced somewhere and tested, but I can understand if that's a low priority for the CSSWG and various browsers. (And it doesn't block adding these to HTML, IMO.)

Filed https://github.com/w3c/csswg-drafts/issues/5847.

> We may also want to file a bug (on this repo) about making autofill more testable, just so the WPT team has a good insight into what untestable things are out there.

https://github.com/web-platform-tests/wpt/issues/27118

**Comment by Loirooriol** [comment]
What about testing the serialization but allowing both possibilities (for now)?

```js
test_valid_selector(":autofill");
test_valid_selector(":-webkit-autofill", [":-webkit-autofill", ":autofill"]);
```

**Comment by emilio** [comment]
> What about testing the serialization but allowing both possibilities (for now)?
> 
> ```js
> test_valid_selector(":autofill");
> test_valid_selector(":-webkit-autofill", [":-webkit-autofill", ":autofill"]);
> ```

Sure, sounds great, done :)

**Comment by emilio** [comment]
I added the CSSWG issue to the agenda, and will edit the test as needed once there's a resolution on that.

**Pull request merged**
