### PR TITLE
Move idle callback tests to its own top-level directory

### PR DESCRIPTION
**Pull request by foolip**
The directory is named after https://w3c.github.io/requestidlecallback/
and the OWNERS file is based on who has touched the tests so far.

### CODE REVIEW

**Comment by foolip** [comment]
@farre, @rmcilroy, PTAL? I've tried to give you both write access to the repo so you can actually merge changes if asked to review.

**Comment by foolip** [comment]
I'm doing this because wpt is supposed to be organized by spec, but mostly because I failed to find the tests for https://foolip.github.io/day-to-day/ and if it's named like the spec it'll be associated automatically.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Firefox Nightly"<small></small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/19102.3">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/282973739">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  <tr>
    <td><code>/requestidlecallback/callback-timeout-with-raf.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>requestIdleCallback not scheduled when event loop is busy.</code></td>
    <td>FAIL: 1<br />PASS: 9<br /></td>
    <td><code>assert_equals: Busy rAF loop should be finished by the time we get scheduled expected 0 but got 9</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>requestIdleCallback scheduled with timeout when event loop is busy.</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  </table>

**Comment by foolip** [comment]
@tobie, is it a bug that @wpt-pr-bot is adding back the status:needs-owners label? I am adding OWNERS in this PR and have assigned a reviewer...

**Comment by foolip** [comment]
@farre, looks like one of the tests is flaky in Firefox. Can you file a bug about that? Since the tests haven't changed, I think we should not block moving on that.

**Review by Ms2ger — APPROVED** [review]
This is good to go once @farre and @rmcilroy confirm they want to get the notifications.

**Comment by tobie** [comment]
@wpt-pr-bot only considers content in the repo (originally for security reasons). Arguably this could be relaxed when creating new repositories. I haven't thought about the implications.

**Review by farre — APPROVED** [review]

**Comment by Ms2ger** [comment]
Oh, and
```
requestidlecallback/basic.html:44: setTimeout used; step_timeout should typically be used instead (SET TIMEOUT)
requestidlecallback/callback-suspended.html:44: setTimeout used; step_timeout should typically be used instead (SET TIMEOUT)
```

**Comment by foolip** [comment]
OK, things look good now. I'll merge and send an email to @rmcilroy offering to remove him again if this was misguided. Merging.

**Comment by foolip** [comment]
@tobie, thanks, I'll just ignore those messages and labels in cases like this.

**Comment by tobie** [comment]
> I'll just ignore those messages and labels in cases like this.

Yeah, that's your best bet. :-(

**Pull request merged**
