### PR TITLE
Add 2dcontext/OWNERS and offscreen-canvas/OWNERS

### PR DESCRIPTION
**Pull request by zcorpan**
cc @fserb @kenrussell @mstange @nical

(You are in here because you are in the whatwg/canvas team.)

### CODE REVIEW

**Comment by annevk** [comment]
I guess I'm okay with this for now.

**Comment by jdashg** [comment]
I don't think it's necessary, but it might be easier that way, since canvas (but not 2d-canvas!) and offscreen canvas have webgl integration.

**Comment by zcorpan** [comment]
@fserb @mstange @nical @grorg @junov @AmeliaBR @RafaelCintron are you OK with being listed in the OWNERS file here? It means you’ll get notified any time someone submits a PR with Media Capture tests, or changes to existing tests. And the tests could only be merged to the master branch after review from one of the OWNERS.

**Comment by AmeliaBR** [comment]
I'm ok with my name being there (with no promises about being able to contribute lots of reviewing time). Not sure I'm comfortable approving the entire PR without other people confirming their own names.

**Pull request merged**
