### PR TITLE
Add test for MediaStreamTrack.getSettings() (Resubmit)

### PR DESCRIPTION
**Pull request by soareschen**
This is a resubmission of #5114 with me taking over the PR and make changes.

I have slightly modified the code with clearer semantics and take in feedback from previous review.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226750977)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226750979)

# Firefox (nightly channel) #
Testing web-platform-tests at revision ac07679eb557cdef73020ff0c4b0d279ed4e1e79
Using browser at version BuildID 20170427100655; SourceStamp 0b77ed3f26c5335503bc16e85b8c067382e7bb1e
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5732/mediacapture-streams/MediaStreamTrack-getSettings.https.html">/mediacapture-streams/MediaStreamTrack-getSettings.https.html</a></summary>


|                          Subtest                           | Results |                                                  Messages                                                 |
|------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------|
|                                                            | OK      |                                                                                                           |
| `A device can be opened twice and have the same device ID` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: audio and/or video is required"`        |
| `A device can be opened twice with different resolutions`  | FAIL    | `promise_test: Unhandled rejection with value: object "NotFoundError: The object can not be found here."` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226750985)

# Chrome (unstable channel) #
Testing web-platform-tests at revision ac07679eb557cdef73020ff0c4b0d279ed4e1e79

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5732/)

**Comment by rwaldron** [comment]
@soareschen Can you revisit this, update as needed and rebase when ready? Thanks!!

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239817948)

# Firefox (nightly) #
Testing web-platform-tests at revision aee2c6a751ae9b76c82d4d1dbd19c998ba105b7c
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5732/mediacapture-streams/MediaStreamTrack-getSettings.https.html">/mediacapture-streams/MediaStreamTrack-getSettings.https.html</a></summary>


|                          Subtest                           | Results |                                                  Messages                                                 |
|------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------|
|                                                            | OK      |                                                                                                           |
| `A device can be opened twice and have the same device ID` | FAIL    | `promise_test: Unhandled rejection with value: object "NotFoundError: The object can not be found here."` |
| `A device can be opened twice with different resolutions`  | FAIL    | `promise_test: Unhandled rejection with value: object "NotFoundError: The object can not be found here."` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239817949)

# Sauce (safari) #
Testing web-platform-tests at revision aee2c6a751ae9b76c82d4d1dbd19c998ba105b7c
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5732/mediacapture-streams/MediaStreamTrack-getSettings.https.html">/mediacapture-streams/MediaStreamTrack-getSettings.https.html</a></summary>


|                          Subtest                           | Results |                                     Messages                                    |
|------------------------------------------------------------|---------|---------------------------------------------------------------------------------|
|                                                            | OK      |                                                                                 |
| `A device can be opened twice and have the same device ID` | FAIL    | `undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')` |
| `A device can be opened twice with different resolutions`  | FAIL    | `undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239817955)

# Chrome (unstable) #
Testing web-platform-tests at revision aee2c6a751ae9b76c82d4d1dbd19c998ba105b7c

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239817956)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision aee2c6a751ae9b76c82d4d1dbd19c998ba105b7c
Using browser at version 14.14393
Starting 10 test iterations

**Comment by soareschen** [comment]
Rebased. I also updated the code with new style to make it more readable.

**Review by rwaldron — APPROVED** [review]

**Comment by rwaldron** [comment]
This isn't in our "webrtc" spec, but it's good test work

**Pull request merged**
