### PR TITLE
Update interfaces/push-api.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/52f31b9/whatwg/idl/push-api.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/563479802

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Test needs updating to fix one regression.

**Comment by lukebjerring** [comment]
This change looks wrong; THe interface isn't deleted.
https://w3c.github.io/push-api/#pushmanager-interface

**Comment by lukebjerring** [comment]
At a guess based on timing and the interfaces that reffy-reports has dropped, this change caused it:
https://github.com/w3c/push-api/commit/9179964494a5cedcca4a104c555e98019fbb1135

Perhaps the default syntax isn't valid IDL according to reffy-reports? @tidoust - any idea?

**Comment by lukebjerring** [comment]
Filed https://github.com/tidoust/reffy-reports/issues/34

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
The changes look sensible now, and no change in results (checked Firefox).

**Pull request merged**
