### PR TITLE
Test that window.location is per global

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5778/)

**Comment by annevk** [comment]
Results: four browsers, four results:

Chrome: PASS, FAIL, FAIL
Edge: FAIL, PASS, FAIL
Firefox: FAIL, PASS, PASS
Safari TP: FAIL, FAIL, FAIL

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228652219)

# Firefox (nightly channel) #
Testing web-platform-tests at revision a58cbd57e3d1238881a81d8b9afa99e0d97f48bd
Using browser at version BuildID 20170503100422; SourceStamp 82c2d17e74ef9cdf38a5d5ac4eb3ae846ec30ba4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5778/html/browsers/history/the-location-interface/per-global.window.html">/html/browsers/history/the-location-interface/per-global.window.html</a></summary>


|                                  Subtest                                   | Results |                     Messages                     |
|----------------------------------------------------------------------------|---------|--------------------------------------------------|
|                                                                            | TIMEOUT |                                                  |
| `Discarding the browsing context must not change window.location`          | FAIL    | `assert_equals: expected object "" but got null` |
| `Navigating from the initial about:blank must not replace window.location` | PASS    |                                                  |
| `document.open() must replace window.location`                             | PASS    |                                                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228652225)

# Chrome (unstable channel) #
Testing web-platform-tests at revision a58cbd57e3d1238881a81d8b9afa99e0d97f48bd

**Review by foolip — APPROVED** [review]

**Pull request merged**
