### PR TITLE
[eme] Fix #4716: Rename all encrypted-media tests to use https

### LINKED ISSUE #4716: [eme] Update tests so that automated test runners run them as https
navigator.requestMediaKeySystemAccess() is supposed to only run on secure contexts [1]. w3c-test.org lets you run the tests as http or https, depending on how you connect to the server. However, automated test runners (e.g. the one in Chromium) by default run the tests as http.

It appears that one way to do this is to rename the tests to test.https.html.

[1] http://w3c.github.io/encrypted-media/#navigator-extension-requestmediakeysystemaccess

### PR DESCRIPTION
**Pull request by jrummell-chromium**
As the EME spec requires https, rename all the tests to .https.html so that
automated test runners will run them as https.

### CODE REVIEW

**Review by joeyparrish — APPROVED** [review]

**Comment by gsnedders** [comment]
Fixes #4716. (Duplicating this because GitHub doesn't pick it up from the title.)

**Comment by gsnedders** [comment]
I think this flakiness on Chrome is pre-existing and not an issue with this PR per-se; Firefox seems to be timing out for reasons I don't know (I admittedly know little about EME). Don't think it should block merge? @jgraham?

**Comment by ddorwin** [comment]
@mwatson2 @cpearce @jdsmith3000 Any concerns with this? I want to double check since it renames all the tests.

@jrummell-chromium, you'll need to rebase due to some of the PRs that were just merged. You might want to wait until the one remaining is merged.

**Comment by cpearce** [comment]
@gsnedders: Firefox won't work on all the EME tests, specifically the *persistent* tests. Does Firefox timeout without this change too?

I'm fine with these tests being made to run under HTTPS, I don't know of any issue that should cause them to have trouble with HTTPS in Firefox.

**Comment by mwatson2** [comment]
Fine by me.

**Comment by gsnedders** [comment]
@cpearce I don't have any actual evidence that it times out, however I suspect it does given it'll crash on every single test that tries to access an external network resources (which is most), and then restart the browser, and doing that ten times per test will take up a lot of time.

**Comment by jrummell-chromium** [comment]
Closing this as it's replaced by https://github.com/w3c/web-platform-tests/pull/6915.

**Pull request closed without merging**
