### PR TITLE
Adapt geolocation-sensor IDL to latest spec

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko, PTAL.

**Comment by anssiko** [comment]
LGTM, thanks!

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24799)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/345187107)

**Review by Ms2ger — APPROVED** [review]

**Comment by anssiko** [comment]
@Ms2ger thanks for the swift review!

**Pull request merged**
