### PR TITLE
manual tests to discover what type is dispatched from click, dblclick, and contextmenu.

### PR DESCRIPTION
**Pull request by travisleithead**
See https://github.com/w3c/html/issues/535

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205134511)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 57f74082b8ce57a772fd58f04f384bce876bf7f4
Using browser at version BuildID 20170223110219; SourceStamp 32dcdde1fc64fc39a9065dc4218265dbc727673f
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/205134513)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 57f74082b8ce57a772fd58f04f384bce876bf7f4
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
No tests run.

**Comment by domenic** [comment]
I guess this only contains contextmenu manual tests so far, but in addition to manual tests, you'll probably also want to check `.click()`.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5012/)

**Comment by travisleithead** [comment]
Now with click() test! Took a guess at which folder to drop these tests...

**Comment by domenic** [comment]
Good stuff!

**Pull request merged**
