### PR TITLE
Rename 'onchange' to 'onreading'

### PR DESCRIPTION
**Pull request by Honry**
Update WebIDL test in generic-sensor folder BTW

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249607929)

# Firefox (nightly) #
Testing web-platform-tests at revision 0c7e68a415790856e7f70daa3b0f3f8dbf44c4b0
Using browser at version BuildID 20170702100334; SourceStamp 4d3de12dcdc539f14fcb06539da39fa7176c8955
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>14 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/accelerometer/Accelerometer.https.html">/accelerometer/Accelerometer.https.html</a></summary>


|       Subtest        | Results |                    Messages                    |
|----------------------|---------|------------------------------------------------|
|                      | OK      |                                                |
| `Accelerometer Test` | FAIL    | `ReferenceError: Accelerometer is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6448/accelerometer/Accelerometer_insecure_context.html">/accelerometer/Accelerometer_insecure_context.html</a></summary>


|                Subtest                 | Results |                    Messages                    |
|----------------------------------------|---------|------------------------------------------------|
|                                        | OK      |                                                |
| `Accelerometer Test: insecure context` | FAIL    | `ReferenceError: Accelerometer is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/accelerometer/idlharness.https.html">/accelerometer/idlharness.https.html</a></summary>


|                                                        Subtest                                                        | Results |                                                                       Messages                                                                      |
|-----------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                       | OK      |                                                                                                                                                     |
| `Accelerometer interface: existence and properties of interface object`                                               | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface object length`                                                                               | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface object name`                                                                                 | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface: existence and properties of interface prototype object`                                     | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface: existence and properties of interface prototype object's "constructor" property`            | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface: attribute x`                                                                                | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface: attribute y`                                                                                | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer interface: attribute z`                                                                                | FAIL    | `assert_own_property: self does not have own property "Accelerometer" expected property "Accelerometer" missing`                                    |
| `Accelerometer must be primary interface of new Accelerometer();`                                                     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Accelerometer is not defined"`            |
| `Stringification of new Accelerometer();`                                                                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Accelerometer is not defined"`            |
| `Accelerometer interface: new Accelerometer(); must inherit property "x" with the proper type (0)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Accelerometer is not defined"`            |
| `Accelerometer interface: new Accelerometer(); must inherit property "y" with the proper type (1)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Accelerometer is not defined"`            |
| `Accelerometer interface: new Accelerometer(); must inherit property "z" with the proper type (2)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Accelerometer is not defined"`            |
| `LinearAccelerationSensor interface: existence and properties of interface object`                                    | FAIL    | `assert_own_property: self does not have own property "LinearAccelerationSensor" expected property "LinearAccelerationSensor" missing`              |
| `LinearAccelerationSensor interface object length`                                                                    | FAIL    | `assert_own_property: self does not have own property "LinearAccelerationSensor" expected property "LinearAccelerationSensor" missing`              |
| `LinearAccelerationSensor interface object name`                                                                      | FAIL    | `assert_own_property: self does not have own property "LinearAccelerationSensor" expected property "LinearAccelerationSensor" missing`              |
| `LinearAccelerationSensor interface: existence and properties of interface prototype object`                          | FAIL    | `assert_own_property: self does not have own property "LinearAccelerationSensor" expected property "LinearAccelerationSensor" missing`              |
| `LinearAccelerationSensor interface: existence and properties of interface prototype object's "constructor" property` | FAIL    | `assert_own_property: self does not have own property "LinearAccelerationSensor" expected property "LinearAccelerationSensor" missing`              |
| `LinearAccelerationSensor must be primary interface of new LinearAccelerationSensor();`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: LinearAccelerationSensor is not defined"` |
| `Stringification of new LinearAccelerationSensor();`                                                                  | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: LinearAccelerationSensor is not defined"` |
| `Accelerometer interface: new LinearAccelerationSensor(); must inherit property "x" with the proper type (0)`         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: LinearAccelerationSensor is not defined"` |
| `Accelerometer interface: new LinearAccelerationSensor(); must inherit property "y" with the proper type (1)`         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: LinearAccelerationSensor is not defined"` |
| `Accelerometer interface: new LinearAccelerationSensor(); must inherit property "z" with the proper type (2)`         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: LinearAccelerationSensor is not defined"` |
| `GravitySensor interface: existence and properties of interface object`                                               | FAIL    | `assert_own_property: self does not have own property "GravitySensor" expected property "GravitySensor" missing`                                    |
| `GravitySensor interface object length`                                                                               | FAIL    | `assert_own_property: self does not have own property "GravitySensor" expected property "GravitySensor" missing`                                    |
| `GravitySensor interface object name`                                                                                 | FAIL    | `assert_own_property: self does not have own property "GravitySensor" expected property "GravitySensor" missing`                                    |
| `GravitySensor interface: existence and properties of interface prototype object`                                     | FAIL    | `assert_own_property: self does not have own property "GravitySensor" expected property "GravitySensor" missing`                                    |
| `GravitySensor interface: existence and properties of interface prototype object's "constructor" property`            | FAIL    | `assert_own_property: self does not have own property "GravitySensor" expected property "GravitySensor" missing`                                    |
| `GravitySensor must be primary interface of new GravitySensor();`                                                     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: GravitySensor is not defined"`            |
| `Stringification of new GravitySensor();`                                                                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: GravitySensor is not defined"`            |
| `Accelerometer interface: new GravitySensor(); must inherit property "x" with the proper type (0)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: GravitySensor is not defined"`            |
| `Accelerometer interface: new GravitySensor(); must inherit property "y" with the proper type (1)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: GravitySensor is not defined"`            |
| `Accelerometer interface: new GravitySensor(); must inherit property "z" with the proper type (2)`                    | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: GravitySensor is not defined"`            |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/ambient-light/AmbientLightSensor.https.html">/ambient-light/AmbientLightSensor.https.html</a></summary>


|          Subtest          | Results |                       Messages                      |
|---------------------------|---------|-----------------------------------------------------|
|                           | OK      |                                                     |
| `AmbientLightSensor Test` | FAIL    | `ReferenceError: AmbientLightSensor is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6448/ambient-light/AmbientLightSensor_insecure_context.html">/ambient-light/AmbientLightSensor_insecure_context.html</a></summary>


|                   Subtest                   | Results |                       Messages                      |
|---------------------------------------------|---------|-----------------------------------------------------|
|                                             | OK      |                                                     |
| `AmbientLightSensor Test: insecure context` | FAIL    | `ReferenceError: AmbientLightSensor is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/ambient-light/idlharness.https.html">/ambient-light/idlharness.https.html</a></summary>


|                                                        Subtest                                                         | Results |                                                                    Messages                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                        | OK      |                                                                                                                                               |
| `AmbientLightSensor interface: existence and properties of interface object`                                           | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor interface object length`                                                                           | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor interface object name`                                                                             | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor interface: existence and properties of interface prototype object`                                 | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor interface: existence and properties of interface prototype object's "constructor" property`        | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor interface: attribute illuminance`                                                                  | FAIL    | `assert_own_property: self does not have own property "AmbientLightSensor" expected property "AmbientLightSensor" missing`                    |
| `AmbientLightSensor must be primary interface of new AmbientLightSensor();`                                            | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AmbientLightSensor is not defined"` |
| `Stringification of new AmbientLightSensor();`                                                                         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AmbientLightSensor is not defined"` |
| `AmbientLightSensor interface: new AmbientLightSensor(); must inherit property "illuminance" with the proper type (0)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AmbientLightSensor is not defined"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6448/generic-sensor/idlharness.html">/generic-sensor/idlharness.html</a></summary>


|                                                                    Subtest                                                                    | Results |                                                                   Messages                                                                  |
|-----------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                               | OK      |                                                                                                                                             |
| `SensorErrorEvent interface: existence and properties of interface object`                                                                    | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent interface object length`                                                                                                    | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent interface object name`                                                                                                      | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent interface: existence and properties of interface prototype object`                                                          | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent interface: existence and properties of interface prototype object's "constructor" property`                                 | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent interface: attribute error`                                                                                                 | FAIL    | `assert_own_property: self does not have own property "SensorErrorEvent" expected property "SensorErrorEvent" missing`                      |
| `SensorErrorEvent must be primary interface of new SensorErrorEvent("SECURITY_ERR", { errorCode: 18 });`                                      | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: SensorErrorEvent is not defined"` |
| `Stringification of new SensorErrorEvent("SECURITY_ERR", { errorCode: 18 });`                                                                 | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: SensorErrorEvent is not defined"` |
| `SensorErrorEvent interface: new SensorErrorEvent("SECURITY_ERR", { errorCode: 18 }); must inherit property "error" with the proper type (0)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: SensorErrorEvent is not defined"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/gyroscope/Gyroscope.https.html">/gyroscope/Gyroscope.https.html</a></summary>


|     Subtest      | Results |                  Messages                  |
|------------------|---------|--------------------------------------------|
|                  | OK      |                                            |
| `Gyroscope Test` | FAIL    | `ReferenceError: Gyroscope is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6448/gyroscope/Gyroscope_insecure_context.html">/gyroscope/Gyroscope_insecure_context.html</a></summary>


|              Subtest               | Results |                  Messages                  |
|------------------------------------|---------|--------------------------------------------|
|                                    | OK      |                                            |
| `Gyroscope Test: insecure context` | FAIL    | `ReferenceError: Gyroscope is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/gyroscope/idlharness.https.html">/gyroscope/idlharness.https.html</a></summary>


|                                                Subtest                                                 | Results |                                                               Messages                                                               |
|--------------------------------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                        | OK      |                                                                                                                                      |
| `Gyroscope interface: existence and properties of interface object`                                    | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface object length`                                                                    | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface object name`                                                                      | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface: existence and properties of interface prototype object`                          | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface: existence and properties of interface prototype object's "constructor" property` | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface: attribute x`                                                                     | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface: attribute y`                                                                     | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope interface: attribute z`                                                                     | FAIL    | `assert_own_property: self does not have own property "Gyroscope" expected property "Gyroscope" missing`                             |
| `Gyroscope must be primary interface of new Gyroscope();`                                              | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Gyroscope is not defined"` |
| `Stringification of new Gyroscope();`                                                                  | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Gyroscope is not defined"` |
| `Gyroscope interface: new Gyroscope(); must inherit property "x" with the proper type (0)`             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Gyroscope is not defined"` |
| `Gyroscope interface: new Gyroscope(); must inherit property "y" with the proper type (1)`             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Gyroscope is not defined"` |
| `Gyroscope interface: new Gyroscope(); must inherit property "z" with the proper type (2)`             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Gyroscope is not defined"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/magnetometer/Magnetometer.https.html">/magnetometer/Magnetometer.https.html</a></summary>


|       Subtest       | Results |                    Messages                   |
|---------------------|---------|-----------------------------------------------|
|                     | OK      |                                               |
| `Magnetometer Test` | FAIL    | `ReferenceError: Magnetometer is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6448/magnetometer/Magnetometer_insecure_context.html">/magnetometer/Magnetometer_insecure_context.html</a></summary>


|                Subtest                | Results |                    Messages                   |
|---------------------------------------|---------|-----------------------------------------------|
|                                       | OK      |                                               |
| `Magnetometer Test: insecure context` | FAIL    | `ReferenceError: Magnetometer is not defined` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/magnetometer/idlharness.https.html">/magnetometer/idlharness.https.html</a></summary>


|                                                           Subtest                                                            | Results |                                                                       Messages                                                                      |
|------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                              | OK      |                                                                                                                                                     |
| `Magnetometer interface: existence and properties of interface object`                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface object length`                                                                                       | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface object name`                                                                                         | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: existence and properties of interface prototype object`                                             | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: existence and properties of interface prototype object's "constructor" property`                    | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute x`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute y`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer interface: attribute z`                                                                                        | FAIL    | `assert_own_property: self does not have own property "Magnetometer" expected property "Magnetometer" missing`                                      |
| `Magnetometer must be primary interface of new Magnetometer();`                                                              | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Stringification of new Magnetometer();`                                                                                     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "x" with the proper type (0)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "y" with the proper type (1)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `Magnetometer interface: new Magnetometer(); must inherit property "z" with the proper type (2)`                             | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: Magnetometer is not defined"`             |
| `UncalibratedMagnetometer interface: existence and properties of interface object`                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface object length`                                                                           | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface object name`                                                                             | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object`                                 | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: existence and properties of interface prototype object's "constructor" property`        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute x`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute y`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute z`                                                                            | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute xBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute yBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer interface: attribute zBias`                                                                        | FAIL    | `assert_own_property: self does not have own property "UncalibratedMagnetometer" expected property "UncalibratedMagnetometer" missing`              |
| `UncalibratedMagnetometer must be primary interface of new UncalibratedMagnetometer();`                                      | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `Stringification of new UncalibratedMagnetometer();`                                                                         | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "x" with the proper type (0)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "y" with the proper type (1)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "z" with the proper type (2)`     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "xBias" with the proper type (3)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "yBias" with the proper type (4)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |
| `UncalibratedMagnetometer interface: new UncalibratedMagnetometer(); must inherit property "zBias" with the proper type (5)` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: UncalibratedMagnetometer is not defined"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6448/orientation-sensor/idlharness.https.html">/orientation-sensor/idlharness.https.html</a></summary>


|                                                                          Subtest                                                                          | Results |                                                                       Messages                                                                       |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                           | OK      |                                                                                                                                                      |
| `OrientationSensor interface: existence and properties of interface object`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface object length`                                                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface object name`                                                                                                                 | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: existence and properties of interface prototype object`                                                                     | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                            | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: attribute quaternion`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `OrientationSensor interface: operation populateMatrix(RotationMatrixType)`                                                                               | FAIL    | `assert_own_property: self does not have own property "OrientationSensor" expected property "OrientationSensor" missing`                             |
| `AbsoluteOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "AbsoluteOrientationSensor" expected property "AbsoluteOrientationSensor" missing`             |
| `AbsoluteOrientationSensor must be primary interface of new AbsoluteOrientationSensor();`                                                                 | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `Stringification of new AbsoluteOrientationSensor();`                                                                                                     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `OrientationSensor interface: new AbsoluteOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new AbsoluteOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: AbsoluteOrientationSensor is not defined"` |
| `RelativeOrientationSensor interface: existence and properties of interface object`                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface object length`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface object name`                                                                                                         | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object`                                                             | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor interface: existence and properties of interface prototype object's "constructor" property`                                    | FAIL    | `assert_own_property: self does not have own property "RelativeOrientationSensor" expected property "RelativeOrientationSensor" missing`             |
| `RelativeOrientationSensor must be primary interface of new RelativeOrientationSensor();`                                                                 | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `Stringification of new RelativeOrientationSensor();`                                                                                                     | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "quaternion" with the proper type (0)`                               | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `OrientationSensor interface: new RelativeOrientationSensor(); must inherit property "populateMatrix" with the proper type (1)`                           | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |
| `OrientationSensor interface: calling populateMatrix(RotationMatrixType) on new RelativeOrientationSensor(); with too few arguments must throw TypeError` | FAIL    | `assert_equals: Unexpected exception when evaluating object expected null but got object "ReferenceError: RelativeOrientationSensor is not defined"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249607930)

# Sauce (safari) #
Testing web-platform-tests at revision 0c7e68a415790856e7f70daa3b0f3f8dbf44c4b0
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249607936)

# Chrome (unstable) #
Testing web-platform-tests at revision c19ccb4affe01d4c3f3b66285af5f3e14986458e

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249607937)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c19ccb4affe01d4c3f3b66285af5f3e14986458e

**Review by alexshalamov — APPROVED** [review]

**Review by pozdnyakov — APPROVED** [review]

**Comment by Honry** [comment]
Thanks, @pozdnyakov, @alexshalamov, merge it.

**Pull request merged**
