### PR TITLE
[CSS21] move "ib-split" tests from vendor-imports into the main suite

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/web-platform-tests/wpt/issues/8615.

### CODE REVIEW

**Comment by foolip** [comment]
Looks like I didn't (visibly) break anything in the move:
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/ib-split?run_id=5647524176068608&run_id=5731331067609088&run_id=5151735565778944
https://wpt.fyi/results/css/CSS2/visuren?sha=1bdb37ce5c&label=pr_head

**Comment by foolip** [comment]
@dbaron might you be able to review this?

**Comment by nt1m** [comment]
@dbaron Review ping? or maybe @emilio can look into this if he has time.

**Comment by heycam** [comment]
@dholbert is probably the most recent person in charge of the reftest upstreaming script.

**Review by emilio — APPROVED** [review]
Since https://bugzilla.mozilla.org/show_bug.cgi?id=1490969 there's no need to do any other manual syncing, and these are the canonical tests, so moving them is totally fine to me.

**Comment by foolip** [comment]
Thanks @nt1m @emilio!

**Pull request merged**
