### PR TITLE
Better explain test execution in resources/test/README

### PR DESCRIPTION
**Pull request by Hexcles**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10184)

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Excellent, thank you!

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-26 21:02:17
Finished: 2018-03-26 21:11:31


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26471)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/358591761)

**Comment by jgraham** [comment]
FWIW I think that using the `ci_*.sh` scripts locally is a bit of an antipattern as they tend to depend on details of the travis setup.

**Comment by Hexcles** [comment]
@jgraham Thanks for the heads up. You're right. This one is probably relatively independent, but the other `ci_*.sh` scripts are indeed quite coupled with the Travis setup.

**Pull request merged**
