### PR TITLE
Added 9 tests and 4 references on active selection [css-pseudo-4]

### PR DESCRIPTION
**Pull request by TalbotG**
It is 9 tests rather, of which 4 are manual tests.
4 reference files.
2 support files.

### CODE REVIEW

**Review by fantasai — COMMENTED** [review]
Overall, I suggest using the text “Select This Text” instead of “Text Sample”, since it's a little more helpful to the tester. :)

active-selection-00*-manual

* Should these tests check multiple properties, e.g. 'cursor' checks that highlight is unaffected

active-selection-004-manual
active-selection-014

* Don't check for fuchsia underline, because it is a new feature. Just use regular underline.

active-selection-18

What's different about your intention for this test compared to active-selection-011 + active-selection-012?

active-selection-19

It looks like here you're testing partial selection, yes? Otherwise there seems to be no difference from active-selection-011. In that case, the metadata, e.g. the title, should say that this is your intention.

(Another option would be to test partial selection in the basic tests. You could do this by setting the color of the text and its background to match, making the selected text “PASS”, and coloring it green to make it visible.)

**Comment by TalbotG** [comment]
> Overall, I suggest using the text “Select This Text” instead of “Text Sample”, since it's a little more helpful to the tester. :)

I agree. I will use "Select This Text" for manual tests.

> 
> active-selection-00*-manual
> 
>  Should these tests check multiple properties, 
> e.g. 'cursor' checks that highlight is unaffected
> 

I can remove or drop 
active-selection-001-manual.html (testing color)
active-selection-002-manual.html (testing background-color)
active-selection-004-manual.html (testing text-decoration). No problem.

But **why should I remove
active-selection-003-manual.html (testing cursor) ?**
 
> 
> active-selection-004-manual
> active-selection-014
> 

I agree. I will remove active-selection-004-manual . No problem.

>   Don't check for fuchsia underline, because it is a new 
> feature. Just use regular underline.
> 

I will replace fuchsia underline by regular underline in 
active-selection-014 .

> 
> active-selection-18
> 
> What's different about your intention for this test compared to active-selection-011 + active-selection-012?
> 

As far as I remember, active-selection-18 is just a bit more complex than 011 and 012. But maybe I kept active-selection-018 for additional reasons... I can not remember if this is the case...
For example, why the test declared `div::selection { background-color: white; }` in that 018 test is not clear in my mind right now and could be related to some difficulty I had... There has to be a reason why I declared `div::selection { background-color: white; }` and I can not remember it right now...

> active-selection-19
> 
> It looks like here you're testing partial selection, yes? Otherwise there seems to be no difference from active-selection-011. In that case, the metadata, e.g. the title, should say that this is your intention.

I agree. I will tune-edit the metadata, e.g. the title in active-selection-19 test.

> 
> (Another option would be to test partial selection in the basic tests. You could do this by setting the color of the text and its background to match, making the selected text “PASS”, and coloring it green to make it visible.)

Okay. I see what you are saying. I could be testing partial selection with a "PASS" being at [beginning | middle | end] of 2 "FAIL" that would become white color on white background once selected. There can be more variations like that...

**Comment by TalbotG** [comment]
The modifications have been edited in the discussed tests in
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/?MD

I will create another Pull Request to submit those modified tests.
I will create a few additional partial selection tests. 
I need to re-examine active-selection-018.

I am waiting for your reply on active-selection-003-manual.html (testing cursor).

**Comment by TalbotG** [comment]
> test partial selection in the basic tests (...) 
> by  setting the color of the text and its background to 
> match,  making the selected text “PASS”, and coloring it 
> green to make it visible.)

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-015.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-015-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-016.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-016-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-017.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-017-ref.html

**Comment by TalbotG** [comment]
I must close this pull request and then create another one which will have the accepted+approved tests and the proposed modifications to the tests ... My current github "skills" prevent me from doing this in here... :(

**Comment by fantasai** [comment]
Replied in #20800

**Pull request closed without merging**
