### PR TITLE
Update interfaces/compression.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/w3c/webref/blob/fdd4fe0/ed/idl/compression.idl
Build: https://travis-ci.org/w3c/webref/builds/184515739

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@stephenmcgruer I don't see the wpt.fyi checks on this PR. Any idea why?

**Comment by foolip** [comment]
Alright, so the tests are broken now: "CompressionStream includes GenericTransformStream, but GenericTransformStream is undefined."

**Comment by foolip** [comment]
The change is from https://github.com/WICG/compression/commit/1f0b64be290e09570b1f986c2b515c9a2a234482. I think we need a dependency on encoding.idl now.

**Comment by stephenmcgruer** [comment]
I believe it moved to `streams` instead?

**Comment by foolip** [comment]
Ah, it's in https://streams.spec.whatwg.org/#other-specs-ts-wrapping, I had an old checkout of wpt and didn't see it there.

**Pull request closed without merging**
