### PR TITLE
[wdspec] fix partition regression

### PR DESCRIPTION
**Pull request by OrKoN**
Fixes a regression from https://github.com/web-platform-tests/wpt/pull/49420

### CODE REVIEW

**Comment by whimboo** [comment]
@OrKoN could we get this done via https://phabricator.services.mozilla.com/D230696? If you are fine with the changes we could get it landed on our side so it will be upstream synced pretty quick.

**Comment by OrKoN** [comment]
> @OrKoN could we get this done via https://phabricator.services.mozilla.com/D230696? If you are fine with the changes we could get it landed on our side so it will be upstream synced pretty quick.

sure, at the same time if someone reviews this one, it will land immediately. The change in https://phabricator.services.mozilla.com/D230696 seems to change more than was regressed and I am not sure that is correct (see https://bugzilla.mozilla.org/show_bug.cgi?id=1934045#c3)

**Review by Lightning00Blade — APPROVED** [review]

**Comment by OrKoN** [comment]
@whimboo this has landed, let me know if you want to revert and re-land on your side first, thanks!

**Comment by whimboo** [comment]
> @whimboo this has landed, let me know if you want to revert and re-land on your side first, thanks!

I don't think it we should get backed out which would only require more CI checks to run. Thanks for the fix! We will take care of the remaining one on our side.

**Pull request merged**
