### PR TITLE
[tools] Enable additional linting rules

### PR DESCRIPTION
**Pull request by jugglinmike**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/11110)

### CODE REVIEW

**Review by Hexcles — CHANGES_REQUESTED** [review]
Custom `has_key` methods are defined in `wptrunner/wptrunner/wptmanifest/backends/{conditional,static}.py`
which is why unit tests are failing with your changes. The methods probably need to be renamed to the magic `__contains__`.

**Comment by jugglinmike** [comment]
Thanks for the tip, @Hexcles! Unfortunately, enabling this linting option might take a little more work. That's because [the "conditional" `ManifestItem` already defines a `__contains__` method](https://github.com/w3c/web-platform-tests/blob/347a7974c93326910109cd0f3386cc427add4ec5/tools/wptrunner/wptrunner/wptmanifest/backends/conditional.py#L196-L197):

```python
    def __contains__(self, key):
        return key in self._data
```

And its semantics are distinct from those of [the custom `has_key` method](https://github.com/w3c/web-platform-tests/blob/347a7974c93326910109cd0f3386cc427add4ec5/tools/wptrunner/wptrunner/wptmanifest/backends/conditional.py#L216-L220)

```python
    def has_key(self, key):
        for node in [self, self.root]:
            if key in node._data:
                return True
        return False
```

There may be a case to be made against an API where `x.has_key(x)` behaves differently than `str in x` and that perhaps `has_key` should be renamed to more clearly signal the advanced lookup logic it implements. However, that discussion and that level of change are more than I really meant to start with this patch. I'm more inclined to remove the second commit and worry about `has_key` when/if we decide to take on the much larger (and more meaningful) task of supporting Python 3.

What do you think?

**Comment by Hexcles** [comment]
We should probably rename `has_key`. Clashing with a deprecated built-in method name is not good.

That said, I haven't looked too closely at the related code. If you're not sure what to do, then we can always make a smaller step each time (i.e. abandon the second and third commits for now).

**Comment by gsnedders** [comment]
@jgraham objected to renaming `has_key` before, fwiw.

**Comment by jugglinmike** [comment]
@gsnedders In that case, we should definitely proceed with that change in a separate patch. Thanks for letting us know!

@jgraham In can't find anything about your objection on GitHub or the #testing IRC logs. Would you mind re-iterating here?

@Hexcles I've reverted the commits related to that rule. This should be good to go now.

**Review by Hexcles — APPROVED** [review]
r+

**Review by gsnedders — APPROVED** [review]

**Comment by jugglinmike** [comment]
Thanks, @gsnedders!

**Comment by jugglinmike** [comment]
Oh and @Hexcles of course :)

**Pull request merged**
