### PR TITLE
 Add test for fragment handling in data URIs

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
This is my attempt at a WPT capturing the correct handling of '#' characters in data URIs. See http://crbug.com/123004 for the Chrome bug, and https://github.com/whatwg/fetch/pull/579 where @annevk is working on making the spec clearer regarding what is correct here.

I'm very open to suggestions for how to do this test 'better'. I wasn't able to find a way in js to get back what would be the "data" of a parsed data URI, so ended up just doing a reftest using <object>.

**Comment by stephenmcgruer** [comment]
@RByers as an FYI.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20342)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/299169026)

**Comment by annevk** [comment]
This looks pretty good. You can also generate HTML with a data URL in an `<iframe>` and `postMessage()` something to the parent. You might also want to test that the fragment is used `:target` selector matching and such.

As far as standards go. I think most folks agree that this is defined even with the original RFCs, it's just not super clear. But indeed that Fetch PR coupled with https://url.spec.whatwg.org/ should make it crystal clear.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20527)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/301503681)

**Review by annevk — APPROVED** [review]
Approving based on the assumption that this passes in Firefox. If it doesn't I need to take a closer look. Let me know if you need help landing this. I recommend squash & merge, combined with modifying the commit title and message.

**Comment by domenic** [comment]
Looks like it passes in Firefox: https://pulls.web-platform-tests.org/job/20527.4

However CI failed due to linting errors: https://travis-ci.org/w3c/web-platform-tests/jobs/301503683#L549

**Comment by stephenmcgruer** [comment]
Yes, sorry, I pushed a half-finished version by mistake. Will fix the linter errors, re-upload, and submit :). Thanks for the review!

**Pull request merged**
