### PR TITLE
Fix html/semantics/interfaces.js for rb and rtc elements to expect HTMLElement

### PR DESCRIPTION
**Pull request by kojiishi**
As per the spec:
https://html.spec.whatwg.org/multipage/obsolete.html#rb

### CODE REVIEW

**Comment by annevk** [comment]
https://html.spec.whatwg.org/multipage/obsolete.html#rb is the normative reference.

**Comment by kojiishi** [comment]
Can I ask what you're suggesting? I could not understand, sorry.
Update the comment with the URL you provided? I can't find interface definition there, but happy to do so if that's what you're suggesting.
Or are you suggesting not to fix this? I thought this is in response to what we were discussing in whatwg/html/#101, do I misunderstand that?

**Comment by kojiishi** [comment]
Updated the URL anyway. If you don't think this is right, please let me know and I'm fine to close, or you can close.

**Comment by annevk** [comment]
The change to the tests are fine, the commit message is misleading, since Web Platform Tests should follow the authoritative copy of HTML.

The reason the interface is `HTMLElement` per the HTML Standard is because the elements are "defined", even though only in the obsolete section. If they were not listed there they would use `HTMLUnknownElement`.

**Comment by kojiishi** [comment]
Thought commit message will not appear in merge, I don't know how to modify that, so I'll close this and re-upload.

**Pull request closed without merging**
