### PR TITLE
Simplify testharnessreport.js

### PR DESCRIPTION
**Pull request by foolip**
Two commits for ease of review and intended to be merged as two, but I could make them a single one and tweak the commit message if requested.

If requested, this could also be blocked on adding a lint for author and maybe a harness error if using per-test metadata, if either seems useful.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/8835)

### CODE REVIEW

**Comment by foolip** [comment]
@jugglinmike, does resources/test/ depend on the block inserted by `dump_test_results`? It kinda seemed like it at first, but I can't find the code that connects the dots, nor did I look very closely.

If it doesn't then maybe`dump_test_results` is also ripe for removal, but separately from this I'd argue.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-02 21:49:26
Finished: 2018-01-02 21:57:13


<h2>Failing Jobs</h2>
<ul>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22265)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/324316153)

**Comment by jugglinmike** [comment]
Hey Philip! In the interest of resiliency, the tests for testharness.js itself [rely on the
global message event](https://github.com/w3c/web-platform-tests/blob/1f9c924a4bf958c8bbd0233c8f0c0faf9251ac96/resources/test/harness.html), not the generated markup. If memory serves, this is the same mechanism in use by wptrunner, so any change that doesn't invalidate WPT should likewise jive with those tests.

**Review by Ms2ger — APPROVED** [review]

**Comment by foolip** [comment]
Thanks @jugglinmike and @Ms2ger!

**Pull request merged**
