### PR TITLE
Replace setTimeout with step_timeout in Fullscreen tests

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I've manually checked that the modified tests still pass or fail as before in Firefox Nightly.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232744243)

# Firefox (nightly) #
Testing web-platform-tests at revision 81c6633fbfca4db57dc72219734a8732f897dc49
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232744244)

# Sauce (safari) #
Testing web-platform-tests at revision 81c6633fbfca4db57dc72219734a8732f897dc49
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232744245)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 81c6633fbfca4db57dc72219734a8732f897dc49
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232744251)

# Chrome (unstable) #
Testing web-platform-tests at revision 81c6633fbfca4db57dc72219734a8732f897dc49

**Review by annevk — APPROVED** [review]
Why are these not in lint.whitelist?

**Comment by foolip** [comment]
> Why are these not in lint.whitelist?

It looks like manual tests aren't linted. I've now tried renaming them all and running the lint and didn't find any other problems.

**Pull request merged**
