### PR TITLE
 Load Ahem as a webfont everywhere (part 2)

### PR DESCRIPTION
**Pull request by LukeZielinski**
This change updates a large number of reftests to link to the
`/fonts/ahem.css` stylesheet. Each file contains a single additional
line before the first `<style>` element:
```
<link rel="stylesheet" type="text/css" href="/fonts/ahem.css" />
```

### CODE REVIEW

**Comment by LukeZielinski** [comment]
@gsnedders Advice on what we want to do with the failure of [`infrastructure/assumptions/ahem.html`](https://taskcluster-artifacts.net/CaVhkXWgRq6azSAqZsexDg/0/public/logs/live_backing.log)? This is generated by [ahem-generate-table.py](https://github.com/web-platform-tests/wpt/blob/master/infrastructure/assumptions/tools/ahem-generate-table.py). Seems like this test becomes a no-op if we're using web fonts.

**Comment by gsnedders** [comment]
@LukeZielinski As I said somewhere before, drop it. There's no point in it.

**Comment by LukeZielinski** [comment]
Ok this should be ready now. There are the following check failures, which I think are all OK to ignore:
- stability checks for both firefox and chrome time out (likely because too many tests are modified)
- wpt.fyi for both firefox and chrome show that the `ahem.html` test is the only one missing, which is expected
- resource tests time-out but this seems unrelated to this change (eg: they also time-out when run for an unrelated change like #16852

**Comment by gsnedders** [comment]
@LukeZielinski is there any chance of you posting the script you used to do this somewhere? (some random gist will do fine)

**Comment by gsnedders** [comment]
Looking over this, without checking every test, this looks good to me, and I've checked there aren't any regressions in any test results here.

I'd rather take a look at a script to have a bit more confidence in more of the tests, beyond the random sample, but in principle this looks good.

**Comment by LukeZielinski** [comment]
> @LukeZielinski is there any chance of you posting the script you used to do this somewhere? (some random gist will do fine)
Sure, I dropped it in a doc: https://docs.google.com/document/d/1Tf8xmC7L-mnMHnFa5Pq66ZTNohIFBvCoxyN0-JimlBE/preview#

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
@LukeZielinski actually, thinking about this again, I think we want to keep `infrastructure/assumptions/ahem.html` until we actually stop installing Ahem, and rely on it being installed?

**Comment by LukeZielinski** [comment]
> @LukeZielinski actually, thinking about this again, I think we want to keep `infrastructure/assumptions/ahem.html` until we actually stop installing Ahem, and rely on it being installed?

Sure, it can be cleaned up along with the docs as the final step.

**Comment by ewilligers** [comment]
> note that this is done from the Chromium side, but the set of tests should be equivalent since they are synced between the two repos

Except for the skipped suites in `third_party/blink/web_tests/W3CImportExpectations`.

**Comment by foolip** [comment]
Admin merging because stability checks time out because too many tests are affected.

**Comment by LukeZielinski** [comment]
> > note that this is done from the Chromium side, but the set of tests should be equivalent since they are synced between the two repos
> 
> Except for the skipped suites in `third_party/blink/web_tests/W3CImportExpectations`.

Yep, fair point. I'll cover those ones in a separate pass. The final step to this whole migration will be to stop installing Ahem on CI, which should uncover any other test that might have been missed.

**Comment by r12a** [comment]
I'm curious about what is the benefit of doing this for a lot of tests that don't need the Ahom font?

**Comment by jgraham** [comment]
> I'm curious about what is the benefit of doing this for a lot of tests that don't need the Ahom font?

The intent is that this only happened for tests that do use Ahem. Do you have examples where the webfont was added but isn't required? I think it would make sense to file a separate issue about that.

**Comment by r12a** [comment]
@jgraham Ah, ok.  In that case it makes more sense.  I thought i spotted a few files that didn't use the font, but i think it may have been a lapse in memory combined with an inability to see the relevant lines in the diff.

**Comment by gsnedders** [comment]
@LukeZielinski also just realised you used a case-sensitive grep, which missed a lot of font: ahem (font names are case-insensitive!).

```
LANG=C grep -R -l -i 'font.*:.*ahem' css | xargs grep -L ahem\\.css
```

in WPT gives 1320 lines (whoops!)

**Pull request merged**
