### PR TITLE
Add a test for innerText and c-v auto

### PR DESCRIPTION
**Pull request by rwlbuis**

### CODE REVIEW

**Comment by vmpstr** [comment]
There's an implementation defined (and allowed by spec) difference in the margin around the viewport. The non-normative recommendation is 50% around the viewport, in which case `200vh` is enough to space the elements off-screen. In Chromium, we ended up changing this to 200% of the viewport, so `200vh` is not enough to space the elements off-screen.

If you change this to `300vh`, then you would get closer to the expected result. It still fails, but it fails because of a trailing newline

If you compare `document.body.innerText.trim()` to a "no trailing newline" expectation, and have `300vh` spacer, the test passes on Chromium.

Let me know if my reasoning makes sense. Maybe we can update the non-normative guidance in the spec.

**Comment by rwlbuis** [comment]
> There's an implementation defined (and allowed by spec) difference in the margin around the viewport. The non-normative recommendation is 50% around the viewport, in which case `200vh` is enough to space the elements off-screen. In Chromium, we ended up changing this to 200% of the viewport, so `200vh` is not enough to space the elements off-screen.
> 
> If you change this to `300vh`, then you would get closer to the expected result. It still fails, but it fails because of a trailing newline

Ah right! So far we have used just 3000px or 300vh in the c-v tests, so clearly my mistake, fixed.

> If you compare `document.body.innerText.trim()` to a "no trailing newline" expectation, and have `300vh` spacer, the test passes on Chromium.

An annoying difference between the implementations, in my new update I circumvented it by introducing a br, let me know if you prefer the trim or the updated test.

> Let me know if my reasoning makes sense. Maybe we can update the non-normative guidance in the spec.

Makes sense, thanks!

**Comment by rwlbuis** [comment]
Also, I think this shows a gecko bug, as it fails in my local gecko build too, unlike chromium and WebKit.

**Comment by rwlbuis** [comment]
@annevk is it needed for sink-task/wpt-firefox-nightly-stability to pass here before the PR can go in? AFAICS this is a real gecko bug.

**Review by vmpstr — APPROVED** [review]

**Comment by vmpstr** [comment]
> An annoying difference between the implementations, in my new update I circumvented it by introducing a br, let me know if you prefer the trim or the updated test.

The way you fixed it is fine as well.

This lgtm, but please wait for Anne to answer your question :)

**Comment by rwlbuis** [comment]
@jgraham maybe you know how to deal with the sink-task failure?

**Pull request merged**
