### PR TITLE
Add lint for files with the same basename path

### LINKED ISSUE #7570: Consider adding a lint for files with the same basename in the same directory
This causes issues for Blink/WebKit at this time; see https://github.com/w3c/web-platform-tests/pull/7569. I'd argue it's not a very good idea in general anyway.

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes #7570

Closes #9957

Co-authored-by: rohilla21 <kritirohilla567@gmail.com>

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
After writing this (based on the old PR), it struck me that maybe this should be a `path_lints` instead, where for each changed path we just look for any other file at the same location with a different extension. That might be more expensive for `--all` (depends on the cost of the file-glob call), but it has the advantage of not running into the problem I describe at https://w3.logbot.info/testing/20200424#c551490

Lmk what you think.

**Comment by Hexcles** [comment]
OK looking at the [test](https://community-tc.services.mozilla.com/tasks/ZSKdeNkgRgq76FHYSn2w9g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZSKdeNkgRgq76FHYSn2w9g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L73), I think this is a bit more complicated. We need to exclude `.js` at least, which expands to `.window.html`, `.worker.html` etc., so it doesn't collide with other extensions.

Regarding https://w3.logbot.info/testing/20200424#c551490, I think this should be the same as `check_css_globally_unique`, which may also unfortunately break when running without `--all`. I'm not surprised, but I think we should probably add a warning to the output.

**Comment by stephenmcgruer** [comment]
> OK looking at the test, I think this is a bit more complicated. We need to exclude .js at least, which expands to .window.html, .worker.html etc., so it doesn't collide with other extensions.

Oof, yeah. That's what I get for fixing the code and then uploading without running a local test :D.

I played with `SourceFile.name_is_non_test`, but it doesn't really get us much (it doesn't actually do what I expect it to do at all...). We may need to require or generate an actual Manifest for this, as I think ultimately what we care about is two test files with the same basename?

**Comment by Hexcles** [comment]
> We may need to require or generate an actual Manifest for this, as I think ultimately what we care about is two test files with the same basename?

If you want to be 100% correct, yes, but I think some false positives are fine: we can simply expand `.any.js` to all possible suffixes in this lint.

**Comment by stephenmcgruer** [comment]
> If you want to be 100% correct, yes, but I think some false positives are fine: we can simply expand .any.js to all possible suffixes in this lint.

The way this lint is currently written, `file.html` and `file.any.js` isn't a collision (see below). Which is arguably a bug (should we allow tests which have different flags, e.g. `foo.https.html` vs `foo.html`?), but also means all these collisions that we've found with this PR are actually of the form `file.html` vs `file.js`, etc. I believe these all to be support or reference files, and having 100s of false-positives is a bit much ;)

```
>>> import os
>>> os.path.splitext("file.any.js")
('file.any', '.js')
```

**Comment by jgraham** [comment]
What's actually required by the blink infra here? My preference would be not having this lint at all, so I'm not too keen for it to do more than's required.

**Comment by stephenmcgruer** [comment]
> What's actually required by the blink infra here? My preference would be not having this lint at all, so I'm not too keen for it to do more than's required.

That's very fair; I'm cognizant of not pushing too much into WPT. Worst case, I'm happy for us to eat this pain on the Blink side (though it also affects WebKit).

That said, having gone through what we actually need I believe we only care about testharness tests; these are the cases where we may create an `-expected.txt` baseline in Chromium and thus where basenames may conflict. @Hexcles may be able to correct me if I'm wrong, but I've uploaded a new version of this that just checks for testharness tests and I think it should have far fewer conflicts (letting CI run to confirm).

**Comment by Hexcles** [comment]
> we only care about testharness tests; these are the cases where we may create an -expected.txt baseline in Chromium and thus where basenames may conflict.

That is correct. I *believe* that's also the case for WebKit unless they somehow also check in the screenshots for reftests or visual tests (not likely).

**Comment by stephenmcgruer** [comment]
Looks like `lint --all` turns up just one case for this, and it's a case we know about and which is an issue, so that's good:

```
ERROR:lint:dom/nodes/Document-createCDATASection: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .html) (DUPLICATE-BASENAME-PATH)
```

I'll fix up the tests and code, and then ping for a review.

**Comment by stephenmcgruer** [comment]
Yay, no more test failures. @Hexcles - PTAL.

**Review by Hexcles — APPROVED** [review]
LGTM. In fact, perfect! :)

**Pull request merged**
