### PR TITLE
Test that removed WebVTT APIs are not supported

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/w3c/webvtt/pull/31

---

Actually `id` might be added back in https://github.com/w3c/webvtt/pull/201 ...

cc @BenjaminSchaaf

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204601240)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 96a0d3d121d96ca3630150bd169364bbe2bb2c74
Using browser at version BuildID 20170222110216; SourceStamp 9a9db410f20781076424307265decbc5de1e94cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4997/webvtt/api/historical.html">/webvtt/api/historical.html</a></summary>


|                    Subtest                    | Results |
|-----------------------------------------------|---------|
|                                               | OK      |
| `TextTrack addRegion member must be nuked`    | PASS    |
| `VTTRegionList interface must be nuked`       | PASS    |
| `VTTCue regionId member must be nuked`        | PASS    |
| `TextTrack removeRegion member must be nuked` | PASS    |
| `TextTrack regions member must be nuked`      | PASS    |
| `VTTRegion track member must be nuked`        | FAIL    |
| `VTTRegion id member must be nuked`           | FAIL    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204601241)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 96a0d3d121d96ca3630150bd169364bbe2bb2c74
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4997/webvtt/api/historical.html">/webvtt/api/historical.html</a></summary>


|                    Subtest                    | Results |
|-----------------------------------------------|---------|
|                                               | OK      |
| `TextTrack addRegion member must be nuked`    | PASS    |
| `VTTRegionList interface must be nuked`       | PASS    |
| `VTTCue regionId member must be nuked`        | PASS    |
| `TextTrack removeRegion member must be nuked` | PASS    |
| `TextTrack regions member must be nuked`      | PASS    |
| `VTTRegion track member must be nuked`        | FAIL    |
| `VTTRegion id member must be nuked`           | FAIL    |

</details>
</details>

**Comment by zcorpan** [comment]
`id` was added in https://github.com/w3c/webvtt/pull/349

**Comment by zcorpan** [comment]
@silviapfeiffer can you review?

**Review by silviapfeiffer — APPROVED** [review]
Sorry for the delay. Agreed

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 05:12:25
Finished: 2017-08-15 05:21:49





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17394)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264618844)

**Pull request merged**
