### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by sadym-chromium**
Fix tests failures in Python 3.10+

https://wpt.fyi/results/webdriver/tests/bidi/session/status/status.py?run_id=5187039419432960

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Review by jgraham — DISMISSED** [review]

**Comment by jgraham** [comment]
Shouldn't we just update to the latest websockets library? I did that in https://phabricator.services.mozilla.com/D157968 (not landed), and I think it also fixes this issue.

**Comment by sadym-chromium** [comment]
@jgraham 
> Shouldn't we just update to the latest websockets library? I did that in https://phabricator.services.mozilla.com/D157968 (not landed), and I think it also fixes this issue.

It would be great! Could you please merge it?

**Comment by sadym-chromium** [comment]
> @jgraham
> 
> > Shouldn't we just update to the latest websockets library? I did that in https://phabricator.services.mozilla.com/D157968 (not landed), and I think it also fixes this issue.
> 
> It would be great! Could you please merge it?

@jgraham 
Or we can merge this PR as an intermediate solution until the websockets library is updated.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/36524 updates the websockets library, but that also seems to break Python 3.6 :/ So I'm inclined to merge this local patch for now.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
