### PR TITLE
Add HTMLScriptElement defer test

### PR DESCRIPTION
**Pull request by xiuqijix**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21867)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/316797160)

**Review by Ms2ger — CHANGES_REQUESTED** [review]
I made the following comment on critic:

Ms2ger at 2015-04-09 17:49 +02:00:
  Right now, if the deferred script runs after the load event fires, the test in
  it will be ignored. I suggest to instead use one async_test() and step in both
  scripts.

  I also think it would be clearer to use two boolean variables, say
  "ran_deferred_script" and "ran_inline_script".

**Comment by kaixinjxq** [comment]
Thanks @Ms2ger, update the test with async_test and I think a 'ran_deferred_script' boolean variable should be enough, PTAL.

**Review by Ms2ger — APPROVED** [review]
I suppose that works too, but "ran_deferred_script" is a pretty poor name for what it does now. Possibly something generic like "script_run_status"?

**Comment by kaixinjxq** [comment]
@Ms2ger, update the test with a 'script_run_status' string variable, PTAL.

**Comment by Ms2ger** [comment]
Thanks, that looks a lot more readable.

**Pull request merged**
