### PR TITLE
Add a gradient color-stops parsing test

### PR DESCRIPTION
**Pull request by fmalita**
This also adds some coverage for parsing CSS Image Values and Replaced
Content Module Level 4 conic-gradient [1] and dual-positioned stops [2].

[1] https://www.w3.org/TR/css-images-4/#conic-gradients
[2] https://www.w3.org/TR/css-images-4/#typedef-color-stop-length

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26736)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/361316137)

**Comment by svgeesus** [comment]
@LeaVerou this could use a review from you, I think.

**Review by LeaVerou — APPROVED** [review]
Looks good to me 👍

**Comment by fmalita** [comment]
Thanks Lea!

I think I also need approval from @tabatkins / @fantasai / @plinss to merge?

**Comment by fmalita** [comment]
@tabatkins @fantasai @plinss could you take a look at this?  Thanks!

**Review by emilio — APPROVED** [review]

**Pull request merged**
