### PR TITLE
Add tests for importing revoked blob URLs across agents

### PR DESCRIPTION
**Pull request by andreubotella**
Ref: https://github.com/denoland/deno/issues/12248

### CODE REVIEW

**Comment by andreubotella** [comment]
In Chrome, `Worker` is not exposed in a `SharedWorker`'s global scope, although the spec says it should be. Since `Worker` is also not exposed on service workers, these tests are best moved to a separate `Window`-only test file.

**Review by annevk — APPROVED** [review]
The "success" member was a little confusing to me as it's really about success of the import operation and not success of the test.

**Comment by andreubotella** [comment]
> The "success" member was a little confusing to me as it's really about success of the import operation and not success of the test.

Renamed it to `importSucceeded`

**Review by annevk — APPROVED** [review]
Thanks! FWIW, when I approve it's okay to merge and if you decide to make the requested changes you don't have to ask for review again, but I'm happy to take another look of course.

**Pull request merged**
