### PR TITLE
Update RTCPeerConnection IDL test to latest editor draft

### PR DESCRIPTION
**Pull request by soareschen**
This PR updates the RTCPeerConnection IDL test to the latest editor draft. The test file is also moved to root webrtc/ directory following new naming convention in accordance to #5657.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5693)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225864288)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225864290)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d063fcc3660d7ce0eadd9d636eab5fbf2b8b2cb4
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5693/webrtc/RTCPeerConnection-idl.html">/webrtc/RTCPeerConnection-idl.html</a></summary>


|                                                                                        Subtest                                                                                        | Results |                                                              Messages                                                              |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                       | OK      |                                                                                                                                    |
| `RTCPeerConnection interface: existence and properties of interface object`                                                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface object length`                                                                                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface object name`                                                                                                                                             | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: existence and properties of interface prototype object`                                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: existence and properties of interface prototype object's "constructor" property`                                                                        | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation createOffer(RTCOfferOptions)`                                                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation createAnswer(RTCAnswerOptions)`                                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation setLocalDescription(RTCSessionDescriptionInit)`                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute localDescription`                                                                                                                             | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute currentLocalDescription`                                                                                                                      | FAIL    | `assert_true: The prototype object must have a property "currentLocalDescription" expected true got false`                         |
| `RTCPeerConnection interface: attribute pendingLocalDescription`                                                                                                                      | FAIL    | `assert_true: The prototype object must have a property "pendingLocalDescription" expected true got false`                         |
| `RTCPeerConnection interface: operation setRemoteDescription(RTCSessionDescriptionInit)`                                                                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute remoteDescription`                                                                                                                            | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute currentRemoteDescription`                                                                                                                     | FAIL    | `assert_true: The prototype object must have a property "currentRemoteDescription" expected true got false`                        |
| `RTCPeerConnection interface: attribute pendingRemoteDescription`                                                                                                                     | FAIL    | `assert_true: The prototype object must have a property "pendingRemoteDescription" expected true got false`                        |
| `RTCPeerConnection interface: operation addIceCandidate([object Object],[object Object])`                                                                                             | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute signalingState`                                                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute iceGatheringState`                                                                                                                            | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute iceConnectionState`                                                                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute connectionState`                                                                                                                              | FAIL    | `assert_true: The prototype object must have a property "connectionState" expected true got false`                                 |
| `RTCPeerConnection interface: attribute canTrickleIceCandidates`                                                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute defaultIceServers`                                                                                                                            | FAIL    | `assert_own_property: The interface object must have a property "defaultIceServers" expected property "defaultIceServers" missing` |
| `RTCPeerConnection interface: operation getConfiguration()`                                                                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation setConfiguration(RTCConfiguration)`                                                                                                           | FAIL    | `assert_own_property: interface prototype object missing non-static operation expected property "setConfiguration" missing`        |
| `RTCPeerConnection interface: operation close()`                                                                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute onnegotiationneeded`                                                                                                                          | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute onicecandidate`                                                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute onicecandidateerror`                                                                                                                          | FAIL    | `assert_true: The prototype object must have a property "onicecandidateerror" expected true got false`                             |
| `RTCPeerConnection interface: attribute onsignalingstatechange`                                                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute oniceconnectionstatechange`                                                                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute onicegatheringstatechange`                                                                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute onconnectionstatechange`                                                                                                                      | FAIL    | `assert_true: The prototype object must have a property "onconnectionstatechange" expected true got false`                         |
| `RTCPeerConnection interface: attribute onfingerprintfailure`                                                                                                                         | FAIL    | `assert_true: The prototype object must have a property "onfingerprintfailure" expected true got false`                            |
| `RTCPeerConnection interface: operation createOffer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback,RTCOfferOptions)`                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation setLocalDescription(RTCSessionDescriptionInit,VoidFunction,RTCPeerConnectionErrorCallback)`                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation createAnswer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback)`                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation setRemoteDescription(RTCSessionDescriptionInit,VoidFunction,RTCPeerConnectionErrorCallback)`                                                  | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation addIceCandidate([object Object],[object Object],VoidFunction,RTCPeerConnectionErrorCallback)`                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation generateCertificate(AlgorithmIdentifier)`                                                                                                     | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation getSenders()`                                                                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation getReceivers()`                                                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation getTransceivers()`                                                                                                                            | FAIL    | `assert_own_property: interface prototype object missing non-static operation expected property "getTransceivers" missing`         |
| `RTCPeerConnection interface: operation addTrack(MediaStreamTrack,MediaStream)`                                                                                                       | FAIL    | `assert_equals: property has wrong .length expected 1 but got 2`                                                                   |
| `RTCPeerConnection interface: operation removeTrack(RTCRtpSender)`                                                                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation addTransceiver([object Object],[object Object],RTCRtpTransceiverInit)`                                                                        | FAIL    | `assert_own_property: interface prototype object missing non-static operation expected property "addTransceiver" missing`          |
| `RTCPeerConnection interface: attribute ontrack`                                                                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute sctp`                                                                                                                                         | FAIL    | `assert_true: The prototype object must have a property "sctp" expected true got false`                                            |
| `RTCPeerConnection interface: operation createDataChannel(USVString,RTCDataChannelInit)`                                                                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute ondatachannel`                                                                                                                                | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation getStats(MediaStreamTrack)`                                                                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation setIdentityProvider(DOMString,RTCIdentityProviderOptions)`                                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: operation getIdentityAssertion()`                                                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute peerIdentity`                                                                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute idpLoginUrl`                                                                                                                                  | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: attribute idpErrorInfo`                                                                                                                                 | FAIL    | `assert_true: The prototype object must have a property "idpErrorInfo" expected true got false`                                    |
| `RTCPeerConnection must be primary interface of pc`                                                                                                                                   | PASS    |                                                                                                                                    |
| `Stringification of pc`                                                                                                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "createOffer" with the proper type (0)`                                                                                        | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling createOffer(RTCOfferOptions) on pc with too few arguments must throw TypeError`                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "createAnswer" with the proper type (1)`                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling createAnswer(RTCAnswerOptions) on pc with too few arguments must throw TypeError`                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "setLocalDescription" with the proper type (2)`                                                                                | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling setLocalDescription(RTCSessionDescriptionInit) on pc with too few arguments must throw TypeError`                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "localDescription" with the proper type (3)`                                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "currentLocalDescription" with the proper type (4)`                                                                            | FAIL    | `assert_inherits: property "currentLocalDescription" not found in prototype chain`                                                 |
| `RTCPeerConnection interface: pc must inherit property "pendingLocalDescription" with the proper type (5)`                                                                            | FAIL    | `assert_inherits: property "pendingLocalDescription" not found in prototype chain`                                                 |
| `RTCPeerConnection interface: pc must inherit property "setRemoteDescription" with the proper type (6)`                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling setRemoteDescription(RTCSessionDescriptionInit) on pc with too few arguments must throw TypeError`                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "remoteDescription" with the proper type (7)`                                                                                  | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "currentRemoteDescription" with the proper type (8)`                                                                           | FAIL    | `assert_inherits: property "currentRemoteDescription" not found in prototype chain`                                                |
| `RTCPeerConnection interface: pc must inherit property "pendingRemoteDescription" with the proper type (9)`                                                                           | FAIL    | `assert_inherits: property "pendingRemoteDescription" not found in prototype chain`                                                |
| `RTCPeerConnection interface: pc must inherit property "addIceCandidate" with the proper type (10)`                                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling addIceCandidate([object Object],[object Object]) on pc with too few arguments must throw TypeError`                                             | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "signalingState" with the proper type (11)`                                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "iceGatheringState" with the proper type (12)`                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "iceConnectionState" with the proper type (13)`                                                                                | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "connectionState" with the proper type (14)`                                                                                   | FAIL    | `assert_inherits: property "connectionState" not found in prototype chain`                                                         |
| `RTCPeerConnection interface: pc must inherit property "canTrickleIceCandidates" with the proper type (15)`                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "defaultIceServers" with the proper type (16)`                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "getConfiguration" with the proper type (17)`                                                                                  | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "setConfiguration" with the proper type (18)`                                                                                  | FAIL    | `assert_inherits: property "setConfiguration" not found in prototype chain`                                                        |
| `RTCPeerConnection interface: calling setConfiguration(RTCConfiguration) on pc with too few arguments must throw TypeError`                                                           | FAIL    | `assert_inherits: property "setConfiguration" not found in prototype chain`                                                        |
| `RTCPeerConnection interface: pc must inherit property "close" with the proper type (19)`                                                                                             | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "onnegotiationneeded" with the proper type (20)`                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "onicecandidate" with the proper type (21)`                                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "onicecandidateerror" with the proper type (22)`                                                                               | FAIL    | `assert_inherits: property "onicecandidateerror" not found in prototype chain`                                                     |
| `RTCPeerConnection interface: pc must inherit property "onsignalingstatechange" with the proper type (23)`                                                                            | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "oniceconnectionstatechange" with the proper type (24)`                                                                        | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "onicegatheringstatechange" with the proper type (25)`                                                                         | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "onconnectionstatechange" with the proper type (26)`                                                                           | FAIL    | `assert_inherits: property "onconnectionstatechange" not found in prototype chain`                                                 |
| `RTCPeerConnection interface: pc must inherit property "onfingerprintfailure" with the proper type (27)`                                                                              | FAIL    | `assert_inherits: property "onfingerprintfailure" not found in prototype chain`                                                    |
| `RTCPeerConnection interface: pc must inherit property "createOffer" with the proper type (28)`                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling createOffer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback,RTCOfferOptions) on pc with too few arguments must throw TypeError`    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "setLocalDescription" with the proper type (29)`                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling setLocalDescription(RTCSessionDescriptionInit,VoidFunction,RTCPeerConnectionErrorCallback) on pc with too few arguments must throw TypeError`   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "createAnswer" with the proper type (30)`                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling createAnswer(RTCSessionDescriptionCallback,RTCPeerConnectionErrorCallback) on pc with too few arguments must throw TypeError`                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "setRemoteDescription" with the proper type (31)`                                                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling setRemoteDescription(RTCSessionDescriptionInit,VoidFunction,RTCPeerConnectionErrorCallback) on pc with too few arguments must throw TypeError`  | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "addIceCandidate" with the proper type (32)`                                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling addIceCandidate([object Object],[object Object],VoidFunction,RTCPeerConnectionErrorCallback) on pc with too few arguments must throw TypeError` | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "generateCertificate" with the proper type (33)`                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling generateCertificate(AlgorithmIdentifier) on pc with too few arguments must throw TypeError`                                                     | FAIL    | `assert_unreached: Throws "TypeError: fn is undefined" instead of rejecting promise Reached unreachable code`                      |
| `RTCPeerConnection interface: pc must inherit property "getSenders" with the proper type (34)`                                                                                        | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "getReceivers" with the proper type (35)`                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "getTransceivers" with the proper type (36)`                                                                                   | FAIL    | `assert_inherits: property "getTransceivers" not found in prototype chain`                                                         |
| `RTCPeerConnection interface: pc must inherit property "addTrack" with the proper type (37)`                                                                                          | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling addTrack(MediaStreamTrack,MediaStream) on pc with too few arguments must throw TypeError`                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "removeTrack" with the proper type (38)`                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling removeTrack(RTCRtpSender) on pc with too few arguments must throw TypeError`                                                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "addTransceiver" with the proper type (39)`                                                                                    | FAIL    | `assert_inherits: property "addTransceiver" not found in prototype chain`                                                          |
| `RTCPeerConnection interface: calling addTransceiver([object Object],[object Object],RTCRtpTransceiverInit) on pc with too few arguments must throw TypeError`                        | FAIL    | `assert_inherits: property "addTransceiver" not found in prototype chain`                                                          |
| `RTCPeerConnection interface: pc must inherit property "ontrack" with the proper type (40)`                                                                                           | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "sctp" with the proper type (41)`                                                                                              | FAIL    | `assert_inherits: property "sctp" not found in prototype chain`                                                                    |
| `RTCPeerConnection interface: pc must inherit property "createDataChannel" with the proper type (42)`                                                                                 | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling createDataChannel(USVString,RTCDataChannelInit) on pc with too few arguments must throw TypeError`                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "ondatachannel" with the proper type (43)`                                                                                     | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "getStats" with the proper type (44)`                                                                                          | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling getStats(MediaStreamTrack) on pc with too few arguments must throw TypeError`                                                                   | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "setIdentityProvider" with the proper type (45)`                                                                               | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: calling setIdentityProvider(DOMString,RTCIdentityProviderOptions) on pc with too few arguments must throw TypeError`                                    | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "getIdentityAssertion" with the proper type (46)`                                                                              | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "peerIdentity" with the proper type (47)`                                                                                      | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "idpLoginUrl" with the proper type (48)`                                                                                       | PASS    |                                                                                                                                    |
| `RTCPeerConnection interface: pc must inherit property "idpErrorInfo" with the proper type (49)`                                                                                      | FAIL    | `assert_inherits: property "idpErrorInfo" not found in prototype chain`                                                            |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225864296)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d063fcc3660d7ce0eadd9d636eab5fbf2b8b2cb4

**Comment by foolip** [comment]
In https://github.com/w3c/web-platform-tests/pull/5666 @ayg has begun splitting out IDL files into interfaces/*.idl, which I think will be a big improvement and could make it much easier to maintain these tests.

So, I would actually suggest a single interfaces/webrtc-pc.idl that contains all of the IDL in https://w3c.github.io/webrtc-pc/, and a single webrtc/interfaces.html that tests all of that. I think it's still small enough that timeouts wouldn't be a problem.

**Comment by soareschen** [comment]
+1 sounds good. I will submit a separate PR replacing this and the other IDL PRs I submitted.

**Comment by agouaillard-cosmo** [comment]
ok, when you have the new PR in place, let me know, we will reference it in here for traceability, and close this one.

**Comment by foolip** [comment]
Closed the others, leaving this one open until the replacement is in.

**Comment by foolip** [comment]
Closing in favor of https://github.com/w3c/web-platform-tests/issues/5712 even though it's still open.

**Pull request closed without merging**
