### PR TITLE
wai-aria: update tests

### PR DESCRIPTION
**Pull request by joanmarie**
* Correct platform expectations for MSAA, IA2, and UIA
* Remove use of external source for tests with iframe

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242923025)

# Firefox (nightly) #
Testing web-platform-tests at revision d76e88794585d899defd44fe3b70aeb157142b01
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242923026)

# Sauce (safari) #
Testing web-platform-tests at revision d76e88794585d899defd44fe3b70aeb157142b01
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242923032)

# Chrome (unstable) #
Testing web-platform-tests at revision d76e88794585d899defd44fe3b70aeb157142b01

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242923033)

# Sauce (MicrosoftEdge) #

**Review by halindrome — APPROVED** [review]
LGTM.  I wonder if we want to add a way to put a more meaningful name on each step?  Maybe we already have one, actually.  I will create an issue about that separately.

**Pull request merged**
