### PR TITLE
Support instrumenting child process

### PR DESCRIPTION
**Pull request by WeizhongX**
Using multiprocessing.Queue so that the Instrument class can receive
messages from child processes.

Plan to add more instrumenting code later.

### CODE REVIEW

**Review by DanielRyanSmith — APPROVED** [review]
I'm going to approve these changes and take the blame if anything breaks 😅

**Comment by WeizhongX** [comment]
Thank you Daniel. No worry if there is any breakage I should take the major blame.

(I did break things before because the change made is for android side, and the CI does not have sufficient coverage for that. I guess it is unlikely for this one.)

**Comment by jgraham** [comment]
This did break something in the end; `native_id` on threads is Python 3.8+ whereas we still need to support 3.6+. I'm going to patch it locally in gecko.

**Comment by jgraham** [comment]
We should maybe turn the intrumentation on in some of our CI to avoid this kind of thing in the future; if I haven't looked at that next week please remind me.

**Comment by jgraham** [comment]
It also appears to cause a shutdown hang.

**Comment by WeizhongX** [comment]
jgraham@, sorry about this.

What is your suggestion for next step? I would be fine if we want to revert this.

Also at the code review side, it will be better if we can have more ppl that are familiar with the code to review.

**Comment by jgraham** [comment]
No worries; I didn't notice for a long time because the gecko sync has been behind, and I discovered this at the weekend when it was failing to land a rather large sync push because every test job was failing :)

https://github.com/web-platform-tests/wpt/pull/33277 is the fixes I made to unblock the sync. The revert to `Thread.ident` was for Python 3.6 compat, and the change to use `mp.Queue` was to avoid the hang. I think we should consider producing instruments data whenever we run infrastructure tests. That would have caught the Py 3.6 issue, but probably not the hang, which I think also required running with > 1 process at a time.

I totally agree that we should have more people familiar with the code and I didn't mean to imply that it should have been blocked on my review or anything (honestly I might well have missed the issues anyway). I think process wise the only problem here is that when I initially landed the instumentation patches I assumed that they would only really be used for Gecko so it was OK to just test them in Gecko's CI.

**Pull request merged**
