### PR TITLE
Auto-update the console IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by lukebjerring** [comment]
Note that the tests just fail - blocked by https://github.com/web-platform-tests/wpt/issues/11766 (no `namespace` support)

**Comment by domfarolino** [comment]
I believe an issue tracking the lack of namdspace support can be found https://github.com/web-platform-tests/wpt/issues/7583 but haven’t looked closely enough to determine if #11766 is definitely a dupe (on mobile right now).

**Comment by lukebjerring** [comment]
@domfarolino you are indeed correct, it's a dupe, and I've flagged it as such, ty.

**Comment by domfarolino** [comment]
Thanks for digging into https://github.com/web-platform-tests/wpt/issues/7583, much appreciated.

**Comment by lukebjerring** [comment]
This is ready for a review now. Note that the pass rate on Chrome is only 3/20; most of the namespace's methods are returning an incorrect value for `.length`.

**Review by domfarolino — APPROVED** [review]
Thanks for taking this on. LGTM

**Pull request merged**
