### PR TITLE
Merge infrastructure/ into assumptions/

### PR DESCRIPTION
**Pull request by foolip**
These are boths sets of tests validating the test running
infrastructure itself.

### CODE REVIEW

**Comment by foolip** [comment]
@stephenmcgruer, you created one of these tests, does the merge make sense to you?

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-09-09 19:30:55
Finished: 2017-09-09 19:40:34


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

<li>firefox:nightly</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18345)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/273685895)

**Comment by gsnedders** [comment]
Theoretically there's a distinction: infrastructure is things that check the test runner works correctly, assumptions is UA behaviour. I don't know whether it's that meaningful or worthwhile, however.

**Comment by foolip** [comment]
@gsnedders, so, this split was intentional, and not just an accident / lack of coordination? If so, I'll go ahead and close this. A README.md in each file would be good, could you do that?

**Comment by gsnedders** [comment]
It was deliberate. I'm open to discussion as to whether it actually makes any sense. There's definitely an argument that it doesn't. :)

**Comment by jgraham** [comment]
What about a single top level directory, with multiple subdirectories? It would avoid needless polluting of the namespace and make it simpler to identify tests for things other than specs.

**Comment by foolip** [comment]
That would WFM, but which directory should subsume the other?

I also notice that some things in assumptions/ are actually covered by some spec, like initial-color.html I presume. That makes it more like a smoke test of sorts.

And assumptions/ahem.html is in part infrastructure given https://github.com/w3c/web-platform-tests/pull/7227

**Comment by gsnedders** [comment]
Let's just put it all in `infrastructure`, and have an `assumptions` directory in there.

**Comment by gsnedders** [comment]
And document `assumptions` as testing http://web-platform-tests.org/writing-tests/assumptions.html

**Comment by foolip** [comment]
@gsnedders, since it'll involve writing 2+ words of documentation, can you do that? I'll close this PR.

**Pull request closed without merging**
