### PR TITLE
Get the CSS 3 Selectors testsuite included

### PR DESCRIPTION
**Pull request by gsnedders**
**see https://github.com/w3c/web-platform-tests/pull/5302#issuecomment-338514009**

### CODE REVIEW

**Comment by gsnedders** [comment]
This is failing CI because Travis doesn't have the `XML::Parser` Perl module.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217222307)

# Firefox (nightly channel) #
Testing web-platform-tests at revision edde4462f14e6f2fdc5645f003b9853890f71b87
Using browser at version BuildID 20170331102157; SourceStamp 8df9fabf2587b7020889755acb9e75b664fe13cf
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217222308)

# Chrome (unstable channel) #
Testing web-platform-tests at revision edde4462f14e6f2fdc5645f003b9853890f71b87
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5302/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226078005)

# Lint #

Passed

**Comment by foolip** [comment]
@gsnedders, is this still relevant?

**Comment by gsnedders** [comment]
@foolip Yes. We should still make it possible to run the CSS 3 Selectors testsuite. I wonder if we should just get rid of the unbuilt files and the build system here? Probably. And we should probably convert them to reftests as part of this too.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19783)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/291272183)

**Comment by gsnedders** [comment]
OK, this has totally redone the PR, and this now gets rid of the build system entirely, replacing all the tests with their built counterparts. It also adds references for 35% of the testsuite (using ~20 refs; we need 143 to cover the rest!).

To review, I suggest taking the first and last commits on trust (which move hundreds of files), and reviewing the intermediate commits (which do nice small atomic changes).

IMO this should now land.

**Comment by gsnedders** [comment]
After this, there's only files which require individual refs and the following pairs of files which could share a ref:

```
css3-modsel-100.xml css3-modsel-100b.xml
css3-modsel-104.xml css3-modsel-104b.xml
css3-modsel-107.xml css3-modsel-107b.xml
css3-modsel-111.xml css3-modsel-111b.xml
css3-modsel-113.xml css3-modsel-113b.xml
css3-modsel-114.xml css3-modsel-114b.xml
css3-modsel-124.xml css3-modsel-124b.xml
css3-modsel-130.xml css3-modsel-130b.xml
css3-modsel-131.xml css3-modsel-131b.xml
css3-modsel-132.xml css3-modsel-132b.xml
css3-modsel-133.xml css3-modsel-133b.xml
css3-modsel-137.xml css3-modsel-137b.xml
css3-modsel-138.xml css3-modsel-138b.xml
css3-modsel-139.xml css3-modsel-139b.xml
css3-modsel-140.xml css3-modsel-140b.xml
css3-modsel-145a.xml css3-modsel-145b.xml
css3-modsel-146a.xml css3-modsel-146b.xml
css3-modsel-147a.xml css3-modsel-147b.xml
css3-modsel-14c.xml css3-modsel-14e.xml
css3-modsel-150.xml css3-modsel-153.xml
css3-modsel-166.xml css3-modsel-166a.xml
css3-modsel-167.xml css3-modsel-167a.xml
css3-modsel-174a.xml css3-modsel-174b.xml
css3-modsel-21b.xml css3-modsel-66b.xml
css3-modsel-23.xml css3-modsel-69.xml
css3-modsel-24.xml css3-modsel-68.xml
css3-modsel-39.xml css3-modsel-39b.xml
css3-modsel-39a.xml css3-modsel-39c.xml
css3-modsel-4.xml css3-modsel-83.xml
css3-modsel-41.xml css3-modsel-41a.xml
css3-modsel-42.xml css3-modsel-42a.xml
css3-modsel-46.xml css3-modsel-46b.xml
css3-modsel-52.xml css3-modsel-53.xml
css3-modsel-57.xml css3-modsel-57b.xml
css3-modsel-72.xml css3-modsel-72b.xml
css3-modsel-73.xml css3-modsel-73b.xml
css3-modsel-74.xml css3-modsel-74b.xml
css3-modsel-75.xml css3-modsel-75b.xml
css3-modsel-76.xml css3-modsel-76b.xml
css3-modsel-77.xml css3-modsel-77b.xml
css3-modsel-78.xml css3-modsel-78b.xml
css3-modsel-81.xml css3-modsel-81b.xml
css3-modsel-82.xml css3-modsel-82b.xml
css3-modsel-86.xml css3-modsel-89.xml
css3-modsel-88.xml css3-modsel-88b.xml
css3-modsel-91.xml css3-modsel-92.xml
css3-modsel-96.xml css3-modsel-96b.xml
css3-modsel-97.xml css3-modsel-97b.xml
```

**Comment by svgeesus** [comment]
@gsnedders I see two conflicts,  
css/.gitignore
update-built-tests.sh 
can that be fixed?

I agree it would be good to have the built tests in WPT so they can be run automatically. I don't see how that affects the built tests though, for manual runs.

**Review by svgeesus — APPROVED** [review]
Checking in the built tests looks like a fine thing to do, to me. It means the tests can be automatically run without depending on the build system.

**Pull request merged**
