### PR TITLE
Link header preload on a subresource triggers a preload

### PR DESCRIPTION
**Pull request by yoavweiss**
This adds a test to make sure preloads on subresources are triggered as they should.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17551)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265935223)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 11:48:09
Finished: 2017-08-18 11:58:12



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17551)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265935223)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 11:48:09
Finished: 2017-08-18 11:58:12



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17551)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265935223)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-18 11:48:09
Finished: 2017-08-18 11:58:12



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17551)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265935223)

**Review by igrigorik — APPROVED** [review]
👍

**Pull request merged**
