### PR TITLE
Properly expect a syntax error with :scope selectors in Element.closest

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by Ms2ger** [comment]
Code reviewed upstream.

**Comment by ayg** [comment]
@Ms2ger @nox I don't understand how this follows the spec.  The spec says to throw a syntax error only if the selector doesn't parse, and it seems like this selector does parse?  I don't know how :scope works, so perhaps it should return null, but I don't see how it can throw.  Firefox and Chrome fail the first three of these four tests, although Edge passes.

**Comment by Ms2ger** [comment]
https://github.com/servo/servo/pull/14080

CC @SimonSapin

**Comment by ayg** [comment]
Oh, it was Servo, that's why I couldn't find it.  I assumed Gecko.

That PR refers to w3c/csswg-drafts@9b7faa3, which removes :scope from some version of the spec.  It seems to be in the current version: https://drafts.csswg.org/selectors-4/#the-scope-pseudo  So is it still a parse error?  Firefox and Chrome both support it in practice, and I don't see why it should be considered non-conforming just because it was dropped from some particular version of a standard for procedural reasons (I assume to get to REC).

**Comment by ayg** [comment]
@Ms2ger @SimonSapin Ping?  Should I submit a PR to revert this?

**Comment by Ms2ger** [comment]
I don't have an opinion, I just upstreamed the patch.

**Comment by nox** [comment]
> @Ms2ger @nox I don't understand how this follows the spec. The spec says to throw a syntax error only if the selector doesn't parse, and it seems like this selector does parse? I don't know how :scope works, so perhaps it should return null, but I don't see how it can throw. Firefox and Chrome fail the first three of these four tests, although Edge passes.

I remember absolutely nothing about this, sorry.

**Pull request merged**
