### PR TITLE
Enable WebDriver executor by default for Chrome

### LINKED ISSUE #13225: Re-enable ExecutorWebDriver in Chrome
#13200 enabled it, but this was reverted in #13220.

See [wpt-chrome-dev-testharness-5](https://tools.taskcluster.net/groups/HuC12DhIShShqh7UcovreA/tasks/J9HbAmKwQSuyfn-3f-TEmw/runs/0/logs/public%2Flogs%2Flive.log) and [wpt-chrome-dev-testharness-6](https://tools.taskcluster.net/groups/HuC12DhIShShqh7UcovreA/tasks/Pn2YWHFYRuWDpl3y1bWEAA/runs/0/logs/public%2Flogs%2Flive.log) logs both of which contain a fair number of tracebacks.

https://staging.wpt.fyi/results/?product=chrome@1e7408fcd3&product=chrome@9bc71d422a&diff=true shows a lot of tests vanishing due to these tracebacks. This suggests there is at least one of the following bugs here:

 * We aren't exiting with non-zero when we fail to run all the tests in the job (because, e.g., of #13073)
 * We aren't setting results to ERROR/CRASH in some cases

@jgraham pointed out that in many implementations when the content process crashes the WebDriver "execute script" command just returns `null`, and this is indistinguishable from `wd.execute_script("return null")`.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #13225.

Note this doesn't deal with all the exceptions we got last time, notably it doesn't solve #13276, but that's a generic error-case cleanup failure I believe.

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Alright, let's merge and compare before/after results from Taskcluster.

**Comment by gsnedders** [comment]
Let's just go ahead and try this again.

**Comment by foolip** [comment]
Good, we have results for the immediately preceding commit:
https://wpt.fyi/results/?sha=f95086e8eb

When https://tools.taskcluster.net/groups/EIuVf04JSsOCsg2xd7ufaQ is done, hopefully results are identical :)

**Comment by foolip** [comment]
@gsnedders can you list each test with changes and why those changes are probably OK?

https://staging.wpt.fyi/results/storage/storagemanager-persisted.https.any.html?product=chrome@f95086e8eb&product=chrome@caf4aa367e&diff=true is a change that seems a bit worrying, but I didn't check them all.

**Comment by gsnedders** [comment]
> @gsnedders can you list each test with changes and why those changes are probably OK?

It's almost entirely flake, if you compare against more recent builds (e.g., https://staging.wpt.fyi/results/?product=chrome@f95086e8eb&product=chrome@aab176b97b&diff=true).

> 
> https://staging.wpt.fyi/results/storage/storagemanager-persisted.https.any.html?product=chrome@f95086e8eb&product=chrome@caf4aa367e&diff=true is a change that seems a bit worrying, but I didn't check them all.

That's just flake (it goes back to passing in later builds).

**Comment by foolip** [comment]
I see at least two directories where the number doesn't change. Can you look into those?

**Comment by gsnedders** [comment]
* WebCryptoAPI/: this is some `testharness.js` tests running to completion but returning fewer results, and it seems very unlikely to be executor related
* offscreen-canvas/: this has some more tests that run to completion than before; I don't know why they've started completing now.
* web-animations/: this is just timing related in the test.
* service-workers: again, tests running to completion rather than ERRORing.

Anything else?

**Comment by foolip** [comment]
The only other I can see is https://staging.wpt.fyi/results/paint-timing/first-image-child.html?product=chrome@f95086e8eb&product=chrome@aab176b97b&diff=true which is now timing out, but that wasn't in the original diff so probably also flaky.

Looks like we should be good, then!

@jugglinmike, please shout if this causes trouble for Buildbot results collection.

**Pull request merged**
