### PR TITLE
[Taskcluster] unpin Chrome Dev version

### LINKED ISSUE #19367: Upgrade to Chrome Dev 79 (pinned to 78)
[Postmortem: Chrome Dev 78→79 broke PR and master runs](https://github.com/web-platform-tests/wpt/issues/19362) tracks breakage triggered by the Chrome Dev version bumping from 78 to 79.

https://github.com/web-platform-tests/wpt/pull/19360 pinned the version to 78, and this issue tracks getting it unpinned again.

@JohnChen0

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Was pinned to 78.0.3904.17 in #19360.

Fixes #19367

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
With any luck, this should work (not tested locally, just throwing it up for the bots).

**Comment by stephenmcgruer** [comment]
Ok. Good news, it doesn't hang and timeout. Bad news, it fails three tests in infrastructure/...

```
Unexpected Results
------------------
/infrastructure/server/context.any.serviceworker.html
  FAIL context - Unhandled rejection: Failed to register a ServiceWorker for scope ('https://web-platform.test:8443/infrastructure/server/does/not/exist') with script ('https://web-platform.test:8443/infrastructure/server/context.any.worker.js'): An SSL certificate error occurred when fetching the script.
/infrastructure/server/secure-context.https.any.serviceworker.html
  FAIL secure-context - Unhandled rejection: Failed to register a ServiceWorker for scope ('https://web-platform.test:8443/infrastructure/server/does/not/exist') with script ('https://web-platform.test:8443/infrastructure/server/secure-context.https.any.worker.js'): An SSL certificate error occurred when fetching the script.
/infrastructure/server/secure-context.https.any.sharedworker.html
  FAIL secure-context - Uncaught 
Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://web-platform.test:8443/infrastructure/server/secure-context.https.any.js' failed to load.
    at https://web-platform.test:8443/infrastructure/server/secure-context.https.any.worker.js:8:1
```

**Comment by foolip** [comment]
Looks like a real SSL cert might now be needed? Another round of bisect? :{

**Comment by stephenmcgruer** [comment]
Do we not pass `--ignore-certificate-errors` if we're using fake certs? (Or not certs?). I'm not familiar with the history here.

We may not be able to bisect because the Chrome versions before that shared memory patch were added don't work. I would have to personally patch it in + build them, and that is *very* slow (would take multiple days to do a bisect that way).

**Comment by Hexcles** [comment]
> Do we not pass --ignore-certificate-errors if we're using fake certs? (Or not certs?). I'm not familiar with the history here.

We used to, but switched to a WebDriver capability instead: #19402 , which *should* be equivalent to that CLI flag. If not, then this is a ChromeDriver bug.

**Comment by Hexcles** [comment]
Actually, maybe try rebasing first just in case?

**Comment by stephenmcgruer** [comment]
@Hexcles ^ looks like it still failed after rebase :(

**Comment by Hexcles** [comment]
cc @JohnChen0 is `"acceptInsecureCerts": True` not equivalent to `--ignore-certificate-errors`, especially when it comes to service workers?

**Comment by stephenmcgruer** [comment]
This is not a guarantee, but https://cs.chromium.org/chromium/src/content/browser/service_worker/service_worker_loader_helpers.cc?l=40&rcl=9bc823dd43b88ae5d036aa8ad9670c1b4b6f5137 appears to be where the error comes from. 

Next step (unless John knows something) is likely to add webdriver and Chromium logging into this CL

**Comment by JohnChen0** [comment]
> cc @JohnChen0 is `"acceptInsecureCerts": True` not equivalent to `--ignore-certificate-errors`, especially when it comes to service workers?

`acceptInsecureCerts` is implemented by calling DevTools `Security.setIgnoreCertificateErrors` command. The effects were expected to be the same, but I think the problem might be `--ignore-certificate-errors` is global, while `Security.setIgnoreCertificateErrors` is only effective on browsing contexts that ChromeDriver is aware of. That might explain the difference for service worker.

**Comment by Hexcles** [comment]
That sound plausible. I've sent #20006.

**Comment by stephenmcgruer** [comment]
Rebased version passed. When we land this, we should monitor taskcluster runs afterwards to check for issues.

**Review by foolip — APPROVED** [review]
LGTM to land when you're able to monitor the outcome.

**Pull request merged**
