### PR TITLE
Test Web Neural Network API by WebNN-polyfill

### PR DESCRIPTION
**Pull request by BruceDai**
According to [the previous comment](https://github.com/web-platform-tests/wpt/pull/31201#discussion_r752915202) by @dontcallmedom on https://github.com/web-platform-tests/wpt/pull/31201, 

 > We could also have a separate open PR with just the polyfill added which would allow us to use WPT.fyi to collect results once the polyfill is added.

I added this pr of testing Web Neural Network API by WebNN-polyfill.

@dontcallmedom @Honry PTAL, thanks.

### CODE REVIEW

**Comment by dontcallmedom** [comment]
@web-platform-tests/admins help? I'm not clear why the jobs are failing

**Comment by jgraham** [comment]
The failure is https://github.com/web-platform-tests/wpt/pull/31771/checks?check_run_id=4350229430

**Comment by jgraham** [comment]
But as a general comment, adding a polyfill like this to test something seems highly unusual, since it's not helping implementors (except the polyfill implementors) and gives a misleading impression of the status of browser implementations. Also using scripts outside wpt isn't allowed (Firefox is configured to crash in CI for this case, as you can see at https://wpt.fyi/results/webnn/idlharness.https.any.html?diff&filter=ADC&run_id=5729986758574080&run_id=5705420837486592 ).

If you want to include the behaviour of a polyfill in wpt.fyi results I think we need a broader discussion about how to achieve that.

**Comment by BruceDai** [comment]
Thanks for your feedbacks. Close it.

**Pull request closed without merging**
