### PR TITLE
Delete invalid test.

### PR DESCRIPTION
**Pull request by emilio**
It seems it expects `transform: rotate(1deg, 20px, 20px)` to somehow be valid.

It was introduced in cdc3032f56c86cc68121e54e169485441d9cdb1a, pointing to https://www.w3.org/TR/css-transforms-1/#svg-transform-functions, which doesn't say anything like that.

Doesn't pass in any browser.

### CODE REVIEW

**Comment by emilio** [comment]
https://wpt.fyi/results/css/css-transforms/external-styles/svg-external-styles-012.html

**Comment by dbaron** [comment]
Seems like you should also delete both occurrences of:

```css
.rotate-3-args {
    transform: rotate(90deg,20px,20px);
}
```

from `css/css-transforms/external-styles/support/svg-external-styles.css`.

**Comment by emilio** [comment]
Good point, done.

**Review by dbaron — APPROVED** [review]

**Comment by dbaron** [comment]
For what it's worth, the syntax might come from the [SVG transform attribute](https://www.w3.org/TR/SVG11/coords.html#TransformAttribute) as specified in SVG 1.1.

**Pull request merged**
