### PR TITLE
Run pywebsocket unittests in CI

### PR DESCRIPTION
**Pull request by svillar**

### CODE REVIEW

**Comment by svillar** [comment]
Not totally sure about this though, my experience with WPT CI is pretty limitted. I checked test.yml and ci_tools_unittest.sh and they seem to point to this direction but shrug.

**Comment by jgraham** [comment]
It seems like the tests run and then fail and then hang:

```
pywebsocket/test/test_dispatch.py ................                       [ 52%]
pywebsocket/test/test_endtoend.py F....FFFFF
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

**Review by jgraham — CHANGES_REQUESTED** [review]
(Need to get the tests actually passing)

**Comment by stephenmcgruer** [comment]
Locally, if I remove `test_endtoend.py` and run the tests I get one error in `test_parse_invalid_uri.py` (`test_parse_invalid_uri`) and the rest pass.

`test_endtoend.py` looks like a fairly complex integration test, so we could likely drop that to start and look into it for later.

**Comment by stephenmcgruer** [comment]
Now that we've integrated pywebsocket3, this can probably be closed. Might be interesting to run the unittests at some point just to see, but they're no longer helping us migrate to Py3 so priority would be very low :)

**Comment by jgraham** [comment]
OK.

**Pull request closed without merging**
