### PR TITLE
Add PNG cICP chunk test

### PR DESCRIPTION
**Pull request by ProgramMax**
The PNG spec Third Edition adds a new cICP chunk which allows succinct storage of the image's color space.

This commit adds a PNG image which contains this cICP chunk as well as a test to verify it is read correctly.

### CODE REVIEW

**Comment by ProgramMax** [comment]
I am struggling to test this locally at the moment. I'm going to try to fix this.
Chromium-based browsers should pass, as they already support the cICP chunk.

**Comment by ProgramMax** [comment]
I am now able to test and it passes on Chromium-based browsers as expected.
However, it also passes on Firefox, which I believe doesn't yet support the cICP chunk. So there is something wrong with the test. I'll look into it.

**Review by svgeesus — COMMENTED** [review]
Verifying that color(display-p3 0.196078 0.39215686 0.58823529) = color(display-p3 0.196078 0.39215686 0.58823529) which in 0..255 notation is 26.12, 101.48, 154.25 which rounds to integer values 26, 101, 154.

https://colorjs.io/apps/convert/?color=color(display-p3%200.196078%200.39215686%200.58823529)&precision=6

**Review by svgeesus — COMMENTED** [review]
cicp.png is not valid according to pngcheck but seems OK:

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/CICP$ pngcheck -f -vv cicp.png
File: cicp.png (168 bytes)
  chunk IHDR at offset 0x0000c, length 13
    100 x 50 image, 24-bit RGB, non-interlaced
  chunk cICP at offset 0x00025, length 4:  illegal (unless recently approved) unknown, public chunk
  chunk IDAT at offset 0x00035, length 95
    zlib: deflated, 16K window, maximum compression
  chunk IEND at offset 0x000a0, length 0
ERRORS DETECTED in cicp.png
```

**Comment by svgeesus** [comment]
Small point but using increments of 51 rather than 50 can work better because 0.2 * 255 = 51 exactly so you would get 0.2, 0.4, 0.6 before conversion to sRGB.

**Review by svgeesus — COMMENTED** [review]
I believe that support files such as images are supposed to be in a 'support' directory. But perhaps 'images' works the same way?

**Comment by ProgramMax** [comment]
I found and fixed the bug in my test.
But when I test locally, it fails on Chrome when it shouldn't. Chrome seems to be ignoring the cICP chunk. I'll investigate.

I saw a bunch of test images in the images/ directory so I went with that. Happy to move it if we want.

I do think a different increment than 50 would be better, since I'm comparing 100 to 101 with an epsilon of 2. I'll get back to this thought.

**Comment by ProgramMax** [comment]
I found the problem. I was calling getImageData() with colorSpace: display-p3. This preserved the values (50, 100, 150) as those are the correct values in Display P3.

If I call getImageData() with colorSpace: srgb then the conversion happens as expected, resulting in pixel values (26, 101, 154).

The test is now working correctly (passing on Chrome and failing on Firefox, as expected).

**Comment by ProgramMax** [comment]
I have updated the image to use increments of 51 instead of 50 as @svgeesus suggested.

I do not see a 'support' directory to satisfy that request. But note that the apng/ directory has its images in the images/ directory. So this mimics the apng/ tests. Perhaps it is okay?

**Review by svgeesus — APPROVED** [review]
This now looks good to me.

**Pull request merged**
