### PR TITLE
[css-text] 2 new word-spacing tests and 1 reference

### PR DESCRIPTION
**Pull request by TalbotG**
Added:
 
css/css-text/word-spacing/word-spacing-negative-value-001.html 
css/css-text/word-spacing/support/swatch-blue.png
css/css-text/word-spacing/support/swatch-orange.png 
css/css-text/word-spacing/reference/ref-filled-green-100px-square.xht 

Removed:
css/css-text/word-spacing/word-spacing-computed-001.html

[Update]
**Re-added (see below; with 012f8b0 commit)**
css/css-text/word-spacing/word-spacing-computed-001.html
[/Update]

[Update]
**Removed (see below; with aab7f47 commit)**
css/css-text/word-spacing/word-spacing-inherited-value-001.html
and
css/css-text/word-spacing/reference/word-spacing-inherited-value-001-ref.html
[/Update]
The tests and references on my website are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/word-spacing/word-spacing-computed-001.html
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/word-spacing/word-spacing-inherited-value-001.html
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/word-spacing/word-spacing-negative-value-001.html
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/word-spacing/reference/ref-filled-green-100px-square.xht
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/word-spacing/reference/word-spacing-inherited-value-001-ref.html

### CODE REVIEW

**Comment by TalbotG** [comment]
In word-spacing-computed-001.html

line 13:  <script src="../resources/testharness.js"></script>

line 15:  <script src="../resources/testharnessreport.js"></script>

most likely should have been instead

line 13:  <script src="/resources/testharness.js"></script>

line 15:  <script src="/resources/testharnessreport.js"></script>

**Review by fantasai — CHANGES_REQUESTED** [review]
It seems like the first test in the testharness series should be serializing to `0px` rather than `0`. I believe this is what CSSOM says in https://drafts.csswg.org/cssom/#ref-for-length-value and it seems to be what Chrome and Firefox are doing.

The second test for inheritance should be incorporated as a testharness test, there's no need for it to be a rendering test.

The third test for negative values is necessarily a reftest because we need to test whether the UA can render negative numbers, so that's good. (I would consider simplifying the code a bit by giving the divs a fixed width and a red background rather than a separate positioned red square, though.)

**Comment by TalbotG** [comment]
> test for inheritance should be incorporated as a testharness test

This will require me more time as I have not tested inheritance as a testharness test before...

**Comment by TalbotG** [comment]
`word-spacing` initial value and `word-spacing` inheritance are
already being tested thoroughly in this testharness test

http://wpt.live/css/css-text/inheritance.html

therefore, I am removing 
css/css-text/word-spacing/word-spacing-inherited-value-001.html
and
css/css-text/word-spacing/reference/word-spacing-inherited-value-001-ref.html
from this PR.

**Comment by TalbotG** [comment]
Note to me:

line 11: meta content="This test checks that the computed value of 'normal' for the property word-spacing is zero. 
should be
line 11:  meta content="This test checks that the computed value of 'normal' for the property word-spacing is **'0px'**.

**Review by fantasai — APPROVED** [review]

**Pull request merged**
