### PR TITLE
[presentation-api] Fix a broken href in the receiver's IDL harness

### PR DESCRIPTION
**Pull request by tomoyukilabs**
This PR fixes a wrong `href` attribute in `receiving-ua/idlharness-manual.https.html`.

In addition, I have found that only `idlharness_receiving-ua.https.html` has `.https` in the `receiving-ua/support` directory. This PR renames the other `*.html` files in the same directory, as well. I still wonder whether `.https` should be added in all files in `receiving-ua/support` or `.https` should be removed from `idlharness_receiving-ua.https.html`, though.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218363698)

# Firefox (nightly channel) #
Testing web-platform-tests at revision f6e1b04949644c7e5bd3540093ce84e91433ee81
Using browser at version BuildID 20170403100136; SourceStamp 38894655c89e68bcd8f45d31a0d3005f2c2b53db
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218363699)

# Chrome (unstable channel) #
Testing web-platform-tests at revision f6e1b04949644c7e5bd3540093ce84e91433ee81
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
No tests run.

**Comment by tidoust** [comment]
Hmm, good point, @tomoyukilabs. I think I would actually drop the `.https` from files in `receiving-ua/support`, which would also have the benefit of being consistent with files in `controlling-ua/support`.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5335/)

**Comment by tomoyukilabs** [comment]
Okay, I have updated this PR so that `.https` is removed from files in `receiving-ua/support`.

**Review by tidoust — APPROVED** [review]
LGTM!

**Comment by tidoust** [comment]
As far as I can tell, this is good to merge, but I do not know how to understand Travis failure (which seems unrelated, but perhaps it's not?). I'll defer to @w3c/web-platform-testing-and-tools-admins

**Comment by tomoyukilabs** [comment]
@tidoust Thanks! I wish the failure were unrelated.

**Pull request merged**
