### PR TITLE
(Cleanup) these are decoder tests, not user agent tests

### PR DESCRIPTION
**Pull request by svgeesus**
Erroneously committed to the UA tests, these are actually decoder tests and should not be in this test suite.
Upstream review by WebFonts WG

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232617925)

# Firefox (nightly) #
Testing web-platform-tests at revision 6c70b6846a563fec45e6bb81204e4255f59e17c3
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232617926)

# Sauce (safari) #
Testing web-platform-tests at revision 6c70b6846a563fec45e6bb81204e4255f59e17c3
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232617927)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 6c70b6846a563fec45e6bb81204e4255f59e17c3
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232617933)

# Chrome (unstable) #
Testing web-platform-tests at revision 6c70b6846a563fec45e6bb81204e4255f59e17c3
Using browser at version 60.0.3095.5 dev
Starting 10 test iterations
No tests run.

**Review by khaledhosny — COMMENTED** [review]
I think you should remove the `valid-009.woff2` font file as well since it is no longer needed.

**Review by rsheeter — APPROVED** [review]
As @khaledhosny  noted, you might want to remove css/WOFF2/support/valid-009.woff2 as well?

**Comment by svgeesus** [comment]
Thanks @rsheeter @khaledhosny removed that font too

**Review by khaledhosny — APPROVED** [review]

**Pull request merged**
