### PR TITLE
CSSOM: make deleteMedium exception explicit and remove two redundant tests

### PR DESCRIPTION
**Pull request by annevk**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5399)

### CODE REVIEW

**Comment by annevk** [comment]
Forgot to mention that this helps with #5317.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5399/)

**Comment by rune-opera** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5399)*

**Comment by annevk** [comment]
@rune-opera sorry, the Reviewable UI is not entirely clear to me. Does this mean you've reviewed this change?

**Comment by rune-opera** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5399#-:-Kh1U4uL_2qyWwwx6AmB:bnfp4nl)*

**Pull request merged**
