### PR TITLE
[custom-elements] Add HTML serialization tests

### PR DESCRIPTION
**Pull request by tkent-google**
This is for https://github.com/whatwg/html/pull/3444

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24305)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/341223169)

**Review by domenic — APPROVED** [review]
Perfect, these were exactly the cases I had in mind to test!

**Comment by snuggs** [comment]
@domenic @tkent-google one of our contributors to our CE project [bought to my attention](https://github.com/devpunks/snuggsi/issues/167):
 
> Webkit safari devs stated that they would never implement is. So why bother with it [`is`]?
[stats](https://gs.statcounter.com/browser-market-share) show that almost 20% of users use Safari, either desktop or mobile. - @GeorgeTailor

I've always been under the assumption if a test lands in `web-platform-tests` that the onus is now on the vendors to implement. Or is the convention more so "It behooves the vendor to implement _(but they don't necessarily have to)_"?

Thanks in advance for taking time out of your day to answer this. :pray:

**Comment by snuggs** [comment]
NVM. Was pointed _(back)_ to this conversation. https://github.com/w3c/webcomponents/issues/509#issuecomment-224212371

Thanks!

**Pull request merged**
