### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=181491

### PR DESCRIPTION
**Pull request by youennf**
Redirected iframe loading with Request.redirect=follow should fail

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22613)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/327417605)

**Comment by foolip** [comment]
@youennf, are you merging these yourself once in a while? Would you like a label and to have @wpt-pr-bot auto-approve as in https://github.com/w3c/web-platform-tests/pull/8985?

**Comment by youennf** [comment]
> @youennf, are you merging these yourself once in a while? Would you like a label and to have @wpt-pr-bot auto-approve as in #8985?

Currently I need a WPT reviewer for each change :(
It would be great to have a label that would be set once changes are r+ed and finalized in bugs.webkit.org, triggering wpt-pr-bot to automerge.

**Comment by foolip** [comment]
@youennfa I've added  the label webkit-export label and used the purple color from https://webkit.org/blog/, is that OK?

@Hexcles, do you have the details of how the chromium-export label is added, and how that relates to @wpt-pr-bot *not* adding OWNERS and instead approving?

**Comment by Hexcles** [comment]
The tag is for our own convenience. The PR bot looks at authors of the PRs: https://github.com/tobie/ganesh/blob/53cf6554ec2b58ac9bbf6a6cdd57220924f6428c/lib/metadata/index.js#L84

So you can create a webkit-export-bot account and add the username there (or do something similar to jgraham's 'MozReview-Commit-ID' matching).

**Comment by foolip** [comment]
> The tag is for our own convenience.

Oops. @youennf, I can delete the webkit-export label again if you don't want it.

**Comment by youennf** [comment]
webkit-export label is fine. I'll update the script to tag PR accordingly.

As we discussed privately a few weeks ago, WebKit authored PRs will probably be authored by individual WebKittens for the moment.
Changing a bit the WPT infra to auto-merge in some ways might be fine. 
I was considering the possibility to use labels for that.

**Comment by Hexcles** [comment]
Well, wpt-pr-bot could be modified to look at labels, easily. However, that's insecure as many people can randomly add labels.

I'm not sure what ACL model would work best if there will be multiple (and indefinite) users doing webkit export.

**Comment by foolip** [comment]
@youennf, would be acceptable to enumerate a list of webkittens who together with the webkit-export label get auto-review?

**Comment by youennf** [comment]
> cceptable to enumerate a list of webkittens who together with the webkit-export label get auto-review?

That seems reasonable, the list should be fairly small at this early stage.
I hope we will be able to beef-up WebKit infrastructure though.

**Comment by foolip** [comment]
@youennf, a PR for a change around https://github.com/tobie/ganesh/blob/53cf6554ec2b58ac9bbf6a6cdd57220924f6428c/lib/metadata/index.js#L84 should do the trick then. Please CC me there, I'm interested to see this happen :)

**Comment by youennf** [comment]
> @youennf, a PR for a change around https://github.com/tobie/ganesh/blob/53cf6554ec2b58ac9bbf6a6cdd57220924f6428c/lib/metadata/index.js#L84 should do the trick then. Please CC me there, I'm interested to see this happen :)

Not really, the infrastructure is expecting the PR to have already been reviewed downstream.
In WebKit workflow, the PR might be created before being reviewed downstream.
It should only become mergeable without any WPT review if there is a clear statement like a "reviewed-downstream" label is added at some point, and by a trusted entity.

**Comment by youennf** [comment]
Maybe WebKit workflow could be adapted, at least until WPT infra allows supporting that case (or maybe it is already supporting this case, I am not very familiar here).
Let's start with small steps.

**Comment by foolip** [comment]
@youennf, even without a bot account, I think Chromium's and WebKit's cases are already quite similar. When you create the wpt PR before the WebKit review is done, you probably aren't looking for review from wpt contributors, right? And once the WebKit review is done, you want to merge the wpt PR as-is with reference to that review, and make any fixes separate if necessary. (Except lint changes and other things which make it impossible to land the PR.)

Is that accurate?

**Comment by youennf** [comment]
> @youennf, even without a bot account, I think Chromium's and WebKit's cases are already quite similar. When you create the wpt PR before the WebKit review is done, you probably aren't looking for review from wpt contributors, right? And once the WebKit review is done, you want to merge the wpt PR as-is with reference to that review, and make any fixes separate if necessary. (Except lint changes and other things which make it impossible to land the PR.)
> 
> Is that accurate?

That is true most of the time so we can start with that approach.

**Pull request closed without merging**
