### PR TITLE
Fetch: use `t.step_timeout()` instead of bare `step_timeout()`

### PR DESCRIPTION
**Pull request by foolip**
This avoid a harness error in the case of failure:
https://wpt.fyi/results/fetch/stale-while-revalidate?run_id=6045131320852480&run_id=4797529354928128&run_id=6524192509919232&run_id=6492651545165824

### CODE REVIEW

**Comment by foolip** [comment]
From https://github.com/web-platform-tests/wpt/pull/15047

**Comment by foolip** [comment]
Flakiness from Taskcluster logs:

## Chrome

### /fetch/stale-while-revalidate/stale-css.tentative.html ###
|            Subtest             |          Results           |                               Messages                              |
|--------------------------------|----------------------------|---------------------------------------------------------------------|
|                                | OK                         |                                                                     |
| `Cache returns stale resource` | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected "rgb(0, 128, 0)" but got "rgb(255, 0, 0)"` |

## Firefox

### /fetch/stale-while-revalidate/stale-css.tentative.html ###
|            Subtest             |            Results            |                                      Messages                                      |
|--------------------------------|-------------------------------|------------------------------------------------------------------------------------|
|                                | **OK: 9/10, TIMEOUT: 1/10**   |                                                                                    |
| `Cache returns stale resource` | **FAIL: 9/10, TIMEOUT: 1/10** | `assert_equals: expected "rgb(0, 128, 0)" but got "rgb(255, 0, 0)";Test timed out` |

The similarity suggests an issue with the test rather than Chrome or Firefox. @dtapuska I guess the test assumes that it will only be run once, because after that the thing is in cache again? Would adding a random token somewhere fix the problem?

**Review by youennf — APPROVED** [review]
I guess we should we recommend Test.step_timeout whenever feasible.

**Comment by foolip** [comment]
Yes, but it's not clear what a lint could look like, since when a bare `step_timeout` is used the callback could actually be correctly wrapped directly or indirectly, or the callback could be so trivial that it won't ever throw. At least that's what I found when grepping a bit.

@lukebjerring, what remains to make harness errors require human confirmation to land? That would have avoided this case.

**Comment by foolip** [comment]
Ignoring the flakiness as pre-existing and merging.

**Pull request merged**
