### PR TITLE
Update travis status before optional jobs are finished.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5639)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5639/)

**Comment by jugglinmike** [comment]
I've used this configuration in my own projects, but I still watched this build
just to be sure.

screenshot from 2017-04-21 14-37-47

And subsequently

screenshot from 2017-04-21 14-38-04

Looking good!

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224456073)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224456075)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d6504fd99715c0dcd2c48d33bde664d757621cf9
Using browser at version BuildID 20170420100256; SourceStamp 27311156637f9b5d4504373967e01c4241902ae7
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224456081)

# Chrome (unstable channel) #

**Comment by jugglinmike** [comment]
Thanks, @jgraham!

**Pull request merged**
