### PR TITLE
Encoding: Verify UTF-32 tests aren't parsing as (X)HTML

### PR DESCRIPTION
**Pull request by inexorabletash**
One approach for fixing https://github.com/web-platform-tests/wpt/issues/10588

This modifies the .html/.xml samples to include a data-parsed attribute on the HTML element, and probe for it. Since the files should have failed to parse as HTML/XHTML the resulting iframe documents should not contain the attribute.

### CODE REVIEW

**Comment by inexorabletash** [comment]
@annevk - please take a look? 

Not urgent, just picking off an easy item with my name on it.

I tried adding .txt samples, but in Chrome at least navigating an iframe to a .txt file triggers a download instead. The sniffing exposed in the other cases here may be implementation specific and/or just way out of scope for this directory. *shrug*

**Comment by annevk** [comment]
1. XML defaults to UTF-8, so I think that would make sense to expect here.
2. XML would result in a parse error. I'm not sure if you should be able to access the resulting document, I don't think that's defined.

For HTML this is probably okay though.

**Comment by hsivonen** [comment]
> XML defaults to UTF-8, so I think that would make sense to expect here.

Indeed. I'm curious where the notion of expecting windows-1252 for XML came from.

**Comment by inexorabletash** [comment]
In Chrome, at least, the files with `.xml` suffix are not parsing as XML/XHTML or HTML; presumably due to sniffing (I haven't traced through) they are being treated as plain text, hence the _"such content will be sniffed as plain text and interpreted in the default encoding (windows-1252)"_ comment in the file. So "expecting windows-1252 for XML" is not what the test asserts. (Suggestions for ways to make that clearer are appreciated!)

I haven't gone through [MIMESNIFF](https://mimesniff.spec.whatwg.org) to see if the sniffing is standardized. And I think implementations differ on the default encoding for text/plain.

**Comment by annevk** [comment]
Per https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource you basically never sniff resources with an XML MIME type.

**Comment by hsivonen** [comment]
Ping? Any chance we could get the XML tests fixed?

**Comment by inexorabletash** [comment]
Firefox and Chrome have differing behavior.

If the containing doc has `<meta charset=utf-8>` then both agree (everything is UTF-8 or UTF-16LE). If not, or if `<meta charset=windows-1252>` then behavior differs, and I still haven't dug into why yet.

**Comment by inexorabletash** [comment]
Okay, these pass in Firefox, and I'd call the Chrome behavior a bug (or let others have that argument). Take a peek. 

Also feel free to push changes/take over/land if you want.

**Review by annevk — APPROVED** [review]
Thanks, looks great now! I pushed two minor nits and will land this with those applied.

**Comment by inexorabletash** [comment]
Thanks! (and nit fixes lgtm too)

**Pull request merged**
