### PR TITLE
change webhook URL and add functionality for each job to post to bot

### PR DESCRIPTION
**Pull request by bobholt**
This is the PR that will switch from using prbuildbot to the wptdash app. This is dependent on @sideshowbarker completing the GitHub Token setup and updating the vault file in wptdash, but I wanted to get this in front of @jgraham as it includes new check_stability code.

This currently points to the staging server so we can make sure it works before landing. Need to change that before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6719)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 100 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719#-KqYE5Cqu5WXbS-zvjkN:-KqYE5CrJ7dZKU08pUmI:b-r4mag6) ([raw file](https://github.com/w3c/web-platform-tests/blob/7eb932f0fdd1931377e993dda537063231256134/.travis.yml#L100)):*
> ```YAML
>     on_success: never
>     on_failure: always
>   webhooks: http://pulls-staging.web-platform-tests.org/api/build
> ```

Noting that this is a thing that needs to be changed, so we have all data in Reviewable

---

*[check_stability.ini, line 10 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719#-KqYE9406hPEokeLmQZp:-KqYE9406hPEokeLmQZq:b-r4mag6) ([raw file](https://github.com/w3c/web-platform-tests/blob/7eb932f0fdd1931377e993dda537063231256134/check_stability.ini#L10)):*
> ```INI
> # cases.
> ignore_changes: resources
> results_url: http://pulls-staging.web-platform-tests.org/api/stability
> ```

Noting that this is a thing that needs to be changed, so we have all data in Reviewable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719)*

**Review by sideshowbarker — COMMENTED** [review]
LGTM but I defer to @jgraham pending resolution of his review comments

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-03 14:25:00
Finished: 2017-08-03 14:36:40


<h2>Unstable Results</h2>

**Comment by bobholt** [comment]
Almost there. Looks like I need to fix a conditional in the template.

**Comment by bobholt** [comment]
@jgraham I think this is ready to go pending the following:

1. Any further code review you'd like to do
2. Land https://github.com/w3c/wptdash/pull/11
3. Remove `-staging` from URLs and webhook

I'll do #3 after 1 and 2 because doing that will cause it to start immediately posting to the production server. You can see it populating http://pulls-staging.web-platform-tests.org/ with pulls (but no build data except for this PR) already.

The other open question is SSL. I don't think it should hold us up since there's nothing protected there. I'm working with the infrastructure people on our side to make getting and renewing that certificate free and painless for all, but probably won't have that until next week.

**Comment by bobholt** [comment]
@jgraham. I've added https://github.com/w3c/wptdash/pull/12 which for SSL support to the dashboard. Do you have any other review on this PR before I switch it to reference the production servers instead of staging?

**Comment by bobholt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 100 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719#-KqYE5Cqu5WXbS-zvjkN:-Kr5leDrSZR9vayTCxNK:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/7eb932f0fdd1931377e993dda537063231256134/.travis.yml#L100)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Noting that this is a thing that needs to be changed, so we have all data in Reviewable
</blockquote></details>

Done.

---

*[check_stability.ini, line 10 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719#-KqYE9406hPEokeLmQZp:-Kr5lfM1L1l9IPWoHVI8:b-896fix) ([raw file](https://github.com/w3c/web-platform-tests/blob/7eb932f0fdd1931377e993dda537063231256134/check_stability.ini#L10)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Noting that this is a thing that needs to be changed, so we have all data in Reviewable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6719)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
