### PR TITLE
[css-backgrounds] Added clip-text-multi-line-002 test and its reference

### PR DESCRIPTION
**Pull request by TalbotG**
This test spun from [a comment I made in Issue 30812](https://github.com/web-platform-tests/wpt/pull/30812#issuecomment-1314514987) . This test is an optimized, clearer test and it does not rely on the `fill-color` property.

At my website:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/clip-text-multi-line-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/clip-text-multi-line-002-ref.html

### CODE REVIEW

**Review by fantasai — APPROVED** [review]
Approved to replace clip-text-multi-line.html if you merge in the authorship metadata.

**Comment by TalbotG** [comment]
@litherum You were added in the authorship metadata.

**Comment by TalbotG** [comment]
> Approved to replace clip-text-multi-line.html

Regarding replacement, can you do it for me please? Thank you.

**Comment by TalbotG** [comment]
Somehow, I forgot to remove
line 38:  `</head>`

line 40: `<body>`

so I will revisit this test later...

**Comment by fantasai** [comment]
> Somehow, I forgot to remove line 38: `</head>`
> 
> line 40: `<body>`
> 
> so I will revisit this test later...

Done.

**Pull request merged**
