### PR TITLE
Add manual keyboard tests

### PR DESCRIPTION
**Pull request by garykac**
Add some basic manual keyboard tests for UIEvents.

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/uievents-reviewers.

**Comment by garykac** [comment]
ping!

**Comment by travisleithead** [comment]
All reviewed via Critic (via UI Events call). Please merge!

**Comment by garykac** [comment]
Any update on merging this?

**Comment by gsnedders** [comment]
We should totally give @travisleithead push perms so he can merge stuff. @sideshowbarker? (I have no idea what groups you're using given there are forty million.)

**Pull request merged**
