### PR TITLE
Remove CancellationError

### PR DESCRIPTION
**Pull request by tobie**
Revert https://github.com/w3c/testharness.js/commit/bf0e213dcfb5b3f12e5c3c73b692b7326fc88f47.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5733)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5733/)

**Review by annevk — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226811993)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226811995)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 446a9c292b8fd1be77160fa000f856513b218881
Ignoring 1 changed files:
No files changed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226812001)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 446a9c292b8fd1be77160fa000f856513b218881
Ignoring 1 changed files:
No files changed

**Pull request merged**
