### PR TITLE
Extend `browsingContext.navigationStarted` tests

### PR DESCRIPTION
**Pull request by sadym-chromium**
`browsingContext.navigationStarted` should not be emitted when the browsing context is create.

### CODE REVIEW

**Comment by whimboo** [comment]
@sadym-chromium while no-one from Google reviewed this PR yet let me give a quick reply.

In the [TPAC meeting](https://github.com/w3c/webdriver-bidi/issues/766#issuecomment-2379918773) we agreed on that all events should not be emitted. Are you going to file other PRs or will you immediately update this PR to cover all the scenarios?

**Comment by lutien** [comment]
@sadym-chromium, if you don't have time to finish up the PR, would it be ok with you if we introduce this update in the gecko repo? It would be easier for us to release it together with the update for the event. If you have any feedback, you can provide it on [the patch](https://phabricator.services.mozilla.com/D228641)

**Comment by sadym-chromium** [comment]
> @sadym-chromium, if you don't have time to finish up the PR, would it be ok with you if we introduce this update in the gecko repo? It would be easier for us to release it together with the update for the event. If you have any feedback, you can provide it on [the patch](https://phabricator.services.mozilla.com/D228641)

Sorry for the delay, and yes, it would be amazing, thanks!

**Comment by whimboo** [comment]
> @sadym-chromium, if you don't have time to finish up the PR, would it be ok with you if we introduce this update in the gecko repo? It would be easier for us to release it together with the update for the event. If you have any feedback, you can provide it on [the patch](https://phabricator.services.mozilla.com/D228641)

@lutien I assume this is all done now or does it still miss some more changes?

**Comment by lutien** [comment]
> @lutien I assume this is all done now or does it still miss some more changes?

It should be all done

**Pull request closed without merging**
