### PR TITLE
armenian/css3-counter-styles-008.html: Removes range

### PR DESCRIPTION
**Pull request by kriti21**
Closes https://github.com/w3c/web-platform-tests/issues/9741

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-16 19:07:42
Finished: 2018-03-16 19:13:59


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:dev</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26127)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/354465429)

**Comment by liamquin** [comment]
The CSS Working Group needs to make a decision first on whether range make sense for Armenian, or whether to remove it, or whether to change the wording of the spec. As I recall from using grep :) there are 17 files that test numbers greater than 10,000 (and possibly more in the Mozilla tests).

Also, can you confirm that without range, Mozilla is correctly counting over 10,000 in Armenian?

**Comment by liamquin** [comment]
Someone who is a native speaker of the Armenian language could tell us. Ifrah's book on the history of numbers only goes up to 9,9999, ironically enough (see pages 224 and 225). However, on further research I learned that an overline is used for values over 9,999. E.g. Wikipedia gives ՌՃԽԳՌՄԾԵ = 11431255 at https://en.wikipedia.org/wiki/Armenian_numerals and Ա = 10000, Ջ = 9000000, although the line over them isn't showing up in my browser here.

**Comment by gsnedders** [comment]
@liamquin is there an issue open for the CSS WG issue side of this?

**Comment by liamquin** [comment]
@gsnedders i'd planned to bring up issue 9741 which is against the test for range in the armenian counters, but i could file one against the spec if you think that's better. Originally i was going through marking bad tests and marked that one by mistake - the test is correct according to the spec as written - but didn't close it because i think we should change the spec, and then change or delete this test as appropriate along with about a dozen others tests.

https://github.com/w3c/web-platform-tests/issues/9741#

**Comment by gsnedders** [comment]
@liamquin odds of anyone from the CSS WG acting on a spec issue in this repo are tiny

**Pull request closed without merging**
