### PR TITLE
Lint changed files

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6663)

### CODE REVIEW

**Comment by jgraham** [comment]
This is an alternative to https://github.com/w3c/web-platform-tests/pull/6639.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259428920)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259428921)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259428927)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259428928)

# Sauce (MicrosoftEdge) #

**Review by bobholt — APPROVED** [review]
Overall, I like this approach better than the manifest. Have you perceived/measured any real time gains between the two?

**Comment by jgraham** [comment]
I think they're pretty similar performance wise. I guess this might be faster since it isn't hashing every file to check for changes, but trusting the VCS.

**Pull request merged**
