### PR TITLE
Add wpt test for service worker registration from signed exchange

### PR DESCRIPTION
**Pull request by foolip**
Bug: 939237
Change-Id: I956f1b1bc0b66f249b337b0c190c7cd5fcd96eb2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1519951
Reviewed-by: Kunihiko Sakamoto <ksakamoto@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#640558}

### CODE REVIEW

**Comment by foolip** [comment]
I had to manually export this because of a conflict in lint.whitelist. `git rebase` was able to automatically resolve it, it was trivial.

**Comment by Hexcles** [comment]
@foolip you missed the `chromium-export` label so the exporter was still complaining.

**Comment by Hexcles** [comment]
Looks like legit timeout on Firefox: https://tools.taskcluster.net/groups/WOR45FE1QpGPwh88txWQ-Q/tasks/PUWFI0c3SDOe2Q5xGA3k0g/runs/0/logs/public%2Flogs%2Flive.log#L9632

Also Firefox hasn't implemented sxg anyway, so I'm force-merging it.

**Comment by foolip** [comment]
@Hexcles thanks for merging! Taskcluster took so long I had to go home before it finished.

**Pull request merged**
