### PR TITLE
"sub" suffix should be used in where server env is defined

### PR DESCRIPTION
**Pull request by Honry**
Fix https://github.com/w3c/web-platform-tests/issues/8550

### CODE REVIEW

**Comment by Honry** [comment]
@pozdnyakov, PTAL.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21447)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/311723505)

**Review by pozdnyakov — APPROVED** [review]
lgtm, thanks!

**Comment by Honry** [comment]
Thanks @pozdnyakov, merging it.

**Pull request merged**
