### PR TITLE
Submit tests for ParentNode.{query,queryAll}.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by cvrebert** [comment]
This PR has merge conflicts.

**Comment by cvrebert** [comment]
@Ms2ger Looks like this needs to be updated to account for 8fde4abf3bd3e7f224f52c94368a82d7364e075f

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/1562/)

**Comment by annevk** [comment]
I rebased this. @cvrebert still interested in reviewing?

**Comment by ayg** [comment]
These no longer exist, right?

**Comment by gsnedders** [comment]
@ayg https://dom.spec.whatwg.org/#interface-parentnode defines them, no?

**Comment by ayg** [comment]
It defines `querySelector()` and `querySelectorAll()`, not `query()` or `queryAll()`.  Those are gone for now, as of whatwg/dom@10b6cf1b.

**Comment by annevk** [comment]
Indeed.

**Pull request closed without merging**
