### PR TITLE
CORS: Access-Control-Expose-Headers and invalid values

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
Bugs filed:

* https://bugs.webkit.org/show_bug.cgi?id=172357
* https://bugs.chromium.org/p/chromium/issues/detail?id=724452
* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12071551/

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233983206)

# Firefox (nightly) #
Testing web-platform-tests at revision ae56a2cf2fa9381a5256f9897427ee85b12c96c9
Using browser at version BuildID 20170518100156; SourceStamp baf05f61bc14fdf45511bc1165ce76daa08c5c0f
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6000/cors/access-control-expose-headers-parsing.window.html">/cors/access-control-expose-headers-parsing.window.html</a></summary>


|                   Subtest                   | Results | Messages |
|---------------------------------------------|---------|----------|
|                                             | OK      |          |
| `Access-Control-Expose-Headers parsing: #1` | PASS    |          |
| `Access-Control-Expose-Headers parsing: #2` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233983207)

# Sauce (safari) #
Testing web-platform-tests at revision ae56a2cf2fa9381a5256f9897427ee85b12c96c9
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6000/cors/access-control-expose-headers-parsing.window.html">/cors/access-control-expose-headers-parsing.window.html</a></summary>


|                   Subtest                   | Results |           Messages           |
|---------------------------------------------|---------|------------------------------|
|                                             | OK      |                              |
| `Access-Control-Expose-Headers parsing: #1` | FAIL    | `Can't find variable: fetch` |
| `Access-Control-Expose-Headers parsing: #2` | FAIL    | `Can't find variable: fetch` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233983213)

# Chrome (unstable) #
Testing web-platform-tests at revision ff1f03977a13d6f7814d99f461121fc5ef6c8f7c

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233983214)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ff1f03977a13d6f7814d99f461121fc5ef6c8f7c

**Review by jdm — APPROVED** [review]

**Pull request merged**
