### PR TITLE
Add more isEqualNode tests

### PR DESCRIPTION
**Pull request by domenic**
Supercedes https://github.com/w3c/web-platform-tests/pull/2261. Upstreamed from https://github.com/tmpvar/jsdom/blob/master/test/web-platform-tests/to-upstream/dom/nodes/Node-isEqualNode.html. Feel free to edit for Safari compatibility.

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/dom-reviewers.

**Comment by Ms2ger** [comment]
Reviewed on critic; would also appreciate reviews of my commits.

**Comment by domenic** [comment]
Thanks. Agreed on the createDocument bug; we caught that about a week ago, and I apologize for not updating this. Your commits look good.

Also agree on it being a mistake to insert doctypes into comments. Not sure how best to salvage that test, but I can poke at it this weekend unless you want to do it.

Apologies for submitting tests which don't pass in browsers for dumb reasons. That was obviously not a good move on our part when upstreaming. In the future we'll do better testing that beforehand to catch issues like that and not waste WPT reviewers time.

**Comment by domenic** [comment]
@Ms2ger I ended up just trimming down that test a decent bit. Tests now pass in Firefox. Chrome fails the "documents should not be compared based on properties" and Edge fails four separate tests (!).

**Pull request merged**
