### PR TITLE
Core AAM: Rename tests so that they do not contain "'" in the file name

### PR DESCRIPTION
**Pull request by joanmarie**
Also fix several assertions related to verifying text attributes.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-09-11 21:08:54
Finished: 2017-09-11 21:13:29


<h2>Failing Jobs</h2>
<ul>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18419)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/274350774)

**Review by halindrome — COMMENTED** [review]
I don't really mind that you made these changes - but did you fix the generation script too?  Sorry, I am looking on my phone.

**Comment by joanmarie** [comment]
> I don't really mind that you made these changes - but did you fix the generation script too?

I didn't. I was in a hurry yesterday. Sorry! I'll do it today and add it to this PR. Thanks for the review!

**Comment by halindrome** [comment]
Thanks!

**Comment by joanmarie** [comment]
Ok, while I was in there, I also fixed an annoyance of mine (double underscores when `"` appears in the heading, because there's always at least one neighboring space or `=` which is also turned into an underscore). Hashtag iamnotneuroticiswear. :grin: Please review. Thanks again!

**Review by halindrome — APPROVED** [review]
LGTM

**Pull request merged**
