### PR TITLE
Update CI to Python 3.10

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Some of the failures are because of `from collections import Iterable, Mapping`, which gives this warning in Python 3.8:
> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

**Comment by foolip** [comment]
This will also be blocked by https://github.com/mozilla/sphinx-js/issues/186.

**Comment by foolip** [comment]
@jgraham unfortunately I've hit another problem with Python versions here. To avoid building aioquic we need to pick versions that have prebuilt wheels for Python 3.6 and 3.10, but unfortunately I don't think such a version exist, although I haven't tested all versions between 0.9.15 and 0.9.19.

https://github.com/web-platform-tests/wpt/pull/33108/commits/b292cb61bd93973c5f1052e35bc797f2d9c7bf51 seems to have mostly worked, but not entirely, there are still Azure Pipelines failures where it looks like 0.9.15 is being attempted even though we should be running Python 3.10 there.

Any thoughts on how to deal with this situation? Options I can see:
- Just allow the dependency to be built from source, installing all the stuff required to do that on all platforms
- Stop running the webtransport tests when using Python 3.6
- Figure out a way of installing different versions of aioquic depending on Python version that actually works

**Comment by jgraham** [comment]
> Just allow the dependency to be built from source, installing all the stuff required to do that on all platforms

I'm pretty sure that's going to be a "now you have N problems" approach. Also since upstream dropped 3.6 support there's no real guarantee it would actually solve the problem. 

> Stop running the webtransport tests when using Python 3.6

This seems plausible given that aioquic is already set up as an optional component (the server needs to be explcitly enabled), and afaik Gecko doesn't run these tests at the moment (I think we'd like to run them at some point, but I don't have any information to suggest that has to be before updating to 3.7).

> Figure out a way of installing different versions of aioquic depending on Python version that actually works

I think the worry with that approach is that you could end up with results that depend on the version of aioquic installed. Or we could end up with interface differences. But if there was every a non-optional library for which we wanted to support more Python versions than the upstream, I think this would be the only workable approach, so we may end up needing to use it at some point.

**Comment by DanielRyanSmith** [comment]
After doing some investigation, I think the reason the CI is not installing the correct `aioquic` version correctly for pipeline `affected tests without changes: Safari Technology Preview` because it is switching branches before it installs Python dependencies.

Screen Shot 2022-03-24 at 4 08 58 PM

Maybe I'm misunderstanding this, but it seems like we're not actually taking new code changes into consideration at this step

**Comment by foolip** [comment]
@DanielRyanSmith ah yes, of course, good find!

We do this because we want to run the affected tests without the changes, and we do this by simply checking out the commit that was merged to produce the commit under test.

But the version of Python installed is still going to be determined by `.azure-pipelines.yml` from the PR branch.

There are many ways of breaking things similar to this, and it's happened with Taskcluster too. But fortunately, once we know what the cause is, we can just admin merge.

"infrastructure/ tests: macOS" and "tools/wpt/ tests: macOS + Python 3.10" are still failing on Azure Pipelines though. In particular the latter seems like a real problem related to aioquic. Can you investigate?

When looking at a problem like this, I usually start by rebasing https://github.com/web-platform-tests/wpt/pull/28759 to be sure that all tests are in fact passing on `master`, to avoid a wild goose chase after a problem not caused by the PR. I'd suggest creating your own draft PR like it for these purposes.

(It would also be a good idea to automate this, so that we would find out if tests are ever broken on `master`.)

**Pull request closed without merging**
