### PR TITLE
'ethiopic-numeric' suffix is '/ ' (U+002F, U+0020)

### PR DESCRIPTION
**Pull request by tgraham-antenna**
From https://www.w3.org/TR/css-counter-styles-3/#ethiopic-numeric-counter-style:

> the suffix is "/ " (U+002F SOLIDUS followed by a U+0020 SPACE)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249898999)

# Firefox (nightly) #
Testing web-platform-tests at revision bcf9898c0fc1431e6560379f024abe191fdb137c
Using browser at version BuildID 20170703100343; SourceStamp 283debe8155accfec5812c66e33384ce217d02c2
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249899000)

# Sauce (safari) #
Testing web-platform-tests at revision bcf9898c0fc1431e6560379f024abe191fdb137c
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249899006)

# Chrome (unstable) #
Testing web-platform-tests at revision bcf9898c0fc1431e6560379f024abe191fdb137c

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249899007)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision bcf9898c0fc1431e6560379f024abe191fdb137c

**Review by r12a — APPROVED** [review]
Thanks for spotting that, Tony. I'll change in the i18n test suite too, and rejig the results where necessary.

**Pull request merged**
