### PR TITLE
Refine the tests for scrolling to fragid according to the revised alg…

### PR DESCRIPTION
**Pull request by alphan102**
…orithm.

Applied algorithm from whatwg spec
https://html.spec.whatwg.org/multipage/#the-indicated-part-of-the-document

### CODE REVIEW

**Comment by alphan102** [comment]
Chrome and Safari can both pass the tests.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17399)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264631173)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17399)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264631173)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-15 06:35:46
Finished: 2017-08-15 06:44:53



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17399)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264631173)

**Review by tkent-google — APPROVED** [review]
lgtm

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
