### PR TITLE
[geometry-1] Add DOMQuad test for Editor’s Draft.

### PR DESCRIPTION
**Pull request by hwanseung**
https://drafts.fxtf.org/geometry/#DOMQuad

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5702)

### CODE REVIEW

**Comment by hwanseung** [comment]
@zcorpan could you reivew this patch?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225998546)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225998551)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e78cf06005c025c9c54778ae3bce67600ec70113
Using browser at version BuildID 20170426100344; SourceStamp 0f5ba06c4c5959030a05cb852656d854065e2226
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5702/css/geometry-1/DOMQuad-002.html">/css/geometry-1/DOMQuad-002.html</a></summary>


|                     Subtest                      | Results |               Messages               |
|--------------------------------------------------|---------|--------------------------------------|
|                                                  | OK      |                                      |
| `test Constructor no args`                       | PASS    |                                      |
| `test Constructor with one init DOMPoint arg`    | PASS    |                                      |
| `test Constructor with two init DOMPoint args`   | PASS    |                                      |
| `test Constructor with three init DOMPoint args` | PASS    |                                      |
| `test Constructor with four init DOMPoint args`  | PASS    |                                      |
| `test Constructor with one DOMPoint arg`         | PASS    |                                      |
| `test Constructor with two DOMPoint args`        | PASS    |                                      |
| `test Constructor with three DOMPoint args`      | PASS    |                                      |
| `test Constructor with four DOMPoint args`       | PASS    |                                      |
| `test Constructor with invaild integer args`     | PASS    |                                      |
| `test Constructor with invaild string args`      | PASS    |                                      |
| `test Constructor with NaN`                      | PASS    |                                      |
| `test fromRect`                                  | FAIL    | `DOMQuad.fromRect is not a function` |
| `test fromRect with Infinity`                    | FAIL    | `DOMQuad.fromRect is not a function` |
| `test fromQuad`                                  | FAIL    | `DOMQuad.fromQuad is not a function` |
| `test p1, p2, p3, p4 are readonly`               | PASS    |                                      |
| `test getBounds`                                 | FAIL    | `DOMQuad.fromQuad is not a function` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225998561)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 72ac3c9341e25e6a2d10956b38a428485cce8270

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
