### PR TITLE
Make us consistent with reftest window size

### PR DESCRIPTION
**Pull request by gsnedders**
This is the correctness parts of #12695, given the ongoing debate whether to land that or not.

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by gsnedders** [comment]
oh, it's `session.window.size`, not `session.window_size` in our wdclient.

**Comment by gsnedders** [comment]
Chrome/macOS on Azure is now giving 600x566, despite it working locally. This is odd.

**Review by jgraham — APPROVED** [review]
Subject to removing debug commit.

**Comment by WeizhongX** [comment]
@gsnedders We have a bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1517767) pointing some change in this PR. The change in chrome.py that added "enable-automation" to excludeSwitches.

Do you might still remember why this is needed? (Sorry for asking questions on such an old PR.)

**Comment by gsnedders** [comment]
> @gsnedders We have a bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1517767) pointing some change in this PR. The change in chrome.py that added "enable-automation" to excludeSwitches.
> 
> Do you might still remember why this is needed? (Sorry for asking questions on such an old PR.)

The commit message that originally added it (for testharness.js only) I think justifies this in the commit message: https://github.com/web-platform-tests/wpt/commit/970761acd77478950da2b21d97c839629c74e678. Specifically:

> When this extension is used, Chrome displays a warning bar that changes the window size while a test is already running, and this can cause test flake.

**Comment by WeizhongX** [comment]
Thanks for the prompt response!

**Pull request merged**
