### PR TITLE
[css-text] Control characters should be visible

### PR DESCRIPTION
**Pull request by frivoal**
Tests for https://github.com/w3c/csswg-drafts/issues/1990 and https://github.com/w3c/csswg-drafts/issues/855

### CODE REVIEW

**Review by FremyCompany — APPROVED** [review]

**Comment by foolip** [comment]
@frivoal, the control-chars-00D.html test is failing in both Chrome Dev and Firefox Nightly:
https://wpt.fyi/results/css/css-text/white-space?sha=434ca47448&label=experimental

No results from Edge or Safari yet, but is that known and intentional?

**Comment by foolip** [comment]
Ah, 0x0D is precisely the topic of https://github.com/w3c/csswg-drafts/issues/855.

I've tested http://web-platform-tests.live/css/css-text/white-space/control-chars-00D.html and it's not visible in Chrome, Edge, Firefox or Safari.

Anyway, I've filed https://crbug.com/893490 to track it.

**Comment by frivoal** [comment]
> is that known and intentional?

Yes. Thanks for filing the bug.

**Comment by FremyCompany** [comment]
I was about to say that the character was visible in the latest Edge builds where our new text engine is enabled... but apparently we "fixed" (or "regressed" I guess) this at some point during the release and it no longer shows up. Sigh...

I don't have a very strong opinion but I think being consistent with our general decision with control characters makes sense, and we agreed to go that road at the last meeting, maybe we should stick with this decision except if we find a compelling reason to switch back.

**Comment by frivoal** [comment]
I think consistency is the way to go. This is not a pressing issue, since it only applies to U+000D injected by script or CSS (those in the markup get converted by the HTML parser), but given some time to fix it, one less oddity in the platform sounds nice.

**Comment by eaenet** [comment]
Agreed, consistency here seems like the best way forward.

**Pull request merged**
