### PR TITLE
Cross-Origin-Resource-Policy tests

### PR DESCRIPTION
**Pull request by youennf**
These are initial tests targeting https://github.com/whatwg/fetch/pull/733
These are based on https://bugs.webkit.org/show_bug.cgi?id=185840.

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
In general this looks great, but I found a couple issues. (I annotated them in one file, but they apply to most tests.)

**Comment by annevk** [comment]
The other thing that'd be nice to test is ensuring the header is properly parsed. E.g., `same-ORIGIN` does not match, `same-origin, same-site` does not match, etc.

**Review by annevk — APPROVED** [review]
Thanks for addressing the nits and writing all these. I created two more small PRs that cover some remaining aspects.

Let's wait with landing this until next week so we can land all the various pieces together.

**Comment by annevk** [comment]
The reason this is timing out is because it changes `common/get-host-info.sub.js` so we'll need an admin to land this next week.

**Comment by foolip** [comment]
Rebase+merge button pressed as requested by @annevk on IRC.

**Pull request merged**
