### PR TITLE
Install ahem

### PR DESCRIPTION
**Pull request by bobholt**
Let's try this again. This adds 2 commits: 1 to fix the apparent error and 1 (that should be removed) to run a stability test to verify that will work.

cc @foolip

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/7322)

### CODE REVIEW

**Comment by gsnedders** [comment]
Still failing.

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability.py", line 355, in run
    iterations, results, inconsistent = run(venv, wpt_logger, **wpt_kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/stability.py", line 188, in run
    wptrunner.run_tests(**kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 260, in run_tests
    logger.suite_end()
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 120, in __exit__
    cm.__exit__()
TypeError: __exit__() takes exactly 4 arguments (1 given)
```

**Review by gsnedders — DISMISSED** [review]
Still failing.

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability.py", line 355, in run
    iterations, results, inconsistent = run(venv, wpt_logger, **wpt_kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/stability.py", line 188, in run
    wptrunner.run_tests(**kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 260, in run_tests
    logger.suite_end()
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 120, in __exit__
    cm.__exit__()
TypeError: __exit__() takes exactly 4 arguments (1 given)
```

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2017-09-11 11:39:55
Finished: 2017-09-11 12:03:32


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18407)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/274141312)

**Comment by jgraham** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/7322)*

**Review by jgraham — APPROVED** [review]
Approved  when the test file is removed.

**Comment by bobholt** [comment]
Test file removed and PR squashed (since it was going to re-run CI anyway).

**Pull request merged**
