### PR TITLE
unittests failing because lint test failing

### PR DESCRIPTION
**Pull request by gsnedders**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9170)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-01-23 23:51:48
Finished: 2018-01-24 00:13:19


<h2>Failing Jobs</h2>
<ul>

<li>lint</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23194)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/332563179)

**Comment by gsnedders** [comment]
This is failing with:

ERROR:lint:css/css-grid/alignment/support/100x100-green.png: The filename support/100x100-green.png is shared by: css/css-flexbox/support/100x100-green.png, css/css-grid/alignment/support/100x100-green.png, css/css-grid/grid-items/support/100x100-green.png (CSS-COLLIDING-SUPPORT-NAME)

THis seems to be pre-existing. :(

**Comment by gsnedders** [comment]
See https://github.com/w3c/web-platform-tests/pull/9172 for fixing the existing failing lint, and https://github.com/w3c/web-platform-tests/issues/9171 for the underlying cause of how we landed a test that fails the lint).

**Comment by jgraham** [comment]
I think you missed a case.

**Review by jgraham — APPROVED** [review]

**Comment by Hexcles** [comment]
Sorry, late to the party, but LGTM. Thanks :)

**Pull request merged**
