### PR TITLE
Manual tests for the download attribute on anchors

### PR DESCRIPTION
**Pull request by jeisinger**
Tests for whatwg/html#2622

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232730735)

# Firefox (nightly) #
Testing web-platform-tests at revision 8b9e949fabcb1309aad8f06537a985ac647dd207
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-about-url.manual.html">/html/semantics/downloading-resources/a-download-about-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-blob-url.manual.html">/html/semantics/downloading-resources/a-download-blob-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-data-url.manual.html">/html/semantics/downloading-resources/a-download-data-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232730736)

# Sauce (safari) #
Testing web-platform-tests at revision 8b9e949fabcb1309aad8f06537a985ac647dd207
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-about-url.manual.html">/html/semantics/downloading-resources/a-download-about-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-blob-url.manual.html">/html/semantics/downloading-resources/a-download-blob-url.manual.html</a></summary>


|                 Subtest                 | Results |                                        Messages                                       |
|-----------------------------------------|---------|---------------------------------------------------------------------------------------|
|                                         | OK      |                                                                                       |
| `Download a blob URL from an a element` | FAIL    | `SyntaxError: Can't create duplicate variable that shadows a global property: 'blob'` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-data-url.manual.html">/html/semantics/downloading-resources/a-download-data-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232730737)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 8b9e949fabcb1309aad8f06537a985ac647dd207
Using browser at version 14.14393
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232730743)

# Chrome (unstable) #
Testing web-platform-tests at revision 8b9e949fabcb1309aad8f06537a985ac647dd207
Using browser at version 60.0.3095.5 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-about-url.manual.html">/html/semantics/downloading-resources/a-download-about-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-blob-url.manual.html">/html/semantics/downloading-resources/a-download-blob-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-cross-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-data-url.manual.html">/html/semantics/downloading-resources/a-download-data-url.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-dont-redirect-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-same-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-with-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5935/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html">/html/semantics/downloading-resources/a-download-same-origin-redirect-swap-origin-without-content-disposition.manual.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | TIMEOUT |          |

</details>
</details>

**Comment by jeisinger** [comment]
@bzbarsky @annevk any feedback on these tests?

**Comment by annevk** [comment]
I haven't looked in detail, but one thing that needs fixing is that "-manual" is a suffix as far as I know (last string before the dot), not a dot-delimited identifier.

**Comment by jeisinger** [comment]
ah, that would explain why the CI tries to run the tests :)

**Comment by bzbarsky** [comment]
The general idea seems reasonable.  I haven't looked at the details of the tests.

**Comment by jeisinger** [comment]
After re-reading the spec, I've updated the tests a bit: a download is considered trusted if the initiator origin and the resource's final origin are same origin, so even if you start cross origin, or redirect cross origin and then back, it's trusted.

Also updated chrome's implementation, and the tests now pass there.

**Comment by jeisinger** [comment]
@zcorpan can you please review?

**Comment by zcorpan** [comment]
@jeisinger can you please check the "allow edits from maintainers" checkbox in the sidebar? I'd like to push a commit here.

**Comment by jeisinger** [comment]
done.

Note that I had to revert the version we landed in Chromium, so while the tests still reflect the spec, it's not what any browser ships today :/

**Comment by zcorpan** [comment]
Thanks, pushed. I also rebased to latest master, it seems this branch was previously based on a really old master (before testharness.js was moved to this repo).

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
What was the reason for the revert?

**Comment by jeisinger** [comment]
It made us cancel about 5% of all downloads, which we consider too much of a breakage

**Comment by zcorpan** [comment]
OK. I guess we should merge this and the spec change as-is, and then followup if there needs to be any changes for compat. WDYT?

**Comment by jeisinger** [comment]
the spec is already updated, so yeah, I guess it makes sense to merge the tests as well, and update both together once we have something better

**Comment by zcorpan** [comment]
https://github.com/whatwg/html/pull/2623 is not yet merged.

**Comment by jeisinger** [comment]
ah, fair enough.. @domenic wdyt?

**Comment by domenic** [comment]
What do I think about what? It sounds like maybe we should just close both the spec and tests change, since it's not web-compatible after all?

**Comment by zcorpan** [comment]
Does the current spec match any implementation, though?

I guess we should leave this open until we have figured out something that a browser is able to ship.

**Comment by jeisinger** [comment]
The spec is very vague and leaves many key questions open to UA defined behavior or based on some notion of user preferences. As such, the implementations all match the spec, even though they're visibly different.

**Comment by annevk** [comment]
I suggest we consider this abandoned.

**Pull request closed without merging**
