### PR TITLE
MathML: Automate href-manual using testdriver.js

### PR DESCRIPTION
**Pull request by fred-wang**
Tentative rewriting using testdriver

### CODE REVIEW

**Comment by fred-wang** [comment]
- test passes on safari
- href is not supported in chromium
- test passes (manually) on firefox but fails with testdriver:

UnknownException: TypeError: el.style is undefined
stacktrace:
	element.isInView@chrome://marionette/content/element.js:1065:7
	webdriverClickElement@chrome://marionette/content/interaction.js:148:8
	interaction.clickElement@chrome://marionette/content/interaction.js:130:11
	clickElement/<@chrome://marionette/content/listener.js:1208:14
	navigate/<@chrome://marionette/content/listener.js:408:13
	navigate@chrome://marionette/content/listener.js:407:13
	clickElement@chrome://marionette/content/listener.js:1207:5

It seems el.style on the MathML mspace element returns undefined in Firefox. So I guess it is a Firefox/Marionette bug rather than a test bug.

**Comment by gsnedders** [comment]
Yeah, that definitely looks like a Firefox bug. :/

**Comment by fred-wang** [comment]
I rebased after https://github.com/web-platform-tests/wpt/pull/15537

**Review by rwlbuis — APPROVED** [review]

**Comment by emilio** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1530110 for this.

**Comment by fred-wang** [comment]
Thanks emilio

**Pull request merged**
