### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=217537

### PR DESCRIPTION
**Pull request by darinadler**
Added a test for replaceChildren with no arguments on a parent having a child.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]
This has already been reviewed upstream, right? (I mean, reviewed by a WebKit-project reviewer already.)

**Comment by darinadler** [comment]
> This has already been reviewed upstream, right? (I mean, reviewed by a WebKit-project reviewer already.)

Yes. Hadn’t yet been reviewed when I posted the pull request, but has been since.

**Comment by sideshowbarker** [comment]
> Yes. Hadn’t yet been reviewed when I posted the pull request, but has been since.

OK yeah I see the r+ there now from Sam Weinig

**Comment by sideshowbarker** [comment]
…and I guess this is your first WPT PR — thanks 🎉

**Pull request merged**
