### PR TITLE
Extend `evaluate` serialization tests

### PR DESCRIPTION
**Pull request by sadym-chromium**
* Extend `evaluate` serialization tests with missing non-primitives.
* Reorder input params to align with the spec.
* Removed `ids` test param, as it screens out test failure details.

### CODE REVIEW

**Comment by sadym-chromium** [comment]
Converting to draft, as adding `missing` functionality from #34777 is needed to check `handle` serialization properly for different `resultOwnership`.

**Comment by sadym-chromium** [comment]
Converting to draft, as adding `missing` functionality from #34777 is needed to check `handle` serialization properly for different `resultOwnership`.

**Comment by sadym-chromium** [comment]
~~Converting to draft, as adding `missing` functionality from #34777 is needed to check `handle` serialization properly for different `resultOwnership`.~~
UPD: actually, the PR #34777 is not a blocker.

**Comment by lutien** [comment]
Thanks @sadym-chromium! 
That looks good to me, but I would leave the final review to @whimboo or @juliandescottes.

**Review by juliandescottes — APPROVED** [review]
LGTM as well, thanks!

**Pull request merged**
