### PR TITLE
Also test partial interfaces from selection spec

### PR DESCRIPTION
**Pull request by ayg**

### CODE REVIEW

**Comment by ayg** [comment]
@Ms2ger @jgraham @gsnedders This is easy to review.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT Results Dashboard](http://pulls.web-platform-tests.org/build/17211)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263094244)

**Comment by ayg** [comment]
@rniwa, can you review?

**Review by Ms2ger — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-10 14:11:11
Finished: 2017-08-10 14:38:58





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17211)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/263094244)

**Pull request merged**
