### PR TITLE
Revert "Make testharness tests run in a top-level browsing context"

### PR DESCRIPTION
**Pull request by foolip**
This reverts commit 74522a275bea481821e789145578e9e16fd27be3.

Fixes https://github.com/web-platform-tests/wpt/issues/14495.

Reopens https://github.com/web-platform-tests/wpt/issues/13418.

### CODE REVIEW

**Comment by foolip** [comment]
Crap, `test_run_firefox` is failing on Travis:
https://travis-ci.org/web-platform-tests/wpt/jobs/467412785#L629

I sort of doubt it's because of the changes since I saw something similar yesterday, but I've sent https://github.com/web-platform-tests/wpt/pull/14500 to run all the tools/ tests before I merge this, to see if there are failures on master.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/14500 was passing. I'll retrigger again with my revert included to see if it goes to failing. If it does then the problem is real. (Or it's flaky and I'm unlucky.)

**Comment by foolip** [comment]
Still passing. That test must be flaky then. @jgraham can you tell from https://travis-ci.org/web-platform-tests/wpt/jobs/467412785#L629 if it was due to mozdownload failing, or what's up?

**Comment by jgraham** [comment]
It's not the download, it's the websockets server not starting for some reason.

**Pull request merged**
