### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by marcoscaceres**
Add rsolomakhin

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Sorry, some reason this got created twice.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857926)

# Firefox (nightly) #
Testing web-platform-tests at revision 7ed28e3d1d77946cc74b5b6fd84af0ad5eaecc48
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857927)

# Sauce (safari) #
Testing web-platform-tests at revision 7ed28e3d1d77946cc74b5b6fd84af0ad5eaecc48
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857933)

# Chrome (unstable) #
Testing web-platform-tests at revision 890ebde6ab312b831d953aa9b3b902bf7bde828e
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857934)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 890ebde6ab312b831d953aa9b3b902bf7bde828e
Using browser at version 14.14393
Starting 10 test iterations

**Pull request closed without merging**
