### PR TITLE
[Azure Pipelines] Use Python 3.8.x for Safari test-suite runs

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See the RFC: https://github.com/web-platform-tests/rfcs/pull/65

### CODE REVIEW

**Comment by foolip** [comment]
The run for 2089041d2a90d9f15054b8cd69d5049a5f7da5c3 finished and the differences aren't massive:
https://wpt.fyi/results/?q=is%3Adifferent&run_id=627220001&run_id=648510001

**Comment by stephenmcgruer** [comment]
I have pushed efc998196652b73879662e23e2c9a3d14f1fea57 to `triggers/safari_preview`. The nearest parent is 0bc7269d68 which is 2 commits back but should be pretty close for a comparison.

Once the run has finished I will post the wpt.fyi comparison url.

cc @ziransun

**Comment by stephenmcgruer** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=694810001&run_id=702810004 is the diff, but there's something strange there. Multiple directories have hundreds of tests now `MISSING`, and unless someone deleted them in 6ceb598f2089fff3f8e538932116de75c1de7458...78424f24c79d550eebc93f1f255919ae99397c22 (which I doubt) then something is wrong with the run.

@ziransun FYI as you might want to take a look anyway, but really I need to dig into the Azure Pipelines logs for the run.

**Comment by stephenmcgruer** [comment]
I wasn't able to find anything obvious in the logs at a quick look, so I'm being lazy and just triggering another run to see. eb419a7411e6355acc78d81d8f9003d75b84eb75 is the run, the parent is c960a244c1fe3679c8c64eab618a2daf7977a081 aka https://wpt.fyi/results/?run_id=683470005

**Comment by stephenmcgruer** [comment]
Ok, the new run seems much more reasonable: https://wpt.fyi/results/?diff&filter=ADC&run_id=683470005&run_id=695000002 . A little concerning to not figure out what was happening last time, but for now I think we can proceed with using this as the newest Safari run.

cc @ziransun

**Review by Hexcles — APPROVED** [review]

**Pull request merged**
