### PR TITLE
[Azure Pipelines] use `python -m ensurepip` instead of `easy_install pip`

### PR DESCRIPTION
**Pull request by foolip**
Based on investigation in https://github.com/web-platform-tests/wpt/issues/19753#issuecomment-546586311.

### CODE REVIEW

**Comment by foolip** [comment]
Looks like it works. Full Safari TP run on progress in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35275

**Comment by foolip** [comment]
@Hexcles would you mind trying this without `sudo` on a fresh macOS and seeing what it does, if anything?

**Comment by foolip** [comment]
https://wpt.fyi/results/?q=is%3Adifferent&run_id=336710008&run_id=346250013 is the differences in results and it looks like a similar number of tests as usually differ due to flakiness, so this is probably fine.

I've also kicked off https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35281 since Safari stable is running on macOS 10.13, compared to 10.14 for STP.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/19933 might be an alternative, seems like `pip` is already installed on the Azure Pipelines VMs now. Needs testing though.

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt/pull/19933, but @Hexcles I'm still interested in the questions about running this locally.

**Comment by Hexcles** [comment]
@foolip 

```
$  python -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Collecting pip
Installing collected packages: pip
  Exception:
  Traceback (most recent call last):
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/commands/install.py", line 352, in run
      root=options.root_path,
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/req/req_set.py", line 693, in install
      **kwargs
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/req/req_install.py", line 817, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/req/req_install.py", line 1018, in move_wheel_files
      isolated=self.isolated,
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/wheel.py", line 237, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/var/folders/_c/7mgd5_9926l5v7nyq1_vcbcr00bvkn/T/tmpZtd1dP/pip-6.1.1-py2.py3-none-any.whl/pip/wheel.py", line 208, in clobber
      os.makedirs(destdir)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip-6.1.1.dist-info'
```

**Comment by foolip** [comment]
Thanks @Hexcles, sounds like it tries to install system wide by default. I'll ask more on the main issue :)

**Pull request closed without merging**
