### PR TITLE
Use multiple global scopes (aka any.js)

### PR DESCRIPTION
**Pull request by plehegar**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5203)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5203/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213993036)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 87b75de41643a3cf71f8a11609917185fbd2627e
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213993037)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 87b75de41643a3cf71f8a11609917185fbd2627e
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
No tests run.

**Comment by annevk** [comment]
LGTM, assuming you ran the resulting tests in browsers and there were no differences (for the window case). (Also, if there are new failures for the worker case, it would be good to file bugs.)

**Comment by annevk** [comment]
(Especially since not all browsers have support for .any.js locally yet.)

**Comment by igrigorik** [comment]
LGTM for the content.

w3c-bots doesn't seem to be picking up the tests.. any idea why not?

**Review by igrigorik — APPROVED** [review]

**Comment by annevk** [comment]
Bots issue is #5130.

**Comment by plehegar** [comment]
I ran the tests on Chrome, Firefox, and Edge. Chrome doesn't support observer in workers yet and edge doesn't support observers at all.

**Pull request merged**
