### PR TITLE
Add specific error for Bluetooth's test

### PR DESCRIPTION
**Pull request by g-ortuno**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5516)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/220387723)

# Firefox (nightly channel) #
Testing web-platform-tests at revision ef6d082f5719ec470f355ac149216d5bff921e7d
Using browser at version BuildID 20170409194145; SourceStamp 45692c884fdd5136a64fb2f8a61a0c8183b69331
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5516/bluetooth/idl-Bluetooth.html">/bluetooth/idl-Bluetooth.html</a></summary>


|       Subtest        | Results |                                                                                                         Messages                                                                                                         |
|----------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                      | OK      |                                                                                                                                                                                                                          |
| `Bluetooth IDL test` | FAIL    | `assert_throws: the constructor should not be callable with "new" function "() => new Bluetooth()" threw object "ReferenceError: Bluetooth is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/220387724)

# Chrome (unstable channel) #
Testing web-platform-tests at revision ef6d082f5719ec470f355ac149216d5bff921e7d
Using browser at version 59.0.3063.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5516/bluetooth/idl-Bluetooth.html">/bluetooth/idl-Bluetooth.html</a></summary>


|       Subtest        | Results |                                                                                                         Messages                                                                                                         |
|----------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                      | OK      |                                                                                                                                                                                                                          |
| `Bluetooth IDL test` | FAIL    | `assert_throws: the constructor should not be callable with "new" function "() => new Bluetooth()" threw object "ReferenceError: Bluetooth is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")` |

</details>
</details>

**Comment by jdm** [comment]
Thanks!

**Comment by annevk** [comment]
This helps with #5317, thanks!

**Pull request merged**
