### PR TITLE
Add RTCSessionDescription IDL test

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5689)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225848137)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225848139)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e1ec70c2730a4f3453769abb480e4ac95bcd5b0c
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5689/webrtc/RTCSessionDescription-idl.html">/webrtc/RTCSessionDescription-idl.html</a></summary>


|                                                      Subtest                                                       | Results |                                                                                  Messages                                                                                  |
|--------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                    | OK      |                                                                                                                                                                            |
| `RTCSessionDescription interface: existence and properties of interface object`                                    | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface object length`                                                                    | FAIL    | `assert_equals: wrong value for RTCSessionDescription.length expected 1 but got 0`                                                                                         |
| `RTCSessionDescription interface object name`                                                                      | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface: existence and properties of interface prototype object`                          | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface: existence and properties of interface prototype object's "constructor" property` | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface: attribute type`                                                                  | FAIL    | `assert_equals: setter must be undefined for readonly attributes expected (undefined) undefined but got (function) function "function set type() {\n    [native code]\n}"` |
| `RTCSessionDescription interface: attribute sdp`                                                                   | FAIL    | `assert_equals: setter must be undefined for readonly attributes expected (undefined) undefined but got (function) function "function set sdp() {\n    [native code]\n}"`  |
| `RTCSessionDescription must be primary interface of sessionDesc`                                                   | PASS    |                                                                                                                                                                            |
| `Stringification of sessionDesc`                                                                                   | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface: sessionDesc must inherit property "type" with the proper type (0)`               | PASS    |                                                                                                                                                                            |
| `RTCSessionDescription interface: sessionDesc must inherit property "sdp" with the proper type (1)`                | PASS    |                                                                                                                                                                            |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225848145)

# Chrome (unstable channel) #

**Comment by agouaillard** [comment]
see #5693

**Pull request closed without merging**
