### PR TITLE
Revert "Make some tests more self descriptive"

### PR DESCRIPTION
**Pull request by bfgeek**
@Reverts web-platform-tests/wpt#36661

### CODE REVIEW

**Comment by bfgeek** [comment]
@vmpstr ptal

**Review by vmpstr — APPROVED** [review]
Florian should probably take a look as well, but this looks fine to me to revert unintentional test failures

**Comment by bfgeek** [comment]
Ping @frivoal

**Comment by frivoal** [comment]
Looking at this today. Weill either fix or revert.

**Comment by frivoal** [comment]
Sorry about that. I made a pile of changes to the tests to make them more understandable to human reviewers (as was my case as I tried to figure out which one corresponded to which part of the spec, and will be the case for anyone trying to implement it and running into errors before their implementation passes everything), and among the various changes I made, there's one where I had modified a ref and a corresponding test, but the ref was used in more than one test, and I failed to change all of them accordingly.

That particular change was not essential, so I've reverted it in https://github.com/web-platform-tests/wpt/pull/36814. The other tweaks did not change the tests results, so having merged that, all tests results should be back to what they were.

Very sorry about the inconvenience.

**Pull request closed without merging**
