### PR TITLE
 Update webaudio/js/worklet-recorder.js

### LINKED ISSUE #17662: options should be options.processorOptions at  Web Audio worklet-recorder.js
At https://github.com/web-platform-tests/wpt/commit/d5be80a86d4f938250c075ac12414ad47516969c#diff-f3873c920bd541f45825be596c3a4a6fR10 `options` should be `options.processorOptions` else the properties passed at a plain object not having property `processorOptions` will not be defined at `AudioWorkletProcessor`.

`const aw = new AudioWorkletNode(context, "recorder-processor", {0:1})`

results in 

`console.log(options) // {numberOfInputs: 1, numberOfOutputs: 1}` 

where

`const aw = new AudioWorkletNode(context, "recorder-processor", {processorOptions:{0:1}})`

results in

`console.log(options) // {numberOfInputs: 1, numberOfOutputs: 1, processorOptions: {0: 1}}`

within `AudioWorkletProcessor`.

Specification https://webaudio.github.io/web-audio-api/#dom-audioworkletnodeoptions-processoroptions

cc @yutakahirano

### PR DESCRIPTION
**Pull request by guest271314**
Fixes https://github.com/web-platform-tests/wpt/issues/17662

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Thank you for the pull request! It looks like there are two files here which are unrelated to web-audio:

* offscreen-canvas/the-offscreen-canvas/2d.getcontext.exists.html
* offscreen-canvas/tools/tests2d.yaml

Assuming that they were accidentally included, can you remove them from the change? Thanks!

**Comment by guest271314** [comment]
How to remove the files from this pull request? Delete the files in the branch?

**Comment by guest271314** [comment]
@stephenmcgruer Deleted the listed files. Do any other files need to be deleted? Thanks.

**Comment by stephenmcgruer** [comment]
Hey @guest271314 ; what you seem to have done in your new commits is remove those two files entirely, rather than remove your changes to them. How to fix this will depend on how you've setup your fork of the WPT repository (https://gist.github.com/Chaser324/ce0505fbed06b947d962 is a useful guide, if you're new to the fork + pull-request model)

Looking at the commit log for this pull request, it seems like you have a lot of unrelated commits in it: "Merge pull request #2 from web-platform-tests/master", "Update 2d.getcontext.exists.html", ... "Update context-preserves-canvas.html", ..., "Merge branch 'master' into guest271314-patch-1" to give a few examples. I think the only commit that actually applies to the work you're trying to do in this pull request is https://github.com/web-platform-tests/wpt/pull/22878/commits/5da48b870568a8d6fdf1a249f593de6d7b03177f ?

Given that, I would suggest doing something like this in your local fork - **but** be aware that this will remove all those other commits from the `guest271314-patch-3` branch. As always with commands that strangers on the internet provide, I would suggest making sure you understand what each of these is going to do before executing them :)

```
$ git checkout guest271314-patch-3
$ git remote add upstream https://github.com/web-platform-tests/wpt.git
$ git fetch upstream
$ git reset upstream/master --hard  # This makes guest271314-patch-3 point directly to WPT's master
$ git cherry-pick 5da48b870568a8d6fdf1a249f593de6d7b03177f  # This adds back the commit that changes worklet-recorder.js
$ git push origin guest271314-patch-3 --force  # This updates your GitHub fork, and thus this pull request. '--force' is required as you are rewriting history.
```

**Comment by guest271314** [comment]
@stephenmcgruer Been a while since ran git at command line. Got user name and email and SSH set up. Though do not already have a local clone of the repository. For some reason 

```
$ git clone https://github.com/guest271314/wpt.git
Cloning into 'wpt'...
```

fails to download the repository. Size? 

Is there a way to achieve those commands using GitHub UI?

**Comment by guest271314** [comment]
@stephenmcgruer No space left on device

```
fatal: cannot create directory at 'css/CSS2/tables/reference': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

proceed anyway

```
$ git reset upstream/master --hard
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.

```

Is there a way to perform the task at GitHub UI?

Or, should just delete the fork and start from scratch?

**Comment by stephenmcgruer** [comment]
Ah, I didn't realize you were using the GitHub UI, sorry.

Looking at https://github.com/guest271314/wpt/tree/master it does look like your fork is in a bit of a bad state. The master branch is "19 commits ahead, 1034 commits behind web-platform-tests:master.", which implies that you have commits on your master that are **not** on WPT's master That makes everything a pain - generally you want to keep your master on the same path as WPT (so that at worst it would say "is 1034 commits behind web-platform-tests:master", because then you can just bring it forward to our master).

If you don't have anything in your fork that you want to keep, I would suggest [deleting it](https://help.github.com/en/github/administering-a-repository/deleting-a-repository), re-forking WPT, and then making the edits again. If you do have stuff you want to keep, it's going to get more complicated :)...

**Comment by guest271314** [comment]
> If you don't have anything in your fork that you want to keep, I would suggest deleting it, re-forking WPT, and then making the edits again. If you do have stuff you want to keep, it's going to get more complicated :)...

Well, they code is apparently included in this PR, so if delete current WPT repository and close this PR, the code will still be in listed in "Pull requests", correct? Can browse the documents that have composed, mainly some `canvas` and `OffscreenCanvas` tests that appear to have been referenced elsewhere in another PR. The landscape re `canvas` is not consistent from browser to browser, so will more than likely encounter and re-write the code and tests, anyway.

> When you do make the edits, btw, you always want to do them from your master branch, and then select the 'create a new branch' option when making the edit (see step 7 of [this](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository)). (See also [this guide](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository)).

That is illuminating. Have been creating a branch for each PR instead of just editing master branch. That is what the link illustrates, not editing master first and then creating a branch. Are you sure you meant to convey edit in master _then_ create a branch? If you find the time could you write up a brief single gist detailing each step that need to take when delete current WPT repository and re-file this PR?

**Comment by stephenmcgruer** [comment]
> Well, they code is apparently included in this PR, so if delete current WPT repository and close this PR, the code will still be in listed in "Pull requests", correct?

I _think_ so, but am not sure. The branch this PR refers to will go away, so its possible that GitHub will not be able to see the edits anymore. In this case because there are only 6 or so lines of diff I would be inclined to take a note of the diff and just re-create it by hand.

> Have been creating a branch for each PR instead of just editing master branch. That is what the link illustrates, not editing master first and then creating a branch. Are you sure you meant to convey edit in master then create a branch? If you find the time could you write up a brief single gist detailing each step that need to take when delete current WPT repository and re-file this PR?

You can create the branch first, as long as you make sure that branch is based from master (and not from another branch). If you accidentally chain branches (e.g. `branch-1` is based on `master`, `branch-2` is based on `branch-1`, etc), you will get pull requests that contain multiple unrelated commits.

In both of those guides, they do not prescribe which branch you view the file on (step 1 [in the first guide](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository) just says "In your repository, browse to the file you want to edit." - no mention of which branch), they just suggest (and they are right) that you should make sure the changes are on a branch rather than on master (step 7).

List of steps:

1. Make a manual note of the diff you have to worklet-recorder.js that you want to keep (e.g. via a screenshot, noting it down by hand, etc).
1. Follow the steps to [delete a repository](https://help.github.com/en/github/administering-a-repository/deleting-a-repository) for https://github.com/guest271314/wpt/ .
1. Visit https://github.com/web-platform-tests/wpt and click the 'Fork' button in the top-right to re-fork the repository.
1. Go to https://github.com/guest271314/wpt/blob/master/webaudio/js/worklet-recorder.js in your **new** fork, and follow steps 1-8 in [this guide](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository).
1. When you see the pull request UI, make sure you are making a pull request against `web-platform-tests/wpt:master` from `guest271314/wpt:your-branch-name`.
1. Send the new PR out for review and close this one.

**Pull request closed without merging**
