### PR TITLE
[intersection-observer] Test isIntersecting change events

### PR DESCRIPTION
**Pull request by nolanlawson**
This is a test for the change introduced in https://github.com/w3c/IntersectionObserver/pull/245. The main difference with the previous version of the spec is that the observer fires events when `isIntersecting` changes but `thresholdsIndex` does not, which covers some odd edge-adjacency scenarios.

On my machine, Chrome 60 and Edge 16 prerelease (e.g. [public insider 16275](https://blogs.windows.com/windowsexperience/2017/08/25/announcing-windows-10-insider-preview-build-16275-pc-build-15245-mobile/)) pass the 5 new tests, whereas Firefox Nightly (57.0a1 2017-08-31) does not. This is to be expected given discussion in https://github.com/w3c/IntersectionObserver/pull/222.

/cc @szager-chromium @tobytailor @scottlow

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18054)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/270600831)

**Comment by jgraham** [comment]
@tobytailor Are you able to review this?

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by foolip** [comment]
@scottlow @szager-chromium are you able to review this?

@nolanlawson can you rebase it so that Travis runs again?

**Comment by nolanlawson** [comment]
rebased ^

**Comment by foolip** [comment]
w3c-test:mirror

**Review by foolip — APPROVED** [review]
Manually confirmed http://w3c-test.org/submissions/7215/intersection-observer/isIntersecting-change-events.html to be passing in Chrome, Edge and Firefox. Safari fails with "Can't find variable: IntersectionObserver"

**Pull request merged**
