### PR TITLE
[css-ui-3] Mark support for non fixed size svg as optional

### PR DESCRIPTION
**Pull request by frivoal**
This is to match the following spec change: https://github.com/w3c/csswg-drafts/commit/5dcad3014735dbe9828273d952e2eb3115f33d5b

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-09-21 03:00:30
Finished: 2017-09-21 03:06:49


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18723)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/278025114)

**Review by AmeliaBR — APPROVED** [review]
I can confirm that the test is testing whether an SVG image without intrinsic size is accepted as a valid cursor, and that the CSS WG agreed to make that a "may" option.

Based on [the definitions of the WPT/CSS metadata flags](http://web-platform-tests.org/writing-tests/css-metadata.html), the change to the `<meta>` tag therefore seems to be correct.

I can also confirm that it it very disappointing that browsers all fail this test. That [sheep](https://rawgit.com/frivoal/web-platform-tests/69770828793197dda004547e6ab3b009c96add95/css/css-ui-3/support/cursors/woolly.svg) would make a very cute cursor.

**Comment by frivoal** [comment]
@plehegar @gsnedders @plinss Can one of you make @AmeliaBR an approved reviewer?

**Review by svgeesus — COMMENTED** [review]
lgtm

**Pull request merged**
