### PR TITLE
Update tests for slot change events

### PR DESCRIPTION
**Pull request by hayatoito**
…t is inserted

DOM Standard chagne is https://github.com/whatwg/dom/pull/459.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233116403)

# Firefox (nightly) #
Testing web-platform-tests at revision 9c115b70a438f615bf56aa18170184bbf9bc2476
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5954/shadow-dom/slotchange-event.html">/shadow-dom/slotchange-event.html</a></summary>


|                                                                                                                 Subtest                                                                                                                 | Results |                  Messages                  |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|--------------------------------------------|
|                                                                                                                                                                                                                                         | OK      |                                            |
| `slotchange event must fire on a default slot element inside an open shadow root  in a document`                                                                                                                                        | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a default slot element inside a closed shadow root  in a document`                                                                                                                                       | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a default slot element inside an open shadow root  not in a document`                                                                                                                                    | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a default slot element inside a closed shadow root  not in a document`                                                                                                                                   | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a named slot element insidean open shadow root  in a document`                                                                                                                                           | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a named slot element insidea closed shadow root  in a document`                                                                                                                                          | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a named slot element insidean open shadow root  not in a document`                                                                                                                                       | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a named slot element insidea closed shadow root  not in a document`                                                                                                                                      | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must not fire on a slot element inside an open shadow root  in a document when another slot's assigned nodes change`                                                                                                  | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must not fire on a slot element inside a closed shadow root  in a document when another slot's assigned nodes change`                                                                                                 | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must not fire on a slot element inside an open shadow root  not in a document when another slot's assigned nodes change`                                                                                              | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must not fire on a slot element inside a closed shadow root  not in a document when another slot's assigned nodes change`                                                                                             | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  in a document`      | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  in a document`     | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  not in a document`  | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  not in a document` | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside an open shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                 | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                             | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                            | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                        | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                       | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                    | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                   | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when nested slots's contents change`                                                                                                            | FAIL    | `outerHost.attachShadow is not a function` |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when nested slots's contents change`                                                                                                           | FAIL    | `outerHost.attachShadow is not a function` |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when nested slots's contents change`                                                                                                        | FAIL    | `outerHost.attachShadow is not a function` |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when nested slots's contents change`                                                                                                       | FAIL    | `outerHost.attachShadow is not a function` |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  in a document when slots's contents change`                                                                | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  in a document when slots's contents change`                                                               | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  not in a document when slots's contents change`                                                            | FAIL    | `host.attachShadow is not a function`      |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  not in a document when slots's contents change`                                                           | FAIL    | `host.attachShadow is not a function`      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233116404)

# Sauce (safari) #
Testing web-platform-tests at revision 9c115b70a438f615bf56aa18170184bbf9bc2476
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5954/shadow-dom/slotchange-event.html">/shadow-dom/slotchange-event.html</a></summary>


|                                                                                                                 Subtest                                                                                                                 | Results |                                                                Messages                                                                |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                                                                         | ERROR   |                                                                                                                                        |
| `slotchange event must fire on a default slot element inside an open shadow root  in a document`                                                                                                                                        | PASS    |                                                                                                                                        |
| `slotchange event must fire on a default slot element inside a closed shadow root  in a document`                                                                                                                                       | PASS    |                                                                                                                                        |
| `slotchange event must fire on a default slot element inside an open shadow root  not in a document`                                                                                                                                    | PASS    |                                                                                                                                        |
| `slotchange event must fire on a default slot element inside a closed shadow root  not in a document`                                                                                                                                   | PASS    |                                                                                                                                        |
| `slotchange event must fire on a named slot element insidean open shadow root  in a document`                                                                                                                                           | PASS    |                                                                                                                                        |
| `slotchange event must fire on a named slot element insidea closed shadow root  in a document`                                                                                                                                          | PASS    |                                                                                                                                        |
| `slotchange event must fire on a named slot element insidean open shadow root  not in a document`                                                                                                                                       | PASS    |                                                                                                                                        |
| `slotchange event must fire on a named slot element insidea closed shadow root  not in a document`                                                                                                                                      | PASS    |                                                                                                                                        |
| `slotchange event must not fire on a slot element inside an open shadow root  in a document when another slot's assigned nodes change`                                                                                                  | PASS    |                                                                                                                                        |
| `slotchange event must not fire on a slot element inside a closed shadow root  in a document when another slot's assigned nodes change`                                                                                                 | PASS    |                                                                                                                                        |
| `slotchange event must not fire on a slot element inside an open shadow root  not in a document when another slot's assigned nodes change`                                                                                              | PASS    |                                                                                                                                        |
| `slotchange event must not fire on a slot element inside a closed shadow root  not in a document when another slot's assigned nodes change`                                                                                             | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  in a document`      | FAIL    | `assert_equals: slotchange must be fired on a slot element if there is assigned nodes when the slot was inserted expected 1 but got 0` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  in a document`     | FAIL    | `assert_equals: slotchange must be fired on a slot element if there is assigned nodes when the slot was inserted expected 1 but got 0` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  not in a document`  | FAIL    | `assert_equals: slotchange must be fired on a slot element if there is assigned nodes when the slot was inserted expected 1 but got 0` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  not in a document` | FAIL    | `assert_equals: slotchange must be fired on a slot element if there is assigned nodes when the slot was inserted expected 1 but got 0` |
| `slotchange event must fire on a slot element inside an open shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                 | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                             | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                            | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                        | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                       | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                    | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                   | PASS    |                                                                                                                                        |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when nested slots's contents change`                                                                                                            | FAIL    | `assert_equals: slotchange must be fired on a slot element and must bubble expected 2 but got 1`                                       |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when nested slots's contents change`                                                                                                           | FAIL    | `assert_equals: slotchange must be fired on a slot element and must bubble expected 2 but got 1`                                       |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when nested slots's contents change`                                                                                                        | FAIL    | `assert_equals: slotchange must be fired on a slot element and must bubble expected 2 but got 1`                                       |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when nested slots's contents change`                                                                                                       | FAIL    | `assert_equals: slotchange must be fired on a slot element and must bubble expected 2 but got 1`                                       |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  in a document when slots's contents change`                                                                | PASS    |                                                                                                                                        |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  in a document when slots's contents change`                                                               | PASS    |                                                                                                                                        |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  not in a document when slots's contents change`                                                            | PASS    |                                                                                                                                        |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  not in a document when slots's contents change`                                                           | PASS    |                                                                                                                                        |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233116405)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 9c115b70a438f615bf56aa18170184bbf9bc2476
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5954/shadow-dom/slotchange-event.html">/shadow-dom/slotchange-event.html</a></summary>


|                                                                                                                 Subtest                                                                                                                 | Results |                          Messages                          |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------|
|                                                                                                                                                                                                                                         | OK      |                                                            |
| `slotchange event must fire on a default slot element inside an open shadow root  in a document`                                                                                                                                        | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a default slot element inside a closed shadow root  in a document`                                                                                                                                       | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a default slot element inside an open shadow root  not in a document`                                                                                                                                    | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a default slot element inside a closed shadow root  not in a document`                                                                                                                                   | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a named slot element insidean open shadow root  in a document`                                                                                                                                           | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a named slot element insidea closed shadow root  in a document`                                                                                                                                          | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a named slot element insidean open shadow root  not in a document`                                                                                                                                       | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a named slot element insidea closed shadow root  not in a document`                                                                                                                                      | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must not fire on a slot element inside an open shadow root  in a document when another slot's assigned nodes change`                                                                                                  | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must not fire on a slot element inside a closed shadow root  in a document when another slot's assigned nodes change`                                                                                                 | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must not fire on a slot element inside an open shadow root  not in a document when another slot's assigned nodes change`                                                                                              | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must not fire on a slot element inside a closed shadow root  not in a document when another slot's assigned nodes change`                                                                                             | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  in a document`      | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  in a document`     | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside an open shadow root  not in a document`  | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element when a shadow host has a slotable and the slot was inserted and must not fire when the shadow host was mutated after the slot was removed inside a closed shadow root  not in a document` | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                 | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                                | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                             | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document even if the slot was removed immediately after the assigned nodes were mutated`                                                            | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                        | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when innerHTML modifies the children of the shadow host`                                                                                       | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                    | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when innerHTML modifies the children of the shadow host`                                                                                   | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  in a document when nested slots's contents change`                                                                                                            | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  in a document when nested slots's contents change`                                                                                                           | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside an open shadow root  not in a document when nested slots's contents change`                                                                                                        | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire on a slot element inside a closed shadow root  not in a document when nested slots's contents change`                                                                                                       | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  in a document when slots's contents change`                                                                | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  in a document when slots's contents change`                                                               | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside an open shadow root  not in a document when slots's contents change`                                                            | FAIL    | `Object doesn't support property or method 'attachShadow'` |
| `slotchange event must fire at the end of current microtask after mutation observers are invoked inside a closed shadow root  not in a document when slots's contents change`                                                           | FAIL    | `Object doesn't support property or method 'attachShadow'` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233116411)

# Chrome (unstable) #

**Comment by hayatoito** [comment]
I have updated the PR so that it reflects the latest whatwg/dom#459.
@rniwa Could you have a chance to take a look?
We might want to clean up tests further, but this PR could be good enough to catch up the DOM Standard's change.

cc: @domenic

**Comment by hayatoito** [comment]
@TakayoshiKochi Could you review this too?

**Comment by TakayoshiKochi** [comment]
LGTM

**Review by TakayoshiKochi — APPROVED** [review]
LGTM

**Pull request merged**
