### PR TITLE
[css-overflow] Inheritance and initial values

### PR DESCRIPTION
**Pull request by ewilligers**
Test that CSS Overflow properties inherit.
Test that they have the initial values given in the spec.
https://drafts.csswg.org/css-overflow/#property-index

### CODE REVIEW

**Comment by foolip** [comment]
The failing Travis build in this PR was due to https://github.com/web-platform-tests/wpt/issues/13112, which has now been resolved. To recover, rebase the PR on master and push. (Simply restarting the Travis jobs may also work, not tested.)

**Comment by ewilligers** [comment]
@dbaron  Please review

**Review by frivoal — CHANGES_REQUESTED** [review]
The test looks correct based on the spec, but the spec seems to have an issue. how can overflow-block and overflow-inline have `auto` as the initial value, when overflow-x and overflow-y have `visible` as the initial value? That made no sense (and I had introduced that mistake), so I've fixed in in https://github.com/w3c/csswg-drafts/commit/60fc9bf33b3d8e8c5f7c8e37b9ed9aaf194f0286. If you can update the test to match that, then it will be good to merge.

**Comment by ewilligers** [comment]
@frivoal I have updated the test.

**Review by frivoal — APPROVED** [review]

**Comment by frivoal** [comment]
Looks good. Ready to merge, but Taskcluster seems stuck.
@gsnedders @foolip @Ms2ger

**Pull request merged**
