### PR TITLE
[wdspec] fix C-s typo override on wait_for_future_safe

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Comment by thiagowfx** [comment]
This was a typo caused by the previous PR (attempt to hit C-s to save the document but ended up missing the Ctrl key).

**Review by whimboo — COMMENTED** [review]
Before merging PRs please check at least the wpt.fyi results to detect those regressions. I usually do that on top when I review PRs.

Which PR regressed this in detail?

**Comment by thiagowfx** [comment]
It was this one: https://github.com/web-platform-tests/wpt/pull/43232

I'm used to relying on CI to block obvious breakages, especially as there are 19(!) checks. It creates a false sense of security to see (all?) the checks green, yet some obvious regression gets introduced.

**Comment by thiagowfx** [comment]
> Before merging PRs please check at least the wpt.fyi results to detect those regressions. 

But yes, I suppose it's the only way to be sure. I'll do that in future PRs.

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
