### PR TITLE
HTMLMediaElement.play() should return a Promise

### PR DESCRIPTION
**Pull request by cdumez**
HTMLMediaElement.play() should return a Promise as per:
https://html.spec.whatwg.org/#htmlmediaelement

### CODE REVIEW

**Comment by cdumez** [comment]
ping?

**Comment by cdumez** [comment]
Looks like this change to the specification was made in:
https://github.com/whatwg/html/pull/509

But the web-platform-tests were not updated accordingly.

@domenic @foolip @mounirlamouri ?

**Comment by zcorpan** [comment]
Thanks!

**Comment by foolip** [comment]
Thanks @cdumez !

**Pull request merged**
