### PR TITLE
Fix broken Pointer Lock IDL tests

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26703)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/360467379)

**Comment by foolip** [comment]
Context: [Find and investigate [something] every week](https://docs.google.com/document/d/1kFYTqUMEbo9p87i6wAzORoicMWgHsuYwL2CgtvdhDaE/edit#heading=h.6lssu2bocbaz)

**Review by lukebjerring — COMMENTED** [review]
Sorry, this slipped under the radar months ago.

I think we'd be better off using the new `{only: 'EventInit'...}` or wait for https://github.com/w3c/web-platform-tests/pull/10381

**Review by lukebjerring — APPROVED** [review]
@foolip - I took the liberty of updating your PR.. and approve my own work.

**Pull request merged**
