### PR TITLE
Add Web IDL OWNERS

### LINKED ISSUE #5892: Assembling an OWNERS file for Web IDL
Who wants in? This means you'll get pinged whenever there's a test PR for the WebIDL/ directory.

/ccing some potential people. I'll work on a PR after a day or two containing the people who chime in here. Please feel free to direct your colleagues here too.

@domenic @bzbarsky @tobie @yuki3 @jensl @nox @samweinig

### PR DESCRIPTION
**Pull request by domenic**
Closes #5892.

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Review by gsnedders — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233339192)

# Firefox (nightly) #
Testing web-platform-tests at revision a7345a6b299c92952c7d31f3397d43120005d925
Using browser at version BuildID 20170517100341; SourceStamp 6e3ca5b38f7173b214b10de49e58cb01890bf39d
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233339193)

# Sauce (safari) #
Testing web-platform-tests at revision a7345a6b299c92952c7d31f3397d43120005d925
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233339199)

# Chrome (unstable) #
Testing web-platform-tests at revision a7345a6b299c92952c7d31f3397d43120005d925

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233339200)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision a7345a6b299c92952c7d31f3397d43120005d925

**Pull request merged**
