### PR TITLE
Run `./wpt test-jobs --all` to see if all tests pass

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@LukeZielinski I was attempting in https://github.com/web-platform-tests/wpt/pull/17217/commits/143c349109f73b7f813b4bd8390566e7447b788c to mark a failure as expected, but then the failure shifted somewhere else. This is very reminiscent of something you were telling me about debugging these tests, was it state in ChromeDriver leaking between them? Were you able to get to the bottom of that?

This job isn't blocking, but it will be failing on all PRs which trigger the tests. Should we just disable them?

**Comment by foolip** [comment]
@Ms2ger there are now failures on master in test_tests_affected_null, and my best guess is that it's related to https://github.com/web-platform-tests/wpt/pull/18787, although it's not obvious how.

Can you check if it was a regression from that change?

**Comment by Ms2ger** [comment]
Don't you think it might be #18743 and #18688?

**Comment by foolip** [comment]
Possibly, but they landed longer ago. Will have to bisect I guess...

**Comment by gsnedders** [comment]
Yeah, it's the issues @Ms2ger linked to. I'd noticed this last week just before heading off and never got around to filing a bug for it. :/

**Comment by foolip** [comment]
Fixed in https://github.com/web-platform-tests/wpt/pull/18819. I'll close this PR and open a new one so that y'all don't have to be notified when I keep rebasing it.

**Pull request closed without merging**
