### PR TITLE
Fix css-nesting parsing typo

### PR DESCRIPTION
**Pull request by mdubet**
https://wpt.fyi/results/css/css-nesting/parsing.html?label=experimental&label=master&aligned

### CODE REVIEW

**Review by tabatkins — APPROVED** [review]

**Comment by tabatkins** [comment]
I swear I made that edit already, but in any case, thanks!

**Comment by emilio** [comment]
@tabatkins are the expectations here correct? At the very least this probably needs:

```
diff --git a/testing/web-platform/tests/css/css-nesting/parsing.html b/testing/web-platform/tests/css/css-nesting/parsing.html
index b189190f41257..3ef3811b311cb 100644
--- a/testing/web-platform/tests/css/css-nesting/parsing.html
+++ b/testing/web-platform/tests/css/css-nesting/parsing.html
@@ -42,7 +42,7 @@
   testNestedSelector("&.bar");
   testNestedSelector("& .bar");
   testNestedSelector("& > .bar");
-  testNestedSelector("> & .bar");
+  testNestedSelector("> & .bar", {expected: "& > & .bar" });
   testNestedSelector("> .bar", {expected:"& > .bar"});
   testNestedSelector("+ .bar &", {expected:"& + .bar &"});
   testNestedSelector(".test > & .bar");
```

As otherwise the selector is invalid in non-nested contexts?

But this also expects that ampersands are introduced if not there already for non-relative selectors, in some cases even for non-relative selectors, which is very weird?

E.g, the test expects: `.bar, .foo &` to get turned into `& .bar, .foo &`, which doesn't seem necessary? All browsers right now serializes that as `.bar, .foo &` which seems fine, since it's not an invalid selector list in any context.

Just wanted to double-check the expectations before changing behavior here...

**Comment by emilio** [comment]
Also `testNestedSelector(":is(.bar, .baz)", {expected:"&:is(.bar, .baz)"});` should probably be `& :is(.bar, .baz)` (note the extra space)?

**Comment by emilio** [comment]
(If we want to do that, which per my previous comment we might not...)

**Comment by tabatkins** [comment]
...sigh, the reason I was so confused is that I did fix a lot of these issues in <https://github.com/web-platform-tests/wpt/pull/41050/>, but that never merged.

**Comment by tabatkins** [comment]
```
-  testNestedSelector("> & .bar");
+  testNestedSelector("> & .bar", {expected: "& > & .bar" });
```

Yup.

> But this also expects that ampersands are introduced if not there already for non-relative selectors, in some cases even for non-relative selectors, which is very weird?

Hm, you're right, I just misinterpreted the resolution. Curiously enough, I wrote the spec correctly, matching the resolution.

Both of these are fixed in #41213.

**Comment by emilio** [comment]
Thanks!

**Pull request merged**
