### PR TITLE
XMLHttpRequest: update Document serialization test

### PR DESCRIPTION
**Pull request by annevk**
Serialization can never fail: https://github.com/whatwg/xhr/issues/120.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5123/)

**Comment by annevk** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=169554 on WebKit.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210567727)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d2de22cd3c1f09726c57bac8fb40c694866bd6af
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5123/XMLHttpRequest/send-entity-body-document-bogus.htm">/XMLHttpRequest/send-entity-body-document-bogus.htm</a></summary>


|                             Subtest                             | Results | Messages |
|-----------------------------------------------------------------|---------|----------|
|                                                                 | OK      |          |
| `XMLHttpRequest: send() - Document with serialization errors`   | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 1` | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 2` | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 3` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210567728)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d2de22cd3c1f09726c57bac8fb40c694866bd6af
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5123/XMLHttpRequest/send-entity-body-document-bogus.htm">/XMLHttpRequest/send-entity-body-document-bogus.htm</a></summary>


|                             Subtest                             | Results | Messages |
|-----------------------------------------------------------------|---------|----------|
|                                                                 | OK      |          |
| `XMLHttpRequest: send() - Document with serialization errors`   | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 1` | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 2` | PASS    |          |
| `XMLHttpRequest: send() - Document with serialization errors 3` | PASS    |          |

</details>
</details>

**Review by jdm — CHANGES_REQUESTED** [review]

**Pull request merged**
