### PR TITLE
Mark Trusted Types tests as not tentative

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@otherdaniel you said most or maybe all of these tests should no longer be tentative, so let's figure it out in a review. If none of the tests call out for special attention, I'd suggest randomly picking 5 tests out of the renamed ones, and linking to the spec(s) that cover those.

**Comment by otherdaniel** [comment]
>  I'd suggest randomly picking 5 tests out of the renamed ones, and linking to the spec(s) that cover those.

That makes sense. I randomly picked all of them - which admittedly makes the result a bit unwieldy to read. I didn't check all tests line-for-line, but in the checking I didn't find any tests that tried to test for behaviour that isn't specced. (I did find one bit in the spec that has no tests associated with it, and that I think we never implemented. I'll file that as a bug against the spec.)

Here's a mapping of spec chapters to tests. Admittedly, this mapping is a bit arbitrary, since the tests were written partially before and during the spec being written, and hence oftentimes don't cleanly map to one specific spec chapter. 

------------------

### "Generic" tests, that don't map to a single spec chapter
- trusted-types/HTMLElement-generic.html
- trusted-types/block-string-assignment-to-HTMLElement-generic.html
- trusted-types/idlharness.tentative.window.js
- trusted-types/trusted-types-createHTMLDocument.html

### TrustedHTML/Script/ScriptURL basic methods: https://www.w3.org/TR/trusted-types/#trusted-types
- trusted-types/trusted-types-tojson.tentative.html
- trusted-types/trusted-types-from-literal.tentative.html

### Document interface: https://www.w3.org/TR/trusted-types/#extensions-to-the-document-interface 
- trusted-types/Document-write.html
- trusted-types/block-string-assignment-to-Document-write.html

### Scripts / internal slot: https://www.w3.org/TR/trusted-types/#enforcement-in-scripts
- trusted-types/HTMLScriptElement-internal-slot.html
- trusted-types/HTMLScriptElement-in-xhtml-document.https.xhtml
- trusted-types/block-text-node-insertion-into-script-element.html
- trusted-types/block-Node-multiple-arguments.html
- trusted-types/Node-multiple-arguments.html

### Element attributes: https://www.w3.org/TR/trusted-types/#enforcement-in-sinks, also  https://www.w3.org/TR/trusted-types/#integration-with-dom
- trusted-types/block-string-assignment-to-Element-setAttributeNS.html
- trusted-types/block-string-assignment-to-attribute-via-attribute-node.html
- trusted-types/Element-setAttribute.html
- trusted-types/block-string-assignment-to-Element-setAttribute.html
- trusted-types/TrustedType-AttributeNodes.html
- trusted-types/Element-setAttributeNS.html

### Timer functions: https://www.w3.org/TR/trusted-types/#enforcement-in-timer-functions
- trusted-types/block-string-assignment-to-DOMWindowTimers-setTimeout-setInterval.html
- trusted-types/DOMWindowTimers-setTimeout-setInterval.html

### Event handlers: https://www.w3.org/TR/trusted-types/#enforcement-in-event-handler-content-attributes 
- trusted-types/GlobalEventHandlers-onclick.html
- trusted-types/trusted-types-event-handlers.html


### Web Workers and Service Workers: https://www.w3.org/TR/trusted-types/#html-workers and  https://www.w3.org/TR/trusted-types/#sw-integration
- trusted-types/worker-constructor.https.html 
- trusted-types/WorkerGlobalScope-importScripts.html
- trusted-types/WorkerGlobalScope-eval.html

### SVG: https://www.w3.org/TR/trusted-types/#integration-with-svg
- trusted-types/trusted-types-svg-script.html

### DOM: https://www.w3.org/TR/trusted-types/#integration-with-dom
- (covered in Element attributes)

### DOM parsing APIs: https://www.w3.org/TR/trusted-types/#integration-with-dom-parsing 
- trusted-types/Element-outerHTML.html
- trusted-types/Range-createContextualFragment.html
- trusted-types/Element-insertAdjacentText.html
- trusted-types/DOMParser-parseFromString.html
- trusted-types/Element-insertAdjacentHTML.html
- trusted-types/block-string-assignment-to-Element-outerHTML.html
- trusted-types/block-string-assignment-to-Range-createContextualFragment.html
- trusted-types/block-string-assignment-to-Element-insertAdjacentHTML.html
- trusted-types/block-string-assignment-to-DOMParser-parseFromString.html
- trusted-types/DOMParser-parseFromString-regression.html

### execCommand: https://www.w3.org/TR/trusted-types/#integration-with-exec-command
- trusted-types/block-Document-execCommand.html
- trusted-types/Document-execCommand.html

### Policies: creation, default policy, etc.: https://www.w3.org/TR/trusted-types/#trusted-type-policy-factory 
- trusted-types/Window-TrustedTypes.html
- trusted-types/TrustedTypePolicyFactory-defaultPolicy.html
- trusted-types/TrustedTypePolicyFactory-isXXX.html
- trusted-types/TrustedTypePolicyFactory-constants.html
- trusted-types/TrustedTypePolicyFactory-blocking.html
- trusted-types/TrustedTypePolicy-createXXX.html
- trusted-types/TrustedTypePolicyFactory-getAttributeType-namespace.html
 -trusted-types/TrustedTypePolicyFactory-getPropertyType.html
 -trusted-types/TrustedTypePolicyFactory-createPolicy-nameTests.html
 -trusted-types/TrustedTypePolicyFactory-metadata.html
 -trusted-types/TrustedTypePolicyFactory-createPolicy-unenforced.html
 -trusted-types/TrustedTypePolicyFactory-createPolicy-createXYZTests.html
 -trusted-types/empty-default-policy.html
 -trusted-types/default-policy-callback-arguments.html
 -trusted-types/default-policy.html

### CSP: https://www.w3.org/TR/trusted-types/#integration-with-content-security-policy
- _(This is quite a grab bag of tests. I found it a bit difficult to seperate them into smaller groups.)_
- trusted-types/trusted-types-duplicate-names-list.html
- trusted-types/no-require-trusted-types-for.html
- trusted-types/TrustedTypePolicyFactory-createPolicy-cspTests-none.html
- trusted-types/TrustedTypePolicy-CSP-no-name.html
- trusted-types/TrustedTypePolicy-CSP-wildcard.html
- trusted-types/TrustedTypePolicyFactory-createPolicy-cspTests-noNamesGiven.html
- trusted-types/TrustedTypePolicyFactory-createPolicy-cspTests-wildcard.html
 -trusted-types/TrustedTypePolicyFactory-createPolicy-cspTests.html
 -trusted-types/TrustedTypePolicyFactory-createPolicy-cspTests-none-skip.html
 -trusted-types/trusted-types-duplicate-names.html
- trusted-types/require-trusted-types-for-report-only.html
- trusted-types/no-require-trusted-types-for-report-only.html
- trusted-types/require-trusted-types-for.html
- trusted-types/csp-block-eval.html
- trusted-types/eval-csp-tt-no-default-policy.html
- trusted-types/eval-with-permissive-csp.html
- trusted-types/eval-function-constructor.html
- trusted-types/eval-no-csp-no-tt.html
- trusted-types/eval-csp-no-tt.html
- trusted-types/eval-csp-tt-default-policy.html
- trusted-types/tt-block-eval.html
- trusted-types/eval-no-csp-no-tt-default-policy.html
- trusted-types/trusted-types-report-only.html
- trusted-types/trusted-types-duplicate-names-list-report-only.html
- trusted-types/trusted-types-duplicate-names-without-enforcement.html

### CSP reporting
- _(Technically a sub-group of CSP above. But all of these deal with CSP reports and reporting events.)_
- trusted-types/trusted-types-reporting-check-report.html
- trusted-types/trusted-types-reporting.html
- trusted-types/trusted-types-eval-reporting-no-unsafe-eval.html
- trusted-types/trusted-types-eval-reporting.html
- trusted-types/trusted-types-eval-reporting.html.headers
- trusted-types/trusted-types-eval-reporting-report-only.html
- trusted-types/empty-default-policy-report-only.html
- trusted-types/default-policy-report-only.html
- trusted-types/trusted-types-source-file-path.html
- trusted-types/trusted-types-navigation.html

**Review by otherdaniel — APPROVED** [review]
Looks good to me. I posted a mapping of spec chapters to tests in the comments, to make sure these are actually covered by spec text.

**Comment by foolip** [comment]
Thank you @otherdaniel for the thorough review, it's much appreciated! Good that it also turned up some unimplemented and untested bits of the spec, so that can be remedied somehow.

I'll go ahead and merge this.

**Pull request merged**
