### PR TITLE
Added 24 tests and 6 references to cover issue 3066

### PR DESCRIPTION
**Pull request by TalbotG**
This is a followup-to [PR 18112](https://github.com/web-platform-tests/wpt/pull/18112).
These 24 tests, 6 reference files and 1 support file are closely related to the resolving of
[Issue 3066: [css-writing-modes] Does vertical writing mode of an HTML body element cause an orthogonal flow?](https://github.com/w3c/csswg-drafts/issues/3066)

@frivoal Florian,
I have adopted each and all of your corrections and suggestions listed in PR 18112. I wanted to continue to use pull request 18112 to make those modifications but could not (I am not mastering github yet) .

Again, once this pull request has been reviewed, approved and merged, then I (or someone else) can delete the following 5 unneeded tests and 1 reference file:

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-006.xht

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-008.xht

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-010.xht

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-011.xht

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-015.xht

http://web-platform-tests.live/css/css-writing-modes/wm-propagation-body-003-ref.xht

### CODE REVIEW

**Review by frivoal — CHANGES_REQUESTED** [review]
* The two margins added to the div in tests -033, -037 are wrong: they make the test pass in error cases, and they should be removed. If the writing-mode is propagated from the body to the html element, then the box and the text will be aligned correctly without any margin. If it is not propagated, they will not align correctly, but we should not compensate, we should just let the test fail.
* test -047 passes if sideways-lr is supported even if it is not propagated. Just like we fixed -042, we should add this too (sorry for not catching it the first time):
    ```css
    html::before
    {
      content: "This text must be written sideways: vertically, with letters rotated 90 degrees.";
      text-orientation: upright; /* this has no effect with sideways-rl, but does with vertical-rl*/
    }
    ```

**Comment by frivoal** [comment]
The fixes are quite small, I'm doing them myself.

**Review by frivoal — APPROVED** [review]
Made the fixes I suggested, plus some cosmetic adjustments.

**Comment by frivoal** [comment]
> once this pull request has been reviewed, approved and merged, then I (or someone else) can delete the following 5 unneeded tests and 1 reference file:

https://github.com/web-platform-tests/wpt/pull/18125

**Comment by TalbotG** [comment]
> The two margins added to the div in tests -033, -037 are wrong: they make the test pass in error cases, and they should be removed.

After a long examination, you are correct!

There may be another problem with -033-ref : there should be no gap between the orange square and the image that says "Test passes if there is an orange square in the upper-left corner of the page."

This file
http://www.gtalbot.org/BrowserBugsSection/CSS3WritingModes/wm-propagation-body-033-ref-2.html
is a closer and more exact representation of what the -033 and -037 tests should be rendering.

**Comment by frivoal** [comment]
Good catch. -033-ref is used by a few more files, which did use it correctly, so I found it easier to fix -033 and -037 than the ref and -040, -041, -048, -050, and -052. Fixing this with https://github.com/web-platform-tests/wpt/pull/18141

**Comment by TalbotG** [comment]
> I found it easier to fix -033 and -037 than the ref and -040, -041, -048, -050, and -052.

This is best.

Thank you! :)

**Pull request merged**
