### PR TITLE
Test current Realm (still to be defined in more detail)

### PR DESCRIPTION
**Pull request by annevk**
Create a test based on http://web.mit.edu/bzbarsky/www/testcases/global-object-association/createImageData.html to see what the global object is for various things.

### CODE REVIEW

**Comment by annevk** [comment]
Rebased and squashed this. @bzbarsky, should we commit this? I don't really remember the context anymore and whether Web IDL covers this already or not.

**Comment by bzbarsky** [comment]
@annevk The context is that IDL requires specs to define which global their objects are associated with but specs by and large don't do that.  UA behavior is not terribly consistent in practice on some of the more interesting cases.

So we need to get several things to happen:

1. Specs actually define the behavior.
2. Tests test for that behavior.
3. UAs implement the behavior.

The PR here is for item #2 of that, right?

**Comment by annevk** [comment]
It is, but I also remember having a proposal for how 1 could be largely solved by IDL except for a few cases. I think that's why we ended up writing these tests, but unfortunately I didn't link from this PR to that discussion.

**Comment by bzbarsky** [comment]
Item 1 (God, I wish github didn't mangle '#' for me) can mostly be solved by saying that the associated global of an object created via a DOM API call is the associated global of the "this" value, I think.  Trying to recall what the exceptions to that would be....

Or were we talking about using the callee function Realm except for some exceptions?

**Comment by annevk** [comment]
A DOM API call being a call going through IDL? Anyway, I don't remember what exactly it was we thought we should do here. Just that I wanted IDL to handle it and you wanted to see tests first.

**Comment by bzbarsky** [comment]
Well, I wanted to see what browsers do right now, so we could evaluate what the handling in IDL should look like.

**Comment by annevk** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=24652 is the corresponding specification bug for this set of tests.

**Comment by bzbarsky** [comment]
To add to the list from <https://github.com/w3c/web-platform-tests/pull/1381#issuecomment-62585881>:

8) The global of the async-created key returned from WebCrypto stuff.  Note that webcrypto is known non-interoperable across browsers; see https://www.w3.org/Bugs/Public/show_bug.cgi?id=29514

**Comment by annevk** [comment]
@jgraham according to @bzbarsky we routinely land tests not covered by standards. Perhaps this could be one of those?

**Comment by annevk** [comment]
Please explain what you did here @ayg.

**Comment by ayg** [comment]
@annevk I accidentally did git push --mirror to the w3c repo instead of mine, due to incorrect .git/config (since fixed), and didn't have any idea how to fix it.  I e-mailed @jgraham and @Ms2ger because they were the people I thought of off the top of my head, but if you know how to fix it, please do.

**Comment by annevk** [comment]
No 😟

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by annevk** [comment]
Going to land this per discussion with @jgraham on IRC (#whatwg).

**Comment by Anamazina** [comment]
> @annevk Спасибо, что написали этот тест!
> 
> Некоторые другие вещи, которые, как я подозреваю, стоит проверить:
> 
> 1. API global of crypto обещает возвращать значения, когда методы из одного глобального применяются к crypto.subtle другого глобального.
> 2. Глобальные обещания FontFace / FontFaceSet.
> 3. Глобальный набор `getElementsByTagName`возвращаемых значений.
> 4. Глобальный набор `NamedNodeMap.prototype.getNamedItem`возвращаемых значений.
> 5. Возвращаемое значение `getImageData`(вместо `createImageData`).
> 6. Возвращаемое значение таких вещей, как `createImageBitmap`где оно поддерживается; как возвращаемое обещание, так и значение, с которым обещание в конечном итоге разрешается. В частности, зависит ли это от глобальности аргумента.
> 7. Глобальное значение возвращаемого значения `HTMLCanvasElement.prototype.getContext`.

Да ладно

**Pull request merged**
