### PR TITLE
Bump flake8 and related dependencies

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This is blocked on https://github.com/web-platform-tests/wpt/pull/39110

**Review by gsnedders — APPROVED** [review]

**Comment by foolip** [comment]
@gsnedders there are a lot of failures like this:

```
./ci/tc/github_checks_output.py:4:5: F401 'typing.Optional' imported but unused
```

They all have to do with type annotations. There are two options:

1. Disable F401 in this PR and enable again in a PR that lands after the mypy changes
2. Combine flake8 and mypy changes into a single bigger PR

Which do you prefer?

@jgraham may also have preferences.

**Comment by foolip** [comment]
Oh, and option 3 is to wait until after the mypy changes to land this, but still as a separate PR.

**Comment by jgraham** [comment]
These patches and subsequent fixes landed in #39843

**Pull request closed without merging**
