### PR TITLE
"ownership" of a SpeechSynthesisUtterance is not defined by the specification

### LINKED ISSUE #23097: speech-api/SpeechSynthesis-speak-ownership.html is incomplete; renders inaccurate results; should be removed from WPT pending specification clarification [type:untestable]
https://github.com/web-platform-tests/wpt/blob/master/speech-api/SpeechSynthesis-speak-ownership.html links to https://github.com/WICG/speech-api/issues/8 which does not settle at all precisely what the concept of "ownership" is in the Web Speech API specification, where the term used exactly once

> [4.2.2. SpeechSynthesis Methods](https://wicg.github.io/speech-api/#tts-methods)
`speak(utterance)` method
> 
> The SpeechSynthesis object takes exclusive ownership of the SpeechSynthesisUtterance object. Passing it as a speak() argument to another SpeechSynthesis object should throw an exception. (For example, two frames may have the same origin and each will contain a SpeechSynthesis object.)

with no accompanying definition of the term or algorithm clearly describing how "ownership" is set or thereafter verified programmatically.

The language used is _should_ throw an exception, not MUST throw an exception.

Nor is there any explanation as to _why_ an exception "should" be thrown in that case.

In practice, it _is_ possible to differentiate `speechSynthesis` instances, depending on the implementation, not the specification, because `speechSynthesis.speak()` calls _could_ be added to _the_ same global queue, if, for example, the implementer routes all `speak()` calls to a single local speech synthesis socket connection application (for the browsers where a speech synthesis engine is not shipped by default with the source code, e.g., Chromium), where it is possible to call `cancel()`  at a _different_ `window` from a closed `window` that initiated a `speak()` call and thereby clear _the_ queue in the socket connection for all pending `speak()` call, for _every_ `window`: there is limited consistency at implementations because the specification is ambiguous in certain locations. The specification does not state that calling `cancel()` should only affect a _single_ queue

> This method removes all utterances from the queue. 

note the singular _the_ queue.

For example, if `speechSynthesis.pause()` is executed at Chromium before calling `speak()`, neither `iframe.contentWindow.speak()` nor `speechSynthesis.speak()` will output audio, `iframe.contentWindow.speechSynthesis.pending` _and_ `speechSynthesis` will always be `false`. Nightly _does_ output audio for `iframe.contentWindow.speak()` (because that "instance" of `speechSynthesis` was not paused) and sets `speechSynthesis.pending` to `true`.

The test will always fail because there is no documentation or algorithm or implementation of the concept of "ownership" of a `SpeechSynthesisUtterance` object resulting in `threw` always being `false`, which means the test results are inaccurate: What specific language in the specification is the current test relying on for how to determine "ownership" of a `SpeechSynthesisUtterance` by a particular call or reference to `speechSynthesis`, and exactly how is that verification done in the test? 

Presently, it is impossible to programmatically determine the "ownership" of a `SpeechSynthesisUtterance` instance because no such concept exists in practice. Therefore, the test, is incomplete and inaccurate, and without clarity in the specification, should be removed from the WPT tests until the specification is clear, as it is currently impossible to verify "ownership" of a `SpeechSynthesisUtterance` instance relying solely on the language in the specification.

### PR DESCRIPTION
**Pull request by guest271314**
Fixes https://github.com/web-platform-tests/wpt/issues/23097

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by marcoscaceres** [comment]
I'm unsure what to do about the the CI failure.

**Comment by stephenmcgruer** [comment]
Infra flake, sorry. I'll kick it to retry.

**Comment by guest271314** [comment]
Chrome not downloading?
```
ERROR: Connection reset by peer. Retrying after 1s...
INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 2/3
ERROR: Connection reset by peer. Retrying after 2s...
INFO: Downloading https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb Try 3/3
```

**Comment by stephenmcgruer** [comment]
Correct, this is https://github.com/web-platform-tests/wpt/issues/21529 (we're working on it, we're sorry it's causing problems). Admin-merging this time.

**Pull request merged**
