### PR TITLE
Encoding/XMLHttpRequest: default is UTF-8

### LINKED ISSUE #14082: unsupported-encodings.any.js expects XHR text response to default to windows-1252
Fails in Gecko:
https://wpt.fyi/results/encoding/unsupported-encodings.any.worker.html?label=experimental
https://wpt.fyi/results/encoding/unsupported-encodings.any.html?label=experimental

The test uses XHR:
https://github.com/web-platform-tests/wpt/blob/master/encoding/unsupported-encodings.any.js

XHR spec says the default is UTF-8:
https://xhr.spec.whatwg.org/#text-response

Test wrongly expects the default to be windows-1252.

### PR DESCRIPTION
**Pull request by annevk**
Fixes #14082.

### CODE REVIEW

**Review by inexorabletash — APPROVED** [review]
lgtm!

**Comment by ricea** [comment]
Nit: comment still says
```
// UTF-32 will be detected as UTF-16LE if leading BOM, or windows-1252 otherwise.
```

**Comment by annevk** [comment]
Fix coming up.

**Comment by annevk** [comment]
https://github.com/web-platform-tests/wpt/pull/14126

**Pull request merged**
