### PR TITLE
mv payments policy tests to /feature-policy/

### LINKED ISSUE #6899: Cross-origin Payment Request in Payment Allowed By Feature Policy
In https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-allowed-by-feature-policy.https.sub.html#L32
The test expects a payment request to succeed when launched from a cross-origin iframe and without the `allowpaymentrequest` attribute. This is against the W3C spec for web payment requests, so it fails for browsers that implement the spec. The function passed in the `async_test` call should be `expect_feature_unavailable_default`.

### PR DESCRIPTION
**Pull request by marcoscaceres**
* closes #6899, #6812

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18422)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/274418574)

**Review by clelland — APPROVED** [review]
If this pattern repeats for a large number of other APIs, we may want to move this into /feature-policy/features/payment-request/ or something similar, but I don't think there's any need to impose that kind of structure yet.

**Comment by clelland** [comment]
(Also, I may not be allowed to approve the change that makes me an owner -- it might have to be done in two steps, or someone else may need to approve this one)

**Comment by marcoscaceres** [comment]
cc @sideshowbarker for super powers.

**Comment by marcoscaceres** [comment]
> If this pattern repeats for a large number of other APIs, we may want to move this into /feature-policy/features/payment-request/ or something similar, but I don't think there's any need to impose that kind of structure yet.

Agree. That would be nice. I'm not a huge fan of the tests with the massively long filenames. Prefer they were in nicely organized folders.

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
