### PR TITLE
Revert "Drop funcsigs"

### PR DESCRIPTION
**Pull request by nt1m**
This reverts commit ef70ce9623f50e9e7a89bb713920588cfb1259cf.

This broke the WebKit import-w3c-tests script, reverting until someone has time to look more closely into it.

### CODE REVIEW

**Comment by nt1m** [comment]
```
ntim @ OpenSource ⚡️ import-w3c-tests -t web-platform-tests/fullscreen                          
Downloading W3C test repositories
Fetching https://github.com/web-platform-tests/wpt.git...
Checking out revision origin/master
Traceback (most recent call last):
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/import-w3c-tests", line 35, in <module>
    sys.exit(test_importer.main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/webkitpy/w3c/test_importer.py", line 98, in main
    test_importer.do_import()
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/webkitpy/w3c/test_importer.py", line 208, in do_import
    self.test_downloader().download_tests(self.source_directory, self.test_paths, self.options.use_tip_of_tree)
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/webkitpy/w3c/test_downloader.py", line 228, in download_tests
    self.copy_tests(destination_directory, test_paths)
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/webkitpy/w3c/test_downloader.py", line 181, in copy_tests
    self._filesystem.copyfile(source_path, destination_path)
  File "/Volumes/Data/Code/Safari/OpenSource/Tools/Scripts/webkitpy/common/system/filesystem.py", line 83, in copyfile
    return shutil.copyfile(source, destination)
  File "/AppleInternal/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Data/Code/Safari/OpenSource/WebKitBuild/w3c-tests/web-platform-tests/tools/third_party/funcsigs/docs/index.rst'
```

**Comment by nt1m** [comment]
I can confirm that reverting this commit fixes the import-w3c-tests script. cc @gsnedders

**Review by marcoscaceres — APPROVED** [review]

**Comment by annevk** [comment]
cc @web-platform-tests/admins

**Comment by jdm** [comment]
This also broke servo's import, and the revert fixed it.

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/wpt/commit/ef70ce9623f50e9e7a89bb713920588cfb1259cf left tools/third_party/funcsigs/docs/index.rst as a symlink to the (non-existent) `tools/third_party/funcsigs/docs/README.rst`, which I believe is the origin of all the problems here.

**Pull request merged**
