### PR TITLE
[GitHub Actions] run manifest_build.py directly on Ubuntu 18.04

### LINKED ISSUE #19380: manifest-build-and-tag spends most time in Docker build step
The manifest-build-and-tag jobs on GitHub Actions ([example](https://github.com/web-platform-tests/wpt/runs/239302415)) are what add merge_pr_* tags and upload the manifest as a release asset for that tag.

These jobs seem to usually take more than 4 minutes, almost all of it spend building the [Docker image](https://github.com/web-platform-tests/wpt/blob/master/tools/docker/github/Dockerfile).

I suspect the image can't be cached because the `apt-get -qqy update` step does something different on every invocation.

Since we're running Ubuntu 18.04, there isn't much of a reason to use Docker since GitHub Actions provides those images directly, and we could run the exact same steps in those images, with no greater risk of breakage it seems.

The manifest release being delayed isn't a big problem, but it is a bit silly.

@jugglinmike FYI.

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt/issues/19380.

Running faster increases the risk that the GitHub search API can't
find the pull request yet, so add retry.py with a --delay value that
with 5 iterations adds up to a total of 15 minutes waiting.

### CODE REVIEW

**Comment by foolip** [comment]
In https://github.com/web-platform-tests/wpt/commit/192914f7083de9ae2d5add87ed260a1036601e0f#r35409518 @jgraham asked:

> Wouldn't an alternative be just to upload this image to dockerhub, and they we could also avoid needing to instal zstd or other deps?

That would indeed be possible, and might be 15-30 seconds faster than this if the docker image is cached, but the dependencies are so few/simple here that I'm not sure the extra work of maintaining/updating the image are worth it.

@jugglinmike thoughts?

**Comment by foolip** [comment]
Comparing these two checks gives an idea about the speed improvement:
https://github.com/web-platform-tests/wpt/runs/253789228 (master)
https://github.com/web-platform-tests/wpt/pull/19580/checks?check_run_id=253821136

The original setup too 218s in "Run manifest_build.py", while this PR took 94s for installing dependencies and running the same step. It didn't actually upload the assets and create the release, but that part was only 2s in the original setup. So, one can shave off 2 minutes or so.

At the end of the day the speedup is not hugely important, a more direct benefit is that the logs are cleaner as they don't start with a whole lot of docker fetching.

**Comment by gsnedders** [comment]
I am in favour, but I leave the review to @jgraham.

**Review by jgraham — APPROVED** [review]

**Comment by foolip** [comment]
Alright, https://github.com/web-platform-tests/wpt/runs/259065754 worked and was not all too slow. Now let's see how long it takes before the job fails when fetching from pythonhosted.org and what to do then...

**Pull request merged**
