### PR TITLE
Output Chromium log on `shutdown`, not `suite_end`

### LINKED ISSUE #33064: Chromium-style logs are not valid JSON with more than one repetition
```sh
CHROME_BUILD_DIR="${HOME}/chromium/src/out/Default"
./wpt run \
  --binary="${CHROME_BUILD_DIR}/chrome" \
  --webdriver-binary="${CHROME_BUILD_DIR}/chromedriver" \
  --binary-arg=--enable-experimental-web-platform-features \
  --binary-arg=--enable-blink-test-features \
  --binary-arg=--enable-blink-features=MojoJS,MojoJSTest \
  --binary-arg=--disable-field-trial-config \
  --webdriver-arg=--enable-chrome-logs \
  --headless \
  --no-capture-stdio \
  --no-manifest-download \
  --no-pause-after-test \
  --manifest="${CHROME_BUILD_DIR}/MANIFEST.json" \
  --log-mach=- \
  --log-mach-verbose \
  --processes=20 \
  --mojojs-path="${CHROME_BUILD_DIR}/gen" \
  --repeat=2 \
  --log-chromium=output.json \
  chrome \
  badging/badge-success.https.html \
```

# Expected
`output.json` is valid JSON, or at least have newlines between log records.

# Actual
Multiple records on a single line. wptrunner logs test results for each repetition: https://github.com/web-platform-tests/wpt/blob/206491af1ac7c2400c0f45cca4ea133dd2845762/tools/wptrunner/wptrunner/wptrunner.py#L410
The string appended on each iteration: https://github.com/web-platform-tests/wpt/blob/206491af1ac7c2400c0f45cca4ea133dd2845762/tools/wptrunner/wptrunner/formatters/chromium.py#L260-L271

# Info
Platform: `#1 SMP Debian 5.15.15-1rodete2 (2022-02-23) x86_64 GNU/Linux`
Revision: 27ae27bc3e

### PR DESCRIPTION
**Pull request by jonathan-j-lee**
Fixes #33064

It seems that `logger.suite_start` and `logger.suite_end` are running too often (at least for Chromium, where the test report is cumulative).

I'm not sure how widely the `--repeat` flag is used in practice with a value >1. This change may impact downstream users who rely on the current behavior of logging every repetition.

### CODE REVIEW

**Comment by DanielRyanSmith** [comment]
It seems like this change would only make a difference if `--repeat` is >1, right? My understanding is that we call `suite_start` and run the entire suite of tests, then call `suite_end`, and then if we need to repeat this process we start and end it for each additional iteration of the test suite.
I know that our browser stability checks repeat 10 times in order to detect flakiness in new changes. @jgraham Maybe you have some insight on this?

**Comment by DanielRyanSmith** [comment]
Taking a look closer look at this, it is true that the current results logs are output in a syntactically-incorrect JSON file when more than 1 iterations are run. The JSON file has multiple results objects side by side (i.e. {result1}{result2}{result3}). This happens when using the flag `--log-chromium` and `--log-wptreport` for both Firefox or Chrome (or any other browsers I assume).
This proposed change seems to fix the syntax issue, but it might be an issue that the new result format has all results listed together without any information on which repeat iteration they were a part of.

I'll hold off on suggesting anything because I'm not familiar with the logging side and how it is used for other browsers.

**Comment by WeizhongX** [comment]
I feel it is ok if we don't list the iteration number for the tests. Probably nobody is requesting/using such information as of now.

I guess we can go ahead to merge this, and we can always revert if it breaks anything.

**Review by WeizhongX — APPROVED** [review]

**Comment by jgraham** [comment]
Sorry, I meant to reply to this earlier.

I understand the problem here, but I'm worried about this change. 

The current data model is that tests must (enforced) have a unique id in a suite and subtests must (not strictly enforced, but required for correctness) have a unique name inside that test. That allows representing the output using a data structure like `{test_id: {subtest_name: result}}`. I'm not *competely* sure whether we already have tooling that does that; for example it looks like the metadata update code treats multiple subtest results in the same JSON object identically to multiple subtest results across different log files, which is a well supported use case. So I think that won't break, but it's hard to audit every other consumer of wpt logging to ensure that all of them are able to cope with this change. At the very least a change like this requires an RFC so that people aren't surprised when an update breaks their code. (I also wonder if such tooling would already be broken when using the `--rerun` flag to repeat each test without restarting, but use of that is pretty much confined to the test stability checks in Gecko CI).

I also notice that in the metadata update code, we try to handle the case of a wptreport file containing multiple, newline separated, JSON objects, see [metadata.py](https://github.com/web-platform-tests/wpt/blob/b494ad81e9de67691707d24b74116d868f410813/tools/wptrunner/wptrunner/metadata.py#L358-L361). So I think the original idea for handling multiple repetitions in that log format was to force single-line serialization and then read one JSON object per line.

So if you want to solve the general problem here it might be necessary to write an RFC and have people audit existing log consumers to see if it's possible to change the behaviour without breaking things. But if you are mostly just interested in solving the problem with the chromium formatter for now, it might be possible to use the [`shutdown` log action](https://searchfox.org/mozilla-central/source/testing/mozbase/mozlog/mozlog/structuredlog.py#576) rather than `suite_end`. This is supposed to be called exactly once per logger, so is the correct place to write data that's supposed to be logged at the very end of a test run.

**Review by jgraham — CHANGES_REQUESTED** [review]
(see comment)

**Review by WeizhongX — APPROVED** [review]

**Comment by jonathan-j-lee** [comment]
@jgraham Thanks for the insight. For now, I'm only interested in fixing Chromium log syntax so that a consumer in Chromium's CI stops breaking. I've implemented a narrower change that uses `shutdown` to achieve this.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
