### PR TITLE
URL: ensure deleting all params keeps ? in URL

### PR DESCRIPTION
**Pull request by TimothyGu**
See https://github.com/jsdom/whatwg-url/issues/97.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249053886)

# Firefox (nightly) #
Testing web-platform-tests at revision da797a555ae6540deec504952eb5d6ad765d6309
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6445/url/urlsearchparams-delete.html">/url/urlsearchparams-delete.html</a></summary>


|               Subtest                | Results |                                            Messages                                           |
|--------------------------------------|---------|-----------------------------------------------------------------------------------------------|
|                                      | OK      |                                                                                               |
| `Delete basics`                      | PASS    |                                                                                               |
| `Deleting appended multiple`         | PASS    |                                                                                               |
| `Deleting all params keeps ? in URL` | FAIL    | `assert_equals: url.href has ? expected "http://example.com/?" but got "http://example.com/"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249053887)

# Sauce (safari) #
Testing web-platform-tests at revision da797a555ae6540deec504952eb5d6ad765d6309
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249053893)

# Chrome (unstable) #
Testing web-platform-tests at revision da797a555ae6540deec504952eb5d6ad765d6309

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/249053894)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision da797a555ae6540deec504952eb5d6ad765d6309

**Comment by GPHemsley** [comment]
Despite what the spec might suggest, neither Firefox nor Chrome keep the `?` around in `href`:

image

image

**Comment by annevk** [comment]
It might be worth changing this given what browsers do. It does seem a little cleaner.

**Comment by TimothyGu** [comment]
@annevk I'll check what Edge does. It is cleaner, but less consistent with the fact that generally the update step is equivalent to `url.search = "?" + url.searchParams.toString()`.

**Comment by zimbabao** [comment]
Deleting non existing param gives different behavior on browsers
1. Chrome: Removes '?'
2. Safari/Firefox: Keeps '?'

```javascript
let url = new URL("http://ex.com/?");
console.log(`Before Delete: ${url.toString()}`)
url.searchParams.delete('NotPresent');
console.log(`After Delete: ${url.toString()}`)
```

This behavior is again inconsistent on Firefox's current behavior.
[jsbin link ](https://jsbin.com/bukofocufo/edit?html,js,console,output)

**Comment by TimothyGu** [comment]
Indeed. And Edge apparently does not support the `searchParams` attribute...

**Comment by annevk** [comment]
Okay, I guess I'm good either way. Anyone up for filing browser bugs?

**Comment by stevenvachon** [comment]
I think it makes sense to remove the "?" delimiter. By changing any param, the URL has already been mutated and removes the need to preserve the delimiter. A URL with and without the delimiter are considered the same, anyway.

**Comment by TimothyGu** [comment]
@stevenvachon What do you think about the case in https://github.com/w3c/web-platform-tests/pull/6445#issuecomment-312589973? Specifically, in Chrome, there is a case when no param is actually changed but the URL is still mutated. This just doesn't sit well with me. In my opinion the current spec behavior is still the most consistent.

**Comment by stevenvachon** [comment]
Deleting a non-existent param isn't technically a mutation, but it had the intent of such. We could always check before deleting.

**Comment by zimbabao** [comment]
'?' should be present in URL only when there is at least one QP makes sense. 
eg. it should be
```javascript
new URL('http://w.co/?').toString() == new URL('http://w.co/').toString() 
```

**Comment by stevenvachon** [comment]
If we were to parse `http://host/?` we would get a `{ '': '' }` value for `searchParams`. When the last param is removed, the `?` delimiter should be removed.

**Comment by TimothyGu** [comment]
> '?' should be present in URL only when there is at least one QP makes sense.

This is a dangerous assumption. In fact it goes against what ALL implementations of URLs are doing today and the last few decades. If the spec is to be changed this way, this would mean that it would be impossible to visit a website like `http://example.com/?`, because the browser would *always* normalize it to `http://example.com/`. The cost would simply be too great.

Plus, we have to be careful to avoid slippery slope here. By this token, one could argue that a trailing `#` does not make sense either, and that would introduce breakages of its own.

----

> Also, when we parse `http://host/?` we do not get a `{ '': '' }` value for `searchParams`.

This is true. However, we should not conflate URL-level concepts with `application/x-www-form-urlencoded`-level concepts like `searchParams`. It is by tradition, not any standard, that the content in a URL's query generally follows `application/x-www-form-urlencoded` format. The current URL Standard as well as [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.4) does not impose any additional meaning or syntax to query. RFC 3986 describes a URL's query as:

> The query component contains non-hierarchical data that, along with data in the path component (Section 3.3), serves to identify a resource within the scope of the URI's scheme and naming authority (if any).

The older [RFC 2396](https://tools.ietf.org/html/rfc2396) [defines](https://tools.ietf.org/html/rfc2396#section-3.4) query as:

> The query component is a string of information to be interpreted by the resource.

Based on these definitions, there is surely a difference between an empty query component and an undefined query component, a distinction reaffirmed by the URL Standard.

**Comment by stevenvachon** [comment]
> Plus, we have to be careful to avoid slippery slope here. By this token, one could argue that a trailing # does not make sense either, and that would introduce breakages of its own.

I agree, but `url.href = ''` will clear a trailing `#`. As should using `URL#searchParams#delete()` to remove the last param do so for a trailing `?`. These actions are mutational

**Comment by annevk** [comment]
I don't see how base URL handling for `#` (which won't even work for normal `URL` objects as they don't have a stored base URL) relates to `?`.

**Comment by stevenvachon** [comment]
@annevk I don't understand your comment. By "base URL", are you referring to `new URL(url, base)`? And I wasn't referring to a URL containing *only* `#`, but instead trailing on a full URL.

**Comment by annevk** [comment]
I meant that if `url.href = ''` does anything other than throwing (which it would with `URL` objects) it would be to resolve the input against a base URL (as `<a>.href = ''` would handle it for instance).

**Comment by stevenvachon** [comment]
Oops, I typo'ed. Comment edited.

**Comment by annevk** [comment]
I still don't understand what you're trying to say. Anyway, if you want to advocate some kind of change I recommend raising an issue against whatwg/url so we can consider it standalone. It shouldn't block this PR. My bad for taking in that direction to begin with.

**Review by annevk — APPROVED** [review]
Do you want me to file the bugs @TimothyGu?

**Comment by stevenvachon** [comment]
We could end up with a bigger issue if browsers need to be re-patched.

**Comment by TimothyGu** [comment]
@annevk Sure, go ahead.

**Comment by annevk** [comment]
Safari TP already passes. Bugs:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1379113
* https://bugs.chromium.org/p/chromium/issues/detail?id=740048

**Pull request merged**
