### PR TITLE
Stop running python tests on Python 3.5

### PR DESCRIPTION
**Pull request by jgraham**
Since we are running 3.6

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6630)

### CODE REVIEW

**Review by gsnedders — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257821544)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257821545)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257821557)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257821561)

# Sauce (MicrosoftEdge) #

**Pull request merged**
