### PR TITLE
Upstream service worker `client` tests to WPT


### PR DESCRIPTION
**Pull request by jeffcarp**
BUG=688116, 705685
R=falken@chromium.org

Review-Url: https://codereview.chromium.org/2778903002
Cr-Commit-Position: refs/heads/master@{#461000}

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5307)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217355667)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 54385a2909acf6f97ccec8c88a7959bb64b3ba60
Using browser at version BuildID 20170331102157; SourceStamp 8df9fabf2587b7020889755acb9e75b664fe13cf
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/client-id.https.html">/service-workers/service-worker/client-id.https.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Client.id returns the client's ID.` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get-client-types.https.html">/service-workers/service-worker/clients-get-client-types.https.html</a></summary>


|                       Subtest                       | Results |                                         Messages                                        |
|-----------------------------------------------------|---------|-----------------------------------------------------------------------------------------|
|                                                     | OK      |                                                                                         |
| `Test Clients.get() with window and worker clients` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: actual is undefined"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get-cross-origin.https.html">/service-workers/service-worker/clients-get-cross-origin.https.html</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| `Test Clients.get() cross origin` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get.https.html">/service-workers/service-worker/clients-get.https.html</a></summary>


|       Subtest        | Results | Messages |
|----------------------|---------|----------|
|                      | OK      |          |
| `Test Clients.get()` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-client-types.https.html">/service-workers/service-worker/clients-matchall-client-types.https.html</a></summary>


|                            Subtest                            | Results |                                                                  Messages                                                                  |
|---------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------|
|                                                               | OK      |                                                                                                                                            |
| `Verify matchAll() with window client type`                   | PASS    |                                                                                                                                            |
| `Verify matchAll() with window and sharedworker client types` | FAIL    | `promise_test: Unhandled rejection with value: object "Error: clients.matchAll() rejected: NotSupportedError: Operation is not supported"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-exact-controller.https.html">/service-workers/service-worker/clients-matchall-exact-controller.https.html</a></summary>


|                     Subtest                     | Results | Messages |
|-------------------------------------------------|---------|----------|
|                                                 | OK      |          |
| `Test Clients.matchAll() with exact controller` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html">/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html</a></summary>


|                     Subtest                     | Results | Messages |
|-------------------------------------------------|---------|----------|
|                                                 | OK      |          |
| `Verify matchAll() respect includeUncontrolled` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-on-evaluation.https.html">/service-workers/service-worker/clients-matchall-on-evaluation.https.html</a></summary>


|                    Subtest                     | Results | Messages |
|------------------------------------------------|---------|----------|
|                                                | OK      |          |
| `Test Clients.matchAll() on script evaluation` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-order.https.html">/service-workers/service-worker/clients-matchall-order.https.html</a></summary>


|                                     Subtest                                      | Results | Messages |
|----------------------------------------------------------------------------------|---------|----------|
|                                                                                  | OK      |          |
| `Clients.matchAll() returns non-focused controlled windows in creation order.`   | PASS    |          |
| `Clients.matchAll() returns controlled windows in focus order.  Case 1.`         | PASS    |          |
| `Clients.matchAll() returns controlled windows in focus order.  Case 2.`         | PASS    |          |
| `Clients.matchAll() returns non-focused uncontrolled windows in creation order.` | PASS    |          |
| `Clients.matchAll() returns uncontrolled windows in focus order.  Case 1.`       | PASS    |          |
| `Clients.matchAll() returns uncontrolled windows in focus order.  Case 2.`       | PASS    |          |
| `Clients.matchAll() returns controlled windows and frames in focus order.`       | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall.https.html">/service-workers/service-worker/clients-matchall.https.html</a></summary>


|          Subtest          | Results | Messages |
|---------------------------|---------|----------|
|                           | OK      |          |
| `Test Clients.matchAll()` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/217355668)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 54385a2909acf6f97ccec8c88a7959bb64b3ba60
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
## Unstable results ##


|                                 Test                                |                                    Subtest                                     |          Results           |                                                                                                                                                                                                                                                                                                                                                                                                                                                           Messages                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|---------------------------------------------------------------------|--------------------------------------------------------------------------------|----------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `/service-workers/service-worker/clients-matchall-order.https.html` | `Clients.matchAll() returns non-focused controlled windows in creation order.` | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=0" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=2";assert_equals: expected URL index 1 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=1" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=2";assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=0" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=1"` |

## All results ##
<details>
<summary>10 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/client-id.https.html">/service-workers/service-worker/client-id.https.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Client.id returns the client's ID.` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get-client-types.https.html">/service-workers/service-worker/clients-get-client-types.https.html</a></summary>


|                       Subtest                       | Results | Messages |
|-----------------------------------------------------|---------|----------|
|                                                     | OK      |          |
| `Test Clients.get() with window and worker clients` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get-cross-origin.https.html">/service-workers/service-worker/clients-get-cross-origin.https.html</a></summary>


|              Subtest              | Results | Messages |
|-----------------------------------|---------|----------|
|                                   | OK      |          |
| `Test Clients.get() cross origin` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-get.https.html">/service-workers/service-worker/clients-get.https.html</a></summary>


|       Subtest        | Results | Messages |
|----------------------|---------|----------|
|                      | OK      |          |
| `Test Clients.get()` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-client-types.https.html">/service-workers/service-worker/clients-matchall-client-types.https.html</a></summary>


|                            Subtest                            | Results |                                                                                                                                                                      Messages                                                                                                                                                                      |
|---------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                               | OK      |                                                                                                                                                                                                                                                                                                                                                    |
| `Verify matchAll() with window client type`                   | FAIL    | `assert_unreached: unexpected rejection: assert_array_equals: property 2, expected "https://web-platform.test:8443/service-workers/service-worker/resources/clients-matchall-client-types-iframe.html" but got "https://web-platform.test:8443/service-workers/service-worker/resources/url-modified-via-pushstate.html" Reached unreachable code` |
| `Verify matchAll() with window and sharedworker client types` | FAIL    | `promise_test: Unhandled rejection with value: object "Error: wait_for_state must be passed a ServiceWorker"`                                                                                                                                                                                                                                      |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-exact-controller.https.html">/service-workers/service-worker/clients-matchall-exact-controller.https.html</a></summary>


|                     Subtest                     | Results |                                                                 Messages                                                                |
|-------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------|
|                                                 | OK      |                                                                                                                                         |
| `Test Clients.matchAll() with exact controller` | FAIL    | `assert_unreached: unexpected rejection: assert_array_equals: property 3, expected "window" but got undefined Reached unreachable code` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html">/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html</a></summary>


|                     Subtest                     | Results |     Messages     |
|-------------------------------------------------|---------|------------------|
|                                                 | ERROR   |                  |
| `Verify matchAll() respect includeUncontrolled` | TIMEOUT | `Test timed out` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-on-evaluation.https.html">/service-workers/service-worker/clients-matchall-on-evaluation.https.html</a></summary>


|                    Subtest                     | Results | Messages |
|------------------------------------------------|---------|----------|
|                                                | OK      |          |
| `Test Clients.matchAll() on script evaluation` | PASS    |          |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall-order.https.html">/service-workers/service-worker/clients-matchall-order.https.html</a></summary>


|                                     Subtest                                      |          Results           |                                                                                                                                                                                                                                                                                                                                                                                                                                                           Messages                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|----------------------------------------------------------------------------------|----------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                  | OK                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Clients.matchAll() returns non-focused controlled windows in creation order.`   | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=0" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=2";assert_equals: expected URL index 1 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=1" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=2";assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=0" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-controlled-windows&q=1"` |
| `Clients.matchAll() returns controlled windows in focus order.  Case 1.`         | PASS                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Clients.matchAll() returns controlled windows in focus order.  Case 2.`         | PASS                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Clients.matchAll() returns non-focused uncontrolled windows in creation order.` | FAIL                       | `assert_equals: expected URL index 2 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=no-focus-uncontrolled-windows&q=0" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=extra"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `Clients.matchAll() returns uncontrolled windows in focus order.  Case 1.`       | FAIL                       | `assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/clients-matchall-order.https.html" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=focus-uncontrolled-windows-1&q=2"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| `Clients.matchAll() returns uncontrolled windows in focus order.  Case 2.`       | FAIL                       | `assert_equals: expected URL index 0 expected "https://web-platform.test:8443/service-workers/service-worker/clients-matchall-order.https.html" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=focus-uncontrolled-windows-2&q=0"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| `Clients.matchAll() returns controlled windows and frames in focus order.`       | FAIL                       | `assert_equals: expected URL index 1 expected "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=focus-controlled-nested-windows&q=1" but got "https://web-platform.test:8443/service-workers/service-worker/resources/empty.html?name=focus-controlled-nested-windows&q=1&nested=true"`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5307/service-workers/service-worker/clients-matchall.https.html">/service-workers/service-worker/clients-matchall.https.html</a></summary>


|          Subtest          | Results |                                Messages                                |
|---------------------------|---------|------------------------------------------------------------------------|
|                           | OK      |                                                                        |
| `Test Clients.matchAll()` | FAIL    | `assert_array_equals: property 3, expected "window" but got undefined` |

</details>
</details>

**Comment by jugglinmike** [comment]
The instability reported above is present in `master` today and is therefore likely unrelated to this change set. I've created https://github.com/w3c/web-platform-tests/issues/5310 to track the resolution of that problem.

**Comment by jeffcarp** [comment]
@jugglinmike since this PR is failing CI, there's a chance the WPT Sync process will skip over it and it will be removed from Chromium master until this PR lands. Is that OK? If not, we can look into ways of keeping it.

**Comment by jugglinmike** [comment]
@jeffcarp It would create more work for me/my reviewers down the line, but I
would be able to continue working even if the commit is removed from Chromium's
`master` branch. More importantly, though: it would not actually solve the
problem. I've demonstrated that the test in question already behaves
inconsistently in WPT `master`, so even if Chromium's automated process reverts
this patch, the flakiness will persist.

(roping @rbyers and @foolip in here)

I wasn't aware of that aspect of Chromium's WPT Sync process. This may be a
more fundamental problem due to the following aspects of the current set up:

- Chromium rejects patches that are not merged to WPT
- WPT rejects patches that are inconsistent in Firefox or Chrome (this is soon
  to include Edge and Safari, too)

Unless I'm mistaken, this means that Chromium cannot contribute tests that
demonstrates flaky behavior in any browser. Similarly (as in the case of this
patch), it cannot modify "resource" files that happen to be used by such flaky
tests.

This is news to me. Does it concern you folks at all, or is it too rare to
worry about?

**Comment by jeffcarp** [comment]
also cc @qyearsley 

It's definitely not an ideal situation, but the way our import works means it's "all-or-nothing" - either all changes are exported to WPT, pass Travis CI, and are merged, or the importer can't run. Skipping over a PR that's stuck due to Travis CI is the only way we can unblock the importer currently.

> Chromium cannot contribute tests that demonstrates flaky behavior in any browser

Yes. The next step I'm taking to lessen this problem is to create WPT PRs once Gerrit CLs are uploaded, so we get Travis CI results before the CL lands on Chromium master. This will guarantee that everything that lands on Chromium master can be exported.

**Comment by jeffcarp** [comment]
Update: @qyearsley informed me that we can do a manual import of WPT minus directories that have pending PRs (which he is working on now), so this is not as urgent as I had previously thought

**Comment by jugglinmike** [comment]
I didn't realize this was blocking the importer altogether. That's definitely
a cause for urgency. Thanks to @qyearsly for coming to the rescue.

Just so I'm clear though: while the automation will not be blocked, it sounds
like Chromium will remain unable to contribute valid tests that demonstrate
flaky behavior in any of the browsers WPT uses in CI. Is that correct?

(I don't mean to beat a dead horse here; I'm just trying to understand the
problem and determine if it's something that warrants further discussion
outside of the context of this particular test.)

**Comment by jeffcarp** [comment]
> it sounds like Chromium will remain unable to contribute valid tests that demonstrate flaky behavior in any of the browsers WPT uses in CI. Is that correct?

For the most part, yes, however it is also possible to force-merge PRs into WPT. We have done this a couple times by giving rationale and asking @jgraham and @gsnedders nicely.

> (I don't mean to beat a dead horse here; I'm just trying to understand the problem and determine if it's something that warrants further discussion outside of the context of this particular test.)

Definitely not a dead horse - the process is not perfect and we're trying to decrease the bumpiness. Thank you for sticking with it so far. There is ongoing discussion on how to mitigate these issues between @qyearsley @foolip and myself on various crbugs (see https://crbug.com/686471).

**Comment by mattto** [comment]
Sorry to come to this late. It'd be unfortunate to not accept this change and to revert the change in Chromium.

Is the rationale for not accepting flakiness because the flakiness is typically the fault of the test rather than the browser?

In this case, Mike seems to have identified the Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=701233#c3

My preference would be to keep this change locally and in WPT. In Chrome, we've broken down the service worker WPT test effort into two subtasks that will run in parallel:
- Upstream correct tests
- Get Chrome to pass the tests

It'd be painful for us to block one on the other in general.

But in this case, since just one test failing, we could also revise the patch to not include this flaky test, and keep the flaky test in http/tests/serviceworker only.

**Comment by foolip** [comment]
When we know that the flakiness is because of a browser bug and not a problem with the test, then we should merge the PR anyway. It looks like that is the only flakiness, so I'll go ahead and merge manually.

**Pull request merged**
