### PR TITLE
URL: merge historical tests

### PR DESCRIPTION
**Pull request by annevk**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5658)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5658/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225185783)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225185786)

# Firefox (nightly channel) #
Testing web-platform-tests at revision a5b5d85a5e7918ee5165a4791c3dacad9441b4a2
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5658/url/historical.any.worker.html">/url/historical.any.worker.html</a></summary>


|                   Subtest                    | Results | Messages |
|----------------------------------------------|---------|----------|
|                                              | OK      |          |
| `searchParams on location object`            | PASS    | `{}`     |
| `Setting URL's href attribute and base URLs` | PASS    | `{}`     |
| `URL.domainToASCII should be undefined`      | PASS    | `{}`     |
| `URL.domainToUnicode should be undefined`    | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5658/url/historical.any.html">/url/historical.any.html</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| `searchParams on location object`                 | PASS    |          |
| `<a> and <area>.searchParams should be undefined` | PASS    |          |
| `Setting URL's href attribute and base URLs`      | PASS    |          |
| `URL.domainToASCII should be undefined`           | PASS    |          |
| `URL.domainToUnicode should be undefined`         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225185794)

# Chrome (unstable channel) #
Testing web-platform-tests at revision a5b5d85a5e7918ee5165a4791c3dacad9441b4a2
Using browser at version 59.0.3071.15 dev
Starting 10 test iterations

**Review by domenic — APPROVED** [review]

**Pull request merged**
