### PR TITLE
Change document-color-01.html to not remove the top-level body.

### LINKED ISSUE #2391: Add tests for Document#fgColor with special body elements.
<https://html.spec.whatwg.org/multipage/#dom-document-fgcolor> states:

> The attributes of the Document object listed in the first column of the following table must reflect the content attribute on the body element with the name given in the corresponding cell in the second column on the same row, if the body element is a body element (as opposed to a frameset element). When there is no body element or if it is a frameset element, the attributes must instead return the empty string on getting and do nothing on setting.

In particular, the following should be tested:
- [x] getting with no body or frameset element
- [ ] setting with no body or frameset element
- [ ] getting with both only a frameset element
- [ ] setting with both only a frameset element
- [ ] getting with both a body and a frameset element
- [ ] setting with both a body and a frameset element

See some existing tests in `html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/`.

### PR DESCRIPTION
**Pull request by qyearsley-zz**
When this test page is loaded, it doesn't show any results currently because the top-level body is removed. In order to test behavior of a document when a body is removed, this pull request would change the test to remove the body of an document in an iframe inside the top-level body.

This will make it easier to fix #2391 (missing coverage for document color attributes).

### CODE REVIEW

**Comment by ayg** [comment]
Can you remove the body of the current document and re-add it at the end of the test, or would it still not output results then?  I'd prefer that to testing in an iframe, because it's possible the behavior might differ -- although I see no particular reason why it would.  If the problem is that setting the attributes makes the test output hard to read, per your comment in #2391, you could reset them at the end of the test.

If for some reason it's still a problem to mutate the actual body, then an iframe is fine by me.

**Comment by qyearsley** [comment]
Makes sense -- removing the body of the top-level document and re-adding at the end of the test does work, and resetting the colors at the end of the test allows everything to be displayed as usual.

I'd also like to change this test to test verify that setting does nothing when there's no body, but it may be neater to do this in a separate pull request.

I was also considering adding a separate test method next to the original that does the same thing but verifies that setting and getting does have an effect when there is a body, although this is done in document-color-02.html, so maybe there's no need; any thoughts?

**Comment by ayg** [comment]
There's no need to duplicate things that are already tested elsewhere, but if the same basic tests are repeated in two files for two different scenarios with different expected results, they should probably be merged into one file if that reduces code duplication.  (E.g., have a helper function that takes the expected output as the argument or figures out the expected values programmatically or such.)

It's fine to put a bunch of changes to one test in one pull request, IMO, although if you prefer you could put it in multiple commits.  If you make multiple changes to one test in multiple simultaneous pull requests, you run the risk of merge conflicts, so that's not a good idea (unless you're sure they can be automatically merged).

**Comment by qyearsley** [comment]
Alright; uploaded another commit which would make it so that document-color-01.html tests getting and setting color attributes with no body in the document; that was the next change I wanted to make. Would it be alright to change the title of this pull request and use `git rebase -i ...` and `git push ... --force` to squash the 3 commits?

**Comment by ayg** [comment]
Thanks a lot for the change!  web-platform-tests is configured so that merging pull requests via the web interface always squashes into one commit anyway, so I just went ahead and merged your change.

**Pull request merged**
