### PR TITLE
Use .window.js for webstorage tests

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by Ms2ger** [comment]
Can you split this into two commits: one that moves the files, and one that reindents?

**Comment by crowlKats** [comment]
> Can you split this into two commits: one that moves the files, and one that reindents?

Not sure i understand

**Comment by crowlKats** [comment]
god sorry i am messing up with git...

**Review by Ms2ger — APPROVED** [review]
Thanks!

**Comment by vityafx** [comment]
Can you please explain how to run these tests now? I need to run the `local_window_open.html` but you've refactored it to a javascript code, now I can't run it with my browser, I have to embed it myself into another page.
Another question is, was there a motivation for these changes?

**Comment by Ms2ger** [comment]
You can load `X.window.js` tests at the corresponding `X.window.html` URL.

**Comment by vityafx** [comment]
> You can load `X.window.js` tests at the corresponding `X.window.html` URL.

I am sorry, can you point to these files that can run these tests? I can't find such files in the repository.
I only see `"storage*window.js"` files and no `storage*window.html` files there.

**Comment by Ms2ger** [comment]
Some docs here: https://github.com/web-platform-tests/wpt/blob/master/docs/writing-tests/testharness.md#window-tests

**Pull request merged**
