### PR TITLE
Capitalize WebdriverSpecTest => WebDriverSpecTest

### PR DESCRIPTION
**Pull request by foolip**
This was the only class capitalized like this, and the only occurences
of "Webdriver" anywhere in the repo. For consistency with classes
WebDriverException, WebDriverProtocol and WebDriverServer.

### CODE REVIEW

**Review by gsnedders — APPROVED** [review]
LGTM, but should check with others in case this might break any downstream code (@Hexcles? @jgraham?)

**Comment by Ms2ger** [comment]
https://searchfox.org/mozilla-central/search?q=WebdriverSpecTest&path= shows no occurrences in m-c outside wpt proper.

**Review by jgraham — APPROVED** [review]

**Comment by gsnedders** [comment]
https://cs.chromium.org/search/?q=WebDriverSpecTest&sq=package:chromium&type=cs shows nothing in Chromium either.

**Comment by Hexcles** [comment]
Confirmed this shouldn't affect Chromium. And this change will be manually rolled into Chromium together with other wpt tooling changes next time.

**Pull request merged**
