### PR TITLE
Remove remaining promise_rejects uses

### PR DESCRIPTION
**Pull request by bzbarsky**

### CODE REVIEW

**Comment by bzbarsky** [comment]
@stephenmcgruer @clopez

**Comment by stephenmcgruer** [comment]
This failed Chrome + Firefox stability checks for flakes in `/fetch/range/sw.https.window.html` (both) and /webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface/cors-check.https.html` (chrome-only). I would suspect they are pre-existing.

The wpt.fyi results for Safari and Firefox are good (no diff), but the results for Chrome are weirdly missing. I'm going to close/re-open this PR to trigger a re-run of the CI and hopefully get some wpt.fyi results for Chrome.

**Review by inexorabletash — APPROVED** [review]
lgtm (FWIW; I got auto-tagged by the bot and the ☕ was still kicking in)

**Comment by klausw** [comment]
WebXR LGTM

**Review by jcjones — APPROVED** [review]
webauthn LGTM

**Comment by stephenmcgruer** [comment]
Ok, got Chrome results. I see two that might be regressions associated with this PR:

https://wpt.fyi/results/encoding/streams/realms.window.html?diff&filter=ADC&run_id=407590001&run_id=438070004
https://wpt.fyi/results/mediacapture-image/MediaStreamTrack-applyConstraints-fast.html?diff&filter=ADC&run_id=407590001&run_id=438070004

They could be true failures exposed by the PR, or they could be bugs with the PR, PTAL @bzbarsky

**Review by marcoscaceres — APPROVED** [review]
Payments looks good. Thank you!

**Review by jan-ivar — APPROVED** [review]
webrtc-extensions & mediacapture-image good.

**Comment by bzbarsky** [comment]
> https://wpt.fyi/results/encoding/streams/realms.window.html?diff&filter=ADC&run_id=407590001&run_id=438070004

Typo in the changes to this test (`constructorRealm.typeError` instead of `constructorRealm.TypeError`).  Fix coming up.

>  https://wpt.fyi/results/mediacapture-image/MediaStreamTrack-applyConstraints-fast.html?diff&filter=ADC&run_id=407590001&run_id=438070004

This is a true failure exposed by the PR.  https://w3c.github.io/mediacapture-main/getusermedia.html#overconstrainederror-object defines a new `OverconstrainedError` thing which is supposed to be an `Error` subclass.  In particular, https://w3c.github.io/mediacapture-main/getusermedia.html#properties-of-the-overconstrainederror-constructor says:

> The value of the [[Prototype]] internal slot of the OverconstrainedError constructor is the intrinsic object %Error%.

Chrome implements `OverconstrainedError` but gets its prototype wrong; `Object.getPrototypeOf(OverconstrainedError) === Function.prototype` tests true in Chrome.  Since `promise_rejects_js` asserts that the constructor passed in has `Error` on its proto chain, the test fails.

**Review by pwnall — APPROVED** [review]
web-locks/ LGTM.

**Review by annevk — APPROVED** [review]

**Pull request merged**
