### PR TITLE
HTML: test display and box-sizing UA style for form controls

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/whatwg/html/pull/4840

### CODE REVIEW

**Comment by zcorpan** [comment]
This tests these parts of the spec change:

https://github.com/whatwg/html/pull/4840/files#diff-36cd38f49b9afa08222c0dc9ebfe35ebR114466
https://github.com/whatwg/html/pull/4840/files#diff-36cd38f49b9afa08222c0dc9ebfe35ebR115669

`box-sizing` was added because it was tested in `button-style.html` (that test is now removed).

**Review by annevk — APPROVED** [review]
Changes look reasonable. I'm assuming you've run this across browsers and filed bugs as needed.

**Comment by zcorpan** [comment]
I'll file browser bugs when https://github.com/whatwg/html/pull/4840 is closer to ready to merge.

**Comment by josepharhar** [comment]
Any reason this hasn't been merged yet?

**Comment by josepharhar** [comment]
Oh, I see it's probably because https://github.com/whatwg/html/pull/4840 hasn't been merged yet

**Comment by zcorpan** [comment]
@josepharhar yeah, I'll hopefully get to work a bit on 'appearance' again soon to finish 4840. We could land this earlier, though this commit has not yet been reviewed: 0d6bde63309527b5c675e753828ed9241ca02cb5

**Comment by zcorpan** [comment]
I've rebased this, and the [spec change](https://github.com/whatwg/html/pull/4840) seems ready to merge. Let's merge!

**Pull request merged**
