### PR TITLE
[DO NOT SUBMIT] Reproduce MacOS + Py3.8 mozinstall failure

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1656225

**Comment by stephenmcgruer** [comment]
At this point I'm fairly confident that this is some very, very strange issue where we seem to somehow be running old mozinstall code, even as the filesystem tells us new code is there (seriously, https://dev.azure.com/web-platform-tests/b14026b4-9423-4454-858f-bf76cf6d1faa/_apis/build/builds/51979/logs/213 is a fun read... an error thrown in a file that when later cat'd  has different content).

I have been digging in on-and-off via runs on the bots (oh, to own a mac device...), will summarize my findings so far tomorrow.

**Comment by Hexcles** [comment]
I've gone down the rabbit hole and found the root cause.

First of all, some of `tools/wpt/tests` are integration tests in the sense that they invoke `wpt.main` directly, e.g.
https://github.com/web-platform-tests/wpt/blob/bd98c68802522edfae543a2a83dcd289c0972811/tools/wpt/tests/test_install.py#L89
(Some other tests create venvs themselves, e.g. `test_run.py`.)

`wpt.main` will then set up virtualenv itself:
https://github.com/web-platform-tests/wpt/blob/bd98c68802522edfae543a2a83dcd289c0972811/tools/wpt/wpt.py#L150 

This means that only the test cases use the dependencies installed by tox; everything inside `wpt.main` uses `_venv*` instead.

Now to the root: we manage `_venv*` ourselves, using a special flag when installing dependencies:
https://github.com/web-platform-tests/wpt/blob/bd98c68802522edfae543a2a83dcd289c0972811/tools/wpt/virtualenv.py#L128-L132

The newest release of `mozinstall` (2.0.0) unfortunately does not have binary wheels: https://pypi.org/project/mozInstall/2.0.0/#files, but the previous version does https://pypi.org/project/mozInstall/1.16.0/#files

Finally, the `install` command uses the `install` field in `commands.json` which does not pin the version of `mozinstall`
https://github.com/web-platform-tests/wpt/blob/bd98c68802522edfae543a2a83dcd289c0972811/tools/wpt/commands.json#L54-L55
unlike in `tools/wptrunner/requirements_firefox.txt`.
https://github.com/web-platform-tests/wpt/blob/bd98c68802522edfae543a2a83dcd289c0972811/tools/wptrunner/requirements_firefox.txt#L3

Therefore, when you run `wpt run`, `requirements_firefox.txt` will be used and everything works, including `wpt install` from then on (since the dependency is satisfied); but if you run `wpt install` on a fresh checkout, `pip install --prefer-binary mozinstall` will give you the broken 1.16.0.

**Comment by Hexcles** [comment]
@jgraham has published the wheel for mozinstall 2.0.0. Let's try again now.

**Comment by Hexcles** [comment]
The tests in question indeed pass now. Filed #24829 to keep track of the venv management issue.

**Pull request closed without merging**
