### PR TITLE
[css-flexbox] lowercase Flexible-order.html

### PR DESCRIPTION
**Pull request by foolip**
This is the only Flexbox test with this capitalization and it's always
listed first, making it a bit of an eyesore. (Most of the time when this
file name style is used in WPT, it's the name of an interface.)

### CODE REVIEW

**Review by tabatkins — APPROVED** [review]

**Comment by cbiesinger** [comment]
Will this cause problems on case insensitive file systems such as windows?

**Comment by tabatkins** [comment]
I don't *think* I've run into issues with casing renames, tho I definitely have with two files in git that differed only by casing. But I could be wrong.

**Comment by foolip** [comment]
@domenic do you have a WPT checkout on Windows? Is so, can you see if something weird happens with this file when you update your checkout?

**Comment by domenic** [comment]
No issue here; it seems to work fine.

**Pull request merged**
