### PR TITLE
Remove erroneous reftest-wait class which was not removed by script

### PR DESCRIPTION
**Pull request by svgeesus**
Caused test failure due to reference timeout

### CODE REVIEW

**Comment by svgeesus** [comment]
@anne @foolip It would be very helpful if Chris Blume @ProgramMax who is chair of the PNG WG could be made a WPT reviewer for wpt/png so I didn't have to bug you folks to review trivial one-line bugfixes.

**Comment by ProgramMax** [comment]
Non-reviewer LGTM :D

**Comment by svgeesus** [comment]
@Ms2ger perhaps you can unblock this?

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@svgeesus I have invited @ProgramMax to the reviewers team now.

**Pull request merged**
