### PR TITLE
Test Geolocation Sensor IDL

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20627)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/302454792)

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
Thanks @foolip! LGTM.

Including @Honry who has done a bunch of Generic Sensor tests lately.

**Comment by foolip** [comment]
@Honry, feel free to add yourself to the OWNERS file if you care about this directory.

**Comment by Honry** [comment]
@foolip, Cool! It's easy to add more tests, just refer to other sensor tests. I will do that soon. :)

**Pull request merged**
