### PR TITLE
web-platform-tests.org index: Make images clickable.

### PR DESCRIPTION
**Pull request by qyearsley-zz**
@gsnedders Does this look alright? By the way, web-platform-tests.org is looking excellent :-)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 93011fc43dbbd249f3ae9aba4bc12075b8b0faa0
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 93011fc43dbbd249f3ae9aba4bc12075b8b0faa0
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
No tests run.

**Comment by qyearsley** [comment]
Note, after this the images at http://web-platform-tests.org/ are all blue-colored and they look a bit different, hope that's OK...

**Comment by gsnedders** [comment]
Uh, we should fix that!

**Comment by qyearsley** [comment]
Would it be better if the images had "color: black" style applied to them, but were still part of the link?

**Comment by gsnedders** [comment]
Yes. (I'll do that soon, probably before you wake up. :))

**Pull request merged**
