### PR TITLE
Add a WKTR test job to Azure Pipelines

### PR DESCRIPTION
**Pull request by gsnedders**
This currently requires a manual trigger, but this should be enough to be able to validate that it (and the wpt.fyi side) works.

### CODE REVIEW

**Comment by gsnedders** [comment]
Given nobody reviewed this while I was out, this will now need updated in light of #39687.

**Review by jcscottiii — APPROVED** [review]
LGTM from an Azure Pipeline perspective.

I have one question for myself since I'm relatively new to the project. Do you need to install anything for the webkit preview? (I saw in the STP job there was an install_safari step. I was wondering if we needed to have a similar install_wekbit step.)

**Comment by gsnedders** [comment]
> I have one question for myself since I'm relatively new to the project. Do you need to install anything for the webkit preview? (I saw in the STP job there was an install_safari step. I was wondering if we needed to have a similar install_wekbit step.)

The CLI contains `--install-browser wktr` which does everything needed; installing STP is a separate step on Azure Pipelines because it requires admin perms.

**Comment by gsnedders** [comment]
(Landing this before https://github.com/web-platform-tests/wpt/pull/39687 because there's no actual dependency here, just didn't want to add new macOS Monterey jobs after moving existing jobs to macOS Ventura)

**Pull request merged**
