### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=169680

### PR DESCRIPTION
**Pull request by youennf**
LayoutTests/imported/w3c/web-platform-tests/cors/preflight-failure.htm should use localhost/127.0.0.1

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5193)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5193/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213706444)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 430e5276b82fe8e917e95221a9bbaff48318aec6
Using browser at version BuildID 20170320110254; SourceStamp 1b9293be51637f841275541d8991314ca56561a5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5193/cors/preflight-failure.htm">/cors/preflight-failure.htm</a></summary>


|                      Subtest                       | Results |     Messages     |
|----------------------------------------------------|---------|------------------|
|                                                    | TIMEOUT |                  |
| `Should throw error if preflight respond with 100` | TIMEOUT | `Test timed out` |
| `Should throw error if preflight respond with 101` | PASS    |                  |
| `Should throw error if preflight respond with 200` | PASS    |                  |
| `Should throw error if preflight respond with 300` | PASS    |                  |
| `Should throw error if preflight respond with 301` | PASS    |                  |
| `Should throw error if preflight respond with 302` | PASS    |                  |
| `Should throw error if preflight respond with 303` | PASS    |                  |
| `Should throw error if preflight respond with 304` | PASS    |                  |
| `Should throw error if preflight respond with 305` | PASS    |                  |
| `Should throw error if preflight respond with 306` | PASS    |                  |
| `Should throw error if preflight respond with 307` | PASS    |                  |
| `Should throw error if preflight respond with 308` | PASS    |                  |
| `Should throw error if preflight respond with 400` | PASS    |                  |
| `Should throw error if preflight respond with 401` | PASS    |                  |
| `Should throw error if preflight respond with 402` | PASS    |                  |
| `Should throw error if preflight respond with 403` | PASS    |                  |
| `Should throw error if preflight respond with 404` | PASS    |                  |
| `Should throw error if preflight respond with 405` | PASS    |                  |
| `Should throw error if preflight respond with 406` | PASS    |                  |
| `Should throw error if preflight respond with 407` | PASS    |                  |
| `Should throw error if preflight respond with 408` | PASS    |                  |
| `Should throw error if preflight respond with 409` | PASS    |                  |
| `Should throw error if preflight respond with 410` | PASS    |                  |
| `Should throw error if preflight respond with 411` | PASS    |                  |
| `Should throw error if preflight respond with 412` | PASS    |                  |
| `Should throw error if preflight respond with 413` | PASS    |                  |
| `Should throw error if preflight respond with 414` | PASS    |                  |
| `Should throw error if preflight respond with 415` | PASS    |                  |
| `Should throw error if preflight respond with 416` | PASS    |                  |
| `Should throw error if preflight respond with 417` | PASS    |                  |
| `Should throw error if preflight respond with 500` | PASS    |                  |
| `Should throw error if preflight respond with 501` | PASS    |                  |
| `Should throw error if preflight respond with 502` | PASS    |                  |
| `Should throw error if preflight respond with 503` | PASS    |                  |
| `Should throw error if preflight respond with 504` | PASS    |                  |
| `Should throw error if preflight respond with 505` | PASS    |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213706445)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 430e5276b82fe8e917e95221a9bbaff48318aec6
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5193/cors/preflight-failure.htm">/cors/preflight-failure.htm</a></summary>


|                      Subtest                       | Results | Messages |
|----------------------------------------------------|---------|----------|
|                                                    | OK      |          |
| `Should throw error if preflight respond with 100` | PASS    |          |
| `Should throw error if preflight respond with 101` | PASS    |          |
| `Should throw error if preflight respond with 200` | PASS    |          |
| `Should throw error if preflight respond with 300` | PASS    |          |
| `Should throw error if preflight respond with 301` | PASS    |          |
| `Should throw error if preflight respond with 302` | PASS    |          |
| `Should throw error if preflight respond with 303` | PASS    |          |
| `Should throw error if preflight respond with 304` | PASS    |          |
| `Should throw error if preflight respond with 305` | PASS    |          |
| `Should throw error if preflight respond with 306` | PASS    |          |
| `Should throw error if preflight respond with 307` | PASS    |          |
| `Should throw error if preflight respond with 308` | PASS    |          |
| `Should throw error if preflight respond with 400` | PASS    |          |
| `Should throw error if preflight respond with 401` | PASS    |          |
| `Should throw error if preflight respond with 402` | PASS    |          |
| `Should throw error if preflight respond with 403` | PASS    |          |
| `Should throw error if preflight respond with 404` | PASS    |          |
| `Should throw error if preflight respond with 405` | PASS    |          |
| `Should throw error if preflight respond with 406` | PASS    |          |
| `Should throw error if preflight respond with 407` | PASS    |          |
| `Should throw error if preflight respond with 408` | PASS    |          |
| `Should throw error if preflight respond with 409` | PASS    |          |
| `Should throw error if preflight respond with 410` | PASS    |          |
| `Should throw error if preflight respond with 411` | PASS    |          |
| `Should throw error if preflight respond with 412` | PASS    |          |
| `Should throw error if preflight respond with 413` | PASS    |          |
| `Should throw error if preflight respond with 414` | PASS    |          |
| `Should throw error if preflight respond with 415` | PASS    |          |
| `Should throw error if preflight respond with 416` | PASS    |          |
| `Should throw error if preflight respond with 417` | PASS    |          |
| `Should throw error if preflight respond with 500` | PASS    |          |
| `Should throw error if preflight respond with 501` | PASS    |          |
| `Should throw error if preflight respond with 502` | PASS    |          |
| `Should throw error if preflight respond with 503` | PASS    |          |
| `Should throw error if preflight respond with 504` | PASS    |          |
| `Should throw error if preflight respond with 505` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213707637)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 0daeaba2b911386fcb431c5176c4b8c5f28b7e86
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5193/cors/preflight-failure.htm">/cors/preflight-failure.htm</a></summary>


|                      Subtest                       | Results |     Messages     |
|----------------------------------------------------|---------|------------------|
|                                                    | TIMEOUT |                  |
| `Should throw error if preflight respond with 100` | TIMEOUT | `Test timed out` |
| `Should throw error if preflight respond with 101` | PASS    |                  |
| `Should throw error if preflight respond with 200` | PASS    |                  |
| `Should throw error if preflight respond with 300` | PASS    |                  |
| `Should throw error if preflight respond with 301` | PASS    |                  |
| `Should throw error if preflight respond with 302` | PASS    |                  |
| `Should throw error if preflight respond with 303` | PASS    |                  |
| `Should throw error if preflight respond with 304` | PASS    |                  |
| `Should throw error if preflight respond with 305` | PASS    |                  |
| `Should throw error if preflight respond with 306` | PASS    |                  |
| `Should throw error if preflight respond with 307` | PASS    |                  |
| `Should throw error if preflight respond with 308` | PASS    |                  |
| `Should throw error if preflight respond with 400` | PASS    |                  |
| `Should throw error if preflight respond with 401` | PASS    |                  |
| `Should throw error if preflight respond with 402` | PASS    |                  |
| `Should throw error if preflight respond with 403` | PASS    |                  |
| `Should throw error if preflight respond with 404` | PASS    |                  |
| `Should throw error if preflight respond with 405` | PASS    |                  |
| `Should throw error if preflight respond with 406` | PASS    |                  |
| `Should throw error if preflight respond with 407` | PASS    |                  |
| `Should throw error if preflight respond with 408` | PASS    |                  |
| `Should throw error if preflight respond with 409` | PASS    |                  |
| `Should throw error if preflight respond with 410` | PASS    |                  |
| `Should throw error if preflight respond with 411` | PASS    |                  |
| `Should throw error if preflight respond with 412` | PASS    |                  |
| `Should throw error if preflight respond with 413` | PASS    |                  |
| `Should throw error if preflight respond with 414` | PASS    |                  |
| `Should throw error if preflight respond with 415` | PASS    |                  |
| `Should throw error if preflight respond with 416` | PASS    |                  |
| `Should throw error if preflight respond with 417` | PASS    |                  |
| `Should throw error if preflight respond with 500` | PASS    |                  |
| `Should throw error if preflight respond with 501` | PASS    |                  |
| `Should throw error if preflight respond with 502` | PASS    |                  |
| `Should throw error if preflight respond with 503` | PASS    |                  |
| `Should throw error if preflight respond with 504` | PASS    |                  |
| `Should throw error if preflight respond with 505` | PASS    |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213707638)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 0daeaba2b911386fcb431c5176c4b8c5f28b7e86
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5193/cors/preflight-failure.htm">/cors/preflight-failure.htm</a></summary>


|                      Subtest                       | Results | Messages |
|----------------------------------------------------|---------|----------|
|                                                    | OK      |          |
| `Should throw error if preflight respond with 100` | PASS    |          |
| `Should throw error if preflight respond with 101` | PASS    |          |
| `Should throw error if preflight respond with 200` | PASS    |          |
| `Should throw error if preflight respond with 300` | PASS    |          |
| `Should throw error if preflight respond with 301` | PASS    |          |
| `Should throw error if preflight respond with 302` | PASS    |          |
| `Should throw error if preflight respond with 303` | PASS    |          |
| `Should throw error if preflight respond with 304` | PASS    |          |
| `Should throw error if preflight respond with 305` | PASS    |          |
| `Should throw error if preflight respond with 306` | PASS    |          |
| `Should throw error if preflight respond with 307` | PASS    |          |
| `Should throw error if preflight respond with 308` | PASS    |          |
| `Should throw error if preflight respond with 400` | PASS    |          |
| `Should throw error if preflight respond with 401` | PASS    |          |
| `Should throw error if preflight respond with 402` | PASS    |          |
| `Should throw error if preflight respond with 403` | PASS    |          |
| `Should throw error if preflight respond with 404` | PASS    |          |
| `Should throw error if preflight respond with 405` | PASS    |          |
| `Should throw error if preflight respond with 406` | PASS    |          |
| `Should throw error if preflight respond with 407` | PASS    |          |
| `Should throw error if preflight respond with 408` | PASS    |          |
| `Should throw error if preflight respond with 409` | PASS    |          |
| `Should throw error if preflight respond with 410` | PASS    |          |
| `Should throw error if preflight respond with 411` | PASS    |          |
| `Should throw error if preflight respond with 412` | PASS    |          |
| `Should throw error if preflight respond with 413` | PASS    |          |
| `Should throw error if preflight respond with 414` | PASS    |          |
| `Should throw error if preflight respond with 415` | PASS    |          |
| `Should throw error if preflight respond with 416` | PASS    |          |
| `Should throw error if preflight respond with 417` | PASS    |          |
| `Should throw error if preflight respond with 500` | PASS    |          |
| `Should throw error if preflight respond with 501` | PASS    |          |
| `Should throw error if preflight respond with 502` | PASS    |          |
| `Should throw error if preflight respond with 503` | PASS    |          |
| `Should throw error if preflight respond with 504` | PASS    |          |
| `Should throw error if preflight respond with 505` | PASS    |          |

</details>
</details>

**Comment by annevk** [comment]
I changed the commit message a bit, but looks good otherwise.

**Pull request merged**
