### PR TITLE
Meta: make CONTRIBUTING.md point to documentation

### LINKED ISSUE #969: Make a better CONTRIBUTING file.
Any time somebody creates a new issue or PR, they'll see a dialog that includes a link to 
the CONTRIBUTING.md file, with the link text saying:

   Please review the _guidelines for contributing_ to this repository. 

Unfortunately the current CONTRIBUTING.md file only contains information about the license for the test suite—it doesn't contain any actual guidelines for contributing.

We should update it to include some (at least minimal) guidelines for contributing.

### PR DESCRIPTION
**Pull request by annevk**
Fixes #969.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210989801)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e8e5e8993f555b7b01f901dae220c49c826e95ec
Using browser at version BuildID 20170313110417; SourceStamp f9362554866b327700c7f9b18050d7b7eb3d2b23
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210989802)

# Chrome (unstable channel) #
Testing web-platform-tests at revision e8e5e8993f555b7b01f901dae220c49c826e95ec
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
No tests run.

**Comment by jgraham** [comment]
Gonna get @sideshowbarker to OK changes to this file.

**Review by sideshowbarker — APPROVED** [review]
Still disappointing that for now we have to point people at an insecure URL for the docs, and not clear to me at least what our plan/timeline is for fixing that. But anyway that doesn’t need to block this PR.

**Pull request merged**
