### PR TITLE
Add aria11 tests and add myself to OWNERS

### PR DESCRIPTION
**Pull request by joanmarie**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5682)

### CODE REVIEW

**Comment by annevk** [comment]
Is there a reason these are put in a subdirectory? web-platform-tests tracks the latest version of a particular feature. Using versioned directories is generally not the way to go.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225534080)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225534082)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 2459ed463f6d338e7fd7cd3ce317b7d2b26ad145
Using browser at version BuildID 20170423100233; SourceStamp 070fc3c2f8400c09f1037f5444c3d33b499e7128
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225534090)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 2459ed463f6d338e7fd7cd3ce317b7d2b26ad145

**Comment by Joanmarie** [comment]
> Is there a reason these are put in a subdirectory? web-platform-tests tracks the latest version of a particular feature. Using versioned directories is generally not the way to go.

If you are strictly asking about the "11", that is there simply because @halindrome had done so in the setup we have been using. I have no objections to removing the "11" if he doesn't.

On the other hand, if you're asking about subdirectories in WAI-ARIA, that was to avoid cluttering things up for all the non-WAI-ARIA folks. Our specs, which will ultimately need tests, include the following:

* [ARIA](https://rawgit.com/w3c/aria/master/aria/aria.html) and [Core AAM](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html): "aria11" (or "aria" if you prefer)
* [DPub ARIA](https://rawgit.com/w3c/aria/master/aria/dpub.html) and [DPub AAM](https://rawgit.com/w3c/aria/master/dpub-aam/dpub-aam.html): "dpub"
* [Graphics ARIA](https://rawgit.com/w3c/aria/master/aria/graphics.html) and [Graphics AAM](https://rawgit.com/w3c/aria/master/graphics-aam/graphics-aam.html): "graphics"
* [SVG AAM](https://rawgit.com/w3c/aria/master/svg-aam/svg-aam.html): "svg"
* [AccName AAM](https://rawgit.com/w3c/aria/master/accname-aam/accname-aam.html): "accname"

**Comment by annevk** [comment]
I see. I guess it's fine to group standards together like that in a single top-level directory, although the established pattern is that the shortname of the standard is the top-level directory in web-platform-tests. That also gives you separate labels for the separate standards.

And yeah, I think you should avoid the version number. If a future revision modifies some requirements we should end up with a single test and not in a situation where an implementation has to pick between multiple tests.

**Comment by Joanmarie** [comment]
Thanks for the feedback. I will nuke the "11". But before I modify the commit, I'd like @halindrome to chime in on the structure as what I had envisioned was based on what he had done in a branch related to our automated testing work. I personally don't care where things live as long as I _know_ where they live.

Once we have consensus on the structure, I'll modify my stuff accordingly. Thanks again!

**Comment by halindrome** [comment]
I have no concerns about removing the 11.  It is there because that is in the shortname of the spec (which I strongly object to, btw).  Rip it out!

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5682/)

**Comment by Joanmarie** [comment]
Having poked around some more, I see there is already the structure described by @annevk, put into place by @halindrome. So apologies to you both.

This branch now has the aria tests and dpub-aam.

**Comment by annevk** [comment]
(No need for apologies by the way. That's what review is for.)

**Comment by Joanmarie** [comment]
Ok. I believe I am done for the moment adding and fixing tests, and it would be helpful to have these tests in the official repo so implementors can access them in the expected place.

Are there changes anyone feels should be made? (aka please re-review) Thanks!

**Comment by halindrome** [comment]
This still LGTM

**Pull request merged**
