### PR TITLE
xhr: Use .any.js syntax for access-control-{and-redirects-*,basic-allow-*} tests

### PR DESCRIPTION
**Pull request by CYBAI**
Part of #11588

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Thanks!

**Comment by annevk** [comment]
Did you try running the tests btw? Any new failures discovered in browsers?

**Comment by CYBAI** [comment]
> Did you try running the tests btw? Any new failures discovered in browsers?

Yes :) I only see one failure (`Request is redirected to a same-origin resource file` test case) in `/xhr/access-control-and-redirects-async.any.js` but I found I also get that test case failed locally in the original format 🤔

**Comment by annevk** [comment]
Hmm how? `xhr/access-control-and-redirects-async.htm` passes for me in Chrome and Firefox.

**Comment by CYBAI** [comment]
This is what I get in Firefox Nightly. I launch `wpt` serve with `./wpt serve`. Did I miss something 🤔?

| `.any.js` | `.htm` |
| -------- | ------- |
| xhr/access-control-and-redirects-async.any.js | xhr/access-control-and-redirects-async.htm |

**Comment by annevk** [comment]
And you navigate the browser to `http://web-platform.test:8000/xhr/access-control-and-redirects-async.htm`?

**Comment by CYBAI** [comment]
> And you navigate the browser to `http://web-platform.test:8000/xhr/access-control-and-redirects-async.htm`?

Ahh, I navigate it by `http://localhost:8000/xhr/access-control-and-redirects-async.htm` 😭
After navigating to `http://web-platform.test:8000`, I can pass the test case! Thanks!

**Pull request merged**
