### PR TITLE
Add test for multi-arg document.writeln

### PR DESCRIPTION
**Pull request by Sebmaster**
Really basic test, but found that lacking in jsdom.

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/html-reviewers.

**Comment by zcorpan** [comment]
LGTM

**Comment by foolip** [comment]
This test fails in at least Gecko and Blink, and I suspect in fact all browsers, because `document.body` is null. Fixed in https://github.com/w3c/web-platform-tests/pull/2386

**Comment by zcorpan** [comment]
Oops. Thanks.

**Pull request merged**
