### PR TITLE
replace serializers by toJSON for Performance

### PR DESCRIPTION
**Pull request by siusin**
Modify the test for the proposed spec change in [pull 114](https://github.com/w3c/resource-timing/pull/114).

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248435002)

# Firefox (nightly) #
Testing web-platform-tests at revision a23c7bed21dcd8a22c67de17070c3e6d72f7a82d
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6428/resource-timing/idlharness.html">/resource-timing/idlharness.html</a></summary>


|                                                                    Subtest                                                                    | Results |               Messages               |
|-----------------------------------------------------------------------------------------------------------------------------------------------|---------|--------------------------------------|
|                                                                                                                                               | OK      |                                      |
| `Performance interface: operation clearResourceTimings()`                                                                                     | PASS    |                                      |
| `Performance interface: operation setResourceTimingBufferSize(unsigned long)`                                                                 | PASS    |                                      |
| `Performance interface: attribute onresourcetimingbufferfull`                                                                                 | PASS    |                                      |
| `Performance interface: window.performance must inherit property "clearResourceTimings" with the proper type (3)`                             | PASS    |                                      |
| `Performance interface: window.performance must inherit property "setResourceTimingBufferSize" with the proper type (4)`                      | PASS    |                                      |
| `Performance interface: calling setResourceTimingBufferSize(unsigned long) on window.performance with too few arguments must throw TypeError` | PASS    |                                      |
| `Performance interface: window.performance must inherit property "onresourcetimingbufferfull" with the proper type (5)`                       | PASS    |                                      |
| `PerformanceResourceTiming interface: existence and properties of interface object`                                                           | PASS    |                                      |
| `PerformanceResourceTiming interface object length`                                                                                           | PASS    |                                      |
| `PerformanceResourceTiming interface object name`                                                                                             | PASS    |                                      |
| `PerformanceResourceTiming interface: existence and properties of interface prototype object`                                                 | PASS    |                                      |
| `PerformanceResourceTiming interface: existence and properties of interface prototype object's "constructor" property`                        | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute initiatorType`                                                                                | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute redirectStart`                                                                                | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute redirectEnd`                                                                                  | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute fetchStart`                                                                                   | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute domainLookupStart`                                                                            | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute domainLookupEnd`                                                                              | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute connectStart`                                                                                 | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute connectEnd`                                                                                   | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute secureConnectionStart`                                                                        | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute requestStart`                                                                                 | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute responseStart`                                                                                | PASS    |                                      |
| `PerformanceResourceTiming interface: attribute responseEnd`                                                                                  | PASS    |                                      |
| `PerformanceResourceTiming interface: operation toJSON()`                                                                                     | FAIL    | `Type DOMHighResTimeStamp not found` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248435004)

# Sauce (safari) #
Testing web-platform-tests at revision a23c7bed21dcd8a22c67de17070c3e6d72f7a82d
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248435018)

# Chrome (unstable) #
Testing web-platform-tests at revision a23c7bed21dcd8a22c67de17070c3e6d72f7a82d

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248435020)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision a23c7bed21dcd8a22c67de17070c3e6d72f7a82d

**Comment by toddreifsteck** [comment]
@siusin The test update looks good, but I expect to see more tests completing. Is that understood?

**Review by toddreifsteck — APPROVED** [review]
This change looks good, but we'd ideally see all tests completing before merging.

**Comment by siusin** [comment]
Update the idl test for the other affected specs: HR-time, Performance Timeline and NavTiming 2.
See discussion in RT [#112](https://github.com/w3c/resource-timing/issues/112).

**Comment by igrigorik** [comment]
@siusin thanks for updating these! 

Sanity check before we merge: looks like all the tests are green, but we know that Chrome & Edge don't implement toJSON. We'll tackle adding toJSON tests in a separate PR?

**Comment by tobie** [comment]
> We'll tackle adding toJSON tests in a separate PR?

idlharness tests for toJSON and [Default] toJSON since https://github.com/w3c/web-platform-tests/pull/6246.

**Comment by foolip** [comment]
@bobholt, same question here as in https://github.com/w3c/web-platform-tests/pull/6361, is this a known issue?

**Comment by bobholt** [comment]
@foolip Same as #6361, I believe this is known and resolved. I'll restart the build here as well.

**Comment by igrigorik** [comment]
> idlharness tests for toJSON and [Default] toJSON since #6246.

Just to confirm, the above PR automatically validates toJSON serialization for interfaces that define it? So, in this case, @siusin's update is all that's needed to get us complete coverage.. right?

Also, do we actually **need to**  specify `[Default] object toJSON()` on each interface? All of our entries inherit from PerformanceEntry object defined in performance-timeline. Do the subclasses need to specify toJSON as well?

**Comment by tobie** [comment]
> Just to confirm, the above PR automatically validates toJSON serialization for interfaces that define it? So, in this case, @siusin's update is all that's needed to get us complete coverage.. right?

Yes. Well, at least, that's the intent.

> Also, do we actually need to specify [Default] object toJSON() on each interface? All of our entries inherit from PerformanceEntry object defined in performance-timeline. Do the subclasses need to specify toJSON as well?

Yes, they need to specify it too. The default toJSON operation only considers the attributes of interfaces on which `[Default]  object toJSON();` has been specified. So if you don't specify it on subclasses, only the attributes of the parent class will be accounted for.

**Comment by igrigorik** [comment]
@tobie got it, thank you. 

Merging.

**Pull request merged**
