### PR TITLE
Update the css-paint-api IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by foolip** [comment]
No existing tests under css/css-paint-api/, so we'll need to add one.

**Comment by foolip** [comment]
> No existing tests under css/css-paint-api/, so we'll need to add one.

Still true.

**Comment by lukebjerring** [comment]
Test added, which currently fails hard (see https://github.com/w3c/css-houdini-drafts/pull/765).

**Comment by foolip** [comment]
https://github.com/w3c/css-houdini-drafts/pull/765 has been merged and propagated to https://github.com/tidoust/reffy-reports/commit/c35fc98fbc958dbdd6bbfa60fff212d56f5298fd#diff-20c75e1b0339cc7a395cb95e24c63b2d, can you update?

**Comment by lukebjerring** [comment]
Updated! Only failure in chrome is 
> SS interface: attribute paintWorklet
> assert_true: The prototype object must have a property "paintWorklet" expected true got false

**Review by foolip — APPROVED** [review]

**Pull request merged**
