### PR TITLE
Make reftests wait for fonts to load over WebDriver

### LINKED ISSUE #5412: Reftests take screenshot too early in Chrome
~~Probably https://github.com/w3c/wptrunner/issues/241~~

Almost identical to to #6328.

https://github.com/w3c/csswg-drafts/issues/1088 is the issue that causes the issue here. Notably, wptrunner needs to block screenshots on fonts loading.

cc/ @jgraham @jugglinmike @bobholt

### LINKED ISSUE #6328: Reftests take screenshot too early in Safari
Almost identical to to https://github.com/w3c/web-platform-tests/issues/5412.

https://github.com/w3c/csswg-drafts/issues/1088 is the issue that causes the issue here. Notably, wptrunner needs to block screenshots on fonts loading.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #6328. Fixes #5412. Fixes, partially, #6327.

This doesn't change the Martionette script as per https://github.com/w3c/csswg-drafts/issues/1088#issuecomment-292997364 Firefox blocks the load event on fonts loading.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6558)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253673541)

# Firefox (nightly) #
Testing web-platform-tests at revision 17f69b08033455df7b3994d08695ee057cba4e5f
Using browser at version BuildID 20170714100217; SourceStamp 67cd1ee26f2661fa5efe3d952485ab3c89af4271
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253673542)

# Sauce (safari) #
Testing web-platform-tests at revision 17f69b08033455df7b3994d08695ee057cba4e5f
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253673558)

# Chrome (unstable) #
Testing web-platform-tests at revision 9d65700a8da64a17def59ab60a7c2631c5127ea7

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253673559)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 9d65700a8da64a17def59ab60a7c2631c5127ea7

**Comment by bobholt** [comment]
This looks good to me, but I'd like to wait for @jgraham to weigh in on how we make sure it doesn't break Servo.

**Comment by jdm** [comment]
These changes will not break Servo.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by jgraham** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6558)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
