### PR TITLE
Move a lone css-break test into css-multicol/

### PR DESCRIPTION
**Pull request by foolip**
Per the `<link rel="help">`, this is the most relevant spec.

### CODE REVIEW

**Comment by foolip** [comment]
@fantasai, you wrote this test, can you confirm that css-multicol is the least wrong place to put it?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-11-20 12:55:13
Finished: 2017-11-20 13:00:09


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20831)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/304722835)

**Review by fantasai — CHANGES_REQUESTED** [review]
Actually, the test is in fact a css-break test. The URL needs updating since that section of the spec moved to the (relatively new) css-break module. This test in particular seems to be checking both multicol and page breaks, so it definitely doesn't go into the multicol folder. :)

**Comment by foolip** [comment]
Aha, https://drafts.csswg.org/css-break/ exists, I did not look that far but assumed that single test meant mishap.

**Pull request closed without merging**
