### PR TITLE
Test if gradient background covers padding

### PR DESCRIPTION
**Pull request by pyfisch**
Checks for a bug found in servo.

@glennw this is the reftest you requested for servo/servo#17395.

### CODE REVIEW

**Comment by jdm** [comment]
@pyfisch It's easier to deal with if you include the test in that PR and we upstream it to this repository automatically later.

**Comment by pyfisch** [comment]
@jdm if this is easier i will close this PR and add it to the PR. I have submitted some more tests to this repo at #5845 but it does not get reviewed. Should I also upload these tests to servo so they can be upstreamed later?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/244517262)

# Firefox (nightly) #
Testing web-platform-tests at revision 35576f8c138c4e5803ab47e10bd87ce447669514
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6273/css/css-images-3/gradient-button.html">/css/css-images-3/gradient-button.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/244517263)

# Sauce (safari) #
Testing web-platform-tests at revision 35576f8c138c4e5803ab47e10bd87ce447669514
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6273/css/css-images-3/gradient-button.html">/css/css-images-3/gradient-button.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/244517269)

# Chrome (unstable) #
Testing web-platform-tests at revision 35576f8c138c4e5803ab47e10bd87ce447669514

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/244517270)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 35576f8c138c4e5803ab47e10bd87ce447669514

**Comment by jdm** [comment]
Yes, please do both of those things.

**Pull request closed without merging**
