### PR TITLE
Add coverage annotation and new test for createDataChannel

### PR DESCRIPTION
**Pull request by soareschen**
I have updated to the tip of the tree spec as there are related PRs being merged recently.

### CODE REVIEW

**Comment by w3c-bots** [comment]
*This report has been truncated because the total content is 2168212 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245287546)

# Firefox (nightly) #
Testing web-platform-tests at revision 7b984a4a9fc3c01ce4ae26dd8a69b883a32276a7
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6300/webrtc/RTCPeerConnection-createDataChannel.html">/webrtc/RTCPeerConnection-createDataChannel.html</a></summary>


|                                           Subtest                                            | Results |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Messages

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245287547)

# Sauce (safari) #
Testing web-platform-tests at revision 7b984a4a9fc3c01ce4ae26dd8a69b883a32276a7
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6300/webrtc/RTCPeerConnection-createDataChannel.html">/webrtc/RTCPeerConnection-createDataChannel.html</a></summary>


|                                           Subtest                                            | Results |                 Messages                 |
|----------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                              | OK      |                                          |
| `createDataChannel with no argument should throw TypeError`                                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with closed connection should throw InvalidStateError`                    | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel attribute default values`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with provided parameters should initialize attributes to provided values` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label "foo" should succeed`                                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label null should succeed`                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label undefined should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label lone surrogate should succeed`                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with ordered false should succeed`                                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with ordered null/undefined should succeed`                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with maxPacketLifeTime 0 should succeed`                                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with maxRetransmits 0 should succeed`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with both maxPacketLifeTime and maxRetransmits should throw SyntaxError`  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol "foo" should succeed`                                       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol null should succeed`                                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol undefined should succeed`                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol lone surrogate should succeed`                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated true should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 0 should succeed`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 1 should succeed`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65534 should succeed`                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id -1 should throw TypeError`                                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65535 should throw TypeError`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65536 should throw TypeError`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with priority "high" should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with invalid priority should throw TypeError`                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated false and long label should throw TypeError`              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated false and long protocol should throw TypeError`           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated true and long label and long protocol should succeed`     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Channels created after SCTP transport is established should have id assigned`               | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245287553)

# Chrome (unstable) #
Testing web-platform-tests at revision 7b984a4a9fc3c01ce4ae26dd8a69b883a32276a7

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/245287554)

# Sauce (MicrosoftEdge) #

**Comment by rwaldron** [comment]
Same question I posted in #6298...

> Should this PR be blocked for merging until the changes are published in a new draft?

I'm working from the latest draft here https://w3c.github.io/webrtc-pc/ which means that I don't have some of these new steps to mark in the coverage spec.

cc @foolip

**Comment by foolip** [comment]
Commented on https://github.com/w3c/web-platform-tests/pull/6298 and pointed to https://github.com/w3c/webrtc-pc/issues/942.

Please comment there if this setup has caused you confusion or wasted time.

**Comment by soareschen** [comment]
I am fine with the PRs being merged either now or after they become official Editor's Draft. My motivation for referencing tip-of-tree draft is because there are non trivial changes added, and I want to move fast while avoid having to rewrite the tests when the next editor's draft is published. (which might be pretty soon since the last draft is a month ago?)

Note that in the tests I reference the specific version of drafts by linking to either the specific dated version or the git commit ID. This partially prevents the confusion of people reading the wrong versions when the main URLs point to new versions of the draft.

**Comment by rwaldron** [comment]
If I land PRs that I cannot actually track in the coverage spec (because the content is not present in my version), then I will accumulate workload debt until the actual spec is published. Put another way: I won't have any way of accounting for your work that applies to spec content of which doesn't yet exist in a published draft.

**Review by rwaldron — APPROVED** [review]
I will keep track of the PRs that include coverage for spec prose that is not yet published.

**Pull request merged**
