### PR TITLE
Add the test itself in get_affected_testfiles().

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/4709)

### CODE REVIEW

**Comment by tobie** [comment]
@wpt-pr-bot, are you there?

**Comment by tobie** [comment]
Double checking @wpt-pr-bot presence.

**Comment by jgraham** [comment]
Sorry I'm being thick, but I don't see what you're trying to achieve here.

**Comment by Ms2ger** [comment]
This was intended to fix #5130

**Pull request closed without merging**
