### PR TITLE
Revert "Handle CONNECT messages by keeping the server alive."

### PR DESCRIPTION
**Pull request by Hexcles**
This reverts commit 70f1c91935512d14a3d7bd91203a3fd899d8063a.

File was moved to tools/pywebsocket/mod_pywebsocket/standalone.py

### CODE REVIEW

**Comment by Hexcles** [comment]
Apparently we only process the first matched trigger on Taskcluster, so here's the Firefox Nightly run for now: https://community-tc.services.mozilla.com/tasks/groups/R0eaxjIfTqiwm5Dalur85Q

**Comment by jgraham** [comment]
So I think this was necessary when gecko CI was using autoproxy to configure the hosts. But we aren't doing that now, so reverting this won't break us, but could theoretically break anyone else trying to do that.

**Comment by Hexcles** [comment]
Looks like everything is good:
https://community-tc.services.mozilla.com/tasks/groups/R0eaxjIfTqiwm5Dalur85Q
https://wpt.fyi/results/websockets?diff&filter=ADC&run_id=441990004&run_id=441990007

@jgraham I don't think we need to worry about that potential edge case, which is only one of many unknown setups that we don't officially support. Do you want to take this PR first? Or shall we directly land #21845 ?

**Comment by Hexcles** [comment]
Hmm actually, Chrome has 231 more passes!
https://wpt.fyi/results/websockets?diff&filter=ADC&run_id=432390003&run_id=413500009

**Comment by stephenmcgruer** [comment]
I strongly suggest that we figure out *why* Chrome has 231 more passes. We don't want to accidentally let bad behavior (if thats what Chrome has) through.

**Comment by ricea** [comment]
> I strongly suggest that we figure out _why_ Chrome has 231 more passes. We don't want to accidentally let bad behavior (if thats what Chrome has) through.

I think this is the Chrome behaviour which is making the difference: https://bugs.chromium.org/p/chromium/issues/detail?id=949763. I can prioritise changing that if it helps.

**Comment by gsnedders** [comment]
https://github.com/google/pywebsocket/issues/132 (from @jgraham) is what originally motivated the change:

> For web-platform-tests we are using pywebsocket to handle websockets requests. This works fine in many situations, but for various reasons, in the Mozilla setup we don't change the DNS settings (e.g. via /etc/hosts) but instead use an autoproxy file to, in effect, reroute requests from web-platform.test to localhost.
>
> With pywebsocket this is a problem because a proxied request requires an initial CONNECT that currently can't be handled without adding a seperate proxy into the mix; something I am keen to avoid. To handle it in a way that solves this use case in pywebsocket itself just requires using HTTP 1.1 and adding code that responds to CONNECT with 200 and keeps the connection open.

…which matches what he said above.

**Comment by Hexcles** [comment]
Thanks Sam for providing the context.

I'm closing this draft PR because by migrating to pywebsocket3 we have effectively reverted this local patch.

**Pull request closed without merging**
