### PR TITLE
Update noopener tests to match spec rules for choosing a browsing con…

### PR DESCRIPTION
**Pull request by natechapin**
Per https://github.com/whatwg/html/issues/1826, a few tests are out of date with https://html.spec.whatwg.org/multipage/browsers.html#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name

html/browsers/the-window-object/window-open-noopener.html?indexed and
html/semantics/links/links-created-by-a-and-area-elements/htmlanchorelement_noopener.html
both assert that specifying noopener will prevent reuse of an existing named browser context, but the spec does not include this special case.

### CODE REVIEW

**Comment by annevk** [comment]
These changes make me realize there's something we did not discuss. Whether opener should be cleared or not. Currently the specification does not require that (look at the "window open steps", it never sets the opener browsing context to null). It probably makes sense, even though it could have been leaked already via another popup or so, but that would also require a further specification change.

**Comment by natechapin** [comment]
> These changes make me realize there's something we did not discuss. Whether opener should be cleared or not. Currently the specification does not require that (look at the "window open steps", it never sets the opener browsing context to null). It probably makes sense, even though it could have been leaked already via another popup or so, but that would also require a further specification change.

I don't feel strongly. FWIW, chromium doesn't currently clear the opener, but if the spec changes, I'm happy to update it.

**Comment by annevk** [comment]
Okay, but these test changes make it look like you were assuming such a spec change, or am I missing something? In particular they suggest that you should reuse but also not have an opener, whereas the specification says you should reuse and have an opener. I'd suggest we test the spec as-is first and then do a change separately, if desired.

**Comment by natechapin** [comment]
> Okay, but these test changes make it look like you were assuming such a spec change, or am I missing something? In particular they suggest that you should reuse but also not have an opener, whereas the specification says you should reuse and have an opener. I'd suggest we test the spec as-is first and then do a change separately, if desired.

That was poor naming on my part, sorry for the confusion. I've renamed "shouldHaveOpener" in window-open-nooopener.html to "shouldReturnWindow", which better described what the spec expects. When shouldReturnWindow is false because of noopener, the test case communicates with the target browsing context via the BroadcastChannel to ensure that the opener was not cleared even though the window.open() call returned null.

**Review by annevk — APPROVED** [review]
Thank you, this looks great!

**Comment by annevk** [comment]
So from https://github.com/whatwg/html/issues/1826#issuecomment-458586037 the main thing remaining here is implementation bugs I suppose?

**Comment by natechapin** [comment]
> So from [whatwg/html#1826 (comment)](https://github.com/whatwg/html/issues/1826#issuecomment-458586037) the main thing remaining here is implementation bugs I suppose?

https://bugs.chromium.org/p/chromium/issues/detail?id=961816
https://bugzilla.mozilla.org/show_bug.cgi?id=1550840

**Pull request merged**
