### PR TITLE
Cross-origin objects: symbol properties are not enumerable

### PR DESCRIPTION
**Pull request by annevk**
Second follow-up for #6538.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255234256)

# Firefox (nightly) #
Testing web-platform-tests at revision 780d4b3cfd932eb119cb1ccc993db0d24407bae0
Using browser at version BuildID 20170718164211; SourceStamp dece50457378ac4934afe9fb3c2a8054e8894588
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6583/html/browsers/origin/cross-origin-objects/cross-origin-objects.html">/html/browsers/origin/cross-origin-objects/cross-origin-objects.html</a></summary>


|                                              Subtest                                               | Results |                                                        Messages                                                       |
|----------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------|
|                                                                                                    | OK      |                                                                                                                       |
| `Basic sanity-checking`                                                                            | PASS    |                                                                                                                       |
| `Only whitelisted properties are accessible cross-origin`                                          | PASS    |                                                                                                                       |
| `[[GetPrototypeOf]] should return null`                                                            | PASS    |                                                                                                                       |
| `[[SetPrototypeOf]] should return false`                                                           | PASS    |                                                                                                                       |
| `[[IsExtensible]] should return true for cross-origin objects`                                     | PASS    |                                                                                                                       |
| `[[PreventExtensions]] should throw for cross-origin objects`                                      | PASS    |                                                                                                                       |
| `[[GetOwnProperty]] - Properties on cross-origin objects should be reported \|own\|`               | PASS    |                                                                                                                       |
| `[[GetOwnProperty]] - Property descriptors for cross-origin properties should be set up correctly` | FAIL    | `assert_equals: property descriptor for 0 should be enumerable expected true but got false`                           |
| `[[Delete]] Should throw on cross-origin objects`                                                  | PASS    |                                                                                                                       |
| `[[DefineOwnProperty]] Should throw for cross-origin objects`                                      | PASS    |                                                                                                                       |
| `Can only enumerate safelisted properties`                                                         | FAIL    | `assert_equals: Enumerate all safelisted cross-origin Window properties expected 15 but got 0`                        |
| `[[OwnPropertyKeys]] should return all properties from cross-origin objects`                       | FAIL    | `assert_array_equals: Object.keys() gives the right answer for cross-origin Window lengths differ, expected 15 got 0` |
| `[[OwnPropertyKeys]] should return the right symbol-named properties for cross-origin objects`     | PASS    |                                                                                                                       |
| `[[OwnPropertyKeys]] should place the symbols after the property names after the subframe indices` | PASS    |                                                                                                                       |
| `A and B jointly observe the same identity for cross-origin Window and Location`                   | PASS    |                                                                                                                       |
| `Cross-origin functions get local Function.prototype`                                              | PASS    |                                                                                                                       |
| `Cross-origin Window accessors get local Function.prototype`                                       | PASS    |                                                                                                                       |
| `Same-origin observers get different functions for cross-origin objects`                           | PASS    |                                                                                                                       |
| `Same-origin observers get different accessors for cross-origin Window`                            | PASS    |                                                                                                                       |
| `Same-origin observers get different accessors for cross-origin Location`                          | PASS    |                                                                                                                       |
| `{}.toString.call() does the right thing on cross-origin objects`                                  | PASS    |                                                                                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255234257)

# Sauce (safari) #
Testing web-platform-tests at revision 780d4b3cfd932eb119cb1ccc993db0d24407bae0
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6583/html/browsers/origin/cross-origin-objects/cross-origin-objects.html">/html/browsers/origin/cross-origin-objects/cross-origin-objects.html</a></summary>


|                                              Subtest                                               | Results |                                                                                     Messages                                                                                     |
|----------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                    | OK      |                                                                                                                                                                                  |
| `Basic sanity-checking`                                                                            | FAIL    | `assert_throws: location.pathname throws cross-origin function "function () { C.location.pathname; }" did not throw`                                                             |
| `Only whitelisted properties are accessible cross-origin`                                          | FAIL    | `assert_throws: Should throw when accessing testList on Window function "function () { C[prop]; }" did not throw`                                                                |
| `[[GetPrototypeOf]] should return null`                                                            | FAIL    | `assert_true: cross-origin Window proto is null expected true got false`                                                                                                         |
| `[[SetPrototypeOf]] should return false`                                                           | FAIL    | `assert_throws: proto set on cross-origin Window function "function () { C.__proto__ = new Object(); }" did not throw`                                                           |
| `[[IsExtensible]] should return true for cross-origin objects`                                     | PASS    |                                                                                                                                                                                  |
| `[[PreventExtensions]] should throw for cross-origin objects`                                      | FAIL    | `assert_throws: preventExtensions on cross-origin Window should throw function "function () { Object.preventExtensions(C) }" did not throw`                                      |
| `[[GetOwnProperty]] - Properties on cross-origin objects should be reported \|own\|`               | PASS    |                                                                                                                                                                                  |
| `[[GetOwnProperty]] - Property descriptors for cross-origin properties should be set up correctly` | FAIL    | `assert_equals: property descriptor for 0 should be configurable expected true but got false`                                                                                    |
| `[[Delete]] Should throw on cross-origin objects`                                                  | FAIL    | `assert_throws: Can't delete cross-origin indexed property function "function () { delete C[0]; }" did not throw`                                                                |
| `[[DefineOwnProperty]] Should throw for cross-origin objects`                                      | FAIL    | `assert_throws: Can't define cross-origin value property length function "function () { Object.defineProperty(obj, prop, valueDesc); }" did not throw`                           |
| `Can only enumerate safelisted properties`                                                         | FAIL    | `assert_equals: Enumerate all safelisted cross-origin Window properties expected 15 but got 0`                                                                                   |
| `[[OwnPropertyKeys]] should return all properties from cross-origin objects`                       | FAIL    | `assert_array_equals: Object.getOwnPropertyNames() gives the right answer for cross-origin Window lengths differ, expected 15 got 0`                                             |
| `[[OwnPropertyKeys]] should return the right symbol-named properties for cross-origin objects`     | FAIL    | `assert_array_equals: Object.getOwnPropertySymbols() should return the three symbol-named properties that are exposed on a cross-origin Window lengths differ, expected 3 got 0` |
| `[[OwnPropertyKeys]] should place the symbols after the property names after the subframe indices` | FAIL    | `assert_array_equals: Reflect.ownKeys should start with the indices exposed on the cross-origin window. lengths differ, expected 2 got 0`                                        |
| `A and B jointly observe the same identity for cross-origin Window and Location`                   | PASS    |                                                                                                                                                                                  |
| `Cross-origin functions get local Function.prototype`                                              | PASS    |                                                                                                                                                                                  |
| `Cross-origin Window accessors get local Function.prototype`                                       | FAIL    | `undefined is not an object (evaluating 'f.name')`                                                                                                                               |
| `Same-origin observers get different functions for cross-origin objects`                           | PASS    |                                                                                                                                                                                  |
| `Same-origin observers get different accessors for cross-origin Window`                            | FAIL    | `assert_true: different Window accessors per-incumbent script settings object expected true got false`                                                                           |
| `Same-origin observers get different accessors for cross-origin Location`                          | FAIL    | `assert_true: different Location accessors per-incumbent script settings object expected true got false`                                                                         |
| `{}.toString.call() does the right thing on cross-origin objects`                                  | FAIL    | `assert_equals: expected "[object Object]" but got "[object Window]"`                                                                                                            |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255234263)

# Chrome (unstable) #
Testing web-platform-tests at revision 780d4b3cfd932eb119cb1ccc993db0d24407bae0

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255234264)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 780d4b3cfd932eb119cb1ccc993db0d24407bae0

**Comment by bzbarsky** [comment]
Looks good, thank you!

**Comment by annevk** [comment]
Added a test for same-origin indexed properties now. Finds bugs in Chrome and Safari.

**Comment by annevk** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=174649 and https://bugs.chromium.org/p/chromium/issues/detail?id=746418.

**Review by cdumez — APPROVED** [review]
LGTM

**Pull request merged**
