### PR TITLE
Remove tentative from lazy load tests

### PR DESCRIPTION
**Pull request by rwlbuis**
https://github.com/whatwg/html/pull/3752 landed, so
remove comments and tentative extension.

### CODE REVIEW

**Review by domfarolino — APPROVED** [review]

**Comment by annevk** [comment]
It's a little weird for these to be a in top-level loading diretory. We we put them with the img element inside `html/semantics/embedded-content/the-img-element/`?

**Comment by domfarolino** [comment]
Yes we discussed moving these at some point, but I guess we haven't done it yet. @rwlbuis do you want to go ahead and include the move in this PR?

And no worries @annevk

**Comment by rwlbuis** [comment]
> Yes we discussed moving these at some point, but I guess we haven't done it yet. @rwlbuis do you want to go ahead and include the move in this PR?

Yes, will do.

**Comment by rwlbuis** [comment]
> Yes we discussed moving these at some point, but I guess we haven't done it yet. @rwlbuis do you want to go ahead and include the move in this PR?

Done. Is it ok to remove META.yml?

**Comment by annevk** [comment]
You might want to keep it if you want to get review requests for changes in that directory.

**Comment by rwlbuis** [comment]
> You might want to keep it if you want to get review requests for changes in that directory.

Don't really want review requests personally :) Anyway I think it will become clear who could be reviewers for lazy image loading. Or we could add it later if there is a lot of confusion.

**Pull request merged**
