### PR TITLE
Added parentheses to check minimum of 32 nested pairs inside calc

### PR DESCRIPTION
**Pull request by TalbotG**
- I added 8 pairs of nested parentheses to the original test
- I corrected title text
- I improved the text assert
- I referenced issue 3462
https://github.com/w3c/csswg-drafts/issues/3462
in a comment
@FremyCompany

### CODE REVIEW

**Comment by frivoal** [comment]
Blocked on https://github.com/w3c/csswg-drafts/issues/3462

**Comment by FremyCompany** [comment]
Sounds fine by me, pending resolution as mentioned by @frivoal above.

**Review by FremyCompany — COMMENTED** [review]
We might want to add one more nesting level, if we resolve to clarify the nesting level not to include the `calc()` itself. See https://github.com/w3c/csswg-drafts/issues/3462#issuecomment-478579269

**Comment by TalbotG** [comment]
@FremyCompany
François,
You want one more nesting level in the test, right? 33 pairs of parentheses. Or 32 **nested pairs** of parentheses **inside**  `calc()` , right?

**Comment by FremyCompany** [comment]
@TalbotG If the tests still passes with 32 nested parentheses inside the `calc()` then yes. Could you check if all browsers (that support 31 right now) support that? If yes, I'd say we should update the test. If not, maybe let's leave it as is.

**Comment by TalbotG** [comment]
Blink and WebKit engines fails with 32 nested parentheses inside the calc():

http://www.gtalbot.org/BrowserBugsSection/CSS3Values/HowManyNestedParenthesesCalc.html

**Comment by FremyCompany** [comment]
Okay, then let's approve as-is. Thanks for taking a look!

**Review by FremyCompany — APPROVED** [review]

**Pull request merged**
