### PR TITLE
Use correct color.

### PR DESCRIPTION
**Pull request by tgraham-antenna**
Test text and reference page both use 'red' instead of 'blue'.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242484077)

# Firefox (nightly) #
Testing web-platform-tests at revision 4269065e98c2dca81ac6b78b074d440df2ec5874
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6226/css/css-backgrounds-3/background-clip-content-box-001.html">/css/css-backgrounds-3/background-clip-content-box-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242484078)

# Sauce (safari) #
Testing web-platform-tests at revision 4269065e98c2dca81ac6b78b074d440df2ec5874
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6226/css/css-backgrounds-3/background-clip-content-box-001.html">/css/css-backgrounds-3/background-clip-content-box-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242484084)

# Chrome (unstable) #
Testing web-platform-tests at revision 4269065e98c2dca81ac6b78b074d440df2ec5874
Using browser at version 61.0.3124.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6226/css/css-backgrounds-3/background-clip-content-box-001.html">/css/css-backgrounds-3/background-clip-content-box-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/242484085)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 4269065e98c2dca81ac6b78b074d440df2ec5874

**Review by gsnedders — DISMISSED** [review]
It'd be better to change this to use blue everywhere (and probably orange instead of green), given in 99% of cases the presence of red indicates a failure.

**Comment by tgraham-antenna** [comment]
Yes, it would be better to change everything to blue, but I was going for the least disruption.

It turns out that the reference page is only also used by 'css-backgrounds-3/css3-background-clip-content-box.html'.  The reference does not match the expected result for that test anyway, but if you are arguing against red and green, you might want to also change the red and green in that test.

**Review by Ms2ger — APPROVED** [review]
Looks like this needs a rebase.

**Comment by TalbotG** [comment]
People should not be doing this:
`* { padding: 0; margin: 0; }`
 in tests. We should remove such zero-reset from tests.

**Comment by Ms2ger** [comment]
Rebased as https://github.com/w3c/web-platform-tests/pull/10814

**Pull request closed without merging**
