### PR TITLE
[geometry] Test new DOMMatrix("none") and variants

### LINKED ISSUE #5497: Add tests for `new DOMMatrix('none')`
Originally posted as https://github.com/w3c/csswg-test/issues/1173 by @zcorpan on 12 Jan 2017, 20:22 UTC:

> See https://github.com/w3c/fxtf-drafts/issues/55
> 
> Variants to test: leading/trailing whitespace, uppercase, CSS comments before/after. (should all work I think)
> 
> Also: empty string (should work), and only whitespace (should throw).
> 
> https://github.com/w3c/csswg-test/blob/master/geometry-1/DOMMatrix-001.html
> 
> cc @tim-loh

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #5497.

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5777/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228643429)

# Firefox (nightly channel) #
Testing web-platform-tests at revision da7d73ee6378ae891da2b374b39e16e08eb95325
Using browser at version BuildID 20170503100422; SourceStamp 82c2d17e74ef9cdf38a5d5ac4eb3ae846ec30ba4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5777/css/geometry-1/DOMMatrix-001.html">/css/geometry-1/DOMMatrix-001.html</a></summary>


|                                 Subtest                                 | Results |                                                                                                             Messages                                                                                                            |
|-------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                         | OK      |                                                                                                                                                                                                                                 |
| `new DOMMatrix()`                                                       | FAIL    | `assert_equals: Expected value for isIdentity is true expected (boolean) true but got (undefined) undefined`                                                                                                                    |
| `new DOMMatrix(undefined)`                                              | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix(new DOMMatrix())`                                        | FAIL    | `assert_equals: Expected value for isIdentity is true expected (boolean) true but got (undefined) undefined`                                                                                                                    |
| `new DOMMatrix("none")`                                                 | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix(" none")`                                                | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("none ")`                                                | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("NONE")`                                                 | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("none/**/")`                                             | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("/**/none")`                                             | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("")`                                                     | FAIL    | `assert_equals: Expected value for isIdentity is true expected (boolean) true but got (undefined) undefined`                                                                                                                    |
| `new DOMMatrix(float32Array) 16 elements`                               | FAIL    | `Index or size is negative or greater than the allowed amount`                                                                                                                                                                  |
| `new DOMMatrix(float32Array) 6 elements`                                | FAIL    | `Index or size is negative or greater than the allowed amount`                                                                                                                                                                  |
| `new DOMMatrix(float64Array) 16 elements`                               | FAIL    | `assert_equals: Expected value for is2D is false expected false but got true`                                                                                                                                                   |
| `new DOMMatrix((float64Array) 6 elements`                               | FAIL    | `Index or size is negative or greater than the allowed amount`                                                                                                                                                                  |
| `new DOMMatrix(sequence) 16 elements`                                   | FAIL    | `assert_equals: Expected value for is2D is false expected false but got true`                                                                                                                                                   |
| `new DOMMatrix(sequence) 6 elements`                                    | FAIL    | `assert_equals: Expected value for is2D is false expected false but got true`                                                                                                                                                   |
| `new DOMMatrix("scale(2) translateX(5px) translateY(5px)")`             | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("scale(2 2) translateX(5) translateY(5)")`               | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("scale(2, 2), translateX(5)  ,translateY(5)")`           | FAIL    | `An invalid or illegal string was specified`                                                                                                                                                                                    |
| `new DOMMatrix("translateX    (5px)")`                                  | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("scale(2)translateX(5px)")`                              | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5em)")`                                      | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5ex)")`                                      | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5ch)")`                                      | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5rem)")`                                     | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5vw)")`                                      | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5vh)")`                                      | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5vmin)")`                                    | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5vmax)")`                                    | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("translateX(5%)")`                                       | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix(" ")`                                                    | FAIL    | `assert_throws: function "function() { new self[constr](string); }" did not throw`                                                                                                                                              |
| `new DOMMatrix("/**/")`                                                 | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("\0")`                                                   | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix(";")`                                                    | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("none;")`                                                | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("null")`                                                 | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix(null)`                                                   | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("undefined")`                                            | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("inherit")`                                              | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("initial")`                                              | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix("unset")`                                                | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix(sequence)`                                               | FAIL    | `assert_equals: Expected value for is2D is false expected false but got true`                                                                                                                                                   |
| `new DOMMatrix(matrix)`                                                 | FAIL    | `assert_equals: Expected value for is2D is false expected false but got true`                                                                                                                                                   |
| `new DOMMatrix("scale(2, 2), translateX(5px) translateY(5px)")`         | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrix(sequence) 17 elements`                                   | FAIL    | `assert_throws: function "function() { new self[constr](sequence); }" threw object "IndexSizeError: Index or size is negative or greater than the allowed amount" ("IndexSizeError") expected object "TypeError" ("TypeError")` |
| `new DOMMatrix(sequence) 15 elements`                                   | FAIL    | `assert_throws: function "function() { new self[constr](sequence); }" threw object "IndexSizeError: Index or size is negative or greater than the allowed amount" ("IndexSizeError") expected object "TypeError" ("TypeError")` |
| `new DOMMatrix(sequence) 5 elements`                                    | FAIL    | `assert_throws: function "function() { new self[constr](sequence); }" threw object "IndexSizeError: Index or size is negative or greater than the allowed amount" ("IndexSizeError") expected object "TypeError" ("TypeError")` |
| `new DOMMatrix(sequence) 0 elements`                                    | FAIL    | `assert_throws: function "function() { new self[constr](sequence); }" threw object "IndexSizeError: Index or size is negative or greater than the allowed amount" ("IndexSizeError") expected object "TypeError" ("TypeError")` |
| `new DOMMatrixReadOnly()`                                               | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(undefined)`                                      | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(new DOMMatrixReadOnly())`                        | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("none")`                                         | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(" none")`                                        | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("none ")`                                        | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("NONE")`                                         | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("none/**/")`                                     | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("/**/none")`                                     | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("")`                                             | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(float32Array) 16 elements`                       | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(float32Array) 6 elements`                        | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(float64Array) 16 elements`                       | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly((float64Array) 6 elements`                       | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(sequence) 16 elements`                           | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(sequence) 6 elements`                            | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("scale(2) translateX(5px) translateY(5px)")`     | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("scale(2 2) translateX(5) translateY(5)")`       | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("scale(2, 2), translateX(5)  ,translateY(5)")`   | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("translateX    (5px)")`                          | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("scale(2)translateX(5px)")`                      | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5em)")`                              | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5ex)")`                              | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5ch)")`                              | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5rem)")`                             | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5vw)")`                              | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5vh)")`                              | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5vmin)")`                            | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5vmax)")`                            | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("translateX(5%)")`                               | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly(" ")`                                            | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("/**/")`                                         | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("\0")`                                           | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly(";")`                                            | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("none;")`                                        | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("null")`                                         | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly(null)`                                           | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("undefined")`                                    | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("inherit")`                                      | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("initial")`                                      | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly("unset")`                                        | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly(sequence)`                                       | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly(matrix)`                                         | FAIL    | `Illegal constructor.`                                                                                                                                                                                                          |
| `new DOMMatrixReadOnly("scale(2, 2), translateX(5px) translateY(5px)")` | FAIL    | `assert_throws: function "function() { new self[constr](string); }" threw object "TypeError: Illegal constructor." that is not a DOMException SyntaxError: property "code" is equal to undefined, expected 12`                  |
| `new DOMMatrixReadOnly(sequence) 17 elements`                           | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrixReadOnly(sequence) 15 elements`                           | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrixReadOnly(sequence) 5 elements`                            | PASS    |                                                                                                                                                                                                                                 |
| `new DOMMatrixReadOnly(sequence) 0 elements`                            | PASS    |                                                                                                                                                                                                                                 |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228643435)

# Chrome (unstable channel) #
Testing web-platform-tests at revision da7d73ee6378ae891da2b374b39e16e08eb95325

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Looks like a lot of failing in Firefox. I guess this is correct per spec, but what step in https://drafts.fxtf.org/geometry/#dom-dommatrix-dommatrix should I follow to get into a parser that handles comments and whitespace?

**Comment by zcorpan** [comment]
Geometry defers to SVG `transform` attribute. https://drafts.csswg.org/css-transforms-1/#two-d-transform-functions is defined in terms of CSS V&U grammar, which says:
https://drafts.csswg.org/css-values-3/#component-whitespace

https://drafts.csswg.org/css-values-3/#numbers references css-syntax.

It's not super-clear, for sure...

**Pull request merged**
