### PR TITLE
tests for PaymentRequest.shippingType attr

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260030514)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260030515)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260030522)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260030524)

# Sauce (MicrosoftEdge) #

**Comment by bentian** [comment]
Should we remove [duplicate tests in constructor.https](https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor.https.html#L813) accordingly?

**Comment by marcoscaceres** [comment]
Nah, I think it's ok to leave them. They are slightly different.

**Comment by marcoscaceres** [comment]
@alphan102, could you kindly review?

**Review by edenchuang — APPROVED** [review]
LGTM

**Pull request merged**
