### PR TITLE
Make Safari an allowed failure for stability check

### PR DESCRIPTION
**Pull request by sideshowbarker**
Relates to https://github.com/w3c/web-platform-tests/issues/6602

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6791)

### CODE REVIEW

**Review by jgraham — APPROVED** [review]

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/262669457)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/262669458)

# Sauce (MicrosoftEdge) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/262669465)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/262669466)

# Sauce (safari) #

**Pull request merged**
