### PR TITLE
Remove duplicated css-fonts variations tests

### PR DESCRIPTION
**Pull request by foolip**
These were accidentally duplicated by Chromium export:
https://bugs.chromium.org/p/chromium/issues/detail?id=755510

The files are byte-for-byte identical with the ones in
css-fonts/variations/, moved here:
https://github.com/w3c/web-platform-tests/pull/6442

### CODE REVIEW

**Comment by foolip** [comment]
@drott FYI.

**Comment by foolip** [comment]
I'll go ahead and merge without review since this was a mishap and the files are still identical.

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 13:27:48
Finished: 2017-08-15 13:32:34



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17416)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264739750)

**Comment by w3c-bots** [comment]
# Build ERRORED

Started: 2017-08-15 13:27:48
Finished: 2017-08-15 13:32:34



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17416)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264739750)

**Comment by foolip** [comment]
@bobholt, not sure what happened here, I guess when I merge the PR before the results are in everything breaks?

**Comment by bobholt** [comment]
@foolip Travis runs the builds based on the merge commit generated from the PR. When a PR is merged, (apparently) that commit disappears and the build jobs aren't able to fetch it. The error I'm seeing on Travis in all of the jobs is then `The command "eval git fetch origin +refs/pull/6894/merge: " failed.`

**Comment by foolip** [comment]
That makes sense. Hopefully this doesn't happen often, but if it does I think a PR like this could be excluded from latency stats, it's just as if I'd pushed directly to master.

**Pull request merged**
