### PR TITLE
adding document.body.onfoo and window.onfoo mirror test

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@Ms2ger , @jdm I've added a test for one of the events in the specs. I don't think it is very right. Do let me know the required changes before I move to the other tests. Resolving #2258

### CODE REVIEW

**Comment by Ms2ger** [comment]
Will try to look tomorrow.

**Comment by jgraham** [comment]
I added some comments on critic; let me know if you can't see them.

**Comment by martiansideofthemoon** [comment]
@jgraham I've added the changes you mentioned. Do I just create files for each of the events mentioned by @Ms2ger ?

**Comment by Ms2ger** [comment]
I think it would be better to put them all in the same file, but each in their own `test(..)`.

**Comment by jgraham** [comment]
Yup, one file and a loop would be ideal

**Comment by martiansideofthemoon** [comment]
@jgraham would something like this do? What did you mean by a loop? Do I deal with the onafterprint type of handlers in a similar fashion?

**Comment by jdm** [comment]
I assume a loop means something like this:
```js
var handlers = ['afterprint', 'storage', 'load', /*etc/*];
handlers.forEach(function(handler) {
  //perform a test() using handler
});
```

**Comment by martiansideofthemoon** [comment]
@jdm :- Wouldn't that require the use of `element.addEventListener()` ? How will I get the EventListener for the `assert`?

**Comment by jdm** [comment]
`element['on' + handler] = ...`

**Comment by martiansideofthemoon** [comment]
@jgraham I hope it's okay now.

**Comment by jgraham** [comment]
Nearly there, just a couple of trivial style issues.

**Comment by martiansideofthemoon** [comment]
@jgraham fixed the style errors.

**Comment by martiansideofthemoon** [comment]
@jgraham One last thing, is the file name appropriate? In the case it isn't, would simply renaming it do? Or would I have to update the `manifest`?

**Comment by jgraham** [comment]
Good catch!

Update the name to something that's not specific to the blur attribute. It's hard to think of something great from this case but e.g. event-handler-attributes-body-window.html might be good. Also, please squash your commits.

**Comment by martiansideofthemoon** [comment]
@jgraham would I need to update the `manifest` file? I get a "test not found body-blur.html" when I just rename the file

**Comment by jgraham** [comment]
To run the test locally, yes, but the manifest file isn't committed so you don't need any additional changes in the PR.

**Comment by martiansideofthemoon** [comment]
I hope it is okay now :smile:

**Comment by jgraham** [comment]
Perfect, thanks!

**Pull request merged**
