### PR TITLE
Notifications: Notification.get is removed

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/notifications/issues/37.

### CODE REVIEW

**Comment by annevk** [comment]
But it should be exposed in workers per the specification and it seems reasonable to test this there too as well as future historical things, no?

**Comment by foolip** [comment]
I'm not sure if I follow. It was renamed and moved to some other interface in the spec. The only thing that might happen here is that Gecko accidentally starts exposing `Notification.get` in workers as well, but that seems too unlikely to test for.

The Safari failure is for a valid reason, just not what the test is for. If you'd like to keep the worker test, using `assert_implements` is an option.

**Comment by annevk** [comment]
I don't really understand why I have to workaround a Safari bug here.

**Comment by foolip** [comment]
Failures that aren't for the reason that they first seem to be (based on test/subtest name) are a nuisance, they reduce the signal-to-noise ratio when working with WPT failures in a systematic way, whether it's triaging new failures or just trying to understand the numbers of a directory. Where we can make the failure cause obvious I think we should, and if the failure cause is already captured well elsewhere (https://wpt.fyi/results/notifications/idlharness.https.any.worker.html) just working around it is better IMHO. In this case the simple workaround would be not having the worker test at all, which is very unlikely to ever begin failing for the right reasons in any browser.

**Review by saschanaz — APPROVED** [review]
Being nice to Safari is okay but I don't think it's required here.

**Comment by saschanaz** [comment]
(There's an existing historical test with `assert_implements`, btw:

https://github.com/web-platform-tests/wpt/blob/7b0ebaccc62b566a1965396e5be7bb2bc06f841f/speech-api/historical.html#L20-L33

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
