### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by marcoscaceres**
Add rsolomakhin

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@rsolomakhin, is it ok to add you as co-owner? Means you get auto-notified when I add new tests, and you get auto assigned for review.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857449)

# Firefox (nightly) #
Testing web-platform-tests at revision c2d6ac6824ba0b1e3ffed0a1adbfed0c242289b1
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857450)

# Sauce (safari) #
Testing web-platform-tests at revision 7aa0b3eeb9749e3ad8583f40a3048db26e3db335
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857456)

# Chrome (unstable) #
Testing web-platform-tests at revision 7aa0b3eeb9749e3ad8583f40a3048db26e3db335
('pip', 'install', '-r', '/home/travis/build/w3c/web-platform-tests/tools/wptrunner/requirements_chrome.txt') exited with return code 2
Collecting mozprocess>=0.19 (from -r /home/travis/build/w3c/web-platform-tests/tools/wptrunner/requirements_chrome.txt (line 1))

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239857457)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 7aa0b3eeb9749e3ad8583f40a3048db26e3db335

**Comment by marcoscaceres** [comment]
@RByers, can you help me find an OWNER on the Chrome side? It would be amazing if we could collaborate more closely on these tests. Right now, it's just Firefox folks reviewing each other's tests (and me filing bugs on Chrome when I find issues).

**Comment by RByers** [comment]
Shoot, sorry for the long delay (still getting caught up on old GH notifications during a vacation).  I'll follow up now and get you a response - I agree there should be someone at Google reviewing upstream.  Note that we have downstream owners [here](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/external/wpt/payment-request/OWNERS) - yes including @rsolomakhin.

**Comment by marcoscaceres** [comment]
@rsolomakhin, what say you? Can you help with the incoming Payment Request tests... I've landed about 95% of them already, but would really appreciate another set of eyes.

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-09-07 05:48:26
Finished: 2017-09-07 05:53:27


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18249)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/272745921)

**Comment by rsolomakhin** [comment]
It's OK to add me as a reviewer. Sorry this post slipped under my radar initially.

**Review by rsolomakhin — APPROVED** [review]
LGTM!

**Review by foolip — APPROVED** [review]

**Pull request merged**
