### PR TITLE
Update interfaces/picture-in-picture.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/1c5a999/ed/idl/picture-in-picture.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/588932563

### CODE REVIEW

**Review by lukebjerring — APPROVED** [review]

**Comment by lukebjerring** [comment]
Suspicious that both prod and staging time out in safari; @foolip I'll let you investigate.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=32022&view=logs&jobId=bf8f5026-3d1f-5955-26be-17f9e1ef0bb3 says this:
```
Running 1 tests in web-platform-tests

  ▶ TIMEOUT [expected OK] /picture-in-picture/idlharness.window.html

  ▶ Unexpected subtest result in /picture-in-picture/idlharness.window.html:
  │ TIMEOUT [expected PASS] idl_test setup
  └   → Test timed out
```

So the timeout was in the setup test.

**Comment by foolip** [comment]
It wasn't a timeout on master:
https://wpt.fyi/results/picture-in-picture/idlharness.window.html?run_id=316530001&run_id=311100002&run_id=337810001&run_id=335860003

**Comment by foolip** [comment]
I suspect one of the two async helpers in https://github.com/web-platform-tests/wpt/blob/master/picture-in-picture/resources/picture-in-picture-helpers.js never resolve. But it seems unlikely it's because of these changes, and I can't see that failure mode in the history of the test.

**Comment by foolip** [comment]
It looks like the video element is never inserted into the document and I wonder if perhaps it just won't start loading then. But I don't know why that would be flaky.

I'll close and reopen to retrigger to see if this is flaky or a persistent timeout.

**Comment by foolip** [comment]
Still a timeout where it wasn't before, so it might not be flakiness. Will have to dig more into this.

**Comment by foolip** [comment]
STP has changed since I last took a look, so I rebased the branch. https://wpt.fyi/results/picture-in-picture/idlharness.window.html?diff&filter=ADC&run_id=355990001&run_id=329790001 shows the same state before and after, so I'm merging now.

**Pull request merged**
