### PR TITLE
remove remaining invalid/challenged cell expectations in display-contents-role-and-label

### PR DESCRIPTION
**Pull request by cookiecrook**
Closes https://github.com/web-platform-tests/interop-accessibility/issues/150

### CODE REVIEW

**Comment by cookiecrook** [comment]
FYI @rahimabdi since you wrote this test, and @twilco @nmlapre since you discussed at TPAC. Seems like these were overlooked in the fix WPT PR raised to resolve this problem: 
- https://github.com/web-platform-tests/interop-accessibility/issues/119

**Comment by cookiecrook** [comment]
I took out too much... Marking as Draft PR while I fix that.

**Comment by cookiecrook** [comment]
results diff looks a little bit more impactful than it is, 8 label tests were removed, but 8 more role tests had a prefix removed from the test name, so the delta makes it look like -16+8 instead of just -8... 🤷

**Review by twilco — APPROVED** [review]

**Review by nmlapre — APPROVED** [review]
Looks good, thanks. Not sure why I didn't list those tests in my original bug - my bad.

**Comment by cookiecrook** [comment]
You may have... Sorry for missing them the first time.

**Pull request merged**
