### PR TITLE
[css-scrollbars] Inheritance, initial values

### PR DESCRIPTION
**Pull request by ewilligers**
Properties inherit or not according to the spec.
Properties have initial values according to the spec.
https://drafts.csswg.org/css-scrollbars/#property-index

### CODE REVIEW

**Comment by ewilligers** [comment]
The inheritance tests were failing in Firefox when
scrollbar-color was light and scrollbar-width was 10px.
    
Changed the values used for inheritance testing, to allow the
inheritance tests to pass with the current Firefox implementation.
    
(The scrollbar-color initial value test still fails in Firefox.)

**Comment by upsuper** [comment]
Filed w3c/csswg-drafts#3237 for that.

**Comment by upsuper** [comment]
The latest nightly should pass all tests here now.

**Comment by ewilligers** [comment]
The spec is clear that `auto` is the expected computed value for `scrollbar-color` initial value:

> Initial: auto

>  Computed value: keyword or two computed colors

> If this property computes to value other than auto

@tantek Please review.

**Comment by upsuper** [comment]
But the result of gCS is resolved value, which is not necessarily computed value. Anyway the group has resolved on have keywords keep being keywords in resolved value.

**Comment by ewilligers** [comment]
@upsuper  Please review.  I  have updated the commit message so it no longer mentions Firefox.

**Review by upsuper — APPROVED** [review]
LGTM. `auto` should work now given the resolution a while back.

**Pull request merged**
