### PR TITLE
Conformance tests for IntersectionObserver.

### PR DESCRIPTION
**Pull request by szager-chromium**
Spec: http://wicg.github.io/IntersectionObserver/

### CODE REVIEW

**Comment by sideshowbarker** [comment]
The lint tool found some problems that need to be fixed—

https://travis-ci.org/w3c/web-platform-tests/jobs/186189394

> INDENT TABS: intersection-observer/cross-origin-iframe.html 37 Tabs used for indentation
> INDENT TABS: intersection-observer/timestamp.html 55 Tabs used for indentation
> INDENT TABS: intersection-observer/timestamp.html 82 Tabs used for indentation

**Comment by RByers** [comment]
szager-chromium@ if there's someone who's familiar with the details of the Intersection Observer spec that can review this (or has already reviewed this upstream in blink), then I can push it for you.

**Comment by inexorabletash** [comment]
@smaug---- points out we should have tests for moving elements to other documents. Shouldn't block upstreaming these, but would be good to have.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by jgraham** [comment]
Can we rebase this branch on master so we stability checker results?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4384/)

**Comment by szager-chromium** [comment]
This tests were reviewed in the chromium repository by foolip@:

https://codereview.chromium.org/2560253004

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221495993)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e04b52bdee0c2cd9407ba027f7b221f9cc3e020c
Using browser at version BuildID 20170412100254; SourceStamp f40e24f40b4c4556944c762d4764eace261297f5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>22 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/client-rect.html">/intersection-observer/client-rect.html</a></summary>


|                                         Subtest                                         | Results |                                  Messages                                 |
|-----------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                         | OK      |                                                                           |
| `IntersectionObserverEntry.boundingClientRect should match target.boundingClientRect()` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/containing-block.html">/intersection-observer/containing-block.html</a></summary>


|                                                  Subtest                                                  | Results |                                  Messages                                 |
|-----------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                                           | OK      |                                                                           |
| `IntersectionObserver should only report intersections if root is a containing block ancestor of target.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/cross-origin-iframe.html">/intersection-observer/cross-origin-iframe.html</a></summary>


|                                         Subtest                                         | Results |                                  Messages                                 |
|-----------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                         | OK      |                                                                           |
| `Intersection observer test with no explicit root and target in a cross-origin iframe.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/disconnect.html">/intersection-observer/disconnect.html</a></summary>


|                                       Subtest                                       | Results |                                  Messages                                 |
|-------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                     | OK      |                                                                           |
| `IntersectionObserver should not deliver pending notifications after disconnect().` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/display-none.html">/intersection-observer/display-none.html</a></summary>


|                                                 Subtest                                                 | Results |                                  Messages                                 |
|---------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                                         | OK      |                                                                           |
| `IntersectionObserver should send a not-intersecting notification for a target that gets display:none.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/edge-inclusive-intersection.html">/intersection-observer/edge-inclusive-intersection.html</a></summary>


|                                          Subtest                                           | Results |                                  Messages                                 |
|--------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                            | OK      |                                                                           |
| `IntersectionObserver should detect and report edge-adjacent and zero-area intersections.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/iframe-no-root.html">/intersection-observer/iframe-no-root.html</a></summary>


|                              Subtest                               | Results |                                  Messages                                 |
|--------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                    | OK      |                                                                           |
| `Observer with the implicit root; target in a same-origin iframe.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/multiple-targets.html">/intersection-observer/multiple-targets.html</a></summary>


|                Subtest                | Results |                                  Messages                                 |
|---------------------------------------|---------|---------------------------------------------------------------------------|
|                                       | OK      |                                                                           |
| `One observer with multiple targets.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/multiple-thresholds.html">/intersection-observer/multiple-thresholds.html</a></summary>


|               Subtest                | Results |                                  Messages                                 |
|--------------------------------------|---------|---------------------------------------------------------------------------|
|                                      | OK      |                                                                           |
| `Observer with multiple thresholds.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-attributes.html">/intersection-observer/observer-attributes.html</a></summary>


|            Subtest            | Results |                Messages               |
|-------------------------------|---------|---------------------------------------|
|                               | OK      |                                       |
| `Observer attribute getters.` | FAIL    | `IntersectionObserver is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-exceptions.html">/intersection-observer/observer-exceptions.html</a></summary>


|                                    Subtest                                    | Results |                                                                                                                                        Messages                                                                                                                                        |
|-------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                               | OK      |                                                                                                                                                                                                                                                                                        |
| `IntersectionObserver constructor with { threshold: [1.1] }`                  | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {threshold: [1.1]})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" ("ReferenceError") expected object "RangeError" ("RangeError")`                                             |
| `IntersectionObserver constructor with { threshold: ["foo"] }`                | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {threshold: ["foo"]})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                             |
| `IntersectionObserver constructor witth { rootMargin: "1" }`                  | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {rootMargin: "1"})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" that is not a DOMException SYNTAX_ERR: property "code" is equal to undefined, expected 12`                   |
| `IntersectionObserver constructor with { rootMargin: "2em" }`                 | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {rootMargin: "2em"})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" that is not a DOMException SYNTAX_ERR: property "code" is equal to undefined, expected 12`                 |
| `IntersectionObserver constructor width { rootMargin: "auto" }`               | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {rootMargin: "auto"})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" that is not a DOMException SYNTAX_ERR: property "code" is equal to undefined, expected 12`                |
| `IntersectionObserver constructor with { rootMargin: "1px 1px 1px 1px 1px" }` | FAIL    | `assert_throws: function "function() {\n    new IntersectionObserver(e => {}, {rootMargin: "1px 1px 1px 1px 1px"})\n  }" threw object "ReferenceError: IntersectionObserver is not defined" that is not a DOMException SYNTAX_ERR: property "code" is equal to undefined, expected 12` |
| `IntersectionObserver.observe("foo")`                                         | FAIL    | `assert_throws: function "function() {\n    let observer = new IntersectionObserver(c => {}, {});\n    observer.observe("foo");\n  }" threw object "ReferenceError: IntersectionObserver is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")`                 |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-without-js-reference.html">/intersection-observer/observer-without-js-reference.html</a></summary>


|                                        Subtest                                        | Results |                                  Messages                                 |
|---------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                       | OK      |                                                                           |
| `IntersectionObserver that is unreachable in js should still generate notifications.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/remove-element.html">/intersection-observer/remove-element.html</a></summary>


|                                              Subtest                                              | Results |                                  Messages                                 |
|---------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                                   | OK      |                                                                           |
| `Verify that not-intersecting notifications are sent when a target is removed from the DOM tree.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/root-margin.html">/intersection-observer/root-margin.html</a></summary>


|       Subtest       | Results |                                  Messages                                 |
|---------------------|---------|---------------------------------------------------------------------------|
|                     | OK      |                                                                           |
| `Root margin tests` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-no-root.html">/intersection-observer/same-document-no-root.html</a></summary>


|                               Subtest                                | Results |                                  Messages                                 |
|----------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                      | OK      |                                                                           |
| `IntersectionObserver in a single document using the implicit root.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-root.html">/intersection-observer/same-document-root.html</a></summary>


|                             Subtest                             | Results |                                  Messages                                 |
|-----------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                 | OK      |                                                                           |
| `IntersectionObserver in a single document with explicit root.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-zero-size-target.html">/intersection-observer/same-document-zero-size-target.html</a></summary>


|             Subtest             | Results |                                  Messages                                 |
|---------------------------------|---------|---------------------------------------------------------------------------|
|                                 | OK      |                                                                           |
| `Observing a zero-area target.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/shadow-content.html">/intersection-observer/shadow-content.html</a></summary>


|                 Subtest                 | Results |                                  Messages                                 |
|-----------------------------------------|---------|---------------------------------------------------------------------------|
|                                         | OK      |                                                                           |
| `Observing a target inside shadow DOM.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/timestamp.html">/intersection-observer/timestamp.html</a></summary>


|                                          Subtest                                          | Results |                                  Messages                                 |
|-------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                           | OK      |                                                                           |
| `Check that timestamps correspond to the to execution context that created the observer.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/unclipped-root.html">/intersection-observer/unclipped-root.html</a></summary>


|                                           Subtest                                            | Results |                Messages               |
|----------------------------------------------------------------------------------------------|---------|---------------------------------------|
|                                                                                              | OK      |                                       |
| `Test that border bounding box is used to calculate intersection with a non-scrolling root.` | FAIL    | `IntersectionObserver is not defined` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/zero-area-element-hidden.html">/intersection-observer/zero-area-element-hidden.html</a></summary>


|                         Subtest                         | Results |                                  Messages                                 |
|---------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                         | OK      |                                                                           |
| `A zero-area hidden target should not be intersecting.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/zero-area-element-visible.html">/intersection-observer/zero-area-element-visible.html</a></summary>


|                                                 Subtest                                                 | Results |                                  Messages                                 |
|---------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------|
|                                                                                                         | OK      |                                                                           |
| `Ensure that a zero-area target intersecting root generates a notification with intersectionRatio == 1` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 921` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221495995)

# Chrome (unstable channel) #
Testing web-platform-tests at revision e04b52bdee0c2cd9407ba027f7b221f9cc3e020c
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
## Unstable results ##


|                        Test                       |        Subtest        |     Results     | Messages |
|---------------------------------------------------|-----------------------|-----------------|----------|
| `/intersection-observer/observer-attributes.html` | `observer.root`       | **PASS: 20/10** |          |
| `/intersection-observer/observer-attributes.html` | `observer.thresholds` | **PASS: 20/10** |          |
| `/intersection-observer/observer-attributes.html` | `observer.rootMargin` | **PASS: 20/10** |          |

## All results ##
<details>
<summary>22 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/client-rect.html">/intersection-observer/client-rect.html</a></summary>


|                                         Subtest                                         | Results |                                  Messages                                  |
|-----------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                         | OK      |                                                                            |
| `IntersectionObserverEntry.boundingClientRect should match target.boundingClientRect()` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/containing-block.html">/intersection-observer/containing-block.html</a></summary>


|                                                  Subtest                                                  | Results |                                  Messages                                  |
|-----------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                                           | OK      |                                                                            |
| `IntersectionObserver should only report intersections if root is a containing block ancestor of target.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/cross-origin-iframe.html">/intersection-observer/cross-origin-iframe.html</a></summary>


|                                         Subtest                                         | Results |                                  Messages                                  |
|-----------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                         | OK      |                                                                            |
| `Intersection observer test with no explicit root and target in a cross-origin iframe.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/disconnect.html">/intersection-observer/disconnect.html</a></summary>


|                                       Subtest                                       | Results |                                  Messages                                  |
|-------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                     | OK      |                                                                            |
| `IntersectionObserver should not deliver pending notifications after disconnect().` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/display-none.html">/intersection-observer/display-none.html</a></summary>


|                                                 Subtest                                                 | Results |                                  Messages                                  |
|---------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                                         | OK      |                                                                            |
| `IntersectionObserver should send a not-intersecting notification for a target that gets display:none.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/edge-inclusive-intersection.html">/intersection-observer/edge-inclusive-intersection.html</a></summary>


|                                          Subtest                                           | Results |                                  Messages                                  |
|--------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                            | OK      |                                                                            |
| `IntersectionObserver should detect and report edge-adjacent and zero-area intersections.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/iframe-no-root.html">/intersection-observer/iframe-no-root.html</a></summary>


|                              Subtest                               | Results |                                  Messages                                  |
|--------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                    | OK      |                                                                            |
| `Observer with the implicit root; target in a same-origin iframe.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/multiple-targets.html">/intersection-observer/multiple-targets.html</a></summary>


|                Subtest                | Results |                                  Messages                                  |
|---------------------------------------|---------|----------------------------------------------------------------------------|
|                                       | OK      |                                                                            |
| `One observer with multiple targets.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/multiple-thresholds.html">/intersection-observer/multiple-thresholds.html</a></summary>


|               Subtest                | Results |                                  Messages                                  |
|--------------------------------------|---------|----------------------------------------------------------------------------|
|                                      | OK      |                                                                            |
| `Observer with multiple thresholds.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-attributes.html">/intersection-observer/observer-attributes.html</a></summary>


|            Subtest            |     Results     | Messages |
|-------------------------------|-----------------|----------|
|                               | ERROR           |          |
| `Observer attribute getters.` | PASS            |          |
| `observer.root`               | **PASS: 20/10** |          |
| `observer.thresholds`         | **PASS: 20/10** |          |
| `observer.rootMargin`         | **PASS: 20/10** |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-exceptions.html">/intersection-observer/observer-exceptions.html</a></summary>


|                                    Subtest                                    | Results | Messages |
|-------------------------------------------------------------------------------|---------|----------|
|                                                                               | OK      |          |
| `IntersectionObserver constructor with { threshold: [1.1] }`                  | PASS    |          |
| `IntersectionObserver constructor with { threshold: ["foo"] }`                | PASS    |          |
| `IntersectionObserver constructor witth { rootMargin: "1" }`                  | PASS    |          |
| `IntersectionObserver constructor with { rootMargin: "2em" }`                 | PASS    |          |
| `IntersectionObserver constructor width { rootMargin: "auto" }`               | PASS    |          |
| `IntersectionObserver constructor with { rootMargin: "1px 1px 1px 1px 1px" }` | PASS    |          |
| `IntersectionObserver.observe("foo")`                                         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/observer-without-js-reference.html">/intersection-observer/observer-without-js-reference.html</a></summary>


|                                        Subtest                                        | Results |                                  Messages                                  |
|---------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                       | OK      |                                                                            |
| `IntersectionObserver that is unreachable in js should still generate notifications.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/remove-element.html">/intersection-observer/remove-element.html</a></summary>


|                                              Subtest                                              | Results |                                  Messages                                  |
|---------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                                   | OK      |                                                                            |
| `Verify that not-intersecting notifications are sent when a target is removed from the DOM tree.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/root-margin.html">/intersection-observer/root-margin.html</a></summary>


|       Subtest       | Results |                                  Messages                                  |
|---------------------|---------|----------------------------------------------------------------------------|
|                     | OK      |                                                                            |
| `Root margin tests` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-no-root.html">/intersection-observer/same-document-no-root.html</a></summary>


|                               Subtest                                | Results |                                  Messages                                  |
|----------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                      | OK      |                                                                            |
| `IntersectionObserver in a single document using the implicit root.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-root.html">/intersection-observer/same-document-root.html</a></summary>


|                             Subtest                             | Results |                                  Messages                                  |
|-----------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                 | OK      |                                                                            |
| `IntersectionObserver in a single document with explicit root.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/same-document-zero-size-target.html">/intersection-observer/same-document-zero-size-target.html</a></summary>


|             Subtest             | Results |                                  Messages                                  |
|---------------------------------|---------|----------------------------------------------------------------------------|
|                                 | OK      |                                                                            |
| `Observing a zero-area target.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/shadow-content.html">/intersection-observer/shadow-content.html</a></summary>


|                 Subtest                 | Results |                                  Messages                                  |
|-----------------------------------------|---------|----------------------------------------------------------------------------|
|                                         | OK      |                                                                            |
| `Observing a target inside shadow DOM.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/timestamp.html">/intersection-observer/timestamp.html</a></summary>


|                                          Subtest                                          | Results |                                  Messages                                  |
|-------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                           | OK      |                                                                            |
| `Check that timestamps correspond to the to execution context that created the observer.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/unclipped-root.html">/intersection-observer/unclipped-root.html</a></summary>


|                                           Subtest                                            | Results | Messages |
|----------------------------------------------------------------------------------------------|---------|----------|
|                                                                                              | OK      |          |
| `Test that border bounding box is used to calculate intersection with a non-scrolling root.` | PASS    |          |
| `First rAF.`                                                                                 | PASS    |          |
| `target.style.transform = 'translateY(195px)'`                                               | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/zero-area-element-hidden.html">/intersection-observer/zero-area-element-hidden.html</a></summary>


|                         Subtest                         | Results |                                  Messages                                  |
|---------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                         | OK      |                                                                            |
| `A zero-area hidden target should not be intersecting.` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4384/intersection-observer/zero-area-element-visible.html">/intersection-observer/zero-area-element-visible.html</a></summary>


|                                                 Subtest                                                 | Results |                                  Messages                                  |
|---------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------|
|                                                                                                         | OK      |                                                                            |
| `Ensure that a zero-area target intersecting root generates a notification with intersectionRatio == 1` | FAIL    | `assert_equals: Window must be 800 pixels wide. expected 800 but got 1004` |

</details>
</details>

**Comment by smaug----** [comment]
@tobytailor could you take a look at the Firefox results. I assume some of the tests are buggy and Firefox implementation has some bugs too.

**Comment by szager-chromium** [comment]
@smaug---- It seems like most or all of the failures stem from the fact that the tests require an 800x600 viewport.  That's always the case when running chromium tests, so that assumption is hard-coded into the tests.

Is there a way to force that requirement when running them against firefox?

**Comment by smaug----** [comment]
No, or even if there was that is a bug in the tests and should be fixed there.

**Comment by smaug----** [comment]
But @jgraham could say more about the setup in Firefox.

**Comment by tobytailor** [comment]
Be aware that the API is still disabled by default as of now. It needs to be enabled via dom.IntersectionObserver.enabled flag in about:config. That would explain all the IntersectionObserver not being defined errors.

**Comment by tobytailor** [comment]
I removed requirements of a 800x600 viewport and got all tests to work in Chrome(Canary) and Firefox Nightly (with additional patches tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1358666). See https://github.com/szager-chromium/web-platform-tests/pull/1

**Comment by nolanlawson** [comment]
Can this PR be closed because apparently the tests have already made it into master? https://github.com/w3c/web-platform-tests/pull/6216#issuecomment-311743305

**Pull request closed without merging**
