### PR TITLE
Fix some pretty inconsequential typos

### PR DESCRIPTION
**Pull request by dumbmatter**
`indexedDB.delete` should be `indexedDB.deleteDatabase`

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5694)

### CODE REVIEW

**Comment by dumbmatter** [comment]
Also, is it actually desired behavior to ignore errors that happen in cleanup functions?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225867311)

# Lint #

Passed

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225867313)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 8e6ff73e9e72bf035612b3b7adbdf27083b60284
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5694/IndexedDB/idbcursor_iterating.htm">/IndexedDB/idbcursor_iterating.htm</a></summary>


|                                    Subtest                                    | Results | Messages |
|-------------------------------------------------------------------------------|---------|----------|
|                                                                               | OK      |          |
| `IDBCursor.continue() - objectstore - delete next element, and iterate to it` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5694/IndexedDB/idbcursor_iterating_objectstore.htm">/IndexedDB/idbcursor_iterating_objectstore.htm</a></summary>


|                                    Subtest                                    | Results | Messages |
|-------------------------------------------------------------------------------|---------|----------|
|                                                                               | OK      |          |
| `IDBCursor.continue() - objectstore - delete next element, and iterate to it` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5694/IndexedDB/idbcursor_iterating_objectstore2.htm">/IndexedDB/idbcursor_iterating_objectstore2.htm</a></summary>


|                                  Subtest                                   | Results | Messages |
|----------------------------------------------------------------------------|---------|----------|
|                                                                            | OK      |          |
| `IDBCursor.continue() - objectstore - add next element, and iterate to it` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225867319)

# Chrome (unstable channel) #

**Comment by foolip** [comment]
> Also, is it actually desired behavior to ignore errors that happen in cleanup functions?

@jugglinmike, this seems related to something we talked about with async cleanup. I thought it was treated as a harness error already?

**Review by foolip — APPROVED** [review]

**Comment by jugglinmike** [comment]
@foolip The behavior is currently undocumented and inconsistent. My work with
asynchronous cleanup has exposed a number of bugs, but fixes (and documentation)
are gated on the automated testing infrastructure. That's currently under review
here: https://github.com/w3c/web-platform-tests/pull/5627 . Hopefully we'll have
this all cleared up soon.

**Comment by inexorabletash** [comment]
Ugh, thanks for catching this and the fix.

**Pull request merged**
