### PR TITLE
IndexedDB: Add coverage for exceptions in EventListener::handleEvent

### PR DESCRIPTION
**Pull request by shvaikalesh**
WebKit issue: [Non-callable "handleEvent" property is silently ignored](https://bugs.webkit.org/show_bug.cgi?id=200066).

Follow-up of #15122.

### CODE REVIEW

**Review by inexorabletash — APPROVED** [review]
lgtm!

**Comment by shvaikalesh** [comment]
@annevk could you please give this PR a second look? Thank you in advance.

**Review by annevk — APPROVED** [review]
This seems fine, though it's not immediately clear to me why all the `AbortErrror` asserts are not inside `fire_error_event_test`. Seems like a lot of needless duplication?

I see one or two cases with additional asserts, but in those cases we could also explicitly override. Anyway, not blocking this on that.

**Comment by shvaikalesh** [comment]
Good catch, thank you @annevk.

I've moved `AbortError` asserts inside `fire_*_event_test` helpers. It worked out especially well for [`"upgradeneeded"` event](https://github.com/web-platform-tests/wpt/pull/18554/commits/7aab2d6573c06d91c3d71686de50b9e407215401).

Is there anything I could do to help get this merged? As soon as the tests are in, I would be able to add an exception for [non-callable `handleEvent` in WebKit](https://bugs.webkit.org/show_bug.cgi?id=200066).

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Using `addEventListener()` is even nicer, cool! I'll merge this.

**Pull request merged**
