### PR TITLE
Replace some assert_throws("Something", stuff) calls with assert_throws_dom

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This a piece-by-piece landing of #21350 due to the size of the original PR. Please excuse the email spam when wpt-pr-bot cc's you to this PR.

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Chrome shows one diff in [offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html](https://wpt.fyi/results/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html?diff&filter=ADC&run_id=414880009&run_id=414890006), but the two tests that newly fail are not ones touched by this PR. I suspect flake, and indeed looking at the history view on https://wpt.fyi/results/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html?label=master&label=experimental&aligned that appears to be the case. So let's ignore those.

Similarly, `infrastructure/ tests` failed due to a network issue on the bot, so irrelevant.

`resources/ tests` looks like a real failure; looks like there are expected files that have to be updated for the new world.

`update-built` also fails, so we need to fix the generated tests similarly to https://github.com/web-platform-tests/wpt/pull/21354#issuecomment-577400156

**Comment by stephenmcgruer** [comment]
Ok, uploaded a new version with the 2dcontext generator updated. I also rolled back the change in `resources/test/tests/functional/api-tests-1.html`, as I believe that is causing the `resources/ tests` to fail. Let's revisit it later. (cc @bzbarsky )

**Comment by bzbarsky** [comment]
Oh, yes, I expect this test:
```
        assert_throws("TEST_ERR", function() {throw e});
```
behaves differently if changed to `assert_throws_dom`.  I agree with leaving this out for now; we can then fix up `resources/` bits later.  There's a bunch in there that needs some manual looking at.

**Comment by stephenmcgruer** [comment]
Ok, results look good this time (modulo expected flake)

**Pull request merged**
