### PR TITLE
Update the shape-detection-api IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The Spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-05 21:59:04
Finished: 2018-03-05 22:04:18


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25292)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349439298)

**Comment by foolip** [comment]
@yellowdoge, are you happy to be the suggested reviewer for this directory? Also, should it be "shape-detection-api" or just "shape-detection"? Which is most likely to become the /TR/ name is better, and then it'd be ideal to rename the current spec repo as well.

**Comment by yellowdoge** [comment]
@foolip, 👍 to having my handle as reviewer. Re. naming, all code in Chromium has `shape-detection` (no `_api`), but there are links and whatnot in the code pointing to the `_api` URLs. If we want to change it, it needs to happen soon. WDYT?

**Review by yell0wd0g — APPROVED** [review]
👍

**Comment by foolip** [comment]
When you rename a GitHub repo, github.com URLs will redirect, but it seems like github.io URLs do not. So if you would like to rename the spec repo, then doing so sooner rather than later is good.

@yellowdoge, can you make a decision on that, so that we make the directory name here match?

**Comment by lukebjerring** [comment]
Should I merge this as-is and we follow up with a rename if needed?

**Comment by foolip** [comment]
Sure, let's bet on the shorter name being the final one.

**Pull request merged**
