### PR TITLE
Test <video autoplay> with various broken <track src> URLs

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This created for discussion for a bug report I got. I'm not sure this is per spec yet.

**Comment by foolip** [comment]
Can be tested at http://w3c-test.org/submissions/9495/html/semantics/embedded-content/media-elements/autoplay-with-broken-track.html.

**Comment by foolip** [comment]
`<video autoplay> with <track src="" default=""> child` is the case I really wanted to test here, and I see it passing in Edge and failing everywhere else. And yet I can't see why it should fail, if the empty string resolves to the URL of the test page, then it should be just like the 404 case. So there must be checks for the empty string somewhere in the implementation where it doesn't belong.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/24261)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/340900926)

**Review by fsoder — APPROVED** [review]
The case you're interested in should be covered by [1], which will yield an empty string in step 7 of [2], and then fail to load in step 10 (paragraph after the note.)

[1] https://html.spec.whatwg.org/multipage/media.html#attr-track-src
[2] https://html.spec.whatwg.org/multipage/media.html#start-the-track-processing-model

**Comment by foolip** [comment]
Thanks @fsoder!

**Pull request merged**
