### PR TITLE
Add tests for CSS Color 5 color-mix()

### PR DESCRIPTION
**Pull request by weinig**
Tests for parsing and serializing color-mix().

### CODE REVIEW

**Comment by nt1m** [comment]
@emilio might be a good reviewer here since he worked on color-mix in Gecko.

**Comment by nt1m** [comment]
This is the test Gecko contributed: https://github.com/web-platform-tests/wpt/tree/master/css/css-color/color-mix-basic-001.tentative.html

**Comment by weinig** [comment]
Because I forgot to mention it in the description, this is a wpt-ified version of the color-mix() tests in WebKit's layout tests that I wrote, https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-color-mix.html.

**Review by foolip — APPROVED** [review]

**Comment by svgeesus** [comment]
@nt1m 

> This is the test Gecko contributed: https://github.com/web-platform-tests/wpt/tree/master/css/css-color/color-mix-basic-001.tentative.html

That test should no longer be marked tentative. It references  https://github.com/w3c/csswg-drafts/issues/6066 which is closed, and the test case is conformant to the way the issue was resolved.

**Comment by nt1m** [comment]
@svgeesus https://github.com/web-platform-tests/wpt/pull/32064

**Pull request merged**
