### PR TITLE
WebIDL: [PutForwards] should not throw if [[Set]] has failed

### PR DESCRIPTION
**Pull request by shvaikalesh**
Per https://github.com/heycam/webidl/pull/406.

//cc @TimothyGu

### CODE REVIEW

**Review by yuki3 — APPROVED** [review]
LGTM.

**Review by TimothyGu — CHANGES_REQUESTED** [review]
Hmm, doesn't look like Chrome or Firefox implements Throw = true. Maybe the better fix here would be to change the spec to say 

> Perform ? Set(_Q_, _forwardId_, _V_, **false**).

instead.

**Comment by TimothyGu** [comment]
See heycam/webidl#832.

**Comment by TimothyGu** [comment]
Modified to account for heycam/webidl#832.

**Review by TimothyGu — APPROVED** [review]

**Pull request merged**
