### PR TITLE
a change to include a test for final readystatechange (readyState === 3)

### PR DESCRIPTION
**Pull request by Yaffle**
https://github.com/whatwg/xhr/issues/161

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19247)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/284311297)

**Comment by wisniewskit** [comment]
Hmm. Firefox nightly and stable seem to pass this revised version of the test on my end.

**Comment by Yaffle** [comment]
@wisniewskit , Oh! Sorry.
It seems, I misunderstood how trickle.py works.
The final extra byte is needed to reproduce it in Firefox.
And also I can reproduce this in Chrome if I use delay < 50 ms...
So, seems this is not a bug.
`onreadystatechange` with `readyState === 3`only cannot be used insteadof "progress"...

**Comment by wisniewskit** [comment]
Oh, no need for apologies; thanks for confirming!

**Pull request closed without merging**
