### PR TITLE
[wptrunner] Remove obsolete testharness `supports_eager_pageload=False` workaround

### PR DESCRIPTION
**Pull request by jonathan-j-lee**
`chromedriver` support for eager pageloads shipped in M77: https://chromedriver.storage.googleapis.com/77.0.3865.10/notes.txt

This change removes a workaround in wptrunner's WebDriver testharness
executor for Chromium-based browser (`chrome` and `edgechromium`) that
formerly lacked `pageLoadStrategy: eager` support.

See Also: crrev.com/c/1241213/5/chrome/test/chromedriver/capabilities.cc#202

### CODE REVIEW

**Comment by WeizhongX** [comment]
What is the benefit if we use eager pageload strategy?

**Comment by jonathan-j-lee** [comment]
This is just a small cleanup that obviates the need for this nonstandard workaround:

https://github.com/web-platform-tests/wpt/blob/c759244ce57746d5a8ddbff40835a6bb91ec077b/tools/wptrunner/wptrunner/executors/executorwebdriver.py#L561-L582

This change leaves `edgechromium` as the only browser with `supports_eager_pageload=False`, but I suspect they copied `chrome`, so they also don't need this.

**Comment by WeizhongX** [comment]
> 

So if we also remove `supports_eager_pageload=False` for edgechromium, we can remove `wait_for_load `? Does this speed up the testing?

**Comment by jonathan-j-lee** [comment]
> So if we also remove supports_eager_pageload=False for edgechromium, we can remove wait_for_load?

I think so. @jgraham added that code 5 years ago in https://github.com/web-platform-tests/wpt/commit/e4ba26cf0324af4ffd46607b296f5362243728a3. The comment mentions that this was to support Chrome's noncompliant behavior.

> Does this speed up the testing?

No. This was just something I found along the way. I'm still investigating.

**Comment by WeizhongX** [comment]
> > So if we also remove supports_eager_pageload=False for edgechromium, we can remove wait_for_load?
> 
> I think so.
Should we remove that and ask jgraham@ to review?

**Comment by jgraham** [comment]
I'm happy to remove that method if it's no longer needed. It would be surprising for it to make a _huge_ perf difference, you save one command, but the injected script is just waiting for a `readystatechange` event, which is exactly the same behaviour as `pageLoadStrategy=eager`.

**Review by WeizhongX — APPROVED** [review]

**Comment by jonathan-j-lee** [comment]
@jgraham Would you mind taking a look at the completed cleanup as well? I didn't test this change against `edgechromium` because I don't know how to get the browser, but I doubt this will break it.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
