### PR TITLE
innerText setter should not result in empty text nodes

### PR DESCRIPTION
**Pull request by zcorpan**
Ref. https://github.com/whatwg/html/issues/1679

### CODE REVIEW

**Comment by zcorpan** [comment]
@cdumez r?

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Although, maybe rebase and let me have another look?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/3492/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210940063)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 0dd98b13bc6e711685bf5e7ffd175a1676dec07b
Using browser at version BuildID 20170313110417; SourceStamp f9362554866b327700c7f9b18050d7b7eb3d2b23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/3492/innerText/setter.html">/innerText/setter.html</a></summary>


|                                   Subtest                                   | Results | Messages |
|-----------------------------------------------------------------------------|---------|----------|
|                                                                             | OK      |          |
| `Simplest possible test`                                                    | PASS    |          |
| `Newlines convert to <br> in non-white-space:pre elements`                  | PASS    |          |
| `Newlines convert to <br> in <pre> element`                                 | PASS    |          |
| `Newlines convert to <br> in white-space:pre element`                       | PASS    |          |
| `CRs convert to <br> in non-white-space:pre elements`                       | PASS    |          |
| `CRs convert to <br> in <pre> element`                                      | PASS    |          |
| `Newline/CR pair converts to <br> in non-white-space:pre element`           | PASS    |          |
| `Newline/newline pair converts to two <br>s in non-white-space:pre element` | PASS    |          |
| `CR/CR pair converts to two <br>s in non-white-space:pre element`           | PASS    |          |
| `CRs convert to <br> in white-space:pre element`                            | PASS    |          |
| `< preserved`                                                               | PASS    |          |
| `> preserved`                                                               | PASS    |          |
| `& preserved`                                                               | PASS    |          |
| `" preserved`                                                               | PASS    |          |
| `' preserved`                                                               | PASS    |          |
| `innerText not supported on SVG elements`                                   | PASS    |          |
| `innerText not supported on MathML elements`                                | PASS    |          |
| `Null characters preserved`                                                 | PASS    |          |
| `Tabs preserved`                                                            | PASS    |          |
| `Leading whitespace preserved`                                              | PASS    |          |
| `Trailing whitespace preserved`                                             | PASS    |          |
| `Whitespace not compressed`                                                 | PASS    |          |
| `Existing text deleted`                                                     | PASS    |          |
| `Existing <br> deleted`                                                     | PASS    |          |
| `Assigning the empty string`                                                | PASS    |          |
| `Assigning null`                                                            | PASS    |          |
| `Assigning undefined`                                                       | PASS    |          |
| `Start with CR`                                                             | PASS    |          |
| `Start with LF`                                                             | PASS    |          |
| `Start with CRLF`                                                           | PASS    |          |
| `End with CR`                                                               | PASS    |          |
| `End with LF`                                                               | PASS    |          |
| `End with CRLF`                                                             | PASS    |          |
| `innerText on <area> element`                                               | PASS    |          |
| `innerText on <base> element`                                               | PASS    |          |
| `innerText on <basefont> element`                                           | PASS    |          |
| `innerText on <bgsound> element`                                            | PASS    |          |
| `innerText on <br> element`                                                 | PASS    |          |
| `innerText on <col> element`                                                | PASS    |          |
| `innerText on <embed> element`                                              | PASS    |          |
| `innerText on <frame> element`                                              | PASS    |          |
| `innerText on <hr> element`                                                 | PASS    |          |
| `innerText on <image> element`                                              | PASS    |          |
| `innerText on  element`                                                | PASS    |          |
| `innerText on <input> element`                                              | PASS    |          |
| `innerText on <keygen> element`                                             | PASS    |          |
| `innerText on <link> element`                                               | PASS    |          |
| `innerText on <menuitem> element`                                           | PASS    |          |
| `innerText on <meta> element`                                               | PASS    |          |
| `innerText on <param> element`                                              | PASS    |          |
| `innerText on <source> element`                                             | PASS    |          |
| `innerText on <track> element`                                              | PASS    |          |
| `innerText on <wbr> element`                                                | PASS    |          |
| `innerText on <colgroup> element`                                           | PASS    |          |
| `innerText on <frameset> element`                                           | PASS    |          |
| `innerText on <head> element`                                               | PASS    |          |
| `innerText on <html> element`                                               | PASS    |          |
| `innerText on <table> element`                                              | PASS    |          |
| `innerText on <tbody> element`                                              | PASS    |          |
| `innerText on <tfoot> element`                                              | PASS    |          |
| `innerText on <thead> element`                                              | PASS    |          |
| `innerText on <tr> element`                                                 | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210940065)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 0dd98b13bc6e711685bf5e7ffd175a1676dec07b
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/3492/innerText/setter.html">/innerText/setter.html</a></summary>


|                                   Subtest                                   | Results |                                           Messages                                          |
|-----------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------|
|                                                                             | OK      |                                                                                             |
| `Simplest possible test`                                                    | PASS    |                                                                                             |
| `Newlines convert to <br> in non-white-space:pre elements`                  | PASS    |                                                                                             |
| `Newlines convert to <br> in <pre> element`                                 | PASS    |                                                                                             |
| `Newlines convert to <br> in white-space:pre element`                       | PASS    |                                                                                             |
| `CRs convert to <br> in non-white-space:pre elements`                       | PASS    |                                                                                             |
| `CRs convert to <br> in <pre> element`                                      | PASS    |                                                                                             |
| `Newline/CR pair converts to <br> in non-white-space:pre element`           | PASS    |                                                                                             |
| `Newline/newline pair converts to two <br>s in non-white-space:pre element` | FAIL    | `assert_not_equals: Should not have empty text nodes got disallowed value ""`               |
| `CR/CR pair converts to two <br>s in non-white-space:pre element`           | FAIL    | `assert_not_equals: Should not have empty text nodes got disallowed value ""`               |
| `CRs convert to <br> in white-space:pre element`                            | PASS    |                                                                                             |
| `< preserved`                                                               | PASS    |                                                                                             |
| `> preserved`                                                               | PASS    |                                                                                             |
| `& preserved`                                                               | PASS    |                                                                                             |
| `" preserved`                                                               | PASS    |                                                                                             |
| `' preserved`                                                               | PASS    |                                                                                             |
| `innerText not supported on SVG elements`                                   | PASS    |                                                                                             |
| `innerText not supported on MathML elements`                                | PASS    |                                                                                             |
| `Null characters preserved`                                                 | PASS    |                                                                                             |
| `Tabs preserved`                                                            | PASS    |                                                                                             |
| `Leading whitespace preserved`                                              | PASS    |                                                                                             |
| `Trailing whitespace preserved`                                             | PASS    |                                                                                             |
| `Whitespace not compressed`                                                 | PASS    |                                                                                             |
| `Existing text deleted`                                                     | FAIL    | `assert_not_equals: Child should be a *new* text node got disallowed value Text node "abc"` |
| `Existing <br> deleted`                                                     | PASS    |                                                                                             |
| `Assigning the empty string`                                                | PASS    |                                                                                             |
| `Assigning null`                                                            | PASS    |                                                                                             |
| `Assigning undefined`                                                       | PASS    |                                                                                             |
| `Start with CR`                                                             | FAIL    | `assert_not_equals: Should not have empty text nodes got disallowed value ""`               |
| `Start with LF`                                                             | FAIL    | `assert_not_equals: Should not have empty text nodes got disallowed value ""`               |
| `Start with CRLF`                                                           | FAIL    | `assert_not_equals: Should not have empty text nodes got disallowed value ""`               |
| `End with CR`                                                               | PASS    |                                                                                             |
| `End with LF`                                                               | PASS    |                                                                                             |
| `End with CRLF`                                                             | PASS    |                                                                                             |
| `innerText on <area> element`                                               | PASS    |                                                                                             |
| `innerText on <base> element`                                               | PASS    |                                                                                             |
| `innerText on <basefont> element`                                           | PASS    |                                                                                             |
| `innerText on <bgsound> element`                                            | PASS    |                                                                                             |
| `innerText on <br> element`                                                 | PASS    |                                                                                             |
| `innerText on <col> element`                                                | PASS    |                                                                                             |
| `innerText on <embed> element`                                              | PASS    |                                                                                             |
| `innerText on <frame> element`                                              | PASS    |                                                                                             |
| `innerText on <hr> element`                                                 | PASS    |                                                                                             |
| `innerText on <image> element`                                              | PASS    |                                                                                             |
| `innerText on  element`                                                | PASS    |                                                                                             |
| `innerText on <input> element`                                              | PASS    |                                                                                             |
| `innerText on <keygen> element`                                             | PASS    |                                                                                             |
| `innerText on <link> element`                                               | PASS    |                                                                                             |
| `innerText on <menuitem> element`                                           | PASS    |                                                                                             |
| `innerText on <meta> element`                                               | PASS    |                                                                                             |
| `innerText on <param> element`                                              | PASS    |                                                                                             |
| `innerText on <source> element`                                             | PASS    |                                                                                             |
| `innerText on <track> element`                                              | PASS    |                                                                                             |
| `innerText on <wbr> element`                                                | PASS    |                                                                                             |
| `innerText on <colgroup> element`                                           | PASS    |                                                                                             |
| `innerText on <frameset> element`                                           | PASS    |                                                                                             |
| `innerText on <head> element`                                               | PASS    |                                                                                             |
| `innerText on <html> element`                                               | PASS    |                                                                                             |
| `innerText on <table> element`                                              | PASS    |                                                                                             |
| `innerText on <tbody> element`                                              | PASS    |                                                                                             |
| `innerText on <tfoot> element`                                              | PASS    |                                                                                             |
| `innerText on <thead> element`                                              | PASS    |                                                                                             |
| `innerText on <tr> element`                                                 | PASS    |                                                                                             |

</details>
</details>

**Comment by annevk** [comment]
It seems you should maybe file an issue against Chrome, but I suppose you'll track that as part of the HTML issue.

**Comment by zcorpan** [comment]
Commented in https://bugs.chromium.org/p/chromium/issues/detail?id=573309
Filed a new issue for WebKit https://bugs.webkit.org/show_bug.cgi?id=169600

**Pull request merged**
