### PR TITLE
Re-apply submodule updates

### PR DESCRIPTION
**Pull request by jugglinmike**
In 7649b7796e4f75085d2910dfb9ce38fd9b76f7bf, the `resources` and `tools`
submodules were unintentionally reverted to a previous state. Re-apply
the updates.

Because rolling back submodules is a fairly uncommon operation, and because [the review for the patch that did so](https://github.com/w3c/web-platform-tests/pull/5184) includes no mention of this, I expect this was a mistake. @mikewest: can you please confirm?

@jgraham The most obvious indication is that [log output is currently being duplicated in recent pull requests](https://github.com/w3c/web-platform-tests/pull/5196) because [this commit](https://github.com/w3c/wpt-tools/commit/1cd1a1aea918b48a1b3540272073004a80c98247) is no longer applied. There are likely more significant problems, though, e.g. changes to `wdclient` and `testharness.js` (including the change that disallows duplicate test names).

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5197/)

**Comment by annevk** [comment]
Note that I mentioned this in `#testing` already but I guess it gets lost there somehow. I guess I'll file issues from now on.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213891030)

# Firefox (nightly channel) #
Testing web-platform-tests at revision e1804af3fc8d425bbdf54ab533606444201818c5
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213891031)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 2d1230ead3f988ba90dd22358e085cbb260c5dbf
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5197/fetch/api/cors/cors-preflight-worker.html">/fetch/api/cors/cors-preflight-worker.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    | `{}`     |
| `CORS [DELETE], server refuses`                       | PASS    | `{}`     |
| `CORS [PUT], server allows`                           | PASS    | `{}`     |
| `CORS [PUT], server refuses`                          | PASS    | `{}`     |
| `CORS [PATCH], server allows`                         | PASS    | `{}`     |
| `CORS [PATCH], server refuses`                        | PASS    | `{}`     |
| `CORS [NEW], server allows`                           | PASS    | `{}`     |
| `CORS [NEW], server refuses`                          | PASS    | `{}`     |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    | `{}`     |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    | `{}`     |
| `CORS [GET] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [GET] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [several headers], server allows`         | PASS    | `{}`     |
| `CORS [PUT] [several headers], server refuses`        | PASS    | `{}`     |
| `CORS [PUT] [only safe headers], server allows`       | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5197/fetch/api/cors/cors-preflight.html">/fetch/api/cors/cors-preflight.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `CORS [DELETE], server allows`                        | PASS    |          |
| `CORS [DELETE], server refuses`                       | PASS    |          |
| `CORS [PUT], server allows`                           | PASS    |          |
| `CORS [PUT], server refuses`                          | PASS    |          |
| `CORS [PATCH], server allows`                         | PASS    |          |
| `CORS [PATCH], server refuses`                        | PASS    |          |
| `CORS [NEW], server allows`                           | PASS    |          |
| `CORS [NEW], server refuses`                          | PASS    |          |
| `CORS [GET] [x-test-header: allowed], server allows`  | PASS    |          |
| `CORS [GET] [x-test-header: refused], server refuses` | PASS    |          |
| `CORS [GET] [several headers], server allows`         | PASS    |          |
| `CORS [GET] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [several headers], server allows`         | PASS    |          |
| `CORS [PUT] [several headers], server refuses`        | PASS    |          |
| `CORS [PUT] [only safe headers], server allows`       | PASS    |          |

</details>
</details>

**Comment by jugglinmike** [comment]
@annevk Ah, I hadn't logged in to IRC yet. No harm, no foul

**Comment by mikewest** [comment]
This patch LGTM, sorry for the breakage, it was unintentional.

@jeffcarp, @foolip: It's probably a good idea to make sure the chromium export bot never touches submodules. :)

**Comment by jgraham** [comment]
@mikewest np, once we monorepo all the things this problem will go away. Soon now!

**Pull request merged**
