### PR TITLE
Remove redundant test

### PR DESCRIPTION
**Pull request by jugglinmike**
Since the application of [1], the `idlharness.js` library asserts
prototype immutability of all global platform objects and interface
prototype objects. Because an `idlharness.js` test dedicated to the
`Window` constructor (and global instance) was previously written [2],
this extension obviated the need for a test explicitly dedicated to
prototype immutability of this object.

[1] 13b0e2d8d609603b0230ba950404ea21c149f0db
[2] See `html/dom/interfaces.html`

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/250025894)

# Firefox (nightly) #
Testing web-platform-tests at revision 4ae80f62a24f5c3fd517749f2bf315d5bf8e90e6
Using browser at version BuildID 20170704100254; SourceStamp fef489e8c2a193dde885adc48deb74cc883a5881
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/250025895)

# Sauce (safari) #
Testing web-platform-tests at revision 4ae80f62a24f5c3fd517749f2bf315d5bf8e90e6
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/250025901)

# Chrome (unstable) #
Testing web-platform-tests at revision 4ae80f62a24f5c3fd517749f2bf315d5bf8e90e6

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/250025902)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 4ae80f62a24f5c3fd517749f2bf315d5bf8e90e6

**Comment by domenic** [comment]
These are not redundant and should be preserved. The linked commit does not test the cases tested here.

**Comment by ayg** [comment]
The linked commit tests only setting to Object.create(null), not window or Object.create(window) as in this file.  I would expect this to make no real difference, but perhaps idlharness should be updated to test these cases just so we don't lose test coverage.

**Comment by Ms2ger** [comment]
Let's just keep the test.

**Pull request closed without merging**
