### PR TITLE
Heavily rewrite the documentation

### PR DESCRIPTION
**Pull request by gsnedders**
This moves it over to being a Jekyll website in and of itself instead of
relying on testthewebforward.org; for technical reasons[0] testharness.js
documentation will continue to live on TTWF.org for now and is included here
via an iframe.

Almost all the content on the site has been heavily edited and rewritten in an
attempt to ensure that it is up-to-date and more cohesive and easily navigable
than before.

[0]: https://github.com/jekyll/jekyll/issues/5728

---

For those wanting to review this, please see https://gsnedders.github.io/wpt-docs/, though it is known the testharness.js API and idlharness.js pages are broken on that copy due to mixed-content errors; this is a limitation of GitHub Pages and will be solved once both are on custom domains and hence both are only available on HTTP (sadly).

### CODE REVIEW

**Comment by gsnedders** [comment]
Per agreement with @jgraham and @Ms2ger, this will get merged after CI has run.

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision a12afe8bba4bf619f2e8393910b5007505d2dcbe
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision a12afe8bba4bf619f2e8393910b5007505d2dcbe
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
No tests run.

**Comment by gsnedders** [comment]
Fixes #4165.

**Pull request merged**
