### PR TITLE
Use double as attribute type and introduce 'hasReading' attribute

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@alexshalamov, @pozdnyakov, PTAL.

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18853)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/279817076)

**Review by alexshalamov — APPROVED** [review]
lgtm

**Comment by Honry** [comment]
Thanks @alexshalamov, I will merge this PR and use standalone IDL files for idlharness.js in follow-up PRs.

**Pull request merged**
