### PR TITLE
23253 Remove Invalid/Deprecated CSS Req Flags

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
#23253
This change removes all invalid or deprecated CSS requirement flags (valid flags are listed [here](https://web-platform-tests.org/writing-tests/css-metadata.html#requirement-flags)).

### CODE REVIEW

**Review by dbaron — COMMENTED** [review]
It seems like there are some verification steps worth doing before removing all of these. For example, in tests where you remove the `ahem` flag, it's worth checking that these tests include the stylesheet that provides the Ahem font.  To know if there are more such steps, it would be useful to see a list of the flags that are being removed.

Also, any `<meta name="flags" content="">` with an empty content attribute hould be removed rather than left empty.

**Comment by DanielRyanSmith** [comment]
@dbaron Thank you for taking a look at this. I want to make sure this causes no issues so I appreciate your insight 🙂

These are the flags that were found that are either deprecated or not listed as relevant flags (and the number of times they appear):
```
'ahem': 2956,
'image': 1678,
'dom': 885,
'interact': 668,
'font': 234,
'animated': 125,
'namespace': 124,
'32bit': 65,
'http': 48,
'Ahem': 41,
'userstyle': 28,
'96dpi': 14,
'speech': 7,
'history': 7,
'combo': 2,
'internal': 1,
'page': 1,
'may21': 1
```
If any of these could possibly cause issue to remove, we can ignore them for the time being and wait to remove them. This procedure is a step to add css requirement flag validation to the lint tool.

> Also, any `<meta name="flags" content="">` with an empty content attribute hould be removed rather than left empty.

This is feasible, but there are already a number of files in the css directory with a `flags` tag containing an empty content attribute (6000+ even). Perhaps this is something that can be addressed with an additional PR?

**Comment by foolip** [comment]
@DanielRyanSmith could you split this into smaller PRs? In particular ahem/Ahem is one, maybe one for each thing with more than 100 occurrences, and then throw everything that remains into a final PR?

> This is feasible, but there are already a number of files in the css directory with a `flags` tag containing an empty content attribute (6000+ even). Perhaps this is something that can be addressed with an additional PR?

That's a lot! Can you file an issue about that? Not adding more such cases in this PR would be good.

**Comment by DanielRyanSmith** [comment]
@foolip
> could you split this into smaller PRs?

This is a good idea. I've created 3 PRs as a test run for:
[ahem](https://github.com/web-platform-tests/wpt/pull/31990)
[font](https://github.com/web-platform-tests/wpt/pull/31991)
[and interact](https://github.com/web-platform-tests/wpt/pull/31992)
These flags don't seem to overlap in the same tag very much. Hopefully this is a more manageable approach!
**Also, the `meta flags` tag should now be removed entirely if the last flag is removed from the `contents`**

> That's a lot! Can you file an issue about that?

Yes! - [issue created here](https://github.com/web-platform-tests/wpt/issues/31946)

**Comment by foolip** [comment]
@DanielRyanSmith looks like this flag is very often together with "image". Maybe bundle those? Or alternatively, if the overlap is mostly in a few directories, remove all flags in those directories first.

There are lots of ways to split up PRs of course. One consideration in addition to splitting by flag is to avoid touching the same files and directories many times. Files because you'll get conflicts and `git blame` will have an extra layer, and directories because the same people will be added as reviewers multiple times.

There's no need to perfect this though, just carve off relatively big pieces each time that roughly fit that description, and eventually you'll be done :)

**Pull request closed without merging**
