### PR TITLE
[GitHub Actions] remove the update-pr-preview job

### PR DESCRIPTION
**Pull request by foolip**
As discovered in https://github.com/web-platform-tests/wpt/issues/19378,
the existing setup isn't compatible with the GitHub Actions read-only tokens
for pull requests from forks.

Since the location of the staging deployment isn't very discoverable even
when it does work, disable the job pending a new setup.

### CODE REVIEW

**Comment by jugglinmike** [comment]
What do you think about removing the script and its tests, too? I sometimes have trouble understanding who (if anyone) depends on things in the `tools/` directory, so I'd rather not leave behind unused infrastructure.

**Comment by foolip** [comment]
Sure. I didn't read the config very carefully and look for what would be left dead code. You probably know exactly which bits it are, can you just push a commit to my branch with those removals?

**Comment by jugglinmike** [comment]
Sure thing. I don't know if you'd like a third opinion since I'm now a participant, so I'll leave merging to you

**Review by jugglinmike — APPROVED** [review]

**Review by foolip — COMMENTED** [review]
Second commit LGTM

**Comment by foolip** [comment]
We reviewed each other's changes so that's okay.

**Comment by foolip** [comment]
@jugglinmike FYI, since the code that adds the pull-request-has-preview label was removed in this PR and most likely that won't be used in the new solution, I'll remove that label from the repo entirely.

**Pull request merged**
