### PR TITLE
[GitHub Actions] dry run the manifest workflow on pull requests

### PR DESCRIPTION
**Pull request by foolip**
To avoid mishaps like https://github.com/web-platform-tests/wpt/pull/19568#issuecomment-539546267.

### CODE REVIEW

**Comment by jugglinmike** [comment]
`get_pr` currently logs an error if it can't find a merged pull request. It doesn't influence the process's return code, but it is a bit confusing (since it's completely expected for the dry run). How about relocating the message until after we've exited due to the dry run, just before we exit with a non-zero code?

**Comment by foolip** [comment]
`get_pr` might call `logger.error` or `logger.warning` with different messages, and returning `None` doesn't always involve a message, so trying to suppress the messages would get a bit unsightly. How about just not call `get_pr` at all in dry run mode and leaving it untested like the later bits?

**Review by jugglinmike — APPROVED** [review]

**Comment by foolip** [comment]
@jugglinmike the wpt commit history is far from tidy, but when squashing a commit as in https://github.com/web-platform-tests/wpt/commit/ca1a7a206f4ff0f8de1169b183b3b2474850a7c0 feel free to edit the commit message quite liberally and delete parts like the double subject and intermediate steps like "Update manifest_build.py".

**Comment by foolip** [comment]
If you haven't already noticed and be amused, try `git log --grep 'fixup!'` for a long list of amusing failures to clean up commit messages :)

**Pull request merged**
