### PR TITLE
Update expected result to match sorting performed by the test in clie…

### PR DESCRIPTION
**Pull request by wanderview**
…nts-matchall-client-types.https.html.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260705079)

# Firefox (nightly) #
Testing web-platform-tests at revision bffcebdc738ffab8aa53a2ca5bc1de0e28cf52dc
Using binary /home/travis/build/w3c/web-platform-tests/_venv/firefox/firefox
Starting tests
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6745/service-workers/service-worker/clients-matchall-client-types.https.html">/service-workers/service-worker/clients-matchall-client-types.https.html</a></summary>


|                               Subtest                                | Results |                                                                  Messages                                                                  |
|----------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                      | OK      |                                                                                                                                            |
| `Verify matchAll() with window client type`                          | PASS    |                                                                                                                                            |
| `Verify matchAll() with {window, sharedworker, worker} client types` | FAIL    | `promise_test: Unhandled rejection with value: object "Error: clients.matchAll() rejected: NotSupportedError: Operation is not supported"` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260705080)

# Sauce (safari) #
Testing web-platform-tests at revision bffcebdc738ffab8aa53a2ca5bc1de0e28cf52dc
Using binary None
Starting tests
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/6745/service-workers/service-worker/clients-matchall-client-types.https.html">/service-workers/service-worker/clients-matchall-client-types.https.html</a></summary>


|                               Subtest                                | Results |                                       Messages                                      |
|----------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------|
|                                                                      | OK      |                                                                                     |
| `Verify matchAll() with window client type`                          | FAIL    | `undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')` |
| `Verify matchAll() with {window, sharedworker, worker} client types` | FAIL    | `undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260705087)

# Chrome (unstable) #
Testing web-platform-tests at revision bffcebdc738ffab8aa53a2ca5bc1de0e28cf52dc

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/260705088)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision bffcebdc738ffab8aa53a2ca5bc1de0e28cf52dc

**Review by jakearchibald — APPROVED** [review]

**Pull request merged**
