### PR TITLE
webcrypto: merge tentative BigInt test into main

### PR DESCRIPTION
**Pull request by TimothyGu**
The spec change got merged in https://github.com/w3c/webcrypto/pull/266.

### CODE REVIEW

**Comment by TimothyGu** [comment]
CC @twiss

**Comment by sideshowbarker** [comment]
Once @twiss OK’s this, I can rubberstamp-approve it (and merge it)

**Comment by sideshowbarker** [comment]
I see now that although we have the `WebCryptoAPI/META.yml` file set up right:

https://github.com/web-platform-tests/wpt/blob/fc086c82d5a7e9b01a684a23336d6d1f9e79e303/WebCryptoAPI/META.yml#L1-L3

…I’d forgotten to add @twiss to the Reviewers team. Invited now, anyway — so the next time there’s a WPT WebCryptoAPI PR, this should all just work as expected.

**Review by twiss — APPROVED** [review]
Thanks! 🙏
This looks good to me 👍

**Comment by sideshowbarker** [comment]
@twiss do you have a merge button in the UI now? If so, please go ahead and push it…

**Comment by twiss** [comment]
Ah, yeah, now that you mention it, I do 😄

**Pull request merged**
