### PR TITLE
Revert "Properly expect a syntax error with :scope selectors in Eleme…

### PR DESCRIPTION
**Pull request by ayg**
…nt.closest"

This reverts commit e7eb15fa308a406dfb15ae8d40b5ddb02832f90e.

Nobody could tell me why this commit was correct in discussion on #4179.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17361)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264386577)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17361)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264386577)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 14:37:48
Finished: 2017-08-14 14:48:47



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17361)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264386577)

**Comment by zcorpan** [comment]
https://github.com/servo/servo/pull/14080#issuecomment-258617281 points to
https://github.com/w3c/csswg-drafts/commit/9b7faa30f2f42b04eb96b32ee8152f856c9edc08

https://drafts.csswg.org/css-scoping/ does not have :scope but https://drafts.csswg.org/selectors/#the-scope-pseudo does, so I guess it was re-introduced in Selectors at some point. @tabatkins ?

**Comment by ayg** [comment]
We always test the latest version of the spec in wpt, and that does contain :scope, so isn't it clear that this change is correct?

**Review by zcorpan — APPROVED** [review]
AFAICT the change is correct.

**Comment by ayg** [comment]
Thanks!

**Comment by upsuper** [comment]
FWIW, `:scope`-related definitions are not just for CSS Scoping, they are also mentioned from DOM spec for methods like `querySelector`, `querySelectorAll`, `matches`, and `closest`, and both Gecko (pre-Stylo) and Blink support that.

**Pull request merged**
