### PR TITLE
Remove remaining IDL `implements`

### PR DESCRIPTION
**Pull request by saschanaz**
Currently blocking #16864.

Try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5fa1dfcd8ac5c8cecf72ac0cf022cd9ebd4e2c5b

### CODE REVIEW

**Comment by gsnedders** [comment]
@saschanaz the DOM XPath IDL changes don't seem quite in-sync with https://wiki.whatwg.org/wiki/DOM_XPath (and the changes there were made by you 🙂), and notably miss `XPathEvaluator includes XPathEvaluatorBase`, and don't expose it.

**Comment by saschanaz** [comment]
>don't seem quite in-sync with

I was to minimize diffs, but okay, I'll sync it.

>notably miss XPathEvaluator includes XPathEvaluatorBase, and don't expose it.

Oops!

**Comment by gsnedders** [comment]
Easier to avoid mistakes like that if it's just in sync!

**Review by gsnedders — COMMENTED** [review]
The `domxpath` changes LGTM. Can someone else review the `dedicated-worker.idl` changes, plz? (I presume there's some reason we have that rather than including `html.idl` in places, though having something that auto-extracted is annoying from a keeping-things-in-sync point-of-view.)

**Comment by foolip** [comment]
dedicated-worker.idl should be deleted, I just haven't gotten around to it yet. It's not auto-updated, and as evidenced here that can cause trouble. But the changes LGTM.

**Review by foolip — APPROVED** [review]

**Pull request merged**
