### PR TITLE
Revert "Mark crossOrigin.sub.html infrastructure test failing in Chrome"

### PR DESCRIPTION
**Pull request by foolip**
Reverts web-platform-tests/wpt#30519

### CODE REVIEW

**Comment by foolip** [comment]
With the tests tweaked I see that instead of "PASS" string resulting from `test_driver.message_test(input.value, "*")` a message event arrives with this object:

```json
{
  "type": "testdriver-command",
  "message": {
    "type": "action",
    "action": "action_sequence",
    "actions": [
      {
        "type": "none",
        "actions": [
          {
            "type": "pause",
            "duration": 16
          },
          {
            "type": "pause",
            "duration": 16
          },
          {
            "type": "pause",
            "duration": 16
          }
        ],
        "id": "0"
      },
      {
        "type": "pointer",
        "actions": [
          {
            "type": "pointerMove",
            "x": 0,
            "y": 0,
            "origin": {
              "selector": ":root > *|body:nth-child(2) > *|input:nth-child(1)"
            }
          },
          {
            "type": "pointerDown",
            "button": 0
          },
          {
            "type": "pointerUp",
            "button": 0
          }
        ],
        "parameters": {
          "pointerType": "mouse"
        },
        "id": "1"
      }
    ],
    "context": "7c4cc6db-9fa1-4f7c-bc07-7a8dd7671161",
    "id": 0
  }
}
```

I assume that came from here:
https://github.com/web-platform-tests/wpt/blob/4c88c57b521c269a20cdb958a05f01a020629b0a/tools/wptrunner/wptrunner/testdriver-extra.js#L144-L145

@jgraham do you think this is the code path that Firefox is taking and still passing the test, or would you expect `is_test_context` to be true and this code path to not be taken?

Regardless, I guess I should put back the implicit filtering of message events to ignore this internal message...

**Comment by foolip** [comment]
Alright, the `input.value` in crossOriginChild.html is still the empty string after the P-A-S-S sequence of keystrokes has been sent. Perhaps the `<input>` element didn't get focus properly.

**Comment by foolip** [comment]
Nope, `document.activeElement` is the `<input>` element, so I guess it's the actual keyboard input that isn't working properly.

@jgraham would you happen to know if there are any wdspec tests for cross-origin actions? Looking for something more self-contained than this test case to file a chromedriver bug...

**Comment by jgraham** [comment]
I don't know, but if there were I'd expect it to show up in https://wpt.fyi/results/webdriver/tests/perform_actions?label=master&label=experimental&product=chrome&product=firefox&aligned&diff&filter=ADC&q=perform_actions and I can't see anything obvious there.

**Pull request closed without merging**
