### PR TITLE
Implements Node::isSameNode

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #10746

Adapted the tests from dom/nodes/Node-isEqualNode.html

### CODE REVIEW

**Comment by Ms2ger** [comment]
Code reviewed upstream.

**Comment by jugglinmike** [comment]
@foolip @gsnedders Do you know how this issue came to reference a pull request filed 2 years later? It's almost certainly related to the repository renaming, but I can't think of a good explanation. Thought I should bring it up now since it might cause confusion if it happens elsewhere

**Comment by gsnedders** [comment]
@jugglinmike Pretty sure it's referencing an issue in the Servo repo, and because the commit message got copied over during export…

**Comment by foolip** [comment]
In other words, there's a risk that we'll close issues that shouldn't be closed with exports...

**Comment by jugglinmike** [comment]
That explains why the ID appears in the pull request description, but the reference was only just activated today (note its position within the discussion thread of that other pull request). My new theory is that when renaming repositories, GitHub re-scans all the existing issues and activates any references it finds. I'm not sure if that is every desirable, so it may be a bug.

//cc @github 

(also: is there a better way to request support from an issue?)

**Pull request merged**
