### PR TITLE
Updated assertions in urlsearchparams-getall tests

### PR DESCRIPTION
**Pull request by IvanJov**
Hi,

I've updated tests, made them nicer for debugging. Let me know what do you think.

Code was also sent as PR to Node repo: https://github.com/nodejs/node/pull/11142

Thanks!

### CODE REVIEW

**Comment by tobie** [comment]
@wpt-pr-bot, are you there?

**Comment by annevk** [comment]
This looks reasonable to me, but I'm never quite sure whether the assertion description needs to describe the assertion or the unexpected result.

@gsnedders @jgraham? Seems that http://testthewebforward.org/docs/testharness-library.html#making-assertions should say this, no?

**Comment by IvanJov** [comment]
@annevk I think that it should describe why the test failed. This is what docs say: `The description parameter is used to present more useful error messages when a test fails`. 🙂

**Comment by domenic** [comment]
I've always gone with "should" or "must" in my assertion messages. So `'Search params object must have name "a"`

**Comment by zcorpan** [comment]
w3c-test:mirror

**Comment by zcorpan** [comment]
For `assert_equals` I generally avoid saying what the expected value is in the message, since the message already contains that and it tends to get out of sync if the test is later updated to change what is expected.

**Comment by annevk** [comment]
@IvanJov it says to be useful when the test fails, it doesn't say describe when it fails. Given the feedback from others I guess we should either close this or simply drop these messages and rely on the default handling. Are you up for doing that?

**Comment by annevk** [comment]
Closing due to lack of feedback. Sorry it didn't work out.

**Pull request closed without merging**
