### PR TITLE
Check for test files affected by wdspec support files

### PR DESCRIPTION
**Pull request by mjzffr**
wdspec tests are run using pytest, and are therefore
affected by changes to fixtures in ancestor directories
(usually in conftest.py).

Unlike other tests, wdspec tests do not list the paths
of the support files they rely on. Instead, it's fair
to assume a test relies on any support file in the
same directory or a 'support' subdirectory.

You can see some sample Travis runs with this change (with wdspec test fixtures modified and extra debug printing):
* https://travis-ci.org/mjzffr/web-platform-tests/jobs/228558971#L406
* https://travis-ci.org/mjzffr/web-platform-tests/jobs/228570201#L406

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5797)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229124126)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1883ba074f37a8cdbb3160d2deeed22e6af9dd6f
Using browser at version BuildID 20170504100357; SourceStamp 33b92d9c40562dab3d7b602368c75619f1d793f7
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229124132)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1883ba074f37a8cdbb3160d2deeed22e6af9dd6f

**Comment by jgraham** [comment]
Can you add an example change to this PR to verify that it works as expected? We'll remove it before landing.

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5797)*

**Comment by jgraham** [comment]
r+ please remove the example change again so we can merge.

**Comment by mjzffr** [comment]
@jgraham Done

**Pull request merged**
