### PR TITLE
Add test for Web Storage API

### PR DESCRIPTION
**Pull request by kangxu**
- Add test for event fired by remove item
- Add manual test for local and session storage basic
  application scene

### CODE REVIEW

**Comment by chunywang** [comment]
Thank you for review @Ms2ger . I have improved them and call for review again.

**Comment by zqzhang** [comment]
@Ms2ger are you available for reviewing the rest in critic?

**Comment by Ms2ger** [comment]
Reviewed!

**Comment by kangxu** [comment]
@Ms2ger  I have squashed all the commits into one to address your comments.

**Pull request merged**
