### PR TITLE
URL: Percent-encode additional characters in "fragment state".

### PR DESCRIPTION
**Pull request by mikewest**
Tests for the new percent-encoding rules introduced in whatwg/url#347.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-09 13:10:05
Finished: 2017-10-09 13:23:42


<h2>Failing Jobs</h2>
<ul>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19275)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/285568014)

**Review by TimothyGu — APPROVED** [review]

**Comment by annevk** [comment]
This looks reasonable, but I think there are many existing fragment tests that will also be affected by this change.

**Comment by mikewest** [comment]
At some point this week, I'll have time to change Chrome's implementation so I can see what breaks. Will report back when that happens!

**Comment by annevk** [comment]
Great. You could also do it via https://github.com/jsdom/whatwg-url though that might still miss some tests I suppose.

**Review by domenic — CHANGES_REQUESTED** [review]
The following existing tests need updating:

```
<http://f:21/ b ? d # e > against <http://example.org/foo/bar>

<lolscheme:x x#x x> against <about:blank>

<http://www.google.com/foo?bar=baz# »> against <about:blank>

<data:test# »> against <about:blank>
```

These all appear to have to do with the encoding of spaces.

**Comment by mikewest** [comment]
Closing this out in favor of https://github.com/w3c/web-platform-tests/pull/7776, which will be automatically exported from Chromium's repository once I work through review. Would y'all mind taking a look at the additions to that patch to see if you think they're reasonable? It should just be this patch, plus the tests @domenic noted above.

Thanks!

**Pull request closed without merging**
