### PR TITLE
updating readme to point to a new tool

### PR DESCRIPTION
**Pull request by thejohnjansen**
I've written a powershell script to install all of the necessary tools to run these tests on Windows. Adding a link to it here.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/9209)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-26 19:47:24
Finished: 2018-01-26 19:57:46


<h2>Failing Jobs</h2>
<ul>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23342)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/333877912)

**Review by jgraham — APPROVED** [review]
Sure, but I would be happier if the tool lived in this repository. You could use `raw.githubusercontent.com` based links for downloading it.

**Comment by gsnedders** [comment]
+1. Let's just add into tools/.

**Comment by thejohnjansen** [comment]
OK. I'll submit to tools and kill this PR.

**Pull request closed without merging**
