### PR TITLE
Returning the promise in promise_test

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5228/)

**Comment by annevk** [comment]
Hmm, this ends up breaking #5129 even more, but does seem like a good idea to fix... Any ETA on review for that PR?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215570306)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 1346b976ac1369eb2fc8fe320eb30cf713240238
Using browser at version BuildID 20170326110231; SourceStamp f5e214144799889e2408c4841351f4053f00544e
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5228/fetch/api/cors/cors-preflight-status-worker.html">/fetch/api/cors/cors-preflight-status-worker.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Preflight answered with status 200` | PASS    | `{}`     |
| `Preflight answered with status 201` | PASS    | `{}`     |
| `Preflight answered with status 202` | PASS    | `{}`     |
| `Preflight answered with status 203` | PASS    | `{}`     |
| `Preflight answered with status 204` | PASS    | `{}`     |
| `Preflight answered with status 205` | PASS    | `{}`     |
| `Preflight answered with status 206` | PASS    | `{}`     |
| `Preflight answered with status 300` | PASS    | `{}`     |
| `Preflight answered with status 301` | PASS    | `{}`     |
| `Preflight answered with status 302` | PASS    | `{}`     |
| `Preflight answered with status 303` | PASS    | `{}`     |
| `Preflight answered with status 304` | PASS    | `{}`     |
| `Preflight answered with status 305` | PASS    | `{}`     |
| `Preflight answered with status 306` | PASS    | `{}`     |
| `Preflight answered with status 307` | PASS    | `{}`     |
| `Preflight answered with status 308` | PASS    | `{}`     |
| `Preflight answered with status 400` | PASS    | `{}`     |
| `Preflight answered with status 401` | PASS    | `{}`     |
| `Preflight answered with status 402` | PASS    | `{}`     |
| `Preflight answered with status 403` | PASS    | `{}`     |
| `Preflight answered with status 404` | PASS    | `{}`     |
| `Preflight answered with status 405` | PASS    | `{}`     |
| `Preflight answered with status 501` | PASS    | `{}`     |
| `Preflight answered with status 502` | PASS    | `{}`     |
| `Preflight answered with status 503` | PASS    | `{}`     |
| `Preflight answered with status 504` | PASS    | `{}`     |
| `Preflight answered with status 505` | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5228/fetch/api/cors/cors-preflight-status.html">/fetch/api/cors/cors-preflight-status.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Preflight answered with status 200` | PASS    |          |
| `Preflight answered with status 201` | PASS    |          |
| `Preflight answered with status 202` | PASS    |          |
| `Preflight answered with status 203` | PASS    |          |
| `Preflight answered with status 204` | PASS    |          |
| `Preflight answered with status 205` | PASS    |          |
| `Preflight answered with status 206` | PASS    |          |
| `Preflight answered with status 300` | PASS    |          |
| `Preflight answered with status 301` | PASS    |          |
| `Preflight answered with status 302` | PASS    |          |
| `Preflight answered with status 303` | PASS    |          |
| `Preflight answered with status 304` | PASS    |          |
| `Preflight answered with status 305` | PASS    |          |
| `Preflight answered with status 306` | PASS    |          |
| `Preflight answered with status 307` | PASS    |          |
| `Preflight answered with status 308` | PASS    |          |
| `Preflight answered with status 400` | PASS    |          |
| `Preflight answered with status 401` | PASS    |          |
| `Preflight answered with status 402` | PASS    |          |
| `Preflight answered with status 403` | PASS    |          |
| `Preflight answered with status 404` | PASS    |          |
| `Preflight answered with status 405` | PASS    |          |
| `Preflight answered with status 501` | PASS    |          |
| `Preflight answered with status 502` | PASS    |          |
| `Preflight answered with status 503` | PASS    |          |
| `Preflight answered with status 504` | PASS    |          |
| `Preflight answered with status 505` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215570307)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 1346b976ac1369eb2fc8fe320eb30cf713240238
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5228/fetch/api/cors/cors-preflight-status-worker.html">/fetch/api/cors/cors-preflight-status-worker.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Preflight answered with status 200` | PASS    | `{}`     |
| `Preflight answered with status 201` | PASS    | `{}`     |
| `Preflight answered with status 202` | PASS    | `{}`     |
| `Preflight answered with status 203` | PASS    | `{}`     |
| `Preflight answered with status 204` | PASS    | `{}`     |
| `Preflight answered with status 205` | PASS    | `{}`     |
| `Preflight answered with status 206` | PASS    | `{}`     |
| `Preflight answered with status 300` | PASS    | `{}`     |
| `Preflight answered with status 301` | PASS    | `{}`     |
| `Preflight answered with status 302` | PASS    | `{}`     |
| `Preflight answered with status 303` | PASS    | `{}`     |
| `Preflight answered with status 304` | PASS    | `{}`     |
| `Preflight answered with status 305` | PASS    | `{}`     |
| `Preflight answered with status 306` | PASS    | `{}`     |
| `Preflight answered with status 307` | PASS    | `{}`     |
| `Preflight answered with status 308` | PASS    | `{}`     |
| `Preflight answered with status 400` | PASS    | `{}`     |
| `Preflight answered with status 401` | PASS    | `{}`     |
| `Preflight answered with status 402` | PASS    | `{}`     |
| `Preflight answered with status 403` | PASS    | `{}`     |
| `Preflight answered with status 404` | PASS    | `{}`     |
| `Preflight answered with status 405` | PASS    | `{}`     |
| `Preflight answered with status 501` | PASS    | `{}`     |
| `Preflight answered with status 502` | PASS    | `{}`     |
| `Preflight answered with status 503` | PASS    | `{}`     |
| `Preflight answered with status 504` | PASS    | `{}`     |
| `Preflight answered with status 505` | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5228/fetch/api/cors/cors-preflight-status.html">/fetch/api/cors/cors-preflight-status.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `Preflight answered with status 200` | PASS    |          |
| `Preflight answered with status 201` | PASS    |          |
| `Preflight answered with status 202` | PASS    |          |
| `Preflight answered with status 203` | PASS    |          |
| `Preflight answered with status 204` | PASS    |          |
| `Preflight answered with status 205` | PASS    |          |
| `Preflight answered with status 206` | PASS    |          |
| `Preflight answered with status 300` | PASS    |          |
| `Preflight answered with status 301` | PASS    |          |
| `Preflight answered with status 302` | PASS    |          |
| `Preflight answered with status 303` | PASS    |          |
| `Preflight answered with status 304` | PASS    |          |
| `Preflight answered with status 305` | PASS    |          |
| `Preflight answered with status 306` | PASS    |          |
| `Preflight answered with status 307` | PASS    |          |
| `Preflight answered with status 308` | PASS    |          |
| `Preflight answered with status 400` | PASS    |          |
| `Preflight answered with status 401` | PASS    |          |
| `Preflight answered with status 402` | PASS    |          |
| `Preflight answered with status 403` | PASS    |          |
| `Preflight answered with status 404` | PASS    |          |
| `Preflight answered with status 405` | PASS    |          |
| `Preflight answered with status 501` | PASS    |          |
| `Preflight answered with status 502` | PASS    |          |
| `Preflight answered with status 503` | PASS    |          |
| `Preflight answered with status 504` | PASS    |          |
| `Preflight answered with status 505` | PASS    |          |

</details>
</details>

**Comment by youennf** [comment]
@annevk, you can merge it in #5129 if that is more convenient.

**Comment by annevk** [comment]
Created #5230 to take care of this.

**Pull request closed without merging**
