### PR TITLE
Update existing tests as per https://github.com/web-platform-tests/wpt/pull/13499

### PR DESCRIPTION
**Pull request by youennf**
This PR takes https://github.com/web-platform-tests/wpt/pull/13499 changes from existing tests and move them to a separate PR.

### CODE REVIEW

**Comment by youennf** [comment]
Some of the newly added tests require a change to createDataChannelPair in RTCPeerConnection-helpers.js.
@lgrahl, would you be able to update in this PR RTCPeerConnection-helpers.js with the new functionality required for createDataChannelPair?

The alternative might be that I remove the tests using this new functionality to allow merging the other changes.
I do not think we should work around Safari bugs as in https://github.com/web-platform-tests/wpt/pull/13499.

**Comment by youennf** [comment]
This PR does not contain PR #13499 changes related to RTCSctpTransport-constructor.html as they were conflicting with other changes that landed already.
@lgrahl, if you can file a separate PR for these specific changes, that would be nice.

**Comment by youennf** [comment]
PR not yet ready to be merged.

**Comment by lgrahl** [comment]
I've compared the changes to my branch and I'm confused by the changes that have been made to it.

1. I'm seeing a syntax error in `RTCDataChannel-bufferedAmount.html`.
2. The `resolver` is not being awaited any longer in `RTCPeerConnection-ondatachannel.html`. The test ends prematurely.
3. The local timeout stuff and the global timeout disabler I added still exist.

Thus, I took this branch and rebased it, added the required functionality to `RTCPeerConnection-helper.js`, added the `RTCSctpTransport` tests and removed the local timeouts. See #14424.

**Comment by youennf** [comment]
@lgrahl, thanks for taking over in #14424.
Let's close this one then.

**Pull request closed without merging**
