### PR TITLE
 #11343 - Redirect POST requests using .py resource

### PR DESCRIPTION
**Pull request by dheiberg**
Created a simple .py resource that redirects the POST request to `reload_post_1-1.html`. URL is hardcoded, it would be possible to make it a more general resource if necessary?

### CODE REVIEW

**Comment by dhdavvie** [comment]
#11343

**Comment by zcorpan** [comment]
I don't think it should redirect, instead it should return a normal response body, and the other helper file can be removed.

**Comment by dhdavvie** [comment]
I've changed it so that the py file does not redirect, but instead returns a response body as suggested. The subsequent reload requires user approval, so I have flagged the test as `manual`.

**Comment by zcorpan** [comment]
Looks good. Can you also remove `reload_post_1-1.html`?

**Review by zcorpan — APPROVED** [review]

**Comment by zcorpan** [comment]
Let's leave #11343 open since we may want to change the behavior of the server.

**Pull request merged**
