### PR TITLE
Mixed-Content WebSockets

### PR DESCRIPTION
**Pull request by kristijanburnik**
Add mixed-content tests for WebSockets.

This PR also displays the first use case of the shared Stash in WebSockets. (CC: @jgraham )

See both commits for more context.

@mikewest

### CODE REVIEW

**Comment by kristijanburnik** [comment]
I repushed the PR, I managed to generate some non-applicable scenarios yesterday, now it's cleaned up.

@mikewest

**Comment by mikewest** [comment]
Have you run the tests against Canary and Aurora? How do things look with regard to conformance?

**Comment by kristijanburnik** [comment]
I'd say pretty much the same as stables 43 and 39, I can run them today and give back the stats.

Chrome 43 stable passes all websocket tests.

**Comment by kristijanburnik** [comment]
Btw, by Aurora you mean FF nightly?

Isn't Aurora for android only? I mean I'd be happy to run it on an emulator if we can gain more insight :-)

**Comment by mikewest** [comment]
I thought Aurora was nightly. Apparently I have no idea how Mozilla works. :)

**Comment by kristijanburnik** [comment]
I was confused a bit too, here it says it's sort of a pre-beta channel:
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Mercurial

**Comment by jgraham** [comment]
Aurora has become developer edition, more or less.

You probably want to test against nightly.

**Comment by kristijanburnik** [comment]
A bit of my local stats for websocket tests:

No. of tests: 19

Chrome 43 stable: 19 pass
Firefox 39 stable: 14 pass, 5 fail (all which should be alllowed requests) seemingly due to an SSL misconfiguration:

```
https://web-platform.test:8443/mixed-content/allowed/no-opt-in/same-host-wss/websocket-request/top-level/keep-scheme-redirect/websocket-allowed.https.html
https://web-platform.test:8443/mixed-content/allowed/no-opt-in/same-host-wss/websocket-request/top-level/no-redirect/websocket-allowed.https.html
https://web-platform.test:8443/mixed-content/allowed/http-csp/same-host-wss/websocket-request/top-level/keep-scheme-redirect/websocket-allowed.https.html
https://web-platform.test:8443/mixed-content/allowed/http-csp/same-host-wss/websocket-request/top-level/no-redirect/websocket-allowed.https.html
https://web-platform.test:8443/mixed-content/allowed/meta-csp/same-host-wss/websocket-request/top-level/no-redirect/websocket-allowed.https.html
```

I get this error in PyWebSocket when running the tests in FF

```
DEBUG:web-platform-tests:200 GET /mixed-content/generic/expect.py?action=put&key=54fa26df-3af0-41b2-a9fc-34bf398c3ffd&value=73b30c4b-e3cc-4875-9aa1-d26d6ab56861&path=%2Fmixed-content (https://web-platform.test:8443/mixed-content/allowed/no-opt-in/same-host-wss/websocket-request/top-level/keep-scheme-redirect/websocket-allowed.https.html) 0
DEBUG:mod_pywebsocket.standalone.WebSocketServer:Cipher: ('AES128-SHA', 'TLSv1/SSLv3', 128)
DEBUG:mod_pywebsocket.standalone.WebSocketServer:Client cert: None
ERROR:mod_pywebsocket.standalone.WebSocketServer:Exception in processing request from: ('127.0.0.1', 37621)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/google/home/burnik/web-platform-tests/tools/pywebsocket/src/mod_pywebsocket/standalone.py", line 696, in __init__
    self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/google/home/burnik/web-platform-tests/tools/pywebsocket/src/mod_pywebsocket/memorizingfile.py", line 85, in readline
    line = self._file.readline()
  File "/usr/lib/python2.7/socket.py", line 430, in readline
    data = recv(1)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
```

The network tab in the FF console says:

```
web-platform.test:35279 uses an invalid security certificate.

The certificate is not trusted because the issuer certificate has expired.

(Error code: sec_error_expired_issuer_certificate)
```

Not sure if I have a local SSL misconfig, or if the problem is in FF/WPTServe/PyWebSocket?

CC: @jgraham

**Comment by kristijanburnik** [comment]
@mikewest

Anything else required before landing the tests?

**Comment by mikewest** [comment]
No. As long as @jgraham knows that there will likely be some tests he needs to skip while we figure out whether the SSL issue reproduces anywhere other than your machine, I'm happy landing the patch.

**Pull request merged**
