### PR TITLE
Update OWNERS - remove bentian

### PR DESCRIPTION
**Pull request by marcoscaceres**
bentian is working on other fun things.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 04:58:09
Finished: 2017-08-14 05:02:42



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17334)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264239878)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 04:58:09
Finished: 2017-08-14 05:02:42



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17334)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264239878)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 04:58:09
Finished: 2017-08-14 05:02:42



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17334)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264239878)

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 04:58:09
Finished: 2017-08-14 05:02:42



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17334)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264239878)

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
