### PR TITLE
Re-sync Canvas API in html/dom/interfaces.html

### PR DESCRIPTION
**Pull request by cdumez**
Re-sync Canvas API in html/dom/interfaces.html with the latest HTML specification.

### CODE REVIEW

**Comment by cdumez** [comment]
@domenic

**Comment by domenic** [comment]
Trailing whitespace, says Travis CI.

**Comment by cdumez** [comment]
Looks like Travis CI is happy now.

**Comment by domenic** [comment]
Thanks very much!

**Pull request merged**
