### PR TITLE
[GitHub Actions] consistently use ubuntu-20.04 and checkout v2

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
Makes sense, assuming you tested this.

**Comment by foolip** [comment]
@Ms2ger `.github/workflows/regen_certs.yml` doesn't need to be tested since `ubuntu-latest` is currently `ubuntu-20.04`. For the other two I'll push a test commit to dry run it and monitor what happens after I merge.

**Comment by foolip** [comment]
I did a dry run of all 3 workflows instead:
https://github.com/web-platform-tests/wpt/actions/runs/770037163 (failed)
https://github.com/web-platform-tests/wpt/actions/runs/770037165 (failed)
https://github.com/web-platform-tests/wpt/actions/runs/770037167

@Ms2ger thanks for asking, because things failed in ways I didn't expect. I'll investigate...

**Comment by foolip** [comment]
It turns out this did break the epochs workflow, because `actions/checkout@v2` changed the default to a shallow checkout, where that script actually requires some amount of history for `./wpt rev-list` to work. Fixing...

**Comment by foolip** [comment]
Dry runs look good now:
https://github.com/web-platform-tests/wpt/actions/runs/770336206
https://github.com/web-platform-tests/wpt/actions/runs/770336210

**Pull request merged**
