### PR TITLE
Improved precision of text-align-end-00[1-15].html and their reference files

### PR DESCRIPTION
**Pull request by TalbotG**
This is a followup and an **entire replacement** to #34705, #34708, #34724 and #34726

On my website (12 tests and 12 correspondent reference files):

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-001-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-001-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-002-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-002-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-003-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-003-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-004-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-004-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-005-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-005-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-006-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-006-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-007-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-007-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-008-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-008-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-009-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-009-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-010-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-010-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-014-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-014-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/text-align-end-015-newer-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/text-align/reference/text-align-end-ref-015-newer-GT.html

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
Hi @TalbotG, these look very good as improvements, however since we are no longer relying on box layout for the references, I would like to be a little bit more explicit about the alignment of the reference text. Here are two options to consider:

Option A: Use `text-align: left` and `text-align: right` explicitly on the references.
Option B: Use `margin-left` and `margin-right` to position the text of the references.

**Comment by TalbotG** [comment]
The 12 tests and correspondent references use `margin: 20px` already.

I can replace` direction: ltr` inside test14 and ref14 with `text-align: left` for more and better consistency with its counterpart test15 and ref15. Pull request on that coming up.

But besides such replacement, is there a need for more tweaking?

**Comment by fantasai** [comment]
What I'm asking is to be more explicit about the references. E.g.

```
<style type='text/css'>
.test { text-align: end; }
/* the CSS below is not part of the test */
.test, .ref { border: 1px solid orange; margin: 20px; width: 300px; color: orange; font: 25px/1 Ahem; }
</style>
</head>
<body>
<div id='instructions'>Test passes if shading in both orange boxes is identical.</div>
<div dir="rtl">
<div class="test" dir="ltr">TES TES TES TES TES TES TES TES</div>
<div class="ref">REF REF REF REF REF REF REF REF</div>
</div>
```

Change to
```
<style type='text/css'>
.test { text-align: end; }
.ref { text-align: right; }
/* the CSS below is not part of the test */
.test, .ref { border: 1px solid orange; margin: 20px; width: 300px; color: orange; font: 25px/1 Ahem; }
</style>
</head>
<body>
<div id='instructions'>Test passes if shading in both orange boxes is identical.</div>
<div dir="rtl">
<div class="test" dir="ltr">TES TES TES TES TES TES TES TES</div>
<div class="ref">REF REF REF REF REF REF REF REF</div>
</div>
```

This way the reference is less dependent on the browser getting the default behavior right, and also the reference behavior is very easy to understand from someone reading the source code.

**Comment by TalbotG** [comment]
There is a small oversight in R. Ishida's  original text-align-end-010.html test. The left‐to‐right mark (`&lrm;`) is missing from the test while the text (title and assert) clearly discusses about it. So, I will add it along with the explicitness additions. A commit is upcoming...

**Comment by jcscottiii** [comment]
This looks to be a transient error unrelated to this PR: 
```
bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
```

Going to close and reopen

**Comment by TalbotG** [comment]
@jcscottiii Thank you!

**Review by fantasai — APPROVED** [review]

**Pull request merged**
