### PR TITLE
Revert "[Gecko Bug 1614329] Fix the handling of the type attribute of HTMLStyleElement"

### PR DESCRIPTION
**Pull request by Hexcles**
Reverts web-platform-tests/wpt#21736

### CODE REVIEW

**Comment by Hexcles** [comment]
I'm not sure -- is this redundant with https://github.com/web-platform-tests/wpt/blob/master/html/semantics/document-metadata/the-style-element/style_type.html ? @ehsan 

If this was intentional, then we have yet another example of #7570 and we might just have to rename them.

**Comment by Hexcles** [comment]
FYI @KyleJu this is blocking wpt-import

**Comment by annevk** [comment]
FWIW, this looks very much intentional. Ensuring there's no subtle differences between HTML and XML code paths.

**Review by jgraham — CHANGES_REQUESTED** [review]
I think reverting this is the wrong thing to do. If there are Blink-specific rules around file naming they should be encoded in the lint (and existing instances can be fixed).

**Comment by Hexcles** [comment]
Sorry if I wasn't clear: I wasn't going to just land this, but was genuinely unsure. And thanks for the answer @annevk ; @jgraham yeah I'll send another PR to rename them.

**Pull request closed without merging**
