### PR TITLE
Add apng that uses cICP

### PR DESCRIPTION
**Pull request by svgeesus**
> [Each frame inherits every property specified by any critical or ancillary chunks before the first `IDAT` chunk in the file](https://w3c.github.io/PNG-spec/#fdAT-chunk)

Test image has  `IHDR`, `cICP`, `acTL`, `IDAT`, `fcTL`, `fdAT`, `IEND`

`cICP` is 12, 13, 0, 1 _ie_ Display P3

Animation has one frame, static image is not part of the animation.

The static image is P3 red, the first frame in the fdAT is srgb lime converted to Display P3.
sRGB lime =  color(display-p3 0.4584 0.9853 0.2983)

So the displayed result should be sRGB lime, converted back from Display P3

### CODE REVIEW

**Comment by svgeesus** [comment]
@ProgramMax I thought that you had been added as a reviewer for WPT PNG tests, but it seems not.

**Review by ProgramMax — APPROVED** [review]
non-OWNER LGTM

**Comment by svgeesus** [comment]
@ProgramMax you are listed [here](https://github.com/web-platform-tests/wpt/blob/master/png/META.yml) as a reviewer, maybe it needs some other permission as well.

**Comment by svgeesus** [comment]
@foolip @jgraham sorry to keep bothering you like this, could we get an owner approval please?

**Comment by svgeesus** [comment]
@annevk perhaps you could review?

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
@svgeesus you should ask on the Matrix chat to get @ProgramMax added as a committer.

**Pull request merged**
