### PR TITLE
Removed {% raw %} and {% endraw %} stuff.

### PR DESCRIPTION
**Pull request by sideshowbarker**
See w3c/testtwf-website-src#17

### CODE REVIEW

**Comment by sideshowbarker** [comment]
See https://github.com/w3c/testtwf-website-src/pull/17

**Comment by gsnedders** [comment]
This was accepted months ago, @sideshowbarker. I presume merging this won't do anything silly like breaking the website? (It doesn't automatically update, right?)

**Comment by sideshowbarker** [comment]
@gsnedders Please see https://github.com/w3c/testtwf-website-src/pull/17#issuecomment-124501291

**Comment by gsnedders** [comment]
@sideshowbarker But can we merge this *now* and fix that later?

**Comment by sideshowbarker** [comment]
> @sideshowbarker But can we merge this now and fix that later?

Yes, I think we can but please doublecheck with @jgraham before doing the merge. I should just be able to answer this myself easily but I’ve been highly preoccupied for the last week or so, and only getting back to things just now.

**Comment by zcorpan** [comment]
ping

**Pull request merged**
