### PR TITLE
Use pc.createOffer({ ... }) wherever possible. Make generateOffer() accept RTCPeerConnection object. Fixes gh-7054

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17929)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/270191826)

**Comment by soareschen** [comment]
`generateOffer` and `generateAnswer` was written as a short hand for quickly creating an offer/answer when we do not care about the `RTCPeerConnection` object. If we make the `pc` argument explicit, might as well just use `pc.createOffer()` since the only other shortcut is automatically creating data channel when the `data` argument is `true`.

We should probably replace calls to `generateOffer` to `pc.createOffer` and `pc.createDataChannel`. `generateOffer` can be left as is and only used when it is clearly saving lines, or be removed altogether if there is no more use for it.

**Comment by soareschen** [comment]
Btw I have submitted #7070 to fix #7054. We can work on the other refactoring of `generateOffer` in this PR.

**Comment by rwaldron** [comment]
> might as well just use pc.createOffer() since the only other shortcut is automatically creating data channel when the data argument is true.

That's exactly what I've done, keeping only the uses of `generateOffer` that included a `data: true` property in the options.

**Comment by rwaldron** [comment]
@soareschen I will land your #7070 and then rebase this PR

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Review by soareschen — APPROVED** [review]

**Pull request merged**
