### PR TITLE
*.any.js: explicitly list defaults, part 1

### PR DESCRIPTION
**Pull request by annevk**
Helps with #23111.

### CODE REVIEW

**Review by ricea — APPROVED** [review]
lgtm

**Review by domfarolino — APPROVED** [review]

**Review by Ms2ger — COMMENTED** [review]
Holding off on this until https://github.com/web-platform-tests/rfcs/pull/52 passes.

**Review by Ms2ger — CHANGES_REQUESTED** [review]
https://github.com/web-platform-tests/rfcs/pull/52

**Comment by annevk** [comment]
@Ms2ger could you explain why you feel this change is blocked on that? Most tests we have are already explicit and there's no functional change here.

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
