### PR TITLE
HTML: attribute selectors with case-insensitive values

### PR DESCRIPTION
**Pull request by annevk**
Given https://bugs.webkit.org/show_bug.cgi?id=265719 this needs some coverage.

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
This seems correct. (I assume you copied the list correctly.)

It might be good to also cover the following:

* MathML elements
* SVG elements
* attributes in a namespace (though I'm not quite sure what the spec expects there)

**Comment by Ms2ger** [comment]
Oh, and:

* that other attributes *are* case-sensitive

**Comment by Ms2ger** [comment]
Feel free to either add those to this PR or file a followup issue

**Review by Nevalynn88 — COMMENTED** [review]
Back to normal

**Pull request merged**
