### PR TITLE
Remove untested IDL fragments from battery-interface-idlharness.html

### PR DESCRIPTION
**Pull request by zqzhang**
This will bypass 2 failures not specific to Battery Status API.

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/battery-status-reviewers.

**Comment by zqzhang** [comment]
I haven't checked why does `idlharness.js` create such tests for the untested IDL. Seems something there can be improved.

You can try the testing with this change at

http://zqzhang.github.io/demo/idlharness/battery-status.html

**Comment by dontcallmedom** [comment]
Well, idlharness doesn't test instances of `EventTarget`, but it tests that `BatteryManager` properly inherits from` EventTarget` which makes sense to me.
I don't think we should merge that change; if the test fails, we can explain that it is due to a bug in implementation of the `EventTarget` interface in general, not due to the specifics of the battery API. But the test should nevertheless shows there is a bug in Chrome there.

**Comment by zqzhang** [comment]
Good, thanks @dontcallmedom

**Pull request closed without merging**
