### PR TITLE
Map some CSS features to web-features

### PR DESCRIPTION
**Pull request by foolip**
This is a somewhat random collection of CSS features in web-features
mapped to tests in WPT. Mostly features starting with A-C, plus a few
more by association.

### CODE REVIEW

**Comment by svgeesus** [comment]
To help me review, what are these yml files used for?

**Comment by foolip** [comment]
@svgeesus they are used to create a `WEB_FEATURES_MANIFEST.json` file published for every merged PR. Example:
https://github.com/web-platform-tests/wpt/releases/tag/merge_pr_45492

That is then used to allow filtering by feature on wpt.fyi, like this:
https://wpt.fyi/results/?label=master&label=experimental&aligned&q=feature%3Afocus-visible

It's especially useful for features that span directories or when the same directory covers many features.

**Review by svgeesus — COMMENTED** [review]
What is here looks correct to me.

I didn't check for completeness (i.e. a feature being tested by another test aimed at a different feature) and I know such tests exist. Depends on what granularity is desired, I suppose.

**Comment by foolip** [comment]
@svgeesus thanks! I have avoided tests that clearly test multiple features at the same time, which includes many tests using inheritance-testcommon.js or idlharness.js. Those are quite surface level, but at some point it would be nice to be able to handle tests that cover the interactions between two features. I'll file an issue I think...

**Review by dbaron — APPROVED** [review]

**Pull request merged**
