### PR TITLE
add pytest-icdiff to make diffs easier to visualize

### PR DESCRIPTION
**Pull request by thiagowfx**
Adopt the same approach as in Chromium BiDi mapper repo:
https://github.com/search?q=repo%3AGoogleChromeLabs%2Fchromium-bidi%20pytest-icdiff&type=code

### CODE REVIEW

**Comment by thiagowfx** [comment]
This is working well for us in the chromium bidi mapper repo: https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/tests/requirements.txt#L5

**Review by sadym-chromium — APPROVED** [review]

**Comment by sadym-chromium** [comment]
It can potentially break some runners expecting specific test output, but not sure if it's a case.

**Comment by thiagowfx** [comment]
We can always revert it if so, let's see.

**Comment by foolip** [comment]
Is the dependency alone enough to make this work, aren't any code changes needed?

**Comment by thiagowfx** [comment]
The unittests fail but it not obvious why: https://github.com/web-platform-tests/wpt/pull/39831/checks?check_run_id=13762982848

**Comment by thiagowfx** [comment]
The only message in the logs is:

```
Failed to fetch
An error occurred attempting to load the provided log.
Please check the URL and ensure it is reachable.
https://community-tc.services.mozilla.com/api/queue/v1/task/R9Cys9T8Sse8hl3a9TUHsg/runs/5/artifacts/public%2Flogs%2Flive.log
```

It seems unrelated to me. What else can we do to unblock this?

**Comment by thiagowfx** [comment]
Sure, triggered a new run.

**Comment by thiagowfx** [comment]
There are no logs even with a fresh run.

**Pull request closed without merging**
