### PR TITLE
Update css-masking IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-07 19:54:09
Finished: 2018-03-07 20:03:17


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25470)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350481472)

**Comment by foolip** [comment]
Can you add a test in https://github.com/w3c/web-platform-tests/tree/master/css/css-masking?

**Comment by foolip** [comment]
@lukebjerring FYI, this is still missing a test.

**Review by foolip — APPROVED** [review]
Nice, test entirely passing in Firefox, and reveals some minor broken thing in Chrome!

**Pull request merged**
