### PR TITLE
Add RTCSctpTransport-onstatechange.html test from PR13499

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by youennf** [comment]
@lgrahl, made some changes to the original test. PTAL.

**Comment by youennf** [comment]
Maybe we should move that test to RTCSctpTransport-events.html

**Comment by youennf** [comment]
Actually, maybe this is redundant with RTCSctpTransport-events.html

**Comment by lgrahl** [comment]
Agree that it should be moved. It's mostly redundant but `RTCSctpTransport-events.html` doesn't test for `connecting`.

**Review by lgrahl — CHANGES_REQUESTED** [review]
I don't believe this test works without delaying the connection establishment (due to holding back ICE candidates).

**Comment by youennf** [comment]
> Agree that it should be moved. It's mostly redundant but `RTCSctpTransport-events.html` doesn't test for `connecting`.

Well it does test for connecting in the first test and for connected in the second test.
I am closing this PR in favor of RTCSctpTransport-events.html.

> I don't believe this test works without delaying the connection establishment (due to holding back ICE candidates).

Indeed!

**Pull request closed without merging**
