### PR TITLE
Replace ARIA reflection attribute ariaErrorMessageElement with ariaErrorMessageElements

### PR DESCRIPTION
**Pull request by rniwa**
This is WPT updates for https://github.com/w3c/aria/pull/1802

### CODE REVIEW

**Review by annevk — APPROVED** [review]
I think it would be good to add a historical test that asserts `ariaErrorMessageElement` is not implemented.

**Comment by rniwa** [comment]
> I think it would be good to add a historical test that asserts `ariaErrorMessageElement` is not implemented.

Good point. Adding that.

**Review by annevk — APPROVED** [review]
Thanks!

**Review by mrego — APPROVED** [review]
LGTM, thanks for updating the tests.

**Pull request merged**
