### PR TITLE
Merge w3ctestlib into web-platform-tests

### LINKED ISSUE #11034: Import w3ctestlib into WPT
cc/ @plinss 

As far as I can tell, w3ctestlib was only ever used by the CSS build system and Shepherd; given Shepherd isn't actively syncing any more, it seems like we could reasonably import w3ctestlib and fork it within the WPT repo without causing any issue.

This would allow us to make it start relying on the manifest, and therefore get rid of many of the differences in how the two find tests.

### PR DESCRIPTION
**Pull request by gsnedders**
**MUST BE MERGED WITH A MERGE COMMIT** (because `git-subtree`)

This fixes #11034.

Note that if you have submodules initialized, you'll be unable to do a checkout of this branch (as per what we had before when we monorepo'd):

```
error: The following untracked working tree files would be overwritten by checkout:
        css/tools/w3ctestlib/Groups.py
        css/tools/w3ctestlib/HTMLSerializer.py
        css/tools/w3ctestlib/Indexer.py
        css/tools/w3ctestlib/OutputFormats.py
        css/tools/w3ctestlib/Sources.py
        css/tools/w3ctestlib/Suite.py
        css/tools/w3ctestlib/Utils.py
        css/tools/w3ctestlib/__init__.py
        css/tools/w3ctestlib/catalog/catalog.xml
        css/tools/w3ctestlib/catalog/xhtml-lat1.ent
        css/tools/w3ctestlib/catalog/xhtml-special.ent
        css/tools/w3ctestlib/catalog/xhtml-symbol.ent
        css/tools/w3ctestlib/catalog/xhtml1-frameset.dtd
        css/tools/w3ctestlib/catalog/xhtml1-strict.dtd
        css/tools/w3ctestlib/catalog/xhtml1-transitional.dtd
        css/tools/w3ctestlib/catalog/xhtml11.dtd
        css/tools/w3ctestlib/templates/chapter-toc.tmpl
        css/tools/w3ctestlib/templates/implementation-report-TEMPLATE.data.tmpl
        css/tools/w3ctestlib/templates/index.content.tmpl
        css/tools/w3ctestlib/templates/index.htm.tmpl
        css/tools/w3ctestlib/templates/index.xht.tmpl
        css/tools/w3ctestlib/templates/indices.css
        css/tools/w3ctestlib/templates/reftest-toc.tmpl
        css/tools/w3ctestlib/templates/reftest.tmpl
        css/tools/w3ctestlib/templates/suitedata.tmpl
        css/tools/w3ctestlib/templates/test-toc.tmpl
        css/tools/w3ctestlib/templates/testinfo.data.tmpl
Please move or remove them before you switch branches.
Aborting
```

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/11072)

### CODE REVIEW

**Comment by jgraham** [comment]
Do we have any expectation of resyncing with upstream? Why import this as a subtree rather than just a copy?

**Comment by gsnedders** [comment]
@jgraham Probably not. But importing it as a subtree seems cleaner, even if we never pull again, IMO.

**Comment by gsnedders** [comment]
(Maybe we ought to move apiclient over to being a subtree too given it rarely gets updated…)

**Review by jgraham — APPROVED** [review]
Rubberstamp

**Pull request merged**
