### PR TITLE
Sync Mozilla tests as of 2017-06-28

### PR DESCRIPTION
**Pull request by dbaron**
This contains a single change, by @emilio, already reviewed in [Mozillla bug 1372056](https://bugzilla.mozilla.org/show_bug.cgi?id=1372056).

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247973206)

# Firefox (nightly) #
Testing web-platform-tests at revision 72c794c247a011bbbadae3a10001f40ec2d7501e
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6357/css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/text-decoration-propagation-dynamic-001.html">/css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/text-decoration-propagation-dynamic-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247973209)

# Sauce (safari) #
Testing web-platform-tests at revision 72c794c247a011bbbadae3a10001f40ec2d7501e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6357/css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/text-decoration-propagation-dynamic-001.html">/css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/text-decoration-propagation-dynamic-001.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247973223)

# Chrome (unstable) #
Testing web-platform-tests at revision 72c794c247a011bbbadae3a10001f40ec2d7501e

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247973224)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 72c794c247a011bbbadae3a10001f40ec2d7501e

**Comment by jgraham** [comment]
@dbaron The lint is failing with:

css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/text-decoration-propagation-dynamic-001.html: Reference test with a non-existent 'match' relationship reference: 'text-decoration-propagation-dymanic-001-ref.html' (NON-EXISTENT-REF)

**Comment by dbaron** [comment]
@emilio fixed that, and I updated the PR with a newer import with that fix.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
