### PR TITLE
Add feature policy tests for generic sensors

### PR DESCRIPTION
**Pull request by Honry**
Fix https://github.com/w3c/web-platform-tests/issues/8417

### CODE REVIEW

**Comment by Honry** [comment]
@alexshalamov, @pozdnyakov, PTAL.

**Review by pozdnyakov — APPROVED** [review]
lgtm, thanks!

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21190)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/308858952)

**Review by anssiko — APPROVED** [review]

**Comment by Honry** [comment]
Thanks @anssiko and @pozdnyakov, merging it.

**Pull request merged**
