### PR TITLE
WebKit export of https://bugs.webkit.org/show_bug.cgi?id=240563

### PR DESCRIPTION
**Pull request by mrego**
The original patch is available on the following PR:
https://github.com/WebKit/WebKit/pull/1166

### CODE REVIEW

**Comment by annevk** [comment]
Pre-existing issue, but it seems a little odd to test ARIA in `dom/` as it's not defined in the DOM Standard.

**Comment by mrego** [comment]
> Pre-existing issue, but it seems a little odd to test ARIA in `dom/` as it's not defined in the DOM Standard.

I guess we could move this test somewhere else in a separated PR.

**Review by nt1m — APPROVED** [review]
Reviewed by @rniwa in https://github.com/WebKit/WebKit/pull/1166

**Comment by mrego** [comment]
> Pre-existing issue, but it seems a little odd to test ARIA in `dom/` as it's not defined in the DOM Standard.

Addressing this in https://github.com/web-platform-tests/wpt/pull/34299.

**Pull request merged**
