### PR TITLE
Test DOM's XPath interfaces

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by lukebjerring — APPROVED** [review]
Did you manually update the IDL? Will it match reffys next scrape?

**Comment by foolip** [comment]
@lukebjerring no I cherry-picked the first commit from https://github.com/web-platform-tests/wpt/pull/18735.

**Comment by foolip** [comment]
When putting this together I noticed some failures in Chrome. Waiting for all results (https://github.com/web-platform-tests/wpt.fyi/issues/1458) to check if any of the new subtests fail in all browsers. If so, those subtests are ones we possibly should avoid adding.

**Comment by foolip** [comment]
Alright, https://wpt.fyi/results/dom/idlharness.window.html%3Fexclude=Node?run_id=305000004&run_id=301020003&run_id=309960002 shows that there's only one consistently failing subtest: "XPathNSResolver must be primary interface of document.createNSResolver(document.body)"

That seems to be because the `XPathNSResolver` (callback) interface object isn't exposed in Chrome, Firefox or Safari. It seems to have been exposed in EdgeHTML, but we're not testing that in WPT's CI anymore.

**Comment by foolip** [comment]
No, wait, this looks like it could be an idlharness.js bug. https://heycam.github.io/webidl/#legacy-callback-interface-object says "For every callback interface that is exposed in a given Realm and on which constants are defined, a corresponding property exists on the Realm's global object." but this callback interface has no constants. Still the failing subtest seems to assert that the interface object should be exposed.

**Comment by foolip** [comment]
The problem is around here:
https://github.com/web-platform-tests/wpt/blob/9fa0c4a378b96e242adda6d1f921fa2fb7ed4abe/resources/idlharness.js#L2701-L2720

**Review by gsnedders — APPROVED** [review]
Oh, is the lack of the failure in the existing tentative test because someone (read: me) wrote XPathResolver instead of XPathNSResolver?

On the whole, given this is correcting an obvious test bug, and the bug is in idlharness.js, and otherwise just moving this interface around, I'd be happy to just land this as is and deal with the idlharness.js issue as a followup.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/wpt/issues/18827 and commented out the line adding a XPathNSResolver object. @gsnedders does that seem OK?

**Comment by gsnedders** [comment]
Yes.

**Comment by gsnedders** [comment]
(I'll let you land this, I dunno if you were just planning on squashing the entire thing including the autofoolip.)

**Comment by foolip** [comment]
I'll squash, can't be bothered to turn into two nice commits.

**Pull request merged**
