### PR TITLE
[css-flexbox] Use /fonts/ahem.css over similar support/ahem.css

### PR DESCRIPTION
**Pull request by foolip**
As a drive-by fix, make use of XHTML-style `<link />` markup more
consistent within tests, usually dropping it.

### CODE REVIEW

**Comment by foolip** [comment]
@davidsgrogan can you take a look? I didn't realize when merging https://chromium-review.googlesource.com/c/chromium/src/+/2585929 how exactly I'd need to fix the lint and that cleaning it up after would seem prudent. If the lint had been working in Chromium CQ it would have made more sense to do these changes in the CL of course.

**Comment by foolip** [comment]
I've also sent https://github.com/web-platform-tests/wpt/pull/26855 based on this to clean up the stuff left in vendor-imports, to make moving that easier.

**Review by mrego — APPROVED** [review]
LGTM.

**Comment by foolip** [comment]
Since I based https://github.com/web-platform-tests/wpt/pull/26855 on this and @mrego kindly reviewed I'll go ahead and merge. @davidsgrogan please shout if I broke something with this! :)

**Comment by davidsgrogan** [comment]
LGTM.

In case it helps narrow down the missing chromium lint error about ahem.css: the chromium git-cl upload presubmit check DID tell me that I shouldn't add a copy of Ahem.ttf, which I initially blithely tried to do.

**Pull request merged**
