### PR TITLE
changed SyntaxError out for TypeError() per bug request #2256

### PR DESCRIPTION
**Pull request by fylith**
Hi, I changed the SyntaxError to new TypeError() like requested.

### CODE REVIEW

**Comment by Ms2ger** [comment]
I don't believe this is correct for all these values, only for the values that contain code points over 255.

**Comment by jdm** [comment]
I would recommend choosing which error to expect by adding a loop in each method that checks each string character using charCodeAt.

**Comment by fylith** [comment]
Ok i will work on it and send a pull request again after i fix it. Thanks!

**Comment by jdm** [comment]
If you make further commits to this branch and push them, they'll show up in this existing pull request. That's the recommended workflow :)

**Comment by jdm** [comment]
@fylith Any progress?

**Comment by jdm** [comment]
Fixed by #2806.

**Pull request closed without merging**
