### PR TITLE
HTTP/1 status code tests

### PR DESCRIPTION
**Pull request by annevk**
For https://github.com/whatwg/fetch/issues/1142.

The expectations match Safari, which seems to have the most reasonable behavior. In part this might be due Safari rejecting HTTP/0.9 entirely at this point?

This still allows for some behavior that HTTP does not, such as `HTTP/1.1 9 OK`, but that might be hard to get rid of? (I.e., require three digits always.)

cc @ddragana

### CODE REVIEW

**Comment by MattMenke2** [comment]
Is there an associated proposed update to the fetch spec?

Think we need a test for something like 0200 (4 digit value that's less than 1000). I assume we want to reject those - seems safer to me, at least.

Also suggested:  negative numbers, 0xA, C8 (200 in hex without a leading 0x), numbers with a decimal (seems unlikely a browser will allow either, but best to be safe).

I guess this is not the best spot for a non-redirect 3xx with a location header (Assume we have tests for that case elsewhere, anyways).

Should we have a test without a status string?  While that's not the primary purpose of these tests, they do vary the status string and test it's parsed correctly.

**Comment by annevk** [comment]
I'm not sure yet how to specify "here's how browsers parse HTTP/1", but I would change Fetch to clearly define status as being within the range of 0 to 999, inclusive. And then use tests (as with 0x00) and the H/1 parsing issue to document the remainder for now.

**Comment by annevk** [comment]
Added the suggested tests. And yeah, redirects are best covered separately (I haven't looked to see if they are, but there must be some).

**Review by MattMenke2 — APPROVED** [review]
Looks good, thanks for pursuing this!

**Pull request merged**
