### PR TITLE
Added handling for tests with no AT steps

### PR DESCRIPTION
**Pull request by halindrome**
If a test has no steps for an associated ATTA, then the test
should report NOTRUN and move on.  This simple change enables that.

@joanmarie please review!

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235789178)

# Firefox (nightly) #
Testing web-platform-tests at revision c5c4d75561f17ba03eb938fe181358005d67f4b7
Using browser at version BuildID 20170524100215; SourceStamp 291a11111bdd05c5cd55dd552da4b1285ceba9b2
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235789179)

# Sauce (safari) #
Testing web-platform-tests at revision c5c4d75561f17ba03eb938fe181358005d67f4b7
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235789185)

# Chrome (unstable) #
Testing web-platform-tests at revision c5c4d75561f17ba03eb938fe181358005d67f4b7
Using browser at version 60.0.3107.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/235789186)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c5c4d75561f17ba03eb938fe181358005d67f4b7
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Review by joanmarie — APPROVED** [review]
Nice! This definitely solves the problem (not going into manual mode forcing the human running the test to declare "pass" or "fail" on a test that doesn't apply to the platform). And I like how the status and message shown after running a set of tests make it clear the test wasn't run and why.

When I generated the results report, however, I noticed a related cosmetic change that I *think* we might also want to make. I'll attach a screenshot. But the description in the meantime is this: If I test is run, the word "PASS" OR "FAIL" appears in the table row. I was expecting to see something similar for a skipped test, namely "NOTRUN" instead of "PASS" or "FAIL". Instead, I see "-" as the result and "NOTRUN" in the row above.

If this is the desired result, then never mind and please commit this change. Similarly, if this is not the desired result, but the fix has nothing to do with the code you're modifying here, then please commit your fix as we need it in place. BUT if the proper fix for the cosmetic issue is to solve the problem at hand slightly differently, it might be worth doing that now.

Regardless, thanks for doing this!!

**Comment by joanmarie** [comment]
This screenshot illustrates the cosmetic issue I described in my review:
not-run

**Comment by halindrome** [comment]
The output of wptreport in that case is actually correct.  It means "this whole test was not run" as opposed to "this subtest failed".  We cant report anything about subtests if the whole test was never started.

**Pull request merged**
