### PR TITLE
Moving WebDriver context tests from root directory to correct directory

### PR DESCRIPTION
**Pull request by jimevans**
No test changes, just moving to a more appropriate directory.

### CODE REVIEW

**Comment by whimboo** [comment]
I'm currently working on refactoring those tests too, with a lot of other changes on https://bugzilla.mozilla.org/show_bug.cgi?id=1455568. I have all of that already in place. It means that it would cost me a bit of work to rebase. Mind if I finish that on the mentioned bug? It will be done by end of next week.

**Comment by jimevans** [comment]
Don't mind at all. This has just bugged me for awhile, and it would be nice to get these tests moved out from the root directory. I can even close this PR and wait, if you like.

**Comment by whimboo** [comment]
That would be great, yes. My plan is to have it landed on our side by end of the week at latest.

**Comment by jimevans** [comment]
Closing this pull request and recreating.

**Comment by whimboo** [comment]
FYI this PR was closed in favor of PR #10938 which adjusted the location of all the tests.

**Pull request closed without merging**
