### PR TITLE
Fix referrer-policy setup for fetch

### PR DESCRIPTION
**Pull request by JuniorHsu**
Previous setup didn't pass the RP to fetch

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
I think this is a good test, but the test it replaces was also a good test. In particular, if the referrer policy passed to `fetch()` is the empty string (the default value), the fetching algorithm will pull the value from the request's client, which is the iframe's global object/document which does have a referrer policy, right? So as far as I can tell both should work.

**Comment by JuniorHsu** [comment]
> I think this is a good test, but the test it replaces was also a good test. In particular, if the referrer policy passed to `fetch()` is the empty string (the default value), the fetching algorithm will pull the value from the request's client, which is the iframe's global object/document which does have a referrer policy, right? So as far as I can tell both should work.

For the test I replaces, both browsers do *not* work as you said, which is noted in fetch 4.1.2.5
However, it distracts the spec we want to modify here. We might need another issue for Referrer-Policy to address this.

**Comment by annevk** [comment]
How about we leave the test in and file bugs against browsers? It does seem like something that ought to be fixed.

**Comment by JuniorHsu** [comment]
I leave both tests in this version. Two observations:
(a) We load too many iframes in one test, which could cause TIME-OUT
(b) In current Firefox,  |submit.click();| doesn't work sometimes for the form POST test.

**Comment by annevk** [comment]
For a) should we split the test somehow then? I could merge this first and then we can do that separately though. Not sure what the problem could be with b).

**Comment by JuniorHsu** [comment]
Let's merge. Thanks!

**Pull request merged**
