### PR TITLE
Test harness and docs improvements for ShadowRealm testing

### PR DESCRIPTION
**Pull request by ptomato**
We allow running tests in ShadowRealm scopes. This PR contains some improvements that help adapt existing tests to run in a ShadowRealm:

- `GLOBAL.isShadowRealm()` already exists; this documents it.
- Many tests use `fetch()` to import test data from a JSON file. `fetch()` isn't exposed in ShadowRealm globals. This adds a new `fetch_json()` function to the test harness, which works like `fetch()` but can only fetch JSON data, and decodes it before returning.
- The 'variant' mechanism works by appending search params to the URL, but `location` is not exposed in ShadowRealm globals. This adds a dummy `location` object to ShadowRealm scopes with a `search` property, so that ShadowRealm tests can be subsetted by variant.
- The `step_timeout()` and `step_wait_func()` functionality in the test harness relies on `setTimeout()`, which isn't exposed in ShadowRealm globals. This adds a fake `setTimeout()` to ShadowRealm scopes so that this timed test functionality can work in ShadowRealm tests.

### CODE REVIEW

**Comment by ptomato** [comment]
@foolip Thanks. I've opened [RFC 177](https://github.com/web-platform-tests/rfcs/pull/177/files?short_path=3df08f9#diff-3df08f98c18021149e6f02327e0ac1687e3501bb5251ecca865328bb2cd022b3) for this.

**Comment by ptomato** [comment]
The RFC has passed, so I think this is ready for review now!

**Review by Ms2ger — APPROVED** [review]
I'll leave another day in case anyone has comments, but the code looks good to me

**Comment by ptomato** [comment]
Thanks for the review @Ms2ger. Looks like no other comments.

**Pull request merged**
