### PR TITLE
Add DOCTYPE for indent-outdent-after-closing-editable-dialog-element.…

### PR DESCRIPTION
**Pull request by WeizhongX**
…html

### CODE REVIEW

**Comment by masayuki-nakano** [comment]
Although the testcase does not depend on `<!doctype html>`, I don't think that crashtests should be kept clean. I ported the testcase to WPT as-is as far as possible.

**Comment by WeizhongX** [comment]
Thank you. We recently added a presubmit check in chromium, and made it an error for new tests that do not have DOCTYPE. Developers could add '-quirk' to file name to bypass this check. (Should we do this for this test?)

I know we have not get agreement on this. But could we? I am involving more ppl for a discussion. If we think we should not adopt any rules about this, we can skip this check for WPTs.

**Comment by WeizhongX** [comment]
masayuki-nakano@, you said "I ported the testcase to WPT as-is as far as possible." Can you explain where you ported this from a little bit? Thanks!

**Comment by masayuki-nakano** [comment]
> masayuki-nakano@, you said "I ported the testcase to WPT as-is as far as possible." Can you explain where you ported this from a little bit? Thanks!

https://bugzilla.mozilla.org/show_bug.cgi?id=1771812

> Thank you. We recently added a presubmit check in chromium, and made it an error for new tests that do not have DOCTYPE. Developers could add '-quirk' to file name to bypass this check. (Should we do this for this test?)
> 
> I know we have not get agreement on this. But could we? I am involving more ppl for a discussion. If we think we should not adopt any rules about this, we can skip this check for WPTs.

How about to add the rules to ignore `<!doctype html>` error in `*-crash.html` and `crashtests/*.html`?
https://web-platform-tests.org/writing-tests/crashtest.html

**Pull request closed without merging**
