### PR TITLE
WebCryptoAPI: add remaining CFRG algorithms to wrapKey_unwrapKey

### PR DESCRIPTION
**Pull request by panva**
Vectors in this test file do not add new failures unless the algorithm is supported. I've verified the results in Node.js where all four algorithms from https://wicg.github.io/webcrypto-secure-curves/ are supported.

<details>
<summary>Details</summary>

```
[PASS] Can unwrap Ed25519 private key non-extractable keys using jwk and AES-CBC
[PASS] Can unwrap Ed25519 private key non-extractable keys using jwk and AES-CTR
[PASS] Can unwrap Ed25519 private key non-extractable keys using jwk and AES-GCM
[PASS] Can unwrap Ed25519 private key non-extractable keys using jwk and RSA-OAEP
[PASS] Can unwrap Ed448 private key non-extractable keys using jwk and AES-CBC
[PASS] Can unwrap Ed448 private key non-extractable keys using jwk and AES-CTR
[PASS] Can unwrap Ed448 private key non-extractable keys using jwk and AES-GCM
[PASS] Can unwrap Ed448 private key non-extractable keys using jwk and RSA-OAEP
[PASS] Can unwrap X25519 private key non-extractable keys using jwk and AES-CBC
[PASS] Can unwrap X25519 private key non-extractable keys using jwk and AES-CTR
[PASS] Can unwrap X25519 private key non-extractable keys using jwk and AES-GCM
[PASS] Can unwrap X25519 private key non-extractable keys using jwk and RSA-OAEP
[PASS] Can unwrap X448 private key non-extractable keys using jwk and AES-CBC
[PASS] Can unwrap X448 private key non-extractable keys using jwk and AES-CTR
[PASS] Can unwrap X448 private key non-extractable keys using jwk and AES-GCM
[PASS] Can unwrap X448 private key non-extractable keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using pkcs8 and AES-KW
[PASS] Can wrap and unwrap Ed25519 private key keys as non-extractable using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 private key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed25519 private key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed25519 private key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed25519 private key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 private key keys using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap Ed25519 private key keys using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap Ed25519 private key keys using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap Ed25519 private key keys using pkcs8 and AES-KW
[PASS] Can wrap and unwrap Ed25519 private key keys using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 public key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed25519 public key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed25519 public key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed25519 public key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed25519 public key keys using spki and AES-CBC
[PASS] Can wrap and unwrap Ed25519 public key keys using spki and AES-CTR
[PASS] Can wrap and unwrap Ed25519 public key keys using spki and AES-GCM
[PASS] Can wrap and unwrap Ed25519 public key keys using spki and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap Ed448 private key keys as non-extractable using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 private key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed448 private key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed448 private key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed448 private key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 private key keys using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap Ed448 private key keys using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap Ed448 private key keys using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap Ed448 private key keys using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 public key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap Ed448 public key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap Ed448 public key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap Ed448 public key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap Ed448 public key keys using spki and AES-CBC
[PASS] Can wrap and unwrap Ed448 public key keys using spki and AES-CTR
[PASS] Can wrap and unwrap Ed448 public key keys using spki and AES-GCM
[PASS] Can wrap and unwrap Ed448 public key keys using spki and RSA-OAEP
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using jwk and AES-CBC
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using jwk and AES-CTR
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using jwk and AES-GCM
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and AES-KW
[PASS] Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap X25519 private key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap X25519 private key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap X25519 private key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap X25519 private key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X25519 private key keys using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap X25519 private key keys using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap X25519 private key keys using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap X25519 private key keys using pkcs8 and AES-KW
[PASS] Can wrap and unwrap X25519 private key keys using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap X25519 public key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap X25519 public key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap X25519 public key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap X25519 public key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X25519 public key keys using spki and AES-CBC
[PASS] Can wrap and unwrap X25519 public key keys using spki and AES-CTR
[PASS] Can wrap and unwrap X25519 public key keys using spki and AES-GCM
[PASS] Can wrap and unwrap X25519 public key keys using spki and RSA-OAEP
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using jwk and AES-CBC
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using jwk and AES-CTR
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using jwk and AES-GCM
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using pkcs8 and AES-KW
[PASS] Can wrap and unwrap X448 private key keys as non-extractable using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap X448 private key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap X448 private key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap X448 private key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap X448 private key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X448 private key keys using pkcs8 and AES-CBC
[PASS] Can wrap and unwrap X448 private key keys using pkcs8 and AES-CTR
[PASS] Can wrap and unwrap X448 private key keys using pkcs8 and AES-GCM
[PASS] Can wrap and unwrap X448 private key keys using pkcs8 and AES-KW
[PASS] Can wrap and unwrap X448 private key keys using pkcs8 and RSA-OAEP
[PASS] Can wrap and unwrap X448 public key keys using jwk and AES-CBC
[PASS] Can wrap and unwrap X448 public key keys using jwk and AES-CTR
[PASS] Can wrap and unwrap X448 public key keys using jwk and AES-GCM
[PASS] Can wrap and unwrap X448 public key keys using jwk and RSA-OAEP
[PASS] Can wrap and unwrap X448 public key keys using spki and AES-CBC
[PASS] Can wrap and unwrap X448 public key keys using spki and AES-CTR
[PASS] Can wrap and unwrap X448 public key keys using spki and AES-GCM
[PASS] Can wrap and unwrap X448 public key keys using spki and RSA-OAEP
```

</details>

Recommend to hide whitespace when reviewing.

### CODE REVIEW

**Comment by panva** [comment]
I don't understand the failures, fyi.wpt results look the same for both Firefox and Chrome.

**Comment by panva** [comment]
I don't quite understand how this change affects the stability 🤷

**Comment by panva** [comment]
The "unstable" tests in `wpt-chrome-dev-stability` and `wpt-firefox-nightly-stability` are not even in the regular WPT result set. I suspect concurrency and modification of vector data is at play but I really can't find it. It's not introduced by this PR.

**Comment by javifernandez** [comment]
> The "unstable" tests in `wpt-chrome-dev-stability` and `wpt-firefox-nightly-stability` are not even in the regular WPT result set. I suspect concurrency and modification of vector data is at play but I really can't find it. It's not introduced by this PR.

There is a bug  / proposal in Chrome that might be related. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1379179

**Comment by panva** [comment]
Nah, it's the `wrappingIsPossible` function which checks that the thing to wrap is `length % 8 === 0`. The generated keys have length variety in them which is why when repeat 10 times sometimes there's bound to be a mod 8 === 0 length key generated for AES-KW to wrap. Then this function decides that a key is wrapped or not and that generates an extra result.

**Comment by panva** [comment]
I've pushed the possibility check to the individual tests, this means that the number of generated results will now be consistent and instability is actually going to be only triggered if the "sometimes tested" vector starts failing.

**Review by twiss — APPROVED** [review]
:+1: Thanks!

**Pull request merged**
