### PR TITLE
Update hashchange/popstate event tests

### PR DESCRIPTION
**Pull request by foolip**
Spec: https://html.spec.whatwg.org/#history-traversal

### CODE REVIEW

**Comment by foolip** [comment]
w3c-test:mirror

**Comment by foolip** [comment]
@sideshowbarker, any idea why this isn't showing up in http://w3c-test.org/submissions/?

**Comment by foolip** [comment]
w3c-test:mirror

**Comment by foolip** [comment]
FWIW, the https://w3c-test.org/sync.py webhook has a red warning triange in the repo admin view. Related?

**Comment by foolip** [comment]
Conclusion from running these tests in Chrome, Edge, Firefox and Safari:
* Neither event has `bubbles` set to true in Chrome, Edge or Safari, but `bubbles` is true for both events (matching https://html.spec.whatwg.org/#history-traversal) in Firefox.
* For all browsers, `cancelable` is false for hashchange, which makes sense and matches the spec.
* For Chrome and Firefox, `cancelable` is true for popstate, which doesn't appear to be per spec.

**Comment by foolip** [comment]
OK, now ready to review together with spec change: https://github.com/whatwg/html/pull/3737

**Review by annevk — APPROVED** [review]

**Comment by foolip** [comment]
@cdumez @youennf FYI, I'm fixing the cancelable popstate event in https://chromium-review.googlesource.com/c/chromium/src/+/1087047, which will leave WebKit as the only engine where that event is cancelable. Would you like me to file a bug, or can either of you quickfix it?

**Comment by cdumez** [comment]
@foolip I will try and quick fix it today. Thanks for the heads up.

**Pull request merged**
