### PR TITLE
Removed test_spin_event_loop from element_click bubbling.py test suite

### PR DESCRIPTION
**Pull request by julianrkung**
test_spin_event_loop is designed to test step 9 of [element click](https://w3c.github.io/webdriver/#element-click)
> Wait until the user agent event loop has spun enough times to process the DOM events generated by the previous step.

This step can (and in my opinion should) be interpreted as the handling of all current events, meaning that the algorithm should proceed without waiting for the finishing of (in this case non-blocking) actions scheduled to occur in the future. 

Interestingly enough, Firefox also fails this test on my local machine if the setTimeout delay is increased to 250+, indicating that they are passing this test without being truly spec compliant (if the definition of step 9 in the spec is interpreted as the completion of all future actions triggered by this event as well). 

Therefore, since no webdriver is truly spec-compliant in the way this test is attempting to validate, and that this test arguably tests for adherence to unnecessary behavior (waiting for future events) I propose its deletion. In lieu of its deletion, it appears obvious to me at the very least that the test's setTimeout delay must be increased significantly to truly test for spec compliance if we decide to interpret step 9 to include future events.

Thoughts and discussion on interpreting step 9 of element click (or other ways to modify the test) are welcome and appreciated.

### CODE REVIEW

**Review by jgraham — CHANGES_REQUESTED** [review]
My interpretation of this is that the `setTimeout` should be removed, but otherwise the test is valid; I think the intent of the spec is that event handlers triggered by the click have all been processed but not that event scheduled from those handlers are processed. But there may be compatibility concerns here that require us to process at least some timers before returning. In that case the spec needs to be clearer.

In general just deleting tests rather than fixing them is not the correct approach.

**Comment by julianrkung** [comment]
Thanks for the advice regarding deleting the test! I did consider removing the `setTimeout`, but then the test would be identical to the test above it, `test_click_event_bubbles_to_parents`. Sorry I should've anticipated and mentioned that point.

**Comment by JohnChen0** [comment]
Would it worth keeping the setTimeout, but change the timeout value to 0? The spec doesn't seem very clear, but I think it would make sense to ensure that at least all the immediately deferred async calls are done.

**Comment by whimboo** [comment]
> Would it worth keeping the setTimeout, but change the timeout value to 0? The spec doesn't seem very clear, but I think it would make sense to ensure that at least all the immediately deferred async calls are done.

It has been agreed that this is the right solution and https://github.com/web-platform-tests/wpt/pull/19585 got merged with this change. So this PR is no longer needed.

**Pull request closed without merging**
