### PR TITLE
HTML: remove nonsense JSON resources

### PR DESCRIPTION
**Pull request by annevk**
Pretty sure we don't have a use for these.

### CODE REVIEW

**Comment by zcorpan** [comment]
```
$ find . -name "contains.json"
./html/webappapis/scripting/events/contains.json
./html/webappapis/scripting/event-loops/contains.json
./html/webappapis/scripting/processing-model-2/contains.json
./html/webappapis/system-state-and-capabilities/the-navigator-object/contains.json
./html/semantics/sections/headings-and-sections/contains.json
./html/semantics/forms/form-control-infrastructure/contains.json
./html/semantics/forms/constraints/contains.json
./html/semantics/forms/introduction-1/contains.json
./html/semantics/forms/form-submission-0/contains.json
./html/semantics/forms/attributes-common-to-form-controls/contains.json
./html/semantics/forms/the-input-element/contains.json
./html/semantics/scripting-1/the-script-element/contains.json
./html/semantics/tabular-data/the-table-element/contains.json
./html/semantics/tabular-data/processing-model-1/contains.json
./html/semantics/links/linktypes/contains.json
./html/semantics/links/downloading-resources/contains.json
./html/semantics/embedded-content/the-canvas-element/contains.json
./html/semantics/embedded-content/the-img-element/contains.json
./html/semantics/embedded-content/image-maps/contains.json
./html/semantics/embedded-content/media-elements/contains.json
./html/semantics/interactive-elements/the-dialog-element/contains.json
./html/semantics/interactive-elements/commands/contains.json
./html/semantics/document-metadata/the-meta-element/contains.json
./html/browsers/history/the-location-interface/contains.json
./html/browsers/windows/nested-browsing-contexts/contains.json
./html/browsers/windows/auxiliary-browsing-contexts/contains.json
./html/browsers/browsing-the-web/unloading-documents/contains.json
./html/browsers/browsing-the-web/history-traversal/contains.json
./html/browsers/offline/introduction-4/contains.json
./html/browsers/offline/manifests/contains.json
./html/dom/elements/content-models/contains.json
./html/dom/elements/element-definitions/contains.json
./html/dom/elements/global-attributes/contains.json
./html/dom/elements/wai-aria/contains.json
./html/syntax/parsing/contains.json
./html/syntax/writing/elements-0/contains.json
./html/syntax/writing/text/contains.json
./html/infrastructure/common-microsyntaxes/numbers/contains.json
./html/infrastructure/common-microsyntaxes/dates-and-times/contains.json
./html/infrastructure/common-dom-interfaces/collections/contains.json
```

it seems these were added in 2012 by @darobin

**Comment by annevk** [comment]
Removed those too.

**Comment by darobin** [comment]
Yeah, I have no idea what they were but they look like artifacts from a big import of tests or something like that.

**Comment by Ms2ger** [comment]
They were added when @darobin created the directory tree in https://github.com/web-platform-tests/wpt/commit/818bcab4ba58d2bc8dba94276c8b944c76570a19. I doubt they were ever used after that.

**Review by jgraham — APPROVED** [review]

**Pull request merged**
