### PR TITLE
 [docs] Incorporate wptserve documentation 

### PR DESCRIPTION
**Pull request by jugglinmike**
In gh-14648, @gsnedders wrote

> We still have some things in `tools/wptserve/docs/`, mostly API docs. Given
> we're now using Sphinx, I feel like we should put them somewhere on WPT.org,
> even if not directly linked from the main page (some infrastructure
> development section on something).

The module references in the wptserve documentation are currently not
functioning in the wptserve-specific builds process (i.e. running `make html`
from `/tools/wptserve/docs/`. They've been failing since the `tools` directory
was formally included in this repository (via 7ce469d1c4):

    tools/wptserve/docs/stash.rst:27: WARNING: py:mod reference target not found: stash

This patch does not fix that problem, but it does fix it for the main
documentation build process in `/docs/`.

The patch also enables "nit-picky" mode to make things more strict.

Technical details (from the relevant commit):

While Sphinx is capable of including the contents of files which exist
outside of the documentation root (via the `include` directive), it
interprets such text in the context of the including file. That makes
the mechanism inappropriate for including documentation that references
still other files using relative paths.

To address this, create a symbolic link to the `wptserve` source
directory. Fix or ignore infractions in the newly-incorporated files.

### CODE REVIEW

**Review by Hexcles — APPROVED** [review]
LGTM

**Review by gsnedders — APPROVED** [review]
While we've generally avoided symlinks within WPT because of lack of support on Windows; however, I think just within the Sphinx build system that isn't such a problem, so I have no problem with using symlinks here.

**Comment by jugglinmike** [comment]
Thanks @gsnedders. [We recently took steps to disallow symlinks generally](https://github.com/web-platform-tests/wpt/pull/17315), but the one used here is created by the build process and not checked in to the repository. If someone attempts to build the site from an unsupported platform, this will hopefully make the problem more apparent.

I'll merge this myself.

**Comment by jugglinmike** [comment]
Also, apologies to @jgraham and @sideshowbarker for removing the request for their review. This wasn't intentional; there may be a race condition with @wpt-pr-bot.

**Pull request merged**
