### PR TITLE
XHR: correct 303 redirect logic

### PR DESCRIPTION
**Pull request by annevk**
And add a relevant case for it.

### CODE REVIEW

**Comment by jdm** [comment]
Bringing over some Matrix discussion as well:
```
annevk: the 301/302 POSTs with explicit Content-Type that isn't safelisted - why should they be network errors?
annevk: my read of the spec is that the redirection will see take step 11 of https://fetch.spec.whatwg.org/#ref-for-concept-http-redirect-fetch and change the POST to a GET and remove the body, so why should the resulting cross-origin request trigger a network error?
```

**Comment by annevk** [comment]
Thank you! I think I've now addressed that and it indeed changes the results in Chrome and Firefox even more.

**Review by jdm — APPROVED** [review]

**Comment by JuniorHsu** [comment]
> Bringing over some Matrix discussion as well:
> 
> ```
> annevk: the 301/302 POSTs with explicit Content-Type that isn't safelisted - why should they be network errors?
> annevk: my read of the spec is that the redirection will see take step 11 of https://fetch.spec.whatwg.org/#ref-for-concept-http-redirect-fetch and change the POST to a GET and remove the body, so why should the resulting cross-origin request trigger a network error?
> ```

@annevk I see the network request is blocked in preflight request with the console error
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www2.web-platform.test:8000/xhr/resources/corsenabled.py. (Reason: header ‘content-type’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```
Therefore, we don't send the POST request and have no chance to know its response code, i.e., 302 POST->GET redirect.

**Comment by annevk** [comment]
@JuniorHsu I'm not sure how that happens though as the initial request is not cross-origin. By the time it goes cross-origin the `Content-Type` header should already have been removed.

**Comment by JuniorHsu** [comment]
@anneke Ah, you're right. I'll file another bug to address this.

**Pull request merged**
