### PR TITLE
Update to more recent versions of hyper libraries

### PR DESCRIPTION
**Pull request by arenevier**
Chrome wants to enable support for websocket over h2. In order to add
that support to wpt http2 server, we first need to update to update
hyper to a version that supports SETTINGS_ENABLE_CONNECT_PROTOCOL.

That support was added in January 2019, so we need versions at least as
recent. Since python 2.7 support was dropped in September 2020, we can't
take the very last versions. So we are taking the latest stable versions
before September.

Those are version 5.2.0 for hyperframe and version 3.2.0 for hyper-h2.
For hpack, that would be version 3.0.0, which is already the current
version.

### CODE REVIEW

**Comment by arenevier** [comment]
@ricea

**Comment by ricea** [comment]
lgtm (but I didn't actually review the upstream code changes, since I assume they were reviewed upstream).

The bot failures appear to be unrelated to the PR.

**Review by stephenmcgruer — COMMENTED** [review]
Confirmed that these appear to be hyperframe-5.2.0 and h2-3.2.0 (by checking out the PR, downloading the related source, and confirming no diffs. There were a few additional files for h2-3.2.0 that appear not to have been included here, but they are all test files or unrelated, e.g. travis files).

Can I ask what other changes will be following this library upgrade? Is there a design doc or one-pager (if the changes are big enough to warrant one)?

**Comment by arenevier** [comment]
> Can I ask what other changes will be following this library upgrade? Is there a design doc or one-pager (if the changes are big enough to warrant one)?

I have my work in progress available at https://chromium-review.googlesource.com/c/chromium/src/+/2508794/

The main two parts are the websocket handshake: https://chromium-review.googlesource.com/c/chromium/src/+/2508794/2/third_party/pywebsocket3/src/mod_pywebsocket/handshake/h2.py

and those changes in server.py
 https://chromium-review.googlesource.com/c/chromium/src/+/2508794/2/third_party/blink/tools/blinkpy/third_party/wpt/wpt/tools/wptserve/wptserve/server.py

Feel free to give feedback on that design.

**Review by stephenmcgruer — APPROVED** [review]
Thanks, appreciate the context :). Heads up that such a change may require an RFC (https://github.com/web-platform-tests/rfcs) given it changes the capabilities of wptserve, but it seems reasonable at a high level to me.

LGTM.

**Comment by stephenmcgruer** [comment]
Note: This requires CODEOWNER approval, so ping @jgraham for that.

**Review by jgraham — APPROVED** [review]
@stephenmcgruer should definitely be a codeowner for this stuff :)

**Pull request merged**
