### PR TITLE
Changes due to reviewing tests that fail in FF/Chrome/Edge

### PR DESCRIPTION
**Pull request by gregwhitworth**
As stated in #6419 I reviewed the tests that were failing in all UAs. The only modifications made are the following:

- **flexbox_interactive_paged-overflow-2.html:** Simply clarified the text a bit as it was a bit misleading IMO. It's a valid failure in all UAs.
- **flex-minimum-width-flex-items-001.xht:** Updated the test to reflect the update of the spec, as it's testing the transferred size and this only checks the cross-axis so I adjusted the test accordingly to accomplish the spirit of the test. Additionally, it was setting a definite width on the flex container and intrinsic minimums are only triggered when `min-width|height` are set. So modified that as well.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248155185)

# Firefox (nightly) #
Testing web-platform-tests at revision 3d990a5508f26b8aa19f2574402e891c4ba54bda
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248155186)

# Sauce (safari) #
Testing web-platform-tests at revision 3d990a5508f26b8aa19f2574402e891c4ba54bda
Using browser at version 10.0
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248155192)

# Chrome (unstable) #
Testing web-platform-tests at revision 3d990a5508f26b8aa19f2574402e891c4ba54bda
Using browser at version 61.0.3141.7 dev
Starting 10 test iterations

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248155193)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 3d990a5508f26b8aa19f2574402e891c4ba54bda

**Comment by gsnedders** [comment]
Why did this get closed?

**Pull request closed without merging**
