### PR TITLE
Cleanup reflection.js.

### PR DESCRIPTION
**Pull request by Ms2ger**
This is in preparation for some more work I'd like to do here, but that might take a while still.

### CODE REVIEW

**Comment by annevk** [comment]
@Ms2ger what's the status here?

**Comment by ayg** [comment]
@Ms2ger Do you want me to review this?

**Comment by annevk** [comment]
@ayg I suspect this is considered obsolete given that @Ms2ger closed it. My question probably triggered the "asking for review bot".

**Comment by ayg** [comment]
I didn't know if it was actually obsolete or he closed it for some other reason, which is why I asked.

**Pull request closed without merging**
