### PR TITLE
Remove a giant Hixie comment test.

### PR DESCRIPTION
**Pull request by jgraham**
This file has >8Mb of comments, bloats the repo, doesn't generate a
test and hasn't been touched since 2009. It's doing more harm than good.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5321)

### CODE REVIEW

**Comment by gsnedders** [comment]
I can review this insofar as, "yes, this removes the file". :)

@fantasai any thoughts? It'll still be history if anyone actually cares about reviving it.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218152324)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218152325)

**Comment by frivoal** [comment]
Not that I am particularly attached to this file, but since deleted files stay in the git history, the repo doesn't get any smaller by removing them. Is the goal to reduce the size of the checkout even if the repo itself doesn't shrink?

**Comment by jdm** [comment]
It makes importing the contents of the git repository without the git history smaller, which matters for projects like Gecko and Servo.

**Comment by jgraham** [comment]
@gsnedders Can we merge this now?

**Pull request merged**
