### PR TITLE
Adding filter and resize tests

### PR DESCRIPTION
**Pull request by xlai-o**
@junov 

These 3 tests are the remaining offscreencanvas tests (unrelated to commit()) that are in Chromium Layout tests but not in web-platform-tests. The two newly added tests for offscreencanvas.filter are reference tests.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204649209)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 4ac63e5736fd55fbba0b55123a6bc62f9c0b6c28
Using browser at version BuildID 20170222110216; SourceStamp 9a9db410f20781076424307265decbc5de1e94cc
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/filter/offscreencanvas.filter.w.html">/offscreen-canvas/filter/offscreencanvas.filter.w.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/filter/offscreencanvas.filter.html">/offscreen-canvas/filter/offscreencanvas.filter.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html">/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html</a></summary>


|                                                                    Subtest                                                                    | Results |
|-----------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                               | OK      |
| `Verify that resizing a 2d context resets its state.`                                                                                         | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is a 2d context attached.`                     | FAIL    |
| `Verify that resizing an OffscreenCanvas with a webgl context propagates the new size to its placeholder canvas asynchronously, upon commit.` | FAIL    |
| `Verify that setting the size of a 2d context to the same size it already had resets its state.`                                              | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is no context attached.`                       | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is a webgl context attached.`                  | FAIL    |
| `Verify that resizing an OffscreenCanvas with a 2d context propagates the new size to its placeholder canvas asynchronously, upon commit.`    | FAIL    |
| `Verify that drawImage uses the size of the committed frame as the intinsic size of a placeholder canvas.`                                    | FAIL    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204649211)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 4ac63e5736fd55fbba0b55123a6bc62f9c0b6c28
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
## Unstable results ##


|                           Test                           | Subtest |          Results           |
|----------------------------------------------------------|---------|----------------------------|
| `/offscreen-canvas/filter/offscreencanvas.filter.html`   |         | **FAIL: 9/10, PASS: 1/10** |
| `/offscreen-canvas/filter/offscreencanvas.filter.w.html` |         | **FAIL: 9/10, PASS: 1/10** |

## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/filter/offscreencanvas.filter.html">/offscreen-canvas/filter/offscreencanvas.filter.html</a></summary>


| Subtest |          Results           |
|---------|----------------------------|
|         | **FAIL: 9/10, PASS: 1/10** |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html">/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html</a></summary>


|                                                                    Subtest                                                                    | Results |
|-----------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                               | OK      |
| `Verify that resizing a 2d context resets its state.`                                                                                         | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is a 2d context attached.`                     | FAIL    |
| `Verify that resizing an OffscreenCanvas with a webgl context propagates the new size to its placeholder canvas asynchronously, upon commit.` | FAIL    |
| `Verify that setting the size of a 2d context to the same size it already had resets its state.`                                              | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is no context attached.`                       | FAIL    |
| `Verify that writing to the width and height attributes of an OffscreenCanvas works when there is a webgl context attached.`                  | FAIL    |
| `Verify that resizing an OffscreenCanvas with a 2d context propagates the new size to its placeholder canvas asynchronously, upon commit.`    | FAIL    |
| `Verify that drawImage uses the size of the committed frame as the intinsic size of a placeholder canvas.`                                    | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4999/offscreen-canvas/filter/offscreencanvas.filter.w.html">/offscreen-canvas/filter/offscreencanvas.filter.w.html</a></summary>


| Subtest |          Results           |
|---------|----------------------------|
|         | **FAIL: 9/10, PASS: 1/10** |

</details>
</details>

**Comment by junov** [comment]
The tests look good to me but you need to fix the lint errors and the flake.  Aren't you missing a "-ref" for worker test?

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4999)

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4999)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/207481052)

**Comment by xlai-o** [comment]
@junov I've converted the flaky filter tests to non-reference tests. Could you take a look at them to see if they can be merged?

**Comment by junov** [comment]
These are excellent!

**Pull request merged**
