### PR TITLE
Remove invalid reftest: grouping-li-reftest-no-list-owner-ref.html

### PR DESCRIPTION
**Pull request by emilio**
The test relies in the HTML element not generating a layout box, via using
display: contents.

It does generate it though, because display: contents gets blockified in the
root element[1].

Indeed, Gecko shows zero-counters, but it does so even without display: contents
on the body and html elements, because Gecko only checks whether it has a
containing ol/ul/dir/menu elements[2].

[1]: https://drafts.csswg.org/css-display-3/#transformations
[2]: http://searchfox.org/mozilla-central/rev/848c29538ab007fb95dc6cff194f0e3d3809613d/layout/generic/nsContainerFrame.cpp#1822

### CODE REVIEW

**Comment by emilio** [comment]
cc @domenic (who added the reftest)

**Comment by domenic** [comment]
Hmm. Is it then not possible for a `<li>` to have no ancestors that generate CSS boxes? If so we need to update the spec as well (see the bottom of https://html.spec.whatwg.org/#ordinal-value )

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision 4d3d3c8f3a2985202bd5b081e8cb3bd9eeb94e62
Using browser at version 58.0.3000.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision 4d3d3c8f3a2985202bd5b081e8cb3bd9eeb94e62
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
No tests run.

**Comment by emilio** [comment]
> Hmm. Is it then not possible for a <li> to have no ancestors that generate CSS boxes? If so we need to update the spec as well (see the bottom of https://html.spec.whatwg.org/#ordinal-value )

Yes, it's not possible as far as I know, this is a Gecko bug.

**Comment by domenic** [comment]
Great, thanks. In that case, test LGTM, and I'll update the spec.

**Pull request merged**
