### PR TITLE
Remove @danielweck as css-speech reviewer

### PR DESCRIPTION
**Pull request by foolip**
@danielweck has not accepted the org invite and thus cannot be assigned by @wpt-pr-bot.

### CODE REVIEW

**Comment by foolip** [comment]
@danielweck please speak up if this was an oversight. You should be able to see/accept the invite at https://github.com/web-platform-tests.

**Comment by foolip** [comment]
No word from Daniel yet, so I'd like to merge this. @zcorpan for review?

**Comment by danielweck** [comment]
Sorry, please go ahead and merge this PR. I am afraid I am not able to contribute :(

**Review by zcorpan — APPROVED** [review]

**Comment by foolip** [comment]
No worries, thanks Daniel for confirming!

**Pull request merged**
