### PR TITLE
Add streaming upload on redirect code tests.

### PR DESCRIPTION
**Pull request by yoichio**
whatwg/fetch specifies below but it was not tested:
> If actualResponse’s status is not 303, request’s body is non-null, and request’s body’s source is null, then return a network error.

https://github.com/whatwg/fetch/issues/1058 is discussing that and this PR adds such tests.

Because wpt H/1 server doesn't support streaming upload, this test is written over H/2.

### CODE REVIEW

**Review by yutakahirano — COMMENTED** [review]
Can we have a more meaningful PR name?

**Comment by yoichio** [comment]
Updated PR title.

**Comment by yutakahirano** [comment]
Please don't mark comments as resolved without doing anything (You may have different opinions - it's perfectly OK but in that case please express your opinion).

**Comment by yoichio** [comment]
I resolved comments and then uploaded the patch.
Since github doesn't have no good UX to compare diff unlike gerrit, I don't know how to use the github comment thread effectively.

**Comment by yutakahirano** [comment]
You can compare revisions, and I see my comments on the diff. Example: https://github.com/web-platform-tests/wpt/pull/28656/files/d7d70b34e7636c4d43166480ff8428c6c3fb9739..d86d0bd4841071f616b55a8b640b309de10932fb

**Comment by annevk** [comment]
Yeah, I started reviewing this and it seems that @yutakahirano's comments mostly still apply. I unresolved those that do.

**Comment by yoichio** [comment]
Updated the patch but I still don't understand how to view diff between a commented patch and current one on the github UI.
Only typing "https://github.com/web-platform-tests/wpt/pull/28656/files/<before>..<after>" by hand?

**Comment by annevk** [comment]
I'm not sure. My approach is generally that I go through the comments one-by-one and ensure I address them locally, then push the commit, and then check the comments again to make sure nothing was missed and resolve. (And sometimes leave a comment open if it needs further discussion.)

**Review by annevk — APPROVED** [review]
The only additional thing I could think of to test is that 303 semantics are actually followed, but we already have non-stream coverage of that so hopefully that suffices.

**Comment by yutakahirano** [comment]
> Updated the patch but I still don't understand how to view diff between a commented patch and current one on the github UI.
Only typing "https://github.com/web-platform-tests/wpt/pull/28656/files/"before".."after" " by hand?

Sorry, it seems outdated comments are not shown.

**Review by yutakahirano — APPROVED** [review]

**Pull request merged**
