### PR TITLE
Always pass --enable-chrome-logs for Chromedriver

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@Hexcles - WDYT? I pushed a full trigger run and had a poke through the logs to see if anything blew up; we definitely do get some additional logs but not a huge amount so maybe that's fine?

I think it would be nice for folks to get logs both (a) in the stability checks and (b) when running locally without them doing anything, we just need to balance it off against the risk of Chrome spamming our CI logs into submission :D.

**Comment by Hexcles** [comment]
This seems a bit noisy: https://community-tc.services.mozilla.com/tasks/YH7_UqpmRiSMONjq3GtPnA/runs/1/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FYH7_UqpmRiSMONjq3GtPnA%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log

The verbosity *might* be OK (I'm a bit on the fence here), but I'd like to at least tell Chrome logs apart from runner logs more easily, e.g. adding a prefix to logs (I know right now we can filter by "pid:" but that seems a bit brittle and not obvious). Perhaps we can put Chrome logs into a log file as an artifact instead?

**Comment by stephenmcgruer** [comment]
> The verbosity might be OK (I'm a bit on the fence here), but I'd like to at least tell Chrome logs apart from runner logs more easily, e.g. adding a prefix to logs (I know right now we can filter by "pid:" but that seems a bit brittle and not obvious). Perhaps we can put Chrome logs into a log file as an artifact instead?

I'm not sure if we want to do that, as it then becomes hard to find where one test ends and another begins (unless we also dump information on that to the log).

I think there's two main angles we want to cover here:

1. Developers tell us that looking at WPT CI logs are useless (especially for crashes) as they don't include anything from the browser.
1. Developers tell us that they want access to browser logs locally when running WPT.

If we think always-on is too spammy, then I would propose we go forward by turning this flag on for stability checks specifically (as they tend to be the most likely CI that a dev is looking at), and otherwise instruct developers to pass `--webdriver-args=--enable-chrome-logs` when running locally. (That may be worth wrapping in an easier to understand flag).

**Review by Hexcles — APPROVED** [review]
Thanks, Stephen! I'm convinced that we want browser logs included by default; in other words, I'm not worried about the verbosity any more.

Going back to my other point about interleaving two kinds of logs, I agree that splitting Chrome logs into a seperate file defeats the purpose, so it seems the best way is to prefix the runner logs and/or the browser logs, but I'm fine with leaving that as a future improvement.

**Comment by stephenmcgruer** [comment]
>  it seems the best way is to prefix the runner logs and/or the browser logs, but I'm fine with leaving that as a future improvement.

That would be done in `on_output` in `WebDriverServer` (`tools/wptrunner/wptrunner/webdriver_server.py`). It uses mozlog to log the output:

```
    def on_output(self, line):
        self.logger.process_output(self.pid,
                                   line.decode("utf8", "replace"),
                                   command=" ".join(self._cmd))
```

We'd probably have to change the data itself, by prefixing something to the `line.decode(...)` part, since mozlog doesn't give us more more flexibility there afaik.

**Pull request merged**
