### PR TITLE
Tests for ontouch* properties in GlobalEventHandlers

### PR DESCRIPTION
**Pull request by chong-z**
Fixing bug #2375 
Followed test suggestions here https://github.com/w3c/touch-events/issues/44
1. Mixed 'target0.ontouch*' with 'on_event' to check they both working
2. Checked 'in' and 'hasOwnProperty' between
- 'ontouchstart', 'ontouchmove', 'ontouchend', 'ontouchcancel'
- _GlobalEventHandlers_: window, HTMLElement.prototype, SVGElement.prototype, Document.prototype
- _Not GlobalEventHandler_: Element.prototype

Currently passed on **Firefox** and **Chrome Canary**
Not passed on **Safari**
Not tested on **Edge**

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/touch-events-reviewers.

**Comment by choniong** [comment]
Hi @jtangelder, can you take a look at this PR please? Thanks! (I saw your ID in [touch-events/OWNERS](https://github.com/w3c/web-platform-tests/blob/master/touch-events/OWNERS))

**Comment by jtangelder** [comment]
:+1: looks OK. Unfortunately I don't have the rights to merge this.

**Comment by choniong** [comment]
Thanks for the prompt review! @Ms2ger can you also take a look at this PR please? Thanks!

**Comment by choniong** [comment]
Hi @jdm can you take a look at this PR please? Thanks!

**Comment by Ms2ger** [comment]
Sorry for the delay

**Pull request merged**
