### PR TITLE
Add some ImageData constructor tests.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5124/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210581612)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 85f883ca126bdb2fd720721298da7bab0bdfeeb5
Using browser at version BuildID 20170312110221; SourceStamp 3154da520af568d4da3de62bc26fbf97a1317f51
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.bounds.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.bounds.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/210581616)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 85f883ca126bdb2fd720721298da7bab0bdfeeb5
Using browser at version 58.0.3029.14 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html</a></summary>


|               Subtest                | Results |                                                                                                                                      Messages                                                                                                                                      |
|--------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                      | OK      |                                                                                                                                                                                                                                                                                    |
| `ImageData has a usable constructor` | FAIL    | `assert_throws: function "function () { new ImageData(new Uint8ClampedArray(0), 1); }" threw object "IndexSizeError: Failed to construct 'ImageData': The input data has zero elements." that is not a DOMException INVALID_STATE_ERR: property "code" is equal to 1, expected 11` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.bounds.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.bounds.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5124/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.html">/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.html</a></summary>


|               Subtest                | Results | Messages |
|--------------------------------------|---------|----------|
|                                      | OK      |          |
| `ImageData has a usable constructor` | PASS    |          |

</details>
</details>

**Comment by nox** [comment]
LGTM.

**Pull request merged**
