### PR TITLE
Make sure CORS is enforced when 304 is handed to JavaScript

### PR DESCRIPTION
**Pull request by annevk**
Follow up to #1740.

### CODE REVIEW

**Comment by annevk** [comment]
@mnot this is that other thing that I thought was worth testing. All browsers already pass though, so it's not that interesting.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204894476)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 07f918ec11245f605bb30d882824c73e3c04d30e
Using browser at version BuildID 20170223110219; SourceStamp 32dcdde1fc64fc39a9065dc4218265dbc727673f
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5005/XMLHttpRequest/send-conditional.htm">/XMLHttpRequest/send-conditional.htm</a></summary>


|                        Subtest                         | Results |
|--------------------------------------------------------|---------|
|                                                        | OK      |
| `XMLHttpRequest: send() - conditional requests (date)` | PASS    |
| `XMLHttpRequest: send() - conditional requests (tag)`  | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5005/XMLHttpRequest/send-conditional-cors.htm">/XMLHttpRequest/send-conditional-cors.htm</a></summary>


|                Subtest                | Results |
|---------------------------------------|---------|
|                                       | OK      |
| `304 with appropriate CORS header`    | PASS    |
| `304 without appropriate CORS header` | PASS    |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204894478)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 07f918ec11245f605bb30d882824c73e3c04d30e
Using browser at version 58.0.3018.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5005/XMLHttpRequest/send-conditional.htm">/XMLHttpRequest/send-conditional.htm</a></summary>


|                        Subtest                         | Results |
|--------------------------------------------------------|---------|
|                                                        | OK      |
| `XMLHttpRequest: send() - conditional requests (date)` | PASS    |
| `XMLHttpRequest: send() - conditional requests (tag)`  | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5005/XMLHttpRequest/send-conditional-cors.htm">/XMLHttpRequest/send-conditional-cors.htm</a></summary>


|                Subtest                | Results |
|---------------------------------------|---------|
|                                       | OK      |
| `304 with appropriate CORS header`    | PASS    |
| `304 without appropriate CORS header` | PASS    |

</details>
</details>

**Comment by annevk** [comment]
@mnot do these tests look okay to you?

**Comment by mnot** [comment]
Think so.

**Pull request merged**
