### PR TITLE
Remove copyright year

### PR DESCRIPTION
**Pull request by annevk**
This would align with the WHATWG where we made a similar change recently.

If we do this I'm willing to PR https://github.com/html5lib/html5lib-python/blob/master/benchmarks/data/wpt/LICENSE.md as well.

cc @web-platform-tests/wpt-core-team

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]

**Comment by annevk** [comment]
Comparing with WHATWG, should we add `©` while here?

**Comment by foolip** [comment]
I was going to suggest adding ©, so yes :)

**Review by foolip — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Comment by fwadnjar** [comment]
annevk/copyright-year

**Comment by fwadnjar** [comment]
annevk/copyright-year

**Comment by fwadnjar** [comment]
268313@main

**Comment by 923417809125** [comment]
tanveerhussaingujjar6@gmail.com

**Comment by 923417809125** [comment]
03417809125

**Comment by 923417809125** [comment]
Tanveerhussain

**Comment by 923417809125** [comment]
06f938b39b005adf0d2c16a290fd7892596a8da8

**Pull request merged**
