### PR TITLE
Non-special URL path tests

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/url/issues/212 for details.

### CODE REVIEW

**Comment by annevk** [comment]
This is not ready to be reviewed yet. Many existing tests need to change as well.

**Comment by annevk** [comment]
These tests depend on #4406 landing first.

**Comment by domenic** [comment]
@annevk can you rebase these on master?

**Comment by annevk** [comment]
Rebased.

**Review by domenic — APPROVED** [review]

**Pull request merged**
