### PR TITLE
Update interfaces/fetch.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Note: This file was recently manually updated in commit a21bf146db.
      This commit may revert some of those changes.

Source: https://github.com/tidoust/reffy-reports/blob/57f9433/ed/idl/fetch.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/607619722

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Oh, actually this would revert the changes in https://github.com/web-platform-tests/wpt/pull/19991.

@ivanlish is there a pull request incoming for https://github.com/whatwg/fetch to make the same changes?

fetch/META.yml folks FYI: @jdm @youennf @annevk @mnot @yutakahirano @domfarolino

**Comment by annevk** [comment]
@foolip https://github.com/whatwg/fetch/pull/948.

**Comment by foolip** [comment]
Thanks! Do you think we should merge this to match the spec now, or leave it open until the spec matches? It doesn’t really matter because it’s just an enum value and doesn’t affect tests, but if more changes land in the fetch spec it will be inconvenient to *not* land this and effectively revert a previous change.

**Comment by annevk** [comment]
I'm happy to see this land (but also to wait and sort it out when there's a conflict). Not sure about @mikewest et al.

**Comment by iVanlIsh** [comment]
I've got no idea and would like to ship this question to @mikewest .

**Comment by mikewest** [comment]
> I'm happy to see this land (but also to wait and sort it out when there's a conflict)

@annevk: Did you mean "this" as in the PR on which we're having this discussion (web-platform-tests/wpt#20085), or "this" as in whatwg/fetch#948?

I would prefer to land the latter and thereby obsolete the former, but as @foolip notes, I don't think any of this is web-visible anyway, so I don't particularly care in which order we land things.

**Comment by foolip** [comment]
Alright, I'll just merge this since it's harmless.

**Pull request merged**
