### PR TITLE
Initial test for resource timing

### PR DESCRIPTION
**Pull request by plehegar**
This is just an initial test to adjust all of the tests before moving them all.

### CODE REVIEW

**Comment by toddreifsteck** [comment]
@igrigorik @plehegar This PR needs some love. What are the next steps? This may be one where some assistance from Xiaquan

**Comment by plehegar** [comment]
@siusin looked at this PR and concluded that it overlaps with what we have in the repo. Proposal is to close down the PR with no action. @igrigorik ?

**Comment by igrigorik** [comment]
sgtm, closing.

**Comment by toddreifsteck** [comment]
These tests clearly have additional coverage missing from existing tests. They cover clearing the buffer which is something the existing tests don't cover. There is some overlap, but I'm not clear that is a good reason to shut this PR down.

**Comment by siusin** [comment]
Sorry, I was looking at a wrong branch when I did the review last time. My WPT repo got messed up after I merged these commits to the latest :(

@toddreifsteck is correct. I think it's reasonable to keep the following tests, although some of them need to be modified:
- test_resource_cached.html
- test_resource_iframe_self_navigation.html
- test_resource_ignore_data_url.html
- test_resource_ignore_failures.html
- test_resource_script_types.html
- test_resource_reparenting.html 
- test_resource_redirects.html
- test_resource_connection_reuse.html
- test_resource_frame_initiator_type.html
- test_resource_dynamic_insertion.html

These two tests can be removed for overlaps:
- test_resource_attribute_order.html (covered by test_resource_timing.html);
- test_resource_initiator_types.html (covered by resource_timing.html)

I'll submit the updated tests later.

**Comment by plehegar** [comment]
(goal is to close this PR and open one or more new ones with the proper test)

**Comment by plehegar** [comment]
submused by other PRs

**Pull request closed without merging**
