### PR TITLE
[permissions] Add tests for "Set Permission"

### PR DESCRIPTION
**Pull request by jugglinmike**
https://w3c.github.io/permissions/#automation

### CODE REVIEW

**Comment by andreastt** [comment]
@jugglinmike @burg 

Is the WebDriver extension in Permissions in sync with the implementation in Safari? Are these tests in sync with the specification and/or reality?

**Comment by jugglinmike** [comment]
These tests are in sync with the specification.

**Comment by andreastt** [comment]
Tests are failing in Chrome. Retriggered them to see if that makes a difference.

**Review by andreastt — APPROVED** [review]
Thanks for your feedback @jugglinmike!

I don’t have a particular opinion on this API, but if this is defined in Permissions we should have tests for it in WPT. It would be good if we could get some feedback from @burg before we land it, but I’m OK with it.

**Comment by burg** [comment]
These tests look good to me. Thanks!

**Comment by andreastt** [comment]
@jugglinmike Do you want to do the honours when you have time?

**Comment by jugglinmike** [comment]
Thanks for the help!

**Pull request merged**
