### PR TITLE
Add tests verifying that bad preflight response headers fail the load

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by youennf** [comment]
@annevk @yutakahirano, following on https://bugzilla.mozilla.org/show_bug.cgi?id=1364598, it seems we still have some difference of behaviours amongst browsers in that area:
- Firefox fails the load as per spec as soon as there is a wrong header value in the preflight response
- Safari used to be lax, and is now ignoring any faulty header, but does not fail the load automatically
- Chrome seems to be lax according my testing although https://bugs.chromium.org/p/chromium/issues/detail?id=724452 supposedly fixed it.

**Comment by annevk** [comment]
The Chrome bug is about correctly parsing `Access-Control-Expose-Headers`, not rejecting a preflight altogether. Per Fetch a preflight is never to be rejected for a `Access-Control-Expose-Headers` header that fails to parse.

It does return a network error however if either `Access-Control-Allow-Methods` or `Access-Control-Allow-Headers` fails to parse per step 7.3 of https://fetch.spec.whatwg.org/#cors-preflight-fetch-0.

**Comment by youennf** [comment]
> The Chrome bug is about correctly parsing `Access-Control-Expose-Headers`, not rejecting a preflight altogether.

Oh right, this might be a new bug then.
We use the same routine in WebKit.

**Comment by annevk** [comment]
I suppose we could be less strict, in case you don't need to list either headers or methods, but are trying and failing, but the current specified behavior also seems okay to me. (It's not clear to me if the test is testing what the specification requires and Firefox does.)

cc @yutakahirano

**Comment by youennf** [comment]
> It's not clear to me if the test is testing what the specification requires and Firefox does

The test does a fetch with preflight and expects fetch to fail since the preflight response contains either a bad Allow-Access-Control-Headers or a bad Allow-Access-Control-Methods.

Firefox is passing both tests, Chrome none.
Safari is doing as if there is no such header and is passing one but not the other.
I guess we could improve the methods test.

**Review by annevk — APPROVED** [review]
Ah, of course, I somehow thought the preflight shouldn't have been made, but that doesn't make any sense. Apologies for the delay.

**Comment by yutakahirano** [comment]
@youennf Do you have any data how many sites set such broken access-control-allow-{methods, headers}?

**Comment by youennf** [comment]
> @youennf Do you have any data how many sites set such broken access-control-allow-{methods, headers}?

My current assessment is that the breakage risk is low:
- Firefox has this behavior for quite some time
- STP has this behavior for a few months, as well as Safari in recent iOS/MacOS seeds. We identified one breakage so far, which was quickly fixed server-side.

**Comment by annevk** [comment]
Did you mean to close this?

**Comment by youennf** [comment]
Woups, no

**Comment by youennf** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1060504

**Comment by youennf** [comment]
> * Safari used to be lax, and is now ignoring any faulty header, but does not fail the load automatically

https://bugs.webkit.org/show_bug.cgi?id=208924

**Comment by yutakahirano** [comment]
OK, LGTM.

**Pull request merged**
