### PR TITLE
Rename PeriodicBackgroundSync to periodic-background-sync

### PR DESCRIPTION
**Pull request by foolip**
To match the spec shortname.

Also adds a META.yml with the spec editors as suggested reviewers.

### CODE REVIEW

**Comment by foolip** [comment]
@jakearchibald @mugdhalakhani can you review this, are you OK with getting added to PRs in this directory? @mugdhalakhani I've sent you an invite to the reviewers team of web-platform-tests, which you'll need to accept if you'd like to be listed here. (Otherwise the reviewer assigned bot can't assign you.)

**Review by jakearchibald — APPROVED** [review]
lgtm

**Comment by jakearchibald** [comment]
> are you OK with getting added to PRs in this directory?

@mugdhalakhani has more experience with this spec, but I don't mind being added to these PRs

**Comment by mugdhalakhani** [comment]
lgtm, thanks!

**Pull request merged**
