### PR TITLE
remove disabled tests from total count

### PR DESCRIPTION
**Pull request by nihardamar**
Right now there is a discrepancy between count at start of the test run and at the end.
This is due to disabled tests being added to total count.
Just log disabled tests and ignore these rather than adding to total.

Tested in CL:
https://chromium-review.googlesource.com/c/chromium/src/+/4215272

Bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1409939

### CODE REVIEW

**Review by jonathan-j-lee — CHANGES_REQUESTED** [review]
wptrunner emits structured (machine-readable) logs [1] so that other systems can consume them; the logs are not just informational. I think this is not a change we want to make because this could break consumers that rely on the presence of `test_{start,end}` records to detect skipped tests.

[1]: https://firefox-source-docs.mozilla.org/mozbase/mozlog.html#data-format

**Comment by nihardamar** [comment]
> wptrunner emits structured (machine-readable) logs [1](https://firefox-source-docs.mozilla.org/mozbase/mozlog.html#data-format) so that other systems can consume them; the logs are not just informational. I think this is not a change we want to make because this could break consumers that rely on the presence of `test_{start,end}` records to detect skipped tests.

My original thought was that that we could just remove this, but as you said since it's read by external it's probably better to keep these disabled tests in so it's consumable externally.
I'll instead add the disabled tests to the original count.

**Comment by WeizhongX** [comment]
> 

Thanks, I think this is the right way to go.

**Comment by WeizhongX** [comment]
@jgraham Can you pls take a look?

**Review by WeizhongX — APPROVED** [review]

**Review by jonathan-j-lee — COMMENTED** [review]
Looks like this doesn't change what tests are run, just logging disabled tests in `suite_start` and including disabled tests in the `num_test_groups` count.

**Review by jonathan-j-lee — APPROVED** [review]

**Pull request merged**
