### PR TITLE
HTML: mark typemustmatch historical

### PR DESCRIPTION
**Pull request by annevk**
Apart from Firefox nobody adopted this and it creates a smallish cross-origin leak.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Go ahead and remove the line in `webdriver/tests/get_element_attribute/get.py`

**Review by andreastt — APPROVED** [review]
webdriver/ bit is obviously fine. 👍🏻

**Comment by zcorpan** [comment]
Is `interfaces/html.idl` synced automatically?

**Comment by annevk** [comment]
Yeah, it should be, once the HTML change lands.

**Review by zcorpan — APPROVED** [review]

**Pull request merged**
