### PR TITLE
[css-ui-3] remove stray link to unrelated reference

### PR DESCRIPTION
**Pull request by frivoal**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247842908)

# Firefox (nightly) #
Testing web-platform-tests at revision e2702ebc20334e781eba05e4cdd66f59fd26c554
Using browser at version BuildID 20170612100241; SourceStamp 27cad9749cddf68e11fdd4e5d73dad84a8f8cf23
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6354/css/css-ui-3/box-sizing-026.html">/css/css-ui-3/box-sizing-026.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247842909)

# Sauce (safari) #
Testing web-platform-tests at revision e2702ebc20334e781eba05e4cdd66f59fd26c554
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6354/css/css-ui-3/box-sizing-026.html">/css/css-ui-3/box-sizing-026.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247842915)

# Chrome (unstable) #
Testing web-platform-tests at revision e2702ebc20334e781eba05e4cdd66f59fd26c554

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/247842916)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision e2702ebc20334e781eba05e4cdd66f59fd26c554

**Comment by frivoal** [comment]
@gsnedders This PR should take about 5 seconds to review. Can you give it a look?

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
