### PR TITLE
Fix a typo in a resource file name (#9986)

### PR DESCRIPTION
**Pull request by Hexcles**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

</ul>



<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Firefox Nightly"<small></small></h3>
  <p>View in: <a href="http://pulls.web-platform-tests.org/job/26113.4">WPT PR Status</a> |
      <a href="https://travis-ci.org/w3c/web-platform-tests/jobs/354383730">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  
  
  <tr>
    <td><code>/resource-timing/resource_initiator_types.html</code></td>
    <td>&nbsp;</td>
    <td>OK: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/fonts/Ahem.ttf?id=n1 is expected to have initiatorType css</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/fonts/Ahem.ttf?id=n1 is expected to have initiatorType css expected "css" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/fonts/Ahem.ttf is expected to have initiatorType css</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/fonts/Ahem.ttf is expected to have initiatorType css expected "css" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/media/test.mp4?id=video-src is expected to have initiatorType video</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/media/test.mp4?id=video-src is expected to have initiatorType video expected "video" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/media/test.ogv?id=video-source is expected to have initiatorType source</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/media/test.ogv?id=video-source is expected to have initiatorType source expected "source" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blank_page_green.htm?id=frame is expected to have initiatorType frame</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blank_page_green.htm is expected to have initiatorType iframe</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=1 is expected to have initiatorType css</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=2 is expected to have initiatorType css</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=async_xhr is expected to have initiatorType xmlhttprequest</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=body is expected to have initiatorType body</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/blue.png?id=body is expected to have initiatorType body expected "body" but got "css"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=cursor is expected to have initiatorType css</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=input is expected to have initiatorType input</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=n1 is expected to have initiatorType css</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=object is expected to have initiatorType object</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=picture-99x-img-src is expected to have initiatorType img</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=picture-img-srcset is expected to have initiatorType img</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=picture-notsupported-img is expected to have initiatorType img</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=picture-source is expected to have initiatorType source</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/blue.png?id=picture-source is expected to have initiatorType source expected "source" but got "img"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=svg-image is expected to have initiatorType image</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/blue.png?id=video-poster is expected to have initiatorType video</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/blue.png?id=video-poster is expected to have initiatorType video expected "video" but got "img"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-source-ogg is expected to have initiatorType source</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-source-ogg is expected to have initiatorType source expected "source" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-source-wav is expected to have initiatorType source</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-source-wav is expected to have initiatorType source expected "source" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-src is expected to have initiatorType audio</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/empty.py?id=audio-src is expected to have initiatorType audio expected "audio" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=beacon is expected to have initiatorType beacon</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/empty.py?id=beacon is expected to have initiatorType beacon expected "beacon" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=fetch is expected to have initiatorType fetch</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty.py?id=video-track is expected to have initiatorType track</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/empty.py?id=video-track is expected to have initiatorType track expected "track" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/empty_script.js is expected to have initiatorType script</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/eventsource.py?id=eventsource is expected to have initiatorType eventsource</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/eventsource.py?id=eventsource is expected to have initiatorType eventsource expected "eventsource" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/nested.css?id=prefetch is expected to have initiatorType link</code></td>
    <td>FAIL: 6<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/nested.css?id=prefetch is expected to have initiatorType link expected "link" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/nested.css?id=preload is expected to have initiatorType link</code></td>
    <td>FAIL: 10<br /></td>
    <td><code>assert_equals: http://web-platform.test:8000/resource-timing/resources/nested.css?id=preload is expected to have initiatorType link expected "link" but got "other"</code><br /></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/nested.css is expected to have initiatorType link</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/resource_timing_test0.css?id=embed is expected to have initiatorType embed</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/resource_timing_test0.css?id=n1 is expected to have initiatorType css</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/resource_timing_test0.png?id=srcset-srcset is expected to have initiatorType img</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>http://web-platform.test:8000/resource-timing/resources/resource_timing_test0.png is expected to have initiatorType img</code></td>
    <td>PASS: 10<br /></td>
    <td></td>
  </tr>
  
  
  
  
  
  
  
  </table>

**Comment by Hexcles** [comment]
|                       Test                       |                                                         Subtest                                                         |            Results            |                                                                                Messages                                                                                |
|--------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|-------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `/resource-timing/resource_initiator_types.html` | `http://web-platform.test:8000/resource-timing/resources/nested.css?id=prefetch is expected to have initiatorType link` | **FAIL: 6/10, MISSING: 4/10** | `assert_equals: http://web-platform.test:8000/resource-timing/resources/nested.css?id=prefetch is expected to have initiatorType link expected "link" but got "other"` |

Looks like the test is very flaky. How did #9986 pass Travis?

I'm not familiar with Resource Timing, but wonder if there's any guarantees on the ordering of `entries`?

**Comment by nicjansma** [comment]
Thanks @Hexcles, this change looks great.

Unfortunately none of the browsers actually pass these tests today (each has a few bugs to address).

**Review by nicjansma — APPROVED** [review]

**Comment by Hexcles** [comment]
@nicjansma the problem is less about failures, but more about flakes.

We are totally fine with all browsers failing a test, but we don't want a test to produce flaky results (e.g. adding subtests out of order, randomly missing some subtests...).

As you can see from my comment above, 4 out of 10 times a subtest (`nested.css?id=prefetch`) is missing in Firefox. Is there any way to stabilize the test?

**Review by igrigorik — APPROVED** [review]
LGTM for the typo fix. 

We should split the flaky test discussion into a separate thread. :)

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
