### PR TITLE
update pull request #4976

### PR DESCRIPTION
**Pull request by siusin**
Resubmission of #4976 Replace usage of setTimeout with step_timeout in user-timing.

The documents in #4976 have been merged into measure.html and measure_navigation_timing.html.

This update won't change the test result of the documents involved.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257759218)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257759219)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257759226)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257759227)

# Sauce (MicrosoftEdge) #

**Review by igrigorik — APPROVED** [review]

**Comment by igrigorik** [comment]
👍

**Pull request merged**
