### PR TITLE
Update the aom IDL file

### PR DESCRIPTION
**Pull request by lukebjerring**
Hello reviewer(s),

This PR is intended to consolidate the spec’s IDL definition with the WPT test suite’s copy, and any idlharness tests.

The up-to-date copy of the IDL file was automatically extracted from the reffy-reports repo (https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl) which scrapes known specs automatically + regulary.

This PR is part of a migration project which will eventually be automatically updating and creating PRs for changes in spec IDL.

Please check that:
The Spec (and its source) is correct and up-to-date
All tests which cover the IDL in the spec have been migrated to fetch + use the idl in the `interfaces/` directory (instead of inline copies in the test files).

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-03-02 20:41:58
Finished: 2018-03-02 20:51:02


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25163)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/348381332)

**Comment by foolip** [comment]
IDL and test looks good, just needs reviewers in META.yml. https://wicg.github.io/aom/spec/ has these editors:
* Alice Boxhall (Google) &rArr; @alice
* James Craig (Apple) &rArr; @cookiecrook
* Dominic Mazzoni (Google) &rArr; @minorninth
* Alexander Surkov (Mozilla) &rArr; @asurkov

I have sent all four of you invites to the web-platform-tests org, which you can view/accept at https://github.com/web-platform-tests. If one or more of you could volunteer to get reviews for this directory, it would be much appreciated!

I've updated META.yml in this PR to list all of you, but will await confirmation and remove anyone who doesn't reply.

**Review by foolip — APPROVED** [review]
LGTM, but need to await suggested reviewers.

**Comment by alice** [comment]
Note that the version of the spec which includes these IDL properties has been deprecated: https://wicg.github.io/aom/spec/phase1.html

**Comment by foolip** [comment]
Oh, interesting. These IDL files are from reffy, so I filed https://github.com/tidoust/reffy-reports/issues/10. This PR shouldn't be merged then.

**Comment by foolip** [comment]
I'm afraid I don't know the details myself, hoping to find out in https://github.com/tidoust/reffy-reports/issues/10. I'm hopeful that it can be made to just work, so that if something like this happens again, the idl file is simply deleted.

**Comment by tidoust** [comment]
I tried to explain why we ended up in that situation in tidoust/reffy-reports#10 and why it might happen again. I created tidoust/reffy-reports#12 to track the creation of an alert system so that we be notified in the future when an IDL file likely needs to be deleted.

**Comment by lukebjerring** [comment]
Whoops, moving columns affects PR state.

**Pull request closed without merging**
