### PR TITLE
[Azure Pipelines] start running inert element retargeting tests again

### LINKED ISSUE #18634: Inert element retargeting tests not running on Safari
https://github.com/web-platform-tests/wpt/pull/18585 disabled inert/inert-retargeting.tentative.html and inert-retargeting-iframe.tentative.html on Safari because they somehow interrupting the test run.

They should be enabled again when the root cause has been fixed.

@alice FYI.

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt/issues/18634.

Also lists the right issues for Safari stable.

### CODE REVIEW

**Comment by foolip** [comment]
I've triggered https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=36804 to see if this works now.

**Comment by foolip** [comment]
This is blocked by https://github.com/web-platform-tests/wpt/issues/20324.

**Comment by foolip** [comment]
I've rebased and triggered https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=48192&view=results to see if this works now.

**Comment by foolip** [comment]
That worked, and https://wpt.fyi/results/?diff&filter=ADC&run_id=523430002&run_id=544570001 suggests it didn't silently regress all the following tests, or something like that.

**Comment by foolip** [comment]
@stephenmcgruer care to review?

**Review by stephenmcgruer — APPROVED** [review]

**Pull request merged**
