### PR TITLE
Encoding/HTML: cross-document encoding inheritance 

### PR DESCRIPTION
**Pull request by annevk**
Make Encoding tests no longer rely on an interoperability issue and simultaneously add tests for that issue. The latter tests align with the HTML Standard, but that might not necessarily be the path we want to take.

https://github.com/whatwg/html/issues/8789 can be used for further discussion.

### CODE REVIEW

**Comment by annevk** [comment]
@hsivonen so I'm not sure how this is different but somehow it works the same in all browsers here. Inserting the `frame` dynamically thankfully doesn't change things. Maybe it's UTF-8?

**Comment by annevk** [comment]
I guess it has to do with how HTTP `Content-Type` and defaulting interact. HTML also doesn't use the greatest language for that.

**Comment by hsivonen** [comment]
Might be worthwhile to add a different-origin test to check that there's no inheritance across origins. On do we already have that elsewhere?

**Comment by annevk** [comment]
Done, thankfully everyone passes that. (It seems there's room for quite a bit more tests of this algorithm, but I don't have the time at the moment.)

**Review by hsivonen — APPROVED** [review]
Thanks. I trust that some U+FFFDs here are from the GitHub UI showing non-UTF-8 files.

**Review by adokiroev — CHANGES_REQUESTED** [review]
****

**Pull request merged**
