### PR TITLE
Use new IDL mixin syntax in cssom.idl and cssom-view.idl

### PR DESCRIPTION
**Pull request by romandev**
Helps with https://github.com/w3c/csswg-drafts/issues/1931, https://github.com/w3c/csswg-drafts/issues/1932

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22076)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/319583283)

**Comment by foolip** [comment]
@romandev, can you rebase this so that we get a new Travis run? https://pulls.web-platform-tests.org/pull/8772 doesn't have any results (@mattl FYI, maybe because of downtime?)

This should be merged together with https://github.com/w3c/csswg-drafts/pull/2123, right?

(This is an open PR that would require changes if I do https://github.com/w3c/web-platform-tests/issues/9026, that's why I'm here.)

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22798)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/329141331)

**Comment by romandev** [comment]
@foolip Rebased this patch.

> This should be merged together with w3c/csswg-drafts#2123, right?

Yep, right.

Thanks!

**Comment by foolip** [comment]
This was fixed in #9777 and #11819.

**Pull request closed without merging**
