### PR TITLE
WebAppSec CSP tests

### PR DESCRIPTION
**Pull request by odinho**

### CODE REVIEW

**Comment by mikewest** [comment]
@hillbrad: Should we bring these in, or have you already covered these with the tests you landed way back when?

**Comment by hillbrad** [comment]
I'm going to close this as PHP tests are no longer relevant in the new framework.

**Comment by Ms2ger** [comment]
They can be translated if they're useful...

**Comment by hillbrad** [comment]
I wrote almost all of these, have rewritten or helped supervise rewrites of most in the new framework already, and they're still available in the old Hg repo, so I don't see any good reason to clutter up the GH repo with them or do the necessary work to land them when they won't work anyway.

**Pull request closed without merging**
