### PR TITLE
Reland "Update Safari Technology Preview to 97"

### PR DESCRIPTION
**Pull request by foolip**
This is https://github.com/web-platform-tests/wpt/pull/20863 with additional fixes.

### CODE REVIEW

**Comment by foolip** [comment]
Trial run in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39244&view=results

**Review by jgraham — APPROVED** [review]
I kind of wish we would fix the runner to handle these failures more gracefully.

**Comment by foolip** [comment]
That's https://github.com/web-platform-tests/wpt/issues/19620

**Comment by foolip** [comment]
STP 96 vs 97: https://wpt.fyi/results/?diff&filter=ADC&run_id=383280001&run_id=375460004

@othermaciej there are big improvements here, numerically css/css-color/color-resolving-hsl.html and pointerevents/ (safaridriver fix) are a lot of it.

Looks like a lot were Safari-specific failures now fixed:
https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3Apass%20status%3A%21pass%20status%3Apass%29&run_id=394240004&run_id=375480002&run_id=383280001&run_id=375460004

Yay :)

@stephenmcgruer I wonder if this'll show up as a bump on your graphs?

**Comment by stephenmcgruer** [comment]
Yes, it does! Amazing job @othermaciej (and all of the WebKit team). This is so exciting I tweeted it; https://twitter.com/stephenmcgruer/status/1211723768747479042

Engine-specific Failures in WPT (Experimental) (1)

**Pull request merged**
