### PR TITLE
Add historical tests for Custom Elements v0

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@mcatanzaro @Ms2ger PTAL

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19150)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/283242717)

**Comment by domenic** [comment]
We should also test that `createElement(x, "string")` does not work, per https://github.com/Polymer/docs/issues/1705

**Comment by foolip** [comment]
I think these are in good shape now, they fail in Chrome and pass elsewhere.

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
