### PR TITLE
Test UIEvents interfaces

### PR DESCRIPTION
**Pull request by ayg**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17328)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264076955)

**Comment by ayg** [comment]
@garykac @travisleithead Can you review?  It's a pretty straightforward test, similar to tests we have for other specifications that use WebIDL.

**Comment by ayg** [comment]
I currently am unemployed, so I will not be able to work any further on this unless I succeed in finding someone who's willing to pay me to continue to work on web standards.

**Review by Ms2ger — APPROVED** [review]

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-08-14 11:31:21
Finished: 2017-08-14 11:41:31





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17329)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264078092)

**Pull request merged**
