### PR TITLE
Fix #33204: Move Safari stable runs to Big Sur

### LINKED ISSUE #33204: Update Safari stable on Azure Pipelines to Big Sur
Now Safari 15.4 has shipped we can use `acceptInsecureCerts` for Safari stable, which removes the blocker for that upgrading to Big Sur. We're currently failing to complete any runs (https://wpt.fyi/status) because Azure Pipelines is giving us different OS versions, but once we have a complete run for 15.4 on Catalina we should move it to Big Sur.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #33204

### CODE REVIEW

**Comment by gsnedders** [comment]
https://wpt.fyi/results/?diff&filter=ADC&run_id=5769357647937536&run_id=5669570558820352

**Review by jgraham — APPROVED** [review]

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Should we move everything to Big Sur? (Not in this PR.)

**Comment by gsnedders** [comment]
> Should we move everything to Big Sur? (Not in this PR.)

Unfortunately, this does that in this PR. (Safari Stable is the only thing we hadn't already moved.)

**Comment by foolip** [comment]
Ah, OK, I forgot 😀

**Pull request merged**
