### PR TITLE
Update fetch cors tests to limit the use of www/www1 URLs

### PR DESCRIPTION
**Pull request by youennf**
These changes would allow greater execution of the tests in WebKit environments where access to www/www1 URLs always fails.
Change is not done for cookies as different ports might not be different enough.

### CODE REVIEW

**Comment by youennf** [comment]
See also https://github.com/w3c/web-platform-tests/issues/3243

**Comment by youennf** [comment]
Ping?

**Comment by jdm** [comment]
I would be ok with merging most of these changes; my reluctance here is that Servo doesn't support HTTPS tests yet so this change would cause us to lose test coverage :(

**Comment by youennf** [comment]
Ah....
So all changes except for fetch/api/cors/cors-redirect-credentials.js?
I will update the last one then.

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
