### PR TITLE
Remove the use of Big Buck Bunny in favour of a slightly smaller file.

### PR DESCRIPTION
**Pull request by jgraham**
Big buck bunny is huge and bloats the repo considerably. We already
have some video files; in the long run these should just be linked but
in the short run it makes sense to copy one of these to the relevant place.

### CODE REVIEW

**Comment by jgraham** [comment]
@gsnedders ?

**Comment by gsnedders** [comment]
@jgraham @sideshowbarker this isn't on w3c-test.org :\

**Comment by gsnedders** [comment]
And Reviewable hasn't kicked in. Guess the hooks have just failed.

**Comment by gsnedders** [comment]
LGTM.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218160616)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 19f00d670408500e0679eb984551c8227e5ebf12
Using browser at version BuildID 20170403100136; SourceStamp 38894655c89e68bcd8f45d31a0d3005f2c2b53db
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5326/service-workers/service-worker/fetch-event.https.html">/service-workers/service-worker/fetch-event.https.html</a></summary>


|                                   Subtest                                    | Results |                                                      Messages                                                      |
|------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------|
|                                                                              | OK      |                                                                                                                    |
| `Service Worker responds to fetch event with string`                         | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with blob body`                      | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the referrer URL`               | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the referrer policy`            | FAIL    | `assert_unreached: unexpected rejection: NetworkError when attempting to fetch resource. Reached unreachable code` |
| `Service Worker responds to fetch event with an existing client id`          | PASS    |                                                                                                                    |
| `Service Worker does not respond to fetch event`                             | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with null response body`             | PASS    |                                                                                                                    |
| `Service Worker fetches other file in fetch event`                           | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with POST form`                      | PASS    |                                                                                                                    |
| `Multiple calls of respondWith must throw InvalidStateErrors`                | PASS    |                                                                                                                    |
| `Service Worker event.respondWith must set the used flag`                    | PASS    |                                                                                                                    |
| `Service Worker should expose FetchEvent URL fragments.`                     | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the correct cache types`        | PASS    |                                                                                                                    |
| `Service Worker should intercept EventSource`                                | PASS    |                                                                                                                    |
| `Service Worker responds to fetch event with the correct integrity_metadata` | PASS    |                                                                                                                    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5326/service-workers/service-worker/navigation-preload/redirect.https.html">/service-workers/service-worker/navigation-preload/redirect.https.html</a></summary>


|                            Subtest                            | Results |     Messages     |
|---------------------------------------------------------------|---------|------------------|
|                                                               | TIMEOUT |                  |
| `Navigation Preload redirect response.`                       | TIMEOUT | `Test timed out` |
| `Navigation Preload no-location redirect response.`           | NOTRUN  |                  |
| `Navigation Preload no-location redirect response with body.` | NOTRUN  |                  |
| `Navigation Preload redirect to the same scope.`              | NOTRUN  |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/218160617)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 19f00d670408500e0679eb984551c8227e5ebf12
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5326/service-workers/service-worker/fetch-event.https.html">/service-workers/service-worker/fetch-event.https.html</a></summary>


|                                   Subtest                                    | Results |                                                                                                                                                                                                                                                   Messages                                                                                                                                                                                                                                                   |
|------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                              | OK      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with string`                         | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with blob body`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with the referrer URL`               | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with the referrer policy`            | FAIL    | `assert_unreached: unexpected rejection: assert_equals: Service Worker should respond to fetch with the referrer URL when a member of RequestInit is present expected "Referrer: https://web-platform.test:8443/service-workers/service-worker/resources/simple.html?referrerPolicy\nReferrerPolicy: no-referrer-when-downgrade" but got "Referrer: https://web-platform.test:8443/service-workers/service-worker/resources/undefined\nReferrerPolicy: no-referrer-when-downgrade" Reached unreachable code` |
| `Service Worker responds to fetch event with an existing client id`          | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker does not respond to fetch event`                             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with null response body`             | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker fetches other file in fetch event`                           | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker responds to fetch event with POST form`                      | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Multiple calls of respondWith must throw InvalidStateErrors`                | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker event.respondWith must set the used flag`                    | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker should expose FetchEvent URL fragments.`                     | FAIL    | `assert_unreached: unexpected rejection: assert_equals: Service worker should expose URL fragments in request. expected "Fragment Found :#/some/fragment" but got "Fragment Not Found" Reached unreachable code`                                                                                                                                                                                                                                                                                             |
| `Service Worker responds to fetch event with the correct cache types`        | FAIL    | `assert_unreached: unexpected rejection: assert_equals: expected "default" but got "" Reached unreachable code`                                                                                                                                                                                                                                                                                                                                                                                              |
| `Service Worker should intercept EventSource`                                | FAIL    | `assert_unreached: unexpected rejection: assert_equals: EventSource should bypass the http cache. expected (string) "no-store" but got (undefined) undefined Reached unreachable code`                                                                                                                                                                                                                                                                                                                       |
| `Service Worker responds to fetch event with the correct integrity_metadata` | PASS    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5326/service-workers/service-worker/navigation-preload/redirect.https.html">/service-workers/service-worker/navigation-preload/redirect.https.html</a></summary>


|                            Subtest                            | Results |     Messages     |
|---------------------------------------------------------------|---------|------------------|
|                                                               | TIMEOUT |                  |
| `Navigation Preload redirect response.`                       | TIMEOUT | `Test timed out` |
| `Navigation Preload no-location redirect response.`           | NOTRUN  |                  |
| `Navigation Preload no-location redirect response with body.` | NOTRUN  |                  |
| `Navigation Preload redirect to the same scope.`              | NOTRUN  |                  |

</details>
</details>

**Pull request merged**
