### PR TITLE
Wait for animation in reportValidity-bubble reftest

### PR DESCRIPTION
**Pull request by josepharhar**
This reftest does a comparison of the form validation validity bubbles rendered by the browsers, but is failing in chrome because the bubble animates and the time at which the test runner takes a screenshot is not at the exact same frame in the animation.

setTimeout, document.getAnimations(), and requestIdleCallback are not good enough to fix this test, so I changed the reference to not have a validity bubble and then made it a mismatch/notref test instead.

### CODE REVIEW

**Comment by dbaron** [comment]
It seems unfortunate to have to wait for 2 seconds and delay the tests... and also it's a lint failure (see checks) that would need to be fixed before merging this.

Does the validation bubble animation happen to show up in `Document.getAnimations()`?  Or does `requestIdleCallback` happen to wait until the animation is complete?

**Comment by josepharhar** [comment]
I tried getAnimations and requestIdleCallback, and unfortunately they don't work.
I changed the test to a notmatch instead of a match, what do you think?

**Review by dbaron — APPROVED** [review]
I think this is a reasonable approach.

I think the convention is generally to name `rel=mismatch` files as `-notref` rather than `-ref`, although I'm not sure how widely followed that is.  I'd suggest renaming the reference accordingly (and updating the `rel=mismatch` link to match!).

With that change, this looks good to me.

**Comment by josepharhar** [comment]
Renamed, thanks!

**Pull request merged**
