### PR TITLE
Make all parameters to initEvent() / initCustomEvent() optional excep…

### PR DESCRIPTION
**Pull request by cdumez**
…t the first one

Make all parameters to initEvent() / initCustomEvent() optional except the first one.
to match:
- https://github.com/whatwg/dom/pull/417
- https://github.com/whatwg/dom/issues/387

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5043)

**Comment by annevk** [comment]
Is this enough to actually get these methods tested? I somewhat doubt this would end up causing a failure in Firefox for instance.

**Comment by cdumez** [comment]
@annevk It definitely causes failures in Firefox but I will look into adding more testing.

**Comment by annevk** [comment]
Ah yeah, length tests. That's probably good enough.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5043)

**Comment by cdumez** [comment]
I added a bit more extensive testing.

**Pull request merged**
