### PR TITLE
Add wpt frontend for commands

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6421)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248158198)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248158199)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248158205)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/248158206)

# Sauce (MicrosoftEdge) #

**Comment by bobholt** [comment]
This looks like it's still a work-in-progress with (since the build's not passing). Overall, I like how this simplifies the component modules. I left a couple of line comments for things that jumped out at me in this revision, but am pretty much :+1: as long as the builds work. I'd like to see a sample flakey test run with this before merging.

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/browserutils/install.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-KnnkjnR_P6pw8h_tOSI:-KnnkjnS4ob8GiNg6rPX:be68dh5) ([raw file](https://github.com/w3c/web-platform-tests/blob/a092c62d990a4c8a0c15e0fcb729542c82b51982/tools/browserutils/install.py#L18)):*
> ```Python
> def run(venv, **kwargs):
>     browser = kwargs["browser"]
>     if venv and kwargs["destination"] is None:
> ```

This doesn't account for the `not venv and kwargs["destination"] is None` case (where `destination` wouldn't get assigned). If the existence of `venv` is checked in another script, the check isn't needed here.

---

*[tools/wpt/run.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-Knnn-riGLmGQwFMOh4Q:-Knnn-riGLmGQwFMOh4R:bate6ly) ([raw file](https://github.com/w3c/web-platform-tests/blob/a092c62d990a4c8a0c15e0fcb729542c82b51982/tools/wpt/run.py#L18)):*
> ```Python
> 
> 
> <<<<<<< HEAD
> ```

Unresolved merge conflict that may be causing some errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-:-KnnnlBYTq9SxmegTNEd:bx5hws5)*

**Comment by jgraham** [comment]
Yeah, this isn't done, just pushing it here for a little visibility.

**Comment by gsnedders** [comment]
How does this relate to #6237?

**Comment by jgraham** [comment]
This is more stuff on top of that one.

**Comment by jgraham** [comment]
This now passes travis. I think it might just be worth reviewing this rather than also looking at #6237, although I appreciate it's now a large change. However there are additional things that I'm keen to land on top of this to cut down the amount of unnecessary work we do in CI, so I would appreciate some plan to move forward here.

**Comment by bobholt** [comment]
I'm still getting errors similar to (but with import failures in different modules) what @jugglinmike [was getting](https://github.com/w3c/web-platform-tests/pull/6237#issuecomment-312682070) in #6237:

```
[wpt_files_changed] $ ./wpt run firefox url/a-element.html
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/bob/development/Bocoup/wpt-dev/web-platform-tests/tools/wpt/wpt.py", line 104, in main
    script, parser = import_command(command, props)
  File "/home/bob/development/Bocoup/wpt-dev/web-platform-tests/tools/wpt/wpt.py", line 71, in import_command
    parser = getattr(mod, props["parser"])()
  File "/home/bob/development/Bocoup/wpt-dev/web-platform-tests/tools/wpt/run.py", line 44, in create_parser
    from wptrunner import wptcommandline
ImportError: cannot import name wptcommandline
```

I also agree with @gsnedders that there is [a lot of new untested code](https://github.com/w3c/web-platform-tests/pull/6237#issuecomment-312394076)here. I'd be happy to start with even some rudimentary tests that invoked each new command with some option that exits status 0 to make sure the imports work and the commands can actually be called. They don't have to be automated with the rest of infrastructure yet, but it sure beats manually typing in each command to test.

**Comment by jgraham** [comment]
That command WFM; I don't know what's different about your setup (not disputing it's a bug, of course, just saying it's hard for me to track down since it doesn't happen here).

I can write some simple semi-automated tests for this.

**Comment by bobholt** [comment]
I can spend some time trying to debug it on my side.

**Comment by bobholt** [comment]
Reviewed 1 of 35 files at r1, 5 of 12 files at r2, 28 of 29 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[tools/wpt/install.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-KnnkjnR_P6pw8h_tOSI:-KpV8t_ZxCjACRaepegY:bb726fr) ([raw file](https://github.com/w3c/web-platform-tests/blob/a092c62d990a4c8a0c15e0fcb729542c82b51982/tools/wpt/install.py#L18)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

This doesn't account for the `not venv and kwargs["destination"] is None` case (where `destination` wouldn't get assigned). If the existence of `venv` is checked in another script, the check isn't needed here.
</blockquote></details>

Ping

---

*[tools/wpt/run.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-Knnn-riGLmGQwFMOh4Q:-KpV8aoioneWAwibghKd:bb6ywmx) ([raw file](https://github.com/w3c/web-platform-tests/blob/a092c62d990a4c8a0c15e0fcb729542c82b51982/tools/wpt/run.py#L18)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

Unresolved merge conflict that may be causing some errors.
</blockquote></details>

LGTM

---

*[tools/wpt/run.py, line 53 at r3](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-KpV84KPWwlx3LJUHsKs:-KpV84KQp_pz2U3WxeX0:biut3wl) ([raw file](https://github.com/w3c/web-platform-tests/blob/e68ab8cb5401879baf0d2d5aeaef9f45d1db1d9c/tools/wpt/run.py#L53)):*
> ```Python
>     parser.add_argument("--stability", action="store_true",
>                         help="Stability check tests")
>     parser.add_argument("--install-brower", action="store_true",
> ```

`--install-browser`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421)*

**Comment by bobholt** [comment]
re: error, I'm still not sure. I have to duck away for now, but I'll come back to it.

Here's what I've tried so far.

1. Uninstalling my globally-installed `wptrunner` (from way back).
2. Removing and letting `./wpt` re-install my `_venv` directory.

Here's the output of `pip freeze` within the virtual environment. Not sure if anything's missing that should be there.
```
[wpt_files_changed] $ pip freeze
blessings==1.6
certifi==2017.4.17
chardet==3.0.4
html5lib==0.999999999
idna==2.5
mozdebug==0.1
mozfile==1.2
mozinfo==0.10
mozlog==3.5
requests==2.18.1
six==1.10.0
urllib3==1.21.1
webencodings==0.5.1
```

Opening a python interpreter within the virtual environment at `wpt_root` and trying `from wptrunner import wptcommandline` results in `ImportError: No module named wptrunner`

I changed `command.json` to add `wptrunner` to the `install` prop. Doing `from wptrunner import wptcommandline` in the interpreter now works, but I still get the `ImportError: cannot import name wptcommandline` error when running `./wpt run firefox url/a-element.html`.

**Comment by jgraham** [comment]
OK, that's less that I have installed (clean venv, only `wpt run firefox <path>` run):

```
blessings==1.6
certifi==2017.4.17
chardet==3.0.4
html5lib==0.999999999
idna==2.5
marionette-driver==2.3.0
mozcrash==1.0
mozdebug==0.1
mozdevice==0.50
mozfile==1.2
mozinfo==0.10
mozleak==0.1
mozlog==3.5
moznetwork==0.27
mozprocess==0.25
mozprofile==0.28
mozrunner==6.13
mozversion==1.4
pkg-resources==0.0.0
requests==2.18.1
six==1.10.0
urllib3==1.21.1
webencodings==0.5.1
```

But I guess that means you aren't getting as far as `requirements_firefox.txt` being installed, which makes sense given how early this fails for you. 

In theory `wptrunner` should be put in the path by `import localfiles` at `tools/wpt/wpt.py:6`. Can you check the sys.path at that point? Maybe we should change the way that works and require everything to use a venv. But that's' an even bigger change, and this PR is already too large.

**Comment by bobholt** [comment]
Ah, that did it. That line should be `from tools import localfiles`.

**Comment by bobholt** [comment]
:+1: when the tests pass. @gsnedders do you have any interest in taking another pass at this?

---

Reviewed 1 of 35 files at r1, 2 of 29 files at r3, 3 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/wpt/install.py, line 18 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-KnnkjnR_P6pw8h_tOSI:-Kptge3J0Wam5q973Mz3:bb6ywmx) ([raw file](https://github.com/w3c/web-platform-tests/blob/a092c62d990a4c8a0c15e0fcb729542c82b51982/tools/wpt/install.py#L18)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

Ping
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421#-:-KptgvxShhYlti_0dSX4:b-yc3b2s)*

**Comment by gsnedders** [comment]
@bobholt As I said to @jgraham an hour ago, I don't think there's much worth is spending more time on reviewing this; my quick skim before didn't really find anything notable, and I doubt I'll find much more than what you have… though I'll inevitable find stuff in six months regardless of whether I review it now or not. :)

**Comment by gsnedders** [comment]
Reviewed 15 of 35 files at r1, 4 of 12 files at r2, 22 of 29 files at r3, 3 of 3 files at r4, 1 of 3 files at r5, 10 of 10 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6421)*

**Review by gsnedders — APPROVED** [review]

**Pull request merged**
