### PR TITLE
Split Selection API tests out of dom/ranges/Range-mutations.html

### PR DESCRIPTION
**Pull request by cdumez**
Move the Selection API tests to selection/Range-mutations.html instead as
they are not part of DOM.

This closes issue #3444.

### CODE REVIEW

**Comment by cdumez** [comment]
@annevk @ayg @rniwa r?

**Comment by Ms2ger** [comment]
This is duplicating a *lot* of code. I'd like to see a roughly even diffstat before landing this.

**Comment by annevk** [comment]
So you made a copy of the original file and removed the selection bits out of the original?

That is probably worth noting in the copy, that it duplicates some material that someone might want to clean up.

**Comment by cdumez** [comment]
Ok, I'll look into refactoring this so there is less code duplication.

**Comment by cdumez** [comment]
Superseded by https://github.com/w3c/web-platform-tests/pull/3453

**Pull request closed without merging**
