### PR TITLE
Test query encoding of attributes separately

### PR DESCRIPTION
**Pull request by annevk**
Helps with #4934.

### CODE REVIEW

**Comment by annevk** [comment]
Browser bugs needed: Firefox for background, ping; Safari for ping, Chrome for base, ping.

**Review by zcorpan — APPROVED** [review]
LGTM % nit

**Comment by annevk** [comment]
@zcorpan I actually think this test is wrong for the `ping` attribute. There's no requirements on reflecting space-separated URLs, so that would just fallback to reflecting a string, as I understand it.

**Comment by annevk** [comment]
I have now updated it test `ping` as a string reflected attribute. I also added tests for `<area>`.

**Comment by zcorpan** [comment]
Ah yeah, ping was changed in the spec at some point.

**Review by zcorpan — APPROVED** [review]

**Comment by annevk** [comment]
Bugs:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1464021
* https://bugs.chromium.org/p/chromium/issues/detail?id=846256

**Pull request merged**
