### PR TITLE
fix issues #4048 and #3524

### PR DESCRIPTION
**Pull request by louaybassbouss**
This PR fixes issues #4048 and #3524

### CODE REVIEW

**Comment by tidoust** [comment]
@louaybassbouss I took the liberty to commit minor editorial updates. PR looks good to me otherwise. I let you have a look at the updates I made and merge.

**Comment by louaybassbouss** [comment]
Thx @tidoust LGTM. BTW I just pushed a new commit that fixes issue #4041 (I wanted to submit a new PR for the new fix to make review easier but I pushed the new commit accidently in the same branch `presentation-api-bug-fixes`)

**Comment by tidoust** [comment]
I'll merge this PR. Not sure what you think you did wrong for #4041, @louaybassbouss but note the commit has not been added to this pull request: it appears on a `presentation-api-issue-4041` branch in your fork of the WPT repo, so you should be able to create another PR for it.

**Comment by louaybassbouss** [comment]
My mistake I will submit a new PR for the new changes

**Pull request merged**
