### PR TITLE
Throw a meaningful error if concurrent testdriver actions are used

### PR DESCRIPTION
**Pull request by LukeZielinski**
This addresses #10990.

### CODE REVIEW

**Comment by LukeZielinski** [comment]
The Azure failures seem pre-existing (`/infrastructure/testdriver/actions/actionsWithKeyPressed.html` is already failing on Mac).

**Comment by LukeZielinski** [comment]
@jugglinmike @gsnedders Ping, anyone mind taking a look at this?

**Review by gsnedders — CHANGES_REQUESTED** [review]
I don't think we want this in the wptrunner `testharnessreport.js`, even though this is where we actually have a queue here. We really want the behaviour to be the same regardless of the testdriver implementation in use (i.e., we want to also disallow concurrent actions within the Chromium tree, to avoid getting tests that relying on concurrent actions which do work there).

**Comment by LukeZielinski** [comment]
Ahh, I see. This still leaves the possibility of a test being written for a concurrency-capable executor that is broken on webdriver. So I guess we'd need to add something at a common layer like TestharnessExecutor, which currently has no idea about what commands are going back and forth. Any other ideas? At the very least, it doesn't sound like there's a trivial fix for this at the moment.

**Comment by jugglinmike** [comment]
This might be cause to revisit the idea of tolerating concurrent requests by queuing them in the client, as per gh-11202. Though that change has been contentious enough that I'd like to have a voice chat with @gsnedders and you, @LukeZielinski, to nail everything down.

**Pull request closed without merging**
