### PR TITLE
chore: update gbk decoder tests to be any.js

### PR DESCRIPTION
**Pull request by lucacasonato**
This changes the encoding/legacy-mb-schinese﻿ tests that do not require DOM (the decoding tests), to be .any.js tests so [Deno can run them in it's WPT suite](https://github.com/denoland/deno/pull/9242).

### CODE REVIEW

**Comment by annevk** [comment]
Do you have an idea as to why GitHub does not detect the first file as being renamed and slightly changed?

**Comment by annevk** [comment]
@achristensen07 fyi.

**Comment by annevk** [comment]
Maybe it's because you reformatted things slightly? Does your editor have a very short line length?

**Comment by lucacasonato** [comment]
The script in HTML was all intended. I removed the 1 tab indent, which is what caused all of the changes I assume.

**Comment by annevk** [comment]
I guess ignore whitespace changes is not smart enough to revisit the question of whether to show it as a single file.

**Review by annevk — APPROVED** [review]

**Pull request merged**
