### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by marcoscaceres**
Reduce to active owners.

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-22 01:31:37
Finished: 2018-01-22 01:35:48


<h2>Failing Jobs</h2>
<ul>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23068)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/331622845)

**Review by Ms2ger — COMMENTED** [review]
@edenchuang, @AmazingJaze, @MSFTkihan: please confirm

**Comment by Ms2ger** [comment]
Sorry, I meant @MSFTkihans

**Comment by MSFTkihans** [comment]
I think I'm slightly active? Or at least, I can be a bit more active in the coming month than I have been for the last several.

**Review by Ms2ger — CHANGES_REQUESTED** [review]
Sounds like MSFTkihans would prefer to stay.

**Comment by marcoscaceres** [comment]
> I think I'm slightly active? Or at least, I can be a bit more active in the coming month than I have been for the last several.

Ah, great to hear. I'd thought you'd moved on to other fun things.

**Review by sideshowbarker — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@Ms2ger, can you kindly unblock this.

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
