### PR TITLE
Add support for // META: spec=url to satisfy MISSING-LINK

### PR DESCRIPTION
**Pull request by lukebjerring**
Fixes https://github.com/w3c/web-platform-tests/issues/5770.

- Whitelists `// META: spec=url` as a valid `META` tag (stops `UNKNOWN-METADATA`)
- Surfaces `url` from the above expression in the set of `SourceFile.spec_links`

Note that this does not affect what is considered a valid link; opened https://github.com/w3c/web-platform-tests/issues/10288 to cover that.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10289)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26796)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/361808808)

**Review by foolip — APPROVED** [review]
LGTM % documentation. Perhaps a line at the bottom of http://web-platform-tests.org/writing-tests/testharness.html#multi-global-tests would suffice, and perhaps this form+example in http://web-platform-tests.org/writing-tests/css-metadata.html?

Leaving http://web-platform-tests.org/writing-tests/lint-tool.html for https://github.com/w3c/web-platform-tests/issues/5299 seems fine.

**Comment by foolip** [comment]
And, uh, not quite sure what to make of this Travis failure: https://travis-ci.org/w3c/web-platform-tests/jobs/361820644

**Comment by gsnedders** [comment]
The point of this lint it to ensure that the CSS build system can find the tests; as such, for this to make sense, the CSS build system also needs to be updated to support it.  Note that the biggest use of the CSS build system is on test.csswg.org/, and that doesn't even use wptserve so `*.any.js` and similar tests don't work there at all.

**Comment by gsnedders** [comment]
So I guess the question is really: Should we add a second, more explicit lint to disallow *.any.js and *.window.js?

**Comment by lukebjerring** [comment]
re: supporting it in the CSS build, is it sufficient to output `<link rel="help" href="url">` tags in the generated HTML?

re: not allowing *.any.js etc. I'm not fussed; it essentially solves the MISSING-LINK problem via forcing to an html version for which the lint can be appeased. Of course, that makes this PR redundant. Feel free to send a PR.

**Comment by lukebjerring** [comment]
Closing, as this approach opens a can of worms. Better to improve the docs and remove the 2 `.any.js` whitelisted items in favour of `.html`

**Pull request closed without merging**
