### PR TITLE
Update Safari Technology Preview to 102

### PR DESCRIPTION
**Pull request by autofoolip**
Version as reported by safaridriver --version:
Included with Safari Technology Preview (Release 102, 15610.1.5.2)

Source: https://developer.apple.com/safari/download/
Build: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1504&view=logs

### CODE REVIEW

**Comment by KyleJu** [comment]
Release notes: https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by KyleJu** [comment]
Looks like an infra failure. @foolip would you mind taking a look?

Unexpected Results
------------------
/infrastructure/assumptions/allowed-to-play.html
  UNEXPECTED-PASS <video> autoplay
ERROR Unsupported test type crashtest for product safari
 1:36.29 INFO Closing logging queue
 1:36.30 INFO queue closed

##[error]Bash exited with code '1'.

**Comment by foolip** [comment]
Excellent, looks like an infrastructure test has been begun passing. Just need to update expectations.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/22117.

**Pull request closed without merging**
