### PR TITLE
[testharness.js] Get title from the filename if not given

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm a little confused about the `get_title()` function; each caller only uses one of the three separate branches, so why not inline the code?

**Comment by zcorpan** [comment]
In the window case, there might not be a title. But can inline "Untitled" for the shell case.

**Review by Ms2ger — APPROVED** [review]
Fair point.

**Comment by zcorpan** [comment]
The failing check is because of https://github.com/web-platform-tests/wpt/pull/11405

**Comment by Ms2ger** [comment]
We can test the META feature, can't we?

**Comment by zcorpan** [comment]
Yes, done.

**Comment by zcorpan** [comment]
@Ms2ger OK to merge?

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
