### PR TITLE
Add WebGL conformance 1.0.0 test suite

### PR DESCRIPTION
**Pull request by emilio**
This allows to run the full WebGL conformance 1.0.0 test suite from WPT.

There are a few files that could be removed still (mostly READMEs and test lists). I don't think they're a problem though.

cc: https://github.com/KhronosGroup/WebGL/issues/1105

### CODE REVIEW

**Comment by tobie** [comment]
Reviewers for this pull request are: @w3c/webgl-reviewers.

**Comment by ecoal95** [comment]
cc: @Ms2ger @jdm

**Comment by ecoal95** [comment]
Closing for now, I'll make another one with the 1.0.3 test suite.

**Comment by jdm** [comment]
Note: the downside of the 1.0.3 suite is that there are a bunch of infrastructure changes and it seems to get updates pretty regularly. It might make sense to start with 1.0.1.

**Comment by ecoal95** [comment]
@jdm: Actually, seeing https://github.com/KhronosGroup/WebGL/tree/master/conformance-suites/1.0.3/conformance, it doesn't seem so.

The last change was 12 days ago, but it was untouched for some months, and really minor changes.

**Comment by jdm** [comment]
Ok, go for it!

**Pull request closed without merging**
