### PR TITLE
Load Ahem as web font in vars-font-shorthand-001.html

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@LukeZielinski this test appears to predate your Ahem rewrite. Can you check why this test was missed and if there are any more like it?

**Comment by LukeZielinski** [comment]
Ok, so this test sets a variable to "ahem" and then sets font-family to that variable. Not sure there's any reasonable way to grep for that, and there very well might be more tests like this.

I plan to do a final sweep where I update the WPT code to disable installing ahem completely and then see what breaks on CI. That should catch cases like this.

**Comment by foolip** [comment]
@LukeZielinski can you also review this change?

**Review by LukeZielinski — APPROVED** [review]
lgtm

**Pull request merged**
