### PR TITLE
[css-ruby] Improved a bit block-ruby-001 test

### PR DESCRIPTION
**Pull request by TalbotG**
http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/block-ruby-001-ref-GT.html

This is a followup to [Issue 29486](https://github.com/web-platform-tests/wpt/issues/29486) .

### CODE REVIEW

**Review by upsuper — CHANGES_REQUESTED** [review]
This change at least broke the first test case in this file.

While wpt.fyi states that the test failed previously and still fails after this PR on Firefox, they look the same locally before the change, but notably different after. If you look into wpt.fyi's visual comparisons ([master](https://wpt.fyi/analyzer?screenshot=sha1%3A5b48ca7e7e71043a7a526a96ab854c7c757ac3a5&screenshot=sha1%3A4ffa5170fa259ab6cd0376d2f2999805e4d99337) vs. [your change](https://wpt.fyi/analyzer?screenshot=sha1%3A0aef38dd74f2d4c4ee27278025ef65e40b882092&screenshot=sha1%3A5b48ca7e7e71043a7a526a96ab854c7c757ac3a5)) you should see the same issue. I'm not sure what's wrong with it currently, though.

**Comment by TalbotG** [comment]
> This change at least broke the first test case in this file.

Adding `margin: 1em 0em; ` at line 14 of the test caused this.
I need to work on the code tuning...

> While wpt.fyi states that the test failed previously and still fails after this PR on Firefox, they look the same locally before the change, but notably different after. If you look into wpt.fyi's visual comparisons ([master](https://wpt.fyi/analyzer?screenshot=sha1%3A5b48ca7e7e71043a7a526a96ab854c7c757ac3a5&screenshot=sha1%3A4ffa5170fa259ab6cd0376d2f2999805e4d99337) vs. [your change](https://wpt.fyi/analyzer?screenshot=sha1%3A0aef38dd74f2d4c4ee27278025ef65e40b882092&screenshot=sha1%3A5b48ca7e7e71043a7a526a96ab854c7c757ac3a5)) you should see the same issue. I'm not sure what's wrong with it currently, though.

This may be more difficult... I'll work on this later this month..

**Comment by TalbotG** [comment]
@web-platform-tests/wpt-core-team

I do not understand the wpt-firefox-nightly-stability failure. I loaded the test and the reference in Firefox nightly 93.0a1 BuildID=20210830162701 and they visual-compare identically.

Q1: "Test results: FAIL: 5/10, PASS: 5/10": what does that mean?

Q2: How to view the visual differences?

**Comment by TalbotG** [comment]
@web-platform-tests/admins

Dear fellow advanced GitHub colleagues,

These are the files in e879b2f commit and in f82a1cd:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-verify.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/block-ruby-001-ref-verify.html

When I load these in Firefox 93.0a1 buildID=20210831093704 , I see no difference, just a perfect pixel-for-pixel match.

Please explain the check failure in wpt-firefox-nightly-stability .

@upsuper , do you see any difference with a recent nightly of Firefox?

**Comment by upsuper** [comment]
I suspect this is because of lack of Japanese fonts on the machines running the tests, but I have no idea why it sometimes shows the unknown character box, but black em box other times. How can an unknown character show a black em box actually...

**Comment by TalbotG** [comment]
> I suspect this is because of lack of Japanese fonts on the machines running the tests

That is indeed a plausible explanation. Later this month or next month, I will try - in another separate and distinct PR - to replace the Japanese characters with Latin characters and see if it passes all the Continuous Integration checks.

**Comment by upsuper** [comment]
I would actually hope that the machine running the tests to actually include Japanese fonts (among fonts of other languages), since certain tests make more sense when being used in the context they are designed for.

**Comment by himorin** [comment]
> I would actually hope that the machine running the tests to actually include Japanese fonts (among fonts of other languages), since certain tests make more sense when being used in the context the corresponding features are designed for.

In some tests over Japanese (or CJK, arabic, etc.) character specific feature, there are line to include font files within [fonts directory](https://github.com/web-platform-tests/wpt/tree/master/fonts). (but some tests seem to fail due to lack of these lines... e.g. #32236 )

**Comment by TalbotG** [comment]
Hello @upsuper , @himorin  and @jgraham ,

I have read all of your useful + helpful comments and constructive suggestions. I will add
```
  @font-face
  {
  font-family: "mplus-1p-regular";
  src: url("/fonts/mplus-1p-regular.woff") format("woff");
  }

```
into both test and refererence and I will resubmit them accordingly in a few min.
I believe it is worth noting that mplus-1p-regular.woff is a 784.5 Kilo-bytes file but I guess this should not affect screenshot comparison.

**Comment by TalbotG** [comment]
Closing this PR.. Please go to https://github.com/web-platform-tests/wpt/pull/33271 instead

**Pull request closed without merging**
