### PR TITLE
[wasm] sync module-builder and constants

### PR DESCRIPTION
**Pull request by xtuc**
see https://github.com/WebAssembly/spec/pull/944 cc @Ms2ger

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]

**Comment by Ms2ger** [comment]
CI is failing to download Firefox. CC @foolip @jgraham

**Review by titzer — COMMENTED** [review]
Comments on the current state; I realize that this is just a merge over from the spec repo (or should be). But I gotta record the comments somewhere.

**Comment by xtuc** [comment]
@titzer yes that's just a merge from the WebAssembly spec repo.

The files are as close as possible from v8's ones, without some experimental Wasm features. I can open a crbug, update them in v8 and re-sync back in the repos. Does it make sense to you?

**Comment by titzer** [comment]
That sounds fine to me. Given all the new proposals coming in, it's clear that more work on the module builder stuff upcoming. It's got a baroque interface, and I'm partly responsible for it. Fine to land as is.

File a complaint to me :-)

**Review by Ms2ger — APPROVED** [review]

**Comment by xtuc** [comment]
Is this ready to merge?

**Pull request merged**
