### PR TITLE
Remove Chrome's unified plan flag (now on by default)

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@henbos can you confirm that this is no longer needed with Chrome 72?

**Comment by foolip** [comment]
Added in https://github.com/web-platform-tests/wpt/pull/13795.

**Comment by henbos** [comment]
This did indeed ship in M72, but it shipped through an experiment making it 100% enabled (otherwise off by default). I don't know how the bots run Chrome, but a fresh install might need to be restarted before experiments are run, otherwise wait for M73 stable? Though if you are running Beta then you're good to go already.

**Comment by henbos** [comment]
Wait you're running Dev? Go ahead and remove the special flag.

**Comment by foolip** [comment]
@henbos please approve or I'd have to admin merge :)

**Review by gsnedders — APPROVED** [review]
r+ based on @henbos's comment.

**Pull request merged**
