### PR TITLE
[testharness.js] add "Unhandled rejection" to error message

### LINKED ISSUE #19021: Message for unhandled promise rejection is not very helpful
In https://github.com/web-platform-tests/wpt/issues/18932 there was a harness error that said "The user aborted a request" or "The operation was aborted". This turned out to be because of an unhandled promise rejection and fixed in https://github.com/web-platform-tests/wpt/pull/19001.

That it was an unhandled promise rejection wasn't at all clear. That's because the handling of this is to simply use `event.reason.message` as the message:
https://github.com/web-platform-tests/wpt/blob/152adb0185fcfa41ef244355b275a197c3c45f55/resources/testharness.js#L3368-L3399

Prefixing the error with "Unhandled rejection" would really help.

@web-platform-tests/wpt-core-team for opinions.

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt/issues/19021.

### CODE REVIEW

**Comment by foolip** [comment]
https://wpt.fyi/results/infrastructure/expected-fail/unhandled-rejection.html?label=pr_head&max-count=1&pr=19092 shows that this had the intended effect.

I'll do a full run of Chrome to see how often "Unhandled rejection: " shows up.

**Comment by foolip** [comment]
https://tools.taskcluster.net/groups/CoVDvlG_QU25ZDMEnTasMg

**Comment by foolip** [comment]
https://wpt.fyi/results/?diff&filter=ADC&q=is%3Adifferent&run_id=307180008&run_id=307190004 suggests no regressions, there are small differences that are likely flakiness.

**Comment by foolip** [comment]
https://storage.googleapis.com/wptd-results/b6f4f997e209c5741b7b85d70bb98d1c474a91df/chrome-78.0.3904.17_dev-linux-18.04-dbd202a9b8/report.json is the full report and the string "Unhandled rejection: " appears 89 times. That's a bit fewer than I thought, but anyway this clearly works.

**Comment by foolip** [comment]
@Ms2ger for review?

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
