### PR TITLE
fix(payment-request): ctor should be missing, not SecurityError

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by bentian — APPROVED** [review]
LGTM. Also verified with current Moz implementation.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254330157)

# Firefox (nightly) #
Testing web-platform-tests at revision 152ab9671829b516862930076ce5c17e77fa669b
Using browser at version BuildID 20170716100258; SourceStamp b4e656e5a996dd385e9af43a4d9e207553377c51
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6566/payment-request/payment-request-update-event-constructor.http.html">/payment-request/payment-request-update-event-constructor.http.html</a></summary>


|                                     Subtest                                     | Results | Messages |
|---------------------------------------------------------------------------------|---------|----------|
|                                                                                 | OK      |          |
| `PaymentRequestUpdateEvent constructor must not be exposed in insecure context` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254330158)

# Sauce (safari) #
Testing web-platform-tests at revision 152ab9671829b516862930076ce5c17e77fa669b
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6566/payment-request/payment-request-update-event-constructor.http.html">/payment-request/payment-request-update-event-constructor.http.html</a></summary>


|                                     Subtest                                     | Results | Messages |
|---------------------------------------------------------------------------------|---------|----------|
|                                                                                 | OK      |          |
| `PaymentRequestUpdateEvent constructor must not be exposed in insecure context` | PASS    |          |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254330164)

# Chrome (unstable) #
Testing web-platform-tests at revision 7a43fbeda5d21ea685f71192659403d387251140

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254330165)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 7a43fbeda5d21ea685f71192659403d387251140

**Comment by marcoscaceres** [comment]
@sideshowbarker, can you please merge?

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
