### PR TITLE
[geometry] Test WebKitCSSMatrix and add historical.html

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5780/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228691690)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d9fffd711f995fda4065ebf05c32cae796dd57eb
Using browser at version BuildID 20170503100422; SourceStamp 82c2d17e74ef9cdf38a5d5ac4eb3ae846ec30ba4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>3 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5780/css/geometry-1/WebKitCSSMatrix.html">/css/geometry-1/WebKitCSSMatrix.html</a></summary>


|                  Subtest                  | Results |                                                                                 Messages                                                                                 |
|-------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                           | OK      |                                                                                                                                                                          |
| `Equivalence test`                        | FAIL    | `assert_equals: interface object expected function "function DOMMatrix() {\n    [native code]\n}" but got function "function WebKitCSSMatrix() {\n    [native code]\n}"` |
| `Property descriptor for WebKitCSSMatrix` | PASS    |                                                                                                                                                                          |
| `Property descriptor for DOMMatrix`       | PASS    |                                                                                                                                                                          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5780/css/geometry-1/WebKitCSSMatrix.worker.html">/css/geometry-1/WebKitCSSMatrix.worker.html</a></summary>


|           Subtest           | Results | Messages |
|-----------------------------|---------|----------|
|                             | OK      |          |
| `WebKitCSSMatrix in worker` | PASS    | `{}`     |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5780/css/geometry-1/historical.html">/css/geometry-1/historical.html</a></summary>


|                              Subtest                              | Results |                       Messages                       |
|-------------------------------------------------------------------|---------|------------------------------------------------------|
|                                                                   | OK      |                                                      |
| `DOMMatrixReadOnly scaleNonUniform must be nuked`                 | FAIL    | `assert_false: on prototype expected false got true` |
| `DOMMatrix scaleNonUniformSelf must be nuked`                     | FAIL    | `assert_false: on prototype expected false got true` |
| `DOMMatrix multiplyBy must be nuked`                              | PASS    |                                                      |
| `DOMMatrix preMultiplyBy must be nuked`                           | PASS    |                                                      |
| `DOMMatrix translateBy must be nuked`                             | PASS    |                                                      |
| `DOMMatrix scaleBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix scale3dBy must be nuked`                               | PASS    |                                                      |
| `DOMMatrix scaleNonUniformBy must be nuked`                       | PASS    |                                                      |
| `DOMMatrix rotateBy must be nuked`                                | PASS    |                                                      |
| `DOMMatrix rotateFromVectorBy must be nuked`                      | PASS    |                                                      |
| `DOMMatrix rotateAxisAngleBy must be nuked`                       | PASS    |                                                      |
| `DOMMatrix skewXBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix skewYBy must be nuked`                                 | PASS    |                                                      |
| `DOMMatrix fromString static member must be nuked`                | PASS    |                                                      |
| `DOMMatrixReadOnly fromString static member must be nuked`        | PASS    |                                                      |
| `DOMMatrixReadOnly scale number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix scaleSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly translate number of required arguments`        | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrixReadOnly scale3d number of required arguments`          | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly rotateFromVector number of required arguments` | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrixReadOnly rotateAxisAngle number of required arguments`  | FAIL    | `assert_equals: on prototype expected 0 but got 4`   |
| `DOMMatrixReadOnly skewX number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrixReadOnly skewY number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix translateSelf number of required arguments`            | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrix scale3dSelf number of required arguments`              | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix rotateFromVectorSelf number of required arguments`     | FAIL    | `assert_equals: on prototype expected 0 but got 2`   |
| `DOMMatrix rotateAxisAngleSelf number of required arguments`      | FAIL    | `assert_equals: on prototype expected 0 but got 4`   |
| `DOMMatrix skewXSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix skewYSelf number of required arguments`                | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMPointReadOnly matrixTransform number of required arguments`   | FAIL    | `self[interf].prototype[member] is undefined`        |
| `DOMMatrixReadOnly multiply number of required arguments`         | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix multiplySelf number of required arguments`             | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `DOMMatrix preMultiplySelf number of required arguments`          | FAIL    | `assert_equals: on prototype expected 0 but got 1`   |
| `CSSMatrix must be nuked`                                         | PASS    |                                                      |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/228691696)

# Chrome (unstable channel) #

**Review by foolip — APPROVED** [review]
There are conflicts, but LGTM.

**Comment by zcorpan** [comment]
Resolved the conflict. Can merge when the checks are green.

**Pull request merged**
