### PR TITLE
HTML: set location.protocol to broken schemes

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/url/issues/61 for context.

### CODE REVIEW

**Comment by annevk** [comment]
Note: this requires some changes to the URL Standard that the HTML Standard has forever anticipated. PR coming up for that.

**Comment by annevk** [comment]
It might be worth testing these broken schemes inside a data URL `<iframe>` as well and maybe an `<iframe srcdoc>`. So please don't land straight away.

**Comment by annevk** [comment]
https://github.com/whatwg/url/pull/194 is the change to the URL Standard by the way. This is ready to land now.

**Comment by domenic** [comment]
These all fail in Chrome and Firefox because of the exception type, right? I think we should change it to SyntaxError DOMException in the tests and spec before merging; no need to churn browsers over this detail.

**Comment by annevk** [comment]
Well Firefox needs a change anyway since it's not "SyntaxError" there but rather some internal thing. I guess we can decide to align with Chrome, but it seems a little weird since we use TypeError normally for URL parsing issues.

**Comment by domenic** [comment]
Hmm. Edge also has a weird `Error` instead of any normal error type. Safari matches Chrome though. I guess I do not feel strongly, but I do note the following places that use "SyntaxError" DOMExceptions for URL parsing failures:

- location.assign/location.replace
- registerProtocolHandler/registerContentHandler
- EventSource constructor
- WebSocket constructor
- window.postMessage origin parser
- Worker/SharedWorker constructor
- importScripts

**Comment by annevk** [comment]
Okay, I will give up, but not today, dinner time!

**Comment by annevk** [comment]
This is now ready to land.

**Pull request merged**
