### PR TITLE
Update assert, help, reviewer and titles to match current ouput of w3c/woff2-tests

### PR DESCRIPTION
**Pull request by fred-wang**
The following command was applied: sed -i 's/<link  rel="reviewer"/<link rel="reviewer"/' *.xht
More documentation update has also been performed.

This matches the current test documentations at https://github.com/w3c/woff2-tests

### CODE REVIEW

**Comment by fred-wang** [comment]
@svgeesus I suspect the only reason travis is failing is because there are two many files changed (603) so the tests take too long to run. If necessary, I can split the patch into smaller PRs.

**Review by svgeesus — APPROVED** [review]
Yes, looks fine.

**Comment by fred-wang** [comment]
@jgraham It looks like travis fails because the CL modifies too many tests and the Firefox bot times out. How would be the proper way to land this change?

**Comment by fred-wang** [comment]
cc @gsnedders

**Pull request merged**
