### PR TITLE
Fix WebRTC test use of Resolver after PR 14417

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by alvestrand** [comment]
Exactly the same fixes should have been uplifted from Chrome, so @youennf needs to check whether he needs to rebase. @henbos to help.

**Comment by henbos** [comment]
This is what I fixed: https://chromium-review.googlesource.com/c/chromium/src/+/1396140

**Comment by youennf** [comment]
One change was not made in the Chromium patch.
Rebased patch accordingly, @henbos, could you take a look?

**Review by henbos — APPROVED** [review]
LGTM

**Pull request merged**
