### PR TITLE
Two tools-related doc fixes

### PR DESCRIPTION
**Pull request by jeffcarp**
- Fix a broken link to lint-tool.md
- Replace mention of wpt-tools repo with tools/ directory

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5744)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5744/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227653515)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 46cfa7175736db0cdac161bf04863089ad4a581b
Using browser at version BuildID 20170430100638; SourceStamp 2fe636103d7167f3a5d57f61bd19fddcc878ca3c
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227653521)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 46cfa7175736db0cdac161bf04863089ad4a581b

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/5744)*

**Pull request merged**
