### PR TITLE
Run the results jobs when idlharness.js changes

### PR DESCRIPTION
**Pull request by lukebjerring**
Includes https://github.com/web-platform-tests/wpt/pull/18382 temporarily to fully test the behaviour.

### CODE REVIEW

**Review by jgraham — APPROVED** [review]
Subject to removing earlier commit

**Comment by lukebjerring** [comment]
@jgraham - I've totally changed this PR, as per discussion, it makes sense to distinguish the single run job from stability for the idlharness.js case.

PTAL

**Review by foolip — APPROVED** [review]
This looks reasonable to me, but I'd like to hear if @jgraham has more feedback. When I was setting up Azure Pipelines I think I suggested introducing an `affected_tests` job, but ended up making the jobs unconditional instead.

I wonder if we should change Azure Pipelines to use this new job as well, or make unconditional on Taskcluster too? (Need not block this change.)

**Comment by gsnedders** [comment]
Does it really not timeout running the stability job for `idlharness.js`? Huh.

**Comment by lukebjerring** [comment]
No, you're right, it does time out, which is why this change distinguishes single run from stability for including idlharness.js.

**Comment by gsnedders** [comment]
Gah. I can't read. 🙂

This looks reasonable to me too.

**Comment by lukebjerring** [comment]
Taskcluster failure is https://github.com/web-platform-tests/wpt/issues/19297

**Pull request merged**
