### PR TITLE
[css-text-decor] Add parsing tests for text-decoration-line

### PR DESCRIPTION
**Pull request by mrego**

### CODE REVIEW

**Comment by mrego** [comment]
This is a parsing text for `text-decoration-line` based on the ones done by @ericwilligers in other specs.

My only doubt is regarding things like `text-decoration-line: overline underline`, what should be the specified value in that case?

[The property definition says](https://drafts.csswg.org/css-text-decor-4/#text-decoration-line-property):
> Canonical order: per grammar

And I found this text in [CSSOM spec](https://drafts.csswg.org/cssom/#serializing-css-values):
> If certain component values can appear in any order without changing the meaning of the value (a pattern typically represented by a double bar || in the value syntax), reorder the component values to use the canonical order of component values as given in the property definition table.

So I understand that the right answer is `underline overline`.

That's what these tests are checking, and the ones with different order fail in Chromium/WebKit while they pass in Firefox. If actually the order doesn't matter and it could be either `overline underline` or `underline overline` then I'd need to update the tests accordingly.

Could someone clarify this topic? Thanks!

CC @frivoal @emilio

**Comment by emilio** [comment]
> That's what these tests are checking, and the ones with different order fail in Chromium/WebKit while they pass in Firefox. If actually the order doesn't matter and it could be either overline underline or underline overline then I'd need to update the tests accordingly.

The order is supposed to matter. Firefox is right here.

**Review by ewilligers — APPROVED** [review]
I'll fix Blink.

**Comment by mrego** [comment]
> I'll fix Blink.

I've a patch already. :)

**Pull request merged**
