### PR TITLE
Add PaymentRequest constructor tests

### PR DESCRIPTION
**Pull request by sideshowbarker**
This is from Chromium [third_party/WebKit/LayoutTests/payments/payment-request-interface.html](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/LayoutTests/payments/payment-request-interface.html) and so has already been reviewed upstream; however:
- 129 of the 157 tests here pass in Firefox & Safari despite the fact that neither those UAs yet implement PaymentRequest…
- some of the tests here are redundant with IDL tests in [interfaces.https.html](https://w3c-test.org/submissions/3439/payment-request/interfaces.https.html) (which is the proper place to instead be testing the IDL conformance)

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/3441)

### CODE REVIEW

**Comment by halindrome** [comment]
Love it.  In particular the spec text.  It would be awesome if there were a reasonable way to just have pointers into the spec.  Not for right now, but let's define something declarative that will just augment the test definitions with links at runtime?

Otherwise, LGTM so far

**Comment by sideshowbarker** [comment]
> It would be awesome if there were a reasonable way to just have pointers into the spec. Not for right now, but let's define something declarative that will just augment the test definitions with links at runtime?

I think the CSS WG test suite has something like that but I am not sure it’s a feature we are going to support in wpt. @gsnedders might know more.

**Comment by sideshowbarker** [comment]
@halindrome A couple things I could still use some review help with on these constructor tests:

A. identify (and remove) any tests that do not actually map to requirements in the spec
B. identify (and remove) any tests that are actually (better) covered in the [interfaces.html IDL tests](https://github.com/w3c/web-platform-tests/blob/master/payment-request/interfaces.https.html)

Or for _A_ at least I think we need to do more to make it clear in the test names which requirements in the spec are being tested. So far, for some of the tests I have not been able to determine which requirements in the spec they are testing.

**Comment by sideshowbarker** [comment]
@halindrome See the related https://github.com/w3c/browser-payment-api/issues/235 that I just filed.

For the `currency` tests, since [the spec states, “any string is considered valid”](https://w3c.github.io/browser-payment-api/#dfn-currency), it seems to me we need to change the test expectation to be that the UA does *not* throw—that is, the opposite of the current test expectation. (Which incidentally also means that Chrome will fail the test since it doesn’t conform to that spec requirement.)

But please let me know if I’m misunderstanding something.

**Comment by sideshowbarker** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=636723 for the `currency` issue.

**Comment by gsnedders** [comment]
@sideshowbarker csswg-test doesn't have anything beyond the fragment level (with `<link rel="help">`), which also doesn't really work for `testharness.js`.

**Comment by gsnedders** [comment]
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

**Comment by marcoscaceres** [comment]
Need to review these still - but it's great to have something down... I suspect the spec will change quite a bit as Firefox's engineering teams start implementing the spec. 

How should we best handle that? Just take what we have so far and update them as we go?

**Comment by halindrome** [comment]
I am open to that.  I wonder what the WPT powers that be think?  @jgraham ? @gsnedders ? If there are tests that are in development for a spec that is in development, what is the best way to get them into the system so they get exposure?

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by marcoscaceres** [comment]
I spoke to @jgraham about a month ago about this... he told me that we should actually land the tests through Gecko instead... and then they would end up here automagically. And the same would happen on the Blink side, presumedly. 

So we should close this PR and start sending tests via the engines instead. Is my understanding correct?

**Comment by sideshowbarker** [comment]
> So we should close this PR and start sending tests via the engines instead. Is my understanding correct?

Let’s please keep this open until the Gecko tests get hoisted to here

**Pull request closed without merging**
