### PR TITLE
Add tests for CEReactions on HTML Media Capture

### PR DESCRIPTION
**Pull request by Honry**
And introduce a common function to create customized build in element

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20194)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/297822589)

**Review by domenic — APPROVED** [review]
LGTM, although there are two additional useful tests:

- Setting the property to "asdf" causes an attributeChanged with new value "asdf"
- Setting the property to null causes an attributeChanged with the new value null, i.e. removes the attribute.

**Comment by Honry** [comment]
@domenic, thanks for your review and suggestion.

>Setting the property to "asdf" causes an attributeChanged with new value "asdf"

"asdf" is a kind of [ invalid value default ](https://www.w3.org/TR/html51/infrastructure.html#invalid-value-default), useful test. 👍 
>Setting the property to null causes an attributeChanged with the new value null, i.e. removes the attribute.

Setting the property to null doesn't mean removing the attribute for 'capture' attribute, we can setting [missing value default](https://www.w3.org/TR/html51/infrastructure.html#missing-value-default), i.e. empty string. WDYT?

**Comment by domenic** [comment]
Setting it to null should remove the attribute. The spec says it reflects, and per https://html.spec.whatwg.org/#reflect,

> If a reflecting IDL attribute is a nullable DOMString attribute whose content attribute is an enumerated attribute, then, on getting, if the corresponding content attribute is in its missing value default then the IDL attribute must return null, otherwise, the IDL attribute must return the conforming value associated with the state the attribute is in (in its canonical case). **On setting, if the new value is null, the content attribute must be removed**, and otherwise, the content attribute must be set to the specified new value.

**Comment by Honry** [comment]
But the "capture" is not a **nullable DOMString** attribute.
>partial interface HTMLInputElement {
    [CEReactions]
    attribute DOMString capture;
};

I think following piece of spec should be reflected: 
>If a reflecting IDL attribute is a DOMString attribute whose content attribute is an enumerated attribute, and the IDL attribute is limited to only known values, then, on getting, the IDL attribute must return the conforming value associated with the state the attribute is in (in its canonical case), if any, or the empty string if the attribute is in a state that has no associated keyword value or if the attribute is not in a defined state (e.g. the attribute is missing and there is no missing value default). On setting, the content attribute must be set to the specified new value.

**Comment by domenic** [comment]
Hmm, so what's confusing is the spec doesn't say it's limited to known values. So it actually falls into

> If a reflecting IDL attribute is a DOMString or USVString attribute but doesn't fall into any of the above categories, then the getting and setting must be done in a transparent, case-preserving manner.

In that case setting it to null should cause the attribute to change to the string `"null"`.

(The invalid value default then causes this to behave as if it's in the implementation-specific state. But it should still change the attribute to the string `"null"`)

**Comment by domenic** [comment]
Anyway, in that case we're basically testing the reflection, which can be covered by other tests, not the CEReactions tests. So the tests LGTM to merge as-is.

**Comment by Honry** [comment]
@domenic, thanks! Merging it.

**Pull request merged**
