### PR TITLE
HTML: attempt at making it clearer what times out in a COOP test

### PR DESCRIPTION
**Pull request by annevk**
For https://bugzilla.mozilla.org/show_bug.cgi?id=1721310.

### CODE REVIEW

**Review by mikewest — APPROVED** [review]
TIL: `step_wait()`. Big improvement, thank you.

**Comment by annevk** [comment]
It's interesting how on this CI it now passes for Firefox, but apparently Chrome is getting timeouts. @foolip is this something you can help with?

**Comment by ArthurSonzogni** [comment]
> It's interesting how on this CI it now passes for Firefox, but apparently Chrome is getting timeouts. @foolip is this something you can help with?

Yes, it is flaky on Chrome.
Before going on vacation, I was on the verge of rewriting them:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1151555#c15
- https://chromium-review.googlesource.com/c/chromium/src/+/3035167

I will try finishing it next week.

Not entirely sure yet if this is currently flaky because of the test or because of Chromes's implementation thought.

**Comment by foolip** [comment]
I can't investigate (on vacation) but please ping @past or me if you determine we should ignore the failure and one of us can admin merge.

**Comment by annevk** [comment]
Thanks, I'm happy to wait to see what @ArthurSonzogni finds.

**Pull request closed without merging**
