### PR TITLE
Additional innertext tests

### PR DESCRIPTION
**Pull request by Melchizedek6809**
Hey, I've been working on implementing innerText for Servo and noticed that a couple of things aren't tested/specified, so I've added some tests:

1. `<object>` content should be ignored for innerText
2. It wasn't clear whether/how many lines should surround a `<p>` that's `display:block` or `display:inline-block`, both Firefox and Chrome surround them with 2 linebreaks which is a bit suprising, especially for `display:inline-block`.
3. How `<details>` and `<summary>` elements are handled.

### CODE REVIEW

**Comment by annevk** [comment]
https://html.spec.whatwg.org/#rendered-text-collection-steps seems to have an explicit check for the `p` elements, regardless of how it's displayed. Did you miss that or is that unclear in a way that I missed?

**Review by annevk — APPROVED** [review]
This looks fine, but please double check the algorithm.

**Comment by annevk** [comment]
And, thanks for writing these! Much appreciated.

**Comment by Melchizedek6809** [comment]
> https://html.spec.whatwg.org/#rendered-text-collection-steps seems to have an explicit check for the p elements, regardless of how it's displayed. Did you miss that or is that unclear in a way that I missed?

While reading it again it makes sense, somehow misread an either/or in between 8 and 9, and since it wasn't explicitly tested I got a bit unsure.

**Pull request merged**
