### PR TITLE
Adding more request/response consume tests, including empty body and blob body

### PR DESCRIPTION
**Pull request by youennf**
In addition to the new consume tests, this patch converts an ansyc test into a promise test. It also removes the use of TextDecoder API as it is not supported in all engines.

### CODE REVIEW

**Comment by jdm** [comment]
Left comments on Critic. Thanks!

**Comment by youennf** [comment]
Thanks for the review, I updated the patch accordingly.
Last commit made some additional clean-up.
As for ES6 features, arrow functions are already in use in WPT.

**Comment by jdm** [comment]
There have been PRs to remove them from other tests, though. I believe the rule of thumb is to avoid introducing new uses.

**Comment by youennf** [comment]
OK then.
Last commit removes arrow functions for the new tests as well as for one previously added test.

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
