### PR TITLE
Add tools and resources submodules into this repository.

### PR DESCRIPTION
**Pull request by jgraham**
See
https://github.com/w3c/testharness.js
https://github.com/w3c/wpt-tools

This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/5554)

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5554/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221748601)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 07611f455a16d1ffbd0b821624c29b8521a8eb82
Using browser at version BuildID 20170413100144; SourceStamp 819a666afddc804b6099ee1b3cff3a0fdf35ec15
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221748602)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 07611f455a16d1ffbd0b821624c29b8521a8eb82
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
No tests run.

**Comment by jgraham** [comment]
The CI failure here is just because the way we identify affected commits on the push CI doesn't cope with new roots being added to the repo. This is fixable ofc, but I'm not sure it's worthwhile to wait for that fix before landing this.

**Comment by gsnedders** [comment]
I have a slight preference for not changing the revision of the submodules at the same time as everything else for the sake of being able to bisect any breakage.

Also I thought the plan was to get rid of all of the submodules? Why are we readding the submodules within tools?

**Comment by jgraham** [comment]
The plan initially was to get rid of the sbmodules for things we control. Getting rid of all submodules is a reasonable second step (because no one loves submodules), but not part of the initial plan.

**Comment by gsnedders** [comment]
That means more points at which moving between checkouts is going to need forced. Ergh.

Do we have any note anywhere about needing to delete folders before checking out anywhere? That isn't exactly usual git workflow, so I think we should definitely have that.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/223500031)

# Lint #

Passed

**Comment by gsnedders** [comment]
What's currently on #5606 LGTM, though it does update resources (wpt master is missing https://github.com/w3c/testharness.js/commit/e7a80b151358184505514cc20e79444263656b92).

**Comment by jgraham** [comment]
Merged this in 39d07eb01

**Pull request merged**
