### PR TITLE
Tests for PaymentRequestUpdateEvent

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239856467)

# Firefox (nightly) #
Testing web-platform-tests at revision 9a817bbb231002014d5f4dc18ad77eb0706a987d
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6156/payment-request/payment-request-update-event-constructor.http.html">/payment-request/payment-request-update-event-constructor.http.html</a></summary>


|                                Subtest                                 | Results |                                                                                                                          Messages                                                                                                                         |
|------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                        | OK      |                                                                                                                                                                                                                                                           |
| `PaymentRequestUpdateEvent constructor throws in a non-secure context` | FAIL    | `assert_throws: function "() => {\n    new PaymentRequestUpdateEvent("test");\n  }" threw object "ReferenceError: PaymentRequestUpdateEvent is not defined" that is not a DOMException SecurityError: property "code" is equal to undefined, expected 18` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6156/payment-request/payment-request-update-event-constructor.https.html">/payment-request/payment-request-update-event-constructor.https.html</a></summary>


|                                          Subtest                                          | Results |                                                Messages                                               |
|-------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------|
|                                                                                           | OK      |                                                                                                       |
| `PaymentRequestUpdateEvent can be constructed in secure-context`                          | FAIL    | `assert_true: Unexpected exception: PaymentRequestUpdateEvent is not defined expected true got false` |
| `PaymentRequestUpdateEvent can be constructed with an EventInitDict, even if not trusted` | FAIL    | `PaymentRequestUpdateEvent is not defined`                                                            |
| `PaymentRequestUpdateEvent can be dispatched, even if not trusted`                        | FAIL    | `PaymentRequest is not defined`                                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239856468)

# Sauce (safari) #
Testing web-platform-tests at revision 9a817bbb231002014d5f4dc18ad77eb0706a987d
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6156/payment-request/payment-request-update-event-constructor.http.html">/payment-request/payment-request-update-event-constructor.http.html</a></summary>


|                                Subtest                                 | Results |                                                                                                                             Messages                                                                                                                            |
|------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                        | OK      |                                                                                                                                                                                                                                                                 |
| `PaymentRequestUpdateEvent constructor throws in a non-secure context` | FAIL    | `assert_throws: function "() => {\n    new PaymentRequestUpdateEvent("test");\n  }" threw object "ReferenceError: Can't find variable: PaymentRequestUpdateEvent" that is not a DOMException SecurityError: property "code" is equal to undefined, expected 18` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/6156/payment-request/payment-request-update-event-constructor.https.html">/payment-request/payment-request-update-event-constructor.https.html</a></summary>


|                                          Subtest                                          | Results |                                                   Messages                                                  |
|-------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------|
|                                                                                           | OK      |                                                                                                             |
| `PaymentRequestUpdateEvent can be constructed in secure-context`                          | FAIL    | `assert_true: Unexpected exception: Can't find variable: PaymentRequestUpdateEvent expected true got false` |
| `PaymentRequestUpdateEvent can be constructed with an EventInitDict, even if not trusted` | FAIL    | `Can't find variable: PaymentRequestUpdateEvent`                                                            |
| `PaymentRequestUpdateEvent can be dispatched, even if not trusted`                        | FAIL    | `Can't find variable: PaymentRequest`                                                                       |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239856474)

# Chrome (unstable) #
Testing web-platform-tests at revision c71e63689c0dc8400b556483e11ad606c3e60a33

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239856475)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c71e63689c0dc8400b556483e11ad606c3e60a33

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
