### PR TITLE
[wptrunner/chromium] De-dupe merged expected statuses

### PR DESCRIPTION
**Pull request by Hexcles**
Merge expected and known_intermittent into a set and sort it to produce
stable, unique expected statuses.

* known_intermittent from mozlog seems to always include the expected
status, so we could technically just discard "expected", but using a set
is easy enough and may better guard against future surprises.

### CODE REVIEW

**Comment by Hexcles** [comment]
An example: we see `Expected: FAIL FAIL TIMEOUT` in https://test-results.appspot.com/data/layout_results/linux-wpt-input-fyi-rel/15/wpt_tests_suite%20(with%20patch)/layout-test-results/results.html (under "unexpected passes")

**Comment by LukeZielinski** [comment]
> An example: we see `Expected: FAIL FAIL TIMEOUT` in https://test-results.appspot.com/data/layout_results/linux-wpt-input-fyi-rel/15/wpt_tests_suite%20(with%20patch)/layout-test-results/results.html (under "unexpected passes")

Note that I think the duplicate statuses here are the fault of wpt_metadata_builder, not the chromium formatter. That said, I don't oppose this change.

**Review by LukeZielinski — APPROVED** [review]

**Comment by Hexcles** [comment]
> Note that I think the duplicate statuses here are the fault of wpt_metadata_builder, not the chromium formatter. That said, I don't oppose this change.

That doesn't seem to be the case. And my guess might have also been inaccurate.

Running `build_wpt_metadata.py` locally, I got the following in `infrastructure/testdriver/actions/multiDevice.html.ini`:
```
[multiDevice.html]
  expected: [FAIL, ERROR, TIMEOUT]
```

So it seems that duplication is caused by status mapping? The fix still works; I'll update the unit test to capture this case.

**Comment by LukeZielinski** [comment]
> So it seems that duplication is caused by status mapping? The fix still works; I'll update the unit test to capture this case.

Yeah unfortunately there is status mapping happening in both wpt_metadata_builder and the chromium formatter, leading to a messy feedback loop :)
I think it looks something like this:
TestExpectations contains Failure
-> wpt_metadata_builder expands Failure to expected: [FAIL, ERROR]
-> wptrunner sets known_intermittent to [FAIL, ERROR] 
-> chromium formatter maps the ERROR back to FAIL
-> chromium json output contains expected [FAIL FAIL]

But agreed, the fix will help! :)

**Pull request merged**
