### PR TITLE
compressedTexSubImage2D test is wrong and not worth correcting.

### PR DESCRIPTION
**Pull request by kdashg**
We have extensive tests for this in the WebGL conformance suite, so it's hardly worth spending time correcting this trivial test here.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@jdashg given as you point out the [separate WebGL conformance suite](https://github.com/KhronosGroup/WebGL/tree/master/conformance-suites) that’s being actively maintained, maybe we should just remove entire webgl subdir from here. Or are there any other tests in that subdir here that you think we should keep?

**Comment by sideshowbarker** [comment]
This and the other webgl tests here came from @Ms2ger so I reckon he oughta be the one to review and merge this.

**Comment by jdashg** [comment]
I think it would be fine to have tests here for behavior outlined in the HTML spec, but to avoid testing behavior that's in the WebGL spec only. I think that's a good place to establish a split.

Certainly it's not worth repeating WebGL-specific tests here.

**Comment by Ms2ger** [comment]
https://github.com/KhronosGroup/WebGL/issues/1105 is relevant. Until that happens, I have no interest in reducing useful test coverage.

**Comment by jdashg** [comment]
Well, this test here is not useful test coverage, and has to-date cost us more than it has given us. Let's cut our losses here, and discuss your other proposal in its respective PR.

**Pull request closed without merging**
