### PR TITLE
Don't let AES-KW to wrap/unwrap JWK

### PR DESCRIPTION
**Pull request by stephenmcgruer**

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I have to mark this as non-draft, but will be removing reviewers after wpt-pr-bot adds them. Sorry for the spam.

**Comment by jimsch** [comment]
I do not believe that this is a correct modification to the tests.   Section 14.3.11 provides a method of converting a JWK to an object which can be encrypted.  Why do you believe this is not true?

**Comment by stephenmcgruer** [comment]
Sorry @jimsch , I failed to note above that this PR is a straight rebase of https://github.com/web-platform-tests/wpt/pull/6102, trying to see if an old change can be relanded (or really just what it's state is). The author at that time thought it was necessary, but it is over 1.5 years old now so may well be that the spec has moved on.

**Comment by stephenmcgruer** [comment]
Sgtm, left a comment in (and closed) https://github.com/web-platform-tests/wpt/pull/6102

**Pull request closed without merging**
