### PR TITLE
Annotation automated

### PR DESCRIPTION
**Pull request by halindrome**
As per request from @jgraham, removed support for "placeholder" tests and created a new PR.

Also rebased against the current W3C master to ensure easier merging.  WDYT @bigbluehat ?

### CODE REVIEW

**Comment by sideshowbarker** [comment]
This has a conflict in `annotation-model/tools/make_tests.py` that needs to be resolved:
```
<<<<<<< 4b40dcd67fa54129251849024211bfc520cc7797
template = open(TEMPLATE, "r").read()
=======
manualTemplate = open(MANUAL_TEMPLATE).read()
autoTemplate = open(JS_TEMPLATE).read()
>>>>>>> Support for automated JSON tests
```

**Comment by sideshowbarker** [comment]
Merged in https://github.com/w3c/web-platform-tests/commit/ec055915313d8251718168f169299a54a3ccfe72

Along with the conflict I mentioned in https://github.com/w3c/web-platform-tests/pull/3356#issuecomment-239605033 there were some other conflicts that I had to manually resolve before merging this. I am pretty sure I got it all right but please doublecheck.

**Comment by halindrome** [comment]
I will take a look - sorry about the confusion :/

**Comment by sideshowbarker** [comment]
> I will take a look - sorry about the confusion :/

No worries. Merge conflicts for wpt PRs are not uncommon but the longer a PR stays open unmerged the more likely it is to end up with (more) merge conflicts.

**Pull request closed without merging**
