### PR TITLE
Test parse-time HSL clamp of negative saturation to zero

### PR DESCRIPTION
**Pull request by svgeesus**
See

 - https://github.com/w3c/csswg-drafts/commit/be48b10d6514d9464ed5810f4961941a92209a70
 - https://github.com/w3c/csswg-drafts/issues/9222#issuecomment-1858984480

### CODE REVIEW

**Comment by dbaron** [comment]
Looks like it's not as interoperable as https://github.com/w3c/csswg-drafts/issues/9222#issuecomment-1858984480 suggests, since the new tests pass in Firefox but three of them fail in Chrome.  Is that expected?

**Comment by svgeesus** [comment]
> The new tests pass in Firefox but three of them fail in Chrome. Is that expected?

Not expected; the test values and expected values are [from a test you wrote](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/t424-hsl-clip-outside-gamut-b.xht) and the only difference is that your earlier CSS Color 3 test used legacy syntax, while the new addition to the CSS Color 4 test use modern syntax.

However I think the difference here is that Chrome is not accepting a mix of &lt;number> and &lt;percentage>, while Firefox is correctly allowing it for modern syntax. So that would be a Chrome bug.

**Comment by svgeesus** [comment]
Re-opened 

 - https://github.com/w3c/csswg-drafts/issues/9222#issuecomment-1917786373

**Comment by svgeesus** [comment]
@dbaron this is seemingly [a regression between Chrome 120 and Chrome 121](https://github.com/w3c/csswg-drafts/issues/9222#issuecomment-1917902146) but I have made this PR a draft so CSSWG can decide on what behavior we want before this test change lands/doesn't land.

**Review by dbaron — APPROVED** [review]
Based on discussion in https://github.com/w3c/csswg-drafts/issues/9222 this looks good.

**Pull request merged**
