### PR TITLE
Fix bugs in the matches() test.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by Ms2ger** [comment]
For reference: <https://bugzilla.mozilla.org/show_bug.cgi?id=1124652>.

**Comment by Ms2ger** [comment]
I extracted the first commit into https://github.com/w3c/web-platform-tests/pull/2267.

**Comment by cvrebert** [comment]
@Ms2ger Could you rebase this? I've likewise encountered the `scopedSelectors` bug.

**Comment by Ms2ger** [comment]
Remaining comments:
```
--------------------------------------------------------------------------------
358| * These selectors are intended to be used with the find() and findAll() methods.  Expected results
--------------------------------------------------------------------------------
Lachlan Hunt at 2015-01-28 23:27 +00:00:
  find() and findAll() were the names from the original Selectors API 2 draft.
  The DOM spec renamed these methods to query() and queryAll().

  I also couldn't find any actual test scripts for query() and queryAll().
  Those should be written one day.

--------------------------------------------------------------------------------
417| * expect.matches(selector, context)    // Only where refNodes is not specified
--------------------------------------------------------------------------------
Lachlan Hunt at 2015-01-28 23:07 +00:00:
  These documentation comments no longer accurately describe how the matches()
  tests are run because the spec no longer includes support for context/refNodes
  in matches.

  Since no matches() tests are run on the selectors below any more, it would be
  better to move this explanation for the TEST_MATCH type above the other tests
  that are run for it.


General issue:
  https://critic.hoppipolla.co.uk/showcomment?chain=10265
--------------------------------------------------------------------------------
Lachlan Hunt at 2015-01-28 23:07 +00:00:
  Element-matches.js still runs tests based on the assumption that matches()
  takes a second refNodes paramter.  You should probably also edit that script
  to remove that entirely.
```

**Comment by foolip** [comment]
@Ms2ger, can you rebase this if it's still relevant?

**Comment by Ms2ger** [comment]
I have no clue if it's still relevant. What do the test results look like for current browsers?

**Comment by foolip** [comment]
Looks pretty good: https://wpt.fyi/dom/nodes/Element-matches.html

By scrolling, I see only one test that is failing in all browsers: "In-document Element.matches: Universal selector, matching all descendants of the specified reference element (with refNode Element): *	"

**Review by fathi966 — COMMENTED** [review]
what this

**Comment by foolip** [comment]
@Ms2ger do you want to rebase this and get it landed, or abandon?

**Comment by Ms2ger** [comment]
If I haven't done anything a week from now, abandon.

**Comment by foolip** [comment]
A week has passed, closing. I suspect we'd find these same issues again by looking for tests that fail in all browsers.

**Pull request closed without merging**
