### PR TITLE
Consolidated fixes to character encoders/decoders

### PR DESCRIPTION
**Pull request by peteroupc**
Supersedes #11645, #11648, #11650, #11651, #11652.

### CODE REVIEW

**Review by inexorabletash — CHANGES_REQUESTED** [review]
Looks good but the change to line 49 in sjis-decoder.js in #11651 got dropped:

```
if (ptr != null && ptr >= 8836 && ptr <= 10715) {
```

**Comment by inexorabletash** [comment]
Also, thank you for going back and adding those missing `var`s !

**Review by inexorabletash — APPROVED** [review]

**Comment by inexorabletash** [comment]
Awesome, thank you! Waiting for the CI to complete before merging.

**Comment by inexorabletash** [comment]
Looks like the failure was due to missing META.yml lint check, and that lint check was reverted.

Let's see if we can re-run this...

**Comment by inexorabletash** [comment]
I'm really sorry about the delay here. Can you make a whitespace change or something to trigger a re-run?

**Comment by inexorabletash** [comment]
Thanks - now it just looks like it's hitting a timeout error (?) on the firefox?

@gsnedders - can you provide guidance here? These fixes shouldn't be dramatically altering the runtime of the tests.

**Comment by Hexcles** [comment]
Yeah there are too many affected tests. @inexorabletash would you mind mirroring the patch to Chromium to test it through a CQ dry run?

**Comment by inexorabletash** [comment]
Yeah, I'll give it a whirl. Poke me if I haven't reported back in a couple days.

**Comment by inexorabletash** [comment]
Passed locally - CL is up for a CQ run at: https://chromium-review.googlesource.com/c/chromium/src/+/1148994

**Comment by inexorabletash** [comment]
... and it passed on our CI. Do you want me to go ahead and land it from our side?

**Review by irwinnathan888-sketch — APPROVED** [review]

**Pull request merged**
