### PR TITLE
Fix cross-origin browser name test,

### PR DESCRIPTION
**Pull request by jgraham**
MozReview-Commit-ID: 49stqMka8j5

Upstreamed from https://bugzilla.mozilla.org/show_bug.cgi?id=1308969

### CODE REVIEW

**Comment by jgraham** [comment]
Code reviewed upstream.

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5076/)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979547)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208979548)

**Pull request merged**
