### PR TITLE
Added 5 css-pseudo tests and 2 references

### PR DESCRIPTION
**Pull request by TalbotG**
active-selection-057.html : empty `<div>`
active-selection-058.html : empty `<div>`
active-selection-059.html : `<hr>`
active-selection-060.html : `<hr>`
active-selection-061.html : `&NewLine;`
reference/ref-nothing-below.xht
reference/ref-filled-green-100px-square.xht

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
1. In the interests of keeping WPT slightly more efficient, I think all of these tests should be merged into a single file. As long as a group of tests are closely related enough that combining them would not make it harder to run the test or to understand the code, it is better to keep them in a single file. Here you can draw a single selection across all of the interesting content no problem.
2. You're referencing a bug about `<br>` but I see no test with a `<br>` here?

**Comment by TalbotG** [comment]
I will merge these tests into a single file. I will try to draw a single selection across all of the interesting content ... although ... I vaguely remember that I need to wrap all of the content inside a `<div>` otherwise Chromium will not obtemperate.

I will move the referencing of a bug about `<br>` from active-selection-061 into active-selection-026 test.

**Comment by TalbotG** [comment]
@fantasai ,
I just could not merge these 5 tests into a single test. It was too complicated. It was complicated to merge these 5 tests into 2 tests also. The assert text become painful to edit.

**Comment by TalbotG** [comment]
Over at my website, these 2 new tests are
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-057-new.html
and
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-058-new.html

**Comment by TalbotG** [comment]
After more reflexion, I think we need to remove the tests involving the painting of selected empty elements. An <hr> element has no text, therefore it should not be painted via a selection. So, I will be removing (in 10 min with a new commit) the active-selection-058.html test.

**Comment by Hexcles** [comment]
Could you try merging master to your branch, or rebasing your branch onto master?

**Comment by TalbotG** [comment]
@Hexcles 

> Could you try merging master to your branch

How to do this? I am a very beginner with github. I would need step-by-steps instructions.

> rebasing your branch onto master

Would [these steps achieve rebasing of my branch onto master](https://github.com/web-platform-tests/wpt/issues/20803#issuecomment-567208355) ?

**Comment by Hexcles** [comment]
Yeah that should do it!

**Comment by TalbotG** [comment]
Okay... So, just to be clear:

```
cd path/to/where/you/put/wpt
git status
If it comes clean, then
git reset --hard
git checkout master
git pull upstream master
git checkout CSS4Pseudo-GT-PR16
git rebase master
git push -f origin CSS4Pseudo-GT-PR16

```

**Comment by TalbotG** [comment]
There is a conflict after rebase master:

CONFLIT (ajout/ajout) : Conflit de fusion dans css/css-pseudo/reference/ref-nothing-below.xht
error: Échec d'intégration des modifications.
le patch a échoué à 0001 Added 5 css-pseudo tests and 2 references
astuce: Utilisez 'git am --show-current-patch' pour visualiser le patch en échec

```
Résolvez tous les conflits manuellement, marquez-les comme résolus avec
"git add/rm <fichier en conflit>", puis lancez "git rebase --continue".
Si vous préférez sauter ce commit, lancez "git rebase --skip". Pour arrêter
et revenir à l'état antérieur à la commande, lancez "git rebase --abort".
```

**Comment by Hexcles** [comment]
Looks like a genuine conflict (with 233a619edcf51bc8b865831120403dfaced5d485).

Try `git rebase --abort && git merge --squash master`. If it goes well, `git push origin CSS4Pseudo-GT-PR16`.

**Comment by TalbotG** [comment]
after `git rebase --abort && git merge --squash master` , I got a lot of files suppressed

(...)
> Suppression de .well-known/origin-policy/policy-content-security-comma-in-policy
> Ajout de .well-known/origin-policy
> warning: détection de renommage inexact annulée à cause d'un trop grand nombre de fichiers.
> warning: vous souhaitez peut-être régler la variable merge.renamelimit à au moins 13487 et réessayer le commande.
> Validation compressée -- HEAD non mise à jour
> La fusion automatique a réussi ; stoppée avant la validation comme demandé

**Comment by Hexcles** [comment]
So there are still merge conflicts left. Could you see what files contain
conflicts from `git status`? Then maybe try to resolve the conflicts
<https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line>,
which you'd need to do anyway before merging the PR.

**Comment by TalbotG** [comment]
`$ git push origin CSS4Pseudo-GT-PR16`
Username, Password
Everything up-to-date

**Comment by TalbotG** [comment]
with `git status` , I get hundreds of files, in green color: new files, renamed files, suppressed files, modified files. I can not list all of them.

**Comment by Hexcles** [comment]
Only those "both modified" matter. How many do you have there?

**Comment by TalbotG** [comment]
I have hundreds if not thousands of modified files. I just can not list all of them.

**Comment by TalbotG** [comment]
and I only see the tail of a very long list of files on my command line console: I see from `upgrade-insecure-requests/ `to `xslt/` folders.

**Comment by TalbotG** [comment]
I do not understand your 
> "both modified"

**Comment by Hexcles** [comment]
If you look at the GitHub help article, you'll see `git status` print out a list of "both modified" files at the end (I'm not sure what the French translation is though), which shouldn't be too many. Those files contain merge conflicts that you'd need to resolve before being able to merge this branch.

**Comment by Hexcles** [comment]
Essentially this PR is conflicting with another of your PRs https://github.com/web-platform-tests/wpt/pull/21521/files which also added two tests included in this PR. Did you split those two tests out into a different PR? You could maybe try creating a new branch/PR with just `css/css-pseudo/reference/ref-nothing-below.xht`.

**Comment by TalbotG** [comment]
When I do git status , I get a very long list (I only see the last 300 or so files from the tail of the list) of files and I do **not** see anything stating the following:
> You have unmerged paths.
> (fix conflicts and run "git commit")
> Unmerged paths:
>  (use "git add ..." to mark resolution)
> both modified:

**Comment by TalbotG** [comment]
Hexcles,

I can delete this PR and then start all over in another PR. Would that neutralize the conflict occuring now?

**Comment by TalbotG** [comment]
> Essentially this PR is conflicting with another of your PRs https://github.com/web-platform-tests/wpt/pull/21521/files which also added css/css-pseudo/reference/ref-filled-green-100px-square.xht that's included in this PR. Did you split those two tests out into a different PR? You could maybe try creating a new branch/PR with just css/css-pseudo/reference/ref-nothing-below.xht.

:( I do not know . PRs are created and then we wait for days, weeks, months ...

**Comment by TalbotG** [comment]
I can close both PR21503 and PR21521. And start all over again. Would that neutralize the conflict occuring now?

**Comment by Hexcles** [comment]
> I can delete this PR and then start all over in another PR. Would that neutralize the conflict occuring now?

That might be the easiest way without having to learn how to handle merge conflicts in git (which I agree is a pain).

#21521 has been merged, so you just need to close this PR and create a new one that contains `css/css-pseudo/active-selection-057.html` and `css/css-pseudo/reference/ref-nothing-below.xht`. (`css/css-pseudo/reference/ref-filled-green-100px-square.xht` should already exist in master.)

**Comment by TalbotG** [comment]
It indeed exists in master:
```
/css/css-pseudo/reference$ ls
ref-filled-green-100px-square.xht
```

**Comment by TalbotG** [comment]
Hexcles,
Thank you for your time and efforts. I will close PR21503 and start over again in another PR.

**Pull request closed without merging**
