### PR TITLE
[presentation-api] Check both addEventListener and onxxx

### PR DESCRIPTION
**Pull request by tomoyukilabs**
This PR updates tests except ones addressed in #5794, so that these tests check both addEventListener and `onxxx`.

Also, the `onclose` test for a receiving user agent is updated as per https://github.com/w3c/presentation-api/pull/426.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232682706)

# Firefox (nightly) #
Testing web-platform-tests at revision c0929e727550faa1ac302c683102f25714c9221a
Using browser at version BuildID 20170515100238; SourceStamp e66dedabe582ba7b394aee4f89ed70fe389b3c46
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232682707)

# Sauce (safari) #
Testing web-platform-tests at revision c0929e727550faa1ac302c683102f25714c9221a
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232682708)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c0929e727550faa1ac302c683102f25714c9221a
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232682714)

# Chrome (unstable) #
Testing web-platform-tests at revision c0929e727550faa1ac302c683102f25714c9221a

**Review by tidoust — APPROVED** [review]
That all looks good to me.

I guess one could say that you applied the need to check both forms of event handling a bit too much to the letter, but that's great! :)

**Pull request merged**
