### PR TITLE
Remove old xhtml-pubid tests

### PR DESCRIPTION
**Pull request by foolip**
These are for https://www.w3.org/TR/xhtml-pubid/, which says
"Beware. This specification is no longer in active maintenance and the
HTML Working Group does not intend to maintain it further."

Per wpt.fyi, the first 3 tests are passing everywhere and the last 2
fail everywhere, so these tests don't cover any interop issue. The
first 3 also appear to be covered by the tests here:
https://wpt.fyi/html/the-xhtml-syntax/parsing-xhtml-documents/

### CODE REVIEW

**Comment by foolip** [comment]
@davidcarlisle, can you confirm that removing these tests is fine?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2017-10-13 09:22:19
Finished: 2017-10-13 09:26:47


<h2>Failing Jobs</h2>
<ul>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19442)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/287477981)

**Comment by davidcarlisle** [comment]
er yes drop them: the w3c process always seemed a bit backwards requiring tests for changes that hadn't (yet or ever) been adopted. The initial thing was a simple one line suggested change to the first html5 drafts, the fact that it was forced to grow into an "extension specification" and have tests failing apparently for years was never my intention:-)

**Comment by foolip** [comment]
Thanks @davidcarlisle, I didn't know this was an artifact of process requirement. All the more reason to drop it then. Incidentally, this week I've been working on https://github.com/foolip/testing-in-standards/blob/master/lifecycle.md for how I think testing in standards *should* work, feedback welcome :)

**Review by jdm — APPROVED** [review]

**Pull request merged**
