### PR TITLE
SRI: Add tests for <link> elements

### PR DESCRIPTION
**Pull request by joelweinberger**
This adds <link> element tests equivalent to the already present (and valid) <script> tests. @hillbrad, can you take a look? Also, a sanity check from @devd, @mozfreddyb, or @fmarier would be appreciated.

### CODE REVIEW

**Comment by jgraham** [comment]
Note: in the future please don't merge master into your branches, instead please rebase your branch onto master if it conflicts with other changes.

**Comment by jgraham** [comment]
(the reason for this is that this kind of merge makes the history confusing and, in this case, people were worried you had accidentally clobbered some upstream changes)

**Comment by metromoxie** [comment]
Okay, good to know. That's what I usually do, but hoppipolla-critic-bot seems to say that is frowned upon. Is their a nuance I'm missing, or is the bot just wrong? Thanks!

**Comment by jgraham** [comment]
Right, so it's always OK to rebase after you have your review accepted because at that point critic no longer cares. If you need to rebase for some reason whilst review is ongoing you need to do *only* a move-type rebase (i.e. don't squash or push extra stuff) and then tell critic about the rebase (there's a button on the review page) before you push anything else.

Unfortunately critic isn't the best when it comes to handling rebases.

**Comment by metromoxie** [comment]
Got it. Thanks!

**Pull request merged**
