### PR TITLE
Make test_memorizing Python3 compatible

### PR DESCRIPTION
**Pull request by svillar**
By using six.moves.StringIO

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Are `tools/pywebsocket` run on the CI? I don't see any mention of them in the TC run (e.g. https://community-tc.services.mozilla.com/tasks/bGxgrlxsQLC5ZdnGbDBvhQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbGxgrlxsQLC5ZdnGbDBvhQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log), and running `tox` locally in `tools/` doesn't get me results from pywebsocket

**Comment by jgraham** [comment]
No, historically pywebsocket was third party. We vendored it and eventually made a few minor changes, but continued to treat it as mostly third party so we didn't enable the tests in CI &c. If we're making more changes to update it we should also start running the tests.

**Comment by stephenmcgruer** [comment]
Ack. @svillar - can you look into enabling pywebsocket tests as part of the CI testing run? I see it in norecursedirs in pytest.ini, perhaps it just needs removed from there.

**Comment by svillar** [comment]
> Ack. @svillar - can you look into enabling pywebsocket tests as part of the CI testing run? I see it in norecursedirs in pytest.ini, perhaps it just needs removed from there.

Sure. I prefer to do it in a different PR though

**Review by stephenmcgruer — APPROVED** [review]
Very reasonable. This PR LGTM, assuming it takes the test from failing -> pass on your machine and still works in py2.7

**Review by Hexcles — CHANGES_REQUESTED** [review]
Although this LGTM, I think the maintainers of `pywebsocket` are also working on Python 3 compatibility. We should loop them in and avoid collisions. @ricea @quasi-mod

**Comment by svillar** [comment]
> Although this LGTM, I think the maintainers of `pywebsocket` are also working on Python 3 compatibility. We should loop them in and avoid collisions. @ricea @quasi-mod

BTW I have another 3 patches pending to be reviewed related to pywebsocket (and several others about to come), see  https://git.io/JvnrR, https://git.io/JvnrE and https://git.io/Jvnoj

If they're already working on that I can stop working on this component and focus on others.

**Comment by quasi-mod** [comment]
We have officially released [pywebsocket3](https://github.com/GoogleChromeLabs/pywebsocket3) (a python 3 compatible version of the original pywebsocket) earlier this week. 

> BTW I have another 3 patches pending to be reviewed related to pywebsocket (and several others about to come), see https://git.io/JvnrR, https://git.io/JvnrE and https://git.io/Jvnoj

Looking at the patches, I think the changes made in these patches are already applied in pywebsocket3. Our plan is to replace the old pywebsocket to the new pywesocket3, so I think you can stop working on pywebsocket and continue on with the other components.

**Comment by Hexcles** [comment]
Thanks, @quasi-mod . And sorry for the insufficient communication @svillar .

I'm closing these PRs for now. See #21749 for next steps.

**Pull request closed without merging**
