### PR TITLE
Add Additional Beacon CORS Tests

### PR DESCRIPTION
**Pull request by Brandr0id**
Add tests to cover varying Content-Type's and preflight scenarios.

### CODE REVIEW

**Comment by Brandr0id** [comment]
@toddreifsteck @igrigorik fyi

**Comment by w3c-bots** [comment]
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22040)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/319348096)

**Comment by toddreifsteck** [comment]
@igrigorik Please add the Chrome dev that owns sendBeacon to review the Chrome output. There are a number of failures at https://pulls.web-platform-tests.org/job/22040.11

**Comment by toddreifsteck** [comment]
It does not appear that Ilya or myself are owners of this subdirectory so I've pinged testing channel in IRC to unblock.

**Comment by Hexcles** [comment]
@toddreifsteck Can you review the PR now?

You and @igrigorik are now owners of beacon/, but I believe the OWNERS files are merely for wpt-pr-bot to find out whom to ping. You should be able to review the change as long as you have write access to this repo. And as a member of the W3C org on GitHub, you do.

**Comment by toddreifsteck** [comment]
@Hexcles Thanks for that! After that was updated, I now see the "Add your review" buttons because wpt-pr-bot requested it. I also see Ilya and I listed as reviewers required to sign off. Now unblocked!

**Review by igrigorik — APPROVED** [review]
👍

**Comment by toddreifsteck** [comment]
Merging as @igrigorik reviewed and gave a thumbs up.

**Pull request merged**
