### PR TITLE
Update webidl2.js to v20.0.1

### PR DESCRIPTION
**Pull request by gsnedders**
***NB: THIS MUST BE MERGED WITH A MERGE COMMIT***

This is just:

```
git subtree pull --squash --prefix=resources/webidl2 https://github.com/w3c/webidl2.js.git v20.0.1
```

### CODE REVIEW

**Comment by gsnedders** [comment]
@foolip @jgraham do one/both of you want to do a full run prior to landing this?

**Comment by gsnedders** [comment]
Oh, https://github.com/w3c/webidl2.js/pull/293 will probably break things for browsers without module support; probably just want to move to `/resources/webidl2/dist/webidl2.js` instead which is a bundled version.

**Comment by gsnedders** [comment]
I guess as long as this appears to be rather broken there's no rush to do full runs. :)

**Comment by gsnedders** [comment]
There's a billion things broken. :(

**Comment by saschanaz** [comment]
Could we do git submodule instead of copy-pasting everything?

**Comment by saschanaz** [comment]
Never mind my last comment, I'm exploring with latest bits of webidl2...

**Comment by gsnedders** [comment]
see #16864 instead

**Pull request closed without merging**
