### PR TITLE
Add streams test owners

### PR DESCRIPTION
**Pull request by domenic**
@tyoshino @yutakahirano @youennf @calvaris you OK with being pinged to review any streams test changes?

### CODE REVIEW

**Comment by yutakahirano** [comment]
I'm fine with it, thank you.

**Comment by calvaris** [comment]
I'm ok, though I don't know if I can allocate too much time for this.

**Comment by youennf** [comment]
Fine to me as well

**Comment by tyoshino** [comment]
me, too, sure

**Pull request merged**
