### PR TITLE
Update usvstring-reflection.https.html

### PR DESCRIPTION
**Pull request by ericlaw1979**
Test case needs to use HTTPS due to lockdown of the registerProtocolHandler() API to require a secure context.

### CODE REVIEW

**Review by domenic — APPROVED** [review]
Note that the spec is not yet updated for this: https://github.com/whatwg/html/issues/4017

**Comment by foolip** [comment]
@domenic it's fine to merge this before the spec change, right?

What would be needed to cover the change that needs to happen in browsers is a test to ensure that `registerProtocolHandler` isn't exposed in non-secure contexts.

**Comment by ericlaw1979** [comment]
Yeah, I presume that we'll add new tests for the specific limitations as we update the HTML spec itself.

**Comment by domenic** [comment]
Yes, merging this seems relatively harmless even before the spec change. I guess we lose some insecure-HTTP coverage, which per spec should work, but oh well.

**Pull request merged**
