### PR TITLE
Upgrade to Safari Technology Preview 91 on macOS Mojave

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Nope, still the same problem with "Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver." Over to you, @gsnedders.

**Comment by foolip** [comment]
@mustjab I feel I'm really close to finding a solution here, but I don't know the password of the vsts user on the macOS images, nor can I figure out how to reset it. Is it a dummy password that is documented somewhere?

**Comment by mustjab** [comment]
@foolip Asked pipeline team and they say that you should have password-less sudo on the Mac agents.

**Comment by foolip** [comment]
Yes, sudo is password-less and that works, but it looks like `safaridriver --enable` now has to run as the same user that will launch `safaridriver` and it looks like it's `safaridriver` itself that asks for a password. At least I can't find a workaround :(

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18610 was the previous attempt to upgrade to STP 90.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30498 is a full run of STP 91, still in progress.

**Comment by foolip** [comment]
https://staging.wpt.fyi/results/?diff&filter=ADC&run_id=247230003&run_id=253230003 shows the difference in results between master (STP 82) and this (STP 91). There are a bunch of improvements, but the regression due to https://bugs.webkit.org/show_bug.cgi?id=174030 seems to outweigh this.

Let's wait for STP 92.

**Comment by foolip** [comment]
STP 92 is here: https://github.com/web-platform-tests/wpt/pull/19142

**Pull request closed without merging**
