### PR TITLE
Reorganize canvas 2d tests

### PR DESCRIPTION
**Pull request by mysteryDate**
Starting small with this first PR, because small mean ~3k renamed files. In summary:

  2dcontext -> html/canvas/dom-element
  offscreen-canvas -> html/canvas/offscreen

  The tools folder inside 2dcontext and offscreen-canvas has been merged such that `tools/build.sh` generates dom-canvas and offscreen canvas tests. Next steps:

  1. Take the tests that are in `html/semantics/embedded-content/the-canvas-element` and move them inside the `canvas` folder.
  2. Autogen folders for detached, offscreen worker, transferControlToOffscreen and transferControlToOfscreen in workers.
  3. Split up `tools/tests*.yaml` files.
  4. Make non-autogen'd tests autogen'd.

Also, `build.sh` created `annotated-spec.html`. Do we want that file? If not, I'll stop the build script from generating it.

I'm unable to link the issue directly: https://github.com/web-platform-tests/wpt/issues/22979#issuecomment-614283128

### CODE REVIEW

**Comment by annevk** [comment]
If the before and after results haven't changed this seems fine to me. You probably need to get an admin to merge this as the bots will time out for this big a change. (You should probably still confirm that's why things are failing though.)

I have a slight preference for `dom-element` -> `element` as it's kinda redundant otherwise.

You should also update https://github.com/web-platform-tests/wpt/blob/master/html/README.md.

**Comment by domenic** [comment]
> Readd missing expectations 

These should not be checked in the wpt repo, as they are Chromium specific.

**Comment by mysteryDate** [comment]
Ah, that makes sense. I usually edit this directory directly from chromium, hence my confusion.

**Review by fserb — APPROVED** [review]
We may need to force submit because CQ will go crazy.

**Comment by foolip** [comment]
Changing a lot of files will cause the stability jobs to time out on Taskcluster, and we do see wpt-chrome-dev-stability and wpt-firefox-nightly-stability failing. However, the lint and update-built jobs are also failing, and those will need to be fixed.

Once only the stability jobs are failing I'd be happy to force merge this.

**Comment by foolip** [comment]
@mysteryDate annotated-spec.html came up in https://github.com/web-platform-tests/wpt/issues/23293 as well. You mentioned in the description and it was left in.

If you don't think it serves any value, then just deleting it would be good.

**Comment by foolip** [comment]
On [importing this change into Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/2172872/) I found that some tests had regressed because of relative paths. I've sent a fix for some of those in https://github.com/web-platform-tests/wpt/pull/23343, there could be more.

**Pull request merged**
