### PR TITLE
[pointerevents] remove the extensions IDL test

### PR DESCRIPTION
**Pull request by foolip**
Matching this series of upstream removals:
https://github.com/w3c/pointerevents/pull/310
https://github.com/tidoust/reffy/pull/193
https://github.com/tidoust/reffy-reports/pull/43

The API surface will be tested via the main IDL file instead:
https://github.com/web-platform-tests/wpt/pull/19870

### CODE REVIEW

**Comment by NavidZ** [comment]
I'm already removing the pointer event one as part of this review: 
https://chromium-review.googlesource.com/c/chromium/src/+/1906903

**Comment by foolip** [comment]
Can you delete the IDL file there too so that nothing of this PR would remain?

**Comment by NavidZ** [comment]
> Can you delete the IDL file there too so that nothing of this PR would remain?

I thought the interface/* files were autogenerated files and they will be removed/added automatically as well. But if you say I need to remove it manually then sure. I'll remove interfaces/pointerevents-extension.idl as well.

**Comment by foolip** [comment]
Unfortunately removal isn’t automatic, to avoid deleting IDL files due to network flakes, the reffy-reports updater only adds/modifies and never deletes. I don’t remember what happens once it’s manually deleted from reffy-reports, let’s find out by *not* including the deletion in your CL 😀

**Comment by foolip** [comment]
Alright, removal did propagate from reffy-reports to here at least: https://github.com/web-platform-tests/wpt/pull/20248

**Pull request closed without merging**
