### PR TITLE
[WIP] Python 3: Add support for running tests with Python 3 on TaskCl…

### PR DESCRIPTION
**Pull request by ziransun**
…uster CI

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Just noting that this is marked 'WIP' and I believe Ziran is intended to iterate using TaskCluster checks on the PR.

@ziransun feel free to ask explicitly once you want outside eyes on this PR (whether that's a full review or just a question! :))

**Comment by ziransun** [comment]
@jgraham @stephenmcgruer : Any chance to review this and see if it's reasonable?

**Comment by jgraham** [comment]
I wonder if running all the tests under py3 daily is the right tradeoff. If we want to get a full result as a baseline we can get it from a trigger branch push. For ongoing work it seems like it could be more useful to get the infrastructure tests running under py3, since those could flag regression in PRs touching tools/.

**Comment by stephenmcgruer** [comment]
@jgraham - to me, the two reasons to do this (which I documented in https://github.com/web-platform-tests/wpt/issues/22784 where I asked Ziran to do this work) are:

1. far more easily compare Python 3 to Python 2 (i.e. using wpt.fyi and cross-comparing two runs at the same SHA), and
1. easily spot regressions (i.e. using wpt.fyi and cross-comparing consecutive runs of Python 3 at different SHAs)

It is also an exercise in continuing to move forward in our Python 3 support. Outside of wptserve (which is of course a sizable problem still to be surmounted), we're running out of test directories that don't work under Python 3. We have to answer the question of 'ok, what next on the way to Python 3', and I thought this was a useful exercise.

> it seems like it could be more useful to get the infrastructure tests running under py3, since those could flag regression in PRs touching tools/.

That's a good idea and I think we should do that too, but I see it as complementary to having regular test suite runs.

**Comment by stephenmcgruer** [comment]
> is the right tradeoff

Sorry, I missed this statement the first time I read through. Can you explain further what you mean by 'tradeoff' here? (Is it a capacity concern, or something else?)

**Comment by stephenmcgruer** [comment]
Closing this PR; we have switched the CI to Py3 and I think this particular experiment is not needed.

**Pull request closed without merging**
