### PR TITLE
Update WOFF2 test fonts

### PR DESCRIPTION
**Pull request by mokjasmine**
While attempting to use [FreeType's WOFF2 support for fonts within WebKit](https://github.com/WebKit/WebKit/pull/14086), we saw failures with [tests that load WOFF2 fonts](https://ews-build.webkit.org/#/builders/1/builds/14866).[tests that load WOFF2 fonts](https://ews-build.webkit.org/#/builders/1/builds/14866). 

With each of the `woff2` files in the failing tests, we found that FreeType could load them if we decompressed them to a `.ttf` using `woff2_decompress` or `fonttools ttLib.woff2 decompress`, and then compressed them again using `fonttools ttLib.woff2 compress` with the `--no-glyf-transform` option.

[GitLab FreeType bug we filed](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1235)

We compressed the following fonts using `fonttools ttlib.woff2 compress --no-glyf-transform`, all of which FreeType was able to load:
css/WOFF2/support/datatypes-alt-255uint16-001.woff2
css/WOFF2/support/tabledata-transform-hmtx-001.woff2
css/WOFF2/support/tabledata-transform-hmtx-002.woff2
css/WOFF2/support/valid-005.woff2
css/WOFF2/support/valid-006.woff2
css/WOFF2/support/valid-007.woff2
css/WOFF2/support/valid-008.woff2

Only one test font was still unable to load using this method:
css/WOFF2/support/header-totalsfntsize-001.woff2

### CODE REVIEW

**Comment by svgeesus** [comment]
This is because of the [correction to WOFF2](https://www.w3.org/TR/WOFF2/#p1) as [confirmed here](https://github.com/fonttools/fonttools/issues/1636).

So this update to bring the WOFF2 fonts into line with the latest specification looks good to me.

**Review by svgeesus — APPROVED** [review]
LGTM

**Comment by donny-dont** [comment]
Thanks for the review @svgeesus ! Is there anything else on our end required to merge this in so @mokjasmine can bring it into the WebKit tree?

The folks working on FreeType were looking at things over in [GitLab](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1235#note_1940556). @nikramakrishnan @lemzwerg just a heads up about this PR.

**Comment by lemzwerg** [comment]
Thanks for the heads-up.  AFAICS, however, the problem with font `header-totalsfntsize-001.woff2` remains, right?

**Comment by mokjasmine** [comment]
@lemzwerg That's correct. I found that loading the decompressed and re-compressed version of `header-totalsfntsize-001.woff2` in our own separate sample app using `FT_New_Face()` worked fine. However, the test `header-totalsfntsize-001.xht` is still unable to load that font file.

**Pull request merged**
