### PR TITLE
COEP shouldn't take effect in data URL frames.

### PR DESCRIPTION
**Pull request by yutakahirano**
Related to https://github.com/whatwg/html/issues/4930.

### CODE REVIEW

**Comment by yutakahirano** [comment]
Chrome and Firefox [pass the current test](https://wpt.fyi/results/html/cross-origin-embedder-policy/data.https.html?label=experimental&label=master&aligned), which means they will fail with this change.

I'm puzzled by the Firefox behavior because they pass [no-secure-context.html](https://wpt.fyi/results/html/cross-origin-embedder-policy/no-secure-context.html?label=experimental&label=master&aligned).

**Comment by annevk** [comment]
What's the basis for making this change? `data:` URLs are a secure context. If they do not enforce the policy you could have a way to smuggle non-cross-origin isolated data into a cross-origin isolated process, no?

**Comment by yutakahirano** [comment]
I saw old comments such as https://github.com/whatwg/html/issues/5198#issue-546920445 and the (current) Chromium implementation and thought that data URLs are not secure contexts.

But you changed the spec after that, right? https://github.com/w3c/webappsec-secure-contexts/issues/69 https://github.com/w3c/webappsec-secure-contexts/pull/72

**Comment by annevk** [comment]
Yeah, I did. I'll update the comment in that issue.

**Comment by yutakahirano** [comment]
Thanks!

**Pull request closed without merging**
