### PR TITLE
Add some tests for ::marker.

### PR DESCRIPTION
**Pull request by dbates-wk**
We should add some tests for the ::marker pseudo element.

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259881544)

# Firefox (nightly) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259881545)

# Sauce (safari) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259881552)

# Chrome (unstable) #

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259881557)

# Sauce (MicrosoftEdge) #

**Comment by dbates-wk** [comment]
These tests were reviewed in <https://bugs.webkit.org/show_bug.cgi?id=141477>.

**Review by zcorpan — APPROVED** [review]
Rubberstamping upstream review.

**Pull request merged**
