### PR TITLE
Write more tests for HTMLAllCollection (document.all)

### PR DESCRIPTION
**Pull request by foolip**
Tests for https://github.com/whatwg/html/pull/780

### CODE REVIEW

**Comment by foolip** [comment]
http://w3c-test.org/submissions/4037/html/infrastructure/common-dom-interfaces/collections/htmlallcollection.html

**Comment by foolip** [comment]
@jgraham what is this magic?! So awesome :)

**Comment by foolip** [comment]
@cdumez @rwlbuis, would either of you be interested in reviewing this?

**Review by rwlbuis — COMMENTED** [review]
Looks good to me but I think cdumez knows document.all better.

**Comment by foolip** [comment]
Ping @cdumez

**Comment by foolip** [comment]
@zcorpan, can you review?

**Comment by zcorpan** [comment]
LGTM if the failures are the ones you expect. I didn't manage to understand the spec diff well enough to evaluate correctness of some of the asserts, so I will just assume that you know what you're doing. :-)

**Comment by foolip** [comment]
Yeah, the details here require an afternoon to page in. I'm pretty confident because I tried out some Blink changes in https://codereview.chromium.org/2430353005, which had this test + changes.

**Pull request merged**
