### PR TITLE
Infra: remove old service worker code from testharness.js

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Review by jgraham — APPROVED** [review]
I don't know if there's a spec change here, but having one codepath rather than two seems strictly better.

**Comment by stephenmcgruer** [comment]
So it looks like this was added in https://github.com/web-platform-tests/wpt/commit/821d133c37fdb7c74e98d3578fbd36823d2c507b, with no details or Chrome bug link as to why, but the comment clearly suggests that there was a Blink bug that made this necessary.

@annevk do we know that any such bug has been fixed? Did we run a trigger run of this commit to see what changes it makes to the WPT results on Chrome? It would have been nice to be able to provide some of that information in the commit message, to help future-us not have to perform code archaeology* years down the line to understand why a change was made.

* Like the archaeology I just had to perform for that comment, since it didn't link any form of bug to track this claimed Blink problem.

**Comment by annevk** [comment]
I thought I checked with someone if that comment was still true for Chrome, but you're right that I didn't really do a good job of documenting that, including for myself. So I guess this is all we have and if that's not enough, we should revert.

**Comment by stephenmcgruer** [comment]
We can check the wpt.fyi results before and after (I will take the AI to do that), which should be sufficient.

**Comment by annevk** [comment]
Thanks @stephenmcgruer! Won't happen again.

**Comment by stephenmcgruer** [comment]
Diff is https://wpt.fyi/results/?diff&filter=ADC&run_id=451860003&run_id=423660009

There are a handful of TIMEOUT differences in service-worker/:

https://wpt.fyi/results/service-workers/service-worker/client-navigate.https.html?diff&filter=ADC&run_id=451860003&run_id=423660009
https://wpt.fyi/results/service-workers/service-worker/windowclient-navigate.https.html?diff&filter=ADC&run_id=451860003&run_id=423660009

But I'm not sure if these are real or flake. Might be worth running locally with/without the change and seeing if we can reproduce the diff, or we can just wait and see if they go away in subsequent runs.

**Comment by stephenmcgruer** [comment]
Looks like the Chromium import of this change also marked a few service-worker tests as TIMEOUT now - https://chromium-review.googlesource.com/c/chromium/src/+/2083053/4/third_party/blink/web_tests/TestExpectations

**Pull request merged**
