### PR TITLE
Remove instances of 'whitelist' in content-security-policy/

### PR DESCRIPTION
**Pull request by stephenmcgruer**
As per https://whatwg.org/style-guide

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
(kicking the CI to run again)

**Comment by stephenmcgruer** [comment]
@annevk do you mind reviewing? There are some code changes but I think they're reviewable without a deep understanding of csp.

**Review by annevk — APPROVED** [review]
This looks reasonable assuming simpleSourcedScript.js reads out the ID of the element that includes it and then sends a message based on that ID, which is a bit weird, but okay.

**Comment by stephenmcgruer** [comment]
It does!

```
$ cat ./content-security-policy/script-src/simpleSourcedScript.js
window.postMessage(document.currentScript.id, "*");
```

**Pull request merged**
