### PR TITLE
Add interfaces/device-memory.idl

### PR DESCRIPTION
**Pull request by autofoolip**
This PR was automatically created by a bot.

Before merging, please check that any tests that depend on the updated IDL files still work.

If additional changes are needed, please manually create another PR based on this one.

See the [README](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) for how the IDL files in this directory are used.

<hr>

Source: https://github.com/tidoust/reffy-reports/blob/06d5dd3/ed/idl/device-memory.idl
Build: https://travis-ci.org/tidoust/reffy-reports/builds/674982866

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
Started working on a test for this, and found that it has a `NoInterfaceObject` which WebIDL complains about:

```
  ▶ Unexpected subtest result in /device-memory/idlharness.https.any.worker.html:
  │ FAIL [expected PASS] idl_test validation
  │   → Validation error at line 7 in device-memory, inside `extended-attribute NoInterfaceObject`:
    NoInterfaceObject,
    ^ `[NoInterfaceObject]` extended attribute is an undesirable feature that may be removed from Web IDL in the future. Refer to the [relevant upstream PR](https://github.com/heycam/webidl/pull/609) for more information.
  │ 
  │ Error: Validation error at line 7 in device-memory, inside `extended-attribute NoInterfaceObject`:
  │     NoInterfaceObject,
```

I'm not familiar with this; thoughts @foolip ?

**Comment by foolip** [comment]
I've sent https://github.com/w3c/device-memory/pull/25 to modernize the IDL.

**Comment by stephenmcgruer** [comment]
https://github.com/w3c/device-memory/pull/25 landed a week ago; how often does reffy run?

**Comment by foolip** [comment]
https://github.com/tidoust/reffy-reports/blob/master/.github/workflows/update-ed.yml runs every 6 hours. Seems like the problem is deploy failed: https://github.com/w3c/device-memory/runs/406165139

**Comment by foolip** [comment]
I've filed https://github.com/w3c/device-memory/issues/26.

**Pull request closed without merging**
