### PR TITLE
Add more test cases for Document#currentScript

### PR DESCRIPTION
**Pull request by koustuvsinha**
Following added tests :
- Verify in script.async = false
- Verify iframe src=javascript:
- Verify cross origin script
- Test in document.write

### CODE REVIEW

**Comment by koustuvsinha** [comment]
@jgraham review?

**Comment by Ms2ger** [comment]
If nobody beats me to it, I'll try to take some time next week.

**Comment by koustuvsinha** [comment]
@Ms2ger thanks! :)

**Comment by Ms2ger** [comment]
Simon reviewed on critic

**Pull request merged**
