### PR TITLE
[WIP] Debugging tools/wpt/ tests breakage on Windows

### PR DESCRIPTION
**Pull request by stephenmcgruer**
See https://github.com/web-platform-tests/wpt/issues/25394

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@mustjab I may have messed up the command line (PTAL), but I get File Not Found looking for Chrome: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=54040&view=logs&j=802ce073-f5e3-5667-fac8-56b586b322fa&t=3c0c6706-9181-5cd9-6408-1008fd43763b

**Comment by mustjab** [comment]
@stephenmcgruer I see that the script ran on D drive. I've updated the script to first switch to system drive before searching for chrome.exe. Can you please schedule another run?

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer I see that the script ran on D drive. I've updated the script to first switch to system drive before searching for chrome.exe. Can you please schedule another run?

D'oh, of course -_-. It should run automatically; looks like it still failed? https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=54041&view=logs&jobId=802ce073-f5e3-5667-fac8-56b586b322fa&j=802ce073-f5e3-5667-fac8-56b586b322fa&t=3c0c6706-9181-5cd9-6408-1008fd43763b

**Comment by mustjab** [comment]
@stephenmcgruer Looks like Chrome is installed here: 

> Chrome Version = 85.0.4183.83 at C:\Program Files\Google\Chrome\Application\chrome.exe

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=54123&view=logs&j=802ce073-f5e3-5667-fac8-56b586b322fa&t=3c0c6706-9181-5cd9-6408-1008fd43763b

**Comment by stephenmcgruer** [comment]
Thanks for the help debugging this @mustjab !

**Pull request closed without merging**
