### PR TITLE
[preload] Split `media` into `video`, `audio` and `track`

### PR DESCRIPTION
**Pull request by yoavweiss**
This changes `as` values of `media` to their corresponding appropriate destination as defined in https://github.com/whatwg/fetch/pull/437

/cc @annevk

### CODE REVIEW

**Comment by w3c-bots** [comment]
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5033)

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208069462)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 05d6affa340345cd3b4ab47237bd1f04ab161cf1
Using browser at version BuildID 20170305110158; SourceStamp eb23648534779c110f3a1f2baae1849ae4a9c570
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/download-resources.html">/preload/download-resources.html</a></summary>


|                       Subtest                        | Results |                           Messages                           |
|------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                      | OK      |                                                              |
| `Makes sure that preloaded resources are downloaded` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/onerror-event.html">/preload/onerror-event.html</a></summary>


|                             Subtest                             | Results |                           Messages                           |
|-----------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                 | OK      |                                                              |
| `Makes sure that preloaded resources trigger the onerror event` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/onload-event.html">/preload/onload-event.html</a></summary>


|                            Subtest                             | Results |                           Messages                           |
|----------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                | OK      |                                                              |
| `Makes sure that preloaded resources trigger the onload event` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-csp.sub.html">/preload/preload-csp.sub.html</a></summary>


|                    Subtest                     | Results |                           Messages                           |
|------------------------------------------------|---------|--------------------------------------------------------------|
|                                                | OK      |                                                              |
| `Makes sure that preload requests respect CSP` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-default-csp.sub.html">/preload/preload-default-csp.sub.html</a></summary>


|                    Subtest                     | Results |                           Messages                           |
|------------------------------------------------|---------|--------------------------------------------------------------|
|                                                | OK      |                                                              |
| `Makes sure that preload requests respect CSP` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-with-type.html">/preload/preload-with-type.html</a></summary>


|                                       Subtest                                        | Results |                           Messages                           |
|--------------------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                                      | OK      |                                                              |
| `Makes sure that preloaded resources with a type attribute trigger the onload event` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/single-download-preload.html">/preload/single-download-preload.html</a></summary>


|                                 Subtest                                  | Results |                           Messages                           |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                          | OK      |                                                              |
| `Makes sure that preloaded resources are not downloaded again when used` | FAIL    | `assert_true: Preload not supported expected true got false` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/208069463)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 05d6affa340345cd3b4ab47237bd1f04ab161cf1
Using browser at version 58.0.3026.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/download-resources.html">/preload/download-resources.html</a></summary>


|                       Subtest                        | Results |                        Messages                        |
|------------------------------------------------------|---------|--------------------------------------------------------|
|                                                      | OK      |                                                        |
| `Makes sure that preloaded resources are downloaded` | FAIL    | `assert_equals: /media/white.mp4 expected 1 but got 0` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/onerror-event.html">/preload/onerror-event.html</a></summary>


|                             Subtest                             | Results | Messages |
|-----------------------------------------------------------------|---------|----------|
|                                                                 | OK      |          |
| `Makes sure that preloaded resources trigger the onerror event` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/onload-event.html">/preload/onload-event.html</a></summary>


|                            Subtest                             | Results |                              Messages                             |
|----------------------------------------------------------------|---------|-------------------------------------------------------------------|
|                                                                | OK      |                                                                   |
| `Makes sure that preloaded resources trigger the onload event` | FAIL    | `assert_true: video triggered load event expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-csp.sub.html">/preload/preload-csp.sub.html</a></summary>


|                    Subtest                     | Results | Messages |
|------------------------------------------------|---------|----------|
|                                                | OK      |          |
| `Makes sure that preload requests respect CSP` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-default-csp.sub.html">/preload/preload-default-csp.sub.html</a></summary>


|                    Subtest                     | Results | Messages |
|------------------------------------------------|---------|----------|
|                                                | OK      |          |
| `Makes sure that preload requests respect CSP` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/preload-with-type.html">/preload/preload-with-type.html</a></summary>


|                                       Subtest                                        | Results |                              Messages                             |
|--------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------|
|                                                                                      | OK      |                                                                   |
| `Makes sure that preloaded resources with a type attribute trigger the onload event` | FAIL    | `assert_true: video triggered load event expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5033/preload/single-download-preload.html">/preload/single-download-preload.html</a></summary>


|                                 Subtest                                  | Results | Messages |
|--------------------------------------------------------------------------|---------|----------|
|                                                                          | OK      |          |
| `Makes sure that preloaded resources are not downloaded again when used` | PASS    |          |

</details>
</details>

**Comment by yoavweiss** [comment]
These tests are also integrated into https://codereview.chromium.org/2732853003/
I prefer to land them through there.

**Comment by yoavweiss** [comment]
Closed by https://github.com/w3c/web-platform-tests/pull/5103

**Pull request closed without merging**
