### PR TITLE
Improve request-upload.js.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Chrome (unstable channel) #
Testing web-platform-tests at revision c69f9ec4f12ed5257d59fc6c1d2aa076c666fe7b
Using browser at version 58.0.3000.4 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4750/fetch/api/basic/request-upload-worker.html">/fetch/api/basic/request-upload-worker.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Fetch with POST with ArrayBuffer body`                      | PASS    |
| `Fetch with POST with Int8Array body`                        | PASS    |
| `Fetch with PUT with body`                                   | PASS    |
| `Fetch with POST with ReadableStream containing String`      | FAIL    |
| `Fetch with POST with ReadableStream`                        | FAIL    |
| `Fetch with POST with ReadableStream containing number`      | FAIL    |
| `Fetch with POST with Float64Array body`                     | PASS    |
| `Fetch with POST with Blob body`                             | PASS    |
| `Fetch with POST with ReadableStream containing ArrayBuffer` | FAIL    |
| `Fetch with POST with Uint8Array body`                       | PASS    |
| `Fetch with POST with Float32Array body`                     | PASS    |
| `Fetch with POST with Blob body with mime type`              | PASS    |
| `Fetch with POST with ReadableStream containing Blob`        | FAIL    |
| `Fetch with POST with ReadableStream containing null`        | FAIL    |
| `Fetch with POST with text body`                             | PASS    |
| `Fetch with POST with URLSearchParams body`                  | PASS    |
| `Fetch with POST with DataView body`                         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4750/fetch/api/basic/request-upload.html">/fetch/api/basic/request-upload.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Fetch with POST with ArrayBuffer body`                      | PASS    |
| `Fetch with POST with Int8Array body`                        | PASS    |
| `Fetch with PUT with body`                                   | PASS    |
| `Fetch with POST with ReadableStream containing String`      | FAIL    |
| `Fetch with POST with ReadableStream`                        | FAIL    |
| `Fetch with POST with ReadableStream containing number`      | FAIL    |
| `Fetch with POST with Float64Array body`                     | PASS    |
| `Fetch with POST with Blob body`                             | PASS    |
| `Fetch with POST with ReadableStream containing ArrayBuffer` | FAIL    |
| `Fetch with POST with Uint8Array body`                       | PASS    |
| `Fetch with POST with Float32Array body`                     | PASS    |
| `Fetch with POST with Blob body with mime type`              | PASS    |
| `Fetch with POST with ReadableStream containing Blob`        | FAIL    |
| `Fetch with POST with ReadableStream containing null`        | FAIL    |
| `Fetch with POST with text body`                             | PASS    |
| `Fetch with POST with URLSearchParams body`                  | PASS    |
| `Fetch with POST with DataView body`                         | PASS    |

</details>

**Comment by w3c-bots** [comment]
# Firefox (nightly channel) #
Testing web-platform-tests at revision c69f9ec4f12ed5257d59fc6c1d2aa076c666fe7b
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4750/fetch/api/basic/request-upload-worker.html">/fetch/api/basic/request-upload-worker.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Fetch with POST with ArrayBuffer body`                      | PASS    |
| `Fetch with POST with Int8Array body`                        | PASS    |
| `Fetch with PUT with body`                                   | PASS    |
| `Fetch with POST with ReadableStream containing String`      | FAIL    |
| `Fetch with POST with ReadableStream`                        | FAIL    |
| `Fetch with POST with ReadableStream containing number`      | FAIL    |
| `Fetch with POST with Float64Array body`                     | PASS    |
| `Fetch with POST with Blob body`                             | PASS    |
| `Fetch with POST with ReadableStream containing ArrayBuffer` | FAIL    |
| `Fetch with POST with Uint8Array body`                       | PASS    |
| `Fetch with POST with Float32Array body`                     | PASS    |
| `Fetch with POST with Blob body with mime type`              | PASS    |
| `Fetch with POST with ReadableStream containing Blob`        | FAIL    |
| `Fetch with POST with ReadableStream containing null`        | FAIL    |
| `Fetch with POST with text body`                             | PASS    |
| `Fetch with POST with URLSearchParams body`                  | PASS    |
| `Fetch with POST with DataView body`                         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4750/fetch/api/basic/request-upload.html">/fetch/api/basic/request-upload.html</a></summary>


|                           Subtest                            | Results |
|--------------------------------------------------------------|---------|
|                                                              | OK      |
| `Fetch with POST with ArrayBuffer body`                      | PASS    |
| `Fetch with POST with Int8Array body`                        | PASS    |
| `Fetch with PUT with body`                                   | PASS    |
| `Fetch with POST with ReadableStream containing String`      | FAIL    |
| `Fetch with POST with ReadableStream`                        | FAIL    |
| `Fetch with POST with ReadableStream containing number`      | FAIL    |
| `Fetch with POST with Float64Array body`                     | PASS    |
| `Fetch with POST with Blob body`                             | PASS    |
| `Fetch with POST with ReadableStream containing ArrayBuffer` | FAIL    |
| `Fetch with POST with Uint8Array body`                       | PASS    |
| `Fetch with POST with Float32Array body`                     | PASS    |
| `Fetch with POST with Blob body with mime type`              | PASS    |
| `Fetch with POST with ReadableStream containing Blob`        | FAIL    |
| `Fetch with POST with ReadableStream containing null`        | FAIL    |
| `Fetch with POST with text body`                             | PASS    |
| `Fetch with POST with URLSearchParams body`                  | PASS    |
| `Fetch with POST with DataView body`                         | PASS    |

</details>

**Comment by annevk** [comment]
What's the motivation for this change? It makes the test somewhat harder to scan through.

**Comment by Ms2ger** [comment]
Non-support for `ReadableStream` currently breaks the entire test.

**Comment by annevk** [comment]
Firefox does not support it and still passes subtests.

**Comment by annevk** [comment]
I found out I was wrong.

**Comment by guest271314** [comment]
@annevk The requirement is possible using `async/await`, correct?

**Pull request merged**
