### PR TITLE
Make pr_preview.py pass the token as a password rather than a username

### PR DESCRIPTION
**Pull request by stephenmcgruer**
It seems like the code was passing the token as a username rather than a password,
which should never work. (and indeed refs weren't being deleted). Try setting a username
and using it as the password to see if that works.

### CODE REVIEW

**Review by Hexcles — COMMENTED** [review]
I think the problem is that we're setting the token as username instead of password:
https://github.com/web-platform-tests/wpt/blob/5fa6b7cbc4a02a2a5f3d23846373ba38acfe9d18/tools/ci/pr_preview.py#L220

I can't find the docs for `GITHUB_TOKEN`, but assuming it's similar to a personal access token, then we should put it in the password field instead in git. The username is probably "github-actions" (based on e.g. #26870).

**Comment by stephenmcgruer** [comment]
> I think the problem is that we're setting the token as username instead of password:

😂 😂 

That's what I get for not reading the code... I have no idea how this ever worked, even back before we did the `pull_request_target` change.

Changed the method, PTAL.

**Review by Hexcles — APPROVED** [review]
Let's give it a try!

**Comment by stephenmcgruer** [comment]
For the record, this didn't actually work - git wasn't picking up the password properly. However I almost immediately landed the switch to use GitHub APIs rather than the Remote anyway, and that does work (e.g. see https://github.com/web-platform-tests/wpt/pull/26901/checks?check_run_id=1554334286)

**Comment by Hexcles** [comment]
Thanks, Stephen!

I also just realized that git does **not** have a `credential.password` setting but instead relies on one of the "helpers".  Some people on the internet opt to put username and password [in the HTTP URL](https://stackoverflow.com/a/18936804) when cloning the repo but I'm not sure if GitHub Actions is clever enough to scrub that off of the logs.

**Pull request merged**
