### PR TITLE
idlharness.js: Distinguish instance toJSON is being executed against when it's inherited

### LINKED ISSUE #7492: idlharness generates duplicate test names
See https://github.com/w3c/web-platform-tests/pull/7490

The same interface may be tested twice if testing different subinterfaces. When testing objects from the subinterfaces, idlharness could generate duplicate test names.

eg. PerformanceMark and PerformanceMeasure both inherits from PerformanceEntry, which has a toJSON function. idlharness reports "Harness status: Error  1 duplicate test name: "Test default toJSON operation of PerformanceEntry"

### PR DESCRIPTION
**Pull request by lukebjerring**
The specific 'bug' that I am attempting to fix is outlined in https://github.com/w3c/web-platform-tests/pull/9787 - also fixes #7492

I am unsure why changing `[Default] toJSON();` to `[Default] object toJSON();` suddenly results in the new error:

    3 duplicate test names: "Test default toJSON operation of DOMPointReadOnly", "Test default toJSON 
    operation of DOMRectReadOnly", "Test default toJSON operation of DOMMatrixReadOnly"

I _have_ clarified that the duplication occurs from running the test on both `DOMMatrix` and `DOMMatrixReadOnly`, where `DOMMatrix : DOMMatrixReadOnly`.
`this.name` is `DOMMatrixReadOnly` in both cases, in spite of the idlArray object instance being DOMMatrix.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/10029)

### CODE REVIEW

**Comment by w3c-bots** [comment]
# Build BROKEN

Started: 2018-03-14 13:56:45
Finished: 2018-03-14 14:09:33


<h2>Failing Jobs</h2>
<ul>

<li>resources_unittest in py27</li>

<li>chrome:dev</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25936)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/353342164)

**Comment by lukebjerring** [comment]
@tobie - any idea when you'll be able to take a look?

**Comment by tobie** [comment]
LGTM. I think this also fixes #7492. Could you check?

**Comment by tobie** [comment]
Note, you'll have to fix the test suite accordingly.

**Comment by lukebjerring** [comment]
@tobie - Correct, fixes #7492, will add that to the desc. This is now good to go.

**Review by foolip — APPROVED** [review]

**Pull request merged**
