### PR TITLE
WASM JS API: Test new Web IDL class string behavior

### PR DESCRIPTION
**Pull request by shvaikalesh**
Spec: heycam/webidl#357.
Related: #23140.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
_cc_ @domenic

While WASM interfaces are defined by WebIDL, they are not covered by WebKit's bindings generator and have to be handled separately.

**Comment by domenic** [comment]
I guess this is somewhat redundant with https://wpt.fyi/results/wasm/jsapi/idlharness.any.html?label=experimental&label=master&aligned which uses assert_class_string, but it's good to have the extra coverage of the toStringTag.

Maybe we can consider removing this (and some of the tests in https://github.com/web-platform-tests/wpt/pull/23140), and moving them into idlharness, once all browsers have implemented https://github.com/heycam/webidl/pull/357. But until then it's best to not introduce the thousands of failing tests I keep worrying about :). I'll file a followup issue.

**Review by domenic — APPROVED** [review]

**Comment by shvaikalesh** [comment]
Seems like Chrome does not define `Symbol.toStringTag` for WASM Error interfaces, and that makes sense since `NativeError`s do not have one either. Does it contradict the spec though?

**Review by Ms2ger — APPROVED** [review]

**Comment by domenic** [comment]
My reading of the spec at https://webassembly.github.io/spec/js-api/#error-objects is that there is no toStringTag. It says "implementing the NativeError Object Structure", and doesn't use Web IDL at all.

So it'd be good to add tests that there is no toStringTag property for those, IMO.

**Comment by shvaikalesh** [comment]
My bad, I was reading outdated spec at https://www.w3.org/TR/wasm-js-api-1/#error-objects.

**Review by domenic — APPROVED** [review]

**Comment by shvaikalesh** [comment]
@domenic Is there a way I can help get this merged? I am sure these tests will smoothen patch review.

Could I kindly ask you take a brief look at #22833? I would like to avoid syncing WASM tests twice.

**Comment by domenic** [comment]
Oh, I didn't realize you didn't have write permissions.

**Pull request merged**
