### PR TITLE
Remove mention of git submodule update from lint import error message

### PR DESCRIPTION
**Pull request by jeffcarp**
This change is [Reviewable](https://reviewable.io/reviews/w3c/web-platform-tests/6206)

### CODE REVIEW

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241392328)

# Firefox (nightly) #
Testing web-platform-tests at revision 156f658209a086c76d851e36d2ac836b51089bef
Using browser at version BuildID 20170609100251; SourceStamp f4262773c4331d4ae139be536ce278ea9aad3436
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241392329)

# Sauce (safari) #
Testing web-platform-tests at revision 156f658209a086c76d851e36d2ac836b51089bef
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241392338)

# Chrome (unstable) #
Testing web-platform-tests at revision 156f658209a086c76d851e36d2ac836b51089bef
Using browser at version 61.0.3124.4 dev
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241392339)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 156f658209a086c76d851e36d2ac836b51089bef
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6206)*

**Comment by qyearsley** [comment]
Thanks Jeff!

**Pull request merged**
