### PR TITLE
Add intersection-observer/OWNERS

### PR DESCRIPTION
**Pull request by foolip**
Guessed based on activity here:
https://github.com/w3c/web-platform-tests/labels/intersection-observer

### CODE REVIEW

**Comment by foolip** [comment]
Noticed some PRs with the status:needs-owners and tried to find some. @nolanlawson @szager @tobytailor, are you all OK with this? This means you'll get pinged on new PRs. If anyone doesn't reply or wants to be removed, I'll remove them before merging.

@szager, I notice now I perhaps should have used @szager-chromium instead?

**Comment by w3c-bots** [comment]
# Build PASSED

Started: 2018-01-25 18:31:34
Finished: 2018-01-25 18:37:06


<h2>Failing Jobs</h2>
<ul>

<li>safari:11.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23295)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/333397785)

**Comment by tobytailor** [comment]
I left Mozilla and are not involved in the implementation of the
Intersection Observer API anymore. Not sure who at Mozilla is going to take
this over, but please remove me from getting pinged.

Best,

Tobias

**Comment by foolip** [comment]
> please remove me from getting pinged

Done!

**Comment by foolip** [comment]
I haven't heard back from anyone yet, so closing.

**Comment by nolanlawson** [comment]
Sorry for the late reply. The appropriate Microsoft owner for Intersection Observer is @scottlow.

**Comment by foolip** [comment]
Reopening this after @szager-chromium confirmed elsewhere. I'll list him and @scottlow.

**Pull request merged**
