### PR TITLE
HTML: test fieldset and transform: translateZ(0)

### PR DESCRIPTION
**Pull request by zcorpan**
Bugs:
https://bugs.chromium.org/p/chromium/issues/detail?id=661020

### CODE REVIEW

**Comment by zcorpan** [comment]
Apparently this fails in Chromium on Windows and Linux only. I have macOS so I don't know if it reproduces with this test, but I tried to not change things from the attached test case.

**Comment by mstensho** [comment]
Doesn't fail in Chrome for Linux here. https://bugs.chromium.org/p/chromium/issues/attachmentText?aid=310812 fails.

**Comment by zcorpan** [comment]
How about now?

**Comment by mstensho** [comment]
Yep, fails now.

**Review by mstensho — APPROVED** [review]

**Pull request merged**
