### PR TITLE
HTML Media Capture: Drop negative tests

### PR DESCRIPTION
**Pull request by Honry**
As audio capture is not implemented but it's not a normative requirement

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko, could you PTAL?

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234665131)

# Firefox (nightly) #
Testing web-platform-tests at revision ca4387bb3a3780354d1c464631442ca9693c7b22
Using browser at version BuildID 20170521100319; SourceStamp 5b74bbf20e803e299790d266fc6ebf5d53b7a1b7
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234665132)

# Sauce (safari) #
Testing web-platform-tests at revision ca4387bb3a3780354d1c464631442ca9693c7b22
Using browser at version 10.0
Starting 10 test iterations
No tests run.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234665138)

# Chrome (unstable) #
Testing web-platform-tests at revision ca4387bb3a3780354d1c464631442ca9693c7b22

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234665139)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ca4387bb3a3780354d1c464631442ca9693c7b22

**Comment by annevk** [comment]
But are you allowed to implement it? If so, it seems good if there are tests for it...

**Comment by anssiko** [comment]
@Honry, we could leave these tests in place, but indicate in the updated http://w3c.github.io/test-results/html-media-capture/20170428.html the said tests are not "Not applicable", marked as grey.

**Comment by Honry** [comment]
@anssiko and @annevk, many thanks for the comments, close it.

**Pull request closed without merging**
